Class Reference for E1039 Core & Analysis Software: RTCurve Class Reference
RTCurve Class Reference
Class to represent R-T curve.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/RTCurve.h>
Public Member Functions
RTCurve (const int n_pt)
virtual ~RTCurve ()
int GetNumPoints () const
void SetPoint (const int i_pt, const double r, const double t)
void GetPoint (const int i_pt, double &r, double &t) const
void SetRWidth (const double dr)
double GetRWidth () const
double GetTMin () const
double GetTMax () const
double GetRMax () const
double EvalR (const double t)
TSpline3 * GetT2RSpline ()
TGraph * GetT2DRGraph ()
Detailed Description
Class to represent R-T curve.
Definition at line 7 of file RTCurve.h.
Constructor & Destructor Documentation
RTCurve()
RTCurve::RTCurve (const int n_pt)
Definition at line 7 of file RTCurve.cc.
~RTCurve()
RTCurve::~RTCurve () virtual
Definition at line 19 of file RTCurve.cc.
Member Function Documentation
EvalR()
double RTCurve::EvalR (const double t)
Definition at line 53 of file RTCurve.cc.
References GetRMax(), GetT2RSpline(), GetTMax(), and GetTMin().
Referenced by FitRTDist::CalcChi2(), and CalibParam::WriteRTParam().
GetNumPoints()
int RTCurve::GetNumPoints () const inline
Definition at line 22 of file RTCurve.h.
GetPoint()
void RTCurve::GetPoint (const int i_pt, double & r, double & t) const
Definition at line 35 of file RTCurve.cc.
GetRMax()
double RTCurve::GetRMax () const inline
Definition at line 31 of file RTCurve.h.
Referenced by EvalR().
GetRWidth()
double RTCurve::GetRWidth () const
Definition at line 48 of file RTCurve.cc.
Referenced by FitRTDist::CalcChi2(), MakeRTCurve::DrawCalibResult(), SRMakeRTCurve::DrawCalibResult(), and CalibParam::WriteRTParam().
GetT2DRGraph()
TGraph * RTCurve::GetT2DRGraph ()
Definition at line 73 of file RTCurve.cc.
Referenced by MakeRTCurve::DrawCalibResult(), SRMakeRTCurve::DrawCalibResult(), and CalibParam::WriteRTGraph().
GetT2RSpline()
TSpline3 * RTCurve::GetT2RSpline ()
Definition at line 63 of file RTCurve.cc.
Referenced by MakeRTCurve::DrawCalibResult(), SRMakeRTCurve::DrawCalibResult(), EvalR(), and CalibParam::WriteRTGraph().
GetTMax()
double RTCurve::GetTMax () const inline
Definition at line 30 of file RTCurve.h.
Referenced by EvalR().
GetTMin()
double RTCurve::GetTMin () const inline
Definition at line 29 of file RTCurve.h.
Referenced by EvalR().
SetPoint()
void RTCurve::SetPoint (const int i_pt, const double r, const double t)
Definition at line 27 of file RTCurve.cc.
SetRWidth()
void RTCurve::SetRWidth (const double dr)
Definition at line 42 of file RTCurve.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/RTCurve.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/RTCurve.cc