Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/FastTracklet.cxx File Reference
FastTracklet.cxx File Reference
#include <phool/recoConsts.h>
#include <iostream>
#include <algorithm>
#include <cmath>
#include <TMath.h>
#include <TMatrixD.h>
#include "FastTracklet.h"
#include "TriggerRoad.h"
Functions
ClassImp (SignedHit) ClassImp(PropSegment) ClassImp(Tracklet) ClassImp(TrackletVector) namespace
Function Documentation
ClassImp()
ClassImp (SignedHit)
Definition at line 22 of file FastTracklet.cxx.
References GeomSvc::ELOSS_ABSORBER(), GeomSvc::ELOSS_KFMAG(), FMAGSTR, PHFlag::get_BoolFlag(), PHFlag::get_DoubleFlag(), recoConsts::instance(), GeomSvc::instance(), KMAGSTR, GeomSvc::Z_ABSORBER(), GeomSvc::Z_FMAG_BEND(), GeomSvc::Z_KFMAG_BEND(), and GeomSvc::Z_KMAG_BEND().