Class Reference for E1039 Core & Analysis Software: PHG4TrackUserInfo Namespace Reference
PHG4TrackUserInfo Namespace Reference
Functions
void SetUserTrackId (G4Track *track, const int usertrackid)
void SetUserParentId (G4Track *track, const int userparentid)
void SetUserPrimaryId (G4Track *track, const int userprimaryid)
void SetWanted (G4Track *track, const int trkid)
void SetKeep (G4Track *track, const int trkid)
void SetShower (G4Track *track, PHG4Shower *shower)
Function Documentation
SetKeep()
void PHG4TrackUserInfo::SetKeep (G4Track * track, const int trkid)
Definition at line 91 of file PHG4TrackUserInfoV1.cc.
References PHG4TrackUserInfoV1::SetKeep().
SetShower()
void PHG4TrackUserInfo::SetShower (G4Track * track, PHG4Shower * shower)
Definition at line 117 of file PHG4TrackUserInfoV1.cc.
References PHG4TrackUserInfoV1::SetShower().
Referenced by PHG4TruthTrackingAction::PostUserTrackingAction(), and PHG4TruthTrackingAction::PreUserTrackingAction().
SetUserParentId()
void PHG4TrackUserInfo::SetUserParentId (G4Track * track, const int userparentid)
Definition at line 27 of file PHG4TrackUserInfoV1.cc.
References PHG4TrackUserInfoV1::SetUserParentId().
Referenced by PHG4TruthTrackingAction::PostUserTrackingAction().
SetUserPrimaryId()
void PHG4TrackUserInfo::SetUserPrimaryId (G4Track * track, const int userprimaryid)
Definition at line 46 of file PHG4TrackUserInfoV1.cc.
References PHG4TrackUserInfoV1::SetUserPrimaryId().
Referenced by PHG4TruthTrackingAction::PostUserTrackingAction(), and PHG4TruthTrackingAction::PreUserTrackingAction().
SetUserTrackId()
void PHG4TrackUserInfo::SetUserTrackId (G4Track * track, const int usertrackid)
Definition at line 8 of file PHG4TrackUserInfoV1.cc.
References PHG4TrackUserInfoV1::SetUserTrackId().
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
SetWanted()
void PHG4TrackUserInfo::SetWanted (G4Track * track, const int trkid)
Definition at line 65 of file PHG4TrackUserInfoV1.cc.
References PHG4TrackUserInfoV1::SetWanted().