Class Reference for E1039 Core & Analysis Software: submit_bnl Namespace Reference
submit_bnl Namespace Reference
Variables
jobname = sys.argv[1]
njobs = int(sys.argv[2])
nevents = int(sys.argv[3])
do_submition = bool(sys.argv[4])
string sphenix_build_tag = 'new'
string local_build_tag = 'install'
string condor_base_path = '/gpfs/mnt/gpfs04/sphenix/user/yuhw/workspace/TargetSim/TargetSim'
string macros_path = condor_base_path
string output_path = condor_base_path + '/output/' + '/{}/'.format(jobname)
string condor_work_dir_base = condor_base_path + '/work/' + '/{}/'.format(jobname)
string condor_local = condor_base_path + '/temp/'
string condor_work_dir = condor_work_dir_base + '/{}/'.format(ijob)
string runscript = condor_work_dir + '/run.csh'
RUNSCRIPT = open(runscript,'w')
string cmd = 'time root -l -b -q Fun4All_G4_BNL_R1.C\\({}\\‍)'.format(nevents)
string condorfile = condor_work_dir + '/condor.job'
string logfile = condor_work_dir + '/log.txt'
string outfile = condor_work_dir + '/out.txt'
string errfile = condor_work_dir + '/err.txt'
CONDORFILE = open(condorfile,'w')
Variable Documentation
cmd
string submit_bnl.cmd = 'time root -l -b -q Fun4All_G4_BNL_R1.C\\({}\\‍)'.format(nevents)
Definition at line 63 of file submit_bnl.py.
Referenced by PHG4Reco.ApplyCommand().
condor_base_path
string submit_bnl.condor_base_path = '/gpfs/mnt/gpfs04/sphenix/user/yuhw/workspace/TargetSim/TargetSim'
Definition at line 17 of file submit_bnl.py.
condor_local
string submit_bnl.condor_local = condor_base_path + '/temp/'
Definition at line 22 of file submit_bnl.py.
condor_work_dir
string submit_bnl.condor_work_dir = condor_work_dir_base + '/{}/'.format(ijob)
Definition at line 38 of file submit_bnl.py.
condor_work_dir_base
string submit_bnl.condor_work_dir_base = condor_base_path + '/work/' + '/{}/'.format(jobname)
Definition at line 20 of file submit_bnl.py.
condorfile
string submit_bnl.condorfile = condor_work_dir + '/condor.job'
Definition at line 78 of file submit_bnl.py.
CONDORFILE
submit_bnl.CONDORFILE = open(condorfile,'w')
Definition at line 83 of file submit_bnl.py.
do_submition
submit_bnl.do_submition = bool(sys.argv[4])
Definition at line 12 of file submit_bnl.py.
errfile
string submit_bnl.errfile = condor_work_dir + '/err.txt'
Definition at line 81 of file submit_bnl.py.
jobname
submit_bnl.jobname = sys.argv[1]
Definition at line 8 of file submit_bnl.py.
local_build_tag
string submit_bnl.local_build_tag = 'install'
Definition at line 15 of file submit_bnl.py.
logfile
string submit_bnl.logfile = condor_work_dir + '/log.txt'
Definition at line 79 of file submit_bnl.py.
macros_path
string submit_bnl.macros_path = condor_base_path
Definition at line 18 of file submit_bnl.py.
nevents
submit_bnl.nevents = int(sys.argv[3])
Definition at line 11 of file submit_bnl.py.
Referenced by Fun4AllPrdfInputManager.PushBackEvents(), Fun4AllHepMCInputManager.PushBackEvents(), Fun4AllDstInputManager.run(), Fun4AllOscarInputManager.run(), and Fun4AllDummyInputManager.run().
njobs
submit_bnl.njobs = int(sys.argv[2])
Definition at line 10 of file submit_bnl.py.
outfile
string submit_bnl.outfile = condor_work_dir + '/out.txt'
Definition at line 80 of file submit_bnl.py.
output_path
string submit_bnl.output_path = condor_base_path + '/output/' + '/{}/'.format(jobname)
Definition at line 19 of file submit_bnl.py.
runscript
string submit_bnl.runscript = condor_work_dir + '/run.csh'
Definition at line 45 of file submit_bnl.py.
RUNSCRIPT
submit_bnl.RUNSCRIPT = open(runscript,'w')
Definition at line 46 of file submit_bnl.py.
sphenix_build_tag
string submit_bnl.sphenix_build_tag = 'new'
Definition at line 14 of file submit_bnl.py.