Class Reference for E1039 Core & Analysis Software: SQHit_v1 Class Reference
SQHit_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHit_v1.h>
Public Member Functions
SQHit_v1 ()
virtual ~SQHit_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQHit * Clone () const
virtual int get_hit_id () const
Return the ID of this hit.
virtual void set_hit_id (const int a)
virtual short get_detector_id () const
Return the detector ID of this hit.
virtual void set_detector_id (const short a)
virtual short get_element_id () const
Return the element ID of this hit.
virtual void set_element_id (const short id)
virtual short get_level () const
Return the trigger level of this hit. Meaningful only if this hit is of V1495 TDC.
virtual void set_level (const short level)
virtual float get_tdc_time () const
Return the TDC time (nsec) of this hit.
virtual void set_tdc_time (const float a)
virtual float get_drift_distance () const
Return the drift distance of this hit. Probably the value is not properly set at present. Meaningful only if this hit is of drift chamber or prop tube.
virtual void set_drift_distance (const float a)
virtual float get_pos () const
Return the absolute position of this hit. Probably the value is not properly set at present.
virtual void set_pos (const float a)
virtual bool is_in_time () const
Return 'true' if this hit is in the time window.
virtual void set_in_time (const bool a)
virtual bool is_hodo_mask () const
Return 'true' if this hit is accepted (or masked out?) by the hodoscope masking. Meaningful only if this hit is of drift chamber.
virtual void set_hodo_mask (const bool a)
virtual bool is_trigger_mask () const
Return 'true' if this hit is accepted (or masked out?) by the trigger-road masking. Meaningful only if this hit is of drift chamber.
virtual void set_trigger_mask (const bool a)
Public Member Functions inherited from SQHit
SQHit ()
virtual ~SQHit ()
virtual short get_tower_id () const
Not valid in E1039. To be deleted.
virtual void set_tower_id (const short a)
virtual float get_edep () const
Not valid in E1039. To be deleted.
virtual void set_edep (const float a)
virtual int get_track_id () const
Return the track ID associated with this hit. Probably the value is not properly set at present.
virtual void set_track_id (const int a)
virtual PHG4HitDefs::keytype get_g4hit_id () const
Return the Geant-hit ID associated with this hit.
virtual void set_g4hit_id (const PHG4HitDefs::keytype a)
virtual float get_truth_x () const
Return the true x-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_x (const float a)
virtual float get_truth_y () const
Return the true y-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_y (const float a)
virtual float get_truth_z () const
Return the true z-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_z (const float a)
virtual float get_truth_px () const
Return the true x-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_px (const float a)
virtual float get_truth_py () const
Return the true y-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_py (const float a)
virtual float get_truth_pz () const
Return the true z-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_pz (const float a)
virtual unsigned int get_n_cells () const
Return the number of cells included in this hit.
virtual CellMap get_cells () const
Return the list of all cells included in this hit.
virtual float get_cell (unsigned int i) const
Return the 'edep' value of the i-th cell.
virtual void add_cell (unsigned int i, float a)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from SQHit
enum HitQuality { InTime = 1<<0 , HodoMask = 1<<1 , TriggerMask = 1<<2 }
typedef std::map< short, float > CellMap
key -> plateID, float -> edep
Detailed Description
Definition at line 17 of file SQHit_v1.h.
Constructor & Destructor Documentation
SQHit_v1()
SQHit_v1::SQHit_v1 ()
Definition at line 16 of file SQHit_v1.cxx.
Referenced by Clone(), and Reset().
~SQHit_v1()
virtual SQHit_v1::~SQHit_v1 () inline virtual
Definition at line 22 of file SQHit_v1.h.
Member Function Documentation
Clone()
SQHit* SQHit_v1::Clone () const inline virtual
Reimplemented from SQHit.
Reimplemented in SQMCHit_v1.
Definition at line 29 of file SQHit_v1.h.
References SQHit_v1().
get_detector_id()
virtual short SQHit_v1::get_detector_id () const inline virtual
Return the detector ID of this hit.
Reimplemented from SQHit.
Definition at line 36 of file SQHit_v1.h.
Referenced by identify().
get_drift_distance()
virtual float SQHit_v1::get_drift_distance () const inline virtual
Return the drift distance of this hit. Probably the value is not properly set at present. Meaningful only if this hit is of drift chamber or prop tube.
Reimplemented from SQHit.
Definition at line 48 of file SQHit_v1.h.
Referenced by identify().
get_element_id()
virtual short SQHit_v1::get_element_id () const inline virtual
Return the element ID of this hit.
Reimplemented from SQHit.
Definition at line 39 of file SQHit_v1.h.
Referenced by identify().
get_hit_id()
virtual int SQHit_v1::get_hit_id () const inline virtual
Return the ID of this hit.
Reimplemented from SQHit.
Definition at line 33 of file SQHit_v1.h.
Referenced by identify(), and SQMCHit_v1::identify().
get_level()
virtual short SQHit_v1::get_level () const inline virtual
Return the trigger level of this hit. Meaningful only if this hit is of V1495 TDC.
Reimplemented from SQHit.
Definition at line 42 of file SQHit_v1.h.
Referenced by identify().
get_pos()
virtual float SQHit_v1::get_pos () const inline virtual
Return the absolute position of this hit. Probably the value is not properly set at present.
Reimplemented from SQHit.
Definition at line 51 of file SQHit_v1.h.
Referenced by SQDigitizer::digitizePlane(), and identify().
get_tdc_time()
virtual float SQHit_v1::get_tdc_time () const inline virtual
Return the TDC time (nsec) of this hit.
Reimplemented from SQHit.
Definition at line 45 of file SQHit_v1.h.
Referenced by identify().
identify()
void SQHit_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQHit.
Reimplemented in SQMCHit_v1.
Definition at line 27 of file SQHit_v1.cxx.
References get_detector_id(), get_drift_distance(), get_element_id(), get_hit_id(), get_level(), get_pos(), get_tdc_time(), is_hodo_mask(), is_in_time(), and is_trigger_mask().
Referenced by SQMCHit_v1::identify().
is_hodo_mask()
virtual bool SQHit_v1::is_hodo_mask () const inline virtual
Return 'true' if this hit is accepted (or masked out?) by the hodoscope masking. Meaningful only if this hit is of drift chamber.
Reimplemented from SQHit.
Definition at line 57 of file SQHit_v1.h.
References SQHit::HodoMask.
Referenced by identify().
is_in_time()
virtual bool SQHit_v1::is_in_time () const inline virtual
Return 'true' if this hit is in the time window.
Reimplemented from SQHit.
Definition at line 54 of file SQHit_v1.h.
References SQHit::InTime.
Referenced by identify().
is_trigger_mask()
virtual bool SQHit_v1::is_trigger_mask () const inline virtual
Return 'true' if this hit is accepted (or masked out?) by the trigger-road masking. Meaningful only if this hit is of drift chamber.
Reimplemented from SQHit.
Definition at line 60 of file SQHit_v1.h.
References SQHit::TriggerMask.
Referenced by identify().
isValid()
int SQHit_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQHit.
Reimplemented in SQMCHit_v1.
Definition at line 46 of file SQHit_v1.cxx.
Referenced by SQMCHit_v1::isValid().
Reset()
void SQHit_v1::Reset () inline virtual
Clear Event.
Reimplemented from SQHit.
Reimplemented in SQMCHit_v1.
Definition at line 27 of file SQHit_v1.h.
References SQHit_v1().
set_detector_id()
virtual void SQHit_v1::set_detector_id (const short a) inline virtual
Reimplemented from SQHit.
Definition at line 37 of file SQHit_v1.h.
Referenced by SQDigitizer::digitizePlane().
set_drift_distance()
virtual void SQHit_v1::set_drift_distance (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 49 of file SQHit_v1.h.
Referenced by SQDigitizer::digitizePlane().
set_element_id()
virtual void SQHit_v1::set_element_id (const short id) inline virtual
Reimplemented from SQHit.
Definition at line 40 of file SQHit_v1.h.
Referenced by SQDigitizer::digitizePlane().
set_hit_id()
virtual void SQHit_v1::set_hit_id (const int a) inline virtual
Reimplemented from SQHit.
Definition at line 34 of file SQHit_v1.h.
Referenced by SQDigitizer::digitizePlane().
set_hodo_mask()
virtual void SQHit_v1::set_hodo_mask (const bool a) inline virtual
Reimplemented from SQHit.
Definition at line 58 of file SQHit_v1.h.
References SQHit::HodoMask.
Referenced by SQDigitizer::digitizePlane().
set_in_time()
virtual void SQHit_v1::set_in_time (const bool a) inline virtual
Reimplemented from SQHit.
Definition at line 55 of file SQHit_v1.h.
References SQHit::InTime.
Referenced by SQDigitizer::digitizePlane().
set_level()
virtual void SQHit_v1::set_level (const short level) inline virtual
Reimplemented from SQHit.
Definition at line 43 of file SQHit_v1.h.
set_pos()
virtual void SQHit_v1::set_pos (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 52 of file SQHit_v1.h.
Referenced by SQDigitizer::digitizePlane().
set_tdc_time()
virtual void SQHit_v1::set_tdc_time (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 46 of file SQHit_v1.h.
Referenced by SQDigitizer::digitizePlane().
set_trigger_mask()
virtual void SQHit_v1::set_trigger_mask (const bool a) inline virtual
Reimplemented from SQHit.
Definition at line 61 of file SQHit_v1.h.
References SQHit::TriggerMask.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHit_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHit_v1.cxx