Class Reference for E1039 Core & Analysis Software: PdbApplication Class Reference
PdbApplication Class Reference abstract
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbApplication.h>
Public Member Functions
virtual PdbStatus startUpdate ()=0
virtual PdbStatus startRead ()=0
virtual PdbStatus commit ()=0
virtual PdbStatus abort ()=0
virtual PdbStatus isActive ()=0
virtual PdbStatus commit (PdbCalBank *)=0
virtual PdbStatus commit (PdbCalBank *, int, long, long, long)=0
virtual int setDBName (const std::string &name)=0
virtual int DisconnectDB ()=0
Static Public Member Functions
static PdbApplication * instance ()
Protected Member Functions
PdbApplication ()
virtual ~PdbApplication ()
Static Protected Attributes
static std::auto_ptr< PdbApplication > __instance
Friends
class std::auto_ptr< PdbApplication >
Detailed Description
Definition at line 13 of file PdbApplication.h.
Constructor & Destructor Documentation
PdbApplication()
PdbApplication::PdbApplication () inline protected
Definition at line 17 of file PdbApplication.h.
~PdbApplication()
virtual PdbApplication::~PdbApplication () inline protected virtual
Definition at line 18 of file PdbApplication.h.
Member Function Documentation
abort()
virtual PdbStatus PdbApplication::abort () pure virtual
Referenced by PHParameters::ReadFromDB(), PHG4Parameters::ReadFromDB(), PHParameters::WriteToDB(), PHParametersContainer::WriteToDB(), PHG4Parameters::WriteToDB(), and PHG4ParametersContainer::WriteToDB().
commit() [1/3]
virtual PdbStatus PdbApplication::commit () pure virtual
Referenced by PHParameters::WriteToDB(), PHParametersContainer::WriteToDB(), PHG4Parameters::WriteToDB(), and PHG4ParametersContainer::WriteToDB().
commit() [2/3]
virtual PdbStatus PdbApplication::commit (PdbCalBank *) pure virtual
commit() [3/3]
virtual PdbStatus PdbApplication::commit (PdbCalBank * , int , long , long , long) pure virtual
DisconnectDB()
virtual int PdbApplication::DisconnectDB () pure virtual
instance()
PdbApplication * PdbApplication::instance () static
Definition at line 19 of file PdbApplication.cc.
References __instance, and NULL.
isActive()
virtual PdbStatus PdbApplication::isActive () pure virtual
setDBName()
virtual int PdbApplication::setDBName (const std::string & name) pure virtual
startRead()
virtual PdbStatus PdbApplication::startRead () pure virtual
Referenced by PHParameters::ReadFromDB(), and PHG4Parameters::ReadFromDB().
startUpdate()
virtual PdbStatus PdbApplication::startUpdate () pure virtual
Referenced by PHParameters::WriteToDB(), PHParametersContainer::WriteToDB(), PHG4Parameters::WriteToDB(), and PHG4ParametersContainer::WriteToDB().
Friends And Related Function Documentation
std::auto_ptr< PdbApplication >
friend class std::auto_ptr< PdbApplication > friend
Definition at line 36 of file PdbApplication.h.
Member Data Documentation
__instance
std::auto_ptr< PdbApplication > PdbApplication::__instance static protected
Definition at line 45 of file PdbApplication.h.
Referenced by instance().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbApplication.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbApplication.cc