Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/SQGenFit/test/test_minimum.cxx File Reference
test_minimum.cxx File Reference
#include <iostream>
#include <cmath>
#include <list>
#include <TGeoManager.h>
#include <TRandom.h>
#include <jobopts_svc/JobOptsSvc.h>
#include <geom_svc/GeomSvc.h>
#include <phfield/PHField.h>
#include <phfield/PHFieldConfig_v3.h>
#include <phfield/PHFieldUtility.h>
#include <phool/recoConsts.h>
#include "GFField.h"
#include "GFFitter.h"
#include "GFTrack.h"
#include "FastTracklet.h"
#include "KalmanFastTracking.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 23 of file test_minimum.cxx.
References PHFieldUtility::BuildFieldMap(), Hit::detectorID, Hit::driftDistance, Hit::elementID, KalmanFastTracking::fitTracklet(), GeomSvc::getExpElementID(), Tracklet::getExpPositionW(), GeomSvc::getMeasurement(), GeomSvc::getPlaneResolution(), SignedHit::hit, Tracklet::hits, Hit::index, SQGenFit::GFFitter::init(), recoConsts::instance(), GeomSvc::instance(), Tracklet::invP, Hit::pos, SQGenFit::GFTrack::postFitUpdate(), recoConsts::Print(), Tracklet::print(), SQGenFit::GFTrack::print(), GeomSvc::printTable(), SQGenFit::GFFitter::processTrack(), PHFlag::set_DoubleFlag(), SQGenFit::GFTrack::setTracklet(), SQGenFit::GFFitter::setVerbosity(), SQGenFit::GFTrack::setVerbosity(), SignedHit::sign, Tracklet::stationID, Tracklet::tx, Tracklet::ty, GeomSvc::UseDbSvc(), Tracklet::x0, and Tracklet::y0.