E1039 Software: SQSlowCont Class Reference
SQSlowCont Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/interface_main/SQSlowCont.h>
Public Member Functions
virtual ~SQSlowCont ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual SQSlowCont * Clone () const
virtual PHObject * clone () const
Virtual copy constructor.
virtual std::string get_time_stamp () const
virtual void set_time_stamp (const std::string a)
virtual std::string get_name () const
virtual void set_name (const std::string a)
virtual std::string get_value () const
virtual void set_value (const std::string a)
virtual std::string get_type () const
virtual void set_type (const std::string a)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQSlowCont ()
Private Member Functions
ClassDef (SQSlowCont, 1)
Detailed Description
Definition at line 11 of file SQSlowCont.h.
Constructor & Destructor Documentation
~SQSlowCont()
virtual SQSlowCont::~SQSlowCont () inline virtual
Definition at line 13 of file SQSlowCont.h.
SQSlowCont()
SQSlowCont::SQSlowCont () inline protected
Definition at line 38 of file SQSlowCont.h.
References ClassDef().
Member Function Documentation
ClassDef()
SQSlowCont::ClassDef (SQSlowCont , 1) private
Referenced by SQSlowCont().
Clone()
virtual SQSlowCont* SQSlowCont::Clone () const inline virtual
Reimplemented in SQSlowCont_v1.
Definition at line 22 of file SQSlowCont.h.
References NULL.
clone()
virtual PHObject* SQSlowCont::clone () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SQSlowCont_v1.
Definition at line 23 of file SQSlowCont.h.
References NULL.
get_name()
virtual std::string SQSlowCont::get_name (void) const inline virtual
Reimplemented in SQSlowCont_v1.
Definition at line 28 of file SQSlowCont.h.
get_time_stamp()
virtual std::string SQSlowCont::get_time_stamp () const inline virtual
Reimplemented in SQSlowCont_v1.
Definition at line 25 of file SQSlowCont.h.
Referenced by DbUpSpill::PrintSpill(), and DbUpSpill::UploadToSlowContTable().
get_type()
virtual std::string SQSlowCont::get_type () const inline virtual
Reimplemented in SQSlowCont_v1.
Definition at line 34 of file SQSlowCont.h.
Referenced by DbUpSpill::PrintSpill(), and DbUpSpill::UploadToSlowContTable().
get_value()
virtual std::string SQSlowCont::get_value () const inline virtual
Reimplemented in SQSlowCont_v1.
Definition at line 31 of file SQSlowCont.h.
Referenced by DbUpSpill::PrintSpill(), and DbUpSpill::UploadToSlowContTable().
identify()
virtual void SQSlowCont::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SQSlowCont_v1.
Definition at line 17 of file SQSlowCont.h.
isValid()
virtual int SQSlowCont::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SQSlowCont_v1.
Definition at line 21 of file SQSlowCont.h.
Reset()
virtual void SQSlowCont::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SQSlowCont_v1.
Definition at line 20 of file SQSlowCont.h.
set_name()
virtual void SQSlowCont::set_name (const std::string a) inline virtual
Reimplemented in SQSlowCont_v1.
Definition at line 29 of file SQSlowCont.h.
set_time_stamp()
virtual void SQSlowCont::set_time_stamp (const std::string a) inline virtual
Reimplemented in SQSlowCont_v1.
Definition at line 26 of file SQSlowCont.h.
set_type()
virtual void SQSlowCont::set_type (const std::string a) inline virtual
Reimplemented in SQSlowCont_v1.
Definition at line 35 of file SQSlowCont.h.
set_value()
virtual void SQSlowCont::set_value (const std::string a) inline virtual
Reimplemented in SQSlowCont_v1.
Definition at line 32 of file SQSlowCont.h.
The documentation for this class was generated from the following file:
/home/yuhw/GitHub/SeaQuest/e1039-core/interface_main/SQSlowCont.h