E1039 Software: Seed Class Reference
Seed Class Reference
Seed structure to store the temporary prop. seeds information.
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/KalmanTrack.h>
Public Member Functions
double getExpPositionX (double z)
double getExpPositionY (double z)
void decideCharge ()
void decideMomentum ()
void decideMomentum_model ()
double getMomentum (double &px, double &py, double &pz)
bool similarity (Seed &elem)
void print ()
Static Public Member Functions
static void reduceSeedList (std::list< Seed > &_seedlist)
Public Attributes
double axz
double bxz
double ayz
double byz
double charge
double p
Detailed Description
Seed structure to store the temporary prop. seeds information.
Definition at line 27 of file KalmanTrack.h.
Member Function Documentation
decideCharge()
void Seed::decideCharge ()
Definition at line 26 of file KalmanTrack.cxx.
References axz, charge, and getExpPositionX().
Referenced by decideMomentum(), and getExpPositionY().
decideMomentum()
void Seed::decideMomentum ()
Definition at line 41 of file KalmanTrack.cxx.
References axz, bxz, charge, decideCharge(), decideMomentum_model(), and p.
Referenced by getExpPositionY().
decideMomentum_model()
void Seed::decideMomentum_model ()
Definition at line 86 of file KalmanTrack.cxx.
References axz, bxz, and p.
Referenced by decideMomentum(), and getExpPositionY().
getExpPositionX()
double Seed::getExpPositionX (double z) inline
Definition at line 36 of file KalmanTrack.h.
References bxz.
Referenced by decideCharge(), and similarity().
getExpPositionY()
double Seed::getExpPositionY (double z) inline
Definition at line 37 of file KalmanTrack.h.
References byz, decideCharge(), decideMomentum(), decideMomentum_model(), getMomentum(), print(), reduceSeedList(), and similarity().
Referenced by similarity().
getMomentum()
double Seed::getMomentum (double & px, double & py, double & pz)
Definition at line 17 of file KalmanTrack.cxx.
References axz, ayz, and p.
Referenced by getExpPositionY().
print()
void Seed::print ()
Definition at line 134 of file KalmanTrack.cxx.
References axz, ayz, bxz, byz, charge, and p.
Referenced by getExpPositionY(), and KalmanTrack::getMomentumUpstream().
reduceSeedList()
void Seed::reduceSeedList (std::list< Seed > & _seedlist) static
Definition at line 109 of file KalmanTrack.cxx.
Referenced by getExpPositionY().
similarity()
bool Seed::similarity (Seed & elem)
Definition at line 95 of file KalmanTrack.cxx.
References charge, getExpPositionX(), getExpPositionY(), GeomSvc::getPlanePosition(), GeomSvc::instance(), nChamberPlanes, nHodoPlanes, and p.
Referenced by getExpPositionY(), and KalmanTrack::getMomentumUpstream().
Member Data Documentation
axz
double Seed::axz
Definition at line 30 of file KalmanTrack.h.
Referenced by decideCharge(), decideMomentum(), decideMomentum_model(), KalmanTrack::getExpPositionFast(), getMomentum(), KalmanTrack::getXZSlopeInStation(), print(), and KalmanTrack::updateMomentum().
ayz
double Seed::ayz
Definition at line 31 of file KalmanTrack.h.
Referenced by KalmanTrack::getExpPositionFast(), getMomentum(), and print().
bxz
double Seed::bxz
Definition at line 30 of file KalmanTrack.h.
Referenced by decideMomentum(), decideMomentum_model(), getExpPositionX(), and print().
byz
double Seed::byz
Definition at line 31 of file KalmanTrack.h.
Referenced by getExpPositionY(), and print().
charge
double Seed::charge
Definition at line 33 of file KalmanTrack.h.
Referenced by decideCharge(), decideMomentum(), print(), similarity(), and KalmanTrack::updateMomentum().
p
double Seed::p
Definition at line 34 of file KalmanTrack.h.
Referenced by decideMomentum(), decideMomentum_model(), getMomentum(), KalmanTrack::getMomentumInStation(), print(), similarity(), and KalmanTrack::updateMomentum().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/KalmanTrack.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/KalmanTrack.cxx