Class Reference for E1039 Core & Analysis Software: GenFitExtrapolator Class Reference
GenFitExtrapolator Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/kfitter/GenFitExtrapolator.h>
Public Member Functions
GenFitExtrapolator ()
~GenFitExtrapolator ()
bool init (const PHField *field, const TGeoManager *geom)
Initialize geometry and physics.
void setInitialStateWithCov (double z_in, TMatrixD &state_in, TMatrixD &cov_in)
Set input initial state parameters.
void setParticleType (int type)
Set particle type.
void getFinalStateWithCov (TMatrixD &state_out, TMatrixD &cov_out)
Get the final state parameters and covariance.
double getTravelLength ()
void getPropagator (TMatrixD &prop)
Get the propagator.
bool extrapolateTo (double z_out)
double extrapolateToIP ()
Extrapolate to the primary vertex.
void convertSVtoMP (double z, TMatrixD &state, TVector3 &mom, TVector3 &pos)
Transformation between the state vector and the mom/pos.
void convertMPtoSV (TVector3 &mom, TVector3 &pos, TMatrixD &state)
void TRSDSC (int charge, TVector3 mom_input, TVector3 pos_input)
void TRSCSD (int charge, TVector3 mom_input, TVector3 pos_input)
TMatrixD & getJacSD2SC ()
TMatrixD & getJacSC2SD ()
void setPropCalc (bool option)
External control of modes.
void setLengthCalc (bool option)
void TRGENFIT2LEGACY (int charge, TVector3 mom_input, TVector3 pos_input)
Tranformation between GenFit and Legacy plane; Abi.
void TRLEGACY2GENFIT (int charge, TVector3 mom_input, TVector3 pos_input)
void print ()
Debug print.
Detailed Description
Definition at line 30 of file GenFitExtrapolator.h.
Constructor & Destructor Documentation
GenFitExtrapolator()
GenFitExtrapolator::GenFitExtrapolator ()
Definition at line 63 of file GenFitExtrapolator.cxx.
~GenFitExtrapolator()
GenFitExtrapolator::~GenFitExtrapolator ()
Definition at line 72 of file GenFitExtrapolator.cxx.
Member Function Documentation
convertMPtoSV()
void GenFitExtrapolator::convertMPtoSV (TVector3 & mom, TVector3 & pos, TMatrixD & state)
Definition at line 417 of file GenFitExtrapolator.cxx.
Referenced by getFinalStateWithCov().
convertSVtoMP()
void GenFitExtrapolator::convertSVtoMP (double z, TMatrixD & state, TVector3 & mom, TVector3 & pos)
Transformation between the state vector and the mom/pos.
Definition at line 403 of file GenFitExtrapolator.cxx.
Referenced by setInitialStateWithCov().
extrapolateTo()
bool GenFitExtrapolator::extrapolateTo (double z_out)
If the initial or final position is out of the reasonable world
if the initial and final z position is the same, don't make the transportation
set destination plane
Set starting plane in GenFit (similar as destination plane)
Get propagator between the starting and destination plane
Definition at line 288 of file GenFitExtrapolator.cxx.
Referenced by extrapolateToIP(), and KalmanFilter::predict().
extrapolateToIP()
double GenFitExtrapolator::extrapolateToIP ()
Extrapolate to the primary vertex.
Definition at line 349 of file GenFitExtrapolator.cxx.
References extrapolateTo().
Referenced by VertexFit::findSingleMuonVertex().
getFinalStateWithCov()
void GenFitExtrapolator::getFinalStateWithCov (TMatrixD & state_out, TMatrixD & cov_out)
Get the final state parameters and covariance.
Convert from genfit to legacy plane after extrapolation; Abi
Definition at line 190 of file GenFitExtrapolator.cxx.
References convertMPtoSV(), and TRGENFIT2LEGACY().
Referenced by KalmanFilter::predict().
getJacSC2SD()
TMatrixD& GenFitExtrapolator::getJacSC2SD () inline
Definition at line 74 of file GenFitExtrapolator.h.
getJacSD2SC()
TMatrixD& GenFitExtrapolator::getJacSD2SC () inline
Definition at line 73 of file GenFitExtrapolator.h.
getPropagator()
void GenFitExtrapolator::getPropagator (TMatrixD & prop)
Get the propagator.
can probably remove the commented section below (?Abi)
Definition at line 245 of file GenFitExtrapolator.cxx.
Referenced by KalmanFilter::predict().
getTravelLength()
double GenFitExtrapolator::getTravelLength () inline
Definition at line 48 of file GenFitExtrapolator.h.
init()
bool GenFitExtrapolator::init (const PHField * field, const TGeoManager * geom)
Initialize geometry and physics.
Definition at line 75 of file GenFitExtrapolator.cxx.
References PHField::GetFieldValue(), and LogInfo.
Referenced by KalmanFilter::initExtrapolator(), and VertexFit::InitRun().
print()
void GenFitExtrapolator::print ()
Debug print.
Definition at line 620 of file GenFitExtrapolator.cxx.
setInitialStateWithCov()
void GenFitExtrapolator::setInitialStateWithCov (double z_in, TMatrixD & state_in, TMatrixD & cov_in)
Set input initial state parameters.
5D cov
we can probably remove the commented section below (? Abi)
Convert the error matrix from legacy to genfit plane before extrapolation; Abi
Parameters
cov_in 5D state defined on (0, 0, z)
Definition at line 117 of file GenFitExtrapolator.cxx.
References convertSVtoMP(), LogInfo, setParticleType(), and TRLEGACY2GENFIT().
Referenced by VertexFit::findSingleMuonVertex(), and KalmanFilter::predict().
setLengthCalc()
void GenFitExtrapolator::setLengthCalc (bool option) inline
Definition at line 78 of file GenFitExtrapolator.h.
Referenced by KalmanFilter::enableDumpCorrection(), and VertexFit::InitRun().
setParticleType()
void GenFitExtrapolator::setParticleType (int type)
Set particle type.
Definition at line 186 of file GenFitExtrapolator.cxx.
Referenced by setInitialStateWithCov().
setPropCalc()
void GenFitExtrapolator::setPropCalc (bool option) inline
External control of modes.
Definition at line 77 of file GenFitExtrapolator.h.
Referenced by KalmanFilter::enableDumpCorrection(), and VertexFit::InitRun().
TRGENFIT2LEGACY()
void GenFitExtrapolator::TRGENFIT2LEGACY (int charge, TVector3 mom_input, TVector3 pos_input)
Tranformation between GenFit and Legacy plane; Abi.
simple jacobian independent of arguments (can remove the arguments later)
Definition at line 441 of file GenFitExtrapolator.cxx.
Referenced by getFinalStateWithCov().
TRLEGACY2GENFIT()
void GenFitExtrapolator::TRLEGACY2GENFIT (int charge, TVector3 mom_input, TVector3 pos_input)
simple jacobian independent of arguments (can remove the arguments later)
Definition at line 429 of file GenFitExtrapolator.cxx.
Referenced by setInitialStateWithCov().
TRSCSD()
void GenFitExtrapolator::TRSCSD (int charge, TVector3 mom_input, TVector3 pos_input)
convert the internal momentum and positon to ROOT vectors and use GeV and cm
Define the V and W direction of SD coordinate
Calculate the representation of momentum
Definition at line 539 of file GenFitExtrapolator.cxx.
References c_light.
TRSDSC()
void GenFitExtrapolator::TRSDSC (int charge, TVector3 mom_input, TVector3 pos_input)
Transformation between the SC and SD parameters and error matrix Transplanted from GEANT3 fortran code
convert the internal momentum and positon to ROOT vectors and use GeV and cm
Define the V and W direction of SD coordinate
Calculate the representation of momentum
Definition at line 453 of file GenFitExtrapolator.cxx.
References c_light, and LogInfo.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/kfitter/GenFitExtrapolator.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/kfitter/GenFitExtrapolator.cxx