E1039 Software: PdbCalBank Class Reference
PdbCalBank Class Reference abstract
#include </home/yuhw/GitHub/SeaQuest/e1039-core/database/pdbcal/base/PdbCalBank.h>
Public Member Functions
PdbCalBank ()
virtual ~PdbCalBank ()
virtual PdbCalBank * clone () const =0
virtual void printHeader () const =0
virtual void print ()=0
virtual void printEntry (size_t)=0
virtual size_t getLength ()=0
virtual PdbCalChan & getEntry (size_t)=0
virtual void setLength (size_t val)=0
virtual PdbBankID getBankID () const =0
virtual PHTimeStamp getInsertTime () const =0
virtual PHTimeStamp getStartValTime () const =0
virtual PHTimeStamp getEndValTime () const =0
virtual std::string getDescription () const =0
virtual std::string getUserName () const =0
virtual void setBankID (const PdbBankID &)=0
virtual void setInsertTime (const PHTimeStamp &)=0
virtual void setStartValTime (const PHTimeStamp &)=0
virtual void setEndValTime (const PHTimeStamp &)=0
virtual void setDescription (const std::string &)=0
virtual void setUserName (const std::string &)=0
virtual int isValid (const PHTimeStamp &) const =0
ClassDef (PdbCalBank, 2)
Detailed Description
Definition at line 20 of file PdbCalBank.h.
Constructor & Destructor Documentation
PdbCalBank()
PdbCalBank::PdbCalBank ()
Definition at line 6 of file PdbCalBank.cc.
~PdbCalBank()
PdbCalBank::~PdbCalBank () virtual
Definition at line 10 of file PdbCalBank.cc.
Member Function Documentation
ClassDef()
PdbCalBank::ClassDef (PdbCalBank , 2)
clone()
virtual PdbCalBank* PdbCalBank::clone () const pure virtual
getBankID()
virtual PdbBankID PdbCalBank::getBankID () const pure virtual
getDescription()
virtual std::string PdbCalBank::getDescription () const pure virtual
getEndValTime()
virtual PHTimeStamp PdbCalBank::getEndValTime () const pure virtual
getEntry()
virtual PdbCalChan& PdbCalBank::getEntry (size_t) pure virtual
getInsertTime()
virtual PHTimeStamp PdbCalBank::getInsertTime () const pure virtual
getLength()
virtual size_t PdbCalBank::getLength () pure virtual
getStartValTime()
virtual PHTimeStamp PdbCalBank::getStartValTime () const pure virtual
getUserName()
virtual std::string PdbCalBank::getUserName () const pure virtual
isValid()
virtual int PdbCalBank::isValid (const PHTimeStamp &) const pure virtual
print()
virtual void PdbCalBank::print () pure virtual
printEntry()
virtual void PdbCalBank::printEntry (size_t) pure virtual
printHeader()
virtual void PdbCalBank::printHeader () const pure virtual
setBankID()
virtual void PdbCalBank::setBankID (const PdbBankID &) pure virtual
setDescription()
virtual void PdbCalBank::setDescription (const std::string &) pure virtual
setEndValTime()
virtual void PdbCalBank::setEndValTime (const PHTimeStamp &) pure virtual
setInsertTime()
virtual void PdbCalBank::setInsertTime (const PHTimeStamp &) pure virtual
setLength()
virtual void PdbCalBank::setLength (size_t val) pure virtual
Referenced by PHParametersContainer::WriteToDB(), PHG4ParametersContainer::WriteToDB(), PHG4Parameters::WriteToDB(), and PHParameters::WriteToDB().
setStartValTime()
virtual void PdbCalBank::setStartValTime (const PHTimeStamp &) pure virtual
setUserName()
virtual void PdbCalBank::setUserName (const std::string &) pure virtual
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/database/pdbcal/base/PdbCalBank.h
/home/yuhw/GitHub/SeaQuest/e1039-core/database/pdbcal/base/PdbCalBank.cc