Class Reference for E1039 Core & Analysis Software: AnaSignal Class Reference
AnaSignal Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/AnaSignal.h>
Public Member Functions
AnaSignal (const std::string label="ana_signal")
virtual ~AnaSignal ()
void SetMassRange (const double mass_lo, const double mass_hi)
virtual void Init ()
virtual void End ()
virtual void ReadEvents (const char *fname="signal_tree.root")
virtual void Analyze ()
RoadMap * GetRoadMapPosTop ()
RoadMap * GetRoadMapPosBot ()
RoadMap * GetRoadMapNegTop ()
RoadMap * GetRoadMapNegBot ()
Public Member Functions inherited from AnaBase
virtual ~AnaBase ()
virtual void SetInputTreeName (const std::string name)
virtual void SetInputBranchName (const std::string name)
virtual void ReadEventsFromFileList (const char *fn_list, const int n_max=0)
Protected Member Functions
virtual void ProcessOneEvent ()
Protected Member Functions inherited from AnaBase
AnaBase (const std::string label)
Protected Attributes
double m_mass_lo
double m_mass_hi
RoadMap m_road_map_pos_top
RoadMap m_road_map_pos_bot
RoadMap m_road_map_neg_top
RoadMap m_road_map_neg_bot
SignalData * m_sig_data
Protected Attributes inherited from AnaBase
std::string m_label
std::string m_tree_name
std::string m_branch_name
std::string m_dir_out
std::ofstream m_ofs
Detailed Description
Definition at line 9 of file AnaSignal.h.
Constructor & Destructor Documentation
AnaSignal::AnaSignal (const std::string label = "ana_signal")
Definition at line 12 of file AnaSignal.cc.
References m_road_map_neg_bot, m_road_map_neg_top, m_road_map_pos_bot, m_road_map_pos_top, and RoadListBase::SetPNTB().
AnaSignal::~AnaSignal () virtual
Definition at line 24 of file AnaSignal.cc.
Member Function Documentation
void AnaSignal::Analyze () virtual
Reimplemented from AnaBase.
Reimplemented in ReAnaSignal.
Definition at line 87 of file AnaSignal.cc.
Referenced by GenerateRoad(), and GenerateRoadBySignal().
void AnaSignal::End () virtual
Reimplemented from AnaBase.
Reimplemented in ReAnaSignal.
Definition at line 40 of file AnaSignal.cc.
Referenced by GenerateRoad(), and GenerateRoadBySignal().
RoadMap* AnaSignal::GetRoadMapNegBot () inline
Definition at line 34 of file AnaSignal.h.
References m_road_map_neg_bot.
Referenced by ApplyRoadset2Signal(), GenRoadset::SetMap(), and AnaBG::SetRoads().
RoadMap* AnaSignal::GetRoadMapNegTop () inline
Definition at line 33 of file AnaSignal.h.
References m_road_map_neg_top.
Referenced by ApplyRoadset2Signal(), GenRoadset::SetMap(), and AnaBG::SetRoads().
RoadMap* AnaSignal::GetRoadMapPosBot () inline
Definition at line 32 of file AnaSignal.h.
References m_road_map_pos_bot.
Referenced by ApplyRoadset2Signal(), GenRoadset::SetMap(), and AnaBG::SetRoads().
RoadMap* AnaSignal::GetRoadMapPosTop () inline
Definition at line 31 of file AnaSignal.h.
References m_road_map_pos_top.
Referenced by ApplyRoadset2Signal(), GenRoadset::SetMap(), and AnaBG::SetRoads().
void AnaSignal::Init () virtual
Reimplemented from AnaBase.
Reimplemented in ReAnaSignal.
Definition at line 35 of file AnaSignal.cc.
Referenced by GenerateRoad(), and GenerateRoadBySignal().
void AnaSignal::ProcessOneEvent () protected virtual
Reimplemented from AnaBase.
Reimplemented in ReAnaSignal.
Definition at line 70 of file AnaSignal.cc.
References RoadMap::Add(), m_mass_hi, m_road_map_neg_bot, m_road_map_neg_top, m_road_map_pos_bot, m_road_map_pos_top, m_sig_data, SignalData::mass, SignalData::road_neg, SignalData::road_pos, and SignalData::weight.
Referenced by ReadEvents().
void AnaSignal::ReadEvents (const char * fname = "signal_tree.root") virtual
Reimplemented from AnaBase.
Definition at line 45 of file AnaSignal.cc.
References file, AnaBase::m_branch_name, m_sig_data, AnaBase::m_tree_name, ProcessOneEvent(), and tree.
void AnaSignal::SetMassRange (const double mass_lo, const double mass_hi)
Definition at line 29 of file AnaSignal.cc.
References m_mass_hi, and m_mass_lo.
Referenced by ApplyRoadset2Signal(), GenerateRoad(), and GenerateRoadBySignal().
Member Data Documentation
double AnaSignal::m_mass_hi protected
Definition at line 12 of file AnaSignal.h.
Referenced by ProcessOneEvent(), ReAnaSignal::ProcessOneEvent(), and SetMassRange().
double AnaSignal::m_mass_lo protected
Definition at line 11 of file AnaSignal.h.
Referenced by ReAnaSignal::ProcessOneEvent(), and SetMassRange().
RoadMap AnaSignal::m_road_map_neg_bot protected
Definition at line 16 of file AnaSignal.h.
Referenced by AnaSignal(), GetRoadMapNegBot(), ProcessOneEvent(), and ReAnaSignal::ProcessOneEvent().
RoadMap AnaSignal::m_road_map_neg_top protected
Definition at line 15 of file AnaSignal.h.
Referenced by AnaSignal(), GetRoadMapNegTop(), ProcessOneEvent(), and ReAnaSignal::ProcessOneEvent().
RoadMap AnaSignal::m_road_map_pos_bot protected
Definition at line 14 of file AnaSignal.h.
Referenced by AnaSignal(), GetRoadMapPosBot(), ProcessOneEvent(), and ReAnaSignal::ProcessOneEvent().
RoadMap AnaSignal::m_road_map_pos_top protected
Definition at line 13 of file AnaSignal.h.
Referenced by AnaSignal(), GetRoadMapPosTop(), ProcessOneEvent(), and ReAnaSignal::ProcessOneEvent().
SignalData* AnaSignal::m_sig_data protected
Definition at line 18 of file AnaSignal.h.
Referenced by ProcessOneEvent(), ReAnaSignal::ProcessOneEvent(), and ReadEvents().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/AnaSignal.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/AnaSignal.cc