Class Reference for E1039 Core & Analysis Software: PatternDB Class Reference
PatternDB Class Reference
PatternDB interface objects.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/patterndb/PatternDB.h>
Public Types
enum STATION {
DC1, DC2, DC3p, DC3m,
ERROR_STATION
}
Public Member Functions
PatternDB ()
virtual ~PatternDB ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PatternDB * Clone () const
void print ()
ClassDef (PatternDB, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Public Attributes
std::set< TrackletKey > St1
std::set< TrackletKey > St2
std::set< TrackletKey > St3
std::set< PartTrackKey > St23
std::set< GlobTrackKey > St123
Static Public Attributes
static const TrackletKey ERR_KEY = TrackletKey(0,0,0,0)
Detailed Description
PatternDB interface objects.
Author
Haiwang Yu, yuhw@.nosp@m.nmsu.nosp@m..edu
Created: 08-27-2018
Definition at line 117 of file PatternDB.h.
Member Enumeration Documentation
enum PatternDB::STATION
Enumerator
DC1
DC2
DC3p
DC3m
ERROR_STATION
Definition at line 126 of file PatternDB.h.
Constructor & Destructor Documentation
PatternDB::PatternDB ()
Definition at line 87 of file PatternDB.cxx.
Referenced by Clone(), and Reset().
virtual PatternDB::~PatternDB () inline virtual
Definition at line 129 of file PatternDB.h.
Member Function Documentation
PatternDB::ClassDef (PatternDB , 1)
virtual PatternDB* PatternDB::Clone () const inline virtual
Definition at line 135 of file PatternDB.h.
References PatternDB().
void PatternDB::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 90 of file PatternDB.cxx.
References St1, St123, St2, St23, and St3.
Referenced by print().
int PatternDB::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 101 of file PatternDB.cxx.
References St1, St2, St23, and St3.
void PatternDB::print ()
Definition at line 157 of file PatternDB.cxx.
References identify(), and St1.
Referenced by PatternDBUtil::BuildPatternDB(), and PatternDBUtil::LoadPatternDB().
virtual void PatternDB::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 133 of file PatternDB.h.
References PatternDB().
Member Data Documentation
const TrackletKey PatternDB::ERR_KEY = TrackletKey(0,0,0,0) static
Definition at line 124 of file PatternDB.h.
Referenced by KalmanDSTrk::buildBackPartialTracks(), KalmanDSTrk::buildGlobalTracks(), PatternDBUtil::BuildPatternDB(), PatternDBUtil::EncodeTrackletKey(), and PatternDBUtil::GetTrackletKey().
std::set<TrackletKey> PatternDB::St1
Definition at line 142 of file PatternDB.h.
Referenced by PatternDBUtil::BuildPatternDB(), KalmanDSTrk::buildTrackletsInStation(), identify(), isValid(), PatternDBUtil::LoadPatternDB(), and print().
std::set<GlobTrackKey> PatternDB::St123
Definition at line 146 of file PatternDB.h.
Referenced by KalmanDSTrk::buildGlobalTracks(), PatternDBUtil::BuildPatternDB(), identify(), and PatternDBUtil::LoadPatternDB().
std::set<TrackletKey> PatternDB::St2
Definition at line 143 of file PatternDB.h.
Referenced by PatternDBUtil::BuildPatternDB(), KalmanDSTrk::buildTrackletsInStation(), identify(), isValid(), and PatternDBUtil::LoadPatternDB().
std::set<PartTrackKey> PatternDB::St23
Definition at line 145 of file PatternDB.h.
Referenced by KalmanDSTrk::buildBackPartialTracks(), PatternDBUtil::BuildPatternDB(), identify(), isValid(), and PatternDBUtil::LoadPatternDB().
std::set<TrackletKey> PatternDB::St3
Definition at line 144 of file PatternDB.h.
Referenced by PatternDBUtil::BuildPatternDB(), KalmanDSTrk::buildTrackletsInStation(), identify(), isValid(), and PatternDBUtil::LoadPatternDB().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/patterndb/PatternDB.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/patterndb/PatternDB.cxx