Class Reference for E1039 Core & Analysis Software: SQHitVector_v1 Class Reference
SQHitVector_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHitVector_v1.h>
Public Member Functions
SQHitVector_v1 ()
SQHitVector_v1 (const SQHitVector_v1 &hitmap)
SQHitVector_v1 & operator= (const SQHitVector_v1 &hitmap)
virtual ~SQHitVector_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQHitVector * Clone () const
bool empty () const
size_t size () const
void clear ()
const SQHit * at (const size_t idkey) const
SQHit * at (const size_t idkey)
void push_back (const SQHit *hit)
size_t erase (const size_t idkey)
Iter erase (Iter pos)
ConstIter begin () const
ConstIter end () const
Iter begin ()
Iter end ()
Public Member Functions inherited from SQHitVector
virtual ~SQHitVector ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from SQHitVector
typedef std::vector< SQHit * > HitVector
typedef std::vector< SQHit * >::const_iterator ConstIter
typedef std::vector< SQHit * >::iterator Iter
Protected Member Functions inherited from SQHitVector
SQHitVector ()
Detailed Description
Definition at line 18 of file SQHitVector_v1.h.
Constructor & Destructor Documentation
SQHitVector_v1() [1/2]
SQHitVector_v1::SQHitVector_v1 ()
Referenced by Clone().
SQHitVector_v1() [2/2]
SQHitVector_v1::SQHitVector_v1 (const SQHitVector_v1 & hitmap)
Definition at line 22 of file SQHitVector_v1.cxx.
References begin(), SQHit::Clone(), and end().
~SQHitVector_v1()
SQHitVector_v1::~SQHitVector_v1 () virtual
Definition at line 43 of file SQHitVector_v1.cxx.
References Reset().
Member Function Documentation
at() [1/2]
SQHit * SQHitVector_v1::at (const size_t idkey) virtual
Implements SQHitVector.
Definition at line 62 of file SQHitVector_v1.cxx.
at() [2/2]
const SQHit * SQHitVector_v1::at (const size_t idkey) const virtual
Implements SQHitVector.
Definition at line 57 of file SQHitVector_v1.cxx.
References size().
begin() [1/2]
Iter SQHitVector_v1::begin () inline virtual
Implements SQHitVector.
Definition at line 49 of file SQHitVector_v1.h.
begin() [2/2]
ConstIter SQHitVector_v1::begin () const inline virtual
Implements SQHitVector.
Definition at line 46 of file SQHitVector_v1.h.
Referenced by operator=(), and SQHitVector_v1().
clear()
void SQHitVector_v1::clear () inline virtual
Implements SQHitVector.
Definition at line 34 of file SQHitVector_v1.h.
References Reset().
Clone()
SQHitVector* SQHitVector_v1::Clone () const inline virtual
Implements SQHitVector.
Definition at line 30 of file SQHitVector_v1.h.
References SQHitVector_v1().
empty()
bool SQHitVector_v1::empty () const inline virtual
Implements SQHitVector.
Definition at line 32 of file SQHitVector_v1.h.
end() [1/2]
Iter SQHitVector_v1::end () inline virtual
Implements SQHitVector.
Definition at line 50 of file SQHitVector_v1.h.
end() [2/2]
ConstIter SQHitVector_v1::end () const inline virtual
Implements SQHitVector.
Definition at line 47 of file SQHitVector_v1.h.
Referenced by operator=(), and SQHitVector_v1().
erase() [1/2]
size_t SQHitVector_v1::erase (const size_t idkey) inline virtual
Implements SQHitVector.
Definition at line 39 of file SQHitVector_v1.h.
erase() [2/2]
Iter SQHitVector_v1::erase (Iter pos) inline virtual
Implements SQHitVector.
Definition at line 44 of file SQHitVector_v1.h.
identify()
void SQHitVector_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQHitVector.
Definition at line 52 of file SQHitVector_v1.cxx.
isValid()
int SQHitVector_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Implements SQHitVector.
Definition at line 29 of file SQHitVector_v1.h.
operator=()
SQHitVector_v1 & SQHitVector_v1::operator= (const SQHitVector_v1 & hitmap)
Definition at line 32 of file SQHitVector_v1.cxx.
References begin(), SQHit::Clone(), end(), and Reset().
push_back()
void SQHitVector_v1::push_back (const SQHit * hit) virtual
Implements SQHitVector.
Definition at line 67 of file SQHitVector_v1.cxx.
References SQHit::Clone().
Reset()
void SQHitVector_v1::Reset () virtual
Clear Event.
Implements SQHitVector.
Definition at line 47 of file SQHitVector_v1.cxx.
Referenced by clear(), operator=(), and ~SQHitVector_v1().
size()
size_t SQHitVector_v1::size (void) const inline virtual
Implements SQHitVector.
Definition at line 33 of file SQHitVector_v1.h.
Referenced by at().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHitVector_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHitVector_v1.cxx