Class Reference for E1039 Core & Analysis Software: OnlMonTrigNim Class Reference
OnlMonTrigNim Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonTrigNim.h>
Public Types
typedef std::vector< SQHit * > HitList_t
typedef std::map< short,
HitList_t > HitListMap_t
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Public Member Functions
OnlMonTrigNim ()
virtual ~OnlMonTrigNim ()
OnlMonClient * Clone ()
int InitOnlMon (PHCompositeNode *topNode)
int InitRunOnlMon (PHCompositeNode *topNode)
int ProcessEventOnlMon (PHCompositeNode *topNode)
int EndOnlMon (PHCompositeNode *topNode)
int FindAllMonHist ()
int DrawMonitor ()
Public Member Functions inherited from OnlMonClient
OnlMonClient ()
virtual ~OnlMonClient ()
void Title (const std::string &title)
std::string Title ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void GetBasicID (int *run_id=0, int *spill_id=0, int *event_id=0, int *spill_id_min=0, int *spill_id_max=0)
void GetBasicCount (int *n_evt=0, int *n_sp=0)
int StartMonitor ()
TH1 * FindMonHist (const std::string name, const bool non_null=true)
int SendHist (TSocket *sock, int sp_min, int sp_max)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Static Public Member Functions inherited from OnlMonClient
static void SetClearUsFlag (const bool val)
static bool GetClearUsFlag ()
Protected Types inherited from OnlMonClient
enum HistMode_t { MODE_ADD, MODE_UPDATE }
Protected Member Functions inherited from OnlMonClient
void RegisterHist (TH1 *h1, const HistMode_t mode=MODE_ADD)
void NumCanvases (const int num)
int NumCanvases ()
OnlMonCanvas * GetCanvas (const int num=0)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 6 of file OnlMonTrigNim.h.
Member Typedef Documentation
typedef std::vector<SQHit*> OnlMonTrigNim::HitList_t
Definition at line 10 of file OnlMonTrigNim.h.
typedef std::map<short, HitList_t> OnlMonTrigNim::HitListMap_t
Definition at line 11 of file OnlMonTrigNim.h.
Constructor & Destructor Documentation
OnlMonTrigNim::OnlMonTrigNim ()
Definition at line 17 of file OnlMonTrigNim.cc.
Referenced by Clone().
virtual OnlMonTrigNim::~OnlMonTrigNim () inline virtual
Definition at line 14 of file OnlMonTrigNim.h.
Member Function Documentation
OnlMonClient* OnlMonTrigNim::Clone () inline virtual
Reimplemented from OnlMonClient.
Definition at line 15 of file OnlMonTrigNim.h.
References OnlMonTrigNim().
int OnlMonTrigNim::DrawMonitor () virtual
Reimplemented from OnlMonClient.
Definition at line 126 of file OnlMonTrigNim.cc.
References OnlMonCanvas::AddMessage(), OnlMonCanvas::GetMainPad(), OnlMonCanvas::OK, OnlMonCanvas::SetStatus(), and OnlMonCanvas::WARN.
int OnlMonTrigNim::EndOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 115 of file OnlMonTrigNim.cc.
References Fun4AllReturnCodes::EVENT_OK.
int OnlMonTrigNim::FindAllMonHist () virtual
Reimplemented from OnlMonClient.
Definition at line 120 of file OnlMonTrigNim.cc.
int OnlMonTrigNim::InitOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 24 of file OnlMonTrigNim.cc.
References Fun4AllReturnCodes::EVENT_OK.
int OnlMonTrigNim::InitRunOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 29 of file OnlMonTrigNim.cc.
References Fun4AllReturnCodes::EVENT_OK.
int OnlMonTrigNim::ProcessEventOnlMon (PHCompositeNode * topNode) virtual
Sort out all hits.
Judge if each plane should fire (i.e. has a hit) or not
Fill the histogram per trigger
Reimplemented from OnlMonClient.
Definition at line 54 of file OnlMonTrigNim.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, GeomSvc::getDetectorID(), GeomSvc::instance(), SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, SQEvent::MATRIX5, SQEvent::NIM1, SQEvent::NIM2, SQEvent::NIM3, SQEvent::NIM4, and SQEvent::NIM5.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonTrigNim.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonTrigNim.cc