E1039 Software: PatternDBUtil Class Reference
PatternDBUtil Class Reference
PatternDB utilities.
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/PatternDBUtil.h>
Static Public Member Functions
static int BuildPatternDB (const std::string &fin, const std::string &fout, PatternDB &db)
static PatternDB * LoadPatternDB (const std::string &fin)
static TrackletKey EncodeTrackletKey (PatternDB::STATION, const unsigned int X, const unsigned int Xp, const unsigned int U, const unsigned int Up, const unsigned int V, const unsigned int Vp)
static TrackletKey GetTrackletKey (const Tracklet tracklet, const PatternDB::STATION station)
static TrackletKey GetTrackletKey (const std::vector< std::pair< unsigned int, unsigned int > > &det_elem_pairs, const PatternDB::STATION &station)
static int Verbosity ()
static void Verbosity (int verbosity)
Protected Member Functions
PatternDBUtil ()
virtual ~PatternDBUtil ()
Static Private Attributes
static std::map< unsigned int,
unsigned int > _detid_view
static int verbosity = 0
Detailed Description
PatternDB utilities.
Author
Haiwang Yu, yuhw@.nosp@m.nmsu.nosp@m..edu
Created: 08-27-2018
Definition at line 18 of file PatternDBUtil.h.
Constructor & Destructor Documentation
PatternDBUtil::PatternDBUtil () inline protected
Definition at line 50 of file PatternDBUtil.h.
virtual PatternDBUtil::~PatternDBUtil () inline protected virtual
Definition at line 51 of file PatternDBUtil.h.
Member Function Documentation
int PatternDBUtil::BuildPatternDB (const std::string & fin, const std::string & fout, PatternDB & db) static
Definition at line 55 of file PatternDBUtil.cxx.
References PatternDB::DC1, PatternDB::DC2, PatternDB::DC3m, PatternDB::DC3p, EncodeTrackletKey(), PatternDB::ERR_KEY, LogInfo, PatternDB::print(), PatternDB::St1, PatternDB::St123, PatternDB::St2, PatternDB::St23, PatternDB::St3, and verbosity.
Referenced by KalmanDSTrk::KalmanDSTrk().
TrackletKey PatternDBUtil::EncodeTrackletKey (PatternDB::STATION ST, const unsigned int X, const unsigned int Xp, const unsigned int U, const unsigned int Up, const unsigned int V, const unsigned int Vp) static
Definition at line 394 of file PatternDBUtil.cxx.
References _RESOLUTION1_, _RESOLUTION2_, _RESOLUTION3_, PatternDB::DC1, PatternDB::DC2, PatternDB::DC3m, and PatternDB::ERR_KEY.
Referenced by BuildPatternDB(), and GetTrackletKey().
TrackletKey PatternDBUtil::GetTrackletKey (const Tracklet tracklet, const PatternDB::STATION station) static
Definition at line 422 of file PatternDBUtil.cxx.
References _detid_view, PatternDB::DC1, PatternDB::DC2, PatternDB::DC3m, PatternDB::DC3p, EncodeTrackletKey(), PatternDB::ERR_KEY, and Tracklet::hits.
Referenced by KalmanDSTrk::buildBackPartialTracks(), KalmanDSTrk::buildGlobalTracks(), and KalmanDSTrk::buildTrackletsInStation().
TrackletKey PatternDBUtil::GetTrackletKey (const std::vector< std::pair< unsigned int, unsigned int > > & det_elem_pairs, const PatternDB::STATION & station) static
Definition at line 455 of file PatternDBUtil.cxx.
References _detid_view, PatternDB::DC1, PatternDB::DC2, PatternDB::DC3m, PatternDB::DC3p, EncodeTrackletKey(), and PatternDB::ERR_KEY.
PatternDB * PatternDBUtil::LoadPatternDB (const std::string & fin) static
Definition at line 317 of file PatternDBUtil.cxx.
References LogInfo, PatternDB::print(), PatternDB::St1, PatternDB::St123, PatternDB::St2, PatternDB::St23, PatternDB::St3, and verbosity.
Referenced by KalmanDSTrk::KalmanDSTrk().
static int PatternDBUtil::Verbosity () inline static
Definition at line 40 of file PatternDBUtil.h.
References verbosity.
Referenced by KalmanDSTrk::KalmanDSTrk().
static void PatternDBUtil::Verbosity (int verbosity) inline static
Definition at line 44 of file PatternDBUtil.h.
References verbosity.
Member Data Documentation
std::map< unsigned int, unsigned int > PatternDBUtil::_detid_view static private
Initial value:
= {
                {9,  0},
                {10, 1},
                {11, 2},
                {12, 3},
                {7,  4},
                {8,  5},
                {16, 0},
                {15, 1},
                {17, 2},
                {18, 3},
                {13, 4},
                {14, 5},
                {22, 0},
                {21, 1},
                {23, 2},
                {24, 3},
                {20, 4},
                {19, 5},
                {28, 0},
                {27, 1},
                {30, 2},
                {29, 3},
                {26, 4},
                {25, 5}
}
Definition at line 56 of file PatternDBUtil.h.
Referenced by GetTrackletKey().
int PatternDBUtil::verbosity = 0 static private
Definition at line 58 of file PatternDBUtil.h.
Referenced by BuildPatternDB(), LoadPatternDB(), and Verbosity().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/PatternDBUtil.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/PatternDBUtil.cxx