SeaQuest Offline Software: PHG4Prototype2OuterHcalSteppingAction Class Reference
PHG4Prototype2OuterHcalSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.h>
Public Member Functions
PHG4Prototype2OuterHcalSteppingAction (PHG4Prototype2OuterHcalDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4Prototype2OuterHcalSteppingAction ()
dtor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
double GetLightCorrection (const double r) const
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4Prototype2OuterHcalDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4Hit * hit
const PHParameters * params
PHG4HitContainer * savehitcontainer
PHG4Shower * saveshower
int absorbertruth
int IsActive
int IsBlackHole
int light_scint_model
double light_balance_inner_corr
double light_balance_inner_radius
double light_balance_outer_corr
double light_balance_outer_radius
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 12 of file PHG4Prototype2OuterHcalSteppingAction.h.
Constructor & Destructor Documentation
PHG4Prototype2OuterHcalSteppingAction::PHG4Prototype2OuterHcalSteppingAction (PHG4Prototype2OuterHcalDetector * detector, const PHParameters * parameters)
constructor
Definition at line 37 of file PHG4Prototype2OuterHcalSteppingAction.cc.
PHG4Prototype2OuterHcalSteppingAction::~PHG4Prototype2OuterHcalSteppingAction () virtual
dtor
Definition at line 56 of file PHG4Prototype2OuterHcalSteppingAction.cc.
References hit.
Member Function Documentation
double PHG4Prototype2OuterHcalSteppingAction::GetLightCorrection (const double r) const
Definition at line 366 of file PHG4Prototype2OuterHcalSteppingAction.cc.
References light_balance_inner_corr, light_balance_inner_radius, light_balance_outer_corr, and light_balance_outer_radius.
Referenced by UserSteppingAction().
void PHG4Prototype2OuterHcalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 332 of file PHG4Prototype2OuterHcalSteppingAction.cc.
References absorberhits_, detector_, PHG4Detector::GetName(), hits_, PHG4Prototype2OuterHcalDetector::SuperDetector(), and PHG4SteppingAction::verbosity.
bool PHG4Prototype2OuterHcalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 66 of file PHG4Prototype2OuterHcalSteppingAction.cc.
References absorberhits_, absorbertruth, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Prototype2OuterHcalDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4HitContainer::GetID(), GetLightCorrection(), PHG4SteppingAction::GetVisibleEnergyDeposition(), hit, hits_, IsActive, IsBlackHole, PHG4Prototype2OuterHcalDetector::IsInPrototype2OuterHcal(), light_balance_inner_corr, light_balance_inner_radius, light_balance_outer_corr, light_balance_outer_radius, light_scint_model, PHWHERE, PHG4Hit::Reset(), savehitcontainer, saveshower, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_hit_type(), PHG4Hit::set_light_yield(), PHG4Hit::set_row(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4HitContainer* PHG4Prototype2OuterHcalSteppingAction::absorberhits_ private
Definition at line 35 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4Prototype2OuterHcalSteppingAction::absorbertruth private
Definition at line 43 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Prototype2OuterHcalDetector* PHG4Prototype2OuterHcalSteppingAction::detector_ private
pointer to the detector
Definition at line 31 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4Prototype2OuterHcalSteppingAction::hit private
Definition at line 36 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4Prototype2OuterHcalSteppingAction().
PHG4HitContainer* PHG4Prototype2OuterHcalSteppingAction::hits_ private
pointer to hit container
Definition at line 34 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4Prototype2OuterHcalSteppingAction::IsActive private
Definition at line 44 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4Prototype2OuterHcalSteppingAction::IsBlackHole private
Definition at line 45 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
double PHG4Prototype2OuterHcalSteppingAction::light_balance_inner_corr private
Definition at line 48 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4Prototype2OuterHcalSteppingAction::light_balance_inner_radius private
Definition at line 49 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4Prototype2OuterHcalSteppingAction::light_balance_outer_corr private
Definition at line 50 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4Prototype2OuterHcalSteppingAction::light_balance_outer_radius private
Definition at line 51 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
int PHG4Prototype2OuterHcalSteppingAction::light_scint_model private
Definition at line 46 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
const PHParameters* PHG4Prototype2OuterHcalSteppingAction::params private
Definition at line 37 of file PHG4Prototype2OuterHcalSteppingAction.h.
PHG4HitContainer* PHG4Prototype2OuterHcalSteppingAction::savehitcontainer private
Definition at line 38 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4Prototype2OuterHcalSteppingAction::saveshower private
Definition at line 39 of file PHG4Prototype2OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.cc