Class Reference for E1039 Core & Analysis Software: G4Pythia6DecayerMessenger Class Reference
G4Pythia6DecayerMessenger Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4decayer/G4Pythia6DecayerMessenger.hh>
Public Member Functions
G4Pythia6DecayerMessenger (G4Pythia6Decayer *pythia6Decayer)
virtual ~G4Pythia6DecayerMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String string)
Detailed Description
Messenger class that defines commands for G4Pythia6Decayer.
Implements command
/pythia6Decayer/verbose [level]
/pythia6Decayer/forceDecayType [decayType]
Definition at line 50 of file G4Pythia6DecayerMessenger.hh.
Constructor & Destructor Documentation
G4Pythia6DecayerMessenger::G4Pythia6DecayerMessenger (G4Pythia6Decayer * pythia6Decayer)
Standard constructor
Definition at line 50 of file G4Pythia6DecayerMessenger.cc.
References G4Pythia6DecayerMessenger(), kMaxDecay, and kSemiElectronic.
Referenced by G4Pythia6DecayerMessenger().
G4Pythia6DecayerMessenger::~G4Pythia6DecayerMessenger () virtual
Destructor
Definition at line 83 of file G4Pythia6DecayerMessenger.cc.
Member Function Documentation
void G4Pythia6DecayerMessenger::SetNewValue (G4UIcommand * command, G4String string) virtual
Apply command to the associated object.
Definition at line 98 of file G4Pythia6DecayerMessenger.cc.
References G4Pythia6Decayer::ForceDecayType(), and G4Pythia6Decayer::SetVerboseLevel().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4decayer/G4Pythia6DecayerMessenger.hh
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4decayer/G4Pythia6DecayerMessenger.cc