Class Reference for E1039 Core & Analysis Software: boost::array< T, N > Class Template Reference
boost::array< T, N > Class Template Reference
#include </seaquest/users/kenichi/e1039/git/e1039-doc/Doxygen_Assist/array.hpp>
Public Types
enum { static_size = N }
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
reference operator[] (size_type i)
const_reference operator[] (size_type i) const
reference at (size_type i)
const_reference at (size_type i) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void swap (array< T, N > &y)
const T * data () const
T * data ()
T * c_array ()
template<typename T2 >
array< T, N > & operator= (const array< T2, N > &rhs)
void assign (const T &value)
void fill (const T &value)
Static Public Member Functions
static size_type size ()
static bool empty ()
static size_type max_size ()
static void rangecheck (size_type i)
Public Attributes
T elems [N]
Detailed Description
template<class T, std::size_t N>
class boost::array< T, N >
Definition at line 58 of file array.hpp.
Member Typedef Documentation
const_iterator
template<class T , std::size_t N> typedef const T* boost::array< T, N >::const_iterator
Definition at line 66 of file array.hpp.
const_reference
template<class T , std::size_t N> typedef const T& boost::array< T, N >::const_reference
Definition at line 68 of file array.hpp.
const_reverse_iterator
template<class T , std::size_t N> typedef std::reverse_iterator<const_iterator> boost::array< T, N >::const_reverse_iterator
Definition at line 84 of file array.hpp.
difference_type
template<class T , std::size_t N> typedef std::ptrdiff_t boost::array< T, N >::difference_type
Definition at line 70 of file array.hpp.
iterator
template<class T , std::size_t N> typedef T* boost::array< T, N >::iterator
Definition at line 65 of file array.hpp.
reference
template<class T , std::size_t N> typedef T& boost::array< T, N >::reference
Definition at line 67 of file array.hpp.
reverse_iterator
template<class T , std::size_t N> typedef std::reverse_iterator<iterator> boost::array< T, N >::reverse_iterator
Definition at line 83 of file array.hpp.
size_type
template<class T , std::size_t N> typedef std::size_t boost::array< T, N >::size_type
Definition at line 69 of file array.hpp.
value_type
template<class T , std::size_t N> typedef T boost::array< T, N >::value_type
Definition at line 64 of file array.hpp.
Member Enumeration Documentation
anonymous enum
template<class T , std::size_t N> anonymous enum
Enumerator
static_size
Definition at line 160 of file array.hpp.
Member Function Documentation
assign()
template<class T , std::size_t N> void boost::array< T, N >::assign (const T & value) inline
Definition at line 183 of file array.hpp.
References boost::array< T, N >::fill().
at() [1/2]
template<class T , std::size_t N> reference boost::array< T, N >::at (size_type i) inline
Definition at line 132 of file array.hpp.
References boost::array< T, N >::elems, and boost::array< T, N >::rangecheck().
at() [2/2]
template<class T , std::size_t N> const_reference boost::array< T, N >::at (size_type i) const inline
Definition at line 133 of file array.hpp.
References boost::array< T, N >::elems, and boost::array< T, N >::rangecheck().
back() [1/2]
template<class T , std::size_t N> reference boost::array< T, N >::back () inline
Definition at line 146 of file array.hpp.
References boost::array< T, N >::elems.
back() [2/2]
template<class T , std::size_t N> const_reference boost::array< T, N >::back () const inline
Definition at line 151 of file array.hpp.
References boost::array< T, N >::elems.
begin() [1/2]
template<class T , std::size_t N> iterator boost::array< T, N >::begin () inline
Definition at line 73 of file array.hpp.
References boost::array< T, N >::elems.
Referenced by boost::array< T, N >::crend(), boost::array< T, 0 >::crend(), boost::array< T, 0 >::end(), boost::array< T, N >::fill(), boost::operator<(), boost::array< T, N >::operator=(), boost::operator==(), boost::array< T, N >::rend(), and boost::array< T, 0 >::rend().
begin() [2/2]
template<class T , std::size_t N> const_iterator boost::array< T, N >::begin () const inline
Definition at line 74 of file array.hpp.
References boost::array< T, N >::elems.
c_array()
template<class T , std::size_t N> T* boost::array< T, N >::c_array () inline
Definition at line 173 of file array.hpp.
References boost::array< T, N >::elems.
cbegin()
template<class T , std::size_t N> const_iterator boost::array< T, N >::cbegin () const inline
Definition at line 75 of file array.hpp.
References boost::array< T, N >::elems.
Referenced by boost::array< T, 0 >::cend().
cend()
template<class T , std::size_t N> const_iterator boost::array< T, N >::cend () const inline
Definition at line 79 of file array.hpp.
References boost::array< T, N >::elems.
crbegin()
template<class T , std::size_t N> const_reverse_iterator boost::array< T, N >::crbegin () const inline
Definition at line 106 of file array.hpp.
References boost::array< T, N >::end().
crend()
template<class T , std::size_t N> const_reverse_iterator boost::array< T, N >::crend () const inline
Definition at line 114 of file array.hpp.
References boost::array< T, N >::begin().
data() [1/2]
template<class T , std::size_t N> T* boost::array< T, N >::data () inline
Definition at line 170 of file array.hpp.
References boost::array< T, N >::elems.
data() [2/2]
template<class T , std::size_t N> const T* boost::array< T, N >::data () const inline
Definition at line 169 of file array.hpp.
References boost::array< T, N >::elems.
empty()
template<class T , std::size_t N> static bool boost::array< T, N >::empty () inline static
Definition at line 158 of file array.hpp.
end() [1/2]
template<class T , std::size_t N> iterator boost::array< T, N >::end () inline
Definition at line 77 of file array.hpp.
References boost::array< T, N >::elems.
Referenced by boost::array< T, N >::crbegin(), boost::array< T, 0 >::crbegin(), boost::operator<(), boost::array< T, N >::operator=(), boost::operator==(), boost::array< T, N >::rbegin(), and boost::array< T, 0 >::rbegin().
end() [2/2]
template<class T , std::size_t N> const_iterator boost::array< T, N >::end () const inline
Definition at line 78 of file array.hpp.
References boost::array< T, N >::elems.
fill()
template<class T , std::size_t N> void boost::array< T, N >::fill (const T & value) inline
Definition at line 184 of file array.hpp.
References boost::array< T, N >::begin(), and boost::array< T, N >::size().
Referenced by boost::array< T, N >::assign(), and boost::array< T, 0 >::assign().
front() [1/2]
template<class T , std::size_t N> reference boost::array< T, N >::front () inline
Definition at line 136 of file array.hpp.
References boost::array< T, N >::elems.
front() [2/2]
template<class T , std::size_t N> const_reference boost::array< T, N >::front () const inline
Definition at line 141 of file array.hpp.
References boost::array< T, N >::elems.
max_size()
template<class T , std::size_t N> static size_type boost::array< T, N >::max_size () inline static
Definition at line 159 of file array.hpp.
operator=()
template<class T , std::size_t N> template<typename T2 > array<T,N>& boost::array< T, N >::operator= (const array< T2, N > & rhs) inline
Definition at line 177 of file array.hpp.
References boost::array< T, N >::begin(), and boost::array< T, N >::end().
operator[]() [1/2]
template<class T , std::size_t N> reference boost::array< T, N >::operator[] (size_type i) inline
Definition at line 119 of file array.hpp.
References boost::array< T, N >::elems.
operator[]() [2/2]
template<class T , std::size_t N> const_reference boost::array< T, N >::operator[] (size_type i) const inline
Definition at line 125 of file array.hpp.
References boost::array< T, N >::elems.
rangecheck()
template<class T , std::size_t N> static void boost::array< T, N >::rangecheck (size_type i) inline static
Definition at line 190 of file array.hpp.
References boost::array< T, N >::size().
Referenced by boost::array< T, N >::at().
rbegin() [1/2]
template<class T , std::size_t N> reverse_iterator boost::array< T, N >::rbegin () inline
Definition at line 102 of file array.hpp.
References boost::array< T, N >::end().
rbegin() [2/2]
template<class T , std::size_t N> const_reverse_iterator boost::array< T, N >::rbegin () const inline
Definition at line 103 of file array.hpp.
References boost::array< T, N >::end().
rend() [1/2]
template<class T , std::size_t N> reverse_iterator boost::array< T, N >::rend () inline
Definition at line 110 of file array.hpp.
References boost::array< T, N >::begin().
rend() [2/2]
template<class T , std::size_t N> const_reverse_iterator boost::array< T, N >::rend () const inline
Definition at line 111 of file array.hpp.
References boost::array< T, N >::begin().
size()
template<class T , std::size_t N> static size_type boost::array< T, N >::size () inline static
Definition at line 157 of file array.hpp.
Referenced by boost::array< T, N >::fill(), and boost::array< T, N >::rangecheck().
swap()
template<class T , std::size_t N> void boost::array< T, N >::swap (array< T, N > & y) inline
Definition at line 163 of file array.hpp.
References boost::array< T, N >::elems, and boost::swap().
Referenced by boost::swap().
Member Data Documentation
elems
template<class T , std::size_t N> T boost::array< T, N >::elems[N]
Definition at line 60 of file array.hpp.
Referenced by boost::array< T, N >::at(), boost::array< T, N >::back(), boost::array< T, N >::begin(), boost::array< T, N >::c_array(), boost::array< T, N >::cbegin(), boost::array< T, N >::cend(), boost::array< T, N >::data(), boost::array< T, N >::end(), boost::array< T, N >::front(), boost::array< T, N >::operator[](), and boost::array< T, N >::swap().
The documentation for this class was generated from the following file:
/seaquest/users/kenichi/e1039/git/e1039-doc/Doxygen_Assist/array.hpp