SeaQuest Offline Software: PHG4SiliconTrackerCellReco Class Reference
PHG4SiliconTrackerCellReco Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerCellReco.h>
Public Member Functions
PHG4SiliconTrackerCellReco (const std::string &name="SILICON_TRACKER")
virtual ~PHG4SiliconTrackerCellReco ()
int InitRun (PHCompositeNode *topNode)
module initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
end of process
void Detector (const std::string &d)
void checkenergy (const int i=1)
double get_timing_window_min (const int i)
double get_timing_window_max (const int i)
void set_timing_window (const int i, const double tmin, const double tmax)
void set_timing_window_defaults (const double tmin, const double tmax)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int CheckEnergy (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::map< int, int > binning
std::string detector
std::string hitnodename
std::string cellnodename
std::string geonodename
PHTimeServer::timer _timer
int nbins [2]
int chkenergyconservation
std::map< std::string, PHG4Cell * > celllist
double tmin_default
double tmax_default
std::map< int, std::pair
< double, double > > tmin_max
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 13 of file PHG4SiliconTrackerCellReco.h.
Constructor & Destructor Documentation
PHG4SiliconTrackerCellReco::PHG4SiliconTrackerCellReco (const std::string & name = "SILICON_TRACKER")
Definition at line 27 of file PHG4SiliconTrackerCellReco.cc.
References cellnodename, Detector(), detector, geonodename, hitnodename, and nbins.
virtual PHG4SiliconTrackerCellReco::~PHG4SiliconTrackerCellReco () inline virtual
Definition at line 18 of file PHG4SiliconTrackerCellReco.h.
Member Function Documentation
void PHG4SiliconTrackerCellReco::checkenergy (const int i = 1) inline
Definition at line 29 of file PHG4SiliconTrackerCellReco.h.
References chkenergyconservation.
int PHG4SiliconTrackerCellReco::CheckEnergy (PHCompositeNode * topNode) protected
Definition at line 244 of file PHG4SiliconTrackerCellReco.cc.
References cellnodename, PHG4HitContainer::getHits(), hitnodename, Fun4AllBase::Name(), and Fun4AllBase::verbosity.
Referenced by process_event().
void PHG4SiliconTrackerCellReco::Detector (const std::string & d) inline
Definition at line 28 of file PHG4SiliconTrackerCellReco.h.
References detector.
Referenced by PHG4SiliconTrackerCellReco().
int PHG4SiliconTrackerCellReco::End (PHCompositeNode * topNode) virtual
end of process
Reimplemented from SubsysReco.
Definition at line 239 of file PHG4SiliconTrackerCellReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
double PHG4SiliconTrackerCellReco::get_timing_window_max (const int i) inline
Definition at line 31 of file PHG4SiliconTrackerCellReco.h.
References tmin_max.
double PHG4SiliconTrackerCellReco::get_timing_window_min (const int i) inline
Definition at line 30 of file PHG4SiliconTrackerCellReco.h.
References tmin_max.
int PHG4SiliconTrackerCellReco::InitRun (PHCompositeNode * topNode) virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 45 of file PHG4SiliconTrackerCellReco.cc.
References PHCompositeNode::addNode(), cellnodename, detector, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), geonodename, hitnodename, PHG4CylinderGeomContainer::identify(), PHWHERE, and Fun4AllBase::verbosity.
int PHG4SiliconTrackerCellReco::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 107 of file PHG4SiliconTrackerCellReco.cc.
References _timer, PHG4Cell::add_edep(), PHG4CellContainer::AddCell(), celllist, cellnodename, CheckEnergy(), chkenergyconservation, Fun4AllReturnCodes::EVENT_OK, PHG4CylinderGeom::find_strip_center(), PHG4CellDefs::MapsBinning::genkey(), geonodename, PHTimeServer::timer::get(), PHG4HitContainer::getHits(), PHG4CylinderGeomContainer::GetLayerGeom(), hitnodename, Fun4AllBase::Name(), PHG4CellContainer::Reset(), PHTimer::restart(), PHG4Cell::set_ladder_phi_index(), PHG4Cell::set_ladder_z_index(), PHG4Cell::set_phibin(), PHG4Cell::set_zbin(), PHTimer::stop(), tmax_default, tmin_default, and Fun4AllBase::verbosity.
void PHG4SiliconTrackerCellReco::set_timing_window (const int i, const double tmin, const double tmax) inline
Definition at line 32 of file PHG4SiliconTrackerCellReco.h.
References tmin_max.
void PHG4SiliconTrackerCellReco::set_timing_window_defaults (const double tmin, const double tmax) inline
Definition at line 36 of file PHG4SiliconTrackerCellReco.h.
References convertRT::tmax, tmax_default, convertRT::tmin, and tmin_default.
Member Data Documentation
PHTimeServer::timer PHG4SiliconTrackerCellReco::_timer protected
Definition at line 49 of file PHG4SiliconTrackerCellReco.h.
Referenced by process_event().
std::map<int, int> PHG4SiliconTrackerCellReco::binning protected
Definition at line 44 of file PHG4SiliconTrackerCellReco.h.
std::map<std::string, PHG4Cell *> PHG4SiliconTrackerCellReco::celllist protected
Definition at line 52 of file PHG4SiliconTrackerCellReco.h.
Referenced by process_event().
std::string PHG4SiliconTrackerCellReco::cellnodename protected
Definition at line 47 of file PHG4SiliconTrackerCellReco.h.
Referenced by CheckEnergy(), InitRun(), PHG4SiliconTrackerCellReco(), and process_event().
int PHG4SiliconTrackerCellReco::chkenergyconservation protected
Definition at line 51 of file PHG4SiliconTrackerCellReco.h.
Referenced by checkenergy(), and process_event().
std::string PHG4SiliconTrackerCellReco::detector protected
Definition at line 45 of file PHG4SiliconTrackerCellReco.h.
Referenced by Detector(), InitRun(), and PHG4SiliconTrackerCellReco().
std::string PHG4SiliconTrackerCellReco::geonodename protected
Definition at line 48 of file PHG4SiliconTrackerCellReco.h.
Referenced by InitRun(), PHG4SiliconTrackerCellReco(), and process_event().
std::string PHG4SiliconTrackerCellReco::hitnodename protected
Definition at line 46 of file PHG4SiliconTrackerCellReco.h.
Referenced by CheckEnergy(), InitRun(), PHG4SiliconTrackerCellReco(), and process_event().
int PHG4SiliconTrackerCellReco::nbins[2] protected
Definition at line 50 of file PHG4SiliconTrackerCellReco.h.
Referenced by PHG4SiliconTrackerCellReco().
double PHG4SiliconTrackerCellReco::tmax_default protected
Definition at line 55 of file PHG4SiliconTrackerCellReco.h.
Referenced by process_event(), and set_timing_window_defaults().
double PHG4SiliconTrackerCellReco::tmin_default protected
Definition at line 54 of file PHG4SiliconTrackerCellReco.h.
Referenced by process_event(), and set_timing_window_defaults().
std::map<int, std::pair<double, double> > PHG4SiliconTrackerCellReco::tmin_max protected
Definition at line 56 of file PHG4SiliconTrackerCellReco.h.
Referenced by get_timing_window_max(), get_timing_window_min(), and set_timing_window().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerCellReco.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerCellReco.cc