Class Reference for E1039 Core & Analysis Software: UtilTrigger::TrigRoads Class Reference
UtilTrigger::TrigRoads Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/TrigRoads.h>
Public Member Functions
TrigRoads (const int pol, const int top_bot)
virtual ~TrigRoads ()
unsigned int GetNumRoads () const
TrigRoad * GetRoad (const int idx)
TrigRoad * FindRoad (const int road_id)
int Charge () const
int TopBot () const
int LoadConfig (const std::string file_name)
std::string str (const int level=0) const
Detailed Description
Definition at line 10 of file TrigRoads.h.
Constructor & Destructor Documentation
TrigRoads()
UtilTrigger::TrigRoads::TrigRoads (const int pol, const int top_bot)
Definition at line 10 of file TrigRoads.cc.
~TrigRoads()
virtual UtilTrigger::TrigRoads::~TrigRoads () inline virtual
Definition at line 19 of file TrigRoads.h.
Member Function Documentation
Charge()
int UtilTrigger::TrigRoads::Charge () const inline
Definition at line 25 of file TrigRoads.h.
FindRoad()
TrigRoad * UtilTrigger::TrigRoads::FindRoad (const int road_id)
Definition at line 24 of file TrigRoads.cc.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
GetNumRoads()
unsigned int UtilTrigger::TrigRoads::GetNumRoads () const inline
Definition at line 21 of file TrigRoads.h.
GetRoad()
TrigRoad * UtilTrigger::TrigRoads::GetRoad (const int idx)
Definition at line 18 of file TrigRoads.cc.
LoadConfig()
int UtilTrigger::TrigRoads::LoadConfig (const std::string file_name)
Definition at line 31 of file TrigRoads.cc.
References UtilTrigger::TrigRoad::charge, UtilTrigger::TrigRoad::H1X, UtilTrigger::TrigRoad::H2X, UtilTrigger::TrigRoad::H3X, UtilTrigger::TrigRoad::H4X, and UtilTrigger::TrigRoad::road_id.
Referenced by UtilTrigger::TrigRoadset::LoadConfig().
str()
std::string UtilTrigger::TrigRoads::str (const int level = 0) const
Definition at line 60 of file TrigRoads.cc.
Referenced by UtilTrigger::TrigRoadset::str().
TopBot()
int UtilTrigger::TrigRoads::TopBot () const inline
Definition at line 26 of file TrigRoads.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/TrigRoads.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/TrigRoads.cc