E1039 Software: OnlMonServer Class Reference
OnlMonServer Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/online/onlmonserver/OnlMonServer.h>
Public Member Functions
virtual ~OnlMonServer ()
void StartServer ()
bool CloseExistingServer ()
Close an existing server process if such exists.
void HandleConnection (TSocket *sock)
void SetGoEnd (const bool val)
bool GetGoEnd ()
void GetMutex (pthread_mutex_t &lock)
void SetThreadId (pthread_t &id)
Public Member Functions inherited from Fun4AllServer
virtual ~Fun4AllServer ()
virtual bool registerHisto (const char *hname, TNamed *h1d, const int replace=0)
virtual bool registerHisto (TNamed *h1d, const int replace=0)
template<typename T >
T * makeHisto (T *t)
virtual int isHistoRegistered (const std::string &name) const
int registerSubsystem (SubsysReco *subsystem, const std::string &topnodename="TOP")
int unregisterSubsystem (SubsysReco *subsystem)
SubsysReco * getSubsysReco (const std::string &name)
int registerOutputManager (Fun4AllOutputManager *manager)
Fun4AllOutputManager * getOutputManager (const std::string &name)
int registerHistoManager (Fun4AllHistoManager *manager)
Fun4AllHistoManager * getHistoManager (const std::string &name)
TNamed * getHisto (const std::string &hname) const
TNamed * getHisto (const unsigned int ihisto) const
const char * getHistoName (const unsigned int ihisto) const
virtual void Print (const std::string &what="ALL") const
void InitAll ()
int BeginRunTimeStamp (PHTimeStamp &TimeStp)
int dumpHistos (const std::string &filename="", const std::string &openmode="RECREATE")
int process_event (PHCompositeNode *topNode)
int Reset ()
virtual int BeginRun (const int runno)
virtual int EndRun (const int runno=0)
virtual int End ()
PHCompositeNode * topNode () const
PHCompositeNode * topNode (const std::string &name)
int outfileclose ()
virtual int process_event ()
PHCompositeNode * getNode (const char *name, const char *topnodename="TOP")
int AddTopNode (const std::string &name)
int MakeNodesTransient (PHCompositeNode *startNode)
int MakeNodesPersistent (PHCompositeNode *startNode)
int AddComplaint (const std::string &complaint, const std::string &remedy)
int registerInputManager (Fun4AllInputManager *InManager)
Fun4AllInputManager * getInputManager (const char *name)
int PrdfEvents () const
int DstEvents () const
int run (const int nevnts=0, const bool require_nevents=false)
run n events (0 means up to end of file)
int skip (const int nevnts=0)
skip n events (0 means up to the end of file). Skip means read, don't process.
int fileopen (const char *managername="NONE", const char *filename="NONE")
int fileclose (const std::string &managername="")
int SegmentNumber ()
int ResetNodeTree ()
int BranchSelect (const char *managername, const char *branch, int iflag)
int BranchSelect (const char *branch, int iflag)
int setBranches (const char *managername)
int setBranches ()
virtual int DisconnectDB ()
virtual void identify (std::ostream &out=std::cout) const
unsigned GetTopNodes (std::vector< std::string > &names) const
void GetInputFullFileList (std::vector< std::string > &fnames) const
void GetOutputManagerList (std::vector< std::string > &names) const
void GetModuleList (std::vector< std::string > &names) const
Fun4AllSyncManager * getSyncManager (const std::string &name="DefaultSyncManager")
int registerSyncManager (Fun4AllSyncManager *newmaster)
int retcodestats (const int iret)
void EventNumber (const int evtno)
void NodeIdentify (const std::string &name)
void KeepDBConnection (const int i=1)
void PrintTimer (const std::string &name="")
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static OnlMonServer * instance ()
static void SetOutDir (const std::string dir)
static void SetHost (const std::string host)
static void SetPort (const int port)
static std::string GetOutDir ()
static std::string GetHost ()
static int GetPort ()
static void * FuncServer (void *arg)
Static Public Member Functions inherited from Fun4AllServer
static Fun4AllServer * instance ()
Protected Member Functions
OnlMonServer (const std::string &name="OnlMonServer")
Protected Member Functions inherited from Fun4AllServer
Fun4AllServer (const std::string &name="Fun4AllServer")
int InitNodeTree (PHCompositeNode *topNode)
int CountOutNodes (PHCompositeNode *startNode)
int CountOutNodesRecursive (PHCompositeNode *startNode, const int icount)
int UpdateEventSelector (Fun4AllOutputManager *manager)
int unregisterSubsystemsNow ()
int setRun (const int runnumber)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
pthread_mutex_t mutex
pthread_t serverthreadid
Protected Attributes inherited from Fun4AllServer
int OutNodeCount
int bortime_override
int ScreamEveryEvent
int unregistersubsystem
int runnumber
int eventnumber
std::vector< std::string > ComplaintList
PHCompositeNode * TopNode
std::vector< std::pair< SubsysReco *, PHCompositeNode * > > Subsystems
std::vector< std::pair< SubsysReco *, PHCompositeNode * > > DeleteSubsystems
std::vector< int > RetCodes
std::vector< Fun4AllOutputManager * > OutputManager
std::vector< TDirectory * > TDirCollection
Fun4AllHistoManager * ServerHistoManager
std::vector< Fun4AllHistoManager * > HistoManager
std::map< std::string, PHCompositeNode * > topnodemap
PHTimeStamp * beginruntimestamp
std::string default_Tdirectory
Fun4AllSyncManager * defaultSyncManager
std::vector< Fun4AllSyncManager * > SyncManagers
std::map< int, int > retcodesmap
std::map< const std::string, PHTimer > timer_map
TH1 * FrameWorkVars
int keep_db_connected
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Private Attributes
bool m_go_end
Static Private Attributes
static std::string m_out_dir = "/data2/e1039/onlmon/plots"
static std::string m_onl_mon_host = "localhost"
static int m_onl_mon_port = 9081
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Static Protected Attributes inherited from Fun4AllServer
static Fun4AllServer * __instance = 0
Detailed Description
Definition at line 8 of file OnlMonServer.h.
Constructor & Destructor Documentation
~OnlMonServer()
OnlMonServer::~OnlMonServer () virtual
Definition at line 49 of file OnlMonServer.cc.
OnlMonServer()
OnlMonServer::OnlMonServer (const std::string & name = "OnlMonServer") protected
Definition at line 42 of file OnlMonServer.cc.
References mutex.
Referenced by SetThreadId().
Member Function Documentation
CloseExistingServer()
bool OnlMonServer::CloseExistingServer ()
Close an existing server process if such exists.
It is possible that multiple decoding processes run in parallel on multiple runs. This function tries to keep the server of only the lastest process (which is expected to hanle the lastest run).
Definition at line 92 of file OnlMonServer.cc.
References GetHost(), and GetPort().
Referenced by GetPort(), and StartServer().
FuncServer()
void * OnlMonServer::FuncServer (void * arg) static
Definition at line 106 of file OnlMonServer.cc.
References GetGoEnd(), HandleConnection(), NULL, and Fun4AllBase::Verbosity().
Referenced by GetPort(), and StartServer().
GetGoEnd()
bool OnlMonServer::GetGoEnd () inline
Definition at line 32 of file OnlMonServer.h.
References m_go_end.
Referenced by FuncServer().
GetHost()
static std::string OnlMonServer::GetHost () inline static
Definition at line 24 of file OnlMonServer.h.
References m_onl_mon_host.
Referenced by CloseExistingServer(), and OnlMonClient::ReceiveHist().
GetMutex()
void OnlMonServer::GetMutex (pthread_mutex_t & lock) inline
Definition at line 35 of file OnlMonServer.h.
References mutex.
GetOutDir()
static std::string OnlMonServer::GetOutDir () inline static
Definition at line 23 of file OnlMonServer.h.
References m_out_dir.
Referenced by OnlMonClient::End(), and OnlMonCanvas::PostDraw().
GetPort()
static int OnlMonServer::GetPort () inline static
Definition at line 25 of file OnlMonServer.h.
References CloseExistingServer(), FuncServer(), HandleConnection(), m_onl_mon_port, and StartServer().
Referenced by CloseExistingServer(), and OnlMonClient::ReceiveHist().
HandleConnection()
void OnlMonServer::HandleConnection (TSocket * sock)
Definition at line 192 of file OnlMonServer.cc.
References Fun4AllHistoManager::getHisto(), Fun4AllServer::getHistoManager(), m_go_end, Fun4AllHistoManager::nHistos(), NULL, and Fun4AllBase::Verbosity().
Referenced by FuncServer(), and GetPort().
instance()
OnlMonServer * OnlMonServer::instance () static
Definition at line 32 of file OnlMonServer.cc.
Referenced by OnlMonClient::InitRun().
SetGoEnd()
void OnlMonServer::SetGoEnd (const bool val) inline
Definition at line 31 of file OnlMonServer.h.
SetHost()
static void OnlMonServer::SetHost (const std::string host) inline static
Definition at line 21 of file OnlMonServer.h.
SetOutDir()
static void OnlMonServer::SetOutDir (const std::string dir) inline static
Definition at line 20 of file OnlMonServer.h.
SetPort()
static void OnlMonServer::SetPort (const int port) inline static
Definition at line 22 of file OnlMonServer.h.
SetThreadId()
void OnlMonServer::SetThreadId (pthread_t & id) inline
Definition at line 36 of file OnlMonServer.h.
References OnlMonServer(), and serverthreadid.
Referenced by StartServer().
StartServer()
void OnlMonServer::StartServer ()
Definition at line 54 of file OnlMonServer.cc.
References CloseExistingServer(), FuncServer(), NULL, ServerThread, SetThreadId(), and Fun4AllBase::Verbosity().
Referenced by GetPort().
Member Data Documentation
m_go_end
bool OnlMonServer::m_go_end private
Definition at line 14 of file OnlMonServer.h.
Referenced by GetGoEnd(), and HandleConnection().
m_onl_mon_host
std::string OnlMonServer::m_onl_mon_host = "localhost" static private
Definition at line 11 of file OnlMonServer.h.
Referenced by GetHost().
m_onl_mon_port
int OnlMonServer::m_onl_mon_port = 9081 static private
Definition at line 12 of file OnlMonServer.h.
Referenced by GetPort().
m_out_dir
std::string OnlMonServer::m_out_dir = "/data2/e1039/onlmon/plots" static private
Definition at line 10 of file OnlMonServer.h.
Referenced by GetOutDir().
mutex
pthread_mutex_t OnlMonServer::mutex protected
Definition at line 43 of file OnlMonServer.h.
Referenced by GetMutex(), and OnlMonServer().
serverthreadid
pthread_t OnlMonServer::serverthreadid protected
Definition at line 44 of file OnlMonServer.h.
Referenced by SetThreadId().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/online/onlmonserver/OnlMonServer.h
/home/yuhw/GitHub/SeaQuest/e1039-core/online/onlmonserver/OnlMonServer.cc