Class Reference for E1039 Core & Analysis Software: Fun4AllServer Class Reference
Fun4AllServer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/fun4all/Fun4AllServer.h>
Public Member Functions
virtual ~Fun4AllServer ()
virtual bool registerHisto (const char *hname, TNamed *h1d, const int replace=0)
virtual bool registerHisto (TNamed *h1d, const int replace=0)
template<typename T >
T * makeHisto (T *t)
virtual int isHistoRegistered (const std::string &name) const
int registerSubsystem (SubsysReco *subsystem, const std::string &topnodename="TOP")
int unregisterSubsystem (SubsysReco *subsystem)
SubsysReco * getSubsysReco (const std::string &name)
int registerOutputManager (Fun4AllOutputManager *manager)
Fun4AllOutputManager * getOutputManager (const std::string &name)
int registerHistoManager (Fun4AllHistoManager *manager)
Fun4AllHistoManager * getHistoManager (const std::string &name)
TNamed * getHisto (const std::string &hname) const
TNamed * getHisto (const unsigned int ihisto) const
const char * getHistoName (const unsigned int ihisto) const
virtual void Print (const std::string &what="ALL") const
void InitAll ()
int BeginRunTimeStamp (PHTimeStamp &TimeStp)
int dumpHistos (const std::string &filename="", const std::string &openmode="RECREATE")
int process_event (PHCompositeNode *topNode)
int Reset ()
virtual int BeginRun (const int runno)
virtual int EndRun (const int runno=0)
virtual int End ()
PHCompositeNode * topNode () const
PHCompositeNode * topNode (const std::string &name)
int outfileclose ()
virtual int process_event ()
PHCompositeNode * getNode (const char *name, const char *topnodename="TOP")
int AddTopNode (const std::string &name)
int MakeNodesTransient (PHCompositeNode *startNode)
int MakeNodesPersistent (PHCompositeNode *startNode)
int AddComplaint (const std::string &complaint, const std::string &remedy)
int registerInputManager (Fun4AllInputManager *InManager)
Fun4AllInputManager * getInputManager (const char *name)
int PrdfEvents () const
int DstEvents () const
int run (const int nevnts=0, const bool require_nevents=false)
run n events (0 means up to end of file)
int skip (const int nevnts=0)
skip n events (0 means up to the end of file). Skip means read, don't process.
int fileopen (const char *managername="NONE", const char *filename="NONE")
int fileclose (const std::string &managername="")
int SegmentNumber ()
int ResetNodeTree ()
int BranchSelect (const char *managername, const char *branch, int iflag)
int BranchSelect (const char *branch, int iflag)
int setBranches (const char *managername)
int setBranches ()
virtual int DisconnectDB ()
virtual void identify (std::ostream &out=std::cout) const
unsigned GetTopNodes (std::vector< std::string > &names) const
void GetInputFullFileList (std::vector< std::string > &fnames) const
void GetOutputManagerList (std::vector< std::string > &names) const
void GetModuleList (std::vector< std::string > &names) const
Fun4AllSyncManager * getSyncManager (const std::string &name="DefaultSyncManager")
int registerSyncManager (Fun4AllSyncManager *newmaster)
int retcodestats (const int iret)
void EventNumber (const int evtno)
void NodeIdentify (const std::string &name)
void KeepDBConnection (const int i=1)
void PrintTimer (const std::string &name="")
void ReadSpillTimer (double &time_subsys, double &time_output)
void ResetSpillTimer ()
int getRun () const
int setRun (const int runno)
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static Fun4AllServer * instance ()
Protected Member Functions
Fun4AllServer (const std::string &name="Fun4AllServer")
int InitNodeTree (PHCompositeNode *topNode)
int CountOutNodes (PHCompositeNode *startNode)
int CountOutNodesRecursive (PHCompositeNode *startNode, const int icount)
int UpdateEventSelector (Fun4AllOutputManager *manager)
int unregisterSubsystemsNow ()
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
int OutNodeCount
int bortime_override
int ScreamEveryEvent
int unregistersubsystem
int runnumber
int eventnumber
std::vector< std::string > ComplaintList
PHCompositeNode * TopNode
std::vector< std::pair< SubsysReco *, PHCompositeNode * > > Subsystems
std::vector< std::pair< SubsysReco *, PHCompositeNode * > > DeleteSubsystems
std::vector< int > RetCodes
std::vector< Fun4AllOutputManager * > OutputManager
std::vector< TDirectory * > TDirCollection
Fun4AllHistoManager * ServerHistoManager
std::vector< Fun4AllHistoManager * > HistoManager
std::map< std::string, PHCompositeNode * > topnodemap
PHTimeStamp * beginruntimestamp
std::string default_Tdirectory
Fun4AllSyncManager * defaultSyncManager
std::vector< Fun4AllSyncManager * > SyncManagers
std::map< int, int > retcodesmap
std::map< const std::string, PHTimer2 > timer_map
PHTimer2 * timer_sp_subsys
Measure the time used by SubsysReco in process_event().
PHTimer2 * timer_sp_output
Measure the time used by OutputManager in process_event().
TH1 * FrameWorkVars
int keep_db_connected
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Static Protected Attributes
static Fun4AllServer * __instance = 0
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 24 of file Fun4AllServer.h.
Constructor & Destructor Documentation
~Fun4AllServer()
Fun4AllServer::~Fun4AllServer () virtual
Definition at line 70 of file Fun4AllServer.cc.
References __instance, beginruntimestamp, HistoManager, recoConsts::instance(), OutputManager, Reset(), Subsystems, SyncManagers, TDirCollection, timer_sp_output, timer_sp_subsys, topnodemap, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_MORE.
Fun4AllServer()
Fun4AllServer::Fun4AllServer (const std::string & name = "Fun4AllServer") protected
Definition at line 53 of file Fun4AllServer.cc.
References InitAll().
Member Function Documentation
AddComplaint()
int Fun4AllServer::AddComplaint (const std::string & complaint, const std::string & remedy)
Definition at line 356 of file Fun4AllServer.cc.
References ComplaintList, and ScreamEveryEvent.
AddTopNode()
int Fun4AllServer::AddTopNode (const std::string & name)
Definition at line 1261 of file Fun4AllServer.cc.
References topnodemap.
Referenced by topNode().
BeginRun()
int Fun4AllServer::BeginRun (const int runno) virtual
Definition at line 785 of file Fun4AllServer.cc.
References Fun4AllReturnCodes::ABORTRUN, beginruntimestamp, bortime_override, default_Tdirectory, DisconnectDB(), Fun4AllReturnCodes::EVENT_OK, keep_db_connected, PHWHERE, PHTimeStamp::print(), Print(), Subsystems, unregistersubsystem, unregisterSubsystemsNow(), Fun4AllBase::verbosity, Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_SOME.
Referenced by run().
BeginRunTimeStamp()
int Fun4AllServer::BeginRunTimeStamp (PHTimeStamp & TimeStp)
Definition at line 775 of file Fun4AllServer.cc.
References beginruntimestamp, bortime_override, and PHTimeStamp::print().
BranchSelect() [1/2]
int Fun4AllServer::BranchSelect (const char * branch, int iflag)
Definition at line 1506 of file Fun4AllServer.cc.
References SyncManagers.
BranchSelect() [2/2]
int Fun4AllServer::BranchSelect (const char * managername, const char * branch, int iflag)
Definition at line 1495 of file Fun4AllServer.cc.
References SyncManagers.
CountOutNodes()
int Fun4AllServer::CountOutNodes (PHCompositeNode * startNode) protected
Definition at line 898 of file Fun4AllServer.cc.
References CountOutNodesRecursive().
Referenced by process_event().
CountOutNodesRecursive()
int Fun4AllServer::CountOutNodesRecursive (PHCompositeNode * startNode, const int icount) protected
Definition at line 905 of file Fun4AllServer.cc.
References PHNode::getName(), PHNode::getType(), PHNodeIterator::ls(), Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by CountOutNodes().
DisconnectDB()
int Fun4AllServer::DisconnectDB () virtual
Definition at line 1562 of file Fun4AllServer.cc.
Referenced by BeginRun().
DstEvents()
int Fun4AllServer::DstEvents () const
Definition at line 1312 of file Fun4AllServer.cc.
References defaultSyncManager, and Fun4AllSyncManager::TotalEvents().
dumpHistos()
int Fun4AllServer::dumpHistos (const std::string & filename = "", const std::string & openmode = "RECREATE")
Definition at line 163 of file Fun4AllServer.cc.
References HistoManager, ServerHistoManager, and Fun4AllHistoManager::setOutfileName().
End()
int Fun4AllServer::End () virtual
Definition at line 1018 of file Fun4AllServer.cc.
References ComplaintList, default_Tdirectory, EndRun(), PHNodeIterator::findFirst(), PHFlag::get_IntFlag(), recoConsts::instance(), outfileclose(), OutputManager, PHWHERE, ScreamEveryEvent, Subsystems, TopNode, Fun4AllBase::verbosity, Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_SOME.
EndRun()
int Fun4AllServer::EndRun (const int runno = 0) virtual
Definition at line 967 of file Fun4AllServer.cc.
References default_Tdirectory, PHWHERE, Subsystems, Fun4AllBase::verbosity, Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_MORE.
Referenced by End(), and run().
EventNumber()
void Fun4AllServer::EventNumber (const int evtno) inline
Definition at line 102 of file Fun4AllServer.h.
References eventnumber.
Referenced by Fun4AllSyncManager::CurrentEvent().
fileclose()
int Fun4AllServer::fileclose (const std::string & managername = "")
Definition at line 1539 of file Fun4AllServer.cc.
References SyncManagers.
fileopen()
int Fun4AllServer::fileopen (const char * managername = "NONE", const char * filename = "NONE")
Definition at line 1484 of file Fun4AllServer.cc.
References SyncManagers.
getHisto() [1/2]
TNamed * Fun4AllServer::getHisto (const std::string & hname) const
Definition at line 505 of file Fun4AllServer.cc.
References Fun4AllHistoManager::getHisto(), and ServerHistoManager.
getHisto() [2/2]
TNamed * Fun4AllServer::getHisto (const unsigned int ihisto) const
Definition at line 494 of file Fun4AllServer.cc.
References Fun4AllHistoManager::getHisto(), and ServerHistoManager.
getHistoManager()
Fun4AllHistoManager * Fun4AllServer::getHistoManager (const std::string & name)
Definition at line 453 of file Fun4AllServer.cc.
References HistoManager, Fun4AllBase::verbosity, Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_MORE.
getHistoName()
const char * Fun4AllServer::getHistoName (const unsigned int ihisto) const
Definition at line 500 of file Fun4AllServer.cc.
References Fun4AllHistoManager::getHistoName(), and ServerHistoManager.
GetInputFullFileList()
void Fun4AllServer::GetInputFullFileList (std::vector< std::string > & fnames) const
Definition at line 1556 of file Fun4AllServer.cc.
References defaultSyncManager, and Fun4AllSyncManager::GetInputFullFileList().
getInputManager()
Fun4AllInputManager * Fun4AllServer::getInputManager (const char * name)
Definition at line 1293 of file Fun4AllServer.cc.
References SyncManagers.
GetModuleList()
void Fun4AllServer::GetModuleList (std::vector< std::string > & names) const
Definition at line 1589 of file Fun4AllServer.cc.
References Subsystems.
getNode()
PHCompositeNode * Fun4AllServer::getNode (const char * name, const char * topnodename = "TOP")
Definition at line 1274 of file Fun4AllServer.cc.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and topNode().
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), and Fun4AllOscarInputManager::Fun4AllOscarInputManager().
getOutputManager()
Fun4AllOutputManager * Fun4AllServer::getOutputManager (const std::string & name)
Definition at line 434 of file Fun4AllServer.cc.
References OutputManager, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_EVEN_MORE.
GetOutputManagerList()
void Fun4AllServer::GetOutputManagerList (std::vector< std::string > & names) const
Definition at line 1578 of file Fun4AllServer.cc.
References OutputManager.
getRun()
int Fun4AllServer::getRun () const inline
Definition at line 110 of file Fun4AllServer.h.
References runnumber.
getSubsysReco()
SubsysReco * Fun4AllServer::getSubsysReco (const std::string & name)
Definition at line 338 of file Fun4AllServer.cc.
References Subsystems, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_EVEN_MORE.
getSyncManager()
Fun4AllSyncManager * Fun4AllServer::getSyncManager (const std::string & name = "DefaultSyncManager")
Definition at line 1620 of file Fun4AllServer.cc.
References defaultSyncManager, and SyncManagers.
GetTopNodes()
unsigned Fun4AllServer::GetTopNodes (std::vector< std::string > & names) const
Definition at line 1568 of file Fun4AllServer.cc.
References topnodemap.
identify()
void Fun4AllServer::identify (std::ostream & out = std::cout) const virtual
Definition at line 1202 of file Fun4AllServer.cc.
References Fun4AllBase::ThisName.
InitAll()
void Fun4AllServer::InitAll ()
Definition at line 130 of file Fun4AllServer.cc.
References default_Tdirectory, defaultSyncManager, FrameWorkVars, InitNodeTree(), Fun4AllBase::Name(), NFRAMEWORKBINS, registerHisto(), registerHistoManager(), ServerHistoManager, SyncManagers, timer_map, timer_sp_output, timer_sp_subsys, TopNode, and topnodemap.
Referenced by Fun4AllServer().
InitNodeTree()
int Fun4AllServer::InitNodeTree (PHCompositeNode * topNode) protected
Definition at line 1224 of file Fun4AllServer.cc.
References PHCompositeNode::addNode(), and topNode().
Referenced by InitAll(), and topNode().
instance()
Fun4AllServer * Fun4AllServer::instance () static
Definition at line 43 of file Fun4AllServer.cc.
Referenced by Fun4AllSyncManager::CurrentEvent(), PHG4GDMLUtility::Dump_GDML(), Fun4AllSRawEventInputManager::enable_E1039_translation(), Fun4AllDstInputManager::fileopen(), Fun4AllEVIOInputManager::Fun4AllEVIOInputManager(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), Fun4AllHitMatrixInputManager::Fun4AllHitMatrixInputManager(), Fun4AllOscarInputManager::Fun4AllOscarInputManager(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), Fun4AllRUSInputManager::Fun4AllRUSInputManager(), Fun4AllSRawEventInputManager::Fun4AllSRawEventInputManager(), Fun4AllTrackQAv1InputManager::Fun4AllTrackQAv1InputManager(), Fun4AllVectEventInputManager::Fun4AllVectEventInputManager(), PHFieldUtility::GetFieldConfigNode(), PHFieldUtility::GetFieldMapNode(), PHG4CylinderCellTPCReco::Init(), Fun4AllInputManager::registerSubsystem(), registerSubsystem(), Fun4AllInputManager::RejectEvent(), Fun4AllEVIOInputManager::run(), Fun4AllDstOutputManager::Write(), Fun4AllEventOutputManager::Write(), Fun4AllSpillDstOutputManager::Write(), and Fun4AllFileOutStream::WriteEventOut().
isHistoRegistered()
int Fun4AllServer::isHistoRegistered (const std::string & name) const virtual
Definition at line 189 of file Fun4AllServer.cc.
References Fun4AllHistoManager::isHistoRegistered(), and ServerHistoManager.
KeepDBConnection()
void Fun4AllServer::KeepDBConnection (const int i = 1) inline
Definition at line 104 of file Fun4AllServer.h.
References keep_db_connected.
makeHisto()
template<typename T > T* Fun4AllServer::makeHisto (T * t) inline
Definition at line 33 of file Fun4AllServer.h.
References Fun4AllHistoManager::makeHisto(), and ServerHistoManager.
MakeNodesPersistent()
int Fun4AllServer::MakeNodesPersistent (PHCompositeNode * startNode)
Definition at line 948 of file Fun4AllServer.cc.
References PHNode::getType(), PHNodeIterator::ls(), and PHNode::makePersistent().
Referenced by Fun4AllDstOutputManager::Write().
MakeNodesTransient()
int Fun4AllServer::MakeNodesTransient (PHCompositeNode * startNode)
Definition at line 929 of file Fun4AllServer.cc.
References PHNode::getType(), PHNodeIterator::ls(), and PHNode::makeTransient().
Referenced by process_event(), and Fun4AllDstOutputManager::Write().
NodeIdentify()
void Fun4AllServer::NodeIdentify (const std::string & name)
Definition at line 1661 of file Fun4AllServer.cc.
References PHObject::identify(), and TopNode.
outfileclose()
int Fun4AllServer::outfileclose ()
Definition at line 1208 of file Fun4AllServer.cc.
References Fun4AllBase::Name(), OutputManager, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_MORE.
Referenced by End().
PrdfEvents()
int Fun4AllServer::PrdfEvents () const
Definition at line 1307 of file Fun4AllServer.cc.
References defaultSyncManager, and Fun4AllSyncManager::PrdfEvents().
Print()
void Fun4AllServer::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 1109 of file Fun4AllServer.cc.
References HistoManager, Fun4AllBase::Name(), OutputManager, PHNodeIterator::print(), Fun4AllHistoManager::Print(), Fun4AllOutputManager::Print(), Fun4AllSyncManager::Print(), Subsystems, SyncManagers, and topnodemap.
Referenced by BeginRun().
PrintTimer()
void Fun4AllServer::PrintTimer (const std::string & name = "")
Definition at line 1676 of file Fun4AllServer.cc.
References timer_map.
process_event() [1/2]
int Fun4AllServer::process_event () virtual
Definition at line 516 of file Fun4AllServer.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, ComplaintList, CountOutNodes(), default_Tdirectory, Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), MakeNodesTransient(), Fun4AllBase::Name(), OutNodeCount, OutputManager, PHWHERE, PHNodeIterator::print(), Fun4AllSyncManager::ResetEvent(), ResetNodeTree(), PHTimer2::restart(), RetCodes, retcodesmap, ScreamEveryEvent, PHTimer2::stop(), Subsystems, SyncManagers, timer_map, timer_sp_output, timer_sp_subsys, TopNode, unregistersubsystem, unregisterSubsystemsNow(), Fun4AllBase::verbosity, Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_MORE.
Referenced by process_event(), and run().
process_event() [2/2]
int Fun4AllServer::process_event (PHCompositeNode * topNode)
Definition at line 510 of file Fun4AllServer.cc.
References process_event().
ReadSpillTimer()
void Fun4AllServer::ReadSpillTimer (double & time_subsys, double & time_output)
Definition at line 1706 of file Fun4AllServer.cc.
References PHTimer2::get_accumulated_time(), timer_sp_output, and timer_sp_subsys.
Referenced by Fun4AllEVIOInputManager::run().
registerHisto() [1/2]
bool Fun4AllServer::registerHisto (const char * hname, TNamed * h1d, const int replace = 0) virtual
Definition at line 184 of file Fun4AllServer.cc.
References Fun4AllHistoManager::registerHisto(), and ServerHistoManager.
Referenced by PHG4CylinderCellTPCReco::Init(), and InitAll().
registerHisto() [2/2]
bool Fun4AllServer::registerHisto (TNamed * h1d, const int replace = 0) virtual
Definition at line 179 of file Fun4AllServer.cc.
References Fun4AllHistoManager::registerHisto(), and ServerHistoManager.
registerHistoManager()
int Fun4AllServer::registerHistoManager (Fun4AllHistoManager * manager)
Definition at line 474 of file Fun4AllServer.cc.
References HistoManager, Fun4AllBase::Name(), Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_SOME.
Referenced by InitAll().
registerInputManager()
int Fun4AllServer::registerInputManager (Fun4AllInputManager * InManager)
Definition at line 1286 of file Fun4AllServer.cc.
References defaultSyncManager, and Fun4AllSyncManager::registerInputManager().
registerOutputManager()
int Fun4AllServer::registerOutputManager (Fun4AllOutputManager * manager)
Definition at line 373 of file Fun4AllServer.cc.
References Fun4AllBase::Name(), OutputManager, UpdateEventSelector(), Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_SOME.
registerSubsystem()
int Fun4AllServer::registerSubsystem (SubsysReco * subsystem, const std::string & topnodename = "TOP")
Definition at line 195 of file Fun4AllServer.cc.
References default_Tdirectory, Fun4AllReturnCodes::DONOTREGISTERSUBSYSTEM, SubsysReco::Init(), instance(), Fun4AllBase::Name(), PHWHERE, RetCodes, Subsystems, TDirCollection, timer_map, topNode(), Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_SOME.
registerSyncManager()
int Fun4AllServer::registerSyncManager (Fun4AllSyncManager * newmaster)
Definition at line 1600 of file Fun4AllServer.cc.
References Fun4AllBase::Name(), SyncManagers, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_SOME.
Reset()
int Fun4AllServer::Reset ()
Definition at line 755 of file Fun4AllServer.cc.
References HistoManager, Subsystems, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by ~Fun4AllServer().
ResetNodeTree()
int Fun4AllServer::ResetNodeTree ()
Definition at line 732 of file Fun4AllServer.cc.
References PHNodeIterator::cd(), PHNodeIterator::forEach(), topnodemap, Fun4AllBase::verbosity, and PHNodeOperation::Verbosity().
Referenced by process_event(), and run().
ResetSpillTimer()
void Fun4AllServer::ResetSpillTimer ()
Definition at line 1712 of file Fun4AllServer.cc.
References PHTimer2::reset(), timer_sp_output, and timer_sp_subsys.
Referenced by Fun4AllEVIOInputManager::run().
retcodestats()
int Fun4AllServer::retcodestats (const int iret) inline
Definition at line 101 of file Fun4AllServer.h.
References retcodesmap.
run()
int Fun4AllServer::run (const int nevnts = 0, const bool require_nevents = false)
run n events (0 means up to end of file)
Definition at line 1318 of file Fun4AllServer.cc.
References Fun4AllReturnCodes::ABORTEVENT, BeginRun(), EndRun(), PHFlag::FlagExist(), PHFlag::get_IntFlag(), recoConsts::instance(), process_event(), ResetNodeTree(), RetCodes, runnumber, setRun(), SyncManagers, Fun4AllBase::verbosity, Fun4AllBase::VERBOSITY_MORE, Fun4AllBase::VERBOSITY_QUIET, and Fun4AllBase::VERBOSITY_SOME.
SegmentNumber()
int Fun4AllServer::SegmentNumber ()
Definition at line 1550 of file Fun4AllServer.cc.
References defaultSyncManager, and Fun4AllSyncManager::SegmentNumber().
Referenced by Fun4AllFileOutStream::WriteEventOut().
setBranches() [1/2]
int Fun4AllServer::setBranches ()
Definition at line 1528 of file Fun4AllServer.cc.
References SyncManagers.
setBranches() [2/2]
int Fun4AllServer::setBranches (const char * managername)
Definition at line 1517 of file Fun4AllServer.cc.
References SyncManagers.
setRun()
int Fun4AllServer::setRun (const int runno)
This function sets RUNNUMBER via recoConsts.
Definition at line 1642 of file Fun4AllServer.cc.
References FrameWorkVars, recoConsts::instance(), runnumber, RUNNUMBERBIN, and PHFlag::set_IntFlag().
Referenced by run().
skip()
int Fun4AllServer::skip (const int nevnts = 0)
skip n events (0 means up to the end of file). Skip means read, don't process.
Definition at line 1472 of file Fun4AllServer.cc.
References SyncManagers.
topNode() [1/2]
PHCompositeNode* Fun4AllServer::topNode () const inline
Definition at line 59 of file Fun4AllServer.h.
References TopNode.
Referenced by PHG4GDMLUtility::Dump_GDML(), Fun4AllSRawEventInputManager::enable_E1039_translation(), Fun4AllEVIOInputManager::Fun4AllEVIOInputManager(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), Fun4AllHitMatrixInputManager::Fun4AllHitMatrixInputManager(), Fun4AllOscarInputManager::Fun4AllOscarInputManager(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), Fun4AllRUSInputManager::Fun4AllRUSInputManager(), Fun4AllSRawEventInputManager::Fun4AllSRawEventInputManager(), Fun4AllTrackQAv1InputManager::Fun4AllTrackQAv1InputManager(), Fun4AllVectEventInputManager::Fun4AllVectEventInputManager(), PHFieldUtility::GetFieldConfigNode(), PHFieldUtility::GetFieldMapNode(), getNode(), InitNodeTree(), Fun4AllInputManager::registerSubsystem(), registerSubsystem(), Fun4AllInputManager::RejectEvent(), and Fun4AllEventOutputManager::Write().
topNode() [2/2]
PHCompositeNode * Fun4AllServer::topNode (const std::string & name)
Definition at line 1237 of file Fun4AllServer.cc.
References AddTopNode(), InitNodeTree(), PHWHERE, and topnodemap.
unregisterSubsystem()
int Fun4AllServer::unregisterSubsystem (SubsysReco * subsystem)
Definition at line 283 of file Fun4AllServer.cc.
References DeleteSubsystems, and unregistersubsystem.
unregisterSubsystemsNow()
int Fun4AllServer::unregisterSubsystemsNow () protected
Definition at line 291 of file Fun4AllServer.cc.
References DeleteSubsystems, OutputManager, RetCodes, Subsystems, unregistersubsystem, UpdateEventSelector(), Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_MORE.
Referenced by BeginRun(), and process_event().
UpdateEventSelector()
int Fun4AllServer::UpdateEventSelector (Fun4AllOutputManager * manager) protected
Definition at line 393 of file Fun4AllServer.cc.
References Fun4AllOutputManager::EventSelector(), PHWHERE, Fun4AllOutputManager::RecoModuleIndex(), Subsystems, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by registerOutputManager(), and unregisterSubsystemsNow().
Member Data Documentation
__instance
Fun4AllServer * Fun4AllServer::__instance = 0 static protected
Definition at line 120 of file Fun4AllServer.h.
Referenced by ~Fun4AllServer().
beginruntimestamp
PHTimeStamp* Fun4AllServer::beginruntimestamp protected
Definition at line 137 of file Fun4AllServer.h.
Referenced by BeginRun(), BeginRunTimeStamp(), and ~Fun4AllServer().
bortime_override
int Fun4AllServer::bortime_override protected
Definition at line 122 of file Fun4AllServer.h.
Referenced by BeginRun(), and BeginRunTimeStamp().
ComplaintList
std::vector<std::string> Fun4AllServer::ComplaintList protected
Definition at line 127 of file Fun4AllServer.h.
Referenced by AddComplaint(), End(), and process_event().
default_Tdirectory
std::string Fun4AllServer::default_Tdirectory protected
Definition at line 138 of file Fun4AllServer.h.
Referenced by BeginRun(), End(), EndRun(), InitAll(), process_event(), and registerSubsystem().
defaultSyncManager
Fun4AllSyncManager* Fun4AllServer::defaultSyncManager protected
Definition at line 139 of file Fun4AllServer.h.
Referenced by DstEvents(), GetInputFullFileList(), getSyncManager(), InitAll(), PrdfEvents(), registerInputManager(), and SegmentNumber().
DeleteSubsystems
std::vector<std::pair<SubsysReco *, PHCompositeNode *> > Fun4AllServer::DeleteSubsystems protected
Definition at line 130 of file Fun4AllServer.h.
Referenced by unregisterSubsystem(), and unregisterSubsystemsNow().
eventnumber
int Fun4AllServer::eventnumber protected
Definition at line 126 of file Fun4AllServer.h.
Referenced by EventNumber().
FrameWorkVars
TH1* Fun4AllServer::FrameWorkVars protected
Definition at line 147 of file Fun4AllServer.h.
Referenced by InitAll(), and setRun().
HistoManager
std::vector<Fun4AllHistoManager *> Fun4AllServer::HistoManager protected
Definition at line 135 of file Fun4AllServer.h.
Referenced by dumpHistos(), getHistoManager(), Print(), registerHistoManager(), Reset(), and ~Fun4AllServer().
keep_db_connected
int Fun4AllServer::keep_db_connected protected
Definition at line 148 of file Fun4AllServer.h.
Referenced by BeginRun(), and KeepDBConnection().
OutNodeCount
int Fun4AllServer::OutNodeCount protected
Definition at line 121 of file Fun4AllServer.h.
Referenced by process_event().
OutputManager
std::vector<Fun4AllOutputManager *> Fun4AllServer::OutputManager protected
Definition at line 132 of file Fun4AllServer.h.
Referenced by End(), getOutputManager(), GetOutputManagerList(), outfileclose(), Print(), process_event(), registerOutputManager(), unregisterSubsystemsNow(), and ~Fun4AllServer().
RetCodes
std::vector<int> Fun4AllServer::RetCodes protected
Definition at line 131 of file Fun4AllServer.h.
Referenced by process_event(), registerSubsystem(), run(), and unregisterSubsystemsNow().
retcodesmap
std::map<int, int> Fun4AllServer::retcodesmap protected
Definition at line 141 of file Fun4AllServer.h.
Referenced by process_event(), and retcodestats().
runnumber
int Fun4AllServer::runnumber protected
Definition at line 125 of file Fun4AllServer.h.
Referenced by getRun(), run(), and setRun().
ScreamEveryEvent
int Fun4AllServer::ScreamEveryEvent protected
Definition at line 123 of file Fun4AllServer.h.
Referenced by AddComplaint(), End(), and process_event().
ServerHistoManager
Fun4AllHistoManager* Fun4AllServer::ServerHistoManager protected
Definition at line 134 of file Fun4AllServer.h.
Referenced by dumpHistos(), getHisto(), getHistoName(), InitAll(), isHistoRegistered(), makeHisto(), and registerHisto().
Subsystems
std::vector<std::pair<SubsysReco *, PHCompositeNode *> > Fun4AllServer::Subsystems protected
Definition at line 129 of file Fun4AllServer.h.
Referenced by BeginRun(), End(), EndRun(), GetModuleList(), getSubsysReco(), Print(), process_event(), registerSubsystem(), Reset(), unregisterSubsystemsNow(), UpdateEventSelector(), and ~Fun4AllServer().
SyncManagers
std::vector<Fun4AllSyncManager *> Fun4AllServer::SyncManagers protected
Definition at line 140 of file Fun4AllServer.h.
Referenced by BranchSelect(), fileclose(), fileopen(), getInputManager(), getSyncManager(), InitAll(), Print(), process_event(), registerSyncManager(), run(), setBranches(), skip(), and ~Fun4AllServer().
TDirCollection
std::vector<TDirectory *> Fun4AllServer::TDirCollection protected
Definition at line 133 of file Fun4AllServer.h.
Referenced by registerSubsystem(), and ~Fun4AllServer().
timer_map
std::map<const std::string, PHTimer2> Fun4AllServer::timer_map protected
Definition at line 143 of file Fun4AllServer.h.
Referenced by InitAll(), PrintTimer(), process_event(), and registerSubsystem().
timer_sp_output
PHTimer2* Fun4AllServer::timer_sp_output protected
Measure the time used by OutputManager in process_event().
Definition at line 145 of file Fun4AllServer.h.
Referenced by InitAll(), process_event(), ReadSpillTimer(), ResetSpillTimer(), and ~Fun4AllServer().
timer_sp_subsys
PHTimer2* Fun4AllServer::timer_sp_subsys protected
Measure the time used by SubsysReco in process_event().
Definition at line 144 of file Fun4AllServer.h.
Referenced by InitAll(), process_event(), ReadSpillTimer(), ResetSpillTimer(), and ~Fun4AllServer().
TopNode
PHCompositeNode* Fun4AllServer::TopNode protected
Definition at line 128 of file Fun4AllServer.h.
Referenced by End(), InitAll(), NodeIdentify(), process_event(), and topNode().
topnodemap
std::map<std::string, PHCompositeNode *> Fun4AllServer::topnodemap protected
Definition at line 136 of file Fun4AllServer.h.
Referenced by AddTopNode(), GetTopNodes(), InitAll(), Print(), ResetNodeTree(), topNode(), and ~Fun4AllServer().
unregistersubsystem
int Fun4AllServer::unregistersubsystem protected
Definition at line 124 of file Fun4AllServer.h.
Referenced by BeginRun(), process_event(), unregisterSubsystem(), and unregisterSubsystemsNow().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/fun4all/Fun4AllServer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/fun4all/Fun4AllServer.cc