Class Reference for E1039 Core & Analysis Software: NMREvent Class Reference
NMREvent Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaNMRData/NMREvent.h>
Public Member Functions
NMREvent ()
virtual ~NMREvent ()
std::string GetLine ()
void SetLine (const std::string line)
std::string GetString (const int idx)
int GetInt (const int idx)
double GetDouble (const int idx)
std::string GetString (const std::string key)
int GetInt (const std::string key)
double GetDouble (const std::string key)
void AddValue (const std::string value)
void ClearValue ()
Static Public Member Functions
static int GetNumKey ()
static std::string GetKey (const int idx)
static void AddKey (const std::string key)
static int FindKey (const std::string key)
Detailed Description
Definition at line 4 of file NMREvent.h.
Constructor & Destructor Documentation
NMREvent()
NMREvent::NMREvent () inline
Definition at line 11 of file NMREvent.h.
~NMREvent()
virtual NMREvent::~NMREvent () inline virtual
Definition at line 12 of file NMREvent.h.
Member Function Documentation
AddKey()
void NMREvent::AddKey (const std::string key) static
Definition at line 37 of file NMREvent.h.
Referenced by NMRDataManager::ReadEventFile().
AddValue()
void NMREvent::AddValue (const std::string value) inline
Definition at line 30 of file NMREvent.h.
Referenced by NMRDataManager::ReadEventFile().
ClearValue()
void NMREvent::ClearValue () inline
Definition at line 31 of file NMREvent.h.
FindKey()
int NMREvent::FindKey (const std::string key) static
Definition at line 43 of file NMREvent.h.
Referenced by NMRDataManager::FindEvent(), GetDouble(), GetInt(), and GetString().
GetDouble() [1/2]
double NMREvent::GetDouble (const int idx) inline
Definition at line 24 of file NMREvent.h.
Referenced by ana_NMR_event(), and NMRDataManager::GetScanParam().
GetDouble() [2/2]
double NMREvent::GetDouble (const std::string key) inline
Definition at line 28 of file NMREvent.h.
References FindKey(), and GetDouble().
Referenced by GetDouble().
GetInt() [1/2]
int NMREvent::GetInt (const int idx) inline
Definition at line 23 of file NMREvent.h.
Referenced by ana_NMR_event(), ana_NMR_noise(), ana_NMR_poly_signal(), ana_NMR_raw_signal(), NMRDataManager::FindEvent(), and NMRDataManager::GetScanParam().
GetInt() [2/2]
int NMREvent::GetInt (const std::string key) inline
Definition at line 27 of file NMREvent.h.
References FindKey(), and GetInt().
Referenced by GetInt().
GetKey()
static std::string NMREvent::GetKey (const int idx) inline static
Definition at line 15 of file NMREvent.h.
Referenced by NMRDataManager::PrintKeyList(), and NMRDataManager::ReadEventFile().
GetLine()
std::string NMREvent::GetLine () inline
Definition at line 19 of file NMREvent.h.
GetNumKey()
static int NMREvent::GetNumKey () inline static
Definition at line 14 of file NMREvent.h.
Referenced by NMRDataManager::PrintKeyList(), and NMRDataManager::ReadEventFile().
GetString() [1/2]
std::string NMREvent::GetString (const int idx) inline
Definition at line 22 of file NMREvent.h.
Referenced by ana_NMR_event().
GetString() [2/2]
std::string NMREvent::GetString (const std::string key) inline
Definition at line 26 of file NMREvent.h.
References FindKey(), and GetString().
Referenced by GetString().
SetLine()
void NMREvent::SetLine (const std::string line) inline
Definition at line 20 of file NMREvent.h.
Referenced by NMRDataManager::ReadEventFile().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaNMRData/NMREvent.h