Class Reference for E1039 Core & Analysis Software: UtilHodo2::Track2D Struct Reference
UtilHodo2::Track2D Struct Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaRealDst/src/UtilHodo2.h>
Public Member Functions
Track2D ()
~Track2D ()
void AddHit (SQHit *hit)
void AddChamberHit (SQHit *hit)
void AddPropTubeHit (SQHit *hit)
int DoTracking ()
TGraph * GetGraphX ()
TGraph * GetGraphY ()
int GetNDF ()
double GetChi2 ()
TVector3 GetPos0 ()
TVector3 GetSlope ()
TVector3 GetPos (const double z)
Public Attributes
Track1D trk_x
Track1D trk_y
Detailed Description
Definition at line 32 of file UtilHodo2.h.
Constructor & Destructor Documentation
UtilHodo2::Track2D::Track2D ()
Definition at line 83 of file UtilHodo2.cc.
UtilHodo2::Track2D::~Track2D () inline
Definition at line 37 of file UtilHodo2.h.
Member Function Documentation
void UtilHodo2::Track2D::AddChamberHit (SQHit * hit)
Definition at line 94 of file UtilHodo2.cc.
References SQHit::get_detector_id(), GeomSvc::getDetectorName(), GeomSvc::instance(), UtilHodo2::Track1D::list_hit, and trk_x.
Referenced by AnaEffHodo::process_event().
void UtilHodo2::Track2D::AddHit (SQHit * hit)
Definition at line 88 of file UtilHodo2.cc.
References SQHit::get_detector_id(), UtilHodo2::IsHodoX(), UtilHodo2::Track1D::list_hit, trk_x, and trk_y.
Referenced by AnaEffHodo::process_event().
void UtilHodo2::Track2D::AddPropTubeHit (SQHit * hit)
Definition at line 108 of file UtilHodo2.cc.
References SQHit::get_detector_id(), GeomSvc::getDetectorName(), GeomSvc::instance(), UtilHodo2::Track1D::list_hit, trk_x, and trk_y.
Referenced by AnaEffHodo::process_event().
int UtilHodo2::Track2D::DoTracking ()
Definition at line 119 of file UtilHodo2.cc.
References UtilHodo2::Track1D::DoTracking(), trk_x, and trk_y.
Referenced by AnaEffHodo::process_event().
double UtilHodo2::Track2D::GetChi2 ()
Definition at line 141 of file UtilHodo2.cc.
References UtilHodo2::Track1D::chi2, trk_x, and trk_y.
Referenced by AnaEffHodo::process_event().
TGraph * UtilHodo2::Track2D::GetGraphX ()
Definition at line 126 of file UtilHodo2.cc.
References UtilHodo2::Track1D::graph, and trk_x.
TGraph * UtilHodo2::Track2D::GetGraphY ()
Definition at line 131 of file UtilHodo2.cc.
References UtilHodo2::Track1D::graph, and trk_y.
int UtilHodo2::Track2D::GetNDF ()
Definition at line 136 of file UtilHodo2.cc.
References UtilHodo2::Track1D::ndf, trk_x, and trk_y.
Referenced by AnaEffHodo::process_event().
TVector3 UtilHodo2::Track2D::GetPos (const double z)
Definition at line 156 of file UtilHodo2.cc.
References GetPos0(), and GetSlope().
Referenced by AnaEffHodo::process_event().
TVector3 UtilHodo2::Track2D::GetPos0 ()
Definition at line 146 of file UtilHodo2.cc.
References UtilHodo2::Track1D::pos, trk_x, and trk_y.
Referenced by GetPos(), and AnaEffHodo::process_event().
TVector3 UtilHodo2::Track2D::GetSlope ()
Definition at line 151 of file UtilHodo2.cc.
References UtilHodo2::Track1D::slope, trk_x, and trk_y.
Referenced by GetPos(), and AnaEffHodo::process_event().
Member Data Documentation
Track1D UtilHodo2::Track2D::trk_x
Definition at line 33 of file UtilHodo2.h.
Referenced by AddChamberHit(), AddHit(), AddPropTubeHit(), DoTracking(), GetChi2(), GetGraphX(), GetNDF(), GetPos0(), and GetSlope().
Track1D UtilHodo2::Track2D::trk_y
Definition at line 34 of file UtilHodo2.h.
Referenced by AddHit(), AddPropTubeHit(), DoTracking(), GetChi2(), GetGraphY(), GetNDF(), GetPos0(), and GetSlope().
The documentation for this struct was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaRealDst/src/UtilHodo2.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaRealDst/src/UtilHodo2.cc