Class Reference for E1039 Core & Analysis Software: SQG4DipoleMagnetDetector Class Reference
SQG4DipoleMagnetDetector Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/SQG4DipoleMagnetDetector.h>
Public Member Functions
SQG4DipoleMagnetDetector (PHCompositeNode *node, PHParameters *parameters, const std::string &dnam="BLOCK", const int lyr=0)
constructor
virtual ~SQG4DipoleMagnetDetector (void)
destructor
virtual void Construct (G4LogicalVolume *world)
construct
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
volume accessors
bool IsInBlock (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 22 of file SQG4DipoleMagnetDetector.h.
Constructor & Destructor Documentation
SQG4DipoleMagnetDetector::SQG4DipoleMagnetDetector (PHCompositeNode * node, PHParameters * parameters, const std::string & dnam = "BLOCK", const int lyr = 0)
constructor
Definition at line 29 of file SQG4DipoleMagnetDetector.cc.
SQG4DipoleMagnetDetector::~SQG4DipoleMagnetDetector (void) virtual
destructor
Definition at line 36 of file SQG4DipoleMagnetDetector.cc.
Member Function Documentation
void SQG4DipoleMagnetDetector::Construct (G4LogicalVolume * world) virtual
construct
Read all box shapes from Table SolidBoxes
Read all tube shapes from Table SolidTubes
Perform subtraction using Table SubtractionSolids
Implements PHG4Detector.
Definition at line 47 of file SQG4DipoleMagnetDetector.cc.
References PHParameters::get_double_param(), PHParameters::get_string_param(), DbSvc::LITE, PHG4Detector::overlapcheck, DbSvc::Process(), and PHG4Detector::Verbosity().
int SQG4DipoleMagnetDetector::get_Layer () const inline
Definition at line 41 of file SQG4DipoleMagnetDetector.h.
bool SQG4DipoleMagnetDetector::IsInBlock (G4VPhysicalVolume * volume) const
Definition at line 38 of file SQG4DipoleMagnetDetector.cc.
Referenced by SQG4DipoleMagnetSteppingAction::UserSteppingAction().
void SQG4DipoleMagnetDetector::SuperDetector (const std::string & name) inline
Definition at line 39 of file SQG4DipoleMagnetDetector.h.
References PHG4Detector::name.
Referenced by SQG4DipoleMagnetSubsystem::InitRunSubsystem().
const std::string SQG4DipoleMagnetDetector::SuperDetector () const inline
Definition at line 40 of file SQG4DipoleMagnetDetector.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/SQG4DipoleMagnetDetector.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/SQG4DipoleMagnetDetector.cc