Class Reference for E1039 Core & Analysis Software: FitRTDist Class Reference
FitRTDist Class Reference
Class for fitting R-T histogram.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/FitRTDist.h>
Public Member Functions
FitRTDist ()
virtual ~FitRTDist ()
void FixT1T0 (const double t1, const double t0)
int DoFit (const int n_pt, TH2 *h2, double r_max, TGraph *gr_init, RTCurve *rtc)
void Verbosity (const int verb)
int Verbosity () const
Static Public Member Functions
static double FCN (const double *xx)
static void CalcChi2 (const double *pars, double &chi2, int &ndf)
Protected Attributes
bool m_fix_t1t0
double m_t1
Fixed T1 value. Valid only when m_fix_t1t0 = true.
double m_t0
Fixed T0 value. Valid only when m_fix_t1t0 = true.
int m_verb
Static Protected Attributes
static int m_n_pt = 0
N of R-T points.
static int m_n_par = 0
N of free parameters.
static TH2 * m_h2_RT = 0
static double m_t_min = 0
static double m_t_max = 0
static double m_r_max = 0
Detailed Description
Class for fitting R-T histogram.
Definition at line 9 of file FitRTDist.h.
Constructor & Destructor Documentation
FitRTDist()
FitRTDist::FitRTDist ()
Definition at line 21 of file FitRTDist.cc.
~FitRTDist()
FitRTDist::~FitRTDist () virtual
Definition at line 30 of file FitRTDist.cc.
Member Function Documentation
CalcChi2()
void FitRTDist::CalcChi2 (const double * pars, double & chi2, int & ndf) static
N of parameters = m_n_pt + 1 pars[0] = T1 [1] = T0 [2] = DR (constant over T) [3]...[m_n_pt] = R at each non-edge T points
Note that the T position of each point is not fixed but depends on T1 & T0.
Definition at line 52 of file FitRTDist.cc.
References RTCurve::EvalR(), RTCurve::GetRWidth(), m_h2_RT, m_n_par, and m_n_pt.
Referenced by DoFit(), and FCN().
DoFit()
int FitRTDist::DoFit (const int n_pt, TH2 * h2, double r_max, TGraph * gr_init, RTCurve * rtc)
Definition at line 88 of file FitRTDist.cc.
References CalcChi2(), FCN(), m_fix_t1t0, m_h2_RT, m_n_par, m_n_pt, m_r_max, m_t0, m_t1, m_t_max, m_t_min, and m_verb.
Referenced by MakeRTCurve::ExtractRT(), and SRMakeRTCurve::ExtractRT().
FCN()
double FitRTDist::FCN (const double * xx) static
Definition at line 35 of file FitRTDist.cc.
References CalcChi2().
Referenced by DoFit().
FixT1T0()
void FitRTDist::FixT1T0 (const double t1, const double t0)
Definition at line 81 of file FitRTDist.cc.
References m_fix_t1t0, m_t0, and m_t1.
Referenced by MakeRTCurve::ExtractRT(), and SRMakeRTCurve::ExtractRT().
Verbosity() [1/2]
int FitRTDist::Verbosity () const inline
Definition at line 35 of file FitRTDist.h.
References m_verb.
Verbosity() [2/2]
void FitRTDist::Verbosity (const int verb) inline
Definition at line 34 of file FitRTDist.h.
References m_verb.
Referenced by MakeRTCurve::ExtractRT(), and SRMakeRTCurve::ExtractRT().
Member Data Documentation
m_fix_t1t0
bool FitRTDist::m_fix_t1t0 protected
Definition at line 11 of file FitRTDist.h.
Referenced by DoFit(), and FixT1T0().
m_h2_RT
TH2 * FitRTDist::m_h2_RT = 0 static protected
Definition at line 17 of file FitRTDist.h.
Referenced by CalcChi2(), and DoFit().
m_n_par
int FitRTDist::m_n_par = 0 static protected
N of free parameters.
Definition at line 16 of file FitRTDist.h.
Referenced by CalcChi2(), and DoFit().
m_n_pt
int FitRTDist::m_n_pt = 0 static protected
N of R-T points.
Definition at line 15 of file FitRTDist.h.
Referenced by CalcChi2(), and DoFit().
m_r_max
double FitRTDist::m_r_max = 0 static protected
Definition at line 20 of file FitRTDist.h.
Referenced by DoFit().
m_t0
double FitRTDist::m_t0 protected
Fixed T0 value. Valid only when m_fix_t1t0 = true.
Definition at line 13 of file FitRTDist.h.
Referenced by DoFit(), and FixT1T0().
m_t1
double FitRTDist::m_t1 protected
Fixed T1 value. Valid only when m_fix_t1t0 = true.
Definition at line 12 of file FitRTDist.h.
Referenced by DoFit(), and FixT1T0().
m_t_max
double FitRTDist::m_t_max = 0 static protected
Definition at line 19 of file FitRTDist.h.
Referenced by DoFit().
m_t_min
double FitRTDist::m_t_min = 0 static protected
Definition at line 18 of file FitRTDist.h.
Referenced by DoFit().
m_verb
int FitRTDist::m_verb protected
Definition at line 22 of file FitRTDist.h.
Referenced by DoFit(), and Verbosity().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/FitRTDist.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/FitRTDist.cc