E1039 Software: PHG4BlockSteppingAction Class Reference
PHG4BlockSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4BlockSteppingAction.h>
Public Member Functions
PHG4BlockSteppingAction (PHG4BlockDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4BlockSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4BlockDetector * detector_
pointer to the detector
const PHParameters * params
PHG4HitContainer * hits_
pointer to hit container
PHG4Hit * hit
PHG4Shower * saveshower
G4VPhysicalVolume * savevolpre
G4VPhysicalVolume * savevolpost
int savetrackid
int saveprestepstatus
int savepoststepstatus
int active
int IsBlackHole
int use_g4_steps
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 13 of file PHG4BlockSteppingAction.h.
Constructor & Destructor Documentation
PHG4BlockSteppingAction()
PHG4BlockSteppingAction::PHG4BlockSteppingAction (PHG4BlockDetector * detector, const PHParameters * parameters)
constructor
Definition at line 22 of file PHG4BlockSteppingAction.cc.
~PHG4BlockSteppingAction()
PHG4BlockSteppingAction::~PHG4BlockSteppingAction () virtual
destructor
Definition at line 39 of file PHG4BlockSteppingAction.cc.
References hit.
Member Function Documentation
SetInterfacePointers()
void PHG4BlockSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 256 of file PHG4BlockSteppingAction.cc.
References detector_, PHG4Detector::GetName(), hits_, and PHG4BlockDetector::SuperDetector().
UserSteppingAction()
bool PHG4BlockSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 49 of file PHG4BlockSteppingAction.cc.
References active, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4BlockDetector::get_Layer(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), hit, hits_, IsBlackHole, PHG4BlockDetector::IsInBlock(), PHG4Hit::Reset(), savepoststepstatus, saveprestepstatus, saveshower, savetrackid, savevolpost, savevolpre, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and use_g4_steps.
Member Data Documentation
active
int PHG4BlockSteppingAction::active private
Definition at line 41 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
detector_
PHG4BlockDetector* PHG4BlockSteppingAction::detector_ private
pointer to the detector
Definition at line 30 of file PHG4BlockSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
hit
PHG4Hit* PHG4BlockSteppingAction::hit private
Definition at line 34 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4BlockSteppingAction().
hits_
PHG4HitContainer* PHG4BlockSteppingAction::hits_ private
pointer to hit container
Definition at line 33 of file PHG4BlockSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
IsBlackHole
int PHG4BlockSteppingAction::IsBlackHole private
Definition at line 42 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
params
const PHParameters* PHG4BlockSteppingAction::params private
Definition at line 31 of file PHG4BlockSteppingAction.h.
savepoststepstatus
int PHG4BlockSteppingAction::savepoststepstatus private
Definition at line 40 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
saveprestepstatus
int PHG4BlockSteppingAction::saveprestepstatus private
Definition at line 39 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
saveshower
PHG4Shower* PHG4BlockSteppingAction::saveshower private
Definition at line 35 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
savetrackid
int PHG4BlockSteppingAction::savetrackid private
Definition at line 38 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
savevolpost
G4VPhysicalVolume* PHG4BlockSteppingAction::savevolpost private
Definition at line 37 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
savevolpre
G4VPhysicalVolume* PHG4BlockSteppingAction::savevolpre private
Definition at line 36 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
use_g4_steps
int PHG4BlockSteppingAction::use_g4_steps private
Definition at line 44 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4BlockSteppingAction.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4BlockSteppingAction.cc