Class Reference for E1039 Core & Analysis Software: PHParametersContainer Class Reference
PHParametersContainer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/PHParameter/PHParametersContainer.h>
Public Types
typedef std::map< int, PHParameters * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator, Iterator > Range
typedef std::pair< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHParametersContainer (const std::string &name="NONE")
virtual ~PHParametersContainer ()
void AddPHParameters (const int layer, PHParameters *params)
const PHParameters * GetParameters (const int layer) const
PHParameters * GetParametersToModify (const int layer)
int WriteToFile (const std::string &extension, const std::string &dir)
int WriteToDB ()
void set_name (const std::string &name)
std::string Name () const
ConstRange GetAllParameters () const
void Print () const
void SaveToNodeTree (PHCompositeNode *topNode, const std::string &nodename)
int ExistDetid (const int detid) const
void clear ()
void FillFrom (const PdbParameterMapContainer *saveparamcontainer)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
void CopyToPdbParameterMapContainer (PdbParameterMapContainer *myparm)
Protected Attributes
std::string superdetectorname
std::map< int, PHParameters * > parametermap
Detailed Description
Definition at line 13 of file PHParametersContainer.h.
Member Typedef Documentation
ConstIterator
typedef Map::const_iterator PHParametersContainer::ConstIterator
Definition at line 18 of file PHParametersContainer.h.
ConstRange
typedef std::pair<ConstIterator, ConstIterator> PHParametersContainer::ConstRange
Definition at line 20 of file PHParametersContainer.h.
Iterator
typedef Map::iterator PHParametersContainer::Iterator
Definition at line 17 of file PHParametersContainer.h.
Map
typedef std::map<int, PHParameters *> PHParametersContainer::Map
Definition at line 16 of file PHParametersContainer.h.
Range
typedef std::pair<Iterator, Iterator> PHParametersContainer::Range
Definition at line 19 of file PHParametersContainer.h.
Constructor & Destructor Documentation
PHParametersContainer()
PHParametersContainer::PHParametersContainer (const std::string & name = "NONE") explicit
Definition at line 25 of file PHParametersContainer.cc.
~PHParametersContainer()
PHParametersContainer::~PHParametersContainer () virtual
Definition at line 29 of file PHParametersContainer.cc.
References parametermap.
Member Function Documentation
AddPHParameters()
void PHParametersContainer::AddPHParameters (const int layer, PHParameters * params)
Definition at line 58 of file PHParametersContainer.cc.
References parametermap, and PHWHERE.
Referenced by PHParameterContainerInterface::CreateInitialize(), PHG4DetectorSubsystem::InitRun(), PHParameterContainerInterface::set_int_param(), and PHParameterContainerInterface::set_string_param().
clear()
void PHParametersContainer::clear () inline
Definition at line 38 of file PHParametersContainer.h.
References parametermap.
CopyToPdbParameterMapContainer()
void PHParametersContainer::CopyToPdbParameterMapContainer (PdbParameterMapContainer * myparm) protected
Definition at line 171 of file PHParametersContainer.cc.
References PdbParameterMapContainer::AddPdbParameterMap(), and parametermap.
Referenced by SaveToNodeTree(), WriteToDB(), and WriteToFile().
ExistDetid()
int PHParametersContainer::ExistDetid (const int detid) const
Definition at line 216 of file PHParametersContainer.cc.
References parametermap.
Referenced by PHParameterContainerInterface::ExistDetid().
FillFrom()
void PHParametersContainer::FillFrom (const PdbParameterMapContainer * saveparamcontainer)
Definition at line 40 of file PHParametersContainer.cc.
References PHParameters::FillFrom(), PdbParameterMapContainer::get_ParameterMaps(), and parametermap.
GetAllParameters()
ConstRange PHParametersContainer::GetAllParameters () const inline
Definition at line 34 of file PHParametersContainer.h.
References parametermap.
GetParameters()
const PHParameters * PHParametersContainer::GetParameters (const int layer) const
Definition at line 70 of file PHParametersContainer.cc.
References NULL, and parametermap.
Referenced by PHParameterContainerInterface::get_double_param(), PHParameterContainerInterface::get_int_param(), and PHParameterContainerInterface::get_string_param().
GetParametersToModify()
PHParameters * PHParametersContainer::GetParametersToModify (const int layer)
Definition at line 83 of file PHParametersContainer.cc.
References NULL, and parametermap.
Referenced by PHParameterContainerInterface::CreateInitialize(), and PHParameterContainerInterface::UpdateParametersWithMacro().
Name()
std::string PHParametersContainer::Name () const inline
Definition at line 32 of file PHParametersContainer.h.
References superdetectorname.
Referenced by PHParameterContainerInterface::CreateInitialize(), PHParameterContainerInterface::get_double_param(), PHParameterContainerInterface::get_int_param(), PHParameterContainerInterface::get_string_param(), Print(), PHParameterContainerInterface::set_double_param(), PHParameterContainerInterface::set_int_param(), and PHParameterContainerInterface::set_string_param().
Print()
void PHParametersContainer::Print () const
Definition at line 184 of file PHParametersContainer.cc.
References Name(), and parametermap.
SaveToNodeTree()
void PHParametersContainer::SaveToNodeTree (PHCompositeNode * topNode, const std::string & nodename)
Definition at line 197 of file PHParametersContainer.cc.
References PHCompositeNode::addNode(), CopyToPdbParameterMapContainer(), and PdbParameterMapContainer::Reset().
Referenced by PHParameterContainerInterface::SaveToNodeTree().
set_name()
void PHParametersContainer::set_name (const std::string & name) inline
Definition at line 31 of file PHParametersContainer.h.
References superdetectorname.
Referenced by PHParameterContainerInterface::set_name().
WriteToDB()
int PHParametersContainer::WriteToDB ()
Definition at line 133 of file PHParametersContainer.cc.
References PdbApplication::abort(), PdbApplication::commit(), CopyToPdbParameterMapContainer(), PdbBankManager::createBank(), PdbBankManager::getApplication(), PdbCalBank::getEntry(), PdbBankManager::instance(), PHWHERE, PdbCalBank::setLength(), PdbApplication::startUpdate(), and superdetectorname.
Referenced by PHG4DetectorSubsystem::SaveParamsToDB().
WriteToFile()
int PHParametersContainer::WriteToFile (const std::string & extension, const std::string & dir)
Definition at line 94 of file PHParametersContainer.cc.
References CopyToPdbParameterMapContainer(), PdbBankID::getInternalValue(), PHTimeStamp::getTics(), and superdetectorname.
Member Data Documentation
parametermap
std::map<int, PHParameters *> PHParametersContainer::parametermap protected
Definition at line 44 of file PHParametersContainer.h.
Referenced by AddPHParameters(), clear(), CopyToPdbParameterMapContainer(), ExistDetid(), FillFrom(), GetAllParameters(), GetParameters(), GetParametersToModify(), Print(), and ~PHParametersContainer().
superdetectorname
std::string PHParametersContainer::superdetectorname protected
Definition at line 43 of file PHParametersContainer.h.
Referenced by Name(), set_name(), WriteToDB(), and WriteToFile().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/PHParameter/PHParametersContainer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/PHParameter/PHParametersContainer.cc