Class Reference for E1039 Core & Analysis Software: JobOptsSvc Class Reference
JobOptsSvc Class Reference
Read a job options file and apply choices at runtime.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/jobopts_svc/JobOptsSvc.h>
Public Member Functions
JobOptsSvc ()
Constructor for default values.
bool init (bool forceInit=false)
Initialization with defaults.
bool init (const char *filename)
Initialization using this config file.
void close ()
Close the service and cleanup.
void save (TFile *saveFile, TString name="config")
Save the content to a TFile.
std::string ExpandEnvironmentals (const std::string &input) const
Return a string with environmental variables expanded.
std::string GetRoadsFilePlusTop () const
Return the location of PlusTop roads file.
std::string GetRoadsFilePlusBottom () const
Return the location of PlusBottom roads file.
std::string GetRoadsFileMinusTop () const
Return the location of MinusTop roads file.
std::string GetRoadsFileMinusBottom () const
Return the location of MinusBottom roads file.
std::string GetInputMySQLURL () const
Return the URL for the input MySQL server.
std::string GetOutputMySQLURL () const
Return the URL for the output MySQL server.
bool ProcessAllEvents () const
Returns true if all events will be processing, false if only a subset.
Static Public Member Functions
static JobOptsSvc * instance ()
singlton instance
Public Attributes
std::string m_configFile
Name of the config file loaded.
bool m_mcMode
Running on MC?
bool m_alignmentMode
Running in alignment mode?
bool m_enableTriggerMask
Enable hodo masking with trigger road info.
bool m_enableKMag
Turn kMag on.
bool m_enableOnlineAlignment
Get alignment params from database?
bool m_useIdealGeom
do not load alignment for ideal geom
bool m_enableEvaluation
Enable evaluation output.
bool m_attachRawEvent
Attach the raw event in the reconstructed data.
bool m_sagittaReducer
Enable the sagitta ratio reducer.
bool m_updateAlignment
Update the alignment/calibration in tracking, i.e. re-calculate the wire position and drift distance during tracking.
bool m_hodomask
Enable hodoscope masking.
bool m_mergeHodo
merge the TW-TDC and v1495 TDC
bool m_realization
randomly drop hits according to efficiency, and smear drift distance according to resolution
int m_mySQLInputPort
mysql database input port
int m_mySQLOutputPort
mysql database output port
int m_nEvents
number of events to process
int m_firstEvent
first event to process
int m_triggerL1
L1 firmware version (trigger roads)
double m_timingOffset
timing offset for chamber hits (mostly)
double m_st0_reject
Station-0 rejection window.
double m_st1_reject
station-1 rejection window
double m_st2_reject
Station-2 rejection window.
double m_st3p_reject
Station-3 rejection window.
double m_st3m_reject
Station-3 rejection window.
double m_x_vtx
Beam X offset.
double m_y_vtx
Beam Y offset.
double m_x_spot_size
Beam spot size in X.
double m_y_spot_size
Beam spot size in X.
std::string m_inputFile
Name of the input file.
std::string m_outputFile
Name of the output file.
std::string m_inputSchema
Name of the input schema.
std::string m_outputSchema
Name of the output schema.
std::string m_alignmentFileHodo
Name of hodoscope alignment file.
std::string m_alignmentFileChamber
Name of chamber alignment file.
std::string m_alignmentFileProp
Name of prop tune alignment file.
std::string m_alignmentFileMille
Name of mille alignment file.
std::string m_triggerRepo
Location of the trigger repository on local disk.
std::string m_calibrationsFile
Name of calibrations file.
std::string m_fMagFile
Name of fMag ascii file.
std::string m_kMagFile
Name of kMag ascii file.
std::string m_geomVersion
Name of geometry version.
std::string m_mySQLInputServer
Name of input MySQL server.
std::string m_mySQLOutputServer
Name of output MySQL server.
Detailed Description
Read a job options file and apply choices at runtime.
Author
Brian G. Tice
Definition at line 14 of file JobOptsSvc.h.
Constructor & Destructor Documentation
JobOptsSvc::JobOptsSvc ()
Constructor for default values.
Definition at line 43 of file JobOptsSvc.cxx.
Member Function Documentation
void JobOptsSvc::close (void)
Close the service and cleanup.
Definition at line 104 of file JobOptsSvc.cxx.
References debug(), and NULL.
std::string JobOptsSvc::ExpandEnvironmentals (const std::string & input) const
Return a string with environmental variables expanded.
Definition at line 276 of file JobOptsSvc.cxx.
References debug().
std::string JobOptsSvc::GetInputMySQLURL () const
Return the URL for the input MySQL server.
Definition at line 319 of file JobOptsSvc.cxx.
std::string JobOptsSvc::GetOutputMySQLURL () const
Return the URL for the output MySQL server.
Definition at line 324 of file JobOptsSvc.cxx.
std::string JobOptsSvc::GetRoadsFileMinusBottom () const
Return the location of MinusBottom roads file.
Definition at line 313 of file JobOptsSvc.cxx.
References debug().
std::string JobOptsSvc::GetRoadsFileMinusTop () const
Return the location of MinusTop roads file.
Definition at line 306 of file JobOptsSvc.cxx.
References debug().
std::string JobOptsSvc::GetRoadsFilePlusBottom () const
Return the location of PlusBottom roads file.
Definition at line 299 of file JobOptsSvc.cxx.
References debug().
std::string JobOptsSvc::GetRoadsFilePlusTop () const
Return the location of PlusTop roads file.
Definition at line 293 of file JobOptsSvc.cxx.
References debug().
bool JobOptsSvc::init (bool forceInit = false)
Initialization with defaults.
Definition at line 118 of file JobOptsSvc.cxx.
References debug().
Referenced by EventDisplay4Sim(), Fun4CODA(), Fun4DST(), Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4MainDaq(), Fun4PatternDB(), Fun4Sim(), Fun4SRawEvent(), Fun4TrkDev(), InitInput(), main(), and RecoE906Data().
bool JobOptsSvc::init (const char * filename)
Initialization using this config file.
Definition at line 130 of file JobOptsSvc.cxx.
References debug(), and ExpandEnvironmentals().
JobOptsSvc * JobOptsSvc::instance () static
singlton instance
Definition at line 28 of file JobOptsSvc.cxx.
References debug(), and NULL.
Referenced by EventDisplay4Sim(), EventReducer::EventReducer(), Fun4CODA(), Fun4DST(), Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4MainDaq(), Fun4PatternDB(), Fun4Sim(), Fun4SRawEvent(), Fun4TrkDev(), TriggerAnalyzer::init(), GeomSvc::init(), InitInput(), GeomSvc::initPlaneDirect(), KalmanDSTrk::KalmanDSTrk(), KalmanFastTracking::KalmanFastTracking(), KalmanFastTrackingWrapper::KalmanFastTrackingWrapper(), main(), PropSegment::PropSegment(), RecoE906Data(), Settings::Settings(), SQReco::SQReco(), Tracklet::Tracklet(), and VertexFit::VertexFit().
bool JobOptsSvc::ProcessAllEvents () const
Returns true if all events will be processing, false if only a subset.
Definition at line 329 of file JobOptsSvc.cxx.
void JobOptsSvc::save (TFile * saveFile, TString name = "config")
Save the content to a TFile.
Definition at line 341 of file JobOptsSvc.cxx.
References X_VTX, and Y_VTX.
Member Data Documentation
std::string JobOptsSvc::m_alignmentFileChamber
Name of chamber alignment file.
Definition at line 98 of file JobOptsSvc.h.
std::string JobOptsSvc::m_alignmentFileHodo
Name of hodoscope alignment file.
Definition at line 97 of file JobOptsSvc.h.
std::string JobOptsSvc::m_alignmentFileMille
Name of mille alignment file.
Definition at line 100 of file JobOptsSvc.h.
std::string JobOptsSvc::m_alignmentFileProp
Name of prop tune alignment file.
Definition at line 99 of file JobOptsSvc.h.
bool JobOptsSvc::m_alignmentMode
Running in alignment mode?
Definition at line 59 of file JobOptsSvc.h.
Referenced by Settings::Settings().
bool JobOptsSvc::m_attachRawEvent
Attach the raw event in the reconstructed data.
Definition at line 65 of file JobOptsSvc.h.
std::string JobOptsSvc::m_calibrationsFile
Name of calibrations file.
Definition at line 104 of file JobOptsSvc.h.
std::string JobOptsSvc::m_configFile
Name of the config file loaded.
Definition at line 56 of file JobOptsSvc.h.
bool JobOptsSvc::m_enableEvaluation
Enable evaluation output.
Definition at line 64 of file JobOptsSvc.h.
bool JobOptsSvc::m_enableKMag
Turn kMag on.
Definition at line 61 of file JobOptsSvc.h.
Referenced by KalmanFastTracking::buildGlobalTracks(), KalmanDSTrk::buildGlobalTracks(), KalmanFastTracking::fitTracklet(), KalmanDSTrk::fitTracklet(), PropSegment::PropSegment(), and Tracklet::Tracklet().
bool JobOptsSvc::m_enableOnlineAlignment
Get alignment params from database?
Definition at line 62 of file JobOptsSvc.h.
bool JobOptsSvc::m_enableTriggerMask
Enable hodo masking with trigger road info.
Definition at line 60 of file JobOptsSvc.h.
Referenced by SQReco::InitRun(), and KalmanFastTrackingWrapper::InitRun().
int JobOptsSvc::m_firstEvent
first event to process
Definition at line 75 of file JobOptsSvc.h.
std::string JobOptsSvc::m_fMagFile
Name of fMag ascii file.
Definition at line 106 of file JobOptsSvc.h.
Referenced by EventDisplay4Sim(), Fun4CODA(), Fun4DST(), Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4MainDaq(), Fun4PatternDB(), Fun4SRawEvent(), Fun4TrkDev(), main(), and Settings::Settings().
std::string JobOptsSvc::m_geomVersion
Name of geometry version.
Definition at line 109 of file JobOptsSvc.h.
Referenced by Settings::Settings().
bool JobOptsSvc::m_hodomask
Enable hodoscope masking.
Definition at line 68 of file JobOptsSvc.h.
Referenced by SQReco::InitRun(), and KalmanFastTrackingWrapper::InitRun().
std::string JobOptsSvc::m_inputFile
Name of the input file.
Definition at line 92 of file JobOptsSvc.h.
std::string JobOptsSvc::m_inputSchema
Name of the input schema.
Definition at line 94 of file JobOptsSvc.h.
std::string JobOptsSvc::m_kMagFile
Name of kMag ascii file.
Definition at line 107 of file JobOptsSvc.h.
Referenced by EventDisplay4Sim(), Fun4CODA(), Fun4DST(), Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4MainDaq(), Fun4PatternDB(), Fun4SRawEvent(), Fun4TrkDev(), main(), and Settings::Settings().
bool JobOptsSvc::m_mcMode
Running on MC?
Definition at line 58 of file JobOptsSvc.h.
Referenced by EventReducer::reduceEvent(), KalmanFastTracking::setRawEvent(), KalmanDSTrk::setRawEventWorker(), and Settings::Settings().
bool JobOptsSvc::m_mergeHodo
merge the TW-TDC and v1495 TDC
Definition at line 69 of file JobOptsSvc.h.
Referenced by SQReco::InitRun(), and KalmanFastTrackingWrapper::InitRun().
int JobOptsSvc::m_mySQLInputPort
mysql database input port
Definition at line 72 of file JobOptsSvc.h.
Referenced by Settings::Settings().
std::string JobOptsSvc::m_mySQLInputServer
Name of input MySQL server.
Definition at line 110 of file JobOptsSvc.h.
Referenced by Settings::Settings().
int JobOptsSvc::m_mySQLOutputPort
mysql database output port
Definition at line 73 of file JobOptsSvc.h.
std::string JobOptsSvc::m_mySQLOutputServer
Name of output MySQL server.
Definition at line 111 of file JobOptsSvc.h.
int JobOptsSvc::m_nEvents
number of events to process
Definition at line 74 of file JobOptsSvc.h.
std::string JobOptsSvc::m_outputFile
Name of the output file.
Definition at line 93 of file JobOptsSvc.h.
std::string JobOptsSvc::m_outputSchema
Name of the output schema.
Definition at line 95 of file JobOptsSvc.h.
bool JobOptsSvc::m_realization
randomly drop hits according to efficiency, and smear drift distance according to resolution
Definition at line 70 of file JobOptsSvc.h.
Referenced by SQReco::InitRun(), and KalmanFastTrackingWrapper::InitRun().
bool JobOptsSvc::m_sagittaReducer
Enable the sagitta ratio reducer.
Definition at line 66 of file JobOptsSvc.h.
Referenced by SQReco::InitRun(), and KalmanFastTrackingWrapper::InitRun().
double JobOptsSvc::m_st0_reject
Station-0 rejection window.
Definition at line 81 of file JobOptsSvc.h.
double JobOptsSvc::m_st1_reject
station-1 rejection window
Definition at line 82 of file JobOptsSvc.h.
double JobOptsSvc::m_st2_reject
Station-2 rejection window.
Definition at line 83 of file JobOptsSvc.h.
double JobOptsSvc::m_st3m_reject
Station-3 rejection window.
Definition at line 85 of file JobOptsSvc.h.
double JobOptsSvc::m_st3p_reject
Station-3 rejection window.
Definition at line 84 of file JobOptsSvc.h.
double JobOptsSvc::m_timingOffset
timing offset for chamber hits (mostly)
Definition at line 79 of file JobOptsSvc.h.
Referenced by EventReducer::EventReducer().
int JobOptsSvc::m_triggerL1
L1 firmware version (trigger roads)
Definition at line 77 of file JobOptsSvc.h.
std::string JobOptsSvc::m_triggerRepo
Location of the trigger repository on local disk.
Definition at line 102 of file JobOptsSvc.h.
bool JobOptsSvc::m_updateAlignment
Update the alignment/calibration in tracking, i.e. re-calculate the wire position and drift distance during tracking.
Definition at line 67 of file JobOptsSvc.h.
Referenced by SQReco::InitRun(), and KalmanFastTrackingWrapper::InitRun().
bool JobOptsSvc::m_useIdealGeom
do not load alignment for ideal geom
Definition at line 63 of file JobOptsSvc.h.
double JobOptsSvc::m_x_spot_size
Beam spot size in X.
Definition at line 89 of file JobOptsSvc.h.
double JobOptsSvc::m_x_vtx
Beam X offset.
Definition at line 87 of file JobOptsSvc.h.
double JobOptsSvc::m_y_spot_size
Beam spot size in X.
Definition at line 90 of file JobOptsSvc.h.
double JobOptsSvc::m_y_vtx
Beam Y offset.
Definition at line 88 of file JobOptsSvc.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/jobopts_svc/JobOptsSvc.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/jobopts_svc/JobOptsSvc.cxx