Class Reference for E1039 Core & Analysis Software: DPTriggerAnalyzer Class Reference
DPTriggerAnalyzer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/dptrigger/DPTriggerAnalyzer.h>
Classes
class MatrixNode
Public Types
enum NimMode { NIM_AND , NIM_OR }
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Public Member Functions
DPTriggerAnalyzer (const std::string &name="DPTriggerAnalyzer")
virtual ~DPTriggerAnalyzer ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
const std::string & get_road_set_file_name () const
void set_road_set_file_name (const std::string &roadSetFileName)
const std::string & get_output_node_name () const
void set_output_node_name (const std::string &name)
void use_trigger_hit ()
void require_in_time (const bool val)
void set_nim_mode (const NimMode nim1, const NimMode nim2)
void buildTriggerMatrix ()
Build the trigger matrix by the input roads list.
void searchMatrix (MatrixNode *node, int level, int index)
Test the trigger pattern.
void deleteMatrix (MatrixNode *node)
Tree deletion.
std::list< DPTriggerRoad > & getRoadsFound (int index)
Helper function to retrieve the found road list.
void printHitPattern ()
Helper functions to print various things.
void printPath ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 81 of file DPTriggerAnalyzer.h.
Member Enumeration Documentation
NimMode
enum DPTriggerAnalyzer::NimMode
Enumerator
NIM_AND
NIM_OR
Definition at line 88 of file DPTriggerAnalyzer.h.
Constructor & Destructor Documentation
DPTriggerAnalyzer()
DPTriggerAnalyzer::DPTriggerAnalyzer (const std::string & name = "DPTriggerAnalyzer")
Definition at line 102 of file DPTriggerAnalyzer.cxx.
~DPTriggerAnalyzer()
DPTriggerAnalyzer::~DPTriggerAnalyzer () virtual
Definition at line 117 of file DPTriggerAnalyzer.cxx.
References deleteMatrix().
Member Function Documentation
buildTriggerMatrix()
void DPTriggerAnalyzer::buildTriggerMatrix ()
Build the trigger matrix by the input roads list.
This function converts the lists of roads (i.e. roadset given), into the trees of hodo element nodes.
The depth of each branch is always four, which corresponds to the four hodo planes.
Definition at line 333 of file DPTriggerAnalyzer.cxx.
References DPTriggerAnalyzer::MatrixNode::add(), DPTriggerAnalyzer::MatrixNode::children, and NTRPLANES.
Referenced by Init().
deleteMatrix()
void DPTriggerAnalyzer::deleteMatrix (MatrixNode * node)
Tree deletion.
Definition at line 384 of file DPTriggerAnalyzer.cxx.
References DPTriggerAnalyzer::MatrixNode::children, and NULL.
Referenced by ~DPTriggerAnalyzer().
End()
int DPTriggerAnalyzer::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 289 of file DPTriggerAnalyzer.cxx.
References Fun4AllReturnCodes::EVENT_OK.
get_output_node_name()
const std::string& DPTriggerAnalyzer::get_output_node_name () const inline
Definition at line 104 of file DPTriggerAnalyzer.h.
get_road_set_file_name()
const std::string& DPTriggerAnalyzer::get_road_set_file_name () const inline
Definition at line 97 of file DPTriggerAnalyzer.h.
getRoadsFound()
std::list<DPTriggerRoad>& DPTriggerAnalyzer::getRoadsFound (int index) inline
Helper function to retrieve the found road list.
Definition at line 124 of file DPTriggerAnalyzer.h.
Init()
int DPTriggerAnalyzer::Init (PHCompositeNode * topNode) virtual
A roadset is loaded here, not in InitRun(). It is possible but very unlikely that multiple runs taken with different roadsets are analyzed together. When someone moves the contents to InitRun(), please confirm that all variables like "roads" are cleared properly.
Reimplemented from SubsysReco.
Definition at line 134 of file DPTriggerAnalyzer.cxx.
References Fun4AllReturnCodes::ABORTRUN, DPTriggerRoad::addTrElement(), buildTriggerMatrix(), Fun4AllReturnCodes::EVENT_OK, DPTriggerRoad::getStringID(), recoConsts::instance(), LogInfo, NTRPLANES, recoConsts::set_CharFlag(), DPTriggerRoad::setBkgRate(), DPTriggerRoad::setPxMin(), DPTriggerRoad::setRoadID(), and DPTriggerRoad::setSigWeight().
InitRun()
int DPTriggerAnalyzer::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 175 of file DPTriggerAnalyzer.cxx.
printHitPattern()
void DPTriggerAnalyzer::printHitPattern ()
Helper functions to print various things.
Definition at line 394 of file DPTriggerAnalyzer.cxx.
References NTRPLANES.
printPath()
void DPTriggerAnalyzer::printPath ()
Definition at line 404 of file DPTriggerAnalyzer.cxx.
process_event()
int DPTriggerAnalyzer::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Count up the number of hits per hodo planes (and others for simplicity)
Reimplemented from SubsysReco.
Definition at line 180 of file DPTriggerAnalyzer.cxx.
References SQHitVector::at(), Fun4AllReturnCodes::EVENT_OK, SQHit::get_detector_id(), SQHit::get_element_id(), GeomSvc::getDetectorID(), GeomSvc::getHodoStation(), GeomSvc::instance(), SQHit::is_in_time(), SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, SQEvent::MATRIX5, SQEvent::NIM1, SQEvent::NIM2, NIM_AND, NTRPLANES, searchMatrix(), SQEvent::set_trigger(), and SQHitVector::size().
require_in_time()
void DPTriggerAnalyzer::require_in_time (const bool val) inline
Definition at line 108 of file DPTriggerAnalyzer.h.
searchMatrix()
void DPTriggerAnalyzer::searchMatrix (MatrixNode * node, int level, int index)
Test the trigger pattern.
search for possible roads
The contents of "buildHitPattern()" have been moved to process_event(), because the similar hit selection was repeated inside and outside this function.
Definition at line 364 of file DPTriggerAnalyzer.cxx.
References DPTriggerAnalyzer::MatrixNode::children, DPTriggerRoad::getStringID(), and DPTriggerAnalyzer::MatrixNode::uniqueID.
Referenced by process_event().
set_nim_mode()
void DPTriggerAnalyzer::set_nim_mode (const NimMode nim1, const NimMode nim2)
Definition at line 123 of file DPTriggerAnalyzer.cxx.
set_output_node_name()
void DPTriggerAnalyzer::set_output_node_name (const std::string & name) inline
Definition at line 105 of file DPTriggerAnalyzer.h.
set_road_set_file_name()
void DPTriggerAnalyzer::set_road_set_file_name (const std::string & roadSetFileName) inline
Definition at line 100 of file DPTriggerAnalyzer.h.
use_trigger_hit()
void DPTriggerAnalyzer::use_trigger_hit () inline
Definition at line 107 of file DPTriggerAnalyzer.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/dptrigger/DPTriggerAnalyzer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/dptrigger/DPTriggerAnalyzer.cxx