Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHTimeStamp.cc File Reference
PHTimeStamp.cc File Reference
#include "PHTimeStamp.h"
#include <cstdlib>
#include <cstring>
#include <iostream>
Functions
char * strptime (const char *s, const char *format, struct tm *tm)
PHTimeStamp operator+ (const PHTimeStamp &t1, time_t t2)
PHTimeStamp operator- (const PHTimeStamp &t1, time_t t2)
time_t operator- (const PHTimeStamp &t1, const PHTimeStamp &t2)
ostream & operator<< (ostream &s, const PHTimeStamp &t)
istream & operator>> (istream &s, PHTimeStamp &t)
Variables
const phtime_t ticOffset = 35067168000000000ULL
const phtime_t ticFactor = 10000000
Function Documentation
operator+()
PHTimeStamp operator+ (const PHTimeStamp & t1, time_t t2)
Definition at line 215 of file PHTimeStamp.cc.
operator-() [1/2]
time_t operator- (const PHTimeStamp & t1, const PHTimeStamp & t2)
Definition at line 229 of file PHTimeStamp.cc.
References PHTimeStamp::getTics().
operator-() [2/2]
PHTimeStamp operator- (const PHTimeStamp & t1, time_t t2)
Definition at line 222 of file PHTimeStamp.cc.
operator<<()
ostream& operator<< (ostream & s, const PHTimeStamp & t)
Definition at line 234 of file PHTimeStamp.cc.
References PHTimeStamp::getTics().
operator>>()
istream& operator>> (istream & s, PHTimeStamp & t)
Definition at line 243 of file PHTimeStamp.cc.
References PHTimeStamp::set().
strptime()
char* strptime (const char * s, const char * format, struct tm * tm)
Referenced by PHTimeStamp::set().
Variable Documentation
ticFactor
const phtime_t ticFactor = 10000000
Definition at line 34 of file PHTimeStamp.cc.
Referenced by PHTimeStamp::operator+=(), and PHTimeStamp::operator-=().
ticOffset
const phtime_t ticOffset = 35067168000000000ULL
Definition at line 31 of file PHTimeStamp.cc.