Class Reference for E1039 Core & Analysis Software: CalibParamInTimeV1495 Class Reference
CalibParamInTimeV1495 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/CalibParamInTimeV1495.h>
Public Member Functions
CalibParamInTimeV1495 ()
virtual ~CalibParamInTimeV1495 ()
void Add (const std::string det, const short ele, const short lvl, const double center, const double width)
void Add (const std::string det_name, const short det_id, const short ele, const short lvl, const double center, const double width)
bool Find (const short det, const short ele, const short lvl, double &center, double &width)
void Print (std::ostream &os)
Public Member Functions inherited from CalibParamBase
CalibParamBase (const std::string label, const std::string header)
virtual ~CalibParamBase ()
Public Member Functions inherited from RunParamBase
RunParamBase (const std::string type, const std::string label, const std::string header)
virtual ~RunParamBase ()
void SetBaseDir (const std::string dir_base)
std::string GetBaseDir ()
std::string GetParamID ()
std::string GetMapID ()
void SetMapID (const std::string map_id)
void SetMapIDbyFile (const std::string map_id)
void SetMapIDbyDB (const std::string map_id)
void SetMapIDbyFile (const int run)
void SetMapIDbyDB (const int run)
void ReadFromFile ()
void WriteToFile ()
void ReadFromLocalFile (const std::string fn_tsv)
void WriteToLocalFile (const std::string fn_tsv)
void ReadFromDB ()
void WriteToDB ()
void WriteRangeToDB ()
Protected Member Functions
int ReadFileCont (LineList &lines)
int WriteFileCont (std::ostream &os)
void ReadDbTable (DbSvc &db)
void WriteDbTable (DbSvc &db)
Protected Member Functions inherited from RunParamBase
std::string RangeFileName ()
std::string MapFileName ()
std::string SchemaName ()
std::string MapTableName ()
Additional Inherited Members
Protected Types inherited from RunParamBase
typedef std::vector< std::string > LineList
Detailed Description
Definition at line 5 of file CalibParamInTimeV1495.h.
Constructor & Destructor Documentation
CalibParamInTimeV1495::CalibParamInTimeV1495 ()
Definition at line 14 of file CalibParamInTimeV1495.cc.
virtual CalibParamInTimeV1495::~CalibParamInTimeV1495 () inline virtual
Definition at line 24 of file CalibParamInTimeV1495.h.
Member Function Documentation
void CalibParamInTimeV1495::Add (const std::string det, const short ele, const short lvl, const double center, const double width)
Definition at line 88 of file CalibParamInTimeV1495.cc.
References GeomSvc::getDetectorID(), GeomSvc::instance(), and GeomSvc::toLocalDetectorName().
Referenced by ReadDbTable(), and ReadFileCont().
void CalibParamInTimeV1495::Add (const std::string det_name, const short det_id, const short ele, const short lvl, const double center, const double width)
Definition at line 115 of file CalibParamInTimeV1495.cc.
bool CalibParamInTimeV1495::Find (const short det, const short ele, const short lvl, double & center, double & width)
Definition at line 130 of file CalibParamInTimeV1495.cc.
Referenced by CalibHodoInTime::process_event().
void CalibParamInTimeV1495::Print (std::ostream & os) virtual
Reimplemented from RunParamBase.
Definition at line 145 of file CalibParamInTimeV1495.cc.
void CalibParamInTimeV1495::ReadDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 48 of file CalibParamInTimeV1495.cc.
References Add(), RunParamBase::MapTableName(), and DbSvc::Process().
int CalibParamInTimeV1495::ReadFileCont (LineList & lines) protected virtual
Reimplemented from RunParamBase.
Definition at line 20 of file CalibParamInTimeV1495.cc.
References Add().
void CalibParamInTimeV1495::WriteDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 65 of file CalibParamInTimeV1495.cc.
References DbSvc::Con(), DbSvc::CreateTable(), and RunParamBase::MapTableName().
int CalibParamInTimeV1495::WriteFileCont (std::ostream & os) protected virtual
Reimplemented from RunParamBase.
Definition at line 37 of file CalibParamInTimeV1495.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/CalibParamInTimeV1495.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/CalibParamInTimeV1495.cc