SeaQuest Offline Software: /home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/src/millepede.f File Reference
millepede.f File Reference
Functions/Subroutines
subroutine initgl (NAGBAR, NALCAR, NSTD, IPRLIM)
subroutine parglo (PAR)
subroutine parsig (INDEX, SIGMA)
subroutine nonlin (INDEX)
subroutine initun (LUN, CUTFAC)
subroutine constf (DERCS, RHS)
subroutine equloc (DERGB, DERLC, RRMEAS, SIGMA)
subroutine zerloc (DERGB, DERLC)
subroutine fitloc
subroutine fitglo (PAR)
function errpar (I)
function corpar (I, J)
subroutine prtglo (LUN)
subroutine spminv (V, B, N, NRANK, DIAG, FLAG)
subroutine spavat (V, A, W, N, M)
subroutine spax (A, X, Y, M, N)
subroutine pxhist (INC, N, XA, XB)
subroutine chfmt (X, N, XCHAR, ECHAR)
function chindl (N, ND)
subroutine fitmut (NVEC, VEC)
Function/Subroutine Documentation
subroutine chfmt (real, dimension(*) X, N, character*8, dimension(n) XCHAR, character*4 ECHAR)
Definition at line 1414 of file millepede.f.
Referenced by pxhist().
function chindl (N, ND)
Definition at line 1528 of file millepede.f.
Referenced by fitloc(), and initgl().
subroutine constf (real, dimension(*) DERCS, RHS)
Definition at line 285 of file millepede.f.
References PHTimer::stop().
function corpar (I, J)
Definition at line 1030 of file millepede.f.
subroutine equloc (real, dimension(*) DERGB, real, dimension(*) DERLC, RRMEAS, SIGMA)
Definition at line 326 of file millepede.f.
function errpar (I)
Definition at line 994 of file millepede.f.
subroutine fitglo (real, dimension(*) PAR)
Definition at line 768 of file millepede.f.
References boost::array< T, N >::end(), fitloc(), prtglo(), pxhist(), and spminv().
subroutine fitloc ()
Definition at line 463 of file millepede.f.
References chindl(), spavat(), spax(), and spminv().
Referenced by fitglo().
subroutine fitmut (NVEC, real, dimension(*) VEC)
Definition at line 1561 of file millepede.f.
References PHTimer::stop().
subroutine initgl (NAGBAR, NALCAR, NSTD, IPRLIM)
Definition at line 32 of file millepede.f.
References chindl(), and PHTimer::stop().
subroutine initun (LUN, CUTFAC)
Definition at line 233 of file millepede.f.
References PHTimer::stop().
subroutine nonlin (INDEX)
Definition at line 200 of file millepede.f.
subroutine parglo (real, dimension(*) PAR)
Definition at line 131 of file millepede.f.
subroutine parsig (INDEX, SIGMA)
Definition at line 166 of file millepede.f.
subroutine prtglo (LUN)
Definition at line 1071 of file millepede.f.
Referenced by fitglo().
subroutine pxhist (integer, dimension(n) INC, N, XA, XB)
Definition at line 1301 of file millepede.f.
References chfmt().
Referenced by fitglo().
subroutine spavat (double precision, dimension(*) V, double precision, dimension(*) A, double precision, dimension(*) W, N, M)
Definition at line 1228 of file millepede.f.
Referenced by fitloc().
subroutine spax (double precision, dimension(*) A, double precision, dimension(*) X, double precision, dimension(*) Y, M, N)
Definition at line 1277 of file millepede.f.
Referenced by fitloc().
subroutine spminv (double precision, dimension(*) V, double precision, dimension(n) B, N, NRANK, double precision, dimension(n) DIAG, logical, dimension(*) FLAG)
Definition at line 1129 of file millepede.f.
Referenced by fitglo(), and fitloc().
subroutine zerloc (real, dimension(*) DERGB, real, dimension(*) DERLC)
Definition at line 423 of file millepede.f.