Class Reference for E1039 Core & Analysis Software: PHG4TargetCoilV2Detector Class Reference
PHG4TargetCoilV2Detector Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4TargetCoilV2Detector.h>
Public Member Functions
PHG4TargetCoilV2Detector (PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~PHG4TargetCoilV2Detector (void)
destructor
void Construct (G4LogicalVolume *world)
construct
bool IsInCylinder (const G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
int get_elem_id (const std::string &name) const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 12 of file PHG4TargetCoilV2Detector.h.
Constructor & Destructor Documentation
PHG4TargetCoilV2Detector()
PHG4TargetCoilV2Detector::PHG4TargetCoilV2Detector (PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 30 of file PHG4TargetCoilV2Detector.cc.
~PHG4TargetCoilV2Detector()
virtual PHG4TargetCoilV2Detector::~PHG4TargetCoilV2Detector (void) inline virtual
destructor
Definition at line 19 of file PHG4TargetCoilV2Detector.h.
Member Function Documentation
Construct()
void PHG4TargetCoilV2Detector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 278 of file PHG4TargetCoilV2Detector.cc.
References PHParameters::get_double_param(), PHG4Detector::GetName(), PHG4Detector::name, PHG4Detector::overlapcheck, PHParameters::Print(), and PHG4Utils::SetColour().
get_elem_id()
int PHG4TargetCoilV2Detector::get_elem_id (const std::string & name) const
Definition at line 452 of file PHG4TargetCoilV2Detector.cc.
References PHG4Detector::name.
Referenced by PHG4TargetCoilV2SteppingAction::UserSteppingAction().
get_Layer()
int PHG4TargetCoilV2Detector::get_Layer () const inline
Definition at line 29 of file PHG4TargetCoilV2Detector.h.
Referenced by PHG4TargetCoilV2SteppingAction::UserSteppingAction().
IsInCylinder()
bool PHG4TargetCoilV2Detector::IsInCylinder (const G4VPhysicalVolume * volume) const
Definition at line 39 of file PHG4TargetCoilV2Detector.cc.
Referenced by PHG4TargetCoilV2SteppingAction::UserSteppingAction().
SuperDetector() [1/2]
const std::string PHG4TargetCoilV2Detector::SuperDetector () const inline
Definition at line 28 of file PHG4TargetCoilV2Detector.h.
SuperDetector() [2/2]
void PHG4TargetCoilV2Detector::SuperDetector (const std::string & name) inline
Definition at line 27 of file PHG4TargetCoilV2Detector.h.
References PHG4Detector::name.
Referenced by PHG4TargetCoilV2Subsystem::InitRunSubsystem(), PHG4TargetCoilV2SteppingAction::SetInterfacePointers(), and PHG4TargetCoilV2SteppingAction::UserSteppingAction().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4TargetCoilV2Detector.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4TargetCoilV2Detector.cc