Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaRealDst/macro/Fun4RealDst.C File Reference
Fun4RealDst.C File Reference
Functions
int Fun4RealDst (const int run=1666, const int nevent=0)
Fun4MainDaq.C: Fun4all macro to decode the MainDAQ data.
int Fun4MultiRealDst (const char *fn_list_run="list_run.txt")
Function to analyze multiple DST files.
Function Documentation
int Fun4MultiRealDst (const char * fn_list_run = "list_run.txt")
Function to analyze multiple DST files.
You first list up runs in "list_run.txt". Then type the following commands to execute this function: root -b .L Fun4RealDst.C Fun4MultiRealDst();
Definition at line 38 of file Fun4RealDst.C.
References Fun4AllServer::End(), Fun4AllInputManager::fileopen(), UtilOnline::GetDstFileDir(), Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), run(), Fun4AllServer::run(), UtilOnline::RunNum2DstFile(), and se.
int Fun4RealDst (const int run = 1666, const int nevent = 0)
Fun4MainDaq.C: Fun4all macro to decode the MainDAQ data.
Main function.
Definition at line 7 of file Fun4RealDst.C.
References Fun4AllServer::End(), Fun4AllInputManager::fileopen(), UtilOnline::GetDstFilePath(), Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), run(), Fun4AllServer::run(), and se.