Class Reference for E1039 Core & Analysis Software: TrackletVector Class Reference
TrackletVector Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/FastTracklet.h>
Public Member Functions
TrackletVector ()
virtual ~TrackletVector ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
TrackletVector * Clone () const
bool empty () const
size_t size () const
void clear ()
const Tracklet * at (const size_t index) const
Tracklet * at (const size_t index)
void push_back (const Tracklet *tracklet)
size_t erase (const size_t index)
std::vector< Tracklet * >::const_iterator begin () const
std::vector< Tracklet * >::const_iterator end () const
std::vector< Tracklet * >::iterator begin ()
std::vector< Tracklet * >::iterator end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Detailed Description
Definition at line 253 of file FastTracklet.h.
Constructor & Destructor Documentation
TrackletVector()
TrackletVector::TrackletVector ()
Definition at line 1112 of file FastTracklet.cxx.
Referenced by Clone().
~TrackletVector()
TrackletVector::~TrackletVector () virtual
Definition at line 1115 of file FastTracklet.cxx.
References Reset().
Member Function Documentation
at() [1/2]
Tracklet * TrackletVector::at (const size_t index)
Definition at line 1137 of file FastTracklet.cxx.
References size().
at() [2/2]
const Tracklet * TrackletVector::at (const size_t index) const
Definition at line 1131 of file FastTracklet.cxx.
References size().
Referenced by SRMakeRTCurve::AnaForOneStation(), SRMakeRTCurve::FindBestTracklet(), SRMakeRTCurve::process_event(), AnaTrack::process_event(), AnaModule::process_event(), and SimpleTree::process_event().
begin() [1/2]
std::vector<Tracklet*>::iterator TrackletVector::begin () inline
Definition at line 276 of file FastTracklet.h.
begin() [2/2]
std::vector<Tracklet*>::const_iterator TrackletVector::begin () const inline
Definition at line 273 of file FastTracklet.h.
clear()
void TrackletVector::clear () inline
Definition at line 266 of file FastTracklet.h.
References Reset().
Referenced by SQReco::ProcessEventPrep().
Clone()
TrackletVector* TrackletVector::Clone () const inline
Definition at line 262 of file FastTracklet.h.
References TrackletVector().
empty()
bool TrackletVector::empty () const inline
Definition at line 264 of file FastTracklet.h.
end() [1/2]
std::vector<Tracklet*>::iterator TrackletVector::end () inline
Definition at line 277 of file FastTracklet.h.
end() [2/2]
std::vector<Tracklet*>::const_iterator TrackletVector::end () const inline
Definition at line 274 of file FastTracklet.h.
erase()
size_t TrackletVector::erase (const size_t index)
Definition at line 1148 of file FastTracklet.cxx.
References size().
identify()
void TrackletVector::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 1120 of file FastTracklet.cxx.
References size().
isValid()
int TrackletVector::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 261 of file FastTracklet.h.
push_back()
void TrackletVector::push_back (const Tracklet * tracklet)
Definition at line 1143 of file FastTracklet.cxx.
References Tracklet::Clone().
Referenced by SQReco::process_event(), and SQTrackletReco::process_event().
Reset()
void TrackletVector::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 1125 of file FastTracklet.cxx.
Referenced by clear(), and ~TrackletVector().
size()
size_t TrackletVector::size (void) const inline
Definition at line 265 of file FastTracklet.h.
Referenced by at(), erase(), SRMakeRTCurve::FindBestTracklet(), identify(), SRMakeRTCurve::process_event(), AnaTrack::process_event(), AnaModule::process_event(), and SimpleTree::process_event().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/FastTracklet.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/FastTracklet.cxx