Class Reference for E1039 Core & Analysis Software: PHG4PSScanGenerator Class Reference
PHG4PSScanGenerator Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4PSScanGenerator.h>
Public Types
enum FUNCTION { Uniform, Gaus }
supported function distributions
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Public Member Functions
PHG4PSScanGenerator (const std::string &name="EVTGENERATOR")
virtual ~PHG4PSScanGenerator ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void add_particles (const std::string &name, const unsigned int count)
interface for adding particles by name
void add_particles (const int pid, const unsigned int count)
interface for adding particle by pid
void set_t0 (const double t0)
set the starting time for the event
void set_eta_range (const double eta_min, const double eta_max)
range of randomized eta values
void set_phi_range (const double phi_min, const double phi_max)
range of randomized phi values
void set_pt_range (const double pt_min, const double pt_max, const double pt_gaus_width=0)
void set_p_range (const double p_min, const double p_max, const double p_gaus_width=0)
void set_vertex_distribution_function (FUNCTION x, FUNCTION y, FUNCTION z)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z)
set the mean value of the vertex distribution
void set_vertex_distribution_width (const double x, const double y, const double z)
set the width of the vertex distribution function about the mean
void set_existing_vertex_offset_vector (const double x, const double y, const double z)
set an offset vector from the existing vertex
void set_vertex_size_function (FUNCTION r)
set the distribution function of particles about the vertex
void set_vertex_size_parameters (const double mean, const double width)
set the dimensions of the distribution of particles about the vertex
void set_pxpypz_range (const double x_min, const double x_max, const double y_min, const double y_max, const double z_min, const double z_max)
double get_px_step () const
void set_px_step (double pxStep)
double get_py_step () const
void set_py_step (double pyStep)
double get_pz_step () const
void set_pz_step (double pzStep)
Public Member Functions inherited from PHG4ParticleGeneratorBase
virtual ~PHG4ParticleGeneratorBase ()
virtual void set_name (const std::string &particle="proton")
virtual void set_pid (const int pid)
virtual void set_mom (const double x, const double y, const double z)
virtual void set_vtx (const double x, const double y, const double z)
virtual double get_vtx_x () const
virtual double get_vtx_y () const
virtual double get_vtx_z () const
virtual double get_t0 () const
virtual void Print (const std::string &what="ALL") const
virtual void AddParticle (const std::string &particle, const double x, const double y, const double z)
virtual void AddParticle (const int pid, const double x, const double y, const double z)
virtual void Embed (const int i=1)
virtual int ReuseExistingVertex (PHCompositeNode *topNode)
int get_reuse_existing_vertex () const
void set_reuse_existing_vertex (const int i=1)
void set_seed (const unsigned int iseed)
unsigned int get_seed () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Protected Member Functions inherited from PHG4ParticleGeneratorBase
PHG4ParticleGeneratorBase (const std::string &name="GENERATORBASE")
int get_pdgcode (const std::string &name) const
std::string get_pdgname (const int pdgcode) const
double get_mass (const int pdgcode) const
void CheckAndCreateParticleVector ()
void SetParticleId (PHG4Particle *particle, PHG4InEvent *ineve)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from PHG4ParticleGeneratorBase
int embedflag
int reuse_existing_vertex
double vtx_x
double vtx_y
double vtx_z
double t0
std::vector< PHG4Particle * > particlelist
unsigned int seed
gsl_rng * RandomGenerator
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 12 of file PHG4PSScanGenerator.h.
Member Enumeration Documentation
enum PHG4PSScanGenerator::FUNCTION
supported function distributions
Enumerator
Uniform
Gaus
Definition at line 17 of file PHG4PSScanGenerator.h.
Constructor & Destructor Documentation
PHG4PSScanGenerator::PHG4PSScanGenerator (const std::string & name = "EVTGENERATOR")
Definition at line 25 of file PHG4PSScanGenerator.cc.
virtual PHG4PSScanGenerator::~PHG4PSScanGenerator () inline virtual
Definition at line 22 of file PHG4PSScanGenerator.h.
Member Function Documentation
void PHG4PSScanGenerator::add_particles (const std::string & name, const unsigned int count)
interface for adding particles by name
Definition at line 64 of file PHG4PSScanGenerator.cc.
Referenced by Fun4PatternDB().
void PHG4PSScanGenerator::add_particles (const int pid, const unsigned int count)
interface for adding particle by pid
Definition at line 70 of file PHG4PSScanGenerator.cc.
double PHG4PSScanGenerator::get_px_step () const inline
Definition at line 79 of file PHG4PSScanGenerator.h.
double PHG4PSScanGenerator::get_py_step () const inline
Definition at line 87 of file PHG4PSScanGenerator.h.
double PHG4PSScanGenerator::get_pz_step () const inline
Definition at line 95 of file PHG4PSScanGenerator.h.
int PHG4PSScanGenerator::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 177 of file PHG4PSScanGenerator.cc.
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), Gaus, PHG4ParticleGeneratorBase::get_pdgname(), PHG4ParticleGeneratorBase::get_reuse_existing_vertex(), PHG4ParticleGeneratorBase::get_seed(), PHWHERE, Uniform, and Fun4AllBase::verbosity.
int PHG4PSScanGenerator::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 276 of file PHG4PSScanGenerator.cc.
References Fun4AllReturnCodes::ABORTRUN, PHG4InEvent::AddEmbeddedParticle(), PHG4InEvent::AddParticle(), PHG4InEvent::AddVtx(), PHG4ParticleGeneratorBase::embedflag, Fun4AllReturnCodes::EVENT_OK, PHG4ParticleGeneratorBase::get_mass(), PHG4ParticleGeneratorBase::get_pdgcode(), PHG4InEvent::identify(), PHWHERE, PHG4ParticleGeneratorBase::RandomGenerator, PHG4ParticleGeneratorBase::reuse_existing_vertex, PHG4ParticleGeneratorBase::ReuseExistingVertex(), PHG4Particle::set_e(), PHG4Particle::set_name(), PHG4Particle::set_parent_id(), PHG4Particle::set_pid(), PHG4Particle::set_px(), PHG4Particle::set_py(), PHG4Particle::set_pz(), PHG4Particle::set_track_id(), PHG4Particle::set_vtx_id(), Fun4AllBase::verbosity, PHG4ParticleGeneratorBase::vtx_x, PHG4ParticleGeneratorBase::vtx_y, and PHG4ParticleGeneratorBase::vtx_z.
void PHG4PSScanGenerator::set_eta_range (const double eta_min, const double eta_max)
range of randomized eta values
Definition at line 80 of file PHG4PSScanGenerator.cc.
void PHG4PSScanGenerator::set_existing_vertex_offset_vector (const double x, const double y, const double z)
set an offset vector from the existing vertex
Definition at line 157 of file PHG4PSScanGenerator.cc.
void PHG4PSScanGenerator::set_p_range (const double p_min, const double p_max, const double p_gaus_width = 0)
range of randomized p values
Parameters
[in] p_gaus_width if non-zero, further apply a Gauss smearing to the p_min - p_max flat distribution
Definition at line 117 of file PHG4PSScanGenerator.cc.
void PHG4PSScanGenerator::set_phi_range (const double phi_min, const double phi_max)
range of randomized phi values
Definition at line 90 of file PHG4PSScanGenerator.cc.
void PHG4PSScanGenerator::set_pt_range (const double pt_min, const double pt_max, const double pt_gaus_width = 0)
range of randomized pt values
Parameters
[in] pt_gaus_width if non-zero, further apply a Gauss smearing to the pt_min - pt_max flat distribution
Definition at line 100 of file PHG4PSScanGenerator.cc.
void PHG4PSScanGenerator::set_px_step (double pxStep) inline
Definition at line 83 of file PHG4PSScanGenerator.h.
Referenced by Fun4PatternDB().
void PHG4PSScanGenerator::set_pxpypz_range (const double x_min, const double x_max, const double y_min, const double y_max, const double z_min, const double z_max)
Definition at line 420 of file PHG4PSScanGenerator.cc.
Referenced by Fun4PatternDB().
void PHG4PSScanGenerator::set_py_step (double pyStep) inline
Definition at line 91 of file PHG4PSScanGenerator.h.
Referenced by Fun4PatternDB().
void PHG4PSScanGenerator::set_pz_step (double pzStep) inline
Definition at line 99 of file PHG4PSScanGenerator.h.
Referenced by Fun4PatternDB().
void PHG4PSScanGenerator::set_t0 (const double t0) virtual
set the starting time for the event
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 75 of file PHG4PSScanGenerator.cc.
References PHG4ParticleGeneratorBase::t0.
void PHG4PSScanGenerator::set_vertex_distribution_function (FUNCTION x, FUNCTION y, FUNCTION z)
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 133 of file PHG4PSScanGenerator.cc.
Referenced by Fun4PatternDB().
void PHG4PSScanGenerator::set_vertex_distribution_mean (const double x, const double y, const double z)
set the mean value of the vertex distribution
Definition at line 141 of file PHG4PSScanGenerator.cc.
Referenced by Fun4PatternDB().
void PHG4PSScanGenerator::set_vertex_distribution_width (const double x, const double y, const double z)
set the width of the vertex distribution function about the mean
Definition at line 149 of file PHG4PSScanGenerator.cc.
Referenced by Fun4PatternDB().
void PHG4PSScanGenerator::set_vertex_size_function (FUNCTION r)
set the distribution function of particles about the vertex
Definition at line 165 of file PHG4PSScanGenerator.cc.
Referenced by Fun4PatternDB().
void PHG4PSScanGenerator::set_vertex_size_parameters (const double mean, const double width)
set the dimensions of the distribution of particles about the vertex
Definition at line 170 of file PHG4PSScanGenerator.cc.
Referenced by Fun4PatternDB().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4PSScanGenerator.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4PSScanGenerator.cc