Class Reference for E1039 Core & Analysis Software: NMRSignal Class Reference
NMRSignal Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaNMRData/NMRSignal.h>
Public Member Functions
NMRSignal ()
virtual ~NMRSignal ()
void SetEventNum (const int evt_num)
int GetEventNum () const
int GetNumPoint ()
double GetPoint (const int idx)
void AddPoint (const double val)
void ClearPoints ()
Detailed Description
Definition at line 4 of file NMRSignal.h.
Constructor & Destructor Documentation
NMRSignal()
NMRSignal::NMRSignal () inline
Definition at line 8 of file NMRSignal.h.
~NMRSignal()
virtual NMRSignal::~NMRSignal () inline virtual
Definition at line 9 of file NMRSignal.h.
Member Function Documentation
AddPoint()
void NMRSignal::AddPoint (const double val) inline
Definition at line 17 of file NMRSignal.h.
Referenced by NMRDataManager::ReadPolySignalFile(), and NMRDataManager::ReadRawSignalFile().
ClearPoints()
void NMRSignal::ClearPoints () inline
Definition at line 18 of file NMRSignal.h.
GetEventNum()
int NMRSignal::GetEventNum () const inline
Definition at line 12 of file NMRSignal.h.
GetNumPoint()
int NMRSignal::GetNumPoint () inline
Definition at line 14 of file NMRSignal.h.
Referenced by ana_NMR_noise(), and ana_NMR_poly_signal().
GetPoint()
double NMRSignal::GetPoint (const int idx) inline
Definition at line 15 of file NMRSignal.h.
Referenced by ana_NMR_noise(), ana_NMR_poly_signal(), and ana_NMR_raw_signal().
SetEventNum()
void NMRSignal::SetEventNum (const int evt_num) inline
Definition at line 11 of file NMRSignal.h.
Referenced by NMRDataManager::ReadPolySignalFile(), and NMRDataManager::ReadRawSignalFile().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaNMRData/NMRSignal.h