Class Reference for E1039 Core & Analysis Software: AnaModule Class Reference
AnaModule Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Efficiency/AnaModule/AnaModule.h>
Public Member Functions
AnaModule (const std::string &name="AnaModule")
virtual ~AnaModule ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_output_filename (const TString &n)
void registerDetector (TString name)
AnaModule ()
virtual ~AnaModule ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_output_filename (const TString &n)
AnaModule (const std::string &name="AnaModule")
virtual ~AnaModule ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_output_filename (const TString &n)
void set_legacy_rec_container (bool b)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 21 of file AnaModule.h.
Constructor & Destructor Documentation
AnaModule::AnaModule (const std::string & name = "AnaModule")
Definition at line 14 of file AnaModule.cxx.
AnaModule::~AnaModule () virtual
Definition at line 17 of file AnaModule.cxx.
AnaModule::AnaModule () inline
Definition at line 15 of file AnaModule.h.
virtual AnaModule::~AnaModule () inline virtual
Definition at line 16 of file AnaModule.h.
AnaModule::AnaModule (const std::string & name = "AnaModule")
virtual AnaModule::~AnaModule () virtual
Member Function Documentation
int AnaModule::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
int AnaModule::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
int AnaModule::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 70 of file AnaModule.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int AnaModule::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
int AnaModule::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
int AnaModule::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 20 of file AnaModule.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int AnaModule::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int AnaModule::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int AnaModule::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 25 of file AnaModule.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int AnaModule::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int AnaModule::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int AnaModule::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 35 of file AnaModule.cxx.
References TrackletVector::at(), Fun4AllReturnCodes::EVENT_OK, SQHit::get_element_id(), Tracklet::getChisq(), GeomSvc::getExpElementID(), Tracklet::getExpPositionW(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::getNHits(), GeomSvc::getPlaneNElements(), GeomSvc::getPlanePosition(), GeomSvc::isInPlane(), and TrackletVector::size().
void AnaModule::registerDetector (TString name)
Definition at line 106 of file AnaModule.cxx.
References GeomSvc::getDetectorID().
Referenced by run().
void AnaModule::set_legacy_rec_container (bool b) inline
Definition at line 28 of file AnaModule.h.
Referenced by RecoE1039Sim().
void AnaModule::set_output_filename (const TString & n)
void AnaModule::set_output_filename (const TString & n) inline
Definition at line 27 of file AnaModule.h.
void AnaModule::set_output_filename (const TString & n) inline
Definition at line 32 of file AnaModule.h.
Referenced by Fun4EMCal(), RecoE1039Sim(), and run().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Efficiency/AnaModule/AnaModule.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/EMCalDev/AnaModule/AnaModule.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/RecoDev/AnaModule/AnaModule.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Efficiency/AnaModule/AnaModule.cxx
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/EMCalDev/AnaModule/AnaModule.cxx
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/RecoDev/AnaModule/AnaModule.cxx