Class Reference for E1039 Core & Analysis Software: PHG4Particlev2 Class Reference
PHG4Particlev2 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Particlev2.h>
Public Member Functions
PHG4Particlev2 ()
PHG4Particlev2 (const std::string &name, const int pid, const double px, const double py, const double pz)
PHG4Particlev2 (const PHG4Particle *in)
virtual ~PHG4Particlev2 ()
int get_track_id () const
int get_vtx_id () const
int get_parent_id () const
int get_primary_id () const
double get_e () const
void set_track_id (const int i)
void set_vtx_id (const int i)
void set_parent_id (const int i)
void set_primary_id (const int i)
void set_e (const double e)
void identify (std::ostream &os=std::cout) const
Public Member Functions inherited from PHG4Particlev1
PHG4Particlev1 ()
PHG4Particlev1 (const std::string &name, const int pid, const double px, const double py, const double pz)
PHG4Particlev1 (const PHG4Particle *in)
virtual ~PHG4Particlev1 ()
int get_pid () const
std::string get_name () const
double get_px () const
double get_py () const
double get_pz () const
int get_barcode () const
void set_name (const std::string &name)
void set_pid (const int i)
void set_px (const double x)
void set_py (const double x)
void set_pz (const double x)
void set_barcode (const int bcd)
Public Member Functions inherited from PHG4Particle
PHG4Particle ()
virtual ~PHG4Particle ()
bool operator== (const PHG4Particle &p) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
int trkid
int vtxid
int parentid
int primaryid
double fe
Protected Attributes inherited from PHG4Particlev1
std::string fname
int fpid
double fpx
double fpy
double fpz
int barcode
Detailed Description
Definition at line 6 of file PHG4Particlev2.h.
Constructor & Destructor Documentation
PHG4Particlev2() [1/3]
PHG4Particlev2::PHG4Particlev2 ()
Definition at line 7 of file PHG4Particlev2.cc.
PHG4Particlev2() [2/3]
PHG4Particlev2::PHG4Particlev2 (const std::string & name, const int pid, const double px, const double py, const double pz)
PHG4Particlev2() [3/3]
PHG4Particlev2::PHG4Particlev2 (const PHG4Particle * in)
Definition at line 27 of file PHG4Particlev2.cc.
~PHG4Particlev2()
virtual PHG4Particlev2::~PHG4Particlev2 () inline virtual
Definition at line 13 of file PHG4Particlev2.h.
Member Function Documentation
get_e()
double PHG4Particlev2::get_e () const inline virtual
Reimplemented from PHG4Particle.
Definition at line 19 of file PHG4Particlev2.h.
References fe.
get_parent_id()
int PHG4Particlev2::get_parent_id () const inline virtual
Reimplemented from PHG4Particle.
Definition at line 17 of file PHG4Particlev2.h.
References parentid.
get_primary_id()
int PHG4Particlev2::get_primary_id () const inline virtual
Reimplemented from PHG4Particle.
Definition at line 18 of file PHG4Particlev2.h.
References primaryid.
get_track_id()
int PHG4Particlev2::get_track_id () const inline virtual
Reimplemented from PHG4Particle.
Definition at line 15 of file PHG4Particlev2.h.
References trkid.
get_vtx_id()
int PHG4Particlev2::get_vtx_id () const inline virtual
Reimplemented from PHG4Particle.
Definition at line 16 of file PHG4Particlev2.h.
References vtxid.
identify()
void PHG4Particlev2::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4Particlev1.
Definition at line 38 of file PHG4Particlev2.cc.
References fe, PHG4Particlev1::fname, PHG4Particlev1::fpid, PHG4Particlev1::fpx, PHG4Particlev1::fpy, PHG4Particlev1::fpz, parentid, primaryid, trkid, and vtxid.
set_e()
void PHG4Particlev2::set_e (const double e) inline virtual
Reimplemented from PHG4Particle.
Definition at line 28 of file PHG4Particlev2.h.
References fe.
Referenced by PHG4DSTReader::add_particle(), and PHG4TruthTrackingAction::PreUserTrackingAction().
set_parent_id()
void PHG4Particlev2::set_parent_id (const int i) inline virtual
Reimplemented from PHG4Particle.
Definition at line 26 of file PHG4Particlev2.h.
References parentid.
Referenced by PHG4DSTReader::add_particle(), and PHG4TruthTrackingAction::PreUserTrackingAction().
set_primary_id()
void PHG4Particlev2::set_primary_id (const int i) inline virtual
Reimplemented from PHG4Particle.
Definition at line 27 of file PHG4Particlev2.h.
References primaryid.
Referenced by PHG4DSTReader::add_particle(), and PHG4TruthTrackingAction::PreUserTrackingAction().
set_track_id()
void PHG4Particlev2::set_track_id (const int i) inline virtual
Reimplemented from PHG4Particle.
Definition at line 24 of file PHG4Particlev2.h.
References trkid.
Referenced by PHG4DSTReader::add_particle(), and PHG4TruthTrackingAction::PreUserTrackingAction().
set_vtx_id()
void PHG4Particlev2::set_vtx_id (const int i) inline virtual
Reimplemented from PHG4Particle.
Definition at line 25 of file PHG4Particlev2.h.
References vtxid.
Referenced by PHG4DSTReader::add_particle(), and PHG4TruthTrackingAction::PreUserTrackingAction().
Member Data Documentation
fe
double PHG4Particlev2::fe protected
Definition at line 40 of file PHG4Particlev2.h.
Referenced by get_e(), identify(), and set_e().
parentid
int PHG4Particlev2::parentid protected
Definition at line 38 of file PHG4Particlev2.h.
Referenced by get_parent_id(), identify(), and set_parent_id().
primaryid
int PHG4Particlev2::primaryid protected
Definition at line 39 of file PHG4Particlev2.h.
Referenced by get_primary_id(), identify(), and set_primary_id().
trkid
int PHG4Particlev2::trkid protected
Definition at line 36 of file PHG4Particlev2.h.
Referenced by get_track_id(), identify(), and set_track_id().
vtxid
int PHG4Particlev2::vtxid protected
Definition at line 37 of file PHG4Particlev2.h.
Referenced by get_vtx_id(), identify(), and set_vtx_id().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Particlev2.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Particlev2.cc