E1039 Software: PHG4ConeSubsystem Class Reference
PHG4ConeSubsystem Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4ConeSubsystem.h>
Public Member Functions
PHG4ConeSubsystem (const std::string &name="CONE", const int layer=0)
constructor
virtual ~PHG4ConeSubsystem (void)
destructor
int Init (PHCompositeNode *)
init
int process_event (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector (void) const
accessors (reimplemented)
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
void SetR1 (const G4double min, const G4double max)
set inner and outter radius1
void SetR2 (const G4double min, const G4double max)
set inner and outter radius2
void SetZlength (const G4double a)
set length in Z
void SetPhi (const G4double a, const G4double b)
set phi offset and extention
void Set_eta_range (G4double etaMin, G4double etaMax)
set rmaximum and minimums according to the eta range
void SetPlaceZ (const G4double dbl)
void SetPlace (const G4double place_x, const G4double place_y, const G4double place_z)
void SetZRot (const G4double dbl)
void SetMaterial (const std::string &mat)
PHG4EventAction * GetEventAction () const
return pointer to this subsystem event action
void SetActive (const int i=1)
void SuperDetector (const std::string &name)
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4ConeDetector * detector_
detector geometry
PHG4ConeSteppingAction * steppingAction_
particle tracking "stepping" action
PHG4EventAction * eventAction_
G4double place_in_x
G4double place_in_y
G4double place_in_z
G4double rot_in_z
G4double rMin1
G4double rMax1
G4double rMin2
G4double rMax2
G4double dZ
G4double sPhi
G4double dPhi
G4String material
int active
int layer
std::string detector_type
std::string superdetector
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from PHG4Subsystem
bool overlapcheck
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 13 of file PHG4ConeSubsystem.h.
Constructor & Destructor Documentation
PHG4ConeSubsystem()
PHG4ConeSubsystem::PHG4ConeSubsystem (const std::string & name = "CONE", const int layer = 0)
constructor
Definition at line 17 of file PHG4ConeSubsystem.cc.
References Fun4AllBase::Name().
~PHG4ConeSubsystem()
virtual PHG4ConeSubsystem::~PHG4ConeSubsystem (void) inline virtual
destructor
Definition at line 22 of file PHG4ConeSubsystem.h.
References GetDetector(), GetSteppingAction(), Init(), and process_event().
Member Function Documentation
GetDetector()
PHG4Detector * PHG4ConeSubsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 108 of file PHG4ConeSubsystem.cc.
References detector_.
Referenced by ~PHG4ConeSubsystem().
GetEventAction()
PHG4EventAction* PHG4ConeSubsystem::GetEventAction (void) const inline virtual
return pointer to this subsystem event action
Reimplemented from PHG4Subsystem.
Definition at line 72 of file PHG4ConeSubsystem.h.
References eventAction_.
GetSteppingAction()
PHG4SteppingAction * PHG4ConeSubsystem::GetSteppingAction (void) const virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 112 of file PHG4ConeSubsystem.cc.
References steppingAction_.
Referenced by ~PHG4ConeSubsystem().
Init()
int PHG4ConeSubsystem::Init (PHCompositeNode * topNode) virtual
init
creates the detector_ object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from SubsysReco.
Definition at line 48 of file PHG4ConeSubsystem.cc.
References active, PHCompositeNode::addNode(), detector_, detector_type, dPhi, dZ, eventAction_, PHNodeIterator::findFirst(), layer, material, Fun4AllBase::Name(), PHG4Subsystem::overlapcheck, PHG4Detector::OverlapCheck(), place_in_x, place_in_y, place_in_z, rMax1, rMax2, rMin1, rMin2, rot_in_z, PHG4ConeDetector::SetActive(), PHG4ConeDetector::SetMaterial(), PHG4ConeDetector::SetPhi(), PHG4ConeDetector::SetPlace(), PHG4ConeDetector::SetR1(), PHG4ConeDetector::SetR2(), PHG4ConeDetector::SetZlength(), PHG4ConeDetector::SetZRot(), sPhi, steppingAction_, PHG4ConeDetector::SuperDetector(), and superdetector.
Referenced by ~PHG4ConeSubsystem().
process_event()
int PHG4ConeSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 95 of file PHG4ConeSubsystem.cc.
References PHG4ConeSteppingAction::SetInterfacePointers(), and steppingAction_.
Referenced by ~PHG4ConeSubsystem().
Set_eta_range()
void PHG4ConeSubsystem::Set_eta_range (G4double etaMin, G4double etaMax)
set rmaximum and minimums according to the eta range
Definition at line 118 of file PHG4ConeSubsystem.cc.
References dZ, place_in_z, rMax1, rMax2, rMin1, and rMin2.
Referenced by SetPhi().
SetActive()
void PHG4ConeSubsystem::SetActive (const int i = 1) inline
Definition at line 73 of file PHG4ConeSubsystem.h.
References active.
SetMaterial()
void PHG4ConeSubsystem::SetMaterial (const std::string & mat) inline
Definition at line 71 of file PHG4ConeSubsystem.h.
References material.
SetPhi()
void PHG4ConeSubsystem::SetPhi (const G4double a, const G4double b) inline
set phi offset and extention
Definition at line 57 of file PHG4ConeSubsystem.h.
References dPhi, Set_eta_range(), and sPhi.
SetPlace()
void PHG4ConeSubsystem::SetPlace (const G4double place_x, const G4double place_y, const G4double place_z) inline
Definition at line 64 of file PHG4ConeSubsystem.h.
References place_in_x, place_in_y, and place_in_z.
SetPlaceZ()
void PHG4ConeSubsystem::SetPlaceZ (const G4double dbl) inline
Definition at line 63 of file PHG4ConeSubsystem.h.
References place_in_z.
SetR1()
void PHG4ConeSubsystem::SetR1 (const G4double min, const G4double max) inline
set inner and outter radius1
Definition at line 45 of file PHG4ConeSubsystem.h.
References rMax1, and rMin1.
SetR2()
void PHG4ConeSubsystem::SetR2 (const G4double min, const G4double max) inline
set inner and outter radius2
Definition at line 49 of file PHG4ConeSubsystem.h.
References rMax2, and rMin2.
SetZlength()
void PHG4ConeSubsystem::SetZlength (const G4double a) inline
set length in Z
Definition at line 53 of file PHG4ConeSubsystem.h.
References dZ.
SetZRot()
void PHG4ConeSubsystem::SetZRot (const G4double dbl) inline
Definition at line 70 of file PHG4ConeSubsystem.h.
References rot_in_z.
SuperDetector()
void PHG4ConeSubsystem::SuperDetector (const std::string & name) inline
Definition at line 74 of file PHG4ConeSubsystem.h.
References superdetector.
Member Data Documentation
active
int PHG4ConeSubsystem::active private
Definition at line 99 of file PHG4ConeSubsystem.h.
Referenced by Init(), and SetActive().
detector_
PHG4ConeDetector* PHG4ConeSubsystem::detector_ private
detector geometry
defives from PHG4Detector
Definition at line 80 of file PHG4ConeSubsystem.h.
Referenced by GetDetector(), and Init().
detector_type
std::string PHG4ConeSubsystem::detector_type private
Definition at line 101 of file PHG4ConeSubsystem.h.
Referenced by Init().
dPhi
G4double PHG4ConeSubsystem::dPhi private
Definition at line 97 of file PHG4ConeSubsystem.h.
Referenced by Init(), and SetPhi().
dZ
G4double PHG4ConeSubsystem::dZ private
Definition at line 95 of file PHG4ConeSubsystem.h.
Referenced by Init(), Set_eta_range(), and SetZlength().
eventAction_
PHG4EventAction* PHG4ConeSubsystem::eventAction_ private
Definition at line 85 of file PHG4ConeSubsystem.h.
Referenced by GetEventAction(), and Init().
layer
int PHG4ConeSubsystem::layer private
Definition at line 100 of file PHG4ConeSubsystem.h.
Referenced by Init().
material
G4String PHG4ConeSubsystem::material private
Definition at line 98 of file PHG4ConeSubsystem.h.
Referenced by Init(), and SetMaterial().
place_in_x
G4double PHG4ConeSubsystem::place_in_x private
Definition at line 87 of file PHG4ConeSubsystem.h.
Referenced by Init(), and SetPlace().
place_in_y
G4double PHG4ConeSubsystem::place_in_y private
Definition at line 88 of file PHG4ConeSubsystem.h.
Referenced by Init(), and SetPlace().
place_in_z
G4double PHG4ConeSubsystem::place_in_z private
Definition at line 89 of file PHG4ConeSubsystem.h.
Referenced by Init(), Set_eta_range(), SetPlace(), and SetPlaceZ().
rMax1
G4double PHG4ConeSubsystem::rMax1 private
Definition at line 92 of file PHG4ConeSubsystem.h.
Referenced by Init(), Set_eta_range(), and SetR1().
rMax2
G4double PHG4ConeSubsystem::rMax2 private
Definition at line 94 of file PHG4ConeSubsystem.h.
Referenced by Init(), Set_eta_range(), and SetR2().
rMin1
G4double PHG4ConeSubsystem::rMin1 private
Definition at line 91 of file PHG4ConeSubsystem.h.
Referenced by Init(), Set_eta_range(), and SetR1().
rMin2
G4double PHG4ConeSubsystem::rMin2 private
Definition at line 93 of file PHG4ConeSubsystem.h.
Referenced by Init(), Set_eta_range(), and SetR2().
rot_in_z
G4double PHG4ConeSubsystem::rot_in_z private
Definition at line 90 of file PHG4ConeSubsystem.h.
Referenced by Init(), and SetZRot().
sPhi
G4double PHG4ConeSubsystem::sPhi private
Definition at line 96 of file PHG4ConeSubsystem.h.
Referenced by Init(), and SetPhi().
steppingAction_
PHG4ConeSteppingAction* PHG4ConeSubsystem::steppingAction_ private
particle tracking "stepping" action
derives from PHG4SteppingActions
Definition at line 84 of file PHG4ConeSubsystem.h.
Referenced by GetSteppingAction(), Init(), and process_event().
superdetector
std::string PHG4ConeSubsystem::superdetector private
Definition at line 102 of file PHG4ConeSubsystem.h.
Referenced by Init(), and SuperDetector().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4ConeSubsystem.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4ConeSubsystem.cc