E1039 Software: PHG4PhenixEventAction Class Reference
PHG4PhenixEventAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4PhenixEventAction.h>
Public Member Functions
PHG4PhenixEventAction (void)
virtual ~PHG4PhenixEventAction ()
void AddAction (PHG4EventAction *action)
register an action. This is called in PHG4Reco::Init based on which actions are found on the tree
void BeginOfEventAction (const G4Event *)
void EndOfEventAction (const G4Event *)
Private Types
typedef std::list< PHG4EventAction * > ActionList
list of subsystem specific Event actions
Private Attributes
ActionList actions_
PHTimeServer::timer _timer
module timer.
Detailed Description
Definition at line 15 of file PHG4PhenixEventAction.h.
Member Typedef Documentation
ActionList
typedef std::list<PHG4EventAction*> PHG4PhenixEventAction::ActionList private
list of subsystem specific Event actions
Definition at line 34 of file PHG4PhenixEventAction.h.
Constructor & Destructor Documentation
PHG4PhenixEventAction()
PHG4PhenixEventAction::PHG4PhenixEventAction (void)
Definition at line 6 of file PHG4PhenixEventAction.cc.
~PHG4PhenixEventAction()
PHG4PhenixEventAction::~PHG4PhenixEventAction () virtual
Definition at line 10 of file PHG4PhenixEventAction.cc.
References actions_.
Member Function Documentation
AddAction()
void PHG4PhenixEventAction::AddAction (PHG4EventAction * action) inline
register an action. This is called in PHG4Reco::Init based on which actions are found on the tree
Definition at line 24 of file PHG4PhenixEventAction.h.
References actions_, BeginOfEventAction(), and EndOfEventAction().
Referenced by PHG4Reco::InitRun().
BeginOfEventAction()
void PHG4PhenixEventAction::BeginOfEventAction (const G4Event * event)
Definition at line 20 of file PHG4PhenixEventAction.cc.
References _timer, actions_, PHTimeServer::timer::get(), PHTimer::restart(), and VERBOSE.
Referenced by AddAction().
EndOfEventAction()
void PHG4PhenixEventAction::EndOfEventAction (const G4Event * event)
Definition at line 39 of file PHG4PhenixEventAction.cc.
References _timer, actions_, PHTimeServer::timer::get(), PHTimer::stop(), and VERBOSE.
Referenced by AddAction().
Member Data Documentation
_timer
PHTimeServer::timer PHG4PhenixEventAction::_timer private
module timer.
Definition at line 38 of file PHG4PhenixEventAction.h.
Referenced by BeginOfEventAction(), and EndOfEventAction().
actions_
ActionList PHG4PhenixEventAction::actions_ private
Definition at line 35 of file PHG4PhenixEventAction.h.
Referenced by AddAction(), BeginOfEventAction(), EndOfEventAction(), and ~PHG4PhenixEventAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4PhenixEventAction.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4PhenixEventAction.cc