Class Reference for E1039 Core & Analysis Software: KalmanFastTrackletting Class Reference
KalmanFastTrackletting Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/KalmanFastTrackletting.h>
Public Member Functions
KalmanFastTrackletting (const PHField *field, const TGeoManager *geom, bool flag=true)
virtual ~KalmanFastTrackletting ()
virtual int setRawEvent (SRawEvent *event_input)
virtual void buildTrackletsInStation (int stationID, int listID, double *pos_exp=nullptr, double *window=nullptr)
Tracklet finding stuff.
Public Member Functions inherited from KalmanFastTracking
KalmanFastTracking (const PHField *field, const TGeoManager *geom, bool flag=true)
virtual ~KalmanFastTracking ()
void Verbosity (const int a)
int Verbosity () const
void printTimers ()
void setRawEventDebug (SRawEvent *event_input)
bool acceptEvent (SRawEvent *rawEvent)
virtual void buildBackPartialTracks ()
virtual void buildGlobalTracks ()
int fitTracklet (Tracklet &tracklet)
bool acceptTracklet (Tracklet &tracklet)
bool hodoMask (Tracklet &tracklet)
bool muonID_comp (Tracklet &tracklet)
bool muonID_search (Tracklet &tracklet)
bool muonID_hodoAid (Tracklet &tracklet)
void buildPropSegments ()
void resolveLeftRight (SRawEvent::hit_pair hpair, int &LR1, int &LR2)
void resolveLeftRight (Tracklet &tracklet, double threshold)
void resolveSingleLeftRight (Tracklet &tracklet)
void removeBadHits (Tracklet &tracklet)
int reduceTrackletList (std::list< Tracklet > &tracklets)
void getSagittaWindowsInSt1 (Tracklet &tracklet, double *pos_exp, double *window, int st1ID)
void getExtrapoWindowsInSt1 (Tracklet &tracklet, double *pos_exp, double *window, int st1ID)
void printAtDetectorBack (int stationID, std::string outputFileName)
SRecTrack processOneTracklet (Tracklet &tracklet)
Track fitting stuff.
bool fitTrack (KalmanTrack &kmtrk)
void resolveLeftRight (KalmanTrack &kmtrk)
std::list< Tracklet > & getFinalTracklets ()
Final output.
std::list< Tracklet > & getBackPartials ()
std::list< Tracklet > & getTrackletList (int i)
std::list< SRecTrack > & getSRecTracks ()
std::list< PropSegment > & getPropSegments (int i)
void setOutputListIndex (unsigned int i)
Set the index of the final output tracklet list.
void chi2fit (int n, double x[], double y[], double &a, double &b)
Tool, a simple-minded chi square fit.
Additional Inherited Members
Protected Member Functions inherited from KalmanFastTracking
int setRawEventPrep (SRawEvent *event_input)
Protected Attributes inherited from KalmanFastTracking
int verbosity
SRawEvent * rawEvent
std::vector< Hit > hitAll
std::list< Tracklet > trackletsInSt [5]
std::list< SRecTrack > stracks
unsigned int outputListIdx
std::list< PropSegment > propSegs [2]
std::vector< int > detectorIDs_mask [4]
Configurations of tracklet finding.
std::vector< int > detectorIDs_maskX [4]
std::vector< int > detectorIDs_maskY [4]
std::list< int > hitIDs_mask [4]
std::vector< int > detectorIDs_muidHodoAid [2]
std::vector< int > stationIDs_mask [nStations]
int detectorIDs_muid [2][4]
double z_ref_muid [2][4]
std::list< int > hitIDs_muid [2][4]
std::list< int > hitIDs_muidHodoAid [2]
double z_mask [nHodoPlanes+nPropPlanes]
double x_mask_min [nHodoPlanes+nPropPlanes][72]
double x_mask_max [nHodoPlanes+nPropPlanes][72]
double y_mask_min [nHodoPlanes+nPropPlanes][72]
double y_mask_max [nHodoPlanes+nPropPlanes][72]
std::vector< int > superIDs [nChamberPlanes/6+2]
For following part, id = 0, 1, 2, 3, 4, 5, 6 stand for station 0, 1, 2, 3+, 3-, and prop tubes X-Z and Y-Z.
double u_win [nChamberPlanes/6]
double u_costheta [nChamberPlanes/6]
double u_sintheta [nChamberPlanes/6]
double z_plane_x [nChamberPlanes/6]
double z_plane_u [nChamberPlanes/6]
double z_plane_v [nChamberPlanes/6]
double costheta_plane [nChamberPlanes+1]
double sintheta_plane [nChamberPlanes+1]
double z_plane [nChamberPlanes+1]
double slope_max [nChamberPlanes+1]
double intersection_max [nChamberPlanes+1]
double resol_plane [nChamberPlanes+1]
double spacing_plane [nChamberPlanes+1]
int s_detectorID [3]
Tracklet tracklet_curr
ROOT::Math::Minimizer * minimizer [2]
ROOT::Math::Functor fcn
KalmanFitter * kmfitter
GeomSvc * p_geomSvc
const bool enable_KF
std::map< std::string, PHTimer * > _timers
Detailed Description
Definition at line 5 of file KalmanFastTrackletting.h.
Constructor & Destructor Documentation
KalmanFastTrackletting::KalmanFastTrackletting (const PHField * field, const TGeoManager * geom, bool flag = true) explicit
Definition at line 9 of file KalmanFastTrackletting.cxx.
References PHFlag::get_DoubleFlag(), and recoConsts::instance().
KalmanFastTrackletting::~KalmanFastTrackletting () virtual
Definition at line 19 of file KalmanFastTrackletting.cxx.
Member Function Documentation
void KalmanFastTrackletting::buildTrackletsInStation (int stationID, int listID, double * pos_exp = nullptr, double * window = nullptr) virtual
Tracklet finding stuff.
Reimplemented from KalmanFastTracking.
Definition at line 68 of file KalmanFastTrackletting.cxx.
References KalmanFastTracking::fitTracklet(), SRawEvent::getPartialHitPairsInSuperDetector(), KalmanFastTracking::hitAll, Tracklet::hits, Tracklet::isValid(), Tracklet::nUHits, Tracklet::nVHits, Tracklet::nXHits, KalmanFastTracking::rawEvent, Tracklet::sortHits(), KalmanFastTracking::spacing_plane, Tracklet::stationID, KalmanFastTracking::superIDs, KalmanFastTracking::trackletsInSt, KalmanFastTracking::u_costheta, KalmanFastTracking::u_sintheta, KalmanFastTracking::u_win, KalmanFastTracking::z_plane, KalmanFastTracking::z_plane_u, KalmanFastTracking::z_plane_v, and KalmanFastTracking::z_plane_x.
Referenced by setRawEvent().
int KalmanFastTrackletting::setRawEvent (SRawEvent * event_input) virtual
Reimplemented from KalmanFastTracking.
Definition at line 24 of file KalmanFastTrackletting.cxx.
References KalmanFastTracking::_timers, KalmanFastTracking::buildBackPartialTracks(), buildTrackletsInStation(), LogInfo, KalmanFastTracking::setRawEventPrep(), TFEXIT_SUCCESS, KalmanFastTracking::trackletsInSt, and KalmanFastTracking::verbosity.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/KalmanFastTrackletting.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/KalmanFastTrackletting.cxx