Class Reference for E1039 Core & Analysis Software: PHG4CellContainer Class Reference
PHG4CellContainer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CellContainer.h>
Public Types
typedef std::map< PHG4CellDefs::keytype, PHG4Cell * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator, Iterator > Range
typedef std::pair< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHG4CellContainer ()
virtual ~PHG4CellContainer ()
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
ConstIterator AddCell (PHG4Cell *newCell)
ConstIterator AddCellSpecifyKey (const PHG4CellDefs::keytype key, PHG4Cell *newCell)
void RemoveCell (PHG4CellDefs::keytype key)
preferred removal method, key is currently the cell id
void RemoveCell (PHG4Cell *cell)
inefficent, use key where possible instead
Iterator findOrAddCell (PHG4CellDefs::keytype key)
ConstRange getCells (const unsigned short int detid) const
return all Cells matching a given detid
ConstRange getCells (void) const
return all hist
PHG4Cell * findCell (PHG4CellDefs::keytype key)
unsigned int size (void) const
double getTotalEdep () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
Map cellmap
Detailed Description
Definition at line 11 of file PHG4CellContainer.h.
Member Typedef Documentation
ConstIterator
typedef Map::const_iterator PHG4CellContainer::ConstIterator
Definition at line 17 of file PHG4CellContainer.h.
ConstRange
typedef std::pair<ConstIterator, ConstIterator> PHG4CellContainer::ConstRange
Definition at line 19 of file PHG4CellContainer.h.
Iterator
typedef Map::iterator PHG4CellContainer::Iterator
Definition at line 16 of file PHG4CellContainer.h.
Map
typedef std::map<PHG4CellDefs::keytype,PHG4Cell *> PHG4CellContainer::Map
Definition at line 15 of file PHG4CellContainer.h.
Range
typedef std::pair<Iterator, Iterator> PHG4CellContainer::Range
Definition at line 18 of file PHG4CellContainer.h.
Constructor & Destructor Documentation
PHG4CellContainer()
PHG4CellContainer::PHG4CellContainer ()
Definition at line 9 of file PHG4CellContainer.cc.
~PHG4CellContainer()
virtual PHG4CellContainer::~PHG4CellContainer () inline virtual
Definition at line 23 of file PHG4CellContainer.h.
Member Function Documentation
AddCell()
PHG4CellContainer::ConstIterator PHG4CellContainer::AddCell (PHG4Cell * newCell)
Definition at line 37 of file PHG4CellContainer.cc.
References PHG4Cell::get_cellid(), and PHG4CellDefs::get_detid().
Referenced by PHG4BlockCellReco::process_event(), PHG4CylinderCellReco::process_event(), and PHG4CylinderCellTPCReco::process_event().
AddCellSpecifyKey()
PHG4CellContainer::ConstIterator PHG4CellContainer::AddCellSpecifyKey (const PHG4CellDefs::keytype key, PHG4Cell * newCell)
Definition at line 50 of file PHG4CellContainer.cc.
References PHG4Cell::set_cellid().
findCell()
PHG4Cell * PHG4CellContainer::findCell (PHG4CellDefs::keytype key)
Definition at line 96 of file PHG4CellContainer.cc.
findOrAddCell()
PHG4CellContainer::Iterator PHG4CellContainer::findOrAddCell (PHG4CellDefs::keytype key)
Definition at line 82 of file PHG4CellContainer.cc.
References PHG4Cell::set_cellid().
getCells() [1/2]
PHG4CellContainer::ConstRange PHG4CellContainer::getCells (const unsigned short int detid) const
return all Cells matching a given detid
Definition at line 63 of file PHG4CellContainer.cc.
Referenced by PHG4BlockCellReco::CheckEnergy(), and PHG4CylinderCellReco::CheckEnergy().
getCells() [2/2]
PHG4CellContainer::ConstRange PHG4CellContainer::getCells (void) const
return all hist
Definition at line 77 of file PHG4CellContainer.cc.
getTotalEdep()
double PHG4CellContainer::getTotalEdep () const
Definition at line 109 of file PHG4CellContainer.cc.
identify()
void PHG4CellContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 24 of file PHG4CellContainer.cc.
RemoveCell() [1/2]
void PHG4CellContainer::RemoveCell (PHG4Cell * cell) inline
inefficent, use key where possible instead
Definition at line 38 of file PHG4CellContainer.h.
References cellmap.
RemoveCell() [2/2]
void PHG4CellContainer::RemoveCell (PHG4CellDefs::keytype key) inline
preferred removal method, key is currently the cell id
Definition at line 33 of file PHG4CellContainer.h.
References cellmap.
Reset()
void PHG4CellContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 13 of file PHG4CellContainer.cc.
size()
unsigned int PHG4CellContainer::size (void) const inline
Definition at line 66 of file PHG4CellContainer.h.
References cellmap.
Member Data Documentation
cellmap
Map PHG4CellContainer::cellmap protected
Definition at line 72 of file PHG4CellContainer.h.
Referenced by RemoveCell(), and size().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CellContainer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CellContainer.cc