E1039 Software: G4Pythia6Decayer Class Reference
G4Pythia6Decayer Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4decayer/G4Pythia6Decayer.hh>
Public Member Functions
G4Pythia6Decayer ()
virtual ~G4Pythia6Decayer ()
virtual G4DecayProducts * ImportDecayProducts (const G4Track &track)
void ForceDecayType (EDecayType decayType)
void SetVerboseLevel (G4int verboseLevel)
Private Member Functions
G4Pythia6Decayer (const G4Pythia6Decayer &right)
Not implemented.
G4Pythia6Decayer & operator= (const G4Pythia6Decayer &right)
Not implemented.
G4ParticleDefinition * GetParticleDefinition (const Pythia6Particle *p, G4bool warn=true) const
G4DynamicParticle * CreateDynamicParticle (const Pythia6Particle *p) const
G4ThreeVector GetParticlePosition (const Pythia6Particle *particle) const
G4ThreeVector GetParticleMomentum (const Pythia6Particle *particle) const
G4int CountProducts (G4int channel, G4int particle)
void ForceParticleDecay (G4int particle, G4int product, G4int mult)
void ForceParticleDecay (G4int particle, G4int *products, G4int *mult, G4int npart)
void ForceHadronicD ()
void ForceOmega ()
void ForceDecay (EDecayType decayType)
void Decay (G4int pdg, const CLHEP::HepLorentzVector &p)
G4int ImportParticles (ParticleVector *particles)
Private Attributes
G4Pythia6DecayerMessenger fMessenger
command messenger
G4int fVerboseLevel
verbose level
EDecayType fDecayType
selected decay type
ParticleVector * fDecayProductsArray
array of decay products
Static Private Attributes
static const EDecayType fgkDefaultDecayType = kAll
default decay type
Detailed Description
Pythia6 decayer
Implements the G4VExtDecayer abstract class using the Pythia6 interface. According to TPythia6Decayer class in Root: http://root.cern.ch/ see http://root.cern.ch/root/License.html
Definition at line 54 of file G4Pythia6Decayer.hh.
Constructor & Destructor Documentation
G4Pythia6Decayer() [1/2]
G4Pythia6Decayer::G4Pythia6Decayer ()
Standard constructor
Definition at line 55 of file G4Pythia6Decayer.cc.
References fDecayProductsArray, fDecayType, and ForceDecay().
Referenced by SetVerboseLevel().
~G4Pythia6Decayer()
G4Pythia6Decayer::~G4Pythia6Decayer () virtual
Destructor
Definition at line 71 of file G4Pythia6Decayer.cc.
References fDecayProductsArray, and GetParticleDefinition().
G4Pythia6Decayer() [2/2]
G4Pythia6Decayer::G4Pythia6Decayer (const G4Pythia6Decayer & right) private
Not implemented.
Member Function Documentation
CountProducts()
G4int G4Pythia6Decayer::CountProducts (G4int channel, G4int particle) private
Count number of decay products
Definition at line 160 of file G4Pythia6Decayer.cc.
References Pythia6::Instance().
Referenced by ForceParticleDecay(), and SetVerboseLevel().
CreateDynamicParticle()
G4DynamicParticle * G4Pythia6Decayer::CreateDynamicParticle (const Pythia6Particle * p) const private
Create G4DynamicParticle.
Definition at line 112 of file G4Pythia6Decayer.cc.
References GetParticleDefinition(), and GetParticleMomentum().
Referenced by ImportDecayProducts(), and SetVerboseLevel().
Decay()
void G4Pythia6Decayer::Decay (G4int pdg, const CLHEP::HepLorentzVector & p) private
Decay a particle of type IDPART (PDG code) and momentum P.
Definition at line 517 of file G4Pythia6Decayer.cc.
References Pythia6::Instance(), and Pythia6::Py1ent().
Referenced by ImportDecayProducts(), and SetVerboseLevel().
ForceDecay()
void G4Pythia6Decayer::ForceDecay (EDecayType decayType) private
Force a particle decay mode
Definition at line 315 of file G4Pythia6Decayer.cc.
References fDecayType, ForceHadronicD(), ForceOmega(), ForceParticleDecay(), Pythia6::Instance(), kAll, kBJpsi, kBJpsiDiElectron, kBJpsiDiMuon, kBPsiPrimeDiElectron, kBPsiPrimeDiMuon, kDiElectron, kDiMuon, kHadronicD, kHardMuons, kKaToMu, kMaxDecay, kNoDecay, kNoDecayHeavy, kOmega, kPhiKK, kPiToMu, kSemiElectronic, kSemiMuonic, kWToCharm, kWToCharmToMuon, kWToMuon, kZDiMuon, and Pythia6::SetMSTJ().
Referenced by ForceDecayType(), G4Pythia6Decayer(), and SetVerboseLevel().
ForceDecayType()
void G4Pythia6Decayer::ForceDecayType (EDecayType decayType)
Force a given decay type
Definition at line 618 of file G4Pythia6Decayer.cc.
References fDecayType, and ForceDecay().
Referenced by P6DExtDecayerPhysics::ConstructProcess(), and G4Pythia6DecayerMessenger::SetNewValue().
ForceHadronicD()
void G4Pythia6Decayer::ForceHadronicD () private
Force golden D decay modes
Definition at line 226 of file G4Pythia6Decayer.cc.
References ForceParticleDecay(), Pythia6::GetKFDP(), Pythia6::GetMDCY(), Pythia6::Instance(), Pythia6::Pycomp(), Pythia6::SetMDCY(), and Pythia6::SetMDME().
Referenced by ForceDecay(), and SetVerboseLevel().
ForceOmega()
void G4Pythia6Decayer::ForceOmega () private
Force Omega -> Lambda K- Decay
Definition at line 288 of file G4Pythia6Decayer.cc.
References Pythia6::GetKFDP(), Pythia6::GetMDCY(), Pythia6::Instance(), Pythia6::Pycomp(), Pythia6::SetMDCY(), and Pythia6::SetMDME().
Referenced by ForceDecay(), and SetVerboseLevel().
ForceParticleDecay() [1/2]
void G4Pythia6Decayer::ForceParticleDecay (G4int particle, G4int product, G4int mult) private
Force decay of particle into products with multiplicity mult
Definition at line 174 of file G4Pythia6Decayer.cc.
References CountProducts(), Pythia6::GetMDCY(), Pythia6::Instance(), Pythia6::Pycomp(), Pythia6::SetMDCY(), and Pythia6::SetMDME().
Referenced by ForceDecay(), ForceHadronicD(), and SetVerboseLevel().
ForceParticleDecay() [2/2]
void G4Pythia6Decayer::ForceParticleDecay (G4int particle, G4int * products, G4int * mult, G4int npart) private
Force decay of particle into products with multiplicity mult
Definition at line 199 of file G4Pythia6Decayer.cc.
References CountProducts(), Pythia6::GetMDCY(), Pythia6::Instance(), Pythia6::Pycomp(), Pythia6::SetMDCY(), and Pythia6::SetMDME().
GetParticleDefinition()
G4ParticleDefinition * G4Pythia6Decayer::GetParticleDefinition (const Pythia6Particle * p, G4bool warn = true) const private
Return G4 particle definition for given TParticle
Definition at line 86 of file G4Pythia6Decayer.cc.
References Pythia6Particle::fKF.
Referenced by CreateDynamicParticle(), SetVerboseLevel(), and ~G4Pythia6Decayer().
GetParticleMomentum()
G4ThreeVector G4Pythia6Decayer::GetParticleMomentum (const Pythia6Particle * particle) const private
Return particle momentum.
Definition at line 146 of file G4Pythia6Decayer.cc.
References Pythia6Particle::fPx, Pythia6Particle::fPy, and Pythia6Particle::fPz.
Referenced by CreateDynamicParticle(), and SetVerboseLevel().
GetParticlePosition()
G4ThreeVector G4Pythia6Decayer::GetParticlePosition (const Pythia6Particle * particle) const private
Return particle vertex position.
Definition at line 132 of file G4Pythia6Decayer.cc.
References Pythia6Particle::fVx, Pythia6Particle::fVy, and Pythia6Particle::fVz.
Referenced by SetVerboseLevel().
ImportDecayProducts()
G4DecayProducts * G4Pythia6Decayer::ImportDecayProducts (const G4Track & track) virtual
Import decay products
Definition at line 539 of file G4Pythia6Decayer.cc.
References CreateDynamicParticle(), Decay(), fDecayProductsArray, Pythia6Particle::fKF, Pythia6Particle::fKS, fVerboseLevel, and ImportParticles().
ImportParticles()
G4int G4Pythia6Decayer::ImportParticles (ParticleVector * particles) private
Get the decay products into the passed PARTICLES vector
Definition at line 526 of file G4Pythia6Decayer.cc.
References Pythia6::ImportParticles(), and Pythia6::Instance().
Referenced by ImportDecayProducts(), and SetVerboseLevel().
operator=()
G4Pythia6Decayer& G4Pythia6Decayer::operator= (const G4Pythia6Decayer & right) private
Not implemented.
Referenced by SetVerboseLevel().
SetVerboseLevel()
void G4Pythia6Decayer::SetVerboseLevel (G4int verboseLevel) inline
Definition at line 64 of file G4Pythia6Decayer.hh.
References CountProducts(), CreateDynamicParticle(), Decay(), ForceDecay(), ForceHadronicD(), ForceOmega(), ForceParticleDecay(), fVerboseLevel, G4Pythia6Decayer(), GetParticleDefinition(), GetParticleMomentum(), GetParticlePosition(), ImportParticles(), and operator=().
Referenced by P6DExtDecayerPhysics::ConstructProcess(), and G4Pythia6DecayerMessenger::SetNewValue().
Member Data Documentation
fDecayProductsArray
ParticleVector* G4Pythia6Decayer::fDecayProductsArray private
array of decay products
Definition at line 96 of file G4Pythia6Decayer.hh.
Referenced by G4Pythia6Decayer(), ImportDecayProducts(), and ~G4Pythia6Decayer().
fDecayType
EDecayType G4Pythia6Decayer::fDecayType private
selected decay type
Definition at line 95 of file G4Pythia6Decayer.hh.
Referenced by ForceDecay(), ForceDecayType(), and G4Pythia6Decayer().
fgkDefaultDecayType
const EDecayType G4Pythia6Decayer::fgkDefaultDecayType = kAll static private
default decay type
Definition at line 91 of file G4Pythia6Decayer.hh.
fMessenger
G4Pythia6DecayerMessenger G4Pythia6Decayer::fMessenger private
command messenger
Definition at line 93 of file G4Pythia6Decayer.hh.
fVerboseLevel
G4int G4Pythia6Decayer::fVerboseLevel private
verbose level
Definition at line 94 of file G4Pythia6Decayer.hh.
Referenced by ImportDecayProducts(), and SetVerboseLevel().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4decayer/G4Pythia6Decayer.hh
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4decayer/G4Pythia6Decayer.cc