Class Reference for E1039 Core & Analysis Software: PHFieldConfig_v3 Class Reference
PHFieldConfig_v3 Class Reference
PHFieldConfig_v3 implements field configuration information for input a field map file.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig_v3.h>
Public Member Functions
PHFieldConfig_v3 (const std::string &filename1, const std::string &filename2, const double scale1=1.0, const double scale2=1.0, const double targetmag_y=5.0)
PHFieldConfig_v3 ()
default constructor for ROOT file IO
virtual ~PHFieldConfig_v3 ()
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
FieldConfigTypes get_field_config () const
void set_field_config (FieldConfigTypes fieldConfig)
const std::string & get_filename1 () const
field value in Tesla for target field model ONLY for PHFieldConfig_v3
void set_filename1 (const std::string &filename)
const std::string & get_filename2 () const
void set_filename2 (const std::string &filename)
double get_magfield_rescale1 () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
double get_magfield_rescale2 () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
double get_taregetmag_y () const
field value in Tesla for target field model ONLY for PHFieldConfig_v3
void set_taregetmag_y (double taregetmagY)
field value in Tesla for target field model ONLY for PHFieldConfig_v3
Public Member Functions inherited from PHFieldConfig
virtual ~PHFieldConfig ()
std::string get_field_config_description () const
virtual const std::string & get_filename () const
virtual void set_filename (const std::string &filename)
virtual double get_magfield_rescale () const
virtual void set_magfield_rescale (double magfieldRescale)
virtual double get_field_mag_x () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_x (double fieldMagX)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_y () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_y (double fieldMagY)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_z () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_z (double fieldMagZ)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
FieldConfigTypes field_config_
std::string filename1_
std::string filename2_
double scale1_
double scale2_
double _taregetmag_y
Additional Inherited Members
Public Types inherited from PHFieldConfig
enum FieldConfigTypes {
kFieldUniform = 0 , kField2D = 2 , kField3DCylindrical = 3 , kField3DCartesian = 1 ,
RegionalConst = 4 , kFieldSeaQuest = 5 , kFieldInvalid = 9999
}
Protected Member Functions inherited from PHFieldConfig
PHFieldConfig ()
pure virtual interface class. not for direct use
Static Protected Attributes inherited from PHFieldConfig
static const std::string kInvalid_FileName
Detailed Description
PHFieldConfig_v3 implements field configuration information for input a field map file.
Definition at line 19 of file PHFieldConfig_v3.h.
Constructor & Destructor Documentation
PHFieldConfig_v3() [1/2]
PHFieldConfig_v3::PHFieldConfig_v3 (const std::string & filename1, const std::string & filename2, const double scale1 = 1.0, const double scale2 = 1.0, const double targetmag_y = 5.0)
Definition at line 24 of file PHFieldConfig_v3.cc.
References _taregetmag_y, filename1_, scale1_, and scale2_.
PHFieldConfig_v3() [2/2]
PHFieldConfig_v3::PHFieldConfig_v3 () inline
default constructor for ROOT file IO
Definition at line 30 of file PHFieldConfig_v3.h.
References PHFieldConfig_v3().
Referenced by clone(), and PHFieldConfig_v3().
~PHFieldConfig_v3()
PHFieldConfig_v3::~PHFieldConfig_v3 () virtual
Definition at line 46 of file PHFieldConfig_v3.cc.
Member Function Documentation
clone()
PHObject * PHFieldConfig_v3::clone () const virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 52 of file PHFieldConfig_v3.cc.
References PHFieldConfig_v3().
get_field_config()
FieldConfigTypes PHFieldConfig_v3::get_field_config () const inline virtual
Reimplemented from PHFieldConfig.
Definition at line 52 of file PHFieldConfig_v3.h.
References field_config_.
get_filename1()
const std::string& PHFieldConfig_v3::get_filename1 () const inline virtual
field value in Tesla for target field model ONLY for PHFieldConfig_v3
field value in Tesla for target field model ONLY for PHFieldConfig_v3 ONLY for PHFieldConfig_v3
Reimplemented from PHFieldConfig.
Definition at line 61 of file PHFieldConfig_v3.h.
References filename1_.
Referenced by identify().
get_filename2()
const std::string& PHFieldConfig_v3::get_filename2 () const inline virtual
Reimplemented from PHFieldConfig.
Definition at line 71 of file PHFieldConfig_v3.h.
References filename2_.
Referenced by identify().
get_magfield_rescale1()
double PHFieldConfig_v3::get_magfield_rescale1 () const inline virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
Reimplemented from PHFieldConfig.
Definition at line 81 of file PHFieldConfig_v3.h.
References scale1_.
Referenced by identify().
get_magfield_rescale2()
double PHFieldConfig_v3::get_magfield_rescale2 () const inline virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
Reimplemented from PHFieldConfig.
Definition at line 85 of file PHFieldConfig_v3.h.
References scale2_.
Referenced by identify().
get_taregetmag_y()
double PHFieldConfig_v3::get_taregetmag_y () const inline virtual
field value in Tesla for target field model ONLY for PHFieldConfig_v3
Reimplemented from PHFieldConfig.
Definition at line 89 of file PHFieldConfig_v3.h.
References _taregetmag_y.
Referenced by identify().
identify()
void PHFieldConfig_v3::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHFieldConfig.
Definition at line 60 of file PHFieldConfig_v3.cc.
References _taregetmag_y, PHFieldConfig::get_field_config_description(), get_filename1(), get_filename2(), get_magfield_rescale1(), get_magfield_rescale2(), get_taregetmag_y(), isValid(), scale1_, and scale2_.
isValid()
int PHFieldConfig_v3::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHFieldConfig.
Definition at line 81 of file PHFieldConfig_v3.cc.
References filename1_, and filename2_.
Referenced by identify().
Reset()
void PHFieldConfig_v3::Reset () virtual
Clear Event.
Reimplemented from PHFieldConfig.
Definition at line 76 of file PHFieldConfig_v3.cc.
set_field_config()
void PHFieldConfig_v3::set_field_config (FieldConfigTypes fieldConfig) inline virtual
Reimplemented from PHFieldConfig.
Definition at line 56 of file PHFieldConfig_v3.h.
References field_config_.
set_filename1()
void PHFieldConfig_v3::set_filename1 (const std::string & filename) inline
Definition at line 66 of file PHFieldConfig_v3.h.
References filename1_.
set_filename2()
void PHFieldConfig_v3::set_filename2 (const std::string & filename) inline
Definition at line 76 of file PHFieldConfig_v3.h.
References filename2_.
set_taregetmag_y()
void PHFieldConfig_v3::set_taregetmag_y (double fieldMagX) inline virtual
field value in Tesla for target field model ONLY for PHFieldConfig_v3
Reimplemented from PHFieldConfig.
Definition at line 93 of file PHFieldConfig_v3.h.
References _taregetmag_y.
Member Data Documentation
_taregetmag_y
double PHFieldConfig_v3::_taregetmag_y protected
Definition at line 103 of file PHFieldConfig_v3.h.
Referenced by get_taregetmag_y(), identify(), PHFieldConfig_v3(), and set_taregetmag_y().
field_config_
FieldConfigTypes PHFieldConfig_v3::field_config_ protected
Definition at line 98 of file PHFieldConfig_v3.h.
Referenced by get_field_config(), and set_field_config().
filename1_
std::string PHFieldConfig_v3::filename1_ protected
Definition at line 99 of file PHFieldConfig_v3.h.
Referenced by get_filename1(), isValid(), PHFieldConfig_v3(), and set_filename1().
filename2_
std::string PHFieldConfig_v3::filename2_ protected
Definition at line 100 of file PHFieldConfig_v3.h.
Referenced by get_filename2(), isValid(), and set_filename2().
scale1_
double PHFieldConfig_v3::scale1_ protected
Definition at line 101 of file PHFieldConfig_v3.h.
Referenced by get_magfield_rescale1(), identify(), and PHFieldConfig_v3().
scale2_
double PHFieldConfig_v3::scale2_ protected
Definition at line 102 of file PHFieldConfig_v3.h.
Referenced by get_magfield_rescale2(), identify(), and PHFieldConfig_v3().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig_v3.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig_v3.cc