Class Reference for E1039 Core & Analysis Software: PHGeomTGeo Class Reference
PHGeomTGeo Class Reference
PHGeomTGeo provide run-time access to TGeoManger. It is transient object and it shall NOT be saved to DST. For DST storage, please use PHGeomIOTGeo For operation of this class with DST node, please use PHGeomUtility.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHGeometry/PHGeomTGeo.h>
Public Member Functions
PHGeomTGeo ()
virtual ~PHGeomTGeo ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
void SetGeometry (TGeoManager *g)
TGeoManager * GetGeometry ()
bool ConsistencyCheck () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
TGeoManager * _fGeom
store and stream the full geometry via DST objects
Detailed Description
PHGeomTGeo provide run-time access to TGeoManger. It is transient object and it shall NOT be saved to DST. For DST storage, please use PHGeomIOTGeo For operation of this class with DST node, please use PHGeomUtility.
Definition at line 24 of file PHGeomTGeo.h.
Constructor & Destructor Documentation
PHGeomTGeo()
PHGeomTGeo::PHGeomTGeo ()
Definition at line 22 of file PHGeomTGeo.cc.
~PHGeomTGeo()
PHGeomTGeo::~PHGeomTGeo () virtual
Definition at line 28 of file PHGeomTGeo.cc.
References ConsistencyCheck(), and Reset().
Member Function Documentation
ConsistencyCheck()
bool PHGeomTGeo::ConsistencyCheck () const
Since ROOT force TGeoManager is a unique object via global pointer gGeoManager, this function checks whether _fGeom is still the current gGeoManager which avoids operates on an invalid pointer
Definition at line 112 of file PHGeomTGeo.cc.
References _fGeom, and NULL.
Referenced by GetGeometry(), identify(), isValid(), Reset(), SetGeometry(), and ~PHGeomTGeo().
GetGeometry()
TGeoManager * PHGeomTGeo::GetGeometry ()
Definition at line 53 of file PHGeomTGeo.cc.
References _fGeom, ConsistencyCheck(), and NULL.
Referenced by PHGeomUtility::GetTGeoManager(), PHGeomUtility::ImportCurrentTGeoManager(), PHGeomUtility::ImportGeomFile(), and PHGeomUtility::UpdateIONode().
identify()
void PHGeomTGeo::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 72 of file PHGeomTGeo.cc.
References _fGeom, and ConsistencyCheck().
isValid()
int PHGeomTGeo::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 100 of file PHGeomTGeo.cc.
References _fGeom, ConsistencyCheck(), and NULL.
Referenced by PHGeomUtility::GetTGeoManager(), PHGeomUtility::ImportCurrentTGeoManager(), SQReco::InitGeom(), and PHGeomUtility::UpdateIONode().
Reset()
void PHGeomTGeo::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 86 of file PHGeomTGeo.cc.
References _fGeom, ConsistencyCheck(), and NULL.
Referenced by PHGeomUtility::ImportGeomFile(), and ~PHGeomTGeo().
SetGeometry()
void PHGeomTGeo::SetGeometry (TGeoManager * g)
Assign TGeoManager object. Once assigned, the TGeoManager will be locked to avoid a second TGeoManager override gGeoManager and lead to an invalid PHGeomTGeo The pointer TGeoManager should be the current gGeoManager
Definition at line 35 of file PHGeomTGeo.cc.
References _fGeom, ConsistencyCheck(), and NULL.
Referenced by PHGeomUtility::ImportCurrentTGeoManager(), PHGeomUtility::ImportGeomFile(), and PHGeomUtility::LoadFromIONode().
Member Data Documentation
_fGeom
TGeoManager* PHGeomTGeo::_fGeom protected
store and stream the full geometry via DST objects
Definition at line 58 of file PHGeomTGeo.h.
Referenced by ConsistencyCheck(), GetGeometry(), identify(), isValid(), Reset(), and SetGeometry().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHGeometry/PHGeomTGeo.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHGeometry/PHGeomTGeo.cc