SeaQuest Offline Software: PHG4SectorSubsystem Class Reference
PHG4SectorSubsystem Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SectorSubsystem.h>
Public Member Functions
PHG4SectorSubsystem (const std::string &name="Sector")
constructor
virtual ~PHG4SectorSubsystem (void)
destructor
int Init (PHCompositeNode *)
init
int process_event (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector (void) const
accessors (reimplemented)
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
PHG4EventAction * GetEventAction () const
return pointer to this subsystem event action
void SuperDetector (const std::string &name)
PHG4Sector::Sector_Geometry & get_geometry ()
geometry manager PHG4Sector::Sector_Geometry
void set_geometry (PHG4Sector::Sector_Geometry g)
geometry manager PHG4Sector::Sector_Geometry
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4SectorDetector * detector_
detector geometry
PHG4SectorSteppingAction * steppingAction_
particle tracking "stepping" action
PHG4EventAction * eventAction_
std::string superdetector
PHG4Sector::Sector_Geometry geom
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from PHG4Subsystem
bool overlapcheck
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 12 of file PHG4SectorSubsystem.h.
Constructor & Destructor Documentation
PHG4SectorSubsystem::PHG4SectorSubsystem (const std::string & name = "Sector")
constructor
Definition at line 16 of file PHG4SectorSubsystem.cc.
virtual PHG4SectorSubsystem::~PHG4SectorSubsystem (void) inline virtual
destructor
Definition at line 22 of file PHG4SectorSubsystem.h.
Member Function Documentation
PHG4Sector::Sector_Geometry& PHG4SectorSubsystem::get_geometry () inline
geometry manager PHG4Sector::Sector_Geometry
Definition at line 58 of file PHG4SectorSubsystem.h.
References geom.
PHG4Detector * PHG4SectorSubsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 82 of file PHG4SectorSubsystem.cc.
References detector_.
PHG4EventAction* PHG4SectorSubsystem::GetEventAction (void) const inline virtual
return pointer to this subsystem event action
Reimplemented from PHG4Subsystem.
Definition at line 48 of file PHG4SectorSubsystem.h.
References eventAction_.
PHG4SteppingAction * PHG4SectorSubsystem::GetSteppingAction (void) const virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 89 of file PHG4SectorSubsystem.cc.
References steppingAction_.
int PHG4SectorSubsystem::Init (PHCompositeNode * topNode) virtual
init
creates the detector_ object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from SubsysReco.
Definition at line 25 of file PHG4SectorSubsystem.cc.
References PHCompositeNode::addNode(), detector_, eventAction_, PHNodeIterator::findFirst(), geom, PHG4Sector::PHG4SectorConstructor::geom, PHG4Sector::Sector_Geometry::GetNumActiveLayers(), Fun4AllBase::Name(), PHG4Subsystem::overlapcheck, PHG4SectorDetector::OverlapCheck(), steppingAction_, PHG4SectorDetector::SuperDetector(), and superdetector.
int PHG4SectorSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 69 of file PHG4SectorSubsystem.cc.
References PHG4SectorSteppingAction::SetInterfacePointers(), and steppingAction_.
void PHG4SectorSubsystem::set_geometry (PHG4Sector::Sector_Geometry g) inline
geometry manager PHG4Sector::Sector_Geometry
Definition at line 65 of file PHG4SectorSubsystem.h.
References geom.
void PHG4SectorSubsystem::SuperDetector (const std::string & name) inline
Definition at line 51 of file PHG4SectorSubsystem.h.
References superdetector.
Member Data Documentation
PHG4SectorDetector* PHG4SectorSubsystem::detector_ private
detector geometry
defives from PHG4Detector
Definition at line 74 of file PHG4SectorSubsystem.h.
Referenced by GetDetector(), and Init().
PHG4EventAction* PHG4SectorSubsystem::eventAction_ private
Definition at line 80 of file PHG4SectorSubsystem.h.
Referenced by GetEventAction(), and Init().
PHG4Sector::Sector_Geometry PHG4SectorSubsystem::geom private
Definition at line 84 of file PHG4SectorSubsystem.h.
Referenced by get_geometry(), Init(), and set_geometry().
PHG4SectorSteppingAction* PHG4SectorSubsystem::steppingAction_ private
particle tracking "stepping" action
derives from PHG4SteppingActions
Definition at line 78 of file PHG4SectorSubsystem.h.
Referenced by GetSteppingAction(), Init(), and process_event().
std::string PHG4SectorSubsystem::superdetector private
Definition at line 82 of file PHG4SectorSubsystem.h.
Referenced by Init(), and SuperDetector().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SectorSubsystem.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SectorSubsystem.cc