E1039 Software: CalibEvtQual Class Reference
CalibEvtQual Class Reference
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/online/decoder_maindaq/CalibEvtQual.h>
Public Member Functions
CalibEvtQual (const std::string &name="CalibEvtQual")
virtual ~CalibEvtQual ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum EventErrorFlag_t {
ERR_N_TDC = 0x001, ERR_V1495 = 0x002, ERR_N_V1495_0 = 0x004, ERR_N_V1495_2 = 0x008,
ERR_N_TRIGB_0 = 0x010, ERR_N_TRIGB_2 = 0x020, ERR_N_TRIGC_0 = 0x040, ERR_N_TRIGC_2 = 0x080,
ERR_N_QIE_0 = 0x100, ERR_N_QIE_2 = 0x200
}
Private Member Functions
void PrintEvent (SQEvent *evt)
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 7 of file CalibEvtQual.h.
Member Enumeration Documentation
enum CalibEvtQual::EventErrorFlag_t private
Error flags to be inserted to the "Event.dataQuality" field. We should add more types. Ref: https://cdcvs.fnal.gov/redmine/projects/seaquest-production/wiki/Data_Quality_in_our_Productions
Enumerator
ERR_N_TDC
ERR_V1495
ERR_N_V1495_0
ERR_N_V1495_2
ERR_N_TRIGB_0
ERR_N_TRIGB_2
ERR_N_TRIGC_0
ERR_N_TRIGC_2
ERR_N_QIE_0
ERR_N_QIE_2
Definition at line 12 of file CalibEvtQual.h.
Constructor & Destructor Documentation
CalibEvtQual::CalibEvtQual (const std::string & name = "CalibEvtQual")
Definition at line 10 of file CalibEvtQual.cc.
virtual CalibEvtQual::~CalibEvtQual () inline virtual
Definition at line 29 of file CalibEvtQual.h.
Member Function Documentation
int CalibEvtQual::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 61 of file CalibEvtQual.cc.
References Fun4AllReturnCodes::EVENT_OK.
int CalibEvtQual::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 15 of file CalibEvtQual.cc.
References Fun4AllReturnCodes::EVENT_OK.
int CalibEvtQual::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 20 of file CalibEvtQual.cc.
References Fun4AllReturnCodes::EVENT_OK.
void CalibEvtQual::PrintEvent (SQEvent * evt) private
Definition at line 66 of file CalibEvtQual.cc.
References SQEvent::get_coda_event_id(), SQEvent::get_data_quality(), SQEvent::get_event_id(), SQEvent::get_run_id(), SQEvent::get_spill_id(), and SQEvent::get_vme_time().
int CalibEvtQual::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 25 of file CalibEvtQual.cc.
References Fun4AllReturnCodes::ABORTEVENT, ERR_N_QIE_0, ERR_N_QIE_2, ERR_N_TDC, ERR_N_TRIGB_0, ERR_N_TRIGB_2, ERR_N_TRIGC_0, ERR_N_TRIGC_2, ERR_N_V1495_0, ERR_N_V1495_2, and Fun4AllReturnCodes::EVENT_OK.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/online/decoder_maindaq/CalibEvtQual.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/online/decoder_maindaq/CalibEvtQual.cc