Class Reference for E1039 Core & Analysis Software: SQTruthVertexing Class Reference
SQTruthVertexing Class Reference
An SubsysReco module to create create dimuons based on the truth vertex information.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQTruthVertexing.h>
Public Member Functions
SQTruthVertexing (const std::string &name="SQTruthVertexing")
~SQTruthVertexing ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_legacy_rec_container (const bool enable=true)
void set_vtx_smearing (const double r)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
An SubsysReco module to create create dimuons based on the truth vertex information.
This module adds the following information depending on the container type of the reconstruction info
SRecDimuon based on either the truth dimuon info, or random compbination of all available dimuon paris
SRecTrack, if is matched to a true track, its single muon vertex information (pos/mom/chi2) will be updated with truth vertex information
In all reconstruction-related modules, two different container mode is supported:
legacy mode: all the reconstructed tracks (SRecTrack) and dimuons (SRecDimuon) are stored inside a SRecEvent node which internally maintains vectors of all tracks and dimuons
Fun4All-style mode: container node SQTrackVector and SQDimuonVector are used to store the reconstructed tracks and dimuons. The access interface is the same as other fun4all containers like SQHitVector
Since this module relies on the existence of SQTrack and its correlation with SRecTrack, it needs to be added after TruthNodeMaker otherwise it will throw ABORT in InitRun().
Typical usage looks like this:
SQTruthVertexing* truthvtx = new SQTruthVertexing(); truthvtx->set_legacy_rec_container(false); // set the rec info container type like mentioned above, default is true truthvtx->set_vtx_smearing(50.); // smear the truth z_vertex to mimic resolution effect, default is 0. se->registerSubsystem(truthvtx);
Definition at line 39 of file SQTruthVertexing.h.
Constructor & Destructor Documentation
SQTruthVertexing::SQTruthVertexing (const std::string & name = "SQTruthVertexing")
Definition at line 19 of file SQTruthVertexing.cxx.
SQTruthVertexing::~SQTruthVertexing ()
Definition at line 30 of file SQTruthVertexing.cxx.
Member Function Documentation
int SQTruthVertexing::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 129 of file SQTruthVertexing.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int SQTruthVertexing::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 33 of file SQTruthVertexing.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int SQTruthVertexing::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 38 of file SQTruthVertexing.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int SQTruthVertexing::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 51 of file SQTruthVertexing.cxx.
References SQTrackVector::at(), SQDimuonVector::at(), Fun4AllReturnCodes::EVENT_OK, SQDimuon::get_pos(), SQTrack::get_pos_vtx(), SQTrack::get_rec_track_id(), SQTrack::get_track_id(), SQDimuon::get_track_id_neg(), SQDimuon::get_track_id_pos(), SRecTrack::getCharge(), SRecEvent::getNDimuons(), SRecEvent::getNTracks(), SRecEvent::getTrack(), SRecEvent::insertDimuon(), SQDimuonVector::push_back(), SQDimuon::set_rec_dimuon_id(), SQDimuonVector::size(), SQTrackVector::size(), SRecDimuon::trackID_neg, and SRecDimuon::trackID_pos.
void SQTruthVertexing::set_legacy_rec_container (const bool enable = true) inline
Definition at line 50 of file SQTruthVertexing.h.
Referenced by RecoE1039Sim().
void SQTruthVertexing::set_vtx_smearing (const double r) inline
Definition at line 51 of file SQTruthVertexing.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQTruthVertexing.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQTruthVertexing.cxx