Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/macros/UploadCalibParam.C File Reference
UploadCalibParam.C File Reference
Functions
int UploadCalibParam (const std::string type="xt_curve", const std::string map_id="e906run28740")
UploadCalibParam.C: Macro to upload the calibration parameter from tsv file to MySQL DB.
int CheckCalibParam (const std::string type="xt_curve", const int run=25000)
Function Documentation
int CheckCalibParam (const std::string type = "xt_curve", const int run = 25000)
Definition at line 29 of file UploadCalibParam.C.
References RunParamBase::ReadFromDB(), run(), RunParamBase::SetMapIDbyDB(), and RunParamBase::WriteToLocalFile().
int UploadCalibParam (const std::string type = "xt_curve", const std::string map_id = "e906run28740")
UploadCalibParam.C: Macro to upload the calibration parameter from tsv file to MySQL DB.
Usage: .L UploadCalibParam.C UploadCalibParam("xt_curve", "e906run28740"); CheckCalibParam ("xt_curve", 25000);
Definition at line 10 of file UploadCalibParam.C.
References RunParamBase::ReadFromFile(), RunParamBase::SetMapIDbyFile(), RunParamBase::WriteRangeToDB(), and RunParamBase::WriteToDB().