E1039 Software: PHNode Class Reference
PHNode Class Reference abstract
#include </home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHNode.h>
Public Member Functions
PHNode (const std::string &)
PHNode (const std::string &, const std::string &)
virtual ~PHNode ()
PHNode * getParent () const
PHBoolean isPersistent () const
void makePersistent ()
const std::string getObjectType () const
const std::string getType () const
const std::string getName () const
const std::string getClass () const
void setParent (PHNode *p)
void setName (const std::string &n)
void setObjectType (const std::string &type)
virtual void prune ()=0
virtual void print (const std::string &)=0
virtual void forgetMe (PHNode *)=0
virtual bool write (PHIOManager *, const std::string &="")=0
virtual void setResetFlag (const int val)
virtual PHBoolean getResetFlag () const
void makeTransient ()
Protected Member Functions
PHNode ()
PHNode (const PHNode &)
PHNode & operator= (const PHNode &)
Protected Attributes
PHNode * parent
bool persistent
std::string type
std::string objecttype
std::string name
std::string objectclass
bool reset_able
Detailed Description
Definition at line 14 of file PHNode.h.
Constructor & Destructor Documentation
PHNode() [1/4]
PHNode::PHNode (const std::string & n)
Definition at line 19 of file PHNode.cc.
References name, and PHWHERE.
PHNode() [2/4]
PHNode::PHNode (const std::string & n, const std::string & typ)
Definition at line 35 of file PHNode.cc.
References name, and PHWHERE.
~PHNode()
PHNode::~PHNode () virtual
Definition at line 52 of file PHNode.cc.
References forgetMe(), and parent.
PHNode() [3/4]
PHNode::PHNode () protected
Definition at line 10 of file PHNode.cc.
Referenced by makeTransient().
PHNode() [4/4]
PHNode::PHNode (const PHNode & phn) protected
Definition at line 60 of file PHNode.cc.
Member Function Documentation
forgetMe()
virtual void PHNode::forgetMe (PHNode *) pure virtual
Implemented in PHCompositeNode, and PHDataNode< T >.
Referenced by setObjectType(), and ~PHNode().
getClass()
const std::string PHNode::getClass () const inline
Definition at line 33 of file PHNode.h.
References objectclass.
Referenced by operator<<().
getName()
const std::string PHNode::getName () const inline
Definition at line 32 of file PHNode.h.
References name.
Referenced by PHCompositeNode::addNode(), PHNodeIterator::cd(), PHNodeIterator::findFirst(), operator<<(), and PHNodeReset::perform().
getObjectType()
const std::string PHNode::getObjectType () const inline
Definition at line 30 of file PHNode.h.
References objecttype.
Referenced by PHNodeReset::perform().
getParent()
PHNode* PHNode::getParent () const inline
Definition at line 25 of file PHNode.h.
References parent.
Referenced by PHNodeIterator::cd().
getResetFlag()
PHBoolean PHNode::getResetFlag () const virtual
Definition at line 89 of file PHNode.cc.
References reset_able.
Referenced by PHNodeReset::perform(), and setObjectType().
getType()
const std::string PHNode::getType () const inline
Definition at line 31 of file PHNode.h.
References type.
Referenced by PHNodeIterator::cd(), PHNodeIterator::findFirst(), PHNodeIterator::forEach(), operator<<(), and PHNodeReset::perform().
isPersistent()
PHBoolean PHNode::isPersistent () const inline
Definition at line 27 of file PHNode.h.
References persistent.
Referenced by PHCompositeNode::prune().
makePersistent()
void PHNode::makePersistent () inline
Definition at line 28 of file PHNode.h.
References persistent, and True.
Referenced by Fun4AllDstOutputManager::Write().
makeTransient()
void PHNode::makeTransient () inline
Definition at line 45 of file PHNode.h.
References False, operator=(), persistent, and PHNode().
Referenced by Fun4AllDstOutputManager::Write().
operator=()
PHNode & PHNode::operator= (const PHNode &) protected
Definition at line 75 of file PHNode.cc.
Referenced by makeTransient().
print()
virtual void PHNode::print (const std::string &) pure virtual
Implemented in PHCompositeNode, and PHDataNode< T >.
Referenced by PHCompositeNode::print(), and setObjectType().
prune()
virtual void PHNode::prune () pure virtual
Implemented in PHCompositeNode, and PHDataNode< T >.
Referenced by PHCompositeNode::prune(), and setObjectType().
setName()
void PHNode::setName (const std::string & n) inline
Definition at line 36 of file PHNode.h.
References name.
setObjectType()
void PHNode::setObjectType (const std::string & type) inline
Definition at line 37 of file PHNode.h.
References forgetMe(), getResetFlag(), objecttype, print(), prune(), setResetFlag(), type, and write().
Referenced by PHNodeIOManager::reconstructNodeTree().
setParent()
void PHNode::setParent (PHNode * p) inline
Definition at line 35 of file PHNode.h.
References parent.
Referenced by PHCompositeNode::addNode().
setResetFlag()
void PHNode::setResetFlag (const int val) virtual
Definition at line 83 of file PHNode.cc.
References reset_able.
Referenced by setObjectType().
write()
virtual bool PHNode::write (PHIOManager * , const std::string & = "") pure virtual
Implemented in PHCompositeNode, PHIODataNode< T >, and PHDataNode< T >.
Referenced by setObjectType(), and PHCompositeNode::write().
Member Data Documentation
name
std::string PHNode::name protected
Definition at line 57 of file PHNode.h.
Referenced by getName(), PHNode(), PHDataNode< T >::print(), PHCompositeNode::print(), setName(), PHIODataNode< T >::write(), and PHCompositeNode::write().
objectclass
std::string PHNode::objectclass protected
Definition at line 58 of file PHNode.h.
Referenced by getClass(), PHIODataNode< T >::PHIODataNode(), and PHDataNode< T >::print().
objecttype
std::string PHNode::objecttype protected
Definition at line 56 of file PHNode.h.
Referenced by getObjectType(), and setObjectType().
parent
PHNode* PHNode::parent protected
Definition at line 53 of file PHNode.h.
Referenced by getParent(), setParent(), and ~PHNode().
persistent
bool PHNode::persistent protected
Definition at line 54 of file PHNode.h.
Referenced by isPersistent(), makePersistent(), makeTransient(), and PHIODataNode< T >::write().
reset_able
bool PHNode::reset_able protected
Definition at line 59 of file PHNode.h.
Referenced by getResetFlag(), and setResetFlag().
type
std::string PHNode::type protected
Definition at line 55 of file PHNode.h.
Referenced by getType(), PHCompositeNode::PHCompositeNode(), PHDataNode< T >::PHDataNode(), PHIODataNode< T >::PHIODataNode(), PHDataNode< T >::print(), PHCompositeNode::print(), and setObjectType().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHNode.h
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHNode.cc