Class Reference for E1039 Core & Analysis Software: PHG4TargetCoilV2Subsystem Class Reference
PHG4TargetCoilV2Subsystem Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4TargetCoilV2Subsystem.h>
Public Member Functions
PHG4TargetCoilV2Subsystem (const std::string &name="CYLINDER", const int layer=0)
constructor
virtual ~PHG4TargetCoilV2Subsystem (void)
destructor
int InitRunSubsystem (PHCompositeNode *)
init runwise stuff
int process_event (PHCompositeNode *)
event processing
void Print (const std::string &what="ALL") const
Print info (from SubsysReco)
PHG4Detector * GetDetector (void) const
accessors (reimplemented)
PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
Public Member Functions inherited from PHG4DetectorSubsystem
virtual ~PHG4DetectorSubsystem ()
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParameters * GetParams () const
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_vdouble_param (const std::string &name, const std::vector< double > vdval)
void set_vdouble_param (const std::string &name, const double dvals[], const unsigned int n)
std::vector< double > get_vdouble_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void SetAbsorberTruth (const int i=1)
void BlackHole (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParameters * GetParams ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from PHG4DetectorSubsystem
enum FILE_TYPE { none = 0, xml = 1, root = 2 }
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from PHG4DetectorSubsystem
PHG4DetectorSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void set_default_double_param (const std::string &name, const double dval)
void set_default_vdouble_param (const std::string &name, const std::vector< double > &dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
int BeginRunExecuted () const
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from PHG4Subsystem
bool overlapcheck
PHParameters * params
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 12 of file PHG4TargetCoilV2Subsystem.h.
Constructor & Destructor Documentation
PHG4TargetCoilV2Subsystem::PHG4TargetCoilV2Subsystem (const std::string & name = "CYLINDER", const int layer = 0)
constructor
Definition at line 23 of file PHG4TargetCoilV2Subsystem.cc.
References PHG4DetectorSubsystem::InitializeParameters().
virtual PHG4TargetCoilV2Subsystem::~PHG4TargetCoilV2Subsystem (void) inline virtual
destructor
Definition at line 19 of file PHG4TargetCoilV2Subsystem.h.
Member Function Documentation
PHG4Detector * PHG4TargetCoilV2Subsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 157 of file PHG4TargetCoilV2Subsystem.cc.
PHG4SteppingAction* PHG4TargetCoilV2Subsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 43 of file PHG4TargetCoilV2Subsystem.h.
int PHG4TargetCoilV2Subsystem::InitRunSubsystem (PHCompositeNode * topNode) virtual
init runwise stuff
creates the detector_ object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from PHG4DetectorSubsystem.
Definition at line 32 of file PHG4TargetCoilV2Subsystem.cc.
References PHG4HitContainer::AddLayer(), PHG4CylinderGeomContainer::AddLayerGeom(), PHCompositeNode::addNode(), PHG4DetectorSubsystem::CheckOverlap(), PHNodeIterator::findFirst(), PHG4DetectorSubsystem::get_double_param(), PHParameters::get_double_param(), PHG4DetectorSubsystem::get_int_param(), PHG4DetectorSubsystem::GetLayer(), PHG4Utils::GetLengthForRapidityCoverage(), PHG4DetectorSubsystem::GetParams(), Fun4AllBase::Name(), PHG4Detector::OverlapCheck(), PHParameters::set_double_param(), PHG4TargetCoilV2Detector::SuperDetector(), and PHG4DetectorSubsystem::SuperDetector().
void PHG4TargetCoilV2Subsystem::Print (const std::string & what = "ALL") const virtual
Print info (from SubsysReco)
Reimplemented from SubsysReco.
Definition at line 162 of file PHG4TargetCoilV2Subsystem.cc.
References PHG4DetectorSubsystem::BeginRunExecuted(), PHG4DetectorSubsystem::GetParams(), Fun4AllBase::Name(), PHParameters::Print(), and PHG4SteppingAction::Print().
int PHG4TargetCoilV2Subsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 106 of file PHG4TargetCoilV2Subsystem.cc.
References PHG4SteppingAction::SetInterfacePointers().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4TargetCoilV2Subsystem.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4TargetCoilV2Subsystem.cc