Class Reference for E1039 Core & Analysis Software: boost::array< T, 0 > Class Template Reference
boost::array< T, 0 > Class Template Reference
#include </seaquest/users/kenichi/e1039/git/e1039-doc/Doxygen_Assist/array.hpp>
Public Types
enum { static_size = 0 }
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
const_reverse_iterator crbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_reverse_iterator crend () const
reference operator[] (size_type)
const_reference operator[] (size_type) const
reference at (size_type)
const_reference at (size_type) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void swap (array< T, 0 > &)
const T * data () const
T * data ()
T * c_array ()
template<typename T2 >
array< T, 0 > & operator= (const array< T2, 0 > &)
void assign (const T &value)
void fill (const T &)
Static Public Member Functions
static size_type size ()
static bool empty ()
static size_type max_size ()
static reference failed_rangecheck ()
Detailed Description
template<class T>
class boost::array< T, 0 >
Definition at line 201 of file array.hpp.
Member Typedef Documentation
const_iterator
template<class T > typedef const T* boost::array< T, 0 >::const_iterator
Definition at line 207 of file array.hpp.
const_reference
template<class T > typedef const T& boost::array< T, 0 >::const_reference
Definition at line 209 of file array.hpp.
const_reverse_iterator
template<class T > typedef std::reverse_iterator<const_iterator> boost::array< T, 0 >::const_reverse_iterator
Definition at line 225 of file array.hpp.
difference_type
template<class T > typedef std::ptrdiff_t boost::array< T, 0 >::difference_type
Definition at line 211 of file array.hpp.
iterator
template<class T > typedef T* boost::array< T, 0 >::iterator
Definition at line 206 of file array.hpp.
reference
template<class T > typedef T& boost::array< T, 0 >::reference
Definition at line 208 of file array.hpp.
reverse_iterator
template<class T > typedef std::reverse_iterator<iterator> boost::array< T, 0 >::reverse_iterator
Definition at line 224 of file array.hpp.
size_type
template<class T > typedef std::size_t boost::array< T, 0 >::size_type
Definition at line 210 of file array.hpp.
value_type
template<class T > typedef T boost::array< T, 0 >::value_type
Definition at line 205 of file array.hpp.
Member Enumeration Documentation
anonymous enum
template<class T > anonymous enum
Enumerator
static_size
Definition at line 299 of file array.hpp.
Member Function Documentation
assign()
template<class T > void boost::array< T, 0 >::assign (const T & value) inline
Definition at line 318 of file array.hpp.
References boost::array< T, N >::fill().
at() [1/2]
template<class T > reference boost::array< T, 0 >::at (size_type) inline
Definition at line 271 of file array.hpp.
at() [2/2]
template<class T > const_reference boost::array< T, 0 >::at (size_type) const inline
Definition at line 272 of file array.hpp.
back() [1/2]
template<class T > reference boost::array< T, 0 >::back () inline
Definition at line 285 of file array.hpp.
back() [2/2]
template<class T > const_reference boost::array< T, 0 >::back () const inline
Definition at line 290 of file array.hpp.
begin() [1/2]
template<class T > iterator boost::array< T, 0 >::begin () inline
Definition at line 214 of file array.hpp.
begin() [2/2]
template<class T > const_iterator boost::array< T, 0 >::begin () const inline
Definition at line 215 of file array.hpp.
c_array()
template<class T > T* boost::array< T, 0 >::c_array () inline
Definition at line 309 of file array.hpp.
cbegin()
template<class T > const_iterator boost::array< T, 0 >::cbegin () const inline
Definition at line 216 of file array.hpp.
cend()
template<class T > const_iterator boost::array< T, 0 >::cend () const inline
Definition at line 220 of file array.hpp.
References boost::array< T, N >::cbegin().
crbegin()
template<class T > const_reverse_iterator boost::array< T, 0 >::crbegin () const inline
Definition at line 247 of file array.hpp.
References boost::array< T, N >::end().
crend()
template<class T > const_reverse_iterator boost::array< T, 0 >::crend () const inline
Definition at line 255 of file array.hpp.
References boost::array< T, N >::begin().
data() [1/2]
template<class T > T* boost::array< T, 0 >::data () inline
Definition at line 306 of file array.hpp.
data() [2/2]
template<class T > const T* boost::array< T, 0 >::data () const inline
Definition at line 305 of file array.hpp.
empty()
template<class T > static bool boost::array< T, 0 >::empty () inline static
Definition at line 297 of file array.hpp.
end() [1/2]
template<class T > iterator boost::array< T, 0 >::end () inline
Definition at line 218 of file array.hpp.
References boost::array< T, N >::begin().
end() [2/2]
template<class T > const_iterator boost::array< T, 0 >::end () const inline
Definition at line 219 of file array.hpp.
References boost::array< T, N >::begin().
failed_rangecheck()
template<class T > static reference boost::array< T, 0 >::failed_rangecheck () inline static
Definition at line 322 of file array.hpp.
fill()
template<class T > void boost::array< T, 0 >::fill (const T &) inline
Definition at line 319 of file array.hpp.
front() [1/2]
template<class T > reference boost::array< T, 0 >::front () inline
Definition at line 275 of file array.hpp.
front() [2/2]
template<class T > const_reference boost::array< T, 0 >::front () const inline
Definition at line 280 of file array.hpp.
max_size()
template<class T > static size_type boost::array< T, 0 >::max_size () inline static
Definition at line 298 of file array.hpp.
operator=()
template<class T > template<typename T2 > array<T,0>& boost::array< T, 0 >::operator= (const array< T2, 0 > &) inline
Definition at line 313 of file array.hpp.
operator[]() [1/2]
template<class T > reference boost::array< T, 0 >::operator[] (size_type) inline
Definition at line 260 of file array.hpp.
operator[]() [2/2]
template<class T > const_reference boost::array< T, 0 >::operator[] (size_type) const inline
Definition at line 265 of file array.hpp.
rbegin() [1/2]
template<class T > reverse_iterator boost::array< T, 0 >::rbegin () inline
Definition at line 243 of file array.hpp.
References boost::array< T, N >::end().
rbegin() [2/2]
template<class T > const_reverse_iterator boost::array< T, 0 >::rbegin () const inline
Definition at line 244 of file array.hpp.
References boost::array< T, N >::end().
rend() [1/2]
template<class T > reverse_iterator boost::array< T, 0 >::rend () inline
Definition at line 251 of file array.hpp.
References boost::array< T, N >::begin().
rend() [2/2]
template<class T > const_reverse_iterator boost::array< T, 0 >::rend () const inline
Definition at line 252 of file array.hpp.
References boost::array< T, N >::begin().
size()
template<class T > static size_type boost::array< T, 0 >::size () inline static
Definition at line 296 of file array.hpp.
swap()
template<class T > void boost::array< T, 0 >::swap (array< T, 0 > &) inline
Definition at line 301 of file array.hpp.
The documentation for this class was generated from the following file:
/seaquest/users/kenichi/e1039/git/e1039-doc/Doxygen_Assist/array.hpp