E1039 Software: mTrkEveDisplay Class Reference
mTrkEveDisplay Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/Display/modules/mTrkEveDisplay.h>
Public Member Functions
mTrkEveDisplay (boost::shared_ptr< PHEveDisplay >)
~mTrkEveDisplay ()
void init (PHCompositeNode *topNode)
void init_run (PHCompositeNode *topNode)
bool event (PHCompositeNode *topNode)
void end (PHCompositeNode *topNode)
void get_nodes (PHCompositeNode *topNode)
int hit_to_wire (const int det, const int elm, double &x, double &y, double &dx, double &dy)
void draw_hits ()
void draw_tracks ()
bool pid_cut (int pid)
void clear ()
Public Member Functions inherited from mPHEveModuleBase
virtual ~mPHEveModuleBase ()
virtual void draw_event ()
void add_elements ()
void buffer_element (TEveElement *el, TEveElement *parent_elmt)
void clear_element_buffer ()
Private Attributes
boost::shared_ptr< PHEveDisplay > _evedisp
SQHitVector * _sqhit_col
SRecEvent * _recEvent
TEveTrackPropagator * _prop
TEveTrackList * _reco_tracks
TEveQuadSet * _hit_wires [NDETPLANES]
GeomSvc * _geom_svc
int verbosity
Additional Inherited Members
Protected Types inherited from mPHEveModuleBase
typedef std::multimap< TEveElement *, TEveElement * > elmtmap
typedef elmtmap::iterator::value_type mvt
Protected Attributes inherited from mPHEveModuleBase
TEveManager * _evemanager
elmtmap _elmt_buffer
Detailed Description
Definition at line 32 of file mTrkEveDisplay.h.
Constructor & Destructor Documentation
mTrkEveDisplay()
mTrkEveDisplay::mTrkEveDisplay (boost::shared_ptr< PHEveDisplay > dispin)
Definition at line 46 of file mTrkEveDisplay.cxx.
References _evedisp, mPHEveModuleBase::_evemanager, _geom_svc, _hit_wires, _prop, _reco_tracks, PHEveDisplay::get_cnt_prop(), PHEveDisplay::get_dc_list(), PHEveDisplay::get_eve_manager(), PHEveDisplay::get_hodo_list(), PHEveDisplay::get_prop_list(), PHEveDisplay::get_top_list(), PHEveDisplay::get_verbosity(), GeomSvc::getPlaneCenterZ(), GeomSvc::instance(), NDETPLANES, and verbosity.
~mTrkEveDisplay()
mTrkEveDisplay::~mTrkEveDisplay ()
Definition at line 78 of file mTrkEveDisplay.cxx.
Member Function Documentation
clear()
void mTrkEveDisplay::clear () virtual
Implements mPHEveModuleBase.
Definition at line 379 of file mTrkEveDisplay.cxx.
References _geom_svc, _hit_wires, _prop, _reco_tracks, GeomSvc::getPlaneCenterZ(), and NDETPLANES.
Referenced by event().
draw_hits()
void mTrkEveDisplay::draw_hits ()
Definition at line 178 of file mTrkEveDisplay.cxx.
References _hit_wires, _sqhit_col, SQHitVector::begin(), SQHitVector::end(), SQHit::get_detector_id(), SQHit::get_element_id(), hit_to_wire(), LogInfo, NDETPLANES, and verbosity.
Referenced by event().
draw_tracks()
void mTrkEveDisplay::draw_tracks ()
Definition at line 248 of file mTrkEveDisplay.cxx.
References _geom_svc, _prop, _recEvent, _reco_tracks, _sqhit_col, SQHitVector::at(), SQHit::get_hit_id(), SRecTrack::getCharge(), GeomSvc::getDetectorID(), SRecTrack::getExpPositionFast(), SRecTrack::getMomentumSt1(), SRecEvent::getNTracks(), GeomSvc::getPlaneCenterZ(), SRecTrack::getPositionSt1(), SRecTrack::getTargetMom(), SRecTrack::getTargetPos(), SRecEvent::getTrack(), GeomSvc::instance(), LogInfo, SQHitVector::size(), and verbosity.
Referenced by event().
end()
void mTrkEveDisplay::end (PHCompositeNode * topNode) virtual
Implements mPHEveModuleBase.
Definition at line 121 of file mTrkEveDisplay.cxx.
event()
bool mTrkEveDisplay::event (PHCompositeNode * topNode) virtual
Implements mPHEveModuleBase.
Definition at line 94 of file mTrkEveDisplay.cxx.
References clear(), draw_hits(), draw_tracks(), get_nodes(), LogInfo, and verbosity.
get_nodes()
void mTrkEveDisplay::get_nodes (PHCompositeNode * topNode)
Definition at line 126 of file mTrkEveDisplay.cxx.
References _recEvent, _sqhit_col, and verbosity.
Referenced by event().
hit_to_wire()
int mTrkEveDisplay::hit_to_wire (const int det, const int elm, double & x, double & y, double & dx, double & dy)
Get a wire param from detector id and element id
Parameters
[in] det,elm input
[out] x,y 1 end point of the wire
[out] dx,dy wire span in x and y
Definition at line 137 of file mTrkEveDisplay.cxx.
References _geom_svc, GeomSvc::getCostheta(), GeomSvc::getMeasurement(), GeomSvc::getPlane(), GeomSvc::getSintheta(), Plane::x1, Plane::x2, Plane::y1, and Plane::y2.
Referenced by draw_hits().
init()
void mTrkEveDisplay::init (PHCompositeNode * topNode) virtual
Implements mPHEveModuleBase.
Definition at line 83 of file mTrkEveDisplay.cxx.
init_run()
void mTrkEveDisplay::init_run (PHCompositeNode * topNode) virtual
Implements mPHEveModuleBase.
Definition at line 88 of file mTrkEveDisplay.cxx.
pid_cut()
bool mTrkEveDisplay::pid_cut (int pid)
Definition at line 369 of file mTrkEveDisplay.cxx.
Member Data Documentation
_evedisp
boost::shared_ptr<PHEveDisplay> mTrkEveDisplay::_evedisp private
Definition at line 59 of file mTrkEveDisplay.h.
Referenced by mTrkEveDisplay().
_geom_svc
GeomSvc* mTrkEveDisplay::_geom_svc private
Definition at line 67 of file mTrkEveDisplay.h.
Referenced by clear(), draw_tracks(), hit_to_wire(), and mTrkEveDisplay().
_hit_wires
TEveQuadSet* mTrkEveDisplay::_hit_wires[NDETPLANES] private
Definition at line 65 of file mTrkEveDisplay.h.
Referenced by clear(), draw_hits(), and mTrkEveDisplay().
_prop
TEveTrackPropagator* mTrkEveDisplay::_prop private
Definition at line 63 of file mTrkEveDisplay.h.
Referenced by clear(), draw_tracks(), and mTrkEveDisplay().
_recEvent
SRecEvent* mTrkEveDisplay::_recEvent private
Definition at line 61 of file mTrkEveDisplay.h.
Referenced by draw_tracks(), and get_nodes().
_reco_tracks
TEveTrackList* mTrkEveDisplay::_reco_tracks private
Definition at line 64 of file mTrkEveDisplay.h.
Referenced by clear(), draw_tracks(), and mTrkEveDisplay().
_sqhit_col
SQHitVector* mTrkEveDisplay::_sqhit_col private
Definition at line 60 of file mTrkEveDisplay.h.
Referenced by draw_hits(), draw_tracks(), and get_nodes().
verbosity
int mTrkEveDisplay::verbosity private
Definition at line 69 of file mTrkEveDisplay.h.
Referenced by draw_hits(), draw_tracks(), event(), get_nodes(), and mTrkEveDisplay().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/Display/modules/mTrkEveDisplay.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/Display/modules/mTrkEveDisplay.cxx