SeaQuest Offline Software: PHG4Detector Class Reference
PHG4Detector Class Reference abstract
base class for phenix detector creation
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4main/PHG4Detector.h>
Public Member Functions
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world)=0
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Protected Attributes
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
base class for phenix detector creation
derived classes must implement construct method, which takes the "world" logical volume as argument
Definition at line 13 of file PHG4Detector.h.
Constructor & Destructor Documentation
PHG4Detector::PHG4Detector (PHCompositeNode * Node) inline
constructor
Definition at line 20 of file PHG4Detector.h.
PHG4Detector::PHG4Detector (PHCompositeNode * Node, const std::string & nam) inline
Definition at line 27 of file PHG4Detector.h.
virtual PHG4Detector::~PHG4Detector (void) inline virtual
destructor
Definition at line 35 of file PHG4Detector.h.
Member Function Documentation
virtual void PHG4Detector::Construct (G4LogicalVolume * world) pure virtual
construct method
construct all logical and physical volumes relevant for given detector and place them inside the world logical volume
Implemented in PHG4RICHDetector, PHG4SpacalDetector, PHG4FullProjSpacalDetector, PHG4FullProjTiltedSpacalDetector, PHG4EICForwardEcalDetector, PHG4ForwardEcalDetector, PHG4ForwardHcalDetector, PHG4CrystalCalorimeterDetector, PHG4HcalPrototypeDetector, PHG4SpacalPrototypeDetector, PHG4OuterHcalDetector, PHG4InnerHcalDetector, PHG4MapsDetector, PHG4Prototype2InnerHcalDetector, PHG4Prototype2OuterHcalDetector, PHG4SectorDetector, PHG4ConeDetector, PHG4mRICHDetector, PHG4HcalDetector, PHG4SiliconTrackerDetector, PHG4CEmcTestBeamDetector, PHG4FPbScDetector, PHG4FCalDetector, PHG4BeamlineMagnetDetector, PHG4EnvelopeDetector, PHG4BNLTargetCoilDetector, PHG4CylinderDetector, PHG4PolyconDetector, PHG4ProjCrystalCalorimeterDetector, PHG4PSTOFDetector, PHG4TargetCoilDetector, PHG4BlockDetector, and PHG4CollimatorDetector.
virtual std::string PHG4Detector::GetName () const inline virtual
Definition at line 51 of file PHG4Detector.h.
References name.
Referenced by PHG4BlockDetector::Construct(), PHG4CollimatorDetector::Construct(), PHG4BNLTargetCoilDetector::Construct(), PHG4TargetCoilDetector::Construct(), PHG4PolyconDetector::Construct(), PHG4CylinderDetector::Construct(), PHG4BeamlineMagnetDetector::Construct(), PHG4HcalDetector::Construct(), PHG4ConeDetector::Construct(), PHG4SpacalPrototypeDetector::Construct(), PHG4FullProjTiltedSpacalDetector::Construct(), PHG4FullProjSpacalDetector::Construct(), PHG4SpacalDetector::Construct(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_Fiber(), PHG4SpacalDetector::Construct_Fiber(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4SpacalPrototypeDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4SpacalPrototypeDetector::Construct_LightGuide(), PHG4FullProjTiltedSpacalDetector::Construct_LightGuide(), PHG4SpacalPrototypeDetector::Construct_Tower(), PHG4FullProjTiltedSpacalDetector::Construct_Tower(), PHG4FullProjSpacalDetector::Construct_Tower(), PHG4InnerHcalSteppingAction::PHG4InnerHcalSteppingAction(), PHG4OuterHcalSteppingAction::PHG4OuterHcalSteppingAction(), PHG4FullProjSpacalDetector::Print(), PHG4FullProjTiltedSpacalDetector::Print(), PHG4SpacalPrototypeDetector::Print(), PHG4SpacalDetector::Print(), PHG4FPbScSteppingAction::SetInterfacePointers(), PHG4SiliconTrackerSteppingAction::SetInterfacePointers(), PHG4EnvelopeSteppingAction::SetInterfacePointers(), PHG4Prototype2InnerHcalSteppingAction::SetInterfacePointers(), PHG4PSTOFSteppingAction::SetInterfacePointers(), PHG4Prototype2OuterHcalSteppingAction::SetInterfacePointers(), PHG4CollimatorSteppingAction::SetInterfacePointers(), PHG4MapsSteppingAction::SetInterfacePointers(), PHG4InnerHcalSteppingAction::SetInterfacePointers(), PHG4BlockSteppingAction::SetInterfacePointers(), PHG4CEmcTestBeamSteppingAction::SetInterfacePointers(), PHG4ConeSteppingAction::SetInterfacePointers(), PHG4HcalSteppingAction::SetInterfacePointers(), PHG4SectorSteppingAction::SetInterfacePointers(), PHG4CrystalCalorimeterSteppingAction::SetInterfacePointers(), PHG4OuterHcalSteppingAction::SetInterfacePointers(), PHG4ConeRegionSteppingAction::SetInterfacePointers(), PHG4PolyconSteppingAction::SetInterfacePointers(), PHG4BNLTargetCoilSteppingAction::SetInterfacePointers(), PHG4TargetCoilSteppingAction::SetInterfacePointers(), PHG4FPbScRegionSteppingAction::SetInterfacePointers(), PHG4CylinderSteppingAction::SetInterfacePointers(), PHG4ForwardHcalSteppingAction::SetInterfacePointers(), PHG4HcalPrototypeSteppingAction::SetInterfacePointers(), PHG4ForwardEcalSteppingAction::SetInterfacePointers(), PHG4SpacalSteppingAction::SetInterfacePointers(), PHG4SpacalPrototypeSteppingAction::SetInterfacePointers(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4SpacalPrototypeSteppingAction::UserSteppingAction().
virtual G4UserSteppingAction* PHG4Detector::GetSteppingAction (void) inline virtual
Reimplemented in PHG4SpacalDetector, PHG4ConeDetector, PHG4RICHDetector, PHG4HcalDetector, PHG4SectorDetector, PHG4FPbScDetector, and PHG4FCalDetector.
Definition at line 49 of file PHG4Detector.h.
virtual void PHG4Detector::OverlapCheck (const bool chk = true) inline virtual
Reimplemented in PHG4RICHDetector, and PHG4SectorDetector.
Definition at line 53 of file PHG4Detector.h.
References overlapcheck.
Referenced by PHG4CEmcTestBeamSubsystem::Init(), PHG4ConeSubsystem::Init(), PHG4ForwardEcalSubsystem::Init(), PHG4ForwardHcalSubsystem::Init(), PHG4EnvelopeSubsystem::Init(), PHG4CrystalCalorimeterSubsystem::Init(), PHG4HcalPrototypeSubsystem::Init(), PHG4HcalSubsystem::InitRun(), PHG4SpacalPrototypeSubsystem::InitRunSubsystem(), PHG4CollimatorSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4Prototype2InnerHcalSubsystem::InitRunSubsystem(), PHG4BNLTargetCoilSubsystem::InitRunSubsystem(), PHG4OuterHcalSubsystem::InitRunSubsystem(), PHG4TargetCoilSubsystem::InitRunSubsystem(), PHG4Prototype2OuterHcalSubsystem::InitRunSubsystem(), PHG4PolyconSubsystem::InitRunSubsystem(), PHG4InnerHcalSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4MapsSubsystem::InitRunSubsystem(), PHG4mRICHSubsystem::InitRunSubsystem(), PHG4SiliconTrackerSubsystem::InitRunSubsystem(), PHG4SpacalSubsystem::InitRunSubsystem(), PHG4PSTOFSubsystem::InitRunSubsystem(), PHG4SectorDetector::OverlapCheck(), and PHG4RICHDetector::OverlapCheck().
virtual void PHG4Detector::Print (const std::string & what = "ALL") const inline virtual
Reimplemented in PHG4SpacalDetector, PHG4SpacalPrototypeDetector, PHG4FullProjTiltedSpacalDetector, PHG4HcalDetector, PHG4FullProjSpacalDetector, PHG4OuterHcalDetector, PHG4InnerHcalDetector, PHG4Prototype2InnerHcalDetector, PHG4Prototype2OuterHcalDetector, and PHG4PSTOFDetector.
Definition at line 55 of file PHG4Detector.h.
References name.
virtual void PHG4Detector::Verbosity (const int v) inline virtual
Definition at line 45 of file PHG4Detector.h.
References verbosity.
Referenced by PHG4FCalSubsystem::Init(), PHG4FPbScSubsystem::Init(), PHG4ForwardEcalSubsystem::Init(), PHG4ForwardHcalSubsystem::Init(), PHG4RICHSubsystem::Init(), and PHG4MapsSubsystem::InitRunSubsystem().
virtual int PHG4Detector::Verbosity () const inline virtual
Definition at line 47 of file PHG4Detector.h.
References verbosity.
Referenced by PHG4MapsDetector::AddGeometryNode(), PHG4SpacalDetector::Construct(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4MapsDetector::ConstructMaps(), and PHG4MapsDetector::SetDisplayProperty().
Member Data Documentation
std::string PHG4Detector::name protected
Definition at line 61 of file PHG4Detector.h.
Referenced by PHG4mRICHDetector::build_mRICH_wall(), PHG4CylinderDetector::Construct(), PHG4PolyconDetector::Construct(), PHG4BNLTargetCoilDetector::Construct(), PHG4TargetCoilDetector::Construct(), PHG4SpacalPrototypeDetector::Construct(), PHG4SpacalDetector::Construct(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4SpacalPrototypeDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4InnerHcalDetector::ConstructHcalScintillatorAssembly(), PHG4OuterHcalDetector::ConstructHcalScintillatorAssembly(), PHG4OuterHcalDetector::ConstructHcalSingleScintillators(), PHG4InnerHcalDetector::ConstructHcalSingleScintillators(), PHG4InnerHcalDetector::ConstructInnerHcal(), PHG4Prototype2InnerHcalDetector::ConstructInnerHcal(), PHG4OuterHcalDetector::ConstructOuterHcal(), PHG4Prototype2OuterHcalDetector::ConstructOuterHcal(), PHG4ProjCrystalCalorimeterDetector::ConstructProjectiveCrystals(), PHG4SiliconTrackerDetector::Detector(), PHG4MapsDetector::Detector(), GetName(), PHG4mRICHDetector::LensPar::LensPar(), PHG4MapsDetector::PHG4MapsDetector(), PHG4mRICHDetector::PolyPar::PolyPar(), Print(), PHG4BNLTargetCoilDetector::SuperDetector(), PHG4PolyconDetector::SuperDetector(), PHG4CylinderDetector::SuperDetector(), PHG4TargetCoilDetector::SuperDetector(), PHG4BeamlineMagnetDetector::SuperDetector(), PHG4BlockDetector::SuperDetector(), PHG4CollimatorDetector::SuperDetector(), PHG4PSTOFDetector::SuperDetector(), PHG4SiliconTrackerDetector::SuperDetector(), PHG4mRICHDetector::SuperDetector(), PHG4Prototype2OuterHcalDetector::SuperDetector(), PHG4Prototype2InnerHcalDetector::SuperDetector(), PHG4InnerHcalDetector::SuperDetector(), PHG4EnvelopeDetector::SuperDetector(), PHG4OuterHcalDetector::SuperDetector(), PHG4CEmcTestBeamDetector::SuperDetector(), PHG4SectorDetector::SuperDetector(), PHG4HcalDetector::SuperDetector(), PHG4MapsDetector::SuperDetector(), PHG4HcalPrototypeDetector::SuperDetector(), PHG4ConeDetector::SuperDetector(), PHG4ForwardHcalDetector::SuperDetector(), PHG4SpacalPrototypeDetector::SuperDetector(), PHG4SpacalDetector::SuperDetector(), PHG4CrystalCalorimeterDetector::SuperDetector(), and PHG4ForwardEcalDetector::SuperDetector().
bool PHG4Detector::overlapcheck protected
Definition at line 62 of file PHG4Detector.h.
Referenced by PHG4BlockDetector::Construct(), PHG4CylinderDetector::Construct(), PHG4PolyconDetector::Construct(), PHG4PSTOFDetector::Construct(), PHG4BeamlineMagnetDetector::Construct(), PHG4EnvelopeDetector::Construct(), PHG4CEmcTestBeamDetector::Construct(), PHG4HcalDetector::Construct(), PHG4ConeDetector::Construct(), PHG4Prototype2InnerHcalDetector::Construct(), PHG4Prototype2OuterHcalDetector::Construct(), PHG4InnerHcalDetector::Construct(), PHG4OuterHcalDetector::Construct(), PHG4SpacalPrototypeDetector::Construct(), PHG4CrystalCalorimeterDetector::Construct(), PHG4ForwardHcalDetector::Construct(), PHG4ForwardEcalDetector::Construct(), PHG4EICForwardEcalDetector::Construct(), PHG4SpacalDetector::Construct(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_Fiber(), PHG4SpacalDetector::Construct_Fiber(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4SpacalPrototypeDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4InnerHcalDetector::ConstructInnerHcal(), PHG4MapsDetector::ConstructMaps(), PHG4OuterHcalDetector::ConstructOuterHcal(), PHG4CEmcTestBeamDetector::ConstructSandwichVolume(), PHG4Prototype2InnerHcalDetector::ConstructScintillatorBox(), PHG4Prototype2OuterHcalDetector::ConstructScintillatorBox(), PHG4Prototype2InnerHcalDetector::ConstructScintillatorBoxHiEta(), PHG4Prototype2OuterHcalDetector::ConstructScintillatorBoxHiEta(), PHG4SiliconTrackerDetector::ConstructSiliconTracker(), PHG4EICForwardEcalDetector::ConstructTower(), PHG4ForwardHcalDetector::ConstructTower(), PHG4ForwardEcalDetector::ConstructTower(), PHG4CrystalCalorimeterDetector::ConstructTower(), PHG4ForwardEcalDetector::ConstructTowerType2(), PHG4CEmcTestBeamDetector::ConstructTowerVolume(), PHG4SiliconTrackerDetector::DisplayVolume(), PHG4OuterHcalDetector::DisplayVolume(), PHG4InnerHcalDetector::DisplayVolume(), PHG4Prototype2OuterHcalDetector::DisplayVolume(), PHG4Prototype2InnerHcalDetector::DisplayVolume(), OverlapCheck(), PHG4EICForwardEcalDetector::PlaceTower(), PHG4ForwardHcalDetector::PlaceTower(), PHG4ForwardEcalDetector::PlaceTower(), and PHG4CrystalCalorimeterDetector::PlaceTower().
PHCompositeNode* PHG4Detector::topNode protected
Definition at line 59 of file PHG4Detector.h.
Referenced by PHG4SiliconTrackerDetector::AddGeometryNode(), PHG4MapsDetector::AddGeometryNode(), PHG4HcalDetector::Construct(), PHG4SpacalPrototypeDetector::Construct(), and PHG4SpacalDetector::Construct().
int PHG4Detector::verbosity protected
Definition at line 60 of file PHG4Detector.h.
Referenced by PHG4SiliconTrackerDetector::AddGeometryNode(), PHG4ProjCrystalCalorimeterDetector::Construct(), PHG4BeamlineMagnetDetector::Construct(), PHG4SiliconTrackerDetector::Construct(), PHG4MapsDetector::Construct(), PHG4CrystalCalorimeterDetector::Construct(), PHG4ForwardEcalDetector::Construct(), PHG4ForwardHcalDetector::Construct(), PHG4EICForwardEcalDetector::Construct(), PHG4SpacalDetector::Construct(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_Fiber(), PHG4MapsDetector::ConstructMaps(), PHG4EICForwardEcalDetector::ConstructTower(), PHG4ForwardHcalDetector::ConstructTower(), PHG4ForwardEcalDetector::ConstructTower(), PHG4CrystalCalorimeterDetector::ConstructTower(), PHG4ForwardEcalDetector::ConstructTowerType2(), PHG4EICForwardEcalDetector::ParseParametersFromTable(), PHG4ForwardHcalDetector::ParseParametersFromTable(), PHG4ForwardEcalDetector::ParseParametersFromTable(), PHG4CrystalCalorimeterDetector::ParseParametersFromTable(), PHG4MapsDetector::PHG4MapsDetector(), PHG4EICForwardEcalDetector::PlaceTower(), PHG4ForwardHcalDetector::PlaceTower(), PHG4ForwardEcalDetector::PlaceTower(), PHG4CrystalCalorimeterDetector::PlaceTower(), PHG4OuterHcalDetector::SetTiltViaNcross(), PHG4InnerHcalDetector::SetTiltViaNcross(), and Verbosity().
The documentation for this class was generated from the following file:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4main/PHG4Detector.h