Class Reference for E1039 Core & Analysis Software: AnaTrack Class Reference
AnaTrack Class Reference
An example class to analyze hodoscope hits in E1039 DST file.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/ChamRealizationDev/src/AnaTrack.h>
Public Member Functions
AnaTrack (const std::string &name="AnaTrack")
virtual ~AnaTrack ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
AnaTrack (const std::string &name="AnaTrack")
virtual ~AnaTrack ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetOutputFileName (const std::string name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static void AnalyzeTree (TChain *tree)
static void DrawHistIn1D (TH2 *h2, const std::string label, const std::string dir_out)
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
An example class to analyze hodoscope hits in E1039 DST file.
Definition at line 14 of file AnaTrack.h.
Constructor & Destructor Documentation
AnaTrack() [1/2]
AnaTrack::AnaTrack (const std::string & name = "AnaTrack")
Definition at line 24 of file AnaTrack.cc.
~AnaTrack() [1/2]
AnaTrack::~AnaTrack () inline virtual
Definition at line 42 of file AnaTrack.h.
AnaTrack() [2/2]
AnaTrack::AnaTrack (const std::string & name = "AnaTrack")
~AnaTrack() [2/2]
virtual AnaTrack::~AnaTrack () virtual
Member Function Documentation
AnalyzeTree()
void AnaTrack::AnalyzeTree (TChain * tree) static
Definition at line 118 of file AnaTrack.cc.
References TrackData::charge, TrackData::chisq, TrackData::chisq_dump, TrackData::chisq_target, TrackData::chisq_upstream, DrawHistIn1D(), EventData::fpga_bits, TrackData::mom_st1, TrackData::mom_st3, TrackData::mom_vtx, TrackData::n_hits, TrackData::pos_st1, TrackData::pos_st3, and TrackData::pos_vtx.
DrawHistIn1D()
void AnaTrack::DrawHistIn1D (TH2 * h2, const std::string label, const std::string dir_out) static
Definition at line 251 of file AnaTrack.cc.
Referenced by AnalyzeTree().
End() [1/2]
int AnaTrack::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 195 of file AnaTrack.cc.
References Fun4AllReturnCodes::EVENT_OK.
End() [2/2]
int AnaTrack::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Init() [1/2]
int AnaTrack::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 41 of file AnaTrack.cc.
References Fun4AllReturnCodes::EVENT_OK.
Init() [2/2]
int AnaTrack::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
InitRun() [1/2]
int AnaTrack::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 46 of file AnaTrack.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, GeomSvc::getCellWidth(), GeomSvc::getDetectorName(), GeomSvc::getPlaneNElements(), GeomSvc::getPlaneScaleX(), GeomSvc::instance(), and Fun4AllBase::Name().
InitRun() [2/2]
int AnaTrack::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
process_event() [1/2]
int AnaTrack::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 104 of file AnaTrack.cc.
References SQTrackVector::at(), TrackletVector::at(), Tracklet::chisq, Fun4AllReturnCodes::EVENT_OK, SQTrack::get_charge(), SQTrack::get_mom_st1(), SQTrack::get_mom_st3(), SQTrack::get_mom_vtx(), SQTrack::get_pos_st1(), SQTrack::get_pos_st3(), SQTrack::get_pos_vtx(), Tracklet::getExpPositionW(), Tracklet::getNHits(), SRecEvent::getNTracks(), Tracklet::hits, Tracklet::invP, TrackletVector::size(), SQTrackVector::size(), Tracklet::stationID, Tracklet::tx, Tracklet::ty, Fun4AllBase::Verbosity(), Tracklet::x0, and Tracklet::y0.
process_event() [2/2]
int AnaTrack::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
SetOutputFileName()
void AnaTrack::SetOutputFileName (const std::string name) inline
Definition at line 32 of file AnaTrack.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/ChamRealizationDev/src/AnaTrack.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/ChamRealizationDev/src/AnaTrack.cc