Class Reference for E1039 Core & Analysis Software: PHG4ParticleGenerator Class Reference
PHG4ParticleGenerator Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4ParticleGenerator.h>
Public Member Functions
PHG4ParticleGenerator (const std::string &name="PGENERATOR")
virtual ~PHG4ParticleGenerator ()
int process_event (PHCompositeNode *topNode)
void set_z_range (const double z_min, const double z_max)
void set_eta_range (const double eta_min, const double eta_max)
void set_phi_range (const double phi_min, const double phi_max)
void set_mom_range (const double mom_min, const double mom_max)
Public Member Functions inherited from PHG4ParticleGeneratorBase
virtual ~PHG4ParticleGeneratorBase ()
virtual int InitRun (PHCompositeNode *topNode)
virtual void set_name (const std::string &particle="proton")
virtual void set_pid (const int pid)
virtual void set_mom (const double x, const double y, const double z)
virtual void set_vtx (const double x, const double y, const double z)
virtual void set_t0 (const double t)
virtual double get_vtx_x () const
virtual double get_vtx_y () const
virtual double get_vtx_z () const
virtual double get_t0 () const
virtual void Print (const std::string &what="ALL") const
virtual void AddParticle (const std::string &particle, const double x, const double y, const double z)
virtual void AddParticle (const int pid, const double x, const double y, const double z)
virtual void Embed (const int i=1)
virtual int ReuseExistingVertex (PHCompositeNode *topNode)
int get_reuse_existing_vertex () const
void set_reuse_existing_vertex (const int i=1)
void set_seed (const unsigned int iseed)
unsigned int get_seed () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
double z_min
double z_max
double eta_min
double eta_max
double phi_min
double phi_max
double mom_min
double mom_max
Protected Attributes inherited from PHG4ParticleGeneratorBase
int embedflag
int reuse_existing_vertex
double vtx_x
double vtx_y
double vtx_z
double t0
std::vector< PHG4Particle * > particlelist
unsigned int seed
gsl_rng * RandomGenerator
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from PHG4ParticleGeneratorBase
PHG4ParticleGeneratorBase (const std::string &name="GENERATORBASE")
int get_pdgcode (const std::string &name) const
std::string get_pdgname (const int pdgcode) const
double get_mass (const int pdgcode) const
void CheckAndCreateParticleVector ()
void SetParticleId (PHG4Particle *particle, PHG4InEvent *ineve)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 7 of file PHG4ParticleGenerator.h.
Constructor & Destructor Documentation
PHG4ParticleGenerator()
PHG4ParticleGenerator::PHG4ParticleGenerator (const std::string & name = "PGENERATOR")
Definition at line 18 of file PHG4ParticleGenerator.cc.
~PHG4ParticleGenerator()
virtual PHG4ParticleGenerator::~PHG4ParticleGenerator () inline virtual
Definition at line 11 of file PHG4ParticleGenerator.h.
Member Function Documentation
process_event()
int PHG4ParticleGenerator::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 65 of file PHG4ParticleGenerator.cc.
References PHG4InEvent::AddParticle(), PHG4InEvent::AddVtx(), eta_max, eta_min, PHG4InEvent::identify(), mom_max, mom_min, PHG4ParticleGeneratorBase::particlelist, phi_max, phi_min, PHG4ParticleGeneratorBase::RandomGenerator, PHG4ParticleGeneratorBase::ReuseExistingVertex(), PHG4Particle::set_e(), PHG4Particle::set_px(), PHG4Particle::set_py(), PHG4Particle::set_pz(), PHG4ParticleGeneratorBase::SetParticleId(), PHG4ParticleGeneratorBase::t0, Fun4AllBase::verbosity, PHG4ParticleGeneratorBase::vtx_x, PHG4ParticleGeneratorBase::vtx_y, PHG4ParticleGeneratorBase::vtx_z, z_max, and z_min.
set_eta_range()
void PHG4ParticleGenerator::set_eta_range (const double eta_min, const double eta_max)
Definition at line 41 of file PHG4ParticleGenerator.cc.
References eta_max, and eta_min.
set_mom_range()
void PHG4ParticleGenerator::set_mom_range (const double mom_min, const double mom_max)
Definition at line 57 of file PHG4ParticleGenerator.cc.
References mom_max, and mom_min.
set_phi_range()
void PHG4ParticleGenerator::set_phi_range (const double phi_min, const double phi_max)
Definition at line 49 of file PHG4ParticleGenerator.cc.
References phi_max, and phi_min.
set_z_range()
void PHG4ParticleGenerator::set_z_range (const double z_min, const double z_max)
Definition at line 33 of file PHG4ParticleGenerator.cc.
References z_max, and z_min.
Member Data Documentation
eta_max
double PHG4ParticleGenerator::eta_max protected
Definition at line 23 of file PHG4ParticleGenerator.h.
Referenced by process_event(), and set_eta_range().
eta_min
double PHG4ParticleGenerator::eta_min protected
Definition at line 22 of file PHG4ParticleGenerator.h.
Referenced by process_event(), and set_eta_range().
mom_max
double PHG4ParticleGenerator::mom_max protected
Definition at line 27 of file PHG4ParticleGenerator.h.
Referenced by process_event(), and set_mom_range().
mom_min
double PHG4ParticleGenerator::mom_min protected
Definition at line 26 of file PHG4ParticleGenerator.h.
Referenced by process_event(), and set_mom_range().
phi_max
double PHG4ParticleGenerator::phi_max protected
Definition at line 25 of file PHG4ParticleGenerator.h.
Referenced by process_event(), and set_phi_range().
phi_min
double PHG4ParticleGenerator::phi_min protected
Definition at line 24 of file PHG4ParticleGenerator.h.
Referenced by process_event(), and set_phi_range().
z_max
double PHG4ParticleGenerator::z_max protected
Definition at line 21 of file PHG4ParticleGenerator.h.
Referenced by process_event(), and set_z_range().
z_min
double PHG4ParticleGenerator::z_min protected
Definition at line 20 of file PHG4ParticleGenerator.h.
Referenced by process_event(), and set_z_range().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4ParticleGenerator.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4ParticleGenerator.cc