Class Reference for E1039 Core & Analysis Software: PHG4CylinderCellReco Class Reference
PHG4CylinderCellReco Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellReco.h>
Public Member Functions
PHG4CylinderCellReco (const std::string &name="CYLINDERRECO")
virtual ~PHG4CylinderCellReco ()
int InitRun (PHCompositeNode *topNode)
module initialization
int process_event (PHCompositeNode *topNode)
event processing
int ResetEvent (PHCompositeNode *topNode)
Clean up after each event.
void SetDefaultParameters ()
void Detector (const std::string &d)
void cellsize (const int i, const double sr, const double sz)
void etaphisize (const int i, const double deltaeta, const double deltaphi)
void checkenergy (const int i=1)
void OutputDetector (const std::string &d)
double get_timing_window_min (const int i)
double get_timing_window_max (const int i)
void set_timing_window (const int detid, const double tmin, const double tmax)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHG4ParameterContainerInterface
PHG4ParameterContainerInterface (const std::string &name)
virtual ~PHG4ParameterContainerInterface ()
void set_name (const std::string &name)
void set_double_param (const int id, const std::string &name, const double dval)
double get_double_param (const int id, const std::string &name) const
void set_int_param (const int id, const std::string &name, const int ival)
int get_int_param (const int id, const std::string &name) const
void set_string_param (const int id, const std::string &name, const std::string &sval)
std::string get_string_param (const int id, const std::string &name) const
void UpdateParametersWithMacro ()
void CreateInitialize (const int detid)
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
int ExistDetid (const int detid) const
Protected Member Functions
void set_size (const int i, const double sizeA, const double sizeB)
int CheckEnergy (PHCompositeNode *topNode)
bool lines_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double *rx, double *ry)
bool line_and_rectangle_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double *rr)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Member Functions inherited from PHG4ParameterContainerInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
const PHG4ParametersContainer * GetParamsContainer ()
PHG4ParametersContainer * GetParamsContainerModify ()
const PHG4Parameters * GetDefaultParameters ()
Static Protected Member Functions
static std::pair< double, double > get_etaphi (const double x, const double y, const double z)
static double get_eta (const double radius, const double z)
Protected Attributes
std::map< int, int > binning
std::map< int, std::pair< double, double > > cell_size
std::map< int, std::pair< double, double > > zmin_max
std::map< int, double > phistep
std::map< int, double > etastep
std::set< int > implemented_detid
std::string detector
std::string outdetector
std::string hitnodename
std::string cellnodename
std::string geonodename
std::string seggeonodename
std::map< int, std::pair< int, int > > n_phi_z_bins
std::map< unsigned long long, PHG4Cell * > cellptmap
std::map< unsigned long long, PHG4Cell * >::iterator it
std::map< int, std::pair< double, double > > tmin_max
PHTimeServer::timer _timer
int nbins [2]
int chkenergyconservation
double sum_energy_before_cuts
double sum_energy_g4hit
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 17 of file PHG4CylinderCellReco.h.
Constructor & Destructor Documentation
PHG4CylinderCellReco()
PHG4CylinderCellReco::PHG4CylinderCellReco (const std::string & name = "CYLINDERRECO") explicit
Definition at line 32 of file PHG4CylinderCellReco.cc.
References nbins, and SetDefaultParameters().
~PHG4CylinderCellReco()
virtual PHG4CylinderCellReco::~PHG4CylinderCellReco () inline virtual
Definition at line 23 of file PHG4CylinderCellReco.h.
Member Function Documentation
cellsize()
void PHG4CylinderCellReco::cellsize (const int i, const double sr, const double sz)
Definition at line 848 of file PHG4CylinderCellReco.cc.
References binning, PHG4ParameterContainerInterface::set_double_param(), and PHG4CellDefs::sizebinning.
checkenergy()
void PHG4CylinderCellReco::checkenergy (const int i = 1) inline
Definition at line 38 of file PHG4CylinderCellReco.h.
References chkenergyconservation.
CheckEnergy()
int PHG4CylinderCellReco::CheckEnergy (PHCompositeNode * topNode) protected
Definition at line 1075 of file PHG4CylinderCellReco.cc.
References cellnodename, PHG4CellContainer::getCells(), Fun4AllBase::Name(), sum_energy_before_cuts, sum_energy_g4hit, and Fun4AllBase::verbosity.
Referenced by process_event().
Detector()
void PHG4CylinderCellReco::Detector (const std::string & d)
Definition at line 1145 of file PHG4CylinderCellReco.cc.
References detector, outdetector, and OutputDetector().
etaphisize()
void PHG4CylinderCellReco::etaphisize (const int i, const double deltaeta, const double deltaphi)
Definition at line 861 of file PHG4CylinderCellReco.cc.
References binning, PHG4CellDefs::etaphibinning, and PHG4ParameterContainerInterface::set_double_param().
get_eta()
double PHG4CylinderCellReco::get_eta (const double radius, const double z) static protected
Definition at line 904 of file PHG4CylinderCellReco.cc.
Referenced by InitRun().
get_etaphi()
pair< double, double > PHG4CylinderCellReco::get_etaphi (const double x, const double y, const double z) static protected
Definition at line 890 of file PHG4CylinderCellReco.cc.
Referenced by process_event().
get_timing_window_max()
double PHG4CylinderCellReco::get_timing_window_max (const int i) inline
Definition at line 42 of file PHG4CylinderCellReco.h.
References tmin_max.
get_timing_window_min()
double PHG4CylinderCellReco::get_timing_window_min (const int i) inline
Definition at line 41 of file PHG4CylinderCellReco.h.
References tmin_max.
InitRun()
int PHG4CylinderCellReco::InitRun (PHCompositeNode * topNode) virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 52 of file PHG4CylinderCellReco.cc.
References PHG4CylinderCellGeomContainer::AddLayerCellGeom(), PHCompositeNode::addNode(), binning, cell_size, cellnodename, detector, PHG4CellDefs::etaphibinning, etastep, Fun4AllReturnCodes::EVENT_OK, PHG4ParameterContainerInterface::ExistDetid(), PHNodeIterator::findFirst(), geonodename, PHG4CylinderGeomContainer::get_begin_end(), PHG4ParameterContainerInterface::get_double_param(), get_eta(), PHG4CylinderGeom::get_layer(), PHG4CylinderGeom::get_radius(), PHG4CylinderGeom::get_thickness(), PHG4CylinderGeom::get_zmax(), PHG4CylinderGeom::get_zmin(), PHG4ParameterContainerInterface::GetParamsContainer(), PHG4ParameterContainerInterface::GetParamsContainerModify(), hitnodename, PHG4CylinderCellGeom::identify(), PHG4CylinderGeomContainer::identify(), implemented_detid, n_phi_z_bins, Fun4AllBase::Name(), PHG4ParametersContainer::Name(), nbins, outdetector, phistep, PHWHERE, PHG4ParameterContainerInterface::SaveToNodeTree(), seggeonodename, PHG4CylinderCellGeom::set_binning(), PHG4CylinderCellGeom::set_etabins(), PHG4CylinderCellGeom::set_etamin(), PHG4CylinderCellGeom::set_etastep(), PHG4CylinderCellGeom::set_layer(), PHG4ParametersContainer::set_name(), PHG4CylinderCellGeom::set_phibins(), PHG4CylinderCellGeom::set_phimin(), PHG4CylinderCellGeom::set_phistep(), PHG4CylinderCellGeom::set_radius(), set_size(), PHG4CylinderCellGeom::set_thickness(), PHG4CylinderCellGeom::set_zbins(), PHG4CylinderCellGeom::set_zmin(), PHG4CylinderCellGeom::set_zstep(), PHG4CellDefs::sizebinning, tmin_max, PHG4ParameterContainerInterface::UpdateParametersWithMacro(), Fun4AllBase::verbosity, and zmin_max.
line_and_rectangle_intersect()
bool PHG4CylinderCellReco::line_and_rectangle_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double * rr) protected
Definition at line 980 of file PHG4CylinderCellReco.cc.
References lines_intersect().
Referenced by process_event().
lines_intersect()
bool PHG4CylinderCellReco::lines_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double * rx, double * ry) protected
Definition at line 919 of file PHG4CylinderCellReco.cc.
Referenced by line_and_rectangle_intersect().
OutputDetector()
void PHG4CylinderCellReco::OutputDetector (const std::string & d) inline
Definition at line 39 of file PHG4CylinderCellReco.h.
References outdetector.
Referenced by Detector().
process_event()
int PHG4CylinderCellReco::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 330 of file PHG4CylinderCellReco.cc.
References _timer, PHG4Cell::add_edep(), PHG4Cell::add_light_yield(), PHG4Cell::add_shower_edep(), PHG4CellContainer::AddCell(), binning, cell_size, cellnodename, cellptmap, CheckEnergy(), chkenergyconservation, PHG4CellDefs::etaphibinning, Fun4AllReturnCodes::EVENT_OK, PHG4CellDefs::EtaPhiBinning::genkey(), PHG4CellDefs::SizeBinning::genkey(), PHTimeServer::timer::get(), PHG4Cell::get_edep(), PHG4CylinderCellGeom::get_etabin(), PHG4CellDefs::EtaPhiBinning::get_etabin(), PHG4CylinderCellGeom::get_etacenter(), get_etaphi(), PHG4CylinderCellGeom::get_etastep(), PHG4CylinderCellGeom::get_phibin(), PHG4CellDefs::SizeBinning::get_phibin(), PHG4CellDefs::EtaPhiBinning::get_phibin(), PHG4CylinderCellGeom::get_phicenter(), PHG4CylinderCellGeom::get_phistep(), PHG4CylinderCellGeom::get_zbin(), PHG4CellDefs::SizeBinning::get_zbin(), PHG4CylinderCellGeom::get_zcenter(), PHG4CylinderCellGeom::get_zstep(), PHG4HitContainer::getHits(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), PHG4HitContainer::getLayers(), hitnodename, implemented_detid, it, line_and_rectangle_intersect(), n_phi_z_bins, Fun4AllBase::Name(), phistep, PHWHERE, PHG4Hit::prop_light_yield, PHTimer::restart(), seggeonodename, PHTimer::stop(), sum_energy_before_cuts, sum_energy_g4hit, tmin_max, Fun4AllBase::verbosity, and zmin_max.
ResetEvent()
int PHG4CylinderCellReco::ResetEvent (PHCompositeNode *) virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 45 of file PHG4CylinderCellReco.cc.
References Fun4AllReturnCodes::EVENT_OK, sum_energy_before_cuts, and sum_energy_g4hit.
set_size()
void PHG4CylinderCellReco::set_size (const int i, const double sizeA, const double sizeB) protected
Definition at line 875 of file PHG4CylinderCellReco.cc.
References cell_size.
Referenced by InitRun().
set_timing_window()
void PHG4CylinderCellReco::set_timing_window (const int detid, const double tmin, const double tmax)
Definition at line 882 of file PHG4CylinderCellReco.cc.
References PHG4ParameterContainerInterface::set_double_param().
SetDefaultParameters()
void PHG4CylinderCellReco::SetDefaultParameters () virtual
Implements PHG4ParameterContainerInterface.
Definition at line 1158 of file PHG4CylinderCellReco.cc.
References PHG4ParameterContainerInterface::set_default_double_param().
Referenced by PHG4CylinderCellReco().
Member Data Documentation
_timer
PHTimeServer::timer PHG4CylinderCellReco::_timer protected
Definition at line 70 of file PHG4CylinderCellReco.h.
Referenced by process_event().
binning
std::map<int, int> PHG4CylinderCellReco::binning protected
Definition at line 53 of file PHG4CylinderCellReco.h.
Referenced by cellsize(), etaphisize(), InitRun(), and process_event().
cell_size
std::map<int, std::pair <double,double> > PHG4CylinderCellReco::cell_size protected
Definition at line 54 of file PHG4CylinderCellReco.h.
Referenced by InitRun(), process_event(), and set_size().
cellnodename
std::string PHG4CylinderCellReco::cellnodename protected
Definition at line 62 of file PHG4CylinderCellReco.h.
Referenced by CheckEnergy(), InitRun(), and process_event().
cellptmap
std::map<unsigned long long, PHG4Cell*> PHG4CylinderCellReco::cellptmap protected
Definition at line 66 of file PHG4CylinderCellReco.h.
Referenced by process_event().
chkenergyconservation
int PHG4CylinderCellReco::chkenergyconservation protected
Definition at line 72 of file PHG4CylinderCellReco.h.
Referenced by checkenergy(), and process_event().
detector
std::string PHG4CylinderCellReco::detector protected
Definition at line 59 of file PHG4CylinderCellReco.h.
Referenced by Detector(), and InitRun().
etastep
std::map<int, double> PHG4CylinderCellReco::etastep protected
Definition at line 57 of file PHG4CylinderCellReco.h.
Referenced by InitRun().
geonodename
std::string PHG4CylinderCellReco::geonodename protected
Definition at line 63 of file PHG4CylinderCellReco.h.
Referenced by InitRun().
hitnodename
std::string PHG4CylinderCellReco::hitnodename protected
Definition at line 61 of file PHG4CylinderCellReco.h.
Referenced by InitRun(), and process_event().
implemented_detid
std::set<int> PHG4CylinderCellReco::implemented_detid protected
Definition at line 58 of file PHG4CylinderCellReco.h.
Referenced by InitRun(), and process_event().
it
std::map<unsigned long long, PHG4Cell*>::iterator PHG4CylinderCellReco::it protected
Definition at line 67 of file PHG4CylinderCellReco.h.
Referenced by process_event().
n_phi_z_bins
std::map<int, std::pair<int, int> > PHG4CylinderCellReco::n_phi_z_bins protected
Definition at line 65 of file PHG4CylinderCellReco.h.
Referenced by InitRun(), and process_event().
nbins
int PHG4CylinderCellReco::nbins[2] protected
Definition at line 71 of file PHG4CylinderCellReco.h.
Referenced by InitRun(), and PHG4CylinderCellReco().
outdetector
std::string PHG4CylinderCellReco::outdetector protected
Definition at line 60 of file PHG4CylinderCellReco.h.
Referenced by Detector(), InitRun(), and OutputDetector().
phistep
std::map<int, double> PHG4CylinderCellReco::phistep protected
Definition at line 56 of file PHG4CylinderCellReco.h.
Referenced by InitRun(), and process_event().
seggeonodename
std::string PHG4CylinderCellReco::seggeonodename protected
Definition at line 64 of file PHG4CylinderCellReco.h.
Referenced by InitRun(), and process_event().
sum_energy_before_cuts
double PHG4CylinderCellReco::sum_energy_before_cuts protected
Definition at line 74 of file PHG4CylinderCellReco.h.
Referenced by CheckEnergy(), process_event(), and ResetEvent().
sum_energy_g4hit
double PHG4CylinderCellReco::sum_energy_g4hit protected
Definition at line 75 of file PHG4CylinderCellReco.h.
Referenced by CheckEnergy(), process_event(), and ResetEvent().
tmin_max
std::map<int, std::pair<double,double> > PHG4CylinderCellReco::tmin_max protected
Definition at line 68 of file PHG4CylinderCellReco.h.
Referenced by get_timing_window_max(), get_timing_window_min(), InitRun(), and process_event().
zmin_max
std::map<int, std::pair <double,double> > PHG4CylinderCellReco::zmin_max protected
Definition at line 55 of file PHG4CylinderCellReco.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellReco.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellReco.cc