Class Reference for E1039 Core & Analysis Software: PHG4CellDefs::EtaXsizeBinning Namespace Reference
PHG4CellDefs::EtaXsizeBinning Namespace Reference
Functions
keytype genkey (const unsigned short layer, const unsigned short etabin, const unsigned short xbin)
unsigned short int get_etabin (const PHG4CellDefs::keytype key)
unsigned short int get_xsizebin (const PHG4CellDefs::keytype key)
Function Documentation
genkey()
PHG4CellDefs::keytype PHG4CellDefs::EtaXsizeBinning::genkey (const unsigned short layer, const unsigned short etabin, const unsigned short xbin)
Definition at line 114 of file PHG4CellDefs.cc.
References PHG4CellDefs::etaxsizebinning, and generic_16bit_genkey().
Referenced by PHG4BlockCellReco::process_event().
get_etabin()
unsigned short int PHG4CellDefs::EtaXsizeBinning::get_etabin (const PHG4CellDefs::keytype key)
Definition at line 121 of file PHG4CellDefs.cc.
References PHG4CellDefs::etaxsizebinning, and generic_lower_16bit_key().
get_xsizebin()
unsigned short int PHG4CellDefs::EtaXsizeBinning::get_xsizebin (const PHG4CellDefs::keytype key)
Definition at line 128 of file PHG4CellDefs.cc.
References PHG4CellDefs::etaxsizebinning, and generic_upper_16bit_key().