Class Reference for E1039 Core & Analysis Software: SyncObjectv2 Class Reference
SyncObjectv2 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/SyncObjectv2.h>
Public Member Functions
SyncObjectv2 ()
ctor
SyncObjectv2 (const SyncObject &)
SyncObjectv2 * clone () const
Virtual copy constructor.
virtual ~SyncObjectv2 ()
dtor
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
void SegmentNumber (const int ival)
set Segment Number
Public Member Functions inherited from SyncObjectv1
SyncObjectv1 ()
ctor
SyncObjectv1 (const SyncObject &)
virtual ~SyncObjectv1 ()
dtor
int isValid () const
isValid returns non zero if object contains valid data
void EventCounter (const int ival)
set Event Counter
void EventNumber (const int ival)
set Event Number
void RunNumber (const int ival)
set Run Number
Public Member Functions inherited from SyncObject
virtual ~SyncObject ()
dtor
virtual SyncObject & operator= (const SyncObject &source)
virtual int Different (const SyncObject *other) const
virtual ~SyncObject ()
dtor
virtual SyncObject & operator= (const SyncObject &source)
virtual int Different (const SyncObject *other) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
int SegmentNumber () const
get Segment Number
Protected Member Functions inherited from SyncObjectv1
int EventCounter () const
get Event Counter
int EventNumber () const
get Event Number
int RunNumber () const
get Run Number
Protected Attributes
int segmentnumber
Protected Attributes inherited from SyncObjectv1
int eventcounter
int eventnumber
int runnumber
Detailed Description
Definition at line 7 of file SyncObjectv2.h.
Constructor & Destructor Documentation
SyncObjectv2() [1/2]
SyncObjectv2::SyncObjectv2 ()
ctor
Definition at line 9 of file SyncObjectv2.cc.
Referenced by clone().
SyncObjectv2() [2/2]
SyncObjectv2::SyncObjectv2 (const SyncObject & source)
Definition at line 15 of file SyncObjectv2.cc.
References SyncObjectv1::EventCounter(), SyncObject::EventCounter(), SyncObjectv1::EventNumber(), SyncObject::EventNumber(), SyncObjectv1::RunNumber(), SyncObject::RunNumber(), SegmentNumber(), and SyncObject::SegmentNumber().
~SyncObjectv2()
virtual SyncObjectv2::~SyncObjectv2 () inline virtual
dtor
Definition at line 17 of file SyncObjectv2.h.
Member Function Documentation
clone()
SyncObjectv2* SyncObjectv2::clone () const inline virtual
Virtual copy constructor.
Reimplemented from SyncObjectv1.
Definition at line 15 of file SyncObjectv2.h.
References SyncObjectv2().
identify()
void SyncObjectv2::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SyncObjectv1.
Definition at line 30 of file SyncObjectv2.cc.
References SyncObjectv1::eventcounter, SyncObjectv1::eventnumber, SyncObjectv1::runnumber, and segmentnumber.
Reset()
void SyncObjectv2::Reset () virtual
Clear Event.
Reimplemented from SyncObjectv1.
Definition at line 23 of file SyncObjectv2.cc.
References SyncObjectv1::Reset(), and segmentnumber.
SegmentNumber() [1/2]
int SyncObjectv2::SegmentNumber () const inline protected virtual
get Segment Number
Reimplemented from SyncObject.
Definition at line 33 of file SyncObjectv2.h.
References segmentnumber.
Referenced by SyncObjectv2().
SegmentNumber() [2/2]
void SyncObjectv2::SegmentNumber (const int ival) inline virtual
set Segment Number
Reimplemented from SyncObject.
Definition at line 28 of file SyncObjectv2.h.
References segmentnumber.
Member Data Documentation
segmentnumber
int SyncObjectv2::segmentnumber protected
Definition at line 35 of file SyncObjectv2.h.
Referenced by identify(), Reset(), and SegmentNumber().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/SyncObjectv2.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/SyncObjectv2.cc