Class Reference for E1039 Core & Analysis Software: SubsysRecoBG Class Reference
SubsysRecoBG Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/SubsysRecoBG.h>
Public Member Functions
SubsysRecoBG (const std::string &name="SubsysRecoBG")
virtual ~SubsysRecoBG ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void FullBgMode ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
void ExtractHits (const SQHitVector *hit_vec, const std::string det_name, std::vector< int > &list_ele)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 12 of file SubsysRecoBG.h.
Constructor & Destructor Documentation
SubsysRecoBG()
SubsysRecoBG::SubsysRecoBG (const std::string & name = "SubsysRecoBG")
Definition at line 15 of file SubsysRecoBG.cc.
~SubsysRecoBG()
virtual SubsysRecoBG::~SubsysRecoBG () inline virtual
Definition at line 28 of file SubsysRecoBG.h.
Member Function Documentation
End()
int SubsysRecoBG::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 80 of file SubsysRecoBG.cc.
References Fun4AllReturnCodes::EVENT_OK.
ExtractHits()
void SubsysRecoBG::ExtractHits (const SQHitVector * hit_vec, const std::string det_name, std::vector< int > & list_ele) protected
Definition at line 88 of file SubsysRecoBG.cc.
References UtilSQHit::FindFirstHits().
Referenced by process_event().
FullBgMode()
void SubsysRecoBG::FullBgMode () inline
Definition at line 34 of file SubsysRecoBG.h.
Init()
int SubsysRecoBG::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 27 of file SubsysRecoBG.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRun()
int SubsysRecoBG::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 32 of file SubsysRecoBG.cc.
References Fun4AllReturnCodes::ABORTEVENT, and Fun4AllReturnCodes::EVENT_OK.
process_event()
int SubsysRecoBG::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 50 of file SubsysRecoBG.cc.
References Fun4AllReturnCodes::EVENT_OK, BgData::evt, ExtractHits(), BgData::fpga1, SQMCEvent::get_cross_section(), SQEvent::get_event_id(), SQEvent::get_qie_rf_intensity(), SQEvent::get_run_id(), SQEvent::get_trigger(), BgData::h1b, BgData::h1t, BgData::h2b, BgData::h2t, BgData::h3b, BgData::h3t, BgData::h4b, BgData::h4t, BgData::inte_max, BgData::inte_rfp00, SQEvent::MATRIX1, BgData::pot_rfp00, and BgData::run.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/SubsysRecoBG.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/SubsysRecoBG.cc