Class Reference for E1039 Core & Analysis Software: DoEmbedding Class Reference
DoEmbedding Class Reference
An example class to analyze the simulated uDST file.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/HitEmbedding/src/DoEmbedding.h>
Public Member Functions
DoEmbedding (const std::string name="DoEmbedding")
virtual ~DoEmbedding ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void DoOverwriteRfInfo (const bool overwrite)
bool DoOverwriteRfInfo () const
void SetHitIdShift (const int id_shift)
int GetHitIdShift () const
void SetTrackIdShift (const int id_shift)
int GetTrackIdShift () const
void SetDimuonIdShift (const int id_shift)
int GetDimuonIdShift () const
void AddEmbDataFile (const char *fn_root)
void AddEmbDataFiles (const char *fn_list)
int GetNumEmbEvents ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
void OpenEmbDataFile (const char *fn_root)
void CloseEmbDataFile ()
bool GetNextEmbEvent ()
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
An example class to analyze the simulated uDST file.
Definition at line 13 of file DoEmbedding.h.
Constructor & Destructor Documentation
DoEmbedding()
DoEmbedding::DoEmbedding (const std::string name = "DoEmbedding")
Definition at line 17 of file DoEmbedding.cc.
~DoEmbedding()
DoEmbedding::~DoEmbedding () virtual
Definition at line 39 of file DoEmbedding.cc.
Member Function Documentation
AddEmbDataFile()
void DoEmbedding::AddEmbDataFile (const char * fn_root)
Definition at line 160 of file DoEmbedding.cc.
Referenced by AddEmbDataFiles().
AddEmbDataFiles()
void DoEmbedding::AddEmbDataFiles (const char * fn_list)
Definition at line 165 of file DoEmbedding.cc.
References AddEmbDataFile().
CloseEmbDataFile()
void DoEmbedding::CloseEmbDataFile () protected
Definition at line 201 of file DoEmbedding.cc.
Referenced by End(), GetNextEmbEvent(), and GetNumEmbEvents().
DoOverwriteRfInfo() [1/2]
bool DoEmbedding::DoOverwriteRfInfo () const inline
Definition at line 53 of file DoEmbedding.h.
DoOverwriteRfInfo() [2/2]
void DoEmbedding::DoOverwriteRfInfo (const bool overwrite) inline
Definition at line 52 of file DoEmbedding.h.
End()
int DoEmbedding::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 154 of file DoEmbedding.cc.
References CloseEmbDataFile(), and Fun4AllReturnCodes::EVENT_OK.
GetDimuonIdShift()
int DoEmbedding::GetDimuonIdShift () const inline
Definition at line 59 of file DoEmbedding.h.
GetHitIdShift()
int DoEmbedding::GetHitIdShift () const inline
Definition at line 55 of file DoEmbedding.h.
GetNextEmbEvent()
bool DoEmbedding::GetNextEmbEvent () protected
Definition at line 209 of file DoEmbedding.cc.
References CloseEmbDataFile(), and OpenEmbDataFile().
Referenced by process_event().
GetNumEmbEvents()
int DoEmbedding::GetNumEmbEvents ()
Definition at line 173 of file DoEmbedding.cc.
References CloseEmbDataFile(), and OpenEmbDataFile().
GetTrackIdShift()
int DoEmbedding::GetTrackIdShift () const inline
Definition at line 57 of file DoEmbedding.h.
Init()
int DoEmbedding::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 48 of file DoEmbedding.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRun()
int DoEmbedding::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 53 of file DoEmbedding.cc.
References Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
OpenEmbDataFile()
void DoEmbedding::OpenEmbDataFile (const char * fn_root) protected
Definition at line 184 of file DoEmbedding.cc.
References Fun4AllBase::Verbosity().
Referenced by GetNextEmbEvent(), and GetNumEmbEvents().
process_event()
int DoEmbedding::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 99 of file DoEmbedding.cc.
References Fun4AllReturnCodes::ABORTEVENT, SQDimuonVector::begin(), SQHitVector::begin(), SQTrackVector::begin(), SQDimuonVector::end(), SQHitVector::end(), SQTrackVector::end(), Fun4AllReturnCodes::EVENT_OK, SQDimuon::get_dimuon_id(), SQEvent::get_event_id(), SQHit::get_hit_id(), SQEvent::get_qie_rf_id(), SQEvent::get_qie_rf_intensity(), SQEvent::get_qie_turn_id(), SQEvent::get_run_id(), SQEvent::get_spill_id(), SQHit::get_track_id(), SQTrack::get_track_id(), SQDimuon::get_track_id_neg(), SQDimuon::get_track_id_pos(), GetNextEmbEvent(), SQDimuonVector::push_back(), SQHitVector::push_back(), SQTrackVector::push_back(), SQDimuon::set_dimuon_id(), SQHit::set_hit_id(), SQEvent::set_qie_rf_id(), SQEvent::set_qie_rf_intensity(), SQEvent::set_qie_turn_id(), SQHit::set_track_id(), SQTrack::set_track_id(), SQDimuon::set_track_id_neg(), SQDimuon::set_track_id_pos(), SQDimuonVector::size(), SQHitVector::size(), SQTrackVector::size(), and Fun4AllBase::Verbosity().
SetDimuonIdShift()
void DoEmbedding::SetDimuonIdShift (const int id_shift) inline
Definition at line 58 of file DoEmbedding.h.
SetHitIdShift()
void DoEmbedding::SetHitIdShift (const int id_shift) inline
Definition at line 54 of file DoEmbedding.h.
SetTrackIdShift()
void DoEmbedding::SetTrackIdShift (const int id_shift) inline
Definition at line 56 of file DoEmbedding.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/HitEmbedding/src/DoEmbedding.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/HitEmbedding/src/DoEmbedding.cc