E1039 Software: KalmanDSTrk Class Reference
KalmanDSTrk Class Reference
Pattern Dictionary Filter built based on Kun Liu's ktracker.
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/patterndb/KalmanDSTrk.h>
Public Types
enum DS_LEVEL { NO_DS, IN_ST_DS, ST23_DS, ST123_DS }
Public Member Functions
KalmanDSTrk (const PHField *field, const TGeoManager *geom, bool enable_KF=true, int DS_level=KalmanDSTrk::NO_DS, const std::string sim_db_name="", const std::string pattern_db_name="")
~KalmanDSTrk ()
void Verbosity (const int a)
int Verbosity () const
void printTimers ()
int setRawEvent (SRawEvent *event_input)
int setRawEventWorker (SRawEvent *event_input)
void setRawEventDebug (SRawEvent *event_input)
bool acceptEvent (SRawEvent *rawEvent)
void buildTrackletsInStation (int stationID, int listID, double *pos_exp=NULL, double *window=NULL)
Tracklet finding stuff.
void buildBackPartialTracks ()
void buildGlobalTracks ()
int fitTracklet (Tracklet &tracklet)
bool acceptTracklet (Tracklet &tracklet)
bool hodoMask (Tracklet &tracklet)
bool muonID_comp (Tracklet &tracklet)
bool muonID_search (Tracklet &tracklet)
bool muonID_hodoAid (Tracklet &tracklet)
void buildPropSegments ()
void resolveLeftRight (SRawEvent::hit_pair hpair, int &LR1, int &LR2)
void resolveLeftRight (Tracklet &tracklet, double threshold)
void resolveSingleLeftRight (Tracklet &tracklet)
void removeBadHits (Tracklet &tracklet)
int reduceTrackletList (std::list< Tracklet > &tracklets)
void getSagittaWindowsInSt1 (Tracklet &tracklet, double *pos_exp, double *window, int st1ID)
void getExtrapoWindowsInSt1 (Tracklet &tracklet, double *pos_exp, double *window, int st1ID)
void printAtDetectorBack (int stationID, std::string outputFileName)
SRecTrack processOneTracklet (Tracklet &tracklet)
Track fitting stuff.
bool fitTrack (KalmanTrack &kmtrk)
void resolveLeftRight (KalmanTrack &kmtrk)
std::list< Tracklet > & getFinalTracklets ()
Final output.
std::list< Tracklet > & getBackPartials ()
std::list< Tracklet > & getTrackletList (int i)
std::list< SRecTrack > & getSRecTracks ()
std::list< PropSegment > & getPropSegments (int i)
void chi2fit (int n, double x[], double y[], double &a, double &b)
const std::string & get_pattern_db_name () const
void set_pattern_db_name (const std::string &patternDbName)
const std::string & get_sim_db_name () const
void set_sim_db_name (const std::string &simDbName)
Private Attributes
int verbosity
SRawEvent * rawEvent
std::vector< Hit > hitAll
std::list< Tracklet > trackletsInSt [5]
std::list< SRecTrack > stracks
std::list< PropSegment > propSegs [2]
std::vector< int > detectorIDs_mask [4]
Configurations of tracklet finding.
std::vector< int > detectorIDs_maskX [4]
std::vector< int > detectorIDs_maskY [4]
std::list< int > hitIDs_mask [4]
std::vector< int > detectorIDs_muidHodoAid [2]
std::vector< int > stationIDs_mask [nStations]
int detectorIDs_muid [2][4]
double z_ref_muid [2][4]
std::list< int > hitIDs_muid [2][4]
std::list< int > hitIDs_muidHodoAid [2]
double z_mask [nHodoPlanes+nPropPlanes]
double x_mask_min [nHodoPlanes+nPropPlanes][72]
double x_mask_max [nHodoPlanes+nPropPlanes][72]
double y_mask_min [nHodoPlanes+nPropPlanes][72]
double y_mask_max [nHodoPlanes+nPropPlanes][72]
std::vector< int > superIDs [nChamberPlanes/6+2]
For following part, id = 0, 1, 2, 3, 4, 5, 6 stand for station 0, 1, 2, 3+, 3-, and prop tubes X-Z and Y-Z.
double u_win [nChamberPlanes/6]
double u_costheta [nChamberPlanes/6]
double u_sintheta [nChamberPlanes/6]
double z_plane_x [nChamberPlanes/6]
double z_plane_u [nChamberPlanes/6]
double z_plane_v [nChamberPlanes/6]
double costheta_plane [nChamberPlanes+1]
double sintheta_plane [nChamberPlanes+1]
double z_plane [nChamberPlanes+1]
double slope_max [nChamberPlanes+1]
double intersection_max [nChamberPlanes+1]
double resol_plane [nChamberPlanes+1]
double spacing_plane [nChamberPlanes+1]
int s_detectorID [3]
Tracklet tracklet_curr
ROOT::Math::Minimizer * minimizer [2]
ROOT::Math::Functor fcn
KalmanFitter * kmfitter
GeomSvc * p_geomSvc
JobOptsSvc * p_jobOptsSvc
const bool _enable_KF
int _DS_level
std::string _sim_db_name
std::string _pattern_db_name
PatternDB * _pattern_db
std::map< std::string, PHTimer * > _timers
bool _ana_mode
Analysis mode.
TFile * _fana
TNtuple * _tana_Event
TNtuple * _tana_St1
TNtuple * _tana_St2
TNtuple * _tana_St3
TNtuple * _tana_St23
TNtuple * _tana_St123
int _event
Detailed Description
Pattern Dictionary Filter built based on Kun Liu's ktracker.
Author
Haiwang Yu, yuhw@.nosp@m.nmsu.nosp@m..edu
Created: 08-27-2018
Definition at line 40 of file KalmanDSTrk.h.
Member Enumeration Documentation
enum KalmanDSTrk::DS_LEVEL
Enumerator
NO_DS
IN_ST_DS
ST23_DS
ST123_DS
Definition at line 45 of file KalmanDSTrk.h.
Constructor & Destructor Documentation
KalmanDSTrk::KalmanDSTrk (const PHField * field, const TGeoManager * geom, bool enable_KF = true, int DS_level = KalmanDSTrk::NO_DS, const std::string sim_db_name = "", const std::string pattern_db_name = "") explicit
Definition at line 36 of file KalmanDSTrk.cxx.
References _ana_mode, _DS_level, _enable_KF, _event, _fana, _pattern_db, _pattern_db_name, _sim_db_name, _tana_Event, _tana_St1, _tana_St123, _tana_St2, _tana_St23, _tana_St3, _timers, PatternDBUtil::BuildPatternDB(), costheta_plane, detectorIDs_mask, detectorIDs_maskX, detectorIDs_maskY, detectorIDs_muid, detectorIDs_muidHodoAid, Tracklet::Eval(), fcn, GeomSvc::get2DBoxSize(), GeomSvc::getCostheta(), GeomSvc::getDetectorID(), GeomSvc::getDetectorIDs(), GeomSvc::getPlaneNElements(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneResolution(), GeomSvc::getPlaneScaleY(), GeomSvc::getPlaneSpacing(), GeomSvc::getSintheta(), JobOptsSvc::instance(), GeomSvc::instance(), intersection_max, kmfitter, PatternDBUtil::LoadPatternDB(), JobOptsSvc::m_enableKMag, JobOptsSvc::m_st0_reject, JobOptsSvc::m_st1_reject, JobOptsSvc::m_st2_reject, JobOptsSvc::m_st3m_reject, JobOptsSvc::m_st3p_reject, minimizer, MUID_Z_REF, nChamberPlanes, nHodoPlanes, NO_DS, nPropPlanes, nStations, p_geomSvc, p_jobOptsSvc, GeomSvc::printAlignPar(), GeomSvc::printTable(), GeomSvc::printWirePosition(), resol_plane, s_detectorID, KalmanFitter::setControlParameter(), sintheta_plane, slope_max, spacing_plane, PatternDB::St23, stationIDs_mask, superIDs, tracklet_curr, TX_MAX, TY_MAX, u_costheta, u_sintheta, u_win, X0_MAX, x_mask_max, x_mask_min, Y0_MAX, y_mask_max, y_mask_min, z_mask, z_plane, z_plane_u, z_plane_v, z_plane_x, and z_ref_muid.
KalmanDSTrk::~KalmanDSTrk ()
Definition at line 420 of file KalmanDSTrk.cxx.
References _ana_mode, _enable_KF, _fana, _tana_Event, _tana_St1, _tana_St123, _tana_St2, _tana_St23, _tana_St3, kmfitter, and minimizer.
Member Function Documentation
bool KalmanDSTrk::acceptEvent (SRawEvent * rawEvent)
Definition at line 643 of file KalmanDSTrk.cxx.
References detectorIDs_maskX, SRawEvent::getNHitsInD0(), SRawEvent::getNHitsInD1(), SRawEvent::getNHitsInD2(), SRawEvent::getNHitsInD3m(), SRawEvent::getNHitsInD3p(), SRawEvent::getNHitsInDetectors(), SRawEvent::getNPropHitsAll(), SRawEvent::getNRoadsNeg(), SRawEvent::getNRoadsPos(), LogInfo, Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
Referenced by setRawEventWorker().
bool KalmanDSTrk::acceptTracklet (Tracklet & tracklet)
Definition at line 1684 of file KalmanDSTrk.cxx.
References Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), hodoMask(), GeomSvc::isInKMAG(), Tracklet::isValid(), LogInfo, muonID_comp(), muonID_search(), nStations, p_geomSvc, Tracklet::stationID, and Z_KMAG_BEND.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), and buildTrackletsInStation().
void KalmanDSTrk::buildBackPartialTracks ()
Remove bad hits if needed
Definition at line 681 of file KalmanDSTrk.cxx.
References _ana_mode, _DS_level, _pattern_db, _tana_St23, _timers, acceptTracklet(), chi2fit(), Tracklet::chisq, PatternDB::DC2, PatternDB::DC3m, PatternDB::DC3p, detectorIDs_muid, PatternDB::ERR_KEY, fitTracklet(), GeomSvc::getPlaneType(), PatternDBUtil::GetTrackletKey(), hitAll, hitIDs_muid, hodoMask(), Tracklet::isValid(), LogInfo, nChamberPlanes, p_geomSvc, Tracklet::print(), reduceTrackletList(), removeBadHits(), resolveLeftRight(), PatternDB::St23, ST23_DS, trackletsInSt, TX_MAX, Verbosity(), verbosity, Fun4AllBase::VERBOSITY_A_LOT, X0_MAX, z_mask, and z_plane.
Referenced by setRawEventWorker().
void KalmanDSTrk::buildGlobalTracks ()
Resolve the left-right with a tight pull cut, then a loose one, then resolve by single projections
Remove bad hits if needed
Definition at line 899 of file KalmanDSTrk.cxx.
References _ana_mode, _DS_level, _pattern_db, _tana_St123, _timers, acceptTracklet(), buildTrackletsInStation(), Tracklet::chisq_vtx, PatternDB::DC1, PatternDB::DC2, PatternDB::DC3m, PatternDB::DC3p, PatternDB::ERR_KEY, fitTracklet(), SRecTrack::getChisqVertex(), getExtrapoWindowsInSt1(), Tracklet::getMomentum(), getSagittaWindowsInSt1(), PatternDBUtil::GetTrackletKey(), hodoMask(), Tracklet::invP, SRecTrack::isValid(), Tracklet::isValid(), LogInfo, JobOptsSvc::m_enableKMag, Tracklet::merge(), MERGE_THRES, p_jobOptsSvc, Tracklet::print(), processOneTracklet(), removeBadHits(), resolveLeftRight(), resolveSingleLeftRight(), PatternDB::St123, ST123_DS, trackletsInSt, Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
Referenced by setRawEventWorker().
void KalmanDSTrk::buildPropSegments ()
Definition at line 1943 of file KalmanDSTrk.cxx.
References PropSegment::fit(), SRawEvent::getPartialHitPairsInSuperDetector(), hitAll, PropSegment::hits, PropSegment::isValid(), LogInfo, PropSegment::print(), propSegs, rawEvent, and superIDs.
Referenced by setRawEventWorker().
void KalmanDSTrk::buildTrackletsInStation (int stationID, int listID, double * pos_exp = NULL, double * window = NULL)
Tracklet finding stuff.
Definition at line 1416 of file KalmanDSTrk.cxx.
References _ana_mode, _DS_level, _pattern_db, _tana_St1, _tana_St2, _tana_St3, _timers, acceptTracklet(), PatternDB::DC1, PatternDB::DC2, PatternDB::DC3m, PatternDB::DC3p, PatternDB::ERROR_STATION, fitTracklet(), SRawEvent::getPartialHitPairsInSuperDetector(), PatternDBUtil::GetTrackletKey(), hitAll, Tracklet::hits, IN_ST_DS, Tracklet::isValid(), LogInfo, Tracklet::nUHits, NULL, Tracklet::nVHits, Tracklet::nXHits, Tracklet::print(), rawEvent, Tracklet::sortHits(), spacing_plane, PatternDB::St1, PatternDB::St2, PatternDB::St3, Tracklet::stationID, superIDs, trackletsInSt, TX_MAX, TY_MAX, u_costheta, u_sintheta, u_win, Verbosity(), Fun4AllBase::VERBOSITY_A_LOT, z_plane, z_plane_u, z_plane_v, and z_plane_x.
Referenced by buildGlobalTracks(), and setRawEventWorker().
void KalmanDSTrk::chi2fit (int n, double x[], double y[], double & a, double & b)
Tool, a simple-minded chi square fit Y = a*X + b
Definition at line 2409 of file KalmanDSTrk.cxx.
Referenced by buildBackPartialTracks().
bool KalmanDSTrk::fitTrack (KalmanTrack & kmtrk)
Definition at line 2324 of file KalmanDSTrk.cxx.
References KalmanTrack::getNodeList(), kmfitter, KalmanFitter::processOneTrack(), and KalmanFitter::updateTrack().
Referenced by processOneTracklet(), and resolveLeftRight().
int KalmanDSTrk::fitTracklet (Tracklet & tracklet)
Definition at line 2008 of file KalmanDSTrk.cxx.
References Tracklet::chisq, Tracklet::err_invP, Tracklet::err_tx, Tracklet::err_ty, Tracklet::err_x0, Tracklet::err_y0, Tracklet::invP, INVP_MAX, INVP_MIN, JobOptsSvc::m_enableKMag, minimizer, nStations, p_jobOptsSvc, Tracklet::stationID, tracklet_curr, Tracklet::tx, TX_MAX, Tracklet::ty, TY_MAX, Tracklet::x0, X0_MAX, Tracklet::y0, and Y0_MAX.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), buildTrackletsInStation(), removeBadHits(), resolveLeftRight(), and resolveSingleLeftRight().
const std::string& KalmanDSTrk::get_pattern_db_name () const inline
Definition at line 132 of file KalmanDSTrk.h.
References _pattern_db_name.
const std::string& KalmanDSTrk::get_sim_db_name () const inline
Definition at line 140 of file KalmanDSTrk.h.
References _sim_db_name.
std::list<Tracklet>& KalmanDSTrk::getBackPartials () inline
Definition at line 123 of file KalmanDSTrk.h.
References trackletsInSt.
void KalmanDSTrk::getExtrapoWindowsInSt1 (Tracklet & tracklet, double * pos_exp, double * window, int st1ID)
Definition at line 2087 of file KalmanDSTrk.cxx.
References costheta_plane, Tracklet::getExpPosErrorX(), Tracklet::getExpPosErrorY(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), GeomSvc::getPlaneType(), GeomSvc::getUinStereoPlane(), nStations, p_geomSvc, sintheta_plane, Tracklet::stationID, and z_plane.
Referenced by buildGlobalTracks().
std::list<Tracklet>& KalmanDSTrk::getFinalTracklets () inline
Final output.
Definition at line 122 of file KalmanDSTrk.h.
References trackletsInSt.
std::list<PropSegment>& KalmanDSTrk::getPropSegments (int i) inline
Definition at line 126 of file KalmanDSTrk.h.
References propSegs.
void KalmanDSTrk::getSagittaWindowsInSt1 (Tracklet & tracklet, double * pos_exp, double * window, int st1ID)
Definition at line 2115 of file KalmanDSTrk.cxx.
References Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), GeomSvc::getPlaneType(), GeomSvc::getUinStereoPlane(), Tracklet::hits, nStations, p_geomSvc, s_detectorID, SAGITTA_DUMP_CENTER, SAGITTA_DUMP_WIN, SAGITTA_TARGET_CENTER, SAGITTA_TARGET_WIN, Tracklet::stationID, Z_DUMP, z_plane, and Z_TARGET.
Referenced by buildGlobalTracks().
std::list<SRecTrack>& KalmanDSTrk::getSRecTracks () inline
Definition at line 125 of file KalmanDSTrk.h.
References stracks.
std::list<Tracklet>& KalmanDSTrk::getTrackletList (int i) inline
Definition at line 124 of file KalmanDSTrk.h.
References trackletsInSt.
bool KalmanDSTrk::hodoMask (Tracklet & tracklet)
Definition at line 1714 of file KalmanDSTrk.cxx.
References Tracklet::getExpPosErrorX(), Tracklet::getExpPosErrorY(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), hitAll, hitIDs_mask, LogInfo, nChamberPlanes, nStations, Tracklet::stationID, stationIDs_mask, x_mask_max, x_mask_min, y_mask_max, y_mask_min, and z_mask.
Referenced by acceptTracklet(), buildBackPartialTracks(), and buildGlobalTracks().
bool KalmanDSTrk::muonID_comp (Tracklet & tracklet)
Definition at line 1837 of file KalmanDSTrk.cxx.
References Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::invP, LogInfo, MUID_EMP_P0, MUID_EMP_P1, MUID_EMP_P2, MUID_R_CUT, MUID_REJECT, MUID_THE_P0, MUID_Z_REF, nStations, propSegs, Tracklet::seg_x, Tracklet::seg_y, Tracklet::stationID, Tracklet::tx, and Tracklet::ty.
Referenced by acceptTracklet().
bool KalmanDSTrk::muonID_hodoAid (Tracklet & tracklet)
Definition at line 1894 of file KalmanDSTrk.cxx.
References Tracklet::getExpPosErrorX(), Tracklet::getExpPosErrorY(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), hitAll, hitIDs_muidHodoAid, PropSegment::hodoHits, Tracklet::invP, MUID_EMP_P0, MUID_EMP_P1, MUID_EMP_P2, MUID_REJECT, MUID_THE_P0, MUID_Z_REF, nChamberPlanes, PropSegment::nHodoHits, nStations, Tracklet::seg_x, Tracklet::seg_y, Tracklet::stationID, x_mask_max, x_mask_min, y_mask_max, y_mask_min, and z_mask.
Referenced by muonID_search().
bool KalmanDSTrk::muonID_search (Tracklet & tracklet)
Definition at line 1765 of file KalmanDSTrk.cxx.
References detectorIDs_muid, PropSegment::fit(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), PropSegment::getPosRef(), SignedHit::hit, hitAll, hitIDs_muid, PropSegment::hits, PropSegment::init(), Tracklet::invP, GeomSvc::isInPlane(), MUID_EMP_P0, MUID_EMP_P1, MUID_EMP_P2, MUID_REJECT, MUID_THE_P0, MUID_Z_REF, muonID_hodoAid(), nChamberPlanes, PropSegment::nHodoHits, nStations, p_geomSvc, Tracklet::seg_x, Tracklet::seg_y, SignedHit::sign, Tracklet::stationID, Tracklet::tx, Tracklet::ty, z_mask, and z_ref_muid.
Referenced by acceptTracklet().
void KalmanDSTrk::printAtDetectorBack (int stationID, std::string outputFileName)
Definition at line 2163 of file KalmanDSTrk.cxx.
References c1, GeomSvc::getPlaneCenterX(), GeomSvc::getPlaneCenterY(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneScaleX(), GeomSvc::getPlaneScaleY(), p_geomSvc, and trackletsInSt.
void KalmanDSTrk::printTimers ()
Definition at line 2377 of file KalmanDSTrk.cxx.
References _event, and _timers.
SRecTrack KalmanDSTrk::processOneTracklet (Tracklet & tracklet)
Track fitting stuff.
Definition at line 2207 of file KalmanDSTrk.cxx.
References TrkPar::_covar_kf, TrkPar::_state_kf, TrkPar::_z, PropSegment::a, fitTrack(), Tracklet::getCharge(), KalmanTrack::getChisq(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), KalmanTrack::getHitIndexList(), PropSegment::getNHits(), KalmanTrack::getNodeList(), GeomSvc::getPlanePosition(), TriggerRoad::getRoadID(), KalmanTrack::getSRecTrack(), Tracklet::getSRecTrack(), Tracklet::hits, Tracklet::invP, KalmanTrack::isValid(), LogInfo, p_geomSvc, KalmanTrack::print(), KalmanTrack::printNodes(), Tracklet::seg_x, Tracklet::seg_y, KalmanTrack::setCurrTrkpar(), SRecTrack::setKalmanStatus(), SRecTrack::setNHitsInPT(), SRecTrack::setPTSlope(), SRecTrack::setTriggerRoad(), Tracklet::tx, and Tracklet::ty.
Referenced by buildGlobalTracks(), and setRawEventWorker().
int KalmanDSTrk::reduceTrackletList (std::list< Tracklet > & tracklets)
Definition at line 2050 of file KalmanDSTrk.cxx.
References LogInfo.
Referenced by buildBackPartialTracks().
void KalmanDSTrk::removeBadHits (Tracklet & tracklet)
Definition at line 1276 of file KalmanDSTrk.cxx.
References Tracklet::calcChisq(), Hit::detectorID, Hit::driftDistance, fitTracklet(), GeomSvc::getPlaneType(), SignedHit::hit, Tracklet::hits, Hit::index, Tracklet::isValid(), LogInfo, nChamberPlanes, Tracklet::nUHits, NULL, Tracklet::nVHits, Tracklet::nXHits, p_geomSvc, Hit::print(), Tracklet::print(), Tracklet::residual, resol_plane, resolveSingleLeftRight(), and SignedHit::sign.
Referenced by buildBackPartialTracks(), and buildGlobalTracks().
void KalmanDSTrk::resolveLeftRight (SRawEvent::hit_pair hpair, int & LR1, int & LR2)
Definition at line 1376 of file KalmanDSTrk.cxx.
References hitAll, intersection_max, slope_max, and z_plane.
Referenced by buildBackPartialTracks(), and buildGlobalTracks().
void KalmanDSTrk::resolveLeftRight (Tracklet & tracklet, double threshold)
Definition at line 1145 of file KalmanDSTrk.cxx.
References costheta_plane, Tracklet::err_tx, Tracklet::err_ty, Tracklet::err_x0, Tracklet::err_y0, fitTracklet(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::getXZErrorInSt1(), Tracklet::getXZInfoInSt1(), Tracklet::hits, intersection_max, LogInfo, Tracklet::print(), sintheta_plane, slope_max, Tracklet::stationID, Tracklet::tx, Tracklet::ty, Tracklet::x0, Tracklet::y0, and z_plane.
void KalmanDSTrk::resolveLeftRight (KalmanTrack & kmtrk)
Definition at line 2337 of file KalmanDSTrk.cxx.
References fitTrack(), KalmanTrack::getHitIndexList(), KalmanTrack::getNodeList(), GeomSvc::getPlaneResolution(), GeomSvc::getUinStereoPlane(), and p_geomSvc.
void KalmanDSTrk::resolveSingleLeftRight (Tracklet & tracklet)
Definition at line 1253 of file KalmanDSTrk.cxx.
References costheta_plane, fitTracklet(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::hits, LogInfo, Tracklet::print(), sintheta_plane, and z_plane.
Referenced by buildGlobalTracks(), and removeBadHits().
void KalmanDSTrk::set_pattern_db_name (const std::string & patternDbName) inline
Definition at line 136 of file KalmanDSTrk.h.
References _pattern_db_name.
void KalmanDSTrk::set_sim_db_name (const std::string & simDbName) inline
Definition at line 144 of file KalmanDSTrk.h.
References _sim_db_name.
int KalmanDSTrk::setRawEvent (SRawEvent * event_input)
Definition at line 445 of file KalmanDSTrk.cxx.
References _ana_mode, _event, _tana_Event, _timers, setRawEventWorker(), stracks, and trackletsInSt.
void KalmanDSTrk::setRawEventDebug (SRawEvent * event_input)
Definition at line 438 of file KalmanDSTrk.cxx.
References SRawEvent::getAllHits(), hitAll, and rawEvent.
int KalmanDSTrk::setRawEventWorker (SRawEvent * event_input)
Definition at line 482 of file KalmanDSTrk.cxx.
References _enable_KF, _timers, acceptEvent(), buildBackPartialTracks(), buildGlobalTracks(), buildPropSegments(), buildTrackletsInStation(), detectorIDs_maskX, detectorIDs_maskY, detectorIDs_muid, detectorIDs_muidHodoAid, SRawEvent::getAllHits(), SRawEvent::getHitsIndexInDetector(), SRawEvent::getHitsIndexInDetectors(), hitAll, hitIDs_mask, hitIDs_muid, hitIDs_muidHodoAid, SRawEvent::isFPGATriggered(), LogInfo, JobOptsSvc::m_mcMode, p_jobOptsSvc, processOneTracklet(), propSegs, rawEvent, stracks, TFEXIT_FAIL_BACKPARTIAL, TFEXIT_FAIL_GLOABL, TFEXIT_FAIL_MULTIPLICITY, TFEXIT_FAIL_ST2_TRACKLET, TFEXIT_FAIL_ST3_TRACKLET, TFEXIT_SUCCESS, trackletsInSt, and verbosity.
Referenced by setRawEvent().
void KalmanDSTrk::Verbosity (const int a) inline
Definition at line 59 of file KalmanDSTrk.h.
References verbosity.
int KalmanDSTrk::Verbosity () const inline
Definition at line 60 of file KalmanDSTrk.h.
References verbosity.
Referenced by acceptEvent(), buildBackPartialTracks(), buildGlobalTracks(), and buildTrackletsInStation().
Member Data Documentation
bool KalmanDSTrk::_ana_mode private
Analysis mode.
Definition at line 282 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), buildTrackletsInStation(), KalmanDSTrk(), setRawEvent(), and ~KalmanDSTrk().
int KalmanDSTrk::_DS_level private
Definition at line 243 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), buildTrackletsInStation(), and KalmanDSTrk().
const bool KalmanDSTrk::_enable_KF private
Definition at line 240 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk(), setRawEventWorker(), and ~KalmanDSTrk().
int KalmanDSTrk::_event private
Definition at line 292 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk(), printTimers(), and setRawEvent().
TFile* KalmanDSTrk::_fana private
Definition at line 283 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk(), and ~KalmanDSTrk().
PatternDB* KalmanDSTrk::_pattern_db private
Definition at line 277 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), buildTrackletsInStation(), and KalmanDSTrk().
std::string KalmanDSTrk::_pattern_db_name private
Definition at line 245 of file KalmanDSTrk.h.
Referenced by get_pattern_db_name(), KalmanDSTrk(), and set_pattern_db_name().
std::string KalmanDSTrk::_sim_db_name private
Definition at line 244 of file KalmanDSTrk.h.
Referenced by get_sim_db_name(), KalmanDSTrk(), and set_sim_db_name().
TNtuple* KalmanDSTrk::_tana_Event private
Definition at line 284 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk(), setRawEvent(), and ~KalmanDSTrk().
TNtuple* KalmanDSTrk::_tana_St1 private
Definition at line 285 of file KalmanDSTrk.h.
Referenced by buildTrackletsInStation(), KalmanDSTrk(), and ~KalmanDSTrk().
TNtuple* KalmanDSTrk::_tana_St123 private
Definition at line 289 of file KalmanDSTrk.h.
Referenced by buildGlobalTracks(), KalmanDSTrk(), and ~KalmanDSTrk().
TNtuple* KalmanDSTrk::_tana_St2 private
Definition at line 286 of file KalmanDSTrk.h.
Referenced by buildTrackletsInStation(), KalmanDSTrk(), and ~KalmanDSTrk().
TNtuple* KalmanDSTrk::_tana_St23 private
Definition at line 288 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), KalmanDSTrk(), and ~KalmanDSTrk().
TNtuple* KalmanDSTrk::_tana_St3 private
Definition at line 287 of file KalmanDSTrk.h.
Referenced by buildTrackletsInStation(), KalmanDSTrk(), and ~KalmanDSTrk().
std::map< std::string, PHTimer* > KalmanDSTrk::_timers private
Definition at line 279 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), buildTrackletsInStation(), KalmanDSTrk(), printTimers(), setRawEvent(), and setRawEventWorker().
double KalmanDSTrk::costheta_plane[nChamberPlanes+1] private
Definition at line 204 of file KalmanDSTrk.h.
Referenced by getExtrapoWindowsInSt1(), KalmanDSTrk(), resolveLeftRight(), and resolveSingleLeftRight().
std::vector<int> KalmanDSTrk::detectorIDs_mask[4] private
Configurations of tracklet finding.
Definition at line 169 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk().
std::vector<int> KalmanDSTrk::detectorIDs_maskX[4] private
Definition at line 170 of file KalmanDSTrk.h.
Referenced by acceptEvent(), KalmanDSTrk(), and setRawEventWorker().
std::vector<int> KalmanDSTrk::detectorIDs_maskY[4] private
Definition at line 171 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk(), and setRawEventWorker().
int KalmanDSTrk::detectorIDs_muid[2][4] private
Definition at line 179 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), KalmanDSTrk(), muonID_search(), and setRawEventWorker().
std::vector<int> KalmanDSTrk::detectorIDs_muidHodoAid[2] private
Definition at line 173 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk(), and setRawEventWorker().
ROOT::Math::Functor KalmanDSTrk::fcn private
Definition at line 228 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk().
std::vector<Hit> KalmanDSTrk::hitAll private
Definition at line 154 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), buildPropSegments(), buildTrackletsInStation(), hodoMask(), muonID_hodoAid(), muonID_search(), resolveLeftRight(), setRawEventDebug(), and setRawEventWorker().
std::list<int> KalmanDSTrk::hitIDs_mask[4] private
Definition at line 172 of file KalmanDSTrk.h.
Referenced by hodoMask(), and setRawEventWorker().
std::list<int> KalmanDSTrk::hitIDs_muid[2][4] private
Definition at line 181 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), muonID_search(), and setRawEventWorker().
std::list<int> KalmanDSTrk::hitIDs_muidHodoAid[2] private
Definition at line 182 of file KalmanDSTrk.h.
Referenced by muonID_hodoAid(), and setRawEventWorker().
double KalmanDSTrk::intersection_max[nChamberPlanes+1] private
Definition at line 212 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk(), and resolveLeftRight().
KalmanFitter* KalmanDSTrk::kmfitter private
Definition at line 231 of file KalmanDSTrk.h.
Referenced by fitTrack(), KalmanDSTrk(), and ~KalmanDSTrk().
ROOT::Math::Minimizer* KalmanDSTrk::minimizer[2] private
Definition at line 227 of file KalmanDSTrk.h.
Referenced by fitTracklet(), KalmanDSTrk(), and ~KalmanDSTrk().
GeomSvc* KalmanDSTrk::p_geomSvc private
Definition at line 234 of file KalmanDSTrk.h.
Referenced by acceptTracklet(), buildBackPartialTracks(), getExtrapoWindowsInSt1(), getSagittaWindowsInSt1(), KalmanDSTrk(), muonID_search(), printAtDetectorBack(), processOneTracklet(), removeBadHits(), and resolveLeftRight().
JobOptsSvc* KalmanDSTrk::p_jobOptsSvc private
Definition at line 237 of file KalmanDSTrk.h.
Referenced by buildGlobalTracks(), fitTracklet(), KalmanDSTrk(), and setRawEventWorker().
std::list<PropSegment> KalmanDSTrk::propSegs[2] private
Definition at line 165 of file KalmanDSTrk.h.
Referenced by buildPropSegments(), getPropSegments(), muonID_comp(), and setRawEventWorker().
SRawEvent* KalmanDSTrk::rawEvent private
Definition at line 153 of file KalmanDSTrk.h.
Referenced by buildPropSegments(), buildTrackletsInStation(), setRawEventDebug(), and setRawEventWorker().
double KalmanDSTrk::resol_plane[nChamberPlanes+1] private
Definition at line 215 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk(), and removeBadHits().
int KalmanDSTrk::s_detectorID[3] private
Definition at line 221 of file KalmanDSTrk.h.
Referenced by getSagittaWindowsInSt1(), and KalmanDSTrk().
double KalmanDSTrk::sintheta_plane[nChamberPlanes+1] private
Definition at line 205 of file KalmanDSTrk.h.
Referenced by getExtrapoWindowsInSt1(), KalmanDSTrk(), resolveLeftRight(), and resolveSingleLeftRight().
double KalmanDSTrk::slope_max[nChamberPlanes+1] private
Definition at line 211 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk(), and resolveLeftRight().
double KalmanDSTrk::spacing_plane[nChamberPlanes+1] private
Definition at line 218 of file KalmanDSTrk.h.
Referenced by buildTrackletsInStation(), and KalmanDSTrk().
std::vector<int> KalmanDSTrk::stationIDs_mask[nStations] private
Definition at line 176 of file KalmanDSTrk.h.
Referenced by hodoMask(), and KalmanDSTrk().
std::list<SRecTrack> KalmanDSTrk::stracks private
Definition at line 161 of file KalmanDSTrk.h.
Referenced by getSRecTracks(), setRawEvent(), and setRawEventWorker().
std::vector<int> KalmanDSTrk::superIDs[nChamberPlanes/6+2] private
For following part, id = 0, 1, 2, 3, 4, 5, 6 stand for station 0, 1, 2, 3+, 3-, and prop tubes X-Z and Y-Z.
Definition at line 193 of file KalmanDSTrk.h.
Referenced by buildPropSegments(), buildTrackletsInStation(), and KalmanDSTrk().
Tracklet KalmanDSTrk::tracklet_curr private
Definition at line 224 of file KalmanDSTrk.h.
Referenced by fitTracklet(), and KalmanDSTrk().
std::list<Tracklet> KalmanDSTrk::trackletsInSt[5] private
Definition at line 158 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), buildTrackletsInStation(), getBackPartials(), getFinalTracklets(), getTrackletList(), printAtDetectorBack(), setRawEvent(), and setRawEventWorker().
double KalmanDSTrk::u_costheta[nChamberPlanes/6] private
Definition at line 197 of file KalmanDSTrk.h.
Referenced by buildTrackletsInStation(), and KalmanDSTrk().
double KalmanDSTrk::u_sintheta[nChamberPlanes/6] private
Definition at line 198 of file KalmanDSTrk.h.
Referenced by buildTrackletsInStation(), and KalmanDSTrk().
double KalmanDSTrk::u_win[nChamberPlanes/6] private
Definition at line 196 of file KalmanDSTrk.h.
Referenced by buildTrackletsInStation(), and KalmanDSTrk().
int KalmanDSTrk::verbosity private
Definition at line 150 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), setRawEventWorker(), and Verbosity().
double KalmanDSTrk::x_mask_max[nHodoPlanes+nPropPlanes][72] private
Definition at line 187 of file KalmanDSTrk.h.
Referenced by hodoMask(), KalmanDSTrk(), and muonID_hodoAid().
double KalmanDSTrk::x_mask_min[nHodoPlanes+nPropPlanes][72] private
Definition at line 186 of file KalmanDSTrk.h.
Referenced by hodoMask(), KalmanDSTrk(), and muonID_hodoAid().
double KalmanDSTrk::y_mask_max[nHodoPlanes+nPropPlanes][72] private
Definition at line 189 of file KalmanDSTrk.h.
Referenced by hodoMask(), KalmanDSTrk(), and muonID_hodoAid().
double KalmanDSTrk::y_mask_min[nHodoPlanes+nPropPlanes][72] private
Definition at line 188 of file KalmanDSTrk.h.
Referenced by hodoMask(), KalmanDSTrk(), and muonID_hodoAid().
double KalmanDSTrk::z_mask[nHodoPlanes+nPropPlanes] private
Definition at line 185 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), hodoMask(), KalmanDSTrk(), muonID_hodoAid(), and muonID_search().
double KalmanDSTrk::z_plane[nChamberPlanes+1] private
Definition at line 208 of file KalmanDSTrk.h.
Referenced by buildBackPartialTracks(), buildTrackletsInStation(), getExtrapoWindowsInSt1(), getSagittaWindowsInSt1(), KalmanDSTrk(), resolveLeftRight(), and resolveSingleLeftRight().
double KalmanDSTrk::z_plane_u[nChamberPlanes/6] private
Definition at line 200 of file KalmanDSTrk.h.
Referenced by buildTrackletsInStation(), and KalmanDSTrk().
double KalmanDSTrk::z_plane_v[nChamberPlanes/6] private
Definition at line 201 of file KalmanDSTrk.h.
Referenced by buildTrackletsInStation(), and KalmanDSTrk().
double KalmanDSTrk::z_plane_x[nChamberPlanes/6] private
Definition at line 199 of file KalmanDSTrk.h.
Referenced by buildTrackletsInStation(), and KalmanDSTrk().
double KalmanDSTrk::z_ref_muid[2][4] private
Definition at line 180 of file KalmanDSTrk.h.
Referenced by KalmanDSTrk(), and muonID_search().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/patterndb/KalmanDSTrk.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/patterndb/KalmanDSTrk.cxx