Class Reference for E1039 Core & Analysis Software: AnaTriggerHit Class Reference
AnaTriggerHit Class Reference
A simple SubsysReco module to analyze the trigger (i.e. V1495 TDC) hit.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaRealDst/src/AnaTriggerHit.h>
Public Member Functions
AnaTriggerHit (const std::string &name="AnaTriggerHit")
virtual ~AnaTriggerHit ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void UseInTime (const bool val)
int UseInTime () const
void SetLevel (const int level)
int GetLevel () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
A simple SubsysReco module to analyze the trigger (i.e. V1495 TDC) hit.
It outputs small numbers of trees and histograms. You can modify either/both of them as you need.
Definition at line 16 of file AnaTriggerHit.h.
Constructor & Destructor Documentation
AnaTriggerHit()
AnaTriggerHit::AnaTriggerHit (const std::string & name = "AnaTriggerHit")
Definition at line 24 of file AnaTriggerHit.cc.
~AnaTriggerHit()
virtual AnaTriggerHit::~AnaTriggerHit () inline virtual
Definition at line 37 of file AnaTriggerHit.h.
Member Function Documentation
End()
int AnaTriggerHit::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 135 of file AnaTriggerHit.cc.
References Fun4AllReturnCodes::EVENT_OK.
GetLevel()
int AnaTriggerHit::GetLevel () const inline
Definition at line 46 of file AnaTriggerHit.h.
Init()
int AnaTriggerHit::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 34 of file AnaTriggerHit.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRun()
int AnaTriggerHit::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Input
Output
Reimplemented from SubsysReco.
Definition at line 39 of file AnaTriggerHit.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, GeomSvc::getDetectorID(), GeomSvc::getPlaneNElements(), and GeomSvc::instance().
process_event()
int AnaTriggerHit::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Event selection
Get & fill the hit info
Reimplemented from SubsysReco.
Definition at line 99 of file AnaTriggerHit.cc.
References Fun4AllReturnCodes::EVENT_OK, and UtilSQHit::FindHits().
SetLevel()
void AnaTriggerHit::SetLevel (const int level) inline
Definition at line 45 of file AnaTriggerHit.h.
UseInTime() [1/2]
int AnaTriggerHit::UseInTime () const inline
Definition at line 44 of file AnaTriggerHit.h.
UseInTime() [2/2]
void AnaTriggerHit::UseInTime (const bool val) inline
Definition at line 43 of file AnaTriggerHit.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaRealDst/src/AnaTriggerHit.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaRealDst/src/AnaTriggerHit.cc