Class Reference for E1039 Core & Analysis Software: CalibDriftDist Class Reference
CalibDriftDist Class Reference
SubsysReco module to calibrate the drift distance and also the in-time window of the chambers and the prop tube.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/calibrator/CalibDriftDist.h>
Public Member Functions
CalibDriftDist (const std::string &name="CalibDriftDist")
virtual ~CalibDriftDist ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void ReadParamFromFile (const char *fn_xt_curve)
CalibParamXT * GetParamXT ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
SubsysReco module to calibrate the drift distance and also the in-time window of the chambers and the prop tube.
This module automatically selects a proper set of calibration parameters based on the run number. Only when necessary, you can manually give a parameter set via ReadParamFromFile().
Definition at line 12 of file CalibDriftDist.h.
Constructor & Destructor Documentation
CalibDriftDist::CalibDriftDist (const std::string & name = "CalibDriftDist")
Definition at line 16 of file CalibDriftDist.cc.
CalibDriftDist::~CalibDriftDist () virtual
Definition at line 26 of file CalibDriftDist.cc.
Member Function Documentation
int CalibDriftDist::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 97 of file CalibDriftDist.cc.
References Fun4AllReturnCodes::EVENT_OK.
CalibParamXT* CalibDriftDist::GetParamXT () inline
Definition at line 27 of file CalibDriftDist.h.
int CalibDriftDist::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 31 of file CalibDriftDist.cc.
References Fun4AllReturnCodes::EVENT_OK, RunParamBase::ReadFromLocalFile(), and RunParamBase::SetMapID().
int CalibDriftDist::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 41 of file CalibDriftDist.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, PHFlag::get_IntFlag(), RunParamBase::GetMapID(), RunParamBase::GetParamID(), recoConsts::instance(), Fun4AllBase::Name(), RunParamBase::ReadFromDB(), recoConsts::set_CharFlag(), SQParamDeco::set_variable(), RunParamBase::SetMapIDbyDB(), and Fun4AllBase::Verbosity().
int CalibDriftDist::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
No field for resolution in SQHit now.
Reimplemented from SubsysReco.
Definition at line 70 of file CalibDriftDist.cc.
References SQHitVector::begin(), SQHitVector::end(), Fun4AllReturnCodes::EVENT_OK, SQHit::get_detector_id(), SQHit::get_element_id(), SQHit::get_tdc_time(), GeomSvc::getMeasurement(), CalibParamXT::GetParam(), GeomSvc::instance(), GeomSvc::isChamber(), GeomSvc::isPropTube(), SQHit::set_drift_distance(), SQHit::set_in_time(), SQHit::set_pos(), CalibParamXT::Set::T1, and CalibParamXT::Set::t2x.
void CalibDriftDist::ReadParamFromFile (const char * fn_xt_curve)
Definition at line 102 of file CalibDriftDist.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/calibrator/CalibDriftDist.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/calibrator/CalibDriftDist.cc