Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/kTThreads/macros/RecoData.C File Reference
RecoData.C File Reference
Functions
int RecoData (const int run_id, TString infile="input.root", TString outfile="output.root")
ROOT macro to run the online reconstruction.
Function Documentation
int RecoData (const int run_id, TString infile = "input.root", TString outfile = "output.root")
ROOT macro to run the online reconstruction.
Based on RunScheduler.C.
Definition at line 9 of file RecoData.C.
References FMAGSTR, recoConsts::init(), KScheduler::Init(), recoConsts::instance(), KMAGSTR, submit_bnl::outfile, recoConsts::Print(), KScheduler::runThreads(), PHFlag::set_BoolFlag(), recoConsts::set_CharFlag(), PHFlag::set_DoubleFlag(), PHFlag::set_IntFlag(), and KScheduler::UseTrackletReco().