E1039 Software: SQSpill_v1 Class Reference
SQSpill_v1 Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/interface_main/SQSpill_v1.h>
Public Member Functions
SQSpill_v1 ()
virtual ~SQSpill_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQSpill * Clone () const
virtual int get_run_id () const
virtual void set_run_id (const int a)
virtual int get_spill_id () const
virtual void set_spill_id (const int a)
virtual short get_target_pos () const
virtual void set_target_pos (const short a)
Public Member Functions inherited from SQSpill
virtual ~SQSpill ()
virtual int get_bos_coda_id () const
virtual void set_bos_coda_id (const int a)
virtual int get_bos_vme_time () const
virtual void set_bos_vme_time (const int a)
virtual int get_eos_coda_id () const
virtual void set_eos_coda_id (const int a)
virtual int get_eos_vme_time () const
virtual void set_eos_vme_time (const int a)
virtual SQStringMap * get_bos_scaler_list ()
virtual SQStringMap * get_eos_scaler_list ()
virtual SQStringMap * get_slow_cont_list ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Private Member Functions
ClassDef (SQSpill_v1, 1)
Private Attributes
int _run_id
int _spill_id
short _target_pos
Additional Inherited Members
Protected Member Functions inherited from SQSpill
SQSpill ()
Detailed Description
Definition at line 17 of file SQSpill_v1.h.
Constructor & Destructor Documentation
SQSpill_v1()
SQSpill_v1::SQSpill_v1 ()
Definition at line 18 of file SQSpill_v1.cxx.
Referenced by Clone(), and Reset().
~SQSpill_v1()
virtual SQSpill_v1::~SQSpill_v1 () inline virtual
Definition at line 22 of file SQSpill_v1.h.
References identify().
Member Function Documentation
ClassDef()
SQSpill_v1::ClassDef (SQSpill_v1 , 1) private
Clone()
SQSpill* SQSpill_v1::Clone () const inline virtual
Reimplemented from SQSpill.
Definition at line 29 of file SQSpill_v1.h.
References SQSpill_v1().
get_run_id()
virtual int SQSpill_v1::get_run_id () const inline virtual
Reimplemented from SQSpill.
Definition at line 31 of file SQSpill_v1.h.
References _run_id.
Referenced by identify().
get_spill_id()
virtual int SQSpill_v1::get_spill_id () const inline virtual
Reimplemented from SQSpill.
Definition at line 34 of file SQSpill_v1.h.
References _spill_id.
Referenced by identify().
get_target_pos()
virtual short SQSpill_v1::get_target_pos () const inline virtual
Reimplemented from SQSpill.
Definition at line 37 of file SQSpill_v1.h.
References _target_pos.
Referenced by identify().
identify()
void SQSpill_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQSpill.
Definition at line 24 of file SQSpill_v1.cxx.
References get_run_id(), get_spill_id(), and get_target_pos().
Referenced by ~SQSpill_v1().
isValid()
int SQSpill_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQSpill.
Definition at line 34 of file SQSpill_v1.cxx.
References _run_id, _spill_id, and _target_pos.
Referenced by Reset().
Reset()
void SQSpill_v1::Reset () inline virtual
Clear Event.
Reimplemented from SQSpill.
Definition at line 27 of file SQSpill_v1.h.
References isValid(), and SQSpill_v1().
set_run_id()
virtual void SQSpill_v1::set_run_id (const int a) inline virtual
Reimplemented from SQSpill.
Definition at line 32 of file SQSpill_v1.h.
References _run_id.
set_spill_id()
virtual void SQSpill_v1::set_spill_id (const int a) inline virtual
Reimplemented from SQSpill.
Definition at line 35 of file SQSpill_v1.h.
References _spill_id.
set_target_pos()
virtual void SQSpill_v1::set_target_pos (const short a) inline virtual
Reimplemented from SQSpill.
Definition at line 38 of file SQSpill_v1.h.
References _target_pos.
Member Data Documentation
_run_id
int SQSpill_v1::_run_id private
Definition at line 43 of file SQSpill_v1.h.
Referenced by get_run_id(), isValid(), and set_run_id().
_spill_id
int SQSpill_v1::_spill_id private
Definition at line 44 of file SQSpill_v1.h.
Referenced by get_spill_id(), isValid(), and set_spill_id().
_target_pos
short SQSpill_v1::_target_pos private
Definition at line 45 of file SQSpill_v1.h.
Referenced by get_target_pos(), isValid(), and set_target_pos().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/interface_main/SQSpill_v1.h
/home/yuhw/GitHub/SeaQuest/e1039-core/interface_main/SQSpill_v1.cxx