Class Reference for E1039 Core & Analysis Software: PHFieldConfig_v1 Class Reference
PHFieldConfig_v1 Class Reference
PHFieldConfig_v1 implements field configuration information for input a field map file.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig_v1.h>
Public Member Functions
PHFieldConfig_v1 (FieldConfigTypes field_config, const std::string &filename, double magfield_rescale=1.)
PHFieldConfig_v1 ()
default constructor for ROOT file IO
virtual ~PHFieldConfig_v1 ()
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
FieldConfigTypes get_field_config () const
void set_field_config (FieldConfigTypes fieldConfig)
const std::string & get_filename () const
void set_filename (const std::string &filename)
double get_magfield_rescale () const
void set_magfield_rescale (double magfieldRescale)
Public Member Functions inherited from PHFieldConfig
virtual ~PHFieldConfig ()
std::string get_field_config_description () const
virtual double get_field_mag_x () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_x (double fieldMagX)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_y () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_y (double fieldMagY)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_z () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_z (double fieldMagZ)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual const std::string & get_filename1 () const
field value in Tesla for target field model ONLY for PHFieldConfig_v3
virtual const std::string & get_filename2 () const
virtual double get_magfield_rescale1 () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
virtual double get_magfield_rescale2 () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
virtual void set_taregetmag_y (double fieldMagX)
field value in Tesla for target field model ONLY for PHFieldConfig_v3
virtual double get_taregetmag_y () const
field value in Tesla for target field model ONLY for PHFieldConfig_v3
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
FieldConfigTypes field_config_
std::string filename_
double magfield_rescale_
Additional Inherited Members
Public Types inherited from PHFieldConfig
enum FieldConfigTypes {
kFieldUniform = 0 , kField2D = 2 , kField3DCylindrical = 3 , kField3DCartesian = 1 ,
RegionalConst = 4 , kFieldSeaQuest = 5 , kFieldInvalid = 9999
}
Protected Member Functions inherited from PHFieldConfig
PHFieldConfig ()
pure virtual interface class. not for direct use
Static Protected Attributes inherited from PHFieldConfig
static const std::string kInvalid_FileName
Detailed Description
PHFieldConfig_v1 implements field configuration information for input a field map file.
Definition at line 19 of file PHFieldConfig_v1.h.
Constructor & Destructor Documentation
PHFieldConfig_v1() [1/2]
PHFieldConfig_v1::PHFieldConfig_v1 (FieldConfigTypes field_config, const std::string & filename, double magfield_rescale = 1.)
Definition at line 23 of file PHFieldConfig_v1.cc.
PHFieldConfig_v1() [2/2]
PHFieldConfig_v1::PHFieldConfig_v1 () inline
default constructor for ROOT file IO
Definition at line 29 of file PHFieldConfig_v1.h.
References PHFieldConfig::kFieldInvalid, and PHFieldConfig_v1().
Referenced by clone(), and PHFieldConfig_v1().
~PHFieldConfig_v1()
PHFieldConfig_v1::~PHFieldConfig_v1 () virtual
Definition at line 32 of file PHFieldConfig_v1.cc.
Member Function Documentation
clone()
PHObject * PHFieldConfig_v1::clone () const virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 38 of file PHFieldConfig_v1.cc.
References PHFieldConfig_v1().
get_field_config()
FieldConfigTypes PHFieldConfig_v1::get_field_config () const inline virtual
Reimplemented from PHFieldConfig.
Definition at line 51 of file PHFieldConfig_v1.h.
References field_config_.
Referenced by identify().
get_filename()
const std::string& PHFieldConfig_v1::get_filename () const inline virtual
Reimplemented from PHFieldConfig.
Definition at line 60 of file PHFieldConfig_v1.h.
References filename_.
Referenced by identify().
get_magfield_rescale()
double PHFieldConfig_v1::get_magfield_rescale () const inline virtual
Reimplemented from PHFieldConfig.
Definition at line 70 of file PHFieldConfig_v1.h.
References magfield_rescale_.
Referenced by identify().
identify()
void PHFieldConfig_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHFieldConfig.
Definition at line 46 of file PHFieldConfig_v1.cc.
References get_field_config(), PHFieldConfig::get_field_config_description(), get_filename(), get_magfield_rescale(), and isValid().
isValid()
int PHFieldConfig_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHFieldConfig.
Definition at line 66 of file PHFieldConfig_v1.cc.
References filename_.
Referenced by identify().
Reset()
void PHFieldConfig_v1::Reset () virtual
Clear Event.
Reimplemented from PHFieldConfig.
Definition at line 61 of file PHFieldConfig_v1.cc.
set_field_config()
void PHFieldConfig_v1::set_field_config (FieldConfigTypes fieldConfig) inline virtual
Reimplemented from PHFieldConfig.
Definition at line 55 of file PHFieldConfig_v1.h.
References field_config_.
set_filename()
void PHFieldConfig_v1::set_filename (const std::string & filename) inline virtual
Reimplemented from PHFieldConfig.
Definition at line 65 of file PHFieldConfig_v1.h.
References filename_.
set_magfield_rescale()
void PHFieldConfig_v1::set_magfield_rescale (double magfieldRescale) inline virtual
Reimplemented from PHFieldConfig.
Definition at line 75 of file PHFieldConfig_v1.h.
References magfield_rescale_.
Member Data Documentation
field_config_
FieldConfigTypes PHFieldConfig_v1::field_config_ protected
Definition at line 81 of file PHFieldConfig_v1.h.
Referenced by get_field_config(), and set_field_config().
filename_
std::string PHFieldConfig_v1::filename_ protected
Definition at line 82 of file PHFieldConfig_v1.h.
Referenced by get_filename(), isValid(), and set_filename().
magfield_rescale_
double PHFieldConfig_v1::magfield_rescale_ protected
Definition at line 83 of file PHFieldConfig_v1.h.
Referenced by get_magfield_rescale(), and set_magfield_rescale().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig_v1.cc