Class Reference for E1039 Core & Analysis Software: SRMakeRTCurve Class Reference
SRMakeRTCurve Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/SRMakeRTCurve.h>
Public Member Functions
SRMakeRTCurve (const int iter, const std::string &name="SRMakeRTCurve")
virtual ~SRMakeRTCurve ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int AnaForOneStation (TrackletVector *trklet_vec, const int st_id, const int n_trklet)
void GetGoodTrackletRange (const int st_id, double &x_lo, double &x_hi, double &y_lo, double &y_hi, double &tx_lo, double &tx_hi, double &ty_lo, double &ty_hi)
bool InAcceptance (const Tracklet *trk)
int FindBestTracklet (TrackletVector *trklet_vec, const int st_id_tgt)
void DrawHistEvent ()
void DrawHistHit ()
void ExtractRT ()
void WriteRT ()
void DrawCalibResult ()
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 13 of file SRMakeRTCurve.h.
Constructor & Destructor Documentation
SRMakeRTCurve::SRMakeRTCurve (const int iter, const std::string & name = "SRMakeRTCurve")
Definition at line 28 of file SRMakeRTCurve.cc.
virtual SRMakeRTCurve::~SRMakeRTCurve () inline virtual
Definition at line 39 of file SRMakeRTCurve.h.
Member Function Documentation
int SRMakeRTCurve::AnaForOneStation (TrackletVector * trklet_vec, const int st_id, const int n_trklet) protected
Definition at line 116 of file SRMakeRTCurve.cc.
References TrackletVector::at(), CalibData::FillTracklet(), CalibData::FillTrackletHits(), and FindBestTracklet().
Referenced by process_event().
void SRMakeRTCurve::DrawCalibResult () protected
Definition at line 239 of file SRMakeRTCurve.cc.
References c1, CalibParam::GetAnaPlane(), GeomSvc::getDetectorName(), CalibParam::GetGraphT2R(), CalibData::GetHistRT(), CalibParam::GetNumPlanes(), CalibParam::GetRTCurve(), RTCurve::GetRWidth(), RTCurve::GetT2DRGraph(), RTCurve::GetT2RSpline(), and GeomSvc::instance().
Referenced by End().
void SRMakeRTCurve::DrawHistEvent () protected
Definition at line 194 of file SRMakeRTCurve.cc.
References CalibData::DrawHistEvent().
Referenced by End().
void SRMakeRTCurve::DrawHistHit () protected
Definition at line 206 of file SRMakeRTCurve.cc.
References CalibData::DrawHistHit().
Referenced by End().
int SRMakeRTCurve::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 183 of file SRMakeRTCurve.cc.
References DrawCalibResult(), DrawHistEvent(), DrawHistHit(), Fun4AllReturnCodes::EVENT_OK, ExtractRT(), and WriteRT().
void SRMakeRTCurve::ExtractRT () protected
Definition at line 211 of file SRMakeRTCurve.cc.
References FitRTDist::DoFit(), FitRTDist::FixT1T0(), CalibParam::GetAnaPlane(), CalibParam::GetGraphT2R(), CalibData::GetHistRT(), CalibParam::GetNumPlanes(), CalibParam::GetRMax(), CalibParam::GetRTCurve(), CalibParam::GetT0(), CalibParam::GetT1(), CalibParam::TimeWindowIsFixed(), FitRTDist::Verbosity(), and Fun4AllBase::Verbosity().
Referenced by End().
int SRMakeRTCurve::FindBestTracklet (TrackletVector * trklet_vec, const int st_id_tgt) protected
Definition at line 159 of file SRMakeRTCurve.cc.
References TrackletVector::at(), Tracklet::chisq, Tracklet::getNHits(), InAcceptance(), TrackletVector::size(), and Tracklet::stationID.
Referenced by AnaForOneStation().
void SRMakeRTCurve::GetGoodTrackletRange (const int st_id, double & x_lo, double & x_hi, double & y_lo, double & y_hi, double & tx_lo, double & tx_hi, double & ty_lo, double & ty_hi) protected
Definition at line 129 of file SRMakeRTCurve.cc.
Referenced by InAcceptance().
bool SRMakeRTCurve::InAcceptance (const Tracklet * trk) protected
Track in the D3m acceptance, page 15 of doc9856.
Definition at line 142 of file SRMakeRTCurve.cc.
References GetGoodTrackletRange(), Tracklet::stationID, Tracklet::tx, Tracklet::ty, Tracklet::x0, Tracklet::y0, and CalibParam::ZOfStationID().
Referenced by FindBestTracklet().
int SRMakeRTCurve::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 43 of file SRMakeRTCurve.cc.
References Fun4AllReturnCodes::EVENT_OK.
int SRMakeRTCurve::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 48 of file SRMakeRTCurve.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, CalibParam::Init(), CalibData::Init(), CalibParam::ReadRTParam(), and CalibParam::SetAnaPlanes().
int SRMakeRTCurve::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 80 of file SRMakeRTCurve.cc.
References AnaForOneStation(), TrackletVector::at(), Fun4AllReturnCodes::EVENT_OK, CalibData::FillEventInfo(), SQEvent::get_trigger(), SQEvent::NIM2, SQEvent::NIM4, TrackletVector::size(), and Tracklet::stationID.
void SRMakeRTCurve::WriteRT () protected
Definition at line 233 of file SRMakeRTCurve.cc.
References CalibParam::WriteRTGraph(), and CalibParam::WriteRTParam().
Referenced by End().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/SRMakeRTCurve.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/SRMakeRTCurve.cc