E1039 Software: PHField3DCylindrical Class Reference
PHField3DCylindrical Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHField/PHField3DCylindrical.h>
Public Member Functions
PHField3DCylindrical (const std::string &filename, int verb=0, const float magfield_rescale=1.0)
virtual ~PHField3DCylindrical ()
void GetFieldValue (const double Point[4], double *Bfield) const
void GetFieldCyl (const double CylPoint[4], double *Bfield) const
Public Member Functions inherited from PHField
PHField (const int verb=0)
constructor
virtual ~PHField ()
virtual void identify (std::ostream &os=std::cout) const
void Verbosity (const int i)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
std::vector< std::vector< std::vector< float > > > BFieldZ_
std::vector< std::vector< std::vector< float > > > BFieldR_
std::vector< std::vector< std::vector< float > > > BFieldPHI_
std::vector< float > z_map_
std::vector< float > r_map_
std::vector< float > phi_map_
float maxz_
float minz_
Protected Attributes inherited from PHField
unsigned verb_
Private Types
typedef boost::tuple< float, float, float > trio
Private Member Functions
bool bin_search (const std::vector< float > &vec, unsigned start, unsigned end, const float &key, unsigned &index) const
void print_map (std::map< trio, trio >::iterator &it) const
Detailed Description
Definition at line 32 of file PHField3DCylindrical.h.
Member Typedef Documentation
trio
typedef boost::tuple<float, float, float> PHField3DCylindrical::trio private
Definition at line 34 of file PHField3DCylindrical.h.
Constructor & Destructor Documentation
PHField3DCylindrical()
PHField3DCylindrical::PHField3DCylindrical (const std::string & filename, int verb = 0, const float magfield_rescale = 1.0)
Definition at line 13 of file PHField3DCylindrical.cc.
References BFieldPHI_, BFieldR_, BFieldZ_, maxz_, minz_, phi_map_, print_map(), r_map_, PHField::verb_, and z_map_.
~PHField3DCylindrical()
virtual PHField3DCylindrical::~PHField3DCylindrical () inline virtual
Definition at line 38 of file PHField3DCylindrical.h.
References GetFieldCyl(), and GetFieldValue().
Member Function Documentation
bin_search()
bool PHField3DCylindrical::bin_search (const std::vector< float > & vec, unsigned start, unsigned end, const float & key, unsigned & index) const private
Definition at line 397 of file PHField3DCylindrical.cc.
GetFieldCyl()
void PHField3DCylindrical::GetFieldCyl (const double CylPoint[4], double * Bfield) const
Definition at line 265 of file PHField3DCylindrical.cc.
References BFieldPHI_, BFieldR_, BFieldZ_, phi_map_, r_map_, PHField::verb_, and z_map_.
Referenced by GetFieldValue(), and ~PHField3DCylindrical().
GetFieldValue()
void PHField3DCylindrical::GetFieldValue (const double Point[4], double * Bfield) const virtual
access field value Follow the convention of G4ElectroMagneticField
Parameters
[in] Point space time coordinate. x, y, z, t in Geant4/CLHEP units
[out] Bfield field value. In the case of magnetic field, the order is Bx, By, Bz in in Geant4/CLHEP units
Implements PHField.
Definition at line 208 of file PHField3DCylindrical.cc.
References GetFieldCyl(), maxz_, minz_, and PHField::verb_.
Referenced by ~PHField3DCylindrical().
print_map()
void PHField3DCylindrical::print_map (std::map< trio, trio >::iterator & it) const private
Definition at line 423 of file PHField3DCylindrical.cc.
Referenced by PHField3DCylindrical().
Member Data Documentation
BFieldPHI_
std::vector<std::vector<std::vector<float> > > PHField3DCylindrical::BFieldPHI_ protected
Definition at line 46 of file PHField3DCylindrical.h.
Referenced by GetFieldCyl(), and PHField3DCylindrical().
BFieldR_
std::vector<std::vector<std::vector<float> > > PHField3DCylindrical::BFieldR_ protected
Definition at line 45 of file PHField3DCylindrical.h.
Referenced by GetFieldCyl(), and PHField3DCylindrical().
BFieldZ_
std::vector<std::vector<std::vector<float> > > PHField3DCylindrical::BFieldZ_ protected
Definition at line 44 of file PHField3DCylindrical.h.
Referenced by GetFieldCyl(), and PHField3DCylindrical().
maxz_
float PHField3DCylindrical::maxz_ protected
Definition at line 53 of file PHField3DCylindrical.h.
Referenced by GetFieldValue(), and PHField3DCylindrical().
minz_
float PHField3DCylindrical::minz_ protected
Definition at line 53 of file PHField3DCylindrical.h.
Referenced by GetFieldValue(), and PHField3DCylindrical().
phi_map_
std::vector<float> PHField3DCylindrical::phi_map_ protected
Definition at line 51 of file PHField3DCylindrical.h.
Referenced by GetFieldCyl(), and PHField3DCylindrical().
r_map_
std::vector<float> PHField3DCylindrical::r_map_ protected
Definition at line 50 of file PHField3DCylindrical.h.
Referenced by GetFieldCyl(), and PHField3DCylindrical().
z_map_
std::vector<float> PHField3DCylindrical::z_map_ protected
Definition at line 49 of file PHField3DCylindrical.h.
Referenced by GetFieldCyl(), and PHField3DCylindrical().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHField/PHField3DCylindrical.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHField/PHField3DCylindrical.cc