Class Reference for E1039 Core & Analysis Software: PHG4CylinderGeomv2 Class Reference
PHG4CylinderGeomv2 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderGeomv2.h>
Public Member Functions
PHG4CylinderGeomv2 ()
PHG4CylinderGeomv2 (const double r, const double zmi, const double zma, const double thickn, const int n_scint)
virtual ~PHG4CylinderGeomv2 ()
void identify (std::ostream &os=std::cout) const
void set_nscint (const int i)
int get_nscint () const
virtual void ImportParameters (const PHParameters &param)
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHG4CylinderGeomv1
PHG4CylinderGeomv1 ()
PHG4CylinderGeomv1 (const double r, const double zmi, const double zma, const double thickn)
virtual ~PHG4CylinderGeomv1 ()
int get_layer () const
double get_radius () const
double get_thickness () const
double get_zmin () const
double get_zmax () const
void set_layer (const int i)
void set_radius (const double r)
void set_thickness (const double t)
void set_zmin (const double z)
void set_zmax (const double z)
Public Member Functions inherited from PHG4CylinderGeom
virtual ~PHG4CylinderGeom ()
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_tiltangle (const double i)
virtual void set_phi_slat_zero (const double phi)
virtual void find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[])
virtual void find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[])
virtual double get_strip_y_spacing () const
virtual double get_strip_z_spacing () const
virtual double get_strip_tilt () const
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
int nscint
Protected Attributes inherited from PHG4CylinderGeomv1
int layer
double radius
double zmin
double zmax
double thickness
Additional Inherited Members
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Detailed Description
Definition at line 6 of file PHG4CylinderGeomv2.h.
Constructor & Destructor Documentation
PHG4CylinderGeomv2::PHG4CylinderGeomv2 ()
Definition at line 7 of file PHG4CylinderGeomv2.cc.
PHG4CylinderGeomv2::PHG4CylinderGeomv2 (const double r, const double zmi, const double zma, const double thickn, const int n_scint) inline
Definition at line 10 of file PHG4CylinderGeomv2.h.
virtual PHG4CylinderGeomv2::~PHG4CylinderGeomv2 () inline virtual
Definition at line 15 of file PHG4CylinderGeomv2.h.
Member Function Documentation
int PHG4CylinderGeomv2::get_nscint () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 19 of file PHG4CylinderGeomv2.h.
References nscint.
void PHG4CylinderGeomv2::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderGeomv1.
Reimplemented in PHG4CylinderGeomv3.
Definition at line 14 of file PHG4CylinderGeomv2.cc.
References PHG4CylinderGeomv1::layer, nscint, PHG4CylinderGeomv1::radius, PHG4CylinderGeomv1::thickness, PHG4CylinderGeomv1::zmax, and PHG4CylinderGeomv1::zmin.
void PHG4CylinderGeomv2::ImportParameters (const PHParameters & param) virtual
load parameters from PHParameters, which interface to Database/XML/ROOT files
Reimplemented from PHG4CylinderGeomv1.
Definition at line 27 of file PHG4CylinderGeomv2.cc.
References PHParameters::exist_int_param(), PHParameters::get_int_param(), PHG4CylinderGeomv1::ImportParameters(), and nscint.
void PHG4CylinderGeomv2::set_nscint (const int i) inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 18 of file PHG4CylinderGeomv2.h.
References nscint.
Member Data Documentation
int PHG4CylinderGeomv2::nscint protected
Definition at line 25 of file PHG4CylinderGeomv2.h.
Referenced by get_nscint(), identify(), PHG4CylinderGeomv3::identify(), ImportParameters(), and set_nscint().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderGeomv2.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderGeomv2.cc