Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/macros/TestOnlMon4MainDaq.C File Reference
TestOnlMon4MainDaq.C File Reference
Functions
int TestOnlMon4MainDaq ()
TestOnlMon4MainDaq.C.
void ConfigServer ()
int OnlMon4MainDaq ()
int Fun4MainDaq (const int run=1818, const int nevent=0)
Function Documentation
void ConfigServer ()
Definition at line 12 of file TestOnlMon4MainDaq.C.
References OnlMonServer::SetNumPorts(), OnlMonServer::SetPort(), and OnlMonServer::SetPort0().
Referenced by Fun4MainDaq(), and OnlMon4MainDaq().
int Fun4MainDaq (const int run = 1818, const int nevent = 0)
Definition at line 41 of file TestOnlMon4MainDaq.C.
References ConfigServer(), OnlMonServer::End(), Fun4AllInputManager::fileopen(), OnlMonServer::instance(), OnlMonComm::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), UtilOnline::RunNum2DstFile(), se, OnlMonComm::SetMaxNumSelSpills(), OnlMonServer::SetOnline(), OnlMonServer::StartServer(), and UtilOnline::UseOutputLocationForDevel().
int OnlMon4MainDaq ()
Definition at line 19 of file TestOnlMon4MainDaq.C.
References ConfigServer(), and OnlMonUI::Run().
int TestOnlMon4MainDaq ()
TestOnlMon4MainDaq.C.
Definition at line 7 of file TestOnlMon4MainDaq.C.