Class Reference for E1039 Core & Analysis Software: PHG4CellDefs Namespace Reference
PHG4CellDefs Namespace Reference
Namespaces
EtaPhiBinning
EtaXsizeBinning
MapsBinning
ScintillatorSlatBinning
SizeBinning
SpacalBinning
TPCBinning
Typedefs
typedef unsigned long long keytype
Enumerations
enum CellBinning {
undefined = 0 , sizebinning = 1 , etaphibinning = 2 , etaslatbinning = 3 ,
spacalbinning = 4 , scintillatorslatbinning = 5 , etaxsizebinning = 6 , mapsbinning = 7 ,
tpcbinning = 8
}
Functions
static unsigned int bitshift_layer __attribute__ ((unused)) = bitshift_layer - 16
bool has_binning (PHG4CellDefs::keytype key, PHG4CellDefs::CellBinning binning)
short get_binning (PHG4CellDefs::keytype key)
short int get_detid (const PHG4CellDefs::keytype key)
Typedef Documentation
keytype
typedef unsigned long long PHG4CellDefs::keytype
Definition at line 7 of file PHG4CellDefs.h.
Enumeration Type Documentation
CellBinning
enum PHG4CellDefs::CellBinning
Enumerator
undefined
sizebinning
etaphibinning
etaslatbinning
spacalbinning
scintillatorslatbinning
etaxsizebinning
mapsbinning
tpcbinning
Definition at line 31 of file PHG4CellDefs.h.
Function Documentation
__attribute__()
static unsigned int bitshift_phi PHG4CellDefs::__attribute__ ((unused)) = bitshift_layer - 16 static
get_binning()
short PHG4CellDefs::get_binning (PHG4CellDefs::keytype key)
Definition at line 160 of file PHG4CellDefs.cc.
get_detid()
short int PHG4CellDefs::get_detid (const PHG4CellDefs::keytype key)
Definition at line 168 of file PHG4CellDefs.cc.
Referenced by PHG4CellContainer::AddCell(), PHG4Cellv1::get_detid(), and PHG4Cellv2::get_detid().
has_binning()
bool PHG4CellDefs::has_binning (PHG4CellDefs::keytype key, PHG4CellDefs::CellBinning binning)
Definition at line 149 of file PHG4CellDefs.cc.
Referenced by PHG4Cellv1::has_binning(), and PHG4Cellv2::has_binning().