Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHTimeStamp.h File Reference
PHTimeStamp.h File Reference
#include "PHObject.h"
#include <ctime>
Classes
class PHTimeStamp
Typedefs
typedef unsigned long long phtime_t
Functions
PHTimeStamp operator+ (const PHTimeStamp &, time_t)
PHTimeStamp operator- (const PHTimeStamp &, time_t)
time_t operator- (const PHTimeStamp &, const PHTimeStamp &)
std::ostream & operator<< (std::ostream &, const PHTimeStamp &)
std::istream & operator>> (std::istream &, PHTimeStamp &)
Typedef Documentation
phtime_t
typedef unsigned long long phtime_t
Definition at line 19 of file PHTimeStamp.h.
Function Documentation
operator+()
PHTimeStamp operator+ (const PHTimeStamp & t1, time_t t2)
Definition at line 215 of file PHTimeStamp.cc.
operator-() [1/2]
time_t operator- (const PHTimeStamp & t1, const PHTimeStamp & t2)
Definition at line 229 of file PHTimeStamp.cc.
References PHTimeStamp::getTics().
operator-() [2/2]
PHTimeStamp operator- (const PHTimeStamp & t1, time_t t2)
Definition at line 222 of file PHTimeStamp.cc.
operator<<()
std::ostream& operator<< (std::ostream & s, const PHTimeStamp & t)
Definition at line 234 of file PHTimeStamp.cc.
References PHTimeStamp::getTics().
operator>>()
std::istream& operator>> (std::istream & s, PHTimeStamp & t)
Definition at line 243 of file PHTimeStamp.cc.
References PHTimeStamp::set().