Class Reference for E1039 Core & Analysis Software: PHG4VtxPoint Class Reference
PHG4VtxPoint Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4VtxPoint.h>
Public Member Functions
virtual ~PHG4VtxPoint ()
virtual void set_x (const double r)
virtual void set_y (const double r)
virtual void set_z (const double r)
virtual void set_t (const double r)
virtual void set_id (const int i)
virtual double get_x () const
virtual double get_y () const
virtual double get_z () const
virtual double get_t () const
virtual int get_id () const
virtual void identify (std::ostream &os=std::cout) const
bool operator== (const PHG4VtxPoint &) const
comparison of vertex value only, not on the id, per algorithm requirement in PHG4TruthInfoContainer::AddPrimaryVertex
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
PHG4VtxPoint ()
Detailed Description
Definition at line 9 of file PHG4VtxPoint.h.
Constructor & Destructor Documentation
~PHG4VtxPoint()
virtual PHG4VtxPoint::~PHG4VtxPoint () inline virtual
Definition at line 12 of file PHG4VtxPoint.h.
PHG4VtxPoint()
PHG4VtxPoint::PHG4VtxPoint () inline protected
Definition at line 33 of file PHG4VtxPoint.h.
Member Function Documentation
get_id()
virtual int PHG4VtxPoint::get_id () const inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 24 of file PHG4VtxPoint.h.
Referenced by PHG4TruthInfoContainer::is_primary_vtx(), and PHG4DSTReader::process_event().
get_t()
virtual double PHG4VtxPoint::get_t () const inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 23 of file PHG4VtxPoint.h.
Referenced by operator==(), PHG4DSTReader::process_event(), and TruthEval::process_event().
get_x()
virtual double PHG4VtxPoint::get_x () const inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 20 of file PHG4VtxPoint.h.
Referenced by operator==(), PHG4DSTReader::process_event(), TruthEval::process_event(), TruthNodeMaker::process_event(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
get_y()
virtual double PHG4VtxPoint::get_y () const inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 21 of file PHG4VtxPoint.h.
Referenced by operator==(), PHG4DSTReader::process_event(), TruthEval::process_event(), TruthNodeMaker::process_event(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
get_z()
virtual double PHG4VtxPoint::get_z () const inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 22 of file PHG4VtxPoint.h.
Referenced by operator==(), PHG4DSTReader::process_event(), TruthEval::process_event(), TruthNodeMaker::process_event(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
identify()
void PHG4VtxPoint::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4VtxPointv1.
Definition at line 9 of file PHG4VtxPoint.cc.
Referenced by PHG4ParticleGeneratorBase::ReuseExistingVertex().
operator==()
bool PHG4VtxPoint::operator== (const PHG4VtxPoint & p) const
comparison of vertex value only, not on the id, per algorithm requirement in PHG4TruthInfoContainer::AddPrimaryVertex
Definition at line 16 of file PHG4VtxPoint.cc.
References get_t(), get_x(), get_y(), and get_z().
set_id()
virtual void PHG4VtxPoint::set_id (const int i) inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 18 of file PHG4VtxPoint.h.
Referenced by PHG4TruthInfoContainer::AddVertex().
set_t()
virtual void PHG4VtxPoint::set_t (const double r) inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 17 of file PHG4VtxPoint.h.
set_x()
virtual void PHG4VtxPoint::set_x (const double r) inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 14 of file PHG4VtxPoint.h.
set_y()
virtual void PHG4VtxPoint::set_y (const double r) inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 15 of file PHG4VtxPoint.h.
set_z()
virtual void PHG4VtxPoint::set_z (const double r) inline virtual
Reimplemented in PHG4VtxPointv1.
Definition at line 16 of file PHG4VtxPoint.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4VtxPoint.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4VtxPoint.cc