E1039 Software: DetectorConstructionWrapper Class Reference
DetectorConstructionWrapper Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/db2g4/DetectorConstructionWrapper.h>
Public Member Functions
DetectorConstructionWrapper (const std::string &name="DetectorConstructionWrapper")
virtual ~DetectorConstructionWrapper ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
const std::string & get_out_name () const
void set_out_name (const std::string &outName)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string _geometrySchema
double _fMagStr
double _kMagStr
std::string _out_name
JobOptsSvc * _jobOptsSvc
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 17 of file DetectorConstructionWrapper.h.
Constructor & Destructor Documentation
DetectorConstructionWrapper()
DetectorConstructionWrapper::DetectorConstructionWrapper (const std::string & name = "DetectorConstructionWrapper")
Definition at line 35 of file DetectorConstructionWrapper.cxx.
~DetectorConstructionWrapper()
virtual DetectorConstructionWrapper::~DetectorConstructionWrapper () inline virtual
Definition at line 22 of file DetectorConstructionWrapper.h.
References Init().
Member Function Documentation
End()
int DetectorConstructionWrapper::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 61 of file DetectorConstructionWrapper.cxx.
References Fun4AllReturnCodes::EVENT_OK.
Referenced by process_event().
get_out_name()
const std::string& DetectorConstructionWrapper::get_out_name () const inline
Definition at line 30 of file DetectorConstructionWrapper.h.
References _out_name.
Init()
int DetectorConstructionWrapper::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 44 of file DetectorConstructionWrapper.cxx.
References _fMagStr, _geometrySchema, _kMagStr, _out_name, DetectorConstruction::Construct(), Fun4AllReturnCodes::EVENT_OK, Settings::fMagMultiplier, Settings::geometrySchema, and Settings::kMagMultiplier.
Referenced by ~DetectorConstructionWrapper().
InitRun()
int DetectorConstructionWrapper::InitRun (PHCompositeNode *) inline virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 26 of file DetectorConstructionWrapper.h.
process_event()
int DetectorConstructionWrapper::process_event (PHCompositeNode *) inline virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 27 of file DetectorConstructionWrapper.h.
References End().
set_out_name()
void DetectorConstructionWrapper::set_out_name (const std::string & outName) inline
Definition at line 34 of file DetectorConstructionWrapper.h.
References _out_name.
Member Data Documentation
_fMagStr
double DetectorConstructionWrapper::_fMagStr private
Definition at line 42 of file DetectorConstructionWrapper.h.
Referenced by Init().
_geometrySchema
std::string DetectorConstructionWrapper::_geometrySchema private
Definition at line 40 of file DetectorConstructionWrapper.h.
Referenced by Init().
_jobOptsSvc
JobOptsSvc* DetectorConstructionWrapper::_jobOptsSvc private
Definition at line 47 of file DetectorConstructionWrapper.h.
_kMagStr
double DetectorConstructionWrapper::_kMagStr private
Definition at line 43 of file DetectorConstructionWrapper.h.
Referenced by Init().
_out_name
std::string DetectorConstructionWrapper::_out_name private
Definition at line 45 of file DetectorConstructionWrapper.h.
Referenced by get_out_name(), Init(), and set_out_name().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/db2g4/DetectorConstructionWrapper.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/db2g4/DetectorConstructionWrapper.cxx