Class Reference for E1039 Core & Analysis Software: Fun4AllEVIOInputManager Class Reference
Fun4AllEVIOInputManager Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/Fun4AllEVIOInputManager.h>
Public Member Functions
Fun4AllEVIOInputManager (const std::string &name="DUMMY", const std::string &topnodename="TOP")
virtual ~Fun4AllEVIOInputManager ()
int fileopen (const std::string &filenam)
int fileclose ()
int run (const int nevents=0)
int isOpen ()
void Print (const std::string &what="ALL") const
int ResetEvent ()
int PushBackEvents (const int i)
int GetSyncObject (SyncObject **mastersync)
int SyncIt (const SyncObject *mastersync)
void SetOnline (const bool is_online)
void EventSamplingFactor (const int factor)
void DirParam (const std::string dir)
void PretendSpillInterval (const int sec)
Public Member Functions inherited from Fun4AllInputManager
virtual ~Fun4AllInputManager ()
virtual int ReadInRunNode (PHCompositeNode *)
virtual std::string Filename ()
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
virtual int skip (const int nevt)
virtual int NoSyncPushBackEvents (const int)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
int ResetFileList ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int OpenNextFile ()
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
int segment
int isopen
int events_total
int events_thisfile
std::string topNodeName
PHCompositeNode * topNode
SyncObject * syncobject
MainDaqParser * parser
Protected Attributes inherited from Fun4AllInputManager
std::vector< SubsysReco * > Subsystems
std::string InputNode
std::string filename
std::string topNodeName
std::list< std::string > filelist
std::list< std::string > filelist_copy
std::list< std::string > filelist_opened
Fun4AllSyncManager * mySyncManager
int repeat
int myrunnumber
int initrun
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 13 of file Fun4AllEVIOInputManager.h.
Constructor & Destructor Documentation
Fun4AllEVIOInputManager::Fun4AllEVIOInputManager (const std::string & name = "DUMMY", const std::string & topnodename = "TOP")
Definition at line 40 of file Fun4AllEVIOInputManager.cc.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), Fun4AllServer::instance(), se, syncobject, topNode, Fun4AllServer::topNode(), and topNodeName.
Fun4AllEVIOInputManager::~Fun4AllEVIOInputManager () virtual
Definition at line 98 of file Fun4AllEVIOInputManager.cc.
References fileclose(), isopen, parser, and syncobject.
Member Function Documentation
void Fun4AllEVIOInputManager::DirParam (const std::string dir)
Definition at line 558 of file Fun4AllEVIOInputManager.cc.
References MainDaqParser::dec_par, DecoParam::dir_param, and parser.
Referenced by Fun4CODA(), and Fun4MainDaq().
void Fun4AllEVIOInputManager::EventSamplingFactor (const int factor)
Definition at line 553 of file Fun4AllEVIOInputManager.cc.
References MainDaqParser::dec_par, parser, and DecoParam::sampling.
Referenced by Fun4CODA(), Fun4MainDaq(), and Fun4MainDaqE906().
int Fun4AllEVIOInputManager::fileclose () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 374 of file Fun4AllEVIOInputManager.cc.
References MainDaqParser::End(), Fun4AllInputManager::filelist, isopen, Fun4AllBase::Name(), parser, and Fun4AllInputManager::repeat.
Referenced by fileopen(), run(), and ~Fun4AllEVIOInputManager().
int Fun4AllEVIOInputManager::fileopen (const std::string & filenam) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 108 of file Fun4AllEVIOInputManager.cc.
References Fun4AllInputManager::AddToFileOpened(), MainDaqParser::dec_par, events_thisfile, fileclose(), Fun4AllInputManager::filename, isopen, MainDaqParser::OpenCodaFile(), parser, PHWHERE, segment, Fun4AllBase::ThisName, DecoParam::verbose, Fun4AllBase::Verbosity(), and Fun4AllBase::verbosity.
Referenced by Fun4CODA(), Fun4MainDaq(), Fun4MainDaqE906(), and OpenNextFile().
int Fun4AllEVIOInputManager::GetSyncObject (SyncObject ** mastersync) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 509 of file Fun4AllEVIOInputManager.cc.
References SyncObject::clone(), Fun4AllReturnCodes::SYNC_OK, and syncobject.
int Fun4AllEVIOInputManager::isOpen () inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 21 of file Fun4AllEVIOInputManager.h.
References isopen.
int Fun4AllEVIOInputManager::OpenNextFile () protected
Definition at line 413 of file Fun4AllEVIOInputManager.cc.
References Fun4AllInputManager::filelist, fileopen(), PHWHERE, and Fun4AllBase::verbosity.
Referenced by run().
void Fun4AllEVIOInputManager::PretendSpillInterval (const int sec)
Definition at line 563 of file Fun4AllEVIOInputManager.cc.
References MainDaqParser::dec_par, parser, and DecoParam::time_wait.
void Fun4AllEVIOInputManager::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllInputManager.
Definition at line 406 of file Fun4AllEVIOInputManager.cc.
References Fun4AllInputManager::Print().
int Fun4AllEVIOInputManager::PushBackEvents (const int i) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 449 of file Fun4AllEVIOInputManager.cc.
int Fun4AllEVIOInputManager::ResetEvent () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 437 of file Fun4AllEVIOInputManager.cc.
References SyncObject::Reset(), and syncobject.
Referenced by run().
int Fun4AllEVIOInputManager::run (const int nevents = 0) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 141 of file Fun4AllEVIOInputManager.cc.
References Fun4AllReturnCodes::ABORTEVENT, EventInfo::AfterInhMATRIX, SQScaler::BOS, SpillData::bos_coda_id, SpillData::bos_vme_time, DecoParam::chan_map_scaler, DecoParam::chan_map_taiwan, DecoParam::chan_map_v1495, EventInfo::codaEventID, Fun4AllSyncManager::CurrentEvent(), EventInfo::dataQuality, MainDaqParser::dec_par, HitData::det, HitData::ele, SQScaler::EOS, SpillData::eos_coda_id, SpillData::eos_vme_time, EventData::event, Fun4AllReturnCodes::EVENT_OK, SyncObject::EventCounter(), EventInfo::eventID, SyncObject::EventNumber(), events_thisfile, events_total, fileclose(), Fun4AllInputManager::filelist, EventInfo::flag_v1495, RunData::fpga_enabled, RunData::fpga_prescale, SQSpillMap::get(), SQSpill::get_bos_scaler_list(), SQSpill::get_eos_scaler_list(), SQSpill::get_slow_cont_list(), RunParamBase::GetMapID(), RunParamBase::GetParamID(), HitData::id, SQStringMap::insert(), SQSpillMap::insert(), isopen, EventData::list_hit, EventData::list_hit_trig, SpillData::list_scaler, SpillData::list_slow_cont, HitData::lvl, EventInfo::MATRIX, SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, SQEvent::MATRIX5, Fun4AllInputManager::mySyncManager, RunData::n_evt_all, RunData::n_evt_dec, RunData::n_fee_event, RunData::n_fee_prescale, RunData::n_flush_evt, RunData::n_flush_evt_bad, RunData::n_hit, RunData::n_hit_bad, RunData::n_phys_evt, RunData::n_phys_evt_bad, EventData::n_qie, RunData::n_run_desc, RunData::n_spill, RunData::n_t_hit, RunData::n_t_hit_bad, EventData::n_tdc, EventData::n_trig_b, EventData::n_trig_c, RunData::n_v1495, EventData::n_v1495, RunData::n_v1495_d1ad, RunData::n_v1495_d2ad, RunData::n_v1495_d3ad, Fun4AllBase::Name(), MainDaqParser::NextPhysicsEvent(), EventInfo::NIM, SQEvent::NIM1, SQEvent::NIM2, SQEvent::NIM3, SQEvent::NIM4, SQEvent::NIM5, RunData::nim_prescale, OpenNextFile(), parser, Fun4AllSyncManager::PrdfEvents(), SQHitVector::push_back(), EventInfo::RawMATRIX, Fun4AllInputManager::RejectEvent(), ResetEvent(), EventInfo::rf, EventInfo::rfOnset, RunData::run_desc, RunData::run_id, SpillData::run_id, EventInfo::runID, SyncObject::RunNumber(), Fun4AllSyncManager::SegmentNumber(), SyncObject::SegmentNumber(), SQEvent::set_after_inh_matrix(), SQSpill::set_bos_coda_id(), SQSpill::set_bos_vme_time(), SQEvent::set_coda_event_id(), SQScaler_v1::set_count(), SQEvent::set_data_quality(), SQHit::set_detector_id(), SQHit::set_element_id(), SQSpill::set_eos_coda_id(), SQSpill::set_eos_vme_time(), SQEvent::set_event_id(), SQEvent::set_flag_v1495(), SQRun::set_fpga_enabled(), SQRun::set_fpga_prescale(), SQHit::set_hit_id(), SQHit::set_level(), SQEvent::set_n_board_qie(), SQEvent::set_n_board_taiwan(), SQEvent::set_n_board_trig_bit(), SQEvent::set_n_board_trig_count(), SQEvent::set_n_board_v1495(), SQRun::set_n_evt_all(), SQRun::set_n_evt_dec(), SQRun::set_n_fee_event(), SQRun::set_n_fee_prescale(), SQRun::set_n_flush_evt(), SQRun::set_n_flush_evt_bad(), SQRun::set_n_hit(), SQRun::set_n_hit_bad(), SQRun::set_n_phys_evt(), SQRun::set_n_phys_evt_bad(), SQRun::set_n_run_desc(), SQRun::set_n_spill(), SQRun::set_n_t_hit(), SQRun::set_n_t_hit_bad(), SQRun::set_n_v1495(), SQRun::set_n_v1495_d1ad(), SQRun::set_n_v1495_d2ad(), SQRun::set_n_v1495_d3ad(), SQSlowCont_v1::set_name(), SQScaler_v1::set_name(), SQRun::set_nim_enabled(), SQRun::set_nim_prescale(), SQEvent::set_qie_presum(), SQEvent::set_qie_rf_id(), SQEvent::set_qie_rf_intensity(), SQEvent::set_qie_trigger_count(), SQEvent::set_qie_turn_id(), SQEvent::set_raw_matrix(), SQRun::set_run_desc(), SQRun::set_run_id(), SQSpill::set_run_id(), SQEvent::set_run_id(), SQSpill::set_spill_id(), SQEvent::set_spill_id(), SQSpill::set_target_pos(), SQHit::set_tdc_time(), SQSlowCont_v1::set_time_stamp(), SQEvent::set_trigger(), SQScaler_v1::set_type(), SQSlowCont_v1::set_type(), SQRun::set_unix_time_begin(), SQRun::set_unix_time_end(), SQSlowCont_v1::set_value(), SQParamDeco::set_variable(), SQEvent::set_vme_time(), Fun4AllInputManager::SetRunNumber(), SpillData::spill_id, EventInfo::spillID, EventInfo::sums, syncobject, SpillData::targ_pos, Fun4AllBase::ThisName, HitData::time, topNode, EventInfo::triggerCount, EventInfo::turnOnset, MainDaqParser::TYPE_BOS, RunData::utime_b, RunData::utime_e, Fun4AllBase::verbosity, and EventInfo::vmeTime.
void Fun4AllEVIOInputManager::SetOnline (const bool is_online)
Definition at line 547 of file Fun4AllEVIOInputManager.cc.
References MainDaqParser::dec_par, MainDaqParser::GetCoda(), DecoParam::is_online, parser, and CodaInputManager::SetOnline().
Referenced by Fun4MainDaq(), and Fun4MainDaqE906().
int Fun4AllEVIOInputManager::SyncIt (const SyncObject * mastersync) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 527 of file Fun4AllEVIOInputManager.cc.
References SyncObject::Different(), Fun4AllBase::Name(), PHWHERE, Fun4AllReturnCodes::SYNC_FAIL, Fun4AllReturnCodes::SYNC_OK, and syncobject.
Member Data Documentation
int Fun4AllEVIOInputManager::events_thisfile protected
Definition at line 39 of file Fun4AllEVIOInputManager.h.
Referenced by fileopen(), and run().
int Fun4AllEVIOInputManager::events_total protected
Definition at line 38 of file Fun4AllEVIOInputManager.h.
Referenced by run().
int Fun4AllEVIOInputManager::isopen protected
Definition at line 37 of file Fun4AllEVIOInputManager.h.
Referenced by fileclose(), fileopen(), isOpen(), run(), and ~Fun4AllEVIOInputManager().
MainDaqParser* Fun4AllEVIOInputManager::parser protected
Definition at line 43 of file Fun4AllEVIOInputManager.h.
Referenced by DirParam(), EventSamplingFactor(), fileclose(), fileopen(), PretendSpillInterval(), run(), SetOnline(), and ~Fun4AllEVIOInputManager().
int Fun4AllEVIOInputManager::segment protected
Definition at line 36 of file Fun4AllEVIOInputManager.h.
Referenced by fileopen().
SyncObject* Fun4AllEVIOInputManager::syncobject protected
Definition at line 42 of file Fun4AllEVIOInputManager.h.
Referenced by Fun4AllEVIOInputManager(), GetSyncObject(), ResetEvent(), run(), SyncIt(), and ~Fun4AllEVIOInputManager().
PHCompositeNode* Fun4AllEVIOInputManager::topNode protected
Definition at line 41 of file Fun4AllEVIOInputManager.h.
Referenced by Fun4AllEVIOInputManager(), and run().
std::string Fun4AllEVIOInputManager::topNodeName protected
Definition at line 40 of file Fun4AllEVIOInputManager.h.
Referenced by Fun4AllEVIOInputManager().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/Fun4AllEVIOInputManager.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/Fun4AllEVIOInputManager.cc