Class Reference for E1039 Core & Analysis Software: CalibHitPos Class Reference
CalibHitPos Class Reference
SubsysReco module to update the hit position, i.e. SQHit::set_pos().
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaCustomFile/src/CalibHitPos.h>
Public Member Functions
CalibHitPos (const std::string &name="CalibHitPos")
virtual ~CalibHitPos ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
SubsysReco module to update the hit position, i.e. SQHit::set_pos().
Definition at line 7 of file CalibHitPos.h.
Constructor & Destructor Documentation
CalibHitPos()
CalibHitPos::CalibHitPos (const std::string & name = "CalibHitPos")
Definition at line 12 of file CalibHitPos.cc.
~CalibHitPos()
CalibHitPos::~CalibHitPos () virtual
Definition at line 19 of file CalibHitPos.cc.
Member Function Documentation
End()
int CalibHitPos::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 52 of file CalibHitPos.cc.
References Fun4AllReturnCodes::EVENT_OK.
Init()
int CalibHitPos::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 24 of file CalibHitPos.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRun()
int CalibHitPos::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 29 of file CalibHitPos.cc.
References Fun4AllReturnCodes::ABORTEVENT, and Fun4AllReturnCodes::EVENT_OK.
process_event()
int CalibHitPos::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 36 of file CalibHitPos.cc.
References SQHitVector::begin(), SQHitVector::end(), Fun4AllReturnCodes::EVENT_OK, SQHit::get_detector_id(), SQHit::get_element_id(), SQHit::get_pos(), GeomSvc::getMeasurement(), GeomSvc::instance(), GeomSvc::isChamber(), GeomSvc::isPropTube(), SQHit::set_pos(), and Fun4AllBase::Verbosity().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaCustomFile/src/CalibHitPos.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaCustomFile/src/CalibHitPos.cc