E1039 Software: PHPointerListIterator< T > Class Template Reference
PHPointerListIterator< T > Class Template Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHPointerListIterator.h>
Public Member Functions
PHPointerListIterator (const PHPointerList< T > &)
virtual ~PHPointerListIterator ()
T * operator() ()
void operator-- ()
void reset ()
size_t pos () const
Protected Member Functions
PHPointerListIterator ()
Private Attributes
const PHPointerList< T > & list
size_t index
Detailed Description
template<class T>
class PHPointerListIterator< T >
Definition at line 11 of file PHPointerListIterator.h.
Constructor & Destructor Documentation
PHPointerListIterator() [1/2]
template<class T> PHPointerListIterator< T >::PHPointerListIterator (const PHPointerList< T > & lis)
Definition at line 32 of file PHPointerListIterator.h.
~PHPointerListIterator()
template<class T> virtual PHPointerListIterator< T >::~PHPointerListIterator () inline virtual
Definition at line 15 of file PHPointerListIterator.h.
PHPointerListIterator() [2/2]
template<class T> PHPointerListIterator< T >::PHPointerListIterator () inline protected
Definition at line 24 of file PHPointerListIterator.h.
Member Function Documentation
operator()()
template<class T > T * PHPointerListIterator< T >::operator() ()
Definition at line 39 of file PHPointerListIterator.h.
Referenced by PHPointerListIterator< PdbCalBank >::~PHPointerListIterator().
operator--()
template<class T > void PHPointerListIterator< T >::operator-- ()
Definition at line 53 of file PHPointerListIterator.h.
Referenced by PHPointerListIterator< PdbCalBank >::~PHPointerListIterator().
pos()
template<class T> size_t PHPointerListIterator< T >::pos () const inline
Definition at line 21 of file PHPointerListIterator.h.
Referenced by PHCompositeNode::forgetMe(), and PHCompositeNode::prune().
reset()
template<class T > void PHPointerListIterator< T >::reset ()
Definition at line 59 of file PHPointerListIterator.h.
Referenced by PHPointerListIterator< PdbCalBank >::PHPointerListIterator(), and PHPointerListIterator< PdbCalBank >::~PHPointerListIterator().
Member Data Documentation
index
template<class T> size_t PHPointerListIterator< T >::index private
Definition at line 28 of file PHPointerListIterator.h.
Referenced by PHPointerListIterator< PdbCalBank >::operator()(), PHPointerListIterator< PdbCalBank >::operator--(), PHPointerListIterator< PdbCalBank >::pos(), and PHPointerListIterator< PdbCalBank >::reset().
list
template<class T> const PHPointerList<T>& PHPointerListIterator< T >::list private
Definition at line 27 of file PHPointerListIterator.h.
Referenced by PHPointerListIterator< PdbCalBank >::operator()().
The documentation for this class was generated from the following file:
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHPointerListIterator.h