E1039 Software: PatternDBGen Class Reference
PatternDBGen Class Reference
General purposed evaluation module.
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/PatternDBGen.h>
Public Member Functions
PatternDBGen (const std::string &name="PatternDBGen")
virtual ~PatternDBGen ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int InitEvalTree ()
int ResetEvalVars ()
const std::string & get_hit_container_choice () const
void set_hit_container_choice (const std::string &hitContainerChoice)
const std::string & get_out_name () const
void set_out_name (const std::string &outName)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
int TruthEval (PHCompositeNode *topNode)
Private Attributes
std::string _hit_container_type
size_t _event
SQEvent * _event_header
SQHitMap * _hit_map
SQHitVector * _hit_vector
PHG4TruthInfoContainer * _truth
SRecEvent * _recEvent
std::string _out_name
TTree * _tout_truth
int run_id
int spill_id
float target_pos
int event_id
int n_tracks
int pid [1000]
float gvx [1000]
float gvy [1000]
float gvz [1000]
float gpx [1000]
float gpy [1000]
float gpz [1000]
float gx_st1 [1000]
float gy_st1 [1000]
float gz_st1 [1000]
float gpx_st1 [1000]
float gpy_st1 [1000]
float gpz_st1 [1000]
float gpt [1000]
float geta [1000]
float gphi [1000]
int gnhits [1000]
int gndc [1000]
int gnhodo [1000]
int gnprop [1000]
int gelmid [1000][55]
GeomSvc * p_geomSvc
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
General purposed evaluation module.
Author
Haiwang Yu, yuhw@.nosp@m.nmsu.nosp@m..edu
Created: 08-27-2018
Definition at line 44 of file PatternDBGen.h.
Constructor & Destructor Documentation
PatternDBGen()
PatternDBGen::PatternDBGen (const std::string & name = "PatternDBGen")
Definition at line 56 of file PatternDBGen.cxx.
~PatternDBGen()
virtual PatternDBGen::~PatternDBGen () inline virtual
Definition at line 49 of file PatternDBGen.h.
References End(), Init(), InitEvalTree(), InitRun(), process_event(), and ResetEvalVars().
Member Function Documentation
End()
int PatternDBGen::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 260 of file PatternDBGen.cxx.
References _out_name, _tout_truth, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
Referenced by ~PatternDBGen().
get_hit_container_choice()
const std::string& PatternDBGen::get_hit_container_choice () const inline
Definition at line 60 of file PatternDBGen.h.
References _hit_container_type.
get_out_name()
const std::string& PatternDBGen::get_out_name () const inline
Definition at line 68 of file PatternDBGen.h.
References _out_name.
GetNodes()
int PatternDBGen::GetNodes (PHCompositeNode * topNode) private
Definition at line 342 of file PatternDBGen.cxx.
References _hit_container_type, _hit_map, _hit_vector, _truth, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and LogError.
Referenced by InitRun(), and set_out_name().
Init()
int PatternDBGen::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 67 of file PatternDBGen.cxx.
References Fun4AllReturnCodes::EVENT_OK.
Referenced by ~PatternDBGen().
InitEvalTree()
int PatternDBGen::InitEvalTree ()
Definition at line 270 of file PatternDBGen.cxx.
References _out_name, _tout_truth, gelmid, PHTFileServer::get(), gndc, n_tracks, PHTFileServer::open(), and pid.
Referenced by InitRun(), and ~PatternDBGen().
InitRun()
int PatternDBGen::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 71 of file PatternDBGen.cxx.
References Fun4AllReturnCodes::EVENT_OK, GetNodes(), InitEvalTree(), GeomSvc::instance(), p_geomSvc, and ResetEvalVars().
Referenced by ~PatternDBGen().
process_event()
int PatternDBGen::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 84 of file PatternDBGen.cxx.
References _event, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, and TruthEval().
Referenced by ~PatternDBGen().
ResetEvalVars()
int PatternDBGen::ResetEvalVars ()
Definition at line 305 of file PatternDBGen.cxx.
References event_id, gelmid, geta, gndc, gnhits, gnhodo, gnprop, gphi, gpt, gpx, gpx_st1, gpy, gpy_st1, gpz, gpz_st1, gvx, gvy, gvz, gx_st1, gy_st1, gz_st1, n_tracks, pid, run_id, spill_id, and target_pos.
Referenced by InitRun(), TruthEval(), and ~PatternDBGen().
set_hit_container_choice()
void PatternDBGen::set_hit_container_choice (const std::string & hitContainerChoice) inline
Definition at line 64 of file PatternDBGen.h.
References _hit_container_type.
set_out_name()
void PatternDBGen::set_out_name (const std::string & outName) inline
Definition at line 72 of file PatternDBGen.h.
References _out_name, GetNodes(), and TruthEval().
TruthEval()
int PatternDBGen::TruthEval (PHCompositeNode * topNode) private
Definition at line 95 of file PatternDBGen.cxx.
References _event, _hit_vector, _tout_truth, _truth, SQHitVector::at(), Fun4AllReturnCodes::EVENT_OK, gelmid, SQHit::get_detector_id(), SQHit::get_element_id(), SQHit::get_g4hit_id(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Hit::get_px(), PHG4Particle::get_py(), PHG4Hit::get_py(), PHG4Particle::get_pz(), PHG4Hit::get_pz(), PHG4Particle::get_track_id(), SQHit::get_track_id(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), PHG4Hit::get_x(), PHG4VtxPoint::get_y(), PHG4Hit::get_y(), PHG4VtxPoint::get_z(), PHG4Hit::get_z(), geta, PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetVtx(), gndc, gnhits, gnhodo, gnprop, gphi, gpt, gpx, gpx_st1, gpy, gpy_st1, gpz, gpz_st1, gvx, gvy, gvz, gx_st1, gy_st1, gz_st1, PHG4Hit::identify(), SQHit::identify(), LogDebug, LogInfo, LogWarning, n_tracks, Fun4AllBase::Name(), pid, ResetEvalVars(), SQHitVector::size(), Fun4AllBase::Verbosity(), Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_A_LOT.
Referenced by process_event(), and set_out_name().
Member Data Documentation
_event
size_t PatternDBGen::_event private
Definition at line 84 of file PatternDBGen.h.
Referenced by process_event(), and TruthEval().
_event_header
SQEvent* PatternDBGen::_event_header private
Definition at line 86 of file PatternDBGen.h.
_hit_container_type
std::string PatternDBGen::_hit_container_type private
Definition at line 82 of file PatternDBGen.h.
Referenced by get_hit_container_choice(), GetNodes(), and set_hit_container_choice().
_hit_map
SQHitMap* PatternDBGen::_hit_map private
Definition at line 87 of file PatternDBGen.h.
Referenced by GetNodes().
_hit_vector
SQHitVector* PatternDBGen::_hit_vector private
Definition at line 88 of file PatternDBGen.h.
Referenced by GetNodes(), and TruthEval().
_out_name
std::string PatternDBGen::_out_name private
Definition at line 94 of file PatternDBGen.h.
Referenced by End(), get_out_name(), InitEvalTree(), and set_out_name().
_recEvent
SRecEvent* PatternDBGen::_recEvent private
Definition at line 92 of file PatternDBGen.h.
_tout_truth
TTree* PatternDBGen::_tout_truth private
Definition at line 95 of file PatternDBGen.h.
Referenced by End(), InitEvalTree(), and TruthEval().
_truth
PHG4TruthInfoContainer* PatternDBGen::_truth private
Definition at line 90 of file PatternDBGen.h.
Referenced by GetNodes(), and TruthEval().
event_id
int PatternDBGen::event_id private
Definition at line 100 of file PatternDBGen.h.
Referenced by ResetEvalVars().
gelmid
int PatternDBGen::gelmid[1000][55] private
Definition at line 124 of file PatternDBGen.h.
Referenced by InitEvalTree(), ResetEvalVars(), and TruthEval().
geta
float PatternDBGen::geta[1000] private
Definition at line 117 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gndc
int PatternDBGen::gndc[1000] private
Definition at line 120 of file PatternDBGen.h.
Referenced by InitEvalTree(), ResetEvalVars(), and TruthEval().
gnhits
int PatternDBGen::gnhits[1000] private
Definition at line 119 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gnhodo
int PatternDBGen::gnhodo[1000] private
Definition at line 121 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gnprop
int PatternDBGen::gnprop[1000] private
Definition at line 122 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gphi
float PatternDBGen::gphi[1000] private
Definition at line 118 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gpt
float PatternDBGen::gpt[1000] private
Definition at line 116 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gpx
float PatternDBGen::gpx[1000] private
Definition at line 107 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gpx_st1
float PatternDBGen::gpx_st1[1000] private
Definition at line 113 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gpy
float PatternDBGen::gpy[1000] private
Definition at line 108 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gpy_st1
float PatternDBGen::gpy_st1[1000] private
Definition at line 114 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gpz
float PatternDBGen::gpz[1000] private
Definition at line 109 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gpz_st1
float PatternDBGen::gpz_st1[1000] private
Definition at line 115 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gvx
float PatternDBGen::gvx[1000] private
Definition at line 104 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gvy
float PatternDBGen::gvy[1000] private
Definition at line 105 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gvz
float PatternDBGen::gvz[1000] private
Definition at line 106 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gx_st1
float PatternDBGen::gx_st1[1000] private
Definition at line 110 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gy_st1
float PatternDBGen::gy_st1[1000] private
Definition at line 111 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
gz_st1
float PatternDBGen::gz_st1[1000] private
Definition at line 112 of file PatternDBGen.h.
Referenced by ResetEvalVars(), and TruthEval().
n_tracks
int PatternDBGen::n_tracks private
Definition at line 102 of file PatternDBGen.h.
Referenced by InitEvalTree(), ResetEvalVars(), and TruthEval().
p_geomSvc
GeomSvc* PatternDBGen::p_geomSvc private
Definition at line 126 of file PatternDBGen.h.
Referenced by InitRun().
pid
int PatternDBGen::pid[1000] private
Definition at line 103 of file PatternDBGen.h.
Referenced by InitEvalTree(), ResetEvalVars(), and TruthEval().
run_id
int PatternDBGen::run_id private
Definition at line 97 of file PatternDBGen.h.
Referenced by ResetEvalVars().
spill_id
int PatternDBGen::spill_id private
Definition at line 98 of file PatternDBGen.h.
Referenced by ResetEvalVars().
target_pos
float PatternDBGen::target_pos private
Definition at line 99 of file PatternDBGen.h.
Referenced by ResetEvalVars().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/PatternDBGen.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/PatternDBGen.cxx