Class Reference for E1039 Core & Analysis Software: Fun4AllSpillDstOutputManager Class Reference
Fun4AllSpillDstOutputManager Class Reference
A Fun4All output manger that creates one DST file per spill group.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/Fun4AllSpillDstOutputManager.h>
Public Member Functions
Fun4AllSpillDstOutputManager (const std::string &dir_base, const std::string &myname="SPILLDSTOUT")
virtual ~Fun4AllSpillDstOutputManager ()
void SetSpillStep (const int step)
int Write (PHCompositeNode *startNode)
write starting from given node
void EnableDB (const bool refresh_db=false, const std::string name_table="spill_dst_status")
Public Member Functions inherited from Fun4AllDstOutputManager
Fun4AllDstOutputManager (const std::string &myname="DSTOUT", const std::string &filename="dstout.root")
virtual ~Fun4AllDstOutputManager ()
int AddNode (const std::string &nodename)
add a node in outputmanager
int StripNode (const std::string &nodename)
not write a node in outputmanager
int outfileopen (const std::string &fname)
opens output file
int RemoveNode (const std::string &nodename)
removes a node from outputmanager
void Print (const std::string &what="ALL") const
print method (dump event selector)
virtual int WriteNode (PHCompositeNode *thisNode)
write specified node
void EnableRealTimeSave ()
Public Member Functions inherited from Fun4AllOutputManager
virtual ~Fun4AllOutputManager ()
destructor
virtual int AddEventSelector (const std::string &recomodule)
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
int WriteGeneric (PHCompositeNode *startNode)
Common method, called before calling virtual Write.
virtual std::vector< std::string > * EventSelector ()
retrieves pointer to vector of event selector module names
virtual std::vector< unsigned > * RecoModuleIndex ()
retrieves pointer to vector of event selector module ids
virtual int DoNotWriteEvent (std::vector< int > *retcodes) const
decides if event is to be written or not
virtual size_t EventsWritten () const
get number of Events
virtual std::string OutFileName () const
get output file name
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
void DstStarted (const int run, const int spill_f, const int spill_l, const std::string file_name, int utime=0)
void DstFinished (const int run, const int spill_f, const int spill_l, int utime=0)
Protected Member Functions inherited from Fun4AllOutputManager
Fun4AllOutputManager (const std::string &myname)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from Fun4AllDstOutputManager
std::vector< std::string > savenodes
std::vector< std::string > stripnodes
PHNodeIOManager * dstOut
Protected Attributes inherited from Fun4AllOutputManager
size_t nEvents
Number of Events.
std::vector< std::string > EventSelectors
vector of event selectors modules
std::vector< unsigned > recomoduleindex
vector of associated module indexes
std::string outfilename
output file name
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
A Fun4All output manger that creates one DST file per spill group.
The number of spills per group (= spill step) is 10 by default. One can simply register it to Fun4AllServer as usual.
Fun4AllSpillDstOutputManager* out_sp = new Fun4AllSpillDstOutputManager(UtilOnline::GetDstFileDir() + "/spill"); //out_sp->SetSpillStep(50); se->registerOutputManager(out_sp);
The status of DST outputs is recorded onto MySQL DB, once EnableDB() is called. The table name is spill_dst_status by default. The status is 1 when started, and 2 when finished.
Definition at line 19 of file Fun4AllSpillDstOutputManager.h.
Constructor & Destructor Documentation
Fun4AllSpillDstOutputManager()
Fun4AllSpillDstOutputManager::Fun4AllSpillDstOutputManager (const std::string & dir_base, const std::string & myname = "SPILLDSTOUT")
Definition at line 13 of file Fun4AllSpillDstOutputManager.cc.
~Fun4AllSpillDstOutputManager()
Fun4AllSpillDstOutputManager::~Fun4AllSpillDstOutputManager () virtual
Definition at line 25 of file Fun4AllSpillDstOutputManager.cc.
References DstFinished().
Member Function Documentation
DstFinished()
void Fun4AllSpillDstOutputManager::DstFinished (const int run, const int spill_f, const int spill_l, int utime = 0) protected
Definition at line 113 of file Fun4AllSpillDstOutputManager.cc.
References DbSvc::Con().
Referenced by Write(), and ~Fun4AllSpillDstOutputManager().
DstStarted()
void Fun4AllSpillDstOutputManager::DstStarted (const int run, const int spill_f, const int spill_l, const std::string file_name, int utime = 0) protected
Definition at line 99 of file Fun4AllSpillDstOutputManager.cc.
References DbSvc::Con().
Referenced by Write().
EnableDB()
void Fun4AllSpillDstOutputManager::EnableDB (const bool refresh_db = false, const std::string name_table = "spill_dst_status")
Definition at line 78 of file Fun4AllSpillDstOutputManager.cc.
References DbSvc::VarList::Add(), DbSvc::CreateTable(), DbSvc::DB1, DbSvc::DropTable(), UtilOnline::GetSchemaMainDaq(), DbSvc::HasTable(), and DbSvc::UseSchema().
SetSpillStep()
void Fun4AllSpillDstOutputManager::SetSpillStep (const int step) inline
Definition at line 32 of file Fun4AllSpillDstOutputManager.h.
Write()
int Fun4AllSpillDstOutputManager::Write (PHCompositeNode *) virtual
write starting from given node
Write out and close the current DST file.
Open a new DST file.
Reimplemented from Fun4AllDstOutputManager.
Definition at line 33 of file Fun4AllSpillDstOutputManager.cc.
References DstFinished(), Fun4AllDstOutputManager::dstOut, DstStarted(), PHNodeIterator::findFirst(), SQEvent::get_run_id(), SQEvent::get_spill_id(), Fun4AllServer::instance(), PHNodeIOManager::isFunctional(), Fun4AllOutputManager::outfilename, PHWHERE, PHWrite, PHNodeIOManager::SetCompressionLevel(), Fun4AllDstOutputManager::Write(), and Fun4AllDstOutputManager::WriteNode().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/Fun4AllSpillDstOutputManager.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/Fun4AllSpillDstOutputManager.cc