E1039 Software: Node Class Reference
Node Class Reference
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/kfitter/KalmanUtil.h>
Public Member Functions
Node ()
default constructor, only initialize the matrix dimension
Node (const Hit &_hit)
constructor from a Hit to a Node
Node (const SignedHit &_hit_signed)
Constructor from a signed hit to a Node.
void print (bool verbose=true)
print for debugging purposes
TrkPar & getPredicted ()
Gets.
TrkPar & getFiltered ()
TrkPar & getSmoothed ()
TMatrixD & getMeasurement ()
TMatrixD & getMeasurementCov ()
TMatrixD getPredictedResidual ()
Matrix calculations, should be called as less as possible.
TMatrixD getPredictedResidualCov ()
TMatrixD getFilteredResidual ()
TMatrixD getFilteredResidualCov ()
TMatrixD getSmoothedResidual ()
TMatrixD getSmoothedResidualCov ()
TMatrixD & getPropagator ()
TMatrixD & getProjector ()
TMatrixD getKalmanGain ()
double getZ ()
double getChisq ()
Hit & getHit ()
bool isPredictionDone ()
bool isFilterDone ()
bool isSmoothDone ()
void setMeasurement (TMatrixD &m, TMatrixD &cov)
Sets.
void setZ (double z)
void setProjector (TMatrixD &p)
void setPropagator (TMatrixD &p)
void setPredictionDone (bool flag=true)
void setFilterDone (bool flag=true)
void setSmoothDone (bool flag=true)
void setChisq (double chisq)
void addChisq (double chisq)
void resetFlags ()
bool operator< (const Node &elem) const
Overriden operators.
Private Attributes
TMatrixD _measurement
TMatrixD _measurement_cov
TMatrixD _projector
TMatrixD _propagator
double _z
bool _prediction_done
bool _filter_done
bool _smooth_done
TrkPar _predicted
TrkPar _filtered
TrkPar _smoothed
double _chisq
Hit _hit
Detailed Description
Definition at line 90 of file KalmanUtil.h.
Constructor & Destructor Documentation
Node::Node ()
default constructor, only initialize the matrix dimension
Definition at line 234 of file KalmanUtil.cxx.
References _chisq, _filter_done, _measurement, _measurement_cov, _prediction_done, _projector, _propagator, and _smooth_done.
Node::Node (const Hit & _hit)
constructor from a Hit to a Node
Definition at line 249 of file KalmanUtil.cxx.
References _chisq, _filter_done, _filtered, _hit, _measurement, _measurement_cov, _predicted, _prediction_done, _projector, _propagator, _smooth_done, _smoothed, TrkPar::_z, _z, Hit::detectorID, Hit::driftDistance, GeomSvc::getCostheta(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneResolution(), GeomSvc::getSintheta(), GeomSvc::instance(), and Hit::pos.
Node::Node (const SignedHit & _hit_signed)
Constructor from a signed hit to a Node.
Definition at line 281 of file KalmanUtil.cxx.
References _chisq, _filter_done, _filtered, _hit, _measurement, _measurement_cov, _predicted, _prediction_done, _projector, _propagator, _smooth_done, _smoothed, TrkPar::_z, _z, Hit::detectorID, Hit::driftDistance, GeomSvc::getCostheta(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneResolution(), GeomSvc::getSintheta(), SignedHit::hit, Hit::index, GeomSvc::instance(), Hit::pos, and SignedHit::sign.
Member Function Documentation
void Node::addChisq (double chisq) inline
Definition at line 146 of file KalmanUtil.h.
References _chisq.
double Node::getChisq () inline
Definition at line 127 of file KalmanUtil.h.
References _chisq.
Referenced by VertexFit::findVertex(), KalmanTrack::getMomentumVertex(), and SRecTrack::setZVertex().
TrkPar& Node::getFiltered () inline
Definition at line 107 of file KalmanUtil.h.
References _filtered.
Referenced by KalmanTrack::addHit(), KalmanFilter::filter(), VertexFit::findSingleMuonVertex(), KalmanTrack::getExpPosErrorFast(), KalmanTrack::getExpPositionFast(), KalmanTrack::getMomentumVertex(), KalmanFitter::initSmoother(), KalmanTrack::KalmanTrack(), KalmanFilter::setCurrTrkpar(), SRecTrack::setZVertex(), KalmanFilter::smooth(), and VertexFit::updateVertex().
TMatrixD Node::getFilteredResidual ()
Definition at line 343 of file KalmanUtil.cxx.
References _filtered, _measurement, _projector, and TrkPar::_state_kf.
TMatrixD Node::getFilteredResidualCov ()
Definition at line 351 of file KalmanUtil.cxx.
References TrkPar::_covar_kf, _filtered, _measurement_cov, _projector, and SMatrix::getABCt().
Hit& Node::getHit () inline
Definition at line 129 of file KalmanUtil.h.
References _hit.
Referenced by KalmanTrack::getCurrentDetectorID(), KalmanTrack::getExpPosError(), KalmanTrack::getNodeDownstream(), and KalmanTrack::getNodeUpstream().
TMatrixD Node::getKalmanGain ()
Definition at line 375 of file KalmanUtil.cxx.
References TrkPar::_covar_kf, _measurement_cov, _predicted, _projector, SMatrix::getABCt(), SMatrix::getABtC(), and SMatrix::invertMatrix().
TMatrixD& Node::getMeasurement () inline
Definition at line 110 of file KalmanUtil.h.
References _measurement.
Referenced by KalmanFilter::filter(), KalmanTrack::getMomentumVertex(), SRecTrack::setZVertex(), and VertexFit::VertexFit().
TMatrixD& Node::getMeasurementCov () inline
Definition at line 111 of file KalmanUtil.h.
References _measurement_cov.
Referenced by KalmanFilter::filter(), KalmanTrack::getMomentumVertex(), SRecTrack::setZVertex(), and VertexFit::VertexFit().
TrkPar& Node::getPredicted () inline
Gets.
Definition at line 106 of file KalmanUtil.h.
References _predicted.
Referenced by KalmanTrack::addHit(), KalmanFilter::filter(), VertexFit::findSingleMuonVertex(), KalmanTrack::getExpLcSlopErr(), KalmanTrack::getExpLocalSlop(), KalmanTrack::getExpPosError(), KalmanTrack::getExpPosErrorFast(), KalmanTrack::getExpPosErrorX(), KalmanTrack::getExpPosErrorY(), KalmanTrack::getExpPosition(), KalmanTrack::getExpPositionFast(), KalmanTrack::getExpPositionX(), KalmanTrack::getExpPositionY(), KalmanTrack::KalmanTrack(), KalmanFilter::predict(), and KalmanFilter::smooth().
TMatrixD Node::getPredictedResidual ()
Matrix calculations, should be called as less as possible.
Definition at line 327 of file KalmanUtil.cxx.
References _measurement, _predicted, _projector, and TrkPar::_state_kf.
TMatrixD Node::getPredictedResidualCov ()
Definition at line 335 of file KalmanUtil.cxx.
References TrkPar::_covar_kf, _measurement_cov, _predicted, _projector, and SMatrix::getABCt().
TMatrixD& Node::getProjector () inline
Definition at line 122 of file KalmanUtil.h.
References _projector.
Referenced by KalmanFilter::filter(), KalmanTrack::getExpLcSlopErr(), KalmanTrack::getExpLocalSlop(), KalmanTrack::getExpPosError(), KalmanTrack::getExpPosition(), KalmanTrack::getMomentumVertex(), SRecTrack::setZVertex(), and VertexFit::VertexFit().
TMatrixD& Node::getPropagator () inline
Definition at line 121 of file KalmanUtil.h.
References _propagator.
Referenced by KalmanFilter::predict(), and KalmanFilter::smooth().
TrkPar& Node::getSmoothed () inline
Definition at line 108 of file KalmanUtil.h.
References _smoothed.
Referenced by VertexFit::findSingleMuonVertex(), KalmanTrack::getExpPosErrorFast(), KalmanTrack::getExpPositionFast(), KalmanFitter::initSmoother(), KalmanTrack::KalmanTrack(), KalmanFitter::setStartingParameter(), and KalmanFilter::smooth().
TMatrixD Node::getSmoothedResidual ()
Definition at line 359 of file KalmanUtil.cxx.
References _measurement, _projector, _smoothed, and TrkPar::_state_kf.
TMatrixD Node::getSmoothedResidualCov ()
Definition at line 367 of file KalmanUtil.cxx.
References TrkPar::_covar_kf, _measurement_cov, _projector, _smoothed, and SMatrix::getABCt().
double Node::getZ () inline
Definition at line 126 of file KalmanUtil.h.
References _z.
Referenced by VertexFit::findVertex(), and KalmanFilter::predict().
bool Node::isFilterDone () inline
Definition at line 132 of file KalmanUtil.h.
References _filter_done.
Referenced by KalmanFilter::filter(), VertexFit::findSingleMuonVertex(), KalmanTrack::getExpPosErrorFast(), KalmanTrack::getExpPositionFast(), KalmanFitter::initSmoother(), and KalmanFilter::smooth().
bool Node::isPredictionDone () inline
Definition at line 131 of file KalmanUtil.h.
References _prediction_done.
Referenced by KalmanFilter::filter(), and KalmanFilter::predict().
bool Node::isSmoothDone () inline
Definition at line 133 of file KalmanUtil.h.
References _smooth_done.
Referenced by VertexFit::findSingleMuonVertex(), KalmanTrack::getExpPosErrorFast(), KalmanTrack::getExpPositionFast(), KalmanFitter::initSmoother(), and KalmanFilter::smooth().
bool Node::operator< (const Node & elem) const inline
Overriden operators.
Definition at line 151 of file KalmanUtil.h.
References _z.
void Node::print (bool verbose = true)
print for debugging purposes
Definition at line 197 of file KalmanUtil.cxx.
References _chisq, _filter_done, _filtered, _measurement, _measurement_cov, _predicted, _prediction_done, _projector, _propagator, _smooth_done, _smoothed, TrkPar::_state_kf, TrkPar::print(), and SMatrix::printMatrix().
void Node::resetFlags ()
Definition at line 381 of file KalmanUtil.cxx.
References _chisq, _filter_done, _prediction_done, and _smooth_done.
Referenced by VertexFit::findVertex().
void Node::setChisq (double chisq) inline
Definition at line 145 of file KalmanUtil.h.
References _chisq.
Referenced by KalmanFilter::filter(), and KalmanTrack::KalmanTrack().
void Node::setFilterDone (bool flag = true) inline
Definition at line 142 of file KalmanUtil.h.
References _filter_done.
Referenced by KalmanFilter::filter(), and KalmanTrack::KalmanTrack().
void Node::setMeasurement (TMatrixD & m, TMatrixD & cov)
Sets.
Definition at line 321 of file KalmanUtil.cxx.
References _measurement, and _measurement_cov.
void Node::setPredictionDone (bool flag = true) inline
Definition at line 141 of file KalmanUtil.h.
References _prediction_done.
Referenced by KalmanTrack::addHit(), KalmanTrack::KalmanTrack(), and KalmanFilter::predict().
void Node::setProjector (TMatrixD & p) inline
Definition at line 138 of file KalmanUtil.h.
References _projector.
void Node::setPropagator (TMatrixD & p) inline
Definition at line 139 of file KalmanUtil.h.
References _propagator.
void Node::setSmoothDone (bool flag = true) inline
Definition at line 143 of file KalmanUtil.h.
References _smooth_done.
Referenced by KalmanFitter::initSmoother(), KalmanTrack::KalmanTrack(), and KalmanFilter::smooth().
void Node::setZ (double z) inline
Definition at line 137 of file KalmanUtil.h.
References _z.
Referenced by VertexFit::findVertex(), KalmanTrack::getMomentumVertex(), KalmanTrack::KalmanTrack(), and SRecTrack::setZVertex().
Member Data Documentation
double Node::_chisq private
Definition at line 168 of file KalmanUtil.h.
Referenced by addChisq(), getChisq(), Node(), print(), resetFlags(), and setChisq().
bool Node::_filter_done private
Definition at line 162 of file KalmanUtil.h.
Referenced by isFilterDone(), Node(), print(), resetFlags(), and setFilterDone().
TrkPar Node::_filtered private
Definition at line 166 of file KalmanUtil.h.
Referenced by getFiltered(), getFilteredResidual(), getFilteredResidualCov(), Node(), and print().
Hit Node::_hit private
Definition at line 170 of file KalmanUtil.h.
Referenced by getHit(), and Node().
TMatrixD Node::_measurement private
Definition at line 151 of file KalmanUtil.h.
Referenced by getFilteredResidual(), getMeasurement(), getPredictedResidual(), getSmoothedResidual(), Node(), print(), and setMeasurement().
TMatrixD Node::_measurement_cov private
Definition at line 155 of file KalmanUtil.h.
Referenced by getFilteredResidualCov(), getKalmanGain(), getMeasurementCov(), getPredictedResidualCov(), getSmoothedResidualCov(), Node(), print(), and setMeasurement().
TrkPar Node::_predicted private
Definition at line 165 of file KalmanUtil.h.
Referenced by getKalmanGain(), getPredicted(), getPredictedResidual(), getPredictedResidualCov(), Node(), and print().
bool Node::_prediction_done private
Definition at line 161 of file KalmanUtil.h.
Referenced by isPredictionDone(), Node(), print(), resetFlags(), and setPredictionDone().
TMatrixD Node::_projector private
Definition at line 156 of file KalmanUtil.h.
Referenced by getFilteredResidual(), getFilteredResidualCov(), getKalmanGain(), getPredictedResidual(), getPredictedResidualCov(), getProjector(), getSmoothedResidual(), getSmoothedResidualCov(), Node(), print(), and setProjector().
TMatrixD Node::_propagator private
Definition at line 157 of file KalmanUtil.h.
Referenced by getPropagator(), Node(), print(), and setPropagator().
bool Node::_smooth_done private
Definition at line 163 of file KalmanUtil.h.
Referenced by isSmoothDone(), Node(), print(), resetFlags(), and setSmoothDone().
TrkPar Node::_smoothed private
Definition at line 167 of file KalmanUtil.h.
Referenced by getSmoothed(), getSmoothedResidual(), getSmoothedResidualCov(), Node(), and print().
double Node::_z private
Definition at line 159 of file KalmanUtil.h.
Referenced by getZ(), Node(), operator<(), and setZ().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/kfitter/KalmanUtil.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/kfitter/KalmanUtil.cxx