Class Reference for E1039 Core & Analysis Software: AnaSimDst Class Reference
AnaSimDst Class Reference
An example class to analyze the simulated uDST file.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaSimDst/src/AnaSimDst.h>
Public Member Functions
AnaSimDst ()
virtual ~AnaSimDst ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
An example class to analyze the simulated uDST file.
Definition at line 17 of file AnaSimDst.h.
Constructor & Destructor Documentation
AnaSimDst::AnaSimDst () inline
Definition at line 35 of file AnaSimDst.h.
virtual AnaSimDst::~AnaSimDst () inline virtual
Definition at line 36 of file AnaSimDst.h.
Member Function Documentation
int AnaSimDst::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 107 of file AnaSimDst.cc.
References Fun4AllReturnCodes::EVENT_OK.
int AnaSimDst::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 15 of file AnaSimDst.cc.
References Fun4AllReturnCodes::EVENT_OK.
int AnaSimDst::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 20 of file AnaSimDst.cc.
References Fun4AllReturnCodes::EVENT_OK.
int AnaSimDst::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Event info
Track info
Dimuon info
Reimplemented from SubsysReco.
Definition at line 28 of file AnaSimDst.cc.
References UtilDimuon::CalcVar(), DimuonData::costh, Fun4AllReturnCodes::EVENT_OK, SQDimuon::get_mom(), SQDimuon::get_mom_neg(), SQDimuon::get_mom_pos(), SQDimuon::get_pdg_id(), SQDimuon::get_pos(), DimuonData::mass, DimuonData::mom, DimuonData::mom_neg, DimuonData::mom_pos, SRecDimuon::p_neg, SRecDimuon::p_pos, DimuonData::pdg_id, DimuonData::phi, DimuonData::pos, DimuonData::pT, SRecDimuon::vtx, DimuonData::x1, SRecDimuon::x1, DimuonData::x2, SRecDimuon::x2, and DimuonData::xF.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaSimDst/src/AnaSimDst.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaSimDst/src/AnaSimDst.cc