Class Reference for E1039 Core & Analysis Software: DecoError Class Reference
DecoError Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/DecoError.h>
Public Types
enum TdcError_t {
WORD_ONLY89 = 0 , WORD_OVERFLOW = 1 , MULTIPLE_HEADER = 2 , EVT_ID_ONLY = 3 ,
START_WO_STOP = 4 , START_NOT_RISE = 5 , DIRTY_FINISH = 6 , N_TDC_ERROR = 7 ,
V1495_0BAD = 8
}
Public Member Functions
DecoError ()
~DecoError ()
void SetID (const int run_id, const int spill_id)
void SetFlushError (const bool val)
bool GetFlushError ()
void InitData ()
void CountFlush ()
void AddTdcError (const int event, const int roc, const TdcError_t type)
void AggregateData ()
void PrintData (std::ostream &os=std::cout)
Detailed Description
This class manages errors found in the decoder. At present the decoder error is aggregated once per spill. Therefore
InitData() is called at EOS.
Errors are recorded during flush events are decoded.
UploadToDB() is called at BOS.
Definition at line 14 of file DecoError.h.
Member Enumeration Documentation
TdcError_t
enum DecoError::TdcError_t
Enumerator
WORD_ONLY89
WORD_OVERFLOW
MULTIPLE_HEADER
EVT_ID_ONLY
START_WO_STOP
START_NOT_RISE
DIRTY_FINISH
N_TDC_ERROR
V1495_0BAD
Definition at line 16 of file DecoError.h.
Constructor & Destructor Documentation
DecoError()
DecoError::DecoError ()
Definition at line 10 of file DecoError.cc.
References InitData().
~DecoError()
DecoError::~DecoError () inline
Definition at line 41 of file DecoError.h.
Member Function Documentation
AddTdcError()
void DecoError::AddTdcError (const int event, const int roc, const TdcError_t type)
Definition at line 41 of file DecoError.cc.
AggregateData()
void DecoError::AggregateData ()
Definition at line 48 of file DecoError.cc.
References DbSvc::DB1, UtilOnline::GetSchemaMainDaq(), and DbSvc::UseSchema().
CountFlush()
void DecoError::CountFlush ()
Definition at line 35 of file DecoError.cc.
GetFlushError()
bool DecoError::GetFlushError () inline
Definition at line 45 of file DecoError.h.
InitData()
void DecoError::InitData ()
Definition at line 24 of file DecoError.cc.
References N_TDC_ERROR.
Referenced by DecoError(), and MainDaqParser::End().
PrintData()
void DecoError::PrintData (std::ostream & os = std::cout)
Definition at line 56 of file DecoError.cc.
References N_TDC_ERROR.
Referenced by MainDaqParser::End().
SetFlushError()
void DecoError::SetFlushError (const bool val) inline
Definition at line 44 of file DecoError.h.
SetID()
void DecoError::SetID (const int run_id, const int spill_id)
Definition at line 18 of file DecoError.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/DecoError.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/DecoError.cc