Class Reference for E1039 Core & Analysis Software: std::numeric_limits< half > Class Reference
std::numeric_limits< half > Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Half/halfLimits.h>
Static Public Member Functions
static half min () throw ()
static half max () throw ()
static half epsilon () throw ()
static half round_error () throw ()
static half infinity () throw ()
static half quiet_NaN () throw ()
static half signaling_NaN () throw ()
static half denorm_min () throw ()
Static Public Attributes
static const bool is_specialized = true
static const int digits = HALF_MANT_DIG
static const int digits10 = HALF_DIG
static const bool is_signed = true
static const bool is_integer = false
static const bool is_exact = false
static const int radix = HALF_RADIX
static const int min_exponent = HALF_MIN_EXP
static const int min_exponent10 = HALF_MIN_10_EXP
static const int max_exponent = HALF_MAX_EXP
static const int max_exponent10 = HALF_MAX_10_EXP
static const bool has_infinity = true
static const bool has_quiet_NaN = true
static const bool has_signaling_NaN = true
static const float_denorm_style has_denorm = denorm_present
static const bool has_denorm_loss = false
static const bool is_iec559 = false
static const bool is_bounded = false
static const bool is_modulo = false
static const bool traps = true
static const bool tinyness_before = false
static const float_round_style round_style = round_to_nearest
Detailed Description
Definition at line 57 of file halfLimits.h.
Member Function Documentation
denorm_min()
static half std::numeric_limits< half >::denorm_min () throw () inline static
Definition at line 88 of file halfLimits.h.
References HALF_MIN.
epsilon()
static half std::numeric_limits< half >::epsilon () throw () inline static
Definition at line 72 of file halfLimits.h.
References HALF_EPSILON.
infinity()
static half std::numeric_limits< half >::infinity () throw () inline static
Definition at line 85 of file halfLimits.h.
References half::posInf().
max()
static half std::numeric_limits< half >::max () throw () inline static
Definition at line 64 of file halfLimits.h.
References HALF_MAX.
min()
static half std::numeric_limits< half >::min () throw () inline static
Definition at line 63 of file halfLimits.h.
References HALF_NRM_MIN.
quiet_NaN()
static half std::numeric_limits< half >::quiet_NaN () throw () inline static
Definition at line 86 of file halfLimits.h.
References half::qNan().
round_error()
static half std::numeric_limits< half >::round_error () throw () inline static
Definition at line 73 of file halfLimits.h.
References HALF_EPSILON.
signaling_NaN()
static half std::numeric_limits< half >::signaling_NaN () throw () inline static
Definition at line 87 of file halfLimits.h.
References half::sNan().
Member Data Documentation
digits
const int std::numeric_limits< half >::digits = HALF_MANT_DIG static
Definition at line 66 of file halfLimits.h.
digits10
const int std::numeric_limits< half >::digits10 = HALF_DIG static
Definition at line 67 of file halfLimits.h.
has_denorm
const float_denorm_style std::numeric_limits< half >::has_denorm = denorm_present static
Definition at line 83 of file halfLimits.h.
has_denorm_loss
const bool std::numeric_limits< half >::has_denorm_loss = false static
Definition at line 84 of file halfLimits.h.
has_infinity
const bool std::numeric_limits< half >::has_infinity = true static
Definition at line 80 of file halfLimits.h.
has_quiet_NaN
const bool std::numeric_limits< half >::has_quiet_NaN = true static
Definition at line 81 of file halfLimits.h.
has_signaling_NaN
const bool std::numeric_limits< half >::has_signaling_NaN = true static
Definition at line 82 of file halfLimits.h.
is_bounded
const bool std::numeric_limits< half >::is_bounded = false static
Definition at line 91 of file halfLimits.h.
is_exact
const bool std::numeric_limits< half >::is_exact = false static
Definition at line 70 of file halfLimits.h.
is_iec559
const bool std::numeric_limits< half >::is_iec559 = false static
Definition at line 90 of file halfLimits.h.
is_integer
const bool std::numeric_limits< half >::is_integer = false static
Definition at line 69 of file halfLimits.h.
is_modulo
const bool std::numeric_limits< half >::is_modulo = false static
Definition at line 92 of file halfLimits.h.
is_signed
const bool std::numeric_limits< half >::is_signed = true static
Definition at line 68 of file halfLimits.h.
is_specialized
const bool std::numeric_limits< half >::is_specialized = true static
Definition at line 61 of file halfLimits.h.
max_exponent
const int std::numeric_limits< half >::max_exponent = HALF_MAX_EXP static
Definition at line 77 of file halfLimits.h.
max_exponent10
const int std::numeric_limits< half >::max_exponent10 = HALF_MAX_10_EXP static
Definition at line 78 of file halfLimits.h.
min_exponent
const int std::numeric_limits< half >::min_exponent = HALF_MIN_EXP static
Definition at line 75 of file halfLimits.h.
min_exponent10
const int std::numeric_limits< half >::min_exponent10 = HALF_MIN_10_EXP static
Definition at line 76 of file halfLimits.h.
radix
const int std::numeric_limits< half >::radix = HALF_RADIX static
Definition at line 71 of file halfLimits.h.
round_style
const float_round_style std::numeric_limits< half >::round_style = round_to_nearest static
Definition at line 96 of file halfLimits.h.
tinyness_before
const bool std::numeric_limits< half >::tinyness_before = false static
Definition at line 95 of file halfLimits.h.
traps
const bool std::numeric_limits< half >::traps = true static
Definition at line 94 of file halfLimits.h.
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Half/halfLimits.h