E1039 Software: PHEveDisplay Class Reference
PHEveDisplay Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/Display/display/PHEveDisplay.h>
Classes
class MappedField
Public Member Functions
PHEveDisplay (int w, int h, bool use_fieldmap, bool use_goefile, const std::string &mapname, const std::string &filename, int verb)
~PHEveDisplay ()
void load_geometry (PHCompositeNode *topNode, TEveManager *geve)
void add_elements (TEveManager *geve)
void config_bfields (const PHField *field)
void go_fullscreen (TEveManager *geve)
void set_eve_manager (TEveManager *geve)
Set a pointer to the underlying TEveManager.
TEveManager * get_eve_manager () const
Return a pointer to the underlying TEveManager.
TEveTrackPropagator * get_cnt_prop () const
TEveElementList * get_top_list () const
TEveElementList * get_dc_list () const
TEveElementList * get_hodo_list () const
TEveElementList * get_prop_list () const
TEveElementList * get_true_list () const
void set_jet_pt_threshold (float pt)
float get_jet_pt_threshold () const
void set_jet_e_scale (float e_scale)
float get_jet_e_scale () const
void set_calo_e_threshold (float e)
float get_calo_e_threshold () const
int get_verbosity () const
void set_verbosity (const int a)
Protected Attributes
TEveManager * _eve_manager
TEveElementList * _top_list
TEveElementList * _dc_list
TEveElementList * _hodo_list
TEveElementList * _prop_list
TEveElementList * _true_list
TEveTrackPropagator * cnt_prop
MappedField * mapped_field
int _width
int _height
bool _use_fieldmap
bool _use_geofile
float _jet_pt_threshold
float _jet_e_scale
float _calo_e_threshold
std::string map_filename
std::string geo_filename
int verbosity
Detailed Description
Definition at line 21 of file PHEveDisplay.h.
Constructor & Destructor Documentation
PHEveDisplay()
PHEveDisplay::PHEveDisplay (int w, int h, bool use_fieldmap, bool use_goefile, const std::string & mapname, const std::string & filename, int verb)
Definition at line 51 of file PHEveDisplay.cxx.
References Fun4AllServer::instance(), Fun4AllServer::Print(), and verbosity.
~PHEveDisplay()
PHEveDisplay::~PHEveDisplay ()
Definition at line 83 of file PHEveDisplay.cxx.
Member Function Documentation
add_elements()
void PHEveDisplay::add_elements (TEveManager * geve)
Definition at line 146 of file PHEveDisplay.cxx.
References _dc_list, _hodo_list, _prop_list, _top_list, and _true_list.
Referenced by PHEventDisplay::InitRun().
config_bfields()
void PHEveDisplay::config_bfields (const PHField * field)
Definition at line 163 of file PHEveDisplay.cxx.
References _use_fieldmap, cnt_prop, and verbosity.
Referenced by PHEventDisplay::InitRun().
get_calo_e_threshold()
float PHEveDisplay::get_calo_e_threshold () const inline
Definition at line 67 of file PHEveDisplay.h.
References _calo_e_threshold.
get_cnt_prop()
TEveTrackPropagator* PHEveDisplay::get_cnt_prop () const inline
Definition at line 55 of file PHEveDisplay.h.
References cnt_prop.
Referenced by mTrkEveDisplay::mTrkEveDisplay().
get_dc_list()
TEveElementList* PHEveDisplay::get_dc_list () const inline
Definition at line 57 of file PHEveDisplay.h.
References _dc_list.
Referenced by mTrkEveDisplay::mTrkEveDisplay().
get_eve_manager()
TEveManager* PHEveDisplay::get_eve_manager () const inline
Return a pointer to the underlying TEveManager.
Definition at line 54 of file PHEveDisplay.h.
References _eve_manager.
Referenced by mTrkEveDisplay::mTrkEveDisplay().
get_hodo_list()
TEveElementList* PHEveDisplay::get_hodo_list () const inline
Definition at line 58 of file PHEveDisplay.h.
References _hodo_list.
Referenced by PHEventDisplay::draw_default(), and mTrkEveDisplay::mTrkEveDisplay().
get_jet_e_scale()
float PHEveDisplay::get_jet_e_scale () const inline
Definition at line 65 of file PHEveDisplay.h.
References _jet_e_scale.
get_jet_pt_threshold()
float PHEveDisplay::get_jet_pt_threshold () const inline
Definition at line 63 of file PHEveDisplay.h.
References _jet_pt_threshold.
get_prop_list()
TEveElementList* PHEveDisplay::get_prop_list () const inline
Definition at line 59 of file PHEveDisplay.h.
References _prop_list.
Referenced by mTrkEveDisplay::mTrkEveDisplay().
get_top_list()
TEveElementList* PHEveDisplay::get_top_list () const inline
Definition at line 56 of file PHEveDisplay.h.
References _top_list.
Referenced by PHEventDisplay::draw_default(), and mTrkEveDisplay::mTrkEveDisplay().
get_true_list()
TEveElementList* PHEveDisplay::get_true_list () const inline
Definition at line 60 of file PHEveDisplay.h.
References _true_list.
get_verbosity()
int PHEveDisplay::get_verbosity () const inline
Definition at line 68 of file PHEveDisplay.h.
References verbosity.
Referenced by mTrkEveDisplay::mTrkEveDisplay().
go_fullscreen()
void PHEveDisplay::go_fullscreen (TEveManager * geve)
Definition at line 181 of file PHEveDisplay.cxx.
References _height, and _width.
Referenced by PHEventDisplay::go_fullscreen().
load_geometry()
void PHEveDisplay::load_geometry (PHCompositeNode * topNode, TEveManager * geve)
Definition at line 93 of file PHEveDisplay.cxx.
References _use_geofile, geo_filename, PHGeomUtility::GetTGeoManager(), and verbosity.
Referenced by PHEventDisplay::InitRun().
set_calo_e_threshold()
void PHEveDisplay::set_calo_e_threshold (float e) inline
Definition at line 66 of file PHEveDisplay.h.
References _calo_e_threshold.
Referenced by PHEventDisplay::Init().
set_eve_manager()
void PHEveDisplay::set_eve_manager (TEveManager * geve) inline
Set a pointer to the underlying TEveManager.
Definition at line 52 of file PHEveDisplay.h.
References _eve_manager.
Referenced by PHEventDisplay::PHEventDisplay().
set_jet_e_scale()
void PHEveDisplay::set_jet_e_scale (float e_scale) inline
Definition at line 64 of file PHEveDisplay.h.
References _jet_e_scale.
Referenced by PHEventDisplay::Init().
set_jet_pt_threshold()
void PHEveDisplay::set_jet_pt_threshold (float pt) inline
Definition at line 62 of file PHEveDisplay.h.
References _jet_pt_threshold.
Referenced by PHEventDisplay::Init().
set_verbosity()
void PHEveDisplay::set_verbosity (const int a) inline
Definition at line 69 of file PHEveDisplay.h.
References verbosity.
Referenced by PHEventDisplay::InitRun().
Member Data Documentation
_calo_e_threshold
float PHEveDisplay::_calo_e_threshold protected
Definition at line 89 of file PHEveDisplay.h.
Referenced by get_calo_e_threshold(), and set_calo_e_threshold().
_dc_list
TEveElementList* PHEveDisplay::_dc_list protected
Definition at line 75 of file PHEveDisplay.h.
Referenced by add_elements(), and get_dc_list().
_eve_manager
TEveManager* PHEveDisplay::_eve_manager protected
Definition at line 73 of file PHEveDisplay.h.
Referenced by get_eve_manager(), and set_eve_manager().
_height
int PHEveDisplay::_height protected
Definition at line 84 of file PHEveDisplay.h.
Referenced by go_fullscreen().
_hodo_list
TEveElementList* PHEveDisplay::_hodo_list protected
Definition at line 76 of file PHEveDisplay.h.
Referenced by add_elements(), and get_hodo_list().
_jet_e_scale
float PHEveDisplay::_jet_e_scale protected
Definition at line 88 of file PHEveDisplay.h.
Referenced by get_jet_e_scale(), and set_jet_e_scale().
_jet_pt_threshold
float PHEveDisplay::_jet_pt_threshold protected
Definition at line 87 of file PHEveDisplay.h.
Referenced by get_jet_pt_threshold(), and set_jet_pt_threshold().
_prop_list
TEveElementList* PHEveDisplay::_prop_list protected
Definition at line 77 of file PHEveDisplay.h.
Referenced by add_elements(), and get_prop_list().
_top_list
TEveElementList* PHEveDisplay::_top_list protected
Definition at line 74 of file PHEveDisplay.h.
Referenced by add_elements(), and get_top_list().
_true_list
TEveElementList* PHEveDisplay::_true_list protected
Definition at line 78 of file PHEveDisplay.h.
Referenced by add_elements(), and get_true_list().
_use_fieldmap
bool PHEveDisplay::_use_fieldmap protected
Definition at line 85 of file PHEveDisplay.h.
Referenced by config_bfields().
_use_geofile
bool PHEveDisplay::_use_geofile protected
Definition at line 86 of file PHEveDisplay.h.
Referenced by load_geometry().
_width
int PHEveDisplay::_width protected
Definition at line 84 of file PHEveDisplay.h.
Referenced by go_fullscreen().
cnt_prop
TEveTrackPropagator* PHEveDisplay::cnt_prop protected
Definition at line 80 of file PHEveDisplay.h.
Referenced by config_bfields(), and get_cnt_prop().
geo_filename
std::string PHEveDisplay::geo_filename protected
Definition at line 92 of file PHEveDisplay.h.
Referenced by load_geometry().
map_filename
std::string PHEveDisplay::map_filename protected
Definition at line 91 of file PHEveDisplay.h.
mapped_field
MappedField* PHEveDisplay::mapped_field protected
Definition at line 81 of file PHEveDisplay.h.
verbosity
int PHEveDisplay::verbosity protected
Definition at line 94 of file PHEveDisplay.h.
Referenced by config_bfields(), get_verbosity(), load_geometry(), PHEveDisplay(), and set_verbosity().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/Display/display/PHEveDisplay.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/Display/display/PHEveDisplay.cxx