E1039 Software: PHParameterInterface Class Reference
PHParameterInterface Class Reference abstract
#include </home/yuhw/GitHub/SeaQuest/e1039-core/database/PHParameter/PHParameterInterface.h>
Public Member Functions
PHParameterInterface (const std::string &name)
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
virtual void SetDefaultParameters ()=0
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
Protected Member Functions
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Private Attributes
PHParameters * params
std::map< const std::string, double > dparams
std::map< const std::string, int > iparams
std::map< const std::string, std::string > cparams
std::map< const std::string, double > default_double
std::map< const std::string, int > default_int
std::map< const std::string, std::string > default_string
Detailed Description
Definition at line 10 of file PHParameterInterface.h.
Constructor & Destructor Documentation
PHParameterInterface()
PHParameterInterface::PHParameterInterface (const std::string & name)
Definition at line 11 of file PHParameterInterface.cc.
~PHParameterInterface()
virtual PHParameterInterface::~PHParameterInterface () inline virtual
Definition at line 14 of file PHParameterInterface.h.
References get_double_param(), get_int_param(), get_string_param(), InitializeParameters(), PutOnParNode(), SaveToNodeTree(), set_default_double_param(), set_default_int_param(), set_default_string_param(), set_double_param(), set_int_param(), set_paramname(), set_string_param(), SetDefaultParameters(), and UpdateParametersWithMacro().
Member Function Documentation
get_double_param()
double PHParameterInterface::get_double_param (const std::string & name) const
Definition at line 85 of file PHParameterInterface.cc.
References PHParameters::get_double_param(), and params.
Referenced by ~PHParameterInterface().
get_int_param()
int PHParameterInterface::get_int_param (const std::string & name) const
Definition at line 107 of file PHParameterInterface.cc.
References PHParameters::get_int_param(), and params.
Referenced by ~PHParameterInterface().
get_string_param()
string PHParameterInterface::get_string_param (const std::string & name) const
Definition at line 129 of file PHParameterInterface.cc.
References PHParameters::get_string_param(), and params.
Referenced by ~PHParameterInterface().
InitializeParameters()
void PHParameterInterface::InitializeParameters () protected
Definition at line 166 of file PHParameterInterface.cc.
References default_double, default_int, default_string, params, PHParameters::set_double_param(), PHParameters::set_int_param(), PHParameters::set_string_param(), and SetDefaultParameters().
Referenced by ~PHParameterInterface().
PutOnParNode()
void PHParameterInterface::PutOnParNode (PHCompositeNode * parNode, const std::string & nodename)
Definition at line 160 of file PHParameterInterface.cc.
References PHCompositeNode::addNode(), and params.
Referenced by ~PHParameterInterface().
SaveToNodeTree()
void PHParameterInterface::SaveToNodeTree (PHCompositeNode * runNode, const std::string & nodename)
Definition at line 153 of file PHParameterInterface.cc.
References params, and PHParameters::SaveToNodeTree().
Referenced by ~PHParameterInterface().
set_default_double_param()
void PHParameterInterface::set_default_double_param (const std::string & name, const double dval) protected
Definition at line 22 of file PHParameterInterface.cc.
References default_double.
Referenced by ~PHParameterInterface().
set_default_int_param()
void PHParameterInterface::set_default_int_param (const std::string & name, const int ival) protected
Definition at line 38 of file PHParameterInterface.cc.
References default_int.
Referenced by ~PHParameterInterface().
set_default_string_param()
void PHParameterInterface::set_default_string_param (const std::string & name, const std::string & sval) protected
Definition at line 54 of file PHParameterInterface.cc.
References default_string.
Referenced by ~PHParameterInterface().
set_double_param()
void PHParameterInterface::set_double_param (const std::string & name, const double dval)
Definition at line 69 of file PHParameterInterface.cc.
References default_double, and dparams.
Referenced by ~PHParameterInterface().
set_int_param()
void PHParameterInterface::set_int_param (const std::string & name, const int ival)
Definition at line 91 of file PHParameterInterface.cc.
References default_int, and iparams.
Referenced by ~PHParameterInterface().
set_paramname()
void PHParameterInterface::set_paramname (const std::string & name)
Definition at line 16 of file PHParameterInterface.cc.
References params, and PHParameters::set_name().
Referenced by ~PHParameterInterface().
set_string_param()
void PHParameterInterface::set_string_param (const std::string & name, const std::string & sval)
Definition at line 113 of file PHParameterInterface.cc.
References cparams, and default_string.
Referenced by ~PHParameterInterface().
SetDefaultParameters()
virtual void PHParameterInterface::SetDefaultParameters () pure virtual
Referenced by InitializeParameters(), and ~PHParameterInterface().
UpdateParametersWithMacro()
void PHParameterInterface::UpdateParametersWithMacro ()
Definition at line 135 of file PHParameterInterface.cc.
References cparams, dparams, iparams, params, PHParameters::set_double_param(), PHParameters::set_int_param(), and PHParameters::set_string_param().
Referenced by ~PHParameterInterface().
Member Data Documentation
cparams
std::map<const std::string, std::string> PHParameterInterface::cparams private
Definition at line 40 of file PHParameterInterface.h.
Referenced by set_string_param(), and UpdateParametersWithMacro().
default_double
std::map<const std::string, double> PHParameterInterface::default_double private
Definition at line 42 of file PHParameterInterface.h.
Referenced by InitializeParameters(), set_default_double_param(), and set_double_param().
default_int
std::map<const std::string, int> PHParameterInterface::default_int private
Definition at line 43 of file PHParameterInterface.h.
Referenced by InitializeParameters(), set_default_int_param(), and set_int_param().
default_string
std::map<const std::string, std::string> PHParameterInterface::default_string private
Definition at line 44 of file PHParameterInterface.h.
Referenced by InitializeParameters(), set_default_string_param(), and set_string_param().
dparams
std::map<const std::string, double> PHParameterInterface::dparams private
Definition at line 38 of file PHParameterInterface.h.
Referenced by set_double_param(), and UpdateParametersWithMacro().
iparams
std::map<const std::string, int> PHParameterInterface::iparams private
Definition at line 39 of file PHParameterInterface.h.
Referenced by set_int_param(), and UpdateParametersWithMacro().
params
PHParameters* PHParameterInterface::params private
Definition at line 37 of file PHParameterInterface.h.
Referenced by get_double_param(), get_int_param(), get_string_param(), InitializeParameters(), PutOnParNode(), SaveToNodeTree(), set_paramname(), and UpdateParametersWithMacro().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/database/PHParameter/PHParameterInterface.h
/home/yuhw/GitHub/SeaQuest/e1039-core/database/PHParameter/PHParameterInterface.cc