Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/SRawEventChainDev/Fun4SRawEvent.C File Reference
Fun4SRawEvent.C File Reference
#include <TSystem.h>
#include "G4_SensitiveDetectors.C"
#include "G4_Target.C"
Functions
int Fun4SRawEvent (const int nevent=0, const int run=28700)
Function Documentation
int Fun4SRawEvent (const int nevent = 0, const int run = 28700)
Fun4SRawEvent.C: Fun4all macro to run full reconstruction chain from SRawEvent files.
Definition at line 19 of file Fun4SRawEvent.C.
References Fun4AllServer::End(), Fun4AllSRawEventInputManager::fileopen(), JobOptsSvc::init(), recoConsts::instance(), JobOptsSvc::instance(), Fun4AllServer::instance(), GeomSvc::instance(), PatternDBUtil::LooseMode(), JobOptsSvc::m_fMagFile, JobOptsSvc::m_kMagFile, recoConsts::Print(), PHFieldConfig::RegionalConst, Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), se, Fun4AllSRawEventInputManager::set_branch_name(), PHFlag::set_DoubleFlag(), KalmanFastTrackingWrapper::set_DS_level(), KalmanFastTrackingWrapper::set_enable_event_reducer(), PHG4Reco::set_field_map(), KalmanFastTrackingWrapper::set_pattern_db_name(), Fun4AllSRawEventInputManager::set_tree_name(), PHG4Reco::SetPhysicsList(), SetupSensitiveDetectors(), SetupTarget(), PHG4Reco::SetWorldMaterial(), PHG4Reco::SetWorldShape(), PHG4Reco::SetWorldSizeX(), PHG4Reco::SetWorldSizeY(), PHG4Reco::SetWorldSizeZ(), GeomSvc::UseDbSvc(), and Fun4AllBase::Verbosity().