Class Reference for E1039 Core & Analysis Software: AnaDimuonLikeSign Class Reference
AnaDimuonLikeSign Class Reference
An example class to analyze hodoscope hits in E1039 DST file.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/RecoData2024/src/AnaDimuonLikeSign.h>
Public Member Functions
AnaDimuonLikeSign (const std::string &name="AnaDimuonLikeSign", const std::string &label="PP")
virtual ~AnaDimuonLikeSign ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetOutputFileName (const std::string name)
void SetNodePrefix (const std::string name)
std::string GetNodePrefix () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static void AnalyzeTree (TChain *tree, const std::string label)
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
An example class to analyze hodoscope hits in E1039 DST file.
Definition at line 15 of file AnaDimuonLikeSign.h.
Constructor & Destructor Documentation
AnaDimuonLikeSign()
AnaDimuonLikeSign::AnaDimuonLikeSign (const std::string & name = "AnaDimuonLikeSign", const std::string & label = "PP")
Definition at line 24 of file AnaDimuonLikeSign.cc.
~AnaDimuonLikeSign()
AnaDimuonLikeSign::~AnaDimuonLikeSign () virtual
Definition at line 39 of file AnaDimuonLikeSign.cc.
Member Function Documentation
AnalyzeTree()
void AnaDimuonLikeSign::AnalyzeTree (TChain * tree, const std::string label) static
Definition at line 190 of file AnaDimuonLikeSign.cc.
References DimuonData::chisq_dump_neg, DimuonData::chisq_dump_pos, DimuonData::chisq_neg, DimuonData::chisq_pos, DimuonData::chisq_target_neg, DimuonData::chisq_target_pos, DimuonData::chisq_upstream_neg, DimuonData::chisq_upstream_pos, EventData::D1, EventData::D2, EventData::D3m, EventData::D3p, EventData::event_id, EventData::fpga_bits, DimuonData::mom, DimuonData::mom_neg, DimuonData::mom_pos, DimuonData::mom_target, DimuonData::n_hits_neg, DimuonData::n_hits_pos, DimuonData::pos, DimuonData::pos_neg, DimuonData::pos_pos, EventData::run_id, and EventData::spill_id.
End()
int AnaDimuonLikeSign::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 182 of file AnaDimuonLikeSign.cc.
References Fun4AllReturnCodes::EVENT_OK.
GetNodePrefix()
std::string AnaDimuonLikeSign::GetNodePrefix () const inline
Definition at line 41 of file AnaDimuonLikeSign.h.
Init()
int AnaDimuonLikeSign::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 44 of file AnaDimuonLikeSign.cc.
References Fun4AllReturnCodes::ABORTEVENT, and Fun4AllReturnCodes::EVENT_OK.
InitRun()
int AnaDimuonLikeSign::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 55 of file AnaDimuonLikeSign.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, SQRun::get_v1495_id(), UtilTrigger::TrigRoadset::LoadConfig(), and UtilTrigger::TrigRoadset::str().
process_event()
int AnaDimuonLikeSign::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 86 of file AnaDimuonLikeSign.cc.
References SQTrackVector::at(), SQDimuonVector::begin(), SQHitVector::begin(), DimuonData::chisq_dump_neg, DimuonData::chisq_dump_pos, DimuonData::chisq_neg, DimuonData::chisq_pos, DimuonData::chisq_target_neg, DimuonData::chisq_target_pos, DimuonData::chisq_upstream_neg, DimuonData::chisq_upstream_pos, EventData::D1, EventData::D2, EventData::D3m, EventData::D3p, SQDimuonVector::end(), SQHitVector::end(), EventData::event_id, Fun4AllReturnCodes::EVENT_OK, UtilTrigger::TrigRoads::FindRoad(), EventData::fpga_bits, SRecTrack::get_chisq(), SRecTrack::get_chisq_dump(), SRecTrack::get_chsiq_upstream(), SQHit::get_detector_id(), SQEvent::get_event_id(), SRecDimuon::get_mom(), SRecTrack::get_mom_vtx(), SRecTrack::get_num_hits(), SRecDimuon::get_pos(), SRecTrack::get_pos_dump(), SRecTrack::get_pos_target(), SRecTrack::get_pos_vtx(), SQEvent::get_run_id(), SQEvent::get_spill_id(), SRecDimuon::get_track_id_neg(), SRecDimuon::get_track_id_pos(), SQEvent::get_trigger(), SRecTrack::getChisqTarget(), SRecTrack::getTriggerRoad(), SQEvent::MATRIX1, DimuonData::mom, DimuonData::mom_dump, DimuonData::mom_neg, DimuonData::mom_pos, DimuonData::mom_target, DimuonData::n_hits_neg, DimuonData::n_hits_pos, DimuonData::neg_bot, DimuonData::neg_top, UtilTrigger::TrigRoadset::NegBot(), UtilTrigger::TrigRoadset::NegTop(), SQEvent::NIM1, EventData::nim_bits, SRecDimuon::p_neg_dump, SRecDimuon::p_neg_target, SRecDimuon::p_pos_dump, SRecDimuon::p_pos_target, DimuonData::pos, DimuonData::pos_bot, DimuonData::pos_dump_neg, DimuonData::pos_dump_pos, DimuonData::pos_neg, DimuonData::pos_pos, DimuonData::pos_target_neg, DimuonData::pos_target_pos, DimuonData::pos_top, UtilTrigger::TrigRoadset::PosBot(), UtilTrigger::TrigRoadset::PosTop(), DimuonData::road_neg, DimuonData::road_pos, EventData::run_id, and EventData::spill_id.
SetNodePrefix()
void AnaDimuonLikeSign::SetNodePrefix (const std::string name) inline
Definition at line 40 of file AnaDimuonLikeSign.h.
SetOutputFileName()
void AnaDimuonLikeSign::SetOutputFileName (const std::string name) inline
Definition at line 38 of file AnaDimuonLikeSign.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/RecoData2024/src/AnaDimuonLikeSign.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/RecoData2024/src/AnaDimuonLikeSign.cc