Class Reference for E1039 Core & Analysis Software: PHG4CylinderCellGeomContainer Class Reference
PHG4CylinderCellGeomContainer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellGeomContainer.h>
Public Types
typedef std::map< int, PHG4CylinderCellGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator, Iterator > Range
typedef std::pair< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHG4CylinderCellGeomContainer ()
virtual ~PHG4CylinderCellGeomContainer ()
void identify (std::ostream &os=std::cout) const
int AddLayerCellGeom (const int i, PHG4CylinderCellGeom *mygeom)
int AddLayerCellGeom (PHG4CylinderCellGeom *mygeom)
PHG4CylinderCellGeom * GetLayerCellGeom (const int i)
PHG4CylinderCellGeom * GetFirstLayerCellGeom ()
int get_NLayers () const
std::pair< std::map< int, PHG4CylinderCellGeom * >::const_iterator, std::map< int, PHG4CylinderCellGeom * >::const_iterator > get_begin_end () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
std::map< int, PHG4CylinderCellGeom * > layergeoms
Detailed Description
Definition at line 10 of file PHG4CylinderCellGeomContainer.h.
Member Typedef Documentation
ConstIterator
typedef Map::const_iterator PHG4CylinderCellGeomContainer::ConstIterator
Definition at line 15 of file PHG4CylinderCellGeomContainer.h.
ConstRange
typedef std::pair<ConstIterator, ConstIterator> PHG4CylinderCellGeomContainer::ConstRange
Definition at line 17 of file PHG4CylinderCellGeomContainer.h.
Iterator
typedef Map::iterator PHG4CylinderCellGeomContainer::Iterator
Definition at line 14 of file PHG4CylinderCellGeomContainer.h.
Map
typedef std::map<int, PHG4CylinderCellGeom*> PHG4CylinderCellGeomContainer::Map
Definition at line 13 of file PHG4CylinderCellGeomContainer.h.
Range
typedef std::pair<Iterator, Iterator> PHG4CylinderCellGeomContainer::Range
Definition at line 16 of file PHG4CylinderCellGeomContainer.h.
Constructor & Destructor Documentation
PHG4CylinderCellGeomContainer()
PHG4CylinderCellGeomContainer::PHG4CylinderCellGeomContainer ()
Definition at line 7 of file PHG4CylinderCellGeomContainer.cc.
~PHG4CylinderCellGeomContainer()
PHG4CylinderCellGeomContainer::~PHG4CylinderCellGeomContainer () virtual
Definition at line 12 of file PHG4CylinderCellGeomContainer.cc.
Member Function Documentation
AddLayerCellGeom() [1/2]
int PHG4CylinderCellGeomContainer::AddLayerCellGeom (const int i, PHG4CylinderCellGeom * mygeom)
Definition at line 35 of file PHG4CylinderCellGeomContainer.cc.
References PHG4CylinderCellGeom::set_layer().
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
AddLayerCellGeom() [2/2]
int PHG4CylinderCellGeomContainer::AddLayerCellGeom (PHG4CylinderCellGeom * mygeom)
Definition at line 48 of file PHG4CylinderCellGeomContainer.cc.
References PHG4CylinderCellGeom::get_layer().
get_begin_end()
std::pair<std::map<int,PHG4CylinderCellGeom *>::const_iterator, std::map<int,PHG4CylinderCellGeom *>::const_iterator> PHG4CylinderCellGeomContainer::get_begin_end () const inline
Definition at line 29 of file PHG4CylinderCellGeomContainer.h.
References layergeoms.
get_NLayers()
int PHG4CylinderCellGeomContainer::get_NLayers () const inline
Definition at line 28 of file PHG4CylinderCellGeomContainer.h.
References layergeoms.
GetFirstLayerCellGeom()
PHG4CylinderCellGeom * PHG4CylinderCellGeomContainer::GetFirstLayerCellGeom ()
Definition at line 73 of file PHG4CylinderCellGeomContainer.cc.
GetLayerCellGeom()
PHG4CylinderCellGeom * PHG4CylinderCellGeomContainer::GetLayerCellGeom (const int i)
Definition at line 61 of file PHG4CylinderCellGeomContainer.cc.
Referenced by PHG4CylinderCellReco::process_event(), and PHG4CylinderCellTPCReco::process_event().
identify()
void PHG4CylinderCellGeomContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 23 of file PHG4CylinderCellGeomContainer.cc.
Member Data Documentation
layergeoms
std::map<int,PHG4CylinderCellGeom *> PHG4CylinderCellGeomContainer::layergeoms protected
Definition at line 32 of file PHG4CylinderCellGeomContainer.h.
Referenced by get_begin_end(), and get_NLayers().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellGeomContainer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellGeomContainer.cc