Class Reference for E1039 Core & Analysis Software: OnlMonMainDaq Class Reference
OnlMonMainDaq Class Reference
OnlMonMainDaq.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonMainDaq.h>
Public Member Functions
OnlMonMainDaq ()
virtual ~OnlMonMainDaq ()
OnlMonClient * Clone ()
int InitOnlMon (PHCompositeNode *topNode)
int InitRunOnlMon (PHCompositeNode *topNode)
int ProcessEventOnlMon (PHCompositeNode *topNode)
int EndOnlMon (PHCompositeNode *topNode)
int FindAllMonHist ()
int DrawMonitor ()
Public Member Functions inherited from OnlMonClient
OnlMonClient ()
virtual ~OnlMonClient ()
void Title (const std::string &title)
std::string Title ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void GetBasicID (int *run_id=0, int *spill_id=0, int *event_id=0, int *spill_id_min=0, int *spill_id_max=0)
void GetBasicCount (int *n_evt=0, int *n_sp=0)
int StartMonitor ()
TH1 * FindMonHist (const std::string name, const bool non_null=true)
int SendHist (TSocket *sock, int sp_min, int sp_max)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
double EvalAverageOfFilledBins (TH1 *h1) const
Protected Member Functions inherited from OnlMonClient
void RegisterHist (TH1 *h1, const HistMode_t mode=MODE_ADD)
void NumCanvases (const int num)
int NumCanvases ()
OnlMonCanvas * GetCanvas (const int num=0)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Static Public Member Functions inherited from OnlMonClient
static void SetClearUsFlag (const bool val)
static bool GetClearUsFlag ()
Protected Types inherited from OnlMonClient
enum HistMode_t { MODE_ADD , MODE_UPDATE }
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
OnlMonMainDaq.
Definition at line 6 of file OnlMonMainDaq.h.
Constructor & Destructor Documentation
OnlMonMainDaq()
OnlMonMainDaq::OnlMonMainDaq ()
Definition at line 26 of file OnlMonMainDaq.cc.
References Fun4AllBase::Name(), OnlMonClient::NumCanvases(), and OnlMonClient::Title().
Referenced by Clone().
~OnlMonMainDaq()
virtual OnlMonMainDaq::~OnlMonMainDaq () inline virtual
Definition at line 24 of file OnlMonMainDaq.h.
Member Function Documentation
Clone()
OnlMonClient* OnlMonMainDaq::Clone () inline virtual
Reimplemented from OnlMonClient.
Definition at line 25 of file OnlMonMainDaq.h.
References OnlMonMainDaq().
DrawMonitor()
int OnlMonMainDaq::DrawMonitor () virtual
Reimplemented from OnlMonClient.
Definition at line 219 of file OnlMonMainDaq.cc.
References OnlMonCanvas::AddMessage(), UtilHist::AutoSetRange(), OnlMonCanvas::ERROR, EvalAverageOfFilledBins(), UtilHist::FindFilledRange(), OnlMonClient::GetCanvas(), OnlMonParam::GetIntParam(), OnlMonCanvas::GetMainPad(), nChamberPlanes, nDarkPhotonPlanes, nHodoPlanes, nPropPlanes, OnlMonCanvas::OK, OnlMonCanvas::SetStatus(), OnlMonCanvas::SetWorseStatus(), and OnlMonCanvas::WARN.
EndOnlMon()
int OnlMonMainDaq::EndOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 196 of file OnlMonMainDaq.cc.
References Fun4AllReturnCodes::EVENT_OK.
EvalAverageOfFilledBins()
double OnlMonMainDaq::EvalAverageOfFilledBins (TH1 * h1) const protected
Definition at line 469 of file OnlMonMainDaq.cc.
Referenced by DrawMonitor().
FindAllMonHist()
int OnlMonMainDaq::FindAllMonHist () virtual
Reimplemented from OnlMonClient.
Definition at line 201 of file OnlMonMainDaq.cc.
References OnlMonClient::FindMonHist().
InitOnlMon()
int OnlMonMainDaq::InitOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 34 of file OnlMonMainDaq.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRunOnlMon()
int OnlMonMainDaq::InitRunOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 39 of file OnlMonMainDaq.cc.
References Fun4AllReturnCodes::EVENT_OK, GeomSvc::instance(), OnlMonClient::MODE_UPDATE, nChamberPlanes, nDarkPhotonPlanes, nHodoPlanes, nPropPlanes, and OnlMonClient::RegisterHist().
ProcessEventOnlMon()
int OnlMonMainDaq::ProcessEventOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 108 of file OnlMonMainDaq.cc.
References Fun4AllReturnCodes::ABORTEVENT, SQHitVector::begin(), SQHitVector::end(), Fun4AllReturnCodes::EVENT_OK, SQIntMap::get(), SQEvent::get_data_quality(), SQHardEvent::get_flag_v1495(), SQHardEvent::get_n_board_taiwan(), SQRun::get_n_evt_all(), SQRun::get_n_evt_dec(), SQRun::get_n_flush_evt(), SQRun::get_n_flush_evt_bad(), SQRun::get_n_hit(), SQRun::get_n_hit_bad(), SQRun::get_n_phys_evt(), SQRun::get_n_phys_evt_bad(), SQRun::get_n_spill(), SQRun::get_n_t_hit(), SQRun::get_n_t_hit_bad(), SQRun::get_n_v1495(), SQRun::get_n_v1495_d1ad(), SQRun::get_n_v1495_d2ad(), SQRun::get_n_v1495_d3ad(), SQEvent::get_spill_id(), SQHardSpill::get_time_decode(), SQHardSpill::get_time_input(), SQHardSpill::get_time_map(), SQHardSpill::get_time_output(), SQHardSpill::get_time_subsys(), SQEvent::get_trigger(), SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, SQEvent::MATRIX5, nChamberPlanes, nDarkPhotonPlanes, nHodoPlanes, SQEvent::NIM1, SQEvent::NIM2, SQEvent::NIM3, SQEvent::NIM4, SQEvent::NIM5, and nPropPlanes.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonMainDaq.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonMainDaq.cc