Class Reference for E1039 Core & Analysis Software: OnlMonQie Class Reference
OnlMonQie Class Reference
OnlMonQie.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonQie.h>
Public Member Functions
OnlMonQie ()
virtual ~OnlMonQie ()
OnlMonClient * Clone ()
int InitOnlMon (PHCompositeNode *topNode)
int InitRunOnlMon (PHCompositeNode *topNode)
int ProcessEventOnlMon (PHCompositeNode *topNode)
int EndOnlMon (PHCompositeNode *topNode)
int FindAllMonHist ()
int DrawMonitor ()
Public Member Functions inherited from OnlMonClient
OnlMonClient ()
virtual ~OnlMonClient ()
void Title (const std::string &title)
std::string Title ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void GetBasicID (int *run_id=0, int *spill_id=0, int *event_id=0, int *spill_id_min=0, int *spill_id_max=0)
void GetBasicCount (int *n_evt=0, int *n_sp=0)
int StartMonitor ()
TH1 * FindMonHist (const std::string name, const bool non_null=true)
int SendHist (TSocket *sock, int sp_min, int sp_max)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Static Public Member Functions inherited from OnlMonClient
static void SetClearUsFlag (const bool val)
static bool GetClearUsFlag ()
Protected Types inherited from OnlMonClient
enum HistMode_t { MODE_ADD , MODE_UPDATE }
Protected Member Functions inherited from OnlMonClient
void RegisterHist (TH1 *h1, const HistMode_t mode=MODE_ADD)
void NumCanvases (const int num)
int NumCanvases ()
OnlMonCanvas * GetCanvas (const int num=0)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
OnlMonQie.
Definition at line 6 of file OnlMonQie.h.
Constructor & Destructor Documentation
OnlMonQie()
OnlMonQie::OnlMonQie ()
Definition at line 22 of file OnlMonQie.cc.
Referenced by Clone().
~OnlMonQie()
virtual OnlMonQie::~OnlMonQie () inline virtual
Definition at line 27 of file OnlMonQie.h.
Member Function Documentation
Clone()
OnlMonClient* OnlMonQie::Clone () inline virtual
Reimplemented from OnlMonClient.
Definition at line 28 of file OnlMonQie.h.
References OnlMonQie().
DrawMonitor()
int OnlMonQie::DrawMonitor () virtual
Reimplemented from OnlMonClient.
Definition at line 121 of file OnlMonQie.cc.
References OnlMonCanvas::AddMessage(), OnlMonCanvas::GetMainPad(), OnlMonCanvas::SetWorseStatus(), and OnlMonCanvas::WARN.
EndOnlMon()
int OnlMonQie::EndOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 106 of file OnlMonQie.cc.
References Fun4AllReturnCodes::EVENT_OK.
FindAllMonHist()
int OnlMonQie::FindAllMonHist () virtual
Reimplemented from OnlMonClient.
Definition at line 111 of file OnlMonQie.cc.
InitOnlMon()
int OnlMonQie::InitOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 29 of file OnlMonQie.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRunOnlMon()
int OnlMonQie::InitRunOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 34 of file OnlMonQie.cc.
References Fun4AllReturnCodes::EVENT_OK, and UtilBeam::ListOfRfValues().
ProcessEventOnlMon()
int OnlMonQie::ProcessEventOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 63 of file OnlMonQie.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, SQHardEvent::get_n_board_qie(), SQEvent::get_qie_rf_id(), SQEvent::get_qie_rf_intensity(), and SQEvent::get_qie_turn_id().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonQie.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonQie.cc