Class Reference for E1039 Core & Analysis Software: SubsysRecoSignal Class Reference
SubsysRecoSignal Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/SubsysRecoSignal.h>
Public Member Functions
SubsysRecoSignal (const std::string &name="SubsysRecoSignal")
virtual ~SubsysRecoSignal ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 15 of file SubsysRecoSignal.h.
Constructor & Destructor Documentation
SubsysRecoSignal()
SubsysRecoSignal::SubsysRecoSignal (const std::string & name = "SubsysRecoSignal")
Definition at line 17 of file SubsysRecoSignal.cc.
~SubsysRecoSignal()
virtual SubsysRecoSignal::~SubsysRecoSignal () inline virtual
Definition at line 29 of file SubsysRecoSignal.h.
Member Function Documentation
End()
int SubsysRecoSignal::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 83 of file SubsysRecoSignal.cc.
References Fun4AllReturnCodes::EVENT_OK.
Init()
int SubsysRecoSignal::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 23 of file SubsysRecoSignal.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRun()
int SubsysRecoSignal::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 28 of file SubsysRecoSignal.cc.
References Fun4AllReturnCodes::ABORTEVENT, and Fun4AllReturnCodes::EVENT_OK.
process_event()
int SubsysRecoSignal::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 43 of file SubsysRecoSignal.cc.
References SQDimuonVector::at(), UtilDimuon::CalcVar(), SignalData::dz, Fun4AllReturnCodes::EVENT_OK, UtilTrigger::ExtractRoadID(), UtilTrack::FindHodoHitsOfTrack(), UtilTrack::FindTrackByID(), SQDimuon::get_mom(), SQDimuon::get_pos(), SQDimuon::get_track_id_neg(), SQDimuon::get_track_id_pos(), SQMCEvent::get_weight(), SignalData::mass, SignalData::mom, SignalData::phi, SignalData::pT, SignalData::road_neg, SignalData::road_pos, SQDimuonVector::size(), SignalData::theta, SignalData::weight, SignalData::x1, SignalData::x2, and SignalData::xF.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/SubsysRecoSignal.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/SubsysRecoSignal.cc