Class Reference for E1039 Core & Analysis Software: RoadList Class Reference
RoadList Class Reference
Class to hold an ordered set (i.e. vector) of roads.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadList.h>
Public Member Functions
RoadList ()
virtual ~RoadList ()
int Size () const
RoadInfo * Get (int i)
const RoadInfo * Get (int i) const
void Add (RoadInfo *info)
void Add (const RoadMap *road_map)
void SortBySignal ()
void SortByBG ()
void SortByFoM ()
Sort the list by Figure of Merit, i.e. "signal / sqrt(bg)".
Public Member Functions inherited from RoadListBase
virtual ~RoadListBase ()
void SetPNTB (const int pn, const int tb)
void SetPosNeg (const int pn)
void SetTopBot (const int tb)
int GetPosNeg () const
int GetTopBot () const
std::string GetPosNegStr () const
std::string GetTopBotStr () const
void Frozen ()
bool IsFrozen ()
Additional Inherited Members
Protected Member Functions inherited from RoadListBase
RoadListBase ()
Protected Attributes inherited from RoadListBase
int m_pn
int m_tb
bool m_frozen
Detailed Description
Class to hold an ordered set (i.e. vector) of roads.
Definition at line 9 of file RoadList.h.
Constructor & Destructor Documentation
RoadList::RoadList ()
Definition at line 9 of file RoadList.cc.
RoadList::~RoadList () virtual
Definition at line 14 of file RoadList.cc.
Member Function Documentation
void RoadList::Add (RoadInfo * info)
Definition at line 19 of file RoadList.cc.
Referenced by ReAnaBG::Analyze(), and GenRoadset::SetMap().
void RoadList::Add (const RoadMap * road_map)
Definition at line 24 of file RoadList.cc.
References RoadMap::Begin(), and RoadMap::End().
RoadInfo* RoadList::Get (int i) inline
Definition at line 18 of file RoadList.h.
Referenced by GenRoadset::DisableRoadsByFoM(), GenRoadset::DisableRoadsByWeightFraction(), and UtilRoad::PrintList().
const RoadInfo* RoadList::Get (int i) const inline
Definition at line 19 of file RoadList.h.
int RoadList::Size () const inline
Definition at line 17 of file RoadList.h.
Referenced by ReAnaBG::Analyze(), GenRoadset::DisableRoadsByFoM(), GenRoadset::DisableRoadsByWeightFraction(), and UtilRoad::PrintList().
void RoadList::SortByBG ()
Definition at line 36 of file RoadList.cc.
References RoadInfo::GetWeightBG().
Referenced by ReAnaBG::Analyze().
void RoadList::SortByFoM ()
Sort the list by Figure of Merit, i.e. "signal / sqrt(bg)".
Definition at line 44 of file RoadList.cc.
References RoadInfo::GetFoM().
Referenced by GenRoadset::DisableRoadsByFoM().
void RoadList::SortBySignal ()
Definition at line 29 of file RoadList.cc.
References RoadInfo::GetWeight().
Referenced by GenRoadset::DisableRoadsByWeightFraction().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadList.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadList.cc