Class Reference for E1039 Core & Analysis Software: SQHitVector Class Reference
SQHitVector Class Reference abstract
An SQ interface class to hold a list of SQHit objects.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHitVector.h>
Public Types
typedef std::vector< SQHit * > HitVector
typedef std::vector< SQHit * >::const_iterator ConstIter
typedef std::vector< SQHit * >::iterator Iter
Public Member Functions
virtual ~SQHitVector ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()=0
Clear Event.
virtual int isValid () const =0
isValid returns non zero if object contains vailid data
virtual SQHitVector * Clone () const =0
virtual bool empty () const =0
virtual size_t size () const =0
virtual void clear ()=0
virtual const SQHit * at (const size_t idkey) const =0
virtual SQHit * at (const size_t idkey)=0
virtual void push_back (const SQHit *hit)=0
virtual size_t erase (const size_t idkey)=0
virtual Iter erase (Iter pos)=0
virtual ConstIter begin () const =0
virtual ConstIter end () const =0
virtual Iter begin ()=0
virtual Iter end ()=0
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQHitVector ()
Detailed Description
An SQ interface class to hold a list of SQHit objects.
Below is the standard way to find this object in "topNode" and loop over each hit;
SQHitVector* hit_vec = findNode::getClass<SQHitVector>(topNode, "SQHitVector");
for (SQHitVector::ConstIter it = hit_vec->begin(); it != hit_vec->end(); it++) {
  SQHit* hit = *it;
  int det_id = hit->get_detector_id();
}
You can use utility functions defined in UtilSQHit for more complicated manipulations.
Definition at line 32 of file SQHitVector.h.
Member Typedef Documentation
ConstIter
typedef std::vector<SQHit*>::const_iterator SQHitVector::ConstIter
Definition at line 37 of file SQHitVector.h.
HitVector
typedef std::vector<SQHit*> SQHitVector::HitVector
Definition at line 36 of file SQHitVector.h.
Iter
typedef std::vector<SQHit*>::iterator SQHitVector::Iter
Definition at line 38 of file SQHitVector.h.
Constructor & Destructor Documentation
~SQHitVector()
virtual SQHitVector::~SQHitVector () inline virtual
Definition at line 40 of file SQHitVector.h.
SQHitVector()
SQHitVector::SQHitVector () inline protected
Definition at line 66 of file SQHitVector.h.
Member Function Documentation
at() [1/2]
virtual const SQHit* SQHitVector::at (const size_t idkey) const pure virtual
Implemented in SQHitVector_v1.
Referenced by UtilSQHit::FindFirstHits(), SimpleTree::process_event(), DPTriggerAnalyzer::process_event(), TruthNodeMaker::process_event(), UtilSRawEvent::SetHit(), UtilSRawEvent::SetTriggerHit(), SQReco::updateHitInfo(), Fun4AllVectEventOutputManager::Write(), and Fun4AllRUSOutputManager::Write().
at() [2/2]
virtual SQHit* SQHitVector::at (const size_t idkey) pure virtual
Implemented in SQHitVector_v1.
begin() [1/2]
virtual ConstIter SQHitVector::begin () const pure virtual
Implemented in SQHitVector_v1.
Referenced by UtilTrigger::ExtractRoadID(), UtilTrack::FindDetectorHitsOfTrack(), UtilSQHit::FindHits(), UtilSQHit::FindHitsFast(), UtilTrack::FindHitsOfTrack(), UtilSQHit::FindTriggerHitsFast(), CalibHitPos::process_event(), CheckEventData::process_event(), AnaChamHit::process_event(), AnaEmbeddedData::process_event(), DoEmbedding::process_event(), CalibDriftDistMod::process_event(), AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), AnaDimuonV2::process_event(), CalibDriftDist::process_event(), CalibHitElementPos::process_event(), CalibHodoInTime::process_event(), SQChamberRealization::process_event(), and SQGeomAcc::process_event().
begin() [2/2]
virtual Iter SQHitVector::begin () pure virtual
Implemented in SQHitVector_v1.
clear()
virtual void SQHitVector::clear () pure virtual
Implemented in SQHitVector_v1.
Referenced by UtilTrack::FindDetectorHitsOfTrack(), UtilSQHit::FindFirstHits(), UtilSQHit::FindHits(), and UtilTrack::FindHitsOfTrack().
Clone()
virtual SQHitVector* SQHitVector::Clone () const pure virtual
Implemented in SQHitVector_v1.
Referenced by UtilTrack::FindDetectorHitsOfTrack(), UtilSQHit::FindFirstHits(), UtilSQHit::FindHits(), and UtilTrack::FindHitsOfTrack().
empty()
virtual bool SQHitVector::empty () const pure virtual
Implemented in SQHitVector_v1.
end() [1/2]
virtual ConstIter SQHitVector::end () const pure virtual
Implemented in SQHitVector_v1.
Referenced by UtilTrigger::ExtractRoadID(), UtilTrack::FindDetectorHitsOfTrack(), UtilSQHit::FindHits(), UtilSQHit::FindHitsFast(), UtilTrack::FindHitsOfTrack(), UtilSQHit::FindTriggerHitsFast(), CalibHitPos::process_event(), CheckEventData::process_event(), AnaChamHit::process_event(), AnaEmbeddedData::process_event(), DoEmbedding::process_event(), CalibDriftDistMod::process_event(), AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), AnaDimuonV2::process_event(), CalibDriftDist::process_event(), CalibHitElementPos::process_event(), CalibHodoInTime::process_event(), SQChamberRealization::process_event(), and SQGeomAcc::process_event().
end() [2/2]
virtual Iter SQHitVector::end () pure virtual
Implemented in SQHitVector_v1.
erase() [1/2]
virtual size_t SQHitVector::erase (const size_t idkey) pure virtual
Implemented in SQHitVector_v1.
Referenced by CalibDriftDist::process_event(), CalibHodoInTime::process_event(), and SQChamberRealization::process_event().
erase() [2/2]
virtual Iter SQHitVector::erase (Iter pos) pure virtual
Implemented in SQHitVector_v1.
identify()
virtual void SQHitVector::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SQHitVector_v1.
Definition at line 42 of file SQHitVector.h.
isValid()
virtual int SQHitVector::isValid () const pure virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Implemented in SQHitVector_v1.
push_back()
virtual void SQHitVector::push_back (const SQHit * hit) pure virtual
Implemented in SQHitVector_v1.
Referenced by SQDigitizer::digitizeEMCal(), SQDigitizer::digitizePlane(), Fun4AllSRawEventInputManager::E906ToE1039(), UtilTrack::FindDetectorHitsOfTrack(), UtilSQHit::FindFirstHits(), UtilSQHit::FindHits(), UtilTrack::FindHitsOfTrack(), DoEmbedding::process_event(), RndmEmbed::process_event(), SRawEventEmbed::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), Fun4AllEVIOInputManager::run(), Fun4AllVectEventInputManager::VectToE1039(), and Fun4AllRUSInputManager::VectToE1039().
Reset()
virtual void SQHitVector::Reset () pure virtual
Clear Event.
Reimplemented from PHObject.
Implemented in SQHitVector_v1.
size()
virtual size_t SQHitVector::size () const pure virtual
Implemented in SQHitVector_v1.
Referenced by SQDigitizer::digitizeEMCal(), SQDigitizer::digitizePlane(), UtilSQHit::FindFirstHits(), CheckEventData::process_event(), DoEmbedding::process_event(), SimpleTree::process_event(), DPTriggerAnalyzer::process_event(), RndmEmbed::process_event(), SRawEventEmbed::process_event(), SQChamberRealization::process_event(), TruthNodeMaker::process_event(), UtilSRawEvent::SetHit(), UtilSRawEvent::SetTriggerHit(), Fun4AllVectEventOutputManager::Write(), and Fun4AllRUSOutputManager::Write().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHitVector.h