SeaQuest Offline Software: GridUtil Namespace Reference
GridUtil Namespace Reference
Classes
class JobConfig
Functions
def getNEvents
def getOptimizedSize
def getSubDir
def getJobAttr
def gridInit
def ticketValid
def gridGuard
def startGridGuard
def stopGridGuard
def makeCommand
def makeCommandFromOpts
def submitOneJob
def submitAllJobs
def getJobStatus
def runCommand
def getTimeStamp
def mergeFiles
Variables
tuple workDir = os.getenv('HOME')
tuple version = os.getenv("SEAQUEST_RELEASE")
tuple submissionLog = os.path.join(workDir, 'log')
tuple stopGrid = threading.Event()
dictionary inputPrefix = {'track' : 'digit', 'vertex' : 'track'}
dictionary auxPrefix = {'track' : 'track_from_digit', 'vertex' : 'vertex_from_track'}
Function Documentation
def GridUtil.getJobAttr (optfile)
Parse the name and content of job option file to get the basic information
Definition at line 106 of file GridUtil.py.
Referenced by makeCommandFromOpts().
def GridUtil.getJobStatus (conf, jobType, runID)
Get the status of all jobs associated with one runID
Definition at line 245 of file GridUtil.py.
References getSubDir().
def GridUtil.getNEvents (name)
Find the number of events in either ROOT file or MySQL schema
Definition at line 62 of file GridUtil.py.
Referenced by getOptimizedSize().
def GridUtil.getOptimizedSize (name, nEvtMax, nJobsMax = 10, nEvents_default = -1)
Optimize how a run is splitted into serveral jobs
Definition at line 78 of file GridUtil.py.
References getNEvents().
def GridUtil.getSubDir (runID)
Return the sub-director name by runID
Definition at line 100 of file GridUtil.py.
Referenced by getJobStatus().
def GridUtil.getTimeStamp ()
Definition at line 286 of file GridUtil.py.
def GridUtil.gridGuard ()
Renew the grid credetial every hour
Definition at line 143 of file GridUtil.py.
def GridUtil.gridInit ()
Initialize grid credential
Definition at line 131 of file GridUtil.py.
References startGridGuard(), and ticketValid().
def GridUtil.makeCommand (jobType, runID, conf, firstEvent = -1, nEvents = -1, outtag = '', infile = '')
Make a runKTracker.py command according to the configurations
Definition at line 164 of file GridUtil.py.
def GridUtil.makeCommandFromOpts (jobType, opts, conf)
Make a runKTracker command using configuration and opts file
Definition at line 184 of file GridUtil.py.
References getJobAttr().
def GridUtil.mergeFiles (targetFile, sourceFiles, ignoreCorrupted = False)
use hadd to merge ROOT files
Definition at line 289 of file GridUtil.py.
def GridUtil.runCommand (cmd)
Run a bash command and check if there is any stderr output, if not return True, otherwise return False
Definition at line 278 of file GridUtil.py.
def GridUtil.startGridGuard ()
Start a new thread used to refresh the gridGuard
Definition at line 155 of file GridUtil.py.
Referenced by gridInit().
def GridUtil.stopGridGuard ()
Stop the thread before exiting
Definition at line 160 of file GridUtil.py.
def GridUtil.submitAllJobs (cmds, maxFailCounts = 10)
Submit all jobs, retry the failed ones, and save the jobs in errlog when a jobs failed more than once
Definition at line 209 of file GridUtil.py.
References submitOneJob().
def GridUtil.submitOneJob (cmd)
Actually submit the jobs and parse the return info to see if it's successful
Definition at line 197 of file GridUtil.py.
Referenced by submitAllJobs().
def GridUtil.ticketValid ()
Check if the ticket is still valid
Definition at line 139 of file GridUtil.py.
Referenced by gridInit().
Variable Documentation
dictionary GridUtil.auxPrefix = {'track' : 'track_from_digit', 'vertex' : 'vertex_from_track'}
Definition at line 19 of file GridUtil.py.
dictionary GridUtil.inputPrefix = {'track' : 'digit', 'vertex' : 'track'}
Definition at line 18 of file GridUtil.py.
tuple GridUtil.stopGrid = threading.Event()
Definition at line 16 of file GridUtil.py.
tuple GridUtil.submissionLog = os.path.join(workDir, 'log')
Definition at line 15 of file GridUtil.py.
tuple GridUtil.version = os.getenv("SEAQUEST_RELEASE")
Definition at line 14 of file GridUtil.py.
Referenced by PHTimeServer.insert_new(), and PHTimeServer.insert_new_single_shot().
tuple GridUtil.workDir = os.getenv('HOME')
Definition at line 13 of file GridUtil.py.