SeaQuest Offline Software: PHG4mRICHDetector Class Reference
PHG4mRICHDetector Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4mRICHDetector.h>
Classes
class BoxPar
class LensPar
class mRichParameter
class PolyPar
Public Member Functions
PHG4mRICHDetector (PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam="BLOCK", const int lyr=0)
constructor
virtual ~PHG4mRICHDetector (void)
destructor
virtual void Construct (G4LogicalVolume *world)
construct
bool IsInmRICH (G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Private Member Functions
G4VPhysicalVolume * build_box (BoxPar *par, G4LogicalVolume *motherLV)
G4VPhysicalVolume * build_polyhedra (PolyPar *par, G4LogicalVolume *motherLV)
G4LogicalVolume * build_Space (G4LogicalVolume *logicWorld, G4double(&bowlPar)[4])
G4LogicalVolume * Construct_a_mRICH (G4LogicalVolume *logicWorld)
G4VPhysicalVolume * build_holderBox (mRichParameter *detectorParameter, G4LogicalVolume *motherLV)
void build_foamHolder (mRichParameter *detectorParameter, G4LogicalVolume *motherLV)
void build_aerogel (mRichParameter *detectorParameter, G4VPhysicalVolume *motherPV)
void build_lens (LensPar *par, G4LogicalVolume *motherLV)
void build_mirror (mRichParameter *detectorParameter, G4VPhysicalVolume *motherPV)
void build_sensor (mRichParameter *detectorParameter, G4LogicalVolume *motherLV)
void build_mRICH_wall (G4LogicalVolume *space, G4LogicalVolume *a_mRICH, G4double *bowlPar)
G4double eta2polarAngle (G4double eta)
Private Attributes
PHParameters * params
int layer
std::string superdetector
std::set< G4VPhysicalVolume * > active_volumes
std::set< G4VPhysicalVolume * > passive_volumes
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 21 of file PHG4mRICHDetector.h.
Constructor & Destructor Documentation
PHG4mRICHDetector::PHG4mRICHDetector (PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam = "BLOCK", const int lyr = 0)
constructor
Definition at line 57 of file PHG4mRICHDetector.cc.
virtual PHG4mRICHDetector::~PHG4mRICHDetector (void) inline virtual
destructor
Definition at line 30 of file PHG4mRICHDetector.h.
Member Function Documentation
void PHG4mRICHDetector::build_aerogel (mRichParameter * detectorParameter, G4VPhysicalVolume * motherPV) private
Definition at line 592 of file PHG4mRICHDetector.cc.
References build_box(), and PHG4mRICHDetector::mRichParameter::GetBoxPar().
Referenced by Construct_a_mRICH().
G4VPhysicalVolume * PHG4mRICHDetector::build_box (BoxPar * par, G4LogicalVolume * motherLV) private
Definition at line 549 of file PHG4mRICHDetector.cc.
References PHG4mRICHDetector::BoxPar::color, PHG4mRICHDetector::BoxPar::halfXYZ, PHG4mRICHDetector::BoxPar::material, PHG4mRICHDetector::BoxPar::name, PHG4mRICHDetector::BoxPar::pos, PHG4mRICHDetector::BoxPar::surface, PHG4mRICHDetector::BoxPar::visibility, and PHG4mRICHDetector::BoxPar::wireframe.
Referenced by build_aerogel(), build_foamHolder(), build_holderBox(), and build_sensor().
void PHG4mRICHDetector::build_foamHolder (mRichParameter * detectorParameter, G4LogicalVolume * motherLV) private
Definition at line 586 of file PHG4mRICHDetector.cc.
References build_box(), build_polyhedra(), PHG4mRICHDetector::mRichParameter::GetBoxPar(), PHG4mRICHDetector::mRichParameter::GetPolyPar(), and passive_volumes.
Referenced by Construct_a_mRICH().
G4VPhysicalVolume * PHG4mRICHDetector::build_holderBox (mRichParameter * detectorParameter, G4LogicalVolume * motherLV) private
Definition at line 580 of file PHG4mRICHDetector.cc.
References build_box(), and PHG4mRICHDetector::mRichParameter::GetBoxPar().
Referenced by Construct_a_mRICH().
void PHG4mRICHDetector::build_lens (LensPar * par, G4LogicalVolume * motherLV) private
Definition at line 676 of file PHG4mRICHDetector.cc.
References PHG4mRICHDetector::LensPar::centerThickness, PHG4mRICHDetector::LensPar::diameter, PHG4mRICHDetector::LensPar::eff_diameter, PHG4mRICHDetector::LensPar::GetSagita(), PHG4mRICHDetector::LensPar::grooveWidth, PHG4mRICHDetector::LensPar::halfXYZ, PHG4mRICHDetector::LensPar::material, PHG4mRICHDetector::LensPar::name, and PHG4mRICHDetector::LensPar::pos.
Referenced by Construct_a_mRICH().
void PHG4mRICHDetector::build_mirror (mRichParameter * detectorParameter, G4VPhysicalVolume * motherPV) private
Definition at line 619 of file PHG4mRICHDetector.cc.
References build_polyhedra(), c_light, and PHG4mRICHDetector::mRichParameter::GetPolyPar().
Referenced by Construct_a_mRICH().
void PHG4mRICHDetector::build_mRICH_wall (G4LogicalVolume * space, G4LogicalVolume * a_mRICH, G4double * bowlPar) private
Definition at line 817 of file PHG4mRICHDetector.cc.
References PHG4Detector::name.
Referenced by Construct().
G4VPhysicalVolume * PHG4mRICHDetector::build_polyhedra (PolyPar * par, G4LogicalVolume * motherLV) private
Definition at line 564 of file PHG4mRICHDetector.cc.
References PHG4mRICHDetector::PolyPar::color, PHG4mRICHDetector::PolyPar::material, PHG4mRICHDetector::PolyPar::name, PHG4mRICHDetector::PolyPar::num_zLayer, PHG4mRICHDetector::PolyPar::numSide, PHG4mRICHDetector::PolyPar::pos, PHG4mRICHDetector::PolyPar::rinner, PHG4mRICHDetector::PolyPar::router, PHG4mRICHDetector::PolyPar::start, PHG4mRICHDetector::PolyPar::surface, PHG4mRICHDetector::PolyPar::theta, PHG4mRICHDetector::PolyPar::visibility, PHG4mRICHDetector::PolyPar::wireframe, and PHG4mRICHDetector::PolyPar::z.
Referenced by build_foamHolder(), build_mirror(), and Construct_a_mRICH().
void PHG4mRICHDetector::build_sensor (mRichParameter * detectorParameter, G4LogicalVolume * motherLV) private
Definition at line 646 of file PHG4mRICHDetector.cc.
References active_volumes, build_box(), PHG4mRICHDetector::mRichParameter::GetBoxPar(), passive_volumes, PHG4mRICHDetector::BoxPar::pos, PHG4mRICHDetector::mRichParameter::SetPar_glassWindow(), and PHG4mRICHDetector::mRichParameter::SetPar_sensor().
Referenced by Construct_a_mRICH().
G4LogicalVolume * PHG4mRICHDetector::build_Space (G4LogicalVolume * logicWorld, G4double(&) bowlPar[4]) private
Definition at line 755 of file PHG4mRICHDetector.cc.
References eta2polarAngle().
Referenced by Construct().
void PHG4mRICHDetector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 74 of file PHG4mRICHDetector.cc.
References build_mRICH_wall(), build_Space(), Construct_a_mRICH(), PHParameters::get_int_param(), and params.
G4LogicalVolume * PHG4mRICHDetector::Construct_a_mRICH (G4LogicalVolume * logicWorld) private
Definition at line 88 of file PHG4mRICHDetector.cc.
References build_aerogel(), build_foamHolder(), build_holderBox(), build_lens(), build_mirror(), build_polyhedra(), build_sensor(), PHG4mRICHDetector::mRichParameter::GetLensPar(), PHG4mRICHDetector::mRichParameter::GetPolyPar(), and passive_volumes.
Referenced by Construct().
G4double PHG4mRICHDetector::eta2polarAngle (G4double eta) private
Definition at line 811 of file PHG4mRICHDetector.cc.
Referenced by build_Space().
int PHG4mRICHDetector::get_Layer () const inline
Definition at line 44 of file PHG4mRICHDetector.h.
References layer.
bool PHG4mRICHDetector::IsInmRICH (G4VPhysicalVolume * volume) const
Definition at line 65 of file PHG4mRICHDetector.cc.
Referenced by PHG4mRICHSteppingAction::UserSteppingAction().
void PHG4mRICHDetector::SuperDetector (const std::string & name) inline
Definition at line 42 of file PHG4mRICHDetector.h.
References PHG4Detector::name, and superdetector.
Referenced by PHG4mRICHSubsystem::InitRunSubsystem().
const std::string PHG4mRICHDetector::SuperDetector () const inline
Definition at line 43 of file PHG4mRICHDetector.h.
References superdetector.
Member Data Documentation
std::set<G4VPhysicalVolume*> PHG4mRICHDetector::active_volumes private
Definition at line 73 of file PHG4mRICHDetector.h.
Referenced by build_sensor().
int PHG4mRICHDetector::layer private
Definition at line 70 of file PHG4mRICHDetector.h.
Referenced by get_Layer().
PHParameters* PHG4mRICHDetector::params private
Definition at line 50 of file PHG4mRICHDetector.h.
Referenced by Construct().
std::set<G4VPhysicalVolume*> PHG4mRICHDetector::passive_volumes private
Definition at line 74 of file PHG4mRICHDetector.h.
Referenced by build_foamHolder(), build_sensor(), and Construct_a_mRICH().
std::string PHG4mRICHDetector::superdetector private
Definition at line 72 of file PHG4mRICHDetector.h.
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4mRICHDetector.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4mRICHDetector.cc