Class Reference for E1039 Core & Analysis Software: SMatrix Class Reference
SMatrix Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/kfitter/KalmanUtil.h>
Static Public Member Functions
static void printMatrix (const TMatrixD &m)
static void printMatrix (const TMatrixD &m, std::string str)
static TMatrixD invertMatrix (const TMatrixD &m)
static TMatrixD invertMatrixFast (const TMatrixD &m)
static TMatrixD transposeMatrix (const TMatrixD &m)
static void unitMatrix (TMatrixD &m)
static void zeroMatrix (TMatrixD &m)
static TMatrixD getABC (const TMatrixD &A, const TMatrixD &B, const TMatrixD &C)
static TMatrixD getABCt (const TMatrixD &A, const TMatrixD &B, const TMatrixD &C)
static TMatrixD getAtBC (const TMatrixD &A, const TMatrixD &B, const TMatrixD &C)
static TMatrixD getABtC (const TMatrixD &A, const TMatrixD &B, const TMatrixD &C)
static TMatrixD getABtCinv (const TMatrixD &A, const TMatrixD &B, const TMatrixD &C)
Detailed Description
Definition at line 28 of file KalmanUtil.h.
Member Function Documentation
TMatrixD SMatrix::getABC (const TMatrixD & A, const TMatrixD & B, const TMatrixD & C) static
Definition at line 120 of file KalmanUtil.cxx.
TMatrixD SMatrix::getABCt (const TMatrixD & A, const TMatrixD & B, const TMatrixD & C) static
Definition at line 125 of file KalmanUtil.cxx.
Referenced by KalmanFilter::filter(), KalmanTrack::getExpPosError(), Node::getFilteredResidualCov(), Node::getKalmanGain(), Node::getPredictedResidualCov(), Node::getSmoothedResidualCov(), KalmanFilter::predict(), KalmanFilter::smooth(), and VertexFit::updateVertex().
TMatrixD SMatrix::getABtC (const TMatrixD & A, const TMatrixD & B, const TMatrixD & C) static
Definition at line 141 of file KalmanUtil.cxx.
Referenced by KalmanFilter::filter(), Node::getKalmanGain(), and VertexFit::updateVertex().
TMatrixD SMatrix::getABtCinv (const TMatrixD & A, const TMatrixD & B, const TMatrixD & C) static
Definition at line 149 of file KalmanUtil.cxx.
References invertMatrix().
Referenced by KalmanFilter::smooth().
TMatrixD SMatrix::getAtBC (const TMatrixD & A, const TMatrixD & B, const TMatrixD & C) static
Definition at line 133 of file KalmanUtil.cxx.
Referenced by KalmanFilter::filter(), and VertexFit::updateVertex().
TMatrixD SMatrix::invertMatrix (const TMatrixD & m) static
Definition at line 52 of file KalmanUtil.cxx.
Referenced by KalmanFilter::filter(), getABtCinv(), Node::getKalmanGain(), and VertexFit::updateVertex().
TMatrixD SMatrix::invertMatrixFast (const TMatrixD & m) static
Definition at line 71 of file KalmanUtil.cxx.
void SMatrix::printMatrix (const TMatrixD & m) static
Definition at line 17 of file KalmanUtil.cxx.
Referenced by VtxPar::print(), TrkPar::print(), and Node::print().
void SMatrix::printMatrix (const TMatrixD & m, std::string str) static
Definition at line 34 of file KalmanUtil.cxx.
TMatrixD SMatrix::transposeMatrix (const TMatrixD & m) static
Definition at line 79 of file KalmanUtil.cxx.
void SMatrix::unitMatrix (TMatrixD & m) static
Definition at line 87 of file KalmanUtil.cxx.
void SMatrix::zeroMatrix (TMatrixD & m) static
Definition at line 107 of file KalmanUtil.cxx.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/kfitter/KalmanUtil.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/kfitter/KalmanUtil.cxx