E1039 Software: PHGenEventv1 Class Reference
PHGenEventv1 Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/generators/phhepmc/PHGenEventv1.h>
Public Member Functions
PHGenEventv1 ()
PHGenEventv1 (const unsigned int id, HepMC::GenEvent &event)
PHGenEventv1 (const PHGenEventv1 &phevent)
PHGenEventv1 (const PHGenEventv1 *phevent)
virtual ~PHGenEventv1 ()
const HepMC::GenEvent * get_event () const
HepMC::GenEvent * get_event ()
TString get_event_record () const
void set_event (HepMC::GenEvent &event)
void set_event (HepMC::GenEvent *event)
unsigned int get_id () const
void set_id (const unsigned int id)
size_t particles_size () const
size_t vertices_size () const
void identify (std::ostream &out=std::cout) const
void print (std::ostream &out=std::cout) const
void Reset ()
Clear Event.
Public Member Functions inherited from PHGenEvent
virtual ~PHGenEvent ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Private Member Functions
bool stale () const
void refresh () const
Private Attributes
unsigned int _id
TString _event_record
bool _stale
HepMC::GenEvent * _event
exclude from ROOT I/O
Additional Inherited Members
Protected Member Functions inherited from PHGenEvent
PHGenEvent ()
Detailed Description
Definition at line 14 of file PHGenEventv1.h.
Constructor & Destructor Documentation
PHGenEventv1() [1/4]
PHGenEventv1::PHGenEventv1 ()
Definition at line 11 of file PHGenEventv1.cc.
PHGenEventv1() [2/4]
PHGenEventv1::PHGenEventv1 (const unsigned int id, HepMC::GenEvent & event)
Definition at line 18 of file PHGenEventv1.cc.
References set_event().
PHGenEventv1() [3/4]
PHGenEventv1::PHGenEventv1 (const PHGenEventv1 & phevent)
Definition at line 26 of file PHGenEventv1.cc.
PHGenEventv1() [4/4]
PHGenEventv1::PHGenEventv1 (const PHGenEventv1 * phevent)
Definition at line 33 of file PHGenEventv1.cc.
~PHGenEventv1()
PHGenEventv1::~PHGenEventv1 () virtual
Definition at line 40 of file PHGenEventv1.cc.
References _event.
Member Function Documentation
get_event() [1/2]
const HepMC::GenEvent * PHGenEventv1::get_event () const virtual
Reimplemented from PHGenEvent.
Definition at line 44 of file PHGenEventv1.cc.
References _event, refresh(), and stale().
get_event() [2/2]
HepMC::GenEvent * PHGenEventv1::get_event () virtual
Reimplemented from PHGenEvent.
Definition at line 49 of file PHGenEventv1.cc.
References _event, refresh(), and stale().
get_event_record()
TString PHGenEventv1::get_event_record () const inline
Definition at line 26 of file PHGenEventv1.h.
References _event_record, and set_event().
get_id()
unsigned int PHGenEventv1::get_id () const inline virtual
Reimplemented from PHGenEvent.
Definition at line 30 of file PHGenEventv1.h.
References _id.
identify()
void PHGenEventv1::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHGenEvent.
Definition at line 38 of file PHGenEventv1.h.
References print(), and Reset().
Referenced by print().
particles_size()
size_t PHGenEventv1::particles_size () const virtual
Reimplemented from PHGenEvent.
Definition at line 84 of file PHGenEventv1.cc.
References _event, refresh(), and stale().
Referenced by set_id().
print()
void PHGenEventv1::print (std::ostream & out = std::cout) const virtual
Reimplemented from PHGenEvent.
Definition at line 104 of file PHGenEventv1.cc.
References _event, _id, identify(), refresh(), and stale().
Referenced by identify().
refresh()
void PHGenEventv1::refresh () const private
Definition at line 111 of file PHGenEventv1.cc.
References _event, _event_record, _stale, and NULL.
Referenced by get_event(), particles_size(), print(), set_event(), stale(), and vertices_size().
Reset()
void PHGenEventv1::Reset () virtual
Clear Event.
Reimplemented from PHGenEvent.
Definition at line 94 of file PHGenEventv1.cc.
References _event, _event_record, _id, _stale, and NULL.
Referenced by identify().
set_event() [1/2]
void PHGenEventv1::set_event (HepMC::GenEvent & event) virtual
Reimplemented from PHGenEvent.
Definition at line 54 of file PHGenEventv1.cc.
References _event, _event_record, NULL, and refresh().
Referenced by get_event_record(), and PHGenEventv1().
set_event() [2/2]
void PHGenEventv1::set_event (HepMC::GenEvent * event) virtual
Reimplemented from PHGenEvent.
Definition at line 69 of file PHGenEventv1.cc.
References _event, _event_record, NULL, and refresh().
set_id()
void PHGenEventv1::set_id (const unsigned int id) inline virtual
Reimplemented from PHGenEvent.
Definition at line 31 of file PHGenEventv1.h.
References _id, particles_size(), and vertices_size().
stale()
bool PHGenEventv1::stale () const inline private
Definition at line 46 of file PHGenEventv1.h.
References _stale, and refresh().
Referenced by get_event(), particles_size(), print(), and vertices_size().
vertices_size()
size_t PHGenEventv1::vertices_size () const virtual
Reimplemented from PHGenEvent.
Definition at line 89 of file PHGenEventv1.cc.
References _event, refresh(), and stale().
Referenced by set_id().
Member Data Documentation
_event
HepMC::GenEvent* PHGenEventv1::_event mutable private
exclude from ROOT I/O
Definition at line 61 of file PHGenEventv1.h.
Referenced by get_event(), particles_size(), print(), refresh(), Reset(), set_event(), vertices_size(), and ~PHGenEventv1().
_event_record
TString PHGenEventv1::_event_record private
Definition at line 57 of file PHGenEventv1.h.
Referenced by get_event_record(), refresh(), Reset(), and set_event().
_id
unsigned int PHGenEventv1::_id private
Definition at line 50 of file PHGenEventv1.h.
Referenced by get_id(), print(), Reset(), and set_id().
_stale
bool PHGenEventv1::_stale mutable private
Definition at line 60 of file PHGenEventv1.h.
Referenced by refresh(), Reset(), and stale().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/generators/phhepmc/PHGenEventv1.h
/home/yuhw/GitHub/SeaQuest/e1039-core/generators/phhepmc/PHGenEventv1.cc