SeaQuest Offline Software: PHG4SiliconTrackerSubsystem Class Reference
PHG4SiliconTrackerSubsystem Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerSubsystem.h>
Public Types
typedef std::vector< std::pair
< int, int > > vpair
Public Types inherited from PHG4DetectorGroupSubsystem
enum FILE_TYPE { none = 0, xml = 1, root = 2 }
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Public Member Functions
PHG4SiliconTrackerSubsystem (const std::string &name="SILICONTRACKER", const vpair &layerconfig=vpair(0))
constructor
virtual ~PHG4SiliconTrackerSubsystem (void)
destructor
int InitRunSubsystem (PHCompositeNode *)
init
int process_event (PHCompositeNode *)
event processing
PHG4Detector * GetDetector (void) const
accessors (reimplemented)
PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
void Print (const std::string &what="ALL") const
Public Member Functions inherited from PHG4DetectorGroupSubsystem
virtual ~PHG4DetectorGroupSubsystem ()
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHG4ParametersContainer * GetParamsContainer () const
void set_double_param (const int detid, const std::string &name, const double dval)
double get_double_param (const int detid, const std::string &name) const
void set_int_param (const int detid, const std::string &name, const int ival)
int get_int_param (const int detid, const std::string &name) const
void set_string_param (const int detid, const std::string &name, const std::string &sval)
std::string get_string_param (const int detid, const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
int SaveParamsToFile (const FILE_TYPE ftyp)
int ReadParamsFromFile (const std::string &name, const FILE_TYPE ftyp, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int detid, const int i=1)
void SetAbsorberActive (const int detid, const int i=1)
void SetAbsorberTruth (const int detid, const int i=1)
void BlackHole (const int detid, const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SetDefaultParameters ()
Private Attributes
PHG4SiliconTrackerDetector * detector_
detector geometry
PHG4SteppingAction * steppingAction_
particle tracking "stepping" action
std::vector< std::pair< int,
int > > layerconfig_
std::string detector_type
int nlayers
Additional Inherited Members
Protected Member Functions inherited from PHG4DetectorGroupSubsystem
PHG4DetectorGroupSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void AddDetId (const int i)
std::pair< std::set< int >
::const_iterator, std::set
< int >::const_iterator > GetDetIds () const
void set_default_double_param (const int detid, const std::string &name, const double dval)
void set_default_int_param (const int detid, const std::string &name, const int ival)
void set_default_string_param (const int detid, const std::string &name, const std::string &sval)
int BeginRunExecuted () const
void PrintDefaultParams () const
void PrintMacroParams () const
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from PHG4Subsystem
bool overlapcheck
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 15 of file PHG4SiliconTrackerSubsystem.h.
Member Typedef Documentation
typedef std::vector<std::pair<int, int> > PHG4SiliconTrackerSubsystem::vpair
Definition at line 18 of file PHG4SiliconTrackerSubsystem.h.
Constructor & Destructor Documentation
PHG4SiliconTrackerSubsystem::PHG4SiliconTrackerSubsystem (const std::string & name = "SILICONTRACKER", const vpair & layerconfig = vpair(0))
constructor
Definition at line 19 of file PHG4SiliconTrackerSubsystem.cc.
References PHG4DetectorGroupSubsystem::AddDetId(), PHG4DetectorGroupSubsystem::InitializeParameters(), Fun4AllBase::Name(), nlayers, PHWHERE, PHG4DetectorGroupSubsystem::SuperDetector(), and Fun4AllBase::verbosity.
virtual PHG4SiliconTrackerSubsystem::~PHG4SiliconTrackerSubsystem (void) inline virtual
destructor
Definition at line 24 of file PHG4SiliconTrackerSubsystem.h.
Member Function Documentation
PHG4Detector * PHG4SiliconTrackerSubsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 127 of file PHG4SiliconTrackerSubsystem.cc.
References detector_.
PHG4SteppingAction* PHG4SiliconTrackerSubsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 45 of file PHG4SiliconTrackerSubsystem.h.
References steppingAction_.
int PHG4SiliconTrackerSubsystem::InitRunSubsystem (PHCompositeNode * topNode) virtual
init
creates the detector_ object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from PHG4DetectorGroupSubsystem.
Definition at line 42 of file PHG4SiliconTrackerSubsystem.cc.
References PHCompositeNode::addNode(), PHG4DetectorGroupSubsystem::CheckOverlap(), PHG4SiliconTrackerDetector::Detector(), detector_, detector_type, PHNodeIterator::findFirst(), PHG4Parameters::get_int_param(), PHG4DetectorGroupSubsystem::GetDetIds(), PHG4ParametersContainer::GetParameters(), PHG4DetectorGroupSubsystem::GetParamsContainer(), layerconfig_, Fun4AllBase::Name(), PHG4Detector::OverlapCheck(), steppingAction_, PHG4SiliconTrackerDetector::SuperDetector(), PHG4DetectorGroupSubsystem::SuperDetector(), and Fun4AllBase::verbosity.
void PHG4SiliconTrackerSubsystem::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SubsysReco.
Definition at line 235 of file PHG4SiliconTrackerSubsystem.cc.
References PHG4DetectorGroupSubsystem::GetParamsContainer(), PHG4ParametersContainer::Print(), PHG4DetectorGroupSubsystem::PrintDefaultParams(), and PHG4DetectorGroupSubsystem::PrintMacroParams().
int PHG4SiliconTrackerSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 116 of file PHG4SiliconTrackerSubsystem.cc.
References PHG4SteppingAction::SetInterfacePointers(), and steppingAction_.
void PHG4SiliconTrackerSubsystem::SetDefaultParameters () private virtual
Implements PHG4DetectorGroupSubsystem.
Definition at line 132 of file PHG4SiliconTrackerSubsystem.cc.
References PHG4DetectorGroupSubsystem::GetDetIds(), nlayers, PHG4DetectorGroupSubsystem::set_default_double_param(), and PHG4DetectorGroupSubsystem::set_default_int_param().
Member Data Documentation
PHG4SiliconTrackerDetector* PHG4SiliconTrackerSubsystem::detector_ private
detector geometry
defives from PHG4Detector
Definition at line 53 of file PHG4SiliconTrackerSubsystem.h.
Referenced by GetDetector(), and InitRunSubsystem().
std::string PHG4SiliconTrackerSubsystem::detector_type private
Definition at line 60 of file PHG4SiliconTrackerSubsystem.h.
Referenced by InitRunSubsystem().
std::vector<std::pair<int, int> > PHG4SiliconTrackerSubsystem::layerconfig_ private
Definition at line 59 of file PHG4SiliconTrackerSubsystem.h.
Referenced by InitRunSubsystem().
int PHG4SiliconTrackerSubsystem::nlayers private
Definition at line 62 of file PHG4SiliconTrackerSubsystem.h.
Referenced by PHG4SiliconTrackerSubsystem(), and SetDefaultParameters().
PHG4SteppingAction* PHG4SiliconTrackerSubsystem::steppingAction_ private
particle tracking "stepping" action
derives from PHG4SteppingActions
Definition at line 57 of file PHG4SiliconTrackerSubsystem.h.
Referenced by GetSteppingAction(), InitRunSubsystem(), and process_event().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerSubsystem.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerSubsystem.cc