Class Reference for E1039 Core & Analysis Software: DPTriggerRoad Class Reference
DPTriggerRoad Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/dptrigger/DPTriggerAnalyzer.h>
Public Member Functions
DPTriggerRoad ()
DPTriggerRoad (const std::list< int > &path)
void addTrElement (int uniqueID)
add one hit into the road
void addTrElement (int detectorID, int elementID)
int getTB ()
Get the sign of LR or TB.
void flipTB ()
flip the LR or TB
int getRoadID () const
Other gets.
double getSigWeight () const
double getBkgRate () const
double getPxMin () const
int getTrID (unsigned int i) const
int getTrDetectorID (unsigned int i) const
int getTrElementID (unsigned int i) const
TString getStringID ()
void setRoadID (int id)
Sets.
void setSigWeight (double weight)
void setBkgRate (double rate)
void setPxMin (double pxmin)
bool operator== (const DPTriggerRoad &elem) const
comparison
bool operator< (const DPTriggerRoad &elem) const
Friends
std::ostream & operator<< (std::ostream &os, const DPTriggerRoad &road)
printer
Detailed Description
Definition at line 18 of file DPTriggerAnalyzer.h.
Constructor & Destructor Documentation
DPTriggerRoad() [1/2]
DPTriggerRoad::DPTriggerRoad ()
Definition at line 20 of file DPTriggerAnalyzer.cxx.
DPTriggerRoad() [2/2]
DPTriggerRoad::DPTriggerRoad (const std::list< int > & path)
Definition at line 25 of file DPTriggerAnalyzer.cxx.
Member Function Documentation
addTrElement() [1/2]
void DPTriggerRoad::addTrElement (int detectorID, int elementID) inline
Definition at line 26 of file DPTriggerAnalyzer.h.
References addTrElement().
Referenced by addTrElement().
addTrElement() [2/2]
void DPTriggerRoad::addTrElement (int uniqueID) inline
add one hit into the road
Definition at line 25 of file DPTriggerAnalyzer.h.
Referenced by DPTriggerAnalyzer::Init().
flipTB()
void DPTriggerRoad::flipTB ()
flip the LR or TB
Definition at line 50 of file DPTriggerAnalyzer.cxx.
References getTB(), getTrDetectorID(), getTrElementID(), and NTRPLANES.
getBkgRate()
double DPTriggerRoad::getBkgRate () const inline
Definition at line 38 of file DPTriggerAnalyzer.h.
getPxMin()
double DPTriggerRoad::getPxMin () const inline
Definition at line 39 of file DPTriggerAnalyzer.h.
getRoadID()
int DPTriggerRoad::getRoadID () const inline
Other gets.
Definition at line 36 of file DPTriggerAnalyzer.h.
getSigWeight()
double DPTriggerRoad::getSigWeight () const inline
Definition at line 37 of file DPTriggerAnalyzer.h.
getStringID()
TString DPTriggerRoad::getStringID ()
Definition at line 78 of file DPTriggerAnalyzer.cxx.
Referenced by DPTriggerAnalyzer::Init(), and DPTriggerAnalyzer::searchMatrix().
getTB()
int DPTriggerRoad::getTB ()
Get the sign of LR or TB.
Definition at line 35 of file DPTriggerAnalyzer.cxx.
References getTrDetectorID(), and NTRPLANES.
Referenced by flipTB().
getTrDetectorID()
int DPTriggerRoad::getTrDetectorID (unsigned int i) const inline
Definition at line 41 of file DPTriggerAnalyzer.h.
References getTrID().
Referenced by flipTB(), and getTB().
getTrElementID()
int DPTriggerRoad::getTrElementID (unsigned int i) const inline
Definition at line 42 of file DPTriggerAnalyzer.h.
References getTrID().
Referenced by flipTB().
getTrID()
int DPTriggerRoad::getTrID (unsigned int i) const inline
Definition at line 40 of file DPTriggerAnalyzer.h.
References NTRPLANES.
Referenced by getTrDetectorID(), and getTrElementID().
operator<()
bool DPTriggerRoad::operator< (const DPTriggerRoad & elem) const
Definition at line 73 of file DPTriggerAnalyzer.cxx.
operator==()
bool DPTriggerRoad::operator== (const DPTriggerRoad & elem) const
comparison
Definition at line 63 of file DPTriggerAnalyzer.cxx.
References NTRPLANES.
setBkgRate()
void DPTriggerRoad::setBkgRate (double rate) inline
Definition at line 50 of file DPTriggerAnalyzer.h.
Referenced by DPTriggerAnalyzer::Init().
setPxMin()
void DPTriggerRoad::setPxMin (double pxmin) inline
Definition at line 51 of file DPTriggerAnalyzer.h.
Referenced by DPTriggerAnalyzer::Init().
setRoadID()
void DPTriggerRoad::setRoadID (int id) inline
Sets.
Definition at line 48 of file DPTriggerAnalyzer.h.
Referenced by DPTriggerAnalyzer::Init().
setSigWeight()
void DPTriggerRoad::setSigWeight (double weight) inline
Definition at line 49 of file DPTriggerAnalyzer.h.
Referenced by DPTriggerAnalyzer::Init().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const DPTriggerRoad & road) friend
printer
Definition at line 89 of file DPTriggerAnalyzer.cxx.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/dptrigger/DPTriggerAnalyzer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/dptrigger/DPTriggerAnalyzer.cxx