Class Reference for E1039 Core & Analysis Software: SQIntMap_v1 Class Reference
SQIntMap_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQIntMap_v1.h>
Public Member Functions
SQIntMap_v1 ()
SQIntMap_v1 (const SQIntMap_v1 &map)
SQIntMap_v1 & operator= (const SQIntMap_v1 &map)
virtual ~SQIntMap_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQIntMap * Clone () const
bool empty () const
size_t size () const
size_t count (unsigned int idkey) const
void clear ()
const PHObject * get (unsigned int idkey) const
PHObject * get (unsigned int idkey)
PHObject * insert (unsigned int idkey, const PHObject *item)
size_t erase (unsigned int idkey)
ConstIter begin () const
ConstIter find (unsigned int idkey) const
ConstIter end () const
Iter begin ()
Iter find (unsigned int idkey)
Iter end ()
Public Member Functions inherited from SQIntMap
virtual ~SQIntMap ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from SQIntMap
typedef std::map< unsigned int, PHObject * > ObjectMap
typedef ObjectMap::const_iterator ConstIter
typedef ObjectMap::iterator Iter
Protected Member Functions inherited from SQIntMap
SQIntMap ()
Detailed Description
Definition at line 8 of file SQIntMap_v1.h.
Constructor & Destructor Documentation
SQIntMap_v1() [1/2]
SQIntMap_v1::SQIntMap_v1 ()
Referenced by Clone().
SQIntMap_v1() [2/2]
SQIntMap_v1::SQIntMap_v1 (const SQIntMap_v1 & map)
Definition at line 12 of file SQIntMap_v1.cxx.
References begin(), and end().
~SQIntMap_v1()
SQIntMap_v1::~SQIntMap_v1 () virtual
Definition at line 28 of file SQIntMap_v1.cxx.
References Reset().
Member Function Documentation
begin() [1/2]
Iter SQIntMap_v1::begin () inline virtual
Reimplemented from SQIntMap.
Definition at line 37 of file SQIntMap_v1.h.
begin() [2/2]
ConstIter SQIntMap_v1::begin () const inline virtual
Reimplemented from SQIntMap.
Definition at line 33 of file SQIntMap_v1.h.
Referenced by operator=(), and SQIntMap_v1().
clear()
void SQIntMap_v1::clear () inline virtual
Reimplemented from SQIntMap.
Definition at line 23 of file SQIntMap_v1.h.
References Reset().
Clone()
SQIntMap* SQIntMap_v1::Clone () const inline virtual
Reimplemented from SQIntMap.
Definition at line 18 of file SQIntMap_v1.h.
References SQIntMap_v1().
count()
size_t SQIntMap_v1::count (unsigned int idkey) const inline virtual
Reimplemented from SQIntMap.
Definition at line 22 of file SQIntMap_v1.h.
empty()
bool SQIntMap_v1::empty () const inline virtual
Reimplemented from SQIntMap.
Definition at line 20 of file SQIntMap_v1.h.
end() [1/2]
Iter SQIntMap_v1::end () inline virtual
Reimplemented from SQIntMap.
Definition at line 39 of file SQIntMap_v1.h.
end() [2/2]
ConstIter SQIntMap_v1::end () const inline virtual
Reimplemented from SQIntMap.
Definition at line 35 of file SQIntMap_v1.h.
Referenced by operator=(), and SQIntMap_v1().
erase()
size_t SQIntMap_v1::erase (unsigned int idkey) inline virtual
Reimplemented from SQIntMap.
Definition at line 28 of file SQIntMap_v1.h.
find() [1/2]
Iter SQIntMap_v1::find (unsigned int idkey) inline virtual
Reimplemented from SQIntMap.
Definition at line 38 of file SQIntMap_v1.h.
find() [2/2]
ConstIter SQIntMap_v1::find (unsigned int idkey) const inline virtual
Reimplemented from SQIntMap.
Definition at line 34 of file SQIntMap_v1.h.
get() [1/2]
PHObject * SQIntMap_v1::get (unsigned int idkey) virtual
Reimplemented from SQIntMap.
Definition at line 50 of file SQIntMap_v1.cxx.
References NULL.
get() [2/2]
const PHObject * SQIntMap_v1::get (unsigned int idkey) const virtual
Reimplemented from SQIntMap.
Definition at line 44 of file SQIntMap_v1.cxx.
References NULL.
identify()
void SQIntMap_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQIntMap.
Definition at line 39 of file SQIntMap_v1.cxx.
insert()
PHObject * SQIntMap_v1::insert (unsigned int idkey, const PHObject * item) virtual
Reimplemented from SQIntMap.
Definition at line 56 of file SQIntMap_v1.cxx.
References PHObject::clone().
isValid()
int SQIntMap_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQIntMap.
Definition at line 17 of file SQIntMap_v1.h.
operator=()
SQIntMap_v1 & SQIntMap_v1::operator= (const SQIntMap_v1 & map)
Definition at line 19 of file SQIntMap_v1.cxx.
References begin(), end(), and Reset().
Reset()
void SQIntMap_v1::Reset () virtual
Clear Event.
Reimplemented from SQIntMap.
Definition at line 32 of file SQIntMap_v1.cxx.
Referenced by clear(), operator=(), and ~SQIntMap_v1().
size()
size_t SQIntMap_v1::size (void) const inline virtual
Reimplemented from SQIntMap.
Definition at line 21 of file SQIntMap_v1.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQIntMap_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQIntMap_v1.cxx