Class Reference for E1039 Core & Analysis Software: PHHepMCGenEventMap Class Reference
PHHepMCGenEventMap Class Reference
PHHepMCGenEventMap is collection of HEPMC events input into this simulation map of embedding ID -> PHHepMCGenEvent positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/phhepmc/PHHepMCGenEventMap.h>
Public Types
typedef std::map< int, PHHepMCGenEvent * > HepMCGenEventMap
typedef std::map< int, PHHepMCGenEvent * >::const_iterator ConstIter
typedef std::map< int, PHHepMCGenEvent * >::iterator Iter
typedef std::map< int, PHHepMCGenEvent * >::const_reverse_iterator ConstReverseIter
typedef std::map< int, PHHepMCGenEvent * >::reverse_iterator ReverseIter
Public Member Functions
PHHepMCGenEventMap ()
PHHepMCGenEventMap (const PHHepMCGenEventMap &eventmap)
PHHepMCGenEventMap & operator= (const PHHepMCGenEventMap &eventmap)
virtual ~PHHepMCGenEventMap ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHHepMCGenEventMap * Clone (const char *newname="") const
bool empty () const
container service
size_t size () const
size_t count (int idkey) const
void clear ()
const PHHepMCGenEvent * get (int idkey) const
fetch event
PHHepMCGenEvent * get (int idkey)
PHHepMCGenEvent * insert (const PHHepMCGenEvent *event)
insert a event of interest, e.g. jetty event from pythia
PHHepMCGenEvent * insert_active_event (const PHHepMCGenEvent *event=nullptr)
insert a event of interest, e.g. jetty event from pythia
PHHepMCGenEvent * insert_background_event (const PHHepMCGenEvent *event=nullptr)
insert a event of background, e.g. Au+Au collision background. First event has embedding ID = 0, which is usually the primary Au+Au collision in the case of HI embedding
PHHepMCGenEvent * insert_event (const int embedding_id, const PHHepMCGenEvent *event=nullptr)
insert a event with specific embedding ID
size_t erase (int idkey)
ConstIter find (unsigned int idkey) const
find
Iter find (int idkey)
ConstIter begin () const
iterator from lowest ID to highest, i.e. background to signal
ConstIter end () const
Iter begin ()
Iter end ()
ConstReverseIter rbegin () const
iterator from lowest ID to highest, i.e. signal to background
ConstReverseIter rend () const
ReverseIter rbegin ()
ReverseIter rend ()
const HepMCGenEventMap & get_map () const
for c++11 range-based for loop
HepMCGenEventMap & get_map ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Detailed Description
PHHepMCGenEventMap is collection of HEPMC events input into this simulation map of embedding ID -> PHHepMCGenEvent positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background.
Definition at line 14 of file PHHepMCGenEventMap.h.
Member Typedef Documentation
ConstIter
typedef std::map<int, PHHepMCGenEvent*>::const_iterator PHHepMCGenEventMap::ConstIter
Definition at line 22 of file PHHepMCGenEventMap.h.
ConstReverseIter
typedef std::map<int, PHHepMCGenEvent*>::const_reverse_iterator PHHepMCGenEventMap::ConstReverseIter
Definition at line 24 of file PHHepMCGenEventMap.h.
HepMCGenEventMap
typedef std::map<int, PHHepMCGenEvent*> PHHepMCGenEventMap::HepMCGenEventMap
map of embedding ID -> PHHepMCGenEvent positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 21 of file PHHepMCGenEventMap.h.
Iter
typedef std::map<int, PHHepMCGenEvent*>::iterator PHHepMCGenEventMap::Iter
Definition at line 23 of file PHHepMCGenEventMap.h.
ReverseIter
typedef std::map<int, PHHepMCGenEvent*>::reverse_iterator PHHepMCGenEventMap::ReverseIter
Definition at line 25 of file PHHepMCGenEventMap.h.
Constructor & Destructor Documentation
PHHepMCGenEventMap() [1/2]
PHHepMCGenEventMap::PHHepMCGenEventMap ()
Referenced by Clone().
PHHepMCGenEventMap() [2/2]
PHHepMCGenEventMap::PHHepMCGenEventMap (const PHHepMCGenEventMap & eventmap)
Definition at line 16 of file PHHepMCGenEventMap.cc.
References begin(), and end().
~PHHepMCGenEventMap()
PHHepMCGenEventMap::~PHHepMCGenEventMap () virtual
Definition at line 41 of file PHHepMCGenEventMap.cc.
References Reset().
Member Function Documentation
begin() [1/2]
Iter PHHepMCGenEventMap::begin () inline
Definition at line 67 of file PHHepMCGenEventMap.h.
begin() [2/2]
ConstIter PHHepMCGenEventMap::begin () const inline
iterator from lowest ID to highest, i.e. background to signal
Definition at line 65 of file PHHepMCGenEventMap.h.
Referenced by operator=(), PHHepMCGenEventMap(), and TruthNodeMaker::process_event().
clear()
void PHHepMCGenEventMap::clear () inline
Definition at line 41 of file PHHepMCGenEventMap.h.
References Reset().
Clone()
PHHepMCGenEventMap* PHHepMCGenEventMap::Clone (const char * newname = "") const inline
Definition at line 36 of file PHHepMCGenEventMap.h.
References PHHepMCGenEventMap().
count()
size_t PHHepMCGenEventMap::count (int idkey) const inline
Definition at line 40 of file PHHepMCGenEventMap.h.
empty()
bool PHHepMCGenEventMap::empty () const inline
container service
Definition at line 38 of file PHHepMCGenEventMap.h.
end() [1/2]
Iter PHHepMCGenEventMap::end () inline
Definition at line 68 of file PHHepMCGenEventMap.h.
end() [2/2]
ConstIter PHHepMCGenEventMap::end () const inline
Definition at line 66 of file PHHepMCGenEventMap.h.
Referenced by Fun4AllOscarInputManager::ConvertFromOscar(), operator=(), PHHepMCGenEventMap(), TruthNodeMaker::process_event(), and Fun4AllHepMCInputManager::run().
erase()
size_t PHHepMCGenEventMap::erase (int idkey) inline
Definition at line 55 of file PHHepMCGenEventMap.h.
find() [1/2]
Iter PHHepMCGenEventMap::find (int idkey) inline
Definition at line 63 of file PHHepMCGenEventMap.h.
find() [2/2]
ConstIter PHHepMCGenEventMap::find (unsigned int idkey) const inline
find
Definition at line 62 of file PHHepMCGenEventMap.h.
Referenced by Fun4AllOscarInputManager::ConvertFromOscar(), and Fun4AllHepMCInputManager::run().
get() [1/2]
PHHepMCGenEvent * PHHepMCGenEventMap::get (int idkey)
Definition at line 79 of file PHHepMCGenEventMap.cc.
References NULL.
get() [2/2]
const PHHepMCGenEvent * PHHepMCGenEventMap::get (int idkey) const
fetch event
Definition at line 72 of file PHHepMCGenEventMap.cc.
References NULL.
Referenced by PHHepMCGenHelper::move_vertex(), PHHepMCParticleSelectorDecayProductChain::process_event(), and Fun4AllHepMCOutputManager::Write().
get_map() [1/2]
HepMCGenEventMap& PHHepMCGenEventMap::get_map () inline
Definition at line 77 of file PHHepMCGenEventMap.h.
get_map() [2/2]
const HepMCGenEventMap& PHHepMCGenEventMap::get_map () const inline
for c++11 range-based for loop
Definition at line 76 of file PHHepMCGenEventMap.h.
identify()
void PHHepMCGenEventMap::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 58 of file PHHepMCGenEventMap.cc.
Referenced by insert_event(), and PHHepMCGenHelper::move_vertex().
insert()
PHHepMCGenEvent* PHHepMCGenEventMap::insert (const PHHepMCGenEvent * event) inline
insert a event of interest, e.g. jetty event from pythia
Definition at line 47 of file PHHepMCGenEventMap.h.
References insert_active_event().
insert_active_event()
PHHepMCGenEvent * PHHepMCGenEventMap::insert_active_event (const PHHepMCGenEvent * event = nullptr)
insert a event of interest, e.g. jetty event from pythia
Definition at line 86 of file PHHepMCGenEventMap.cc.
References PHHepMCGenEvent::Clone().
Referenced by insert(), and Fun4AllHepMCPileupInputManager::run().
insert_background_event()
PHHepMCGenEvent * PHHepMCGenEventMap::insert_background_event (const PHHepMCGenEvent * event = nullptr)
insert a event of background, e.g. Au+Au collision background. First event has embedding ID = 0, which is usually the primary Au+Au collision in the case of HI embedding
Definition at line 100 of file PHHepMCGenEventMap.cc.
References PHHepMCGenEvent::Clone().
Referenced by Fun4AllHepMCPileupInputManager::run().
insert_event()
PHHepMCGenEvent * PHHepMCGenEventMap::insert_event (const int embedding_id, const PHHepMCGenEvent * event = nullptr)
insert a event with specific embedding ID
Definition at line 114 of file PHHepMCGenEventMap.cc.
References PHHepMCGenEvent::Clone(), and identify().
Referenced by PHHepMCGenHelper::insert_event().
isValid()
int PHHepMCGenEventMap::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 35 of file PHHepMCGenEventMap.h.
operator=()
PHHepMCGenEventMap & PHHepMCGenEventMap::operator= (const PHHepMCGenEventMap & eventmap)
Definition at line 28 of file PHHepMCGenEventMap.cc.
References begin(), end(), and Reset().
rbegin() [1/2]
ReverseIter PHHepMCGenEventMap::rbegin () inline
Definition at line 72 of file PHHepMCGenEventMap.h.
rbegin() [2/2]
ConstReverseIter PHHepMCGenEventMap::rbegin () const inline
iterator from lowest ID to highest, i.e. signal to background
Definition at line 70 of file PHHepMCGenEventMap.h.
Referenced by HepMCNodeReader::process_event(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
rend() [1/2]
ReverseIter PHHepMCGenEventMap::rend () inline
Definition at line 73 of file PHHepMCGenEventMap.h.
rend() [2/2]
ConstReverseIter PHHepMCGenEventMap::rend () const inline
Definition at line 71 of file PHHepMCGenEventMap.h.
Referenced by HepMCNodeReader::process_event(), and PHG4ParticleGeneratorBase::ReuseExistingVertex().
Reset()
void PHHepMCGenEventMap::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 46 of file PHHepMCGenEventMap.cc.
Referenced by clear(), operator=(), and ~PHHepMCGenEventMap().
size()
size_t PHHepMCGenEventMap::size (void) const inline
Definition at line 39 of file PHHepMCGenEventMap.h.
Referenced by TruthNodeMaker::process_event().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/phhepmc/PHHepMCGenEventMap.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/phhepmc/PHHepMCGenEventMap.cc