E1039 Software: ManageCodaInput Class Reference
ManageCodaInput Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/online/decoder_maindaq/ManageCodaInput.h>
Public Member Functions
ManageCodaInput ()
virtual ~ManageCodaInput ()
void SetVerbosity (const int verb)
void SetRunNumber (const int run)
void SetOnline ()
void ForceEnd ()
int OpenFile (const std::string fname, const int file_size_min=0, const int sec_wait=10, const int n_wait=0, const int n_evt_pre_read=0)
int CloseFile ()
bool NextEvent (unsigned int &coda_id, int *&event_words)
Private Member Functions
bool file_exists (const std::string fname)
Private Attributes
int m_verb
bool m_online
bool m_go_end
int m_handle
int m_run
std::string m_fname
long int m_file_size
int m_event_count
int event_words [buflen]
Static Private Attributes
static const int buflen = 500000
Detailed Description
Definition at line 9 of file ManageCodaInput.h.
Constructor & Destructor Documentation
ManageCodaInput::ManageCodaInput ()
Definition at line 11 of file ManageCodaInput.cc.
virtual ManageCodaInput::~ManageCodaInput () inline virtual
Definition at line 23 of file ManageCodaInput.h.
Member Function Documentation
int ManageCodaInput::CloseFile ()
Definition at line 112 of file ManageCodaInput.cc.
References evClose(), and m_handle.
bool ManageCodaInput::file_exists (const std::string fname) private
Definition at line 146 of file ManageCodaInput.cc.
Referenced by NextEvent(), and OpenFile().
void ManageCodaInput::ForceEnd () inline
Definition at line 28 of file ManageCodaInput.h.
References m_go_end.
bool ManageCodaInput::NextEvent (unsigned int & coda_id, int *& event_words)
Definition at line 117 of file ManageCodaInput.cc.
References buflen, event_words, evRead(), file_exists(), m_event_count, m_file_size, m_fname, m_go_end, m_handle, m_online, m_run, and OpenFile().
Referenced by OpenFile(), Fun4AllEVIOInputManager::PushBackEvents(), and Fun4AllEVIOInputManager::run().
int ManageCodaInput::OpenFile (const std::string fname, const int file_size_min = 0, const int sec_wait = 10, const int n_wait = 0, const int n_evt_pre_read = 0)
Definition at line 17 of file ManageCodaInput.cc.
References evOpen(), file_exists(), m_event_count, m_file_size, m_fname, m_handle, m_verb, and NextEvent().
Referenced by Fun4AllEVIOInputManager::fileopen(), and NextEvent().
void ManageCodaInput::SetOnline () inline
Definition at line 27 of file ManageCodaInput.h.
References m_online.
void ManageCodaInput::SetRunNumber (const int run) inline
Definition at line 26 of file ManageCodaInput.h.
References m_run.
void ManageCodaInput::SetVerbosity (const int verb) inline
Definition at line 25 of file ManageCodaInput.h.
References m_verb.
Member Data Documentation
const int ManageCodaInput::buflen = 500000 static private
Definition at line 10 of file ManageCodaInput.h.
Referenced by NextEvent().
int ManageCodaInput::event_words[buflen] private
Definition at line 19 of file ManageCodaInput.h.
Referenced by NextEvent().
int ManageCodaInput::m_event_count private
Definition at line 18 of file ManageCodaInput.h.
Referenced by NextEvent(), and OpenFile().
long int ManageCodaInput::m_file_size private
Definition at line 17 of file ManageCodaInput.h.
Referenced by NextEvent(), and OpenFile().
std::string ManageCodaInput::m_fname private
Definition at line 16 of file ManageCodaInput.h.
Referenced by NextEvent(), and OpenFile().
bool ManageCodaInput::m_go_end private
Definition at line 13 of file ManageCodaInput.h.
Referenced by ForceEnd(), and NextEvent().
int ManageCodaInput::m_handle private
Definition at line 14 of file ManageCodaInput.h.
Referenced by CloseFile(), NextEvent(), and OpenFile().
bool ManageCodaInput::m_online private
Definition at line 12 of file ManageCodaInput.h.
Referenced by NextEvent(), and SetOnline().
int ManageCodaInput::m_run private
Definition at line 15 of file ManageCodaInput.h.
Referenced by NextEvent(), and SetRunNumber().
int ManageCodaInput::m_verb private
Definition at line 11 of file ManageCodaInput.h.
Referenced by OpenFile(), and SetVerbosity().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/online/decoder_maindaq/ManageCodaInput.h
/home/yuhw/GitHub/SeaQuest/e1039-core/online/decoder_maindaq/ManageCodaInput.cc