Class Reference for E1039 Core & Analysis Software: KScheduler Class Reference
KScheduler Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/kTThreads/KScheduler.h>
Public Member Functions
KScheduler (TString inFile, TString outFile)
~KScheduler ()
void Init ()
void postCompletedEvent ()
Int_t runThreads ()
void UseE906Data (const bool a)
bool UseE906Data ()
void UseTrackletReco (const bool a)
bool UseTrackletReco () const
KScheduler (TString inFile, TString outFile)
~KScheduler ()
void Init (PHField *phfield, TGeoManager *t_geo_manager, KalmanFitter *kfitter, SQGenFit::GFFitter *gfitter, SQGenFit::GFField *gfield)
void postCompletedEvent ()
Int_t runThreads ()
Int_t endThreads ()
void PushEvent (SRawEvent *sraw, bool copy)
void PushPoison ()
void UseTrackletReco (const bool a)
bool UseTrackletReco () const
KalmanFitter * GetKFitter ()
SQGenFit::GFFitter * GetGFitter ()
Static Public Member Functions
static TString getInputFilename ()
static void setInputFilename (TString name)
static TString getOutputFilename ()
static void setOutputFilename (TString name)
static void getTrackletsInStation (int stid)
static void Verbose (const int a)
static int Verbose ()
static TString getInputFilename ()
static void setInputFilename (TString name)
static TString getOutputFilename ()
static void setOutputFilename (TString name)
static void Verbose (const int a)
static int Verbose ()
static void SetNumThreads (const int n)
static int GetNumThreads ()
static void SetInputPipeDepth (const int depth)
static int GetInputPipeDepth ()
static void SetOutputPipeDepth (const int depth)
static int GetOutputPipeDepth ()
static void PrintFreq (const int i)
static int PrintFreq ()
static void SaveNum (const int i)
static int SaveNum ()
static void SaveRawEvent (const bool save)
static bool SaveRawEvent ()
Public Attributes
TMutex * ktrkQueueMutex
TSemaphore * ktrkqFSem
TSemaphore * ktrkqESem
std::queue< TClonesArray * > kTrackArrQueue
Detailed Description
Definition at line 66 of file KScheduler.h.
Constructor & Destructor Documentation
KScheduler() [1/2]
KScheduler::KScheduler (TString inFile, TString outFile)
Definition at line 120 of file KScheduler.cxx.
References setInputFilename(), and setOutputFilename().
~KScheduler() [1/2]
KScheduler::~KScheduler ()
Definition at line 258 of file KScheduler.cxx.
References kTrackArrQueue, ktrkqESem, ktrkqFSem, ktrkQueueMutex, NEVENT_REDUCERS, NKFAST_TRACKERS, and NTHREADS.
KScheduler() [2/2]
KScheduler::KScheduler (TString inFile, TString outFile)
~KScheduler() [2/2]
KScheduler::~KScheduler ()
Member Function Documentation
endThreads()
Int_t KScheduler::endThreads ()
Definition at line 301 of file KScheduler.cc.
References NULL.
Referenced by MultiThreadReco::End().
GetGFitter()
SQGenFit::GFFitter* KScheduler::GetGFitter () inline
Definition at line 86 of file KScheduler.h.
getInputFilename() [1/2]
static TString KScheduler::getInputFilename () static
getInputFilename() [2/2]
TString KScheduler::getInputFilename () static
Definition at line 461 of file KScheduler.cxx.
GetInputPipeDepth()
static int KScheduler::GetInputPipeDepth () inline static
Definition at line 65 of file KScheduler.h.
GetKFitter()
KalmanFitter* KScheduler::GetKFitter () inline
Definition at line 85 of file KScheduler.h.
GetNumThreads()
static int KScheduler::GetNumThreads () inline static
Definition at line 62 of file KScheduler.h.
getOutputFilename() [1/2]
static TString KScheduler::getOutputFilename () static
getOutputFilename() [2/2]
TString KScheduler::getOutputFilename () static
Definition at line 468 of file KScheduler.cxx.
GetOutputPipeDepth()
static int KScheduler::GetOutputPipeDepth () inline static
Definition at line 68 of file KScheduler.h.
getTrackletsInStation()
static void KScheduler::getTrackletsInStation (int stid) static
Init() [1/2]
void KScheduler::Init ()
Definition at line 132 of file KScheduler.cxx.
References PHFlag::get_CharFlag(), GeomSvc::getDetectorIDs(), INPUT_PIPE_DEPTH, recoConsts::instance(), GeomSvc::instance(), kTrackArrQueue, ktrkqESem, ktrkqFSem, ktrkQueueMutex, NEVENT_REDUCERS, NKFAST_TRACKERS, NTHREADS, and OUTPUT_PIPE_DEPTH.
Referenced by MultiThreadReco::InitRun().
Init() [2/2]
void KScheduler::Init (PHField * phfield, TGeoManager * t_geo_manager, KalmanFitter * kfitter, SQGenFit::GFFitter * gfitter, SQGenFit::GFField * gfield)
Definition at line 54 of file KScheduler.cc.
References PHFlag::get_CharFlag(), recoConsts::instance(), kTrackArrQueue, ktrkqESem, ktrkqFSem, and ktrkQueueMutex.
postCompletedEvent() [1/2]
void KScheduler::postCompletedEvent ()
postCompletedEvent() [2/2]
void KScheduler::postCompletedEvent ()
Definition at line 476 of file KScheduler.cxx.
References PRINTFREQ.
PrintFreq() [1/2]
static int KScheduler::PrintFreq () inline static
Definition at line 71 of file KScheduler.h.
PrintFreq() [2/2]
static void KScheduler::PrintFreq (const int i) inline static
Definition at line 70 of file KScheduler.h.
PushEvent()
void KScheduler::PushEvent (SRawEvent * sraw, bool copy)
This function is no longer used. Use MultiThreadReco::process_event() instead.
Definition at line 447 of file KScheduler.cc.
Referenced by MultiThreadReco::process_event().
PushPoison()
void KScheduler::PushPoison ()
Definition at line 461 of file KScheduler.cc.
References Verbose().
Referenced by MultiThreadReco::End().
runThreads() [1/2]
Int_t KScheduler::runThreads ()
runThreads() [2/2]
Int_t KScheduler::runThreads ()
Definition at line 430 of file KScheduler.cxx.
References NTHREADS, and NULL.
Referenced by MultiThreadReco::InitRun().
SaveNum() [1/2]
static int KScheduler::SaveNum () inline static
Definition at line 74 of file KScheduler.h.
SaveNum() [2/2]
static void KScheduler::SaveNum (const int i) inline static
Definition at line 73 of file KScheduler.h.
SaveRawEvent() [1/2]
static bool KScheduler::SaveRawEvent () inline static
Definition at line 77 of file KScheduler.h.
SaveRawEvent() [2/2]
static void KScheduler::SaveRawEvent (const bool save) inline static
Definition at line 76 of file KScheduler.h.
Referenced by MultiThreadReco::InitRun().
setInputFilename() [1/2]
static void KScheduler::setInputFilename (TString name) static
setInputFilename() [2/2]
void KScheduler::setInputFilename (TString name) static
Definition at line 464 of file KScheduler.cxx.
Referenced by KScheduler().
SetInputPipeDepth()
static void KScheduler::SetInputPipeDepth (const int depth) inline static
Definition at line 64 of file KScheduler.h.
SetNumThreads()
static void KScheduler::SetNumThreads (const int n) inline static
Definition at line 61 of file KScheduler.h.
setOutputFilename() [1/2]
static void KScheduler::setOutputFilename (TString name) static
setOutputFilename() [2/2]
void KScheduler::setOutputFilename (TString name) static
Definition at line 472 of file KScheduler.cxx.
Referenced by KScheduler().
SetOutputPipeDepth()
static void KScheduler::SetOutputPipeDepth (const int depth) inline static
Definition at line 67 of file KScheduler.h.
UseE906Data() [1/2]
bool KScheduler::UseE906Data () inline
Definition at line 87 of file KScheduler.h.
UseE906Data() [2/2]
void KScheduler::UseE906Data (const bool a) inline
Definition at line 86 of file KScheduler.h.
UseTrackletReco() [1/4]
bool KScheduler::UseTrackletReco () const inline
Definition at line 83 of file KScheduler.h.
UseTrackletReco() [2/4]
bool KScheduler::UseTrackletReco () const inline
Definition at line 90 of file KScheduler.h.
UseTrackletReco() [3/4]
void KScheduler::UseTrackletReco (const bool a) inline
Definition at line 82 of file KScheduler.h.
UseTrackletReco() [4/4]
void KScheduler::UseTrackletReco (const bool a) inline
Definition at line 89 of file KScheduler.h.
Verbose() [1/4]
static int KScheduler::Verbose () inline static
Definition at line 59 of file KScheduler.h.
Verbose() [2/4]
static int KScheduler::Verbose () inline static
Definition at line 84 of file KScheduler.h.
Referenced by PushPoison().
Verbose() [3/4]
static void KScheduler::Verbose (const int a) inline static
Definition at line 58 of file KScheduler.h.
Verbose() [4/4]
static void KScheduler::Verbose (const int a) inline static
Definition at line 83 of file KScheduler.h.
Member Data Documentation
kTrackArrQueue
std::queue< TClonesArray * > KScheduler::kTrackArrQueue
Definition at line 102 of file KScheduler.h.
Referenced by Init(), KJob::KJob(), KJob::~KJob(), and ~KScheduler().
ktrkqESem
TSemaphore * KScheduler::ktrkqESem
Definition at line 99 of file KScheduler.h.
Referenced by Init(), KJob::KJob(), KJob::~KJob(), and ~KScheduler().
ktrkqFSem
TSemaphore * KScheduler::ktrkqFSem
Definition at line 98 of file KScheduler.h.
Referenced by Init(), KJob::KJob(), KJob::~KJob(), and ~KScheduler().
ktrkQueueMutex
TMutex * KScheduler::ktrkQueueMutex
Definition at line 95 of file KScheduler.h.
Referenced by Init(), KJob::KJob(), KJob::~KJob(), and ~KScheduler().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/kTThreads/KScheduler.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/kTThreads/KScheduler.cxx
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/MultiThreadReco/src/KScheduler.cc