Class Reference for E1039 Core & Analysis Software: SQSpill Class Reference
SQSpill Class Reference
An SQ interface class to hold the data of one spill.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSpill.h>
Public Member Functions
virtual ~SQSpill ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual SQSpill * Clone () const
virtual int get_run_id () const
Return the run ID when this spill was taken.
virtual void set_run_id (const int a)
virtual int get_spill_id () const
Return the spill ID.
virtual void set_spill_id (const int a)
virtual short get_target_pos () const
Return the target position in this spill.
virtual void set_target_pos (const short a)
virtual int get_bos_coda_id () const
[Obsolete] Use SQHardSpill instead.
virtual void set_bos_coda_id (const int a)
virtual int get_bos_vme_time () const
[Obsolete] Use SQHardSpill instead.
virtual void set_bos_vme_time (const int a)
virtual int get_eos_coda_id () const
[Obsolete] Use SQHardSpill instead.
virtual void set_eos_coda_id (const int a)
virtual int get_eos_vme_time () const
[Obsolete] Use SQHardSpill instead.
virtual void set_eos_vme_time (const int a)
virtual SQStringMap * get_bos_scaler_list ()
Return the list of scaler variables read out at BOS.
virtual SQStringMap * get_eos_scaler_list ()
Return the list of scaler variables read out at EOS.
virtual SQStringMap * get_slow_cont_list ()
Return the list of slow control variables.
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQSpill ()
Detailed Description
An SQ interface class to hold the data of one spill.
Definition at line 19 of file SQSpill.h.
Constructor & Destructor Documentation
~SQSpill()
virtual SQSpill::~SQSpill () inline virtual
Definition at line 21 of file SQSpill.h.
SQSpill()
SQSpill::SQSpill () inline protected
Definition at line 70 of file SQSpill.h.
Member Function Documentation
Clone()
virtual SQSpill* SQSpill::Clone () const inline virtual
Reimplemented in SQSpill_v2, and SQSpill_v1.
Definition at line 30 of file SQSpill.h.
References NULL.
Referenced by SQSpillMap_v1::insert(), SQSpillMap_v1::operator=(), and SQSpillMap_v1::SQSpillMap_v1().
get_bos_coda_id()
virtual int SQSpill::get_bos_coda_id () const inline virtual
[Obsolete] Use SQHardSpill instead.
Reimplemented in SQSpill_v2.
Definition at line 45 of file SQSpill.h.
get_bos_scaler_list()
virtual SQStringMap* SQSpill::get_bos_scaler_list () inline virtual
Return the list of scaler variables read out at BOS.
Reimplemented in SQSpill_v2.
Definition at line 61 of file SQSpill.h.
Referenced by Fun4AllEVIOInputManager::run().
get_bos_vme_time()
virtual int SQSpill::get_bos_vme_time () const inline virtual
[Obsolete] Use SQHardSpill instead.
Reimplemented in SQSpill_v2.
Definition at line 49 of file SQSpill.h.
get_eos_coda_id()
virtual int SQSpill::get_eos_coda_id () const inline virtual
[Obsolete] Use SQHardSpill instead.
Reimplemented in SQSpill_v2.
Definition at line 53 of file SQSpill.h.
get_eos_scaler_list()
virtual SQStringMap* SQSpill::get_eos_scaler_list () inline virtual
Return the list of scaler variables read out at EOS.
Reimplemented in SQSpill_v2.
Definition at line 64 of file SQSpill.h.
Referenced by Fun4AllEVIOInputManager::run().
get_eos_vme_time()
virtual int SQSpill::get_eos_vme_time () const inline virtual
[Obsolete] Use SQHardSpill instead.
Reimplemented in SQSpill_v2.
Definition at line 57 of file SQSpill.h.
get_run_id()
virtual int SQSpill::get_run_id () const inline virtual
Return the run ID when this spill was taken.
Reimplemented in SQSpill_v2, and SQSpill_v1.
Definition at line 33 of file SQSpill.h.
get_slow_cont_list()
virtual SQStringMap* SQSpill::get_slow_cont_list () inline virtual
Return the list of slow control variables.
Reimplemented in SQSpill_v2.
Definition at line 67 of file SQSpill.h.
Referenced by Fun4AllEVIOInputManager::run().
get_spill_id()
virtual int SQSpill::get_spill_id () const inline virtual
Return the spill ID.
Reimplemented in SQSpill_v2, and SQSpill_v1.
Definition at line 37 of file SQSpill.h.
Referenced by SQSpillMap_v1::insert(), SQSpillMap_v1::operator=(), and SQSpillMap_v1::SQSpillMap_v1().
get_target_pos()
virtual short SQSpill::get_target_pos () const inline virtual
Return the target position in this spill.
Reimplemented in SQSpill_v2, and SQSpill_v1.
Definition at line 41 of file SQSpill.h.
Referenced by UtilSRawEvent::SetSpill().
identify()
virtual void SQSpill::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SQSpill_v2, and SQSpill_v1.
Definition at line 25 of file SQSpill.h.
isValid()
virtual int SQSpill::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SQSpill_v2, and SQSpill_v1.
Definition at line 29 of file SQSpill.h.
Reset()
virtual void SQSpill::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SQSpill_v2, and SQSpill_v1.
Definition at line 28 of file SQSpill.h.
set_bos_coda_id()
virtual void SQSpill::set_bos_coda_id (const int a) inline virtual
Reimplemented in SQSpill_v2.
Definition at line 46 of file SQSpill.h.
set_bos_vme_time()
virtual void SQSpill::set_bos_vme_time (const int a) inline virtual
Reimplemented in SQSpill_v2.
Definition at line 50 of file SQSpill.h.
set_eos_coda_id()
virtual void SQSpill::set_eos_coda_id (const int a) inline virtual
Reimplemented in SQSpill_v2.
Definition at line 54 of file SQSpill.h.
set_eos_vme_time()
virtual void SQSpill::set_eos_vme_time (const int a) inline virtual
Reimplemented in SQSpill_v2.
Definition at line 58 of file SQSpill.h.
set_run_id()
virtual void SQSpill::set_run_id (const int a) inline virtual
Reimplemented in SQSpill_v2, and SQSpill_v1.
Definition at line 34 of file SQSpill.h.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), and Fun4AllEVIOInputManager::run().
set_spill_id()
virtual void SQSpill::set_spill_id (const int a) inline virtual
Reimplemented in SQSpill_v2, and SQSpill_v1.
Definition at line 38 of file SQSpill.h.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), and Fun4AllEVIOInputManager::run().
set_target_pos()
virtual void SQSpill::set_target_pos (const short a) inline virtual
Reimplemented in SQSpill_v2, and SQSpill_v1.
Definition at line 42 of file SQSpill.h.
Referenced by Fun4AllEVIOInputManager::run().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSpill.h