Class Reference for E1039 Core & Analysis Software: recoConsts Class Reference
recoConsts Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/recoConsts.h>
Public Member Functions
void set_defaults ()
set the default value for all the constants needed - user is supposed to add a default value here to introduce new constants
void init (int runNo=0, bool verbose=false)
initialize the constants by the runNo - not implemented yet
void init (const std::string &setname, bool verbose=false)
initialize the constants by pre-defined parameter set name - not implemented yet
void initfile (const std::string &filename, bool verbose=false)
initialize by reading a file
virtual void set_CharFlag (const std::string &name, const std::string &flag)
overide the virtual function to expand the environmental variables
void Print () const
print all the parameters
Public Member Functions inherited from PHFlag
PHFlag ()
virtual ~PHFlag ()
virtual const std::string get_CharFlag (const std::string &flag) const
virtual const std::string get_CharFlag (const std::string &name, const std::string &defaultval)
virtual double get_DoubleFlag (const std::string &name) const
virtual double get_DoubleFlag (const std::string &name, const double defaultval)
virtual void set_DoubleFlag (const std::string &name, const double flag)
virtual float get_FloatFlag (const std::string &name) const
virtual float get_FloatFlag (const std::string &name, const float defaultval)
virtual void set_FloatFlag (const std::string &name, const float flag)
virtual int get_IntFlag (const std::string &name) const
virtual int get_IntFlag (const std::string &name, const int defaultval)
virtual void set_IntFlag (const std::string &name, const int flag)
virtual bool get_BoolFlag (const std::string &name) const
virtual bool get_BoolFlag (const std::string &name, const bool defaultval)
virtual void set_BoolFlag (const std::string &name, const bool flag)
virtual void PrintDoubleFlags () const
virtual void PrintIntFlags () const
virtual void PrintFloatFlags () const
virtual void PrintCharFlags () const
virtual void PrintBoolFlags () const
virtual void ReadFromFile (const std::string &name, bool verbose=false)
virtual void WriteToFile (const std::string &name)
virtual int FlagExist (const std::string &name) const
virtual const std::map
< std::string, int > * IntMap () const
virtual const std::map
< std::string, float > * FloatMap () const
virtual const std::map
< std::string, double > * DoubleMap () const
virtual const std::map
< std::string, std::string > * CharMap () const
virtual const std::map
< std::string, bool > * BoolMap () const
Static Public Member Functions
static recoConsts * instance ()
Protected Member Functions
recoConsts ()
std::string ExpandEnvironmentals (const std::string &input)
Static Protected Attributes
static recoConsts * __instance = nullptr
Additional Inherited Members
Protected Attributes inherited from PHFlag
std::map< std::string, int > intflag
std::map< std::string, double > doubleflag
std::map< std::string, float > floatflag
std::map< std::string,
std::string > charflag
std::map< std::string, bool > boolflag
Detailed Description
This class instantiates a singleton object that can be accessed via recoConsts::instance() User is expected to do the following at the begining of the user macro:
recoConsts* rc = recoConsts::instance(); // get an instance of the recoConsts
rc->init(runNo); // initiatiate the constants by run numer, or
rc->init("cosmic"); // initiatiate the constants by a pre-defined parameter set, or
rc->initfile("const.txt"); //initialize the constants by reading a file, or
rc->set_DoubleFlag("something", somevalue); // set specific constants individually
Definition at line 17 of file recoConsts.h.
Constructor & Destructor Documentation
recoConsts::recoConsts () protected
Definition at line 18 of file recoConsts.cc.
Referenced by instance().
Member Function Documentation
std::string recoConsts::ExpandEnvironmentals (const std::string & input) protected
Definition at line 27 of file recoConsts.cc.
Referenced by set_CharFlag().
void recoConsts::init (int runNo = 0, bool verbose = false)
initialize the constants by the runNo - not implemented yet
Definition at line 157 of file recoConsts.cc.
Referenced by Fun4Sim(), RecoE1039Data(), RecoE1039Sim(), and run().
void recoConsts::init (const std::string & setname, bool verbose = false)
initialize the constants by pre-defined parameter set name - not implemented yet
Definition at line 163 of file recoConsts.cc.
References Print(), PHFlag::set_BoolFlag(), and PHFlag::set_DoubleFlag().
void recoConsts::initfile (const std::string & filename, bool verbose = false)
initialize by reading a file
Definition at line 179 of file recoConsts.cc.
References PHFlag::ReadFromFile().
recoConsts * recoConsts::instance () static
Definition at line 7 of file recoConsts.cc.
References __instance, recoConsts(), and set_defaults().
Referenced by PHG4PhenixDetector::Construct(), Fun4AllHistoManager::dumpHistos(), Fun4AllServer::End(), EventDisplay4Sim(), EventReducer::EventReducer(), Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), Fun4All_ExportGeom(), Fun4All_ImportGeom(), Fun4CODA(), Fun4DQ(), Fun4DST(), Fun4MainDaq(), Fun4Sim(), Fun4Sim_TrkQA(), Fun4SRawEvent(), PHGeomUtility::GetVerbosity(), TriggerAnalyzer::init(), GeomSvc::init(), Fun4AllPrdfOutputManager::InitPrdfManager(), PHG4Reco::InitRun(), VertexFit::InitRun(), PHRandomSeed::InitSeed(), KalmanFastTracking::KalmanFastTracking(), main(), PHGeom_DSTInspection(), HepMCNodeReader::process_event(), RecoE1039Data(), RecoE1039Sim(), RecoE906Data(), run(), Fun4AllServer::run(), Fun4AllServer::setRun(), Fun4AllDummyInputManager::setSyncManager(), PHGeomUtility::SetVerbosity(), SQReco::SQReco(), and Fun4AllServer::~Fun4AllServer().
void recoConsts::Print () const virtual
print all the parameters
Reimplemented from PHFlag.
Definition at line 185 of file recoConsts.cc.
References PHFlag::PrintBoolFlags(), PHFlag::PrintCharFlags(), PHFlag::PrintDoubleFlags(), PHFlag::PrintFloatFlags(), and PHFlag::PrintIntFlags().
Referenced by EventDisplay4Sim(), Fun4CODA(), Fun4DQ(), Fun4DST(), Fun4MainDaq(), Fun4Sim(), Fun4Sim_TrkQA(), Fun4SRawEvent(), init(), main(), RecoE1039Data(), RecoE1039Sim(), RecoE906Data(), and run().
void recoConsts::set_CharFlag (const std::string & name, const std::string & flag) virtual
overide the virtual function to expand the environmental variables
Reimplemented from PHFlag.
Definition at line 21 of file recoConsts.cc.
References PHFlag::charflag, and ExpandEnvironmentals().
Referenced by PHG4PhenixDetector::Construct(), Fun4DQ(), and set_defaults().
void recoConsts::set_defaults ()
set the default value for all the constants needed - user is supposed to add a default value here to introduce new constants
Definition at line 39 of file recoConsts.cc.
References PHFlag::set_BoolFlag(), set_CharFlag(), PHFlag::set_DoubleFlag(), and PHFlag::set_IntFlag().
Referenced by instance().
Member Data Documentation
recoConsts * recoConsts::__instance = nullptr static protected
Definition at line 44 of file recoConsts.h.
Referenced by instance().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/recoConsts.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/recoConsts.cc