Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/macros/UploadChanMap.C File Reference
UploadChanMap.C File Reference
Macro to upload the channel mapping from tsv file to MySQL DB.
Functions
int UploadChanMap (const std::string type="taiwan", const std::string map_id="2019091301")
int CheckChanMap (const std::string type="taiwan", const int run=25000)
int MakeChanMap ()
Test function to make a channel mapping by hand.
Detailed Description
Macro to upload the channel mapping from tsv file to MySQL DB.
The channel mapping of each subsystem is managed by subsystem expert, including all versions and applicable run ranges. Below shows the procedure for first converting the original mapping file to the common-format tsv file and then upload it to MySQL DB. It is usually done by the online software manager, but can be done by subsystem expert.
Taiwan TDC
Create a new mapping file in the original format of each subsystem. Below are all the subsystems using Taiwan TDC and their directories:
Hodoscope: ??
DP hodo: ??
Trigger: ??
Chamber: /data2/chambers/mapping/channel_mapping
Prop Tube: ??
Convert the mapping file to the common-format tsv file. There should be a script per subsystem for this conversion.
Name the new mapping. It is usually "[year][month][day][serial]", e.g. "2020113001". Then create a directory for it by copying the previous one, e.g. "2020012301":
cd /data2/e1039/resource/chan_map/taiwan
cp -a 2020012301 2020113001
Copy the new tsv file ("cham.tsv" as example) into the directory:
cp -p /path/to/cham.tsv /data2/e1039/resource/chan_map/taiwan/2020113001/sub
Merge the tsv files of all subsystems:
cd /data2/e1039/resource/chan_map/taiwan/2020113001
./merge.sh
Define a run range for the new mapping by editing "run_range.tsv".
Upload the new mapping by executing "UploadChanMap.C", where you have to replace the number "123456" below with a run number in the run range for the new mapping:
source /data2/e1039/this-e1039.sh
cd /data2/e1039/core/default/macros/packages/geom_svc
root -b
.L UploadChanMap.C
UploadChanMap("taiwan", "2020113001");
CheckChanMap ("taiwan", 123456);
V1495 TDC
To be written.
Main-DAQ Scaler
To be written.
Definition in file UploadChanMap.C.
Function Documentation
int CheckChanMap (const std::string type = "taiwan", const int run = 25000)
Definition at line 80 of file UploadChanMap.C.
References RunParamBase::ReadFromDB(), run(), RunParamBase::SetMapIDbyDB(), and RunParamBase::WriteToLocalFile().
int MakeChanMap ()
Test function to make a channel mapping by hand.
roc, board chan, det, ele
Definition at line 99 of file UploadChanMap.C.
References ChanMapTaiwan::Add(), ChanMapTaiwan::Print(), and RunParamBase::WriteToLocalFile().
int UploadChanMap (const std::string type = "taiwan", const std::string map_id = "2019091301")
Definition at line 60 of file UploadChanMap.C.
References RunParamBase::ReadFromFile(), RunParamBase::SetMapIDbyFile(), RunParamBase::WriteRangeToDB(), RunParamBase::WriteToDB(), and RunParamBase::WriteToLocalFile().