E1039 Software: SRecDimuon Class Reference
SRecDimuon Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/SRecEvent.h>
Public Member Functions
void identify (std::ostream &os=std::cout) const
PHObject virtual overloads.
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SRecDimuon * Clone () const
TLorentzVector getVPhoton ()
void calcVariables ()
bool isTarget ()
bool isDump ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Public Attributes
Int_t trackID_pos
Int_t trackID_neg
TLorentzVector p_pos
TLorentzVector p_neg
TLorentzVector p_pos_single
TLorentzVector p_neg_single
TVector3 vtx
TVector3 vtx_pos
TVector3 vtx_neg
TVector3 proj_target_pos
TVector3 proj_dump_pos
TVector3 proj_target_neg
TVector3 proj_dump_neg
Double_t mass
Double_t pT
Double_t xF
Double_t x1
Double_t x2
Double_t costh
Double_t phi
Double_t mass_single
Double_t chisq_single
Double_t chisq_kf
Double_t chisq_vx
Double_t chisq_target
Double_t chisq_dump
Double_t chisq_upstream
Detailed Description
Definition at line 231 of file SRecEvent.h.
Member Function Documentation
calcVariables()
void SRecDimuon::calcVariables ()
Definition at line 492 of file SRecEvent.cxx.
Clone()
SRecDimuon* SRecDimuon::Clone () const inline
Definition at line 239 of file SRecEvent.h.
getVPhoton()
TLorentzVector SRecDimuon::getVPhoton () inline
Definition at line 242 of file SRecEvent.h.
References SRecTrack::isDump(), and SRecTrack::isTarget().
identify()
void SRecDimuon::identify (std::ostream & os = std::cout) const inline virtual
PHObject virtual overloads.
Reimplemented from PHObject.
Definition at line 236 of file SRecEvent.h.
isDump()
bool SRecDimuon::isDump ()
Definition at line 560 of file SRecEvent.cxx.
isTarget()
bool SRecDimuon::isTarget ()
Definition at line 544 of file SRecEvent.cxx.
isValid()
int SRecDimuon::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 519 of file SRecEvent.cxx.
References recoConsts::instance().
Reset()
void SRecDimuon::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 237 of file SRecEvent.h.
References SRecTrack::isValid().
Member Data Documentation
chisq_dump
Double_t SRecDimuon::chisq_dump
Definition at line 296 of file SRecEvent.h.
chisq_kf
Double_t SRecDimuon::chisq_kf
Definition at line 291 of file SRecEvent.h.
chisq_single
Double_t SRecDimuon::chisq_single
Definition at line 288 of file SRecEvent.h.
chisq_target
Double_t SRecDimuon::chisq_target
Definition at line 295 of file SRecEvent.h.
chisq_upstream
Double_t SRecDimuon::chisq_upstream
Definition at line 297 of file SRecEvent.h.
chisq_vx
Double_t SRecDimuon::chisq_vx
Definition at line 292 of file SRecEvent.h.
costh
Double_t SRecDimuon::costh
Definition at line 285 of file SRecEvent.h.
mass
Double_t SRecDimuon::mass
Definition at line 280 of file SRecEvent.h.
mass_single
Double_t SRecDimuon::mass_single
Definition at line 287 of file SRecEvent.h.
p_neg
TLorentzVector SRecDimuon::p_neg
Definition at line 262 of file SRecEvent.h.
p_neg_single
TLorentzVector SRecDimuon::p_neg_single
Definition at line 266 of file SRecEvent.h.
p_pos
TLorentzVector SRecDimuon::p_pos
Definition at line 261 of file SRecEvent.h.
p_pos_single
TLorentzVector SRecDimuon::p_pos_single
Definition at line 265 of file SRecEvent.h.
phi
Double_t SRecDimuon::phi
Definition at line 286 of file SRecEvent.h.
proj_dump_neg
TVector3 SRecDimuon::proj_dump_neg
Definition at line 277 of file SRecEvent.h.
proj_dump_pos
TVector3 SRecDimuon::proj_dump_pos
Definition at line 275 of file SRecEvent.h.
proj_target_neg
TVector3 SRecDimuon::proj_target_neg
Definition at line 276 of file SRecEvent.h.
proj_target_pos
TVector3 SRecDimuon::proj_target_pos
Definition at line 274 of file SRecEvent.h.
pT
Double_t SRecDimuon::pT
Definition at line 281 of file SRecEvent.h.
trackID_neg
Int_t SRecDimuon::trackID_neg
Definition at line 258 of file SRecEvent.h.
trackID_pos
Int_t SRecDimuon::trackID_pos
Definition at line 257 of file SRecEvent.h.
vtx
TVector3 SRecDimuon::vtx
Definition at line 269 of file SRecEvent.h.
vtx_neg
TVector3 SRecDimuon::vtx_neg
Definition at line 271 of file SRecEvent.h.
vtx_pos
TVector3 SRecDimuon::vtx_pos
Definition at line 270 of file SRecEvent.h.
x1
Double_t SRecDimuon::x1
Definition at line 283 of file SRecEvent.h.
x2
Double_t SRecDimuon::x2
Definition at line 284 of file SRecEvent.h.
xF
Double_t SRecDimuon::xF
Definition at line 282 of file SRecEvent.h.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/SRecEvent.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/SRecEvent.cxx