Class Reference for E1039 Core & Analysis Software: SyncObjectv1 Class Reference
SyncObjectv1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/SyncObjectv1.h>
Public Member Functions
SyncObjectv1 ()
ctor
SyncObjectv1 (const SyncObject &)
SyncObjectv1 * clone () const
Virtual copy constructor.
virtual ~SyncObjectv1 ()
dtor
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
int isValid () const
isValid returns non zero if object contains valid data
void EventCounter (const int ival)
set Event Counter
void EventNumber (const int ival)
set Event Number
void RunNumber (const int ival)
set Run Number
Public Member Functions inherited from SyncObject
virtual ~SyncObject ()
dtor
virtual SyncObject & operator= (const SyncObject &source)
virtual int Different (const SyncObject *other) const
virtual void SegmentNumber (const int)
set Segment Number
virtual ~SyncObject ()
dtor
virtual SyncObject & operator= (const SyncObject &source)
virtual int Different (const SyncObject *other) const
virtual void SegmentNumber (const int)
set Segment Number
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
int EventCounter () const
get Event Counter
int EventNumber () const
get Event Number
int RunNumber () const
get Run Number
Protected Member Functions inherited from SyncObject
virtual int SegmentNumber () const
get Segment Number
virtual int SegmentNumber () const
get Segment Number
Protected Attributes
int eventcounter
int eventnumber
int runnumber
Detailed Description
Definition at line 7 of file SyncObjectv1.h.
Constructor & Destructor Documentation
SyncObjectv1() [1/2]
SyncObjectv1::SyncObjectv1 ()
ctor
Referenced by clone().
SyncObjectv1() [2/2]
SyncObjectv1::SyncObjectv1 (const SyncObject & source)
Definition at line 14 of file SyncObjectv1.cc.
References EventCounter(), SyncObject::EventCounter(), EventNumber(), SyncObject::EventNumber(), RunNumber(), and SyncObject::RunNumber().
~SyncObjectv1()
virtual SyncObjectv1::~SyncObjectv1 () inline virtual
dtor
Definition at line 17 of file SyncObjectv1.h.
Member Function Documentation
clone()
SyncObjectv1* SyncObjectv1::clone () const inline virtual
Virtual copy constructor.
Reimplemented from SyncObject.
Reimplemented in SyncObjectv2.
Definition at line 15 of file SyncObjectv1.h.
References SyncObjectv1().
EventCounter() [1/2]
int SyncObjectv1::EventCounter () const inline protected virtual
get Event Counter
Reimplemented from SyncObject.
Definition at line 41 of file SyncObjectv1.h.
References eventcounter.
Referenced by SyncObjectv1(), and SyncObjectv2::SyncObjectv2().
EventCounter() [2/2]
void SyncObjectv1::EventCounter (const int ival) inline virtual
set Event Counter
Reimplemented from SyncObject.
Definition at line 31 of file SyncObjectv1.h.
References eventcounter.
EventNumber() [1/2]
int SyncObjectv1::EventNumber () const inline protected virtual
get Event Number
Reimplemented from SyncObject.
Definition at line 43 of file SyncObjectv1.h.
References eventnumber.
Referenced by SyncObjectv1(), and SyncObjectv2::SyncObjectv2().
EventNumber() [2/2]
void SyncObjectv1::EventNumber (const int ival) inline virtual
set Event Number
Reimplemented from SyncObject.
Definition at line 34 of file SyncObjectv1.h.
References eventnumber.
identify()
void SyncObjectv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SyncObject.
Reimplemented in SyncObjectv2.
Definition at line 29 of file SyncObjectv1.cc.
References eventcounter, eventnumber, and runnumber.
isValid()
int SyncObjectv1::isValid () const virtual
isValid returns non zero if object contains valid data
Reimplemented from SyncObject.
Definition at line 40 of file SyncObjectv1.cc.
References eventcounter.
Reset()
void SyncObjectv1::Reset () virtual
Clear Event.
Reimplemented from SyncObject.
Reimplemented in SyncObjectv2.
Definition at line 21 of file SyncObjectv1.cc.
References eventcounter, eventnumber, and runnumber.
Referenced by SyncObjectv2::Reset().
RunNumber() [1/2]
int SyncObjectv1::RunNumber () const inline protected virtual
get Run Number
Reimplemented from SyncObject.
Definition at line 45 of file SyncObjectv1.h.
References runnumber.
Referenced by SyncObjectv1(), and SyncObjectv2::SyncObjectv2().
RunNumber() [2/2]
void SyncObjectv1::RunNumber (const int ival) inline virtual
set Run Number
Reimplemented from SyncObject.
Definition at line 37 of file SyncObjectv1.h.
References runnumber.
Member Data Documentation
eventcounter
int SyncObjectv1::eventcounter protected
Definition at line 47 of file SyncObjectv1.h.
Referenced by EventCounter(), identify(), SyncObjectv2::identify(), isValid(), and Reset().
eventnumber
int SyncObjectv1::eventnumber protected
Definition at line 48 of file SyncObjectv1.h.
Referenced by EventNumber(), identify(), SyncObjectv2::identify(), and Reset().
runnumber
int SyncObjectv1::runnumber protected
Definition at line 49 of file SyncObjectv1.h.
Referenced by identify(), SyncObjectv2::identify(), Reset(), and RunNumber().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/SyncObjectv1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/SyncObjectv1.cc