E1039 Software: OnlMonClient Class Reference
OnlMonClient Class Reference
Base class for the OnlMon subsystem module.
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/online/onlmonserver/OnlMonClient.h>
Public Member Functions
OnlMonClient ()
virtual ~OnlMonClient ()
virtual OnlMonClient * Clone ()
void Title (const std::string &title)
std::string Title ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void GetBasicID (int *run_id=0, int *spill_id=0, int *event_id=0, int *spill_id_min=0, int *spill_id_max=0)
void GetBasicCount (int *n_evt=0, int *n_sp=0)
int StartMonitor ()
TH1 * FindMonHist (const std::string name, const bool non_null=true)
virtual int InitOnlMon (PHCompositeNode *topNode)
virtual int InitRunOnlMon (PHCompositeNode *topNode)
virtual int ProcessEventOnlMon (PHCompositeNode *topNode)
virtual int EndOnlMon (PHCompositeNode *topNode)
virtual int FindAllMonHist ()
virtual int DrawMonitor ()
int SendHist (TSocket *sock, int sp_min, int sp_max)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static void SetClearUsFlag (const bool val)
static bool GetClearUsFlag ()
Protected Types
enum HistMode_t { MODE_ADD, MODE_UPDATE }
Protected Member Functions
void RegisterHist (TH1 *h1, const HistMode_t mode=MODE_ADD)
void NumCanvases (const int num)
int NumCanvases ()
OnlMonCanvas * GetCanvas (const int num=0)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Private Types
enum BasicIdBin_t {
BIN_RUN = 1, BIN_SPILL = 2, BIN_EVENT = 3, BIN_SPILL_MIN = 4,
BIN_SPILL_MAX = 5
}
enum BasicInfoBin_t { BIN_N_EVT = 1, BIN_N_SP = 2 }
typedef std::map< std::string,
HistMode_t > HistModeMap_t
typedef std::vector< TH1 * > HistList_t
typedef std::map< int, TH1 * > SpillHistMap_t
typedef std::map< std::string,
SpillHistMap_t > Name2SpillHistMap_t
typedef std::vector
< OnlMonClient * > SelfList_t
List of OnlMonClient objects created. Used to clear all canvases opened by all objects.
Private Member Functions
void ClearSpillHist ()
void MakeSpillHist (const int spill_id, const int spill_id_new=0)
void DisableSpillHist ()
void MakeMergedHist (HistList_t &list_h1, const int sp_min=0, const int sp_max=0)
int ReceiveHist ()
void ClearHistList (HistList_t &list_h1)
void ClearCanvasList ()
int DrawCanvas (const bool at_end=false)
Private Attributes
std::string m_title
Fun4AllHistoManager * m_hm
int m_n_can
OnlMonCanvas * m_list_can [9]
HistModeMap_t m_hist_mode
TH1 * m_h1_basic_id
TH1 * m_h1_basic_cnt
HistList_t m_list_h1
Name2SpillHistMap_t m_map_hist_sp
int m_spill_id_pre
bool m_make_sp_hist
Static Private Attributes
static SelfList_t m_list_us
static bool m_bl_clear_us = true
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Base class for the OnlMon subsystem module.
All OnlMon histograms are held by "m_hm" via RegisterHist(). They are used in
Being filled in process_event() and
Being saved into ROOT file in SendHist().
Spill-by-spill histograms are by default created and held by "m_map_hist_sp". A set per spill is created when a new spill is found in process_event(). The creation is disabled when
Fun4MainDaq.C starts in the offline mode (via OnlMonServer::GetOnline()) or
The number of spills processed exceeds "m_n_sp_max_hist". Spill-by-spill histograms are merged via MakeMergedHist() when
The creation is disabled in process_event(),
They are sent to the viewer in SendHist() or
They are saved in End().
Todo:
We had better not use "m_hm" but only a set of HistList_t to hold histograms, so that we can reduce the number of operations to copy histograms.
A count in spill-by-spill histogram is not correct when it is an accumulated number over one run (i.e. MODE_UPDATE). Should we take a difference from its number in previous spill?
Definition at line 35 of file OnlMonClient.h.
Member Typedef Documentation
typedef std::vector<TH1*> OnlMonClient::HistList_t private
Definition at line 53 of file OnlMonClient.h.
typedef std::map<std::string, HistMode_t> OnlMonClient::HistModeMap_t private
Definition at line 45 of file OnlMonClient.h.
typedef std::map<std::string, SpillHistMap_t> OnlMonClient::Name2SpillHistMap_t private
Definition at line 57 of file OnlMonClient.h.
typedef std::vector<OnlMonClient*> OnlMonClient::SelfList_t private
List of OnlMonClient objects created. Used to clear all canvases opened by all objects.
Definition at line 63 of file OnlMonClient.h.
typedef std::map<int, TH1*> OnlMonClient::SpillHistMap_t private
Definition at line 56 of file OnlMonClient.h.
Member Enumeration Documentation
enum OnlMonClient::BasicIdBin_t private
Enumerator
BIN_RUN
BIN_SPILL
BIN_EVENT
BIN_SPILL_MIN
BIN_SPILL_MAX
Definition at line 48 of file OnlMonClient.h.
enum OnlMonClient::BasicInfoBin_t private
Enumerator
BIN_N_EVT
BIN_N_SP
Definition at line 49 of file OnlMonClient.h.
enum OnlMonClient::HistMode_t protected
Enumerator
MODE_ADD
MODE_UPDATE
Definition at line 37 of file OnlMonClient.h.
Constructor & Destructor Documentation
OnlMonClient::OnlMonClient ()
Definition at line 26 of file OnlMonClient.cc.
References m_list_can, and m_list_us.
OnlMonClient::~OnlMonClient () virtual
Definition at line 40 of file OnlMonClient.cc.
References ClearCanvasList(), ClearHistList(), ClearSpillHist(), m_hm, m_list_h1, and m_list_us.
Member Function Documentation
void OnlMonClient::ClearCanvasList () private
Definition at line 473 of file OnlMonClient.cc.
References m_list_can, and m_n_can.
Referenced by End(), StartMonitor(), and ~OnlMonClient().
void OnlMonClient::ClearHistList (HistList_t & list_h1) private
Definition at line 456 of file OnlMonClient.cc.
Referenced by DisableSpillHist(), End(), MakeMergedHist(), ReceiveHist(), SendHist(), and ~OnlMonClient().
void OnlMonClient::ClearSpillHist () private
Definition at line 311 of file OnlMonClient.cc.
References m_map_hist_sp.
Referenced by DisableSpillHist(), and ~OnlMonClient().
OnlMonClient * OnlMonClient::Clone () virtual
Reimplemented in OnlMonV1495, OnlMonH4, OnlMonHodo, OnlMonCham, OnlMonProp, OnlMonMainDaq, OnlMonTrigSig, and OnlMonTrigNim.
Definition at line 49 of file OnlMonClient.cc.
void OnlMonClient::DisableSpillHist () private
This function overwrites the contents of "m_hist_h1". Thus "m_hist_h1" must be empty when this function is called.
Definition at line 348 of file OnlMonClient.cc.
References ClearHistList(), ClearSpillHist(), Fun4AllHistoManager::getHisto(), OnlMonComm::instance(), m_hm, m_make_sp_hist, m_map_hist_sp, MakeMergedHist(), Fun4AllHistoManager::nHistos(), and OnlMonComm::SetSpillSelectability().
Referenced by End(), Init(), and process_event().
int OnlMonClient::DrawCanvas (const bool at_end = false) private
Definition at line 483 of file OnlMonClient.cc.
References DrawMonitor(), FindAllMonHist(), FindMonHist(), GetBasicCount(), GetBasicID(), m_h1_basic_cnt, m_h1_basic_id, m_list_can, m_n_can, Fun4AllBase::Name(), OnlMonCanvas::PostDraw(), OnlMonCanvas::PreDraw(), OnlMonCanvas::SetBasicCount(), OnlMonCanvas::SetBasicID(), and Title().
Referenced by End(), and StartMonitor().
int OnlMonClient::DrawMonitor () virtual
Reimplemented in OnlMonV1495, OnlMonH4, OnlMonHodo, OnlMonCham, OnlMonProp, OnlMonMainDaq, OnlMonTrigSig, OnlMonReco, and OnlMonTrigNim.
Definition at line 220 of file OnlMonClient.cc.
Referenced by DrawCanvas().
int OnlMonClient::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 128 of file OnlMonClient.cc.
References ClearCanvasList(), ClearHistList(), DisableSpillHist(), DrawCanvas(), Fun4AllHistoManager::dumpHistos(), EndOnlMon(), Fun4AllReturnCodes::EVENT_OK, GetBasicID(), Fun4AllHistoManager::getHisto(), UtilOnline::GetOnlMonDir(), m_hm, m_list_h1, m_make_sp_hist, m_spill_id_pre, MakeSpillHist(), Fun4AllBase::Name(), and Fun4AllHistoManager::nHistos().
int OnlMonClient::EndOnlMon (PHCompositeNode * topNode) virtual
Reimplemented in OnlMonV1495, OnlMonH4, OnlMonHodo, OnlMonCham, OnlMonProp, OnlMonMainDaq, OnlMonTrigSig, OnlMonReco, and OnlMonTrigNim.
Definition at line 208 of file OnlMonClient.cc.
Referenced by End().
int OnlMonClient::FindAllMonHist () virtual
Reimplemented in OnlMonV1495, OnlMonH4, OnlMonHodo, OnlMonCham, OnlMonProp, OnlMonMainDaq, OnlMonTrigSig, OnlMonReco, and OnlMonTrigNim.
Definition at line 214 of file OnlMonClient.cc.
Referenced by DrawCanvas().
TH1 * OnlMonClient::FindMonHist (const std::string name, const bool non_null = true)
Definition at line 178 of file OnlMonClient.cc.
References m_list_h1.
Referenced by DrawCanvas(), OnlMonCham::FindAllMonHist(), OnlMonProp::FindAllMonHist(), OnlMonHodo::FindAllMonHist(), OnlMonH4::FindAllMonHist(), and OnlMonV1495::FindAllMonHist().
void OnlMonClient::GetBasicCount (int * n_evt = 0, int * n_sp = 0)
Definition at line 172 of file OnlMonClient.cc.
References BIN_N_EVT, BIN_N_SP, and m_h1_basic_cnt.
Referenced by DrawCanvas().
void OnlMonClient::GetBasicID (int * run_id = 0, int * spill_id = 0, int * event_id = 0, int * spill_id_min = 0, int * spill_id_max = 0)
Definition at line 163 of file OnlMonClient.cc.
References BIN_EVENT, BIN_RUN, BIN_SPILL, BIN_SPILL_MAX, BIN_SPILL_MIN, and m_h1_basic_id.
Referenced by DrawCanvas(), and End().
OnlMonCanvas * OnlMonClient::GetCanvas (const int num = 0) protected
Definition at line 464 of file OnlMonClient.cc.
References m_list_can, and m_n_can.
Referenced by OnlMonCham::DrawMonitor(), OnlMonProp::DrawMonitor(), OnlMonH4::DrawMonitor(), OnlMonHodo::DrawMonitor(), and OnlMonV1495::DrawMonitor().
static bool OnlMonClient::GetClearUsFlag () inline static
Definition at line 93 of file OnlMonClient.h.
References m_bl_clear_us.
Referenced by OnlMonUI::BuildInterface(), OnlMon4MainDaq(), and StartMonitor().
int OnlMonClient::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 55 of file OnlMonClient.cc.
References DisableSpillHist(), InitOnlMon(), and OnlMonServer::instance().
int OnlMonClient::InitOnlMon (PHCompositeNode * topNode) virtual
Reimplemented in OnlMonV1495, OnlMonH4, OnlMonHodo, OnlMonCham, OnlMonProp, OnlMonMainDaq, OnlMonTrigSig, OnlMonReco, and OnlMonTrigNim.
Definition at line 190 of file OnlMonClient.cc.
Referenced by Init().
int OnlMonClient::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
These settings will be applied to histograms created in InitRunOnlMon(). Fine tunes should be necessary in the future. Note: the label/title size is a percent of the pad height, and the offset is a relative scale to the default distance from axis.
Reimplemented from SubsysReco.
Definition at line 61 of file OnlMonClient.cc.
References Fun4AllReturnCodes::ABORTEVENT, BIN_RUN, SQRun::get_run_id(), InitRunOnlMon(), OnlMonServer::instance(), m_h1_basic_cnt, m_h1_basic_id, m_hm, Fun4AllBase::Name(), Fun4AllHistoManager::registerHisto(), and Fun4AllServer::registerHistoManager().
int OnlMonClient::InitRunOnlMon (PHCompositeNode * topNode) virtual
Reimplemented in OnlMonV1495, OnlMonH4, OnlMonHodo, OnlMonCham, OnlMonProp, OnlMonMainDaq, OnlMonTrigSig, OnlMonReco, and OnlMonTrigNim.
Definition at line 196 of file OnlMonClient.cc.
Referenced by InitRun().
void OnlMonClient::MakeMergedHist (HistList_t & list_h1, const int sp_min = 0, const int sp_max = 0) private
Definition at line 366 of file OnlMonClient.cc.
References BIN_EVENT, BIN_RUN, BIN_SPILL, BIN_SPILL_MAX, BIN_SPILL_MIN, ClearHistList(), Fun4AllHistoManager::getHisto(), m_hist_mode, m_hm, m_map_hist_sp, MODE_UPDATE, and Fun4AllHistoManager::nHistos().
Referenced by DisableSpillHist(), and SendHist().
void OnlMonClient::MakeSpillHist (const int spill_id, const int spill_id_new = 0) private
This function makes a set of histograms for the given spill ID, "spill_id". The set is copied from the histograms managed by "m_hm" into "m_map_hist_sp". When "spill_id_new" is given, a new entry for that spill is added to "m_map_hist_sp", which is just a set of pointers (not cloned objects) to the histograms managed by "m_hm".
Definition at line 328 of file OnlMonClient.cc.
References Fun4AllHistoManager::getHisto(), m_hm, m_map_hist_sp, and Fun4AllHistoManager::nHistos().
Referenced by End(), and process_event().
void OnlMonClient::NumCanvases (const int num) inline protected
Definition at line 100 of file OnlMonClient.h.
References m_n_can.
int OnlMonClient::NumCanvases () inline protected
Definition at line 101 of file OnlMonClient.h.
References m_n_can.
Referenced by OnlMonCham::OnlMonCham(), OnlMonH4::OnlMonH4(), OnlMonHodo::OnlMonHodo(), OnlMonProp::OnlMonProp(), and OnlMonV1495::OnlMonV1495().
int OnlMonClient::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 88 of file OnlMonClient.cc.
References Fun4AllReturnCodes::ABORTEVENT, OnlMonComm::AddSpill(), BIN_EVENT, BIN_N_EVT, BIN_N_SP, BIN_RUN, BIN_SPILL, BIN_SPILL_MAX, BIN_SPILL_MIN, DisableSpillHist(), OnlMonComm::GetMaxNumSelSpills(), OnlMonServer::GetMutex(), OnlMonComm::GetNumSpills(), OnlMonServer::instance(), OnlMonComm::instance(), m_h1_basic_cnt, m_h1_basic_id, m_make_sp_hist, m_spill_id_pre, MakeSpillHist(), Fun4AllBase::Name(), and ProcessEventOnlMon().
int OnlMonClient::ProcessEventOnlMon (PHCompositeNode * topNode) virtual
Reimplemented in OnlMonV1495, OnlMonH4, OnlMonHodo, OnlMonCham, OnlMonProp, OnlMonMainDaq, OnlMonTrigSig, OnlMonReco, and OnlMonTrigNim.
Definition at line 202 of file OnlMonClient.cc.
Referenced by process_event().
int OnlMonClient::ReceiveHist () private
Definition at line 400 of file OnlMonClient.cc.
References ClearHistList(), OnlMonComm::ConnectServer(), OnlMonComm::GetSpillNum(), OnlMonComm::GetSpillRange(), OnlMonComm::instance(), m_list_h1, Fun4AllBase::Name(), NULL, OnlMonComm::SP_ALL, OnlMonComm::SP_LAST, and OnlMonComm::SP_RANGE.
Referenced by StartMonitor().
void OnlMonClient::RegisterHist (TH1 * h1, const HistMode_t mode = MODE_ADD) protected
Definition at line 250 of file OnlMonClient.cc.
References m_hist_mode, m_hm, and Fun4AllHistoManager::registerHisto().
Referenced by OnlMonCham::InitRunOnlMon(), OnlMonProp::InitRunOnlMon(), OnlMonH4::InitRunOnlMon(), OnlMonHodo::InitRunOnlMon(), and OnlMonV1495::InitRunOnlMon().
int OnlMonClient::SendHist (TSocket * sock, int sp_min, int sp_max)
Definition at line 261 of file OnlMonClient.cc.
References ClearHistList(), OnlMonComm::FindFullSpillRange(), Fun4AllHistoManager::getHisto(), OnlMonServer::GetMutex(), OnlMonServer::instance(), OnlMonComm::instance(), m_hm, m_make_sp_hist, MakeMergedHist(), and Fun4AllHistoManager::nHistos().
Referenced by OnlMonServer::HandleConnection().
static void OnlMonClient::SetClearUsFlag (const bool val) inline static
Definition at line 92 of file OnlMonClient.h.
References m_bl_clear_us.
int OnlMonClient::StartMonitor ()
Definition at line 226 of file OnlMonClient.cc.
References ClearCanvasList(), DrawCanvas(), GetClearUsFlag(), m_list_us, and ReceiveHist().
Referenced by OnlMon4MainDaqSingle().
void OnlMonClient::Title (const std::string & title) inline
Definition at line 72 of file OnlMonClient.h.
References m_title.
std::string OnlMonClient::Title () inline
Definition at line 73 of file OnlMonClient.h.
References m_title.
Referenced by DrawCanvas(), OnlMonCham::OnlMonCham(), OnlMonH4::OnlMonH4(), OnlMonHodo::OnlMonHodo(), OnlMonProp::OnlMonProp(), and OnlMonV1495::OnlMonV1495().
Member Data Documentation
bool OnlMonClient::m_bl_clear_us = true static private
Definition at line 65 of file OnlMonClient.h.
Referenced by GetClearUsFlag(), and SetClearUsFlag().
TH1* OnlMonClient::m_h1_basic_cnt private
Definition at line 51 of file OnlMonClient.h.
Referenced by DrawCanvas(), GetBasicCount(), InitRun(), and process_event().
TH1* OnlMonClient::m_h1_basic_id private
Definition at line 50 of file OnlMonClient.h.
Referenced by DrawCanvas(), GetBasicID(), InitRun(), and process_event().
HistModeMap_t OnlMonClient::m_hist_mode private
Definition at line 46 of file OnlMonClient.h.
Referenced by MakeMergedHist(), and RegisterHist().
Fun4AllHistoManager* OnlMonClient::m_hm private
Definition at line 41 of file OnlMonClient.h.
Referenced by DisableSpillHist(), End(), InitRun(), MakeMergedHist(), MakeSpillHist(), RegisterHist(), SendHist(), and ~OnlMonClient().
OnlMonCanvas* OnlMonClient::m_list_can[9] private
Definition at line 43 of file OnlMonClient.h.
Referenced by ClearCanvasList(), DrawCanvas(), GetCanvas(), and OnlMonClient().
HistList_t OnlMonClient::m_list_h1 private
Definition at line 54 of file OnlMonClient.h.
Referenced by End(), FindMonHist(), ReceiveHist(), and ~OnlMonClient().
std::vector< OnlMonClient * > OnlMonClient::m_list_us static private
Definition at line 64 of file OnlMonClient.h.
Referenced by OnlMonClient(), StartMonitor(), and ~OnlMonClient().
bool OnlMonClient::m_make_sp_hist private
Definition at line 60 of file OnlMonClient.h.
Referenced by DisableSpillHist(), End(), process_event(), and SendHist().
Name2SpillHistMap_t OnlMonClient::m_map_hist_sp private
Definition at line 58 of file OnlMonClient.h.
Referenced by ClearSpillHist(), DisableSpillHist(), MakeMergedHist(), and MakeSpillHist().
int OnlMonClient::m_n_can private
Definition at line 42 of file OnlMonClient.h.
Referenced by ClearCanvasList(), DrawCanvas(), GetCanvas(), and NumCanvases().
int OnlMonClient::m_spill_id_pre private
Definition at line 59 of file OnlMonClient.h.
Referenced by End(), and process_event().
std::string OnlMonClient::m_title private
Definition at line 40 of file OnlMonClient.h.
Referenced by Title().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/online/onlmonserver/OnlMonClient.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/online/onlmonserver/OnlMonClient.cc