Class Reference for E1039 Core & Analysis Software: EvtFilter Class Reference
EvtFilter Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/evt_filter/EvtFilter.h>
Public Member Functions
EvtFilter (const std::string &name="EvtFilter")
virtual ~EvtFilter ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
module initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
Called at the end of all processing.
unsigned short get_trigger_req () const
void set_trigger_req (unsigned short triggerReq)
int get_event_id_req () const
void set_event_id_req (int eventIdReq)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 22 of file EvtFilter.h.
Constructor & Destructor Documentation
EvtFilter::EvtFilter (const std::string & name = "EvtFilter")
Definition at line 35 of file EvtFilter.cxx.
EvtFilter::~EvtFilter () virtual
Definition at line 44 of file EvtFilter.cxx.
Member Function Documentation
int EvtFilter::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 95 of file EvtFilter.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int EvtFilter::get_event_id_req () const inline
Definition at line 50 of file EvtFilter.h.
unsigned short EvtFilter::get_trigger_req () const inline
Definition at line 42 of file EvtFilter.h.
int EvtFilter::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 30 of file EvtFilter.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int EvtFilter::InitRun (PHCompositeNode * topNode) virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 48 of file EvtFilter.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int EvtFilter::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 53 of file EvtFilter.cxx.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, SQEvent::get_event_id(), SQEvent::get_trigger(), SQEvent::identify(), LogInfo, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_A_LOT, and Fun4AllBase::VERBOSITY_EVEN_MORE.
void EvtFilter::set_event_id_req (int eventIdReq) inline
Definition at line 54 of file EvtFilter.h.
Referenced by EventDispUI::ReqEvtID().
void EvtFilter::set_trigger_req (unsigned short triggerReq) inline
Definition at line 46 of file EvtFilter.h.
Referenced by EventDispUI::ReqTrig().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/evt_filter/EvtFilter.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/evt_filter/EvtFilter.cxx