Class Reference for E1039 Core & Analysis Software: PHFlag Class Reference
PHFlag Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHFlag.h>
Public Member Functions
PHFlag ()
virtual ~PHFlag ()
virtual const std::string get_CharFlag (const std::string &flag) const
virtual const std::string get_CharFlag (const std::string &name, const std::string &defaultval)
virtual void set_CharFlag (const std::string &name, const std::string &flag)
virtual double get_DoubleFlag (const std::string &name) const
virtual double get_DoubleFlag (const std::string &name, const double defaultval)
virtual void set_DoubleFlag (const std::string &name, const double flag)
virtual float get_FloatFlag (const std::string &name) const
virtual float get_FloatFlag (const std::string &name, const float defaultval)
virtual void set_FloatFlag (const std::string &name, const float flag)
virtual int get_IntFlag (const std::string &name) const
virtual int get_IntFlag (const std::string &name, const int defaultval)
virtual void set_IntFlag (const std::string &name, const int flag)
virtual bool get_BoolFlag (const std::string &name) const
virtual bool get_BoolFlag (const std::string &name, const bool defaultval)
virtual void set_BoolFlag (const std::string &name, const bool flag)
virtual void Print () const
virtual void PrintDoubleFlags () const
virtual void PrintIntFlags () const
virtual void PrintFloatFlags () const
virtual void PrintCharFlags () const
virtual void PrintBoolFlags () const
virtual void ReadFromFile (const std::string &name, bool verbose=false)
virtual void WriteToFile (const std::string &name)
virtual int FlagExist (const std::string &name) const
virtual const std::map< std::string, int > * IntMap () const
virtual const std::map< std::string, float > * FloatMap () const
virtual const std::map< std::string, double > * DoubleMap () const
virtual const std::map< std::string, std::string > * CharMap () const
virtual const std::map< std::string, bool > * BoolMap () const
Protected Attributes
std::map< std::string, int > intflag
std::map< std::string, double > doubleflag
std::map< std::string, float > floatflag
std::map< std::string, std::string > charflag
std::map< std::string, bool > boolflag
Detailed Description
Definition at line 19 of file PHFlag.h.
Constructor & Destructor Documentation
PHFlag()
PHFlag::PHFlag () inline
Definition at line 23 of file PHFlag.h.
~PHFlag()
virtual PHFlag::~PHFlag () inline virtual
Definition at line 24 of file PHFlag.h.
Member Function Documentation
BoolMap()
virtual const std::map<std::string, bool>* PHFlag::BoolMap () const inline virtual
Definition at line 61 of file PHFlag.h.
References boolflag.
CharMap()
virtual const std::map<std::string, std::string>* PHFlag::CharMap () const inline virtual
Definition at line 60 of file PHFlag.h.
References charflag.
Referenced by FlagSavev1::FillCharFromPHFlag().
DoubleMap()
virtual const std::map<std::string, double>* PHFlag::DoubleMap () const inline virtual
Definition at line 59 of file PHFlag.h.
References doubleflag.
Referenced by FlagSavev1::FillDoubleFromPHFlag().
FlagExist()
int PHFlag::FlagExist (const std::string & name) const virtual
Definition at line 255 of file PHFlag.cc.
Referenced by Fun4AllHistoManager::dumpHistos(), Fun4AllHepMCInputManager::fileopen(), Fun4AllOscarInputManager::fileopen(), PHGeomUtility::GetVerbosity(), GeomSvc::initPlaneDbSvc(), Fun4AllPrdfOutputManager::InitPrdfManager(), PHRandomSeed::InitSeed(), and Fun4AllServer::run().
FloatMap()
virtual const std::map<std::string, float>* PHFlag::FloatMap () const inline virtual
Definition at line 58 of file PHFlag.h.
References floatflag.
Referenced by FlagSavev1::FillFloatFromPHFlag().
get_BoolFlag() [1/2]
bool PHFlag::get_BoolFlag (const std::string & name) const virtual
Definition at line 151 of file PHFlag.cc.
Referenced by ClassImp(), EventReducer::EventReducer(), and EventReducer::reduceEvent().
get_BoolFlag() [2/2]
bool PHFlag::get_BoolFlag (const std::string & name, const bool defaultval) virtual
Definition at line 165 of file PHFlag.cc.
get_CharFlag() [1/2]
const string PHFlag::get_CharFlag (const std::string & flag) const virtual
Definition at line 13 of file PHFlag.cc.
References NULL.
Referenced by TriggerAnalyzer::init(), KScheduler::Init(), SQReco::InitField(), GeomSvc::initPlaneDbSvc(), SQReco::InitRun(), HepMCNodeReader::process_event(), and PHG4Reco::set_field_map().
get_CharFlag() [2/2]
const string PHFlag::get_CharFlag (const std::string & name, const std::string & defaultval) virtual
Definition at line 28 of file PHFlag.cc.
get_DoubleFlag() [1/2]
double PHFlag::get_DoubleFlag (const std::string & name) const virtual
Definition at line 49 of file PHFlag.cc.
Referenced by ClassImp(), GeomSvc::ELOSS_ABSORBER(), GeomSvc::ELOSS_KFMAG(), EventReducer::EventReducer(), GeomSvc::FMAG_HOLE_LENGTH(), GeomSvc::FMAG_HOLE_RADIUS(), GeomSvc::FMAG_LENGTH(), SQReco::InitField(), VertexFit::InitRun(), KalmanFastTracking::KalmanFastTracking(), KalmanFastTrackletting::KalmanFastTrackletting(), PHFieldSeaQuest::PHFieldSeaQuest(), PHG4Reco::set_field_map(), GeomSvc::Z_ABSORBER(), GeomSvc::Z_DOWNSTREAM(), GeomSvc::Z_DUMP(), GeomSvc::Z_FMAG_BEND(), GeomSvc::Z_KFMAG_BEND(), GeomSvc::Z_KMAG_BEND(), GeomSvc::Z_REF(), GeomSvc::Z_ST1(), GeomSvc::Z_ST2(), GeomSvc::Z_ST3(), GeomSvc::Z_TARGET(), and GeomSvc::Z_UPSTREAM().
get_DoubleFlag() [2/2]
double PHFlag::get_DoubleFlag (const std::string & name, const double defaultval) virtual
Definition at line 63 of file PHFlag.cc.
get_FloatFlag() [1/2]
float PHFlag::get_FloatFlag (const std::string & name) const virtual
Definition at line 83 of file PHFlag.cc.
Referenced by HepMCNodeReader::process_event().
get_FloatFlag() [2/2]
float PHFlag::get_FloatFlag (const std::string & name, const float defaultval) virtual
Definition at line 97 of file PHFlag.cc.
get_IntFlag() [1/2]
int PHFlag::get_IntFlag (const std::string & name) const virtual
Definition at line 117 of file PHFlag.cc.
Referenced by ClassImp(), Fun4AllHistoManager::dumpHistos(), Fun4AllServer::End(), Fun4AllHepMCInputManager::fileopen(), Fun4AllOscarInputManager::fileopen(), OnlMonParam::FindParamInDir(), PHGeomUtility::GetVerbosity(), GeomSvc::initPlaneDbSvc(), Fun4AllPrdfOutputManager::InitPrdfManager(), PHG4TruthSubsystem::InitRun(), CalibDriftDist::InitRun(), CalibHodoInTime::InitRun(), SQChamberRealization::InitRun(), PHRandomSeed::InitSeed(), Fun4AllServer::run(), and Fun4AllDummyInputManager::setSyncManager().
get_IntFlag() [2/2]
int PHFlag::get_IntFlag (const std::string & name, const int defaultval) virtual
Definition at line 131 of file PHFlag.cc.
IntMap()
virtual const std::map<std::string, int>* PHFlag::IntMap () const inline virtual
Definition at line 57 of file PHFlag.h.
References intflag.
Referenced by FlagSavev1::FillIntFromPHFlag().
Print()
void PHFlag::Print () const virtual
Reimplemented in recoConsts.
Definition at line 185 of file PHFlag.cc.
PrintBoolFlags()
void PHFlag::PrintBoolFlags () const virtual
Definition at line 243 of file PHFlag.cc.
Referenced by recoConsts::Print().
PrintCharFlags()
void PHFlag::PrintCharFlags () const virtual
Definition at line 231 of file PHFlag.cc.
Referenced by recoConsts::Print().
PrintDoubleFlags()
void PHFlag::PrintDoubleFlags () const virtual
Definition at line 207 of file PHFlag.cc.
Referenced by recoConsts::Print().
PrintFloatFlags()
void PHFlag::PrintFloatFlags () const virtual
Definition at line 219 of file PHFlag.cc.
Referenced by recoConsts::Print().
PrintIntFlags()
void PHFlag::PrintIntFlags () const virtual
Definition at line 195 of file PHFlag.cc.
Referenced by recoConsts::Print().
ReadFromFile()
void PHFlag::ReadFromFile (const std::string & name, bool verbose = false) virtual
Definition at line 285 of file PHFlag.cc.
Referenced by recoConsts::initfile().
set_BoolFlag()
void PHFlag::set_BoolFlag (const std::string & name, const bool flag) virtual
Definition at line 179 of file PHFlag.cc.
Referenced by recoConsts::init(), and recoConsts::set_defaults().
set_CharFlag()
void PHFlag::set_CharFlag (const std::string & name, const std::string & flag) virtual
Reimplemented in recoConsts.
Definition at line 43 of file PHFlag.cc.
Referenced by FlagSavev1::PutCharToPHFlag().
set_DoubleFlag()
void PHFlag::set_DoubleFlag (const std::string & name, const double flag) virtual
Definition at line 77 of file PHFlag.cc.
Referenced by GeomSvc::ELOSS_ABSORBER(), GeomSvc::ELOSS_KFMAG(), GeomSvc::FMAG_HOLE_LENGTH(), GeomSvc::FMAG_HOLE_RADIUS(), GeomSvc::FMAG_LENGTH(), recoConsts::init(), PHG4SimpleEventGenerator::InitRun(), main(), FlagSavev1::PutDoubleToPHFlag(), recoConsts::set_defaults(), GeomSvc::Z_ABSORBER(), GeomSvc::Z_DOWNSTREAM(), GeomSvc::Z_DUMP(), GeomSvc::Z_FMAG_BEND(), GeomSvc::Z_KFMAG_BEND(), GeomSvc::Z_KMAG_BEND(), GeomSvc::Z_REF(), GeomSvc::Z_ST1(), GeomSvc::Z_ST2(), GeomSvc::Z_ST3(), GeomSvc::Z_TARGET(), and GeomSvc::Z_UPSTREAM().
set_FloatFlag()
void PHFlag::set_FloatFlag (const std::string & name, const float flag) virtual
Definition at line 111 of file PHFlag.cc.
Referenced by PHG4Reco::InitRun(), and FlagSavev1::PutFloatToPHFlag().
set_IntFlag()
void PHFlag::set_IntFlag (const std::string & name, const int flag) virtual
Definition at line 145 of file PHFlag.cc.
Referenced by PHG4SimpleEventGenerator::End(), recoConsts::init(), PHG4SimpleEventGenerator::InitRun(), FlagSavev1::PutIntToPHFlag(), recoConsts::set_defaults(), Fun4AllServer::setRun(), and PHGeomUtility::SetVerbosity().
WriteToFile()
void PHFlag::WriteToFile (const std::string & name) virtual
Definition at line 354 of file PHFlag.cc.
Member Data Documentation
boolflag
std::map<std::string, bool> PHFlag::boolflag protected
Definition at line 69 of file PHFlag.h.
Referenced by BoolMap().
charflag
std::map<std::string, std::string> PHFlag::charflag protected
Definition at line 68 of file PHFlag.h.
Referenced by CharMap(), and recoConsts::set_CharFlag().
doubleflag
std::map<std::string, double> PHFlag::doubleflag protected
Definition at line 66 of file PHFlag.h.
Referenced by DoubleMap().
floatflag
std::map<std::string, float> PHFlag::floatflag protected
Definition at line 67 of file PHFlag.h.
Referenced by FloatMap().
intflag
std::map<std::string, int> PHFlag::intflag protected
Definition at line 65 of file PHFlag.h.
Referenced by IntMap().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHFlag.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHFlag.cc