Class Reference for E1039 Core & Analysis Software: ChanMapScaler Class Reference
ChanMapScaler Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/ChanMapScaler.h>
Public Member Functions
ChanMapScaler ()
virtual ~ChanMapScaler ()
void Add (const short roc, const short board, const short chan, const std::string name)
bool Find (const short roc, const short board, const short chan, std::string &name)
void Print (std::ostream &os)
Public Member Functions inherited from ChanMapBase
ChanMapBase (const std::string label, const std::string header)
virtual ~ChanMapBase ()
Public Member Functions inherited from RunParamBase
RunParamBase (const std::string type, const std::string label, const std::string header)
virtual ~RunParamBase ()
void SetBaseDir (const std::string dir_base)
std::string GetBaseDir ()
std::string GetParamID ()
std::string GetMapID ()
void SetMapID (const std::string map_id)
void SetMapIDbyFile (const std::string map_id)
void SetMapIDbyDB (const std::string map_id)
void SetMapIDbyFile (const int run)
void SetMapIDbyDB (const int run)
void ReadFromFile ()
void WriteToFile ()
void ReadFromLocalFile (const std::string fn_tsv)
void WriteToLocalFile (const std::string fn_tsv)
void ReadFromDB ()
void WriteToDB ()
void WriteRangeToDB ()
Protected Member Functions
int ReadFileCont (LineList &lines)
int WriteFileCont (std::ostream &os)
void ReadDbTable (DbSvc &db)
void WriteDbTable (DbSvc &db)
Protected Member Functions inherited from RunParamBase
std::string RangeFileName ()
std::string MapFileName ()
std::string SchemaName ()
std::string MapTableName ()
Additional Inherited Members
Protected Types inherited from ChanMapBase
typedef std::tuple< short,
short, short > RocBoardChan_t
Protected Types inherited from RunParamBase
typedef std::vector< std::string > LineList
Detailed Description
Definition at line 5 of file ChanMapScaler.h.
Constructor & Destructor Documentation
ChanMapScaler::ChanMapScaler ()
Definition at line 12 of file ChanMapScaler.cc.
virtual ChanMapScaler::~ChanMapScaler () inline virtual
Definition at line 20 of file ChanMapScaler.h.
Member Function Documentation
void ChanMapScaler::Add (const short roc, const short board, const short chan, const std::string name)
Definition at line 83 of file ChanMapScaler.cc.
Referenced by ReadDbTable(), and ReadFileCont().
bool ChanMapScaler::Find (const short roc, const short board, const short chan, std::string & name)
Definition at line 94 of file ChanMapScaler.cc.
void ChanMapScaler::Print (std::ostream & os) virtual
Reimplemented from RunParamBase.
Definition at line 105 of file ChanMapScaler.cc.
void ChanMapScaler::ReadDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 45 of file ChanMapScaler.cc.
References Add(), RunParamBase::MapTableName(), and DbSvc::Process().
int ChanMapScaler::ReadFileCont (LineList & lines) protected virtual
Reimplemented from RunParamBase.
Definition at line 18 of file ChanMapScaler.cc.
References Add().
void ChanMapScaler::WriteDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 60 of file ChanMapScaler.cc.
References DbSvc::Con(), DbSvc::CreateTable(), and RunParamBase::MapTableName().
int ChanMapScaler::WriteFileCont (std::ostream & os) protected virtual
Reimplemented from RunParamBase.
Definition at line 34 of file ChanMapScaler.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/ChanMapScaler.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/ChanMapScaler.cc