Class Reference for E1039 Core & Analysis Software: SQReco Class Reference
SQReco Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQReco.h>
Public Types
enum INPUT_TYPE { E906 , E1039 }
enum FITTER_TYPE {
LEGACY , KF , KFREF , DAF ,
DAFREF
}
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Public Member Functions
SQReco (const std::string &name="SQReco")
virtual ~SQReco ()
virtual int Init (PHCompositeNode *topNode)
virtual int InitRun (PHCompositeNode *topNode)
virtual int process_event (PHCompositeNode *topNode)
virtual int End (PHCompositeNode *topNode)
Called at the end of all processing.
void setInputTy (SQReco::INPUT_TYPE input_ty)
void setFitterTy (SQReco::FITTER_TYPE fitter_ty)
const TString & get_eval_file_name () const
void set_eval_file_name (const TString &evalFileName)
bool use_geom_io_node () const
void use_geom_io_node (const bool val)
const std::string & get_geom_file_name () const
void set_geom_file_name (const std::string &geomFileName)
bool is_KF_enabled () const
void set_enable_KF (bool enable)
void set_output_list_index (const int idx)
See KalmanFastTracking::setOutputListID().
bool is_eval_enabled () const
void set_enable_eval (bool enable)
bool is_eval_dst_enabled () const
void set_enable_eval_dst (bool enable)
void add_eval_list (int listID)
const TString & get_evt_reducer_opt () const
void set_evt_reducer_opt (const TString &opt)
void set_legacy_rec_container (const bool b=true)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
virtual int InitField (PHCompositeNode *topNode)
virtual int InitGeom (PHCompositeNode *topNode)
virtual int InitFastTracking ()
virtual int MakeNodes (PHCompositeNode *topNode)
virtual int GetNodes (PHCompositeNode *topNode)
int InitEvalTree ()
int ResetEvalVars ()
void ProcessEventPrep ()
void ProcessEventFinish ()
SRawEvent * BuildSRawEvent ()
int updateHitInfo (SRawEvent *sraw_event)
bool fitTrackCand (Tracklet &tracklet, KalmanFitter *fitter)
bool fitTrackCand (Tracklet &tracklet, SQGenFit::GFFitter *fitter)
void fillRecTrack (SRecTrack &recTrack)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
SQReco::INPUT_TYPE _input_type
SQReco::FITTER_TYPE _fitter_type
int _output_list_idx
bool _enable_eval
TString _eval_file_name
TTree * _eval_tree
TClonesArray * _tracklets
std::vector< int > _eval_listIDs
bool _enable_eval_dst
TrackletVector * _tracklet_vector
TString _evt_reducer_opt
KalmanFastTracking * _fastfinder
EventReducer * _eventReducer
bool _enable_KF
KalmanFitter * _kfitter
SQGenFit::GFFitter * _gfitter
PHField * _phfield
SQGenFit::GFField * _gfield
recoConsts * rc
size_t _event
SQRun * _run_header
SQSpillMap * _spill_map
SQEvent * _event_header
SQHitVector * _hit_vector
SQHitVector * _triggerhit_vector
std::map< int, size_t > _m_hitID_idx
std::map< int, size_t > _m_trghitID_idx
bool _legacy_rec_container
SRawEvent * _rawEvent
SRecEvent * _recEvent
SQTrackVector * _recTrackVec
bool _use_geom_io_node
std::string _geom_file_name
TGeoManager * _t_geo_manager
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 42 of file SQReco.h.
Member Enumeration Documentation
FITTER_TYPE
enum SQReco::FITTER_TYPE
Enumerator
LEGACY
KF
KFREF
DAF
DAFREF
Definition at line 46 of file SQReco.h.
INPUT_TYPE
enum SQReco::INPUT_TYPE
Enumerator
E906
E1039
Definition at line 45 of file SQReco.h.
Constructor & Destructor Documentation
SQReco()
SQReco::SQReco (const std::string & name = "SQReco")
Definition at line 49 of file SQReco.cxx.
References _eval_listIDs, recoConsts::instance(), and rc.
~SQReco()
SQReco::~SQReco () virtual
Definition at line 86 of file SQReco.cxx.
Member Function Documentation
add_eval_list()
void SQReco::add_eval_list (int listID)
Definition at line 616 of file SQReco.cxx.
References _eval_listIDs.
BuildSRawEvent()
SRawEvent * SQReco::BuildSRawEvent () protected
Definition at line 304 of file SQReco.cxx.
References _event, _event_header, _hit_vector, _m_hitID_idx, _m_trghitID_idx, _spill_map, _triggerhit_vector, SQSpillMap::get(), SRawEvent::getSpillID(), UtilSRawEvent::SetEvent(), SRawEvent::setEventInfo(), UtilSRawEvent::SetHit(), UtilSRawEvent::SetSpill(), and UtilSRawEvent::SetTriggerHit().
Referenced by MultiThreadReco::process_event(), and ProcessEventPrep().
End()
int SQReco::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Reimplemented in MultiThreadReco.
Definition at line 407 of file SQReco.cxx.
References _eval_file_name, _eval_tree, _fastfinder, _gfitter, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), is_eval_enabled(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
fillRecTrack()
void SQReco::fillRecTrack (SRecTrack & recTrack) protected
Definition at line 515 of file SQReco.cxx.
References _legacy_rec_container, _recEvent, _recTrackVec, SRecEvent::insertTrack(), and SQTrackVector::push_back().
Referenced by fitTrackCand(), and process_event().
fitTrackCand() [1/2]
bool SQReco::fitTrackCand (Tracklet & tracklet, KalmanFitter * fitter) protected
Definition at line 422 of file SQReco.cxx.
References _kfitter, PropSegment::a, fillRecTrack(), PropSegment::getNHits(), KalmanTrack::getNodeList(), TriggerRoad::getRoadID(), KalmanTrack::getSRecTrack(), KalmanTrack::isValid(), LogDebug, KalmanFitter::processOneTrack(), Tracklet::seg_x, Tracklet::seg_y, SRecTrack::setKalmanStatus(), SRecTrack::setNHitsInPT(), SRecTrack::setPTSlope(), KalmanTrack::setTracklet(), SRecTrack::setTriggerRoad(), and KalmanFitter::updateTrack().
Referenced by process_event().
fitTrackCand() [2/2]
bool SQReco::fitTrackCand (Tracklet & tracklet, SQGenFit::GFFitter * fitter) protected
Definition at line 461 of file SQReco.cxx.
References _gfitter, PropSegment::a, fillRecTrack(), PropSegment::getNHits(), TriggerRoad::getRoadID(), SQGenFit::GFTrack::getSRecTrack(), LogDebug, SQGenFit::GFTrack::postFitUpdate(), SQGenFit::GFTrack::print(), SQGenFit::GFFitter::processTrack(), Tracklet::seg_x, Tracklet::seg_y, SRecTrack::setNHitsInPT(), SRecTrack::setPTSlope(), SQGenFit::GFTrack::setTracklet(), SRecTrack::setTriggerRoad(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
get_eval_file_name()
const TString& SQReco::get_eval_file_name () const inline
Definition at line 59 of file SQReco.h.
References _eval_file_name.
get_evt_reducer_opt()
const TString& SQReco::get_evt_reducer_opt () const inline
Definition at line 80 of file SQReco.h.
References _evt_reducer_opt.
get_geom_file_name()
const std::string& SQReco::get_geom_file_name () const inline
Definition at line 65 of file SQReco.h.
References _geom_file_name.
GetNodes()
int SQReco::GetNodes (PHCompositeNode * topNode) protected virtual
Definition at line 565 of file SQReco.cxx.
References _event_header, _hit_vector, _input_type, _rawEvent, _run_header, _spill_map, _triggerhit_vector, Fun4AllReturnCodes::ABORTEVENT, E1039, Fun4AllReturnCodes::EVENT_OK, LogDebug, LogInfo, and Fun4AllBase::Verbosity().
Referenced by MultiThreadReco::InitRun(), and InitRun().
Init()
int SQReco::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Reimplemented in MultiThreadReco.
Definition at line 89 of file SQReco.cxx.
References Fun4AllReturnCodes::EVENT_OK.
InitEvalTree()
int SQReco::InitEvalTree () protected
Definition at line 495 of file SQReco.cxx.
References _eval_file_name, _eval_tree, _event, _tracklets, PHTFileServer::get(), and PHTFileServer::open().
Referenced by InitRun().
InitFastTracking()
int SQReco::InitFastTracking () protected virtual
Definition at line 241 of file SQReco.cxx.
References _fastfinder, _output_list_idx, _phfield, _t_geo_manager, KalmanFastTracking::setOutputListIndex(), Fun4AllBase::Verbosity(), and KalmanFastTracking::Verbosity().
Referenced by InitRun().
InitField()
int SQReco::InitField (PHCompositeNode * topNode) protected virtual
Definition at line 166 of file SQReco.cxx.
References _enable_KF, _fitter_type, _gfield, _phfield, Fun4AllReturnCodes::EVENT_OK, PHFlag::get_CharFlag(), PHFlag::get_DoubleFlag(), PHFieldUtility::GetFieldMapNode(), PHField::identify(), LEGACY, rc, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
Referenced by MultiThreadReco::InitRun(), and InitRun().
InitGeom()
int SQReco::InitGeom (PHCompositeNode * topNode) protected virtual
Definition at line 193 of file SQReco.cxx.
References _enable_KF, _geom_file_name, _t_geo_manager, _use_geom_io_node, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, PHGeomUtility::GetGeomTGeoNode(), PHGeomUtility::GetTGeoManager(), PHGeomUtility::ImportGeomFile(), PHGeomTGeo::isValid(), PHGeomUtility::LoadFromIONode(), and Fun4AllBase::Verbosity().
Referenced by MultiThreadReco::InitRun(), and InitRun().
InitRun()
int SQReco::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Reimplemented in MultiThreadReco.
Definition at line 94 of file SQReco.cxx.
References _enable_KF, _eventReducer, _evt_reducer_opt, _fitter_type, _gfield, _gfitter, _kfitter, _phfield, _t_geo_manager, DAF, DAFREF, Fun4AllReturnCodes::EVENT_OK, PHFlag::get_CharFlag(), GetNodes(), SQGenFit::GFFitter::init(), InitEvalTree(), InitFastTracking(), InitField(), InitGeom(), is_eval_enabled(), KF, KFREF, LEGACY, MakeNodes(), rc, ResetEvalVars(), and KalmanFitter::setControlParameter().
is_eval_dst_enabled()
bool SQReco::is_eval_dst_enabled () const inline
Definition at line 76 of file SQReco.h.
References _enable_eval_dst.
Referenced by process_event(), SQTrackletReco::process_event(), and ProcessEventPrep().
is_eval_enabled()
bool SQReco::is_eval_enabled () const inline
Definition at line 74 of file SQReco.h.
References _enable_eval.
Referenced by End(), InitRun(), process_event(), SQTrackletReco::process_event(), and ProcessEventPrep().
is_KF_enabled()
bool SQReco::is_KF_enabled () const inline
Definition at line 68 of file SQReco.h.
References _enable_KF.
MakeNodes()
int SQReco::MakeNodes (PHCompositeNode * topNode) protected virtual
Definition at line 523 of file SQReco.cxx.
References _enable_eval_dst, _legacy_rec_container, _recEvent, _recTrackVec, _tracklet_vector, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), LogInfo, PHObject::SplitLevel(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by InitRun().
process_event()
int SQReco::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Reimplemented in SQTrackletReco, and MultiThreadReco.
Definition at line 332 of file SQReco.cxx.
References _enable_KF, _eval_listIDs, _eval_tree, _event, _fastfinder, _fitter_type, _gfitter, _kfitter, _legacy_rec_container, _rawEvent, _recEvent, _tracklet_vector, Fun4AllReturnCodes::EVENT_OK, fillRecTrack(), fitTrackCand(), KalmanFastTracking::getFinalTracklets(), KalmanFastTracking::getTrackletList(), is_eval_dst_enabled(), is_eval_enabled(), LEGACY, LogDebug, KalmanFastTracking::printTimers(), ProcessEventFinish(), ProcessEventPrep(), TrackletVector::push_back(), SRecTrack::setKalmanStatus(), KalmanFastTracking::setRawEvent(), SRecEvent::setRawEvent(), SRecEvent::setRecStatus(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
ProcessEventFinish()
void SQReco::ProcessEventFinish () protected
Definition at line 277 of file SQReco.cxx.
References _event, _input_type, _rawEvent, and E1039.
Referenced by process_event(), and SQTrackletReco::process_event().
ProcessEventPrep()
void SQReco::ProcessEventPrep () protected
Definition at line 251 of file SQReco.cxx.
References _eventReducer, _input_type, _rawEvent, _tracklet_vector, BuildSRawEvent(), TrackletVector::clear(), E1039, SRawEvent::identify(), is_eval_dst_enabled(), is_eval_enabled(), LogInfo, EventReducer::reduceEvent(), ResetEvalVars(), updateHitInfo(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
Referenced by process_event(), and SQTrackletReco::process_event().
ResetEvalVars()
int SQReco::ResetEvalVars () protected
Definition at line 509 of file SQReco.cxx.
References _tracklets.
Referenced by InitRun(), and ProcessEventPrep().
set_enable_eval()
void SQReco::set_enable_eval (bool enable) inline
Definition at line 75 of file SQReco.h.
References _enable_eval.
set_enable_eval_dst()
void SQReco::set_enable_eval_dst (bool enable) inline
Definition at line 77 of file SQReco.h.
References _enable_eval_dst.
set_enable_KF()
void SQReco::set_enable_KF (bool enable) inline
Definition at line 69 of file SQReco.h.
References _enable_KF.
set_eval_file_name()
void SQReco::set_eval_file_name (const TString & evalFileName) inline
Definition at line 60 of file SQReco.h.
References _eval_file_name.
set_evt_reducer_opt()
void SQReco::set_evt_reducer_opt (const TString & opt) inline
Definition at line 81 of file SQReco.h.
References _evt_reducer_opt.
set_geom_file_name()
void SQReco::set_geom_file_name (const std::string & geomFileName) inline
Definition at line 66 of file SQReco.h.
References _geom_file_name.
set_legacy_rec_container()
void SQReco::set_legacy_rec_container (const bool b = true) inline
Definition at line 83 of file SQReco.h.
References _legacy_rec_container.
set_output_list_index()
void SQReco::set_output_list_index (const int idx) inline
See KalmanFastTracking::setOutputListID().
Definition at line 72 of file SQReco.h.
References _output_list_idx.
setFitterTy()
void SQReco::setFitterTy (SQReco::FITTER_TYPE fitter_ty) inline
Definition at line 57 of file SQReco.h.
References _fitter_type.
setInputTy()
void SQReco::setInputTy (SQReco::INPUT_TYPE input_ty) inline
Definition at line 56 of file SQReco.h.
References _input_type.
updateHitInfo()
int SQReco::updateHitInfo (SRawEvent * sraw_event) protected
Definition at line 286 of file SQReco.cxx.
References _hit_vector, _m_hitID_idx, SQHitVector::at(), SRawEvent::getAllHits(), SQHit::set_drift_distance(), SQHit::set_hodo_mask(), SQHit::set_in_time(), SQHit::set_pos(), SQHit::set_tdc_time(), and SQHit::set_trigger_mask().
Referenced by ProcessEventPrep().
use_geom_io_node() [1/2]
bool SQReco::use_geom_io_node () const inline
Definition at line 62 of file SQReco.h.
References _use_geom_io_node.
use_geom_io_node() [2/2]
void SQReco::use_geom_io_node (const bool val) inline
Definition at line 63 of file SQReco.h.
References _use_geom_io_node.
Member Data Documentation
_enable_eval
bool SQReco::_enable_eval protected
Definition at line 111 of file SQReco.h.
Referenced by is_eval_enabled(), and set_enable_eval().
_enable_eval_dst
bool SQReco::_enable_eval_dst protected
Definition at line 117 of file SQReco.h.
Referenced by is_eval_dst_enabled(), MakeNodes(), and set_enable_eval_dst().
_enable_KF
bool SQReco::_enable_KF protected
Definition at line 124 of file SQReco.h.
Referenced by InitField(), InitGeom(), MultiThreadReco::InitRun(), InitRun(), is_KF_enabled(), process_event(), and set_enable_KF().
_eval_file_name
TString SQReco::_eval_file_name protected
Definition at line 112 of file SQReco.h.
Referenced by End(), get_eval_file_name(), InitEvalTree(), and set_eval_file_name().
_eval_listIDs
std::vector<int> SQReco::_eval_listIDs protected
Definition at line 115 of file SQReco.h.
Referenced by add_eval_list(), process_event(), SQTrackletReco::process_event(), and SQReco().
_eval_tree
TTree* SQReco::_eval_tree protected
Definition at line 113 of file SQReco.h.
Referenced by End(), InitEvalTree(), process_event(), and SQTrackletReco::process_event().
_event
size_t SQReco::_event protected
Definition at line 133 of file SQReco.h.
Referenced by BuildSRawEvent(), InitEvalTree(), process_event(), and ProcessEventFinish().
_event_header
SQEvent* SQReco::_event_header protected
Definition at line 138 of file SQReco.h.
Referenced by BuildSRawEvent(), and GetNodes().
_eventReducer
EventReducer* SQReco::_eventReducer protected
Definition at line 122 of file SQReco.h.
Referenced by InitRun(), and ProcessEventPrep().
_evt_reducer_opt
TString SQReco::_evt_reducer_opt protected
Definition at line 120 of file SQReco.h.
Referenced by get_evt_reducer_opt(), InitRun(), and set_evt_reducer_opt().
_fastfinder
KalmanFastTracking* SQReco::_fastfinder protected
Definition at line 121 of file SQReco.h.
Referenced by End(), InitFastTracking(), process_event(), and SQTrackletReco::process_event().
_fitter_type
SQReco::FITTER_TYPE SQReco::_fitter_type protected
Definition at line 107 of file SQReco.h.
Referenced by InitField(), MultiThreadReco::InitRun(), InitRun(), process_event(), and setFitterTy().
_geom_file_name
std::string SQReco::_geom_file_name protected
Definition at line 152 of file SQReco.h.
Referenced by get_geom_file_name(), InitGeom(), and set_geom_file_name().
_gfield
SQGenFit::GFField* SQReco::_gfield protected
Definition at line 129 of file SQReco.h.
Referenced by InitField(), MultiThreadReco::InitRun(), and InitRun().
_gfitter
SQGenFit::GFFitter* SQReco::_gfitter protected
Definition at line 126 of file SQReco.h.
Referenced by End(), fitTrackCand(), MultiThreadReco::InitRun(), InitRun(), and process_event().
_hit_vector
SQHitVector* SQReco::_hit_vector protected
Definition at line 139 of file SQReco.h.
Referenced by BuildSRawEvent(), GetNodes(), and updateHitInfo().
_input_type
SQReco::INPUT_TYPE SQReco::_input_type protected
Definition at line 106 of file SQReco.h.
Referenced by GetNodes(), MultiThreadReco::process_event(), ProcessEventFinish(), ProcessEventPrep(), and setInputTy().
_kfitter
KalmanFitter* SQReco::_kfitter protected
Definition at line 125 of file SQReco.h.
Referenced by fitTrackCand(), MultiThreadReco::InitRun(), InitRun(), and process_event().
_legacy_rec_container
bool SQReco::_legacy_rec_container protected
Definition at line 146 of file SQReco.h.
Referenced by fillRecTrack(), MakeNodes(), process_event(), SQTrackletReco::process_event(), and set_legacy_rec_container().
_m_hitID_idx
std::map<int, size_t> SQReco::_m_hitID_idx protected
Definition at line 143 of file SQReco.h.
Referenced by BuildSRawEvent(), and updateHitInfo().
_m_trghitID_idx
std::map<int, size_t> SQReco::_m_trghitID_idx protected
Definition at line 144 of file SQReco.h.
Referenced by BuildSRawEvent().
_output_list_idx
int SQReco::_output_list_idx protected
Definition at line 109 of file SQReco.h.
Referenced by InitFastTracking(), and set_output_list_index().
_phfield
PHField* SQReco::_phfield protected
Definition at line 128 of file SQReco.h.
Referenced by InitFastTracking(), InitField(), MultiThreadReco::InitRun(), and InitRun().
_rawEvent
SRawEvent* SQReco::_rawEvent protected
Definition at line 147 of file SQReco.h.
Referenced by GetNodes(), MultiThreadReco::process_event(), process_event(), SQTrackletReco::process_event(), ProcessEventFinish(), and ProcessEventPrep().
_recEvent
SRecEvent* SQReco::_recEvent protected
Definition at line 148 of file SQReco.h.
Referenced by fillRecTrack(), MakeNodes(), process_event(), and SQTrackletReco::process_event().
_recTrackVec
SQTrackVector* SQReco::_recTrackVec protected
Definition at line 149 of file SQReco.h.
Referenced by fillRecTrack(), and MakeNodes().
_run_header
SQRun* SQReco::_run_header protected
Definition at line 135 of file SQReco.h.
Referenced by GetNodes().
_spill_map
SQSpillMap* SQReco::_spill_map protected
Definition at line 136 of file SQReco.h.
Referenced by BuildSRawEvent(), and GetNodes().
_t_geo_manager
TGeoManager* SQReco::_t_geo_manager protected
Definition at line 153 of file SQReco.h.
Referenced by InitFastTracking(), InitGeom(), MultiThreadReco::InitRun(), and InitRun().
_tracklet_vector
TrackletVector* SQReco::_tracklet_vector protected
Definition at line 118 of file SQReco.h.
Referenced by MakeNodes(), process_event(), SQTrackletReco::process_event(), and ProcessEventPrep().
_tracklets
TClonesArray* SQReco::_tracklets protected
Definition at line 114 of file SQReco.h.
Referenced by InitEvalTree(), and ResetEvalVars().
_triggerhit_vector
SQHitVector* SQReco::_triggerhit_vector protected
Definition at line 140 of file SQReco.h.
Referenced by BuildSRawEvent(), and GetNodes().
_use_geom_io_node
bool SQReco::_use_geom_io_node protected
Definition at line 151 of file SQReco.h.
Referenced by InitGeom(), and use_geom_io_node().
rc
recoConsts* SQReco::rc protected
Definition at line 131 of file SQReco.h.
Referenced by InitField(), InitRun(), and SQReco().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQReco.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQReco.cxx