E1039 Software: PHG4Shower Class Reference
PHG4Shower Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4Shower.h>
Public Types
typedef std::set< int > ParticleIdSet
typedef ParticleIdSet::iterator ParticleIdIter
typedef ParticleIdSet::const_iterator ParticleIdConstIter
typedef std::set< int > VertexIdSet
typedef VertexIdSet::iterator VertexIdIter
typedef VertexIdSet::const_iterator VertexIdConstIter
typedef std::map< int, std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Public Member Functions
virtual ~PHG4Shower ()
virtual void identify (std::ostream &os=std::cout) const
virtual PHG4Shower * Clone () const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int get_id () const
virtual void set_id (int id)
virtual int get_parent_particle_id () const
virtual void set_parent_particle_id (int parent_particle_id)
virtual int get_parent_shower_id () const
virtual void set_parent_shower_id (int parent_shower_id)
virtual float get_x () const
virtual void set_x (float x)
virtual float get_y () const
virtual void set_y (float y)
virtual float get_z () const
virtual void set_z (float x)
virtual float get_position (unsigned int coor) const
virtual void set_position (unsigned int coor, float xi)
virtual float get_covar (unsigned int i, unsigned int j) const
virtual void set_covar (unsigned int i, unsigned int j, float entry)
virtual unsigned int get_nhits (int volume) const
virtual void set_nhits (int volume, unsigned int nhits)
virtual float get_edep (int volume) const
virtual void set_edep (int volume, float edep)
virtual float get_eion (int volume) const
virtual void set_eion (int volume, float eion)
virtual float get_light_yield (int volume) const
virtual void set_light_yield (int volume, float light_yield)
virtual float get_eh_ratio (int volume) const
virtual void set_eh_ratio (int volume, float eh_ratio)
virtual bool empty_g4particle_id () const
virtual size_t size_g4particle_id () const
virtual void add_g4particle_id (int id)
virtual ParticleIdIter begin_g4particle_id ()
virtual ParticleIdConstIter begin_g4particle_id () const
virtual ParticleIdIter end_g4particle_id ()
virtual ParticleIdConstIter end_g4particle_id () const
virtual size_t remove_g4particle_id (int id)
virtual void clear_g4particle_id ()
virtual bool empty_g4vertex_id () const
virtual size_t size_g4vertex_id () const
virtual void add_g4vertex_id (int id)
virtual VertexIdIter begin_g4vertex_id ()
virtual VertexIdConstIter begin_g4vertex_id () const
virtual VertexIdIter end_g4vertex_id ()
virtual VertexIdConstIter end_g4vertex_id () const
virtual size_t remove_g4vertex_id (int id)
virtual void clear_g4vertex_id ()
virtual bool empty_g4hit_id () const
virtual size_t size_g4hit_id () const
virtual void add_g4hit_id (int volume, PHG4HitDefs::keytype id)
virtual HitIdIter begin_g4hit_id ()
virtual HitIdConstIter begin_g4hit_id () const
virtual HitIdIter find_g4hit_id (int volume)
virtual HitIdConstIter find_g4hit_id (int volume) const
virtual HitIdIter end_g4hit_id ()
virtual HitIdConstIter end_g4hit_id () const
virtual size_t remove_g4hit_id (int volume, PHG4HitDefs::keytype id)
virtual size_t remove_g4hit_volume (int volume)
virtual void clear_g4hit_id ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
PHG4Shower ()
Private Member Functions
ClassDef (PHG4Shower, 1)
Detailed Description
Definition at line 12 of file PHG4Shower.h.
Member Typedef Documentation
HitIdConstIter
typedef HitIdMap::const_iterator PHG4Shower::HitIdConstIter
Definition at line 26 of file PHG4Shower.h.
HitIdIter
typedef HitIdMap::iterator PHG4Shower::HitIdIter
Definition at line 25 of file PHG4Shower.h.
HitIdMap
typedef std::map<int,std::set<PHG4HitDefs::keytype> > PHG4Shower::HitIdMap
Definition at line 24 of file PHG4Shower.h.
ParticleIdConstIter
typedef ParticleIdSet::const_iterator PHG4Shower::ParticleIdConstIter
Definition at line 18 of file PHG4Shower.h.
ParticleIdIter
typedef ParticleIdSet::iterator PHG4Shower::ParticleIdIter
Definition at line 17 of file PHG4Shower.h.
ParticleIdSet
typedef std::set<int> PHG4Shower::ParticleIdSet
Definition at line 16 of file PHG4Shower.h.
VertexIdConstIter
typedef VertexIdSet::const_iterator PHG4Shower::VertexIdConstIter
Definition at line 22 of file PHG4Shower.h.
VertexIdIter
typedef VertexIdSet::iterator PHG4Shower::VertexIdIter
Definition at line 21 of file PHG4Shower.h.
VertexIdSet
typedef std::set<int> PHG4Shower::VertexIdSet
Definition at line 20 of file PHG4Shower.h.
Constructor & Destructor Documentation
~PHG4Shower()
virtual PHG4Shower::~PHG4Shower () inline virtual
Definition at line 28 of file PHG4Shower.h.
PHG4Shower()
PHG4Shower::PHG4Shower () inline protected
Definition at line 112 of file PHG4Shower.h.
References ClassDef().
Member Function Documentation
add_g4hit_id()
virtual void PHG4Shower::add_g4hit_id (int volume, PHG4HitDefs::keytype id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 100 of file PHG4Shower.h.
Referenced by PHG4BlockSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), and PHG4PolyconSteppingAction::UserSteppingAction().
add_g4particle_id()
virtual void PHG4Shower::add_g4particle_id (int id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 80 of file PHG4Shower.h.
add_g4vertex_id()
virtual void PHG4Shower::add_g4vertex_id (int id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 90 of file PHG4Shower.h.
begin_g4hit_id() [1/2]
virtual HitIdIter PHG4Shower::begin_g4hit_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 101 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers(), and PHG4TruthEventAction::PruneShowers().
begin_g4hit_id() [2/2]
virtual HitIdConstIter PHG4Shower::begin_g4hit_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 102 of file PHG4Shower.h.
begin_g4particle_id() [1/2]
virtual ParticleIdIter PHG4Shower::begin_g4particle_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 81 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::PruneShowers().
begin_g4particle_id() [2/2]
virtual ParticleIdConstIter PHG4Shower::begin_g4particle_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 82 of file PHG4Shower.h.
begin_g4vertex_id() [1/2]
virtual VertexIdIter PHG4Shower::begin_g4vertex_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 91 of file PHG4Shower.h.
begin_g4vertex_id() [2/2]
virtual VertexIdConstIter PHG4Shower::begin_g4vertex_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 92 of file PHG4Shower.h.
ClassDef()
PHG4Shower::ClassDef (PHG4Shower , 1) private
Referenced by PHG4Shower().
clear_g4hit_id()
virtual void PHG4Shower::clear_g4hit_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 109 of file PHG4Shower.h.
clear_g4particle_id()
virtual void PHG4Shower::clear_g4particle_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 86 of file PHG4Shower.h.
clear_g4vertex_id()
virtual void PHG4Shower::clear_g4vertex_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 96 of file PHG4Shower.h.
Clone()
virtual PHG4Shower* PHG4Shower::Clone () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 33 of file PHG4Shower.h.
References NULL.
empty_g4hit_id()
virtual bool PHG4Shower::empty_g4hit_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 98 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::PruneShowers().
empty_g4particle_id()
virtual bool PHG4Shower::empty_g4particle_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 78 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::PruneShowers().
empty_g4vertex_id()
virtual bool PHG4Shower::empty_g4vertex_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 88 of file PHG4Shower.h.
end_g4hit_id() [1/2]
virtual HitIdIter PHG4Shower::end_g4hit_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 105 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers(), and PHG4TruthEventAction::PruneShowers().
end_g4hit_id() [2/2]
virtual HitIdConstIter PHG4Shower::end_g4hit_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 106 of file PHG4Shower.h.
end_g4particle_id() [1/2]
virtual ParticleIdIter PHG4Shower::end_g4particle_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 83 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::PruneShowers().
end_g4particle_id() [2/2]
virtual ParticleIdConstIter PHG4Shower::end_g4particle_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 84 of file PHG4Shower.h.
end_g4vertex_id() [1/2]
virtual VertexIdIter PHG4Shower::end_g4vertex_id () inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 93 of file PHG4Shower.h.
end_g4vertex_id() [2/2]
virtual VertexIdConstIter PHG4Shower::end_g4vertex_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 94 of file PHG4Shower.h.
find_g4hit_id() [1/2]
virtual HitIdIter PHG4Shower::find_g4hit_id (int volume) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 103 of file PHG4Shower.h.
find_g4hit_id() [2/2]
virtual HitIdConstIter PHG4Shower::find_g4hit_id (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 104 of file PHG4Shower.h.
get_covar()
virtual float PHG4Shower::get_covar (unsigned int i, unsigned int j) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 60 of file PHG4Shower.h.
get_edep()
virtual float PHG4Shower::get_edep (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 66 of file PHG4Shower.h.
get_eh_ratio()
virtual float PHG4Shower::get_eh_ratio (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 75 of file PHG4Shower.h.
get_eion()
virtual float PHG4Shower::get_eion (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 69 of file PHG4Shower.h.
get_id()
virtual int PHG4Shower::get_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 39 of file PHG4Shower.h.
get_light_yield()
virtual float PHG4Shower::get_light_yield (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 72 of file PHG4Shower.h.
get_nhits()
virtual unsigned int PHG4Shower::get_nhits (int volume) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 63 of file PHG4Shower.h.
get_parent_particle_id()
virtual int PHG4Shower::get_parent_particle_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 42 of file PHG4Shower.h.
get_parent_shower_id()
virtual int PHG4Shower::get_parent_shower_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 45 of file PHG4Shower.h.
get_position()
virtual float PHG4Shower::get_position (unsigned int coor) const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 57 of file PHG4Shower.h.
get_x()
virtual float PHG4Shower::get_x () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 48 of file PHG4Shower.h.
get_y()
virtual float PHG4Shower::get_y () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 51 of file PHG4Shower.h.
get_z()
virtual float PHG4Shower::get_z () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 54 of file PHG4Shower.h.
identify()
virtual void PHG4Shower::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4Showerv1.
Definition at line 32 of file PHG4Shower.h.
isValid()
virtual int PHG4Shower::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in PHG4Showerv1.
Definition at line 35 of file PHG4Shower.h.
remove_g4hit_id()
virtual size_t PHG4Shower::remove_g4hit_id (int volume, PHG4HitDefs::keytype id) inline virtual
Definition at line 107 of file PHG4Shower.h.
remove_g4hit_volume()
virtual size_t PHG4Shower::remove_g4hit_volume (int volume) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 108 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::PruneShowers().
remove_g4particle_id()
virtual size_t PHG4Shower::remove_g4particle_id (int id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 85 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::PruneShowers().
remove_g4vertex_id()
virtual size_t PHG4Shower::remove_g4vertex_id (int id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 95 of file PHG4Shower.h.
Reset()
virtual void PHG4Shower::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in PHG4Showerv1.
Definition at line 34 of file PHG4Shower.h.
set_covar()
virtual void PHG4Shower::set_covar (unsigned int i, unsigned int j, float entry) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 61 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers().
set_edep()
virtual void PHG4Shower::set_edep (int volume, float edep) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 67 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers().
set_eh_ratio()
virtual void PHG4Shower::set_eh_ratio (int volume, float eh_ratio) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 76 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers().
set_eion()
virtual void PHG4Shower::set_eion (int volume, float eion) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 70 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers().
set_id()
virtual void PHG4Shower::set_id (int id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 40 of file PHG4Shower.h.
Referenced by PHG4TruthInfoContainer::AddShower().
set_light_yield()
virtual void PHG4Shower::set_light_yield (int volume, float light_yield) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 73 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers().
set_nhits()
virtual void PHG4Shower::set_nhits (int volume, unsigned int nhits) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 64 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers().
set_parent_particle_id()
virtual void PHG4Shower::set_parent_particle_id (int parent_particle_id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 43 of file PHG4Shower.h.
set_parent_shower_id()
virtual void PHG4Shower::set_parent_shower_id (int parent_shower_id) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 46 of file PHG4Shower.h.
set_position()
virtual void PHG4Shower::set_position (unsigned int coor, float xi) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 58 of file PHG4Shower.h.
set_x()
virtual void PHG4Shower::set_x (float x) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 49 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers().
set_y()
virtual void PHG4Shower::set_y (float y) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 52 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers().
set_z()
virtual void PHG4Shower::set_z (float x) inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 55 of file PHG4Shower.h.
Referenced by PHG4TruthEventAction::ProcessShowers().
size_g4hit_id()
virtual size_t PHG4Shower::size_g4hit_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 99 of file PHG4Shower.h.
size_g4particle_id()
virtual size_t PHG4Shower::size_g4particle_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 79 of file PHG4Shower.h.
size_g4vertex_id()
virtual size_t PHG4Shower::size_g4vertex_id () const inline virtual
Reimplemented in PHG4Showerv1.
Definition at line 89 of file PHG4Shower.h.
The documentation for this class was generated from the following file:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4Shower.h