Class Reference for E1039 Core & Analysis Software: CalibParam Class Reference
CalibParam Class Reference
Class to hold the calibration parameters.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/CalibParam.h>
Public Member Functions
CalibParam ()
virtual ~CalibParam ()
int GetNumPlanes () const
void SetAnaPlanes (const bool d0, const bool d1, const bool d2, const bool d3p, const bool d3m)
bool GetAnaPlane (const int i_pl)
bool TimeWindowIsFixed () const
RTCurve * GetRTCurve (const int i_pl) const
double GetTMin (const int i_pl) const
double GetTMax (const int i_pl) const
double GetRMax (const int i_pl) const
double GetT0 (const int i_pl) const
double GetT1 (const int i_pl) const
TGraph * GetGraphT2R (const int i_pl) const
void Init (const int n_rt_pt)
void ReadRTParam (const std::string fname)
void WriteRTParam (const std::string dir_name, const std::string fname)
void WriteRTGraph (const std::string dir_name, const std::string fname)
void ReadTimeWindow (const std::string fname)
Static Public Member Functions
static double ZOfStationID (const int st_id)
Detailed Description
Class to hold the calibration parameters.
Definition at line 8 of file CalibParam.h.
Constructor & Destructor Documentation
CalibParam()
CalibParam::CalibParam ()
Definition at line 14 of file CalibParam.cc.
~CalibParam()
CalibParam::~CalibParam () virtual
Definition at line 21 of file CalibParam.cc.
Member Function Documentation
GetAnaPlane()
bool CalibParam::GetAnaPlane (const int i_pl) inline
Definition at line 31 of file CalibParam.h.
Referenced by MakeRTCurve::DrawCalibResult(), SRMakeRTCurve::DrawCalibResult(), CalibData::DrawHistHit(), MakeRTCurve::ExtractRT(), and SRMakeRTCurve::ExtractRT().
GetGraphT2R()
TGraph* CalibParam::GetGraphT2R (const int i_pl) const inline
Definition at line 42 of file CalibParam.h.
Referenced by MakeRTCurve::DrawCalibResult(), SRMakeRTCurve::DrawCalibResult(), MakeRTCurve::ExtractRT(), and SRMakeRTCurve::ExtractRT().
GetNumPlanes()
int CalibParam::GetNumPlanes () const inline
Definition at line 28 of file CalibParam.h.
Referenced by MakeRTCurve::DrawCalibResult(), SRMakeRTCurve::DrawCalibResult(), CalibData::DrawHistHit(), MakeRTCurve::ExtractRT(), SRMakeRTCurve::ExtractRT(), and CalibData::Init().
GetRMax()
double CalibParam::GetRMax (const int i_pl) const inline
Definition at line 38 of file CalibParam.h.
Referenced by MakeRTCurve::ExtractRT(), SRMakeRTCurve::ExtractRT(), and CalibData::Init().
GetRTCurve()
RTCurve* CalibParam::GetRTCurve (const int i_pl) const inline
Definition at line 34 of file CalibParam.h.
Referenced by MakeRTCurve::DrawCalibResult(), SRMakeRTCurve::DrawCalibResult(), MakeRTCurve::ExtractRT(), and SRMakeRTCurve::ExtractRT().
GetT0()
double CalibParam::GetT0 (const int i_pl) const inline
Definition at line 39 of file CalibParam.h.
Referenced by MakeRTCurve::ExtractRT(), and SRMakeRTCurve::ExtractRT().
GetT1()
double CalibParam::GetT1 (const int i_pl) const inline
Definition at line 40 of file CalibParam.h.
Referenced by MakeRTCurve::ExtractRT(), and SRMakeRTCurve::ExtractRT().
GetTMax()
double CalibParam::GetTMax (const int i_pl) const inline
Definition at line 37 of file CalibParam.h.
Referenced by CalibData::Init().
GetTMin()
double CalibParam::GetTMin (const int i_pl) const inline
Definition at line 36 of file CalibParam.h.
Referenced by CalibData::Init().
Init()
void CalibParam::Init (const int n_rt_pt)
Definition at line 35 of file CalibParam.cc.
References GeomSvc::getCellWidth(), and GeomSvc::instance().
Referenced by MakeRTCurve::Init(), and SRMakeRTCurve::InitRun().
ReadRTParam()
void CalibParam::ReadRTParam (const std::string fname)
Definition at line 82 of file CalibParam.cc.
References GeomSvc::getDetectorID(), and GeomSvc::instance().
Referenced by MakeRTCurve::Init(), and SRMakeRTCurve::InitRun().
ReadTimeWindow()
void CalibParam::ReadTimeWindow (const std::string fname)
Definition at line 204 of file CalibParam.cc.
SetAnaPlanes()
void CalibParam::SetAnaPlanes (const bool d0, const bool d1, const bool d2, const bool d3p, const bool d3m)
Definition at line 26 of file CalibParam.cc.
Referenced by MakeRTCurve::Init(), and SRMakeRTCurve::InitRun().
TimeWindowIsFixed()
bool CalibParam::TimeWindowIsFixed () const inline
Definition at line 33 of file CalibParam.h.
Referenced by MakeRTCurve::ExtractRT(), and SRMakeRTCurve::ExtractRT().
WriteRTGraph()
void CalibParam::WriteRTGraph (const std::string dir_name, const std::string fname)
Definition at line 172 of file CalibParam.cc.
References GeomSvc::getDetectorName(), RTCurve::GetT2DRGraph(), RTCurve::GetT2RSpline(), and GeomSvc::instance().
Referenced by MakeRTCurve::WriteRT(), and SRMakeRTCurve::WriteRT().
WriteRTParam()
void CalibParam::WriteRTParam (const std::string dir_name, const std::string fname)
Definition at line 120 of file CalibParam.cc.
References RTCurve::EvalR(), GeomSvc::getDetectorName(), RTCurve::GetRWidth(), and GeomSvc::instance().
Referenced by MakeRTCurve::WriteRT(), and SRMakeRTCurve::WriteRT().
ZOfStationID()
double CalibParam::ZOfStationID (const int st_id) static
Definition at line 224 of file CalibParam.cc.
Referenced by CalibData::FillTracklet(), and SRMakeRTCurve::InAcceptance().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/CalibParam.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/CalibParam.cc