Class Reference for E1039 Core & Analysis Software: FilterByTrigger Class Reference
FilterByTrigger Class Reference
A SubsysReco module to filter events by trigger.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/evt_filter/FilterByTrigger.h>
Public Member Functions
FilterByTrigger ()
virtual ~FilterByTrigger ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetFpgaBits (const bool fpga1, const bool fpga2, const bool fpga3, const bool fpga4, const bool fpga5)
void SetNimBits (const bool nim1, const bool nim2, const bool nim3, const bool nim4, const bool nim5)
void SetTriggerBits (const unsigned short trig_bits)
void EnableOutput (const std::string fn_out="filter_by_trigger.tsv")
FilterByTrigger ()
virtual ~FilterByTrigger ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetFpgaBits (const bool fpga1, const bool fpga2, const bool fpga3, const bool fpga4, const bool fpga5)
void SetNimBits (const bool nim1, const bool nim2, const bool nim3, const bool nim4, const bool nim5)
void SetTriggerBits (const unsigned short trig_bits)
void EnableOutput (const std::string fn_out="filter_by_trigger.tsv")
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
A SubsysReco module to filter events by trigger.
It outputs the counts of all and accepted events into a tsv file once EnableOutput() is called.
Typical usage:
FilterByTrigger* fbt = new FilterByTrigger();
fbt->SetFpgaBits(1,0,0,0,0);
fbt->SetNimBits (0,0,1,0,0);
fbt->EnableOutput();
se->registerSubsystem(fbt);
Advanced usage:
fbt->SetTriggerBits((0x1<<SQEvent::MATRIX1) | (0x1<<SQEvent::NIM3));
Definition at line 25 of file FilterByTrigger.h.
Constructor & Destructor Documentation
FilterByTrigger::FilterByTrigger ()
Definition at line 10 of file FilterByTrigger.cxx.
FilterByTrigger::~FilterByTrigger () virtual
Definition at line 19 of file FilterByTrigger.cxx.
FilterByTrigger::FilterByTrigger ()
virtual FilterByTrigger::~FilterByTrigger () virtual
Member Function Documentation
void FilterByTrigger::EnableOutput (const std::string fn_out = "filter_by_trigger.tsv") inline
Definition at line 42 of file FilterByTrigger.h.
Referenced by Fun4All(), and R__LOAD_LIBRARY().
void FilterByTrigger::EnableOutput (const std::string fn_out = "filter_by_trigger.tsv") inline
Definition at line 42 of file FilterByTrigger.h.
int FilterByTrigger::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 53 of file FilterByTrigger.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int FilterByTrigger::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
int FilterByTrigger::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 24 of file FilterByTrigger.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int FilterByTrigger::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
int FilterByTrigger::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 29 of file FilterByTrigger.cxx.
References Fun4AllReturnCodes::ABORTEVENT, and Fun4AllReturnCodes::EVENT_OK.
int FilterByTrigger::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int FilterByTrigger::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int FilterByTrigger::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 43 of file FilterByTrigger.cxx.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and SQEvent::get_trigger().
void FilterByTrigger::SetFpgaBits (const bool fpga1, const bool fpga2, const bool fpga3, const bool fpga4, const bool fpga5)
Definition at line 66 of file FilterByTrigger.cxx.
References SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, and SQEvent::MATRIX5.
void FilterByTrigger::SetFpgaBits (const bool fpga1, const bool fpga2, const bool fpga3, const bool fpga4, const bool fpga5)
void FilterByTrigger::SetNimBits (const bool nim1, const bool nim2, const bool nim3, const bool nim4, const bool nim5)
void FilterByTrigger::SetNimBits (const bool nim1, const bool nim2, const bool nim3, const bool nim4, const bool nim5)
Definition at line 75 of file FilterByTrigger.cxx.
References SQEvent::NIM1, SQEvent::NIM2, SQEvent::NIM3, SQEvent::NIM4, and SQEvent::NIM5.
Referenced by Fun4All(), and R__LOAD_LIBRARY().
void FilterByTrigger::SetTriggerBits (const unsigned short trig_bits) inline
Definition at line 41 of file FilterByTrigger.h.
void FilterByTrigger::SetTriggerBits (const unsigned short trig_bits) inline
Definition at line 41 of file FilterByTrigger.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/evt_filter/FilterByTrigger.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/FilterByTrigger.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/evt_filter/FilterByTrigger.cxx
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/FilterByTrigger.cc