E1039 Software: PHG4GDMLWriteSolids::G4ThreeVectorCompare Class Reference
PHG4GDMLWriteSolids::G4ThreeVectorCompare Class Reference
Public Member Functions
G4bool operator() (const G4ThreeVector &t1, const G4ThreeVector &t2) const
Detailed Description
Definition at line 80 of file PHG4GDMLWriteSolids.hh.
Member Function Documentation
operator()()
G4bool PHG4GDMLWriteSolids::G4ThreeVectorCompare::operator() (const G4ThreeVector & t1, const G4ThreeVector & t2) const inline
Definition at line 84 of file PHG4GDMLWriteSolids.hh.
References PHG4GDMLWriteSolids::AddSolid(), PHG4GDMLWriteSolids::BooleanWrite(), PHG4GDMLWriteSolids::BoxWrite(), PHG4GDMLWriteSolids::ConeWrite(), PHG4GDMLWriteSolids::CutTubeWrite(), PHG4GDMLWriteSolids::ElconeWrite(), PHG4GDMLWriteSolids::EllipsoidWrite(), PHG4GDMLWriteSolids::EltubeWrite(), PHG4GDMLWriteSolids::GenericPolyconeWrite(), PHG4GDMLWriteSolids::GenTrapWrite(), PHG4GDMLWriteSolids::HypeWrite(), PHG4GDMLWriteSolids::MultiUnionWrite(), PHG4GDMLWriteSolids::OpticalSurfaceWrite(), PHG4GDMLWriteSolids::OrbWrite(), PHG4GDMLWriteSolids::ParaboloidWrite(), PHG4GDMLWriteSolids::ParaWrite(), PHG4GDMLWriteSolids::PHG4GDMLWriteSolids(), PHG4GDMLWriteSolids::PolyconeWrite(), PHG4GDMLWriteSolids::PolyhedraWrite(), PHG4GDMLWriteSolids::RZPointWrite(), PHG4GDMLWriteSolids::SolidsWrite(), PHG4GDMLWriteSolids::SphereWrite(), PHG4GDMLWriteSolids::TessellatedWrite(), PHG4GDMLWriteSolids::TetWrite(), PHG4GDMLWriteSolids::TorusWrite(), PHG4GDMLWriteSolids::TrapWrite(), PHG4GDMLWriteSolids::TrdWrite(), PHG4GDMLWriteSolids::TubeWrite(), PHG4GDMLWriteSolids::TwistedboxWrite(), PHG4GDMLWriteSolids::TwistedtrapWrite(), PHG4GDMLWriteSolids::TwistedtrdWrite(), PHG4GDMLWriteSolids::TwistedtubsWrite(), PHG4GDMLWriteSolids::XtruWrite(), PHG4GDMLWriteSolids::ZplaneWrite(), and PHG4GDMLWriteSolids::~PHG4GDMLWriteSolids().
The documentation for this class was generated from the following file:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4gdml/PHG4GDMLWriteSolids.hh