Class Reference for E1039 Core & Analysis Software: PHG4BlockCellGeomContainer Class Reference
PHG4BlockCellGeomContainer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockCellGeomContainer.h>
Public Types
typedef std::map< int, PHG4BlockCellGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator, Iterator > Range
typedef std::pair< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHG4BlockCellGeomContainer ()
virtual ~PHG4BlockCellGeomContainer ()
void identify (std::ostream &os=std::cout) const
int AddLayerCellGeom (const int i, PHG4BlockCellGeom *mygeom)
int AddLayerCellGeom (PHG4BlockCellGeom *mygeom)
PHG4BlockCellGeom * GetLayerCellGeom (const int i)
int get_NLayers () const
std::pair< std::map< int, PHG4BlockCellGeom * >::const_iterator, std::map< int, PHG4BlockCellGeom * >::const_iterator > get_begin_end () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
std::map< int, PHG4BlockCellGeom * > layergeoms
Detailed Description
Definition at line 10 of file PHG4BlockCellGeomContainer.h.
Member Typedef Documentation
ConstIterator
typedef Map::const_iterator PHG4BlockCellGeomContainer::ConstIterator
Definition at line 15 of file PHG4BlockCellGeomContainer.h.
ConstRange
typedef std::pair<ConstIterator, ConstIterator> PHG4BlockCellGeomContainer::ConstRange
Definition at line 17 of file PHG4BlockCellGeomContainer.h.
Iterator
typedef Map::iterator PHG4BlockCellGeomContainer::Iterator
Definition at line 14 of file PHG4BlockCellGeomContainer.h.
Map
typedef std::map<int, PHG4BlockCellGeom*> PHG4BlockCellGeomContainer::Map
Definition at line 13 of file PHG4BlockCellGeomContainer.h.
Range
typedef std::pair<Iterator, Iterator> PHG4BlockCellGeomContainer::Range
Definition at line 16 of file PHG4BlockCellGeomContainer.h.
Constructor & Destructor Documentation
PHG4BlockCellGeomContainer()
PHG4BlockCellGeomContainer::PHG4BlockCellGeomContainer ()
Definition at line 7 of file PHG4BlockCellGeomContainer.cc.
~PHG4BlockCellGeomContainer()
PHG4BlockCellGeomContainer::~PHG4BlockCellGeomContainer () virtual
Definition at line 12 of file PHG4BlockCellGeomContainer.cc.
Member Function Documentation
AddLayerCellGeom() [1/2]
int PHG4BlockCellGeomContainer::AddLayerCellGeom (const int i, PHG4BlockCellGeom * mygeom)
Definition at line 35 of file PHG4BlockCellGeomContainer.cc.
References PHG4BlockCellGeom::set_layer().
Referenced by PHG4BlockCellReco::InitRun().
AddLayerCellGeom() [2/2]
int PHG4BlockCellGeomContainer::AddLayerCellGeom (PHG4BlockCellGeom * mygeom)
Definition at line 48 of file PHG4BlockCellGeomContainer.cc.
References PHG4BlockCellGeom::get_layer().
get_begin_end()
std::pair<std::map<int,PHG4BlockCellGeom *>::const_iterator, std::map<int,PHG4BlockCellGeom *>::const_iterator> PHG4BlockCellGeomContainer::get_begin_end () const inline
Definition at line 28 of file PHG4BlockCellGeomContainer.h.
References layergeoms.
get_NLayers()
int PHG4BlockCellGeomContainer::get_NLayers () const inline
Definition at line 27 of file PHG4BlockCellGeomContainer.h.
References layergeoms.
GetLayerCellGeom()
PHG4BlockCellGeom * PHG4BlockCellGeomContainer::GetLayerCellGeom (const int i)
Definition at line 61 of file PHG4BlockCellGeomContainer.cc.
References NULL.
Referenced by PHG4BlockCellReco::process_event().
identify()
void PHG4BlockCellGeomContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 23 of file PHG4BlockCellGeomContainer.cc.
Member Data Documentation
layergeoms
std::map<int,PHG4BlockCellGeom *> PHG4BlockCellGeomContainer::layergeoms protected
Definition at line 31 of file PHG4BlockCellGeomContainer.h.
Referenced by get_begin_end(), and get_NLayers().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockCellGeomContainer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockCellGeomContainer.cc