SeaQuest Offline Software: PHG4SpacalPrototypeDetector Class Reference
PHG4SpacalPrototypeDetector Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SpacalPrototypeDetector.h>
Public Types
enum {
FIBER_CORE = 1, FIBER_CLADING = 0, ABSORBER = -1, SUPPORT = -2,
INACTIVE = -100
}
typedef PHG4CylinderGeom_Spacalv3 SpacalGeom_t
Public Member Functions
PHG4SpacalPrototypeDetector (PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
virtual ~PHG4SpacalPrototypeDetector (void)
virtual void Construct (G4LogicalVolume *world)
construct method
virtual std::pair
< G4LogicalVolume
*, G4Transform3D > Construct_AzimuthalSeg ()
virtual G4LogicalVolume * Construct_Tower (const SpacalGeom_t::geom_tower &tower)
a block along z axis built with G4Trd that is slightly tapered in x dimension
virtual G4LogicalVolume * Construct_LightGuide (const SpacalGeom_t::geom_tower &tower, const int index_x, const int index_y)
a block for the light guide along z axis that fit to the tower
virtual int Construct_Fibers_SameLengthFiberPerTower (const SpacalGeom_t::geom_tower &tower, G4LogicalVolume *LV_tower)
Fully projective spacal with 2D tapered modules. To speed up construction, same-length fiber is used cross one tower.
virtual G4LogicalVolume * Construct_Fiber (const G4double length, const std::string &id)
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void SetDetectorType (const std::string &typ)
int IsInCylinderActive (const G4VPhysicalVolume *)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
virtual void Print (const std::string &what="ALL") const
const SpacalGeom_t * get_geom () const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
Protected Attributes
PHParameters * construction_params
G4VSolid * cylinder_solid
G4LogicalVolume * cylinder_logic
G4VPhysicalVolume * cylinder_physi
std::map< const
G4VPhysicalVolume *, int > fiber_core_vol
std::map< const
G4VPhysicalVolume *, int > fiber_vol
map for G4VPhysicalVolume -> fiber ID
std::map< const
G4VPhysicalVolume *, int > calo_vol
map for G4VPhysicalVolume -> Sector ID
std::map< const
G4VPhysicalVolume *, int > block_vol
map for G4VPhysicalVolume -> towers ID
int active
int absorberactive
std::string detector_type
std::string superdetector
G4UserLimits * step_limits
G4UserLimits * clading_step_limits
G4UserLimits * fiber_core_step_limits
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Private Attributes
SpacalGeom_t * _geom
Detailed Description
Definition at line 24 of file PHG4SpacalPrototypeDetector.h.
Member Typedef Documentation
typedef PHG4CylinderGeom_Spacalv3 PHG4SpacalPrototypeDetector::SpacalGeom_t
Definition at line 28 of file PHG4SpacalPrototypeDetector.h.
Member Enumeration Documentation
anonymous enum
Enumerator
FIBER_CORE
FIBER_CLADING
ABSORBER
SUPPORT
INACTIVE
Definition at line 100 of file PHG4SpacalPrototypeDetector.h.
Constructor & Destructor Documentation
PHG4SpacalPrototypeDetector::PHG4SpacalPrototypeDetector (PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
Definition at line 47 of file PHG4SpacalPrototypeDetector.cc.
PHG4SpacalPrototypeDetector::~PHG4SpacalPrototypeDetector (void) virtual
Definition at line 61 of file PHG4SpacalPrototypeDetector.cc.
References _geom, clading_step_limits, fiber_core_step_limits, and step_limits.
Member Function Documentation
void PHG4SpacalPrototypeDetector::Construct (G4LogicalVolume * world) virtual
construct method
construct all logical and physical volumes relevant for given detector and place them inside the world logical volume
Implements PHG4Detector.
Definition at line 103 of file PHG4SpacalPrototypeDetector.cc.
References _geom, absorberactive, active, PHG4CylinderGeomContainer::AddLayerGeom(), PHCompositeNode::addNode(), calo_vol, clading_step_limits, Construct_AzimuthalSeg(), construction_params, cylinder_logic, cylinder_physi, cylinder_solid, detector_type, fiber_core_step_limits, PHNodeIterator::findFirst(), PHG4CylinderGeom_Spacalv2::get_azimuthal_n_sec(), PHG4CylinderGeom_Spacalv1::get_construction_verbose(), PHParameters::get_double_param(), PHG4CylinderGeom_Spacalv1::get_fiber_core_step_size(), PHG4CylinderGeom_Spacalv1::get_length(), PHG4CylinderGeom_Spacalv3::get_max_lightguide_height(), PHG4CylinderGeomv2::get_nscint(), PHG4CylinderGeomv1::get_radius(), PHG4CylinderGeom_Spacalv1::get_sector_map(), PHParameters::get_string_param(), PHG4CylinderGeomv1::get_thickness(), PHG4CylinderGeom_Spacalv1::get_xpos(), PHG4CylinderGeom_Spacalv1::get_ypos(), PHG4CylinderGeomv1::get_zmax(), PHG4CylinderGeomv1::get_zmin(), PHG4CylinderGeom_Spacalv1::get_zpos(), findNode::getClass(), PHG4Detector::GetName(), PHG4CylinderGeomContainer::identify(), PHG4CylinderGeom_Spacalv3::ImportParameters(), PHG4CylinderGeom_Spacalv2::is_azimuthal_seg_visible(), PHG4CylinderGeom_Spacalv1::is_virualize_fiber(), PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_SameLengthFiberPerTower, PHG4Detector::name, PHG4Detector::overlapcheck, Print(), PHG4CylinderGeom_Spacalv1::set_config(), PHG4CylinderGeomv2::set_nscint(), PHG4Utils::SetColour(), step_limits, PHG4CylinderGeom_Spacalv3::subtower_consistency_check(), superdetector, and PHG4Detector::topNode.
std::pair< G4LogicalVolume *, G4Transform3D > PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg () virtual
Definition at line 375 of file PHG4SpacalPrototypeDetector.cc.
References _geom, block_vol, PHG4CylinderGeom_Spacalv3::geom_tower::centralX, PHG4CylinderGeom_Spacalv3::geom_tower::centralY, PHG4CylinderGeom_Spacalv3::geom_tower::centralZ, Construct_LightGuide(), Construct_Tower(), PHG4CylinderGeom_Spacalv2::get_azimuthal_n_sec(), PHG4CylinderGeom_Spacalv1::get_construction_verbose(), PHG4CylinderGeom_Spacalv1::get_length(), PHG4CylinderGeom_Spacalv3::get_max_lightguide_height(), PHG4CylinderGeom_Spacalv1::get_max_radius(), PHG4CylinderGeomv1::get_radius(), PHG4CylinderGeom_Spacalv3::get_sector_tower_map(), PHG4CylinderGeom_Spacalv3::get_sidewall_thickness(), PHG4CylinderGeomv1::get_zmax(), PHG4CylinderGeomv1::get_zmin(), PHG4Detector::GetName(), PHG4CylinderGeom_Spacalv3::geom_tower::id, PHG4CylinderGeom_Spacalv2::is_azimuthal_seg_visible(), PHG4CylinderGeom_Spacalv1::is_virualize_fiber(), PHG4CylinderGeom_Spacalv3::geom_tower::LightguideHeight, PHG4CylinderGeom_Spacalv3::geom_tower::NSubtowerX, PHG4CylinderGeom_Spacalv3::geom_tower::NSubtowerY, PHG4Detector::overlapcheck, PHG4CylinderGeom_Spacalv3::geom_tower::pRotationAngleX, and step_limits.
Referenced by Construct().
G4LogicalVolume * PHG4SpacalPrototypeDetector::Construct_Fiber (const G4double length, const std::string & id) virtual
Definition at line 584 of file PHG4SpacalPrototypeDetector.cc.
References _geom, clading_step_limits, fiber_core_step_limits, fiber_core_vol, PHG4CylinderGeom_Spacalv1::get_construction_verbose(), PHG4CylinderGeom_Spacalv1::get_fiber_clading_mat(), PHG4CylinderGeom_Spacalv1::get_fiber_core_diameter(), PHG4CylinderGeom_Spacalv1::get_fiber_core_mat(), PHG4CylinderGeom_Spacalv1::get_fiber_outer_r(), PHG4Detector::GetName(), PHG4CylinderGeom_Spacalv1::is_virualize_fiber(), PHG4Detector::overlapcheck, and PHG4Utils::SetColour().
Referenced by Construct_Fibers_SameLengthFiberPerTower().
int PHG4SpacalPrototypeDetector::Construct_Fibers_SameLengthFiberPerTower (const SpacalGeom_t::geom_tower & tower, G4LogicalVolume * LV_tower) virtual
Fully projective spacal with 2D tapered modules. To speed up construction, same-length fiber is used cross one tower.
Definition at line 651 of file PHG4SpacalPrototypeDetector.cc.
References _geom, PHG4CylinderGeom_Spacalv3::geom_tower::compose_fiber_id(), Construct_Fiber(), fiber_vol, PHG4CylinderGeom_Spacalv1::get_construction_verbose(), PHG4CylinderGeom_Spacalv1::get_fiber_outer_r(), PHG4Detector::GetName(), PHG4CylinderGeom_Spacalv3::geom_tower::id, PHG4CylinderGeom_Spacalv3::geom_tower::ModuleSkinThickness, PHG4Detector::name, PHG4CylinderGeom_Spacalv3::geom_tower::NFiberX, PHG4CylinderGeom_Spacalv3::geom_tower::NFiberY, PHG4Detector::overlapcheck, PHG4CylinderGeom_Spacalv3::geom_tower::pAlp1, PHG4CylinderGeom_Spacalv3::geom_tower::pAlp2, PHG4CylinderGeom_Spacalv3::geom_tower::pDx1, PHG4CylinderGeom_Spacalv3::geom_tower::pDx2, PHG4CylinderGeom_Spacalv3::geom_tower::pDx3, PHG4CylinderGeom_Spacalv3::geom_tower::pDx4, PHG4CylinderGeom_Spacalv3::geom_tower::pDy1, PHG4CylinderGeom_Spacalv3::geom_tower::pDy2, PHG4CylinderGeom_Spacalv3::geom_tower::pDz, PHG4CylinderGeom_Spacalv3::geom_tower::pPhi, and PHG4CylinderGeom_Spacalv3::geom_tower::pTheta.
Referenced by Construct_Tower().
G4LogicalVolume * PHG4SpacalPrototypeDetector::Construct_LightGuide (const SpacalGeom_t::geom_tower & tower, const int index_x, const int index_y) virtual
a block for the light guide along z axis that fit to the tower
Definition at line 872 of file PHG4SpacalPrototypeDetector.cc.
References _geom, PHG4Detector::GetName(), PHG4CylinderGeom_Spacalv3::geom_tower::id, PHG4CylinderGeom_Spacalv2::is_azimuthal_seg_visible(), PHG4CylinderGeom_Spacalv1::is_virualize_fiber(), PHG4CylinderGeom_Spacalv3::geom_tower::LightguideHeight, PHG4CylinderGeom_Spacalv3::geom_tower::LightguideMaterial, PHG4CylinderGeom_Spacalv3::geom_tower::LightguideTaperRatio, PHG4CylinderGeom_Spacalv3::geom_tower::NSubtowerX, PHG4CylinderGeom_Spacalv3::geom_tower::NSubtowerY, PHG4CylinderGeom_Spacalv3::geom_tower::pAlp1, PHG4CylinderGeom_Spacalv3::geom_tower::pDx1, PHG4CylinderGeom_Spacalv3::geom_tower::pDx2, PHG4CylinderGeom_Spacalv3::geom_tower::pDy1, PHG4CylinderGeom_Spacalv3::geom_tower::pDz, PHG4CylinderGeom_Spacalv3::geom_tower::pPhi, PHG4CylinderGeom_Spacalv3::geom_tower::pTheta, PHG4Utils::SetColour(), and step_limits.
Referenced by Construct_AzimuthalSeg().
G4LogicalVolume * PHG4SpacalPrototypeDetector::Construct_Tower (const SpacalGeom_t::geom_tower & tower) virtual
a block along z axis built with G4Trd that is slightly tapered in x dimension
Definition at line 812 of file PHG4SpacalPrototypeDetector.cc.
References _geom, Construct_Fibers_SameLengthFiberPerTower(), PHG4CylinderGeom_Spacalv1::get_absorber_mat(), PHG4CylinderGeom_Spacalv1::get_construction_verbose(), PHG4Detector::GetName(), PHG4CylinderGeom_Spacalv3::geom_tower::id, PHG4CylinderGeom_Spacalv3::geom_tower::identify(), PHG4CylinderGeom_Spacalv2::is_azimuthal_seg_visible(), PHG4CylinderGeom_Spacalv1::is_virualize_fiber(), PHG4CylinderGeom_Spacalv3::geom_tower::pAlp1, PHG4CylinderGeom_Spacalv3::geom_tower::pAlp2, PHG4CylinderGeom_Spacalv3::geom_tower::pDx1, PHG4CylinderGeom_Spacalv3::geom_tower::pDx2, PHG4CylinderGeom_Spacalv3::geom_tower::pDx3, PHG4CylinderGeom_Spacalv3::geom_tower::pDx4, PHG4CylinderGeom_Spacalv3::geom_tower::pDy1, PHG4CylinderGeom_Spacalv3::geom_tower::pDy2, PHG4CylinderGeom_Spacalv3::geom_tower::pDz, PHG4CylinderGeom_Spacalv3::geom_tower::pPhi, PHG4CylinderGeom_Spacalv3::geom_tower::pTheta, and step_limits.
Referenced by Construct_AzimuthalSeg().
const SpacalGeom_t* PHG4SpacalPrototypeDetector::get_geom () const inline
Definition at line 95 of file PHG4SpacalPrototypeDetector.h.
References _geom.
Referenced by PHG4SpacalPrototypeSteppingAction::get_zmax(), PHG4SpacalPrototypeSteppingAction::get_zmin(), and PHG4SpacalPrototypeSteppingAction::UserSteppingAction().
int PHG4SpacalPrototypeDetector::IsInCylinderActive (const G4VPhysicalVolume * volume)
Definition at line 77 of file PHG4SpacalPrototypeDetector.cc.
References ABSORBER, absorberactive, active, block_vol, calo_vol, FIBER_CLADING, FIBER_CORE, fiber_core_vol, fiber_vol, INACTIVE, and SUPPORT.
Referenced by PHG4SpacalPrototypeSteppingAction::UserSteppingAction().
void PHG4SpacalPrototypeDetector::Print (const std::string & what = "ALL") const virtual
Reimplemented from PHG4Detector.
Definition at line 637 of file PHG4SpacalPrototypeDetector.cc.
References _geom, PHG4Detector::GetName(), and PHG4CylinderGeom_Spacalv3::Print().
Referenced by Construct(), and PHG4SpacalPrototypeSubsystem::Print().
void PHG4SpacalPrototypeDetector::SetAbsorberActive (const int i = 1) inline
Definition at line 65 of file PHG4SpacalPrototypeDetector.h.
References absorberactive.
Referenced by PHG4SpacalPrototypeSubsystem::InitRunSubsystem().
void PHG4SpacalPrototypeDetector::SetActive (const int i = 1) inline
Definition at line 59 of file PHG4SpacalPrototypeDetector.h.
References active.
Referenced by PHG4SpacalPrototypeSubsystem::InitRunSubsystem().
void PHG4SpacalPrototypeDetector::SetDetectorType (const std::string & typ) inline
Definition at line 71 of file PHG4SpacalPrototypeDetector.h.
References detector_type.
void PHG4SpacalPrototypeDetector::SuperDetector (const std::string & name) inline
Definition at line 80 of file PHG4SpacalPrototypeDetector.h.
References PHG4Detector::name, and superdetector.
Referenced by PHG4SpacalPrototypeSubsystem::InitRunSubsystem(), and PHG4SpacalPrototypeSteppingAction::SetInterfacePointers().
const std::string PHG4SpacalPrototypeDetector::SuperDetector () const inline
Definition at line 86 of file PHG4SpacalPrototypeDetector.h.
References superdetector.
Member Data Documentation
SpacalGeom_t* PHG4SpacalPrototypeDetector::_geom private
Definition at line 137 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct(), Construct_AzimuthalSeg(), Construct_Fiber(), Construct_Fibers_SameLengthFiberPerTower(), Construct_LightGuide(), Construct_Tower(), get_geom(), Print(), and ~PHG4SpacalPrototypeDetector().
int PHG4SpacalPrototypeDetector::absorberactive protected
Definition at line 128 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct(), IsInCylinderActive(), and SetAbsorberActive().
int PHG4SpacalPrototypeDetector::active protected
Definition at line 127 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct(), IsInCylinderActive(), and SetActive().
std::map<const G4VPhysicalVolume*, int> PHG4SpacalPrototypeDetector::block_vol protected
map for G4VPhysicalVolume -> towers ID
Definition at line 125 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct_AzimuthalSeg(), and IsInCylinderActive().
std::map<const G4VPhysicalVolume*, int> PHG4SpacalPrototypeDetector::calo_vol protected
map for G4VPhysicalVolume -> Sector ID
Definition at line 122 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct(), and IsInCylinderActive().
G4UserLimits* PHG4SpacalPrototypeDetector::clading_step_limits protected
Definition at line 133 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct(), Construct_Fiber(), and ~PHG4SpacalPrototypeDetector().
PHParameters* PHG4SpacalPrototypeDetector::construction_params protected
Definition at line 111 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct().
G4LogicalVolume* PHG4SpacalPrototypeDetector::cylinder_logic protected
Definition at line 114 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct().
G4VPhysicalVolume* PHG4SpacalPrototypeDetector::cylinder_physi protected
Definition at line 115 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct().
G4VSolid* PHG4SpacalPrototypeDetector::cylinder_solid protected
Definition at line 113 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct().
std::string PHG4SpacalPrototypeDetector::detector_type protected
Definition at line 129 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct(), and SetDetectorType().
G4UserLimits* PHG4SpacalPrototypeDetector::fiber_core_step_limits protected
Definition at line 134 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct(), Construct_Fiber(), and ~PHG4SpacalPrototypeDetector().
std::map<const G4VPhysicalVolume*, int> PHG4SpacalPrototypeDetector::fiber_core_vol protected
Definition at line 116 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct_Fiber(), and IsInCylinderActive().
std::map<const G4VPhysicalVolume*, int> PHG4SpacalPrototypeDetector::fiber_vol protected
map for G4VPhysicalVolume -> fiber ID
Definition at line 119 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct_Fibers_SameLengthFiberPerTower(), and IsInCylinderActive().
G4UserLimits* PHG4SpacalPrototypeDetector::step_limits protected
Definition at line 132 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct(), Construct_AzimuthalSeg(), Construct_LightGuide(), Construct_Tower(), and ~PHG4SpacalPrototypeDetector().
std::string PHG4SpacalPrototypeDetector::superdetector protected
Definition at line 130 of file PHG4SpacalPrototypeDetector.h.
Referenced by Construct(), and SuperDetector().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SpacalPrototypeDetector.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SpacalPrototypeDetector.cc