E1039 Software: PHG4PhenixDetector Class Reference
PHG4PhenixDetector Class Reference
this is the main detector construction class, passed to geant to construct the entire phenix detector
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4PhenixDetector.h>
Public Member Functions
PHG4PhenixDetector ()
constructor
virtual ~PHG4PhenixDetector ()
destructor
void Verbosity (int verb)
void AddDetector (PHG4Detector *detector)
register a detector. This is called in PHG4Reco::Init based on which detectors are found on the tree
virtual G4VPhysicalVolume * Construct (void)
this is called by geant to actually construct all detectors
G4double GetWorldSizeX () const
G4double GetWorldSizeY () const
G4double GetWorldSizeZ () const
void SetWorldSizeX (const G4double sx)
void SetWorldSizeY (const G4double sy)
void SetWorldSizeZ (const G4double sz)
void SetWorldShape (const std::string &s)
void SetWorldMaterial (const std::string &s)
G4VPhysicalVolume * GetPhysicalVolume (void)
Private Types
typedef std::list< PHG4Detector * > DetectorList
list of detectors to be constructed
Private Attributes
int verbosity
DetectorList detectors_
G4Material * defaultMaterial
G4LogicalVolume * logicWorld
G4VPhysicalVolume * physiWorld
G4double WorldSizeX
G4double WorldSizeY
G4double WorldSizeZ
std::string worldshape
std::string worldmaterial
Detailed Description
this is the main detector construction class, passed to geant to construct the entire phenix detector
Definition at line 14 of file PHG4PhenixDetector.h.
Member Typedef Documentation
DetectorList
typedef std::list<PHG4Detector*> PHG4PhenixDetector::DetectorList private
list of detectors to be constructed
Definition at line 56 of file PHG4PhenixDetector.h.
Constructor & Destructor Documentation
PHG4PhenixDetector()
PHG4PhenixDetector::PHG4PhenixDetector (void)
constructor
Definition at line 27 of file PHG4PhenixDetector.cc.
~PHG4PhenixDetector()
PHG4PhenixDetector::~PHG4PhenixDetector () virtual
destructor
Definition at line 40 of file PHG4PhenixDetector.cc.
References detectors_.
Member Function Documentation
AddDetector()
void PHG4PhenixDetector::AddDetector (PHG4Detector * detector) inline
register a detector. This is called in PHG4Reco::Init based on which detectors are found on the tree
Definition at line 28 of file PHG4PhenixDetector.h.
References Construct(), and detectors_.
Referenced by PHG4Reco::InitRun().
Construct()
G4VPhysicalVolume * PHG4PhenixDetector::Construct (void) virtual
this is called by geant to actually construct all detectors
Definition at line 51 of file PHG4PhenixDetector.cc.
References detectors_, recoConsts::instance(), logicWorld, NULL, physiWorld, PHFlag::set_CharFlag(), PHG4RegionInformation::SetWorld(), verbosity, worldmaterial, worldshape, WorldSizeX, WorldSizeY, and WorldSizeZ.
Referenced by AddDetector().
GetPhysicalVolume()
G4VPhysicalVolume* PHG4PhenixDetector::GetPhysicalVolume (void) inline
Definition at line 48 of file PHG4PhenixDetector.h.
References physiWorld.
Referenced by PHG4Reco::Dump_GDML().
GetWorldSizeX()
G4double PHG4PhenixDetector::GetWorldSizeX () const inline
Definition at line 34 of file PHG4PhenixDetector.h.
References WorldSizeX.
GetWorldSizeY()
G4double PHG4PhenixDetector::GetWorldSizeY () const inline
Definition at line 37 of file PHG4PhenixDetector.h.
References WorldSizeY.
GetWorldSizeZ()
G4double PHG4PhenixDetector::GetWorldSizeZ () const inline
Definition at line 39 of file PHG4PhenixDetector.h.
References WorldSizeZ.
SetWorldMaterial()
void PHG4PhenixDetector::SetWorldMaterial (const std::string & s) inline
Definition at line 47 of file PHG4PhenixDetector.h.
References worldmaterial.
Referenced by PHG4Reco::InitRun().
SetWorldShape()
void PHG4PhenixDetector::SetWorldShape (const std::string & s) inline
Definition at line 46 of file PHG4PhenixDetector.h.
References worldshape.
Referenced by PHG4Reco::InitRun().
SetWorldSizeX()
void PHG4PhenixDetector::SetWorldSizeX (const G4double sx) inline
Definition at line 42 of file PHG4PhenixDetector.h.
References WorldSizeX.
Referenced by PHG4Reco::InitRun().
SetWorldSizeY()
void PHG4PhenixDetector::SetWorldSizeY (const G4double sy) inline
Definition at line 43 of file PHG4PhenixDetector.h.
References WorldSizeY.
Referenced by PHG4Reco::InitRun().
SetWorldSizeZ()
void PHG4PhenixDetector::SetWorldSizeZ (const G4double sz) inline
Definition at line 44 of file PHG4PhenixDetector.h.
References WorldSizeZ.
Referenced by PHG4Reco::InitRun().
Verbosity()
void PHG4PhenixDetector::Verbosity (int verb) inline
Definition at line 25 of file PHG4PhenixDetector.h.
References verbosity.
Referenced by PHG4Reco::InitRun().
Member Data Documentation
defaultMaterial
G4Material* PHG4PhenixDetector::defaultMaterial private
Definition at line 59 of file PHG4PhenixDetector.h.
detectors_
DetectorList PHG4PhenixDetector::detectors_ private
Definition at line 57 of file PHG4PhenixDetector.h.
Referenced by AddDetector(), Construct(), and ~PHG4PhenixDetector().
logicWorld
G4LogicalVolume* PHG4PhenixDetector::logicWorld private
Definition at line 61 of file PHG4PhenixDetector.h.
Referenced by Construct().
physiWorld
G4VPhysicalVolume* PHG4PhenixDetector::physiWorld private
Definition at line 62 of file PHG4PhenixDetector.h.
Referenced by Construct(), and GetPhysicalVolume().
verbosity
int PHG4PhenixDetector::verbosity private
Definition at line 53 of file PHG4PhenixDetector.h.
Referenced by Construct(), and Verbosity().
worldmaterial
std::string PHG4PhenixDetector::worldmaterial private
Definition at line 67 of file PHG4PhenixDetector.h.
Referenced by Construct(), and SetWorldMaterial().
worldshape
std::string PHG4PhenixDetector::worldshape private
Definition at line 66 of file PHG4PhenixDetector.h.
Referenced by Construct(), and SetWorldShape().
WorldSizeX
G4double PHG4PhenixDetector::WorldSizeX private
Definition at line 63 of file PHG4PhenixDetector.h.
Referenced by Construct(), GetWorldSizeX(), and SetWorldSizeX().
WorldSizeY
G4double PHG4PhenixDetector::WorldSizeY private
Definition at line 64 of file PHG4PhenixDetector.h.
Referenced by Construct(), GetWorldSizeY(), and SetWorldSizeY().
WorldSizeZ
G4double PHG4PhenixDetector::WorldSizeZ private
Definition at line 65 of file PHG4PhenixDetector.h.
Referenced by Construct(), GetWorldSizeZ(), and SetWorldSizeZ().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4PhenixDetector.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4PhenixDetector.cc