E1039 Software: KalmanFastTrackingWrapper Class Reference
KalmanFastTrackingWrapper Class Reference
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/ktracker/KalmanFastTrackingWrapper.h>
Public Types
enum INPUPT_TYPE { E1039, E906 }
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Public Member Functions
KalmanFastTrackingWrapper (const std::string &name="KalmanFastTrackingWrapper")
virtual ~KalmanFastTrackingWrapper ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int InitEvalTree ()
int ResetEvalVars ()
const std::string & get_hit_container_choice () const
void set_hit_container_choice (const std::string &hitContainerChoice)
const std::string & get_out_name () const
void set_out_name (const std::string &outName)
const std::string & get_geom_file_name () const
void set_geom_file_name (const std::string &geomFileName)
bool is_enable_KF () const
void set_enable_KF (bool enableKf)
bool is_enable_event_reducer () const
void set_enable_event_reducer (bool enableEventReducer)
int get_DS_level () const
void set_DS_level (int DS)
const std::string & get_pattern_db_name () const
void set_pattern_db_name (const std::string &patternDbName)
const std::string & get_sim_db_name () const
void set_sim_db_name (const std::string &simDbName)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int InitField (PHCompositeNode *topNode)
int InitGeom (PHCompositeNode *topNode)
int MakeNodes (PHCompositeNode *topNode)
int GetNodes (PHCompositeNode *topNode)
int ReMaskHits (SRawEvent *sraw_event)
SRawEvent * BuildSRawEvent ()
Private Attributes
KalmanFastTrackingWrapper::INPUPT_TYPE _input_type
bool _enable_KF
bool _enable_event_reducer
int _DS_level
std::string _sim_db_name
std::string _pattern_db_name
KalmanFastTracking * fastfinder
EventReducer * eventReducer
std::string _hit_container_type
size_t _event
SQRun * _run_header
SQSpillMap * _spill_map
SQEvent * _event_header
SQHitMap * _hit_map
SQHitVector * _hit_vector
SQHitVector * _triggerhit_vector
std::string _out_name
TTree * _tout
SRawEvent * _rawEvent
SRecEvent * _recEvent
JobOptsSvc * p_jobOptsSvc
std::string _geom_file_name
TGeoManager * _t_geo_manager
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 41 of file KalmanFastTrackingWrapper.h.
Member Enumeration Documentation
enum KalmanFastTrackingWrapper::INPUPT_TYPE
Enumerator
E1039
E906
Definition at line 44 of file KalmanFastTrackingWrapper.h.
Constructor & Destructor Documentation
KalmanFastTrackingWrapper::KalmanFastTrackingWrapper (const std::string & name = "KalmanFastTrackingWrapper")
Definition at line 56 of file KalmanFastTrackingWrapper.cxx.
References JobOptsSvc::instance(), and p_jobOptsSvc.
virtual KalmanFastTrackingWrapper::~KalmanFastTrackingWrapper () inline virtual
Definition at line 47 of file KalmanFastTrackingWrapper.h.
Member Function Documentation
SRawEvent * KalmanFastTrackingWrapper::BuildSRawEvent () private
Definition at line 190 of file KalmanFastTrackingWrapper.cxx.
References _event, _event_header, _hit_vector, _spill_map, _triggerhit_vector, SQHitVector::begin(), Hit::detectorID, Hit::driftDistance, Hit::elementID, SQHitVector::end(), SQSpillMap::get(), SQHit::get_detector_id(), SQHit::get_drift_distance(), SQHit::get_element_id(), SQEvent::get_event_id(), SQHit::get_hit_id(), SQHit::get_pos(), SQEvent::get_run_id(), SQEvent::get_spill_id(), SQSpill::get_target_pos(), SQHit::get_tdc_time(), SQEvent::get_trigger(), Hit::index, SRawEvent::insertHit(), SRawEvent::insertTriggerHit(), SQHit::is_hodo_mask(), SQHit::is_in_time(), LogDebug, LogError, SQEvent::MATRIX5, SQEvent::NIM1, Hit::pos, SRawEvent::reIndex(), SRawEvent::setEventInfo(), Hit::setHodoMask(), Hit::setInTime(), SRawEvent::setTargetPos(), SRawEvent::setTriggerBits(), Hit::tdcTime, and Fun4AllBase::verbosity.
Referenced by process_event().
int KalmanFastTrackingWrapper::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 398 of file KalmanFastTrackingWrapper.cxx.
References _out_name, _tout, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, fastfinder, PHTFileServer::get(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int KalmanFastTrackingWrapper::get_DS_level () const inline
Definition at line 101 of file KalmanFastTrackingWrapper.h.
References _DS_level.
const std::string& KalmanFastTrackingWrapper::get_geom_file_name () const inline
Definition at line 76 of file KalmanFastTrackingWrapper.h.
References _geom_file_name.
const std::string& KalmanFastTrackingWrapper::get_hit_container_choice () const inline
Definition at line 60 of file KalmanFastTrackingWrapper.h.
References _hit_container_type.
const std::string& KalmanFastTrackingWrapper::get_out_name () const inline
Definition at line 68 of file KalmanFastTrackingWrapper.h.
References _out_name.
const std::string& KalmanFastTrackingWrapper::get_pattern_db_name () const inline
Definition at line 109 of file KalmanFastTrackingWrapper.h.
References _pattern_db_name.
const std::string& KalmanFastTrackingWrapper::get_sim_db_name () const inline
Definition at line 117 of file KalmanFastTrackingWrapper.h.
References _sim_db_name.
int KalmanFastTrackingWrapper::GetNodes (PHCompositeNode * topNode) private
Definition at line 471 of file KalmanFastTrackingWrapper.cxx.
References _event_header, _hit_container_type, _hit_map, _hit_vector, _input_type, _rawEvent, _recEvent, _run_header, _spill_map, _triggerhit_vector, Fun4AllReturnCodes::ABORTEVENT, E906, Fun4AllReturnCodes::EVENT_OK, LogError, LogInfo, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int KalmanFastTrackingWrapper::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 79 of file KalmanFastTrackingWrapper.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int KalmanFastTrackingWrapper::InitEvalTree ()
Definition at line 410 of file KalmanFastTrackingWrapper.cxx.
References _out_name, _recEvent, _tout, PHTFileServer::get(), and PHTFileServer::open().
Referenced by InitRun().
int KalmanFastTrackingWrapper::InitField (PHCompositeNode * topNode) private
Definition at line 130 of file KalmanFastTrackingWrapper.cxx.
References Fun4AllReturnCodes::EVENT_OK, PHFieldUtility::GetFieldMapNode(), JobOptsSvc::m_fMagFile, JobOptsSvc::m_kMagFile, p_jobOptsSvc, and Fun4AllBase::verbosity.
Referenced by InitRun().
int KalmanFastTrackingWrapper::InitGeom (PHCompositeNode * topNode) private
Definition at line 150 of file KalmanFastTrackingWrapper.cxx.
References _geom_file_name, _t_geo_manager, Fun4AllReturnCodes::EVENT_OK, PHGeomUtility::GetTGeoManager(), PHGeomUtility::ImportGeomFile(), and Fun4AllBase::verbosity.
Referenced by InitRun().
int KalmanFastTrackingWrapper::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
init KalmanDSTrk
Reimplemented from SubsysReco.
Definition at line 83 of file KalmanFastTrackingWrapper.cxx.
References _enable_event_reducer, _enable_KF, _t_geo_manager, Fun4AllReturnCodes::EVENT_OK, eventReducer, fastfinder, PHFieldUtility::GetFieldMapNode(), GetNodes(), PHField::identify(), InitEvalTree(), InitField(), InitGeom(), JobOptsSvc::m_enableTriggerMask, JobOptsSvc::m_hodomask, JobOptsSvc::m_mergeHodo, JobOptsSvc::m_realization, JobOptsSvc::m_sagittaReducer, JobOptsSvc::m_updateAlignment, MakeNodes(), p_jobOptsSvc, ResetEvalVars(), KalmanFastTracking::Verbosity(), and Fun4AllBase::verbosity.
bool KalmanFastTrackingWrapper::is_enable_event_reducer () const inline
Definition at line 92 of file KalmanFastTrackingWrapper.h.
References _enable_event_reducer.
bool KalmanFastTrackingWrapper::is_enable_KF () const inline
Definition at line 84 of file KalmanFastTrackingWrapper.h.
References _enable_KF.
int KalmanFastTrackingWrapper::MakeNodes (PHCompositeNode * topNode) private
Definition at line 431 of file KalmanFastTrackingWrapper.cxx.
References _recEvent, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), LogInfo, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_SOME.
Referenced by InitRun().
int KalmanFastTrackingWrapper::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 295 of file KalmanFastTrackingWrapper.cxx.
References _enable_event_reducer, _event, _event_header, _hit_vector, _input_type, _rawEvent, _recEvent, _spill_map, _tout, BuildSRawEvent(), E1039, Fun4AllReturnCodes::EVENT_OK, eventReducer, fastfinder, SQEvent::get_event_id(), SQEvent::get_run_id(), SQEvent::get_spill_id(), KalmanFastTracking::getFinalTracklets(), KalmanFastTracking::getSRecTracks(), SRawEvent::identify(), SRecEvent::insertTrack(), LogDebug, LogInfo, SRecTrack::print(), KalmanFastTracking::printTimers(), EventReducer::reduceEvent(), ReMaskHits(), ResetEvalVars(), KalmanFastTracking::setRawEvent(), SRecEvent::setRawEvent(), SRecEvent::setRecStatus(), Fun4AllBase::Verbosity(), Fun4AllBase::verbosity, Fun4AllBase::VERBOSITY_A_LOT, and Fun4AllBase::VERBOSITY_SOME.
int KalmanFastTrackingWrapper::ReMaskHits (SRawEvent * sraw_event) private
Definition at line 170 of file KalmanFastTrackingWrapper.cxx.
References _hit_vector, SQHitVector::at(), SQHit::get_hit_id(), SRawEvent::getAllHits(), SQHit::set_hodo_mask(), and SQHitVector::size().
Referenced by process_event().
int KalmanFastTrackingWrapper::ResetEvalVars ()
Definition at line 424 of file KalmanFastTrackingWrapper.cxx.
Referenced by InitRun(), and process_event().
void KalmanFastTrackingWrapper::set_DS_level (int DS) inline
Definition at line 105 of file KalmanFastTrackingWrapper.h.
References _DS_level.
Referenced by Fun4CODA(), Fun4DB(), Fun4DST(), Fun4MainDaq(), Fun4Sim(), Fun4SRawEvent(), and Fun4TrkDev().
void KalmanFastTrackingWrapper::set_enable_event_reducer (bool enableEventReducer) inline
Definition at line 96 of file KalmanFastTrackingWrapper.h.
References _enable_event_reducer.
Referenced by Fun4CODA(), Fun4DB(), Fun4DST(), Fun4MainDaq(), Fun4Sim(), and Fun4SRawEvent().
void KalmanFastTrackingWrapper::set_enable_KF (bool enableKf) inline
Definition at line 88 of file KalmanFastTrackingWrapper.h.
References _enable_KF.
void KalmanFastTrackingWrapper::set_geom_file_name (const std::string & geomFileName) inline
Definition at line 80 of file KalmanFastTrackingWrapper.h.
References _geom_file_name.
Referenced by Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4kTracker(), and Fun4Sim().
void KalmanFastTrackingWrapper::set_hit_container_choice (const std::string & hitContainerChoice) inline
Definition at line 64 of file KalmanFastTrackingWrapper.h.
References _hit_container_type.
void KalmanFastTrackingWrapper::set_out_name (const std::string & outName) inline
Definition at line 72 of file KalmanFastTrackingWrapper.h.
References _out_name.
void KalmanFastTrackingWrapper::set_pattern_db_name (const std::string & patternDbName) inline
Definition at line 113 of file KalmanFastTrackingWrapper.h.
References _pattern_db_name.
Referenced by Fun4CODA(), Fun4Sim(), and Fun4SRawEvent().
void KalmanFastTrackingWrapper::set_sim_db_name (const std::string & simDbName) inline
Definition at line 121 of file KalmanFastTrackingWrapper.h.
References _sim_db_name.
Member Data Documentation
int KalmanFastTrackingWrapper::_DS_level private
Definition at line 143 of file KalmanFastTrackingWrapper.h.
Referenced by get_DS_level(), and set_DS_level().
bool KalmanFastTrackingWrapper::_enable_event_reducer private
Definition at line 141 of file KalmanFastTrackingWrapper.h.
Referenced by InitRun(), is_enable_event_reducer(), process_event(), and set_enable_event_reducer().
bool KalmanFastTrackingWrapper::_enable_KF private
Definition at line 140 of file KalmanFastTrackingWrapper.h.
Referenced by InitRun(), is_enable_KF(), and set_enable_KF().
size_t KalmanFastTrackingWrapper::_event private
Definition at line 155 of file KalmanFastTrackingWrapper.h.
Referenced by BuildSRawEvent(), and process_event().
SQEvent* KalmanFastTrackingWrapper::_event_header private
Definition at line 160 of file KalmanFastTrackingWrapper.h.
Referenced by BuildSRawEvent(), GetNodes(), and process_event().
std::string KalmanFastTrackingWrapper::_geom_file_name private
Definition at line 172 of file KalmanFastTrackingWrapper.h.
Referenced by get_geom_file_name(), InitGeom(), and set_geom_file_name().
std::string KalmanFastTrackingWrapper::_hit_container_type private
Definition at line 153 of file KalmanFastTrackingWrapper.h.
Referenced by get_hit_container_choice(), GetNodes(), and set_hit_container_choice().
SQHitMap* KalmanFastTrackingWrapper::_hit_map private
Definition at line 161 of file KalmanFastTrackingWrapper.h.
Referenced by GetNodes().
SQHitVector* KalmanFastTrackingWrapper::_hit_vector private
Definition at line 162 of file KalmanFastTrackingWrapper.h.
Referenced by BuildSRawEvent(), GetNodes(), process_event(), and ReMaskHits().
KalmanFastTrackingWrapper::INPUPT_TYPE KalmanFastTrackingWrapper::_input_type private
Definition at line 139 of file KalmanFastTrackingWrapper.h.
Referenced by GetNodes(), and process_event().
std::string KalmanFastTrackingWrapper::_out_name private
Definition at line 165 of file KalmanFastTrackingWrapper.h.
Referenced by End(), get_out_name(), InitEvalTree(), and set_out_name().
std::string KalmanFastTrackingWrapper::_pattern_db_name private
Definition at line 145 of file KalmanFastTrackingWrapper.h.
Referenced by get_pattern_db_name(), and set_pattern_db_name().
SRawEvent* KalmanFastTrackingWrapper::_rawEvent private
Definition at line 168 of file KalmanFastTrackingWrapper.h.
Referenced by GetNodes(), and process_event().
SRecEvent* KalmanFastTrackingWrapper::_recEvent private
Definition at line 169 of file KalmanFastTrackingWrapper.h.
Referenced by GetNodes(), InitEvalTree(), MakeNodes(), and process_event().
SQRun* KalmanFastTrackingWrapper::_run_header private
Definition at line 157 of file KalmanFastTrackingWrapper.h.
Referenced by GetNodes().
std::string KalmanFastTrackingWrapper::_sim_db_name private
Definition at line 144 of file KalmanFastTrackingWrapper.h.
Referenced by get_sim_db_name(), and set_sim_db_name().
SQSpillMap* KalmanFastTrackingWrapper::_spill_map private
Definition at line 158 of file KalmanFastTrackingWrapper.h.
Referenced by BuildSRawEvent(), GetNodes(), and process_event().
TGeoManager* KalmanFastTrackingWrapper::_t_geo_manager private
Definition at line 173 of file KalmanFastTrackingWrapper.h.
Referenced by InitGeom(), and InitRun().
TTree* KalmanFastTrackingWrapper::_tout private
Definition at line 166 of file KalmanFastTrackingWrapper.h.
Referenced by End(), InitEvalTree(), and process_event().
SQHitVector* KalmanFastTrackingWrapper::_triggerhit_vector private
Definition at line 163 of file KalmanFastTrackingWrapper.h.
Referenced by BuildSRawEvent(), and GetNodes().
EventReducer* KalmanFastTrackingWrapper::eventReducer private
Definition at line 151 of file KalmanFastTrackingWrapper.h.
Referenced by InitRun(), and process_event().
KalmanFastTracking* KalmanFastTrackingWrapper::fastfinder private
Definition at line 149 of file KalmanFastTrackingWrapper.h.
Referenced by End(), InitRun(), and process_event().
JobOptsSvc* KalmanFastTrackingWrapper::p_jobOptsSvc private
Definition at line 171 of file KalmanFastTrackingWrapper.h.
Referenced by InitField(), InitRun(), and KalmanFastTrackingWrapper().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/ktracker/KalmanFastTrackingWrapper.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/ktracker/KalmanFastTrackingWrapper.cxx