Class Reference for E1039 Core & Analysis Software: PHG4TargetCoilDetector Class Reference
PHG4TargetCoilDetector Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4TargetCoilDetector.h>
Public Member Functions
PHG4TargetCoilDetector (PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~PHG4TargetCoilDetector (void)
destructor
void Construct (G4LogicalVolume *world)
construct
bool IsInCylinder (const G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
int get_elem_id (const std::string &name) const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 12 of file PHG4TargetCoilDetector.h.
Constructor & Destructor Documentation
PHG4TargetCoilDetector()
PHG4TargetCoilDetector::PHG4TargetCoilDetector (PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 30 of file PHG4TargetCoilDetector.cc.
~PHG4TargetCoilDetector()
virtual PHG4TargetCoilDetector::~PHG4TargetCoilDetector (void) inline virtual
destructor
Definition at line 19 of file PHG4TargetCoilDetector.h.
Member Function Documentation
Construct()
void PHG4TargetCoilDetector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 192 of file PHG4TargetCoilDetector.cc.
References PHParameters::get_double_param(), PHG4Detector::GetName(), PHG4Detector::name, PHG4Detector::overlapcheck, PHParameters::Print(), and PHG4Utils::SetColour().
get_elem_id()
int PHG4TargetCoilDetector::get_elem_id (const std::string & name) const
Definition at line 353 of file PHG4TargetCoilDetector.cc.
References PHG4Detector::name.
Referenced by PHG4TargetCoilSteppingAction::UserSteppingAction().
get_Layer()
int PHG4TargetCoilDetector::get_Layer () const inline
Definition at line 29 of file PHG4TargetCoilDetector.h.
Referenced by PHG4TargetCoilSteppingAction::UserSteppingAction().
IsInCylinder()
bool PHG4TargetCoilDetector::IsInCylinder (const G4VPhysicalVolume * volume) const
Definition at line 39 of file PHG4TargetCoilDetector.cc.
Referenced by PHG4TargetCoilSteppingAction::UserSteppingAction().
SuperDetector() [1/2]
const std::string PHG4TargetCoilDetector::SuperDetector () const inline
Definition at line 28 of file PHG4TargetCoilDetector.h.
SuperDetector() [2/2]
void PHG4TargetCoilDetector::SuperDetector (const std::string & name) inline
Definition at line 27 of file PHG4TargetCoilDetector.h.
References PHG4Detector::name.
Referenced by PHG4TargetCoilSubsystem::InitRunSubsystem(), PHG4TargetCoilSteppingAction::SetInterfacePointers(), and PHG4TargetCoilSteppingAction::UserSteppingAction().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4TargetCoilDetector.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4TargetCoilDetector.cc