Class Reference for E1039 Core & Analysis Software: Fun4AllVectEventInputManager Class Reference
Fun4AllVectEventInputManager Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Fun4AllVectFileManager/Fun4AllVectFileManager/src/Fun4AllVectEventInputManager.h>
Public Member Functions
Fun4AllVectEventInputManager (const std::string &name="DUMMY", const std::string &topnodename="TOP")
virtual ~Fun4AllVectEventInputManager ()
int fileopen (const std::string &filename)
int fileclose ()
int run (const int nevents=0)
int isOpen ()
void Print (const std::string &what="ALL") const
int ResetEvent ()
int PushBackEvents (const int i)
int GetSyncObject (SyncObject **mastersync)
int SyncIt (const SyncObject *mastersync)
const std::string & get_branch_name () const
void set_branch_name (const std::string &branchName)
const std::string & get_tree_name () const
void set_tree_name (const std::string &treeName)
Public Member Functions inherited from Fun4AllInputManager
virtual ~Fun4AllInputManager ()
virtual int ReadInRunNode (PHCompositeNode *)
virtual std::string Filename ()
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
virtual int skip (const int nevt)
virtual int NoSyncPushBackEvents (const int)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
int ResetFileList ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int OpenNextFile ()
void VectToE1039 ()
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
int segment
int isopen
int events_total
int events_thisfile
std::string topNodeName
PHCompositeNode * topNode
SyncObject * syncobject
std::string _tree_name
std::string _branch_name
TFile * _fin
TTree * _tin
int eventID
int spillID
int runID
std::vector< int > * detectorIDs = nullptr
std::vector< int > * elementIDs = nullptr
std::vector< double > * driftDistances = nullptr
std::vector< double > * tdcTimes = nullptr
std::vector< bool > * hitsInTime = nullptr
std::vector< int > * triggerDetectorIDs = nullptr
std::vector< int > * triggerElementIDs = nullptr
std::vector< double > * triggerTdcTimes = nullptr
std::vector< int > * triggerDriftDistances = nullptr
std::vector< bool > * triggerHitsInTime = nullptr
int fpgaTriggers [5] = {0}
int nimTriggers [5] = {0}
int rfIntensities [33] = {0}
SQRun * run_header
SQSpillMap * spill_map
SQEvent * event_header
SQHitVector * hit_vec
SQHitVector * trig_hit_vec
Protected Attributes inherited from Fun4AllInputManager
std::vector< SubsysReco * > Subsystems
std::string InputNode
std::string filename
std::string topNodeName
std::list< std::string > filelist
std::list< std::string > filelist_copy
std::list< std::string > filelist_opened
Fun4AllSyncManager * mySyncManager
int repeat
int myrunnumber
int initrun
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 18 of file Fun4AllVectEventInputManager.h.
Constructor & Destructor Documentation
Fun4AllVectEventInputManager()
Fun4AllVectEventInputManager::Fun4AllVectEventInputManager (const std::string & name = "DUMMY", const std::string & topnodename = "TOP")
Definition at line 32 of file Fun4AllVectEventInputManager.cc.
References PHCompositeNode::addNode(), event_header, PHNodeIterator::findFirst(), hit_vec, Fun4AllServer::instance(), run_header, spill_map, syncobject, topNode, Fun4AllServer::topNode(), topNodeName, and trig_hit_vec.
~Fun4AllVectEventInputManager()
Fun4AllVectEventInputManager::~Fun4AllVectEventInputManager () virtual
Definition at line 86 of file Fun4AllVectEventInputManager.cc.
References fileclose(), isopen, and syncobject.
Member Function Documentation
fileclose()
int Fun4AllVectEventInputManager::fileclose () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 266 of file Fun4AllVectEventInputManager.cc.
References _fin, Fun4AllInputManager::filelist, isopen, Fun4AllBase::Name(), and Fun4AllInputManager::repeat.
Referenced by fileopen(), run(), and ~Fun4AllVectEventInputManager().
fileopen()
int Fun4AllVectEventInputManager::fileopen (const std::string & filename) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 154 of file Fun4AllVectEventInputManager.cc.
References _fin, _tin, _tree_name, Fun4AllInputManager::AddToFileOpened(), detectorIDs, driftDistances, elementIDs, eventID, events_thisfile, fileclose(), Fun4AllInputManager::filename, fpgaTriggers, hitsInTime, isopen, nimTriggers, rfIntensities, runID, segment, spillID, tdcTimes, Fun4AllBase::ThisName, triggerDriftDistances, triggerElementIDs, triggerHitsInTime, triggerTdcTimes, and Fun4AllBase::verbosity.
Referenced by OpenNextFile().
get_branch_name()
const std::string& Fun4AllVectEventInputManager::get_branch_name () const inline
Definition at line 34 of file Fun4AllVectEventInputManager.h.
References _branch_name.
get_tree_name()
const std::string& Fun4AllVectEventInputManager::get_tree_name () const inline
Definition at line 37 of file Fun4AllVectEventInputManager.h.
References _tree_name.
GetSyncObject()
int Fun4AllVectEventInputManager::GetSyncObject (SyncObject ** mastersync) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 382 of file Fun4AllVectEventInputManager.cc.
References SyncObject::clone(), Fun4AllReturnCodes::SYNC_OK, and syncobject.
isOpen()
int Fun4AllVectEventInputManager::isOpen () inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 26 of file Fun4AllVectEventInputManager.h.
References isopen.
OpenNextFile()
int Fun4AllVectEventInputManager::OpenNextFile () protected
Definition at line 299 of file Fun4AllVectEventInputManager.cc.
References Fun4AllInputManager::filelist, fileopen(), PHWHERE, and Fun4AllBase::verbosity.
Referenced by run().
Print()
void Fun4AllVectEventInputManager::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllInputManager.
Definition at line 292 of file Fun4AllVectEventInputManager.cc.
References Fun4AllInputManager::Print().
PushBackEvents()
int Fun4AllVectEventInputManager::PushBackEvents (const int i) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 322 of file Fun4AllVectEventInputManager.cc.
ResetEvent()
int Fun4AllVectEventInputManager::ResetEvent () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 260 of file Fun4AllVectEventInputManager.cc.
References SyncObject::Reset(), and syncobject.
Referenced by run().
run()
int Fun4AllVectEventInputManager::run (const int nevents = 0) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 212 of file Fun4AllVectEventInputManager.cc.
References _tin, Fun4AllSyncManager::CurrentEvent(), Fun4AllReturnCodes::EVENT_OK, SyncObject::EventCounter(), eventID, SyncObject::EventNumber(), events_thisfile, events_total, fileclose(), Fun4AllInputManager::filelist, isopen, Fun4AllInputManager::mySyncManager, Fun4AllBase::Name(), OpenNextFile(), Fun4AllSyncManager::PrdfEvents(), Fun4AllInputManager::RejectEvent(), ResetEvent(), runID, SyncObject::RunNumber(), Fun4AllSyncManager::SegmentNumber(), SyncObject::SegmentNumber(), Fun4AllInputManager::SetRunNumber(), spillID, syncobject, VectToE1039(), and Fun4AllBase::verbosity.
set_branch_name()
void Fun4AllVectEventInputManager::set_branch_name (const std::string & branchName) inline
Definition at line 35 of file Fun4AllVectEventInputManager.h.
References _branch_name.
set_tree_name()
void Fun4AllVectEventInputManager::set_tree_name (const std::string & treeName) inline
Definition at line 38 of file Fun4AllVectEventInputManager.h.
References _tree_name.
SyncIt()
int Fun4AllVectEventInputManager::SyncIt (const SyncObject * mastersync) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 400 of file Fun4AllVectEventInputManager.cc.
References SyncObject::Different(), Fun4AllBase::Name(), PHWHERE, Fun4AllReturnCodes::SYNC_FAIL, Fun4AllReturnCodes::SYNC_OK, and syncobject.
VectToE1039()
void Fun4AllVectEventInputManager::VectToE1039 () protected
Definition at line 95 of file Fun4AllVectEventInputManager.cc.
References detectorIDs, driftDistances, elementIDs, event_header, eventID, fpgaTriggers, SQSpillMap::get(), hit_vec, hitsInTime, SQSpillMap::insert(), SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, SQEvent::MATRIX5, SQEvent::NIM1, SQEvent::NIM2, SQEvent::NIM3, SQEvent::NIM4, SQEvent::NIM5, nimTriggers, SQHitVector::push_back(), rfIntensities, run_header, runID, SQEvent::set_data_quality(), SQHit::set_detector_id(), SQHit::set_drift_distance(), SQHit::set_element_id(), SQEvent::set_event_id(), SQHit::set_hit_id(), SQHit::set_in_time(), SQRun::set_n_spill(), SQEvent::set_qie_rf_intensity(), SQSpill::set_run_id(), SQEvent::set_run_id(), SQSpill::set_spill_id(), SQEvent::set_spill_id(), SQHit::set_tdc_time(), SQEvent::set_trigger(), SQSpillMap::size(), spill_map, spillID, tdcTimes, trig_hit_vec, triggerDetectorIDs, triggerDriftDistances, triggerElementIDs, triggerHitsInTime, and triggerTdcTimes.
Referenced by run().
Member Data Documentation
_branch_name
std::string Fun4AllVectEventInputManager::_branch_name protected
Definition at line 52 of file Fun4AllVectEventInputManager.h.
Referenced by get_branch_name(), and set_branch_name().
_fin
TFile* Fun4AllVectEventInputManager::_fin protected
Definition at line 54 of file Fun4AllVectEventInputManager.h.
Referenced by fileclose(), and fileopen().
_tin
TTree* Fun4AllVectEventInputManager::_tin protected
Definition at line 55 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and run().
_tree_name
std::string Fun4AllVectEventInputManager::_tree_name protected
Definition at line 51 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), get_tree_name(), and set_tree_name().
detectorIDs
std::vector<int>* Fun4AllVectEventInputManager::detectorIDs = nullptr protected
Definition at line 60 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
driftDistances
std::vector<double>* Fun4AllVectEventInputManager::driftDistances = nullptr protected
Definition at line 62 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
elementIDs
std::vector<int>* Fun4AllVectEventInputManager::elementIDs = nullptr protected
Definition at line 61 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
event_header
SQEvent* Fun4AllVectEventInputManager::event_header protected
Definition at line 79 of file Fun4AllVectEventInputManager.h.
Referenced by Fun4AllVectEventInputManager(), and VectToE1039().
eventID
int Fun4AllVectEventInputManager::eventID protected
Definition at line 56 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), run(), and VectToE1039().
events_thisfile
int Fun4AllVectEventInputManager::events_thisfile protected
Definition at line 46 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and run().
events_total
int Fun4AllVectEventInputManager::events_total protected
Definition at line 45 of file Fun4AllVectEventInputManager.h.
Referenced by run().
fpgaTriggers
int Fun4AllVectEventInputManager::fpgaTriggers[5] = {0} protected
Definition at line 72 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
hit_vec
SQHitVector* Fun4AllVectEventInputManager::hit_vec protected
Definition at line 80 of file Fun4AllVectEventInputManager.h.
Referenced by Fun4AllVectEventInputManager(), and VectToE1039().
hitsInTime
std::vector<bool>* Fun4AllVectEventInputManager::hitsInTime = nullptr protected
Definition at line 64 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
isopen
int Fun4AllVectEventInputManager::isopen protected
Definition at line 44 of file Fun4AllVectEventInputManager.h.
Referenced by fileclose(), fileopen(), isOpen(), run(), and ~Fun4AllVectEventInputManager().
nimTriggers
int Fun4AllVectEventInputManager::nimTriggers[5] = {0} protected
Definition at line 73 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
rfIntensities
int Fun4AllVectEventInputManager::rfIntensities[33] = {0} protected
Definition at line 74 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
run_header
SQRun* Fun4AllVectEventInputManager::run_header protected
Definition at line 77 of file Fun4AllVectEventInputManager.h.
Referenced by Fun4AllVectEventInputManager(), and VectToE1039().
runID
int Fun4AllVectEventInputManager::runID protected
Definition at line 58 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), run(), and VectToE1039().
segment
int Fun4AllVectEventInputManager::segment protected
Definition at line 43 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen().
spill_map
SQSpillMap* Fun4AllVectEventInputManager::spill_map protected
Definition at line 78 of file Fun4AllVectEventInputManager.h.
Referenced by Fun4AllVectEventInputManager(), and VectToE1039().
spillID
int Fun4AllVectEventInputManager::spillID protected
Definition at line 57 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), run(), and VectToE1039().
syncobject
SyncObject* Fun4AllVectEventInputManager::syncobject protected
Definition at line 49 of file Fun4AllVectEventInputManager.h.
Referenced by Fun4AllVectEventInputManager(), GetSyncObject(), ResetEvent(), run(), SyncIt(), and ~Fun4AllVectEventInputManager().
tdcTimes
std::vector<double>* Fun4AllVectEventInputManager::tdcTimes = nullptr protected
Definition at line 63 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
topNode
PHCompositeNode* Fun4AllVectEventInputManager::topNode protected
Definition at line 48 of file Fun4AllVectEventInputManager.h.
Referenced by Fun4AllVectEventInputManager().
topNodeName
std::string Fun4AllVectEventInputManager::topNodeName protected
Definition at line 47 of file Fun4AllVectEventInputManager.h.
Referenced by Fun4AllVectEventInputManager().
trig_hit_vec
SQHitVector* Fun4AllVectEventInputManager::trig_hit_vec protected
Definition at line 81 of file Fun4AllVectEventInputManager.h.
Referenced by Fun4AllVectEventInputManager(), and VectToE1039().
triggerDetectorIDs
std::vector<int>* Fun4AllVectEventInputManager::triggerDetectorIDs = nullptr protected
Definition at line 66 of file Fun4AllVectEventInputManager.h.
Referenced by VectToE1039().
triggerDriftDistances
std::vector<int>* Fun4AllVectEventInputManager::triggerDriftDistances = nullptr protected
Definition at line 69 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
triggerElementIDs
std::vector<int>* Fun4AllVectEventInputManager::triggerElementIDs = nullptr protected
Definition at line 67 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
triggerHitsInTime
std::vector<bool>* Fun4AllVectEventInputManager::triggerHitsInTime = nullptr protected
Definition at line 70 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
triggerTdcTimes
std::vector<double>* Fun4AllVectEventInputManager::triggerTdcTimes = nullptr protected
Definition at line 68 of file Fun4AllVectEventInputManager.h.
Referenced by fileopen(), and VectToE1039().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Fun4AllVectFileManager/Fun4AllVectFileManager/src/Fun4AllVectEventInputManager.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Fun4AllVectFileManager/Fun4AllVectFileManager/src/Fun4AllVectEventInputManager.cc