SeaQuest Offline Software: PHG4MapsCellReco Class Reference
PHG4MapsCellReco Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4MapsCellReco.h>
Public Member Functions
PHG4MapsCellReco (const std::string &name="MAPSRECO")
virtual ~PHG4MapsCellReco ()
int InitRun (PHCompositeNode *topNode)
module initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
end of process
void Detector (const std::string &d)
void checkenergy (const int i=1)
double get_timing_window_min (const int i)
double get_timing_window_max (const int i)
void set_timing_window (const int detid, const double tmin, const double tmax)
void SetDefaultParameters ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHG4ParameterContainerInterface
PHG4ParameterContainerInterface (const std::string &name)
virtual ~PHG4ParameterContainerInterface ()
void set_name (const std::string &name)
void set_double_param (const int id, const std::string &name, const double dval)
double get_double_param (const int id, const std::string &name) const
void set_int_param (const int id, const std::string &name, const int ival)
int get_int_param (const int id, const std::string &name) const
void set_string_param (const int id, const std::string &name, const std::string &sval)
std::string get_string_param (const int id, const std::string &name) const
void UpdateParametersWithMacro ()
void CreateInitialize (const int detid)
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
int ExistDetid (const int detid) const
Protected Member Functions
bool lines_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double *rx, double *ry)
bool line_and_rectangle_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double *rr)
double circle_rectangle_intersection (double x1, double y1, double x2, double y2, double mx, double my, double r)
double sA (double r, double x, double y)
int CheckEnergy (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Member Functions inherited from PHG4ParameterContainerInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
const PHG4ParametersContainer * GetParamsContainer ()
PHG4ParametersContainer * GetParamsContainerModify ()
const PHG4Parameters * GetDefaultParameters ()
Static Protected Member Functions
static std::pair< double, double > get_etaphi (const double x, const double y, const double z)
static double get_eta (const double radius, const double z)
Protected Attributes
std::map< int, int > binning
std::map< int, std::pair
< double, int > > cell_size
std::map< int, std::pair
< double, double > > zmin_max
std::map< int, double > etastep
std::string detector
std::string hitnodename
std::string cellnodename
std::string geonodename
std::string seggeonodename
PHTimeServer::timer _timer
int nbins [2]
int chkenergyconservation
std::map< int, std::pair
< double, double > > tmin_max
std::map< unsigned long long,
PHG4Cell * > celllist
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 16 of file PHG4MapsCellReco.h.
Constructor & Destructor Documentation
PHG4MapsCellReco::PHG4MapsCellReco (const std::string & name = "MAPSRECO") explicit
Definition at line 34 of file PHG4MapsCellReco.cc.
References nbins, SetDefaultParameters(), and Fun4AllBase::verbosity.
virtual PHG4MapsCellReco::~PHG4MapsCellReco () inline virtual
Definition at line 22 of file PHG4MapsCellReco.h.
Member Function Documentation
void PHG4MapsCellReco::checkenergy (const int i = 1) inline
Definition at line 34 of file PHG4MapsCellReco.h.
References chkenergyconservation.
int PHG4MapsCellReco::CheckEnergy (PHCompositeNode * topNode) protected
Definition at line 605 of file PHG4MapsCellReco.cc.
References cellnodename, PHG4HitContainer::getHits(), hitnodename, Fun4AllBase::Name(), and Fun4AllBase::verbosity.
Referenced by process_event().
double PHG4MapsCellReco::circle_rectangle_intersection (double x1, double y1, double x2, double y2, double mx, double my, double r) protected
Definition at line 795 of file PHG4MapsCellReco.cc.
References sA(), and Fun4AllBase::verbosity.
Referenced by process_event().
void PHG4MapsCellReco::Detector (const std::string & d) inline
Definition at line 33 of file PHG4MapsCellReco.h.
References detector.
int PHG4MapsCellReco::End (PHCompositeNode * topNode) virtual
end of process
Reimplemented from SubsysReco.
Definition at line 599 of file PHG4MapsCellReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
static double PHG4MapsCellReco::get_eta (const double radius, const double z) static protected
static std::pair<double, double> PHG4MapsCellReco::get_etaphi (const double x, const double y, const double z) static protected
double PHG4MapsCellReco::get_timing_window_max (const int i) inline
Definition at line 37 of file PHG4MapsCellReco.h.
References tmin_max.
double PHG4MapsCellReco::get_timing_window_min (const int i) inline
Definition at line 36 of file PHG4MapsCellReco.h.
References tmin_max.
int PHG4MapsCellReco::InitRun (PHCompositeNode * topNode) virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 48 of file PHG4MapsCellReco.cc.
References PHCompositeNode::addNode(), cellnodename, detector, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), geonodename, hitnodename, PHG4CylinderGeomContainer::identify(), PHWHERE, and Fun4AllBase::verbosity.
bool PHG4MapsCellReco::line_and_rectangle_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double * rr) protected
Definition at line 702 of file PHG4MapsCellReco.cc.
References lines_intersect().
bool PHG4MapsCellReco::lines_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double * rx, double * ry) protected
Definition at line 643 of file PHG4MapsCellReco.cc.
Referenced by line_and_rectangle_intersect().
int PHG4MapsCellReco::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 103 of file PHG4MapsCellReco.cc.
References _timer, PHG4Cell::add_edep(), PHG4Cell::add_eion(), PHG4CellContainer::AddCell(), celllist, cellnodename, CheckEnergy(), chkenergyconservation, circle_rectangle_intersection(), detector, Fun4AllReturnCodes::EVENT_OK, PHG4CellDefs::MapsBinning::genkey(), geonodename, PHTimeServer::timer::get(), PHG4Cell::get_edep(), PHG4CylinderGeom_MAPS::get_layer(), PHG4CylinderGeom_MAPS::get_local_coords_from_pixel(), PHG4CylinderGeom_MAPS::get_local_from_world_coords(), PHG4CylinderGeom_MAPS::get_NX(), PHG4CylinderGeom_MAPS::get_NZ(), PHG4CylinderGeom_MAPS::get_pixel_from_local_coords(), PHG4CylinderGeom_MAPS::get_pixel_number_from_xbin_zbin(), PHG4CylinderGeom_MAPS::get_pixel_x(), PHG4CylinderGeom_MAPS::get_pixel_X_from_pixel_number(), PHG4CylinderGeom_MAPS::get_pixel_z(), PHG4CylinderGeom_MAPS::get_pixel_Z_from_pixel_number(), PHG4CylinderGeom_MAPS::get_world_from_local_coords(), PHG4HitContainer::getHits(), PHG4CylinderGeomContainer::GetLayerGeom(), PHG4HitContainer::getLayers(), hitnodename, PHG4CylinderGeom_MAPS::identify(), Fun4AllBase::Name(), PHWHERE, PHG4Hit::prop_chip_index, PHG4Hit::prop_eion, PHG4Hit::prop_half_stave_index, PHG4Hit::prop_module_index, PHG4Hit::prop_stave_index, PHG4CellContainer::Reset(), PHTimer::restart(), PHG4Cell::set_chip_index(), PHG4Cell::set_half_stave_index(), PHG4Cell::set_module_index(), PHG4Cell::set_phibin(), PHG4Cell::set_pixel_index(), PHG4Cell::set_stave_index(), PHG4Cell::set_zbin(), PHTimer::stop(), tmin_max, and Fun4AllBase::verbosity.
double PHG4MapsCellReco::sA (double r, double x, double y) protected
Definition at line 820 of file PHG4MapsCellReco.cc.
Referenced by circle_rectangle_intersection().
void PHG4MapsCellReco::set_timing_window (const int detid, const double tmin, const double tmax)
Definition at line 867 of file PHG4MapsCellReco.cc.
References tmin_max, and Fun4AllBase::Verbosity().
void PHG4MapsCellReco::SetDefaultParameters () virtual
Implements PHG4ParameterContainerInterface.
Definition at line 877 of file PHG4MapsCellReco.cc.
References tmin_max.
Referenced by PHG4MapsCellReco().
Member Data Documentation
PHTimeServer::timer PHG4MapsCellReco::_timer protected
Definition at line 85 of file PHG4MapsCellReco.h.
Referenced by process_event().
std::map<int, int> PHG4MapsCellReco::binning protected
Definition at line 76 of file PHG4MapsCellReco.h.
std::map<int, std::pair <double,int> > PHG4MapsCellReco::cell_size protected
Definition at line 77 of file PHG4MapsCellReco.h.
std::map<unsigned long long, PHG4Cell*> PHG4MapsCellReco::celllist protected
Definition at line 89 of file PHG4MapsCellReco.h.
Referenced by process_event().
std::string PHG4MapsCellReco::cellnodename protected
Definition at line 82 of file PHG4MapsCellReco.h.
Referenced by CheckEnergy(), InitRun(), and process_event().
int PHG4MapsCellReco::chkenergyconservation protected
Definition at line 87 of file PHG4MapsCellReco.h.
Referenced by checkenergy(), and process_event().
std::string PHG4MapsCellReco::detector protected
Definition at line 80 of file PHG4MapsCellReco.h.
Referenced by Detector(), InitRun(), and process_event().
std::map<int, double> PHG4MapsCellReco::etastep protected
Definition at line 79 of file PHG4MapsCellReco.h.
std::string PHG4MapsCellReco::geonodename protected
Definition at line 83 of file PHG4MapsCellReco.h.
Referenced by InitRun(), and process_event().
std::string PHG4MapsCellReco::hitnodename protected
Definition at line 81 of file PHG4MapsCellReco.h.
Referenced by CheckEnergy(), InitRun(), and process_event().
int PHG4MapsCellReco::nbins[2] protected
Definition at line 86 of file PHG4MapsCellReco.h.
Referenced by PHG4MapsCellReco().
std::string PHG4MapsCellReco::seggeonodename protected
Definition at line 84 of file PHG4MapsCellReco.h.
std::map<int, std::pair<double,double> > PHG4MapsCellReco::tmin_max protected
Definition at line 88 of file PHG4MapsCellReco.h.
Referenced by get_timing_window_max(), get_timing_window_min(), process_event(), set_timing_window(), and SetDefaultParameters().
std::map<int, std::pair <double,double> > PHG4MapsCellReco::zmin_max protected
Definition at line 78 of file PHG4MapsCellReco.h.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4MapsCellReco.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4MapsCellReco.cc