SeaQuest Offline Software: convertRTCurve Namespace Reference
convertRTCurve Namespace Reference
Variables
list sourceDir = sys.argv[1]
list rt_inputFiles = ['rt_curve_D0.txt', 'rt_curve_D1.txt', 'rt_curve_D2.txt', 'rt_curve_D3p.txt', 'rt_curve_D3m.txt']
list t0_inputFiles = ['time_window_D0.txt', 'time_window_D1.txt', 'time_window_D2.txt', 'time_window_D3p.txt', 'time_window_D3m.txt']
dictionary map_detectorID
dictionary map_detectorName = {}
dictionary t0 = {}
tuple fin = open(sourceDir+'/'+t0_input, 'r')
tuple data = line.strip()
dictionary rt_curve = {}
list detectorID = map_detectorID[data[0]]
tuple fout = open(sys.argv[2], 'w')
tuple rt_sorted = sorted(rt_curve[detectorID].iteritems(), key = lambda d: d[0])
Variable Documentation
tuple convertRTCurve.data = line.strip()
Definition at line 25 of file convertRTCurve.py.
Referenced by PHDataNodeIterator.AddIODataNode(), PHTypedNodeIterator< T >.insert(), PHDataNode< T >.PHDataNode(), PHIODataNode< T >.write(), PHNodeIOManager.write(), and PHDataNode< T >.~PHDataNode().
list convertRTCurve.detectorID = map_detectorID[data[0]]
Definition at line 36 of file convertRTCurve.py.
tuple convertRTCurve.fin = open(sourceDir+'/'+t0_input, 'r')
Definition at line 23 of file convertRTCurve.py.
Referenced by JobOptsSvc.init(), and TriggerAnalyzer.init().
tuple convertRTCurve.fout = open(sys.argv[2], 'w')
Definition at line 44 of file convertRTCurve.py.
dictionary convertRTCurve.map_detectorID
Initial value:
 = {'D0U': 1, 'D0Up': 2, 'D0X': 3, 'D0Xp': 4, 'D0V': 5, 'D0Vp': 6,
                    'D1V': 7, 'D1Vp': 8, 'D1X': 9, 'D1Xp': 10, 'D1U': 11, 'D1Up': 12,
                    'D2V': 13, 'D2Vp': 14, 'D2Xp': 15, 'D2X': 16, 'D2U': 17, 'D2Up': 18,
                    'D3pVp': 19, 'D3pV': 20, 'D3pXp': 21, 'D3pX': 22, 'D3pUp': 23, 'D3pU': 24,
                    'D3mVp': 25, 'D3mV': 26, 'D3mXp': 27, 'D3mX': 28, 'D3mUp': 29, 'D3mU': 30}
Definition at line 11 of file convertRTCurve.py.
dictionary convertRTCurve.map_detectorName = {}
Definition at line 16 of file convertRTCurve.py.
dictionary convertRTCurve.rt_curve = {}
Definition at line 30 of file convertRTCurve.py.
list convertRTCurve.rt_inputFiles = ['rt_curve_D0.txt', 'rt_curve_D1.txt', 'rt_curve_D2.txt', 'rt_curve_D3p.txt', 'rt_curve_D3m.txt']
Definition at line 8 of file convertRTCurve.py.
tuple convertRTCurve.rt_sorted = sorted(rt_curve[detectorID].iteritems(), key = lambda d: d[0])
Definition at line 46 of file convertRTCurve.py.
list convertRTCurve.sourceDir = sys.argv[1]
Definition at line 7 of file convertRTCurve.py.
dictionary convertRTCurve.t0 = {}
Definition at line 21 of file convertRTCurve.py.
Referenced by AnaFit.CalcChi2(), AnaFit.CreateSpline(), and AnaFit.InitInput().
list convertRTCurve.t0_inputFiles = ['time_window_D0.txt', 'time_window_D1.txt', 'time_window_D2.txt', 'time_window_D3p.txt', 'time_window_D3m.txt']
Definition at line 9 of file convertRTCurve.py.