Class Reference for E1039 Core & Analysis Software: DrawRoadset Class Reference
DrawRoadset Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/DrawRoadset.h>
Public Member Functions
DrawRoadset (const std::string rs_id)
virtual ~DrawRoadset ()
void SetMaxCount (const double cnt_max)
RoadMap * GetRoadMapPosTop ()
RoadMap * GetRoadMapPosBot ()
RoadMap * GetRoadMapNegTop ()
RoadMap * GetRoadMapNegBot ()
void Draw ()
Public Member Functions inherited from AnaBase
virtual ~AnaBase ()
virtual void SetInputTreeName (const std::string name)
virtual void SetInputBranchName (const std::string name)
virtual void Init ()
virtual void Analyze ()
virtual void End ()
virtual void ReadEventsFromFileList (const char *fn_list, const int n_max=0)
virtual void ReadEvents (const char *fname)
Protected Types
typedef std::pair< int, int > PlaneConn_t
typedef std::map< PlaneConn_t,
int > PlaneConnCount_t
Protected Member Functions
void DrawOneSet (RoadMap *map)
void DrawConnection (const PlaneConnCount_t *list_cnt, const int plane, const int count_max)
void DrawElement (const int st, const int n_ele, const double y_label)
void DrawElementV1 (const int st, const int ele1, const int ele2)
Protected Member Functions inherited from AnaBase
AnaBase (const std::string label)
virtual void ProcessOneEvent ()
Protected Attributes
std::string m_rs_id
double m_cnt_max
RoadMap m_road_map_pos_top
RoadMap m_road_map_pos_bot
RoadMap m_road_map_neg_top
RoadMap m_road_map_neg_bot
Protected Attributes inherited from AnaBase
std::string m_label
std::string m_tree_name
std::string m_branch_name
std::string m_dir_out
std::ofstream m_ofs
Detailed Description
Definition at line 7 of file DrawRoadset.h.
Member Typedef Documentation
typedef std::pair<int, int> DrawRoadset::PlaneConn_t protected
Definition at line 9 of file DrawRoadset.h.
typedef std::map<PlaneConn_t, int> DrawRoadset::PlaneConnCount_t protected
Definition at line 10 of file DrawRoadset.h.
Constructor & Destructor Documentation
DrawRoadset::DrawRoadset (const std::string rs_id)
Definition at line 17 of file DrawRoadset.cc.
References m_road_map_neg_bot, m_road_map_neg_top, m_road_map_pos_bot, m_road_map_pos_top, and RoadListBase::SetPNTB().
DrawRoadset::~DrawRoadset () virtual
Definition at line 28 of file DrawRoadset.cc.
Member Function Documentation
void DrawRoadset::Draw ()
Definition at line 33 of file DrawRoadset.cc.
References DrawOneSet(), m_road_map_neg_bot, m_road_map_neg_top, m_road_map_pos_bot, and m_road_map_pos_top.
Referenced by DrawRS().
void DrawRoadset::DrawConnection (const PlaneConnCount_t * list_cnt, const int plane, const int count_max) protected
Definition at line 109 of file DrawRoadset.cc.
Referenced by DrawOneSet().
void DrawRoadset::DrawElement (const int st, const int n_ele, const double y_label) protected
Definition at line 127 of file DrawRoadset.cc.
Referenced by DrawOneSet().
void DrawRoadset::DrawElementV1 (const int st, const int ele1, const int ele2) protected
Definition at line 149 of file DrawRoadset.cc.
void DrawRoadset::DrawOneSet (RoadMap * map) protected
Definition at line 41 of file DrawRoadset.cc.
References RoadMap::Begin(), c1, DrawConnection(), DrawElement(), RoadMap::End(), RoadListBase::GetPosNegStr(), RoadListBase::GetTopBotStr(), m_cnt_max, AnaBase::m_dir_out, m_rs_id, and UtilTrigger::Road2Hodo().
Referenced by Draw().
RoadMap* DrawRoadset::GetRoadMapNegBot () inline
Definition at line 28 of file DrawRoadset.h.
References m_road_map_neg_bot.
Referenced by DrawRS().
RoadMap* DrawRoadset::GetRoadMapNegTop () inline
Definition at line 27 of file DrawRoadset.h.
References m_road_map_neg_top.
Referenced by DrawRS().
RoadMap* DrawRoadset::GetRoadMapPosBot () inline
Definition at line 26 of file DrawRoadset.h.
References m_road_map_pos_bot.
Referenced by DrawRS().
RoadMap* DrawRoadset::GetRoadMapPosTop () inline
Definition at line 25 of file DrawRoadset.h.
References m_road_map_pos_top.
Referenced by DrawRS().
void DrawRoadset::SetMaxCount (const double cnt_max) inline
Definition at line 23 of file DrawRoadset.h.
References m_cnt_max.
Member Data Documentation
double DrawRoadset::m_cnt_max protected
Definition at line 13 of file DrawRoadset.h.
Referenced by DrawOneSet(), and SetMaxCount().
RoadMap DrawRoadset::m_road_map_neg_bot protected
Definition at line 17 of file DrawRoadset.h.
Referenced by Draw(), DrawRoadset(), and GetRoadMapNegBot().
RoadMap DrawRoadset::m_road_map_neg_top protected
Definition at line 16 of file DrawRoadset.h.
Referenced by Draw(), DrawRoadset(), and GetRoadMapNegTop().
RoadMap DrawRoadset::m_road_map_pos_bot protected
Definition at line 15 of file DrawRoadset.h.
Referenced by Draw(), DrawRoadset(), and GetRoadMapPosBot().
RoadMap DrawRoadset::m_road_map_pos_top protected
Definition at line 14 of file DrawRoadset.h.
Referenced by Draw(), DrawRoadset(), and GetRoadMapPosTop().
std::string DrawRoadset::m_rs_id protected
Definition at line 12 of file DrawRoadset.h.
Referenced by DrawOneSet().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/DrawRoadset.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/DrawRoadset.cc