Class Reference for E1039 Core & Analysis Software: PHG4CylinderCellv2 Class Reference
PHG4CylinderCellv2 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellv2.h>
Public Member Functions
PHG4CylinderCellv2 ()
virtual ~PHG4CylinderCellv2 ()
void identify (std::ostream &os=std::cout) const
void set_sensor_index (const std::string &si)
std::string get_sensor_index () const
void set_ladder_phi_index (const int i)
int get_ladder_phi_index () const
void set_ladder_z_index (const int i)
int get_ladder_z_index () const
Public Member Functions inherited from PHG4CylinderCellv1
PHG4CylinderCellv1 ()
virtual ~PHG4CylinderCellv1 ()
EdepConstRange get_g4hits ()
void add_edep (const PHG4HitDefs::keytype g4hitid, const float edep)
void add_edep (const PHG4HitDefs::keytype g4hitid, const float edep, const float light_yield)
ShowerEdepConstRange get_g4showers ()
void add_shower_edep (const int g4showerid, const float edep)
void set_cell_id (const PHG4CylinderCellDefs::keytype id)
void set_layer (const unsigned int i)
double get_edep () const
unsigned int get_layer () const
PHG4CylinderCellDefs::keytype get_cell_id () const
int get_binz () const
int get_binphi () const
int get_bineta () const
float get_light_yield () const
void set_zbin (const int i)
void set_etabin (const int i)
void set_phibin (const int i)
void set_light_yield (const float lightYield)
Public Member Functions inherited from PHG4CylinderCell
virtual ~PHG4CylinderCell ()
virtual int get_fiber_ID () const
virtual void set_fiber_ID (int fiberId)
virtual int get_j_index () const
virtual void set_j_index (const int i)
virtual int get_k_index () const
virtual void set_k_index (const int i)
virtual int get_l_index () const
virtual void set_l_index (const int i)
virtual int get_pixel_index () const
virtual int get_chip_index () const
virtual int get_module_index () const
virtual int get_half_stave_index () const
virtual int get_stave_index () const
virtual void set_stave_index (const int si)
virtual void set_half_stave_index (const int i)
virtual void set_module_index (const int i)
virtual void set_chip_index (const int i)
virtual void set_pixel_index (const int i)
Public Member Functions inherited from PHG4Cell
virtual ~PHG4Cell ()
virtual void Copy (PHG4Cell const &g4cell)
virtual void Reset ()
virtual void set_cellid (const PHG4CellDefs::keytype i)
virtual PHG4CellDefs::keytype get_cellid () const
virtual bool has_binning (const PHG4CellDefs::CellBinning) const
virtual void add_edep (const PHG4HitDefs::keytype g4hitid, const int tbin, const float edep)
virtual short int get_detid () const
short int get_layer () const
virtual void add_edep (const float f)
virtual void add_eion (const float f)
virtual double get_eion () const
virtual void add_light_yield (const float lightYield)
virtual int get_phibin () const
virtual int get_zbin () const
virtual void print () const
virtual bool has_property (const PROPERTY prop_id) const
virtual float get_property_float (const PROPERTY prop_id) const
virtual int get_property_int (const PROPERTY prop_id) const
virtual unsigned int get_property_uint (const PROPERTY prop_id) const
virtual void set_property (const PROPERTY prop_id, const float value)
virtual void set_property (const PROPERTY prop_id, const int value)
virtual void set_property (const PROPERTY prop_id, const unsigned int value)
Protected Attributes
int ladder_phi_index
int ladder_z_index
std::string sensor_index
Protected Attributes inherited from PHG4CylinderCellv1
unsigned int layer
PHG4CylinderCellDefs::keytype cellid
int binz
int binphi
EdepMap edeps
ShowerEdepMap showeredeps
float light_yield
Additional Inherited Members
Public Types inherited from PHG4CylinderCell
typedef std::map< PHG4HitDefs::keytype, float > EdepMap
typedef EdepMap::iterator EdepIterator
typedef EdepMap::const_iterator EdepConstIterator
typedef std::pair< EdepIterator, EdepIterator > EdepRange
typedef std::pair< EdepConstIterator, EdepConstIterator > EdepConstRange
typedef std::map< int, float > ShowerEdepMap
typedef ShowerEdepMap::iterator ShowerEdepIterator
typedef ShowerEdepMap::const_iterator ShowerEdepConstIterator
typedef std::pair< ShowerEdepIterator, ShowerEdepIterator > ShowerEdepRange
typedef std::pair< ShowerEdepConstIterator, ShowerEdepConstIterator > ShowerEdepConstRange
Public Types inherited from PHG4Cell
enum PROPERTY {
prop_stave_index = 1 , prop_half_stave_index = 2 , prop_module_index = 3 , prop_chip_index = 4 ,
prop_pixel_index = 5 , prop_phibin = 6 , prop_zbin = 7 , prop_ladder_z_index = 8 ,
prop_ladder_phi_index = 9 , prop_edep = 21 , prop_eion = 22 , prop_light_yield = 23 ,
prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1 , type_uint = 2 , type_float = 3 , type_unknown = -1 }
typedef std::map< PHG4HitDefs::keytype, float > EdepMap
typedef EdepMap::iterator EdepIterator
typedef EdepMap::const_iterator EdepConstIterator
typedef std::pair< EdepIterator, EdepIterator > EdepRange
typedef std::pair< EdepConstIterator, EdepConstIterator > EdepConstRange
typedef std::map< int, float > ShowerEdepMap
typedef ShowerEdepMap::iterator ShowerEdepIterator
typedef ShowerEdepMap::const_iterator ShowerEdepConstIterator
typedef std::pair< ShowerEdepIterator, ShowerEdepIterator > ShowerEdepRange
typedef std::pair< ShowerEdepConstIterator, ShowerEdepConstIterator > ShowerEdepConstRange
typedef std::pair< unsigned short, std::map< int, int > > tpccompress
typedef std::map< unsigned short, tpccompress > tpctod
Static Public Member Functions inherited from PHG4Cell
static std::pair< const std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Member Functions inherited from PHG4CylinderCell
PHG4CylinderCell ()
Protected Member Functions inherited from PHG4Cell
PHG4Cell ()
virtual unsigned int get_property_nocheck (const PROPERTY prop_id) const
virtual void set_property_nocheck (const PROPERTY prop_id, const unsigned int)
Detailed Description
Definition at line 9 of file PHG4CylinderCellv2.h.
Constructor & Destructor Documentation
PHG4CylinderCellv2()
PHG4CylinderCellv2::PHG4CylinderCellv2 ()
Definition at line 5 of file PHG4CylinderCellv2.cc.
~PHG4CylinderCellv2()
virtual PHG4CylinderCellv2::~PHG4CylinderCellv2 () inline virtual
Definition at line 14 of file PHG4CylinderCellv2.h.
Member Function Documentation
get_ladder_phi_index()
int PHG4CylinderCellv2::get_ladder_phi_index () const inline virtual
Reimplemented from PHG4CylinderCell.
Definition at line 22 of file PHG4CylinderCellv2.h.
References ladder_phi_index.
Referenced by identify().
get_ladder_z_index()
int PHG4CylinderCellv2::get_ladder_z_index () const inline virtual
Reimplemented from PHG4CylinderCell.
Definition at line 25 of file PHG4CylinderCellv2.h.
References ladder_z_index.
Referenced by identify().
get_sensor_index()
std::string PHG4CylinderCellv2::get_sensor_index () const inline virtual
Reimplemented from PHG4CylinderCell.
Definition at line 19 of file PHG4CylinderCellv2.h.
References sensor_index.
Referenced by identify().
identify()
void PHG4CylinderCellv2::identify (std::ostream & os = std::cout) const virtual
Reimplemented from PHG4CylinderCellv1.
Definition at line 13 of file PHG4CylinderCellv2.cc.
References PHG4CylinderCellv1::binphi, PHG4CylinderCellv1::binz, PHG4CylinderCellv1::cellid, PHG4CylinderCellv1::get_edep(), get_ladder_phi_index(), get_ladder_z_index(), get_sensor_index(), and PHG4CylinderCellv1::layer.
set_ladder_phi_index()
void PHG4CylinderCellv2::set_ladder_phi_index (const int i) inline virtual
Reimplemented from PHG4CylinderCell.
Definition at line 21 of file PHG4CylinderCellv2.h.
References ladder_phi_index.
set_ladder_z_index()
void PHG4CylinderCellv2::set_ladder_z_index (const int i) inline virtual
Reimplemented from PHG4CylinderCell.
Definition at line 24 of file PHG4CylinderCellv2.h.
References ladder_z_index.
set_sensor_index()
void PHG4CylinderCellv2::set_sensor_index (const std::string & si) inline virtual
Reimplemented from PHG4CylinderCell.
Definition at line 18 of file PHG4CylinderCellv2.h.
References sensor_index.
Member Data Documentation
ladder_phi_index
int PHG4CylinderCellv2::ladder_phi_index protected
Definition at line 29 of file PHG4CylinderCellv2.h.
Referenced by get_ladder_phi_index(), and set_ladder_phi_index().
ladder_z_index
int PHG4CylinderCellv2::ladder_z_index protected
Definition at line 30 of file PHG4CylinderCellv2.h.
Referenced by get_ladder_z_index(), and set_ladder_z_index().
sensor_index
std::string PHG4CylinderCellv2::sensor_index protected
Definition at line 31 of file PHG4CylinderCellv2.h.
Referenced by get_sensor_index(), and set_sensor_index().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellv2.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellv2.cc