Class Reference for E1039 Core & Analysis Software: PHG4GenHit Class Reference
PHG4GenHit Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4GenHit.h>
Public Member Functions
PHG4GenHit (const std::string &name="PHG4GenHit")
virtual ~PHG4GenHit ()
int process_event (PHCompositeNode *topNode)
void set_phi (const double d)
void set_theta (const double d)
void set_eloss (const double d)
void set_layer (const int i)
void Detector (const std::string &n)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
double phi
double theta
double eloss
int layer
std::string detector
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
Definition at line 6 of file PHG4GenHit.h.
Constructor & Destructor Documentation
PHG4GenHit()
PHG4GenHit::PHG4GenHit (const std::string & name = "PHG4GenHit")
Definition at line 16 of file PHG4GenHit.cc.
~PHG4GenHit()
virtual PHG4GenHit::~PHG4GenHit () inline virtual
Definition at line 10 of file PHG4GenHit.h.
Member Function Documentation
Detector()
void PHG4GenHit::Detector (const std::string & n) inline
Definition at line 18 of file PHG4GenHit.h.
References detector.
process_event()
int PHG4GenHit::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 25 of file PHG4GenHit.cc.
References PHG4HitContainer::AddHit(), detector, eloss, Fun4AllReturnCodes::EVENT_OK, PHG4CylinderGeom::get_radius(), PHG4CylinderGeom::get_thickness(), PHG4CylinderGeomContainer::GetLayerGeom(), layer, phi, PHG4Hit::set_edep(), PHG4Hit::set_layer(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), theta, and Fun4AllBase::verbosity.
set_eloss()
void PHG4GenHit::set_eloss (const double d) inline
Definition at line 16 of file PHG4GenHit.h.
References eloss.
set_layer()
void PHG4GenHit::set_layer (const int i) inline
Definition at line 17 of file PHG4GenHit.h.
References layer.
set_phi()
void PHG4GenHit::set_phi (const double d) inline
Definition at line 14 of file PHG4GenHit.h.
References phi.
set_theta()
void PHG4GenHit::set_theta (const double d) inline
Definition at line 15 of file PHG4GenHit.h.
References theta.
Member Data Documentation
detector
std::string PHG4GenHit::detector protected
Definition at line 25 of file PHG4GenHit.h.
Referenced by Detector(), and process_event().
eloss
double PHG4GenHit::eloss protected
Definition at line 23 of file PHG4GenHit.h.
Referenced by process_event(), and set_eloss().
layer
int PHG4GenHit::layer protected
Definition at line 24 of file PHG4GenHit.h.
Referenced by process_event(), and set_layer().
phi
double PHG4GenHit::phi protected
Definition at line 21 of file PHG4GenHit.h.
Referenced by process_event(), and set_phi().
theta
double PHG4GenHit::theta protected
Definition at line 22 of file PHG4GenHit.h.
Referenced by process_event(), and set_theta().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4GenHit.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4GenHit.cc