SeaQuest Offline Software: /home/yuhw/GitHub/SeaQuest/seaquest-ktracker/analysis_tools/eventMixer.cxx File Reference
eventMixer.cxx File Reference
#include <iostream>
#include <fstream>
#include <sstream>
#include <cmath>
#include <algorithm>
#include <string>
#include <set>
#include <utility>
#include <map>
#include <TROOT.h>
#include <TFile.h>
#include <TTree.h>
#include <TRandom.h>
#include <TMatrixD.h>
#include <TLorentzVector.h>
#include <TClonesArray.h>
#include <TMath.h>
#include <TRandom3.h>
#include <TChain.h>
#include "GeomSvc.h"
#include "SRawEvent.h"
#include "TriggerRoad.h"
#include "TriggerAnalyzer.h"
#include "EventReducer.h"
#include "JobOptsSvc.h"
#include "dst/DataStruct.h"
Typedefs
typedef pair< int, int > eventPair
Functions
void generateEventIDPairs (int nSig, int nBkg, vector< eventPair > &eventIDs)
int main (int argc, char *argv[])
Typedef Documentation
typedef pair<int, int> eventPair
Definition at line 32 of file eventMixer.cxx.
Function Documentation
void generateEventIDPairs (int nSig, int nBkg, vector< eventPair > & eventIDs)
Definition at line 34 of file eventMixer.cxx.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 65 of file eventMixer.cxx.
References TriggerAnalyzer::acceptEvent(), TriggerAnalyzer::buildTriggerTree(), SRawEvent::clear(), generateEventIDPairs(), SRawEvent::getEventID(), SRawEvent::getIntensity(), TriggerAnalyzer::getNRoadsNegBot(), TriggerAnalyzer::getNRoadsNegTop(), TriggerAnalyzer::getNRoadsPosBot(), TriggerAnalyzer::getNRoadsPosTop(), SRawEvent::getRunID(), SRawEvent::getSpillID(), JobOptsSvc::init(), TriggerAnalyzer::init(), GeomSvc::init(), JobOptsSvc::instance(), GeomSvc::instance(), eventMixer::mcFile, SRawEvent::mergeEvent(), p_geomSvc, EventReducer::reduceEvent(), EventReducer::setChamEff(), SRawEvent::setEventInfo(), SRawEvent::setNRoads(), SRawEvent::setTriggerEmu(), and USE_TRIGGER_HIT.