Class Reference for E1039 Core & Analysis Software: UtilRoad Namespace Reference
UtilRoad Namespace Reference
Functions
void PrintList (RoadList *road_list, int i_begin=0, int i_end=0, std::ostream &os=std::cout)
void WriteToFile (const RoadMap *pos_top, const RoadMap *pos_bot, const RoadMap *neg_top, const RoadMap *neg_bot, const std::string id)
void ReadFromFile (RoadMap *pos_top, RoadMap *pos_bot, RoadMap *neg_top, RoadMap *neg_bot, const std::string id)
Function Documentation
PrintList()
void UtilRoad::PrintList (RoadList * road_list, int i_begin = 0, int i_end = 0, std::ostream & os = std::cout)
Definition at line 25 of file UtilRoad.cc.
References RoadList::Get(), RoadInfo::GetCount(), RoadInfo::GetCountBG(), RoadInfo::GetFoM(), RoadInfo::GetRoadID(), RoadInfo::GetWeight(), RoadInfo::GetWeightBG(), and RoadList::Size().
Referenced by ReAnaBG::Analyze(), GenRoadset::DisableRoadsByFoM(), GenRoadset::DisableRoadsByWeightFraction(), and GenRoadset::GenerateSymmetricRoadSetByFoM().
ReadFromFile()
void UtilRoad::ReadFromFile (RoadMap * pos_top, RoadMap * pos_bot, RoadMap * neg_top, RoadMap * neg_bot, const std::string id)
Definition at line 74 of file UtilRoad.cc.
References RoadMap::Add(), and RoadMap::Size().
WriteToFile()
void UtilRoad::WriteToFile (const RoadMap * pos_top, const RoadMap * pos_bot, const RoadMap * neg_top, const RoadMap * neg_bot, const std::string id)
Definition at line 53 of file UtilRoad.cc.
References RoadMap::End(), RoadInfo::GetCount(), RoadInfo::GetOnOff(), RoadInfo::GetRoadID(), and RoadInfo::GetWeight().
Referenced by GenRoadset::GenerateRoadSetByFoM(), GenRoadset::GenerateRoadSetBySignal(), and GenRoadset::GenerateSymmetricRoadSetByFoM().