Class Reference for E1039 Core & Analysis Software: DecoStatusDb Class Reference
DecoStatusDb Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/DecoStatusDb.h>
Public Member Functions
DecoStatusDb ()
virtual ~DecoStatusDb ()
void InitTable (const bool refresh=false)
void RunStarted (const int run, int utime=0)
void RunUpdated (const int run, int utime=0)
void RunFinished (const int run, const int result, int utime=0)
Detailed Description
Definition at line 5 of file DecoStatusDb.h.
Constructor & Destructor Documentation
DecoStatusDb()
DecoStatusDb::DecoStatusDb ()
Definition at line 8 of file DecoStatusDb.cc.
References DbSvc::DB1, UtilOnline::GetSchemaMainDaq(), and DbSvc::UseSchema().
~DecoStatusDb()
DecoStatusDb::~DecoStatusDb () virtual
Definition at line 20 of file DecoStatusDb.cc.
Member Function Documentation
InitTable()
void DecoStatusDb::InitTable (const bool refresh = false)
Definition at line 25 of file DecoStatusDb.cc.
References DbSvc::VarList::Add(), DbSvc::CreateTable(), DbSvc::DropTable(), and DbSvc::HasTable().
Referenced by RunStarted().
RunFinished()
void DecoStatusDb::RunFinished (const int run, const int result, int utime = 0)
Definition at line 80 of file DecoStatusDb.cc.
References DbSvc::Con().
RunStarted()
void DecoStatusDb::RunStarted (const int run, int utime = 0)
Definition at line 49 of file DecoStatusDb.cc.
References DbSvc::Con(), and InitTable().
RunUpdated()
void DecoStatusDb::RunUpdated (const int run, int utime = 0)
Definition at line 68 of file DecoStatusDb.cc.
References DbSvc::Con().
Referenced by DbUpRun::process_event().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/DecoStatusDb.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/DecoStatusDb.cc