Class Reference for E1039 Core & Analysis Software: Fun4AllVectEventOutputManager Class Reference
Fun4AllVectEventOutputManager Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Fun4AllVectFileManager/Fun4AllVectFileManager/src/Fun4AllVectEventOutputManager.h>
Public Member Functions
Fun4AllVectEventOutputManager (const std::string &myname="UNIVERSALOUT")
virtual ~Fun4AllVectEventOutputManager ()
void SetTreeName (const std::string &name)
void SetFileName (const std::string &name)
virtual int Write (PHCompositeNode *startNode)
write starting from given node
void ResetBranches ()
Public Member Functions inherited from Fun4AllOutputManager
virtual ~Fun4AllOutputManager ()
destructor
virtual void Print (const std::string &what="ALL") const
print method (dump event selector)
virtual int AddNode (const std::string &)
add a node in outputmanager
virtual int StripNode (const std::string &)
not write a node in outputmanager
virtual int AddEventSelector (const std::string &recomodule)
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
virtual int outfileopen (const std::string &)
opens output file
virtual int RemoveNode (const std::string &)
removes a node from outputmanager
int WriteGeneric (PHCompositeNode *startNode)
Common method, called before calling virtual Write.
virtual int WriteNode (PHCompositeNode *)
write specified node
virtual std::vector< std::string > * EventSelector ()
retrieves pointer to vector of event selector module names
virtual std::vector< unsigned > * RecoModuleIndex ()
retrieves pointer to vector of event selector module ids
virtual int DoNotWriteEvent (std::vector< int > *retcodes) const
decides if event is to be written or not
virtual size_t EventsWritten () const
get number of Events
virtual std::string OutFileName () const
get output file name
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int OpenFile (PHCompositeNode *startNode)
void CloseFile ()
Protected Member Functions inherited from Fun4AllOutputManager
Fun4AllOutputManager (const std::string &myname)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from Fun4AllOutputManager
size_t nEvents
Number of Events.
std::vector< std::string > EventSelectors
vector of event selectors modules
std::vector< unsigned > recomoduleindex
vector of associated module indexes
std::string outfilename
output file name
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 18 of file Fun4AllVectEventOutputManager.h.
Constructor & Destructor Documentation
Fun4AllVectEventOutputManager()
Fun4AllVectEventOutputManager::Fun4AllVectEventOutputManager (const std::string & myname = "UNIVERSALOUT")
Definition at line 21 of file Fun4AllVectEventOutputManager.cc.
~Fun4AllVectEventOutputManager()
Fun4AllVectEventOutputManager::~Fun4AllVectEventOutputManager () virtual
Definition at line 34 of file Fun4AllVectEventOutputManager.cc.
References CloseFile().
Member Function Documentation
CloseFile()
void Fun4AllVectEventOutputManager::CloseFile () protected
Definition at line 142 of file Fun4AllVectEventOutputManager.cc.
Referenced by ~Fun4AllVectEventOutputManager().
OpenFile()
int Fun4AllVectEventOutputManager::OpenFile (PHCompositeNode * startNode) protected
Definition at line 38 of file Fun4AllVectEventOutputManager.cc.
References Fun4AllReturnCodes::ABORTEVENT, and Fun4AllReturnCodes::EVENT_OK.
Referenced by Write().
ResetBranches()
void Fun4AllVectEventOutputManager::ResetBranches ()
Definition at line 151 of file Fun4AllVectEventOutputManager.cc.
Referenced by Write().
SetFileName()
void Fun4AllVectEventOutputManager::SetFileName (const std::string & name) inline
Definition at line 24 of file Fun4AllVectEventOutputManager.h.
SetTreeName()
void Fun4AllVectEventOutputManager::SetTreeName (const std::string & name) inline
Definition at line 23 of file Fun4AllVectEventOutputManager.h.
Write()
int Fun4AllVectEventOutputManager::Write (PHCompositeNode *) virtual
write starting from given node
Reimplemented from Fun4AllOutputManager.
Definition at line 86 of file Fun4AllVectEventOutputManager.cc.
References SQHitVector::at(), SQHit::get_detector_id(), SQHit::get_drift_distance(), SQHit::get_element_id(), SQEvent::get_event_id(), SQEvent::get_qie_rf_id(), SQEvent::get_qie_rf_intensity(), SQEvent::get_qie_turn_id(), SQEvent::get_run_id(), SQEvent::get_spill_id(), SQHit::get_tdc_time(), SQEvent::get_trigger(), SQHit::is_in_time(), SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, SQEvent::MATRIX5, SQEvent::NIM1, SQEvent::NIM2, SQEvent::NIM3, SQEvent::NIM4, SQEvent::NIM5, OpenFile(), ResetBranches(), and SQHitVector::size().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Fun4AllVectFileManager/Fun4AllVectFileManager/src/Fun4AllVectEventOutputManager.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Fun4AllVectFileManager/Fun4AllVectFileManager/src/Fun4AllVectEventOutputManager.cc