E1039 Software: /home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4Hit.cc File Reference
PHG4Hit.cc File Reference
#include "PHG4Hit.h"
#include <cstdlib>
Functions
ClassImp (PHG4Hit) void PHG4Hit
ostream & operator<< (ostream &stream, const PHG4Hit *hit)
Function Documentation
ClassImp()
ClassImp (PHG4Hit)
Definition at line 7 of file PHG4Hit.cc.
References PHG4Hit::get_edep(), PHG4Hit::get_hit_id(), PHG4Hit::get_hit_type(), PHG4Hit::get_property_nocheck(), PHG4Hit::get_t(), PHG4Hit::get_trkid(), PHG4Hit::get_x(), PHG4Hit::get_y(), PHG4Hit::get_z(), and PHG4Hit::has_property().
operator<<()
ostream& operator<< (std::ostream & stream, const PHG4Hit * hit)
Definition at line 56 of file PHG4Hit.cc.
References PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), PHG4Hit::get_hit_id(), PHG4Hit::get_layer(), and PHG4Hit::get_trkid().