E1039 Software: ChanMapV1495 Class Reference
ChanMapV1495 Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/ChanMapV1495.h>
Classes
struct MapItem
Public Member Functions
ChanMapV1495 ()
virtual ~ChanMapV1495 ()
void Add (const short roc, const short board, const short chan, const std::string det, const short ele, const short lvl)
void Add (const short roc, const short board, const short chan, const std::string det_name, const short det_id, const short ele, const short lvl)
bool Find (const short roc, const short board, const short chan, short &det, short &ele, short &lvl)
void Print (std::ostream &os)
Public Member Functions inherited from ChanMapBase
ChanMapBase (const std::string label, const std::string header)
virtual ~ChanMapBase ()
Public Member Functions inherited from RunParamBase
RunParamBase (const std::string type, const std::string label, const std::string header)
virtual ~RunParamBase ()
void SetBaseDir (const std::string dir_base)
std::string GetBaseDir ()
std::string GetMapID ()
void SetMapID (const std::string map_id)
void SetMapIDbyFile (const std::string map_id)
void SetMapIDbyDB (const std::string map_id)
void SetMapIDbyFile (const int run)
void SetMapIDbyDB (const int run)
void ReadFromFile ()
void WriteToFile ()
void ReadFromLocalFile (const std::string fn_tsv)
void WriteToLocalFile (const std::string fn_tsv)
void ReadFromDB ()
void WriteToDB ()
void WriteRangeToDB ()
Protected Member Functions
int ReadFileCont (LineList &lines)
int WriteFileCont (std::ostream &os)
void ReadDbTable (DbSvc &db)
void WriteDbTable (DbSvc &db)
void InitNameMap ()
Protected Member Functions inherited from RunParamBase
std::string RangeFileName ()
std::string MapFileName ()
std::string SchemaName ()
std::string MapTableName ()
Private Types
typedef std::vector< MapItem > List_t
typedef std::tuple< short, short, short > DetEleLvl_t
typedef std::map< RocBoardChan_t, DetEleLvl_t > Map_t
Private Attributes
List_t m_list
Used to keep all information in the added order.
Map_t m_map
Used in Find() for better speed.
std::map< std::string, short > m_map_name2id
Additional Inherited Members
Protected Types inherited from ChanMapBase
typedef std::tuple< short, short, short > RocBoardChan_t
Protected Types inherited from RunParamBase
typedef std::vector< std::string > LineList
Detailed Description
Definition at line 5 of file ChanMapV1495.h.
Member Typedef Documentation
DetEleLvl_t
typedef std::tuple<short, short, short> ChanMapV1495::DetEleLvl_t private
Definition at line 18 of file ChanMapV1495.h.
List_t
typedef std::vector<MapItem> ChanMapV1495::List_t private
Definition at line 15 of file ChanMapV1495.h.
Map_t
typedef std::map<RocBoardChan_t, DetEleLvl_t> ChanMapV1495::Map_t private
Definition at line 19 of file ChanMapV1495.h.
Constructor & Destructor Documentation
ChanMapV1495()
ChanMapV1495::ChanMapV1495 ()
Definition at line 13 of file ChanMapV1495.cc.
References InitNameMap().
~ChanMapV1495()
virtual ChanMapV1495::~ChanMapV1495 () inline virtual
Definition at line 26 of file ChanMapV1495.h.
References Add(), ChanMapV1495::MapItem::board, ChanMapV1495::MapItem::chan, ChanMapV1495::MapItem::det, ChanMapV1495::MapItem::det_name, ChanMapV1495::MapItem::ele, Find(), InitNameMap(), ChanMapV1495::MapItem::lvl, Print(), ReadDbTable(), ReadFileCont(), ChanMapV1495::MapItem::roc, WriteDbTable(), and WriteFileCont().
Member Function Documentation
Add() [1/2]
void ChanMapV1495::Add (const short roc, const short board, const short chan, const std::string det, const short ele, const short lvl)
todo: The "STOP" and "L1PX*" detectors should be handled by GeomSvc properly.
Code to check the conversion
Definition at line 90 of file ChanMapV1495.cc.
References GeomSvc::getDetectorID(), GeomSvc::instance(), and GeomSvc::toLocalDetectorName().
Referenced by ReadDbTable(), ReadFileCont(), and ~ChanMapV1495().
Add() [2/2]
void ChanMapV1495::Add (const short roc, const short board, const short chan, const std::string det_name, const short det_id, const short ele, const short lvl)
Definition at line 123 of file ChanMapV1495.cc.
References ChanMapV1495::MapItem::board, ChanMapV1495::MapItem::chan, ChanMapV1495::MapItem::det, ChanMapV1495::MapItem::det_name, ChanMapV1495::MapItem::ele, ChanMapV1495::MapItem::lvl, m_list, m_map, and ChanMapV1495::MapItem::roc.
Find()
bool ChanMapV1495::Find (const short roc, const short board, const short chan, short & det, short & ele, short & lvl)
Definition at line 154 of file ChanMapV1495.cc.
References m_map.
Referenced by ~ChanMapV1495().
InitNameMap()
void ChanMapV1495::InitNameMap () protected
Definition at line 187 of file ChanMapV1495.cc.
References m_map_name2id.
Referenced by ChanMapV1495(), and ~ChanMapV1495().
Print()
void ChanMapV1495::Print (std::ostream & os) virtual
Reimplemented from RunParamBase.
Definition at line 176 of file ChanMapV1495.cc.
References m_list.
Referenced by ~ChanMapV1495().
ReadDbTable()
void ChanMapV1495::ReadDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 46 of file ChanMapV1495.cc.
References Add(), RunParamBase::MapTableName(), and DbSvc::Process().
Referenced by ~ChanMapV1495().
ReadFileCont()
int ChanMapV1495::ReadFileCont (LineList & lines) protected virtual
Reimplemented from RunParamBase.
Definition at line 19 of file ChanMapV1495.cc.
References Add().
Referenced by ~ChanMapV1495().
WriteDbTable()
void ChanMapV1495::WriteDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 64 of file ChanMapV1495.cc.
References DbSvc::Con(), DbSvc::CreateTable(), m_list, and RunParamBase::MapTableName().
Referenced by ~ChanMapV1495().
WriteFileCont()
int ChanMapV1495::WriteFileCont (std::ostream & os) protected virtual
Reimplemented from RunParamBase.
Definition at line 35 of file ChanMapV1495.cc.
References m_list.
Referenced by ~ChanMapV1495().
Member Data Documentation
m_list
List_t ChanMapV1495::m_list private
Used to keep all information in the added order.
Definition at line 16 of file ChanMapV1495.h.
Referenced by Add(), Print(), WriteDbTable(), and WriteFileCont().
m_map
Map_t ChanMapV1495::m_map private
Used in Find() for better speed.
Definition at line 20 of file ChanMapV1495.h.
Referenced by Add(), and Find().
m_map_name2id
std::map<std::string, short> ChanMapV1495::m_map_name2id private
Definition at line 22 of file ChanMapV1495.h.
Referenced by InitNameMap().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/ChanMapV1495.h
/home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/ChanMapV1495.cc