Class Reference for E1039 Core & Analysis Software: SRecTrack Class Reference
SRecTrack Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/SRecEvent.h>
Public Member Functions
SRecTrack ()
void identify (std::ostream &os=std::cout) const
PHObject virtual overloads.
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SRecTrack * Clone () const
virtual int get_track_id () const
SQTrack virtual overloads.
virtual void set_track_id (const int a)
virtual int get_rec_track_id () const
Return the track ID of associated reconstructed track. Valid only if this object holds truth track info.
virtual void set_rec_track_id (const int a)
virtual int get_charge () const
Return the charge, i.e. +1 or -1.
virtual void set_charge (const int a)
virtual int get_num_hits () const
Return the number of hits associated to this track.
virtual void set_num_hits (const int a)
virtual TVector3 get_pos_vtx () const
Return the track position at vertex.
virtual void set_pos_vtx (const TVector3 a)
virtual TVector3 get_pos_st1 () const
Return the track position at Station 1.
virtual void set_pos_st1 (const TVector3 a)
virtual TVector3 get_pos_st3 () const
Return the track position at Station 3.
virtual void set_pos_st3 (const TVector3 a)
virtual TLorentzVector get_mom_vtx () const
Return the track momentum at vertex.
virtual void set_mom_vtx (const TLorentzVector a)
virtual TLorentzVector get_mom_st1 () const
Return the track momentum at Station 1.
virtual void set_mom_st1 (const TLorentzVector a)
virtual TLorentzVector get_mom_st3 () const
Return the track momentum at Station 3.
virtual void set_mom_st3 (const TLorentzVector a)
virtual double get_chisq () const
virtual double get_chisq_target () const
virtual double get_chisq_dump () const
virtual double get_chsiq_upstream () const
virtual double get_chisq_upstream () const
virtual TVector3 get_pos_target () const
virtual TVector3 get_pos_dump () const
virtual TLorentzVector get_mom_target () const
virtual TLorentzVector get_mom_dump () const
virtual int get_hit_id (const int i) const
TLorentzVector getlvec (const TVector3 &vec) const
Int_t getCharge () const
Gets.
Int_t getNHits () const
Int_t getNHitsInStation (Int_t stationID)
Double_t getChisq () const
Double_t getProb () const
Double_t getQuality () const
Int_t getHitIndex (Int_t i)
TMatrixD getStateVector (Int_t i)
TMatrixD getCovariance (Int_t i)
Double_t getZ (Int_t i)
Double_t getChisqAtNode (Int_t i)
TVector3 getGFPlaneO (Int_t i)
TVector3 getGFPlaneU (Int_t i)
TVector3 getGFPlaneV (Int_t i)
TVectorD getGFAuxInfo (Int_t i)
TVectorD getGFState (Int_t i)
TMatrixDSym getGFCov (Int_t i)
Int_t getNearestNode (Double_t z)
void getExpPositionFast (Double_t z, Double_t &x, Double_t &y, Int_t iNode=-1)
void getExpPosErrorFast (Double_t z, Double_t &dx, Double_t &dy, Int_t iNode=-1)
Double_t getExpMomentumFast (Double_t z, Double_t &px, Double_t &py, Double_t &pz, Int_t iNode=-1)
Double_t getExpMomentumFast (Double_t z, Int_t iNode=-1)
Double_t getMomentumSt1 (Double_t &px, Double_t &py, Double_t &pz) const
Double_t getMomentumSt1 () const
TVector3 getMomentumVecSt1 () const
Double_t getMomentumSt3 (Double_t &px, Double_t &py, Double_t &pz) const
Double_t getMomentumSt3 () const
TVector3 getMomentumVecSt3 () const
Double_t getPositionSt1 (Double_t &x, Double_t &y) const
Double_t getPositionSt1 () const
TVector3 getPositionVecSt1 () const
Double_t getPositionSt3 (Double_t &x, Double_t &y) const
Double_t getPositionSt3 () const
TVector3 getPositionVecSt3 () const
Double_t getMomentum (const TMatrixD &state, Double_t &px, Double_t &py, Double_t &pz) const
Double_t getPosition (const TMatrixD &state, Double_t &x, Double_t &y) const
Bool_t isKalmanFitted ()
Fit status.
void setKalmanStatus (Int_t status)
bool operator< (const SRecTrack &elem) const
Comparitor.
void setChisq (Double_t chisq)
Sets.
void insertHitIndex (Int_t index)
void insertStateVector (TMatrixD state)
void insertCovariance (TMatrixD covar)
void insertZ (Double_t z)
void insertChisq (Double_t chisq)
void insertGFState (const genfit::MeasuredStateOnPlane &msop)
void adjustKMag (double kmagStr)
Fast-adjust of kmag.
bool isVertexValid () const
Vertex stuff.
void setZVertex (Double_t z, bool update=true)
void updateVtxHypothesis ()
void setVertexFast (TVector3 mom, TVector3 pos)
Plain setting, no KF-related stuff.
void swimToVertex (TVector3 *pos=nullptr, TVector3 *mom=nullptr, bool hyptest=true)
Simple swim to vertex.
TLorentzVector getMomentumVertex ()
Get the vertex info.
Double_t getMomentumVertex (Double_t &px, Double_t &py, Double_t &pz)
Double_t getZVertex ()
Double_t getRVertex ()
TVector3 getVertex ()
Double_t getVtxPar (Int_t i)
Double_t getChisqVertex ()
TVector3 getDumpPos ()
Get mom/pos at a given location.
TVector3 getDumpFacePos ()
TVector3 getTargetPos ()
TVector3 getXVertexPos ()
TVector3 getYVertexPos ()
TVector3 getDumpMom ()
TVector3 getDumpFaceMom ()
TVector3 getTargetMom ()
TVector3 getXVertexMom ()
TVector3 getYVertexMom ()
TVector3 getVertexPos ()
TVector3 getVertexMom ()
Double_t getChisqDump ()
Double_t getChisqTarget ()
Double_t getChisqUpstream ()
void setDumpPos (TVector3 pos)
Set mom/pos at a given location.
void setDumpFacePos (TVector3 pos)
void setTargetPos (TVector3 pos)
void setXVertexPos (TVector3 pos)
void setYVertexPos (TVector3 pos)
void setVertexPos (TVector3 pos)
void setDumpMom (TVector3 mom)
void setDumpFaceMom (TVector3 mom)
void setTargetMom (TVector3 mom)
void setXVertexMom (TVector3 mom)
void setYVertexMom (TVector3 mom)
void setVertexMom (TVector3 mom)
void setChisqDump (Double_t chisq)
void setChisqTarget (Double_t chisq)
void setChisqUpstream (Double_t chisq)
void setChisqVertex (Double_t chisq)
void setTriggerRoad (Int_t roadID)
Trigger road info.
Int_t getTriggerRoad ()
void setPTSlope (Double_t slopeX, Double_t slopeY)
Prop. tube muon ID info.
void setNHitsInPT (Int_t nHitsX, Int_t nHitsY)
Double_t getPTSlopeX ()
Double_t getPTSlopeY ()
Double_t getDeflectionX ()
Double_t getDeflectionY ()
Int_t getNHitsInPTX ()
Int_t getNHitsInPTY ()
bool isTarget ()
Overall track quality cut.
bool isDump ()
void print (std::ostream &os=std::cout) const
Debugging output.
void printGF (std::ostream &os=std::cout) const
Public Member Functions inherited from SQTrack
virtual ~SQTrack ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Protected Member Functions inherited from SQTrack
SQTrack ()
ClassDef (SQTrack, 1)
Detailed Description
Definition at line 42 of file SRecEvent.h.
Constructor & Destructor Documentation
SRecTrack()
SRecTrack::SRecTrack ()
Definition at line 117 of file SRecEvent.cxx.
Referenced by Clone(), and Reset().
Member Function Documentation
adjustKMag()
void SRecTrack::adjustKMag (double kmagStr)
Fast-adjust of kmag.
Definition at line 363 of file SRecEvent.cxx.
Clone()
SRecTrack* SRecTrack::Clone () const inline virtual
Implements SQTrack.
Definition at line 51 of file SRecEvent.h.
References SRecTrack().
get_charge()
virtual int SRecTrack::get_charge () const inline virtual
Return the charge, i.e. +1 or -1.
Implements SQTrack.
Definition at line 60 of file SRecEvent.h.
References getCharge().
get_chisq()
virtual double SRecTrack::get_chisq () const inline virtual
Implements SQTrack.
Definition at line 84 of file SRecEvent.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
get_chisq_dump()
virtual double SRecTrack::get_chisq_dump () const inline virtual
Implements SQTrack.
Definition at line 86 of file SRecEvent.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
get_chisq_target()
virtual double SRecTrack::get_chisq_target () const inline virtual
Implements SQTrack.
Definition at line 85 of file SRecEvent.h.
get_chisq_upstream()
virtual double SRecTrack::get_chisq_upstream () const inline virtual
Definition at line 88 of file SRecEvent.h.
get_chsiq_upstream()
virtual double SRecTrack::get_chsiq_upstream () const inline virtual
Implements SQTrack.
Definition at line 87 of file SRecEvent.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
get_hit_id()
virtual int SRecTrack::get_hit_id (const int i) const inline virtual
Implements SQTrack.
Definition at line 96 of file SRecEvent.h.
get_mom_dump()
virtual TLorentzVector SRecTrack::get_mom_dump () const inline virtual
Implements SQTrack.
Definition at line 94 of file SRecEvent.h.
References getlvec().
get_mom_st1()
virtual TLorentzVector SRecTrack::get_mom_st1 () const inline virtual
Return the track momentum at Station 1.
Implements SQTrack.
Definition at line 78 of file SRecEvent.h.
References getlvec(), and getMomentumVecSt1().
get_mom_st3()
virtual TLorentzVector SRecTrack::get_mom_st3 () const inline virtual
Return the track momentum at Station 3.
Implements SQTrack.
Definition at line 81 of file SRecEvent.h.
References getlvec(), and getMomentumVecSt3().
get_mom_target()
virtual TLorentzVector SRecTrack::get_mom_target () const inline virtual
Implements SQTrack.
Definition at line 93 of file SRecEvent.h.
References getlvec().
get_mom_vtx()
virtual TLorentzVector SRecTrack::get_mom_vtx () const inline virtual
Return the track momentum at vertex.
Implements SQTrack.
Definition at line 75 of file SRecEvent.h.
References getlvec().
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
get_num_hits()
virtual int SRecTrack::get_num_hits () const inline virtual
Return the number of hits associated to this track.
Implements SQTrack.
Definition at line 63 of file SRecEvent.h.
References getNHits().
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
get_pos_dump()
virtual TVector3 SRecTrack::get_pos_dump () const inline virtual
Implements SQTrack.
Definition at line 91 of file SRecEvent.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
get_pos_st1()
virtual TVector3 SRecTrack::get_pos_st1 () const inline virtual
Return the track position at Station 1.
Implements SQTrack.
Definition at line 69 of file SRecEvent.h.
References getPositionVecSt1().
get_pos_st3()
virtual TVector3 SRecTrack::get_pos_st3 () const inline virtual
Return the track position at Station 3.
Implements SQTrack.
Definition at line 72 of file SRecEvent.h.
References getPositionVecSt3().
get_pos_target()
virtual TVector3 SRecTrack::get_pos_target () const inline virtual
Implements SQTrack.
Definition at line 90 of file SRecEvent.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
get_pos_vtx()
virtual TVector3 SRecTrack::get_pos_vtx () const inline virtual
Return the track position at vertex.
Implements SQTrack.
Definition at line 66 of file SRecEvent.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
get_rec_track_id()
virtual int SRecTrack::get_rec_track_id () const inline virtual
Return the track ID of associated reconstructed track. Valid only if this object holds truth track info.
Implements SQTrack.
Definition at line 57 of file SRecEvent.h.
get_track_id()
virtual int SRecTrack::get_track_id () const inline virtual
SQTrack virtual overloads.
Implements SQTrack.
Definition at line 54 of file SRecEvent.h.
getCharge()
Int_t SRecTrack::getCharge () const inline
Gets.
Definition at line 101 of file SRecEvent.h.
Referenced by mTrkEveDisplay::draw_tracks(), VertexFit::findDimuonVertexFast(), get_charge(), SQGenFit::GFTrack::GFTrack(), AnaSimDst::process_event(), AnaEmbeddedData::process_event(), SQTruthVertexing::process_event(), SQVertexing::process_event(), OnlMonReco::ProcessEventOnlMon(), setVertexFast(), and swimToVertex().
getChisq()
Double_t SRecTrack::getChisq () const inline
Definition at line 104 of file SRecEvent.h.
Referenced by getQuality(), isValid(), and KalmanTrack::KalmanTrack().
getChisqAtNode()
Double_t SRecTrack::getChisqAtNode (Int_t i) inline
Definition at line 112 of file SRecEvent.h.
Referenced by KalmanTrack::KalmanTrack().
getChisqDump()
Double_t SRecTrack::getChisqDump () inline
Definition at line 198 of file SRecEvent.h.
Referenced by VertexFit::setRecEvent().
getChisqTarget()
Double_t SRecTrack::getChisqTarget () inline
Definition at line 199 of file SRecEvent.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), AnaDimuonV2::process_event(), and VertexFit::setRecEvent().
getChisqUpstream()
Double_t SRecTrack::getChisqUpstream () inline
Definition at line 200 of file SRecEvent.h.
Referenced by VertexFit::setRecEvent().
getChisqVertex()
Double_t SRecTrack::getChisqVertex () inline
Definition at line 183 of file SRecEvent.h.
Referenced by KalmanFastTracking::buildGlobalTracks(), KalmanDSTrk::buildGlobalTracks(), and VertexFit::setRecEvent().
getCovariance()
TMatrixD SRecTrack::getCovariance (Int_t i) inline
Definition at line 110 of file SRecEvent.h.
Referenced by VertexFit::addTrack(), VertexFit::findSingleMuonVertex(), and KalmanTrack::KalmanTrack().
getDeflectionX()
Double_t SRecTrack::getDeflectionX () inline
Definition at line 229 of file SRecEvent.h.
getDeflectionY()
Double_t SRecTrack::getDeflectionY () inline
Definition at line 230 of file SRecEvent.h.
getDumpFaceMom()
TVector3 SRecTrack::getDumpFaceMom () inline
Definition at line 192 of file SRecEvent.h.
getDumpFacePos()
TVector3 SRecTrack::getDumpFacePos () inline
Definition at line 187 of file SRecEvent.h.
getDumpMom()
TVector3 SRecTrack::getDumpMom () inline
Definition at line 191 of file SRecEvent.h.
getDumpPos()
TVector3 SRecTrack::getDumpPos () inline
Get mom/pos at a given location.
Definition at line 186 of file SRecEvent.h.
Referenced by VertexFit::setRecEvent().
getExpMomentumFast() [1/2]
Double_t SRecTrack::getExpMomentumFast (Double_t z, Double_t & px, Double_t & py, Double_t & pz, Int_t iNode = -1)
Definition at line 311 of file SRecEvent.cxx.
References getMomentum(), getNearestNode(), and getNHits().
Referenced by getExpMomentumFast().
getExpMomentumFast() [2/2]
double SRecTrack::getExpMomentumFast (Double_t z, Int_t iNode = -1)
Definition at line 305 of file SRecEvent.cxx.
References getExpMomentumFast().
getExpPosErrorFast()
void SRecTrack::getExpPosErrorFast (Double_t z, Double_t & dx, Double_t & dy, Int_t iNode = -1)
Definition at line 288 of file SRecEvent.cxx.
References getNearestNode(), and getNHits().
getExpPositionFast()
void SRecTrack::getExpPositionFast (Double_t z, Double_t & x, Double_t & y, Int_t iNode = -1)
Definition at line 267 of file SRecEvent.cxx.
References TrkPar::_covar_kf, TrkPar::_state_kf, TrkPar::get_dxdz(), TrkPar::get_dydz(), TrkPar::get_x(), TrkPar::get_y(), getNearestNode(), and getNHits().
Referenced by mTrkEveDisplay::draw_tracks(), and TriggerRoad::TriggerRoad().
getGFAuxInfo()
TVectorD SRecTrack::getGFAuxInfo (Int_t i) inline
Definition at line 117 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::GFTrack().
getGFCov()
TMatrixDSym SRecTrack::getGFCov (Int_t i) inline
Definition at line 119 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::GFTrack().
getGFPlaneO()
TVector3 SRecTrack::getGFPlaneO (Int_t i) inline
Definition at line 114 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::GFTrack().
getGFPlaneU()
TVector3 SRecTrack::getGFPlaneU (Int_t i) inline
Definition at line 115 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::GFTrack().
getGFPlaneV()
TVector3 SRecTrack::getGFPlaneV (Int_t i) inline
Definition at line 116 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::GFTrack().
getGFState()
TVectorD SRecTrack::getGFState (Int_t i) inline
Definition at line 118 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::GFTrack().
getHitIndex()
Int_t SRecTrack::getHitIndex (Int_t i) inline
Definition at line 108 of file SRecEvent.h.
Referenced by KalmanTrack::KalmanTrack(), and TruthNodeMaker::process_event().
getlvec()
TLorentzVector SRecTrack::getlvec (const TVector3 & vec) const inline
Definition at line 98 of file SRecEvent.h.
References M_MU.
Referenced by get_mom_dump(), get_mom_st1(), get_mom_st3(), get_mom_target(), and get_mom_vtx().
getMomentum()
Double_t SRecTrack::getMomentum (const TMatrixD & state, Double_t & px, Double_t & py, Double_t & pz) const
Definition at line 322 of file SRecEvent.cxx.
Referenced by getExpMomentumFast(), getMomentumSt1(), getMomentumSt3(), and getMomentumVertex().
getMomentumSt1() [1/2]
Double_t SRecTrack::getMomentumSt1 () const inline
Definition at line 128 of file SRecEvent.h.
References getMomentumSt1().
Referenced by getMomentumSt1(), and getMomentumVecSt1().
getMomentumSt1() [2/2]
Double_t SRecTrack::getMomentumSt1 (Double_t & px, Double_t & py, Double_t & pz) const inline
Definition at line 127 of file SRecEvent.h.
References getMomentum().
Referenced by mTrkEveDisplay::draw_tracks().
getMomentumSt3() [1/2]
Double_t SRecTrack::getMomentumSt3 () const inline
Definition at line 132 of file SRecEvent.h.
References getMomentumSt3().
Referenced by getMomentumSt3(), and getMomentumVecSt3().
getMomentumSt3() [2/2]
Double_t SRecTrack::getMomentumSt3 (Double_t & px, Double_t & py, Double_t & pz) const inline
Definition at line 131 of file SRecEvent.h.
References getMomentum().
getMomentumVecSt1()
TVector3 SRecTrack::getMomentumVecSt1 () const inline
Definition at line 129 of file SRecEvent.h.
References getMomentumSt1().
Referenced by get_mom_st1(), SQGenFit::GFTrack::GFTrack(), OnlMonReco::ProcessEventOnlMon(), and swimToVertex().
getMomentumVecSt3()
TVector3 SRecTrack::getMomentumVecSt3 () const inline
Definition at line 133 of file SRecEvent.h.
References getMomentumSt3().
Referenced by get_mom_st3().
getMomentumVertex() [1/2]
TLorentzVector SRecTrack::getMomentumVertex ()
Get the vertex info.
Definition at line 340 of file SRecEvent.cxx.
Referenced by AnaSimDst::process_event(), AnaEmbeddedData::process_event(), and VertexFit::setRecEvent().
getMomentumVertex() [2/2]
Double_t SRecTrack::getMomentumVertex (Double_t & px, Double_t & py, Double_t & pz) inline
Definition at line 178 of file SRecEvent.h.
References getMomentum().
getNearestNode()
Int_t SRecTrack::getNearestNode (Double_t z)
Definition at line 249 of file SRecEvent.cxx.
References getNHits().
Referenced by getExpMomentumFast(), getExpPosErrorFast(), and getExpPositionFast().
getNHits()
Int_t SRecTrack::getNHits () const inline
Definition at line 102 of file SRecEvent.h.
Referenced by get_num_hits(), getExpMomentumFast(), getExpPosErrorFast(), getExpPositionFast(), getNearestNode(), getProb(), getQuality(), SQGenFit::GFTrack::GFTrack(), isValid(), KalmanTrack::KalmanTrack(), operator<(), and TruthNodeMaker::process_event().
getNHitsInPTX()
Int_t SRecTrack::getNHitsInPTX () inline
Definition at line 231 of file SRecEvent.h.
getNHitsInPTY()
Int_t SRecTrack::getNHitsInPTY () inline
Definition at line 232 of file SRecEvent.h.
getNHitsInStation()
Int_t SRecTrack::getNHitsInStation (Int_t stationID)
Definition at line 149 of file SRecEvent.cxx.
getPosition()
Double_t SRecTrack::getPosition (const TMatrixD & state, Double_t & x, Double_t & y) const
Definition at line 332 of file SRecEvent.cxx.
Referenced by getPositionSt1(), and getPositionSt3().
getPositionSt1() [1/2]
Double_t SRecTrack::getPositionSt1 () const inline
Definition at line 136 of file SRecEvent.h.
References getPositionSt1().
Referenced by getPositionSt1(), and getPositionVecSt1().
getPositionSt1() [2/2]
Double_t SRecTrack::getPositionSt1 (Double_t & x, Double_t & y) const inline
Definition at line 135 of file SRecEvent.h.
References getPosition().
Referenced by mTrkEveDisplay::draw_tracks().
getPositionSt3() [1/2]
Double_t SRecTrack::getPositionSt3 () const inline
Definition at line 140 of file SRecEvent.h.
References getPositionSt3().
Referenced by getPositionSt3(), and getPositionVecSt3().
getPositionSt3() [2/2]
Double_t SRecTrack::getPositionSt3 (Double_t & x, Double_t & y) const inline
Definition at line 139 of file SRecEvent.h.
References getPosition().
getPositionVecSt1()
TVector3 SRecTrack::getPositionVecSt1 () const inline
Definition at line 137 of file SRecEvent.h.
References getPositionSt1().
Referenced by get_pos_st1(), and SQGenFit::GFTrack::GFTrack().
getPositionVecSt3()
TVector3 SRecTrack::getPositionVecSt3 () const inline
Definition at line 141 of file SRecEvent.h.
References getPositionSt3().
Referenced by get_pos_st3().
getProb()
Double_t SRecTrack::getProb () const
Definition at line 163 of file SRecEvent.cxx.
References getNHits().
Referenced by operator<().
getPTSlopeX()
Double_t SRecTrack::getPTSlopeX () inline
Definition at line 227 of file SRecEvent.h.
getPTSlopeY()
Double_t SRecTrack::getPTSlopeY () inline
Definition at line 228 of file SRecEvent.h.
getQuality()
Double_t SRecTrack::getQuality () const inline
Definition at line 106 of file SRecEvent.h.
References getChisq(), and getNHits().
getRVertex()
Double_t SRecTrack::getRVertex () inline
Definition at line 180 of file SRecEvent.h.
getStateVector()
TMatrixD SRecTrack::getStateVector (Int_t i) inline
Definition at line 109 of file SRecEvent.h.
Referenced by VertexFit::addTrack(), VertexFit::findSingleMuonVertex(), and KalmanTrack::KalmanTrack().
getTargetMom()
TVector3 SRecTrack::getTargetMom () inline
Definition at line 193 of file SRecEvent.h.
Referenced by mTrkEveDisplay::draw_tracks().
getTargetPos()
TVector3 SRecTrack::getTargetPos () inline
Definition at line 188 of file SRecEvent.h.
Referenced by mTrkEveDisplay::draw_tracks(), and VertexFit::setRecEvent().
getTriggerRoad()
Int_t SRecTrack::getTriggerRoad () inline
Definition at line 222 of file SRecEvent.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
getVertex()
TVector3 SRecTrack::getVertex () inline
Definition at line 181 of file SRecEvent.h.
Referenced by AnaSimDst::process_event(), and VertexFit::setRecEvent().
getVertexMom()
TVector3 SRecTrack::getVertexMom () inline
Definition at line 197 of file SRecEvent.h.
getVertexPos()
TVector3 SRecTrack::getVertexPos () inline
Definition at line 196 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::getSRecTrack().
getVtxPar()
Double_t SRecTrack::getVtxPar (Int_t i) inline
Definition at line 182 of file SRecEvent.h.
getXVertexMom()
TVector3 SRecTrack::getXVertexMom () inline
Definition at line 194 of file SRecEvent.h.
getXVertexPos()
TVector3 SRecTrack::getXVertexPos () inline
Definition at line 189 of file SRecEvent.h.
getYVertexMom()
TVector3 SRecTrack::getYVertexMom () inline
Definition at line 195 of file SRecEvent.h.
getYVertexPos()
TVector3 SRecTrack::getYVertexPos () inline
Definition at line 190 of file SRecEvent.h.
getZ()
Double_t SRecTrack::getZ (Int_t i) inline
Definition at line 111 of file SRecEvent.h.
Referenced by VertexFit::addTrack(), VertexFit::findSingleMuonVertex(), and KalmanTrack::KalmanTrack().
getZVertex()
Double_t SRecTrack::getZVertex () inline
Definition at line 179 of file SRecEvent.h.
Referenced by updateVtxHypothesis().
identify()
void SRecTrack::identify (std::ostream & os = std::cout) const inline virtual
PHObject virtual overloads.
Implements SQTrack.
Definition at line 48 of file SRecEvent.h.
References print().
insertChisq()
void SRecTrack::insertChisq (Double_t chisq) inline
Definition at line 159 of file SRecEvent.h.
Referenced by KalmanTrack::getSRecTrack(), and SQGenFit::GFTrack::getSRecTrack().
insertCovariance()
void SRecTrack::insertCovariance (TMatrixD covar) inline
Definition at line 157 of file SRecEvent.h.
Referenced by KalmanTrack::getSRecTrack(), SQGenFit::GFTrack::getSRecTrack(), and Tracklet::getSRecTrack().
insertGFState()
void SRecTrack::insertGFState (const genfit::MeasuredStateOnPlane & msop)
Definition at line 351 of file SRecEvent.cxx.
Referenced by SQGenFit::GFTrack::getSRecTrack().
insertHitIndex()
void SRecTrack::insertHitIndex (Int_t index) inline
Definition at line 155 of file SRecEvent.h.
Referenced by KalmanTrack::getSRecTrack(), SQGenFit::GFTrack::getSRecTrack(), and Tracklet::getSRecTrack().
insertStateVector()
void SRecTrack::insertStateVector (TMatrixD state) inline
Definition at line 156 of file SRecEvent.h.
Referenced by KalmanTrack::getSRecTrack(), SQGenFit::GFTrack::getSRecTrack(), and Tracklet::getSRecTrack().
insertZ()
void SRecTrack::insertZ (Double_t z) inline
Definition at line 158 of file SRecEvent.h.
Referenced by KalmanTrack::getSRecTrack(), SQGenFit::GFTrack::getSRecTrack(), and Tracklet::getSRecTrack().
isDump()
bool SRecTrack::isDump ()
Definition at line 397 of file SRecEvent.cxx.
isKalmanFitted()
Bool_t SRecTrack::isKalmanFitted () inline
Fit status.
Definition at line 147 of file SRecEvent.h.
Referenced by SQVertexing::process_event().
isTarget()
bool SRecTrack::isTarget ()
Overall track quality cut.
Definition at line 392 of file SRecEvent.cxx.
isValid()
int SRecTrack::isValid () const virtual
isValid returns non zero if object contains vailid data
Implements SQTrack.
Definition at line 371 of file SRecEvent.cxx.
References getChisq(), getNHits(), and isVertexValid().
Referenced by KalmanFastTracking::buildGlobalTracks(), KalmanDSTrk::buildGlobalTracks(), and VertexFit::setRecEvent().
isVertexValid()
bool SRecTrack::isVertexValid () const
Vertex stuff.
Definition at line 241 of file SRecEvent.cxx.
Referenced by isValid().
operator<()
bool SRecTrack::operator< (const SRecTrack & elem) const
Comparitor.
Definition at line 144 of file SRecEvent.cxx.
References getNHits(), and getProb().
print()
void SRecTrack::print (std::ostream & os = std::cout) const
Debugging output.
Definition at line 578 of file SRecEvent.cxx.
Referenced by identify().
printGF()
void SRecTrack::printGF (std::ostream & os = std::cout) const
Definition at line 593 of file SRecEvent.cxx.
Reset()
void SRecTrack::Reset () inline virtual
Clear Event.
Implements SQTrack.
Definition at line 49 of file SRecEvent.h.
References SRecTrack().
set_charge()
virtual void SRecTrack::set_charge (const int a) inline virtual
Implements SQTrack.
Definition at line 61 of file SRecEvent.h.
set_mom_st1()
virtual void SRecTrack::set_mom_st1 (const TLorentzVector a) inline virtual
Implements SQTrack.
Definition at line 79 of file SRecEvent.h.
set_mom_st3()
virtual void SRecTrack::set_mom_st3 (const TLorentzVector a) inline virtual
Implements SQTrack.
Definition at line 82 of file SRecEvent.h.
set_mom_vtx()
virtual void SRecTrack::set_mom_vtx (const TLorentzVector a) inline virtual
Implements SQTrack.
Definition at line 76 of file SRecEvent.h.
set_num_hits()
virtual void SRecTrack::set_num_hits (const int a) inline virtual
Implements SQTrack.
Definition at line 64 of file SRecEvent.h.
set_pos_st1()
virtual void SRecTrack::set_pos_st1 (const TVector3 a) inline virtual
Implements SQTrack.
Definition at line 70 of file SRecEvent.h.
set_pos_st3()
virtual void SRecTrack::set_pos_st3 (const TVector3 a) inline virtual
Implements SQTrack.
Definition at line 73 of file SRecEvent.h.
set_pos_vtx()
virtual void SRecTrack::set_pos_vtx (const TVector3 a) inline virtual
Implements SQTrack.
Definition at line 67 of file SRecEvent.h.
set_rec_track_id()
virtual void SRecTrack::set_rec_track_id (const int a) inline virtual
Implements SQTrack.
Definition at line 58 of file SRecEvent.h.
set_track_id()
virtual void SRecTrack::set_track_id (const int a) inline virtual
Implements SQTrack.
Definition at line 55 of file SRecEvent.h.
setChisq()
void SRecTrack::setChisq (Double_t chisq) inline
Sets.
Definition at line 154 of file SRecEvent.h.
Referenced by KalmanTrack::getSRecTrack(), SQGenFit::GFTrack::getSRecTrack(), and Tracklet::getSRecTrack().
setChisqDump()
void SRecTrack::setChisqDump (Double_t chisq) inline
Definition at line 215 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::getSRecTrack(), and updateVtxHypothesis().
setChisqTarget()
void SRecTrack::setChisqTarget (Double_t chisq) inline
Definition at line 216 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::getSRecTrack(), SQVertexing::process_event(), and updateVtxHypothesis().
setChisqUpstream()
void SRecTrack::setChisqUpstream (Double_t chisq) inline
Definition at line 217 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::getSRecTrack(), and updateVtxHypothesis().
setChisqVertex()
void SRecTrack::setChisqVertex (Double_t chisq) inline
Definition at line 218 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::getSRecTrack().
setDumpFaceMom()
void SRecTrack::setDumpFaceMom (TVector3 mom) inline
Definition at line 210 of file SRecEvent.h.
Referenced by swimToVertex().
setDumpFacePos()
void SRecTrack::setDumpFacePos (TVector3 pos) inline
Definition at line 204 of file SRecEvent.h.
Referenced by swimToVertex().
setDumpMom()
void SRecTrack::setDumpMom (TVector3 mom) inline
Definition at line 209 of file SRecEvent.h.
Referenced by swimToVertex().
setDumpPos()
void SRecTrack::setDumpPos (TVector3 pos) inline
Set mom/pos at a given location.
Definition at line 203 of file SRecEvent.h.
Referenced by swimToVertex().
setKalmanStatus()
void SRecTrack::setKalmanStatus (Int_t status) inline
Definition at line 148 of file SRecEvent.h.
Referenced by SQReco::fitTrackCand(), KalmanTrack::getSRecTrack(), SQGenFit::GFTrack::getSRecTrack(), SQReco::process_event(), KalmanFastTracking::processOneTracklet(), and KalmanDSTrk::processOneTracklet().
setNHitsInPT()
void SRecTrack::setNHitsInPT (Int_t nHitsX, Int_t nHitsY) inline
Definition at line 226 of file SRecEvent.h.
Referenced by SQReco::fitTrackCand(), Tracklet::getSRecTrack(), KalmanFastTracking::processOneTracklet(), and KalmanDSTrk::processOneTracklet().
setPTSlope()
void SRecTrack::setPTSlope (Double_t slopeX, Double_t slopeY) inline
Prop. tube muon ID info.
Definition at line 225 of file SRecEvent.h.
Referenced by SQReco::fitTrackCand(), Tracklet::getSRecTrack(), KalmanFastTracking::processOneTracklet(), and KalmanDSTrk::processOneTracklet().
setTargetMom()
void SRecTrack::setTargetMom (TVector3 mom) inline
Definition at line 211 of file SRecEvent.h.
Referenced by SQVertexing::process_event(), and swimToVertex().
setTargetPos()
void SRecTrack::setTargetPos (TVector3 pos) inline
Definition at line 205 of file SRecEvent.h.
Referenced by SQVertexing::process_event(), and swimToVertex().
setTriggerRoad()
void SRecTrack::setTriggerRoad (Int_t roadID) inline
Trigger road info.
Definition at line 221 of file SRecEvent.h.
Referenced by SQReco::fitTrackCand(), Tracklet::getSRecTrack(), KalmanFastTracking::processOneTracklet(), and KalmanDSTrk::processOneTracklet().
setVertexFast()
void SRecTrack::setVertexFast (TVector3 mom, TVector3 pos)
Plain setting, no KF-related stuff.
Definition at line 227 of file SRecEvent.cxx.
References getCharge().
Referenced by swimToVertex().
setVertexMom()
void SRecTrack::setVertexMom (TVector3 mom) inline
Definition at line 214 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::getSRecTrack().
setVertexPos()
void SRecTrack::setVertexPos (TVector3 pos) inline
Definition at line 208 of file SRecEvent.h.
Referenced by SQGenFit::GFTrack::getSRecTrack().
setXVertexMom()
void SRecTrack::setXVertexMom (TVector3 mom) inline
Definition at line 212 of file SRecEvent.h.
Referenced by swimToVertex().
setXVertexPos()
void SRecTrack::setXVertexPos (TVector3 pos) inline
Definition at line 206 of file SRecEvent.h.
Referenced by swimToVertex().
setYVertexMom()
void SRecTrack::setYVertexMom (TVector3 mom) inline
Definition at line 213 of file SRecEvent.h.
Referenced by swimToVertex().
setYVertexPos()
void SRecTrack::setYVertexPos (TVector3 pos) inline
Definition at line 207 of file SRecEvent.h.
Referenced by swimToVertex().
setZVertex()
void SRecTrack::setZVertex (Double_t z, bool update = true)
Definition at line 168 of file SRecEvent.cxx.
References TrkPar::_covar_kf, TrkPar::_state_kf, TrkPar::_z, KalmanFilter::enableDumpCorrection(), KalmanFilter::fit_node(), TrkPar::get_mom_vec(), TrkPar::get_x(), TrkPar::get_y(), Node::getChisq(), Node::getFiltered(), Node::getMeasurement(), Node::getMeasurementCov(), Node::getProjector(), KalmanFilter::instance(), KalmanFilter::setCurrTrkpar(), and Node::setZ().
Referenced by VertexFit::setRecEvent(), and updateVtxHypothesis().
swimToVertex()
void SRecTrack::swimToVertex (TVector3 * pos = nullptr, TVector3 * mom = nullptr, bool hyptest = true)
Simple swim to vertex.
Definition at line 402 of file SRecEvent.cxx.
References FMAGSTR, getCharge(), getMomentumVecSt1(), setDumpFaceMom(), setDumpFacePos(), setDumpMom(), setDumpPos(), setTargetMom(), setTargetPos(), setVertexFast(), setXVertexMom(), setXVertexPos(), setYVertexMom(), setYVertexPos(), and updateVtxHypothesis().
Referenced by VertexFit::findDimuonVertexFast(), KalmanTrack::getSRecTrack(), SQGenFit::GFTrack::getSRecTrack(), and Tracklet::getSRecTrack().
updateVtxHypothesis()
void SRecTrack::updateVtxHypothesis ()
Definition at line 213 of file SRecEvent.cxx.
References getZVertex(), setChisqDump(), setChisqTarget(), setChisqUpstream(), and setZVertex().
Referenced by swimToVertex().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/SRecEvent.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/SRecEvent.cxx