E1039 Software: HepMCCompress Class Reference
HepMCCompress Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/HepMCCompress.h>
Public Member Functions
HepMCCompress (const std::string &name="HEPMCREADER")
virtual ~HepMCCompress ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
short int FloatToInt (const float rval) const
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::set< int > exclude_pid
std::set< int > select_pid
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 11 of file HepMCCompress.h.
Constructor & Destructor Documentation
HepMCCompress()
HepMCCompress::HepMCCompress (const std::string & name = "HEPMCREADER")
Definition at line 34 of file HepMCCompress.cc.
~HepMCCompress()
virtual HepMCCompress::~HepMCCompress () inline virtual
Definition at line 15 of file HepMCCompress.h.
References FloatToInt(), Init(), and process_event().
Member Function Documentation
FloatToInt()
short int HepMCCompress::FloatToInt (const float rval) const protected
Definition at line 141 of file HepMCCompress.cc.
References half::bits().
Referenced by process_event(), and ~HepMCCompress().
Init()
int HepMCCompress::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 39 of file HepMCCompress.cc.
References PHCompositeNode::addNode(), VariableArrayContainer::AddVarArray(), PHNodeIterator::findFirst(), varids::G4PARTICLEV1, and varids::G4VTXV1.
Referenced by ~HepMCCompress().
process_event()
int HepMCCompress::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 61 of file HepMCCompress.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, exclude_pid, FloatToInt(), isfinal, PHWHERE, and select_pid.
Referenced by ~HepMCCompress().
Member Data Documentation
exclude_pid
std::set<int> HepMCCompress::exclude_pid protected
Definition at line 21 of file HepMCCompress.h.
Referenced by process_event().
select_pid
std::set<int> HepMCCompress::select_pid protected
Definition at line 22 of file HepMCCompress.h.
Referenced by process_event().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/HepMCCompress.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/HepMCCompress.cc