Class Reference for E1039 Core & Analysis Software: SQHardEvent_v1 Class Reference
SQHardEvent_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHardEvent_v1.h>
Public Member Functions
SQHardEvent_v1 ()
virtual ~SQHardEvent_v1 ()
virtual void Reset ()
Clear Event.
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual SQHardEvent * Clone () const
virtual int get_coda_event_id () const
Return the Coda-event ID, which is unique per run.
virtual void set_coda_event_id (const int a)
virtual int get_vme_time () const
Return the VME time.
virtual void set_vme_time (const int a)
virtual int get_raw_matrix (const unsigned short i) const
Return the raw count of the selected trigger channel.
virtual void set_raw_matrix (const unsigned short i, const bool a)
virtual int get_after_inh_matrix (const unsigned short i) const
Return the after-inhibited count of the selected trigger channel.
virtual void set_after_inh_matrix (const unsigned short i, const bool a)
virtual short get_flag_v1495 () const
Return the quality flag of the V1495 readout.
virtual void set_flag_v1495 (const short a)
virtual short get_n_board_qie () const
Return the number of QIE boards read out.
virtual void set_n_board_qie (const short a)
virtual short get_n_board_v1495 () const
Return the number of V1495 boards read out.
virtual void set_n_board_v1495 (const short a)
virtual short get_n_board_taiwan () const
Return the number of Taiwan-TDC boards read out.
virtual void set_n_board_taiwan (const short a)
virtual short get_n_board_trig_bit () const
Return the number of trigger-bit boards read out.
virtual void set_n_board_trig_bit (const short a)
virtual short get_n_board_trig_count () const
Return the number of trigger-count boards read out.
virtual void set_n_board_trig_count (const short a)
ClassDef (SQHardEvent_v1, 1)
Public Member Functions inherited from SQHardEvent
virtual ~SQHardEvent ()
ClassDef (SQHardEvent, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Protected Member Functions inherited from SQHardEvent
SQHardEvent ()
Detailed Description
Definition at line 9 of file SQHardEvent_v1.h.
Constructor & Destructor Documentation
SQHardEvent_v1()
SQHardEvent_v1::SQHardEvent_v1 ()
Referenced by Clone().
~SQHardEvent_v1()
SQHardEvent_v1::~SQHardEvent_v1 () virtual
Definition at line 21 of file SQHardEvent_v1.cxx.
References Reset().
Member Function Documentation
ClassDef()
SQHardEvent_v1::ClassDef (SQHardEvent_v1 , 1)
Clone()
virtual SQHardEvent* SQHardEvent_v1::Clone () const inline virtual
Implements SQHardEvent.
Definition at line 29 of file SQHardEvent_v1.h.
References SQHardEvent_v1().
get_after_inh_matrix()
int SQHardEvent_v1::get_after_inh_matrix (const unsigned short i) const virtual
Return the after-inhibited count of the selected trigger channel.
Implements SQHardEvent.
Definition at line 52 of file SQHardEvent_v1.cxx.
get_coda_event_id()
virtual int SQHardEvent_v1::get_coda_event_id () const inline virtual
Return the Coda-event ID, which is unique per run.
Implements SQHardEvent.
Definition at line 31 of file SQHardEvent_v1.h.
get_flag_v1495()
virtual short SQHardEvent_v1::get_flag_v1495 () const inline virtual
Return the quality flag of the V1495 readout.
Implements SQHardEvent.
Definition at line 43 of file SQHardEvent_v1.h.
get_n_board_qie()
virtual short SQHardEvent_v1::get_n_board_qie () const inline virtual
Return the number of QIE boards read out.
Implements SQHardEvent.
Definition at line 46 of file SQHardEvent_v1.h.
get_n_board_taiwan()
virtual short SQHardEvent_v1::get_n_board_taiwan () const inline virtual
Return the number of Taiwan-TDC boards read out.
Implements SQHardEvent.
Definition at line 52 of file SQHardEvent_v1.h.
get_n_board_trig_bit()
virtual short SQHardEvent_v1::get_n_board_trig_bit () const inline virtual
Return the number of trigger-bit boards read out.
Implements SQHardEvent.
Definition at line 55 of file SQHardEvent_v1.h.
get_n_board_trig_count()
virtual short SQHardEvent_v1::get_n_board_trig_count () const inline virtual
Return the number of trigger-count boards read out.
Implements SQHardEvent.
Definition at line 58 of file SQHardEvent_v1.h.
get_n_board_v1495()
virtual short SQHardEvent_v1::get_n_board_v1495 () const inline virtual
Return the number of V1495 boards read out.
Implements SQHardEvent.
Definition at line 49 of file SQHardEvent_v1.h.
get_raw_matrix()
int SQHardEvent_v1::get_raw_matrix (const unsigned short i) const virtual
Return the raw count of the selected trigger channel.
Implements SQHardEvent.
Definition at line 40 of file SQHardEvent_v1.cxx.
get_vme_time()
virtual int SQHardEvent_v1::get_vme_time () const inline virtual
Return the VME time.
Implements SQHardEvent.
Definition at line 34 of file SQHardEvent_v1.h.
identify()
void SQHardEvent_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Implements SQHardEvent.
Definition at line 64 of file SQHardEvent_v1.cxx.
isValid()
virtual int SQHardEvent_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Implements SQHardEvent.
Definition at line 28 of file SQHardEvent_v1.h.
Reset()
void SQHardEvent_v1::Reset () virtual
Clear Event.
Implements SQHardEvent.
Definition at line 26 of file SQHardEvent_v1.cxx.
Referenced by ~SQHardEvent_v1().
set_after_inh_matrix()
void SQHardEvent_v1::set_after_inh_matrix (const unsigned short i, const bool a) virtual
Implements SQHardEvent.
Definition at line 58 of file SQHardEvent_v1.cxx.
set_coda_event_id()
virtual void SQHardEvent_v1::set_coda_event_id (const int a) inline virtual
Implements SQHardEvent.
Definition at line 32 of file SQHardEvent_v1.h.
set_flag_v1495()
virtual void SQHardEvent_v1::set_flag_v1495 (const short a) inline virtual
Implements SQHardEvent.
Definition at line 44 of file SQHardEvent_v1.h.
set_n_board_qie()
virtual void SQHardEvent_v1::set_n_board_qie (const short a) inline virtual
Implements SQHardEvent.
Definition at line 47 of file SQHardEvent_v1.h.
set_n_board_taiwan()
virtual void SQHardEvent_v1::set_n_board_taiwan (const short a) inline virtual
Implements SQHardEvent.
Definition at line 53 of file SQHardEvent_v1.h.
set_n_board_trig_bit()
virtual void SQHardEvent_v1::set_n_board_trig_bit (const short a) inline virtual
Implements SQHardEvent.
Definition at line 56 of file SQHardEvent_v1.h.
set_n_board_trig_count()
virtual void SQHardEvent_v1::set_n_board_trig_count (const short a) inline virtual
Implements SQHardEvent.
Definition at line 59 of file SQHardEvent_v1.h.
set_n_board_v1495()
virtual void SQHardEvent_v1::set_n_board_v1495 (const short a) inline virtual
Implements SQHardEvent.
Definition at line 50 of file SQHardEvent_v1.h.
set_raw_matrix()
void SQHardEvent_v1::set_raw_matrix (const unsigned short i, const bool a) virtual
Implements SQHardEvent.
Definition at line 46 of file SQHardEvent_v1.cxx.
set_vme_time()
virtual void SQHardEvent_v1::set_vme_time (const int a) inline virtual
Implements SQHardEvent.
Definition at line 35 of file SQHardEvent_v1.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHardEvent_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHardEvent_v1.cxx