Class Reference for E1039 Core & Analysis Software: UtilTrigger Namespace Reference
UtilTrigger Namespace Reference
Functions
int Hodo2Road (const int h1, const int h2, const int h3, const int h4, const int tb)
Convert a set of hodo IDs to a roadset ID.
void Road2Hodo (const int road, int &h1, int &h2, int &h3, int &h4, int &tb)
Convert a roadset ID to a set of hodo IDs.
int ExtractRoadID (const SQHitVector *vec)
Find a unique road in the given list of SQHits.
Function Documentation
int UtilTrigger::ExtractRoadID (const SQHitVector * vec)
Find a unique road in the given list of SQHits.
This function returns a road ID if the given list contains exactly one hit every top plane (i.e. H1T, H2T, H3T & H4T) or every bottom plane. It returns '0' if any plan has no hit or multiple hit. The given list can contain any extra Y-hodoscope, chamber or prop tube hit, which is just ignored.
Definition at line 40 of file UtilTrigger.cc.
References SQHitVector::begin(), SQHitVector::end(), SQHit::get_detector_id(), SQHit::get_element_id(), GeomSvc::getDetectorName(), Hodo2Road(), and GeomSvc::instance().
int UtilTrigger::Hodo2Road (const int h1, const int h2, const int h3, const int h4, const int tb)
Convert a set of hodo IDs to a roadset ID.
Note that the max hodo IDs are 23 (H1), 16 (H2), 16 (H3) and 16 (H4).
Definition at line 11 of file UtilTrigger.cc.
Referenced by ExtractRoadID().
void UtilTrigger::Road2Hodo (const int road, int & h1, int & h2, int & h3, int & h4, int & tb)
Convert a roadset ID to a set of hodo IDs.
Definition at line 19 of file UtilTrigger.cc.