SeaQuest Offline Software: MySQLSvc Class Reference
MySQLSvc Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/MySQLSvc.h>
Public Member Functions
MySQLSvc ()
virtual ~MySQLSvc ()
bool connectInput (std::string mysqlServer="", int mysqlPort=-1)
bool connectOutput (std::string mysqlServer="", int mysqlPort=-1)
TSQLServer * getInputServer ()
TSQLServer * getOutputServer ()
void setUserPasswd (std::string user_input, std::string passwd_input)
bool isRunStopped ()
int getNEventsFast (int event_hi=-1, int event_lo=0)
int getNEvents (int event_hi=-1, int event_lo=0)
bool getEvent (SRawEvent *rawEvent, int eventID)
bool getLatestEvt (SRawEvent *rawEvent)
bool getRandomEvt (SRawEvent *rawEvent)
bool getNextEvent (SRawEvent *rawEvent)
bool getNextEvent (SRawMCEvent *rawEvent)
bool isEventLoaded (int eventID)
bool getEventHeader (SRawEvent *rawEvent, int eventID)
bool getMCGenInfo (SRawMCEvent *mcEvent, int eventID)
bool initReader ()
bool initWriter ()
bool initBakWriter ()
void resetWriter ()
void finalizeWriter ()
void writeInfoTable (TTree *config)
void writeTrackingRes (TString tableSuffix, SRecEvent *recEvent, TClonesArray *tracklets=NULL)
void writeTrackTable (int trackID, SRecTrack *recTrack, TString tableSuffix)
void writeTrackHitTable (int trackID, Tracklet *tracklet)
void writeDimuonTable (int dimuonID, SRecDimuon dimuon, TString tableSuffix, int targetPos)
void writeEventTable (int eventID, int statusCode, int source1, int source2, TString tableSuffix)
std::string getSubsetTableSuffix () const
Get the suffix to add to end of intermediate event subrange tables (if any)
std::string getMySQLEventSelection () const
Get WHERE clause to add to MySQL query to select the event subrange (if any)
std::string getTableDefinition (const TString tableType) const
Get the definition of fields, keys, indices for a table (kTrack, kDimuon, or kTrackHit)
void pushToFinalTables (bool dropSubsetTables)
Copy output from intermediate subset tables to final table and delete subset tables (if desired)
void setInputSchema (std::string schema)
void setOutputSchema (std::string schema)
void setLoggingSchema (std::string schema)
void enableQIE (bool opt)
void enableTargetPos (bool opt)
void enableTriggerHits (bool opt)
int makeQueryInput ()
int makeQueryOutput ()
void commitInsertion (TString &insertion)
bool nextEntry ()
int getInt (int id, int default_val=0)
float getFloat (int id, float default_val=0.)
double getDouble (int id, double default_val=0.)
std::string getString (int id, std::string default_val="")
Static Public Member Functions
static MySQLSvc * instance ()
Private Attributes
std::string user
std::string passwd
GeomSvc * p_geomSvc
TriggerAnalyzer * p_triggerAna
TSQLServer * inputServer
Fetch input from this server.
TSQLServer * outputServer
Write output to this server.
TSQLResult * res
TSQLRow * row
std::string subsetTableSuffix
Append suffix to table names for intermediate event subset tables.
std::string subsetEventString
MySQL string used to select only the events to be processed (e.g. WHERE caluse)
bool readQIE
bool readTriggerHits
bool readTargetPos
bool readTrackPos
bool setTriggerEmu
TRandom rndm
int runID
int spillID
int nEvents
std::vector< int > eventIDs
std::vector< int > eventIDs_loaded
int index_eventID
char query [2000]
std::string inputSchema
std::string outputSchema
std::string logSchema
TString eventQuery
TString dimuonQuery
TString trackQuery
TString hitQuery
int nTracks
int nDimuons
Static Private Attributes
static MySQLSvc * p_mysqlSvc = NULL
Detailed Description
Definition at line 35 of file MySQLSvc.h.
Constructor & Destructor Documentation
MySQLSvc::MySQLSvc ()
Definition at line 27 of file MySQLSvc.cxx.
References eventIDs, getMySQLEventSelection(), getSubsetTableSuffix(), inputSchema, inputServer, JobOptsSvc::instance(), GeomSvc::instance(), logSchema, JobOptsSvc::m_inputSchema, JobOptsSvc::m_outputSchema, nDimuons, nEvents, nTracks, NULL, outputSchema, outputServer, p_geomSvc, p_triggerAna, passwd, readQIE, readTargetPos, readTrackPos, readTriggerHits, res, rndm, row, runID, spillID, subsetEventString, subsetTableSuffix, and user.
Referenced by instance().
MySQLSvc::~MySQLSvc () virtual
Definition at line 65 of file MySQLSvc.cxx.
References inputServer, NULL, outputServer, p_triggerAna, res, and row.
Member Function Documentation
void MySQLSvc::commitInsertion (TString & insertion)
Definition at line 1303 of file MySQLSvc.cxx.
References outputServer.
Referenced by finalizeWriter(), writeDimuonTable(), writeEventTable(), writeTrackHitTable(), and writeTrackTable().
bool MySQLSvc::connectInput (std::string mysqlServer = "", int mysqlPort = -1)
Definition at line 84 of file MySQLSvc.cxx.
References JobOptsSvc::GetInputMySQLURL(), inputServer, JobOptsSvc::instance(), LogInfo, NULL, passwd, and user.
Referenced by main().
bool MySQLSvc::connectOutput (std::string mysqlServer = "", int mysqlPort = -1)
Definition at line 112 of file MySQLSvc.cxx.
References JobOptsSvc::GetOutputMySQLURL(), inputServer, JobOptsSvc::instance(), LogInfo, NULL, outputServer, passwd, and user.
Referenced by main().
void MySQLSvc::enableQIE (bool opt) inline
Definition at line 104 of file MySQLSvc.h.
References readQIE.
void MySQLSvc::enableTargetPos (bool opt) inline
Definition at line 105 of file MySQLSvc.h.
References readTargetPos.
void MySQLSvc::enableTriggerHits (bool opt) inline
Definition at line 106 of file MySQLSvc.h.
References readTriggerHits.
void MySQLSvc::finalizeWriter ()
Definition at line 825 of file MySQLSvc.cxx.
References commitInsertion(), dimuonQuery, eventQuery, hitQuery, and trackQuery.
Referenced by main().
double MySQLSvc::getDouble (int id, double default_val = 0.)
Definition at line 1356 of file MySQLSvc.cxx.
References NULL, and row.
Referenced by getMCGenInfo().
bool MySQLSvc::getEvent (SRawEvent * rawEvent, int eventID)
Definition at line 322 of file MySQLSvc.cxx.
References TriggerAnalyzer::acceptEvent(), Hit::detectorID, Hit::driftDistance, Hit::elementID, GeomSvc::getDetectorID(), GeomSvc::getDriftDistance(), getFloat(), getInt(), GeomSvc::getMeasurement(), TriggerAnalyzer::getNRoadsNegBot(), TriggerAnalyzer::getNRoadsNegTop(), TriggerAnalyzer::getNRoadsPosBot(), TriggerAnalyzer::getNRoadsPosTop(), Hit::index, SRawEvent::insertHit(), GeomSvc::isCalibrationLoaded(), Hit::isInTime(), GeomSvc::isInTime(), makeQueryInput(), nChamberPlanes, nextEntry(), nHodoPlanes, p_geomSvc, p_triggerAna, Hit::pos, query, readTriggerHits, SRawEvent::reIndex(), row, Hit::setHodoMask(), Hit::setInTime(), SRawEvent::setNRoads(), setTriggerEmu, SRawEvent::setTriggerEmu(), Hit::tdcTime, GeomSvc::toLocalDetectorName(), USE_HIT, and USE_TRIGGER_HIT.
Referenced by getLatestEvt(), and getNextEvent().
bool MySQLSvc::getEventHeader (SRawEvent * rawEvent, int eventID)
Definition at line 464 of file MySQLSvc.cxx.
References Hit::detectorID, Hit::driftDistance, Hit::elementID, eventIDs_loaded, GeomSvc::getDetectorID(), getFloat(), getInt(), GeomSvc::getMeasurement(), Hit::index, SRawEvent::insertTriggerHit(), makeQueryInput(), nextEntry(), p_geomSvc, Hit::pos, query, readQIE, readTargetPos, readTriggerHits, row, runID, SRawEvent::setEventInfo(), SRawEvent::setIntensity(), Hit::setInTime(), SRawEvent::setRFID(), SRawEvent::setTargetPos(), SRawEvent::setTriggerBits(), SRawEvent::setTurnID(), spillID, and Hit::tdcTime.
Referenced by getLatestEvt(), and getNextEvent().
float MySQLSvc::getFloat (int id, float default_val = 0.)
Definition at line 1346 of file MySQLSvc.cxx.
References NULL, and row.
Referenced by getEvent(), and getEventHeader().
TSQLServer* MySQLSvc::getInputServer () inline
Definition at line 47 of file MySQLSvc.h.
References inputServer.
int MySQLSvc::getInt (int id, int default_val = 0)
Definition at line 1329 of file MySQLSvc.cxx.
References NULL, and row.
Referenced by getEvent(), getEventHeader(), getLatestEvt(), getMCGenInfo(), getNEvents(), and initReader().
bool MySQLSvc::getLatestEvt (SRawEvent * rawEvent)
Definition at line 265 of file MySQLSvc.cxx.
References SRawEvent::clear(), getEvent(), getEventHeader(), getInt(), isEventLoaded(), makeQueryInput(), nextEntry(), and query.
bool MySQLSvc::getMCGenInfo (SRawMCEvent * mcEvent, int eventID)
Definition at line 555 of file MySQLSvc.cxx.
References SRawMCEvent::costh, getDouble(), getInt(), makeQueryInput(), SRawMCEvent::mass, nextEntry(), SRawMCEvent::nHits, SRawMCEvent::p_station1, SRawMCEvent::p_station2, SRawMCEvent::p_station3, SRawMCEvent::p_station4, SRawMCEvent::p_stationH1, SRawMCEvent::p_stationH2, SRawMCEvent::p_stationH3, SRawMCEvent::p_stationH4, SRawMCEvent::p_vertex, SRawMCEvent::pT, query, readTrackPos, runID, SRawEvent::setEventInfo(), spillID, SRawMCEvent::v_station1, SRawMCEvent::v_station2, SRawMCEvent::v_station3, SRawMCEvent::v_station4, SRawMCEvent::v_stationH1, SRawMCEvent::v_stationH2, SRawMCEvent::v_stationH3, SRawMCEvent::v_stationH4, SRawMCEvent::vtx, SRawMCEvent::weight, SRawMCEvent::x1, SRawMCEvent::x2, and SRawMCEvent::xF.
Referenced by getNextEvent().
std::string MySQLSvc::getMySQLEventSelection () const
Get WHERE clause to add to MySQL query to select the event subrange (if any)
Definition at line 850 of file MySQLSvc.cxx.
References JobOptsSvc::instance(), JobOptsSvc::m_firstEvent, JobOptsSvc::m_nEvents, and JobOptsSvc::ProcessAllEvents().
Referenced by MySQLSvc().
int MySQLSvc::getNEvents (int event_hi = -1, int event_lo = 0)
Definition at line 423 of file MySQLSvc.cxx.
References eventIDs, eventIDs_loaded, eventQuery, getInt(), JobOptsSvc::instance(), makeQueryInput(), nextEntry(), query, and subsetEventString.
Referenced by getNEventsFast(), and main().
int MySQLSvc::getNEventsFast (int event_hi = -1, int event_lo = 0)
Definition at line 1272 of file MySQLSvc.cxx.
References getNEvents(), and nEvents.
Referenced by main().
bool MySQLSvc::getNextEvent (SRawEvent * rawEvent)
Definition at line 298 of file MySQLSvc.cxx.
References SRawEvent::clear(), eventIDs, getEvent(), getEventHeader(), and index_eventID.
Referenced by main().
bool MySQLSvc::getNextEvent (SRawMCEvent * rawEvent)
Definition at line 310 of file MySQLSvc.cxx.
References SRawEvent::clear(), eventIDs, getEvent(), getEventHeader(), getMCGenInfo(), and index_eventID.
TSQLServer* MySQLSvc::getOutputServer () inline
Definition at line 48 of file MySQLSvc.h.
References outputServer.
Referenced by main().
bool MySQLSvc::getRandomEvt (SRawEvent * rawEvent)
Definition at line 284 of file MySQLSvc.cxx.
std::string MySQLSvc::getString (int id, std::string default_val = "")
Definition at line 1366 of file MySQLSvc.cxx.
References NULL, and row.
Referenced by initReader().
std::string MySQLSvc::getSubsetTableSuffix () const
Get the suffix to add to end of intermediate event subrange tables (if any)
Definition at line 833 of file MySQLSvc.cxx.
References JobOptsSvc::instance(), JobOptsSvc::m_firstEvent, JobOptsSvc::m_nEvents, and JobOptsSvc::ProcessAllEvents().
Referenced by MySQLSvc().
std::string MySQLSvc::getTableDefinition (const TString tableType) const
Get the definition of fields, keys, indices for a table (kTrack, kDimuon, or kTrackHit)
Definition at line 867 of file MySQLSvc.cxx.
Referenced by initBakWriter(), and initWriter().
bool MySQLSvc::initBakWriter ()
Definition at line 742 of file MySQLSvc.cxx.
References getTableDefinition(), outputSchema, outputServer, query, subsetEventString, subsetTableSuffix, and updateAlignment::tableNames.
Referenced by main().
bool MySQLSvc::initReader ()
Definition at line 161 of file MySQLSvc.cxx.
References TriggerAnalyzer::buildTriggerTree(), getInt(), getString(), TriggerAnalyzer::init(), inputSchema, inputServer, makeQueryInput(), nextEntry(), p_triggerAna, query, readQIE, readTargetPos, readTrackPos, readTriggerHits, and setTriggerEmu.
Referenced by main().
bool MySQLSvc::initWriter ()
Definition at line 644 of file MySQLSvc.cxx.
References getTableDefinition(), outputSchema, outputServer, query, res, subsetEventString, subsetTableSuffix, and updateAlignment::tableNames.
Referenced by main().
MySQLSvc * MySQLSvc::instance () static
Definition at line 74 of file MySQLSvc.cxx.
References MySQLSvc(), NULL, and p_mysqlSvc.
Referenced by main().
bool MySQLSvc::isEventLoaded (int eventID) inline
Definition at line 68 of file MySQLSvc.h.
References eventIDs_loaded.
Referenced by getLatestEvt().
bool MySQLSvc::isRunStopped ()
Definition at line 252 of file MySQLSvc.cxx.
References logSchema, makeQueryOutput(), nextEntry(), NULL, query, row, and runID.
int MySQLSvc::makeQueryInput ()
Definition at line 1278 of file MySQLSvc.cxx.
References inputServer, NULL, query, and res.
Referenced by getEvent(), getEventHeader(), getLatestEvt(), getMCGenInfo(), getNEvents(), and initReader().
int MySQLSvc::makeQueryOutput ()
Definition at line 1290 of file MySQLSvc.cxx.
References NULL, outputServer, query, and res.
Referenced by isRunStopped().
bool MySQLSvc::nextEntry ()
Definition at line 1318 of file MySQLSvc.cxx.
References NULL, res, and row.
Referenced by getEvent(), getEventHeader(), getLatestEvt(), getMCGenInfo(), getNEvents(), initReader(), and isRunStopped().
void MySQLSvc::pushToFinalTables (bool dropSubsetTables)
Copy output from intermediate subset tables to final table and delete subset tables (if desired)
Definition at line 1252 of file MySQLSvc.cxx.
References outputServer, subsetTableSuffix, and updateAlignment::tableNames.
void MySQLSvc::resetWriter ()
Definition at line 814 of file MySQLSvc.cxx.
References eventQuery, nDimuons, nTracks, and trackQuery.
Referenced by main().
void MySQLSvc::setInputSchema (std::string schema)
Definition at line 154 of file MySQLSvc.cxx.
References eventIDs, index_eventID, and inputSchema.
Referenced by main().
void MySQLSvc::setLoggingSchema (std::string schema) inline
Definition at line 103 of file MySQLSvc.h.
References logSchema.
void MySQLSvc::setOutputSchema (std::string schema) inline
Definition at line 102 of file MySQLSvc.h.
References outputSchema.
Referenced by main().
void MySQLSvc::setUserPasswd (std::string user_input, std::string passwd_input) inline
Definition at line 51 of file MySQLSvc.h.
References passwd, and user.
Referenced by main().
void MySQLSvc::writeDimuonTable (int dimuonID, SRecDimuon dimuon, TString tableSuffix, int targetPos)
Definition at line 1215 of file MySQLSvc.cxx.
References SRecDimuon::chisq_kf, commitInsertion(), SRecDimuon::costh, dimuonQuery, eventIDs_loaded, SRecDimuon::getVPhoton(), SRecDimuon::isDump(), SRecDimuon::isTarget(), SRecDimuon::isValid(), SRecDimuon::mass, MaxQueryLen, nTracks, SRecDimuon::p_neg, SRecDimuon::p_pos, SRecDimuon::phi, runID, spillID, subsetTableSuffix, eventMixer::targetPos, SRecDimuon::trackID_neg, SRecDimuon::trackID_pos, SRecDimuon::vtx, SRecDimuon::vtx_neg, SRecDimuon::vtx_pos, SRecDimuon::x1, SRecDimuon::x2, and SRecDimuon::xF.
Referenced by writeTrackingRes().
void MySQLSvc::writeEventTable (int eventID, int statusCode, int source1, int source2, TString tableSuffix)
Definition at line 1069 of file MySQLSvc.cxx.
References commitInsertion(), eventQuery, MaxQueryLen, runID, and spillID.
Referenced by writeTrackingRes().
void MySQLSvc::writeInfoTable (TTree * config)
Definition at line 1033 of file MySQLSvc.cxx.
References outputServer, and query.
Referenced by main().
void MySQLSvc::writeTrackHitTable (int trackID, Tracklet * tracklet)
Definition at line 1165 of file MySQLSvc.cxx.
References commitInsertion(), detectorID, Hit::detectorID, Hit::driftDistance, Hit::elementID, eventIDs_loaded, TriggerRoad::getDetectorID(), GeomSvc::getDetectorName(), TriggerRoad::getElementID(), Tracklet::getExpPositionW(), GeomSvc::getMeasurement(), TriggerRoad::getNElements(), SignedHit::hit, hitQuery, PropSegment::hits, Tracklet::hits, Hit::index, MaxQueryLen, p_geomSvc, res, Tracklet::residual, runID, Tracklet::seg_x, Tracklet::seg_y, SignedHit::sign, spillID, subsetTableSuffix, and Hit::tdcTime.
Referenced by writeTrackingRes().
void MySQLSvc::writeTrackingRes (TString tableSuffix, SRecEvent * recEvent, TClonesArray * tracklets = NULL)
Definition at line 997 of file MySQLSvc.cxx.
References eventIDs_loaded, SRecEvent::getDimuon(), SRecEvent::getEventID(), SRecEvent::getNDimuons(), SRecEvent::getNTracks(), SRecEvent::getRecStatus(), SRecEvent::getRunID(), SRecEvent::getSourceID1(), SRecEvent::getSourceID2(), SRecEvent::getSpillID(), SRecEvent::getTargetPos(), SRecEvent::getTrack(), nDimuons, nTracks, NULL, runID, spillID, eventMixer::targetPos, writeDimuonTable(), writeEventTable(), writeTrackHitTable(), and writeTrackTable().
Referenced by main().
void MySQLSvc::writeTrackTable (int trackID, SRecTrack * recTrack, TString tableSuffix)
Definition at line 1081 of file MySQLSvc.cxx.
References commitInsertion(), eventIDs_loaded, SRecTrack::getCharge(), SRecTrack::getChisq(), SRecTrack::getChisqDump(), SRecTrack::getChisqTarget(), SRecTrack::getChisqUpstream(), SRecTrack::getDumpMom(), SRecTrack::getDumpPos(), SRecTrack::getExpMomentumFast(), SRecTrack::getExpPositionFast(), SRecTrack::getMomentumVertex(), SRecTrack::getNHits(), SRecTrack::getNHitsInPTX(), SRecTrack::getNHitsInPTY(), SRecTrack::getNHitsInStation(), SRecTrack::getPTSlopeX(), SRecTrack::getPTSlopeY(), SRecTrack::getTargetMom(), SRecTrack::getTargetPos(), SRecTrack::getTriggerRoad(), SRecTrack::getVtxPar(), SRecTrack::getXVertexPos(), SRecTrack::getYVertexPos(), SRecTrack::isKalmanFitted(), MaxQueryLen, runID, spillID, subsetTableSuffix, trackQuery, Z_ST1, and Z_ST3.
Referenced by writeTrackingRes().
Member Data Documentation
TString MySQLSvc::dimuonQuery private
Definition at line 173 of file MySQLSvc.h.
Referenced by finalizeWriter(), and writeDimuonTable().
std::vector<int> MySQLSvc::eventIDs private
Definition at line 159 of file MySQLSvc.h.
Referenced by getNEvents(), getNextEvent(), MySQLSvc(), and setInputSchema().
std::vector<int> MySQLSvc::eventIDs_loaded private
Definition at line 160 of file MySQLSvc.h.
Referenced by getEventHeader(), getNEvents(), isEventLoaded(), writeDimuonTable(), writeTrackHitTable(), writeTrackingRes(), and writeTrackTable().
TString MySQLSvc::eventQuery private
Definition at line 172 of file MySQLSvc.h.
Referenced by finalizeWriter(), getNEvents(), resetWriter(), and writeEventTable().
TString MySQLSvc::hitQuery private
Definition at line 175 of file MySQLSvc.h.
Referenced by finalizeWriter(), and writeTrackHitTable().
int MySQLSvc::index_eventID private
Definition at line 161 of file MySQLSvc.h.
Referenced by getNextEvent(), and setInputSchema().
std::string MySQLSvc::inputSchema private
Definition at line 167 of file MySQLSvc.h.
Referenced by initReader(), MySQLSvc(), and setInputSchema().
TSQLServer* MySQLSvc::inputServer private
Fetch input from this server.
Definition at line 134 of file MySQLSvc.h.
Referenced by connectInput(), connectOutput(), getInputServer(), initReader(), makeQueryInput(), MySQLSvc(), and ~MySQLSvc().
std::string MySQLSvc::logSchema private
Definition at line 169 of file MySQLSvc.h.
Referenced by isRunStopped(), MySQLSvc(), and setLoggingSchema().
int MySQLSvc::nDimuons private
Definition at line 179 of file MySQLSvc.h.
Referenced by MySQLSvc(), resetWriter(), and writeTrackingRes().
int MySQLSvc::nEvents private
Definition at line 156 of file MySQLSvc.h.
Referenced by getNEventsFast(), and MySQLSvc().
int MySQLSvc::nTracks private
Definition at line 178 of file MySQLSvc.h.
Referenced by MySQLSvc(), resetWriter(), writeDimuonTable(), and writeTrackingRes().
std::string MySQLSvc::outputSchema private
Definition at line 168 of file MySQLSvc.h.
Referenced by initBakWriter(), initWriter(), MySQLSvc(), and setOutputSchema().
TSQLServer* MySQLSvc::outputServer private
Write output to this server.
Definition at line 135 of file MySQLSvc.h.
Referenced by commitInsertion(), connectOutput(), getOutputServer(), initBakWriter(), initWriter(), makeQueryOutput(), MySQLSvc(), pushToFinalTables(), writeInfoTable(), and ~MySQLSvc().
GeomSvc* MySQLSvc::p_geomSvc private
Definition at line 128 of file MySQLSvc.h.
Referenced by getEvent(), getEventHeader(), MySQLSvc(), and writeTrackHitTable().
MySQLSvc * MySQLSvc::p_mysqlSvc = NULL static private
Definition at line 121 of file MySQLSvc.h.
Referenced by instance().
TriggerAnalyzer* MySQLSvc::p_triggerAna private
Definition at line 131 of file MySQLSvc.h.
Referenced by getEvent(), initReader(), MySQLSvc(), and ~MySQLSvc().
std::string MySQLSvc::passwd private
Definition at line 125 of file MySQLSvc.h.
Referenced by connectInput(), connectOutput(), MySQLSvc(), and setUserPasswd().
char MySQLSvc::query[2000] private
Definition at line 164 of file MySQLSvc.h.
Referenced by getEvent(), getEventHeader(), getLatestEvt(), getMCGenInfo(), getNEvents(), initBakWriter(), initReader(), initWriter(), isRunStopped(), makeQueryInput(), makeQueryOutput(), and writeInfoTable().
bool MySQLSvc::readQIE private
Definition at line 144 of file MySQLSvc.h.
Referenced by enableQIE(), getEventHeader(), initReader(), and MySQLSvc().
bool MySQLSvc::readTargetPos private
Definition at line 146 of file MySQLSvc.h.
Referenced by enableTargetPos(), getEventHeader(), initReader(), and MySQLSvc().
bool MySQLSvc::readTrackPos private
Definition at line 147 of file MySQLSvc.h.
Referenced by getMCGenInfo(), initReader(), and MySQLSvc().
bool MySQLSvc::readTriggerHits private
Definition at line 145 of file MySQLSvc.h.
Referenced by enableTriggerHits(), getEvent(), getEventHeader(), initReader(), and MySQLSvc().
TSQLResult* MySQLSvc::res private
Definition at line 136 of file MySQLSvc.h.
Referenced by initWriter(), makeQueryInput(), makeQueryOutput(), MySQLSvc(), nextEntry(), writeTrackHitTable(), and ~MySQLSvc().
TRandom MySQLSvc::rndm private
Definition at line 151 of file MySQLSvc.h.
Referenced by MySQLSvc().
TSQLRow* MySQLSvc::row private
Definition at line 137 of file MySQLSvc.h.
Referenced by getDouble(), getEvent(), getEventHeader(), getFloat(), getInt(), getString(), isRunStopped(), MySQLSvc(), nextEntry(), and ~MySQLSvc().
int MySQLSvc::runID private
Definition at line 154 of file MySQLSvc.h.
Referenced by getEventHeader(), getMCGenInfo(), isRunStopped(), MySQLSvc(), writeDimuonTable(), writeEventTable(), writeTrackHitTable(), writeTrackingRes(), and writeTrackTable().
bool MySQLSvc::setTriggerEmu private
Definition at line 148 of file MySQLSvc.h.
Referenced by getEvent(), and initReader().
int MySQLSvc::spillID private
Definition at line 155 of file MySQLSvc.h.
Referenced by getEventHeader(), getMCGenInfo(), MySQLSvc(), writeDimuonTable(), writeEventTable(), writeTrackHitTable(), writeTrackingRes(), and writeTrackTable().
std::string MySQLSvc::subsetEventString private
MySQL string used to select only the events to be processed (e.g. WHERE caluse)
Definition at line 141 of file MySQLSvc.h.
Referenced by getNEvents(), initBakWriter(), initWriter(), and MySQLSvc().
std::string MySQLSvc::subsetTableSuffix private
Append suffix to table names for intermediate event subset tables.
Definition at line 140 of file MySQLSvc.h.
Referenced by initBakWriter(), initWriter(), MySQLSvc(), pushToFinalTables(), writeDimuonTable(), writeTrackHitTable(), and writeTrackTable().
TString MySQLSvc::trackQuery private
Definition at line 174 of file MySQLSvc.h.
Referenced by finalizeWriter(), resetWriter(), and writeTrackTable().
std::string MySQLSvc::user private
Definition at line 124 of file MySQLSvc.h.
Referenced by connectInput(), connectOutput(), MySQLSvc(), and setUserPasswd().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/MySQLSvc.h
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/src/MySQLSvc.cxx