E1039 Software: PHNodeIOManager Class Reference
PHNodeIOManager Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHNodeIOManager.h>
Public Member Functions
PHNodeIOManager ()
PHNodeIOManager (const std::string &, const PHAccessType=PHReadOnly)
PHNodeIOManager (const std::string &, const std::string &, const PHAccessType=PHReadOnly)
PHNodeIOManager (const std::string &, const PHAccessType, const PHTreeType)
virtual ~PHNodeIOManager ()
virtual void closeFile ()
virtual PHBoolean write (PHCompositeNode *)
virtual void print () const
PHBoolean setFile (const std::string &, const std::string &, const PHAccessType=PHReadOnly)
PHCompositeNode * read (PHCompositeNode *=0, size_t=0)
PHBoolean read (size_t requestedEvent)
int readSpecific (size_t requestedEvent, const char *objectName)
void selectObjectToRead (const char *objectName, PHBoolean readit)
PHBoolean isSelected (const char *objectName)
int isFunctional () const
PHBoolean SetCompressionLevel (const int level)
double GetBytesWritten ()
std::map< std::string, TBranch * > * GetBranchMap ()
PHBoolean write (TObject **, const std::string &)
Public Member Functions inherited from PHIOManager
virtual ~PHIOManager ()
std::string getFilename () const
size_t getEventNumber () const
void setEventNumber (const size_t evno)
Private Member Functions
int FillBranchMap ()
PHCompositeNode * reconstructNodeTree (PHCompositeNode *)
PHBoolean readEventFromFile (size_t requestedEvent)
std::string getBranchClassName (TBranch *)
Private Attributes
TFile * file
TTree * tree
std::string TreeName
int bufSize
int split
int accessMode
int CompressionLevel
std::map< std::string, TBranch * > fBranches
std::map< std::string, PHBoolean > objectToRead
int isFunctionalFlag
Additional Inherited Members
Protected Member Functions inherited from PHIOManager
PHIOManager ()
Protected Attributes inherited from PHIOManager
std::string filename
size_t eventNumber
Detailed Description
Definition at line 18 of file PHNodeIOManager.h.
Constructor & Destructor Documentation
PHNodeIOManager() [1/4]
PHNodeIOManager::PHNodeIOManager ()
Definition at line 36 of file PHNodeIOManager.cc.
PHNodeIOManager() [2/4]
PHNodeIOManager::PHNodeIOManager (const std::string & f, const PHAccessType a = PHReadOnly)
Definition at line 47 of file PHNodeIOManager.cc.
References isFunctionalFlag, and setFile().
PHNodeIOManager() [3/4]
PHNodeIOManager::PHNodeIOManager (const std::string & f, const std::string & title, const PHAccessType a = PHReadOnly)
Definition at line 57 of file PHNodeIOManager.cc.
References isFunctionalFlag, and setFile().
PHNodeIOManager() [4/4]
PHNodeIOManager::PHNodeIOManager (const std::string & f, const PHAccessType a, const PHTreeType treeindex)
Definition at line 67 of file PHNodeIOManager.cc.
References isFunctionalFlag, PHEventTree, setFile(), and TreeName.
~PHNodeIOManager()
PHNodeIOManager::~PHNodeIOManager () virtual
Definition at line 83 of file PHNodeIOManager.cc.
References closeFile(), and file.
Member Function Documentation
closeFile()
void PHNodeIOManager::closeFile () virtual
Implements PHIOManager.
Definition at line 94 of file PHNodeIOManager.cc.
References accessMode, file, PHUpdate, and PHWrite.
Referenced by setFile(), and ~PHNodeIOManager().
FillBranchMap()
int PHNodeIOManager::FillBranchMap () private
Definition at line 618 of file PHNodeIOManager.cc.
References fBranches, file, PHIOManager::filename, PHWHERE, and TreeName.
Referenced by GetBranchMap(), and isFunctional().
getBranchClassName()
string PHNodeIOManager::getBranchClassName (TBranch * branch) private
Definition at line 289 of file PHNodeIOManager.cc.
References PHWHERE.
Referenced by isFunctional(), and reconstructNodeTree().
GetBranchMap()
map< string, TBranch * > * PHNodeIOManager::GetBranchMap ()
Definition at line 611 of file PHNodeIOManager.cc.
References fBranches, and FillBranchMap().
Referenced by isFunctional(), and Fun4AllDstInputManager::ReadNextEventSyncObject().
GetBytesWritten()
double PHNodeIOManager::GetBytesWritten ()
Definition at line 604 of file PHNodeIOManager.cc.
References file.
Referenced by isFunctional().
isFunctional()
int PHNodeIOManager::isFunctional () const inline
Definition at line 37 of file PHNodeIOManager.h.
References FillBranchMap(), getBranchClassName(), GetBranchMap(), GetBytesWritten(), isFunctionalFlag, readEventFromFile(), reconstructNodeTree(), SetCompressionLevel(), and write().
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllDstOutputManager::Fun4AllDstOutputManager(), and Fun4AllDstOutputManager::outfileopen().
isSelected()
PHBoolean PHNodeIOManager::isSelected (const char * objectName)
Definition at line 574 of file PHNodeIOManager.cc.
References False, fBranches, and True.
print()
void PHNodeIOManager::print () const virtual
Implements PHIOManager.
Definition at line 263 of file PHNodeIOManager.cc.
References accessMode, file, PHIOManager::filename, objectToRead, PHReadOnly, and tree.
Referenced by Fun4AllDstInputManager::fileopen(), and Fun4AllDstInputManager::Print().
read() [1/2]
PHCompositeNode * PHNodeIOManager::read (PHCompositeNode * topNode = 0, size_t requestedEvent = 0)
Definition at line 240 of file PHNodeIOManager.cc.
References readEventFromFile(), reconstructNodeTree(), and tree.
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllDstInputManager::ReadNextEventSyncObject(), Fun4AllDstInputManager::run(), and Fun4AllDstInputManager::SyncIt().
read() [2/2]
PHBoolean PHNodeIOManager::read (size_t requestedEvent)
Definition at line 227 of file PHNodeIOManager.cc.
References False, readEventFromFile(), and True.
readEventFromFile()
PHBoolean PHNodeIOManager::readEventFromFile (size_t requestedEvent) private
Definition at line 325 of file PHNodeIOManager.cc.
References PHIOManager::eventNumber, False, file, PHError, PHMessage(), PHWHERE, tree, and True.
Referenced by isFunctional(), and read().
readSpecific()
int PHNodeIOManager::readSpecific (size_t requestedEvent, const char * objectName)
Definition at line 374 of file PHNodeIOManager.cc.
References fBranches, PHError, and PHMessage().
Referenced by Fun4AllDstInputManager::ReadNextEventSyncObject().
reconstructNodeTree()
PHCompositeNode * PHNodeIOManager::reconstructNodeTree (PHCompositeNode * topNode) private
Definition at line 399 of file PHNodeIOManager.cc.
References PHNodeIterator::addNode(), phooldefs::branchpathdelim, PHNodeIterator::cd(), PHDataNode< T >::data, fBranches, file, PHIOManager::filename, PHNodeIterator::findFirst(), getBranchClassName(), PHDataNode< T >::getData(), NULL, objectToRead, PHWHERE, PHNode::setObjectType(), tree, and TreeName.
Referenced by isFunctional(), and read().
selectObjectToRead()
void PHNodeIOManager::selectObjectToRead (const char * objectName, PHBoolean readit)
Definition at line 554 of file PHNodeIOManager.cc.
References objectToRead, and tree.
Referenced by Fun4AllDstInputManager::setBranches(), setFile(), and Fun4AllDstInputManager::setSyncBranches().
SetCompressionLevel()
PHBoolean PHNodeIOManager::SetCompressionLevel (const int level)
Definition at line 588 of file PHNodeIOManager.cc.
References CompressionLevel, False, file, and True.
Referenced by Fun4AllDstOutputManager::Fun4AllDstOutputManager(), isFunctional(), and Fun4AllDstOutputManager::outfileopen().
setFile()
PHBoolean PHNodeIOManager::setFile (const std::string & f, const std::string & title, const PHAccessType a = PHReadOnly)
Definition at line 107 of file PHNodeIOManager.cc.
References accessMode, bufSize, closeFile(), CompressionLevel, False, file, PHIOManager::filename, PHReadOnly, PHUpdate, PHWrite, selectObjectToRead(), split, tree, TreeName, and True.
Referenced by PHNodeIOManager().
write() [1/2]
PHBoolean PHNodeIOManager::write (PHCompositeNode * topNode) virtual
Implements PHIOManager.
Definition at line 167 of file PHNodeIOManager.cc.
References PHIOManager::eventNumber, False, file, tree, True, and PHCompositeNode::write().
Referenced by isFunctional(), Fun4AllDstOutputManager::Write(), PHIODataNode< T >::write(), and Fun4AllDstOutputManager::WriteNode().
write() [2/2]
PHBoolean PHNodeIOManager::write (TObject ** data, const std::string & path)
Definition at line 190 of file PHNodeIOManager.cc.
References PHObject::BufferSize(), bufSize, False, file, split, PHObject::SplitLevel(), tree, and True.
Member Data Documentation
accessMode
int PHNodeIOManager::accessMode private
Definition at line 55 of file PHNodeIOManager.h.
Referenced by closeFile(), print(), and setFile().
bufSize
int PHNodeIOManager::bufSize private
Definition at line 53 of file PHNodeIOManager.h.
Referenced by setFile(), and write().
CompressionLevel
int PHNodeIOManager::CompressionLevel private
Definition at line 56 of file PHNodeIOManager.h.
Referenced by SetCompressionLevel(), and setFile().
fBranches
std::map<std::string,TBranch*> PHNodeIOManager::fBranches private
Definition at line 57 of file PHNodeIOManager.h.
Referenced by FillBranchMap(), GetBranchMap(), isSelected(), readSpecific(), and reconstructNodeTree().
file
TFile* PHNodeIOManager::file private
Definition at line 50 of file PHNodeIOManager.h.
Referenced by closeFile(), FillBranchMap(), GetBytesWritten(), print(), readEventFromFile(), reconstructNodeTree(), SetCompressionLevel(), setFile(), write(), and ~PHNodeIOManager().
isFunctionalFlag
int PHNodeIOManager::isFunctionalFlag private
Definition at line 60 of file PHNodeIOManager.h.
Referenced by isFunctional(), and PHNodeIOManager().
objectToRead
std::map<std::string,PHBoolean> PHNodeIOManager::objectToRead private
Definition at line 58 of file PHNodeIOManager.h.
Referenced by print(), reconstructNodeTree(), and selectObjectToRead().
split
int PHNodeIOManager::split private
Definition at line 54 of file PHNodeIOManager.h.
Referenced by setFile(), and write().
tree
TTree* PHNodeIOManager::tree private
Definition at line 51 of file PHNodeIOManager.h.
Referenced by print(), read(), readEventFromFile(), reconstructNodeTree(), selectObjectToRead(), setFile(), and write().
TreeName
std::string PHNodeIOManager::TreeName private
Definition at line 52 of file PHNodeIOManager.h.
Referenced by FillBranchMap(), PHNodeIOManager(), reconstructNodeTree(), and setFile().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHNodeIOManager.h
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHNodeIOManager.cc