Class Reference for E1039 Core & Analysis Software: UtilHodo Namespace Reference
UtilHodo Namespace Reference
Classes
struct Track1D
struct Track2D
Functions
bool IsHodoX (const std::string det_name)
bool IsHodoY (const std::string det_name)
bool IsHodoX (const int det_id)
bool IsHodoY (const int det_id)
int GetPlanePos (const int det, double &x, double &y, double &z)
int GetElementPos (const int det, const int ele, double &x, double &y, double &z)
Function Documentation
GetElementPos()
int UtilHodo::GetElementPos (const int det, const int ele, double & x, double & y, double & z)
Definition at line 38 of file UtilHodo.cc.
References GeomSvc::getPlaneNElements(), GetPlanePos(), GeomSvc::getPlaneSpacing(), GeomSvc::instance(), and IsHodoX().
Referenced by UtilHodo::Track1D::DoTracking().
GetPlanePos()
int UtilHodo::GetPlanePos (const int det, double & x, double & y, double & z)
Definition at line 29 of file UtilHodo.cc.
References GeomSvc::getPlaneCenterX(), GeomSvc::getPlaneCenterY(), GeomSvc::getPlaneCenterZ(), and GeomSvc::instance().
Referenced by GetElementPos().
IsHodoX() [1/2]
bool UtilHodo::IsHodoX (const int det_id)
Definition at line 19 of file UtilHodo.cc.
References GeomSvc::instance().
Referenced by GetElementPos(), and IsHodoY().
IsHodoX() [2/2]
bool UtilHodo::IsHodoX (const std::string det_name)
Definition at line 9 of file UtilHodo.cc.
Referenced by UtilHodo::Track2D::AddHit().
IsHodoY() [1/2]
bool UtilHodo::IsHodoY (const int det_id)
Definition at line 24 of file UtilHodo.cc.
References IsHodoX().
IsHodoY() [2/2]
bool UtilHodo::IsHodoY (const std::string det_name)
Definition at line 14 of file UtilHodo.cc.
References IsHodoX().