SeaQuest Offline Software: SRecEvent Class Reference
SRecEvent Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/inc/SRecEvent.h>
Public Member Functions
SRecEvent ()
void setEventInfo (SRawEvent *rawEvent)
Set/Get event info.
void setEventInfo (int runID, int spillID, int eventID)
void setTargetPos (int targetPos)
void setRecStatus (int status)
void setRawEvent (SRawEvent *rawEvent)
directly setup everything by raw event
bool isTriggeredBy (Int_t trigger)
Trigger util.
Int_t getRunID ()
Int_t getSpillID ()
Int_t getEventID ()
Int_t getTargetPos ()
Int_t getTriggerBits ()
Int_t getRecStatus ()
Int_t getLocalID (Int_t hitID)
void setEventSource (Int_t id1, Int_t id2)
Int_t getSourceID1 ()
Int_t getSourceID2 ()
Int_t getNTracks ()
Get tracks.
SRecTrack & getTrack (Int_t i)
std::vector< Int_t > getChargedTrackIDs (Int_t charge)
Get track IDs.
Int_t getNDimuons ()
Get dimuons.
SRecDimuon getDimuon (Int_t i)
void insertTrack (SRecTrack trk)
Insert tracks.
void reIndex ()
void insertDimuon (SRecDimuon dimuon)
Insert dimuon.
void clear ()
Clear everything.
Private Attributes
Short_t fRecStatus
Reconstruction status.
Int_t fRunID
Basic event info.
Int_t fSpillID
Int_t fEventID
Int_t fTargetPos
Target position.
Int_t fTriggerBits
Trigger bit.
std::vector< SRecTrack > fAllTracks
Container of SRecTrack.
std::vector< SRecDimuon > fDimuons
Dimuons reconstructed.
std::map< Int_t, Int_t > fLocalID
Mapping of hitID to local container ID in SRawEvent.
Int_t fSource1
Int_t fSource2
Detailed Description
Definition at line 286 of file SRecEvent.h.
Constructor & Destructor Documentation
SRecEvent::SRecEvent ()
Definition at line 571 of file SRecEvent.cxx.
References clear(), fEventID, fRecStatus, fRunID, fSource1, fSource2, and fSpillID.
Member Function Documentation
void SRecEvent::clear ()
Clear everything.
Definition at line 623 of file SRecEvent.cxx.
References fAllTracks, fDimuons, fLocalID, and fRecStatus.
Referenced by main(), and SRecEvent().
std::vector< Int_t > SRecEvent::getChargedTrackIDs (Int_t charge)
Get track IDs.
Definition at line 606 of file SRecEvent.cxx.
References fAllTracks, and getNTracks().
Referenced by VertexFit::setRecEvent().
SRecDimuon SRecEvent::getDimuon (Int_t i) inline
Definition at line 326 of file SRecEvent.h.
References fDimuons.
Referenced by MySQLSvc::writeTrackingRes().
Int_t SRecEvent::getEventID () inline
Definition at line 305 of file SRecEvent.h.
References fEventID.
Referenced by main(), VertexFit::setRecEvent(), and MySQLSvc::writeTrackingRes().
Int_t SRecEvent::getLocalID (Int_t hitID) inline
Definition at line 310 of file SRecEvent.h.
References fLocalID.
Referenced by SMillepede::addTrack(), and KalmanTrack::KalmanTrack().
Int_t SRecEvent::getNDimuons () inline
Get dimuons.
Definition at line 325 of file SRecEvent.h.
References fDimuons.
Referenced by main(), VertexFit::setRecEvent(), and MySQLSvc::writeTrackingRes().
Int_t SRecEvent::getNTracks () inline
Get tracks.
Definition at line 318 of file SRecEvent.h.
References fAllTracks.
Referenced by getChargedTrackIDs(), main(), SMillepede::setEvent(), and MySQLSvc::writeTrackingRes().
Int_t SRecEvent::getRecStatus () inline
Definition at line 308 of file SRecEvent.h.
References fRecStatus.
Referenced by MySQLSvc::writeTrackingRes().
Int_t SRecEvent::getRunID () inline
Definition at line 303 of file SRecEvent.h.
References fRunID.
Referenced by VertexFit::setRecEvent(), and MySQLSvc::writeTrackingRes().
Int_t SRecEvent::getSourceID1 () inline
Definition at line 314 of file SRecEvent.h.
References fSource1.
Referenced by MySQLSvc::writeTrackingRes().
Int_t SRecEvent::getSourceID2 () inline
Definition at line 315 of file SRecEvent.h.
References fSource2.
Referenced by MySQLSvc::writeTrackingRes().
Int_t SRecEvent::getSpillID () inline
Definition at line 304 of file SRecEvent.h.
References fSpillID.
Referenced by MySQLSvc::writeTrackingRes().
Int_t SRecEvent::getTargetPos () inline
Definition at line 306 of file SRecEvent.h.
References fTargetPos.
Referenced by main(), VertexFit::setRecEvent(), and MySQLSvc::writeTrackingRes().
SRecTrack& SRecEvent::getTrack (Int_t i) inline
Definition at line 319 of file SRecEvent.h.
References fAllTracks.
Referenced by main(), SMillepede::setEvent(), VertexFit::setRecEvent(), and MySQLSvc::writeTrackingRes().
Int_t SRecEvent::getTriggerBits () inline
Definition at line 307 of file SRecEvent.h.
References fTriggerBits.
void SRecEvent::insertDimuon (SRecDimuon dimuon) inline
Insert dimuon.
Definition at line 333 of file SRecEvent.h.
References fDimuons.
Referenced by VertexFit::setRecEvent().
void SRecEvent::insertTrack (SRecTrack trk) inline
Insert tracks.
Definition at line 329 of file SRecEvent.h.
References fAllTracks.
Referenced by main().
bool SRecEvent::isTriggeredBy (Int_t trigger) inline
Trigger util.
Definition at line 301 of file SRecEvent.h.
References fTriggerBits.
Referenced by main().
void SRecEvent::reIndex () inline
Definition at line 330 of file SRecEvent.h.
References fAllTracks.
void SRecEvent::setEventInfo (SRawEvent * rawEvent)
Set/Get event info.
Definition at line 596 of file SRecEvent.cxx.
References fEventID, fRunID, fSpillID, fTargetPos, fTriggerBits, SRawEvent::getEventID(), SRawEvent::getRunID(), SRawEvent::getSpillID(), SRawEvent::getTargetPos(), and SRawEvent::getTriggerBits().
Referenced by main(), and setRawEvent().
void SRecEvent::setEventInfo (int runID, int spillID, int eventID) inline
Definition at line 293 of file SRecEvent.h.
References fEventID, fRunID, fSpillID, and longJobManager::runID.
void SRecEvent::setEventSource (Int_t id1, Int_t id2) inline
Definition at line 313 of file SRecEvent.h.
References fSource1, and fSource2.
Referenced by main().
void SRecEvent::setRawEvent (SRawEvent * rawEvent)
directly setup everything by raw event
Definition at line 584 of file SRecEvent.cxx.
References fAllTracks, fLocalID, SRawEvent::getHit(), SRawEvent::getNHitsAll(), Hit::index, and setEventInfo().
Referenced by main().
void SRecEvent::setRecStatus (int status) inline
Definition at line 295 of file SRecEvent.h.
References fRecStatus, and qdel::status.
Referenced by main().
void SRecEvent::setTargetPos (int targetPos) inline
Definition at line 294 of file SRecEvent.h.
References fTargetPos, and eventMixer::targetPos.
Referenced by main().
Member Data Documentation
std::vector<SRecTrack> SRecEvent::fAllTracks private
Container of SRecTrack.
Definition at line 354 of file SRecEvent.h.
Referenced by clear(), getChargedTrackIDs(), getNTracks(), getTrack(), insertTrack(), reIndex(), and setRawEvent().
std::vector<SRecDimuon> SRecEvent::fDimuons private
Dimuons reconstructed.
Definition at line 357 of file SRecEvent.h.
Referenced by clear(), getDimuon(), getNDimuons(), and insertDimuon().
Int_t SRecEvent::fEventID private
Definition at line 345 of file SRecEvent.h.
Referenced by getEventID(), setEventInfo(), and SRecEvent().
std::map<Int_t, Int_t> SRecEvent::fLocalID private
Mapping of hitID to local container ID in SRawEvent.
Definition at line 360 of file SRecEvent.h.
Referenced by clear(), getLocalID(), and setRawEvent().
Short_t SRecEvent::fRecStatus private
Reconstruction status.
Definition at line 340 of file SRecEvent.h.
Referenced by clear(), getRecStatus(), setRecStatus(), and SRecEvent().
Int_t SRecEvent::fRunID private
Basic event info.
Definition at line 343 of file SRecEvent.h.
Referenced by getRunID(), setEventInfo(), and SRecEvent().
Int_t SRecEvent::fSource1 private
Definition at line 363 of file SRecEvent.h.
Referenced by getSourceID1(), setEventSource(), and SRecEvent().
Int_t SRecEvent::fSource2 private
Definition at line 364 of file SRecEvent.h.
Referenced by getSourceID2(), setEventSource(), and SRecEvent().
Int_t SRecEvent::fSpillID private
Definition at line 344 of file SRecEvent.h.
Referenced by getSpillID(), setEventInfo(), and SRecEvent().
Int_t SRecEvent::fTargetPos private
Target position.
Definition at line 348 of file SRecEvent.h.
Referenced by getTargetPos(), setEventInfo(), and setTargetPos().
Int_t SRecEvent::fTriggerBits private
Trigger bit.
Definition at line 351 of file SRecEvent.h.
Referenced by getTriggerBits(), isTriggeredBy(), and setEventInfo().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/inc/SRecEvent.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/src/SRecEvent.cxx