Class Reference for E1039 Core & Analysis Software: PHG4ParticleGun Class Reference
PHG4ParticleGun Class Reference
[Obsolete] A simple event generator.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4ParticleGun.h>
Public Member Functions
PHG4ParticleGun (const std::string &name="PGUN")
virtual ~PHG4ParticleGun ()
virtual int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
TF2 * get_beam_profile () const
void set_beam_profile (TF2 *beamProfile)
void enableLegacyVtxGen ()
Enable legacy vertex gen.
Public Member Functions inherited from PHG4ParticleGeneratorBase
virtual ~PHG4ParticleGeneratorBase ()
virtual void set_name (const std::string &particle="proton")
virtual void set_pid (const int pid)
virtual void set_mom (const double x, const double y, const double z)
virtual void set_vtx (const double x, const double y, const double z)
virtual void set_t0 (const double t)
virtual double get_vtx_x () const
virtual double get_vtx_y () const
virtual double get_vtx_z () const
virtual double get_t0 () const
virtual void Print (const std::string &what="ALL") const
virtual void AddParticle (const std::string &particle, const double x, const double y, const double z)
virtual void AddParticle (const int pid, const double x, const double y, const double z)
virtual void Embed (const int i=1)
virtual int ReuseExistingVertex (PHCompositeNode *topNode)
int get_reuse_existing_vertex () const
void set_reuse_existing_vertex (const int i=1)
void set_seed (const unsigned int iseed)
unsigned int get_seed () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
TF2 * _beam_profile
bool _legacy_vertexgenerator
SQPrimaryVertexGen * _vertexGen
Protected Attributes inherited from PHG4ParticleGeneratorBase
int embedflag
int reuse_existing_vertex
double vtx_x
double vtx_y
double vtx_z
double t0
std::vector< PHG4Particle * > particlelist
unsigned int seed
gsl_rng * RandomGenerator
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from PHG4ParticleGeneratorBase
PHG4ParticleGeneratorBase (const std::string &name="GENERATORBASE")
int get_pdgcode (const std::string &name) const
std::string get_pdgname (const int pdgcode) const
double get_mass (const int pdgcode) const
void CheckAndCreateParticleVector ()
void SetParticleId (PHG4Particle *particle, PHG4InEvent *ineve)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Detailed Description
[Obsolete] A simple event generator.
It generates events that contain a single particle. You had better use PHG4SimpleEventGenerator since it is upward compatible.
Definition at line 17 of file PHG4ParticleGun.h.
Constructor & Destructor Documentation
PHG4ParticleGun()
PHG4ParticleGun::PHG4ParticleGun (const std::string & name = "PGUN")
Definition at line 23 of file PHG4ParticleGun.cc.
References _vertexGen.
~PHG4ParticleGun()
PHG4ParticleGun::~PHG4ParticleGun () virtual
Definition at line 33 of file PHG4ParticleGun.cc.
References _beam_profile, and _vertexGen.
Member Function Documentation
enableLegacyVtxGen()
void PHG4ParticleGun::enableLegacyVtxGen () inline
Enable legacy vertex gen.
Definition at line 38 of file PHG4ParticleGun.h.
References _legacy_vertexgenerator.
get_beam_profile()
TF2* PHG4ParticleGun::get_beam_profile () const inline
Definition at line 29 of file PHG4ParticleGun.h.
References _beam_profile.
InitRun()
int PHG4ParticleGun::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 40 of file PHG4ParticleGun.cc.
References _vertexGen, SQPrimaryVertexGen::InitRun(), and PHG4ParticleGeneratorBase::InitRun().
process_event()
int PHG4ParticleGun::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
using vertex generated by E906 legacy generator
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 48 of file PHG4ParticleGun.cc.
References _beam_profile, _legacy_vertexgenerator, _vertexGen, PHG4InEvent::AddParticle(), PHG4InEvent::AddVtx(), SQPrimaryVertexGen::generateVertex(), PHG4InEvent::identify(), PHG4ParticleGeneratorBase::particlelist, PHG4ParticleGeneratorBase::ReuseExistingVertex(), PHG4ParticleGeneratorBase::SetParticleId(), PHG4ParticleGeneratorBase::t0, Fun4AllBase::verbosity, PHG4ParticleGeneratorBase::vtx_x, PHG4ParticleGeneratorBase::vtx_y, and PHG4ParticleGeneratorBase::vtx_z.
set_beam_profile()
void PHG4ParticleGun::set_beam_profile (TF2 * beamProfile) inline
Definition at line 33 of file PHG4ParticleGun.h.
References _beam_profile.
Member Data Documentation
_beam_profile
TF2* PHG4ParticleGun::_beam_profile protected
Definition at line 42 of file PHG4ParticleGun.h.
Referenced by get_beam_profile(), process_event(), set_beam_profile(), and ~PHG4ParticleGun().
_legacy_vertexgenerator
bool PHG4ParticleGun::_legacy_vertexgenerator protected
Definition at line 44 of file PHG4ParticleGun.h.
Referenced by enableLegacyVtxGen(), and process_event().
_vertexGen
SQPrimaryVertexGen* PHG4ParticleGun::_vertexGen protected
Definition at line 45 of file PHG4ParticleGun.h.
Referenced by InitRun(), PHG4ParticleGun(), process_event(), and ~PHG4ParticleGun().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4ParticleGun.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4ParticleGun.cc