E1039 Software: /home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHGenFitPkg/Example/minimumTestPHGenFit.cc File Reference
minimumTestPHGenFit.cc File Reference
Minimum program to demonstrate the usage of PHGenFit.
#include <vector>
#include <TVector3.h>
#include <TMatrixDSym.h>
#include <GenFit/AbsTrackRep.h>
#include <GenFit/RKTrackRep.h>
#include <GenFit/StateOnPlane.h>
#include <phgenfit/Fitter.h>
#include <phgenfit/Track.h>
#include <phgenfit/Measurement.h>
#include <phgenfit/PlanarMeasurement.h>
#include <phgenfit/SpacepointMeasurement.h>
#include <phfield/PHFieldUtility.h>
Macros
#define LogDEBUG std::cout<<"DEBUG: "<<__LINE__<<"\n"
Functions
void get_seed (TVector3 &seed_pos, TVector3 &seed_mom, TMatrixDSym &seed_cov)
std::vector< TVector3 > get_raw_measurements ()
int main (int argc, char **argv)
Detailed Description
Minimum program to demonstrate the usage of PHGenFit.
Author
Haiwang Yu yuhw@.nosp@m.nmsu.nosp@m..edu
Definition in file minimumTestPHGenFit.cc.
Macro Definition Documentation
LogDEBUG
#define LogDEBUG std::cout<<"DEBUG: "<<__LINE__<<"\n"
Definition at line 28 of file minimumTestPHGenFit.cc.
Function Documentation
get_raw_measurements()
std::vector<TVector3> get_raw_measurements ()
Definition at line 37 of file minimumTestPHGenFit.cc.
Referenced by main().
get_seed()
void get_seed (TVector3 & seed_pos, TVector3 & seed_mom, TMatrixDSym & seed_cov)
Definition at line 30 of file minimumTestPHGenFit.cc.
Referenced by main().
main()
int main (int argc, char ** argv)
Initiallize Geometry, Field, Fitter
Build TrackRep from particle assumption
Initiallize track with seed from pattern recognition
Create measurements
Add measurements to track
Fit the track
Extrapolate to beam line
Event display, uncomment to use
Comment off if want to keep event display.
Definition at line 47 of file minimumTestPHGenFit.cc.
References PHGenFit::Track::addMeasurements(), PHFieldUtility::BuildFieldMap(), PHFieldUtility::DefaultFieldConfig(), PHGenFit::Track::extrapolateToCylinder(), get_raw_measurements(), get_seed(), and PHGenFit::Fitter::processTrack().