Class Reference for E1039 Core & Analysis Software: ReAnaBG Class Reference
ReAnaBG Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/ReAnaBG.h>
Public Member Functions
ReAnaBG (const std::string label="re_ana_bg")
virtual ~ReAnaBG ()
virtual void Init ()
virtual void End ()
virtual void Analyze ()
RoadMap * GetRoadMapTop ()
RoadMap * GetRoadMapBot ()
Public Member Functions inherited from AnaBG
AnaBG (const std::string label="ana_bg")
virtual ~AnaBG ()
virtual void ReadEvents (const char *fname)
void SetInteCut (const int inte_cut)
int GetInteCut ()
void SetRoads (AnaSignal *ana_signal)
void SetRoads (RoadMap *pos_top, RoadMap *pos_bot, RoadMap *neg_top, RoadMap *neg_bot)
Public Member Functions inherited from AnaBase
virtual ~AnaBase ()
virtual void SetInputTreeName (const std::string name)
virtual void SetInputBranchName (const std::string name)
virtual void ReadEventsFromFileList (const char *fn_list, const int n_max=0)
Protected Member Functions
virtual void ProcessOneEvent ()
Protected Member Functions inherited from AnaBG
void FindAllRoads (const EleList *h1, const EleList *h2, const EleList *h3, const EleList *h4, const int tb, RoadMap *road_map)
void DrawInteMax ()
Protected Member Functions inherited from AnaBase
AnaBase (const std::string label)
Protected Attributes
RoadMap m_road_map_top
RoadMap m_road_map_bot
Protected Attributes inherited from AnaBG
int m_n_evt_used
int m_n_evt_tb
int m_n_evt_fired
TH1 * m_h1_evt_cnt
RoadMap * m_road_map_pos_top
RoadMap * m_road_map_pos_bot
RoadMap * m_road_map_neg_top
RoadMap * m_road_map_neg_bot
BgData * m_bg_data
TFile * m_file_out
TH1 * m_h1_inte_max
int m_inte_cut
Protected Attributes inherited from AnaBase
std::string m_label
std::string m_tree_name
std::string m_branch_name
std::string m_dir_out
std::ofstream m_ofs
Additional Inherited Members
Protected Types inherited from AnaBG
typedef std::vector< int > EleList
Static Protected Attributes inherited from AnaBG
static constexpr double N_RF_PER_SPILL = 186e6
N of RFs per spill.
Detailed Description
Definition at line 5 of file ReAnaBG.h.
Constructor & Destructor Documentation
ReAnaBG::ReAnaBG (const std::string label = "re_ana_bg")
Definition at line 20 of file ReAnaBG.cc.
ReAnaBG::~ReAnaBG () virtual
Definition at line 26 of file ReAnaBG.cc.
Member Function Documentation
void ReAnaBG::Analyze () virtual
Reimplemented from AnaBG.
Definition at line 86 of file ReAnaBG.cc.
References RoadList::Add(), AnaBG::m_h1_evt_cnt, AnaBG::m_n_evt_fired, AnaBG::m_n_evt_tb, AnaBG::m_n_evt_used, AnaBase::m_ofs, m_road_map_bot, m_road_map_top, AnaBG::N_RF_PER_SPILL, UtilRoad::PrintList(), RoadList::Size(), and RoadList::SortByBG().
Referenced by ApplyRoadset2BG().
void ReAnaBG::End () virtual
Reimplemented from AnaBG.
Definition at line 39 of file ReAnaBG.cc.
Referenced by ApplyRoadset2BG().
RoadMap* ReAnaBG::GetRoadMapBot () inline
Definition at line 18 of file ReAnaBG.h.
References m_road_map_bot.
RoadMap* ReAnaBG::GetRoadMapTop () inline
Definition at line 17 of file ReAnaBG.h.
References m_road_map_top.
void ReAnaBG::Init () virtual
Reimplemented from AnaBG.
Definition at line 31 of file ReAnaBG.cc.
References AnaBG::m_road_map_pos_top.
Referenced by ApplyRoadset2BG().
void ReAnaBG::ProcessOneEvent () protected virtual
Reimplemented from AnaBG.
Definition at line 44 of file ReAnaBG.cc.
References RoadMap::AddBG(), RoadMap::ContainEnabled(), AnaBG::FindAllRoads(), BgData::h1b, BgData::h1t, BgData::h2b, BgData::h2t, BgData::h3b, BgData::h3t, BgData::h4b, BgData::h4t, BgData::inte_max, AnaBG::m_bg_data, AnaBG::m_inte_cut, AnaBG::m_n_evt_fired, AnaBG::m_n_evt_tb, AnaBG::m_n_evt_used, m_road_map_bot, AnaBG::m_road_map_neg_bot, AnaBG::m_road_map_neg_top, AnaBG::m_road_map_pos_bot, AnaBG::m_road_map_pos_top, and m_road_map_top.
Member Data Documentation
RoadMap ReAnaBG::m_road_map_bot protected
Definition at line 8 of file ReAnaBG.h.
Referenced by Analyze(), GetRoadMapBot(), and ProcessOneEvent().
RoadMap ReAnaBG::m_road_map_top protected
Definition at line 7 of file ReAnaBG.h.
Referenced by Analyze(), GetRoadMapTop(), and ProcessOneEvent().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/ReAnaBG.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/ReAnaBG.cc