Class Reference for E1039 Core & Analysis Software: Fun4AllTrackQAv1InputManager Class Reference
Fun4AllTrackQAv1InputManager Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaCustomFile/src/Fun4AllTrackQAv1InputManager.h>
Public Member Functions
Fun4AllTrackQAv1InputManager (const std::string &name="DUMMY", const std::string &topnodename="TOP")
virtual ~Fun4AllTrackQAv1InputManager ()
int fileopen (const std::string &filenam)
int fileclose ()
int run (const int nevents=0)
int isOpen ()
void Print (const std::string &what="ALL") const
int ResetEvent ()
int PushBackEvents (const int i)
int GetSyncObject (SyncObject **mastersync)
int SyncIt (const SyncObject *mastersync)
const std::string & GetTreeName () const
void SetTreeName (const std::string &treeName)
Public Member Functions inherited from Fun4AllInputManager
virtual ~Fun4AllInputManager ()
virtual int ReadInRunNode (PHCompositeNode *)
virtual std::string Filename ()
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
virtual int skip (const int nevt)
virtual int NoSyncPushBackEvents (const int)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
int ResetFileList ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int OpenNextFile ()
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
int segment
int isopen
int events_total
int events_thisfile
std::string topNodeName
PHCompositeNode * topNode
SyncObject * syncobject
std::string _tree_name
Input.
TFile * _fin
TTree * _tin
int nHits
int detectorID [500]
int elementID [500]
float driftDistance [500]
SQRun * run_header
Output.
SQEvent * event_header
SQHitVector * hit_vec
Protected Attributes inherited from Fun4AllInputManager
std::vector< SubsysReco * > Subsystems
std::string InputNode
std::string filename
std::string topNodeName
std::list< std::string > filelist
std::list< std::string > filelist_copy
std::list< std::string > filelist_opened
Fun4AllSyncManager * mySyncManager
int repeat
int myrunnumber
int initrun
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 14 of file Fun4AllTrackQAv1InputManager.h.
Constructor & Destructor Documentation
Fun4AllTrackQAv1InputManager()
Fun4AllTrackQAv1InputManager::Fun4AllTrackQAv1InputManager (const std::string & name = "DUMMY", const std::string & topnodename = "TOP")
Definition at line 22 of file Fun4AllTrackQAv1InputManager.cc.
References PHCompositeNode::addNode(), event_header, PHNodeIterator::findFirst(), hit_vec, Fun4AllServer::instance(), run_header, syncobject, topNode, Fun4AllServer::topNode(), and topNodeName.
~Fun4AllTrackQAv1InputManager()
Fun4AllTrackQAv1InputManager::~Fun4AllTrackQAv1InputManager () virtual
Definition at line 62 of file Fun4AllTrackQAv1InputManager.cc.
References fileclose(), isopen, and syncobject.
Member Function Documentation
fileclose()
int Fun4AllTrackQAv1InputManager::fileclose () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 181 of file Fun4AllTrackQAv1InputManager.cc.
References _fin, Fun4AllInputManager::filelist, isopen, Fun4AllBase::Name(), and Fun4AllInputManager::repeat.
Referenced by fileopen(), run(), and ~Fun4AllTrackQAv1InputManager().
fileopen()
int Fun4AllTrackQAv1InputManager::fileopen (const std::string & filenam) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 68 of file Fun4AllTrackQAv1InputManager.cc.
References _fin, _tin, _tree_name, Fun4AllInputManager::AddToFileOpened(), detectorID, driftDistance, elementID, events_thisfile, fileclose(), Fun4AllInputManager::filename, isopen, nHits, segment, Fun4AllBase::ThisName, and Fun4AllBase::verbosity.
Referenced by OpenNextFile().
GetSyncObject()
int Fun4AllTrackQAv1InputManager::GetSyncObject (SyncObject ** mastersync) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 246 of file Fun4AllTrackQAv1InputManager.cc.
References SyncObject::clone(), Fun4AllReturnCodes::SYNC_OK, and syncobject.
GetTreeName()
const std::string& Fun4AllTrackQAv1InputManager::GetTreeName () const inline
Definition at line 30 of file Fun4AllTrackQAv1InputManager.h.
References _tree_name.
isOpen()
int Fun4AllTrackQAv1InputManager::isOpen () inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 22 of file Fun4AllTrackQAv1InputManager.h.
References isopen.
OpenNextFile()
int Fun4AllTrackQAv1InputManager::OpenNextFile () protected
Definition at line 214 of file Fun4AllTrackQAv1InputManager.cc.
References Fun4AllInputManager::filelist, fileopen(), PHWHERE, and Fun4AllBase::verbosity.
Referenced by run().
Print()
void Fun4AllTrackQAv1InputManager::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllInputManager.
Definition at line 207 of file Fun4AllTrackQAv1InputManager.cc.
References Fun4AllInputManager::Print().
PushBackEvents()
int Fun4AllTrackQAv1InputManager::PushBackEvents (const int i) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 239 of file Fun4AllTrackQAv1InputManager.cc.
ResetEvent()
int Fun4AllTrackQAv1InputManager::ResetEvent () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 232 of file Fun4AllTrackQAv1InputManager.cc.
References SyncObject::Reset(), and syncobject.
Referenced by run().
run()
int Fun4AllTrackQAv1InputManager::run (const int nevents = 0) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 105 of file Fun4AllTrackQAv1InputManager.cc.
References _tin, Fun4AllSyncManager::CurrentEvent(), detectorID, driftDistance, elementID, event_header, Fun4AllReturnCodes::EVENT_OK, SyncObject::EventCounter(), SyncObject::EventNumber(), events_thisfile, events_total, fileclose(), Fun4AllInputManager::filelist, hit_vec, isopen, Fun4AllInputManager::mySyncManager, Fun4AllBase::Name(), nHits, OpenNextFile(), Fun4AllSyncManager::PrdfEvents(), SQHitVector::push_back(), Fun4AllInputManager::RejectEvent(), ResetEvent(), run_header, SyncObject::RunNumber(), Fun4AllSyncManager::SegmentNumber(), SyncObject::SegmentNumber(), SQEvent::set_data_quality(), SQHit::set_detector_id(), SQHit::set_drift_distance(), SQHit::set_element_id(), SQEvent::set_event_id(), SQHit::set_hit_id(), SQHit::set_in_time(), SQHit::set_pos(), SQEvent::set_qie_rf_id(), SQEvent::set_qie_rf_intensity(), SQEvent::set_qie_turn_id(), SQRun::set_run_id(), SQEvent::set_run_id(), SQEvent::set_spill_id(), SQHit::set_tdc_time(), SQEvent::set_trigger(), Fun4AllInputManager::SetRunNumber(), syncobject, and Fun4AllBase::verbosity.
SetTreeName()
void Fun4AllTrackQAv1InputManager::SetTreeName (const std::string & treeName) inline
Definition at line 31 of file Fun4AllTrackQAv1InputManager.h.
References _tree_name.
SyncIt()
int Fun4AllTrackQAv1InputManager::SyncIt (const SyncObject * mastersync) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 261 of file Fun4AllTrackQAv1InputManager.cc.
References SyncObject::Different(), Fun4AllBase::Name(), PHWHERE, Fun4AllReturnCodes::SYNC_FAIL, Fun4AllReturnCodes::SYNC_OK, and syncobject.
Member Data Documentation
_fin
TFile* Fun4AllTrackQAv1InputManager::_fin protected
Definition at line 46 of file Fun4AllTrackQAv1InputManager.h.
Referenced by fileclose(), and fileopen().
_tin
TTree* Fun4AllTrackQAv1InputManager::_tin protected
Definition at line 47 of file Fun4AllTrackQAv1InputManager.h.
Referenced by fileopen(), and run().
_tree_name
std::string Fun4AllTrackQAv1InputManager::_tree_name protected
Input.
Definition at line 45 of file Fun4AllTrackQAv1InputManager.h.
Referenced by fileopen(), GetTreeName(), and SetTreeName().
detectorID
int Fun4AllTrackQAv1InputManager::detectorID[500] protected
Definition at line 49 of file Fun4AllTrackQAv1InputManager.h.
Referenced by fileopen(), and run().
driftDistance
float Fun4AllTrackQAv1InputManager::driftDistance[500] protected
Definition at line 51 of file Fun4AllTrackQAv1InputManager.h.
Referenced by fileopen(), and run().
elementID
int Fun4AllTrackQAv1InputManager::elementID[500] protected
Definition at line 50 of file Fun4AllTrackQAv1InputManager.h.
Referenced by fileopen(), and run().
event_header
SQEvent* Fun4AllTrackQAv1InputManager::event_header protected
Definition at line 55 of file Fun4AllTrackQAv1InputManager.h.
Referenced by Fun4AllTrackQAv1InputManager(), and run().
events_thisfile
int Fun4AllTrackQAv1InputManager::events_thisfile protected
Definition at line 39 of file Fun4AllTrackQAv1InputManager.h.
Referenced by fileopen(), and run().
events_total
int Fun4AllTrackQAv1InputManager::events_total protected
Definition at line 38 of file Fun4AllTrackQAv1InputManager.h.
Referenced by run().
hit_vec
SQHitVector* Fun4AllTrackQAv1InputManager::hit_vec protected
Definition at line 56 of file Fun4AllTrackQAv1InputManager.h.
Referenced by Fun4AllTrackQAv1InputManager(), and run().
isopen
int Fun4AllTrackQAv1InputManager::isopen protected
Definition at line 37 of file Fun4AllTrackQAv1InputManager.h.
Referenced by fileclose(), fileopen(), isOpen(), run(), and ~Fun4AllTrackQAv1InputManager().
nHits
int Fun4AllTrackQAv1InputManager::nHits protected
Definition at line 48 of file Fun4AllTrackQAv1InputManager.h.
Referenced by fileopen(), and run().
run_header
SQRun* Fun4AllTrackQAv1InputManager::run_header protected
Output.
Definition at line 54 of file Fun4AllTrackQAv1InputManager.h.
Referenced by Fun4AllTrackQAv1InputManager(), and run().
segment
int Fun4AllTrackQAv1InputManager::segment protected
Definition at line 36 of file Fun4AllTrackQAv1InputManager.h.
Referenced by fileopen().
syncobject
SyncObject* Fun4AllTrackQAv1InputManager::syncobject protected
Definition at line 42 of file Fun4AllTrackQAv1InputManager.h.
Referenced by Fun4AllTrackQAv1InputManager(), GetSyncObject(), ResetEvent(), run(), SyncIt(), and ~Fun4AllTrackQAv1InputManager().
topNode
PHCompositeNode* Fun4AllTrackQAv1InputManager::topNode protected
Definition at line 41 of file Fun4AllTrackQAv1InputManager.h.
Referenced by Fun4AllTrackQAv1InputManager().
topNodeName
std::string Fun4AllTrackQAv1InputManager::topNodeName protected
Definition at line 40 of file Fun4AllTrackQAv1InputManager.h.
Referenced by Fun4AllTrackQAv1InputManager().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaCustomFile/src/Fun4AllTrackQAv1InputManager.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaCustomFile/src/Fun4AllTrackQAv1InputManager.cc