E1039 Software: PHG4CylinderSteppingAction Class Reference
PHG4CylinderSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4CylinderSteppingAction.h>
Public Member Functions
PHG4CylinderSteppingAction (PHG4CylinderDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4CylinderSteppingAction ()
destructor
bool UserSteppingAction (const G4Step *, bool)
stepping action
void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
void SaveLightYield (const int i=1)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4CylinderDetector * detector_
pointer to the detector
const PHParameters * params
PHG4HitContainer * hits_
pointer to hit container
PHG4Hit * hit
PHG4Shower * saveshower
G4VPhysicalVolume * savevolpre
G4VPhysicalVolume * savevolpost
int save_light_yield
int savetrackid
int saveprestepstatus
int savepoststepstatus
int active
int IsBlackHole
int use_g4_steps
double zmin
double zmax
double tmin
double tmax
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 15 of file PHG4CylinderSteppingAction.h.
Constructor & Destructor Documentation
PHG4CylinderSteppingAction()
PHG4CylinderSteppingAction::PHG4CylinderSteppingAction (PHG4CylinderDetector * detector, const PHParameters * parameters)
constructor
Definition at line 25 of file PHG4CylinderSteppingAction.cc.
References zmax, and zmin.
~PHG4CylinderSteppingAction()
PHG4CylinderSteppingAction::~PHG4CylinderSteppingAction () virtual
destructor
Definition at line 50 of file PHG4CylinderSteppingAction.cc.
References hit.
Member Function Documentation
SaveLightYield()
void PHG4CylinderSteppingAction::SaveLightYield (const int i = 1) inline
Definition at line 30 of file PHG4CylinderSteppingAction.h.
References save_light_yield.
SetInterfacePointers()
void PHG4CylinderSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 306 of file PHG4CylinderSteppingAction.cc.
References detector_, PHG4Detector::GetName(), hits_, IsBlackHole, and PHG4CylinderDetector::SuperDetector().
UserSteppingAction()
bool PHG4CylinderSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 60 of file PHG4CylinderSteppingAction.cc.
References active, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4CylinderDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4Hit::get_x(), PHG4Hit::get_z(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), hit, hits_, IsBlackHole, PHG4CylinderDetector::IsInCylinder(), PHG4Hit::Reset(), save_light_yield, savepoststepstatus, saveprestepstatus, saveshower, savetrackid, savevolpost, savevolpre, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_light_yield(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4CylinderDetector::SuperDetector(), tmax, tmin, use_g4_steps, zmax, and zmin.
Member Data Documentation
active
int PHG4CylinderSteppingAction::active private
Definition at line 47 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction().
detector_
PHG4CylinderDetector* PHG4CylinderSteppingAction::detector_ private
pointer to the detector
Definition at line 33 of file PHG4CylinderSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
hit
PHG4Hit* PHG4CylinderSteppingAction::hit private
Definition at line 39 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4CylinderSteppingAction().
hits_
PHG4HitContainer* PHG4CylinderSteppingAction::hits_ private
pointer to hit container
Definition at line 38 of file PHG4CylinderSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
IsBlackHole
int PHG4CylinderSteppingAction::IsBlackHole private
Definition at line 48 of file PHG4CylinderSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
params
const PHParameters* PHG4CylinderSteppingAction::params private
Definition at line 35 of file PHG4CylinderSteppingAction.h.
save_light_yield
int PHG4CylinderSteppingAction::save_light_yield private
Definition at line 43 of file PHG4CylinderSteppingAction.h.
Referenced by SaveLightYield(), and UserSteppingAction().
savepoststepstatus
int PHG4CylinderSteppingAction::savepoststepstatus private
Definition at line 46 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction().
saveprestepstatus
int PHG4CylinderSteppingAction::saveprestepstatus private
Definition at line 45 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction().
saveshower
PHG4Shower* PHG4CylinderSteppingAction::saveshower private
Definition at line 40 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction().
savetrackid
int PHG4CylinderSteppingAction::savetrackid private
Definition at line 44 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction().
savevolpost
G4VPhysicalVolume* PHG4CylinderSteppingAction::savevolpost private
Definition at line 42 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction().
savevolpre
G4VPhysicalVolume* PHG4CylinderSteppingAction::savevolpre private
Definition at line 41 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction().
tmax
double PHG4CylinderSteppingAction::tmax private
Definition at line 53 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction().
tmin
double PHG4CylinderSteppingAction::tmin private
Definition at line 52 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction().
use_g4_steps
int PHG4CylinderSteppingAction::use_g4_steps private
Definition at line 49 of file PHG4CylinderSteppingAction.h.
Referenced by UserSteppingAction().
zmax
double PHG4CylinderSteppingAction::zmax private
Definition at line 51 of file PHG4CylinderSteppingAction.h.
Referenced by PHG4CylinderSteppingAction(), and UserSteppingAction().
zmin
double PHG4CylinderSteppingAction::zmin private
Definition at line 50 of file PHG4CylinderSteppingAction.h.
Referenced by PHG4CylinderSteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4CylinderSteppingAction.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4CylinderSteppingAction.cc