SeaQuest Offline Software: PHG4SiliconTrackerDetector Class Reference
PHG4SiliconTrackerDetector Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerDetector.h>
Public Types
typedef std::vector< std::pair
< int, int > > vpair
Public Member Functions
PHG4SiliconTrackerDetector (PHCompositeNode *Node, PHG4ParametersContainer *parameters, const std::string &dnam="SILICON_TRACKER", const vpair &layerconfig=vpair(0))
constructor
virtual ~PHG4SiliconTrackerDetector ()
destructor
virtual void Construct (G4LogicalVolume *world)
construct
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
void Detector (const std::string &name)
const std::string Detector () const
volume accessors
int IsInSiliconTracker (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Private Member Functions
void AddGeometryNode ()
int ConstructSiliconTracker (G4LogicalVolume *sandwich)
int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
Private Attributes
PHG4ParametersContainer * paramscontainer
vpair layerconfig_
unsigned int nlayer_
int layermin_
int layermax_
G4double overlap_fraction
std::string detector_type
std::string superdetector
G4double eff_radius [4]
G4double posz [4][2]
G4double strip_x_offset [4]
std::set< G4LogicalVolume * > absorberlogvols
std::set< G4LogicalVolume * > activelogvols
std::map< int, int > IsActive
std::map< int, int > IsAbsorberActive
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 21 of file PHG4SiliconTrackerDetector.h.
Member Typedef Documentation
typedef std::vector<std::pair<int, int> > PHG4SiliconTrackerDetector::vpair
Definition at line 24 of file PHG4SiliconTrackerDetector.h.
Constructor & Destructor Documentation
PHG4SiliconTrackerDetector::PHG4SiliconTrackerDetector (PHCompositeNode * Node, PHG4ParametersContainer * parameters, const std::string & dnam = "SILICON_TRACKER", const vpair & layerconfig = vpair(0))
constructor
Definition at line 31 of file PHG4SiliconTrackerDetector.cc.
References PHG4Parameters::get_int_param(), PHG4ParametersContainer::GetAllParameters(), IsAbsorberActive, IsActive, layerconfig_, layermax_, layermin_, nlayer_, and paramscontainer.
virtual PHG4SiliconTrackerDetector::~PHG4SiliconTrackerDetector () inline virtual
destructor
Definition at line 30 of file PHG4SiliconTrackerDetector.h.
Member Function Documentation
void PHG4SiliconTrackerDetector::AddGeometryNode () private
Definition at line 468 of file PHG4SiliconTrackerDetector.cc.
References PHG4CylinderGeomContainer::AddLayerGeom(), PHCompositeNode::addNode(), detector_type, eff_radius, PHNodeIterator::findFirst(), PHG4Parameters::get_double_param(), PHG4Parameters::get_int_param(), PHG4ParametersContainer::GetParameters(), PHG4CylinderGeomContainer::identify(), IsActive, layerconfig_, nlayer_, paramscontainer, posz, strip_x_offset, superdetector, PHG4Detector::topNode, and PHG4Detector::verbosity.
Referenced by Construct().
void PHG4SiliconTrackerDetector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 81 of file PHG4SiliconTrackerDetector.cc.
References AddGeometryNode(), ConstructSiliconTracker(), layermax_, layermin_, and PHG4Detector::verbosity.
int PHG4SiliconTrackerDetector::ConstructSiliconTracker (G4LogicalVolume * sandwich) private
Definition at line 94 of file PHG4SiliconTrackerDetector.cc.
References absorberlogvols, activelogvols, eff_radius, PHG4Parameters::get_double_param(), PHG4Parameters::get_int_param(), PHG4ParametersContainer::GetParameters(), IsAbsorberActive, IsActive, layerconfig_, nlayer_, PHG4Detector::overlapcheck, paramscontainer, posz, and strip_x_offset.
Referenced by Construct().
void PHG4SiliconTrackerDetector::Detector (const std::string & name) inline
Definition at line 47 of file PHG4SiliconTrackerDetector.h.
References detector_type, and PHG4Detector::name.
Referenced by PHG4SiliconTrackerSubsystem::InitRunSubsystem().
const std::string PHG4SiliconTrackerDetector::Detector () const inline
Definition at line 51 of file PHG4SiliconTrackerDetector.h.
References detector_type.
int PHG4SiliconTrackerDetector::DisplayVolume (G4VSolid * volume, G4LogicalVolume * logvol, G4RotationMatrix * rotm = nullptr) private
Definition at line 428 of file PHG4SiliconTrackerDetector.cc.
References PHG4Detector::overlapcheck.
int PHG4SiliconTrackerDetector::IsInSiliconTracker (G4VPhysicalVolume * volume) const
Definition at line 60 of file PHG4SiliconTrackerDetector.cc.
References absorberlogvols, and activelogvols.
Referenced by PHG4SiliconTrackerSteppingAction::UserSteppingAction().
void PHG4SiliconTrackerDetector::SuperDetector (const std::string & name) inline
Definition at line 39 of file PHG4SiliconTrackerDetector.h.
References PHG4Detector::name, and superdetector.
Referenced by PHG4SiliconTrackerSubsystem::InitRunSubsystem(), and PHG4SiliconTrackerSteppingAction::SetInterfacePointers().
const std::string PHG4SiliconTrackerDetector::SuperDetector () const inline
Definition at line 43 of file PHG4SiliconTrackerDetector.h.
References superdetector.
Member Data Documentation
std::set<G4LogicalVolume *> PHG4SiliconTrackerDetector::absorberlogvols private
Definition at line 76 of file PHG4SiliconTrackerDetector.h.
Referenced by ConstructSiliconTracker(), and IsInSiliconTracker().
std::set<G4LogicalVolume *> PHG4SiliconTrackerDetector::activelogvols private
Definition at line 77 of file PHG4SiliconTrackerDetector.h.
Referenced by ConstructSiliconTracker(), and IsInSiliconTracker().
std::string PHG4SiliconTrackerDetector::detector_type private
Definition at line 69 of file PHG4SiliconTrackerDetector.h.
Referenced by AddGeometryNode(), and Detector().
G4double PHG4SiliconTrackerDetector::eff_radius[4] private
Definition at line 72 of file PHG4SiliconTrackerDetector.h.
Referenced by AddGeometryNode(), and ConstructSiliconTracker().
std::map<int, int> PHG4SiliconTrackerDetector::IsAbsorberActive private
Definition at line 79 of file PHG4SiliconTrackerDetector.h.
Referenced by ConstructSiliconTracker(), and PHG4SiliconTrackerDetector().
std::map<int, int> PHG4SiliconTrackerDetector::IsActive private
Definition at line 78 of file PHG4SiliconTrackerDetector.h.
Referenced by AddGeometryNode(), ConstructSiliconTracker(), and PHG4SiliconTrackerDetector().
vpair PHG4SiliconTrackerDetector::layerconfig_ private
Definition at line 62 of file PHG4SiliconTrackerDetector.h.
Referenced by AddGeometryNode(), ConstructSiliconTracker(), and PHG4SiliconTrackerDetector().
int PHG4SiliconTrackerDetector::layermax_ private
Definition at line 65 of file PHG4SiliconTrackerDetector.h.
Referenced by Construct(), and PHG4SiliconTrackerDetector().
int PHG4SiliconTrackerDetector::layermin_ private
Definition at line 64 of file PHG4SiliconTrackerDetector.h.
Referenced by Construct(), and PHG4SiliconTrackerDetector().
unsigned int PHG4SiliconTrackerDetector::nlayer_ private
Definition at line 63 of file PHG4SiliconTrackerDetector.h.
Referenced by AddGeometryNode(), ConstructSiliconTracker(), and PHG4SiliconTrackerDetector().
G4double PHG4SiliconTrackerDetector::overlap_fraction private
Definition at line 67 of file PHG4SiliconTrackerDetector.h.
PHG4ParametersContainer* PHG4SiliconTrackerDetector::paramscontainer private
Definition at line 61 of file PHG4SiliconTrackerDetector.h.
Referenced by AddGeometryNode(), ConstructSiliconTracker(), and PHG4SiliconTrackerDetector().
G4double PHG4SiliconTrackerDetector::posz[4][2] private
Definition at line 73 of file PHG4SiliconTrackerDetector.h.
Referenced by AddGeometryNode(), and ConstructSiliconTracker().
G4double PHG4SiliconTrackerDetector::strip_x_offset[4] private
Definition at line 74 of file PHG4SiliconTrackerDetector.h.
Referenced by AddGeometryNode(), and ConstructSiliconTracker().
std::string PHG4SiliconTrackerDetector::superdetector private
Definition at line 70 of file PHG4SiliconTrackerDetector.h.
Referenced by AddGeometryNode(), and SuperDetector().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerDetector.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerDetector.cc