Class Reference for E1039 Core & Analysis Software: AnaBG Class Reference
AnaBG Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/AnaBG.h>
Public Member Functions
AnaBG (const std::string label="ana_bg")
virtual ~AnaBG ()
virtual void Init ()
virtual void End ()
virtual void ReadEvents (const char *fname)
virtual void Analyze ()
void SetInteCut (const int inte_cut)
int GetInteCut ()
void SetRoads (AnaSignal *ana_signal)
void SetRoads (RoadMap *pos_top, RoadMap *pos_bot, RoadMap *neg_top, RoadMap *neg_bot)
Public Member Functions inherited from AnaBase
virtual ~AnaBase ()
virtual void SetInputTreeName (const std::string name)
virtual void SetInputBranchName (const std::string name)
virtual void ReadEventsFromFileList (const char *fn_list, const int n_max=0)
Protected Types
typedef std::vector< int > EleList
Protected Member Functions
virtual void ProcessOneEvent ()
void FindAllRoads (const EleList *h1, const EleList *h2, const EleList *h3, const EleList *h4, const int tb, RoadMap *road_map)
void DrawInteMax ()
Protected Member Functions inherited from AnaBase
AnaBase (const std::string label)
Protected Attributes
int m_n_evt_used
int m_n_evt_tb
int m_n_evt_fired
RoadMap * m_road_map_pos_top
RoadMap * m_road_map_pos_bot
RoadMap * m_road_map_neg_top
RoadMap * m_road_map_neg_bot
BgData * m_bg_data
TFile * m_file_out
TH1 * m_h1_inte_max
int m_inte_cut
Protected Attributes inherited from AnaBase
std::string m_label
std::string m_tree_name
std::string m_branch_name
std::string m_dir_out
std::ofstream m_ofs
Static Protected Attributes
static constexpr double N_RF_PER_SPILL = 186e6
N of RFs per spill.
Detailed Description
Definition at line 12 of file AnaBG.h.
Member Typedef Documentation
typedef std::vector<int> AnaBG::EleList protected
Definition at line 19 of file AnaBG.h.
Constructor & Destructor Documentation
AnaBG::AnaBG (const std::string label = "ana_bg")
Definition at line 22 of file AnaBG.cc.
AnaBG::~AnaBG () virtual
Definition at line 37 of file AnaBG.cc.
Member Function Documentation
void AnaBG::Analyze () virtual
Regularize BG, namely set its weight to 1 (per spill), so that FoM is always finite.
Reimplemented from AnaBase.
Reimplemented in ReAnaBG.
Definition at line 146 of file AnaBG.cc.
References RoadMap::Begin(), DrawInteMax(), RoadMap::End(), m_n_evt_fired, m_n_evt_tb, m_n_evt_used, AnaBase::m_ofs, m_road_map_neg_bot, m_road_map_neg_top, m_road_map_pos_bot, m_road_map_pos_top, N_RF_PER_SPILL, and RoadMap::ScaleBG().
Referenced by GenerateRoad().
void AnaBG::DrawInteMax () protected
Definition at line 220 of file AnaBG.cc.
References c1, AnaBase::m_dir_out, m_h1_inte_max, m_inte_cut, and AnaBase::m_ofs.
Referenced by Analyze().
void AnaBG::End () virtual
Reimplemented from AnaBase.
Reimplemented in ReAnaBG.
Definition at line 57 of file AnaBG.cc.
References m_file_out.
Referenced by GenerateRoad().
void AnaBG::FindAllRoads (const EleList * h1, const EleList * h2, const EleList * h3, const EleList * h4, const int tb, RoadMap * road_map) protected
Definition at line 204 of file AnaBG.cc.
References RoadMap::AddBG(), and UtilTrigger::Hodo2Road().
Referenced by ReAnaBG::ProcessOneEvent(), and ProcessOneEvent().
int AnaBG::GetInteCut () inline
Definition at line 55 of file AnaBG.h.
References m_inte_cut.
void AnaBG::Init () virtual
Reimplemented from AnaBase.
Reimplemented in ReAnaBG.
Definition at line 42 of file AnaBG.cc.
References AnaBase::m_dir_out, m_file_out, m_h1_inte_max, m_inte_cut, AnaBase::m_ofs, and m_road_map_pos_top.
Referenced by GenerateRoad().
void AnaBG::ProcessOneEvent () protected virtual
Reimplemented from AnaBase.
Reimplemented in ReAnaBG.
Definition at line 88 of file AnaBG.cc.
References RoadMap::AddBG(), RoadMap::Begin(), RoadMap::Contain(), RoadMap::End(), RoadMap::Find(), FindAllRoads(), BgData::h1b, BgData::h1t, BgData::h2b, BgData::h2t, BgData::h3b, BgData::h3t, BgData::h4b, BgData::h4t, BgData::inte_max, m_bg_data, m_h1_inte_max, m_inte_cut, m_n_evt_fired, m_n_evt_tb, m_n_evt_used, m_road_map_neg_bot, m_road_map_neg_top, m_road_map_pos_bot, and m_road_map_pos_top.
Referenced by ReadEvents().
void AnaBG::ReadEvents (const char * fname) virtual
Reimplemented from AnaBase.
Definition at line 64 of file AnaBG.cc.
References file, m_bg_data, AnaBase::m_branch_name, AnaBase::m_tree_name, ProcessOneEvent(), and tree.
void AnaBG::SetInteCut (const int inte_cut) inline
Definition at line 54 of file AnaBG.h.
References m_inte_cut.
Referenced by ApplyRoadset2BG(), and GenerateRoad().
void AnaBG::SetRoads (AnaSignal * ana_signal)
Definition at line 184 of file AnaBG.cc.
References RoadListBase::Frozen(), AnaSignal::GetRoadMapNegBot(), AnaSignal::GetRoadMapNegTop(), AnaSignal::GetRoadMapPosBot(), AnaSignal::GetRoadMapPosTop(), m_road_map_neg_bot, m_road_map_neg_top, m_road_map_pos_bot, and m_road_map_pos_top.
Referenced by ApplyRoadset2BG(), and GenerateRoad().
void AnaBG::SetRoads (RoadMap * pos_top, RoadMap * pos_bot, RoadMap * neg_top, RoadMap * neg_bot)
Definition at line 196 of file AnaBG.cc.
References m_road_map_neg_bot, m_road_map_neg_top, m_road_map_pos_bot, and m_road_map_pos_top.
Member Data Documentation
BgData* AnaBG::m_bg_data protected
Inputs
Definition at line 33 of file AnaBG.h.
Referenced by ReAnaBG::ProcessOneEvent(), ProcessOneEvent(), and ReadEvents().
TFile* AnaBG::m_file_out protected
Outputs
Definition at line 38 of file AnaBG.h.
Referenced by End(), and Init().
TH1* AnaBG::m_h1_inte_max protected
Definition at line 39 of file AnaBG.h.
Referenced by DrawInteMax(), Init(), and ProcessOneEvent().
int AnaBG::m_inte_cut protected
Parameters
Definition at line 44 of file AnaBG.h.
Referenced by DrawInteMax(), GetInteCut(), Init(), ReAnaBG::ProcessOneEvent(), ProcessOneEvent(), and SetInteCut().
int AnaBG::m_n_evt_fired protected
Definition at line 23 of file AnaBG.h.
Referenced by ReAnaBG::Analyze(), Analyze(), ReAnaBG::ProcessOneEvent(), and ProcessOneEvent().
int AnaBG::m_n_evt_tb protected
Definition at line 22 of file AnaBG.h.
Referenced by ReAnaBG::Analyze(), Analyze(), ReAnaBG::ProcessOneEvent(), and ProcessOneEvent().
int AnaBG::m_n_evt_used protected
Definition at line 21 of file AnaBG.h.
Referenced by ReAnaBG::Analyze(), Analyze(), ReAnaBG::ProcessOneEvent(), and ProcessOneEvent().
RoadMap* AnaBG::m_road_map_neg_bot protected
Definition at line 28 of file AnaBG.h.
Referenced by Analyze(), ReAnaBG::ProcessOneEvent(), ProcessOneEvent(), and SetRoads().
RoadMap* AnaBG::m_road_map_neg_top protected
Definition at line 27 of file AnaBG.h.
Referenced by Analyze(), ReAnaBG::ProcessOneEvent(), ProcessOneEvent(), and SetRoads().
RoadMap* AnaBG::m_road_map_pos_bot protected
Definition at line 26 of file AnaBG.h.
Referenced by Analyze(), ReAnaBG::ProcessOneEvent(), ProcessOneEvent(), and SetRoads().
RoadMap* AnaBG::m_road_map_pos_top protected
Definition at line 25 of file AnaBG.h.
Referenced by Analyze(), ReAnaBG::Init(), Init(), ReAnaBG::ProcessOneEvent(), ProcessOneEvent(), and SetRoads().
constexpr double AnaBG::N_RF_PER_SPILL = 186e6 static protected
N of RFs per spill.
Expected counts per spill = [N of "fired" events] / [N of all events] * [N of filled RFs] N of filled RFs = 186e6 = 588 * 369000 * 6 / 7
Definition at line 18 of file AnaBG.h.
Referenced by ReAnaBG::Analyze(), and Analyze().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/AnaBG.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/AnaBG.cc