SeaQuest Offline Software: SHit Class Reference
SHit Class Reference
#include <seaquest-offline/fun4all/interfaces/SHit.h>
Public Member Functions
virtual ~SHit ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual SHit * Clone () const
virtual unsigned int get_id () const
virtual void set_id (unsigned int id)
virtual std::string get_detector_name () const
virtual void set_detector_name (const std::string &name)
virtual unsigned int get_element_id () const
virtual void set_element_id (unsigned int id)
virtual float get_drift_distance () const
virtual void set_drift_distance (const float distance)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SHit ()
Private Member Functions
ClassDef (SHit, 1)
Detailed Description
Definition at line 17 of file SHit.h.
Constructor & Destructor Documentation
virtual SHit::~SHit () inline virtual
Definition at line 21 of file SHit.h.
SHit::SHit () inline protected
Definition at line 47 of file SHit.h.
Member Function Documentation
SHit::ClassDef (SHit , 1) private
virtual SHit* SHit::Clone () const inline virtual
Reimplemented in SHit_v1.
Definition at line 30 of file SHit.h.
Referenced by SHitMap_v1::insert(), SHitMap_v1::operator=(), and SHitMap_v1::SHitMap_v1().
virtual std::string SHit::get_detector_name () const inline virtual
Reimplemented in SHit_v1.
Definition at line 37 of file SHit.h.
virtual float SHit::get_drift_distance () const inline virtual
Reimplemented in SHit_v1.
Definition at line 43 of file SHit.h.
virtual unsigned int SHit::get_element_id () const inline virtual
Reimplemented in SHit_v1.
Definition at line 40 of file SHit.h.
virtual unsigned int SHit::get_id () const inline virtual
Reimplemented in SHit_v1.
Definition at line 34 of file SHit.h.
Referenced by SHitMap_v1::operator=(), and SHitMap_v1::SHitMap_v1().
virtual void SHit::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SHit_v1.
Definition at line 25 of file SHit.h.
Referenced by SimpleReadMySql::process_event().
virtual int SHit::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SHit_v1.
Definition at line 29 of file SHit.h.
virtual void SHit::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SHit_v1.
Definition at line 28 of file SHit.h.
virtual void SHit::set_detector_name (const std::string & name) inline virtual
Reimplemented in SHit_v1.
Definition at line 38 of file SHit.h.
Referenced by SimpleReadMySql::process_event().
virtual void SHit::set_drift_distance (const float distance) inline virtual
Reimplemented in SHit_v1.
Definition at line 44 of file SHit.h.
Referenced by SimpleReadMySql::process_event().
virtual void SHit::set_element_id (unsigned int id) inline virtual
Reimplemented in SHit_v1.
Definition at line 41 of file SHit.h.
Referenced by SimpleReadMySql::process_event().
virtual void SHit::set_id (unsigned int id) inline virtual
Reimplemented in SHit_v1.
Definition at line 35 of file SHit.h.
Referenced by SimpleReadMySql::process_event().
The documentation for this class was generated from the following file:
seaquest-offline/fun4all/interfaces/SHit.h