Class Reference for E1039 Core & Analysis Software: SQParamDeco Class Reference
SQParamDeco Class Reference abstract
SQParamDeco.h.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQParamDeco.h>
Public Types
typedef std::map< std::string, std::string > ParamMap
typedef ParamMap::const_iterator ParamConstIter
typedef ParamMap::iterator ParamIter
Public Member Functions
virtual ~SQParamDeco ()
virtual void identify (std::ostream &os=std::cout) const =0
virtual int isValid () const =0
isValid returns non zero if object contains vailid data
virtual SQParamDeco * Clone () const =0
virtual void Reset ()=0
Clear Event.
virtual bool has_variable (const std::string name) const =0
Return 'true' if a variable having 'name' exists.
virtual std::string get_variable (const std::string name) const =0
Return the value of a variable having 'name'. Return "" if no variable exists.
virtual void set_variable (const std::string name, const std::string value)=0
virtual ParamConstIter begin () const =0
Return the begin iterator.
virtual ParamConstIter end () const =0
Return the end iterator.
virtual unsigned int size () const =0
Return the number of variables held.
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQParamDeco ()
Detailed Description
SQParamDeco.h.
A container class to hold a set of decoding parameters. An SQ interface class to hold a set of decoding parameters. Available only for real data.
Definition at line 16 of file SQParamDeco.h.
Member Typedef Documentation
ParamConstIter
typedef ParamMap::const_iterator SQParamDeco::ParamConstIter
Definition at line 19 of file SQParamDeco.h.
ParamIter
typedef ParamMap::iterator SQParamDeco::ParamIter
Definition at line 20 of file SQParamDeco.h.
ParamMap
typedef std::map<std::string, std::string> SQParamDeco::ParamMap
Definition at line 18 of file SQParamDeco.h.
Constructor & Destructor Documentation
~SQParamDeco()
virtual SQParamDeco::~SQParamDeco () inline virtual
Definition at line 22 of file SQParamDeco.h.
SQParamDeco()
SQParamDeco::SQParamDeco () inline protected
Definition at line 38 of file SQParamDeco.h.
Member Function Documentation
begin()
virtual ParamConstIter SQParamDeco::begin () const pure virtual
Return the begin iterator.
Implemented in SQParamDeco_v1.
Clone()
virtual SQParamDeco* SQParamDeco::Clone () const pure virtual
Implemented in SQParamDeco_v1.
end()
virtual ParamConstIter SQParamDeco::end () const pure virtual
Return the end iterator.
Implemented in SQParamDeco_v1.
get_variable()
virtual std::string SQParamDeco::get_variable (const std::string name) const pure virtual
Return the value of a variable having 'name'. Return "" if no variable exists.
Implemented in SQParamDeco_v1.
has_variable()
virtual bool SQParamDeco::has_variable (const std::string name) const pure virtual
Return 'true' if a variable having 'name' exists.
Implemented in SQParamDeco_v1.
identify()
virtual void SQParamDeco::identify (std::ostream & os = std::cout) const pure virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Implemented in SQParamDeco_v1.
isValid()
virtual int SQParamDeco::isValid () const pure virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Implemented in SQParamDeco_v1.
Reset()
virtual void SQParamDeco::Reset () pure virtual
Clear Event.
Reimplemented from PHObject.
Implemented in SQParamDeco_v1.
set_variable()
virtual void SQParamDeco::set_variable (const std::string name, const std::string value) pure virtual
Implemented in SQParamDeco_v1.
Referenced by CalibDriftDistMod::InitRun(), CalibDriftDist::InitRun(), CalibHodoInTime::InitRun(), and Fun4AllEVIOInputManager::run().
size()
virtual unsigned int SQParamDeco::size () const pure virtual
Return the number of variables held.
Implemented in SQParamDeco_v1.
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQParamDeco.h