Class Reference for E1039 Core & Analysis Software: PHG4InEventReadBack Class Reference
PHG4InEventReadBack Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4InEventReadBack.h>
Public Member Functions
PHG4InEventReadBack (const std::string &name="PHG4InEventReadBack")
virtual ~PHG4InEventReadBack ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 6 of file PHG4InEventReadBack.h.
Constructor & Destructor Documentation
PHG4InEventReadBack()
PHG4InEventReadBack::PHG4InEventReadBack (const std::string & name = "PHG4InEventReadBack")
Definition at line 23 of file PHG4InEventReadBack.cc.
~PHG4InEventReadBack()
virtual PHG4InEventReadBack::~PHG4InEventReadBack () inline virtual
Definition at line 10 of file PHG4InEventReadBack.h.
Member Function Documentation
End()
int PHG4InEventReadBack::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 107 of file PHG4InEventReadBack.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRun()
int PHG4InEventReadBack::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 27 of file PHG4InEventReadBack.cc.
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, and PHNodeIterator::findFirst().
process_event()
int PHG4InEventReadBack::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 45 of file PHG4InEventReadBack.cc.
References PHG4InEvent::AddParticle(), PHG4InEvent::AddVtx(), Fun4AllReturnCodes::EVENT_OK, VariableArray::get_array(), VariableArray::get_array_size(), PHG4InEvent::Reset(), PHG4Particle::set_pid(), PHG4Particle::set_px(), PHG4Particle::set_py(), PHG4Particle::set_pz(), PHG4VtxPointv1::set_t(), PHG4VtxPointv1::set_x(), PHG4VtxPointv1::set_y(), PHG4VtxPointv1::set_z(), and VariableArrayUtils::ShortBitsToFloat().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4InEventReadBack.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4InEventReadBack.cc