Class Reference for E1039 Core & Analysis Software: Fun4AllRUSOutputManager Class Reference
Fun4AllRUSOutputManager Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/RUS/Fun4AllRUSOutputManager.h>
Public Member Functions
Fun4AllRUSOutputManager (const std::string &myname="UNIVERSALOUT")
virtual ~Fun4AllRUSOutputManager ()
void SetTreeName (const std::string &name)
void SetFileName (const std::string &name)
virtual int Write (PHCompositeNode *startNode)
write starting from given node
void ResetBranches ()
void SetBasketSize (int size)
void SetAutoFlush (int flush)
void SetCompressionLevel (int level)
Public Member Functions inherited from Fun4AllOutputManager
virtual ~Fun4AllOutputManager ()
destructor
virtual void Print (const std::string &what="ALL") const
print method (dump event selector)
virtual int AddNode (const std::string &)
add a node in outputmanager
virtual int StripNode (const std::string &)
not write a node in outputmanager
virtual int AddEventSelector (const std::string &recomodule)
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
virtual int outfileopen (const std::string &)
opens output file
virtual int RemoveNode (const std::string &)
removes a node from outputmanager
int WriteGeneric (PHCompositeNode *startNode)
Common method, called before calling virtual Write.
virtual int WriteNode (PHCompositeNode *)
write specified node
virtual std::vector< std::string > * EventSelector ()
retrieves pointer to vector of event selector module names
virtual std::vector< unsigned > * RecoModuleIndex ()
retrieves pointer to vector of event selector module ids
virtual int DoNotWriteEvent (std::vector< int > *retcodes) const
decides if event is to be written or not
virtual size_t EventsWritten () const
get number of Events
virtual std::string OutFileName () const
get output file name
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int OpenFile (PHCompositeNode *startNode)
void CloseFile ()
Protected Member Functions inherited from Fun4AllOutputManager
Fun4AllOutputManager (const std::string &myname)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from Fun4AllOutputManager
size_t nEvents
Number of Events.
std::vector< std::string > EventSelectors
vector of event selectors modules
std::vector< unsigned > recomoduleindex
vector of associated module indexes
std::string outfilename
output file name
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 17 of file Fun4AllRUSOutputManager.h.
Constructor & Destructor Documentation
Fun4AllRUSOutputManager()
Fun4AllRUSOutputManager::Fun4AllRUSOutputManager (const std::string & myname = "UNIVERSALOUT")
Definition at line 23 of file Fun4AllRUSOutputManager.cc.
~Fun4AllRUSOutputManager()
Fun4AllRUSOutputManager::~Fun4AllRUSOutputManager () virtual
Definition at line 40 of file Fun4AllRUSOutputManager.cc.
References CloseFile().
Member Function Documentation
CloseFile()
void Fun4AllRUSOutputManager::CloseFile () protected
Definition at line 133 of file Fun4AllRUSOutputManager.cc.
Referenced by ~Fun4AllRUSOutputManager().
OpenFile()
int Fun4AllRUSOutputManager::OpenFile (PHCompositeNode * startNode) protected
Definition at line 44 of file Fun4AllRUSOutputManager.cc.
References Fun4AllReturnCodes::ABORTEVENT, and Fun4AllReturnCodes::EVENT_OK.
Referenced by Write().
ResetBranches()
void Fun4AllRUSOutputManager::ResetBranches ()
Definition at line 142 of file Fun4AllRUSOutputManager.cc.
Referenced by Write().
SetAutoFlush()
void Fun4AllRUSOutputManager::SetAutoFlush (int flush) inline
Definition at line 27 of file Fun4AllRUSOutputManager.h.
SetBasketSize()
void Fun4AllRUSOutputManager::SetBasketSize (int size) inline
Definition at line 26 of file Fun4AllRUSOutputManager.h.
SetCompressionLevel()
void Fun4AllRUSOutputManager::SetCompressionLevel (int level) inline
Definition at line 28 of file Fun4AllRUSOutputManager.h.
SetFileName()
void Fun4AllRUSOutputManager::SetFileName (const std::string & name) inline
Definition at line 23 of file Fun4AllRUSOutputManager.h.
SetTreeName()
void Fun4AllRUSOutputManager::SetTreeName (const std::string & name) inline
Definition at line 22 of file Fun4AllRUSOutputManager.h.
Write()
int Fun4AllRUSOutputManager::Write (PHCompositeNode *) virtual
write starting from given node
Reimplemented from Fun4AllOutputManager.
Definition at line 91 of file Fun4AllRUSOutputManager.cc.
References SQHitVector::at(), SQHit::get_detector_id(), SQHit::get_drift_distance(), SQHit::get_element_id(), SQEvent::get_event_id(), SQHit::get_hit_id(), SQEvent::get_qie_rf_id(), SQEvent::get_qie_rf_intensity(), SQEvent::get_qie_turn_id(), SQEvent::get_run_id(), SQEvent::get_spill_id(), SQHit::get_tdc_time(), SQEvent::get_trigger(), SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, SQEvent::MATRIX5, SQEvent::NIM1, SQEvent::NIM2, SQEvent::NIM3, SQEvent::NIM4, SQEvent::NIM5, OpenFile(), ResetBranches(), and SQHitVector::size().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/RUS/Fun4AllRUSOutputManager.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/RUS/Fun4AllRUSOutputManager.cc