E1039 Software: PHG4TruthSubsystem Class Reference
PHG4TruthSubsystem Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4TruthSubsystem.h>
Public Member Functions
PHG4TruthSubsystem (const std::string &name="TRUTH")
constructor
virtual ~PHG4TruthSubsystem (void)
destructor
int InitRun (PHCompositeNode *)
init
int process_event (PHCompositeNode *)
event processing
virtual int process_after_geant (PHCompositeNode *)
event processing
int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual PHG4EventAction * GetEventAction (void) const
accessors (reimplemented)
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void SetSaveOnlyEmbeded (bool b=true)
only save the G4 truth information that is associated with the embedded particle
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual PHG4Detector * GetDetector (void) const
return pointer to created detector object
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4TruthEventAction * eventAction_
PHG4TruthSteppingAction * steppingAction_
PHG4TruthTrackingAction * trackingAction_
bool saveOnlyEmbeded_
only save the G4 truth information that is associated with the embedded particle
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from PHG4Subsystem
bool overlapcheck
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 11 of file PHG4TruthSubsystem.h.
Constructor & Destructor Documentation
PHG4TruthSubsystem()
PHG4TruthSubsystem::PHG4TruthSubsystem (const std::string & name = "TRUTH")
constructor
Definition at line 27 of file PHG4TruthSubsystem.cc.
~PHG4TruthSubsystem()
virtual PHG4TruthSubsystem::~PHG4TruthSubsystem (void) inline virtual
destructor
Definition at line 20 of file PHG4TruthSubsystem.h.
References GetEventAction(), GetSteppingAction(), GetTrackingAction(), InitRun(), process_after_geant(), process_event(), and ResetEvent().
Member Function Documentation
GetEventAction()
PHG4EventAction * PHG4TruthSubsystem::GetEventAction (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 154 of file PHG4TruthSubsystem.cc.
References eventAction_.
Referenced by ~PHG4TruthSubsystem().
GetSteppingAction()
PHG4SteppingAction * PHG4TruthSubsystem::GetSteppingAction (void) const virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 159 of file PHG4TruthSubsystem.cc.
References steppingAction_.
Referenced by ~PHG4TruthSubsystem().
GetTrackingAction()
PHG4TrackingAction * PHG4TruthSubsystem::GetTrackingAction (void) const virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 163 of file PHG4TruthSubsystem.cc.
References trackingAction_.
Referenced by ~PHG4TruthSubsystem().
InitRun()
int PHG4TruthSubsystem::InitRun (PHCompositeNode * topNode) virtual
init
Reimplemented from SubsysReco.
Definition at line 36 of file PHG4TruthSubsystem.cc.
References PHCompositeNode::addNode(), eventAction_, PHNodeIterator::findFirst(), and trackingAction_.
Referenced by ~PHG4TruthSubsystem().
process_after_geant()
int PHG4TruthSubsystem::process_after_geant (PHCompositeNode * topNode) virtual
event processing
Reimplemented from PHG4Subsystem.
Definition at line 91 of file PHG4TruthSubsystem.cc.
References PHG4TruthInfoContainer::delete_particle(), PHG4TruthInfoContainer::delete_vtx(), PHG4TruthInfoContainer::GetParticleRange(), PHG4TruthInfoContainer::GetVtxRange(), PHG4TruthInfoContainer::isEmbeded(), saveOnlyEmbeded_, and Fun4AllBase::Verbosity().
Referenced by ~PHG4TruthSubsystem().
process_event()
int PHG4TruthSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 64 of file PHG4TruthSubsystem.cc.
References Fun4AllReturnCodes::EVENT_OK, eventAction_, PHWHERE, PHG4TruthTrackingAction::SetInterfacePointers(), PHG4TruthEventAction::SetInterfacePointers(), and trackingAction_.
Referenced by ~PHG4TruthSubsystem().
ResetEvent()
int PHG4TruthSubsystem::ResetEvent (PHCompositeNode * topNode) virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 146 of file PHG4TruthSubsystem.cc.
References eventAction_, PHG4TruthEventAction::ResetEvent(), PHG4TruthTrackingAction::ResetEvent(), and trackingAction_.
Referenced by ~PHG4TruthSubsystem().
SetSaveOnlyEmbeded()
void PHG4TruthSubsystem::SetSaveOnlyEmbeded (bool b = true) inline
only save the G4 truth information that is associated with the embedded particle
Definition at line 41 of file PHG4TruthSubsystem.h.
References eventAction_, and saveOnlyEmbeded_.
Member Data Documentation
eventAction_
PHG4TruthEventAction* PHG4TruthSubsystem::eventAction_ private
Definition at line 41 of file PHG4TruthSubsystem.h.
Referenced by GetEventAction(), InitRun(), process_event(), ResetEvent(), and SetSaveOnlyEmbeded().
saveOnlyEmbeded_
bool PHG4TruthSubsystem::saveOnlyEmbeded_ private
only save the G4 truth information that is associated with the embedded particle
Definition at line 50 of file PHG4TruthSubsystem.h.
Referenced by process_after_geant(), and SetSaveOnlyEmbeded().
steppingAction_
PHG4TruthSteppingAction* PHG4TruthSubsystem::steppingAction_ private
Definition at line 46 of file PHG4TruthSubsystem.h.
Referenced by GetSteppingAction().
trackingAction_
PHG4TruthTrackingAction* PHG4TruthSubsystem::trackingAction_ private
Definition at line 47 of file PHG4TruthSubsystem.h.
Referenced by GetTrackingAction(), InitRun(), process_event(), and ResetEvent().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4TruthSubsystem.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4TruthSubsystem.cc