SeaQuest Offline Software: KalmanFastTracking Class Reference
KalmanFastTracking Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/KalmanFastTracking.h>
Public Member Functions
KalmanFastTracking (bool flag=true)
~KalmanFastTracking ()
int setRawEvent (SRawEvent *event_input)
void setRawEventDebug (SRawEvent *event_input)
bool acceptEvent (SRawEvent *rawEvent)
void buildTrackletsInStation (int stationID, int listID, double *pos_exp=NULL, double *window=NULL)
Tracklet finding stuff.
void buildBackPartialTracks ()
void buildGlobalTracks ()
int fitTracklet (Tracklet &tracklet)
bool acceptTracklet (Tracklet &tracklet)
bool hodoMask (Tracklet &tracklet)
bool muonID_comp (Tracklet &tracklet)
bool muonID_search (Tracklet &tracklet)
bool muonID_hodoAid (Tracklet &tracklet)
void buildPropSegments ()
void resolveLeftRight (SRawEvent::hit_pair hpair, int &LR1, int &LR2)
void resolveLeftRight (Tracklet &tracklet, double threshold)
void resolveSingleLeftRight (Tracklet &tracklet)
void removeBadHits (Tracklet &tracklet)
int reduceTrackletList (std::list< Tracklet > &tracklets)
void getSagittaWindowsInSt1 (Tracklet &tracklet, double *pos_exp, double *window, int st1ID)
void getExtrapoWindowsInSt1 (Tracklet &tracklet, double *pos_exp, double *window, int st1ID)
void printAtDetectorBack (int stationID, std::string outputFileName)
SRecTrack processOneTracklet (Tracklet &tracklet)
Track fitting stuff.
bool fitTrack (KalmanTrack &kmtrk)
void resolveLeftRight (KalmanTrack &kmtrk)
std::list< Tracklet > & getFinalTracklets ()
Final output.
std::list< Tracklet > & getBackPartials ()
std::list< Tracklet > & getTrackletList (int i)
std::list< SRecTrack > & getSRecTracks ()
std::list< PropSegment > & getPropSegments (int i)
void chi2fit (int n, double x[], double y[], double &a, double &b)
Tool, a simple-minded chi square fit.
KalmanFastTracking (const PHField *field, const TGeoManager *geom, bool flag=true)
~KalmanFastTracking ()
int setRawEvent (SRawEvent *event_input)
void setRawEventDebug (SRawEvent *event_input)
bool acceptEvent (SRawEvent *rawEvent)
void buildTrackletsInStation (int stationID, int listID, double *pos_exp=NULL, double *window=NULL)
Tracklet finding stuff.
void buildBackPartialTracks ()
void buildGlobalTracks ()
int fitTracklet (Tracklet &tracklet)
bool acceptTracklet (Tracklet &tracklet)
bool hodoMask (Tracklet &tracklet)
bool muonID_comp (Tracklet &tracklet)
bool muonID_search (Tracklet &tracklet)
bool muonID_hodoAid (Tracklet &tracklet)
void buildPropSegments ()
void resolveLeftRight (SRawEvent::hit_pair hpair, int &LR1, int &LR2)
void resolveLeftRight (Tracklet &tracklet, double threshold)
void resolveSingleLeftRight (Tracklet &tracklet)
void removeBadHits (Tracklet &tracklet)
int reduceTrackletList (std::list< Tracklet > &tracklets)
void getSagittaWindowsInSt1 (Tracklet &tracklet, double *pos_exp, double *window, int st1ID)
void getExtrapoWindowsInSt1 (Tracklet &tracklet, double *pos_exp, double *window, int st1ID)
void printAtDetectorBack (int stationID, std::string outputFileName)
SRecTrack processOneTracklet (Tracklet &tracklet)
Track fitting stuff.
bool fitTrack (KalmanTrack &kmtrk)
void resolveLeftRight (KalmanTrack &kmtrk)
std::list< Tracklet > & getFinalTracklets ()
Final output.
std::list< Tracklet > & getBackPartials ()
std::list< Tracklet > & getTrackletList (int i)
std::list< SRecTrack > & getSRecTracks ()
std::list< PropSegment > & getPropSegments (int i)
void chi2fit (int n, double x[], double y[], double &a, double &b)
Tool, a simple-minded chi square fit.
Private Attributes
SRawEvent * rawEvent
std::vector< Hit > hitAll
std::list< Tracklet > trackletsInSt [5]
std::list< SRecTrack > stracks
std::list< PropSegment > propSegs [2]
std::vector< int > detectorIDs_mask [4]
Configurations of tracklet finding.
std::vector< int > detectorIDs_maskX [4]
std::vector< int > detectorIDs_maskY [4]
std::list< int > hitIDs_mask [4]
std::vector< int > detectorIDs_muidHodoAid [2]
std::vector< int > stationIDs_mask [nStations]
int detectorIDs_muid [2][4]
double z_ref_muid [2][4]
std::list< int > hitIDs_muid [2][4]
std::list< int > hitIDs_muidHodoAid [2]
double z_mask [nHodoPlanes+nPropPlanes]
double x_mask_min [nHodoPlanes+nPropPlanes][72]
double x_mask_max [nHodoPlanes+nPropPlanes][72]
double y_mask_min [nHodoPlanes+nPropPlanes][72]
double y_mask_max [nHodoPlanes+nPropPlanes][72]
std::vector< int > superIDs [nChamberPlanes/6+2]
For following part, id = 0, 1, 2, 3, 4, 5, 6 stand for station 0, 1, 2, 3+, 3-, and prop tubes X-Z and Y-Z.
double u_win [nChamberPlanes/6]
double u_costheta [nChamberPlanes/6]
double u_sintheta [nChamberPlanes/6]
double z_plane_x [nChamberPlanes/6]
double z_plane_u [nChamberPlanes/6]
double z_plane_v [nChamberPlanes/6]
double costheta_plane [nChamberPlanes+1]
double sintheta_plane [nChamberPlanes+1]
double z_plane [nChamberPlanes+1]
double slope_max [nChamberPlanes+1]
double intersection_max [nChamberPlanes+1]
double resol_plane [nChamberPlanes+1]
double spacing_plane [nChamberPlanes+1]
int s_detectorID [3]
Tracklet tracklet_curr
ROOT::Math::Minimizer * minimizer [2]
ROOT::Math::Functor fcn
KalmanFitter * kmfitter
GeomSvc * p_geomSvc
JobOptsSvc * p_jobOptsSvc
const bool enable_KF
Detailed Description
Definition at line 29 of file KalmanFastTracking.h.
Constructor & Destructor Documentation
KalmanFastTracking::KalmanFastTracking (bool flag = true) explicit
Definition at line 23 of file KalmanFastTracking.cxx.
References costheta_plane, detectorIDs_mask, detectorIDs_maskX, detectorIDs_maskY, detectorIDs_muid, detectorIDs_muidHodoAid, enable_KF, Tracklet::Eval(), fcn, GeomSvc::get2DBoxSize(), GeomSvc::getCostheta(), GeomSvc::getDetectorID(), GeomSvc::getDetectorIDs(), GeomSvc::getPlaneNElements(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneResolution(), GeomSvc::getPlaneScaleY(), GeomSvc::getPlaneSpacing(), GeomSvc::getSintheta(), JobOptsSvc::instance(), GeomSvc::instance(), intersection_max, kmfitter, JobOptsSvc::m_enableKMag, JobOptsSvc::m_st0_reject, JobOptsSvc::m_st1_reject, JobOptsSvc::m_st2_reject, JobOptsSvc::m_st3m_reject, JobOptsSvc::m_st3p_reject, minimizer, MUID_Z_REF, nChamberPlanes, nHodoPlanes, nPropPlanes, nStations, p_geomSvc, p_jobOptsSvc, resol_plane, s_detectorID, KalmanFitter::setControlParameter(), sintheta_plane, slope_max, spacing_plane, stationIDs_mask, superIDs, tracklet_curr, TX_MAX, TY_MAX, u_costheta, u_sintheta, u_win, X0_MAX, x_mask_max, x_mask_min, Y0_MAX, y_mask_max, y_mask_min, z_mask, z_plane, z_plane_u, z_plane_v, z_plane_x, and z_ref_muid.
KalmanFastTracking::~KalmanFastTracking ()
Definition at line 300 of file KalmanFastTracking.cxx.
References enable_KF, kmfitter, and minimizer.
KalmanFastTracking::KalmanFastTracking (const PHField * field, const TGeoManager * geom, bool flag = true) explicit
Definition at line 27 of file KalmanFastTracking.cxx.
References costheta_plane, detectorIDs_mask, detectorIDs_maskX, detectorIDs_maskY, detectorIDs_muid, detectorIDs_muidHodoAid, enable_KF, Tracklet::Eval(), fcn, GeomSvc::get2DBoxSize(), GeomSvc::getCostheta(), GeomSvc::getDetectorID(), GeomSvc::getDetectorIDs(), GeomSvc::getPlaneNElements(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneResolution(), GeomSvc::getPlaneScaleY(), GeomSvc::getPlaneSpacing(), GeomSvc::getSintheta(), JobOptsSvc::instance(), GeomSvc::instance(), intersection_max, kmfitter, JobOptsSvc::m_enableKMag, JobOptsSvc::m_st0_reject, JobOptsSvc::m_st1_reject, JobOptsSvc::m_st2_reject, JobOptsSvc::m_st3m_reject, JobOptsSvc::m_st3p_reject, minimizer, MUID_Z_REF, nChamberPlanes, nHodoPlanes, nPropPlanes, nStations, p_geomSvc, p_jobOptsSvc, resol_plane, s_detectorID, KalmanFitter::setControlParameter(), sintheta_plane, slope_max, spacing_plane, stationIDs_mask, superIDs, tracklet_curr, TX_MAX, TY_MAX, u_costheta, u_sintheta, u_win, X0_MAX, x_mask_max, x_mask_min, Y0_MAX, y_mask_max, y_mask_min, z_mask, z_plane, z_plane_u, z_plane_v, z_plane_x, and z_ref_muid.
KalmanFastTracking::~KalmanFastTracking ()
Member Function Documentation
bool KalmanFastTracking::acceptEvent (SRawEvent * rawEvent)
Definition at line 448 of file KalmanFastTracking.cxx.
References detectorIDs_maskX, SRawEvent::getNHitsInD0(), SRawEvent::getNHitsInD1(), SRawEvent::getNHitsInD2(), SRawEvent::getNHitsInD3m(), SRawEvent::getNHitsInD3p(), SRawEvent::getNHitsInDetectors(), SRawEvent::getNPropHitsAll(), SRawEvent::getNRoadsNeg(), SRawEvent::getNRoadsPos(), and LogInfo.
Referenced by setRawEvent().
bool KalmanFastTracking::acceptEvent (SRawEvent * rawEvent)
bool KalmanFastTracking::acceptTracklet (Tracklet & tracklet)
Definition at line 1193 of file KalmanFastTracking.cxx.
References Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), hodoMask(), GeomSvc::isInKMAG(), Tracklet::isValid(), LogInfo, muonID_comp(), muonID_search(), nStations, p_geomSvc, Tracklet::stationID, and Z_KMAG_BEND.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), and buildTrackletsInStation().
bool KalmanFastTracking::acceptTracklet (Tracklet & tracklet)
void KalmanFastTracking::buildBackPartialTracks ()
Remove bad hits if needed
Definition at line 485 of file KalmanFastTracking.cxx.
References acceptTracklet(), chi2fit(), Tracklet::chisq, detectorIDs_muid, fitTracklet(), GeomSvc::getPlaneType(), hitAll, hitIDs_muid, hodoMask(), Tracklet::isValid(), LogInfo, nChamberPlanes, p_geomSvc, Tracklet::print(), reduceTrackletList(), removeBadHits(), resolveLeftRight(), trackletsInSt, TX_MAX, X0_MAX, z_mask, and z_plane.
Referenced by setRawEvent().
void KalmanFastTracking::buildBackPartialTracks ()
void KalmanFastTracking::buildGlobalTracks ()
Resolve the left-right with a tight pull cut, then a loose one, then resolve by single projections
Remove bad hits if needed
Definition at line 615 of file KalmanFastTracking.cxx.
References acceptTracklet(), buildTrackletsInStation(), Tracklet::chisq_vtx, fitTracklet(), SRecTrack::getChisqVertex(), getExtrapoWindowsInSt1(), Tracklet::getMomentum(), getSagittaWindowsInSt1(), hodoMask(), Tracklet::invP, Tracklet::isValid(), SRecTrack::isValid(), LogInfo, JobOptsSvc::m_enableKMag, Tracklet::merge(), MERGE_THRES, p_jobOptsSvc, Tracklet::print(), processOneTracklet(), removeBadHits(), resolveLeftRight(), resolveSingleLeftRight(), and trackletsInSt.
Referenced by setRawEvent().
void KalmanFastTracking::buildGlobalTracks ()
void KalmanFastTracking::buildPropSegments ()
Definition at line 1449 of file KalmanFastTracking.cxx.
References PropSegment::fit(), SRawEvent::getPartialHitPairsInSuperDetector(), hitAll, PropSegment::hits, PropSegment::isValid(), LogInfo, PropSegment::print(), propSegs, rawEvent, and superIDs.
Referenced by setRawEvent().
void KalmanFastTracking::buildPropSegments ()
void KalmanFastTracking::buildTrackletsInStation (int stationID, int listID, double * pos_exp = NULL, double * window = NULL)
Tracklet finding stuff.
Definition at line 1027 of file KalmanFastTracking.cxx.
References _DEBUG_ON, acceptTracklet(), fitTracklet(), SRawEvent::getPartialHitPairsInSuperDetector(), hitAll, Tracklet::hits, Tracklet::isValid(), LogInfo, Tracklet::nUHits, NULL, Tracklet::nVHits, Tracklet::nXHits, Tracklet::print(), rawEvent, Tracklet::sortHits(), spacing_plane, Tracklet::stationID, superIDs, trackletsInSt, TX_MAX, TY_MAX, u_costheta, u_sintheta, u_win, z_plane, z_plane_u, z_plane_v, and z_plane_x.
Referenced by buildGlobalTracks(), and setRawEvent().
void KalmanFastTracking::buildTrackletsInStation (int stationID, int listID, double * pos_exp = NULL, double * window = NULL)
Tracklet finding stuff.
void KalmanFastTracking::chi2fit (int n, double x[], double y[], double & a, double & b)
Tool, a simple-minded chi square fit.
Definition at line 1827 of file KalmanFastTracking.cxx.
Referenced by buildBackPartialTracks().
void KalmanFastTracking::chi2fit (int n, double x[], double y[], double & a, double & b)
Tool, a simple-minded chi square fit.
bool KalmanFastTracking::fitTrack (KalmanTrack & kmtrk)
Definition at line 1774 of file KalmanFastTracking.cxx.
References KalmanTrack::getNodeList(), kmfitter, KalmanFitter::processOneTrack(), and KalmanFitter::updateTrack().
Referenced by processOneTracklet(), and resolveLeftRight().
bool KalmanFastTracking::fitTrack (KalmanTrack & kmtrk)
int KalmanFastTracking::fitTracklet (Tracklet & tracklet)
Definition at line 1508 of file KalmanFastTracking.cxx.
References Tracklet::chisq, Tracklet::err_invP, Tracklet::err_tx, Tracklet::err_ty, Tracklet::err_x0, Tracklet::err_y0, Tracklet::invP, INVP_MAX, INVP_MIN, JobOptsSvc::m_enableKMag, minimizer, nStations, p_jobOptsSvc, Tracklet::stationID, qdel::status, tracklet_curr, Tracklet::tx, TX_MAX, Tracklet::ty, TY_MAX, Tracklet::x0, X0_MAX, Tracklet::y0, and Y0_MAX.
Referenced by SMillepede::addTrack(), buildBackPartialTracks(), buildGlobalTracks(), buildTrackletsInStation(), removeBadHits(), resolveLeftRight(), and resolveSingleLeftRight().
int KalmanFastTracking::fitTracklet (Tracklet & tracklet)
std::list<Tracklet>& KalmanFastTracking::getBackPartials () inline
Definition at line 94 of file KalmanFastTracking.h.
References trackletsInSt.
std::list<Tracklet>& KalmanFastTracking::getBackPartials () inline
Definition at line 98 of file KalmanFastTracking.h.
References trackletsInSt.
void KalmanFastTracking::getExtrapoWindowsInSt1 (Tracklet & tracklet, double * pos_exp, double * window, int st1ID)
Definition at line 1587 of file KalmanFastTracking.cxx.
References costheta_plane, detectorID, Tracklet::getExpPosErrorX(), Tracklet::getExpPosErrorY(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), GeomSvc::getPlaneType(), GeomSvc::getUinStereoPlane(), nStations, p_geomSvc, sintheta_plane, Tracklet::stationID, and z_plane.
Referenced by buildGlobalTracks().
void KalmanFastTracking::getExtrapoWindowsInSt1 (Tracklet & tracklet, double * pos_exp, double * window, int st1ID)
std::list<Tracklet>& KalmanFastTracking::getFinalTracklets () inline
Final output.
Definition at line 93 of file KalmanFastTracking.h.
References trackletsInSt.
Referenced by main(), and KalmanFastTrackingWrapper::process_event().
std::list<Tracklet>& KalmanFastTracking::getFinalTracklets () inline
Final output.
Definition at line 97 of file KalmanFastTracking.h.
References trackletsInSt.
std::list<PropSegment>& KalmanFastTracking::getPropSegments (int i) inline
Definition at line 97 of file KalmanFastTracking.h.
References propSegs.
std::list<PropSegment>& KalmanFastTracking::getPropSegments (int i) inline
Definition at line 101 of file KalmanFastTracking.h.
References propSegs.
void KalmanFastTracking::getSagittaWindowsInSt1 (Tracklet & tracklet, double * pos_exp, double * window, int st1ID)
Definition at line 1615 of file KalmanFastTracking.cxx.
References detectorID, Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), GeomSvc::getPlaneType(), GeomSvc::getUinStereoPlane(), Tracklet::hits, nStations, p_geomSvc, s_detectorID, SAGITTA_DUMP_CENTER, SAGITTA_DUMP_WIN, SAGITTA_TARGET_CENTER, SAGITTA_TARGET_WIN, Tracklet::stationID, Z_DUMP, z_plane, and Z_TARGET.
Referenced by buildGlobalTracks().
void KalmanFastTracking::getSagittaWindowsInSt1 (Tracklet & tracklet, double * pos_exp, double * window, int st1ID)
std::list<SRecTrack>& KalmanFastTracking::getSRecTracks () inline
Definition at line 96 of file KalmanFastTracking.h.
References stracks.
Referenced by main(), and KalmanFastTrackingWrapper::process_event().
std::list<SRecTrack>& KalmanFastTracking::getSRecTracks () inline
Definition at line 100 of file KalmanFastTracking.h.
References stracks.
std::list<Tracklet>& KalmanFastTracking::getTrackletList (int i) inline
Definition at line 95 of file KalmanFastTracking.h.
References trackletsInSt.
Referenced by main().
std::list<Tracklet>& KalmanFastTracking::getTrackletList (int i) inline
Definition at line 99 of file KalmanFastTracking.h.
References trackletsInSt.
bool KalmanFastTracking::hodoMask (Tracklet & tracklet)
Definition at line 1220 of file KalmanFastTracking.cxx.
References detectorID, Tracklet::getExpPosErrorX(), Tracklet::getExpPosErrorY(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), hitAll, hitIDs_mask, LogInfo, nChamberPlanes, nStations, Tracklet::stationID, stationIDs_mask, x_mask_max, x_mask_min, y_mask_max, y_mask_min, and z_mask.
Referenced by acceptTracklet(), buildBackPartialTracks(), and buildGlobalTracks().
bool KalmanFastTracking::hodoMask (Tracklet & tracklet)
bool KalmanFastTracking::muonID_comp (Tracklet & tracklet)
Definition at line 1343 of file KalmanFastTracking.cxx.
References Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::invP, LogInfo, MUID_EMP_P0, MUID_EMP_P1, MUID_EMP_P2, MUID_R_CUT, MUID_REJECT, MUID_THE_P0, MUID_Z_REF, nStations, propSegs, Tracklet::seg_x, Tracklet::seg_y, Tracklet::stationID, Tracklet::tx, and Tracklet::ty.
Referenced by acceptTracklet().
bool KalmanFastTracking::muonID_comp (Tracklet & tracklet)
bool KalmanFastTracking::muonID_hodoAid (Tracklet & tracklet)
Definition at line 1400 of file KalmanFastTracking.cxx.
References detectorID, Tracklet::getExpPosErrorX(), Tracklet::getExpPosErrorY(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), hitAll, hitIDs_muidHodoAid, PropSegment::hodoHits, Tracklet::invP, MUID_EMP_P0, MUID_EMP_P1, MUID_EMP_P2, MUID_REJECT, MUID_THE_P0, MUID_Z_REF, nChamberPlanes, PropSegment::nHodoHits, nStations, Tracklet::seg_x, Tracklet::seg_y, Tracklet::stationID, x_mask_max, x_mask_min, y_mask_max, y_mask_min, and z_mask.
Referenced by muonID_search().
bool KalmanFastTracking::muonID_hodoAid (Tracklet & tracklet)
bool KalmanFastTracking::muonID_search (Tracklet & tracklet)
Definition at line 1271 of file KalmanFastTracking.cxx.
References detectorIDs_muid, driftDistance, PropSegment::fit(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), PropSegment::getPosRef(), SignedHit::hit, hitAll, hitIDs_muid, PropSegment::hits, PropSegment::init(), Tracklet::invP, GeomSvc::isInPlane(), MUID_EMP_P0, MUID_EMP_P1, MUID_EMP_P2, MUID_REJECT, MUID_THE_P0, MUID_Z_REF, muonID_hodoAid(), nChamberPlanes, PropSegment::nHodoHits, nStations, p_geomSvc, Tracklet::seg_x, Tracklet::seg_y, SignedHit::sign, Tracklet::stationID, Tracklet::tx, Tracklet::ty, z_mask, and z_ref_muid.
Referenced by acceptTracklet().
bool KalmanFastTracking::muonID_search (Tracklet & tracklet)
void KalmanFastTracking::printAtDetectorBack (int stationID, std::string outputFileName)
Definition at line 1660 of file KalmanFastTracking.cxx.
References GeomSvc::getPlaneCenterX(), GeomSvc::getPlaneCenterY(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneScaleX(), GeomSvc::getPlaneScaleY(), p_geomSvc, and trackletsInSt.
void KalmanFastTracking::printAtDetectorBack (int stationID, std::string outputFileName)
SRecTrack KalmanFastTracking::processOneTracklet (Tracklet & tracklet)
Track fitting stuff.
Definition at line 1704 of file KalmanFastTracking.cxx.
References TrkPar::_covar_kf, TrkPar::_state_kf, TrkPar::_z, PropSegment::a, fitTrack(), Tracklet::getCharge(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), KalmanTrack::getHitIndexList(), PropSegment::getNHits(), KalmanTrack::getNodeList(), GeomSvc::getPlanePosition(), TriggerRoad::getRoadID(), KalmanTrack::getSRecTrack(), Tracklet::getSRecTrack(), Tracklet::hits, Tracklet::invP, KalmanTrack::isValid(), p_geomSvc, Tracklet::seg_x, Tracklet::seg_y, KalmanTrack::setCurrTrkpar(), SRecTrack::setKalmanStatus(), SRecTrack::setNHitsInPT(), SRecTrack::setPTSlope(), SRecTrack::setTriggerRoad(), Tracklet::tx, and Tracklet::ty.
Referenced by buildGlobalTracks(), and setRawEvent().
SRecTrack KalmanFastTracking::processOneTracklet (Tracklet & tracklet)
Track fitting stuff.
int KalmanFastTracking::reduceTrackletList (std::list< Tracklet > & tracklets)
Definition at line 1550 of file KalmanFastTracking.cxx.
References LogInfo.
Referenced by buildBackPartialTracks().
int KalmanFastTracking::reduceTrackletList (std::list< Tracklet > & tracklets)
void KalmanFastTracking::removeBadHits (Tracklet & tracklet)
Definition at line 887 of file KalmanFastTracking.cxx.
References Tracklet::calcChisq(), detectorID, Hit::detectorID, Hit::driftDistance, fitTracklet(), GeomSvc::getPlaneType(), SignedHit::hit, Tracklet::hits, Hit::index, Tracklet::isValid(), LogInfo, nChamberPlanes, Tracklet::nUHits, NULL, Tracklet::nVHits, Tracklet::nXHits, p_geomSvc, Hit::print(), Tracklet::print(), Tracklet::residual, resol_plane, resolveSingleLeftRight(), and SignedHit::sign.
Referenced by buildBackPartialTracks(), and buildGlobalTracks().
void KalmanFastTracking::removeBadHits (Tracklet & tracklet)
void KalmanFastTracking::resolveLeftRight (SRawEvent::hit_pair hpair, int & LR1, int & LR2)
Definition at line 987 of file KalmanFastTracking.cxx.
References detectorID, hitAll, intersection_max, slope_max, and z_plane.
Referenced by buildBackPartialTracks(), and buildGlobalTracks().
void KalmanFastTracking::resolveLeftRight (Tracklet & tracklet, double threshold)
Definition at line 761 of file KalmanFastTracking.cxx.
References costheta_plane, Tracklet::err_tx, Tracklet::err_ty, Tracklet::err_x0, Tracklet::err_y0, fitTracklet(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::getXZErrorInSt1(), Tracklet::getXZInfoInSt1(), Tracklet::hits, intersection_max, LogInfo, Tracklet::print(), sintheta_plane, slope_max, Tracklet::stationID, Tracklet::tx, Tracklet::ty, Tracklet::x0, Tracklet::y0, and z_plane.
void KalmanFastTracking::resolveLeftRight (SRawEvent::hit_pair hpair, int & LR1, int & LR2)
void KalmanFastTracking::resolveLeftRight (Tracklet & tracklet, double threshold)
void KalmanFastTracking::resolveLeftRight (KalmanTrack & kmtrk)
Definition at line 1787 of file KalmanFastTracking.cxx.
References fitTrack(), KalmanTrack::getHitIndexList(), KalmanTrack::getNodeList(), GeomSvc::getPlaneResolution(), GeomSvc::getUinStereoPlane(), and p_geomSvc.
void KalmanFastTracking::resolveLeftRight (KalmanTrack & kmtrk)
void KalmanFastTracking::resolveSingleLeftRight (Tracklet & tracklet)
Definition at line 864 of file KalmanFastTracking.cxx.
References costheta_plane, detectorID, fitTracklet(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::hits, LogInfo, Tracklet::print(), sintheta_plane, and z_plane.
Referenced by buildGlobalTracks(), and removeBadHits().
void KalmanFastTracking::resolveSingleLeftRight (Tracklet & tracklet)
int KalmanFastTracking::setRawEvent (SRawEvent * event_input)
Definition at line 313 of file KalmanFastTracking.cxx.
References acceptEvent(), buildBackPartialTracks(), buildGlobalTracks(), buildPropSegments(), buildTrackletsInStation(), detectorIDs_maskX, detectorIDs_maskY, detectorIDs_muid, detectorIDs_muidHodoAid, enable_KF, SRawEvent::getAllHits(), SRawEvent::getHitsIndexInDetector(), SRawEvent::getHitsIndexInDetectors(), hitAll, hitIDs_mask, hitIDs_muid, hitIDs_muidHodoAid, SRawEvent::isFPGATriggered(), LogInfo, JobOptsSvc::m_mcMode, p_jobOptsSvc, processOneTracklet(), propSegs, rawEvent, stracks, TFEXIT_FAIL_BACKPARTIAL, TFEXIT_FAIL_GLOABL, TFEXIT_FAIL_MULTIPLICITY, TFEXIT_FAIL_ST2_TRACKLET, TFEXIT_FAIL_ST3_TRACKLET, TFEXIT_SUCCESS, and trackletsInSt.
Referenced by main(), and KalmanFastTrackingWrapper::process_event().
int KalmanFastTracking::setRawEvent (SRawEvent * event_input)
void KalmanFastTracking::setRawEventDebug (SRawEvent * event_input)
Definition at line 307 of file KalmanFastTracking.cxx.
References SRawEvent::getAllHits(), hitAll, and rawEvent.
void KalmanFastTracking::setRawEventDebug (SRawEvent * event_input)
Member Data Documentation
double KalmanFastTracking::costheta_plane private
Definition at line 155 of file KalmanFastTracking.h.
Referenced by getExtrapoWindowsInSt1(), KalmanFastTracking(), resolveLeftRight(), and resolveSingleLeftRight().
std::vector< int > KalmanFastTracking::detectorIDs_mask private
Configurations of tracklet finding.
Definition at line 120 of file KalmanFastTracking.h.
Referenced by KalmanFastTracking().
std::vector< int > KalmanFastTracking::detectorIDs_maskX private
Definition at line 121 of file KalmanFastTracking.h.
Referenced by acceptEvent(), KalmanFastTracking(), and setRawEvent().
std::vector< int > KalmanFastTracking::detectorIDs_maskY private
Definition at line 122 of file KalmanFastTracking.h.
Referenced by KalmanFastTracking(), and setRawEvent().
int KalmanFastTracking::detectorIDs_muid private
Definition at line 130 of file KalmanFastTracking.h.
Referenced by buildBackPartialTracks(), KalmanFastTracking(), muonID_search(), and setRawEvent().
std::vector< int > KalmanFastTracking::detectorIDs_muidHodoAid private
Definition at line 124 of file KalmanFastTracking.h.
Referenced by KalmanFastTracking(), and setRawEvent().
const bool KalmanFastTracking::enable_KF private
Definition at line 191 of file KalmanFastTracking.h.
Referenced by KalmanFastTracking(), setRawEvent(), and ~KalmanFastTracking().
ROOT::Math::Functor KalmanFastTracking::fcn private
Definition at line 179 of file KalmanFastTracking.h.
Referenced by KalmanFastTracking().
std::vector< Hit > KalmanFastTracking::hitAll private
Definition at line 105 of file KalmanFastTracking.h.
Referenced by buildBackPartialTracks(), buildPropSegments(), buildTrackletsInStation(), hodoMask(), muonID_hodoAid(), muonID_search(), resolveLeftRight(), setRawEvent(), and setRawEventDebug().
std::list< int > KalmanFastTracking::hitIDs_mask private
Definition at line 123 of file KalmanFastTracking.h.
Referenced by hodoMask(), and setRawEvent().
std::list< int > KalmanFastTracking::hitIDs_muid private
Definition at line 132 of file KalmanFastTracking.h.
Referenced by buildBackPartialTracks(), muonID_search(), and setRawEvent().
std::list< int > KalmanFastTracking::hitIDs_muidHodoAid private
Definition at line 133 of file KalmanFastTracking.h.
Referenced by muonID_hodoAid(), and setRawEvent().
double KalmanFastTracking::intersection_max private
Definition at line 163 of file KalmanFastTracking.h.
Referenced by KalmanFastTracking(), and resolveLeftRight().
KalmanFitter * KalmanFastTracking::kmfitter private
Definition at line 182 of file KalmanFastTracking.h.
Referenced by fitTrack(), KalmanFastTracking(), and ~KalmanFastTracking().
ROOT::Math::Minimizer * KalmanFastTracking::minimizer private
Definition at line 178 of file KalmanFastTracking.h.
Referenced by fitTracklet(), KalmanFastTracking(), and ~KalmanFastTracking().
GeomSvc * KalmanFastTracking::p_geomSvc private
Definition at line 185 of file KalmanFastTracking.h.
Referenced by acceptTracklet(), buildBackPartialTracks(), getExtrapoWindowsInSt1(), getSagittaWindowsInSt1(), KalmanFastTracking(), muonID_search(), printAtDetectorBack(), processOneTracklet(), removeBadHits(), and resolveLeftRight().
JobOptsSvc * KalmanFastTracking::p_jobOptsSvc private
Definition at line 188 of file KalmanFastTracking.h.
Referenced by buildGlobalTracks(), fitTracklet(), KalmanFastTracking(), and setRawEvent().
std::list< PropSegment > KalmanFastTracking::propSegs private
Definition at line 116 of file KalmanFastTracking.h.
Referenced by buildPropSegments(), getPropSegments(), muonID_comp(), and setRawEvent().
SRawEvent * KalmanFastTracking::rawEvent private
Definition at line 104 of file KalmanFastTracking.h.
Referenced by buildPropSegments(), buildTrackletsInStation(), setRawEvent(), and setRawEventDebug().
double KalmanFastTracking::resol_plane private
Definition at line 166 of file KalmanFastTracking.h.
Referenced by KalmanFastTracking(), and removeBadHits().
int KalmanFastTracking::s_detectorID private
Definition at line 172 of file KalmanFastTracking.h.
Referenced by getSagittaWindowsInSt1(), and KalmanFastTracking().
double KalmanFastTracking::sintheta_plane private
Definition at line 156 of file KalmanFastTracking.h.
Referenced by getExtrapoWindowsInSt1(), KalmanFastTracking(), resolveLeftRight(), and resolveSingleLeftRight().
double KalmanFastTracking::slope_max private
Definition at line 162 of file KalmanFastTracking.h.
Referenced by KalmanFastTracking(), and resolveLeftRight().
double KalmanFastTracking::spacing_plane private
Definition at line 169 of file KalmanFastTracking.h.
Referenced by buildTrackletsInStation(), and KalmanFastTracking().
std::vector< int > KalmanFastTracking::stationIDs_mask private
Definition at line 127 of file KalmanFastTracking.h.
Referenced by hodoMask(), and KalmanFastTracking().
std::list< SRecTrack > KalmanFastTracking::stracks private
Definition at line 112 of file KalmanFastTracking.h.
Referenced by getSRecTracks(), and setRawEvent().
std::vector< int > KalmanFastTracking::superIDs private
For following part, id = 0, 1, 2, 3, 4, 5, 6 stand for station 0, 1, 2, 3+, 3-, and prop tubes X-Z and Y-Z.
Definition at line 144 of file KalmanFastTracking.h.
Referenced by buildPropSegments(), buildTrackletsInStation(), and KalmanFastTracking().
Tracklet KalmanFastTracking::tracklet_curr private
Definition at line 175 of file KalmanFastTracking.h.
Referenced by fitTracklet(), and KalmanFastTracking().
std::list< Tracklet > KalmanFastTracking::trackletsInSt private
Definition at line 109 of file KalmanFastTracking.h.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), buildTrackletsInStation(), getBackPartials(), getFinalTracklets(), getTrackletList(), printAtDetectorBack(), and setRawEvent().
double KalmanFastTracking::u_costheta private
Definition at line 148 of file KalmanFastTracking.h.
Referenced by buildTrackletsInStation(), and KalmanFastTracking().
double KalmanFastTracking::u_sintheta private
Definition at line 149 of file KalmanFastTracking.h.
Referenced by buildTrackletsInStation(), and KalmanFastTracking().
double KalmanFastTracking::u_win private
Definition at line 147 of file KalmanFastTracking.h.
Referenced by buildTrackletsInStation(), and KalmanFastTracking().
double KalmanFastTracking::x_mask_max private
Definition at line 138 of file KalmanFastTracking.h.
Referenced by hodoMask(), KalmanFastTracking(), and muonID_hodoAid().
double KalmanFastTracking::x_mask_min private
Definition at line 137 of file KalmanFastTracking.h.
Referenced by hodoMask(), KalmanFastTracking(), and muonID_hodoAid().
double KalmanFastTracking::y_mask_max private
Definition at line 140 of file KalmanFastTracking.h.
Referenced by hodoMask(), KalmanFastTracking(), and muonID_hodoAid().
double KalmanFastTracking::y_mask_min private
Definition at line 139 of file KalmanFastTracking.h.
Referenced by hodoMask(), KalmanFastTracking(), and muonID_hodoAid().
double KalmanFastTracking::z_mask private
Definition at line 136 of file KalmanFastTracking.h.
Referenced by buildBackPartialTracks(), hodoMask(), KalmanFastTracking(), muonID_hodoAid(), and muonID_search().
double KalmanFastTracking::z_plane private
Definition at line 159 of file KalmanFastTracking.h.
Referenced by buildBackPartialTracks(), buildTrackletsInStation(), getExtrapoWindowsInSt1(), getSagittaWindowsInSt1(), KalmanFastTracking(), resolveLeftRight(), and resolveSingleLeftRight().
double KalmanFastTracking::z_plane_u private
Definition at line 151 of file KalmanFastTracking.h.
Referenced by buildTrackletsInStation(), and KalmanFastTracking().
double KalmanFastTracking::z_plane_v private
Definition at line 152 of file KalmanFastTracking.h.
Referenced by buildTrackletsInStation(), and KalmanFastTracking().
double KalmanFastTracking::z_plane_x private
Definition at line 150 of file KalmanFastTracking.h.
Referenced by buildTrackletsInStation(), and KalmanFastTracking().
double KalmanFastTracking::z_ref_muid private
Definition at line 131 of file KalmanFastTracking.h.
Referenced by KalmanFastTracking(), and muonID_search().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/KalmanFastTracking.h
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/src/KalmanFastTracking.cxx