E1039 Software: CodaInputManager Class Reference
CodaInputManager Class Reference
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/online/decoder_maindaq/CodaInputManager.h>
Public Member Functions
CodaInputManager ()
virtual ~CodaInputManager ()
void SetVerbosity (const int verb)
void SetRunNumber (const int run)
void SetOnline (const bool val)
void ForceEnd ()
bool IsEnded ()
int OpenFile (const std::string fname, const long file_size_min=0, const int sec_wait=10, const int n_wait=0)
int CloseFile ()
bool JumpCodaEvent (unsigned int &coda_id, int *&event_words, const int n_evt)
bool NextCodaEvent (unsigned int &coda_id, int *&event_words)
Private Member Functions
bool file_exists (const std::string fname)
Private Attributes
int m_verb
bool m_online
bool m_go_end
int m_handle
int m_run
std::string m_fname
long int m_file_size
int m_event_count
int m_event_words [buflen]
Static Private Attributes
static const int buflen = 500000
Detailed Description
Definition at line 9 of file CodaInputManager.h.
Constructor & Destructor Documentation
CodaInputManager::CodaInputManager ()
Definition at line 12 of file CodaInputManager.cc.
virtual CodaInputManager::~CodaInputManager () inline virtual
Definition at line 23 of file CodaInputManager.h.
Member Function Documentation
int CodaInputManager::CloseFile ()
Definition at line 68 of file CodaInputManager.cc.
References evClose(), and m_handle.
Referenced by MainDaqParser::End(), and OpenFile().
bool CodaInputManager::file_exists (const std::string fname) private
Definition at line 124 of file CodaInputManager.cc.
Referenced by NextCodaEvent(), and OpenFile().
void CodaInputManager::ForceEnd () inline
Definition at line 28 of file CodaInputManager.h.
References m_go_end.
Referenced by NextCodaEvent(), and MainDaqParser::ParseOneSpill().
bool CodaInputManager::IsEnded () inline
Definition at line 29 of file CodaInputManager.h.
References m_go_end.
Referenced by MainDaqParser::NextPhysicsEvent().
bool CodaInputManager::JumpCodaEvent (unsigned int & coda_id, int *& event_words, const int n_evt)
Definition at line 76 of file CodaInputManager.cc.
References NextCodaEvent().
Referenced by NextCodaEvent(), and MainDaqParser::ParseOneSpill().
bool CodaInputManager::NextCodaEvent (unsigned int & coda_id, int *& event_words)
Definition at line 87 of file CodaInputManager.cc.
References buflen, evRead(), file_exists(), ForceEnd(), UtilOnline::GetCodaFilePath(), UtilOnline::GetEndFilePath(), JumpCodaEvent(), m_event_count, m_event_words, m_file_size, m_fname, m_go_end, m_handle, m_online, m_run, and OpenFile().
Referenced by JumpCodaEvent(), and MainDaqParser::ParseOneSpill().
int CodaInputManager::OpenFile (const std::string fname, const long file_size_min = 0, const int sec_wait = 10, const int n_wait = 0)
Definition at line 18 of file CodaInputManager.cc.
References CloseFile(), evOpen(), file_exists(), m_event_count, m_file_size, m_fname, m_handle, m_verb, and NULL.
Referenced by NextCodaEvent(), MainDaqParser::OpenCodaFile(), and MainDaqParser::ParseOneSpill().
void CodaInputManager::SetOnline (const bool val) inline
Definition at line 27 of file CodaInputManager.h.
References m_online.
Referenced by Fun4AllEVIOInputManager::SetOnline().
void CodaInputManager::SetRunNumber (const int run) inline
Definition at line 26 of file CodaInputManager.h.
References m_run.
Referenced by MainDaqParser::ProcessCodaPrestart().
void CodaInputManager::SetVerbosity (const int verb) inline
Definition at line 25 of file CodaInputManager.h.
References m_verb.
Member Data Documentation
const int CodaInputManager::buflen = 500000 static private
Definition at line 10 of file CodaInputManager.h.
Referenced by NextCodaEvent().
int CodaInputManager::m_event_count private
Definition at line 18 of file CodaInputManager.h.
Referenced by NextCodaEvent(), and OpenFile().
int CodaInputManager::m_event_words[buflen] private
Definition at line 19 of file CodaInputManager.h.
Referenced by NextCodaEvent().
long int CodaInputManager::m_file_size private
Definition at line 17 of file CodaInputManager.h.
Referenced by NextCodaEvent(), and OpenFile().
std::string CodaInputManager::m_fname private
Definition at line 16 of file CodaInputManager.h.
Referenced by NextCodaEvent(), and OpenFile().
bool CodaInputManager::m_go_end private
Definition at line 13 of file CodaInputManager.h.
Referenced by ForceEnd(), IsEnded(), and NextCodaEvent().
int CodaInputManager::m_handle private
Definition at line 14 of file CodaInputManager.h.
Referenced by CloseFile(), NextCodaEvent(), and OpenFile().
bool CodaInputManager::m_online private
Definition at line 12 of file CodaInputManager.h.
Referenced by NextCodaEvent(), and SetOnline().
int CodaInputManager::m_run private
Definition at line 15 of file CodaInputManager.h.
Referenced by NextCodaEvent(), and SetRunNumber().
int CodaInputManager::m_verb private
Definition at line 11 of file CodaInputManager.h.
Referenced by OpenFile(), and SetVerbosity().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/online/decoder_maindaq/CodaInputManager.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/online/decoder_maindaq/CodaInputManager.cc