Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaNMRData/ana_NMR_noise.cc File Reference
ana_NMR_noise.cc File Reference
#include "NMRDataManager.h"
Functions
void DrawPolySignal (TH2 *h2_vt, const int i_evt_b, const int i_evt_e, const int time_b, const int time_e)
void ana_NMR_noise (const bool draw_h2=true)
Function Documentation
ana_NMR_noise()
void ana_NMR_noise (const bool draw_h2 = true)
Read event file(s).
Set the reference time. Set 'utime0' to 0 to pick up the time of the 1st data.
Create graphs/histograms and fill them in the event loop.
Draw graphs/histograms.
Definition at line 4 of file ana_NMR_noise.cc.
References NMRUtil::ConvEventNum(), DrawPolySignal(), NMRDataManager::GetEvent(), NMREvent::GetInt(), NMRDataManager::GetNumEvent(), NMRSignal::GetNumPoint(), NMRSignal::GetPoint(), NMRDataManager::GetPolySignal(), NMRDataManager::GetPolySignalRange(), NMRDataManager::GetScanParam(), NMRDataManager::ReadEventFile(), and NMRDataManager::Verb().
DrawPolySignal()
void DrawPolySignal (TH2 * h2_vt, const int i_evt_b, const int i_evt_e, const int time_b, const int time_e)
Definition at line 149 of file ana_NMR_noise.cc.
Referenced by ana_NMR_noise().