E1039 Software: MCHit Class Reference
MCHit Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/db2g4/MCHit.hh>
Public Member Functions
MCHit ()
~MCHit ()
void * operator new (size_t)
void operator delete (void *)
G4int GetParticleID () const
void SetParticleID (G4int particle_id)
G4String GetParticleName () const
void SetParticleName (G4String pName)
G4ThreeVector GetPosition () const
void SetPosition (G4ThreeVector pos)
G4double GetDE () const
void SetDE (G4double de)
G4String GetVolume () const
void SetVolume (G4String volume)
G4ThreeVector GetMomentum () const
void SetMomentum (G4ThreeVector p)
G4ThreeVector GetVertex () const
void SetVertex (G4ThreeVector v0)
G4double GetTime () const
void SetTime (G4double time)
G4int GetTrackID () const
void SetTrackID (G4int tid)
G4int GetParentID () const
void SetParentID (G4int parentID)
G4ThreeVector GetVertexMomentumDirection () const
void SetVertexMomentumDirection (G4ThreeVector vmd)
G4double GetVertexKineticEnergy () const
void SetVertexKineticEnergy (G4double vke)
Private Attributes
G4int fPid
G4String fName
G4ThreeVector fPosition
G4double fDE
G4String fVolume
G4ThreeVector fMomentum
G4ThreeVector fVertex
G4double fTime
G4int fTrackID
G4int fParentID
G4ThreeVector fVertexMomentumDirection
G4double fVertexKineticEnergy
Detailed Description
Definition at line 15 of file MCHit.hh.
Constructor & Destructor Documentation
MCHit()
MCHit::MCHit ()
Definition at line 5 of file MCHit.cc.
~MCHit()
MCHit::~MCHit ()
Definition at line 9 of file MCHit.cc.
Member Function Documentation
GetDE()
G4double MCHit::GetDE () const inline
Definition at line 50 of file MCHit.hh.
References fDE.
GetMomentum()
G4ThreeVector MCHit::GetMomentum () const inline
Definition at line 56 of file MCHit.hh.
References fMomentum.
GetParentID()
G4int MCHit::GetParentID () const inline
Definition at line 68 of file MCHit.hh.
References fParentID.
GetParticleID()
G4int MCHit::GetParticleID () const inline
Definition at line 41 of file MCHit.hh.
References fPid.
GetParticleName()
G4String MCHit::GetParticleName () const inline
Definition at line 44 of file MCHit.hh.
References fName.
GetPosition()
G4ThreeVector MCHit::GetPosition () const inline
Definition at line 47 of file MCHit.hh.
References fPosition.
GetTime()
G4double MCHit::GetTime () const inline
Definition at line 62 of file MCHit.hh.
References fTime.
GetTrackID()
G4int MCHit::GetTrackID () const inline
Definition at line 65 of file MCHit.hh.
References fTrackID.
GetVertex()
G4ThreeVector MCHit::GetVertex () const inline
Definition at line 59 of file MCHit.hh.
References fVertex.
GetVertexKineticEnergy()
G4double MCHit::GetVertexKineticEnergy () const inline
Definition at line 74 of file MCHit.hh.
References fVertexKineticEnergy.
GetVertexMomentumDirection()
G4ThreeVector MCHit::GetVertexMomentumDirection () const inline
Definition at line 71 of file MCHit.hh.
References fVertexMomentumDirection.
GetVolume()
G4String MCHit::GetVolume () const inline
Definition at line 53 of file MCHit.hh.
References fVolume.
operator delete()
void MCHit::operator delete (void * aHit) inline
Definition at line 90 of file MCHit.hh.
References MCHitAllocator.
operator new()
void * MCHit::operator new (size_t) inline
Definition at line 83 of file MCHit.hh.
References MCHitAllocator.
SetDE()
void MCHit::SetDE (G4double de) inline
Definition at line 51 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetMomentum()
void MCHit::SetMomentum (G4ThreeVector p) inline
Definition at line 57 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetParentID()
void MCHit::SetParentID (G4int parentID) inline
Definition at line 69 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetParticleID()
void MCHit::SetParticleID (G4int particle_id) inline
Definition at line 42 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetParticleName()
void MCHit::SetParticleName (G4String pName) inline
Definition at line 45 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetPosition()
void MCHit::SetPosition (G4ThreeVector pos) inline
Definition at line 48 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetTime()
void MCHit::SetTime (G4double time) inline
Definition at line 63 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetTrackID()
void MCHit::SetTrackID (G4int tid) inline
Definition at line 66 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetVertex()
void MCHit::SetVertex (G4ThreeVector v0) inline
Definition at line 60 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetVertexKineticEnergy()
void MCHit::SetVertexKineticEnergy (G4double vke) inline
Definition at line 75 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetVertexMomentumDirection()
void MCHit::SetVertexMomentumDirection (G4ThreeVector vmd) inline
Definition at line 72 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
SetVolume()
void MCHit::SetVolume (G4String volume) inline
Definition at line 54 of file MCHit.hh.
Referenced by GenericSD::ProcessHits().
Member Data Documentation
fDE
G4double MCHit::fDE private
Definition at line 29 of file MCHit.hh.
Referenced by GetDE().
fMomentum
G4ThreeVector MCHit::fMomentum private
Definition at line 31 of file MCHit.hh.
Referenced by GetMomentum().
fName
G4String MCHit::fName private
Definition at line 27 of file MCHit.hh.
Referenced by GetParticleName().
fParentID
G4int MCHit::fParentID private
Definition at line 35 of file MCHit.hh.
Referenced by GetParentID().
fPid
G4int MCHit::fPid private
Definition at line 26 of file MCHit.hh.
Referenced by GetParticleID().
fPosition
G4ThreeVector MCHit::fPosition private
Definition at line 28 of file MCHit.hh.
Referenced by GetPosition().
fTime
G4double MCHit::fTime private
Definition at line 33 of file MCHit.hh.
Referenced by GetTime().
fTrackID
G4int MCHit::fTrackID private
Definition at line 34 of file MCHit.hh.
Referenced by GetTrackID().
fVertex
G4ThreeVector MCHit::fVertex private
Definition at line 32 of file MCHit.hh.
Referenced by GetVertex().
fVertexKineticEnergy
G4double MCHit::fVertexKineticEnergy private
Definition at line 37 of file MCHit.hh.
Referenced by GetVertexKineticEnergy().
fVertexMomentumDirection
G4ThreeVector MCHit::fVertexMomentumDirection private
Definition at line 36 of file MCHit.hh.
Referenced by GetVertexMomentumDirection().
fVolume
G4String MCHit::fVolume private
Definition at line 30 of file MCHit.hh.
Referenced by GetVolume().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/db2g4/MCHit.hh
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/db2g4/MCHit.cc