Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/macros/Daemon4MainDaq.C File Reference
Daemon4MainDaq.C File Reference
Functions
bool FindExistingRuns (vector< int > &list_run)
Daemon4MainDaq.C.
void StartDecoder (const int run, const int n_evt=0, const bool is_online=true)
int Daemon4MainDaq (const int interval=30)
Function Documentation
int Daemon4MainDaq (const int interval = 30)
Definition at line 58 of file Daemon4MainDaq.C.
References FindExistingRuns(), run(), and StartDecoder().
bool FindExistingRuns (vector< int > & list_run)
Daemon4MainDaq.C.
Definition at line 6 of file Daemon4MainDaq.C.
References UtilOnline::CodaFile2RunNum(), UtilOnline::GetCodaFileDir(), and run().
Referenced by Daemon4MainDaq().
void StartDecoder (const int run, const int n_evt = 0, const bool is_online = true)
Definition at line 29 of file Daemon4MainDaq.C.
Referenced by Daemon4MainDaq().