Class Reference for E1039 Core & Analysis Software: PHNodeOperation Class Reference
PHNodeOperation Class Reference abstract
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHNodeOperation.h>
Public Member Functions
PHNodeOperation ()
virtual ~PHNodeOperation ()
void operator() (PHNode &o)
void operator() (PHNode *o)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Protected Member Functions
virtual void perform (PHNode *)=0
Protected Attributes
int verbosity
Detailed Description
Definition at line 10 of file PHNodeOperation.h.
Constructor & Destructor Documentation
PHNodeOperation()
PHNodeOperation::PHNodeOperation () inline
Definition at line 13 of file PHNodeOperation.h.
~PHNodeOperation()
virtual PHNodeOperation::~PHNodeOperation () inline virtual
Definition at line 17 of file PHNodeOperation.h.
Member Function Documentation
operator()() [1/2]
void PHNodeOperation::operator() (PHNode & o) inline
Definition at line 19 of file PHNodeOperation.h.
References perform().
operator()() [2/2]
void PHNodeOperation::operator() (PHNode * o) inline
Definition at line 24 of file PHNodeOperation.h.
References perform().
perform()
virtual void PHNodeOperation::perform (PHNode *) protected pure virtual
Implemented in PHNodeReset.
Referenced by operator()().
Verbosity() [1/2]
virtual int PHNodeOperation::Verbosity () const inline virtual
Definition at line 30 of file PHNodeOperation.h.
References verbosity.
Verbosity() [2/2]
virtual void PHNodeOperation::Verbosity (const int i) inline virtual
Definition at line 29 of file PHNodeOperation.h.
References verbosity.
Referenced by Fun4AllServer::ResetNodeTree().
Member Data Documentation
verbosity
int PHNodeOperation::verbosity protected
Definition at line 33 of file PHNodeOperation.h.
Referenced by Verbosity().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHNodeOperation.h