Class Reference for E1039 Core & Analysis Software: PHG4ConeSteppingAction Class Reference
PHG4ConeSteppingAction Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4ConeSteppingAction.h>
Public Member Functions
PHG4ConeSteppingAction (PHG4ConeDetector *)
constructor
virtual ~PHG4ConeSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 11 of file PHG4ConeSteppingAction.h.
Constructor & Destructor Documentation
PHG4ConeSteppingAction::PHG4ConeSteppingAction (PHG4ConeDetector * detector)
constructor
Definition at line 18 of file PHG4ConeSteppingAction.cc.
PHG4ConeSteppingAction::~PHG4ConeSteppingAction () virtual
destructor
Definition at line 25 of file PHG4ConeSteppingAction.cc.
Member Function Documentation
void PHG4ConeSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 161 of file PHG4ConeSteppingAction.cc.
References PHG4Detector::GetName(), and PHG4ConeDetector::SuperDetector().
Referenced by PHG4ConeSubsystem::process_event().
bool PHG4ConeSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 35 of file PHG4ConeSteppingAction.cc.
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), PHG4Hit::get_edep(), PHG4Hit::get_hit_id(), PHG4ConeDetector::get_Layer(), PHG4HitContainer::GetID(), PHG4ConeDetector::IsInConeActive(), NULL, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4ConeSteppingAction.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4ConeSteppingAction.cc