SeaQuest Offline Software: PHG4SteppingAction Class Reference
PHG4SteppingAction Class Reference abstract
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4main/PHG4SteppingAction.h>
Public Member Functions
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual bool UserSteppingAction (const G4Step *step, bool was_used)=0
stepping action. This defines processing of a single step in a given volume
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void SetInterfacePointers (PHCompositeNode *)
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Protected Attributes
int verbosity
std::string name
Private Attributes
std::set< std::string > _ScintLightYieldMissingMaterial
std::map< std::string, int > opt_int
Detailed Description
Definition at line 12 of file PHG4SteppingAction.h.
Constructor & Destructor Documentation
PHG4SteppingAction::PHG4SteppingAction (const int i = 0) inline
Definition at line 16 of file PHG4SteppingAction.h.
virtual PHG4SteppingAction::~PHG4SteppingAction () inline virtual
Definition at line 21 of file PHG4SteppingAction.h.
Member Function Documentation
int PHG4SteppingAction::GetIntOpt (const std::string & name)
Definition at line 167 of file PHG4SteppingAction.cc.
Referenced by PHG4OuterHcalSteppingAction::Init().
std::string PHG4SteppingAction::GetName () const inline
Definition at line 53 of file PHG4SteppingAction.h.
References name.
Referenced by PHG4SiliconTrackerSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), and PHG4SpacalSteppingAction::UserSteppingAction().
double PHG4SteppingAction::GetScintLightYield (const G4Step * step) virtual
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
Definition at line 31 of file PHG4SteppingAction.cc.
double PHG4SteppingAction::GetVisibleEnergyDeposition (const G4Step * step) virtual
get amount of energy that can make scintillation light, in Unit of GeV.
Definition at line 95 of file PHG4SteppingAction.cc.
Referenced by PHG4Prototype2InnerHcalSteppingAction::UserSteppingAction(), PHG4Prototype2OuterHcalSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4SpacalPrototypeSteppingAction::UserSteppingAction().
virtual int PHG4SteppingAction::Init () inline virtual
Reimplemented in PHG4OuterHcalSteppingAction.
Definition at line 35 of file PHG4SteppingAction.h.
Referenced by PHG4OuterHcalSubsystem::InitRunSubsystem(), and PHG4PSTOFSubsystem::InitRunSubsystem().
bool PHG4SteppingAction::IntOptExist (const std::string & name)
Definition at line 157 of file PHG4SteppingAction.cc.
virtual void PHG4SteppingAction::Print (const std::string & what) const inline virtual
Definition at line 48 of file PHG4SteppingAction.h.
Referenced by PHG4Prototype2InnerHcalSubsystem::Print(), PHG4TargetCoilSubsystem::Print(), PHG4CylinderSubsystem::Print(), PHG4PolyconSubsystem::Print(), PHG4InnerHcalSubsystem::Print(), and PHG4BNLTargetCoilSubsystem::Print().
virtual void PHG4SteppingAction::SetInterfacePointers (PHCompositeNode *) inline virtual
Reimplemented in PHG4SpacalPrototypeSteppingAction, PHG4SpacalSteppingAction, PHG4ForwardEcalSteppingAction, PHG4ForwardHcalSteppingAction, PHG4HcalPrototypeSteppingAction, PHG4BNLTargetCoilSteppingAction, PHG4CrystalCalorimeterSteppingAction, PHG4CylinderSteppingAction, PHG4OuterHcalSteppingAction, PHG4PolyconSteppingAction, PHG4TargetCoilSteppingAction, PHG4ConeSteppingAction, PHG4HcalSteppingAction, PHG4mRICHSteppingAction, PHG4SectorSteppingAction, PHG4BlockSteppingAction, PHG4CEmcTestBeamSteppingAction, PHG4CollimatorSteppingAction, PHG4InnerHcalSteppingAction, PHG4MapsSteppingAction, PHG4EnvelopeSteppingAction, PHG4Prototype2InnerHcalSteppingAction, PHG4Prototype2OuterHcalSteppingAction, PHG4PSTOFSteppingAction, PHG4SiliconTrackerSteppingAction, and PHG4FPbScSteppingAction.
Definition at line 46 of file PHG4SteppingAction.h.
Referenced by PHG4BlockSubsystem::process_event(), PHG4CollimatorSubsystem::process_event(), PHG4SpacalPrototypeSubsystem::process_event(), PHG4Prototype2InnerHcalSubsystem::process_event(), PHG4BNLTargetCoilSubsystem::process_event(), PHG4Prototype2OuterHcalSubsystem::process_event(), PHG4PolyconSubsystem::process_event(), PHG4CylinderSubsystem::process_event(), PHG4OuterHcalSubsystem::process_event(), PHG4InnerHcalSubsystem::process_event(), PHG4TargetCoilSubsystem::process_event(), PHG4mRICHSubsystem::process_event(), PHG4SiliconTrackerSubsystem::process_event(), and PHG4PSTOFSubsystem::process_event().
void PHG4SteppingAction::SetOpt (const std::string & name, const int i) inline
Definition at line 50 of file PHG4SteppingAction.h.
References name, and opt_int.
Referenced by PHG4OuterHcalSubsystem::InitRunSubsystem().
void PHG4SteppingAction::StoreLocalCoordinate (PHG4Hit * hit, const G4Step * step, const bool do_prepoint, const bool do_postpoint) virtual
Extract local coordinate of the hit and save to PHG4Hit.
Definition at line 119 of file PHG4SteppingAction.cc.
References PHG4Hit::set_local_x(), PHG4Hit::set_local_y(), and PHG4Hit::set_local_z().
Referenced by PHG4MapsSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), and PHG4SpacalPrototypeSteppingAction::UserSteppingAction().
virtual bool PHG4SteppingAction::UserSteppingAction (const G4Step * step, bool was_used) pure virtual
stepping action. This defines processing of a single step in a given volume
returns true if hits associated to this step was processed by this detector
Parameters
step pointer to the geant 4 step class
was_used true if the hit was already used by a previously registered subsystem
Implemented in PHG4SpacalPrototypeSteppingAction, PHG4SpacalSteppingAction, PHG4ForwardEcalSteppingAction, PHG4ForwardHcalSteppingAction, PHG4HcalPrototypeSteppingAction, PHG4BNLTargetCoilSteppingAction, PHG4CrystalCalorimeterSteppingAction, PHG4CylinderSteppingAction, PHG4PolyconSteppingAction, PHG4TargetCoilSteppingAction, PHG4ConeSteppingAction, PHG4HcalSteppingAction, PHG4mRICHSteppingAction, PHG4SectorSteppingAction, PHG4BlockSteppingAction, PHG4CEmcTestBeamSteppingAction, PHG4CollimatorSteppingAction, PHG4InnerHcalSteppingAction, PHG4MapsSteppingAction, PHG4OuterHcalSteppingAction, PHG4EnvelopeSteppingAction, PHG4Prototype2InnerHcalSteppingAction, PHG4Prototype2OuterHcalSteppingAction, PHG4PSTOFSteppingAction, PHG4TruthSteppingAction, PHG4SiliconTrackerSteppingAction, and PHG4FPbScSteppingAction.
virtual void PHG4SteppingAction::Verbosity (const int i) inline virtual
Definition at line 32 of file PHG4SteppingAction.h.
References verbosity.
int PHG4SteppingAction::Verbosity () const inline
Definition at line 33 of file PHG4SteppingAction.h.
References verbosity.
Referenced by PHG4OuterHcalSteppingAction::SetInterfacePointers().
Member Data Documentation
std::set<std::string> PHG4SteppingAction::_ScintLightYieldMissingMaterial private
Definition at line 59 of file PHG4SteppingAction.h.
std::string PHG4SteppingAction::name protected
Definition at line 56 of file PHG4SteppingAction.h.
Referenced by PHG4CrystalCalorimeterSteppingAction::FindTowerIndex2LevelUp(), GetName(), PHG4InnerHcalSteppingAction::PHG4InnerHcalSteppingAction(), PHG4OuterHcalSteppingAction::PHG4OuterHcalSteppingAction(), and SetOpt().
std::map<std::string, int> PHG4SteppingAction::opt_int private
Definition at line 60 of file PHG4SteppingAction.h.
Referenced by SetOpt().
int PHG4SteppingAction::verbosity protected
Definition at line 55 of file PHG4SteppingAction.h.
Referenced by PHG4SiliconTrackerSteppingAction::SetInterfacePointers(), PHG4Prototype2InnerHcalSteppingAction::SetInterfacePointers(), PHG4Prototype2OuterHcalSteppingAction::SetInterfacePointers(), PHG4InnerHcalSteppingAction::SetInterfacePointers(), PHG4MapsSteppingAction::SetInterfacePointers(), PHG4CEmcTestBeamSteppingAction::SetInterfacePointers(), PHG4HcalSteppingAction::SetInterfacePointers(), PHG4mRICHSteppingAction::SetInterfacePointers(), PHG4CrystalCalorimeterSteppingAction::SetInterfacePointers(), PHG4ForwardEcalSteppingAction::SetInterfacePointers(), PHG4ForwardHcalSteppingAction::SetInterfacePointers(), PHG4HcalPrototypeSteppingAction::SetInterfacePointers(), PHG4SpacalSteppingAction::SetInterfacePointers(), PHG4SpacalPrototypeSteppingAction::SetInterfacePointers(), PHG4SiliconTrackerSteppingAction::UserSteppingAction(), PHG4MapsSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), PHG4SpacalPrototypeSteppingAction::UserSteppingAction(), and Verbosity().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4main/PHG4SteppingAction.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4main/PHG4SteppingAction.cc