Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/CodaInputManager.h File Reference
CodaInputManager.h File Reference
#include <cstdlib>
#include <iostream>
#include <vector>
#include <map>
#include <string>
Classes
class CodaInputManager
Enumerations
enum { PHYSICS_EVENT = 0x10cc }
enum { CODA_EVENT = 0x01cc }
enum { FEE_PREFIX = 0x0100 }
enum { PRESTART_EVENT = 0x001101cc }
enum { GO_EVENT = 0x001201cc }
enum { END_EVENT = 0x001401cc }
enum { FEE_EVENT = 0x00840100 }
enum { STANDARD_PHYSICS = 14 }
enum { FLUSH_EVENTS = 10 }
enum { SLOW_CONTROL = 130 }
enum { RUN_DESCRIPTOR = 140 }
enum { PRESTART_INFO = 150 }
enum { BEGIN_SPILL = 11 }
enum { END_SPILL = 12 }
enum { SPILL_COUNTER = 129 }
Functions
int get_hex_bits (unsigned int hexNum, int numBitFromRight, int numBits)
int get_hex_bit (unsigned int hexNum, int numBitFromRight)
int get_bin_bits (unsigned int binNum, int numBitFromRight, int numBits)
int get_bin_bit (unsigned int binNum, int numBitFromRight)
void Abort (const char *message)
void PrintWords (int *words, int idx_begin, int idx_end, int idx_atte=-1)
void PrintCodaEventSummary (int *words)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
END_EVENT
Definition at line 48 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
FEE_EVENT
Definition at line 49 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
STANDARD_PHYSICS
Definition at line 51 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
FLUSH_EVENTS
Definition at line 52 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
SLOW_CONTROL
Definition at line 53 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
RUN_DESCRIPTOR
Definition at line 54 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
PRESTART_INFO
Definition at line 55 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
BEGIN_SPILL
Definition at line 56 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
END_SPILL
Definition at line 57 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
SPILL_COUNTER
Definition at line 58 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
PHYSICS_EVENT
Definition at line 43 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
CODA_EVENT
Definition at line 44 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
FEE_PREFIX
Definition at line 45 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
PRESTART_EVENT
Definition at line 46 of file CodaInputManager.h.
anonymous enum
anonymous enum
Enumerator
GO_EVENT
Definition at line 47 of file CodaInputManager.h.
Function Documentation
Abort()
void Abort (const char * message)
Definition at line 234 of file CodaInputManager.cc.
get_bin_bit()
int get_bin_bit (unsigned int binNum, int numBitFromRight)
This function takes an integer, grabs a certain binary digit from a certain position in the binary number.
For example, if number = 11010001101011100 (or, 0d107356) then get_bin_bit(number, 3) would return 1 (or 0d01), representing 11010001101011100 <– this part of the number ^
Definition at line 194 of file CodaInputManager.cc.
Referenced by get_bin_bits().
get_bin_bits()
int get_bin_bits (unsigned int binNum, int numBitFromRight, int numBits)
This function takes an integer, grabs a certain number of binary digits from a certain position in the binary number.
For example, if number = 11010001101011100, then get_bin_bits(number, 3, 3) would return 110 (or 0d06), representing 11010001101011100 <– those parts of the number ^^^
Definition at line 212 of file CodaInputManager.cc.
References get_bin_bit().
get_hex_bit()
int get_hex_bit (unsigned int hexNum, int numBitFromRight)
This function takes an integer, grabs a certain number of hexadecimal digits from a certain position in the hex representation of the number.
For example, if number = 0x10e59c (or, 0d107356) then get_hex_bit(number, 3) would return e (or 0d14), representing 0x10e59c <– those parts of the number
Definition at line 141 of file CodaInputManager.cc.
get_hex_bits()
int get_hex_bits (unsigned int hexNum, int numBitFromRight, int numBits)
This function takes an integer, grabs a certain number of hexadecimal digits from a certain position in the hex representation of the number.
For example, if number = 0x10e59c (or, 0d107356) then get_bin_bits(number, 3, 3) would return e59 (or 0d3673), representing 0x10e59c <– those parts of the number ^^^
Definition at line 161 of file CodaInputManager.cc.
Referenced by PrintCodaEventSummary().
PrintCodaEventSummary()
void PrintCodaEventSummary (int * words)
Print out lists of ROCs and boards found in one Coda event.
This function might be useful when you check the word format independent of all main functions (like ProcessPhysFlush() & format()). But you should not assume that the output of this function is always consistent with those of the main functions, since this function decodes words by itself.
Definition at line 260 of file CodaInputManager.cc.
References get_hex_bits().
PrintWords()
void PrintWords (int * words, int idx_begin, int idx_end, int idx_atte = -1)
Definition at line 240 of file CodaInputManager.cc.