E1039 Software: PHG4ConeRegionSteppingAction Class Reference
PHG4ConeRegionSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4ConeRegionSteppingAction.h>
Public Member Functions
PHG4ConeRegionSteppingAction (PHG4ConeDetector *)
constructor
virtual ~PHG4ConeRegionSteppingAction ()
destroctor
virtual void UserSteppingAction (const G4Step *)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Private Attributes
PHG4ConeDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4Hit * hit
Detailed Description
Definition at line 12 of file PHG4ConeRegionSteppingAction.h.
Constructor & Destructor Documentation
PHG4ConeRegionSteppingAction()
PHG4ConeRegionSteppingAction::PHG4ConeRegionSteppingAction (PHG4ConeDetector * detector)
constructor
Definition at line 18 of file PHG4ConeRegionSteppingAction.cc.
~PHG4ConeRegionSteppingAction()
virtual PHG4ConeRegionSteppingAction::~PHG4ConeRegionSteppingAction () inline virtual
destroctor
Definition at line 21 of file PHG4ConeRegionSteppingAction.h.
References SetInterfacePointers(), and UserSteppingAction().
Member Function Documentation
SetInterfacePointers()
void PHG4ConeRegionSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Definition at line 110 of file PHG4ConeRegionSteppingAction.cc.
References detector_, PHG4Detector::GetName(), and hits_.
Referenced by ~PHG4ConeRegionSteppingAction().
UserSteppingAction()
void PHG4ConeRegionSteppingAction::UserSteppingAction (const G4Step * aStep) virtual
stepping action
Definition at line 23 of file PHG4ConeRegionSteppingAction.cc.
References PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_hit_id(), PHG4HitContainer::GetID(), hit, hits_, PHG4ConeDetector::IsInConeActive(), PHG4Hit::set_edep(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Referenced by ~PHG4ConeRegionSteppingAction().
Member Data Documentation
detector_
PHG4ConeDetector* PHG4ConeRegionSteppingAction::detector_ private
pointer to the detector
Definition at line 33 of file PHG4ConeRegionSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
hit
PHG4Hit* PHG4ConeRegionSteppingAction::hit private
Definition at line 37 of file PHG4ConeRegionSteppingAction.h.
Referenced by UserSteppingAction().
hits_
PHG4HitContainer* PHG4ConeRegionSteppingAction::hits_ private
pointer to hit container
Definition at line 36 of file PHG4ConeRegionSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4ConeRegionSteppingAction.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4ConeRegionSteppingAction.cc