Class Reference for E1039 Core & Analysis Software: SQHardEvent Class Reference
SQHardEvent Class Reference abstract
An SQ interface class to hold one hardware-related event info.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHardEvent.h>
Public Member Functions
virtual ~SQHardEvent ()
virtual void Reset ()=0
Clear Event.
virtual void identify (std::ostream &os=std::cout) const =0
virtual int isValid () const =0
isValid returns non zero if object contains vailid data
virtual SQHardEvent * Clone () const =0
virtual int get_coda_event_id () const =0
Return the Coda-event ID, which is unique per run.
virtual void set_coda_event_id (const int a)=0
virtual int get_vme_time () const =0
Return the VME time.
virtual void set_vme_time (const int a)=0
virtual int get_raw_matrix (const unsigned short i) const =0
Return the raw count of the selected trigger channel.
virtual void set_raw_matrix (const unsigned short i, const bool a)=0
virtual int get_after_inh_matrix (const unsigned short i) const =0
Return the after-inhibited count of the selected trigger channel.
virtual void set_after_inh_matrix (const unsigned short i, const bool a)=0
virtual short get_flag_v1495 () const =0
Return the quality flag of the V1495 readout.
virtual void set_flag_v1495 (const short a)=0
virtual short get_n_board_qie () const =0
Return the number of QIE boards read out.
virtual void set_n_board_qie (const short a)=0
virtual short get_n_board_v1495 () const =0
Return the number of V1495 boards read out.
virtual void set_n_board_v1495 (const short a)=0
virtual short get_n_board_taiwan () const =0
Return the number of Taiwan-TDC boards read out.
virtual void set_n_board_taiwan (const short a)=0
virtual short get_n_board_trig_bit () const =0
Return the number of trigger-bit boards read out.
virtual void set_n_board_trig_bit (const short a)=0
virtual short get_n_board_trig_count () const =0
Return the number of trigger-count boards read out.
virtual void set_n_board_trig_count (const short a)=0
ClassDef (SQHardEvent, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQHardEvent ()
Detailed Description
An SQ interface class to hold one hardware-related event info.
Definition at line 7 of file SQHardEvent.h.
Constructor & Destructor Documentation
SQHardEvent()
SQHardEvent::SQHardEvent () inline protected
Definition at line 9 of file SQHardEvent.h.
~SQHardEvent()
virtual SQHardEvent::~SQHardEvent () inline virtual
Definition at line 12 of file SQHardEvent.h.
Member Function Documentation
ClassDef()
SQHardEvent::ClassDef (SQHardEvent , 1)
Clone()
virtual SQHardEvent* SQHardEvent::Clone () const pure virtual
Implemented in SQHardEvent_v1.
get_after_inh_matrix()
virtual int SQHardEvent::get_after_inh_matrix (const unsigned short i) const pure virtual
Return the after-inhibited count of the selected trigger channel.
Implemented in SQHardEvent_v1.
get_coda_event_id()
virtual int SQHardEvent::get_coda_event_id () const pure virtual
Return the Coda-event ID, which is unique per run.
Implemented in SQHardEvent_v1.
Referenced by AnaHardEvent::process_event().
get_flag_v1495()
virtual short SQHardEvent::get_flag_v1495 () const pure virtual
Return the quality flag of the V1495 readout.
Implemented in SQHardEvent_v1.
Referenced by OnlMonMainDaq::ProcessEventOnlMon().
get_n_board_qie()
virtual short SQHardEvent::get_n_board_qie () const pure virtual
Return the number of QIE boards read out.
Implemented in SQHardEvent_v1.
Referenced by CalibEvtQual::process_event(), and OnlMonQie::ProcessEventOnlMon().
get_n_board_taiwan()
virtual short SQHardEvent::get_n_board_taiwan () const pure virtual
Return the number of Taiwan-TDC boards read out.
Implemented in SQHardEvent_v1.
Referenced by AnaHardEvent::process_event(), CalibEvtQual::process_event(), and OnlMonMainDaq::ProcessEventOnlMon().
get_n_board_trig_bit()
virtual short SQHardEvent::get_n_board_trig_bit () const pure virtual
Return the number of trigger-bit boards read out.
Implemented in SQHardEvent_v1.
Referenced by CalibEvtQual::process_event().
get_n_board_trig_count()
virtual short SQHardEvent::get_n_board_trig_count () const pure virtual
Return the number of trigger-count boards read out.
Implemented in SQHardEvent_v1.
Referenced by CalibEvtQual::process_event().
get_n_board_v1495()
virtual short SQHardEvent::get_n_board_v1495 () const pure virtual
Return the number of V1495 boards read out.
Implemented in SQHardEvent_v1.
Referenced by CalibEvtQual::process_event().
get_raw_matrix()
virtual int SQHardEvent::get_raw_matrix (const unsigned short i) const pure virtual
Return the raw count of the selected trigger channel.
Implemented in SQHardEvent_v1.
get_vme_time()
virtual int SQHardEvent::get_vme_time () const pure virtual
Return the VME time.
Implemented in SQHardEvent_v1.
identify()
virtual void SQHardEvent::identify (std::ostream & os = std::cout) const pure virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Implemented in SQHardEvent_v1.
isValid()
virtual int SQHardEvent::isValid () const pure virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Implemented in SQHardEvent_v1.
Reset()
virtual void SQHardEvent::Reset () pure virtual
Clear Event.
Reimplemented from PHObject.
Implemented in SQHardEvent_v1.
set_after_inh_matrix()
virtual void SQHardEvent::set_after_inh_matrix (const unsigned short i, const bool a) pure virtual
Implemented in SQHardEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_coda_event_id()
virtual void SQHardEvent::set_coda_event_id (const int a) pure virtual
Implemented in SQHardEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_flag_v1495()
virtual void SQHardEvent::set_flag_v1495 (const short a) pure virtual
Implemented in SQHardEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_n_board_qie()
virtual void SQHardEvent::set_n_board_qie (const short a) pure virtual
Implemented in SQHardEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_n_board_taiwan()
virtual void SQHardEvent::set_n_board_taiwan (const short a) pure virtual
Implemented in SQHardEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_n_board_trig_bit()
virtual void SQHardEvent::set_n_board_trig_bit (const short a) pure virtual
Implemented in SQHardEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_n_board_trig_count()
virtual void SQHardEvent::set_n_board_trig_count (const short a) pure virtual
Implemented in SQHardEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_n_board_v1495()
virtual void SQHardEvent::set_n_board_v1495 (const short a) pure virtual
Implemented in SQHardEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_raw_matrix()
virtual void SQHardEvent::set_raw_matrix (const unsigned short i, const bool a) pure virtual
Implemented in SQHardEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_vme_time()
virtual void SQHardEvent::set_vme_time (const int a) pure virtual
Implemented in SQHardEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHardEvent.h