E1039 Software: PHG4E1039InsensDetector Class Reference
PHG4E1039InsensDetector Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4E1039InsensDetector.h>
Public Member Functions
PHG4E1039InsensDetector (PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam="BLOCK", const int lyr=0)
constructor
virtual ~PHG4E1039InsensDetector (void)
destructor
virtual void Construct (G4LogicalVolume *world)
construct
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
const double GetFmagCenter ()
const double GetFmagLength ()
void SetTargetMaterial (std::string)
void IronToggle (bool)
void ReloadMagField ()
volume accessors
bool IsInBlock (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Public Attributes
double fmagCenter
double fmagLength
double z1v
double z2v
double z1h
double z2h
std::vector< G4Element * > elementVec
std::vector< G4Material * > materialVec
std::vector< G4VSolid * > solidVec
std::vector< G4LogicalVolume * > logicalVolumeVec
std::vector< G4RotationMatrix * > rotationMatrixVec
Private Member Functions
int AssignAttributes (G4VPhysicalVolume *)
Private Attributes
PHParameters * params
G4VPhysicalVolume * block_physi
int layer
std::string superdetector
G4VPhysicalVolume * physiWorld
MYSQL * con
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 27 of file PHG4E1039InsensDetector.h.
Constructor & Destructor Documentation
PHG4E1039InsensDetector()
PHG4E1039InsensDetector::PHG4E1039InsensDetector (PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam = "BLOCK", const int lyr = 0)
constructor
Definition at line 30 of file PHG4E1039InsensDetector.cc.
~PHG4E1039InsensDetector()
virtual PHG4E1039InsensDetector::~PHG4E1039InsensDetector (void) inline virtual
destructor
Definition at line 36 of file PHG4E1039InsensDetector.h.
References Construct(), and IsInBlock().
Member Function Documentation
AssignAttributes()
int PHG4E1039InsensDetector::AssignAttributes (G4VPhysicalVolume *) private
Construct()
void PHG4E1039InsensDetector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 51 of file PHG4E1039InsensDetector.cc.
References con, elementVec, logicalVolumeVec, materialVec, PHG4Detector::name, NULL, physiWorld, rotationMatrixVec, and solidVec.
Referenced by ~PHG4E1039InsensDetector().
get_Layer()
int PHG4E1039InsensDetector::get_Layer () const inline
Definition at line 49 of file PHG4E1039InsensDetector.h.
References layer.
Referenced by PHG4E1039InsensSteppingAction::UserSteppingAction().
GetFmagCenter()
const double PHG4E1039InsensDetector::GetFmagCenter () inline
Definition at line 73 of file PHG4E1039InsensDetector.h.
References fmagCenter.
GetFmagLength()
const double PHG4E1039InsensDetector::GetFmagLength () inline
Definition at line 74 of file PHG4E1039InsensDetector.h.
References fmagLength, IronToggle(), ReloadMagField(), and SetTargetMaterial().
IronToggle()
void PHG4E1039InsensDetector::IronToggle (bool)
Referenced by GetFmagLength().
IsInBlock()
bool PHG4E1039InsensDetector::IsInBlock (G4VPhysicalVolume * volume) const
Definition at line 38 of file PHG4E1039InsensDetector.cc.
References block_physi.
Referenced by PHG4E1039InsensSteppingAction::UserSteppingAction(), and ~PHG4E1039InsensDetector().
ReloadMagField()
void PHG4E1039InsensDetector::ReloadMagField ()
Referenced by GetFmagLength().
SetTargetMaterial()
void PHG4E1039InsensDetector::SetTargetMaterial (std::string)
Referenced by GetFmagLength().
SuperDetector() [1/2]
void PHG4E1039InsensDetector::SuperDetector (const std::string & name) inline
Definition at line 47 of file PHG4E1039InsensDetector.h.
References PHG4Detector::name, and superdetector.
Referenced by PHG4E1039InsensSubsystem::InitRunSubsystem(), and PHG4E1039InsensSteppingAction::SetInterfacePointers().
SuperDetector() [2/2]
const std::string PHG4E1039InsensDetector::SuperDetector () const inline
Definition at line 48 of file PHG4E1039InsensDetector.h.
References superdetector.
Member Data Documentation
block_physi
G4VPhysicalVolume* PHG4E1039InsensDetector::block_physi private
Definition at line 55 of file PHG4E1039InsensDetector.h.
Referenced by IsInBlock().
con
MYSQL* PHG4E1039InsensDetector::con private
Definition at line 84 of file PHG4E1039InsensDetector.h.
Referenced by Construct().
elementVec
std::vector<G4Element*> PHG4E1039InsensDetector::elementVec
Definition at line 67 of file PHG4E1039InsensDetector.h.
Referenced by Construct().
fmagCenter
double PHG4E1039InsensDetector::fmagCenter
Definition at line 63 of file PHG4E1039InsensDetector.h.
Referenced by GetFmagCenter().
fmagLength
double PHG4E1039InsensDetector::fmagLength
Definition at line 64 of file PHG4E1039InsensDetector.h.
Referenced by GetFmagLength().
layer
int PHG4E1039InsensDetector::layer private
Definition at line 58 of file PHG4E1039InsensDetector.h.
Referenced by get_Layer().
logicalVolumeVec
std::vector<G4LogicalVolume*> PHG4E1039InsensDetector::logicalVolumeVec
Definition at line 70 of file PHG4E1039InsensDetector.h.
Referenced by Construct().
materialVec
std::vector<G4Material*> PHG4E1039InsensDetector::materialVec
Definition at line 68 of file PHG4E1039InsensDetector.h.
Referenced by Construct().
params
PHParameters* PHG4E1039InsensDetector::params private
Definition at line 53 of file PHG4E1039InsensDetector.h.
physiWorld
G4VPhysicalVolume* PHG4E1039InsensDetector::physiWorld private
Definition at line 82 of file PHG4E1039InsensDetector.h.
Referenced by Construct().
rotationMatrixVec
std::vector<G4RotationMatrix*> PHG4E1039InsensDetector::rotationMatrixVec
Definition at line 71 of file PHG4E1039InsensDetector.h.
Referenced by Construct().
solidVec
std::vector<G4VSolid*> PHG4E1039InsensDetector::solidVec
Definition at line 69 of file PHG4E1039InsensDetector.h.
Referenced by Construct().
superdetector
std::string PHG4E1039InsensDetector::superdetector private
Definition at line 59 of file PHG4E1039InsensDetector.h.
Referenced by SuperDetector().
z1h
double PHG4E1039InsensDetector::z1h
Definition at line 65 of file PHG4E1039InsensDetector.h.
z1v
double PHG4E1039InsensDetector::z1v
Definition at line 65 of file PHG4E1039InsensDetector.h.
z2h
double PHG4E1039InsensDetector::z2h
Definition at line 65 of file PHG4E1039InsensDetector.h.
z2v
double PHG4E1039InsensDetector::z2v
Definition at line 65 of file PHG4E1039InsensDetector.h.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4E1039InsensDetector.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4E1039InsensDetector.cc