Class Reference for E1039 Core & Analysis Software: SyncObject Class Reference
SyncObject Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/SyncObject.h>
Public Member Functions
virtual ~SyncObject ()
dtor
virtual void Reset ()
Clear Sync.
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains valid data
virtual SyncObject * clone () const
Virtual copy constructor.
virtual SyncObject & operator= (const SyncObject &source)
virtual int Different (const SyncObject *other) const
virtual void EventCounter (const int)
set Event Counter
virtual void EventNumber (const int)
set Event Number
virtual void SegmentNumber (const int)
set Segment Number
virtual void RunNumber (const int)
set Run Number
virtual ~SyncObject ()
dtor
virtual void Reset ()
Clear Sync.
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains valid data
virtual SyncObject * clone () const
Virtual copy constructor.
virtual SyncObject & operator= (const SyncObject &source)
virtual int Different (const SyncObject *other) const
virtual void EventCounter (const int)
set Event Counter
virtual void EventNumber (const int)
set Event Number
virtual void SegmentNumber (const int)
set Segment Number
virtual void RunNumber (const int)
set Run Number
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
virtual int EventNumber () const
get Event Number
virtual int EventCounter () const
get Event Counter
virtual int RunNumber () const
get Run Number
virtual int SegmentNumber () const
get Segment Number
virtual int EventNumber () const
get Event Number
virtual int EventCounter () const
get Event Counter
virtual int RunNumber () const
get Run Number
virtual int SegmentNumber () const
get Segment Number
Friends
class SyncObjectv1
class SyncObjectv2
class Fun4AllDstInputManager
class DumpSyncObject
class SegmentSelect
Detailed Description
Definition at line 9 of file SyncObject.h.
Constructor & Destructor Documentation
~SyncObject() [1/2]
virtual SyncObject::~SyncObject () inline virtual
dtor
Definition at line 14 of file SyncObject.h.
~SyncObject() [2/2]
virtual SyncObject::~SyncObject () inline virtual
dtor
Definition at line 14 of file SyncObject.h.
Member Function Documentation
clone() [1/2]
SyncObject * SyncObject::clone () const virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SyncObjectv2, and SyncObjectv1.
Definition at line 28 of file SyncObject.cc.
References NULL.
Referenced by Fun4AllHitMatrixInputManager::GetSyncObject(), Fun4AllTrackQAv1InputManager::GetSyncObject(), Fun4AllVectEventInputManager::GetSyncObject(), Fun4AllDstInputManager::GetSyncObject(), Fun4AllPrdfInputManager::GetSyncObject(), Fun4AllEVIOInputManager::GetSyncObject(), Fun4AllSRawEventInputManager::GetSyncObject(), and Fun4AllRUSInputManager::GetSyncObject().
clone() [2/2]
virtual SyncObject* SyncObject::clone () const virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SyncObjectv2, and SyncObjectv1.
Different() [1/2]
int SyncObject::Different (const SyncObject * other) const virtual
Definition at line 47 of file SyncObject.cc.
References EventNumber(), and RunNumber().
Referenced by Fun4AllHitMatrixInputManager::SyncIt(), Fun4AllTrackQAv1InputManager::SyncIt(), Fun4AllVectEventInputManager::SyncIt(), Fun4AllDstInputManager::SyncIt(), Fun4AllPrdfInputManager::SyncIt(), Fun4AllEVIOInputManager::SyncIt(), Fun4AllSRawEventInputManager::SyncIt(), and Fun4AllRUSInputManager::SyncIt().
Different() [2/2]
virtual int SyncObject::Different (const SyncObject * other) const virtual
EventCounter() [1/4]
virtual int SyncObject::EventCounter () const inline protected virtual
get Event Counter
Reimplemented in SyncObjectv1.
Definition at line 49 of file SyncObject.h.
EventCounter() [2/4]
virtual int SyncObject::EventCounter () const inline protected virtual
get Event Counter
Reimplemented in SyncObjectv1.
Definition at line 49 of file SyncObject.h.
EventCounter() [3/4]
virtual void SyncObject::EventCounter (const int) inline virtual
set Event Counter
Reimplemented in SyncObjectv1.
Definition at line 33 of file SyncObject.h.
Referenced by operator=(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), Fun4AllVectEventInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllEVIOInputManager::run(), Fun4AllSRawEventInputManager::run(), Fun4AllRUSInputManager::run(), Fun4AllDstInputManager::SyncIt(), SyncObjectv1::SyncObjectv1(), and SyncObjectv2::SyncObjectv2().
EventCounter() [4/4]
virtual void SyncObject::EventCounter (const int) inline virtual
set Event Counter
Reimplemented in SyncObjectv1.
Definition at line 33 of file SyncObject.h.
EventNumber() [1/4]
virtual int SyncObject::EventNumber () const inline protected virtual
get Event Number
Reimplemented in SyncObjectv1.
Definition at line 47 of file SyncObject.h.
EventNumber() [2/4]
virtual int SyncObject::EventNumber () const inline protected virtual
get Event Number
Reimplemented in SyncObjectv1.
Definition at line 47 of file SyncObject.h.
EventNumber() [3/4]
virtual void SyncObject::EventNumber (const int) inline virtual
set Event Number
Reimplemented in SyncObjectv1.
Definition at line 36 of file SyncObject.h.
Referenced by Different(), operator=(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), Fun4AllVectEventInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllEVIOInputManager::run(), Fun4AllSRawEventInputManager::run(), Fun4AllRUSInputManager::run(), Fun4AllDstInputManager::SyncIt(), SyncObjectv1::SyncObjectv1(), and SyncObjectv2::SyncObjectv2().
EventNumber() [4/4]
virtual void SyncObject::EventNumber (const int) inline virtual
set Event Number
Reimplemented in SyncObjectv1.
Definition at line 36 of file SyncObject.h.
identify() [1/2]
void SyncObject::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SyncObjectv2, and SyncObjectv1.
Definition at line 15 of file SyncObject.cc.
Referenced by Fun4AllDstInputManager::SyncIt().
identify() [2/2]
virtual void SyncObject::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SyncObjectv2, and SyncObjectv1.
isValid() [1/2]
int SyncObject::isValid () const virtual
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Reimplemented in SyncObjectv1.
Definition at line 21 of file SyncObject.cc.
References PHWHERE.
isValid() [2/2]
virtual int SyncObject::isValid () const virtual
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Reimplemented in SyncObjectv1.
operator=() [1/2]
SyncObject & SyncObject::operator= (const SyncObject & source) virtual
Definition at line 35 of file SyncObject.cc.
References EventCounter(), EventNumber(), RunNumber(), and SegmentNumber().
operator=() [2/2]
virtual SyncObject& SyncObject::operator= (const SyncObject & source) virtual
Reset() [1/2]
void SyncObject::Reset () virtual
Clear Sync.
Reimplemented from PHObject.
Reimplemented in SyncObjectv2, and SyncObjectv1.
Definition at line 9 of file SyncObject.cc.
References PHWHERE.
Referenced by Fun4AllHitMatrixInputManager::ResetEvent(), Fun4AllTrackQAv1InputManager::ResetEvent(), Fun4AllVectEventInputManager::ResetEvent(), Fun4AllPrdfInputManager::ResetEvent(), Fun4AllEVIOInputManager::ResetEvent(), Fun4AllSRawEventInputManager::ResetEvent(), and Fun4AllRUSInputManager::ResetEvent().
Reset() [2/2]
virtual void SyncObject::Reset () virtual
Clear Sync.
Reimplemented from PHObject.
Reimplemented in SyncObjectv2, and SyncObjectv1.
RunNumber() [1/4]
virtual int SyncObject::RunNumber () const inline protected virtual
get Run Number
Reimplemented in SyncObjectv1.
Definition at line 51 of file SyncObject.h.
RunNumber() [2/4]
virtual int SyncObject::RunNumber () const inline protected virtual
get Run Number
Reimplemented in SyncObjectv1.
Definition at line 51 of file SyncObject.h.
RunNumber() [3/4]
virtual void SyncObject::RunNumber (const int) inline virtual
set Run Number
Reimplemented in SyncObjectv1.
Definition at line 43 of file SyncObject.h.
Referenced by Different(), operator=(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), Fun4AllVectEventInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllEVIOInputManager::run(), Fun4AllSRawEventInputManager::run(), Fun4AllRUSInputManager::run(), Fun4AllDstInputManager::SyncIt(), SyncObjectv1::SyncObjectv1(), and SyncObjectv2::SyncObjectv2().
RunNumber() [4/4]
virtual void SyncObject::RunNumber (const int) inline virtual
set Run Number
Reimplemented in SyncObjectv1.
Definition at line 43 of file SyncObject.h.
SegmentNumber() [1/4]
virtual int SyncObject::SegmentNumber () const inline protected virtual
get Segment Number
Reimplemented in SyncObjectv2.
Definition at line 53 of file SyncObject.h.
SegmentNumber() [2/4]
virtual int SyncObject::SegmentNumber () const inline protected virtual
get Segment Number
Reimplemented in SyncObjectv2.
Definition at line 53 of file SyncObject.h.
SegmentNumber() [3/4]
virtual void SyncObject::SegmentNumber (const int) inline virtual
set Segment Number
Reimplemented in SyncObjectv2.
Definition at line 40 of file SyncObject.h.
Referenced by operator=(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), Fun4AllVectEventInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllEVIOInputManager::run(), Fun4AllSRawEventInputManager::run(), Fun4AllRUSInputManager::run(), Fun4AllDstInputManager::SyncIt(), and SyncObjectv2::SyncObjectv2().
SegmentNumber() [4/4]
virtual void SyncObject::SegmentNumber (const int) inline virtual
set Segment Number
Reimplemented in SyncObjectv2.
Definition at line 40 of file SyncObject.h.
Friends And Related Function Documentation
DumpSyncObject
DumpSyncObject friend
Definition at line 59 of file SyncObject.h.
Fun4AllDstInputManager
Fun4AllDstInputManager friend
Definition at line 58 of file SyncObject.h.
SegmentSelect
SegmentSelect friend
Definition at line 60 of file SyncObject.h.
SyncObjectv1
friend class SyncObjectv1 friend
Definition at line 56 of file SyncObject.h.
SyncObjectv2
SyncObjectv2 friend
Definition at line 57 of file SyncObject.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/SyncObject.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/SyncObject.cc