E1039 Software: OnlMonComm Class Reference
OnlMonComm Class Reference
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/online/onlmonserver/OnlMonComm.h>
Public Types
enum SpillMode_t { SP_ALL, SP_LAST, SP_RANGE }
Public Member Functions
virtual ~OnlMonComm ()
void SetSpillMode (const SpillMode_t mode)
SpillMode_t GetSpillMode ()
void SetSpillSelectability (const bool val)
bool GetSpillSelectability ()
void SetSpillNum (const int num)
int GetSpillNum ()
void SetSpillRangeLow (const int sp)
void SetSpillRangeHigh (const int sp)
void SetSpillRange (const int sp_lo, const int sp_hi)
void GetSpillRange (int &sp_lo, int &sp_hi)
void SetMaxNumSelSpills (const int val)
int GetMaxNumSelSpills ()
int GetNumSpills ()
void ClearSpill ()
void AddSpill (const int id)
void FindFullSpillRange (int &id_min, int &id_max)
int ReceiveFullSpillRange ()
void GetFullSpillRange (int &id_min, int &id_max)
TSocket * ConnectServer ()
Static Public Member Functions
static OnlMonComm * instance ()
Protected Member Functions
OnlMonComm ()
Private Types
typedef std::vector< int > SpillList_t
Private Attributes
SpillMode_t m_sp_mode
int m_sp_num
int m_sp_lo
int m_sp_hi
int m_sp_min
int m_sp_max
bool m_sp_sel
int m_n_sp_sel_max
SpillList_t m_list_sp
Static Private Attributes
static OnlMonComm * m_inst = 0
Detailed Description
Definition at line 6 of file OnlMonComm.h.
Member Typedef Documentation
typedef std::vector<int> OnlMonComm::SpillList_t private
Definition at line 22 of file OnlMonComm.h.
Member Enumeration Documentation
enum OnlMonComm::SpillMode_t
Enumerator
SP_ALL
SP_LAST
SP_RANGE
Definition at line 8 of file OnlMonComm.h.
Constructor & Destructor Documentation
OnlMonComm::~OnlMonComm () virtual
Definition at line 35 of file OnlMonComm.cc.
OnlMonComm::OnlMonComm () protected
Definition at line 22 of file OnlMonComm.cc.
Member Function Documentation
void OnlMonComm::AddSpill (const int id)
Definition at line 62 of file OnlMonComm.cc.
References m_list_sp.
Referenced by OnlMonClient::process_event().
void OnlMonComm::ClearSpill () inline
Definition at line 47 of file OnlMonComm.h.
References m_list_sp.
TSocket * OnlMonComm::ConnectServer ()
Definition at line 111 of file OnlMonComm.cc.
References OnlMonServer::GetHost(), OnlMonServer::GetNumPorts(), OnlMonServer::GetPort(), OnlMonServer::GetPort0(), and OnlMonServer::SetPort().
Referenced by ReceiveFullSpillRange(), and OnlMonClient::ReceiveHist().
void OnlMonComm::FindFullSpillRange (int & id_min, int & id_max)
Definition at line 67 of file OnlMonComm.cc.
References m_list_sp.
Referenced by OnlMonServer::HandleConnection(), and OnlMonClient::SendHist().
void OnlMonComm::GetFullSpillRange (int & id_min, int & id_max)
Definition at line 105 of file OnlMonComm.cc.
References m_sp_max, and m_sp_min.
Referenced by OnlMonUI::HandleSpRadRange(), and OnlMonUI::UpdateFullSpillRange().
int OnlMonComm::GetMaxNumSelSpills () inline
Definition at line 44 of file OnlMonComm.h.
References m_n_sp_sel_max.
Referenced by OnlMonClient::process_event().
int OnlMonComm::GetNumSpills () inline
Definition at line 46 of file OnlMonComm.h.
References m_list_sp.
Referenced by OnlMonClient::process_event().
SpillMode_t OnlMonComm::GetSpillMode () inline
Definition at line 30 of file OnlMonComm.h.
References m_sp_mode.
int OnlMonComm::GetSpillNum () inline
Definition at line 36 of file OnlMonComm.h.
References m_sp_num.
Referenced by OnlMonClient::ReceiveHist().
void OnlMonComm::GetSpillRange (int & sp_lo, int & sp_hi)
Definition at line 56 of file OnlMonComm.cc.
References m_sp_hi, and m_sp_lo.
Referenced by OnlMonClient::ReceiveHist(), and OnlMonUI::SyncSpillRange().
bool OnlMonComm::GetSpillSelectability () inline
Definition at line 33 of file OnlMonComm.h.
References m_sp_sel.
Referenced by OnlMonServer::HandleConnection(), and OnlMonUI::UpdateFullSpillRange().
OnlMonComm * OnlMonComm::instance () static
Definition at line 16 of file OnlMonComm.cc.
Referenced by OnlMonUI::BuildInterface(), OnlMonClient::DisableSpillHist(), Fun4MainDaq(), OnlMonServer::HandleConnection(), OnlMonUI::HandleSpEntHi(), OnlMonUI::HandleSpEntLo(), OnlMonUI::HandleSpLastNum(), OnlMonUI::HandleSpRadAll(), OnlMonUI::HandleSpRadLast(), OnlMonUI::HandleSpRadRange(), OnlMonUI::HandleSpSlider(), OnlMonClient::process_event(), OnlMonClient::ReceiveHist(), OnlMonClient::SendHist(), OnlMonUI::SyncSpillRange(), and OnlMonUI::UpdateFullSpillRange().
int OnlMonComm::ReceiveFullSpillRange ()
Definition at line 78 of file OnlMonComm.cc.
References ConnectServer(), m_sp_max, m_sp_min, and m_sp_sel.
Referenced by OnlMonUI::UpdateFullSpillRange().
void OnlMonComm::SetMaxNumSelSpills (const int val) inline
Definition at line 43 of file OnlMonComm.h.
References m_n_sp_sel_max.
Referenced by Fun4MainDaq().
void OnlMonComm::SetSpillMode (const SpillMode_t mode) inline
Definition at line 29 of file OnlMonComm.h.
References m_sp_mode.
Referenced by OnlMonUI::HandleSpRadAll(), OnlMonUI::HandleSpRadLast(), and OnlMonUI::HandleSpRadRange().
void OnlMonComm::SetSpillNum (const int num) inline
Definition at line 35 of file OnlMonComm.h.
References m_sp_num.
Referenced by OnlMonUI::HandleSpLastNum().
void OnlMonComm::SetSpillRange (const int sp_lo, const int sp_hi)
Definition at line 50 of file OnlMonComm.cc.
References m_sp_hi, and m_sp_lo.
Referenced by OnlMonUI::HandleSpRadRange(), and OnlMonUI::HandleSpSlider().
void OnlMonComm::SetSpillRangeHigh (const int sp)
Definition at line 45 of file OnlMonComm.cc.
References m_sp_hi.
Referenced by OnlMonUI::HandleSpEntHi().
void OnlMonComm::SetSpillRangeLow (const int sp)
Definition at line 40 of file OnlMonComm.cc.
References m_sp_lo.
Referenced by OnlMonUI::HandleSpEntLo().
void OnlMonComm::SetSpillSelectability (const bool val) inline
Definition at line 32 of file OnlMonComm.h.
References m_sp_sel.
Referenced by OnlMonClient::DisableSpillHist().
Member Data Documentation
OnlMonComm * OnlMonComm::m_inst = 0 static private
Definition at line 11 of file OnlMonComm.h.
SpillList_t OnlMonComm::m_list_sp private
Definition at line 23 of file OnlMonComm.h.
Referenced by AddSpill(), ClearSpill(), FindFullSpillRange(), and GetNumSpills().
int OnlMonComm::m_n_sp_sel_max private
Definition at line 20 of file OnlMonComm.h.
Referenced by GetMaxNumSelSpills(), and SetMaxNumSelSpills().
int OnlMonComm::m_sp_hi private
Definition at line 16 of file OnlMonComm.h.
Referenced by GetSpillRange(), SetSpillRange(), and SetSpillRangeHigh().
int OnlMonComm::m_sp_lo private
Definition at line 15 of file OnlMonComm.h.
Referenced by GetSpillRange(), SetSpillRange(), and SetSpillRangeLow().
int OnlMonComm::m_sp_max private
Definition at line 18 of file OnlMonComm.h.
Referenced by GetFullSpillRange(), and ReceiveFullSpillRange().
int OnlMonComm::m_sp_min private
Definition at line 17 of file OnlMonComm.h.
Referenced by GetFullSpillRange(), and ReceiveFullSpillRange().
SpillMode_t OnlMonComm::m_sp_mode private
Definition at line 13 of file OnlMonComm.h.
Referenced by GetSpillMode(), and SetSpillMode().
int OnlMonComm::m_sp_num private
Definition at line 14 of file OnlMonComm.h.
Referenced by GetSpillNum(), and SetSpillNum().
bool OnlMonComm::m_sp_sel private
Definition at line 19 of file OnlMonComm.h.
Referenced by GetSpillSelectability(), ReceiveFullSpillRange(), and SetSpillSelectability().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/online/onlmonserver/OnlMonComm.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/online/onlmonserver/OnlMonComm.cc