Class Reference for E1039 Core & Analysis Software: SQDimuonTruthInfoContainer Class Reference
SQDimuonTruthInfoContainer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/E906LegacyGen/SQDimuonTruthInfoContainer.h>
Public Member Functions
SQDimuonTruthInfoContainer ()
virtual ~SQDimuonTruthInfoContainer ()
void Reset ()
Clear Event.
double get_Dimuon_xs () const
double get_Dimuon_m () const
double get_Dimuon_cosThetaCS () const
double get_Dimuon_phiCS () const
double get_Dimuon_xF () const
double get_Dimuon_pt () const
void set_Dimuon_xs (const double xs)
void set_Dimuon_m (const double m)
void set_Dimuon_xF (const double xF)
void set_Dimuon_pt (const double pt)
void set_Dimuon_cosThetaCS (const double costheta)
void set_Dimuon_phiCS (const double phi)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Detailed Description
Definition at line 11 of file SQDimuonTruthInfoContainer.h.
Constructor & Destructor Documentation
SQDimuonTruthInfoContainer::SQDimuonTruthInfoContainer () inline
Definition at line 16 of file SQDimuonTruthInfoContainer.h.
SQDimuonTruthInfoContainer::~SQDimuonTruthInfoContainer () virtual
Definition at line 14 of file SQDimuonTruthInfoContainer.C.
Member Function Documentation
double SQDimuonTruthInfoContainer::get_Dimuon_cosThetaCS () const inline
Definition at line 23 of file SQDimuonTruthInfoContainer.h.
double SQDimuonTruthInfoContainer::get_Dimuon_m () const inline
Definition at line 22 of file SQDimuonTruthInfoContainer.h.
double SQDimuonTruthInfoContainer::get_Dimuon_phiCS () const inline
Definition at line 24 of file SQDimuonTruthInfoContainer.h.
double SQDimuonTruthInfoContainer::get_Dimuon_pt () const inline
Definition at line 26 of file SQDimuonTruthInfoContainer.h.
double SQDimuonTruthInfoContainer::get_Dimuon_xF () const inline
Definition at line 25 of file SQDimuonTruthInfoContainer.h.
double SQDimuonTruthInfoContainer::get_Dimuon_xs () const inline
Definition at line 21 of file SQDimuonTruthInfoContainer.h.
void SQDimuonTruthInfoContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 18 of file SQDimuonTruthInfoContainer.C.
void SQDimuonTruthInfoContainer::set_Dimuon_cosThetaCS (const double costheta) inline
Definition at line 32 of file SQDimuonTruthInfoContainer.h.
Referenced by SQPrimaryParticleGen::generateDrellYan(), SQPrimaryParticleGen::generateJPsi(), and SQPrimaryParticleGen::generatePsip().
void SQDimuonTruthInfoContainer::set_Dimuon_m (const double m) inline
Definition at line 29 of file SQDimuonTruthInfoContainer.h.
Referenced by SQPrimaryParticleGen::generateDrellYan(), SQPrimaryParticleGen::generateJPsi(), and SQPrimaryParticleGen::generatePsip().
void SQDimuonTruthInfoContainer::set_Dimuon_phiCS (const double phi) inline
Definition at line 33 of file SQDimuonTruthInfoContainer.h.
Referenced by SQPrimaryParticleGen::generateDrellYan(), SQPrimaryParticleGen::generateJPsi(), and SQPrimaryParticleGen::generatePsip().
void SQDimuonTruthInfoContainer::set_Dimuon_pt (const double pt) inline
Definition at line 31 of file SQDimuonTruthInfoContainer.h.
Referenced by SQPrimaryParticleGen::generateDrellYan(), SQPrimaryParticleGen::generateJPsi(), and SQPrimaryParticleGen::generatePsip().
void SQDimuonTruthInfoContainer::set_Dimuon_xF (const double xF) inline
Definition at line 30 of file SQDimuonTruthInfoContainer.h.
Referenced by SQPrimaryParticleGen::generateDrellYan(), SQPrimaryParticleGen::generateJPsi(), and SQPrimaryParticleGen::generatePsip().
void SQDimuonTruthInfoContainer::set_Dimuon_xs (const double xs) inline
Definition at line 28 of file SQDimuonTruthInfoContainer.h.
Referenced by SQPrimaryParticleGen::generateDrellYan(), SQPrimaryParticleGen::generateJPsi(), and SQPrimaryParticleGen::generatePsip().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/E906LegacyGen/SQDimuonTruthInfoContainer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/E906LegacyGen/SQDimuonTruthInfoContainer.C