Class Reference for E1039 Core & Analysis Software: SQSingleMuonGen Class Reference
SQSingleMuonGen Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/SingleMuonGen/SQSingleMuonGen.h>
Public Member Functions
SQSingleMuonGen (const std::string &name="SINGLEGEN")
virtual ~SQSingleMuonGen ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
const void set_target_only (bool en=true)
const void enable_geom_cut (bool en=true)
const void set_mother_decay_length (double l)
const void set_charge_ratio (double v)
const void set_pt_max (double v)
const void set_mom_range (double min, double max)
const void enable_real_mom_dist (bool en=true)
Public Member Functions inherited from PHG4ParticleGeneratorBase
virtual ~PHG4ParticleGeneratorBase ()
virtual void set_name (const std::string &particle="proton")
virtual void set_pid (const int pid)
virtual void set_mom (const double x, const double y, const double z)
virtual void set_vtx (const double x, const double y, const double z)
virtual void set_t0 (const double t)
virtual double get_vtx_x () const
virtual double get_vtx_y () const
virtual double get_vtx_z () const
virtual double get_t0 () const
virtual void Print (const std::string &what="ALL") const
virtual void AddParticle (const std::string &particle, const double x, const double y, const double z)
virtual void AddParticle (const int pid, const double x, const double y, const double z)
virtual void Embed (const int i=1)
virtual int ReuseExistingVertex (PHCompositeNode *topNode)
int get_reuse_existing_vertex () const
void set_reuse_existing_vertex (const int i=1)
void set_seed (const unsigned int iseed)
unsigned int get_seed () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from PHG4ParticleGeneratorBase
PHG4ParticleGeneratorBase (const std::string &name="GENERATORBASE")
int get_pdgcode (const std::string &name) const
std::string get_pdgname (const int pdgcode) const
double get_mass (const int pdgcode) const
void CheckAndCreateParticleVector ()
void SetParticleId (PHG4Particle *particle, PHG4InEvent *ineve)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from PHG4ParticleGeneratorBase
int embedflag
int reuse_existing_vertex
double vtx_x
double vtx_y
double vtx_z
double t0
std::vector< PHG4Particle * > particlelist
unsigned int seed
gsl_rng * RandomGenerator
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 18 of file SQSingleMuonGen.h.
Constructor & Destructor Documentation
SQSingleMuonGen()
SQSingleMuonGen::SQSingleMuonGen (const std::string & name = "SINGLEGEN")
Definition at line 25 of file SQSingleMuonGen.cxx.
~SQSingleMuonGen()
SQSingleMuonGen::~SQSingleMuonGen () virtual
Definition at line 73 of file SQSingleMuonGen.cxx.
Member Function Documentation
enable_geom_cut()
const void SQSingleMuonGen::enable_geom_cut (bool en = true) inline
Definition at line 29 of file SQSingleMuonGen.h.
enable_real_mom_dist()
const void SQSingleMuonGen::enable_real_mom_dist (bool en = true) inline
Definition at line 34 of file SQSingleMuonGen.h.
InitRun()
int SQSingleMuonGen::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 45 of file SQSingleMuonGen.cxx.
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, and PHNodeIterator::findFirst().
process_event()
int SQSingleMuonGen::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 82 of file SQSingleMuonGen.cxx.
References PHG4InEvent::AddParticle(), PHG4InEvent::AddVtx(), Fun4AllReturnCodes::EVENT_OK, PHG4ParticleGeneratorBase::get_pdgname(), PHG4InEvent::identify(), SQSingleMuonTruthInfo::motherPid, SQSingleMuonTruthInfo::muMom, SQSingleMuonTruthInfo::muVtx, PHG4Particle::set_e(), PHG4Particle::set_name(), PHG4Particle::set_parent_id(), PHG4Particle::set_pid(), PHG4Particle::set_px(), PHG4Particle::set_py(), PHG4Particle::set_pz(), PHG4Particle::set_track_id(), PHG4Particle::set_vtx_id(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
set_charge_ratio()
const void SQSingleMuonGen::set_charge_ratio (double v) inline
Definition at line 31 of file SQSingleMuonGen.h.
set_mom_range()
const void SQSingleMuonGen::set_mom_range (double min, double max) inline
Definition at line 33 of file SQSingleMuonGen.h.
set_mother_decay_length()
const void SQSingleMuonGen::set_mother_decay_length (double l) inline
Definition at line 30 of file SQSingleMuonGen.h.
set_pt_max()
const void SQSingleMuonGen::set_pt_max (double v) inline
Definition at line 32 of file SQSingleMuonGen.h.
set_target_only()
const void SQSingleMuonGen::set_target_only (bool en = true) inline
Definition at line 28 of file SQSingleMuonGen.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/SingleMuonGen/SQSingleMuonGen.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/SingleMuonGen/SQSingleMuonGen.cxx