Class Reference for E1039 Core & Analysis Software: PdbParameterMap Class Reference
PdbParameterMap Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbParameterMap.h>
Public Types
typedef std::map< const std::string, double > dMap
typedef std::map< const std::string, int > iMap
typedef std::map< const std::string, std::string > strMap
typedef dMap::const_iterator dIter
typedef iMap::const_iterator iIter
typedef strMap::const_iterator strIter
typedef std::pair< dIter, dIter > dConstRange
typedef std::pair< iIter, iIter > iConstRange
typedef std::pair< strIter, strIter > strConstRange
Public Member Functions
PdbParameterMap ()
virtual ~PdbParameterMap ()
void print () const
void Reset ()
Clear Event.
size_t get_hash () const
hash of binary information for checking purpose
dConstRange get_dparam_iters () const
iConstRange get_iparam_iters () const
strConstRange get_cparam_iters () const
void set_int_param (const std::string &name, const int ival)
void set_double_param (const std::string &name, const double dval)
void set_string_param (const std::string &name, const std::string &str)
Public Member Functions inherited from PdbCalChan
PdbCalChan ()
virtual ~PdbCalChan ()
ClassDef (PdbCalChan, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
dMap dparams
iMap iparams
strMap cparams
Detailed Description
Definition at line 9 of file PdbParameterMap.h.
Member Typedef Documentation
dConstRange
typedef std::pair<dIter, dIter> PdbParameterMap::dConstRange
Definition at line 18 of file PdbParameterMap.h.
dIter
typedef dMap::const_iterator PdbParameterMap::dIter
Definition at line 15 of file PdbParameterMap.h.
dMap
typedef std::map<const std::string, double> PdbParameterMap::dMap
Definition at line 12 of file PdbParameterMap.h.
iConstRange
typedef std::pair<iIter, iIter> PdbParameterMap::iConstRange
Definition at line 19 of file PdbParameterMap.h.
iIter
typedef iMap::const_iterator PdbParameterMap::iIter
Definition at line 16 of file PdbParameterMap.h.
iMap
typedef std::map<const std::string, int> PdbParameterMap::iMap
Definition at line 13 of file PdbParameterMap.h.
strConstRange
typedef std::pair<strIter, strIter> PdbParameterMap::strConstRange
Definition at line 20 of file PdbParameterMap.h.
strIter
typedef strMap::const_iterator PdbParameterMap::strIter
Definition at line 17 of file PdbParameterMap.h.
strMap
typedef std::map<const std::string, std::string> PdbParameterMap::strMap
Definition at line 14 of file PdbParameterMap.h.
Constructor & Destructor Documentation
PdbParameterMap()
PdbParameterMap::PdbParameterMap () inline
Definition at line 22 of file PdbParameterMap.h.
~PdbParameterMap()
virtual PdbParameterMap::~PdbParameterMap () inline virtual
Definition at line 23 of file PdbParameterMap.h.
Member Function Documentation
get_cparam_iters()
strConstRange PdbParameterMap::get_cparam_iters () const inline
Definition at line 38 of file PdbParameterMap.h.
References cparams.
Referenced by PHParameters::FillFrom(), and PHG4Parameters::FillFrom().
get_dparam_iters()
dConstRange PdbParameterMap::get_dparam_iters () const inline
Definition at line 31 of file PdbParameterMap.h.
References dparams.
Referenced by PHParameters::FillFrom(), and PHG4Parameters::FillFrom().
get_hash()
size_t PdbParameterMap::get_hash () const
hash of binary information for checking purpose
Definition at line 59 of file PdbParameterMap.cc.
get_iparam_iters()
iConstRange PdbParameterMap::get_iparam_iters () const inline
Definition at line 34 of file PdbParameterMap.h.
References iparams.
Referenced by PHParameters::FillFrom(), and PHG4Parameters::FillFrom().
print()
void PdbParameterMap::print () const virtual
Implements PdbCalChan.
Definition at line 9 of file PdbParameterMap.cc.
Reset()
void PdbParameterMap::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 31 of file PdbParameterMap.cc.
Referenced by PHParameters::SaveToNodeTree(), and PHG4Parameters::SaveToNodeTree().
set_double_param()
void PdbParameterMap::set_double_param (const std::string & name, const double dval)
Definition at line 46 of file PdbParameterMap.cc.
Referenced by PHParameters::CopyToPdbParameterMap(), and PHG4Parameters::CopyToPdbParameterMap().
set_int_param()
void PdbParameterMap::set_int_param (const std::string & name, const int ival)
Definition at line 40 of file PdbParameterMap.cc.
Referenced by PHParameters::CopyToPdbParameterMap(), and PHG4Parameters::CopyToPdbParameterMap().
set_string_param()
void PdbParameterMap::set_string_param (const std::string & name, const std::string & str)
Definition at line 52 of file PdbParameterMap.cc.
Referenced by PHParameters::CopyToPdbParameterMap(), and PHG4Parameters::CopyToPdbParameterMap().
Member Data Documentation
cparams
strMap PdbParameterMap::cparams protected
Definition at line 49 of file PdbParameterMap.h.
Referenced by get_cparam_iters().
dparams
dMap PdbParameterMap::dparams protected
Definition at line 47 of file PdbParameterMap.h.
Referenced by get_dparam_iters().
iparams
iMap PdbParameterMap::iparams protected
Definition at line 48 of file PdbParameterMap.h.
Referenced by get_iparam_iters().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbParameterMap.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbParameterMap.cc