Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/swap_util.c File Reference
swap_util.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <memory.h>
#include <errno.h>
Typedefs
typedef struct _stack evStack
typedef struct _lk LK_AHEAD
Functions
static evStack * init_evStack ()
static evStack * evStack_top ()
static void evStack_popoff ()
static void evStack_pushon ()
static void evStack_free ()
int int_swap_byte (int input)
void onmemory_swap (char *buffer)
void swapped_intcpy (char *des, char *source, int size)
void swapped_shortcpy (char *des, char *source, int size)
void swapped_longcpy (char *des, char *source, int size)
int swapped_fread (void *ptr, int size, int n_items, FILE *stream)
void swapped_memcpy (char *buffer, char *source, int size)
static evStack * evStack_top (evStack *head)
static void evStack_popoff (evStack *head)
static void evStack_pushon (int size, int posi, int type, int tag, int num, evStack *head)
static void evStack_free (evStack *head)
Typedef Documentation
evStack
typedef struct _stack evStack
LK_AHEAD
typedef struct _lk LK_AHEAD
Function Documentation
evStack_free() [1/2]
static void evStack_free () static
Referenced by swapped_memcpy().
evStack_free() [2/2]
static void evStack_free (evStack * head) static
Definition at line 454 of file swap_util.c.
References NULL.
evStack_popoff() [1/2]
static void evStack_popoff () static
Referenced by swapped_memcpy().
evStack_popoff() [2/2]
static void evStack_popoff (evStack * head) static
Definition at line 407 of file swap_util.c.
References NULL.
evStack_pushon() [1/2]
static void evStack_pushon () static
Referenced by swapped_memcpy().
evStack_pushon() [2/2]
static void evStack_pushon (int size, int posi, int type, int tag, int num, evStack * head) static
Definition at line 425 of file swap_util.c.
References NULL.
evStack_top() [1/2]
static evStack * evStack_top ()
Referenced by swapped_memcpy().
evStack_top() [2/2]
static evStack* evStack_top (evStack * head) static
Definition at line 392 of file swap_util.c.
References NULL.
init_evStack()
static evStack * init_evStack () static
Definition at line 370 of file swap_util.c.
References NULL.
Referenced by swapped_memcpy().
int_swap_byte()
int int_swap_byte (int input)
Definition at line 76 of file swap_util.c.
onmemory_swap()
void onmemory_swap (char * buffer)
Definition at line 96 of file swap_util.c.
swapped_fread()
int swapped_fread (void * ptr, int size, int n_items, FILE * stream)
Definition at line 173 of file swap_util.c.
References swapped_intcpy().
swapped_intcpy()
void swapped_intcpy (char * des, char * source, int size)
Definition at line 113 of file swap_util.c.
Referenced by swapped_fread(), and swapped_memcpy().
swapped_longcpy()
void swapped_longcpy (char * des, char * source, int size)
Definition at line 153 of file swap_util.c.
swapped_memcpy()
void swapped_memcpy (char * buffer, char * source, int size)
Definition at line 192 of file swap_util.c.
References evStack_free(), evStack_popoff(), evStack_pushon(), evStack_top(), init_evStack(), NULL, swapped_intcpy(), and swapped_shortcpy().
swapped_shortcpy()
void swapped_shortcpy (char * des, char * source, int size)
Definition at line 133 of file swap_util.c.
Referenced by swapped_memcpy().