Class Reference for E1039 Core & Analysis Software: PHObject Class Reference
PHObject Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHObject.h>
Inherits TObject.
Inherited by EventHeader, FlagSave, Hit, PHField, PHFieldConfig, PHG4BlockCellGeom, PHG4BlockCellGeomContainer, PHG4BlockGeom, PHG4BlockGeomContainer, PHG4CellContainer, PHG4CylinderCellContainer, PHG4CylinderCellGeom, PHG4CylinderCellGeomContainer, PHG4CylinderGeom, PHG4CylinderGeomContainer, PHG4EventHeader, PHG4GDMLConfig, PHG4Hit, PHG4HitContainer, PHG4InEvent, PHG4Parameters, PHG4ParametersContainer, PHG4Particle, PHG4Shower, PHG4TruthInfoContainer, PHG4VtxPoint, PHGenEvent, PHGenEventList, PHGenIntegral, PHGeomIOTGeo, PHGeomTGeo, PHHepMCGenEvent, PHHepMCGenEventMap, PHParameters, PHParametersContainer, PHTimeStamp, PatternDB, PdbCalChan, PropSegment, RunHeader, SQDimuon, SQDimuonVector, SQEvent, SQHardEvent, SQHardSpill, SQHit, SQHitMap, SQHitVector, SQIntMap, SQMCEvent, SQParamDeco, SQRun, SQScaler, SQSingleMuonTruthInfo, SQSlowCont, SQSpill, SQSpillMap, SQStringMap, SQTrack, SQTrackVector, SRawEvent, SRecEvent, SignedHit, SyncObject, SyncObject, Tracklet, TrackletVector, VariableArray, and VariableArrayContainer.
Public Member Functions
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Detailed Description
Definition at line 12 of file PHObject.h.
Constructor & Destructor Documentation
PHObject()
PHObject::PHObject ()
ctor
Definition at line 6 of file PHObject.cc.
~PHObject()
virtual PHObject::~PHObject () inline virtual
dtor
Definition at line 19 of file PHObject.h.
Member Function Documentation
BufferSize() [1/2]
int PHObject::BufferSize () const inline
Definition at line 45 of file PHObject.h.
BufferSize() [2/2]
void PHObject::BufferSize (const int i) inline
Definition at line 44 of file PHObject.h.
Referenced by PHNodeIOManager::write().
clone()
PHObject * PHObject::clone () const virtual
Virtual copy constructor.
Reimplemented in SQHardSpill, PHGeomIOTGeo, PHFieldConfig_v3, PHFieldConfig_v2, PHFieldConfig_v1, SQSlowCont_v1, SQSlowCont, SQScaler_v1, SQScaler, SQHardSpill_v1, PHGenIntegralv1, SyncObject, SyncObjectv2, SyncObjectv1, SyncObject, RunHeader, FlagSavev1, and EventHeaderv1.
Definition at line 14 of file PHObject.cc.
References PHWHERE.
Referenced by SQStringMap_v1::insert(), and SQIntMap_v1::insert().
identify()
void PHObject::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented in PHGenEventv1, PHGenEventListv1, PHGenEventList, PHGenEvent, SQTrackVector, SQTrack, SQParamDeco, SQMCEvent, SQHardSpill, SQHardEvent, SQDimuonVector, SQDimuon, PHG4VtxPointv1, PHG4VtxPoint, PHG4TruthInfoContainer, PHG4Showerv1, PHG4Shower, PHG4Particlev2, PHG4Particlev1, PHG4Particle, PHG4InEvent, PHG4Hitv1, PHG4HitContainer, PHG4Hit, PHG4EventHeaderv1, PHG4EventHeader, PHG4GDMLConfig, PHG4CylinderGeomv4, PHG4CylinderGeomv3, PHG4CylinderGeomv2, PHG4CylinderGeomv1, PHG4CylinderGeomContainer, PHG4CylinderGeom, PHG4CylinderCellGeomContainer, PHG4CylinderCellGeom, PHG4CylinderCellContainer, PHG4CellContainer, PHG4BlockGeomv1, PHG4BlockGeomContainer, PHG4BlockGeom, PHG4BlockCellGeomContainer, PHG4BlockCellGeom, VariableArrayContainer, VariableArray, PatternDB, SRecEvent, SRecDimuon, SRecTrack, SRawEvent, Hit, TrackletVector, Tracklet, PropSegment, SignedHit, PHGeomTGeo, PHGeomIOTGeo, PHFieldSeaQuest, PHFieldRegionalConst, PHFieldConfig_v3, PHFieldConfig_v2, PHFieldConfig_v1, PHFieldConfig, PHField, SQTrackVector_v1, SQTrack_v1, SQStringMap_v1, SQStringMap, SQSpillMap_v1, SQSpillMap, SQSpill_v2, SQSpill_v1, SQSpill, SQSlowCont_v1, SQSlowCont, SQScaler_v1, SQScaler, SQRun_v2, SQRun_v1, SQRun, SQParamDeco_v1, SQMCHit_v1, SQMCEvent_v1, SQIntMap_v1, SQIntMap, SQHitVector_v1, SQHitVector, SQHitMap_v1, SQHitMap, SQHit_v1, SQHit, SQHardSpill_v1, SQHardEvent_v1, SQEvent_v2, SQEvent_v1, SQEvent, SQDimuonVector_v1, SQDimuon_v1, SQCalMCHit_v1, SQCalHit_v1, SQSingleMuonTruthInfo, PHHepMCGenEventMap, PHHepMCGenEvent, PHGenIntegralv1, SyncObject, SyncObjectv2, SyncObjectv1, SyncObject, RunHeader, FlagSavev1, FlagSave, EventHeaderv1, and EventHeader.
Definition at line 21 of file PHObject.cc.
Referenced by PHGenIntegralv1::CopyContent(), PHGenIntegralv1::Integrate(), and Fun4AllServer::NodeIdentify().
isImplemented() [1/4]
int PHObject::isImplemented (const double f) const virtual
Definition at line 98 of file PHObject.cc.
References PHWHERE.
isImplemented() [2/4]
int PHObject::isImplemented (const float f) const virtual
Definition at line 89 of file PHObject.cc.
References PHWHERE.
isImplemented() [3/4]
int PHObject::isImplemented (const int i) const virtual
Definition at line 107 of file PHObject.cc.
References PHWHERE.
isImplemented() [4/4]
int PHObject::isImplemented (const unsigned int i) const virtual
Definition at line 116 of file PHObject.cc.
References PHWHERE.
isValid() [1/5]
int PHObject::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented in SQTrackVector, SQTrack, SQParamDeco, SQMCEvent, SQHitVector, SQHardSpill, SQHardEvent, SQDimuonVector, SQDimuon, PHG4Showerv1, PHG4Shower, PHG4EventHeaderv1, PHG4EventHeader, PHG4GDMLConfig, PatternDB, SRecEvent, SRecDimuon, SRecTrack, SRawEvent, Hit, TrackletVector, Tracklet, PropSegment, SignedHit, PHGeomTGeo, PHGeomIOTGeo, PHFieldConfig_v3, PHFieldConfig_v2, PHFieldConfig_v1, PHFieldConfig, SQTrackVector_v1, SQTrack_v1, SQStringMap_v1, SQStringMap, SQSpillMap_v1, SQSpillMap, SQSpill_v2, SQSpill_v1, SQSpill, SQSlowCont_v1, SQSlowCont, SQScaler_v1, SQScaler, SQParamDeco_v1, SQMCHit_v1, SQMCEvent_v1, SQIntMap_v1, SQIntMap, SQHitVector_v1, SQHitMap_v1, SQHitMap, SQHit_v1, SQHit, SQHardSpill_v1, SQHardEvent_v1, SQEvent_v2, SQEvent_v1, SQDimuonVector_v1, SQDimuon_v1, SQCalMCHit_v1, SQCalHit_v1, SQSingleMuonTruthInfo, PHHepMCGenEventMap, PHHepMCGenEvent, PHGenIntegralv1, SyncObject, SyncObjectv1, SyncObject, RunHeader, FlagSavev1, FlagSave, EventHeaderv1, and EventHeader.
Definition at line 44 of file PHObject.cc.
References PHWHERE.
isValid() [2/5]
int PHObject::isValid (const double) const virtual
Definition at line 62 of file PHObject.cc.
References PHWHERE.
isValid() [3/5]
int PHObject::isValid (const float) const virtual
Definition at line 53 of file PHObject.cc.
References PHWHERE.
isValid() [4/5]
int PHObject::isValid (const int) const virtual
Definition at line 71 of file PHObject.cc.
References PHWHERE.
isValid() [5/5]
int PHObject::isValid (const unsigned int) const virtual
Definition at line 80 of file PHObject.cc.
References PHWHERE.
Reset()
void PHObject::Reset () virtual
Clear Event.
Reimplemented in SQTrackVector, SQTrack, SQParamDeco, SQMCEvent, SQHitVector, SQHardSpill, SQHardEvent, SQDimuonVector, SQDimuon, PHG4TruthInfoContainer, PHG4Showerv1, PHG4Shower, PHG4InEvent, PHG4Hitv1, PHG4HitContainer, PHG4Hit, PHG4EventHeaderv1, PHG4EventHeader, PHG4GDMLConfig, PHG4CylinderCellContainer, PHG4CellContainer, VariableArrayContainer, VariableArray, PatternDB, SRecEvent, SRecDimuon, SRecTrack, SRawEvent, Hit, TrackletVector, Tracklet, PropSegment, SignedHit, PHGeomTGeo, PHGeomIOTGeo, PHFieldConfig_v3, PHFieldConfig_v2, PHFieldConfig_v1, PHFieldConfig, SQTrackVector_v1, SQTrack_v1, SQStringMap_v1, SQStringMap, SQSpillMap_v1, SQSpillMap, SQSpill_v2, SQSpill_v1, SQSpill, SQSlowCont_v1, SQSlowCont, SQScaler_v1, SQScaler, SQRun_v2, SQRun_v1, SQRun, SQParamDeco_v1, SQMCHit_v1, SQMCEvent_v1, SQIntMap_v1, SQIntMap, SQHitVector_v1, SQHitMap_v1, SQHitMap, SQHit_v1, SQHit, SQHardSpill_v1, SQHardEvent_v1, SQEvent_v2, SQEvent_v1, SQEvent, SQDimuonVector_v1, SQDimuon_v1, SQCalMCHit_v1, SQCalHit_v1, SQSingleMuonTruthInfo, PHHepMCGenEventMap, PHHepMCGenEvent, PHGenIntegralv1, PHGenEventv1, PHGenEventListv1, PHGenEventList, PHGenEvent, SyncObject, SyncObjectv2, SyncObjectv1, SyncObject, RunHeader, FlagSavev1, FlagSave, EventHeaderv1, EventHeader, PdbParameterMapContainer, and PdbParameterMap.
Definition at line 26 of file PHObject.cc.
References PHWHERE.
SplitLevel() [1/2]
int PHObject::SplitLevel () const inline
Definition at line 43 of file PHObject.h.
Referenced by PHGeomIOTGeo::PHGeomIOTGeo().
SplitLevel() [2/2]
void PHObject::SplitLevel (const int i) inline
Definition at line 42 of file PHObject.h.
Referenced by SQReco::MakeNodes(), and PHNodeIOManager::write().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHObject.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHObject.cc