Class Reference for E1039 Core & Analysis Software: PHG4ParametersContainer Class Reference
PHG4ParametersContainer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4ParametersContainer.h>
Public Types
typedef std::map< int, PHG4Parameters * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator, Iterator > Range
typedef std::pair< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHG4ParametersContainer (const std::string &name="NONE")
virtual ~PHG4ParametersContainer ()
void AddPHG4Parameters (const int layer, PHG4Parameters *params)
const PHG4Parameters * GetParameters (const int layer) const
PHG4Parameters * GetParametersToModify (const int layer)
int WriteToFile (const std::string &extension, const std::string &dir)
int WriteToDB ()
void set_name (const std::string &name)
std::string Name () const
ConstRange GetAllParameters () const
void Print () const
void SaveToNodeTree (PHCompositeNode *topNode, const std::string &nodename)
int ExistDetid (const int detid) const
void clear ()
void FillFrom (const PdbParameterMapContainer *saveparamcontainer)
void CreateAndFillFrom (const PdbParameterMapContainer *saveparamcontainer, const std::string &name)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
void CopyToPdbParameterMapContainer (PdbParameterMapContainer *myparm)
Protected Attributes
std::string superdetectorname
std::map< int, PHG4Parameters * > parametermap
Detailed Description
This class is deprecated, please use PHG4Parameter instead. See https://github.com/sPHENIX-Collaboration/coresoftware/pull/405
Definition at line 15 of file PHG4ParametersContainer.h.
Member Typedef Documentation
ConstIterator
typedef Map::const_iterator PHG4ParametersContainer::ConstIterator
Definition at line 20 of file PHG4ParametersContainer.h.
ConstRange
typedef std::pair<ConstIterator, ConstIterator> PHG4ParametersContainer::ConstRange
Definition at line 22 of file PHG4ParametersContainer.h.
Iterator
typedef Map::iterator PHG4ParametersContainer::Iterator
Definition at line 19 of file PHG4ParametersContainer.h.
Map
typedef std::map<int, PHG4Parameters *> PHG4ParametersContainer::Map
Definition at line 18 of file PHG4ParametersContainer.h.
Range
typedef std::pair<Iterator, Iterator> PHG4ParametersContainer::Range
Definition at line 21 of file PHG4ParametersContainer.h.
Constructor & Destructor Documentation
PHG4ParametersContainer()
PHG4ParametersContainer::PHG4ParametersContainer (const std::string & name = "NONE") explicit
Definition at line 25 of file PHG4ParametersContainer.cc.
~PHG4ParametersContainer()
PHG4ParametersContainer::~PHG4ParametersContainer () virtual
Definition at line 29 of file PHG4ParametersContainer.cc.
References parametermap.
Member Function Documentation
AddPHG4Parameters()
void PHG4ParametersContainer::AddPHG4Parameters (const int layer, PHG4Parameters * params)
Definition at line 80 of file PHG4ParametersContainer.cc.
References parametermap, and PHWHERE.
Referenced by CreateAndFillFrom(), PHG4ParameterContainerInterface::CreateInitialize(), PHG4DetectorGroupSubsystem::InitializeParameters(), PHG4DetectorGroupSubsystem::InitRun(), PHG4ParameterContainerInterface::set_int_param(), and PHG4ParameterContainerInterface::set_string_param().
clear()
void PHG4ParametersContainer::clear () inline
Definition at line 40 of file PHG4ParametersContainer.h.
References parametermap.
Referenced by PHG4DetectorGroupSubsystem::InitRun().
CopyToPdbParameterMapContainer()
void PHG4ParametersContainer::CopyToPdbParameterMapContainer (PdbParameterMapContainer * myparm) protected
Definition at line 193 of file PHG4ParametersContainer.cc.
References PdbParameterMapContainer::AddPdbParameterMap(), and parametermap.
Referenced by SaveToNodeTree(), WriteToDB(), and WriteToFile().
CreateAndFillFrom()
void PHG4ParametersContainer::CreateAndFillFrom (const PdbParameterMapContainer * saveparamcontainer, const std::string & name)
Definition at line 58 of file PHG4ParametersContainer.cc.
References AddPHG4Parameters(), PHG4Parameters::FillFrom(), PdbParameterMapContainer::get_ParameterMaps(), and parametermap.
ExistDetid()
int PHG4ParametersContainer::ExistDetid (const int detid) const
Definition at line 238 of file PHG4ParametersContainer.cc.
References parametermap.
Referenced by PHG4ParameterContainerInterface::ExistDetid().
FillFrom()
void PHG4ParametersContainer::FillFrom (const PdbParameterMapContainer * saveparamcontainer)
Definition at line 40 of file PHG4ParametersContainer.cc.
References PHG4Parameters::FillFrom(), PdbParameterMapContainer::get_ParameterMaps(), and parametermap.
Referenced by PHG4DetectorGroupSubsystem::InitRun().
GetAllParameters()
ConstRange PHG4ParametersContainer::GetAllParameters () const inline
Definition at line 36 of file PHG4ParametersContainer.h.
References parametermap.
Referenced by PHG4DetectorGroupSubsystem::InitRun().
GetParameters()
const PHG4Parameters * PHG4ParametersContainer::GetParameters (const int layer) const
Definition at line 92 of file PHG4ParametersContainer.cc.
References NULL, and parametermap.
Referenced by PHG4DetectorGroupSubsystem::get_double_param(), PHG4ParameterContainerInterface::get_double_param(), PHG4DetectorGroupSubsystem::get_int_param(), PHG4ParameterContainerInterface::get_int_param(), PHG4DetectorGroupSubsystem::get_string_param(), and PHG4ParameterContainerInterface::get_string_param().
GetParametersToModify()
PHG4Parameters * PHG4ParametersContainer::GetParametersToModify (const int layer)
Definition at line 105 of file PHG4ParametersContainer.cc.
References NULL, and parametermap.
Referenced by PHG4ParameterContainerInterface::CreateInitialize(), PHG4DetectorGroupSubsystem::InitializeParameters(), PHG4DetectorGroupSubsystem::UpdateParametersWithMacro(), and PHG4ParameterContainerInterface::UpdateParametersWithMacro().
Name()
std::string PHG4ParametersContainer::Name () const inline
Definition at line 34 of file PHG4ParametersContainer.h.
References superdetectorname.
Referenced by PHG4ParameterContainerInterface::CreateInitialize(), PHG4ParameterContainerInterface::get_double_param(), PHG4ParameterContainerInterface::get_int_param(), PHG4ParameterContainerInterface::get_string_param(), PHG4DetectorGroupSubsystem::InitRun(), PHG4BlockCellReco::InitRun(), PHG4CylinderCellReco::InitRun(), Print(), PHG4ParameterContainerInterface::set_double_param(), PHG4ParameterContainerInterface::set_int_param(), and PHG4ParameterContainerInterface::set_string_param().
Print()
void PHG4ParametersContainer::Print () const
Definition at line 206 of file PHG4ParametersContainer.cc.
References Name(), and parametermap.
SaveToNodeTree()
void PHG4ParametersContainer::SaveToNodeTree (PHCompositeNode * topNode, const std::string & nodename)
Definition at line 219 of file PHG4ParametersContainer.cc.
References PHCompositeNode::addNode(), CopyToPdbParameterMapContainer(), and PdbParameterMapContainer::Reset().
Referenced by PHG4DetectorGroupSubsystem::InitRun(), and PHG4ParameterContainerInterface::SaveToNodeTree().
set_name()
void PHG4ParametersContainer::set_name (const std::string & name) inline
Definition at line 33 of file PHG4ParametersContainer.h.
References superdetectorname.
Referenced by PHG4DetectorGroupSubsystem::Init(), PHG4BlockCellReco::InitRun(), PHG4CylinderCellReco::InitRun(), and PHG4ParameterContainerInterface::set_name().
WriteToDB()
int PHG4ParametersContainer::WriteToDB ()
Definition at line 155 of file PHG4ParametersContainer.cc.
References PdbApplication::abort(), PdbApplication::commit(), CopyToPdbParameterMapContainer(), PdbBankManager::createBank(), PdbBankManager::getApplication(), PdbCalBank::getEntry(), PdbBankManager::instance(), PHWHERE, PdbCalBank::setLength(), PdbApplication::startUpdate(), and superdetectorname.
Referenced by PHG4DetectorGroupSubsystem::SaveParamsToDB().
WriteToFile()
int PHG4ParametersContainer::WriteToFile (const std::string & extension, const std::string & dir)
Definition at line 116 of file PHG4ParametersContainer.cc.
References CopyToPdbParameterMapContainer(), PdbBankID::getInternalValue(), PHTimeStamp::getTics(), and superdetectorname.
Referenced by PHG4DetectorGroupSubsystem::SaveParamsToFile().
Member Data Documentation
parametermap
std::map<int, PHG4Parameters *> PHG4ParametersContainer::parametermap protected
Definition at line 47 of file PHG4ParametersContainer.h.
Referenced by AddPHG4Parameters(), clear(), CopyToPdbParameterMapContainer(), CreateAndFillFrom(), ExistDetid(), FillFrom(), GetAllParameters(), GetParameters(), GetParametersToModify(), Print(), and ~PHG4ParametersContainer().
superdetectorname
std::string PHG4ParametersContainer::superdetectorname protected
Definition at line 46 of file PHG4ParametersContainer.h.
Referenced by Name(), set_name(), WriteToDB(), and WriteToFile().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4ParametersContainer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4ParametersContainer.cc