SeaQuest Offline Software: KalmanFilter Class Reference
KalmanFilter Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/inc/KalmanFilter.h>
Public Member Functions
void close ()
KalmanFilter (bool limitedStep=true)
Real constructor.
bool predict (Node &_node)
Kalman filter steps.
bool filter (Node &_node)
bool smooth (Node &_node, Node &_node_prev)
void setCurrTrkpar (Node &_node)
set the current track parameter using the current node
void setCurrTrkpar (TrkPar &_trkpar)
bool fit_node (Node &_node)
Fit one node.
void enableDumpCorrection ()
Enable the dump mode: stop calc prop matrix, start calc travel length.
Static Public Member Functions
static KalmanFilter * instance ()
singlton instance
Private Attributes
TrkPar _trkpar_curr
Stores the current track parameter.
TrackExtrapolator _extrapolator
Track extrapolator.
Static Private Attributes
static KalmanFilter * p_kmfit = NULL
Pointer to singlton instance.
Detailed Description
Definition at line 26 of file KalmanFilter.h.
Constructor & Destructor Documentation
KalmanFilter::KalmanFilter (bool limitedStep = true)
Real constructor.
Definition at line 38 of file KalmanFilter.cxx.
References _extrapolator, TrackExtrapolator::init(), JobOptsSvc::instance(), and JobOptsSvc::m_geomVersion.
Referenced by instance().
Member Function Documentation
void KalmanFilter::close (void)
Definition at line 30 of file KalmanFilter.cxx.
References p_kmfit.
Referenced by main().
void KalmanFilter::enableDumpCorrection () inline
Enable the dump mode: stop calc prop matrix, start calc travel length.
Definition at line 49 of file KalmanFilter.h.
References _extrapolator, TrackExtrapolator::setLengthCalc(), and TrackExtrapolator::setPropCalc().
Referenced by SRecTrack::setZVertex(), and VertexFit::VertexFit().
bool KalmanFilter::filter (Node & _node)
Get all the predicted state vector and covariance
Calculate the filtered covariance matrix cov_filter = (c_pred^{-1} + proj^t*G*proj)^{-1}
Calculate the filtered state vector p_filter = c_filter.(c_pred^{-1}.p_pred + h^t.g.measure) Three equations below are mathematically equal, but EQ.2 appears to be faster
Calculate the filtered residule and associated covariance r_filter = m - h.p_filter r_cov_filter = m_cov - h.c_filter.h^t
Calculate the filtered parameter's contribution to chi square chi2 += chi2m + chi2p chi2m = r_filter^t.g.r_filter (contribution from measurement) chi2p = (p_filter-p_pred)^t.c_pred^{-1}.(p_filter - p_pred) (contribution from extrapolator)
Store the filtered state vector
Definition at line 105 of file KalmanFilter.cxx.
References TrkPar::_covar_kf, TrkPar::_state_kf, TrkPar::_z, SMatrix::getABCt(), SMatrix::getABtC(), SMatrix::getAtBC(), Node::getFiltered(), Node::getMeasurement(), Node::getMeasurementCov(), Node::getPredicted(), Node::getProjector(), SMatrix::invertMatrix(), Node::isFilterDone(), Node::isPredictionDone(), LogInfo, Node::setChisq(), and Node::setFilterDone().
Referenced by KalmanTrack::addHit(), and fit_node().
bool KalmanFilter::fit_node (Node & _node)
Fit one node.
Definition at line 44 of file KalmanFilter.cxx.
References filter(), and predict().
Referenced by VertexFit::findVertex(), KalmanTrack::getMomentumVertex(), KalmanFitter::processOneTrack(), and SRecTrack::setZVertex().
KalmanFilter * KalmanFilter::instance () static
singlton instance
Definition at line 20 of file KalmanFilter.cxx.
References KalmanFilter(), and p_kmfit.
Referenced by KalmanTrack::addHit(), KalmanTrack::getMomentumVertex(), KalmanFitter::KalmanFitter(), KalmanTrack::propagateTo(), SRecTrack::setZVertex(), and VertexFit::VertexFit().
bool KalmanFilter::predict (Node & _node)
Kalman filter steps.
Empty prediction, for debugging purpose
Definition at line 56 of file KalmanFilter.cxx.
References TrkPar::_covar_kf, _extrapolator, TrkPar::_state_kf, _trkpar_curr, TrkPar::_z, TrackExtrapolator::extrapolateTo(), FMAG_LENGTH, SMatrix::getABCt(), TrackExtrapolator::getFinalStateWithCov(), Node::getPredicted(), TrackExtrapolator::getPropagator(), Node::getPropagator(), Node::getZ(), Node::isPredictionDone(), LogInfo, TrackExtrapolator::setInitialStateWithCov(), and Node::setPredictionDone().
Referenced by fit_node(), and KalmanTrack::propagateTo().
void KalmanFilter::setCurrTrkpar (Node & _node) inline
set the current track parameter using the current node
Definition at line 42 of file KalmanFilter.h.
References _trkpar_curr, and Node::getFiltered().
Referenced by VertexFit::findVertex(), KalmanTrack::getMomentumVertex(), KalmanFitter::processOneTrack(), KalmanTrack::propagateTo(), KalmanFitter::setStartingParameter(), and SRecTrack::setZVertex().
void KalmanFilter::setCurrTrkpar (TrkPar & _trkpar) inline
Definition at line 43 of file KalmanFilter.h.
References _trkpar_curr.
bool KalmanFilter::smooth (Node & _node, Node & _node_prev)
Retrieve related info
Calculate smoothed state vector p_smooth = p_filter + a.(p_prev_smooth - p_prev_pred) a = c_filter.prop_prev^t.c_prev_pred^{-1}
Calculate the covariance of the smoothed state vector c_smooth = c_filter + a.(c_smooth_prev - c_pred_prev).a^t
Fill the smoothed track parameter
Definition at line 179 of file KalmanFilter.cxx.
References TrkPar::_covar_kf, TrkPar::_state_kf, TrkPar::_z, SMatrix::getABCt(), SMatrix::getABtCinv(), Node::getFiltered(), Node::getPredicted(), Node::getPropagator(), Node::getSmoothed(), Node::isFilterDone(), Node::isSmoothDone(), LogInfo, and Node::setSmoothDone().
Referenced by KalmanFitter::processOneTrack().
Member Data Documentation
TrackExtrapolator KalmanFilter::_extrapolator private
Track extrapolator.
Definition at line 59 of file KalmanFilter.h.
Referenced by enableDumpCorrection(), KalmanFilter(), and predict().
TrkPar KalmanFilter::_trkpar_curr private
Stores the current track parameter.
Definition at line 56 of file KalmanFilter.h.
Referenced by predict(), and setCurrTrkpar().
KalmanFilter * KalmanFilter::p_kmfit = NULL static private
Pointer to singlton instance.
Definition at line 53 of file KalmanFilter.h.
Referenced by close(), and instance().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/inc/KalmanFilter.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/src/KalmanFilter.cxx