Class Reference for E1039 Core & Analysis Software: GeomParamPlane Class Reference
GeomParamPlane Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/GeomParamPlane.h>
Classes
struct Plane
Public Member Functions
GeomParamPlane ()
virtual ~GeomParamPlane ()
void Add (const Plane &plane)
bool Find (const std::string det_name, Plane *&plane)
int GetNumPlanes ()
Plane * GetPlane (const int idx)
void Print (std::ostream &os)
Public Member Functions inherited from GeomParamBase
GeomParamBase (const std::string label, const std::string header)
virtual ~GeomParamBase ()
Public Member Functions inherited from RunParamBase
RunParamBase (const std::string type, const std::string label, const std::string header)
virtual ~RunParamBase ()
void SetBaseDir (const std::string dir_base)
std::string GetBaseDir ()
std::string GetParamID ()
std::string GetMapID ()
void SetMapID (const std::string map_id)
void SetMapIDbyFile (const std::string map_id)
void SetMapIDbyDB (const std::string map_id)
void SetMapIDbyFile (const int run)
void SetMapIDbyDB (const int run)
void ReadFromFile ()
void WriteToFile ()
void ReadFromLocalFile (const std::string fn_tsv)
void WriteToLocalFile (const std::string fn_tsv)
void ReadFromDB ()
void WriteToDB ()
void WriteRangeToDB ()
Protected Member Functions
int ReadFileCont (LineList &lines)
int WriteFileCont (std::ostream &os)
void ReadDbTable (DbSvc &db)
void WriteDbTable (DbSvc &db)
Protected Member Functions inherited from RunParamBase
std::string RangeFileName ()
std::string MapFileName ()
std::string SchemaName ()
std::string MapTableName ()
Additional Inherited Members
Protected Types inherited from RunParamBase
typedef std::vector< std::string > LineList
Detailed Description
Definition at line 5 of file GeomParamPlane.h.
Constructor & Destructor Documentation
GeomParamPlane::GeomParamPlane ()
Definition at line 12 of file GeomParamPlane.cc.
virtual GeomParamPlane::~GeomParamPlane () inline virtual
Definition at line 33 of file GeomParamPlane.h.
Member Function Documentation
void GeomParamPlane::Add (const Plane & plane)
Definition at line 103 of file GeomParamPlane.cc.
References GeomParamPlane::Plane::det_name.
Referenced by ReadDbTable(), and ReadFileCont().
bool GeomParamPlane::Find (const std::string det_name, Plane *& plane)
Definition at line 109 of file GeomParamPlane.cc.
int GeomParamPlane::GetNumPlanes () inline
Definition at line 37 of file GeomParamPlane.h.
Plane* GeomParamPlane::GetPlane (const int idx) inline
Definition at line 38 of file GeomParamPlane.h.
void GeomParamPlane::Print (std::ostream & os) virtual
Reimplemented from RunParamBase.
Definition at line 119 of file GeomParamPlane.cc.
void GeomParamPlane::ReadDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 43 of file GeomParamPlane.cc.
References Add(), GeomParamPlane::Plane::angle_from_vert, GeomParamPlane::Plane::cell_spacing, GeomParamPlane::Plane::cell_width, GeomParamPlane::Plane::det_name, GeomParamPlane::Plane::height, RunParamBase::MapTableName(), GeomParamPlane::Plane::n_ele, DbSvc::Process(), GeomParamPlane::Plane::theta_x, GeomParamPlane::Plane::theta_y, GeomParamPlane::Plane::theta_z, GeomParamPlane::Plane::width, GeomParamPlane::Plane::x0, GeomParamPlane::Plane::xoffset, GeomParamPlane::Plane::y0, and GeomParamPlane::Plane::z0.
int GeomParamPlane::ReadFileCont (LineList & lines) protected virtual
Reimplemented from RunParamBase.
Definition at line 18 of file GeomParamPlane.cc.
References Add(), GeomParamPlane::Plane::angle_from_vert, GeomParamPlane::Plane::cell_spacing, GeomParamPlane::Plane::cell_width, GeomParamPlane::Plane::det_name, GeomParamPlane::Plane::height, GeomParamPlane::Plane::n_ele, GeomParamPlane::Plane::theta_x, GeomParamPlane::Plane::theta_y, GeomParamPlane::Plane::theta_z, GeomParamPlane::Plane::width, GeomParamPlane::Plane::x0, GeomParamPlane::Plane::xoffset, GeomParamPlane::Plane::y0, and GeomParamPlane::Plane::z0.
void GeomParamPlane::WriteDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 69 of file GeomParamPlane.cc.
References DbSvc::VarList::Add(), DbSvc::Con(), DbSvc::CreateTable(), and RunParamBase::MapTableName().
int GeomParamPlane::WriteFileCont (std::ostream & os) protected virtual
Reimplemented from RunParamBase.
Definition at line 33 of file GeomParamPlane.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/GeomParamPlane.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/GeomParamPlane.cc