Class Reference for E1039 Core & Analysis Software: SQSpillMap Class Reference
SQSpillMap Class Reference
An SQ interface class to hold a list of SQSpill objects.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSpillMap.h>
Public Types
typedef std::map< unsigned int, SQSpill * > SpillMap
typedef std::map< unsigned int, SQSpill * >::const_iterator ConstIter
typedef std::map< unsigned int, SQSpill * >::iterator Iter
Public Member Functions
virtual ~SQSpillMap ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual SQSpillMap * Clone () const
virtual bool empty () const
Return 'true' if this object holds no spill.
virtual size_t size () const
Return the number of spills held.
virtual size_t count (unsigned int idkey) const
Return the number of spills having spill ID = 'idkey'. Must be '0' or '1'.
virtual void clear ()
Clear the list.
virtual const SQSpill * get (unsigned int idkey) const
Return the SQSpill entry having spill ID = 'idkey'. Return '0' if no entry exists.
virtual SQSpill * get (unsigned int idkey)
Return the SQSpill entry having spill ID = 'idkey'. Return '0' if no entry exists.
virtual SQSpill * insert (const SQSpill *hit)
Insert the given SQSpill object.
virtual size_t erase (unsigned int idkey)
Erase the SQSpill entry having spill ID = 'idkey'.
virtual ConstIter begin () const
Return the const begin iterator.
virtual ConstIter find (unsigned int idkey) const
Return the const iterator of the SQSpill entry having spill ID = 'idkey'.
virtual ConstIter end () const
Return the const end iterator.
virtual Iter begin ()
Return the begin iterator.
virtual Iter find (unsigned int idkey)
Return the iterator of the SQSpill entry having spill ID = 'idkey'.
virtual Iter end ()
Return the end iterator.
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQSpillMap ()
Detailed Description
An SQ interface class to hold a list of SQSpill objects.
Definition at line 19 of file SQSpillMap.h.
Member Typedef Documentation
ConstIter
typedef std::map<unsigned int, SQSpill*>::const_iterator SQSpillMap::ConstIter
Definition at line 24 of file SQSpillMap.h.
Iter
typedef std::map<unsigned int, SQSpill*>::iterator SQSpillMap::Iter
Definition at line 25 of file SQSpillMap.h.
SpillMap
typedef std::map<unsigned int, SQSpill*> SQSpillMap::SpillMap
Definition at line 23 of file SQSpillMap.h.
Constructor & Destructor Documentation
~SQSpillMap()
virtual SQSpillMap::~SQSpillMap () inline virtual
Definition at line 27 of file SQSpillMap.h.
SQSpillMap()
SQSpillMap::SQSpillMap () inline protected
Definition at line 55 of file SQSpillMap.h.
Member Function Documentation
begin() [1/2]
virtual Iter SQSpillMap::begin () inline virtual
Return the begin iterator.
Reimplemented in SQSpillMap_v1.
Definition at line 50 of file SQSpillMap.h.
begin() [2/2]
virtual ConstIter SQSpillMap::begin () const inline virtual
Return the const begin iterator.
Reimplemented in SQSpillMap_v1.
Definition at line 46 of file SQSpillMap.h.
clear()
virtual void SQSpillMap::clear () inline virtual
Clear the list.
Reimplemented in SQSpillMap_v1.
Definition at line 39 of file SQSpillMap.h.
Clone()
virtual SQSpillMap* SQSpillMap::Clone () const inline virtual
Reimplemented in SQSpillMap_v1.
Definition at line 34 of file SQSpillMap.h.
References NULL.
count()
virtual size_t SQSpillMap::count (unsigned int idkey) const inline virtual
Return the number of spills having spill ID = 'idkey'. Must be '0' or '1'.
Reimplemented in SQSpillMap_v1.
Definition at line 38 of file SQSpillMap.h.
empty()
virtual bool SQSpillMap::empty () const inline virtual
Return 'true' if this object holds no spill.
Reimplemented in SQSpillMap_v1.
Definition at line 36 of file SQSpillMap.h.
end() [1/2]
virtual Iter SQSpillMap::end () inline virtual
Return the end iterator.
Reimplemented in SQSpillMap_v1.
Definition at line 52 of file SQSpillMap.h.
end() [2/2]
virtual ConstIter SQSpillMap::end () const inline virtual
Return the const end iterator.
Reimplemented in SQSpillMap_v1.
Definition at line 48 of file SQSpillMap.h.
erase()
virtual size_t SQSpillMap::erase (unsigned int idkey) inline virtual
Erase the SQSpill entry having spill ID = 'idkey'.
Reimplemented in SQSpillMap_v1.
Definition at line 44 of file SQSpillMap.h.
find() [1/2]
virtual Iter SQSpillMap::find (unsigned int idkey) inline virtual
Return the iterator of the SQSpill entry having spill ID = 'idkey'.
Reimplemented in SQSpillMap_v1.
Definition at line 51 of file SQSpillMap.h.
find() [2/2]
virtual ConstIter SQSpillMap::find (unsigned int idkey) const inline virtual
Return the const iterator of the SQSpill entry having spill ID = 'idkey'.
Reimplemented in SQSpillMap_v1.
Definition at line 47 of file SQSpillMap.h.
get() [1/2]
virtual SQSpill* SQSpillMap::get (unsigned int idkey) inline virtual
Return the SQSpill entry having spill ID = 'idkey'. Return '0' if no entry exists.
Reimplemented in SQSpillMap_v1.
Definition at line 42 of file SQSpillMap.h.
References NULL.
get() [2/2]
virtual const SQSpill* SQSpillMap::get (unsigned int idkey) const inline virtual
Return the SQSpill entry having spill ID = 'idkey'. Return '0' if no entry exists.
Reimplemented in SQSpillMap_v1.
Definition at line 41 of file SQSpillMap.h.
References NULL.
Referenced by SQReco::BuildSRawEvent(), Fun4AllSRawEventInputManager::E906ToE1039(), MakeMyTree::process_event(), DbUpSpill::process_event(), Fun4AllEVIOInputManager::run(), Fun4AllSRawEventOutputManagerV2::Write(), Fun4AllSpillSRawEventOutputManager::Write(), and Fun4AllSRawEventOutputManager::Write().
identify()
virtual void SQSpillMap::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SQSpillMap_v1.
Definition at line 29 of file SQSpillMap.h.
insert()
virtual SQSpill* SQSpillMap::insert (const SQSpill * hit) inline virtual
Insert the given SQSpill object.
Reimplemented in SQSpillMap_v1.
Definition at line 43 of file SQSpillMap.h.
References NULL.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), and Fun4AllEVIOInputManager::run().
isValid()
virtual int SQSpillMap::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SQSpillMap_v1.
Definition at line 33 of file SQSpillMap.h.
Reset()
virtual void SQSpillMap::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SQSpillMap_v1.
Definition at line 32 of file SQSpillMap.h.
size()
virtual size_t SQSpillMap::size (void) const inline virtual
Return the number of spills held.
Reimplemented in SQSpillMap_v1.
Definition at line 37 of file SQSpillMap.h.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSpillMap.h