Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Pythia8Demo/Fun4Sim.C File Reference
Fun4Sim.C File Reference
#include <iostream>
Functions
int Fun4Sim (const int nEvents=1)
PHG4ParticleGun * get_gun (const char *name="PGUN")
Function Documentation
int Fun4Sim (const int nEvents = 1)
Definition at line 6 of file Fun4Sim.C.
References PHG4DSTReader::AddNode(), PHPy8ParticleTrigger::AddParticles(), ana(), Fun4AllServer::End(), PHGeomUtility::ExportGeomtry(), Fun4AllServer::instance(), PHPythia8::register_trigger(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), se, PHPythia8::set_config_file(), PHG4Reco::set_field_map(), PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHG4ParticleGeneratorBase::set_mom(), PHG4ParticleGeneratorBase::set_name(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), PHPythia8::set_vertex_distribution_mean(), PHG4ParticleGeneratorBase::set_vtx(), PHG4Reco::SetPhysicsList(), SetupDriftChamber(), SetupTarget(), PHG4Reco::SetWorldMaterial(), PHG4Reco::SetWorldShape(), PHG4Reco::SetWorldSizeX(), PHG4Reco::SetWorldSizeY(), PHG4Reco::SetWorldSizeZ(), Fun4AllServer::topNode(), and Fun4AllBase::Verbosity().
PHG4ParticleGun* get_gun (const char * name = "PGUN")
Definition at line 157 of file Fun4Sim.C.
References Fun4AllServer::getSubsysReco(), Fun4AllServer::instance(), and se.