Class Reference for E1039 Core & Analysis Software: PHField Class Reference
PHField Class Reference abstract
transient DST object for field storage and access
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHField.h>
Public Member Functions
PHField (const int verb=0)
constructor
virtual ~PHField ()
virtual void GetFieldValue (const double Point[4], double *Bfield) const =0
virtual void identify (std::ostream &os=std::cout) const
void Verbosity (const int i)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
unsigned verb_
Detailed Description
transient DST object for field storage and access
Definition at line 13 of file PHField.h.
Constructor & Destructor Documentation
PHField()
PHField::PHField (const int verb = 0) inline explicit
constructor
Definition at line 17 of file PHField.h.
~PHField()
virtual PHField::~PHField () inline virtual
Definition at line 21 of file PHField.h.
Member Function Documentation
GetFieldValue()
virtual void PHField::GetFieldValue (const double Point[4], double * Bfield) const pure virtual
access field value Follow the convention of G4ElectroMagneticField
Parameters
[in] Point space time coordinate. x, y, z, t in Geant4/CLHEP units
[out] Bfield field value. In the case of magnetic field, the order is Bx, By, Bz in in Geant4/CLHEP units
Implemented in SQField3DCartesian, PHFieldUniform, PHFieldSeaQuest, PHFieldRegionalConst, PHField3DCylindrical, PHField3DCartesian, and PHField2D.
Referenced by SQGenFit::GFField::get(), PHG4MagneticField::GetFieldValue(), and GenFitExtrapolator::init().
identify()
virtual void PHField::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHFieldSeaQuest, and PHFieldRegionalConst.
Definition at line 30 of file PHField.h.
Referenced by SQReco::InitField(), and VertexFit::InitRun().
Verbosity()
void PHField::Verbosity (const int i) inline
Definition at line 32 of file PHField.h.
References verb_.
Member Data Documentation
verb_
unsigned PHField::verb_ protected
Definition at line 34 of file PHField.h.
Referenced by PHField2D::GetFieldCyl(), PHField3DCylindrical::GetFieldCyl(), PHField2D::GetFieldValue(), PHField3DCylindrical::GetFieldValue(), PHField2D::PHField2D(), PHField3DCylindrical::PHField3DCylindrical(), and Verbosity().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHField.h