Class Reference for E1039 Core & Analysis Software: SQDimuon_v1 Class Reference
SQDimuon_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQDimuon_v1.h>
Public Member Functions
SQDimuon_v1 ()
virtual ~SQDimuon_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQDimuon * Clone () const
int get_dimuon_id () const
Return the dimuon ID, which is unique per event(?).
void set_dimuon_id (const int a)
virtual int get_rec_dimuon_id () const
Return the dimuon ID of associated reconstructed dimuon. Valid only if this object holds truth dimuon info.
virtual void set_rec_dimuon_id (const int a)
int get_pdg_id () const
Return the GPD ID of parent particle. It is valid only for true dimuon.
void set_pdg_id (const int a)
int get_track_id_pos () const
Return the track ID of the positive track.
void set_track_id_pos (const int a)
int get_track_id_neg () const
Return the track ID of the negative track.
void set_track_id_neg (const int a)
TVector3 get_pos () const
Return the dimuon position at vertex.
void set_pos (const TVector3 a)
TLorentzVector get_mom () const
Return the dimuon momentum at vertex.
void set_mom (const TLorentzVector a)
TLorentzVector get_mom_pos () const
Return the momentum of the positive track at vertex.
void set_mom_pos (const TLorentzVector a)
TLorentzVector get_mom_neg () const
Return the momentum of the negative track at vertex.
void set_mom_neg (const TLorentzVector a)
virtual double get_mass () const
virtual double get_x1 () const
virtual double get_x2 () const
virtual double get_xf () const
virtual double get_chisq () const
Public Member Functions inherited from SQDimuon
virtual ~SQDimuon ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
ClassDef (SQDimuon_v1, 1)
Protected Member Functions inherited from SQDimuon
SQDimuon ()
ClassDef (SQDimuon, 1)
Protected Attributes
int _id
int _rec_id
int _pdg_id
int _track_id_pos
int _track_id_neg
TVector3 _pos
TLorentzVector _mom
TLorentzVector _mom_pos
TLorentzVector _mom_neg
Detailed Description
Definition at line 5 of file SQDimuon_v1.h.
Constructor & Destructor Documentation
SQDimuon_v1::SQDimuon_v1 ()
Definition at line 6 of file SQDimuon_v1.cxx.
Referenced by Clone().
SQDimuon_v1::~SQDimuon_v1 () virtual
Definition at line 20 of file SQDimuon_v1.cxx.
Member Function Documentation
SQDimuon_v1::ClassDef (SQDimuon_v1 , 1) protected
SQDimuon* SQDimuon_v1::Clone () const inline virtual
Implements SQDimuon.
Definition at line 13 of file SQDimuon_v1.h.
References SQDimuon_v1().
virtual double SQDimuon_v1::get_chisq () const inline virtual
Implements SQDimuon.
Definition at line 47 of file SQDimuon_v1.h.
int SQDimuon_v1::get_dimuon_id () const inline virtual
Return the dimuon ID, which is unique per event(?).
Implements SQDimuon.
Definition at line 15 of file SQDimuon_v1.h.
References _id.
virtual double SQDimuon_v1::get_mass () const inline virtual
Implements SQDimuon.
Definition at line 42 of file SQDimuon_v1.h.
References _mom.
TLorentzVector SQDimuon_v1::get_mom () const inline virtual
Return the dimuon momentum at vertex.
Implements SQDimuon.
Definition at line 33 of file SQDimuon_v1.h.
References _mom.
TLorentzVector SQDimuon_v1::get_mom_neg () const inline virtual
Return the momentum of the negative track at vertex.
Implements SQDimuon.
Definition at line 39 of file SQDimuon_v1.h.
References _mom_neg.
TLorentzVector SQDimuon_v1::get_mom_pos () const inline virtual
Return the momentum of the positive track at vertex.
Implements SQDimuon.
Definition at line 36 of file SQDimuon_v1.h.
References _mom_pos.
int SQDimuon_v1::get_pdg_id () const inline virtual
Return the GPD ID of parent particle. It is valid only for true dimuon.
Implements SQDimuon.
Definition at line 21 of file SQDimuon_v1.h.
References _pdg_id.
TVector3 SQDimuon_v1::get_pos () const inline virtual
Return the dimuon position at vertex.
Implements SQDimuon.
Definition at line 30 of file SQDimuon_v1.h.
References _pos.
virtual int SQDimuon_v1::get_rec_dimuon_id () const inline virtual
Return the dimuon ID of associated reconstructed dimuon. Valid only if this object holds truth dimuon info.
Implements SQDimuon.
Definition at line 18 of file SQDimuon_v1.h.
References _rec_id.
int SQDimuon_v1::get_track_id_neg () const inline virtual
Return the track ID of the negative track.
Implements SQDimuon.
Definition at line 27 of file SQDimuon_v1.h.
References _track_id_neg.
int SQDimuon_v1::get_track_id_pos () const inline virtual
Return the track ID of the positive track.
Implements SQDimuon.
Definition at line 24 of file SQDimuon_v1.h.
References _track_id_pos.
double SQDimuon_v1::get_x1 () const virtual
Implements SQDimuon.
Definition at line 35 of file SQDimuon_v1.cxx.
References _mom_neg, _mom_pos, E_BEAM, M_P, DPGEN::p_beam(), DPGEN::p_cms, and DPGEN::p_target().
double SQDimuon_v1::get_x2 () const virtual
Implements SQDimuon.
Definition at line 46 of file SQDimuon_v1.cxx.
References _mom_neg, _mom_pos, E_BEAM, M_P, DPGEN::p_beam(), DPGEN::p_cms, and DPGEN::p_target().
double SQDimuon_v1::get_xf () const virtual
Implements SQDimuon.
Definition at line 57 of file SQDimuon_v1.cxx.
References _mom_neg, _mom_pos, E_BEAM, M_P, DPGEN::p_beam(), DPGEN::p_cms, DPGEN::p_target(), and DPGEN::sqrts.
void SQDimuon_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Implements SQDimuon.
Definition at line 25 of file SQDimuon_v1.cxx.
int SQDimuon_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Implements SQDimuon.
Definition at line 12 of file SQDimuon_v1.h.
void SQDimuon_v1::Reset () virtual
Clear Event.
Implements SQDimuon.
Definition at line 30 of file SQDimuon_v1.cxx.
void SQDimuon_v1::set_dimuon_id (const int a) inline virtual
Implements SQDimuon.
Definition at line 16 of file SQDimuon_v1.h.
References _id.
Referenced by TruthNodeMaker::process_event().
void SQDimuon_v1::set_mom (const TLorentzVector a) inline virtual
Implements SQDimuon.
Definition at line 34 of file SQDimuon_v1.h.
References _mom.
Referenced by TruthNodeMaker::process_event().
void SQDimuon_v1::set_mom_neg (const TLorentzVector a) inline virtual
Implements SQDimuon.
Definition at line 40 of file SQDimuon_v1.h.
References _mom_neg.
Referenced by TruthNodeMaker::process_event().
void SQDimuon_v1::set_mom_pos (const TLorentzVector a) inline virtual
Implements SQDimuon.
Definition at line 37 of file SQDimuon_v1.h.
References _mom_pos.
Referenced by TruthNodeMaker::process_event().
void SQDimuon_v1::set_pdg_id (const int a) inline virtual
Implements SQDimuon.
Definition at line 22 of file SQDimuon_v1.h.
References _pdg_id.
void SQDimuon_v1::set_pos (const TVector3 a) inline virtual
Implements SQDimuon.
Definition at line 31 of file SQDimuon_v1.h.
References _pos.
Referenced by TruthNodeMaker::process_event().
virtual void SQDimuon_v1::set_rec_dimuon_id (const int a) inline virtual
Implements SQDimuon.
Definition at line 19 of file SQDimuon_v1.h.
References _rec_id.
void SQDimuon_v1::set_track_id_neg (const int a) inline virtual
Implements SQDimuon.
Definition at line 28 of file SQDimuon_v1.h.
References _track_id_neg.
Referenced by TruthNodeMaker::process_event().
void SQDimuon_v1::set_track_id_pos (const int a) inline virtual
Implements SQDimuon.
Definition at line 25 of file SQDimuon_v1.h.
References _track_id_pos.
Referenced by TruthNodeMaker::process_event().
Member Data Documentation
int SQDimuon_v1::_id protected
Definition at line 50 of file SQDimuon_v1.h.
Referenced by get_dimuon_id(), and set_dimuon_id().
TLorentzVector SQDimuon_v1::_mom protected
Definition at line 56 of file SQDimuon_v1.h.
Referenced by get_mass(), get_mom(), and set_mom().
TLorentzVector SQDimuon_v1::_mom_neg protected
Definition at line 58 of file SQDimuon_v1.h.
Referenced by get_mom_neg(), get_x1(), get_x2(), get_xf(), and set_mom_neg().
TLorentzVector SQDimuon_v1::_mom_pos protected
Definition at line 57 of file SQDimuon_v1.h.
Referenced by get_mom_pos(), get_x1(), get_x2(), get_xf(), and set_mom_pos().
int SQDimuon_v1::_pdg_id protected
Definition at line 52 of file SQDimuon_v1.h.
Referenced by get_pdg_id(), and set_pdg_id().
TVector3 SQDimuon_v1::_pos protected
Definition at line 55 of file SQDimuon_v1.h.
Referenced by get_pos(), and set_pos().
int SQDimuon_v1::_rec_id protected
Definition at line 51 of file SQDimuon_v1.h.
Referenced by get_rec_dimuon_id(), and set_rec_dimuon_id().
int SQDimuon_v1::_track_id_neg protected
Definition at line 54 of file SQDimuon_v1.h.
Referenced by get_track_id_neg(), and set_track_id_neg().
int SQDimuon_v1::_track_id_pos protected
Definition at line 53 of file SQDimuon_v1.h.
Referenced by get_track_id_pos(), and set_track_id_pos().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQDimuon_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQDimuon_v1.cxx