Class Reference for E1039 Core & Analysis Software: SQSpill_v2 Class Reference
SQSpill_v2 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSpill_v2.h>
Public Member Functions
SQSpill_v2 ()
virtual ~SQSpill_v2 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQSpill * Clone () const
virtual int get_run_id () const
Return the run ID when this spill was taken.
virtual void set_run_id (const int a)
virtual int get_spill_id () const
Return the spill ID.
virtual void set_spill_id (const int a)
virtual short get_target_pos () const
Return the target position in this spill.
virtual void set_target_pos (const short a)
virtual int get_bos_coda_id () const
[Obsolete] Use SQHardSpill instead.
virtual void set_bos_coda_id (const int a)
virtual int get_bos_vme_time () const
[Obsolete] Use SQHardSpill instead.
virtual void set_bos_vme_time (const int a)
virtual int get_eos_coda_id () const
[Obsolete] Use SQHardSpill instead.
virtual void set_eos_coda_id (const int a)
virtual int get_eos_vme_time () const
[Obsolete] Use SQHardSpill instead.
virtual void set_eos_vme_time (const int a)
virtual SQStringMap * get_bos_scaler_list ()
Return the list of scaler variables read out at BOS.
virtual SQStringMap * get_eos_scaler_list ()
Return the list of scaler variables read out at EOS.
virtual SQStringMap * get_slow_cont_list ()
Return the list of slow control variables.
Public Member Functions inherited from SQSpill
virtual ~SQSpill ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Protected Member Functions inherited from SQSpill
SQSpill ()
Detailed Description
Definition at line 11 of file SQSpill_v2.h.
Constructor & Destructor Documentation
SQSpill_v2()
SQSpill_v2::SQSpill_v2 ()
Definition at line 15 of file SQSpill_v2.cxx.
Referenced by Clone(), and Reset().
~SQSpill_v2()
SQSpill_v2::~SQSpill_v2 () virtual
Definition at line 28 of file SQSpill_v2.cxx.
Member Function Documentation
Clone()
SQSpill* SQSpill_v2::Clone () const inline virtual
Reimplemented from SQSpill.
Definition at line 23 of file SQSpill_v2.h.
References SQSpill_v2().
get_bos_coda_id()
virtual int SQSpill_v2::get_bos_coda_id () const inline virtual
[Obsolete] Use SQHardSpill instead.
Reimplemented from SQSpill.
Definition at line 34 of file SQSpill_v2.h.
get_bos_scaler_list()
virtual SQStringMap* SQSpill_v2::get_bos_scaler_list () inline virtual
Return the list of scaler variables read out at BOS.
Reimplemented from SQSpill.
Definition at line 46 of file SQSpill_v2.h.
get_bos_vme_time()
virtual int SQSpill_v2::get_bos_vme_time () const inline virtual
[Obsolete] Use SQHardSpill instead.
Reimplemented from SQSpill.
Definition at line 37 of file SQSpill_v2.h.
get_eos_coda_id()
virtual int SQSpill_v2::get_eos_coda_id () const inline virtual
[Obsolete] Use SQHardSpill instead.
Reimplemented from SQSpill.
Definition at line 40 of file SQSpill_v2.h.
get_eos_scaler_list()
virtual SQStringMap* SQSpill_v2::get_eos_scaler_list () inline virtual
Return the list of scaler variables read out at EOS.
Reimplemented from SQSpill.
Definition at line 47 of file SQSpill_v2.h.
get_eos_vme_time()
virtual int SQSpill_v2::get_eos_vme_time () const inline virtual
[Obsolete] Use SQHardSpill instead.
Reimplemented from SQSpill.
Definition at line 43 of file SQSpill_v2.h.
get_run_id()
virtual int SQSpill_v2::get_run_id () const inline virtual
Return the run ID when this spill was taken.
Reimplemented from SQSpill.
Definition at line 25 of file SQSpill_v2.h.
Referenced by identify().
get_slow_cont_list()
virtual SQStringMap* SQSpill_v2::get_slow_cont_list () inline virtual
Return the list of slow control variables.
Reimplemented from SQSpill.
Definition at line 49 of file SQSpill_v2.h.
get_spill_id()
virtual int SQSpill_v2::get_spill_id () const inline virtual
Return the spill ID.
Reimplemented from SQSpill.
Definition at line 28 of file SQSpill_v2.h.
Referenced by identify().
get_target_pos()
virtual short SQSpill_v2::get_target_pos () const inline virtual
Return the target position in this spill.
Reimplemented from SQSpill.
Definition at line 31 of file SQSpill_v2.h.
Referenced by identify().
identify()
void SQSpill_v2::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQSpill.
Definition at line 35 of file SQSpill_v2.cxx.
References get_run_id(), get_spill_id(), and get_target_pos().
isValid()
int SQSpill_v2::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQSpill.
Definition at line 45 of file SQSpill_v2.cxx.
Reset()
void SQSpill_v2::Reset () inline virtual
Clear Event.
Reimplemented from SQSpill.
Definition at line 21 of file SQSpill_v2.h.
References SQSpill_v2().
set_bos_coda_id()
virtual void SQSpill_v2::set_bos_coda_id (const int a) inline virtual
Reimplemented from SQSpill.
Definition at line 35 of file SQSpill_v2.h.
set_bos_vme_time()
virtual void SQSpill_v2::set_bos_vme_time (const int a) inline virtual
Reimplemented from SQSpill.
Definition at line 38 of file SQSpill_v2.h.
set_eos_coda_id()
virtual void SQSpill_v2::set_eos_coda_id (const int a) inline virtual
Reimplemented from SQSpill.
Definition at line 41 of file SQSpill_v2.h.
set_eos_vme_time()
virtual void SQSpill_v2::set_eos_vme_time (const int a) inline virtual
Reimplemented from SQSpill.
Definition at line 44 of file SQSpill_v2.h.
set_run_id()
virtual void SQSpill_v2::set_run_id (const int a) inline virtual
Reimplemented from SQSpill.
Definition at line 26 of file SQSpill_v2.h.
set_spill_id()
virtual void SQSpill_v2::set_spill_id (const int a) inline virtual
Reimplemented from SQSpill.
Definition at line 29 of file SQSpill_v2.h.
set_target_pos()
virtual void SQSpill_v2::set_target_pos (const short a) inline virtual
Reimplemented from SQSpill.
Definition at line 32 of file SQSpill_v2.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSpill_v2.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSpill_v2.cxx