SeaQuest Offline Software: PHG4EnvelopeSubsystem Class Reference
PHG4EnvelopeSubsystem Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4EnvelopeSubsystem.h>
Public Member Functions
PHG4EnvelopeSubsystem (const std::string &name="ENVELOPE_DEFAULT", const int layer=0)
virtual ~PHG4EnvelopeSubsystem (void)
int Init (PHCompositeNode *)
int process_event (PHCompositeNode *)
virtual PHG4Detector * GetDetector (void) const
return pointer to created detector object
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4EnvelopeDetector * detector_
PHG4EnvelopeSteppingAction * steppingAction_
PHG4EventAction * eventAction_
G4String material
int active
std::string detector_type
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from PHG4Subsystem
bool overlapcheck
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 17 of file PHG4EnvelopeSubsystem.h.
Constructor & Destructor Documentation
PHG4EnvelopeSubsystem::PHG4EnvelopeSubsystem (const std::string & name = "ENVELOPE_DEFAULT", const int layer = 0)
Definition at line 14 of file PHG4EnvelopeSubsystem.cc.
virtual PHG4EnvelopeSubsystem::~PHG4EnvelopeSubsystem (void) inline virtual
Definition at line 24 of file PHG4EnvelopeSubsystem.h.
Member Function Documentation
PHG4Detector * PHG4EnvelopeSubsystem::GetDetector (void) const virtual
return pointer to created detector object
Reimplemented from PHG4Subsystem.
Definition at line 72 of file PHG4EnvelopeSubsystem.cc.
References detector_.
PHG4SteppingAction * PHG4EnvelopeSubsystem::GetSteppingAction (void) const virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 79 of file PHG4EnvelopeSubsystem.cc.
References steppingAction_.
int PHG4EnvelopeSubsystem::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 26 of file PHG4EnvelopeSubsystem.cc.
References active, PHCompositeNode::addNode(), detector_, detector_type, PHNodeIterator::findFirst(), Fun4AllBase::Name(), PHG4Subsystem::overlapcheck, PHG4Detector::OverlapCheck(), PHG4EnvelopeDetector::SetActive(), and steppingAction_.
int PHG4EnvelopeSubsystem::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 59 of file PHG4EnvelopeSubsystem.cc.
References PHG4EnvelopeSteppingAction::SetInterfacePointers(), and steppingAction_.
Member Data Documentation
int PHG4EnvelopeSubsystem::active private
Definition at line 51 of file PHG4EnvelopeSubsystem.h.
Referenced by Init().
PHG4EnvelopeDetector* PHG4EnvelopeSubsystem::detector_ private
Definition at line 44 of file PHG4EnvelopeSubsystem.h.
Referenced by GetDetector(), and Init().
std::string PHG4EnvelopeSubsystem::detector_type private
Definition at line 53 of file PHG4EnvelopeSubsystem.h.
Referenced by Init().
PHG4EventAction* PHG4EnvelopeSubsystem::eventAction_ private
Definition at line 48 of file PHG4EnvelopeSubsystem.h.
G4String PHG4EnvelopeSubsystem::material private
Definition at line 50 of file PHG4EnvelopeSubsystem.h.
PHG4EnvelopeSteppingAction* PHG4EnvelopeSubsystem::steppingAction_ private
Definition at line 47 of file PHG4EnvelopeSubsystem.h.
Referenced by GetSteppingAction(), Init(), and process_event().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4EnvelopeSubsystem.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4EnvelopeSubsystem.cc