Class Reference for E1039 Core & Analysis Software: UtilHodo::Track2D Struct Reference
UtilHodo::Track2D Struct Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/UtilHodo.h>
Public Member Functions
Track2D ()
~Track2D ()
void AddHit (SQHit *hit)
int DoTracking ()
TGraph * GetGraphX ()
TGraph * GetGraphY ()
int GetNDF ()
double GetChi2 ()
TVector3 GetPos0 ()
TVector3 GetSlope ()
TVector3 GetPos (const double z)
Public Attributes
Track1D trk_x
Track1D trk_y
Detailed Description
Definition at line 32 of file UtilHodo.h.
Constructor & Destructor Documentation
Track2D()
UtilHodo::Track2D::Track2D ()
Definition at line 77 of file UtilHodo.cc.
~Track2D()
UtilHodo::Track2D::~Track2D () inline
Definition at line 37 of file UtilHodo.h.
Member Function Documentation
AddHit()
void UtilHodo::Track2D::AddHit (SQHit * hit)
Definition at line 82 of file UtilHodo.cc.
References SQHit::get_detector_id(), UtilHodo::IsHodoX(), UtilHodo::Track1D::list_hit, trk_x, and trk_y.
DoTracking()
int UtilHodo::Track2D::DoTracking ()
Definition at line 88 of file UtilHodo.cc.
References UtilHodo::Track1D::DoTracking(), trk_x, and trk_y.
GetChi2()
double UtilHodo::Track2D::GetChi2 ()
Definition at line 110 of file UtilHodo.cc.
References UtilHodo::Track1D::chi2, trk_x, and trk_y.
GetGraphX()
TGraph * UtilHodo::Track2D::GetGraphX ()
Definition at line 95 of file UtilHodo.cc.
References UtilHodo::Track1D::graph, and trk_x.
GetGraphY()
TGraph * UtilHodo::Track2D::GetGraphY ()
Definition at line 100 of file UtilHodo.cc.
References UtilHodo::Track1D::graph, and trk_y.
GetNDF()
int UtilHodo::Track2D::GetNDF ()
Definition at line 105 of file UtilHodo.cc.
References UtilHodo::Track1D::ndf, trk_x, and trk_y.
GetPos()
TVector3 UtilHodo::Track2D::GetPos (const double z)
Definition at line 125 of file UtilHodo.cc.
References GetPos0(), and GetSlope().
GetPos0()
TVector3 UtilHodo::Track2D::GetPos0 ()
Definition at line 115 of file UtilHodo.cc.
References UtilHodo::Track1D::pos, trk_x, and trk_y.
Referenced by GetPos().
GetSlope()
TVector3 UtilHodo::Track2D::GetSlope ()
Definition at line 120 of file UtilHodo.cc.
References UtilHodo::Track1D::slope, trk_x, and trk_y.
Referenced by GetPos().
Member Data Documentation
trk_x
Track1D UtilHodo::Track2D::trk_x
Definition at line 33 of file UtilHodo.h.
Referenced by AddHit(), DoTracking(), GetChi2(), GetGraphX(), GetNDF(), GetPos0(), and GetSlope().
trk_y
Track1D UtilHodo::Track2D::trk_y
Definition at line 34 of file UtilHodo.h.
Referenced by AddHit(), DoTracking(), GetChi2(), GetGraphY(), GetNDF(), GetPos0(), and GetSlope().
The documentation for this struct was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/UtilHodo.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/UtilHodo.cc