Class Reference for E1039 Core & Analysis Software: SQEvent_v2 Class Reference
SQEvent_v2 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQEvent_v2.h>
Public Member Functions
SQEvent_v2 ()
virtual ~SQEvent_v2 ()
virtual void Reset ()
Clear Event.
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual SQEvent * Clone () const
virtual int get_run_id () const
Return the run ID.
virtual void set_run_id (const int a)
virtual int get_spill_id () const
Return the spill ID.
virtual void set_spill_id (const int a)
virtual int get_event_id () const
Return the event ID, which is unique per run.
virtual void set_event_id (const int a)
virtual int get_data_quality () const
Return the data-quality bits.
virtual void set_data_quality (const int a)
virtual bool get_trigger (const SQEvent::TriggerMask i) const
Return the trigger bit (fired or not) of the selected trigger channel.
virtual void set_trigger (const SQEvent::TriggerMask i, const bool a)
virtual unsigned short get_trigger () const
Return the full trigger bits.
virtual void set_trigger (const unsigned short a)
virtual int get_qie_presum (const unsigned short i) const
Return the i-th QIE presum, where i=0...3.
virtual void set_qie_presum (const unsigned short i, const int a)
virtual int get_qie_trigger_count () const
Return the QIE trigger counts.
virtual void set_qie_trigger_count (const int a)
virtual int get_qie_turn_id () const
Return the QIE turn ID.
virtual void set_qie_turn_id (const int a)
virtual int get_qie_rf_id () const
Return the QIE RF ID.
virtual void set_qie_rf_id (const int a)
virtual int get_qie_rf_intensity (const short i) const
Return the i-th QIE RF intensity, where i=-16...+16.
virtual void set_qie_rf_intensity (const short i, const int a)
ClassDef (SQEvent_v2, 1)
Public Member Functions inherited from SQEvent
virtual ~SQEvent ()
virtual int get_coda_event_id () const
[Obsolete] Use SQHardEvent instead.
virtual void set_coda_event_id (const int a)
virtual int get_vme_time () const
[Obsolete] Use SQHardEvent instead.
virtual void set_vme_time (const int a)
virtual int get_raw_matrix (const unsigned short i) const
[Obsolete] Use SQHardEvent instead.
virtual void set_raw_matrix (const unsigned short i, const bool a)
virtual int get_after_inh_matrix (const unsigned short i) const
[Obsolete] Use SQHardEvent instead.
virtual void set_after_inh_matrix (const unsigned short i, const bool a)
virtual short get_flag_v1495 () const
[Obsolete] Use SQHardEvent instead.
virtual void set_flag_v1495 (const short a)
virtual short get_n_board_qie () const
[Obsolete] Use SQHardEvent instead.
virtual void set_n_board_qie (const short a)
virtual short get_n_board_v1495 () const
[Obsolete] Use SQHardEvent instead.
virtual void set_n_board_v1495 (const short a)
virtual short get_n_board_taiwan () const
[Obsolete] Use SQHardEvent instead.
virtual void set_n_board_taiwan (const short a)
virtual short get_n_board_trig_bit () const
[Obsolete] Use SQHardEvent instead.
virtual void set_n_board_trig_bit (const short a)
virtual short get_n_board_trig_count () const
[Obsolete] Use SQHardEvent instead.
virtual void set_n_board_trig_count (const short a)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from SQEvent
enum TriggerMask {
NIM1 = 0 , NIM2 = 1 , NIM3 = 2 , NIM4 = 3 ,
NIM5 = 4 , MATRIX1 = 5 , MATRIX2 = 6 , MATRIX3 = 7 ,
MATRIX4 = 8 , MATRIX5 = 9
}
Protected Member Functions inherited from SQEvent
SQEvent ()
ClassDef (SQEvent, 1)
Detailed Description
Definition at line 9 of file SQEvent_v2.h.
Constructor & Destructor Documentation
SQEvent_v2()
SQEvent_v2::SQEvent_v2 ()
Referenced by Clone().
~SQEvent_v2()
SQEvent_v2::~SQEvent_v2 () virtual
Definition at line 20 of file SQEvent_v2.cxx.
References Reset().
Member Function Documentation
ClassDef()
SQEvent_v2::ClassDef (SQEvent_v2 , 1)
Clone()
virtual SQEvent* SQEvent_v2::Clone () const inline virtual
Definition at line 29 of file SQEvent_v2.h.
References SQEvent_v2().
get_data_quality()
virtual int SQEvent_v2::get_data_quality () const inline virtual
Return the data-quality bits.
Implements SQEvent.
Definition at line 40 of file SQEvent_v2.h.
get_event_id()
virtual int SQEvent_v2::get_event_id () const inline virtual
Return the event ID, which is unique per run.
Implements SQEvent.
Definition at line 37 of file SQEvent_v2.h.
get_qie_presum()
virtual int SQEvent_v2::get_qie_presum (const unsigned short i) const inline virtual
Return the i-th QIE presum, where i=0...3.
Implements SQEvent.
Definition at line 49 of file SQEvent_v2.h.
get_qie_rf_id()
virtual int SQEvent_v2::get_qie_rf_id () const inline virtual
Return the QIE RF ID.
Implements SQEvent.
Definition at line 64 of file SQEvent_v2.h.
get_qie_rf_intensity()
virtual int SQEvent_v2::get_qie_rf_intensity (const short i) const inline virtual
Return the i-th QIE RF intensity, where i=-16...+16.
Implements SQEvent.
Definition at line 67 of file SQEvent_v2.h.
get_qie_trigger_count()
virtual int SQEvent_v2::get_qie_trigger_count () const inline virtual
Return the QIE trigger counts.
Implements SQEvent.
Definition at line 58 of file SQEvent_v2.h.
get_qie_turn_id()
virtual int SQEvent_v2::get_qie_turn_id () const inline virtual
Return the QIE turn ID.
Implements SQEvent.
Definition at line 61 of file SQEvent_v2.h.
get_run_id()
virtual int SQEvent_v2::get_run_id () const inline virtual
Return the run ID.
Implements SQEvent.
Definition at line 31 of file SQEvent_v2.h.
get_spill_id()
virtual int SQEvent_v2::get_spill_id () const inline virtual
Return the spill ID.
Implements SQEvent.
Definition at line 34 of file SQEvent_v2.h.
get_trigger() [1/2]
virtual unsigned short SQEvent_v2::get_trigger () const inline virtual
Return the full trigger bits.
Implements SQEvent.
Definition at line 46 of file SQEvent_v2.h.
Referenced by identify().
get_trigger() [2/2]
virtual bool SQEvent_v2::get_trigger (const SQEvent::TriggerMask i) const inline virtual
Return the trigger bit (fired or not) of the selected trigger channel.
Implements SQEvent.
Definition at line 43 of file SQEvent_v2.h.
identify()
void SQEvent_v2::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQEvent.
Definition at line 39 of file SQEvent_v2.cxx.
References get_trigger(), SQEvent::MATRIX1, SQEvent::MATRIX5, SQEvent::NIM1, and SQEvent::NIM5.
isValid()
virtual int SQEvent_v2::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 28 of file SQEvent_v2.h.
Reset()
void SQEvent_v2::Reset () virtual
Clear Event.
Reimplemented from SQEvent.
Definition at line 25 of file SQEvent_v2.cxx.
Referenced by ~SQEvent_v2().
set_data_quality()
virtual void SQEvent_v2::set_data_quality (const int a) inline virtual
Implements SQEvent.
Definition at line 41 of file SQEvent_v2.h.
set_event_id()
virtual void SQEvent_v2::set_event_id (const int a) inline virtual
Implements SQEvent.
Definition at line 38 of file SQEvent_v2.h.
set_qie_presum()
virtual void SQEvent_v2::set_qie_presum (const unsigned short i, const int a) inline virtual
Implements SQEvent.
Definition at line 53 of file SQEvent_v2.h.
set_qie_rf_id()
virtual void SQEvent_v2::set_qie_rf_id (const int a) inline virtual
Implements SQEvent.
Definition at line 65 of file SQEvent_v2.h.
set_qie_rf_intensity()
virtual void SQEvent_v2::set_qie_rf_intensity (const short i, const int a) inline virtual
Implements SQEvent.
Definition at line 71 of file SQEvent_v2.h.
set_qie_trigger_count()
virtual void SQEvent_v2::set_qie_trigger_count (const int a) inline virtual
Implements SQEvent.
Definition at line 59 of file SQEvent_v2.h.
set_qie_turn_id()
virtual void SQEvent_v2::set_qie_turn_id (const int a) inline virtual
Implements SQEvent.
Definition at line 62 of file SQEvent_v2.h.
set_run_id()
virtual void SQEvent_v2::set_run_id (const int a) inline virtual
Implements SQEvent.
Definition at line 32 of file SQEvent_v2.h.
set_spill_id()
virtual void SQEvent_v2::set_spill_id (const int a) inline virtual
Implements SQEvent.
Definition at line 35 of file SQEvent_v2.h.
set_trigger() [1/2]
virtual void SQEvent_v2::set_trigger (const SQEvent::TriggerMask i, const bool a) inline virtual
Implements SQEvent.
Definition at line 44 of file SQEvent_v2.h.
set_trigger() [2/2]
virtual void SQEvent_v2::set_trigger (const unsigned short a) inline virtual
Implements SQEvent.
Definition at line 47 of file SQEvent_v2.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQEvent_v2.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQEvent_v2.cxx