Class Reference for E1039 Core & Analysis Software: GenericSD Class Reference
GenericSD Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/db2g4/GenericSD.hh>
Public Member Functions
GenericSD (G4String)
~GenericSD ()
void Initialize (G4HCofThisEvent *)
G4bool ProcessHits (G4Step *, G4TouchableHistory *)
void EndOfEvent (G4HCofThisEvent *)
Detailed Description
Definition at line 16 of file GenericSD.hh.
Constructor & Destructor Documentation
GenericSD()
GenericSD::GenericSD (G4String name)
Definition at line 5 of file GenericSD.cc.
~GenericSD()
GenericSD::~GenericSD ()
Definition at line 11 of file GenericSD.cc.
Member Function Documentation
EndOfEvent()
void GenericSD::EndOfEvent (G4HCofThisEvent *)
Definition at line 58 of file GenericSD.cc.
Initialize()
void GenericSD::Initialize (G4HCofThisEvent * HCE)
Definition at line 15 of file GenericSD.cc.
ProcessHits()
G4bool GenericSD::ProcessHits (G4Step * aStep, G4TouchableHistory *)
Definition at line 24 of file GenericSD.cc.
References MCHit::SetDE(), MCHit::SetMomentum(), MCHit::SetParentID(), MCHit::SetParticleID(), MCHit::SetParticleName(), MCHit::SetPosition(), MCHit::SetTime(), MCHit::SetTrackID(), MCHit::SetVertex(), MCHit::SetVertexKineticEnergy(), MCHit::SetVertexMomentumDirection(), and MCHit::SetVolume().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/db2g4/GenericSD.hh
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/db2g4/GenericSD.cc