Class Reference for E1039 Core & Analysis Software: PHIOManager Class Reference
PHIOManager Class Reference abstract
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHIOManager.h>
Public Member Functions
virtual ~PHIOManager ()
std::string getFilename () const
size_t getEventNumber () const
void setEventNumber (const size_t evno)
virtual void closeFile ()=0
virtual PHBoolean write (PHCompositeNode *)=0
virtual void print () const =0
Protected Member Functions
PHIOManager ()
Protected Attributes
std::string filename
size_t eventNumber
Detailed Description
Definition at line 14 of file PHIOManager.h.
Constructor & Destructor Documentation
~PHIOManager()
virtual PHIOManager::~PHIOManager () inline virtual
Definition at line 16 of file PHIOManager.h.
PHIOManager()
PHIOManager::PHIOManager () protected
Definition at line 13 of file PHIOManager.cc.
Member Function Documentation
closeFile()
virtual void PHIOManager::closeFile () pure virtual
Implemented in PHNodeIOManager.
getEventNumber()
size_t PHIOManager::getEventNumber () const inline
Definition at line 20 of file PHIOManager.h.
References eventNumber.
Referenced by Fun4AllDstInputManager::PushBackEvents(), and Fun4AllDstInputManager::ReadNextEventSyncObject().
getFilename()
std::string PHIOManager::getFilename () const inline
Definition at line 19 of file PHIOManager.h.
References filename.
print()
virtual void PHIOManager::print () const pure virtual
Implemented in PHNodeIOManager.
setEventNumber()
void PHIOManager::setEventNumber (const size_t evno) inline
Definition at line 21 of file PHIOManager.h.
References eventNumber.
Referenced by Fun4AllDstInputManager::PushBackEvents(), and Fun4AllDstInputManager::ReadNextEventSyncObject().
write()
virtual PHBoolean PHIOManager::write (PHCompositeNode *) pure virtual
Implemented in PHNodeIOManager.
Member Data Documentation
eventNumber
size_t PHIOManager::eventNumber protected
Definition at line 29 of file PHIOManager.h.
Referenced by getEventNumber(), setEventNumber(), and PHNodeIOManager::write().
filename
std::string PHIOManager::filename protected
Definition at line 28 of file PHIOManager.h.
Referenced by getFilename(), PHNodeIOManager::print(), and PHNodeIOManager::setFile().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHIOManager.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHIOManager.cc