Class Reference for E1039 Core & Analysis Software: KalmanFitter Class Reference
KalmanFitter Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/kfitter/KalmanFitter.h>
Public Member Functions
KalmanFitter (const PHField *field, const TGeoManager *geom)
void setControlParameter (int nMaxIteration, double tolerance)
Set the convergence control parameters.
int processOneTrack (KalmanTrack &_track)
void updateTrack (KalmanTrack &_track)
void init ()
Initialize the kalman filter.
int initNodeList (KalmanTrack &_track)
Initialize the node list.
void updateAlignment ()
Update the actual z position of each node according to current fit results.
void setStartingParameter (KalmanTrack &_track)
Set the starting parameters.
void setStartingParameter (Node &_node)
bool initSmoother (Node &_node)
Initialize the smoother.
std::list< Node > & getNodeList ()
return the node list
double findVertex ()
Vertex finder.
double getMomentumInitial (double &px, double &py, double &pz)
Get the final results – temporary interfaces, just for debugging purposes.
double getMomentumFinal (double &px, double &py, double &pz)
double getPositionInitial (double &x, double &y, double &z)
double getPositionFinal (double &x, double &y, double &z)
double getChisq ()
const TrkPar & getTrkParInitial ()
const TrkPar & getTrkParFinal ()
Detailed Description
Definition at line 24 of file KalmanFitter.h.
Constructor & Destructor Documentation
KalmanFitter::KalmanFitter (const PHField * field, const TGeoManager * geom)
Definition at line 20 of file KalmanFitter.cxx.
References GeomSvc::getPlaneCenterZ(), GeomSvc::getRotationInX(), GeomSvc::getRotationInY(), GeomSvc::getRotationInZ(), KalmanFilter::initExtrapolator(), KalmanFilter::instance(), GeomSvc::instance(), and nChamberPlanes.
Member Function Documentation
double KalmanFitter::findVertex ()
Vertex finder.
double KalmanFitter::getChisq () inline
Definition at line 68 of file KalmanFitter.h.
double KalmanFitter::getMomentumFinal (double & px, double & py, double & pz) inline
Definition at line 63 of file KalmanFitter.h.
double KalmanFitter::getMomentumInitial (double & px, double & py, double & pz) inline
Get the final results – temporary interfaces, just for debugging purposes.
Definition at line 62 of file KalmanFitter.h.
std::list<Node>& KalmanFitter::getNodeList () inline
return the node list
Definition at line 56 of file KalmanFitter.h.
double KalmanFitter::getPositionFinal (double & x, double & y, double & z) inline
Definition at line 66 of file KalmanFitter.h.
double KalmanFitter::getPositionInitial (double & x, double & y, double & z) inline
Definition at line 65 of file KalmanFitter.h.
const TrkPar& KalmanFitter::getTrkParFinal () inline
Definition at line 71 of file KalmanFitter.h.
const TrkPar& KalmanFitter::getTrkParInitial () inline
Definition at line 70 of file KalmanFitter.h.
void KalmanFitter::init ()
Initialize the kalman filter.
Definition at line 42 of file KalmanFitter.cxx.
Referenced by processOneTrack().
int KalmanFitter::initNodeList (KalmanTrack & _track)
Initialize the node list.
Definition at line 130 of file KalmanFitter.cxx.
References KalmanTrack::getNodeList().
Referenced by processOneTrack().
bool KalmanFitter::initSmoother (Node & _node)
Initialize the smoother.
Definition at line 192 of file KalmanFitter.cxx.
References Node::getFiltered(), Node::getSmoothed(), Node::isFilterDone(), Node::isSmoothDone(), LogInfo, and Node::setSmoothDone().
Referenced by processOneTrack().
int KalmanFitter::processOneTrack (KalmanTrack & _track)
external call to process one single tracks the prediction-filter-smooth cycle is iteratively done until the chi square converges
Initialize the nodes from the input track
Set the initial track parameters
Call the kalman filter core functions iteratively until the chi square converges
Definition at line 51 of file KalmanFitter.cxx.
References KalmanFilter::fit_node(), init(), initNodeList(), initSmoother(), LogInfo, KalmanFilter::setCurrTrkpar(), setStartingParameter(), KalmanFilter::smooth(), and updateAlignment().
Referenced by KalmanFastTracking::fitTrack(), and KalmanDSTrk::fitTrack().
void KalmanFitter::setControlParameter (int nMaxIteration, double tolerance) inline
Set the convergence control parameters.
Definition at line 31 of file KalmanFitter.h.
Referenced by SQReco::InitRun().
void KalmanFitter::setStartingParameter (KalmanTrack & _track)
Set the starting parameters.
Definition at line 187 of file KalmanFitter.cxx.
References KalmanTrack::getNodeList(), and KalmanFilter::setCurrTrkpar().
Referenced by processOneTrack().
void KalmanFitter::setStartingParameter (Node & _node)
Method 1.
Definition at line 169 of file KalmanFitter.cxx.
References Node::getSmoothed(), and KalmanFilter::setCurrTrkpar().
void KalmanFitter::updateAlignment ()
Update the actual z position of each node according to current fit results.
Definition at line 140 of file KalmanFitter.cxx.
Referenced by processOneTrack().
void KalmanFitter::updateTrack (KalmanTrack & _track)
Definition at line 123 of file KalmanFitter.cxx.
References KalmanTrack::getNodeList(), KalmanTrack::setCurrTrkpar(), and KalmanTrack::update().
Referenced by KalmanFastTracking::fitTrack(), and KalmanDSTrk::fitTrack().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/kfitter/KalmanFitter.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/kfitter/KalmanFitter.cxx