Class Reference for E1039 Core & Analysis Software: SQCalMCHit_v1 Class Reference
SQCalMCHit_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQCalMCHit_v1.h>
Public Member Functions
SQCalMCHit_v1 ()
virtual ~SQCalMCHit_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQHit * Clone () const
virtual int get_track_id () const
Return the track ID associated with this hit. Probably the value is not properly set at present.
virtual void set_track_id (const int a)
virtual int get_shower_id () const
virtual void set_shower_id (const int a)
virtual PHG4HitDefs::keytype get_g4hit_id () const
Return the Geant-hit ID associated with this hit.
virtual void set_g4hit_id (const PHG4HitDefs::keytype a)
virtual float get_truth_x () const
Return the true x-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_x (const float a)
virtual float get_truth_y () const
Return the true y-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_y (const float a)
virtual float get_truth_z () const
Return the true z-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_z (const float a)
virtual float get_truth_px () const
Return the true x-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_px (const float a)
virtual float get_truth_py () const
Return the true y-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_py (const float a)
virtual float get_truth_pz () const
Return the true z-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_pz (const float a)
Public Member Functions inherited from SQCalHit_v1
SQCalHit_v1 ()
virtual ~SQCalHit_v1 ()
virtual int get_hit_id () const
Return the ID of this hit.
virtual void set_hit_id (const int a)
virtual short get_detector_id () const
Return the detector ID of this hit.
virtual void set_detector_id (const short a)
virtual short get_element_id () const
Return the element ID of this hit.
virtual void set_element_id (const short id)
virtual short get_tower_id () const
Not valid in E1039. To be deleted.
virtual void set_tower_id (const short id)
virtual float get_edep () const
Not valid in E1039. To be deleted.
virtual void set_edep (const float a)
virtual unsigned int get_n_cells () const
Return the number of cells included in this hit.
virtual CellMap get_cells () const
Return the list of all cells included in this hit.
virtual float get_cell (short i) const
virtual void add_cell (short i, float edep)
Public Member Functions inherited from SQHit
SQHit ()
virtual ~SQHit ()
virtual short get_level () const
Return the trigger level of this hit. Meaningful only if this hit is of V1495 TDC.
virtual void set_level (const short a)
virtual float get_tdc_time () const
Return the TDC time (nsec) of this hit.
virtual void set_tdc_time (const float a)
virtual float get_drift_distance () const
Return the drift distance of this hit. Probably the value is not properly set at present. Meaningful only if this hit is of drift chamber or prop tube.
virtual void set_drift_distance (const float a)
virtual float get_pos () const
Return the absolute position of this hit. Probably the value is not properly set at present.
virtual void set_pos (const float a)
virtual bool is_in_time () const
Return 'true' if this hit is in the time window.
virtual void set_in_time (const bool a)
virtual bool is_hodo_mask () const
Return 'true' if this hit is accepted (or masked out?) by the hodoscope masking. Meaningful only if this hit is of drift chamber.
virtual void set_hodo_mask (const bool a)
virtual bool is_trigger_mask () const
Return 'true' if this hit is accepted (or masked out?) by the trigger-road masking. Meaningful only if this hit is of drift chamber.
virtual void set_trigger_mask (const bool a)
virtual float get_cell (unsigned int i) const
Return the 'edep' value of the i-th cell.
virtual void add_cell (unsigned int i, float a)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from SQHit
enum HitQuality { InTime = 1<<0 , HodoMask = 1<<1 , TriggerMask = 1<<2 }
typedef std::map< short, float > CellMap
key -> plateID, float -> edep
Detailed Description
Definition at line 11 of file SQCalMCHit_v1.h.
Constructor & Destructor Documentation
SQCalMCHit_v1()
SQCalMCHit_v1::SQCalMCHit_v1 ()
Definition at line 10 of file SQCalMCHit_v1.cxx.
Referenced by Clone(), and Reset().
~SQCalMCHit_v1()
virtual SQCalMCHit_v1::~SQCalMCHit_v1 () inline virtual
Definition at line 16 of file SQCalMCHit_v1.h.
Member Function Documentation
Clone()
SQHit* SQCalMCHit_v1::Clone () const inline virtual
Reimplemented from SQCalHit_v1.
Definition at line 22 of file SQCalMCHit_v1.h.
References SQCalMCHit_v1().
get_g4hit_id()
virtual PHG4HitDefs::keytype SQCalMCHit_v1::get_g4hit_id () const inline virtual
Return the Geant-hit ID associated with this hit.
Reimplemented from SQHit.
Definition at line 30 of file SQCalMCHit_v1.h.
get_shower_id()
virtual int SQCalMCHit_v1::get_shower_id () const inline virtual
Definition at line 27 of file SQCalMCHit_v1.h.
get_track_id()
virtual int SQCalMCHit_v1::get_track_id () const inline virtual
Return the track ID associated with this hit. Probably the value is not properly set at present.
Reimplemented from SQHit.
Definition at line 24 of file SQCalMCHit_v1.h.
Referenced by identify().
get_truth_px()
virtual float SQCalMCHit_v1::get_truth_px () const inline virtual
Return the true x-momentum of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 42 of file SQCalMCHit_v1.h.
get_truth_py()
virtual float SQCalMCHit_v1::get_truth_py () const inline virtual
Return the true y-momentum of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 45 of file SQCalMCHit_v1.h.
get_truth_pz()
virtual float SQCalMCHit_v1::get_truth_pz () const inline virtual
Return the true z-momentum of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 48 of file SQCalMCHit_v1.h.
get_truth_x()
virtual float SQCalMCHit_v1::get_truth_x () const inline virtual
Return the true x-position of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 33 of file SQCalMCHit_v1.h.
get_truth_y()
virtual float SQCalMCHit_v1::get_truth_y () const inline virtual
Return the true y-position of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 36 of file SQCalMCHit_v1.h.
get_truth_z()
virtual float SQCalMCHit_v1::get_truth_z () const inline virtual
Return the true z-position of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 39 of file SQCalMCHit_v1.h.
identify()
void SQCalMCHit_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQCalHit_v1.
Definition at line 17 of file SQCalMCHit_v1.cxx.
References SQCalHit_v1::get_hit_id(), get_track_id(), and SQCalHit_v1::identify().
isValid()
int SQCalMCHit_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQCalHit_v1.
Definition at line 30 of file SQCalMCHit_v1.cxx.
References SQCalHit_v1::isValid().
Reset()
void SQCalMCHit_v1::Reset () inline virtual
Clear Event.
Reimplemented from SQCalHit_v1.
Definition at line 20 of file SQCalMCHit_v1.h.
References SQCalMCHit_v1().
set_g4hit_id()
virtual void SQCalMCHit_v1::set_g4hit_id (const PHG4HitDefs::keytype a) inline virtual
Reimplemented from SQHit.
Definition at line 31 of file SQCalMCHit_v1.h.
Referenced by SQDigitizer::digitizeEMCal().
set_shower_id()
virtual void SQCalMCHit_v1::set_shower_id (const int a) inline virtual
Definition at line 28 of file SQCalMCHit_v1.h.
Referenced by SQDigitizer::digitizeEMCal().
set_track_id()
virtual void SQCalMCHit_v1::set_track_id (const int a) inline virtual
Reimplemented from SQHit.
Definition at line 25 of file SQCalMCHit_v1.h.
Referenced by SQDigitizer::digitizeEMCal().
set_truth_px()
virtual void SQCalMCHit_v1::set_truth_px (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 43 of file SQCalMCHit_v1.h.
Referenced by SQDigitizer::digitizeEMCal().
set_truth_py()
virtual void SQCalMCHit_v1::set_truth_py (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 46 of file SQCalMCHit_v1.h.
Referenced by SQDigitizer::digitizeEMCal().
set_truth_pz()
virtual void SQCalMCHit_v1::set_truth_pz (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 49 of file SQCalMCHit_v1.h.
Referenced by SQDigitizer::digitizeEMCal().
set_truth_x()
virtual void SQCalMCHit_v1::set_truth_x (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 34 of file SQCalMCHit_v1.h.
Referenced by SQDigitizer::digitizeEMCal().
set_truth_y()
virtual void SQCalMCHit_v1::set_truth_y (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 37 of file SQCalMCHit_v1.h.
Referenced by SQDigitizer::digitizeEMCal().
set_truth_z()
virtual void SQCalMCHit_v1::set_truth_z (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 40 of file SQCalMCHit_v1.h.
Referenced by SQDigitizer::digitizeEMCal().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQCalMCHit_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQCalMCHit_v1.cxx