Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Display/interface/PHEventDisplay.cxx File Reference
PHEventDisplay.cxx File Reference
event display interface, set parameters/switches, call detector modules, control display.
#include <boost/shared_ptr.hpp>
#include <boost/make_shared.hpp>
#include <boost/bind.hpp>
#include <fun4all/Fun4AllReturnCodes.h>
#include <fun4all/Fun4AllServer.h>
#include <phool/getClass.h>
#include <phool/phool.h>
#include <phool/PHIODataNode.h>
#include <phool/PHNodeIterator.h>
#include <phool/PHTimer.h>
#include <phool/PHCompositeNode.h>
#include <phool/PHTimeServer.h>
#include <phgeom/PHGeomUtility.h>
#include <phgeom/PHGeomTGeo.h>
#include <phfield/PHFieldUtility.h>
#include <phfield/PHField.h>
#include <interface_main/SQEvent.h>
#include "TEveManager.h"
#include "TApplication.h"
#include "TEveBrowser.h"
#include "TEveWindow.h"
#include "TGeoManager.h"
#include "TGeoVolume.h"
#include "TGLAutoRotator.h"
#include "TGLViewer.h"
#include "TEveViewer.h"
#include "TEveScene.h"
#include "TEveProjectionManager.h"
#include "TEveProjectionAxes.h"
#include "TEveGeoNode.h"
#include "TGLCameraOverlay.h"
#include "TGLAnnotation.h"
#include "TFile.h"
#include <pheve_display/PHEveDisplay.h>
#include <pheve_modules/mTrkEveDisplay.h>
#include <TThread.h>
#include <TStyle.h>
#include "PHEventDisplay.h"
Functions
void MakeViewerScene (TEveWindowSlot *slot, TEveViewer *&v, TEveScene *&s)
TEveElement * MakeProjection (TEveWindowSlot *slot, TEveElement *element, const double start_z, const double end_z=200, const char *name="Projection")
TEveElement * DrawHodo (TEveWindowSlot *slot, TEveElement *element, const double zoom=0.1, const double hrot=0, const double vrot=0, const char *name="Hodo")
Detailed Description
event display interface, set parameters/switches, call detector modules, control display.
Author
Sookhyun Lee
Version
Revision:
1.2
Date
$Date: 07/26/2016
Definition in file PHEventDisplay.cxx.
Function Documentation
TEveElement* DrawHodo (TEveWindowSlot * slot, TEveElement * element, const double zoom = 0.1, const double hrot = 0, const double vrot = 0, const char * name = "Hodo")
Definition at line 116 of file PHEventDisplay.cxx.
References MakeViewerScene(), and DPGEN::s.
TEveElement* MakeProjection (TEveWindowSlot * slot, TEveElement * element, const double start_z, const double end_z = 200, const char * name = "Projection")
Definition at line 77 of file PHEventDisplay.cxx.
References MakeViewerScene(), and DPGEN::s.
void MakeViewerScene (TEveWindowSlot * slot, TEveViewer *& v, TEveScene *& s)
Definition at line 66 of file PHEventDisplay.cxx.
Referenced by DrawHodo(), and MakeProjection().