E1039 Software: PdbCalChan Class Reference
PdbCalChan Class Reference abstract
#include </home/yuhw/GitHub/SeaQuest/e1039-core/database/pdbcal/base/PdbCalChan.h>
Public Member Functions
PdbCalChan ()
virtual ~PdbCalChan ()
virtual void print () const =0
ClassDef (PdbCalChan, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Detailed Description
Definition at line 18 of file PdbCalChan.h.
Constructor & Destructor Documentation
PdbCalChan()
PdbCalChan::PdbCalChan () inline
Definition at line 21 of file PdbCalChan.h.
~PdbCalChan()
virtual PdbCalChan::~PdbCalChan () inline virtual
Definition at line 22 of file PdbCalChan.h.
References ClassDef(), and print().
Member Function Documentation
ClassDef()
PdbCalChan::ClassDef (PdbCalChan , 1)
Referenced by ~PdbCalChan().
print()
virtual void PdbCalChan::print () const pure virtual
Implemented in PdbParameter, PdbParameterMap, PdbParameterError, and PdbParameterMapContainer.
Referenced by ~PdbCalChan().
The documentation for this class was generated from the following file:
/home/yuhw/GitHub/SeaQuest/e1039-core/database/pdbcal/base/PdbCalChan.h