Class Reference for E1039 Core & Analysis Software: GeomSvc Class Reference
GeomSvc Class Reference
User interface class about the geometry of detector planes.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/GeomSvc.h>
Public Member Functions
void init ()
Initialization, either from MySQL or from ascii file.
void initPlaneDirect ()
void initPlaneDbSvc ()
void initWireLUT ()
void loadCalibration (const std::string &calibrateFile)
void loadOnlineAlignment (const std::string &alignmentFile_mille)
Load parameters used in the online-alignment mode.
void loadAlignment (const std::string &alignmentFile_chamber, const std::string &alignmentFile_hodo, const std::string &alignmentFile_prop)
void loadMilleAlignment (const std::string &alignmentFile_mille)
void close ()
Close the geometry service before exit or starting a new one.
void toLocalDetectorName (std::string &detectorName, int &eID)
Convert the official detectorName to local detectorName.
void setDetectorX0 (const std::string detectorName, const double val)
TODO temp solution to overwrite the y0 of a plane.
void setDetectorY0 (const std::string detectorName, const double val)
void setDetectorZ0 (const std::string detectorName, const double val)
double getDetectorX0 (const std::string detectorName) const
double getDetectorY0 (const std::string detectorName) const
double getDetectorZ0 (const std::string detectorName) const
int getDetectorID (const std::string &detectorName) const
Get the plane position.
std::string getDetectorName (const int &detectorID) const
std::vector< int > getDetectorIDs (std::string pattern)
bool findPatternInDetector (int detectorID, std::string pattern)
const Plane & getPlane (int detectorID) const
Plane getPlane (int detectorID)
Plane * getPlanePtr (int detectorID)
double getPlanePosition (int detectorID) const
double getPlaneSpacing (int detectorID) const
double getPlaneOverlap (int detectorID) const
double getCellWidth (int detectorID) const
double getCostheta (int detectorID) const
double getSintheta (int detectorID) const
double getTantheta (int detectorID) const
double getPlaneScaleX (int detectorID) const
double getPlaneScaleY (int detectorID) const
double getPlaneScaleZ (int detectorID) const
double getPlaneResolution (int detectorID) const
double getPlaneCenterX (int detectorID) const
double getPlaneCenterY (int detectorID) const
double getPlaneCenterZ (int detectorID) const
double getRotationInX (int detectorID) const
double getRotationInY (int detectorID) const
double getRotationInZ (int detectorID) const
double getStereoAngle (int detectorID) const
double getPlaneZOffset (int detectorID) const
double getPlanePhiOffset (int detectorID) const
double getPlaneWOffset (int detectorID) const
double getPlaneWOffset (int detectorID, int moduleID) const
int getPlaneNElements (int detectorID) const
int getPlaneType (int detectorID) const
bool isChamber (const int detectorID) const
Return "true" for chamber planes.
bool isChamber (const std::string detectorName) const
Return "true" for chamber planes.
bool isHodo (const int detectorID) const
Return "true" for hodo planes.
bool isHodo (const std::string detectorName) const
Return "true" for hodo planes.
bool isPropTube (const int detectorID) const
Return "true" for prop tube planes.
bool isPropTube (const std::string detectorName) const
Return "true" for prop tube planes.
bool isDPHodo (const int detectorID) const
Return "true" for DP hodo planes.
bool isDPHodo (const std::string detectorName) const
Return "true" for DP hodo planes.
bool isInh (const int detectorID) const
Return "true" for BeforeInh and AfterInh signals.
bool isInh (const std::string detectorName) const
int getHodoStation (const int detectorID) const
Return a station number (1-4) for hodo planes or "0" for others.
int getHodoStation (const std::string detectorName) const
Return a station number (1-4) for hodo planes or "0" for others.
int getTriggerLv (int detectorID)
double getInterception (int detectorID, double tx, double ty, double x0, double y0) const
Get the interception of a line an a plane.
double getInterceptionFast (int detectorID, double tx, double ty, double x0, double y0) const
double getInterceptionFast (int detectorID, double x_exp, double y_exp) const
double getDCA (int detectorID, int elementID, double tx, double ty, double x0, double y0)
void getMeasurement (int detectorID, int elementID, double &measurement, double &dmeasurement)
Convert the detectorID and elementID to the actual hit position.
double getMeasurement (int detectorID, int elementID)
void getEndPoints (int detectorID, int elementID, TVectorD &ep1, TVectorD &ep2)
void getEndPoints (int detectorID, int elementID, TVector3 &ep1, TVector3 &ep2)
void get2DBoxSize (int detectorID, int elementID, double &x_min, double &x_max, double &y_min, double &y_max)
void getWireEndPoints (int detectorID, int elementID, double &x_min, double &x_max, double &y_min, double &y_max)
int getExpElementID (int detectorID, double pos_exp)
bool isCalibrationLoaded ()
Calibration related.
double getDriftDistance (int detectorID, double tdcTime)
bool isInTime (int detectorID, double tdcTime)
TSpline3 * getRTCurve (int detectorID)
double getYinStereoPlane (int detectorID, double x, double u)
Convert the stereo hits to Y value.
double getUinStereoPlane (int detectorID, double x, double y)
double getXinStereoPlane (int detectorID, double u, double y)
bool isInPlane (int detectorID, double x, double y)
See if a point is in a plane.
bool isInElement (int detectorID, int elementID, double x, double y, double tolr=0.)
bool isInKMAG (double x, double y)
double Z_KMAG_BEND () const
Getter/setters for a set of fixed parameters - should not be changed unless absolutely necessary.
void Z_KMAG_BEND (const double v)
double Z_FMAG_BEND () const
void Z_FMAG_BEND (const double v)
double Z_KFMAG_BEND () const
void Z_KFMAG_BEND (const double v)
double ELOSS_KFMAG () const
void ELOSS_KFMAG (const double v)
double ELOSS_ABSORBER () const
void ELOSS_ABSORBER (const double v)
double Z_ST2 () const
void Z_ST2 (const double v)
double Z_ABSORBER () const
void Z_ABSORBER (const double v)
double Z_REF () const
void Z_REF (const double v)
double Z_TARGET () const
void Z_TARGET (const double v)
double Z_DUMP () const
void Z_DUMP (const double v)
double Z_ST1 () const
void Z_ST1 (const double v)
double Z_ST3 () const
void Z_ST3 (const double v)
double FMAG_HOLE_LENGTH () const
void FMAG_HOLE_LENGTH (const double v)
double FMAG_HOLE_RADIUS () const
void FMAG_HOLE_RADIUS (const double v)
double FMAG_LENGTH () const
void FMAG_LENGTH (const double v)
double Z_UPSTREAM () const
void Z_UPSTREAM (const double v)
double Z_DOWNSTREAM () const
void Z_DOWNSTREAM (const double v)
void printAlignPar ()
Debugging print of the content.
void printTable ()
void printWirePosition ()
Static Public Member Functions
static GeomSvc * instance ()
singlton instance
static void UseDbSvc (const bool val)
static bool UseDbSvc ()
Detailed Description
User interface class about the geometry of detector planes.
When you need the geometry information, such as the name and the z position of detector ID = 1, you first get the instance of this class and then call corresponding member functions;
int det_id = 1;
GeomSvc* geom = GeomSvc::instance();
string det_name = geom->getDetectorName(det_id);
double det_zc   = getPlaneCenterZ(det_id);
Usually a version of the geometry information is selected based on run ID. Thus you need set the RUNNUMBER flag before instantiating this object, namely
recoConsts* rc = recoConsts::instance();
rc->set_IntFlag("RUNNUMBER", 1234);
GeomSvc* geom = GeomSvc::instance();
Or you might manually select a version via the GeomPlane flag;
recoConsts* rc = recoConsts::instance();
rc->set_CharFlag("GeomPlane", "2022111601");
GeomSvc* geom = GeomSvc::instance();
Definition at line 155 of file GeomSvc.h.
Member Function Documentation
close()
void GeomSvc::close (void)
Close the geometry service before exit or starting a new one.
Definition at line 223 of file GeomSvc.cxx.
References nChamberPlanes, nDarkPhotonPlanes, nHodoPlanes, nPropPlanes, NULL, and Plane::rtprofile.
ELOSS_ABSORBER() [1/2]
double GeomSvc::ELOSS_ABSORBER () const inline
Definition at line 311 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Referenced by ClassImp().
ELOSS_ABSORBER() [2/2]
void GeomSvc::ELOSS_ABSORBER (const double v) inline
Definition at line 312 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
ELOSS_KFMAG() [1/2]
double GeomSvc::ELOSS_KFMAG () const inline
Definition at line 309 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Referenced by ClassImp().
ELOSS_KFMAG() [2/2]
void GeomSvc::ELOSS_KFMAG (const double v) inline
Definition at line 310 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
findPatternInDetector()
bool GeomSvc::findPatternInDetector (int detectorID, std::string pattern)
Definition at line 606 of file GeomSvc.cxx.
FMAG_HOLE_LENGTH() [1/2]
double GeomSvc::FMAG_HOLE_LENGTH () const inline
Definition at line 327 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
FMAG_HOLE_LENGTH() [2/2]
void GeomSvc::FMAG_HOLE_LENGTH (const double v) inline
Definition at line 328 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
FMAG_HOLE_RADIUS() [1/2]
double GeomSvc::FMAG_HOLE_RADIUS () const inline
Definition at line 329 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
FMAG_HOLE_RADIUS() [2/2]
void GeomSvc::FMAG_HOLE_RADIUS (const double v) inline
Definition at line 330 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
FMAG_LENGTH() [1/2]
double GeomSvc::FMAG_LENGTH () const inline
Definition at line 331 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
FMAG_LENGTH() [2/2]
void GeomSvc::FMAG_LENGTH (const double v) inline
Definition at line 332 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
get2DBoxSize()
void GeomSvc::get2DBoxSize (int detectorID, int elementID, double & x_min, double & x_max, double & y_min, double & y_max)
Definition at line 692 of file GeomSvc.cxx.
References Plane::cellWidth, getDetectorName(), Plane::x1, Plane::x2, Plane::y1, and Plane::y2.
Referenced by EventReducer::initHodoMaskLUT(), isInElement(), and KalmanFastTracking::KalmanFastTracking().
getCellWidth()
double GeomSvc::getCellWidth (int detectorID) const inline
Definition at line 230 of file GeomSvc.h.
References Plane::cellWidth.
Referenced by SQDigitizer::digitizePlane(), SQGenFit::GFMeasurement::GFMeasurement(), CalibParam::Init(), AnaChamPlane::InitRun(), and AnaTrack::InitRun().
getCostheta()
double GeomSvc::getCostheta (int detectorID) const inline
Definition at line 231 of file GeomSvc.h.
References Plane::costheta.
Referenced by KalmanTrack::getAlignment(), KalmanTrack::getSagittaInSuperDetector(), mTrkEveDisplay::hit_to_wire(), KalmanFastTracking::KalmanFastTracking(), and Node::Node().
getDCA()
double GeomSvc::getDCA (int detectorID, int elementID, double tx, double ty, double x0, double y0)
Definition at line 857 of file GeomSvc.cxx.
References getEndPoints().
Referenced by SQDigitizer::digitizePlane().
getDetectorID()
int GeomSvc::getDetectorID (const std::string & detectorName) const inline
Get the plane position.
Definition at line 211 of file GeomSvc.h.
Referenced by ChanMapV1495::Add(), ChanMapTaiwan::Add(), CalibParamXT::Add(), CalibParamInTimeTaiwan::Add(), CalibParamInTimeV1495::Add(), mTrkEveDisplay::draw_tracks(), UtilSQHit::FindFirstHits(), UtilSQHit::FindHits(), UtilSQHit::FindHitsFast(), UtilSQHit::FindTriggerHitsFast(), getDetectorX0(), getDetectorY0(), getDetectorZ0(), EventReducer::initHodoMaskLUT(), AnaHodoHit::InitRun(), AnaTriggerHit::InitRun(), AnaTrigSignal::InitRun(), AnaChamPlane::InitRun(), OnlMonH4::InitRunOnlMon(), KalmanFastTracking::KalmanFastTracking(), AnaHodoHit::process_event(), AnaEmbeddedData::process_event(), DPTriggerAnalyzer::process_event(), RndmEmbed::process_event(), CalibParam::ReadRTParam(), AnaModule::registerDetector(), setDetectorX0(), setDetectorY0(), and setDetectorZ0().
getDetectorIDs()
std::vector< int > GeomSvc::getDetectorIDs (std::string pattern)
Definition at line 586 of file GeomSvc.cxx.
Referenced by KScheduler::Init(), OnlMonCham::InitRunOnlMon(), OnlMonProp::InitRunOnlMon(), KalmanFastTracking::KalmanFastTracking(), and TriggerAnalyzer::TriggerAnalyzer().
getDetectorName()
std::string GeomSvc::getDetectorName (const int & detectorID) const inline
Definition at line 215 of file GeomSvc.h.
Referenced by AnaChamHit::AnalyzeTree(), TriggerAnalyzer::buildData(), MakeRTCurve::DrawCalibResult(), SRMakeRTCurve::DrawCalibResult(), CalibData::DrawHistHit(), UtilTrigger::ExtractRoadID(), UtilTrack::FindDetectorHitsOfTrack(), SQChamberRealization::FixChamReso(), get2DBoxSize(), getHodoStation(), CalibData::Init(), AnaEffCham::Init(), ExtractTdcDist::Init(), SQDigitizer::Init(), AnaTrack::InitRun(), OnlMonCham::InitRunOnlMon(), OnlMonProp::InitRunOnlMon(), isChamber(), isDPHodo(), isHodo(), isInh(), isPropTube(), loadCalibration(), TriggerRoad::makeRoadList(), SQChamberRealization::process_event(), SQChamberRealization::ScaleChamReso(), SQChamberRealization::SetChamEff(), SQChamberRealization::SetPropTubeEff(), CalibParam::WriteRTGraph(), and CalibParam::WriteRTParam().
getDetectorX0()
double GeomSvc::getDetectorX0 (const std::string detectorName) const inline
Definition at line 197 of file GeomSvc.h.
References getDetectorID(), and Plane::x0.
getDetectorY0()
double GeomSvc::getDetectorY0 (const std::string detectorName) const inline
Definition at line 201 of file GeomSvc.h.
References getDetectorID(), and Plane::y0.
getDetectorZ0()
double GeomSvc::getDetectorZ0 (const std::string detectorName) const inline
Definition at line 205 of file GeomSvc.h.
References getDetectorID(), and Plane::z0.
getDriftDistance()
double GeomSvc::getDriftDistance (int detectorID, double tdcTime)
Definition at line 826 of file GeomSvc.cxx.
References Plane::cellWidth, NULL, and Plane::rtprofile.
Referenced by KalmanTrack::KalmanTrack().
getEndPoints() [1/2]
void GeomSvc::getEndPoints (int detectorID, int elementID, TVector3 & ep1, TVector3 & ep2)
Definition at line 660 of file GeomSvc.cxx.
getEndPoints() [2/2]
void GeomSvc::getEndPoints (int detectorID, int elementID, TVectorD & ep1, TVectorD & ep2)
Definition at line 654 of file GeomSvc.cxx.
Referenced by getDCA(), and SQGenFit::GFMeasurement::GFMeasurement().
getExpElementID()
int GeomSvc::getExpElementID (int detectorID, double pos_exp)
Definition at line 669 of file GeomSvc.cxx.
References Plane::cellWidth, Plane::elementPos, nChamberPlanes, Plane::nElements, nHodoPlanes, nPropPlanes, and Plane::spacing.
Referenced by SQDigitizer::digitizePlane(), EventReducer::initHodoMaskLUT(), main(), AnaModule::process_event(), SimpleTree::process_event(), and TriggerRoad::TriggerRoad().
getHodoStation() [1/2]
int GeomSvc::getHodoStation (const int detectorID) const
Return a station number (1-4) for hodo planes or "0" for others.
Definition at line 814 of file GeomSvc.cxx.
References getDetectorName().
Referenced by DPTriggerAnalyzer::process_event().
getHodoStation() [2/2]
int GeomSvc::getHodoStation (const std::string detectorName) const
Return a station number (1-4) for hodo planes or "0" for others.
Definition at line 819 of file GeomSvc.cxx.
getInterception()
double GeomSvc::getInterception (int detectorID, double tx, double ty, double x0, double y0) const inline
Get the interception of a line an a plane.
Definition at line 272 of file GeomSvc.h.
References Plane::intercept().
Referenced by SQDigitizer::digitizePlane().
getInterceptionFast() [1/2]
double GeomSvc::getInterceptionFast (int detectorID, double tx, double ty, double x0, double y0) const
Definition at line 852 of file GeomSvc.cxx.
References Plane::costheta, and Plane::zc.
Referenced by SQGenFit::GFMeasurement::print().
getInterceptionFast() [2/2]
double GeomSvc::getInterceptionFast (int detectorID, double x_exp, double y_exp) const inline
Definition at line 274 of file GeomSvc.h.
References Plane::getW().
getMeasurement() [1/2]
double GeomSvc::getMeasurement (int detectorID, int elementID)
Definition at line 649 of file GeomSvc.cxx.
getMeasurement() [2/2]
void GeomSvc::getMeasurement (int detectorID, int elementID, double & measurement, double & dmeasurement)
Convert the detectorID and elementID to the actual hit position.
Definition at line 643 of file GeomSvc.cxx.
References Plane::resolution.
Referenced by SQDigitizer::digitizePlane(), GetRoad::get_mc_roads(), GetRoad::get_old_roads(), mTrkEveDisplay::hit_to_wire(), KalmanTrack::KalmanTrack(), main(), CalibHitPos::process_event(), CalibDriftDistMod::process_event(), CalibDriftDist::process_event(), CalibHitElementPos::process_event(), RndmEmbed::process_event(), SRawEventEmbed::process_event(), and TriggerAnalyzer::trimEvent().
getPlane() [1/2]
Plane GeomSvc::getPlane (int detectorID) inline
Definition at line 224 of file GeomSvc.h.
getPlane() [2/2]
const Plane& GeomSvc::getPlane (int detectorID) const inline
Definition at line 223 of file GeomSvc.h.
Referenced by mTrkEveDisplay::hit_to_wire(), and RndmEmbed::process_event().
getPlaneCenterX()
double GeomSvc::getPlaneCenterX (int detectorID) const inline
Definition at line 239 of file GeomSvc.h.
References Plane::xc.
Referenced by UtilHodo::GetPlanePos(), KalmanFastTracking::printAtDetectorBack(), and KalmanDSTrk::printAtDetectorBack().
getPlaneCenterY()
double GeomSvc::getPlaneCenterY (int detectorID) const inline
Definition at line 240 of file GeomSvc.h.
References Plane::yc.
Referenced by UtilHodo::GetPlanePos(), KalmanFastTracking::printAtDetectorBack(), and KalmanDSTrk::printAtDetectorBack().
getPlaneCenterZ()
double GeomSvc::getPlaneCenterZ (int detectorID) const inline
Definition at line 241 of file GeomSvc.h.
References Plane::zc.
Referenced by mTrkEveDisplay::clear(), mTrkEveDisplay::draw_tracks(), UtilHodo::GetPlanePos(), KalmanFitter::KalmanFitter(), and mTrkEveDisplay::mTrkEveDisplay().
getPlaneNElements()
int GeomSvc::getPlaneNElements (int detectorID) const inline
Definition at line 252 of file GeomSvc.h.
References Plane::nElements.
Referenced by AnaChamHit::AnalyzeTree(), SQDigitizer::digitizePlane(), UtilHodo::GetElementPos(), TriggerRoad::getLR(), AnaEffCham::Init(), ExtractTdcDist::Init(), EventReducer::initHodoMaskLUT(), AnaHodoHit::InitRun(), AnaTriggerHit::InitRun(), AnaChamPlane::InitRun(), AnaTrack::InitRun(), OnlMonCham::InitRunOnlMon(), OnlMonH4::InitRunOnlMon(), OnlMonHodo::InitRunOnlMon(), OnlMonProp::InitRunOnlMon(), OnlMonTrigEP::InitRunOnlMon(), OnlMonTrigV1495::InitRunOnlMon(), OnlMonV1495::InitRunOnlMon(), KalmanFastTracking::KalmanFastTracking(), AnaModule::process_event(), SimpleTree::process_event(), and TriggerRoad::reflectLR().
getPlaneOverlap()
double GeomSvc::getPlaneOverlap (int detectorID) const inline
Definition at line 229 of file GeomSvc.h.
References Plane::overlap.
Referenced by SQDigitizer::digitizePlane().
getPlanePhiOffset()
double GeomSvc::getPlanePhiOffset (int detectorID) const inline
Definition at line 248 of file GeomSvc.h.
References Plane::rotZ.
getPlanePosition()
double GeomSvc::getPlanePosition (int detectorID) const inline
Definition at line 227 of file GeomSvc.h.
References Plane::zc.
Referenced by SQDigitizer::digitizePlane(), GetRoad::get_mc_roads(), GetRoad::get_old_roads(), KalmanTrack::getSagittaInSuperDetector(), SQGenFit::GFMeasurement::GFMeasurement(), EventReducer::initHodoMaskLUT(), KalmanFastTracking::KalmanFastTracking(), Node::Node(), KalmanFastTracking::printAtDetectorBack(), KalmanDSTrk::printAtDetectorBack(), AnaModule::process_event(), SimpleTree::process_event(), KalmanDSTrk::processOneTracklet(), EventReducer::sagittaReducer(), KalmanTrack::setTracklet(), and TriggerRoad::TriggerRoad().
getPlanePtr()
Plane* GeomSvc::getPlanePtr (int detectorID) inline
Definition at line 225 of file GeomSvc.h.
Referenced by CalibDriftDistMod::InitRun(), and CalibDriftDist::InitRun().
getPlaneResolution()
double GeomSvc::getPlaneResolution (int detectorID) const inline
Definition at line 237 of file GeomSvc.h.
References Plane::resolution.
Referenced by SQGenFit::GFMeasurement::GFMeasurement(), KalmanFastTracking::KalmanFastTracking(), main(), Node::Node(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
getPlaneScaleX()
double GeomSvc::getPlaneScaleX (int detectorID) const inline
Definition at line 234 of file GeomSvc.h.
References Plane::x1, and Plane::x2.
Referenced by CalibData::Init(), AnaChamPlane::InitRun(), AnaTrack::InitRun(), KalmanFastTracking::printAtDetectorBack(), and KalmanDSTrk::printAtDetectorBack().
getPlaneScaleY()
double GeomSvc::getPlaneScaleY (int detectorID) const inline
Definition at line 235 of file GeomSvc.h.
References Plane::y1, and Plane::y2.
Referenced by KalmanFastTracking::KalmanFastTracking(), KalmanFastTracking::printAtDetectorBack(), and KalmanDSTrk::printAtDetectorBack().
getPlaneScaleZ()
double GeomSvc::getPlaneScaleZ (int detectorID) const inline
Definition at line 236 of file GeomSvc.h.
References Plane::z1, and Plane::z2.
getPlaneSpacing()
double GeomSvc::getPlaneSpacing (int detectorID) const inline
Definition at line 228 of file GeomSvc.h.
References Plane::spacing.
Referenced by AnaChamHit::AnalyzeTree(), UtilHodo::GetElementPos(), KalmanTrack::getExpPosError(), and KalmanFastTracking::KalmanFastTracking().
getPlaneType()
int GeomSvc::getPlaneType (int detectorID) const inline
Definition at line 253 of file GeomSvc.h.
References Plane::planeType.
Referenced by KalmanFastTracking::buildBackPartialTracks(), KalmanDSTrk::buildBackPartialTracks(), KalmanFastTracking::getExtrapoWindowsInSt1(), KalmanDSTrk::getExtrapoWindowsInSt1(), KalmanFastTracking::getSagittaWindowsInSt1(), KalmanDSTrk::getSagittaWindowsInSt1(), EventReducer::initHodoMaskLUT(), EventReducer::reduceEvent(), KalmanFastTracking::removeBadHits(), KalmanDSTrk::removeBadHits(), and EventReducer::sagittaReducer().
getPlaneWOffset() [1/2]
double GeomSvc::getPlaneWOffset (int detectorID) const inline
Definition at line 249 of file GeomSvc.h.
References Plane::deltaW.
getPlaneWOffset() [2/2]
double GeomSvc::getPlaneWOffset (int detectorID, int moduleID) const inline
Definition at line 250 of file GeomSvc.h.
References Plane::deltaW_module.
getPlaneZOffset()
double GeomSvc::getPlaneZOffset (int detectorID) const inline
Definition at line 247 of file GeomSvc.h.
References Plane::deltaZ.
getRotationInX()
double GeomSvc::getRotationInX (int detectorID) const inline
Definition at line 242 of file GeomSvc.h.
References Plane::rX.
Referenced by KalmanFitter::KalmanFitter().
getRotationInY()
double GeomSvc::getRotationInY (int detectorID) const inline
Definition at line 243 of file GeomSvc.h.
References Plane::rY.
Referenced by KalmanFitter::KalmanFitter().
getRotationInZ()
double GeomSvc::getRotationInZ (int detectorID) const inline
Definition at line 244 of file GeomSvc.h.
References Plane::rZ.
Referenced by KalmanFitter::KalmanFitter().
getRTCurve()
TSpline3* GeomSvc::getRTCurve (int detectorID) inline
Definition at line 290 of file GeomSvc.h.
References Plane::rtprofile.
getSintheta()
double GeomSvc::getSintheta (int detectorID) const inline
Definition at line 232 of file GeomSvc.h.
References Plane::sintheta.
Referenced by KalmanTrack::getAlignment(), KalmanTrack::getSagittaInSuperDetector(), mTrkEveDisplay::hit_to_wire(), KalmanFastTracking::KalmanFastTracking(), and Node::Node().
getStereoAngle()
double GeomSvc::getStereoAngle (int detectorID) const inline
Definition at line 245 of file GeomSvc.h.
References Plane::angleFromVert, and Plane::rZ.
getTantheta()
double GeomSvc::getTantheta (int detectorID) const inline
Definition at line 233 of file GeomSvc.h.
References Plane::tantheta.
getTriggerLv()
int GeomSvc::getTriggerLv (int detectorID) inline
Definition at line 269 of file GeomSvc.h.
Referenced by SQDigitizer::getTriggerLv().
getUinStereoPlane()
double GeomSvc::getUinStereoPlane (int detectorID, double x, double y) inline
Definition at line 294 of file GeomSvc.h.
References Plane::getW().
Referenced by KalmanFastTracking::getExtrapoWindowsInSt1(), KalmanDSTrk::getExtrapoWindowsInSt1(), KalmanFastTracking::getSagittaWindowsInSt1(), KalmanDSTrk::getSagittaWindowsInSt1(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
getWireEndPoints()
void GeomSvc::getWireEndPoints (int detectorID, int elementID, double & x_min, double & x_max, double & y_min, double & y_max)
Definition at line 717 of file GeomSvc.cxx.
References Plane::nElements, Plane::spacing, Plane::xc, Plane::xoffset, Plane::y1, and Plane::y2.
Referenced by EventReducer::initHodoMaskLUT().
getXinStereoPlane()
double GeomSvc::getXinStereoPlane (int detectorID, double u, double y) inline
Definition at line 295 of file GeomSvc.h.
References Plane::getX().
getYinStereoPlane()
double GeomSvc::getYinStereoPlane (int detectorID, double x, double u) inline
Convert the stereo hits to Y value.
Definition at line 293 of file GeomSvc.h.
References Plane::getY().
init()
void GeomSvc::init ()
Initialization, either from MySQL or from ascii file.
Initialize channel mapping — not needed at the moment
Definition at line 240 of file GeomSvc.cxx.
References initPlaneDbSvc(), initPlaneDirect(), initWireLUT(), recoConsts::instance(), loadAlignment(), loadCalibration(), loadMilleAlignment(), loadOnlineAlignment(), nChamberPlanes, nDarkPhotonPlanes, nHodoPlanes, and nPropPlanes.
Referenced by instance().
initPlaneDbSvc()
void GeomSvc::initPlaneDbSvc ()
Definition at line 419 of file GeomSvc.cxx.
References GeomParamPlane::Plane::angle_from_vert, GeomParamPlane::Plane::cell_spacing, GeomParamPlane::Plane::cell_width, GeomParamPlane::Plane::det_name, PHFlag::FlagExist(), PHFlag::get_CharFlag(), PHFlag::get_IntFlag(), RunParamBase::GetMapID(), GeomParamPlane::GetNumPlanes(), GeomParamPlane::GetPlane(), GeomParamPlane::Plane::height, recoConsts::instance(), GeomParamPlane::Plane::n_ele, nChamberPlanes, nDarkPhotonPlanes, nHodoPlanes, nPropPlanes, RunParamBase::ReadFromDB(), recoConsts::set_CharFlag(), RunParamBase::SetMapID(), RunParamBase::SetMapIDbyDB(), GeomParamPlane::Plane::theta_x, GeomParamPlane::Plane::theta_y, GeomParamPlane::Plane::theta_z, toLocalDetectorName(), GeomParamPlane::Plane::width, GeomParamPlane::Plane::x0, GeomParamPlane::Plane::xoffset, GeomParamPlane::Plane::y0, and GeomParamPlane::Plane::z0.
Referenced by init().
initPlaneDirect()
void GeomSvc::initPlaneDirect ()
Definition at line 411 of file GeomSvc.cxx.
Referenced by init().
initWireLUT()
void GeomSvc::initWireLUT ()
Initialize the position look up table for all wires, hodos, and tubes
Definition at line 537 of file GeomSvc.cxx.
References Plane::costheta, Plane::deltaW, Plane::deltaW_module, Plane::elementPos, nChamberPlanes, nDarkPhotonPlanes, Plane::nElements, nHodoPlanes, nPropPlanes, Plane::sintheta, Plane::spacing, Plane::x0, Plane::xoffset, and Plane::y0.
Referenced by init(), setDetectorX0(), setDetectorY0(), and setDetectorZ0().
instance()
GeomSvc * GeomSvc::instance () static
singlton instance
Definition at line 212 of file GeomSvc.cxx.
References init(), and NULL.
Referenced by ChanMapV1495::Add(), ChanMapTaiwan::Add(), CalibParamXT::Add(), CalibParamInTimeTaiwan::Add(), CalibParamInTimeV1495::Add(), AnaChamHit::AnalyzeTree(), TriggerAnalyzer::buildData(), ClassImp(), mTrkEveDisplay::draw_tracks(), MakeRTCurve::DrawCalibResult(), SRMakeRTCurve::DrawCalibResult(), CalibData::DrawHistHit(), EventReducer::EventReducer(), UtilTrigger::ExtractRoadID(), UtilTrack::FindDetectorHitsOfTrack(), UtilSQHit::FindFirstHits(), UtilSQHit::FindHits(), UtilSQHit::FindHitsFast(), UtilSQHit::FindTriggerHitsFast(), SQChamberRealization::FixChamReso(), KalmanTrack::getAlignment(), UtilHodo::GetElementPos(), KalmanTrack::getExpPosError(), TriggerRoad::getLR(), UtilHodo::GetPlanePos(), KalmanTrack::getSagittaInSuperDetector(), SQGenFit::GFMeasurement::GFMeasurement(), KScheduler::Init(), CalibData::Init(), CalibParam::Init(), AnaEffCham::Init(), ExtractTdcDist::Init(), SQDigitizer::Init(), AnaHodoHit::InitRun(), AnaTriggerHit::InitRun(), AnaTrigSignal::InitRun(), AnaTrkQA::InitRun(), AnaChamPlane::InitRun(), AnaTrack::InitRun(), AnaPileup::InitRun(), CalibDriftDistMod::InitRun(), CalibDriftDist::InitRun(), RndmEmbed::InitRun(), SRawEventEmbed::InitRun(), PatternDBGen::InitRun(), OnlMonCham::InitRunOnlMon(), OnlMonH4::InitRunOnlMon(), OnlMonHodo::InitRunOnlMon(), OnlMonMainDaq::InitRunOnlMon(), OnlMonProp::InitRunOnlMon(), OnlMonTrigEP::InitRunOnlMon(), OnlMonTrigV1495::InitRunOnlMon(), OnlMonV1495::InitRunOnlMon(), UtilHodo::IsHodoX(), KalmanDSTrk::KalmanDSTrk(), KalmanFastTracking::KalmanFastTracking(), KalmanFitter::KalmanFitter(), KalmanTrack::KalmanTrack(), main(), TriggerRoad::makeRoadList(), mTrkEveDisplay::mTrkEveDisplay(), Node::Node(), SQGenFit::GFMeasurement::print(), CalibHitPos::process_event(), AnaChamHit::process_event(), AnaHodoHit::process_event(), AnaEmbeddedData::process_event(), CalibDriftDistMod::process_event(), CalibDriftDist::process_event(), CalibHitElementPos::process_event(), CalibHodoInTime::process_event(), DPTriggerAnalyzer::process_event(), SQChamberRealization::process_event(), SQGeomAcc::process_event(), CalibParam::ReadRTParam(), TriggerRoad::reflectLR(), SQChamberRealization::ScaleChamReso(), SQChamberRealization::SetChamEff(), SQChamberRealization::SetPropTubeEff(), KalmanTrack::setTracklet(), TriggerAnalyzer::TriggerAnalyzer(), TriggerRoad::TriggerRoad(), CalibParam::WriteRTGraph(), and CalibParam::WriteRTParam().
isCalibrationLoaded()
bool GeomSvc::isCalibrationLoaded () inline
Calibration related.
Definition at line 287 of file GeomSvc.h.
isChamber() [1/2]
bool GeomSvc::isChamber (const int detectorID) const
Return "true" for chamber planes.
Definition at line 764 of file GeomSvc.cxx.
References getDetectorName().
Referenced by CalibHitPos::process_event(), AnaChamHit::process_event(), CalibDriftDistMod::process_event(), and CalibDriftDist::process_event().
isChamber() [2/2]
bool GeomSvc::isChamber (const std::string detectorName) const
Return "true" for chamber planes.
Definition at line 769 of file GeomSvc.cxx.
isDPHodo() [1/2]
bool GeomSvc::isDPHodo (const int detectorID) const
Return "true" for DP hodo planes.
Definition at line 794 of file GeomSvc.cxx.
References getDetectorName().
Referenced by CalibHodoInTime::process_event().
isDPHodo() [2/2]
bool GeomSvc::isDPHodo (const std::string detectorName) const
Return "true" for DP hodo planes.
Definition at line 799 of file GeomSvc.cxx.
isHodo() [1/2]
bool GeomSvc::isHodo (const int detectorID) const
Return "true" for hodo planes.
Definition at line 774 of file GeomSvc.cxx.
References getDetectorName().
Referenced by CalibHodoInTime::process_event().
isHodo() [2/2]
bool GeomSvc::isHodo (const std::string detectorName) const
Return "true" for hodo planes.
Definition at line 779 of file GeomSvc.cxx.
isInElement()
bool GeomSvc::isInElement (int detectorID, int elementID, double x, double y, double tolr = 0.)
Definition at line 622 of file GeomSvc.cxx.
References get2DBoxSize().
isInh() [1/2]
bool GeomSvc::isInh (const int detectorID) const
Return "true" for BeforeInh and AfterInh signals.
Definition at line 804 of file GeomSvc.cxx.
References getDetectorName().
Referenced by CalibHodoInTime::process_event().
isInh() [2/2]
bool GeomSvc::isInh (const std::string detectorName) const
Definition at line 809 of file GeomSvc.cxx.
isInKMAG()
bool GeomSvc::isInKMAG (double x, double y)
Definition at line 635 of file GeomSvc.cxx.
Referenced by KalmanFastTracking::acceptTracklet(), and KalmanDSTrk::acceptTracklet().
isInPlane()
bool GeomSvc::isInPlane (int detectorID, double x, double y)
See if a point is in a plane.
Definition at line 614 of file GeomSvc.cxx.
Referenced by SQDigitizer::digitizePlane(), KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), AnaModule::process_event(), SimpleTree::process_event(), and TriggerRoad::TriggerRoad().
isInTime()
bool GeomSvc::isInTime (int detectorID, double tdcTime)
Definition at line 1091 of file GeomSvc.cxx.
References Plane::tmax, and Plane::tmin.
isPropTube() [1/2]
bool GeomSvc::isPropTube (const int detectorID) const
Return "true" for prop tube planes.
Definition at line 784 of file GeomSvc.cxx.
References getDetectorName().
Referenced by CalibHitPos::process_event(), CalibDriftDistMod::process_event(), and CalibDriftDist::process_event().
isPropTube() [2/2]
bool GeomSvc::isPropTube (const std::string detectorName) const
Return "true" for prop tube planes.
Definition at line 789 of file GeomSvc.cxx.
loadAlignment()
void GeomSvc::loadAlignment (const std::string & alignmentFile_chamber, const std::string & alignmentFile_hodo, const std::string & alignmentFile_prop)
Definition at line 916 of file GeomSvc.cxx.
References nChamberPlanes, nHodoPlanes, and nPropPlanes.
Referenced by init().
loadCalibration()
void GeomSvc::loadCalibration (const std::string & calibrateFile)
Definition at line 1053 of file GeomSvc.cxx.
References getDetectorName(), and NULL.
Referenced by init().
loadMilleAlignment()
void GeomSvc::loadMilleAlignment (const std::string & alignmentFile_mille)
Definition at line 1014 of file GeomSvc.cxx.
References nChamberPlanes.
Referenced by init(), and loadOnlineAlignment().
loadOnlineAlignment()
void GeomSvc::loadOnlineAlignment (const std::string & alignmentFile_mille)
Load parameters used in the online-alignment mode.
The major part of this function is not implemented yet because we are not sure if we store the alignment parameters in DB table. We might use the text file ("align_mille.txt") during the online-alignment mode.
Definition at line 877 of file GeomSvc.cxx.
References loadMilleAlignment().
Referenced by init().
printAlignPar()
void GeomSvc::printAlignPar ()
Debugging print of the content.
Definition at line 1116 of file GeomSvc.cxx.
References Plane::deltaW, Plane::deltaZ, nChamberPlanes, nHodoPlanes, nPropPlanes, and Plane::rotZ.
Referenced by KalmanFastTracking::KalmanFastTracking().
printTable()
void GeomSvc::printTable ()
Definition at line 1126 of file GeomSvc.cxx.
References nChamberPlanes, nHodoPlanes, and nPropPlanes.
Referenced by KalmanFastTracking::KalmanFastTracking(), and main().
printWirePosition()
void GeomSvc::printWirePosition ()
Definition at line 1096 of file GeomSvc.cxx.
References Plane::cellWidth, nChamberPlanes, Plane::nElements, nHodoPlanes, and nPropPlanes.
Referenced by KalmanFastTracking::KalmanFastTracking().
setDetectorX0()
void GeomSvc::setDetectorX0 (const std::string detectorName, const double val) inline
TODO temp solution to overwrite the y0 of a plane.
Definition at line 178 of file GeomSvc.h.
References getDetectorID(), initWireLUT(), Plane::update(), and Plane::x0.
setDetectorY0()
void GeomSvc::setDetectorY0 (const std::string detectorName, const double val) inline
Definition at line 184 of file GeomSvc.h.
References getDetectorID(), initWireLUT(), Plane::update(), and Plane::y0.
setDetectorZ0()
void GeomSvc::setDetectorZ0 (const std::string detectorName, const double val) inline
Definition at line 190 of file GeomSvc.h.
References getDetectorID(), initWireLUT(), Plane::update(), and Plane::z0.
toLocalDetectorName()
void GeomSvc::toLocalDetectorName (std::string & detectorName, int & eID)
Convert the official detectorName to local detectorName.
Convert, for example, "P1H1f" to "P1Y1" and element ID accordingly. The input arguments are kept unchanged when they are not "local" name. The local name is used only in the channel mapping of the prop tube as of 2021-10-03.
Definition at line 732 of file GeomSvc.cxx.
Referenced by ChanMapV1495::Add(), ChanMapTaiwan::Add(), CalibParamXT::Add(), CalibParamInTimeTaiwan::Add(), CalibParamInTimeV1495::Add(), and initPlaneDbSvc().
UseDbSvc() [1/2]
static bool GeomSvc::UseDbSvc () inline static
Definition at line 344 of file GeomSvc.h.
Referenced by main().
UseDbSvc() [2/2]
static void GeomSvc::UseDbSvc (const bool val) inline static
Definition at line 343 of file GeomSvc.h.
Z_ABSORBER() [1/2]
double GeomSvc::Z_ABSORBER () const inline
Definition at line 315 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Referenced by ClassImp().
Z_ABSORBER() [2/2]
void GeomSvc::Z_ABSORBER (const double v) inline
Definition at line 316 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_DOWNSTREAM() [1/2]
double GeomSvc::Z_DOWNSTREAM () const inline
Definition at line 335 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Z_DOWNSTREAM() [2/2]
void GeomSvc::Z_DOWNSTREAM (const double v) inline
Definition at line 336 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_DUMP() [1/2]
double GeomSvc::Z_DUMP () const inline
Definition at line 321 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Z_DUMP() [2/2]
void GeomSvc::Z_DUMP (const double v) inline
Definition at line 322 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_FMAG_BEND() [1/2]
double GeomSvc::Z_FMAG_BEND () const inline
Definition at line 305 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Referenced by ClassImp().
Z_FMAG_BEND() [2/2]
void GeomSvc::Z_FMAG_BEND (const double v) inline
Definition at line 306 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_KFMAG_BEND() [1/2]
double GeomSvc::Z_KFMAG_BEND () const inline
Definition at line 307 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Referenced by ClassImp().
Z_KFMAG_BEND() [2/2]
void GeomSvc::Z_KFMAG_BEND (const double v) inline
Definition at line 308 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_KMAG_BEND() [1/2]
double GeomSvc::Z_KMAG_BEND () const inline
Getter/setters for a set of fixed parameters - should not be changed unless absolutely necessary.
Definition at line 303 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Referenced by ClassImp().
Z_KMAG_BEND() [2/2]
void GeomSvc::Z_KMAG_BEND (const double v) inline
Definition at line 304 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_REF() [1/2]
double GeomSvc::Z_REF () const inline
Definition at line 317 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Z_REF() [2/2]
void GeomSvc::Z_REF (const double v) inline
Definition at line 318 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_ST1() [1/2]
double GeomSvc::Z_ST1 () const inline
Definition at line 323 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Z_ST1() [2/2]
void GeomSvc::Z_ST1 (const double v) inline
Definition at line 324 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_ST2() [1/2]
double GeomSvc::Z_ST2 () const inline
Definition at line 313 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Z_ST2() [2/2]
void GeomSvc::Z_ST2 (const double v) inline
Definition at line 314 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_ST3() [1/2]
double GeomSvc::Z_ST3 () const inline
Definition at line 325 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Z_ST3() [2/2]
void GeomSvc::Z_ST3 (const double v) inline
Definition at line 326 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_TARGET() [1/2]
double GeomSvc::Z_TARGET () const inline
Definition at line 319 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Z_TARGET() [2/2]
void GeomSvc::Z_TARGET (const double v) inline
Definition at line 320 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
Z_UPSTREAM() [1/2]
double GeomSvc::Z_UPSTREAM () const inline
Definition at line 333 of file GeomSvc.h.
References PHFlag::get_DoubleFlag().
Z_UPSTREAM() [2/2]
void GeomSvc::Z_UPSTREAM (const double v) inline
Definition at line 334 of file GeomSvc.h.
References PHFlag::set_DoubleFlag().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/GeomSvc.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/GeomSvc.cxx