E1039 Software: PHG4Hit Class Reference
PHG4Hit Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4Hit.h>
Public Types
enum PROPERTY {
prop_eion = 1, prop_light_yield = 2, prop_px_0 = 10, prop_px_1 = 11,
prop_py_0 = 12, prop_py_1 = 13, prop_pz_0 = 14, prop_pz_1 = 15,
prop_path_length = 16, prop_local_x_0 = 20, prop_local_x_1 = 21, prop_local_y_0 = 22,
prop_local_y_1 = 23, prop_local_z_0 = 24, prop_local_z_1 = 25, prop_layer = 101,
prop_scint_id = 102, prop_row = 103, prop_strip_z_index = 110, prop_strip_y_index = 111,
prop_ladder_z_index = 112, prop_ladder_phi_index = 113, prop_stave_index = 114, prop_half_stave_index = 115,
prop_module_index = 116, prop_chip_index = 117, prop_local_pos_x_0 = 118, prop_local_pos_y_0 = 119,
prop_local_pos_z_0 = 120, prop_index_i = 121, prop_index_j = 122, prop_index_k = 123,
prop_index_l = 124, prop_hit_type = 125, prop_local_pos_x_1 = 128, prop_local_pos_y_1 = 126,
prop_local_pos_z_1 = 127, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
Public Member Functions
PHG4Hit ()
virtual ~PHG4Hit ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Copy (PHG4Hit const &g4hit)
virtual void Reset ()
Clear Event.
virtual float get_x (const int i) const
virtual float get_y (const int i) const
virtual float get_z (const int i) const
virtual float get_px (const int i) const
virtual float get_py (const int i) const
virtual float get_pz (const int i) const
virtual float get_local_x (const int i) const
virtual float get_local_y (const int i) const
virtual float get_local_z (const int i) const
virtual float get_t (const int i) const
virtual float get_edep () const
virtual float get_eion () const
virtual float get_light_yield () const
virtual float get_path_length () const
virtual unsigned int get_layer () const
virtual PHG4HitDefs::keytype get_hit_id () const
virtual int get_detid () const
virtual int get_shower_id () const
virtual int get_scint_id () const
virtual int get_row () const
virtual int get_trkid () const
virtual int get_strip_z_index () const
virtual int get_strip_y_index () const
virtual int get_ladder_z_index () const
virtual int get_ladder_phi_index () const
virtual int get_index_i () const
virtual int get_index_j () const
virtual int get_index_k () const
virtual int get_index_l () const
virtual int get_hit_type () const
virtual void set_x (const int i, const float f)
virtual void set_y (const int i, const float f)
virtual void set_z (const int i, const float f)
virtual void set_px (const int i, const float f)
virtual void set_py (const int i, const float f)
virtual void set_pz (const int i, const float f)
virtual void set_local_x (const int i, const float f)
virtual void set_local_y (const int i, const float f)
virtual void set_local_z (const int i, const float f)
virtual void set_t (const int i, const float f)
virtual void set_edep (const float f)
virtual void set_eion (const float f)
virtual void set_light_yield (const float lightYield)
virtual void set_path_length (const float pathLength)
virtual void set_layer (const unsigned int i)
virtual void set_hit_id (const PHG4HitDefs::keytype i)
virtual void set_shower_id (const int i)
virtual void set_scint_id (const int i)
virtual void set_row (const int i)
virtual void set_trkid (const int i)
virtual void set_strip_z_index (const int i)
virtual void set_strip_y_index (const int i)
virtual void set_ladder_z_index (const int i)
virtual void set_ladder_phi_index (const int i)
virtual void set_index_i (const int i)
virtual void set_index_j (const int i)
virtual void set_index_k (const int i)
virtual void set_index_l (const int i)
virtual void set_hit_type (const int i)
virtual float get_avg_x () const
virtual float get_avg_y () const
virtual float get_avg_z () const
virtual float get_avg_t () const
virtual void print () const
virtual bool has_property (const PROPERTY prop_id) const
virtual float get_property_float (const PROPERTY prop_id) const
virtual int get_property_int (const PROPERTY prop_id) const
virtual unsigned int get_property_uint (const PROPERTY prop_id) const
virtual void set_property (const PROPERTY prop_id, const float value)
virtual void set_property (const PROPERTY prop_id, const int value)
virtual void set_property (const PROPERTY prop_id, const unsigned int value)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Static Public Member Functions
static std::pair< const std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Member Functions
virtual unsigned int get_property_nocheck (const PROPERTY prop_id) const
virtual void set_property_nocheck (const PROPERTY prop_id, const unsigned int)
Friends
std::ostream & operator<< (std::ostream &stream, const PHG4Hit *hit)
Detailed Description
Definition at line 9 of file PHG4Hit.h.
Member Enumeration Documentation
PROPERTY
enum PHG4Hit::PROPERTY
Procedure to add a new PROPERTY tag: 1.add new tag below with unique value, 2.add a short name to PHG4Hit::get_property_info
Enumerator
prop_eion
ionizing energy loss
prop_light_yield
for scintillation detectors, the amount of light produced
prop_px_0
momentum
prop_px_1
prop_py_0
prop_py_1
prop_pz_0
prop_pz_1
prop_path_length
pathlength
prop_local_x_0
local coordinate
prop_local_x_1
prop_local_y_0
prop_local_y_1
prop_local_z_0
prop_local_z_1
prop_layer
layer ID
prop_scint_id
scintillator ID
prop_row
row (mother volume or steel plate id)
prop_strip_z_index
SVX stuff.
prop_strip_y_index
prop_ladder_z_index
prop_ladder_phi_index
prop_stave_index
prop_half_stave_index
prop_module_index
prop_chip_index
prop_local_pos_x_0
prop_local_pos_y_0
prop_local_pos_z_0
prop_index_i
generic indexes
prop_index_j
prop_index_k
prop_index_l
prop_hit_type
hit type
prop_local_pos_x_1
prop_local_pos_y_1
prop_local_pos_z_1
prop_MAX_NUMBER
max limit in order to fit into 8 bit unsigned number
Definition at line 93 of file PHG4Hit.h.
PROPERTY_TYPE
enum PHG4Hit::PROPERTY_TYPE
Enumerator
type_int
type_uint
type_float
type_unknown
Definition at line 166 of file PHG4Hit.h.
Constructor & Destructor Documentation
PHG4Hit()
PHG4Hit::PHG4Hit () inline
Definition at line 12 of file PHG4Hit.h.
~PHG4Hit()
virtual PHG4Hit::~PHG4Hit () inline virtual
Definition at line 13 of file PHG4Hit.h.
References Copy(), identify(), operator<<, and Reset().
Member Function Documentation
check_property()
bool PHG4Hit::check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type) static
Definition at line 157 of file PHG4Hit.cc.
Referenced by PHG4Hitv1::get_property_float(), PHG4Hitv1::get_property_int(), PHG4Hitv1::get_property_uint(), PHG4Hitv1::set_property(), and set_property().
Copy()
virtual void PHG4Hit::Copy (PHG4Hit const & g4hit) virtual
Reimplemented in PHG4HitEval.
Referenced by PHG4HitEval::Copy(), PHG4Hitv1::PHG4Hitv1(), and ~PHG4Hit().
get_avg_t()
float PHG4Hit::get_avg_t () const inline virtual
Definition at line 195 of file PHG4Hit.h.
References get_t().
Referenced by set_hit_type().
get_avg_x()
float PHG4Hit::get_avg_x () const inline virtual
Definition at line 192 of file PHG4Hit.h.
References get_x().
Referenced by operator<<(), and set_hit_type().
get_avg_y()
float PHG4Hit::get_avg_y () const inline virtual
Definition at line 193 of file PHG4Hit.h.
References get_y().
Referenced by operator<<(), and set_hit_type().
get_avg_z()
float PHG4Hit::get_avg_z () const inline virtual
Definition at line 194 of file PHG4Hit.h.
References get_z().
Referenced by operator<<(), and set_hit_type().
get_detid()
virtual int PHG4Hit::get_detid () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 37 of file PHG4Hit.h.
get_edep()
virtual float PHG4Hit::get_edep () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 31 of file PHG4Hit.h.
Referenced by ClassImp(), TruthEval::process_event(), PHG4TruthEventAction::ProcessShowers(), PHG4HitContainer::RemoveZeroEDep(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4ConeRegionSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), and PHG4PolyconSteppingAction::UserSteppingAction().
get_eion()
virtual float PHG4Hit::get_eion () const inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 32 of file PHG4Hit.h.
Referenced by PHG4TruthEventAction::ProcessShowers(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), and PHG4TargetCoilV2SteppingAction::UserSteppingAction().
get_hit_id()
virtual PHG4HitDefs::keytype PHG4Hit::get_hit_id () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 36 of file PHG4Hit.h.
Referenced by PHG4HitContainer::AddHit(), ClassImp(), DPDigitizer::digitize(), operator<<(), PHG4DSTReader::process_event(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4ConeRegionSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), and PHG4PolyconSteppingAction::UserSteppingAction().
get_hit_type()
virtual int PHG4Hit::get_hit_type () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 50 of file PHG4Hit.h.
Referenced by ClassImp().
get_index_i()
virtual int PHG4Hit::get_index_i () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 46 of file PHG4Hit.h.
get_index_j()
virtual int PHG4Hit::get_index_j () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 47 of file PHG4Hit.h.
get_index_k()
virtual int PHG4Hit::get_index_k () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 48 of file PHG4Hit.h.
get_index_l()
virtual int PHG4Hit::get_index_l () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 49 of file PHG4Hit.h.
get_ladder_phi_index()
virtual int PHG4Hit::get_ladder_phi_index () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 45 of file PHG4Hit.h.
get_ladder_z_index()
virtual int PHG4Hit::get_ladder_z_index () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 44 of file PHG4Hit.h.
get_layer()
virtual unsigned int PHG4Hit::get_layer () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 35 of file PHG4Hit.h.
Referenced by PHG4HitContainer::findOrAddHit(), operator<<(), and TruthEval::process_event().
get_light_yield()
virtual float PHG4Hit::get_light_yield () const inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 33 of file PHG4Hit.h.
Referenced by PHG4TruthEventAction::ProcessShowers(), PHG4PolyconSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), and PHG4CylinderSteppingAction::UserSteppingAction().
get_local_x()
virtual float PHG4Hit::get_local_x (const int i) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 27 of file PHG4Hit.h.
get_local_y()
virtual float PHG4Hit::get_local_y (const int i) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 28 of file PHG4Hit.h.
get_local_z()
virtual float PHG4Hit::get_local_z (const int i) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 29 of file PHG4Hit.h.
get_path_length()
virtual float PHG4Hit::get_path_length () const inline virtual
Reimplemented in PHG4HitEval, and PHG4Hitv1.
Definition at line 34 of file PHG4Hit.h.
get_property_float()
virtual float PHG4Hit::get_property_float (const PROPERTY prop_id) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 175 of file PHG4Hit.h.
get_property_info()
std::pair< const std::string, PHG4Hit::PROPERTY_TYPE > PHG4Hit::get_property_info (PROPERTY prop_id) static
Definition at line 70 of file PHG4Hit.cc.
References type_float, type_int, and type_uint.
Referenced by PHG4Hitv1::get_property_float(), PHG4Hitv1::get_property_int(), PHG4Hitv1::get_property_uint(), PHG4Hitv1::identify(), PHG4Hitv1::print(), PHG4Hitv1::set_property(), and set_property().
get_property_int()
virtual int PHG4Hit::get_property_int (const PROPERTY prop_id) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 176 of file PHG4Hit.h.
get_property_nocheck()
virtual unsigned int PHG4Hit::get_property_nocheck (const PROPERTY prop_id) const inline protected virtual
Reimplemented in PHG4Hitv1.
Definition at line 186 of file PHG4Hit.h.
Referenced by ClassImp().
get_property_type()
string PHG4Hit::get_property_type (const PROPERTY_TYPE prop_type) static
Definition at line 168 of file PHG4Hit.cc.
Referenced by PHG4Hitv1::get_property_float(), PHG4Hitv1::get_property_int(), PHG4Hitv1::get_property_uint(), PHG4Hitv1::set_property(), and set_property().
get_property_uint()
virtual unsigned int PHG4Hit::get_property_uint (const PROPERTY prop_id) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 177 of file PHG4Hit.h.
get_px()
virtual float PHG4Hit::get_px (const int i) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 24 of file PHG4Hit.h.
Referenced by DPDigitizer::digitize(), TrkEval::RecoEval(), PatternDBGen::TruthEval(), and TrkEval::TruthEval().
get_py()
virtual float PHG4Hit::get_py (const int i) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 25 of file PHG4Hit.h.
Referenced by DPDigitizer::digitize(), TrkEval::RecoEval(), PatternDBGen::TruthEval(), and TrkEval::TruthEval().
get_pz()
virtual float PHG4Hit::get_pz (const int i) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 26 of file PHG4Hit.h.
Referenced by DPDigitizer::digitize(), TrkEval::RecoEval(), PatternDBGen::TruthEval(), and TrkEval::TruthEval().
get_row()
virtual int PHG4Hit::get_row () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 40 of file PHG4Hit.h.
get_scint_id()
virtual int PHG4Hit::get_scint_id () const inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 39 of file PHG4Hit.h.
get_shower_id()
virtual int PHG4Hit::get_shower_id () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 38 of file PHG4Hit.h.
get_strip_y_index()
virtual int PHG4Hit::get_strip_y_index () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 43 of file PHG4Hit.h.
get_strip_z_index()
virtual int PHG4Hit::get_strip_z_index () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 42 of file PHG4Hit.h.
get_t()
virtual float PHG4Hit::get_t (const int i) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 30 of file PHG4Hit.h.
Referenced by ClassImp(), and get_avg_t().
get_trkid()
virtual int PHG4Hit::get_trkid () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 41 of file PHG4Hit.h.
Referenced by ClassImp(), DPDigitizer::digitize(), operator<<(), TruthEval::process_event(), PHG4DSTReader::process_event(), DPDigitizer::process_event(), and PHG4TruthEventAction::ProcessShowers().
get_x()
virtual float PHG4Hit::get_x (const int i) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 21 of file PHG4Hit.h.
Referenced by ClassImp(), DPDigitizer::digitize(), get_avg_x(), TruthEval::process_event(), PHG4TruthEventAction::ProcessShowers(), TrkEval::RecoEval(), PatternDBGen::TruthEval(), TrkEval::TruthEval(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), and PHG4CylinderSteppingAction::UserSteppingAction().
get_y()
virtual float PHG4Hit::get_y (const int i) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 22 of file PHG4Hit.h.
Referenced by ClassImp(), DPDigitizer::digitize(), get_avg_y(), TruthEval::process_event(), PHG4TruthEventAction::ProcessShowers(), TrkEval::RecoEval(), PatternDBGen::TruthEval(), and TrkEval::TruthEval().
get_z()
virtual float PHG4Hit::get_z (const int i) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 23 of file PHG4Hit.h.
Referenced by ClassImp(), DPDigitizer::digitize(), get_avg_z(), TruthEval::process_event(), PHG4TruthEventAction::ProcessShowers(), TrkEval::RecoEval(), PatternDBGen::TruthEval(), TrkEval::TruthEval(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), and PHG4CylinderSteppingAction::UserSteppingAction().
has_property()
virtual bool PHG4Hit::has_property (const PROPERTY prop_id) const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 174 of file PHG4Hit.h.
Referenced by ClassImp().
identify()
void PHG4Hit::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4Hitv1.
Definition at line 35 of file PHG4Hit.cc.
Referenced by TruthEval::process_event(), DPDigitizer::process_event(), TrkEval::RecoEval(), PatternDBGen::TruthEval(), TrkEval::TruthEval(), and ~PHG4Hit().
print()
virtual void PHG4Hit::print () const inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 87 of file PHG4Hit.h.
Reset()
void PHG4Hit::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in PHG4Hitv1.
Definition at line 63 of file PHG4Hit.cc.
Referenced by PHG4BlockSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), and ~PHG4Hit().
set_edep()
virtual void PHG4Hit::set_edep (const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 62 of file PHG4Hit.h.
Referenced by PHG4HitContainer::findOrAddHit(), PHG4GenHit::process_event(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), and PHG4ConeRegionSteppingAction::UserSteppingAction().
set_eion()
virtual void PHG4Hit::set_eion (const float f) inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 63 of file PHG4Hit.h.
Referenced by PHG4BlockSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), and PHG4TargetCoilV2SteppingAction::UserSteppingAction().
set_hit_id()
virtual void PHG4Hit::set_hit_id (const PHG4HitDefs::keytype i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 67 of file PHG4Hit.h.
Referenced by PHG4HitContainer::AddHit(), and PHG4HitContainer::findOrAddHit().
set_hit_type()
virtual void PHG4Hit::set_hit_type (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 80 of file PHG4Hit.h.
References get_avg_t(), get_avg_x(), get_avg_y(), and get_avg_z().
set_index_i()
virtual void PHG4Hit::set_index_i (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 76 of file PHG4Hit.h.
set_index_j()
virtual void PHG4Hit::set_index_j (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 77 of file PHG4Hit.h.
set_index_k()
virtual void PHG4Hit::set_index_k (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 78 of file PHG4Hit.h.
set_index_l()
virtual void PHG4Hit::set_index_l (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 79 of file PHG4Hit.h.
set_ladder_phi_index()
virtual void PHG4Hit::set_ladder_phi_index (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 75 of file PHG4Hit.h.
set_ladder_z_index()
virtual void PHG4Hit::set_ladder_z_index (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 74 of file PHG4Hit.h.
set_layer()
virtual void PHG4Hit::set_layer (const unsigned int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 66 of file PHG4Hit.h.
Referenced by PHG4GenHit::process_event(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), and PHG4TargetCoilSteppingAction::UserSteppingAction().
set_light_yield()
virtual void PHG4Hit::set_light_yield (const float lightYield) inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 64 of file PHG4Hit.h.
Referenced by PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), and PHG4CylinderSteppingAction::UserSteppingAction().
set_local_x()
virtual void PHG4Hit::set_local_x (const int i, const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 58 of file PHG4Hit.h.
Referenced by PHG4SteppingAction::StoreLocalCoordinate().
set_local_y()
virtual void PHG4Hit::set_local_y (const int i, const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 59 of file PHG4Hit.h.
Referenced by PHG4SteppingAction::StoreLocalCoordinate().
set_local_z()
virtual void PHG4Hit::set_local_z (const int i, const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 60 of file PHG4Hit.h.
Referenced by PHG4SteppingAction::StoreLocalCoordinate().
set_path_length()
virtual void PHG4Hit::set_path_length (const float pathLength) inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 65 of file PHG4Hit.h.
set_property() [1/3]
virtual void PHG4Hit::set_property (const PROPERTY prop_id, const float value) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 178 of file PHG4Hit.h.
set_property() [2/3]
virtual void PHG4Hit::set_property (const PROPERTY prop_id, const int value) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 179 of file PHG4Hit.h.
set_property() [3/3]
virtual void PHG4Hit::set_property (const PROPERTY prop_id, const unsigned int value) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 180 of file PHG4Hit.h.
References check_property(), get_property_info(), and get_property_type().
set_property_nocheck()
virtual void PHG4Hit::set_property_nocheck (const PROPERTY prop_id, const unsigned int) inline protected virtual
Reimplemented in PHG4Hitv1.
Definition at line 187 of file PHG4Hit.h.
set_px()
virtual void PHG4Hit::set_px (const int i, const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 55 of file PHG4Hit.h.
Referenced by PHG4BlockSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), and PHG4BNLTargetCoilSteppingAction::UserSteppingAction().
set_py()
virtual void PHG4Hit::set_py (const int i, const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 56 of file PHG4Hit.h.
Referenced by PHG4BlockSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), and PHG4BNLTargetCoilSteppingAction::UserSteppingAction().
set_pz()
virtual void PHG4Hit::set_pz (const int i, const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 57 of file PHG4Hit.h.
Referenced by PHG4BlockSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), and PHG4BNLTargetCoilSteppingAction::UserSteppingAction().
set_row()
virtual void PHG4Hit::set_row (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 70 of file PHG4Hit.h.
set_scint_id()
virtual void PHG4Hit::set_scint_id (const int i) inline virtual
Reimplemented in PHG4Hitv1, and PHG4HitEval.
Definition at line 69 of file PHG4Hit.h.
set_shower_id()
virtual void PHG4Hit::set_shower_id (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 68 of file PHG4Hit.h.
Referenced by PHG4BlockSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4ConeRegionSteppingAction::UserSteppingAction(), and PHG4PolyconSteppingAction::UserSteppingAction().
set_strip_y_index()
virtual void PHG4Hit::set_strip_y_index (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 73 of file PHG4Hit.h.
set_strip_z_index()
virtual void PHG4Hit::set_strip_z_index (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 72 of file PHG4Hit.h.
set_t()
virtual void PHG4Hit::set_t (const int i, const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 61 of file PHG4Hit.h.
Referenced by PHG4BlockSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4ConeRegionSteppingAction::UserSteppingAction(), and PHG4PolyconSteppingAction::UserSteppingAction().
set_trkid()
virtual void PHG4Hit::set_trkid (const int i) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 71 of file PHG4Hit.h.
Referenced by PHG4GenHit::process_event(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), and PHG4ConeRegionSteppingAction::UserSteppingAction().
set_x()
virtual void PHG4Hit::set_x (const int i, const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 52 of file PHG4Hit.h.
Referenced by PHG4GenHit::process_event(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), and PHG4ConeRegionSteppingAction::UserSteppingAction().
set_y()
virtual void PHG4Hit::set_y (const int i, const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 53 of file PHG4Hit.h.
Referenced by PHG4GenHit::process_event(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), and PHG4ConeRegionSteppingAction::UserSteppingAction().
set_z()
virtual void PHG4Hit::set_z (const int i, const float f) inline virtual
Reimplemented in PHG4Hitv1.
Definition at line 54 of file PHG4Hit.h.
Referenced by PHG4GenHit::process_event(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4SquareTubeSteppingAction::UserSteppingAction(), PHG4CollimatorSteppingAction::UserSteppingAction(), PHG4E1039InsensSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4BNLTargetCoilSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4TargetCoilV2SteppingAction::UserSteppingAction(), PHG4TargetCoilSteppingAction::UserSteppingAction(), PHG4PolyconSteppingAction::UserSteppingAction(), and PHG4ConeRegionSteppingAction::UserSteppingAction().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, const PHG4Hit * hit) friend
Definition at line 56 of file PHG4Hit.cc.
Referenced by ~PHG4Hit().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4Hit.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4Hit.cc