E1039 Software: PHHepMCGenHelper Class Reference
PHHepMCGenHelper Class Reference
PHHepMCGenHelper provides service of DST upload of HepMC subevent, vertex assignment and random generator.
#include </home/yuhw/GitHub/SeaQuest/e1039-core/generators/phhepmc/PHHepMCGenHelper.h>
Public Types
enum VTXFUNC { Uniform, Gaus }
supported function distributions
Public Member Functions
PHHepMCGenHelper ()
virtual ~PHHepMCGenHelper ()
void set_vertex_distribution_function (VTXFUNC x, VTXFUNC y, VTXFUNC z, VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
int get_embedding_id () const
void set_embedding_id (int id)
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int create_node_tree (PHCompositeNode *topNode)
init interface nodes
PHHepMCGenEvent * insert_event (HepMC::GenEvent *evt)
send HepMC::GenEvent to DST tree. This function takes ownership of evt
void move_vertex (PHHepMCGenEvent *genevent)
move vertex according to vertex settings
const PHHepMCGenEventMap * get_geneventmap () const
PHHepMCGenEventMap * get_geneventmap ()
gsl_rng * get_random_generator ()
void set_geneventmap (PHHepMCGenEventMap *geneventmap)
Protected Member Functions
double smear (const double position, const double width, VTXFUNC dist) const
Protected Attributes
gsl_rng * RandomGenerator
Private Attributes
VTXFUNC _vertex_func_x
VTXFUNC _vertex_func_y
VTXFUNC _vertex_func_z
VTXFUNC _vertex_func_t
double _vertex_x
double _vertex_y
double _vertex_z
double _vertex_t
double _vertex_width_x
double _vertex_width_y
double _vertex_width_z
double _vertex_width_t
int _embedding_id
bool _reuse_vertex
whether reuse vertex from another PHHepMCGenEvent
int _reuse_vertex_embedding_id
if reuse_vertex, which embedding_id provide the source vertex. Additional smearing and shift possible with set_vertex_distribution*()
PHHepMCGenEventMap * _geneventmap
pointer to the output container
Detailed Description
PHHepMCGenHelper provides service of DST upload of HepMC subevent, vertex assignment and random generator.
Definition at line 32 of file PHHepMCGenHelper.h.
Member Enumeration Documentation
VTXFUNC
enum PHHepMCGenHelper::VTXFUNC
supported function distributions
Enumerator
Uniform
uniform distribution with half width set via set_vertex_distribution_width()
Gaus
normal distribution with sigma width set via set_vertex_distribution_width()
Definition at line 39 of file PHHepMCGenHelper.h.
Constructor & Destructor Documentation
PHHepMCGenHelper()
PHHepMCGenHelper::PHHepMCGenHelper ()
Definition at line 35 of file PHHepMCGenHelper.cc.
References RandomGenerator.
~PHHepMCGenHelper()
PHHepMCGenHelper::~PHHepMCGenHelper () virtual
Definition at line 59 of file PHHepMCGenHelper.cc.
References RandomGenerator.
Member Function Documentation
create_node_tree()
int PHHepMCGenHelper::create_node_tree (PHCompositeNode * topNode)
init interface nodes
Definition at line 65 of file PHHepMCGenHelper.cc.
References _geneventmap, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by ReadEICFiles::CreateNodeTree().
get_embedding_id()
int PHHepMCGenHelper::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 60 of file PHHepMCGenHelper.h.
Referenced by Fun4AllOscarInputManager::ConvertFromOscar(), Fun4AllHepMCPileupInputManager::run(), and Fun4AllHepMCInputManager::run().
get_geneventmap() [1/2]
const PHHepMCGenEventMap* PHHepMCGenHelper::get_geneventmap () const inline
Definition at line 85 of file PHHepMCGenHelper.h.
Referenced by Fun4AllOscarInputManager::ConvertFromOscar(), Fun4AllHepMCPileupInputManager::run(), and Fun4AllHepMCInputManager::run().
get_geneventmap() [2/2]
PHHepMCGenEventMap* PHHepMCGenHelper::get_geneventmap () inline
Definition at line 90 of file PHHepMCGenHelper.h.
get_random_generator()
gsl_rng* PHHepMCGenHelper::get_random_generator () inline
Definition at line 96 of file PHHepMCGenHelper.h.
insert_event()
PHHepMCGenEvent * PHHepMCGenHelper::insert_event (HepMC::GenEvent * evt)
send HepMC::GenEvent to DST tree. This function takes ownership of evt
Definition at line 89 of file PHHepMCGenHelper.cc.
References _embedding_id, _geneventmap, PHHepMCGenEvent::addEvent(), PHHepMCGenEventMap::insert_event(), and move_vertex().
Referenced by Fun4AllOscarInputManager::ConvertFromOscar(), and Fun4AllHepMCInputManager::run().
move_vertex()
void PHHepMCGenHelper::move_vertex (PHHepMCGenEvent * genevent)
move vertex according to vertex settings
Definition at line 102 of file PHHepMCGenHelper.cc.
References _geneventmap, _reuse_vertex, _reuse_vertex_embedding_id, _vertex_func_t, _vertex_func_x, _vertex_func_y, _vertex_func_z, _vertex_t, _vertex_width_t, _vertex_width_x, _vertex_width_y, _vertex_width_z, _vertex_x, _vertex_y, _vertex_z, PHHepMCGenEventMap::get(), PHHepMCGenEvent::get_collision_vertex(), PHHepMCGenEventMap::identify(), PHHepMCGenEvent::moveVertex(), and smear().
Referenced by insert_event(), and Fun4AllHepMCPileupInputManager::run().
set_embedding_id()
void PHHepMCGenHelper::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 66 of file PHHepMCGenHelper.h.
Referenced by Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager(), and ReadEICFiles::ReadEICFiles().
set_geneventmap()
void PHHepMCGenHelper::set_geneventmap (PHHepMCGenEventMap * geneventmap) inline
Definition at line 99 of file PHHepMCGenHelper.h.
Referenced by Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), and Fun4AllOscarInputManager::Fun4AllOscarInputManager().
set_reuse_vertex()
void PHHepMCGenHelper::set_reuse_vertex (int src_embedding_id) inline
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
Definition at line 69 of file PHHepMCGenHelper.h.
set_vertex_distribution_function()
void PHHepMCGenHelper::set_vertex_distribution_function (VTXFUNC x, VTXFUNC y, VTXFUNC z, VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 137 of file PHHepMCGenHelper.cc.
References _vertex_func_t, _vertex_func_x, _vertex_func_y, and _vertex_func_z.
Referenced by Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager().
set_vertex_distribution_mean()
void PHHepMCGenHelper::set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
Definition at line 146 of file PHHepMCGenHelper.cc.
References _vertex_t, _vertex_x, _vertex_y, and _vertex_z.
Referenced by Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager().
set_vertex_distribution_width()
void PHHepMCGenHelper::set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
Definition at line 155 of file PHHepMCGenHelper.cc.
References _vertex_width_t, _vertex_width_x, _vertex_width_y, and _vertex_width_z.
Referenced by Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager().
smear()
double PHHepMCGenHelper::smear (const double position, const double width, VTXFUNC dist) const protected
Definition at line 164 of file PHHepMCGenHelper.cc.
References Gaus, RandomGenerator, and Uniform.
Referenced by move_vertex().
Member Data Documentation
_embedding_id
int PHHepMCGenHelper::_embedding_id private
positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 130 of file PHHepMCGenHelper.h.
Referenced by insert_event().
_geneventmap
PHHepMCGenEventMap* PHHepMCGenHelper::_geneventmap private
pointer to the output container
Definition at line 139 of file PHHepMCGenHelper.h.
Referenced by create_node_tree(), insert_event(), and move_vertex().
_reuse_vertex
bool PHHepMCGenHelper::_reuse_vertex private
whether reuse vertex from another PHHepMCGenEvent
Definition at line 133 of file PHHepMCGenHelper.h.
Referenced by move_vertex().
_reuse_vertex_embedding_id
int PHHepMCGenHelper::_reuse_vertex_embedding_id private
if reuse_vertex, which embedding_id provide the source vertex. Additional smearing and shift possible with set_vertex_distribution*()
Definition at line 136 of file PHHepMCGenHelper.h.
Referenced by move_vertex().
_vertex_func_t
VTXFUNC PHHepMCGenHelper::_vertex_func_t private
Definition at line 115 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_function().
_vertex_func_x
VTXFUNC PHHepMCGenHelper::_vertex_func_x private
Definition at line 112 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_function().
_vertex_func_y
VTXFUNC PHHepMCGenHelper::_vertex_func_y private
Definition at line 113 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_function().
_vertex_func_z
VTXFUNC PHHepMCGenHelper::_vertex_func_z private
Definition at line 114 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_function().
_vertex_t
double PHHepMCGenHelper::_vertex_t private
Definition at line 120 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_mean().
_vertex_width_t
double PHHepMCGenHelper::_vertex_width_t private
Definition at line 125 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_width().
_vertex_width_x
double PHHepMCGenHelper::_vertex_width_x private
Definition at line 122 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_width().
_vertex_width_y
double PHHepMCGenHelper::_vertex_width_y private
Definition at line 123 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_width().
_vertex_width_z
double PHHepMCGenHelper::_vertex_width_z private
Definition at line 124 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_width().
_vertex_x
double PHHepMCGenHelper::_vertex_x private
Definition at line 117 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_mean().
_vertex_y
double PHHepMCGenHelper::_vertex_y private
Definition at line 118 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_mean().
_vertex_z
double PHHepMCGenHelper::_vertex_z private
Definition at line 119 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_mean().
RandomGenerator
gsl_rng* PHHepMCGenHelper::RandomGenerator protected
Definition at line 106 of file PHHepMCGenHelper.h.
Referenced by PHHepMCGenHelper(), smear(), and ~PHHepMCGenHelper().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/generators/phhepmc/PHHepMCGenHelper.h
/home/yuhw/GitHub/SeaQuest/e1039-core/generators/phhepmc/PHHepMCGenHelper.cc