Class Reference for E1039 Core & Analysis Software: UtilTrack Namespace Reference
UtilTrack Namespace Reference
Functions
SQTrack * FindTrackByID (const SQTrackVector *vec, const int id_trk, const bool do_assert=false)
Find a track by track ID in the given track list.
SQHitVector * FindHitsOfTrack (const SQHitVector *vec_in, const int id_trk)
Find all hits associated with the given track.
SQHitVector * FindDetectorHitsOfTrack (const SQHitVector *vec_in, const int id_trk, const std::string det_name)
Find track-associated hits whose detector name starts with 'det_name'.
SQHitVector * FindDetectorHitsOfTrack (const SQHitVector *vec_in, const int id_trk, const char *det_name)
Find track-associated hits whose detector name starts with 'det_name'.
SQHitVector * FindHodoHitsOfTrack (const SQHitVector *vec_in, const int id_trk)
Find all hodoscope hits hits associated with the given track.
Function Documentation
FindDetectorHitsOfTrack() [1/2]
SQHitVector * UtilTrack::FindDetectorHitsOfTrack (const SQHitVector * vec_in, const int id_trk, const char * det_name)
Find track-associated hits whose detector name starts with 'det_name'.
Definition at line 67 of file UtilTrack.cc.
References FindDetectorHitsOfTrack().
FindDetectorHitsOfTrack() [2/2]
SQHitVector * UtilTrack::FindDetectorHitsOfTrack (const SQHitVector * vec_in, const int id_trk, const std::string det_name)
Find track-associated hits whose detector name starts with 'det_name'.
Examples:
shared_ptr<SQHitVector> hit_vec_trk_d0(UtilTrack::FindDetectorHitsOfTrack(hit_vec, id_trk, "D0"));
You can use "FindHodoHitsOfTrack()" to more-conveniently find all hodoscope hits.
Definition at line 52 of file UtilTrack.cc.
References SQHitVector::begin(), SQHitVector::clear(), SQHitVector::Clone(), SQHitVector::end(), SQHit::get_detector_id(), SQHit::get_track_id(), GeomSvc::getDetectorName(), GeomSvc::instance(), and SQHitVector::push_back().
Referenced by FindDetectorHitsOfTrack(), and FindHodoHitsOfTrack().
FindHitsOfTrack()
SQHitVector * UtilTrack::FindHitsOfTrack (const SQHitVector * vec_in, const int id_trk)
Find all hits associated with the given track.
It is recommended to receive the returned pointer by "shared_ptr".
shared_ptr<SQHitVector> hit_vec_trk(UtilTrack::FindHitsOfTrack(hit_vec, id_trk));
Definition at line 32 of file UtilTrack.cc.
References SQHitVector::begin(), SQHitVector::clear(), SQHitVector::Clone(), SQHitVector::end(), SQHit::get_track_id(), and SQHitVector::push_back().
FindHodoHitsOfTrack()
SQHitVector * UtilTrack::FindHodoHitsOfTrack (const SQHitVector * vec_in, const int id_trk)
Find all hodoscope hits hits associated with the given track.
Example:
shared_ptr<SQHitVector> hit_vec_trk(UtilTrack::FindHodoHitsOfTrack(hit_vec, id_trk));
Definition at line 79 of file UtilTrack.cc.
References FindDetectorHitsOfTrack().
Referenced by SubsysRecoSignal::process_event().
FindTrackByID()
SQTrack * UtilTrack::FindTrackByID (const SQTrackVector * vec, const int id_trk, const bool do_assert = false)
Find a track by track ID in the given track list.
This function returns a SQTrack pointer if successful. Otherwise it returns '0' by default, or aborts when 'do_assert' = true.
Definition at line 13 of file UtilTrack.cc.
References SQTrackVector::begin(), SQTrackVector::end(), and SQTrack::get_track_id().
Referenced by SubsysRecoSignal::process_event().