Class Reference for E1039 Core & Analysis Software: PHG4EventHeader Class Reference
PHG4EventHeader Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4EventHeader.h>
Public Member Functions
virtual ~PHG4EventHeader ()
dtor
virtual void Reset ()
Clear Event.
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains valid data
virtual int get_EvtSequence () const
get Event Number
virtual void set_EvtSequence (const int)
set Event Number
virtual float get_ImpactParameter () const
virtual void set_ImpactParameter (const float)
virtual float get_EventPlaneAngle () const
virtual void set_EventPlaneAngle (const float)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Detailed Description
Definition at line 11 of file PHG4EventHeader.h.
Constructor & Destructor Documentation
~PHG4EventHeader()
virtual PHG4EventHeader::~PHG4EventHeader () inline virtual
dtor
Definition at line 16 of file PHG4EventHeader.h.
Member Function Documentation
get_EventPlaneAngle()
virtual float PHG4EventHeader::get_EventPlaneAngle () const inline virtual
Reimplemented in PHG4EventHeaderv1.
Definition at line 49 of file PHG4EventHeader.h.
get_EvtSequence()
virtual int PHG4EventHeader::get_EvtSequence () const inline virtual
get Event Number
Reimplemented in PHG4EventHeaderv1.
Definition at line 42 of file PHG4EventHeader.h.
get_ImpactParameter()
virtual float PHG4EventHeader::get_ImpactParameter () const inline virtual
Reimplemented in PHG4EventHeaderv1.
Definition at line 46 of file PHG4EventHeader.h.
identify()
virtual void PHG4EventHeader::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4EventHeaderv1.
Definition at line 28 of file PHG4EventHeader.h.
Referenced by PHG4HeadReco::process_event().
isValid()
virtual int PHG4EventHeader::isValid () const inline virtual
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Reimplemented in PHG4EventHeaderv1.
Definition at line 35 of file PHG4EventHeader.h.
References PHWHERE.
Reset()
virtual void PHG4EventHeader::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in PHG4EventHeaderv1.
Definition at line 19 of file PHG4EventHeader.h.
References PHWHERE.
set_EventPlaneAngle()
virtual void PHG4EventHeader::set_EventPlaneAngle (const float) inline virtual
Reimplemented in PHG4EventHeaderv1.
Definition at line 50 of file PHG4EventHeader.h.
Referenced by PHG4HeadReco::process_event().
set_EvtSequence()
virtual void PHG4EventHeader::set_EvtSequence (const int) inline virtual
set Event Number
Reimplemented in PHG4EventHeaderv1.
Definition at line 44 of file PHG4EventHeader.h.
Referenced by PHG4HeadReco::process_event().
set_ImpactParameter()
virtual void PHG4EventHeader::set_ImpactParameter (const float) inline virtual
Reimplemented in PHG4EventHeaderv1.
Definition at line 47 of file PHG4EventHeader.h.
Referenced by PHG4HeadReco::process_event().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4EventHeader.h