E1039 Software: SQGenFit::GFTrack Class Reference
SQGenFit::GFTrack Class Reference
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/SQGenFit/GFTrack.h>
Public Member Functions
GFTrack ()
~GFTrack ()
void setVerbosity (unsigned int v)
void setTracklet (Tracklet &tracklet, double z_reference=590., bool wildseedcov=false)
void addMeasurements (std::vector< GFMeasurement * > &measurements)
void addMeasurement (GFMeasurement *measurement)
double getChi2 ()
double getNDF ()
int getCharge ()
int getNearestMeasurementID (GFMeasurement *meas)
double extrapolateToLine (TVector3 &endPoint1, TVector3 &endPoint2, const int startPtID=0)
double extrapolateToPlane (TVector3 &pO, TVector3 &pU, TVector3 &pV, const int startPtID=0)
double extrapolateToPoint (TVector3 &point, bool update=false, const int startPtID=0)
double updatePropState (const TVectorD &meas, const TMatrixDSym &V)
void getExtrapPosMomCov (TVector3 &pos, TVector3 &mom, TMatrixDSym &cov)
void getExtrapPosMom (TVector3 &pos, TVector3 &mom)
void checkConsistency ()
void postFitUpdate (bool updateMeasurements=true)
SRecTrack getSRecTrack ()
void print (unsigned int debugLvl=0)
genfit::Track * getGenFitTrack ()
genfit::AbsTrackRep * getGenFitTrkRep ()
Private Member Functions
bool setInitialStateForExtrap (const int startPtID=0)
Private Attributes
genfit::AbsTrackRep * _trkrep
genfit::Track * _track
std::vector< GFMeasurement * > _measurements
std::unique_ptr
< genfit::MeasuredStateOnPlane > _propState
std::unique_ptr
< genfit::AbsMeasurement > _virtMeas
Tracklet * _trkcand
int _pdg
Detailed Description
Definition at line 21 of file GFTrack.h.
Constructor & Destructor Documentation
SQGenFit::GFTrack::GFTrack ()
Definition at line 23 of file GFTrack.cxx.
SQGenFit::GFTrack::~GFTrack ()
Definition at line 26 of file GFTrack.cxx.
References _track.
Member Function Documentation
void SQGenFit::GFTrack::addMeasurement (GFMeasurement * measurement)
Definition at line 45 of file GFTrack.cxx.
References _track, SQGenFit::GFMeasurement::getZ(), and SQGenFit::GFMeasurement::setTrackPtr().
Referenced by addMeasurements().
void SQGenFit::GFTrack::addMeasurements (std::vector< GFMeasurement * > & measurements)
Definition at line 36 of file GFTrack.cxx.
References addMeasurement().
Referenced by setTracklet().
void SQGenFit::GFTrack::checkConsistency () inline
Definition at line 46 of file GFTrack.h.
References _track.
Referenced by SQGenFit::GFFitter::processTrack(), and setTracklet().
double SQGenFit::GFTrack::extrapolateToLine (TVector3 & endPoint1, TVector3 & endPoint2, const int startPtID = 0)
Definition at line 97 of file GFTrack.cxx.
References _propState, _track, _virtMeas, and setInitialStateForExtrap().
double SQGenFit::GFTrack::extrapolateToPlane (TVector3 & pO, TVector3 & pU, TVector3 & pV, const int startPtID = 0)
Definition at line 122 of file GFTrack.cxx.
References _propState, _track, _virtMeas, and setInitialStateForExtrap().
Referenced by getSRecTrack().
double SQGenFit::GFTrack::extrapolateToPoint (TVector3 & point, bool update = false, const int startPtID = 0)
Definition at line 144 of file GFTrack.cxx.
References _propState, _track, and setInitialStateForExtrap().
int SQGenFit::GFTrack::getCharge () inline
Definition at line 34 of file GFTrack.h.
References _trkcand, and Tracklet::getCharge().
Referenced by getSRecTrack().
double SQGenFit::GFTrack::getChi2 ()
Definition at line 54 of file GFTrack.cxx.
References _track.
Referenced by getSRecTrack().
void SQGenFit::GFTrack::getExtrapPosMom (TVector3 & pos, TVector3 & mom) inline
Definition at line 44 of file GFTrack.h.
References _propState.
void SQGenFit::GFTrack::getExtrapPosMomCov (TVector3 & pos, TVector3 & mom, TMatrixDSym & cov) inline
Definition at line 43 of file GFTrack.h.
References _propState.
genfit::Track* SQGenFit::GFTrack::getGenFitTrack () inline
Definition at line 53 of file GFTrack.h.
References _track.
Referenced by SQGenFit::GFFitter::processTrack().
genfit::AbsTrackRep* SQGenFit::GFTrack::getGenFitTrkRep () inline
Definition at line 54 of file GFTrack.h.
References _trkrep.
double SQGenFit::GFTrack::getNDF ()
Definition at line 66 of file GFTrack.cxx.
References _track.
int SQGenFit::GFTrack::getNearestMeasurementID (GFMeasurement * meas)
Definition at line 78 of file GFTrack.cxx.
References _measurements, and SQGenFit::GFMeasurement::getZ().
SRecTrack SQGenFit::GFTrack::getSRecTrack ()
Definition at line 261 of file GFTrack.cxx.
References _measurements, extrapolateToPlane(), getCharge(), getChi2(), SRecTrack::getVertexPos(), SRecTrack::insertChisq(), SRecTrack::insertCovariance(), SRecTrack::insertHitIndex(), SRecTrack::insertStateVector(), SRecTrack::insertZ(), SRecTrack::setChisq(), SRecTrack::setChisqDump(), SRecTrack::setChisqTarget(), SRecTrack::setChisqUpstream(), SRecTrack::setChisqVertex(), SRecTrack::setKalmanStatus(), SRecTrack::swimToVertex(), updatePropState(), Z_DUMP, Z_TARGET, and Z_UPSTREAM.
Referenced by SQReco::fitTrackCand().
void SQGenFit::GFTrack::postFitUpdate (bool updateMeasurements = true)
Definition at line 252 of file GFTrack.cxx.
References _measurements.
Referenced by SQReco::fitTrackCand(), and main().
void SQGenFit::GFTrack::print (unsigned int debugLvl = 0)
Definition at line 402 of file GFTrack.cxx.
References _measurements, _track, _trkcand, _trkrep, and Tracklet::print().
Referenced by SQReco::fitTrackCand(), and main().
bool SQGenFit::GFTrack::setInitialStateForExtrap (const int startPtID = 0) private
Definition at line 193 of file GFTrack.cxx.
References _propState, and _track.
Referenced by extrapolateToLine(), extrapolateToPlane(), and extrapolateToPoint().
void SQGenFit::GFTrack::setTracklet (Tracklet & tracklet, double z_reference = 590., bool wildseedcov = false)
Definition at line 205 of file GFTrack.cxx.
References _measurements, _pdg, _track, _trkcand, _trkrep, addMeasurements(), checkConsistency(), Tracklet::getCharge(), Tracklet::getExpMomentum(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), SQGenFit::GFMeasurement::getZ(), and Tracklet::hits.
Referenced by SQReco::fitTrackCand(), and main().
void SQGenFit::GFTrack::setVerbosity (unsigned int v)
Definition at line 31 of file GFTrack.cxx.
References _trkrep.
Referenced by main().
double SQGenFit::GFTrack::updatePropState (const TVectorD & meas, const TMatrixDSym & V)
Definition at line 156 of file GFTrack.cxx.
References _propState, and _virtMeas.
Referenced by getSRecTrack().
Member Data Documentation
std::vector<GFMeasurement*> SQGenFit::GFTrack::_measurements private
Definition at line 63 of file GFTrack.h.
Referenced by getNearestMeasurementID(), getSRecTrack(), postFitUpdate(), print(), and setTracklet().
int SQGenFit::GFTrack::_pdg private
Definition at line 71 of file GFTrack.h.
Referenced by setTracklet().
std::unique_ptr<genfit::MeasuredStateOnPlane> SQGenFit::GFTrack::_propState private
Definition at line 66 of file GFTrack.h.
Referenced by extrapolateToLine(), extrapolateToPlane(), extrapolateToPoint(), getExtrapPosMom(), getExtrapPosMomCov(), setInitialStateForExtrap(), and updatePropState().
genfit::Track* SQGenFit::GFTrack::_track private
Definition at line 62 of file GFTrack.h.
Referenced by addMeasurement(), checkConsistency(), extrapolateToLine(), extrapolateToPlane(), extrapolateToPoint(), getChi2(), getGenFitTrack(), getNDF(), print(), setInitialStateForExtrap(), setTracklet(), and ~GFTrack().
Tracklet* SQGenFit::GFTrack::_trkcand private
Definition at line 70 of file GFTrack.h.
Referenced by getCharge(), print(), and setTracklet().
genfit::AbsTrackRep* SQGenFit::GFTrack::_trkrep private
Definition at line 61 of file GFTrack.h.
Referenced by getGenFitTrkRep(), print(), setTracklet(), and setVerbosity().
std::unique_ptr<genfit::AbsMeasurement> SQGenFit::GFTrack::_virtMeas private
Definition at line 67 of file GFTrack.h.
Referenced by extrapolateToLine(), extrapolateToPlane(), and updatePropState().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/SQGenFit/GFTrack.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/SQGenFit/GFTrack.cxx