E1039 Software: PHG4TruthTrackingAction Class Reference
PHG4TruthTrackingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4TruthTrackingAction.h>
Public Member Functions
PHG4TruthTrackingAction (PHG4TruthEventAction *)
constructor
virtual ~PHG4TruthTrackingAction ()
destructor
virtual void PreUserTrackingAction (const G4Track *)
tracking action
virtual void PostUserTrackingAction (const G4Track *)
virtual void SetInterfacePointers (PHCompositeNode *)
Set pointers to the i/o nodes.
int ResetEvent (PHCompositeNode *)
Public Member Functions inherited from PHG4TrackingAction
PHG4TrackingAction (void)
virtual ~PHG4TrackingAction ()
Private Attributes
std::map< G4ThreeVector, int > VertexMap
PHG4TruthEventAction * eventAction_
pointer to the "owning" event action
PHG4TruthInfoContainer * truthInfoList_
pointer to truth information container
Detailed Description
Definition at line 13 of file PHG4TruthTrackingAction.h.
Constructor & Destructor Documentation
PHG4TruthTrackingAction()
PHG4TruthTrackingAction::PHG4TruthTrackingAction (PHG4TruthEventAction * eventAction)
constructor
Definition at line 27 of file PHG4TruthTrackingAction.cc.
~PHG4TruthTrackingAction()
virtual PHG4TruthTrackingAction::~PHG4TruthTrackingAction () inline virtual
destructor
Definition at line 21 of file PHG4TruthTrackingAction.h.
References PostUserTrackingAction(), PreUserTrackingAction(), ResetEvent(), and SetInterfacePointers().
Member Function Documentation
PostUserTrackingAction()
void PHG4TruthTrackingAction::PostUserTrackingAction (const G4Track * track) virtual
Definition at line 149 of file PHG4TruthTrackingAction.cc.
References PHG4TruthEventAction::AddTrackidToWritelist(), eventAction_, NULL, PHG4TrackUserInfo::SetShower(), PHG4TrackUserInfo::SetUserParentId(), and PHG4TrackUserInfo::SetUserPrimaryId().
Referenced by ~PHG4TruthTrackingAction().
PreUserTrackingAction()
void PHG4TruthTrackingAction::PreUserTrackingAction (const G4Track * track) virtual
tracking action
Definition at line 32 of file PHG4TruthTrackingAction.cc.
References PHG4TruthInfoContainer::AddParticle(), PHG4TruthInfoContainer::AddShower(), PHG4TruthInfoContainer::AddVertex(), PHG4UserPrimaryParticleInformation::get_user_barcode(), PHG4TruthInfoContainer::maxtrkindex(), PHG4TruthInfoContainer::maxvtxindex(), PHG4TruthInfoContainer::mintrkindex(), PHG4TruthInfoContainer::minvtxindex(), PHG4Particlev1::set_barcode(), PHG4Particlev2::set_e(), PHG4Showerv1::set_id(), PHG4Particlev1::set_name(), PHG4Particlev2::set_parent_id(), PHG4Showerv1::set_parent_particle_id(), PHG4Showerv1::set_parent_shower_id(), PHG4Particlev1::set_pid(), PHG4Particlev2::set_primary_id(), PHG4Particlev1::set_px(), PHG4Particlev1::set_py(), PHG4Particlev1::set_pz(), PHG4Particlev2::set_track_id(), PHG4UserPrimaryParticleInformation::set_user_track_id(), PHG4UserPrimaryParticleInformation::set_user_vtx_id(), PHG4Particlev2::set_vtx_id(), PHG4TrackUserInfo::SetShower(), PHG4TrackUserInfo::SetUserPrimaryId(), PHG4TrackUserInfo::SetUserTrackId(), truthInfoList_, and VertexMap.
Referenced by ~PHG4TruthTrackingAction().
ResetEvent()
int PHG4TruthTrackingAction::ResetEvent (PHCompositeNode *) virtual
Reimplemented from PHG4TrackingAction.
Definition at line 194 of file PHG4TruthTrackingAction.cc.
References VertexMap.
Referenced by PHG4TruthSubsystem::ResetEvent(), and ~PHG4TruthTrackingAction().
SetInterfacePointers()
void PHG4TruthTrackingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
Set pointers to the i/o nodes.
Reimplemented from PHG4TrackingAction.
Definition at line 182 of file PHG4TruthTrackingAction.cc.
References truthInfoList_.
Referenced by PHG4TruthSubsystem::process_event(), and ~PHG4TruthTrackingAction().
Member Data Documentation
eventAction_
PHG4TruthEventAction* PHG4TruthTrackingAction::eventAction_ private
pointer to the "owning" event action
Definition at line 38 of file PHG4TruthTrackingAction.h.
Referenced by PostUserTrackingAction().
truthInfoList_
PHG4TruthInfoContainer* PHG4TruthTrackingAction::truthInfoList_ private
pointer to truth information container
Definition at line 41 of file PHG4TruthTrackingAction.h.
Referenced by PreUserTrackingAction(), and SetInterfacePointers().
VertexMap
std::map<G4ThreeVector,int> PHG4TruthTrackingAction::VertexMap private
Definition at line 35 of file PHG4TruthTrackingAction.h.
Referenced by PreUserTrackingAction(), and ResetEvent().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4TruthTrackingAction.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4TruthTrackingAction.cc