Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/decoder_maindaq/evio.c File Reference
evio.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "evfile_msg.h"
#include "evio.h"
Macros
#define PMODE 0644
#define EVBLOCKSIZE 8192
#define EV_READ 0
#define EV_WRITE 1
#define EV_PIPE 2
#define EV_PIPEWRITE 3
#define EV_VERSION 1
#define EV_MAGIC 0xc0da0100
#define EV_HDSIZ 8
#define EV_HD_BLKSIZ 0 /* size of block in longwords */
#define EV_HD_BLKNUM 1 /* number, starting at 0 */
#define EV_HD_HDSIZ 2 /* size of header in longwords (=8) */
#define EV_HD_START 3 /* first start of event in this block */
#define EV_HD_USED 4 /* number of words used in block (<= BLKSIZ) */
#define EV_HD_VER 5 /* version of file format (=1) */
#define EV_HD_RESVD 6 /* (reserved) */
#define EV_HD_MAGIC 7 /* magic number for error detection */
#define evGetStructure() (EVFILE *)malloc(sizeof(EVFILE))
Typedefs
typedef struct evfilestruct EVFILE
typedef struct evBinarySearch EVBSEARCH
Functions
static int findLastEventWithinBlock (EVFILE *)
static int copySingleEvent (EVFILE *, int *, int, int)
static int evSearchWithinBlock (EVFILE *, EVBSEARCH *, int *, int, int *, int, int *)
static void evFindEventBlockNum (EVFILE *, EVBSEARCH *, int *)
static int evGetEventNumber (EVFILE *, int)
static int evGetEventType (EVFILE *)
static int isRealEventsInsideBlock (EVFILE *, int, int)
static int physicsEventsInsideBlock (EVFILE *)
int int_swap_byte ()
void onmemory_swap ()
int swapped_fread ()
void swapped_intcpy ()
void swapped_memcpy ()
int evopen_ (char *filename, char *flags, int *handle, int fnlen, int flen)
static char * kill_trailing (char *s, char t)
int evOpen (char *fname, char *flags, int *handle)
int evread_ (int *handle, int *buffer, int *buflen)
int evRead (int handle, int *buffer, int buflen)
int evGetNewBuffer (EVFILE *a)
int evwrite_ (int *handle, int *buffer)
int evWrite (int handle, int *buffer)
int evFlush (EVFILE *a)
int evioctl_ (int *handle, char *request, void *argp, int reqlen)
int evIoctl (int handle, char *request, void *argp)
int evclose_ (int *handle)
int evClose (int handle)
int evOpenSearch (int handle, int *b_handle)
int evSearch (int handle, int b_handle, int evn, int *buffer, int buflen, int *size)
int evCloseSearch (int b_handle)
Macro Definition Documentation
#define EV_HD_BLKNUM 1 /* number, starting at 0 */
Definition at line 122 of file evio.c.
Referenced by evFlush(), evGetNewBuffer(), evIoctl(), evOpen(), evOpenSearch(), and physicsEventsInsideBlock().
#define EV_HD_BLKSIZ 0 /* size of block in longwords */
Definition at line 121 of file evio.c.
Referenced by evFlush(), evIoctl(), and evOpen().
#define EV_HD_HDSIZ 2 /* size of header in longwords (=8) */
Definition at line 123 of file evio.c.
Referenced by evFlush(), evGetNewBuffer(), evIoctl(), and evOpen().
#define EV_HD_MAGIC 7 /* magic number for error detection */
Definition at line 128 of file evio.c.
Referenced by evFlush(), evGetNewBuffer(), evIoctl(), and evOpen().
#define EV_HD_RESVD 6 /* (reserved) */
Definition at line 127 of file evio.c.
Referenced by evFlush(), evIoctl(), and evOpen().
#define EV_HD_START 3 /* first start of event in this block */
Definition at line 124 of file evio.c.
Referenced by evFindEventBlockNum(), evFlush(), evIoctl(), evOpen(), evWrite(), and physicsEventsInsideBlock().
#define EV_HD_USED 4 /* number of words used in block (<= BLKSIZ) */
Definition at line 125 of file evio.c.
Referenced by evFindEventBlockNum(), evFlush(), evGetNewBuffer(), evIoctl(), evOpen(), and physicsEventsInsideBlock().
#define EV_HD_VER 5 /* version of file format (=1) */
Definition at line 126 of file evio.c.
Referenced by evFlush(), evIoctl(), and evOpen().
#define EV_HDSIZ 8
Definition at line 118 of file evio.c.
Referenced by copySingleEvent(), evFindEventBlockNum(), evFlush(), evGetEventNumber(), evGetEventType(), evGetNewBuffer(), evIoctl(), evOpen(), evOpenSearch(), evSearchWithinBlock(), and physicsEventsInsideBlock().
#define EV_MAGIC 0xc0da0100
Definition at line 117 of file evio.c.
Referenced by evClose(), evFlush(), evGetNewBuffer(), evIoctl(), evOpen(), evRead(), and evWrite().
#define EV_PIPE 2
Definition at line 114 of file evio.c.
Referenced by evClose(), and evOpen().
#define EV_PIPEWRITE 3
Definition at line 115 of file evio.c.
Referenced by evClose(), evIoctl(), and evOpen().
#define EV_READ 0
Definition at line 112 of file evio.c.
Referenced by evOpen().
#define EV_VERSION 1
Definition at line 116 of file evio.c.
Referenced by evFlush(), evIoctl(), and evOpen().
#define EV_WRITE 1
Definition at line 113 of file evio.c.
Referenced by evClose(), evIoctl(), and evOpen().
#define EVBLOCKSIZE 8192
Definition at line 111 of file evio.c.
Referenced by evIoctl(), and evOpen().
#define evGetStructure () (EVFILE *)malloc(sizeof(EVFILE))
Definition at line 130 of file evio.c.
Referenced by evOpen().
#define PMODE 0644
Definition at line 86 of file evio.c.
Typedef Documentation
typedef struct evBinarySearch EVBSEARCH
typedef struct evfilestruct EVFILE
Function Documentation
static int copySingleEvent (EVFILE * a, int * buffer, int buflen, int ev_size) static
Definition at line 1016 of file evio.c.
References EV_HDSIZ, S_EVFILE_TRUNC, S_SUCCESS, and swapped_memcpy().
Referenced by evSearchWithinBlock().
int evClose (int handle)
Definition at line 586 of file evio.c.
References EV_MAGIC, EV_PIPE, EV_PIPEWRITE, EV_WRITE, evFlush(), and S_EVFILE_BADHANDLE.
Referenced by CodaInputManager::CloseFile(), and evclose_().
int evclose_ (int * handle)
Definition at line 581 of file evio.c.
References evClose().
int evCloseSearch (int b_handle)
Definition at line 1096 of file evio.c.
static void evFindEventBlockNum (EVFILE * a, EVBSEARCH * b, int * bknum) static
Definition at line 923 of file evio.c.
References EV_HD_START, EV_HD_USED, EV_HDSIZ, isRealEventsInsideBlock(), and swapped_intcpy().
Referenced by evSearchWithinBlock().
int evFlush (EVFILE * a)
Definition at line 497 of file evio.c.
References EV_HD_BLKNUM, EV_HD_BLKSIZ, EV_HD_HDSIZ, EV_HD_MAGIC, EV_HD_RESVD, EV_HD_START, EV_HD_USED, EV_HD_VER, EV_HDSIZ, EV_MAGIC, EV_VERSION, and S_SUCCESS.
Referenced by evClose(), and evWrite().
static int evGetEventNumber (EVFILE * a, int ev_size) static
Definition at line 1113 of file evio.c.
References EV_HDSIZ, and int_swap_byte().
Referenced by evSearchWithinBlock().
static int evGetEventType (EVFILE * a) static
Definition at line 1136 of file evio.c.
References EV_HDSIZ, and swapped_intcpy().
Referenced by evSearchWithinBlock(), findLastEventWithinBlock(), isRealEventsInsideBlock(), and physicsEventsInsideBlock().
int evGetNewBuffer (EVFILE * a)
Definition at line 425 of file evio.c.
References EV_HD_BLKNUM, EV_HD_HDSIZ, EV_HD_MAGIC, EV_HD_USED, EV_HDSIZ, EV_MAGIC, onmemory_swap(), S_EVFILE_BADBLOCK, S_EVFILE_BADFILE, S_EVFILE_UNXPTDEOF, and S_SUCCESS.
Referenced by evRead().
int evIoctl (int handle, char * request, void * argp)
Definition at line 538 of file evio.c.
References EV_HD_BLKNUM, EV_HD_BLKSIZ, EV_HD_HDSIZ, EV_HD_MAGIC, EV_HD_RESVD, EV_HD_START, EV_HD_USED, EV_HD_VER, EV_HDSIZ, EV_MAGIC, EV_PIPEWRITE, EV_VERSION, EV_WRITE, EVBLOCKSIZE, S_EVFILE_ALLOCFAIL, S_EVFILE_BADHANDLE, S_EVFILE_BADSIZEREQ, S_EVFILE_UNKOPTION, and S_SUCCESS.
Referenced by evioctl_().
int evioctl_ (int * handle, char * request, void * argp, int reqlen)
Definition at line 526 of file evio.c.
References evIoctl().
int evOpen (char * fname, char * flags, int * handle)
Definition at line 187 of file evio.c.
References EV_HD_BLKNUM, EV_HD_BLKSIZ, EV_HD_HDSIZ, EV_HD_MAGIC, EV_HD_RESVD, EV_HD_START, EV_HD_USED, EV_HD_VER, EV_HDSIZ, EV_MAGIC, EV_PIPE, EV_PIPEWRITE, EV_READ, EV_VERSION, EV_WRITE, EVBLOCKSIZE, evGetStructure, int_swap_byte(), kill_trailing(), NULL, S_EVFILE_ALLOCFAIL, S_EVFILE_BADFILE, S_EVFILE_BADHANDLE, S_EVFILE_UNKOPTION, S_SUCCESS, and swapped_intcpy().
Referenced by evopen_(), and CodaInputManager::OpenFile().
int evopen_ (char * filename, char * flags, int * handle, int fnlen, int flen)
Definition at line 161 of file evio.c.
References evOpen().
int evOpenSearch (int handle, int * b_handle)
Definition at line 619 of file evio.c.
References EV_HD_BLKNUM, EV_HDSIZ, findLastEventWithinBlock(), int_swap_byte(), NULL, and physicsEventsInsideBlock().
int evRead (int handle, int * buffer, int buflen)
Definition at line 369 of file evio.c.
References EV_MAGIC, evGetNewBuffer(), int_swap_byte(), S_EVFILE_BADHANDLE, S_EVFILE_TRUNC, S_SUCCESS, and swapped_memcpy().
Referenced by evread_(), and CodaInputManager::NextCodaEvent().
int evread_ (int * handle, int * buffer, int * buflen)
Definition at line 364 of file evio.c.
References evRead().
int evSearch (int handle, int b_handle, int evn, int * buffer, int buflen, int * size)
Definition at line 757 of file evio.c.
References evSearchWithinBlock().
static int evSearchWithinBlock (EVFILE * a, EVBSEARCH * b, int * bknum, int evn, int * buffer, int buflen, int * size) static
Definition at line 830 of file evio.c.
References copySingleEvent(), EV_HDSIZ, evFindEventBlockNum(), evGetEventNumber(), evGetEventType(), and int_swap_byte().
Referenced by evSearch().
int evWrite (int handle, int * buffer)
Definition at line 469 of file evio.c.
References EV_HD_START, EV_MAGIC, evFlush(), S_EVFILE_BADHANDLE, and S_SUCCESS.
Referenced by evwrite_().
int evwrite_ (int * handle, int * buffer)
Definition at line 464 of file evio.c.
References evWrite().
static int findLastEventWithinBlock (EVFILE * a) static
Definition at line 689 of file evio.c.
References evGetEventType(), and int_swap_byte().
Referenced by evOpenSearch().
int int_swap_byte ()
Referenced by evGetEventNumber(), evOpen(), evOpenSearch(), evRead(), evSearchWithinBlock(), findLastEventWithinBlock(), isRealEventsInsideBlock(), and physicsEventsInsideBlock().
static int isRealEventsInsideBlock (EVFILE * a, int bknum, int old_left) static
Definition at line 980 of file evio.c.
References evGetEventType(), and int_swap_byte().
Referenced by evFindEventBlockNum().
static char* kill_trailing (char * s, char t) static
Definition at line 177 of file evio.c.
References DPGEN::s.
Referenced by evOpen().
void onmemory_swap ()
Referenced by evGetNewBuffer().
static int physicsEventsInsideBlock (EVFILE * a) static
Definition at line 1169 of file evio.c.
References EV_HD_BLKNUM, EV_HD_START, EV_HD_USED, EV_HDSIZ, evGetEventType(), int_swap_byte(), and swapped_intcpy().
Referenced by evOpenSearch().
int swapped_fread ()
void swapped_intcpy ()
Referenced by evFindEventBlockNum(), evGetEventType(), evOpen(), physicsEventsInsideBlock(), swapped_fread(), and swapped_memcpy().
void swapped_memcpy ()
Referenced by copySingleEvent(), and evRead().