Class Reference for E1039 Core & Analysis Software: NMRDataManager Class Reference
NMRDataManager Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaNMRData/NMRDataManager.h>
Public Member Functions
NMRDataManager ()
virtual ~NMRDataManager ()
void Verb (const int verb)
int Verb () const
void SetDirBase (const std::string dir_base)
void PrintKeyList (std::ostream &os=std::cout)
int GetNumEvent ()
NMREvent * GetEvent (const int index)
NMREvent * FindEvent (const int evt_num)
void ClearEvent ()
void ReadEventFile (const std::string label)
void ReadRawSignalFile (const std::string label)
void ReadPolySignalFile (const std::string label)
void ReadRawSignalFileListed ()
void ReadPolySignalFileListed ()
NMRSignal * GetRawSignal (const int evt_num)
NMRSignal * GetPolySignal (const int evt_num)
void GetRawSignalRange (double &min, double &max)
void GetPolySignalRange (double &min, double &max)
void GetScanParam (int &ScanSweeps, int &ScanSteps, double &RFFreq, double &RFMod)
Detailed Description
Definition at line 7 of file NMRDataManager.h.
Constructor & Destructor Documentation
NMRDataManager()
NMRDataManager::NMRDataManager ()
Definition at line 46 of file NMRDataManager.h.
~NMRDataManager()
virtual NMRDataManager::~NMRDataManager () inline virtual
Definition at line 21 of file NMRDataManager.h.
Member Function Documentation
ClearEvent()
void NMRDataManager::ClearEvent () inline
Definition at line 31 of file NMRDataManager.h.
FindEvent()
NMREvent * NMRDataManager::FindEvent (const int evt_num)
Definition at line 66 of file NMRDataManager.h.
References NMREvent::FindKey(), GetEvent(), and NMREvent::GetInt().
GetEvent()
NMREvent* NMRDataManager::GetEvent (const int index) inline
Definition at line 29 of file NMRDataManager.h.
Referenced by ana_NMR_event(), ana_NMR_noise(), ana_NMR_poly_signal(), ana_NMR_raw_signal(), FindEvent(), and GetScanParam().
GetNumEvent()
int NMRDataManager::GetNumEvent () inline
Definition at line 28 of file NMRDataManager.h.
Referenced by ana_NMR_event(), ana_NMR_noise(), ana_NMR_poly_signal(), ana_NMR_raw_signal(), and GetScanParam().
GetPolySignal()
NMRSignal * NMRDataManager::GetPolySignal (const int evt_num)
Definition at line 217 of file NMRDataManager.h.
References ReadPolySignalFileListed().
Referenced by ana_NMR_noise(), and ana_NMR_poly_signal().
GetPolySignalRange()
void NMRDataManager::GetPolySignalRange (double & min, double & max)
Definition at line 231 of file NMRDataManager.h.
References ReadPolySignalFileListed().
Referenced by ana_NMR_noise(), and ana_NMR_poly_signal().
GetRawSignal()
NMRSignal * NMRDataManager::GetRawSignal (const int evt_num)
Definition at line 210 of file NMRDataManager.h.
References ReadRawSignalFileListed().
Referenced by ana_NMR_raw_signal().
GetRawSignalRange()
void NMRDataManager::GetRawSignalRange (double & min, double & max)
Definition at line 224 of file NMRDataManager.h.
References ReadRawSignalFileListed().
GetScanParam()
void NMRDataManager::GetScanParam (int & ScanSweeps, int & ScanSteps, double & RFFreq, double & RFMod)
Definition at line 238 of file NMRDataManager.h.
References NMREvent::GetDouble(), GetEvent(), NMREvent::GetInt(), GetNumEvent(), and Verb().
Referenced by ana_NMR_noise(), ana_NMR_poly_signal(), and ana_NMR_raw_signal().
PrintKeyList()
void NMRDataManager::PrintKeyList (std::ostream & os = std::cout)
Definition at line 57 of file NMRDataManager.h.
References NMREvent::GetKey(), and NMREvent::GetNumKey().
Referenced by ana_NMR_event().
ReadEventFile()
void NMRDataManager::ReadEventFile (const std::string label)
Definition at line 76 of file NMRDataManager.h.
References NMREvent::AddKey(), NMREvent::AddValue(), NMREvent::GetKey(), NMREvent::GetNumKey(), NMREvent::SetLine(), and Verb().
Referenced by ana_NMR_event(), ana_NMR_noise(), ana_NMR_poly_signal(), and ana_NMR_raw_signal().
ReadPolySignalFile()
void NMRDataManager::ReadPolySignalFile (const std::string label)
Definition at line 155 of file NMRDataManager.h.
References NMRSignal::AddPoint(), NMRSignal::SetEventNum(), and Verb().
Referenced by ReadPolySignalFileListed().
ReadPolySignalFileListed()
void NMRDataManager::ReadPolySignalFileListed ()
Definition at line 198 of file NMRDataManager.h.
References ReadPolySignalFile(), and Verb().
Referenced by GetPolySignal(), and GetPolySignalRange().
ReadRawSignalFile()
void NMRDataManager::ReadRawSignalFile (const std::string label)
Definition at line 124 of file NMRDataManager.h.
References NMRSignal::AddPoint(), NMRSignal::SetEventNum(), and Verb().
Referenced by ReadRawSignalFileListed().
ReadRawSignalFileListed()
void NMRDataManager::ReadRawSignalFileListed ()
Definition at line 186 of file NMRDataManager.h.
References ReadRawSignalFile(), and Verb().
Referenced by GetRawSignal(), and GetRawSignalRange().
SetDirBase()
void NMRDataManager::SetDirBase (const std::string dir_base) inline
Definition at line 25 of file NMRDataManager.h.
Verb() [1/2]
int NMRDataManager::Verb () const inline
Definition at line 24 of file NMRDataManager.h.
Referenced by GetScanParam(), ReadEventFile(), ReadPolySignalFile(), ReadPolySignalFileListed(), ReadRawSignalFile(), and ReadRawSignalFileListed().
Verb() [2/2]
void NMRDataManager::Verb (const int verb) inline
Definition at line 23 of file NMRDataManager.h.
Referenced by ana_NMR_noise(), ana_NMR_poly_signal(), and ana_NMR_raw_signal().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaNMRData/NMRDataManager.h