Class Reference for E1039 Core & Analysis Software: PHG4BlockCellGeom Class Reference
PHG4BlockCellGeom Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockCellGeom.h>
Public Member Functions
PHG4BlockCellGeom ()
virtual ~PHG4BlockCellGeom ()
void identify (std::ostream &os=std::cout) const
int get_layer () const
int get_binning () const
int get_zbins () const
double get_zstep () const
double get_zmin () const
int get_xbins () const
double get_xstep () const
double get_xmin () const
int get_etabins () const
double get_etastep () const
double get_etamin () const
std::pair< double, double > get_zbounds (const int ibin) const
std::pair< double, double > get_etabounds (const int ibin) const
std::pair< double, double > get_xbounds (const int ibin) const
double get_etacenter (const int ibin) const
double get_zcenter (const int ibin) const
double get_xcenter (const int ibin) const
int get_etabin (const double eta) const
int get_zbin (const double z) const
int get_xbin (const double x) const
void set_layer (const int i)
void set_binning (const int i)
void set_zbins (const int i)
void set_zmin (const double z)
void set_zstep (const double z)
void set_xbins (const int i)
void set_xstep (const double x)
void set_xmin (const double x)
void set_etabins (const int i)
void set_etamin (const double z)
void set_etastep (const double z)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
void check_binning_method (const int i) const
void check_binning_method_eta (const std::string &src="") const
void check_binning_method_x (const std::string &src="") const
std::string methodname (const int i) const
Protected Attributes
int _layer
int _binning
int _nzbins
double _zmin
double _zstep
int _nxbins
double _xmin
double _xstep
Detailed Description
Definition at line 9 of file PHG4BlockCellGeom.h.
Constructor & Destructor Documentation
PHG4BlockCellGeom()
PHG4BlockCellGeom::PHG4BlockCellGeom ()
Definition at line 9 of file PHG4BlockCellGeom.cc.
~PHG4BlockCellGeom()
virtual PHG4BlockCellGeom::~PHG4BlockCellGeom () inline virtual
Definition at line 14 of file PHG4BlockCellGeom.h.
Member Function Documentation
check_binning_method()
void PHG4BlockCellGeom::check_binning_method (const int i) const protected
Definition at line 325 of file PHG4BlockCellGeom.cc.
References _binning, and methodname().
Referenced by get_zbin(), get_zbins(), get_zbounds(), get_zcenter(), get_zmin(), get_zstep(), set_zbins(), set_zmin(), and set_zstep().
check_binning_method_eta()
void PHG4BlockCellGeom::check_binning_method_eta (const std::string & src = "") const protected
Definition at line 338 of file PHG4BlockCellGeom.cc.
References _binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, and methodname().
Referenced by get_etabin(), get_etabins(), get_etabounds(), get_etacenter(), get_etamin(), get_etastep(), set_etabins(), set_etamin(), and set_etastep().
check_binning_method_x()
void PHG4BlockCellGeom::check_binning_method_x (const std::string & src = "") const protected
Definition at line 356 of file PHG4BlockCellGeom.cc.
References _binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, methodname(), and PHG4CylinderCellDefs::sizebinning.
Referenced by get_xbin(), get_xbins(), get_xcenter(), get_xmin(), get_xstep(), set_xbins(), set_xmin(), and set_xstep().
get_binning()
int PHG4BlockCellGeom::get_binning () const inline
Definition at line 18 of file PHG4BlockCellGeom.h.
References _binning.
get_etabin()
int PHG4BlockCellGeom::get_etabin (const double eta) const
Definition at line 242 of file PHG4BlockCellGeom.cc.
References _nzbins, _zmin, _zstep, and check_binning_method_eta().
Referenced by PHG4BlockCellReco::process_event().
get_etabins()
int PHG4BlockCellGeom::get_etabins () const
Definition at line 107 of file PHG4BlockCellGeom.cc.
References _nzbins, and check_binning_method_eta().
get_etabounds()
pair< double, double > PHG4BlockCellGeom::get_etabounds (const int ibin) const
Definition at line 199 of file PHG4BlockCellGeom.cc.
References _nzbins, _zmin, _zstep, and check_binning_method_eta().
get_etacenter()
double PHG4BlockCellGeom::get_etacenter (const int ibin) const
Definition at line 279 of file PHG4BlockCellGeom.cc.
References _nzbins, _zmin, _zstep, and check_binning_method_eta().
Referenced by PHG4BlockCellReco::process_event().
get_etamin()
double PHG4BlockCellGeom::get_etamin () const
Definition at line 120 of file PHG4BlockCellGeom.cc.
References _zmin, and check_binning_method_eta().
get_etastep()
double PHG4BlockCellGeom::get_etastep () const
Definition at line 114 of file PHG4BlockCellGeom.cc.
References _zstep, and check_binning_method_eta().
Referenced by PHG4BlockCellReco::process_event().
get_layer()
int PHG4BlockCellGeom::get_layer () const inline
Definition at line 17 of file PHG4BlockCellGeom.h.
References _layer.
Referenced by PHG4BlockCellGeomContainer::AddLayerCellGeom().
get_xbin()
int PHG4BlockCellGeom::get_xbin (const double x) const
Definition at line 254 of file PHG4BlockCellGeom.cc.
References _nxbins, _xmin, _xstep, and check_binning_method_x().
Referenced by PHG4BlockCellReco::process_event().
get_xbins()
int PHG4BlockCellGeom::get_xbins () const
Definition at line 65 of file PHG4BlockCellGeom.cc.
References _nxbins, and check_binning_method_x().
get_xbounds()
pair< double, double > PHG4BlockCellGeom::get_xbounds (const int ibin) const
Definition at line 215 of file PHG4BlockCellGeom.cc.
References _nxbins, _xmin, and _xstep.
get_xcenter()
double PHG4BlockCellGeom::get_xcenter (const int ibin) const
Definition at line 292 of file PHG4BlockCellGeom.cc.
References _nxbins, _xmin, _xstep, and check_binning_method_x().
Referenced by PHG4BlockCellReco::process_event().
get_xmin()
double PHG4BlockCellGeom::get_xmin () const
Definition at line 79 of file PHG4BlockCellGeom.cc.
References _xmin, and check_binning_method_x().
get_xstep()
double PHG4BlockCellGeom::get_xstep () const
Definition at line 72 of file PHG4BlockCellGeom.cc.
References _xstep, and check_binning_method_x().
Referenced by PHG4BlockCellReco::process_event().
get_zbin()
int PHG4BlockCellGeom::get_zbin (const double z) const
Definition at line 229 of file PHG4BlockCellGeom.cc.
References _nzbins, _zmin, _zstep, check_binning_method(), and PHG4CylinderCellDefs::sizebinning.
get_zbins()
int PHG4BlockCellGeom::get_zbins () const
Definition at line 37 of file PHG4BlockCellGeom.cc.
References _nzbins, check_binning_method(), and PHG4CylinderCellDefs::sizebinning.
get_zbounds()
pair< double, double > PHG4BlockCellGeom::get_zbounds (const int ibin) const
Definition at line 185 of file PHG4BlockCellGeom.cc.
References _nzbins, _zmin, _zstep, check_binning_method(), and PHG4CylinderCellDefs::sizebinning.
get_zcenter()
double PHG4BlockCellGeom::get_zcenter (const int ibin) const
Definition at line 267 of file PHG4BlockCellGeom.cc.
References _nzbins, _zmin, _zstep, check_binning_method(), and PHG4CylinderCellDefs::sizebinning.
get_zmin()
double PHG4BlockCellGeom::get_zmin () const
Definition at line 44 of file PHG4BlockCellGeom.cc.
References _zmin, check_binning_method(), and PHG4CylinderCellDefs::sizebinning.
get_zstep()
double PHG4BlockCellGeom::get_zstep () const
Definition at line 51 of file PHG4BlockCellGeom.cc.
References _zstep, check_binning_method(), and PHG4CylinderCellDefs::sizebinning.
identify()
void PHG4BlockCellGeom::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 148 of file PHG4BlockCellGeom.cc.
References _binning, _layer, _nxbins, _nzbins, _xmin, _xstep, _zmin, _zstep, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, and PHG4CylinderCellDefs::sizebinning.
Referenced by PHG4BlockCellReco::InitRun().
methodname()
string PHG4BlockCellGeom::methodname (const int i) const protected
Definition at line 305 of file PHG4BlockCellGeom.cc.
References PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, and PHG4CylinderCellDefs::sizebinning.
Referenced by check_binning_method(), check_binning_method_eta(), and check_binning_method_x().
set_binning()
void PHG4BlockCellGeom::set_binning (const int i) inline
Definition at line 45 of file PHG4BlockCellGeom.h.
References _binning.
Referenced by PHG4BlockCellReco::InitRun().
set_etabins()
void PHG4BlockCellGeom::set_etabins (const int i)
Definition at line 141 of file PHG4BlockCellGeom.cc.
References _nzbins, and check_binning_method_eta().
Referenced by PHG4BlockCellReco::InitRun().
set_etamin()
void PHG4BlockCellGeom::set_etamin (const double z)
Definition at line 127 of file PHG4BlockCellGeom.cc.
References _zmin, and check_binning_method_eta().
Referenced by PHG4BlockCellReco::InitRun().
set_etastep()
void PHG4BlockCellGeom::set_etastep (const double z)
Definition at line 134 of file PHG4BlockCellGeom.cc.
References _zstep, and check_binning_method_eta().
Referenced by PHG4BlockCellReco::InitRun().
set_layer()
void PHG4BlockCellGeom::set_layer (const int i) inline
Definition at line 44 of file PHG4BlockCellGeom.h.
References _layer.
Referenced by PHG4BlockCellGeomContainer::AddLayerCellGeom(), and PHG4BlockCellReco::InitRun().
set_xbins()
void PHG4BlockCellGeom::set_xbins (const int i)
Definition at line 86 of file PHG4BlockCellGeom.cc.
References _nxbins, and check_binning_method_x().
Referenced by PHG4BlockCellReco::InitRun().
set_xmin()
void PHG4BlockCellGeom::set_xmin (const double x)
Definition at line 100 of file PHG4BlockCellGeom.cc.
References _xmin, and check_binning_method_x().
Referenced by PHG4BlockCellReco::InitRun().
set_xstep()
void PHG4BlockCellGeom::set_xstep (const double x)
Definition at line 93 of file PHG4BlockCellGeom.cc.
References _xstep, and check_binning_method_x().
Referenced by PHG4BlockCellReco::InitRun().
set_zbins()
void PHG4BlockCellGeom::set_zbins (const int i)
Definition at line 23 of file PHG4BlockCellGeom.cc.
References _nzbins, check_binning_method(), and PHG4CylinderCellDefs::sizebinning.
set_zmin()
void PHG4BlockCellGeom::set_zmin (const double z)
Definition at line 30 of file PHG4BlockCellGeom.cc.
References _zmin, check_binning_method(), and PHG4CylinderCellDefs::sizebinning.
set_zstep()
void PHG4BlockCellGeom::set_zstep (const double z)
Definition at line 58 of file PHG4BlockCellGeom.cc.
References _zstep, check_binning_method(), and PHG4CylinderCellDefs::sizebinning.
Member Data Documentation
_binning
int PHG4BlockCellGeom::_binning protected
Definition at line 66 of file PHG4BlockCellGeom.h.
Referenced by check_binning_method(), check_binning_method_eta(), check_binning_method_x(), get_binning(), identify(), and set_binning().
_layer
int PHG4BlockCellGeom::_layer protected
Definition at line 65 of file PHG4BlockCellGeom.h.
Referenced by get_layer(), identify(), and set_layer().
_nxbins
int PHG4BlockCellGeom::_nxbins protected
Definition at line 72 of file PHG4BlockCellGeom.h.
Referenced by get_xbin(), get_xbins(), get_xbounds(), get_xcenter(), identify(), and set_xbins().
_nzbins
int PHG4BlockCellGeom::_nzbins protected
Definition at line 68 of file PHG4BlockCellGeom.h.
Referenced by get_etabin(), get_etabins(), get_etabounds(), get_etacenter(), get_zbin(), get_zbins(), get_zbounds(), get_zcenter(), identify(), set_etabins(), and set_zbins().
_xmin
double PHG4BlockCellGeom::_xmin protected
Definition at line 73 of file PHG4BlockCellGeom.h.
Referenced by get_xbin(), get_xbounds(), get_xcenter(), get_xmin(), identify(), and set_xmin().
_xstep
double PHG4BlockCellGeom::_xstep protected
Definition at line 74 of file PHG4BlockCellGeom.h.
Referenced by get_xbin(), get_xbounds(), get_xcenter(), get_xstep(), identify(), and set_xstep().
_zmin
double PHG4BlockCellGeom::_zmin protected
Definition at line 69 of file PHG4BlockCellGeom.h.
Referenced by get_etabin(), get_etabounds(), get_etacenter(), get_etamin(), get_zbin(), get_zbounds(), get_zcenter(), get_zmin(), identify(), set_etamin(), and set_zmin().
_zstep
double PHG4BlockCellGeom::_zstep protected
Definition at line 70 of file PHG4BlockCellGeom.h.
Referenced by get_etabin(), get_etabounds(), get_etacenter(), get_etastep(), get_zbin(), get_zbounds(), get_zcenter(), get_zstep(), identify(), set_etastep(), and set_zstep().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockCellGeom.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockCellGeom.cc