Class Reference for E1039 Core & Analysis Software: CalibParamXT Class Reference
CalibParamXT Class Reference
Calibration parameter for chamber X-T relation.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/CalibParamXT.h>
Public Member Functions
CalibParamXT ()
virtual ~CalibParamXT ()
void Add (const std::string det, const double t, const double x, const double dt, const double dx)
void Add (const std::string det_name, const short det_id, const double t, const double x, const double dt, const double dx)
bool Find (const short det, TGraphErrors *&gr_t2x, TGraphErrors *&gr_t2dx)
To be obsolete. Use FindT2X().
bool FindT2X (const short det, TGraphErrors *&gr_t2x, TGraphErrors *&gr_t2dx)
bool FindX2T (const short det, TGraphErrors *&gr_x2t, TGraphErrors *&gr_x2dt)
void Print (std::ostream &os)
Public Member Functions inherited from CalibParamBase
CalibParamBase (const std::string label, const std::string header)
virtual ~CalibParamBase ()
Public Member Functions inherited from RunParamBase
RunParamBase (const std::string type, const std::string label, const std::string header)
virtual ~RunParamBase ()
void SetBaseDir (const std::string dir_base)
std::string GetBaseDir ()
std::string GetParamID ()
std::string GetMapID ()
void SetMapID (const std::string map_id)
void SetMapIDbyFile (const std::string map_id)
void SetMapIDbyDB (const std::string map_id)
void SetMapIDbyFile (const int run)
void SetMapIDbyDB (const int run)
void ReadFromFile ()
void WriteToFile ()
void ReadFromLocalFile (const std::string fn_tsv)
void WriteToLocalFile (const std::string fn_tsv)
void ReadFromDB ()
void WriteToDB ()
void WriteRangeToDB ()
Protected Member Functions
int ReadFileCont (LineList &lines)
int WriteFileCont (std::ostream &os)
void ReadDbTable (DbSvc &db)
void WriteDbTable (DbSvc &db)
Protected Member Functions inherited from RunParamBase
std::string RangeFileName ()
std::string MapFileName ()
std::string SchemaName ()
std::string MapTableName ()
Additional Inherited Members
Protected Types inherited from RunParamBase
typedef std::vector< std::string > LineList
Detailed Description
Calibration parameter for chamber X-T relation.
The present parameter set doesn't include "dt". Therefore "dt" is set to "dx * t / x" in this class temporarily. The next parameter set must include "dt".
Definition at line 12 of file CalibParamXT.h.
Constructor & Destructor Documentation
CalibParamXT::CalibParamXT ()
Definition at line 14 of file CalibParamXT.cc.
CalibParamXT::~CalibParamXT () virtual
Definition at line 20 of file CalibParamXT.cc.
Member Function Documentation
void CalibParamXT::Add (const std::string det, const double t, const double x, const double dt, const double dx)
The X-T curve of the prop tubes is given per plane pair in the TSV file (at present), namely P1H, P1V, P2V and P2H. Since CalibParamXT needs one X-T curve per plane, two X-T curves are being made from one input (ex. P1H1f & P1H1b from P1H). In the future, the X-T curve is expected to be given per plane, like the drift chamber.
Definition at line 95 of file CalibParamXT.cc.
References GeomSvc::getDetectorID(), GeomSvc::instance(), and GeomSvc::toLocalDetectorName().
Referenced by ReadDbTable(), and ReadFileCont().
void CalibParamXT::Add (const std::string det_name, const short det_id, const double t, const double x, const double dt, const double dx)
Definition at line 125 of file CalibParamXT.cc.
bool CalibParamXT::Find (const short det, TGraphErrors *& gr_t2x, TGraphErrors *& gr_t2dx)
To be obsolete. Use FindT2X().
Definition at line 162 of file CalibParamXT.cc.
References FindT2X().
Referenced by CalibDriftDist::process_event(), and CalibXTv2::process_event().
bool CalibParamXT::FindT2X (const short det, TGraphErrors *& gr_t2x, TGraphErrors *& gr_t2dx)
Definition at line 167 of file CalibParamXT.cc.
Referenced by Find().
bool CalibParamXT::FindX2T (const short det, TGraphErrors *& gr_x2t, TGraphErrors *& gr_x2dt)
Definition at line 178 of file CalibParamXT.cc.
Referenced by SQChamberRealization::process_event().
void CalibParamXT::Print (std::ostream & os) virtual
Reimplemented from RunParamBase.
Definition at line 189 of file CalibParamXT.cc.
void CalibParamXT::ReadDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 55 of file CalibParamXT.cc.
References Add(), RunParamBase::MapTableName(), and DbSvc::Process().
int CalibParamXT::ReadFileCont (LineList & lines) protected virtual
Reimplemented from RunParamBase.
Definition at line 28 of file CalibParamXT.cc.
References Add().
void CalibParamXT::WriteDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 72 of file CalibParamXT.cc.
References DbSvc::Con(), DbSvc::CreateTable(), and RunParamBase::MapTableName().
int CalibParamXT::WriteFileCont (std::ostream & os) protected virtual
Reimplemented from RunParamBase.
Definition at line 44 of file CalibParamXT.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/CalibParamXT.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/geom_svc/CalibParamXT.cc