SeaQuest Offline Software: PHG4SiliconTrackerSteppingAction Class Reference
PHG4SiliconTrackerSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerSteppingAction.h>
Public Member Functions
PHG4SiliconTrackerSteppingAction (PHG4SiliconTrackerDetector *, const PHG4ParametersContainer *parameters)
virtual ~PHG4SiliconTrackerSteppingAction ()
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action. This defines processing of a single step in a given volume
virtual void SetInterfacePointers (PHCompositeNode *)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4SiliconTrackerDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4Hit * hit
PHG4HitContainer * savehitcontainer
PHG4Shower * saveshower
const PHG4ParametersContainer * paramscontainer
double strip_y [4]
double strip_z [4][2]
int nstrips_z_sensor [4][2]
int nstrips_phi_cell [4]
std::map< int, int > IsActive
std::map< int, int > IsBlackHole
std::map< std::string, int > AbsorberIndex
std::set< std::string > missingabsorbers
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 12 of file PHG4SiliconTrackerSteppingAction.h.
Constructor & Destructor Documentation
PHG4SiliconTrackerSteppingAction::PHG4SiliconTrackerSteppingAction (PHG4SiliconTrackerDetector * detector, const PHG4ParametersContainer * parameters)
Definition at line 46 of file PHG4SiliconTrackerSteppingAction.cc.
References AbsorberIndex, PHG4Parameters::get_double_param(), PHG4Parameters::get_int_param(), PHG4ParametersContainer::GetAllParameters(), IsActive, IsBlackHole, nstrips_phi_cell, nstrips_z_sensor, paramscontainer, strip_y, and strip_z.
PHG4SiliconTrackerSteppingAction::~PHG4SiliconTrackerSteppingAction () virtual
Definition at line 81 of file PHG4SiliconTrackerSteppingAction.cc.
References hit, and missingabsorbers.
Member Function Documentation
void PHG4SiliconTrackerSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
Reimplemented from PHG4SteppingAction.
Definition at line 526 of file PHG4SiliconTrackerSteppingAction.cc.
References absorberhits_, detector_, PHG4Detector::GetName(), hits_, PHG4SiliconTrackerDetector::SuperDetector(), and PHG4SteppingAction::verbosity.
bool PHG4SiliconTrackerSteppingAction::UserSteppingAction (const G4Step * step, bool was_used) virtual
stepping action. This defines processing of a single step in a given volume
returns true if hits associated to this step was processed by this detector
Parameters
step pointer to the geant 4 step class
was_used true if the hit was already used by a previously registered subsystem
Implements PHG4SteppingAction.
Definition at line 95 of file PHG4SiliconTrackerSteppingAction.cc.
References absorberhits_, AbsorberIndex, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), hit, hits_, IsActive, IsBlackHole, PHG4SiliconTrackerDetector::IsInSiliconTracker(), missingabsorbers, nstrips_phi_cell, nstrips_z_sensor, PHG4Hit::print(), PHG4Hit::Reset(), savehitcontainer, saveshower, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_ladder_phi_index(), PHG4Hit::set_ladder_z_index(), PHG4Hit::set_layer(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_strip_y_index(), PHG4Hit::set_strip_z_index(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), strip_y, strip_z, and PHG4SteppingAction::verbosity.
Member Data Documentation
PHG4HitContainer* PHG4SiliconTrackerSteppingAction::absorberhits_ private
Definition at line 29 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::map<std::string, int> PHG4SiliconTrackerSteppingAction::AbsorberIndex private
Definition at line 41 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by PHG4SiliconTrackerSteppingAction(), and UserSteppingAction().
PHG4SiliconTrackerDetector* PHG4SiliconTrackerSteppingAction::detector_ private
pointer to the detector
Definition at line 25 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4SiliconTrackerSteppingAction::hit private
Definition at line 30 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4SiliconTrackerSteppingAction().
PHG4HitContainer* PHG4SiliconTrackerSteppingAction::hits_ private
pointer to hit container
Definition at line 28 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
std::map<int, int> PHG4SiliconTrackerSteppingAction::IsActive private
Definition at line 39 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by PHG4SiliconTrackerSteppingAction(), and UserSteppingAction().
std::map<int, int> PHG4SiliconTrackerSteppingAction::IsBlackHole private
Definition at line 40 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by PHG4SiliconTrackerSteppingAction(), and UserSteppingAction().
std::set<std::string> PHG4SiliconTrackerSteppingAction::missingabsorbers private
Definition at line 42 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4SiliconTrackerSteppingAction().
int PHG4SiliconTrackerSteppingAction::nstrips_phi_cell[4] private
Definition at line 38 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by PHG4SiliconTrackerSteppingAction(), and UserSteppingAction().
int PHG4SiliconTrackerSteppingAction::nstrips_z_sensor[4][2] private
Definition at line 37 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by PHG4SiliconTrackerSteppingAction(), and UserSteppingAction().
const PHG4ParametersContainer* PHG4SiliconTrackerSteppingAction::paramscontainer private
Definition at line 33 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by PHG4SiliconTrackerSteppingAction().
PHG4HitContainer* PHG4SiliconTrackerSteppingAction::savehitcontainer private
Definition at line 31 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4SiliconTrackerSteppingAction::saveshower private
Definition at line 32 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by UserSteppingAction().
double PHG4SiliconTrackerSteppingAction::strip_y[4] private
Definition at line 35 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by PHG4SiliconTrackerSteppingAction(), and UserSteppingAction().
double PHG4SiliconTrackerSteppingAction::strip_z[4][2] private
Definition at line 36 of file PHG4SiliconTrackerSteppingAction.h.
Referenced by PHG4SiliconTrackerSteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerSteppingAction.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SiliconTrackerSteppingAction.cc