Class Reference for E1039 Core & Analysis Software: SQChamberRealization Class Reference
SQChamberRealization Class Reference
SubsysReco module to do the detector realization for chamber and prop tube.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/SQChamberRealization.h>
Public Member Functions
SQChamberRealization (const std::string &name="SQChamberRealization")
virtual ~SQChamberRealization ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetChamEff (const double eff_d0, const double eff_d1, const double eff_d2, const double eff_d3p, const double eff_d3m)
Set the single-plane efficiency of the chamber planes.
void SetPropTubeEff (const double eff_p1x, const double eff_p1y, const double eff_p2x, const double eff_p2y)
Set the single-plane efficiency of the prop-tube planes.
void ScaleChamReso (const double scale_d0, const double scale_d1, const double scale_d2, const double scale_d3p, const double scale_d3m)
Set the scaling factor of the single-plane resolution of the chamber planes.
void FixChamReso (const double reso_d0, const double reso_d1, const double reso_d2, const double reso_d3p, const double reso_d3m)
Set the single-plane resolution of the chamber planes to the given values.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
SubsysReco module to do the detector realization for chamber and prop tube.
This module simulates the detection efficiency and the time/distance resolution.
When it regards a hit as inefficient, it erases the hit from SQHitVector. The efficiency should be set via SetChamEff() and SetPropTubeEff().
It smears the drift distance of a hit using dx of the X-T curve by default. The resolution (dx) can be changed via ScaleChamReso() and FixChamReso(). It sets the TDC time based on the smeared drift distance and the X-T curve.
Definition at line 20 of file SQChamberRealization.h.
Constructor & Destructor Documentation
SQChamberRealization()
SQChamberRealization::SQChamberRealization (const std::string & name = "SQChamberRealization")
Definition at line 17 of file SQChamberRealization.cc.
~SQChamberRealization()
SQChamberRealization::~SQChamberRealization () virtual
Definition at line 26 of file SQChamberRealization.cc.
Member Function Documentation
End()
int SQChamberRealization::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 116 of file SQChamberRealization.cc.
References Fun4AllReturnCodes::EVENT_OK.
FixChamReso()
void SQChamberRealization::FixChamReso (const double reso_d0, const double reso_d1, const double reso_d2, const double reso_d3p, const double reso_d3m)
Set the single-plane resolution of the chamber planes to the given values.
Definition at line 180 of file SQChamberRealization.cc.
References GeomSvc::getDetectorName(), GeomSvc::instance(), nChamberPlanes, and Fun4AllBase::Verbosity().
Init()
int SQChamberRealization::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 31 of file SQChamberRealization.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRun()
int SQChamberRealization::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 36 of file SQChamberRealization.cc.
References Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, PHFlag::get_IntFlag(), RunParamBase::GetMapID(), recoConsts::instance(), Fun4AllBase::Name(), RunParamBase::ReadFromDB(), recoConsts::set_CharFlag(), and RunParamBase::SetMapIDbyDB().
process_event()
int SQChamberRealization::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 61 of file SQChamberRealization.cc.
References SQHitVector::begin(), SQHitVector::end(), SQHitVector::erase(), Fun4AllReturnCodes::EVENT_OK, SQHit::get_detector_id(), SQHit::get_drift_distance(), SQHit::get_element_id(), GeomSvc::getDetectorName(), CalibParamXT::GetParam(), GeomSvc::instance(), PHWHERE, SQHit::set_drift_distance(), SQHit::set_tdc_time(), SQHitVector::size(), Fun4AllBase::Verbosity(), CalibParamXT::Set::X0, CalibParamXT::Set::X1, CalibParamXT::Set::x2dx, and CalibParamXT::Set::x2t.
ScaleChamReso()
void SQChamberRealization::ScaleChamReso (const double scale_d0, const double scale_d1, const double scale_d2, const double scale_d3p, const double scale_d3m)
Set the scaling factor of the single-plane resolution of the chamber planes.
Definition at line 160 of file SQChamberRealization.cc.
References GeomSvc::getDetectorName(), GeomSvc::instance(), nChamberPlanes, and Fun4AllBase::Verbosity().
SetChamEff()
void SQChamberRealization::SetChamEff (const double eff_d0, const double eff_d1, const double eff_d2, const double eff_d3p, const double eff_d3m)
Set the single-plane efficiency of the chamber planes.
Definition at line 121 of file SQChamberRealization.cc.
References GeomSvc::getDetectorName(), GeomSvc::instance(), nChamberPlanes, and Fun4AllBase::Verbosity().
SetPropTubeEff()
void SQChamberRealization::SetPropTubeEff (const double eff_p1x, const double eff_p1y, const double eff_p2x, const double eff_p2y)
Set the single-plane efficiency of the prop-tube planes.
Definition at line 141 of file SQChamberRealization.cc.
References GeomSvc::getDetectorName(), GeomSvc::instance(), nChamberPlanes, nHodoPlanes, nPropPlanes, and Fun4AllBase::Verbosity().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/SQChamberRealization.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/SQChamberRealization.cc