E1039 Software: PHTimer Class Reference
PHTimer Class Reference
high precision timer
#include </home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHTimer.h>
Classes
class Frequency
internal frequency read from cpu information file
struct time_struct
used to store high precision time using two integers
Public Types
enum State { STOP =0, RUN =1 }
enum for timer state
Public Member Functions
State get_state (void) const
access timer state
PHTimer (const std::string &name="Generic Timer")
Construct with a name.
void reset ()
void stop ()
stops the counter
void restart ()
Restart timer.
void print (std::ostream &os=std::cout) const
Dump elapsed time to provided ostream.
void print_stat (std::ostream &os=std::cout) const
Dump statistics.
void set_name (const std::string &name)
Set timer name.
std::string get_name (void) const
get timer name
double get_accumulated_time (void) const
get cumulated time
unsigned int get_ncycle (void) const
get number of cycles
double get_time_per_cycle (void) const
get averaged time/cycle
double elapsed (void) const
retrieve elapsed value since last restart (in ms)
void test (double time, std::ostream &os=std::cout)
test PHTimer for a given amount of time (in ms)
Static Public Member Functions
static void PRINT (std::ostream &os=std::cout, const std::string &message="")
print a message (formated) to a stream
Static Private Member Functions
static time_struct get_clock_counts (void)
gets time from cpu clock counts
static double get_difference (const time_struct &, const time_struct &)
returns difference between to time
Private Attributes
std::string _name
timer name
State _state
timer state
time_struct _start_time
start time structure
time_struct _stop_time
stop time structure
double _accumulated_time
cumulated time
unsigned int _ncycle
number of restart/stop cycles
Static Private Attributes
static Frequency _frequency = PHTimer::Frequency()
static frequency object
static const double _twopower32 = pow(2,32)
to stores 2^32
Detailed Description
high precision timer
high precision timer
Definition at line 24 of file PHTimer.h.
Member Enumeration Documentation
State
enum PHTimer::State
enum for timer state
Enumerator
STOP
RUN
Definition at line 29 of file PHTimer.h.
Constructor & Destructor Documentation
PHTimer()
PHTimer::PHTimer (const std::string & name = "Generic Timer") inline
Construct with a name.
Definition at line 40 of file PHTimer.h.
References PHTimer::time_struct::_low, and _stop_time.
Member Function Documentation
elapsed()
double PHTimer::elapsed (void) const inline
retrieve elapsed value since last restart (in ms)
Definition at line 116 of file PHTimer.h.
References _start_time, _state, _stop_time, get_clock_counts(), get_difference(), and RUN.
Referenced by print(), and stop().
get_accumulated_time()
double PHTimer::get_accumulated_time (void) const inline
get cumulated time
Definition at line 104 of file PHTimer.h.
References _accumulated_time.
get_clock_counts()
static time_struct PHTimer::get_clock_counts (void) inline static private
gets time from cpu clock counts
Definition at line 191 of file PHTimer.h.
References PHTimer::time_struct::_high, PHTimer::time_struct::_low, get_difference(), and rdtsc.
Referenced by elapsed(), reset(), restart(), and stop().
get_difference()
double PHTimer::get_difference (const time_struct & t0, const time_struct & t1) static private
returns difference between to time
Definition at line 62 of file PHTimer.cc.
References PHTimer::Frequency::_frequency, PHTimer::time_struct::_high, PHTimer::time_struct::_low, and _twopower32.
Referenced by elapsed(), and get_clock_counts().
get_name()
std::string PHTimer::get_name (void) const inline
get timer name
Definition at line 100 of file PHTimer.h.
References _name.
get_ncycle()
unsigned int PHTimer::get_ncycle (void) const inline
get number of cycles
Definition at line 108 of file PHTimer.h.
References _ncycle.
get_state()
State PHTimer::get_state (void) const inline
access timer state
Definition at line 36 of file PHTimer.h.
References _state.
get_time_per_cycle()
double PHTimer::get_time_per_cycle (void) const inline
get averaged time/cycle
Definition at line 112 of file PHTimer.h.
References _accumulated_time, and _ncycle.
print()
void PHTimer::print (std::ostream & os = std::cout) const inline
Dump elapsed time to provided ostream.
Definition at line 73 of file PHTimer.h.
References _name, elapsed(), and PRINT().
Referenced by test().
PRINT()
void PHTimer::PRINT (std::ostream & os = std::cout, const std::string & message = "") static
print a message (formated) to a stream
Definition at line 75 of file PHTimer.cc.
Referenced by print(), PHTimeServer::print(), print_stat(), PHTimeServer::print_stat(), and test().
print_stat()
void PHTimer::print_stat (std::ostream & os = std::cout) const inline
Dump statistics.
Definition at line 82 of file PHTimer.h.
References _accumulated_time, _name, _ncycle, and PRINT().
reset()
void PHTimer::reset () inline
Definition at line 51 of file PHTimer.h.
References _accumulated_time, PHTimer::time_struct::_low, _ncycle, _start_time, _state, _stop_time, get_clock_counts(), and STOP.
restart()
void PHTimer::restart () inline
Restart timer.
Definition at line 70 of file PHTimer.h.
References _start_time, _state, get_clock_counts(), and RUN.
Referenced by PHG4PhenixEventAction::BeginOfEventAction(), PHG4BlockCellReco::process_event(), PHG4CylinderCellReco::process_event(), PHG4CylinderCellTPCReco::process_event(), PHG4Reco::process_event(), and test().
set_name()
void PHTimer::set_name (const std::string & name) inline
Set timer name.
Definition at line 96 of file PHTimer.h.
References _name.
stop()
void PHTimer::stop () inline
stops the counter
Definition at line 61 of file PHTimer.h.
References _accumulated_time, _ncycle, _state, _stop_time, elapsed(), get_clock_counts(), and STOP.
Referenced by PHG4PhenixEventAction::EndOfEventAction(), PHG4BlockCellReco::process_event(), PHG4CylinderCellReco::process_event(), PHG4CylinderCellTPCReco::process_event(), and PHG4Reco::process_event().
test()
void PHTimer::test (double time, std::ostream & os = std::cout) inline
test PHTimer for a given amount of time (in ms)
Definition at line 124 of file PHTimer.h.
References _name, print(), PRINT(), and restart().
Member Data Documentation
_accumulated_time
double PHTimer::_accumulated_time private
cumulated time
Definition at line 221 of file PHTimer.h.
Referenced by get_accumulated_time(), get_time_per_cycle(), print_stat(), reset(), and stop().
_frequency
PHTimer::Frequency PHTimer::_frequency = PHTimer::Frequency() static private
static frequency object
Definition at line 203 of file PHTimer.h.
_name
std::string PHTimer::_name private
timer name
Definition at line 209 of file PHTimer.h.
Referenced by get_name(), print(), print_stat(), set_name(), and test().
_ncycle
unsigned int PHTimer::_ncycle private
number of restart/stop cycles
Definition at line 224 of file PHTimer.h.
Referenced by get_ncycle(), get_time_per_cycle(), print_stat(), reset(), and stop().
_start_time
time_struct PHTimer::_start_time private
start time structure
Definition at line 215 of file PHTimer.h.
Referenced by elapsed(), reset(), and restart().
_state
State PHTimer::_state private
timer state
Definition at line 212 of file PHTimer.h.
Referenced by elapsed(), get_state(), reset(), restart(), and stop().
_stop_time
time_struct PHTimer::_stop_time private
stop time structure
Definition at line 218 of file PHTimer.h.
Referenced by elapsed(), PHTimer(), reset(), and stop().
_twopower32
const double PHTimer::_twopower32 = pow(2,32) static private
to stores 2^32
Definition at line 206 of file PHTimer.h.
Referenced by get_difference().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHTimer.h
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/phool/PHTimer.cc