E1039 Software: TestSimAnalyzer Class Reference
TestSimAnalyzer Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/module_example/TestSimAnalyzer.h>
Public Member Functions
TestSimAnalyzer (const std::string &name="TestSimAnalyzer")
virtual ~TestSimAnalyzer ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int InitEvalTree ()
int ResetEvalVars ()
const std::string & get_hit_container_choice () const
void set_hit_container_choice (const std::string &hitContainerChoice)
const std::string & get_out_name () const
void set_out_name (const std::string &outName)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
Private Attributes
std::string _hit_container_type
size_t _event
SQRun * _run_header
SQSpillMap * _spill_map
SQEvent * _event_header
SQHitMap * _hit_map
SQHitVector * _hit_vector
PHG4TruthInfoContainer * _truth
std::string _out_name
TTree * _tout
int _b_run_id
int _b_spill_id
float _b_target_pos
int _b_event_id
int _b_n_hits
int _b_hit_id [10000]
int _b_detector_id [10000]
float _b_drift_distance [10000]
float _b_pos [10000]
float _b_detector_z [10000]
float _b_truth_x [10000]
float _b_truth_y [10000]
float _b_truth_z [10000]
float _b_truth_pos [10000]
GeomSvc * p_geomSvc
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 41 of file TestSimAnalyzer.h.
Constructor & Destructor Documentation
TestSimAnalyzer()
TestSimAnalyzer::TestSimAnalyzer (const std::string & name = "TestSimAnalyzer")
Definition at line 48 of file TestSimAnalyzer.cxx.
~TestSimAnalyzer()
virtual TestSimAnalyzer::~TestSimAnalyzer () inline virtual
Definition at line 46 of file TestSimAnalyzer.h.
References End(), Init(), InitEvalTree(), InitRun(), process_event(), and ResetEvalVars().
Member Function Documentation
End()
int TestSimAnalyzer::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 141 of file TestSimAnalyzer.cxx.
References _out_name, _tout, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by ~TestSimAnalyzer().
get_hit_container_choice()
const std::string& TestSimAnalyzer::get_hit_container_choice () const inline
Definition at line 57 of file TestSimAnalyzer.h.
References _hit_container_type.
get_out_name()
const std::string& TestSimAnalyzer::get_out_name () const inline
Definition at line 65 of file TestSimAnalyzer.h.
References _out_name.
GetNodes()
int TestSimAnalyzer::GetNodes (PHCompositeNode * topNode) private
Definition at line 194 of file TestSimAnalyzer.cxx.
References _event_header, _hit_container_type, _hit_map, _hit_vector, _run_header, _spill_map, _truth, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and LogError.
Referenced by InitRun(), and set_out_name().
Init()
int TestSimAnalyzer::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 61 of file TestSimAnalyzer.cxx.
References Fun4AllReturnCodes::EVENT_OK.
Referenced by ~TestSimAnalyzer().
InitEvalTree()
int TestSimAnalyzer::InitEvalTree ()
Definition at line 151 of file TestSimAnalyzer.cxx.
References _b_detector_id, _b_detector_z, _b_drift_distance, _b_event_id, _b_hit_id, _b_n_hits, _b_pos, _b_run_id, _b_spill_id, _b_target_pos, _b_truth_pos, _b_truth_x, _b_truth_y, _b_truth_z, _out_name, _tout, PHTFileServer::get(), and PHTFileServer::open().
Referenced by InitRun(), and ~TestSimAnalyzer().
InitRun()
int TestSimAnalyzer::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 65 of file TestSimAnalyzer.cxx.
References Fun4AllReturnCodes::EVENT_OK, GetNodes(), InitEvalTree(), GeomSvc::instance(), p_geomSvc, and ResetEvalVars().
Referenced by ~TestSimAnalyzer().
process_event()
int TestSimAnalyzer::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 78 of file TestSimAnalyzer.cxx.
References _b_detector_id, _b_detector_z, _b_drift_distance, _b_event_id, _b_hit_id, _b_n_hits, _b_pos, _b_run_id, _b_spill_id, _b_target_pos, _b_truth_pos, _b_truth_x, _b_truth_y, _b_truth_z, _event, _event_header, _hit_vector, _spill_map, _tout, _truth, SQHitVector::begin(), SQHitVector::end(), Fun4AllReturnCodes::EVENT_OK, SQSpillMap::get(), SQHit::get_detector_id(), SQEvent::get_event_id(), SQEvent::get_run_id(), SQEvent::get_spill_id(), GeomSvc::getCostheta(), GeomSvc::getPlanePosition(), GeomSvc::getSintheta(), LogWarning, p_geomSvc, ResetEvalVars(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by ~TestSimAnalyzer().
ResetEvalVars()
int TestSimAnalyzer::ResetEvalVars ()
Definition at line 173 of file TestSimAnalyzer.cxx.
References _b_detector_id, _b_detector_z, _b_drift_distance, _b_event_id, _b_n_hits, _b_pos, _b_run_id, _b_spill_id, _b_target_pos, _b_truth_pos, _b_truth_x, _b_truth_y, and _b_truth_z.
Referenced by InitRun(), process_event(), and ~TestSimAnalyzer().
set_hit_container_choice()
void TestSimAnalyzer::set_hit_container_choice (const std::string & hitContainerChoice) inline
Definition at line 61 of file TestSimAnalyzer.h.
References _hit_container_type.
set_out_name()
void TestSimAnalyzer::set_out_name (const std::string & outName) inline
Definition at line 69 of file TestSimAnalyzer.h.
References _out_name, and GetNodes().
Member Data Documentation
_b_detector_id
int TestSimAnalyzer::_b_detector_id[10000] private
Definition at line 99 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_detector_z
float TestSimAnalyzer::_b_detector_z[10000] private
Definition at line 102 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_drift_distance
float TestSimAnalyzer::_b_drift_distance[10000] private
Definition at line 100 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_event_id
int TestSimAnalyzer::_b_event_id private
Definition at line 96 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_hit_id
int TestSimAnalyzer::_b_hit_id[10000] private
Definition at line 98 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), and process_event().
_b_n_hits
int TestSimAnalyzer::_b_n_hits private
Definition at line 97 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_pos
float TestSimAnalyzer::_b_pos[10000] private
Definition at line 101 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_run_id
int TestSimAnalyzer::_b_run_id private
Definition at line 93 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_spill_id
int TestSimAnalyzer::_b_spill_id private
Definition at line 94 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_target_pos
float TestSimAnalyzer::_b_target_pos private
Definition at line 95 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_truth_pos
float TestSimAnalyzer::_b_truth_pos[10000] private
Definition at line 107 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_truth_x
float TestSimAnalyzer::_b_truth_x[10000] private
Definition at line 104 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_truth_y
float TestSimAnalyzer::_b_truth_y[10000] private
Definition at line 105 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_truth_z
float TestSimAnalyzer::_b_truth_z[10000] private
Definition at line 106 of file TestSimAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_event
size_t TestSimAnalyzer::_event private
Definition at line 79 of file TestSimAnalyzer.h.
Referenced by process_event().
_event_header
SQEvent* TestSimAnalyzer::_event_header private
Definition at line 84 of file TestSimAnalyzer.h.
Referenced by GetNodes(), and process_event().
_hit_container_type
std::string TestSimAnalyzer::_hit_container_type private
Definition at line 77 of file TestSimAnalyzer.h.
Referenced by get_hit_container_choice(), GetNodes(), and set_hit_container_choice().
_hit_map
SQHitMap* TestSimAnalyzer::_hit_map private
Definition at line 85 of file TestSimAnalyzer.h.
Referenced by GetNodes().
_hit_vector
SQHitVector* TestSimAnalyzer::_hit_vector private
Definition at line 86 of file TestSimAnalyzer.h.
Referenced by GetNodes(), and process_event().
_out_name
std::string TestSimAnalyzer::_out_name private
Definition at line 90 of file TestSimAnalyzer.h.
Referenced by End(), get_out_name(), InitEvalTree(), and set_out_name().
_run_header
SQRun* TestSimAnalyzer::_run_header private
Definition at line 81 of file TestSimAnalyzer.h.
Referenced by GetNodes().
_spill_map
SQSpillMap* TestSimAnalyzer::_spill_map private
Definition at line 82 of file TestSimAnalyzer.h.
Referenced by GetNodes(), and process_event().
_tout
TTree* TestSimAnalyzer::_tout private
Definition at line 91 of file TestSimAnalyzer.h.
Referenced by End(), InitEvalTree(), and process_event().
_truth
PHG4TruthInfoContainer* TestSimAnalyzer::_truth private
Definition at line 88 of file TestSimAnalyzer.h.
Referenced by GetNodes(), and process_event().
p_geomSvc
GeomSvc* TestSimAnalyzer::p_geomSvc private
Definition at line 109 of file TestSimAnalyzer.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/module_example/TestSimAnalyzer.h
/home/yuhw/GitHub/SeaQuest/e1039-core/module_example/TestSimAnalyzer.cxx