Class Reference for E1039 Core & Analysis Software: PdbBankID Class Reference
PdbBankID Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbBankID.h>
Public Member Functions
PdbBankID (const int val=0)
virtual ~PdbBankID ()
void print () const
int getInternalValue () const
void setInternalValue (const int val)
Friends
int operator== (const PdbBankID &, const PdbBankID &)
Detailed Description
Definition at line 19 of file PdbBankID.h.
Constructor & Destructor Documentation
PdbBankID()
PdbBankID::PdbBankID (const int val = 0)
Definition at line 14 of file PdbBankID.cc.
~PdbBankID()
virtual PdbBankID::~PdbBankID () inline virtual
Definition at line 22 of file PdbBankID.h.
Member Function Documentation
getInternalValue()
int PdbBankID::getInternalValue () const inline
Definition at line 26 of file PdbBankID.h.
Referenced by PdbParameterMapContainer::WriteToFile(), PHParametersContainer::WriteToFile(), and PHG4ParametersContainer::WriteToFile().
print()
void PdbBankID::print () const
Definition at line 19 of file PdbBankID.cc.
setInternalValue()
void PdbBankID::setInternalValue (const int val) inline
Definition at line 27 of file PdbBankID.h.
Friends And Related Function Documentation
operator==
int operator== (const PdbBankID & a, const PdbBankID & b) friend
Definition at line 24 of file PdbBankID.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbBankID.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbBankID.cc