Class Reference for E1039 Core & Analysis Software: RoadMap Class Reference
RoadMap Class Reference
Class to hold a non-ordered set (i.e. map) of roads.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadMap.h>
Public Types
typedef InfoMap::iterator Iter
typedef InfoMap::const_iterator ConstIter
Public Member Functions
RoadMap ()
virtual ~RoadMap ()
int Size () const
ConstIter Begin () const
ConstIter End () const
Iter Begin ()
Iter End ()
RoadInfo * Find (const int road) const
bool Contain (const RoadMap *map) const
bool ContainEnabled (const RoadMap *map) const
void Add (const int road, const double weight, const int count=1)
void Add (const RoadInfo *info)
void Add (const RoadMap *map)
void Scale (const double val)
void AddBG (const int road, const double weight, const int count=1)
void AddBG (const RoadInfo *info)
void AddBG (const RoadMap *map)
void ScaleBG (const double val)
Public Member Functions inherited from RoadListBase
virtual ~RoadListBase ()
void SetPNTB (const int pn, const int tb)
void SetPosNeg (const int pn)
void SetTopBot (const int tb)
int GetPosNeg () const
int GetTopBot () const
std::string GetPosNegStr () const
std::string GetTopBotStr () const
void Frozen ()
bool IsFrozen ()
Additional Inherited Members
Protected Member Functions inherited from RoadListBase
RoadListBase ()
Protected Attributes inherited from RoadListBase
int m_pn
int m_tb
bool m_frozen
Detailed Description
Class to hold a non-ordered set (i.e. map) of roads.
Definition at line 8 of file RoadMap.h.
Member Typedef Documentation
ConstIter
typedef InfoMap::const_iterator RoadMap::ConstIter
Definition at line 14 of file RoadMap.h.
Iter
typedef InfoMap::iterator RoadMap::Iter
Definition at line 13 of file RoadMap.h.
Constructor & Destructor Documentation
RoadMap()
RoadMap::RoadMap ()
Definition at line 8 of file RoadMap.cc.
~RoadMap()
RoadMap::~RoadMap () virtual
Definition at line 13 of file RoadMap.cc.
Member Function Documentation
Add() [1/3]
void RoadMap::Add (const int road, const double weight, const int count = 1)
Definition at line 43 of file RoadMap.cc.
References RoadInfo::Add().
Referenced by AnaSignal::ProcessOneEvent(), and UtilRoad::ReadFromFile().
Add() [2/3]
void RoadMap::Add (const RoadInfo * info)
Definition at line 54 of file RoadMap.cc.
References RoadInfo::GetCount(), RoadInfo::GetRoadID(), and RoadInfo::GetWeight().
Add() [3/3]
void RoadMap::Add (const RoadMap * map)
Definition at line 59 of file RoadMap.cc.
References Begin(), and End().
AddBG() [1/3]
void RoadMap::AddBG (const int road, const double weight, const int count = 1)
Definition at line 69 of file RoadMap.cc.
References RoadInfo::AddBG().
Referenced by AnaBG::FindAllRoads(), AnaBG::ProcessOneEvent(), and ReAnaBG::ProcessOneEvent().
AddBG() [2/3]
void RoadMap::AddBG (const RoadInfo * info)
Definition at line 80 of file RoadMap.cc.
References RoadInfo::GetCountBG(), RoadInfo::GetRoadID(), and RoadInfo::GetWeightBG().
AddBG() [3/3]
void RoadMap::AddBG (const RoadMap * map)
Definition at line 85 of file RoadMap.cc.
References Begin(), and End().
Begin() [1/2]
Iter RoadMap::Begin () inline
Definition at line 22 of file RoadMap.h.
Begin() [2/2]
ConstIter RoadMap::Begin () const inline
Definition at line 20 of file RoadMap.h.
Referenced by Add(), RoadList::Add(), AddBG(), AnaBG::Analyze(), Contain(), ContainEnabled(), DrawRoadset::DrawOneSet(), and AnaBG::ProcessOneEvent().
Contain()
bool RoadMap::Contain (const RoadMap * map) const
Definition at line 26 of file RoadMap.cc.
References Begin(), and End().
Referenced by AnaBG::ProcessOneEvent().
ContainEnabled()
bool RoadMap::ContainEnabled (const RoadMap * map) const
Definition at line 34 of file RoadMap.cc.
References Begin(), and End().
Referenced by ReAnaBG::ProcessOneEvent().
End() [1/2]
Iter RoadMap::End () inline
Definition at line 23 of file RoadMap.h.
End() [2/2]
ConstIter RoadMap::End () const inline
Definition at line 21 of file RoadMap.h.
Referenced by Add(), RoadList::Add(), AddBG(), AnaBG::Analyze(), Contain(), ContainEnabled(), DrawRoadset::DrawOneSet(), AnaBG::ProcessOneEvent(), and UtilRoad::WriteToFile().
Find()
RoadInfo * RoadMap::Find (const int road) const
Definition at line 21 of file RoadMap.cc.
Referenced by GenRoadset::GenerateSymmetricRoadSetByFoM(), AnaBG::ProcessOneEvent(), and ReAnaSignal::ProcessOneEvent().
Scale()
void RoadMap::Scale (const double val)
Definition at line 64 of file RoadMap.cc.
ScaleBG()
void RoadMap::ScaleBG (const double val)
Definition at line 90 of file RoadMap.cc.
Referenced by AnaBG::Analyze().
Size()
int RoadMap::Size () const inline
Definition at line 19 of file RoadMap.h.
Referenced by UtilRoad::ReadFromFile().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadMap.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadMap.cc