Class Reference for E1039 Core & Analysis Software: Fun4AllHepMCPileupInputManager Class Reference
Fun4AllHepMCPileupInputManager Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/phhepmc/Fun4AllHepMCPileupInputManager.h>
Public Member Functions
Fun4AllHepMCPileupInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
virtual ~Fun4AllHepMCPileupInputManager ()
int run (const int nevents=0)
void set_time_window (double past_nsec, double future_nsec)
past times are negative, future times are positive
void set_collision_rate (double Hz)
collision rate in Hz
void set_time_between_crossings (double nsec)
time between bunch crossing in ns
Public Member Functions inherited from Fun4AllHepMCInputManager
Fun4AllHepMCInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
virtual ~Fun4AllHepMCInputManager ()
virtual int fileopen (const std::string &filenam)
virtual int fileclose ()
int isOpen ()
void ReadOscar (const int i=1)
virtual void Print (const std::string &what="ALL") const
virtual int PushBackEvents (const int i)
int SyncIt (const SyncObject *)
int GetSyncObject (SyncObject **)
int NoSyncPushBackEvents (const int nevt)
HepMC::GenEvent * ConvertFromOscar ()
void set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int get_embedding_id () const
void set_embedding_id (int id)
Public Member Functions inherited from Fun4AllInputManager
virtual ~Fun4AllInputManager ()
virtual int ReadInRunNode (PHCompositeNode *)
virtual std::string Filename ()
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
virtual int skip (const int nevt)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
int ResetFileList ()
virtual int ResetEvent ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from Fun4AllHepMCInputManager
int OpenNextFile ()
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllHepMCInputManager
int isopen
int events_total
int events_thisfile
int readoscar
std::string filename
std::string topNodeName
PHCompositeNode * topNode
HepMC::IO_GenEvent * ascii_in
HepMC::GenEvent * evt
HepMC::GenEvent * save_evt
std::ifstream * filestream
std::istream * unzipstream
std::ifstream theOscarFile
PHHepMCGenHelper hepmc_helper
helper for insert HepMC event to DST node and add vertex smearing
boost::iostreams::filtering_streambuf< boost::iostreams::input > zinbuffer
Protected Attributes inherited from Fun4AllInputManager
std::vector< SubsysReco * > Subsystems
std::string InputNode
std::string filename
std::string topNodeName
std::list< std::string > filelist
std::list< std::string > filelist_copy
std::list< std::string > filelist_opened
Fun4AllSyncManager * mySyncManager
int repeat
int myrunnumber
int initrun
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Generate pile up collisions based on beam parameter If set_embedding_id(i) with a negative number or 0, the pile up event will be inserted with increasing positive embedding_id. This is the default operation mode. If set_embedding_id(i) with a positive number, the pile up event will be inserted with increasing positive embedding_id. This would be a strange way to use pile up.
Definition at line 29 of file Fun4AllHepMCPileupInputManager.h.
Constructor & Destructor Documentation
Fun4AllHepMCPileupInputManager()
Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager (const std::string & name = "DUMMY", const std::string & nodename = "DST", const std::string & topnodename = "TOP")
repeatedly read the input file
If set_embedding_id(i) with a negative number or 0, the pile up event will be inserted with increasing positive embedding_id. This is the default operation mode.
setup default beam diamond to ~Run14 level
Definition at line 42 of file Fun4AllHepMCPileupInputManager.cc.
References PHHepMCGenHelper::Gaus, Fun4AllHepMCInputManager::hepmc_helper, Fun4AllInputManager::Repeat(), PHHepMCGenHelper::set_embedding_id(), PHHepMCGenHelper::set_vertex_distribution_function(), PHHepMCGenHelper::set_vertex_distribution_mean(), and PHHepMCGenHelper::set_vertex_distribution_width().
~Fun4AllHepMCPileupInputManager()
Fun4AllHepMCPileupInputManager::~Fun4AllHepMCPileupInputManager () virtual
Definition at line 76 of file Fun4AllHepMCPileupInputManager.cc.
Member Function Documentation
run()
int Fun4AllHepMCPileupInputManager::run (const int nevents = 0) virtual
If set_embedding_id(i) with a positive number, the pile up event will be inserted with increasing positive embedding_id. This would be a strange way to use pile up.
If set_embedding_id(i) with a negative number or 0, the pile up event will be inserted with increasing positive embedding_id. This is the default operation mode.
Reimplemented from Fun4AllHepMCInputManager.
Definition at line 81 of file Fun4AllHepMCPileupInputManager.cc.
References PHHepMCGenEvent::addEvent(), Fun4AllHepMCInputManager::ascii_in, Fun4AllHepMCInputManager::ConvertFromOscar(), Fun4AllSyncManager::CurrentEvent(), Fun4AllReturnCodes::EVENT_OK, Fun4AllHepMCInputManager::events_thisfile, Fun4AllHepMCInputManager::events_total, Fun4AllHepMCInputManager::evt, Fun4AllHepMCInputManager::fileclose(), Fun4AllInputManager::filelist, PHHepMCGenHelper::get_embedding_id(), PHHepMCGenHelper::get_geneventmap(), Fun4AllHepMCInputManager::hepmc_helper, PHHepMCGenEventMap::insert_active_event(), PHHepMCGenEventMap::insert_background_event(), Fun4AllHepMCInputManager::isopen, PHHepMCGenHelper::move_vertex(), PHHepMCGenEvent::moveVertex(), Fun4AllInputManager::mySyncManager, Fun4AllBase::Name(), NULL, Fun4AllHepMCInputManager::OpenNextFile(), Fun4AllHepMCInputManager::readoscar, Fun4AllInputManager::RejectEvent(), Fun4AllInputManager::ResetEvent(), Fun4AllHepMCInputManager::save_evt, Fun4AllBase::Verbosity(), Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_SOME.
set_collision_rate()
void Fun4AllHepMCPileupInputManager::set_collision_rate (double Hz) inline
collision rate in Hz
Definition at line 46 of file Fun4AllHepMCPileupInputManager.h.
set_time_between_crossings()
void Fun4AllHepMCPileupInputManager::set_time_between_crossings (double nsec) inline
time between bunch crossing in ns
Definition at line 48 of file Fun4AllHepMCPileupInputManager.h.
set_time_window()
void Fun4AllHepMCPileupInputManager::set_time_window (double past_nsec, double future_nsec) inline
past times are negative, future times are positive
Definition at line 40 of file Fun4AllHepMCPileupInputManager.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/phhepmc/Fun4AllHepMCPileupInputManager.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/phhepmc/Fun4AllHepMCPileupInputManager.cc