E1039 Software: /home/yuhw/GitHub/SeaQuest/e1039-core/online/evio/evtest.c File Reference
evtest.c File Reference
Macros
#define MIN(a, b) (a<b)? a : b
Functions
int * makeEvent ()
main ()
Macro Definition Documentation
#define MIN (a, b) (a<b)? a : b
Definition at line 34 of file evtest.c.
Referenced by main().
Function Documentation
main ()
Definition at line 36 of file evtest.c.
References cePmsg(), evClose(), evOpen(), evRead(), evWrite(), makeEvent(), MIN, and submit_bnl::nevents.
int * makeEvent ()
Definition at line 74 of file evtest.c.
Referenced by main().