E1039 Software: PHEventDisplay Class Reference
PHEventDisplay Class Reference
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/packages/Display/interface/PHEventDisplay.h>
Public Member Functions
PHEventDisplay (int w, int h, bool _use_fieldmap, bool _use_geofile, const std::string &_mapname, const std::string &_geoname)
~PHEventDisplay ()
int Init (PHCompositeNode *topNode)
Module initialization.
int InitRun (PHCompositeNode *topNode)
Run initialization.
int process_event (PHCompositeNode *topNode)
Event processing.
int End (PHCompositeNode *topNode)
End of process.
void start_rotation ()
Threaded access to Fun4All server.
void go_fullscreen ()
void set_jet_pt_threshold (float pt)
void set_jet_e_scale (float e_scale)
void set_calo_e_threshold (float e)
void set_dc_on (bool dc_on)
void set_hodo_on (bool hodo_on)
void set_prop_on (bool prop_on)
void set_truth_on (bool truth_on)
void set_verbosity (int verb)
void set_view_top ()
void set_view_side ()
void set_view_3d ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
typedef boost::shared_ptr
< mPHEveModuleBase > pBase
Private Member Functions
void reco_thread ()
void draw_default (PHCompositeNode *topNode)
void update_scene (PHCompositeNode *topNode)
template<typename T >
boost::shared_ptr< T > register_module ()
Private Attributes
bool _pending_update
std::vector< boost::shared_ptr
< mPHEveModuleBase > > _modules
Reconstruction mutex.
pthread_mutex_t _mutex
boost::shared_ptr< boost::thread > _update_thread
boost::shared_ptr< PHEveDisplay > _PHEveDisplay
TGLAutoRotator * _rot
boost::shared_ptr< boost::thread > _status_thread
float jet_pt_threshold
float jet_e_scale
float calo_e_threshold
bool is_dc_on
bool is_hodo_on
bool is_prop_on
bool is_truth_on
bool use_fieldmap
bool use_geofile
int width
int height
std::string mapname
std::string geoname
int nevent
int verbosity
TEveWindowSlot * _slot_dc
TEveWindowSlot * _slot_dc_00
TEveWindowSlot * _slot_dc_01
TEveWindowSlot * _slot_dc_10
TEveWindowSlot * _slot_dc_11
TEveWindowSlot * _slot_hodo
TEveWindowSlot * _slot_hodo_xz
TEveWindowSlot * _slot_hodo_yz
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 34 of file PHEventDisplay.h.
Member Typedef Documentation
typedef boost::shared_ptr<mPHEveModuleBase> PHEventDisplay::pBase private
Definition at line 78 of file PHEventDisplay.h.
Constructor & Destructor Documentation
PHEventDisplay::PHEventDisplay (int w = 1920, int h = 1080, bool _use_fieldmap = false, bool _use_geofile = false, const std::string & _mapname = "sPHEBIX.2d.root", const std::string & _geoname = "geo.root")
Definition at line 149 of file PHEventDisplay.cxx.
References _PHEveDisplay, height, PHEveDisplay::set_eve_manager(), v, verbosity, and width.
PHEventDisplay::~PHEventDisplay ()
Definition at line 207 of file PHEventDisplay.cxx.
Member Function Documentation
void PHEventDisplay::draw_default (PHCompositeNode * topNode) private
Definition at line 362 of file PHEventDisplay.cxx.
References _PHEveDisplay, _slot_dc, _slot_dc_00, _slot_dc_01, _slot_dc_10, _slot_dc_11, _slot_hodo, _slot_hodo_xz, _slot_hodo_yz, DrawHodo(), SQEvent::get_event_id(), PHEveDisplay::get_hodo_list(), SQEvent::get_run_id(), SQEvent::get_spill_id(), PHEveDisplay::get_top_list(), SQEvent::get_trigger(), MakeProjection(), SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, SQEvent::MATRIX5, nevent, SQEvent::NIM1, SQEvent::NIM2, SQEvent::NIM3, SQEvent::NIM4, SQEvent::NIM5, set_view_3d(), v, and verbosity.
Referenced by update_scene().
int PHEventDisplay::End (PHCompositeNode * topNode) virtual
End of process.
Reimplemented from SubsysReco.
Definition at line 292 of file PHEventDisplay.cxx.
void PHEventDisplay::go_fullscreen ()
Definition at line 467 of file PHEventDisplay.cxx.
References _PHEveDisplay, and PHEveDisplay::go_fullscreen().
int PHEventDisplay::Init (PHCompositeNode * topNode) virtual
Module initialization.
Reimplemented from SubsysReco.
Definition at line 211 of file PHEventDisplay.cxx.
References _PHEveDisplay, calo_e_threshold, SubsysReco::Init(), is_dc_on, is_hodo_on, is_prop_on, is_truth_on, jet_e_scale, jet_pt_threshold, PHEveDisplay::set_calo_e_threshold(), PHEveDisplay::set_jet_e_scale(), PHEveDisplay::set_jet_pt_threshold(), and verbosity.
int PHEventDisplay::InitRun (PHCompositeNode * topNode) virtual
Run initialization.
Reimplemented from SubsysReco.
Definition at line 230 of file PHEventDisplay.cxx.
References _modules, _PHEveDisplay, PHEveDisplay::add_elements(), PHEveDisplay::config_bfields(), PHFieldUtility::GetFieldMapNode(), mPHEveModuleBase::init_run(), PHEveDisplay::load_geometry(), PHEveDisplay::set_verbosity(), and verbosity.
Referenced by eve_disp(), eve_disp_db(), and InitInput().
int PHEventDisplay::process_event (PHCompositeNode * topNode) virtual
Event processing.
Reimplemented from SubsysReco.
Definition at line 267 of file PHEventDisplay.cxx.
References _modules, mPHEveModuleBase::clear(), mPHEveModuleBase::event(), nevent, update_scene(), and verbosity.
void PHEventDisplay::reco_thread () private
Definition at line 349 of file PHEventDisplay.cxx.
References _mutex, _pending_update, Fun4AllServer::instance(), nevent, Fun4AllServer::run(), se, and verbosity.
template<typename T > boost::shared_ptr<T> PHEventDisplay::register_module () inline private
Definition at line 81 of file PHEventDisplay.h.
References _modules, _PHEveDisplay, and boost::dynamic_pointer_cast().
void PHEventDisplay::set_calo_e_threshold (float e) inline
Definition at line 61 of file PHEventDisplay.h.
References calo_e_threshold.
Referenced by Fun4All_EventDisplay().
void PHEventDisplay::set_dc_on (bool dc_on) inline
Definition at line 62 of file PHEventDisplay.h.
References is_dc_on.
void PHEventDisplay::set_hodo_on (bool hodo_on) inline
Definition at line 63 of file PHEventDisplay.h.
References is_hodo_on.
void PHEventDisplay::set_jet_e_scale (float e_scale) inline
Definition at line 60 of file PHEventDisplay.h.
References jet_e_scale.
Referenced by Fun4All_EventDisplay().
void PHEventDisplay::set_jet_pt_threshold (float pt) inline
Definition at line 59 of file PHEventDisplay.h.
References jet_pt_threshold.
Referenced by Fun4All_EventDisplay().
void PHEventDisplay::set_prop_on (bool prop_on) inline
Definition at line 64 of file PHEventDisplay.h.
References is_prop_on.
void PHEventDisplay::set_truth_on (bool truth_on) inline
Definition at line 65 of file PHEventDisplay.h.
References is_truth_on.
Referenced by Fun4All_EventDisplay().
void PHEventDisplay::set_verbosity (int verb) inline
Definition at line 66 of file PHEventDisplay.h.
References verbosity.
Referenced by EventDisplay(), and Fun4All_EventDisplay().
void PHEventDisplay::set_view_3d ()
Definition at line 316 of file PHEventDisplay.cxx.
References v.
Referenced by draw_default(), and EventDispUI::View3D().
void PHEventDisplay::set_view_side ()
Definition at line 307 of file PHEventDisplay.cxx.
References v.
Referenced by EventDispUI::ViewSide().
void PHEventDisplay::set_view_top ()
Definition at line 297 of file PHEventDisplay.cxx.
References v.
Referenced by EventDispUI::ViewTop().
void PHEventDisplay::start_rotation ()
Threaded access to Fun4All server.
Definition at line 456 of file PHEventDisplay.cxx.
References _rot.
void PHEventDisplay::update_scene (PHCompositeNode * topNode) private
Definition at line 327 of file PHEventDisplay.cxx.
References draw_default(), nevent, and verbosity.
Referenced by process_event().
Member Data Documentation
std::vector<boost::shared_ptr<mPHEveModuleBase> > PHEventDisplay::_modules private
Reconstruction mutex.
Definition at line 93 of file PHEventDisplay.h.
Referenced by InitRun(), process_event(), and register_module().
pthread_mutex_t PHEventDisplay::_mutex private
Definition at line 94 of file PHEventDisplay.h.
Referenced by reco_thread().
bool PHEventDisplay::_pending_update private
Definition at line 89 of file PHEventDisplay.h.
Referenced by reco_thread().
boost::shared_ptr<PHEveDisplay> PHEventDisplay::_PHEveDisplay private
Definition at line 96 of file PHEventDisplay.h.
Referenced by draw_default(), go_fullscreen(), Init(), InitRun(), PHEventDisplay(), and register_module().
TGLAutoRotator* PHEventDisplay::_rot private
Definition at line 99 of file PHEventDisplay.h.
Referenced by start_rotation().
TEveWindowSlot* PHEventDisplay::_slot_dc private
Definition at line 122 of file PHEventDisplay.h.
Referenced by draw_default().
TEveWindowSlot* PHEventDisplay::_slot_dc_00 private
Definition at line 123 of file PHEventDisplay.h.
Referenced by draw_default().
TEveWindowSlot* PHEventDisplay::_slot_dc_01 private
Definition at line 124 of file PHEventDisplay.h.
Referenced by draw_default().
TEveWindowSlot* PHEventDisplay::_slot_dc_10 private
Definition at line 125 of file PHEventDisplay.h.
Referenced by draw_default().
TEveWindowSlot* PHEventDisplay::_slot_dc_11 private
Definition at line 126 of file PHEventDisplay.h.
Referenced by draw_default().
TEveWindowSlot* PHEventDisplay::_slot_hodo private
Definition at line 129 of file PHEventDisplay.h.
Referenced by draw_default().
TEveWindowSlot* PHEventDisplay::_slot_hodo_xz private
Definition at line 130 of file PHEventDisplay.h.
Referenced by draw_default().
TEveWindowSlot* PHEventDisplay::_slot_hodo_yz private
Definition at line 131 of file PHEventDisplay.h.
Referenced by draw_default().
boost::shared_ptr<boost::thread> PHEventDisplay::_status_thread private
Definition at line 102 of file PHEventDisplay.h.
boost::shared_ptr<boost::thread> PHEventDisplay::_update_thread private
Definition at line 95 of file PHEventDisplay.h.
float PHEventDisplay::calo_e_threshold private
Definition at line 106 of file PHEventDisplay.h.
Referenced by Init(), and set_calo_e_threshold().
std::string PHEventDisplay::geoname private
Definition at line 118 of file PHEventDisplay.h.
int PHEventDisplay::height private
Definition at line 116 of file PHEventDisplay.h.
Referenced by PHEventDisplay().
bool PHEventDisplay::is_dc_on private
Definition at line 108 of file PHEventDisplay.h.
Referenced by Init(), and set_dc_on().
bool PHEventDisplay::is_hodo_on private
Definition at line 109 of file PHEventDisplay.h.
Referenced by Init(), and set_hodo_on().
bool PHEventDisplay::is_prop_on private
Definition at line 110 of file PHEventDisplay.h.
Referenced by Init(), and set_prop_on().
bool PHEventDisplay::is_truth_on private
Definition at line 111 of file PHEventDisplay.h.
Referenced by Init(), and set_truth_on().
float PHEventDisplay::jet_e_scale private
Definition at line 105 of file PHEventDisplay.h.
Referenced by Init(), and set_jet_e_scale().
float PHEventDisplay::jet_pt_threshold private
Definition at line 104 of file PHEventDisplay.h.
Referenced by Init(), and set_jet_pt_threshold().
std::string PHEventDisplay::mapname private
Definition at line 117 of file PHEventDisplay.h.
int PHEventDisplay::nevent private
Definition at line 119 of file PHEventDisplay.h.
Referenced by draw_default(), process_event(), reco_thread(), and update_scene().
bool PHEventDisplay::use_fieldmap private
Definition at line 113 of file PHEventDisplay.h.
bool PHEventDisplay::use_geofile private
Definition at line 114 of file PHEventDisplay.h.
int PHEventDisplay::verbosity private
Definition at line 120 of file PHEventDisplay.h.
Referenced by draw_default(), Init(), InitRun(), PHEventDisplay(), process_event(), reco_thread(), set_verbosity(), and update_scene().
int PHEventDisplay::width private
Definition at line 115 of file PHEventDisplay.h.
Referenced by PHEventDisplay().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/Display/interface/PHEventDisplay.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/Display/interface/PHEventDisplay.cxx