E1039 Software: TestAnalyzer Class Reference
TestAnalyzer Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/module_example/TestAnalyzer.h>
Public Member Functions
TestAnalyzer (const std::string &name="TestAnalyzer")
virtual ~TestAnalyzer ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int InitEvalTree ()
int ResetEvalVars ()
const std::string & get_hit_container_choice () const
void set_hit_container_choice (const std::string &hitContainerChoice)
const std::string & get_out_name () const
void set_out_name (const std::string &outName)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
Private Attributes
std::string _hit_container_type
size_t _event
SQRun * _run_header
SQSpillMap * _spill_map
SQEvent * _event_header
SQHitMap * _hit_map
SQHitVector * _hit_vector
std::string _out_name
TTree * _tout
int _b_run_id
int _b_spill_id
float _b_target_pos
int _b_event_id
int _b_n_hits
int _b_hit_id [10000]
short _b_detector_id [10000]
float _b_drift_distance [10000]
float _b_pos [10000]
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 37 of file TestAnalyzer.h.
Constructor & Destructor Documentation
TestAnalyzer()
TestAnalyzer::TestAnalyzer (const std::string & name = "TestAnalyzer")
Definition at line 42 of file TestAnalyzer.cxx.
~TestAnalyzer()
virtual TestAnalyzer::~TestAnalyzer () inline virtual
Definition at line 42 of file TestAnalyzer.h.
References End(), Init(), InitEvalTree(), InitRun(), process_event(), and ResetEvalVars().
Member Function Documentation
End()
int TestAnalyzer::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 112 of file TestAnalyzer.cxx.
References _out_name, _tout, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by ~TestAnalyzer().
get_hit_container_choice()
const std::string& TestAnalyzer::get_hit_container_choice () const inline
Definition at line 53 of file TestAnalyzer.h.
References _hit_container_type.
get_out_name()
const std::string& TestAnalyzer::get_out_name () const inline
Definition at line 61 of file TestAnalyzer.h.
References _out_name.
GetNodes()
int TestAnalyzer::GetNodes (PHCompositeNode * topNode) private
Definition at line 154 of file TestAnalyzer.cxx.
References _event_header, _hit_container_type, _hit_map, _hit_vector, _run_header, _spill_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and LogError.
Referenced by InitRun(), and set_out_name().
Init()
int TestAnalyzer::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 55 of file TestAnalyzer.cxx.
References Fun4AllReturnCodes::EVENT_OK.
Referenced by ~TestAnalyzer().
InitEvalTree()
int TestAnalyzer::InitEvalTree ()
Definition at line 122 of file TestAnalyzer.cxx.
References _b_detector_id, _b_drift_distance, _b_event_id, _b_hit_id, _b_n_hits, _b_pos, _b_run_id, _b_spill_id, _b_target_pos, _out_name, _tout, PHTFileServer::get(), and PHTFileServer::open().
Referenced by InitRun(), and ~TestAnalyzer().
InitRun()
int TestAnalyzer::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 59 of file TestAnalyzer.cxx.
References Fun4AllReturnCodes::EVENT_OK, GetNodes(), InitEvalTree(), and ResetEvalVars().
Referenced by ~TestAnalyzer().
process_event()
int TestAnalyzer::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 70 of file TestAnalyzer.cxx.
References _b_detector_id, _b_drift_distance, _b_event_id, _b_hit_id, _b_n_hits, _b_pos, _b_run_id, _b_spill_id, _b_target_pos, _event, _event_header, _hit_vector, _spill_map, _tout, SQHitVector::begin(), SQHitVector::end(), Fun4AllReturnCodes::EVENT_OK, SQSpillMap::get(), SQEvent::get_event_id(), SQEvent::get_run_id(), SQEvent::get_spill_id(), LogWarning, ResetEvalVars(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by ~TestAnalyzer().
ResetEvalVars()
int TestAnalyzer::ResetEvalVars ()
Definition at line 139 of file TestAnalyzer.cxx.
References _b_detector_id, _b_drift_distance, _b_event_id, _b_n_hits, _b_pos, _b_run_id, _b_spill_id, and _b_target_pos.
Referenced by InitRun(), process_event(), and ~TestAnalyzer().
set_hit_container_choice()
void TestAnalyzer::set_hit_container_choice (const std::string & hitContainerChoice) inline
Definition at line 57 of file TestAnalyzer.h.
References _hit_container_type.
set_out_name()
void TestAnalyzer::set_out_name (const std::string & outName) inline
Definition at line 65 of file TestAnalyzer.h.
References _out_name, and GetNodes().
Member Data Documentation
_b_detector_id
short TestAnalyzer::_b_detector_id[10000] private
Definition at line 93 of file TestAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_drift_distance
float TestAnalyzer::_b_drift_distance[10000] private
Definition at line 94 of file TestAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_event_id
int TestAnalyzer::_b_event_id private
Definition at line 90 of file TestAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_hit_id
int TestAnalyzer::_b_hit_id[10000] private
Definition at line 92 of file TestAnalyzer.h.
Referenced by InitEvalTree(), and process_event().
_b_n_hits
int TestAnalyzer::_b_n_hits private
Definition at line 91 of file TestAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_pos
float TestAnalyzer::_b_pos[10000] private
Definition at line 95 of file TestAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_run_id
int TestAnalyzer::_b_run_id private
Definition at line 87 of file TestAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_spill_id
int TestAnalyzer::_b_spill_id private
Definition at line 88 of file TestAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_b_target_pos
float TestAnalyzer::_b_target_pos private
Definition at line 89 of file TestAnalyzer.h.
Referenced by InitEvalTree(), process_event(), and ResetEvalVars().
_event
size_t TestAnalyzer::_event private
Definition at line 75 of file TestAnalyzer.h.
Referenced by process_event().
_event_header
SQEvent* TestAnalyzer::_event_header private
Definition at line 80 of file TestAnalyzer.h.
Referenced by GetNodes(), and process_event().
_hit_container_type
std::string TestAnalyzer::_hit_container_type private
Definition at line 73 of file TestAnalyzer.h.
Referenced by get_hit_container_choice(), GetNodes(), and set_hit_container_choice().
_hit_map
SQHitMap* TestAnalyzer::_hit_map private
Definition at line 81 of file TestAnalyzer.h.
Referenced by GetNodes().
_hit_vector
SQHitVector* TestAnalyzer::_hit_vector private
Definition at line 82 of file TestAnalyzer.h.
Referenced by GetNodes(), and process_event().
_out_name
std::string TestAnalyzer::_out_name private
Definition at line 84 of file TestAnalyzer.h.
Referenced by End(), get_out_name(), InitEvalTree(), and set_out_name().
_run_header
SQRun* TestAnalyzer::_run_header private
Definition at line 77 of file TestAnalyzer.h.
Referenced by GetNodes().
_spill_map
SQSpillMap* TestAnalyzer::_spill_map private
Definition at line 78 of file TestAnalyzer.h.
Referenced by GetNodes(), and process_event().
_tout
TTree* TestAnalyzer::_tout private
Definition at line 85 of file TestAnalyzer.h.
Referenced by End(), InitEvalTree(), and process_event().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/module_example/TestAnalyzer.h
/home/yuhw/GitHub/SeaQuest/e1039-core/module_example/TestAnalyzer.cxx