E1039 Software: /home/yuhw/GitHub/SeaQuest/e1039-core/online/onlmonserver/HistoServer.h File Reference
HistoServer.h File Reference
#include <vector>
Functions
int setup_server ()
void handleconnection (void *arg)
void handletest (void *arg)
void send_test_message ()
void receive_hist_all ()
int monitor_subsys (const char *name, std::vector< TH1 * > &hist_list)
Function Documentation
void handleconnection (void * arg)
Definition at line 166 of file HistoServer.cc.
References Fun4AllHistoManager::getHisto(), Fun4AllServer::getHisto(), Fun4AllServer::getHistoManager(), Fun4AllServer::getHistoName(), OnlMonServer::instance(), Fun4AllHistoManager::nHistos(), NULL, and Fun4AllBase::Verbosity().
Referenced by server().
void handletest (void * arg)
Definition at line 159 of file HistoServer.cc.
int monitor_subsys (const char * name, std::vector< TH1 * > & hist_list)
Definition at line 409 of file HistoServer.cc.
References MONIPORT, and NULL.
Referenced by OnlMonServer::MonitorSubsys().
void receive_hist_all ()
Definition at line 379 of file HistoServer.cc.
References MONIPORT, and NULL.
Referenced by OnlMonServer::testhist().
void send_test_message ()
Definition at line 371 of file HistoServer.cc.
References MONIPORT.
Referenced by OnlMonServer::testmsg().
int setup_server ()
Definition at line 37 of file HistoServer.cc.
References OnlMonServer::instance(), NULL, server(), ServerThread, and OnlMonServer::SetThreadId().
Referenced by OnlMonServer::StartServer().