Class Reference for E1039 Core & Analysis Software: PHG4Particle Class Reference
PHG4Particle Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Particle.h>
Public Member Functions
PHG4Particle ()
virtual ~PHG4Particle ()
virtual int get_pid () const
virtual std::string get_name () const
virtual double get_px () const
virtual double get_py () const
virtual double get_pz () const
virtual double get_e () const
virtual int get_track_id () const
virtual int get_vtx_id () const
virtual int get_parent_id () const
virtual int get_primary_id () const
virtual int get_barcode () const
virtual void set_track_id (const int i)
virtual void set_vtx_id (const int i)
virtual void set_parent_id (const int i)
virtual void set_primary_id (const int i)
virtual void set_name (const std::string &name)
virtual void set_pid (const int i)
virtual void set_px (const double x)
virtual void set_py (const double x)
virtual void set_pz (const double x)
virtual void set_e (const double e)
virtual void set_barcode (const int barcode)
void identify (std::ostream &os=std::cout) const
bool operator== (const PHG4Particle &p) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Detailed Description
Definition at line 7 of file PHG4Particle.h.
Constructor & Destructor Documentation
PHG4Particle()
PHG4Particle::PHG4Particle () inline
Definition at line 11 of file PHG4Particle.h.
~PHG4Particle()
virtual PHG4Particle::~PHG4Particle () inline virtual
Definition at line 12 of file PHG4Particle.h.
Member Function Documentation
get_barcode()
virtual int PHG4Particle::get_barcode () const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 26 of file PHG4Particle.h.
get_e()
virtual double PHG4Particle::get_e () const inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 19 of file PHG4Particle.h.
Referenced by PHG4DSTReader::add_particle(), TruthEval::process_event(), and TruthNodeMaker::process_event().
get_name()
virtual std::string PHG4Particle::get_name (void) const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 15 of file PHG4Particle.h.
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), and PHG4ParticleGeneratorBase::SetParticleId().
get_parent_id()
virtual int PHG4Particle::get_parent_id () const inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 23 of file PHG4Particle.h.
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), PHG4TruthEventAction::EndOfEventAction(), and TruthEval::process_event().
get_pid()
virtual int PHG4Particle::get_pid () const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 14 of file PHG4Particle.h.
Referenced by PHG4DSTReader::add_particle(), operator==(), TruthEval::process_event(), TruthNodeMaker::process_event(), and PHG4ParticleGeneratorBase::SetParticleId().
get_primary_id()
virtual int PHG4Particle::get_primary_id () const inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 24 of file PHG4Particle.h.
Referenced by PHG4DSTReader::add_particle(), and PHG4ConsistencyCheck::process_event().
get_px()
virtual double PHG4Particle::get_px () const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 16 of file PHG4Particle.h.
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), operator==(), TruthEval::process_event(), and TruthNodeMaker::process_event().
get_py()
virtual double PHG4Particle::get_py () const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 17 of file PHG4Particle.h.
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), operator==(), TruthEval::process_event(), and TruthNodeMaker::process_event().
get_pz()
virtual double PHG4Particle::get_pz () const inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 18 of file PHG4Particle.h.
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), operator==(), TruthEval::process_event(), and TruthNodeMaker::process_event().
get_track_id()
virtual int PHG4Particle::get_track_id () const inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 21 of file PHG4Particle.h.
Referenced by PHG4DSTReader::add_particle(), PHG4TruthInfoContainer::AddParticle(), PHG4TruthInfoContainer::is_primary(), TruthEval::process_event(), and TruthNodeMaker::process_event().
get_vtx_id()
virtual int PHG4Particle::get_vtx_id () const inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 22 of file PHG4Particle.h.
Referenced by PHG4DSTReader::add_particle(), PHG4TruthEventAction::EndOfEventAction(), TruthEval::process_event(), and TruthNodeMaker::process_event().
identify()
void PHG4Particle::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4Particlev2, and PHG4Particlev1.
Definition at line 8 of file PHG4Particle.cc.
Referenced by PHG4ConsistencyCheck::process_event().
operator==()
bool PHG4Particle::operator== (const PHG4Particle & p) const
Definition at line 15 of file PHG4Particle.cc.
References get_pid(), get_px(), get_py(), and get_pz().
set_barcode()
virtual void PHG4Particle::set_barcode (const int barcode) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 39 of file PHG4Particle.h.
Referenced by HepMCNodeReader::process_event().
set_e()
virtual void PHG4Particle::set_e (const double e) inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 37 of file PHG4Particle.h.
Referenced by PHG4ParticleGenerator::process_event(), PHG4PSScanGenerator::process_event(), PHG4SimpleEventGenerator::process_event(), and SQCosmicGen::process_event().
set_name()
virtual void PHG4Particle::set_name (const std::string & name) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 32 of file PHG4Particle.h.
Referenced by PHG4PSScanGenerator::process_event(), PHG4SimpleEventGenerator::process_event(), SQCosmicGen::process_event(), and PHG4ParticleGeneratorBase::SetParticleId().
set_parent_id()
virtual void PHG4Particle::set_parent_id (const int i) inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 30 of file PHG4Particle.h.
Referenced by PHG4PSScanGenerator::process_event(), PHG4SimpleEventGenerator::process_event(), and SQCosmicGen::process_event().
set_pid()
virtual void PHG4Particle::set_pid (const int i) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 33 of file PHG4Particle.h.
Referenced by PHG4ParticleGeneratorBase::AddParticle(), HepMCNodeReader::process_event(), PHG4InEventReadBack::process_event(), PHG4PSScanGenerator::process_event(), PHG4SimpleEventGenerator::process_event(), SQCosmicGen::process_event(), and PHG4ParticleGeneratorBase::SetParticleId().
set_primary_id()
virtual void PHG4Particle::set_primary_id (const int i) inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 31 of file PHG4Particle.h.
set_px()
virtual void PHG4Particle::set_px (const double x) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 34 of file PHG4Particle.h.
Referenced by PHG4ParticleGeneratorBase::AddParticle(), HepMCNodeReader::process_event(), PHG4InEventReadBack::process_event(), PHG4ParticleGenerator::process_event(), PHG4PSScanGenerator::process_event(), PHG4SimpleEventGenerator::process_event(), and SQCosmicGen::process_event().
set_py()
virtual void PHG4Particle::set_py (const double x) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 35 of file PHG4Particle.h.
Referenced by PHG4ParticleGeneratorBase::AddParticle(), HepMCNodeReader::process_event(), PHG4InEventReadBack::process_event(), PHG4ParticleGenerator::process_event(), PHG4PSScanGenerator::process_event(), PHG4SimpleEventGenerator::process_event(), and SQCosmicGen::process_event().
set_pz()
virtual void PHG4Particle::set_pz (const double x) inline virtual
Reimplemented in PHG4Particlev1.
Definition at line 36 of file PHG4Particle.h.
Referenced by PHG4ParticleGeneratorBase::AddParticle(), HepMCNodeReader::process_event(), PHG4InEventReadBack::process_event(), PHG4ParticleGenerator::process_event(), PHG4PSScanGenerator::process_event(), PHG4SimpleEventGenerator::process_event(), and SQCosmicGen::process_event().
set_track_id()
virtual void PHG4Particle::set_track_id (const int i) inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 28 of file PHG4Particle.h.
Referenced by PHG4PSScanGenerator::process_event(), PHG4SimpleEventGenerator::process_event(), and SQCosmicGen::process_event().
set_vtx_id()
virtual void PHG4Particle::set_vtx_id (const int i) inline virtual
Reimplemented in PHG4Particlev2.
Definition at line 29 of file PHG4Particle.h.
Referenced by PHG4PSScanGenerator::process_event(), PHG4SimpleEventGenerator::process_event(), and SQCosmicGen::process_event().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Particle.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Particle.cc