Class Reference for E1039 Core & Analysis Software: PHPy8GenTrigger Class Reference
PHPy8GenTrigger Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/PHPythia8/PHPy8GenTrigger.h>
Public Member Functions
virtual ~PHPy8GenTrigger ()
virtual bool Apply (Pythia8::Pythia *pythia)
virtual std::string GetName ()
std::vector< int > convertToInts (std::string s)
void Verbosity (int v)
Protected Member Functions
PHPy8GenTrigger (const std::string &name="PHPy8GenTrigger")
constructor
Protected Attributes
int _verbosity
Detailed Description
Definition at line 13 of file PHPy8GenTrigger.h.
Constructor & Destructor Documentation
PHPy8GenTrigger::PHPy8GenTrigger (const std::string & name = "PHPy8GenTrigger") protected
constructor
Definition at line 10 of file PHPy8GenTrigger.C.
PHPy8GenTrigger::~PHPy8GenTrigger () virtual
Definition at line 16 of file PHPy8GenTrigger.C.
Member Function Documentation
virtual bool PHPy8GenTrigger::Apply (Pythia8::Pythia * pythia) inline virtual
Reimplemented in PHPy8JetTrigger, and PHPy8ParticleTrigger.
Definition at line 23 of file PHPy8GenTrigger.h.
std::vector< int > PHPy8GenTrigger::convertToInts (std::string s)
Definition at line 18 of file PHPy8GenTrigger.C.
Referenced by PHPy8ParticleTrigger::AddParents(), and PHPy8ParticleTrigger::AddParticles().
virtual std::string PHPy8GenTrigger::GetName () inline virtual
Definition at line 29 of file PHPy8GenTrigger.h.
Referenced by PHPythia8::register_trigger().
void PHPy8GenTrigger::Verbosity (int v) inline
Definition at line 33 of file PHPy8GenTrigger.h.
References _verbosity.
Member Data Documentation
int PHPy8GenTrigger::_verbosity protected
Definition at line 36 of file PHPy8GenTrigger.h.
Referenced by PHPy8JetTrigger::Apply(), PHPy8ParticleTrigger::Apply(), Verbosity(), PHPy8JetTrigger::~PHPy8JetTrigger(), and PHPy8ParticleTrigger::~PHPy8ParticleTrigger().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/PHPythia8/PHPy8GenTrigger.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/PHPythia8/PHPy8GenTrigger.C