Class Reference for E1039 Core & Analysis Software: PHG4ParameterContainerInterface Class Reference
PHG4ParameterContainerInterface Class Reference abstract
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4ParameterContainerInterface.h>
Public Member Functions
PHG4ParameterContainerInterface (const std::string &name)
virtual ~PHG4ParameterContainerInterface ()
void set_name (const std::string &name)
virtual void SetDefaultParameters ()=0
void set_double_param (const int id, const std::string &name, const double dval)
double get_double_param (const int id, const std::string &name) const
void set_int_param (const int id, const std::string &name, const int ival)
int get_int_param (const int id, const std::string &name) const
void set_string_param (const int id, const std::string &name, const std::string &sval)
std::string get_string_param (const int id, const std::string &name) const
void UpdateParametersWithMacro ()
void CreateInitialize (const int detid)
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
int ExistDetid (const int detid) const
Protected Member Functions
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
const PHG4ParametersContainer * GetParamsContainer ()
PHG4ParametersContainer * GetParamsContainerModify ()
const PHG4Parameters * GetDefaultParameters ()
Detailed Description
This class is deprecated, please use PHG4Parameter instead. See https://github.com/sPHENIX-Collaboration/coresoftware/pull/405
Definition at line 13 of file PHG4ParameterContainerInterface.h.
Constructor & Destructor Documentation
PHG4ParameterContainerInterface()
PHG4ParameterContainerInterface::PHG4ParameterContainerInterface (const std::string & name)
Definition at line 14 of file PHG4ParameterContainerInterface.cc.
~PHG4ParameterContainerInterface()
PHG4ParameterContainerInterface::~PHG4ParameterContainerInterface () virtual
Definition at line 23 of file PHG4ParameterContainerInterface.cc.
Member Function Documentation
CreateInitialize()
void PHG4ParameterContainerInterface::CreateInitialize (const int detid)
Definition at line 252 of file PHG4ParameterContainerInterface.cc.
References PHG4ParametersContainer::AddPHG4Parameters(), PHG4ParametersContainer::GetParametersToModify(), and PHG4ParametersContainer::Name().
Referenced by UpdateParametersWithMacro().
ExistDetid()
int PHG4ParameterContainerInterface::ExistDetid (const int detid) const
Definition at line 266 of file PHG4ParameterContainerInterface.cc.
References PHG4ParametersContainer::ExistDetid().
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
get_double_param()
double PHG4ParameterContainerInterface::get_double_param (const int id, const std::string & name) const
Definition at line 109 of file PHG4ParameterContainerInterface.cc.
References PHG4Parameters::get_double_param(), PHG4ParametersContainer::GetParameters(), and PHG4ParametersContainer::Name().
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
get_int_param()
int PHG4ParameterContainerInterface::get_int_param (const int id, const std::string & name) const
Definition at line 149 of file PHG4ParameterContainerInterface.cc.
References PHG4Parameters::get_int_param(), PHG4ParametersContainer::GetParameters(), and PHG4ParametersContainer::Name().
get_string_param()
string PHG4ParameterContainerInterface::get_string_param (const int id, const std::string & name) const
Definition at line 190 of file PHG4ParameterContainerInterface.cc.
References PHG4Parameters::get_string_param(), PHG4ParametersContainer::GetParameters(), and PHG4ParametersContainer::Name().
GetDefaultParameters()
const PHG4Parameters* PHG4ParameterContainerInterface::GetDefaultParameters () inline protected
Definition at line 43 of file PHG4ParameterContainerInterface.h.
GetParamsContainer()
const PHG4ParametersContainer* PHG4ParameterContainerInterface::GetParamsContainer () inline protected
Definition at line 41 of file PHG4ParameterContainerInterface.h.
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
GetParamsContainerModify()
PHG4ParametersContainer* PHG4ParameterContainerInterface::GetParamsContainerModify () inline protected
Definition at line 42 of file PHG4ParameterContainerInterface.h.
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
InitializeParameters()
void PHG4ParameterContainerInterface::InitializeParameters () protected
Definition at line 246 of file PHG4ParameterContainerInterface.cc.
References SetDefaultParameters().
PutOnParNode()
void PHG4ParameterContainerInterface::PutOnParNode (PHCompositeNode * parNode, const std::string & nodename)
Definition at line 240 of file PHG4ParameterContainerInterface.cc.
References PHCompositeNode::addNode().
SaveToNodeTree()
void PHG4ParameterContainerInterface::SaveToNodeTree (PHCompositeNode * runNode, const std::string & nodename)
Definition at line 233 of file PHG4ParameterContainerInterface.cc.
References PHG4ParametersContainer::SaveToNodeTree().
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
set_default_double_param()
void PHG4ParameterContainerInterface::set_default_double_param (const std::string & name, const double dval) protected
Definition at line 43 of file PHG4ParameterContainerInterface.cc.
References PHG4Parameters::exist_double_param(), PHG4Parameters::get_double_param(), and PHG4Parameters::set_double_param().
Referenced by PHG4BlockCellReco::SetDefaultParameters(), and PHG4CylinderCellReco::SetDefaultParameters().
set_default_int_param()
void PHG4ParameterContainerInterface::set_default_int_param (const std::string & name, const int ival) protected
Definition at line 56 of file PHG4ParameterContainerInterface.cc.
References PHG4Parameters::exist_int_param(), PHG4Parameters::get_int_param(), and PHG4Parameters::set_int_param().
set_default_string_param()
void PHG4ParameterContainerInterface::set_default_string_param (const std::string & name, const std::string & sval) protected
Definition at line 69 of file PHG4ParameterContainerInterface.cc.
References PHG4Parameters::exist_string_param(), PHG4Parameters::get_string_param(), and PHG4Parameters::set_string_param().
set_double_param()
void PHG4ParameterContainerInterface::set_double_param (const int id, const std::string & name, const double dval)
Definition at line 82 of file PHG4ParameterContainerInterface.cc.
References PHG4Parameters::exist_double_param(), PHG4ParametersContainer::Name(), PHG4Parameters::printdouble(), and PHG4Parameters::set_double_param().
Referenced by PHG4CylinderCellReco::cellsize(), PHG4CylinderCellReco::etaphisize(), PHG4BlockCellReco::etaxsize(), PHG4BlockCellReco::set_timing_window(), and PHG4CylinderCellReco::set_timing_window().
set_int_param()
void PHG4ParameterContainerInterface::set_int_param (const int id, const std::string & name, const int ival)
Definition at line 122 of file PHG4ParameterContainerInterface.cc.
References PHG4ParametersContainer::AddPHG4Parameters(), PHG4Parameters::exist_int_param(), PHG4ParametersContainer::Name(), PHG4Parameters::printint(), and PHG4Parameters::set_int_param().
set_name()
void PHG4ParameterContainerInterface::set_name (const std::string & name)
Definition at line 37 of file PHG4ParameterContainerInterface.cc.
References PHG4ParametersContainer::set_name().
set_string_param()
void PHG4ParameterContainerInterface::set_string_param (const int id, const std::string & name, const std::string & sval)
Definition at line 162 of file PHG4ParameterContainerInterface.cc.
References PHG4ParametersContainer::AddPHG4Parameters(), PHG4Parameters::exist_string_param(), PHG4ParametersContainer::Name(), PHG4Parameters::printstring(), and PHG4Parameters::set_string_param().
SetDefaultParameters()
virtual void PHG4ParameterContainerInterface::SetDefaultParameters () pure virtual
Implemented in PHG4CylinderCellReco, and PHG4BlockCellReco.
Referenced by InitializeParameters().
UpdateParametersWithMacro()
void PHG4ParameterContainerInterface::UpdateParametersWithMacro ()
Definition at line 203 of file PHG4ParameterContainerInterface.cc.
References CreateInitialize(), PHG4Parameters::get_all_double_params(), PHG4ParametersContainer::GetParametersToModify(), PHG4Parameters::set_double_param(), PHG4Parameters::set_int_param(), and PHG4Parameters::set_string_param().
Referenced by PHG4BlockCellReco::InitRun(), and PHG4CylinderCellReco::InitRun().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4ParameterContainerInterface.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4ParameterContainerInterface.cc