Class Reference for E1039 Core & Analysis Software: PHPointerList< T > Class Template Reference
PHPointerList< T > Class Template Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHPointerList.h>
Public Member Functions
PHPointerList (size_t=2)
PHPointerList (const PHPointerList< T > &)
PHPointerList< T > & operator= (const PHPointerList< T > &)
virtual ~PHPointerList ()
T * operator[] (size_t) const
void clear ()
void clearAndDestroy ()
size_t length () const
T * removeLast ()
T * removeAt (size_t)
PHBoolean append (T *)
PHBoolean insertAt (T *, size_t)
Detailed Description
template<class T>
class PHPointerList< T >
Definition at line 33 of file PHPointerList.h.
Constructor & Destructor Documentation
PHPointerList() [1/2]
template<class T > PHPointerList< T >::PHPointerList (size_t initialSize = 2)
Definition at line 63 of file PHPointerList.h.
PHPointerList() [2/2]
template<class T > PHPointerList< T >::PHPointerList (const PHPointerList< T > & l)
Definition at line 71 of file PHPointerList.h.
~PHPointerList()
template<class T > PHPointerList< T >::~PHPointerList virtual
Definition at line 93 of file PHPointerList.h.
Member Function Documentation
append()
template<class T > PHBoolean PHPointerList< T >::append (T * item) inline
Definition at line 142 of file PHPointerList.h.
References False, and True.
Referenced by PHCompositeNode::addNode(), and PHNodeIterator::ls().
clear()
template<class T > void PHPointerList< T >::clear inline
Definition at line 193 of file PHPointerList.h.
Referenced by PHNodeIterator::ls().
clearAndDestroy()
template<class T > void PHPointerList< T >::clearAndDestroy inline
Definition at line 201 of file PHPointerList.h.
Referenced by PHCompositeNode::~PHCompositeNode().
insertAt()
template<class T > PHBoolean PHPointerList< T >::insertAt (T * item, size_t pos) inline
Definition at line 168 of file PHPointerList.h.
References False, and True.
length()
template<class T > size_t PHPointerList< T >::length inline
Definition at line 213 of file PHPointerList.h.
Referenced by operator<<(), and PHPointerList< T >::operator=().
operator=()
template<class T > PHPointerList< T > & PHPointerList< T >::operator= (const PHPointerList< T > & l)
Definition at line 78 of file PHPointerList.h.
References PHPointerList< T >::length().
operator[]()
template<class T > T * PHPointerList< T >::operator[] (size_t i) const inline
Definition at line 127 of file PHPointerList.h.
removeAt()
template<class T > T * PHPointerList< T >::removeAt (size_t i) inline
Definition at line 235 of file PHPointerList.h.
Referenced by PHCompositeNode::forgetMe(), and PHCompositeNode::prune().
removeLast()
template<class T > T * PHPointerList< T >::removeLast inline
Definition at line 220 of file PHPointerList.h.
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHPointerList.h