Class Reference for E1039 Core & Analysis Software: SQVertexing Class Reference
SQVertexing Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQVertexing.h>
Public Member Functions
SQVertexing (const std::string &name="SQVertexing", int sign1=1, int sign2=-1)
~SQVertexing ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_legacy_rec_container (const bool enable=true)
void set_legacy_in_container (const bool enable=true)
void set_legacy_out_container (const bool enable=true)
void set_single_retracking (const bool enable=true)
void set_geom_file_name (const std::string &geomFileName)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 19 of file SQVertexing.h.
Constructor & Destructor Documentation
SQVertexing()
SQVertexing::SQVertexing (const std::string & name = "SQVertexing", int sign1 = 1, int sign2 = -1)
Definition at line 62 of file SQVertexing.cxx.
~SQVertexing()
SQVertexing::~SQVertexing ()
Definition at line 76 of file SQVertexing.cxx.
Member Function Documentation
End()
int SQVertexing::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 166 of file SQVertexing.cxx.
References Fun4AllReturnCodes::EVENT_OK.
Init()
int SQVertexing::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 79 of file SQVertexing.cxx.
References Fun4AllReturnCodes::EVENT_OK.
InitRun()
int SQVertexing::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 85 of file SQVertexing.cxx.
References Fun4AllReturnCodes::EVENT_OK, PHFlag::get_IntFlag(), and recoConsts::instance().
process_event()
int SQVertexing::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 106 of file SQVertexing.cxx.
References SQTrackVector::at(), SRecEvent::clearDimuons(), Fun4AllReturnCodes::EVENT_OK, SRecTrack::getCharge(), SRecEvent::getNTracks(), SRecEvent::getTrack(), SRecEvent::insertDimuon(), SRecTrack::isKalmanFitted(), SQDimuonVector::push_back(), SRecDimuon::set_track_id_pos(), SRecTrack::setChisqTarget(), SRecTrack::setTargetMom(), SRecTrack::setTargetPos(), SQTrackVector::size(), and Fun4AllBase::Verbosity().
set_geom_file_name()
void SQVertexing::set_geom_file_name (const std::string & geomFileName) inline
Definition at line 35 of file SQVertexing.h.
set_legacy_in_container()
void SQVertexing::set_legacy_in_container (const bool enable = true) inline
Definition at line 31 of file SQVertexing.h.
set_legacy_out_container()
void SQVertexing::set_legacy_out_container (const bool enable = true) inline
Definition at line 32 of file SQVertexing.h.
set_legacy_rec_container()
void SQVertexing::set_legacy_rec_container (const bool enable = true) inline
Definition at line 30 of file SQVertexing.h.
set_single_retracking()
void SQVertexing::set_single_retracking (const bool enable = true) inline
Definition at line 33 of file SQVertexing.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQVertexing.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQVertexing.cxx