Class Reference for E1039 Core & Analysis Software: OnlMonReco Class Reference
OnlMonReco Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonReco.h>
Public Member Functions
OnlMonReco ()
virtual ~OnlMonReco ()
int InitOnlMon (PHCompositeNode *topNode)
int InitRunOnlMon (PHCompositeNode *topNode)
int ProcessEventOnlMon (PHCompositeNode *topNode)
int EndOnlMon (PHCompositeNode *topNode)
int FindAllMonHist ()
int DrawMonitor ()
Public Member Functions inherited from OnlMonClient
OnlMonClient ()
virtual ~OnlMonClient ()
virtual OnlMonClient * Clone ()
void Title (const std::string &title)
std::string Title ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void GetBasicID (int *run_id=0, int *spill_id=0, int *event_id=0, int *spill_id_min=0, int *spill_id_max=0)
void GetBasicCount (int *n_evt=0, int *n_sp=0)
int StartMonitor ()
TH1 * FindMonHist (const std::string name, const bool non_null=true)
int SendHist (TSocket *sock, int sp_min, int sp_max)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Static Public Member Functions inherited from OnlMonClient
static void SetClearUsFlag (const bool val)
static bool GetClearUsFlag ()
Protected Types inherited from OnlMonClient
enum HistMode_t { MODE_ADD, MODE_UPDATE }
Protected Member Functions inherited from OnlMonClient
void RegisterHist (TH1 *h1, const HistMode_t mode=MODE_ADD)
void NumCanvases (const int num)
int NumCanvases ()
OnlMonCanvas * GetCanvas (const int num=0)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 5 of file OnlMonReco.h.
Constructor & Destructor Documentation
OnlMonReco::OnlMonReco ()
Definition at line 21 of file OnlMonReco.cc.
virtual OnlMonReco::~OnlMonReco () inline virtual
Definition at line 15 of file OnlMonReco.h.
Member Function Documentation
int OnlMonReco::DrawMonitor () virtual
Reimplemented from OnlMonClient.
Definition at line 98 of file OnlMonReco.cc.
References OnlMonCanvas::AddMessage(), OnlMonCanvas::GetMainPad(), OnlMonCanvas::OK, and OnlMonCanvas::SetStatus().
int OnlMonReco::EndOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 79 of file OnlMonReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
int OnlMonReco::FindAllMonHist () virtual
Reimplemented from OnlMonClient.
Definition at line 84 of file OnlMonReco.cc.
int OnlMonReco::InitOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 27 of file OnlMonReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
int OnlMonReco::InitRunOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 32 of file OnlMonReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
int OnlMonReco::ProcessEventOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 46 of file OnlMonReco.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, SRecTrack::getCharge(), SRecEvent::getEventID(), SRecTrack::getMomentumVecSt1(), SRecEvent::getNTracks(), SRecEvent::getRecStatus(), SRecEvent::getTrack(), and MUON_MASS.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonReco.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonReco.cc