Class Reference for E1039 Core & Analysis Software: PHG4CylinderCellContainer Class Reference
PHG4CylinderCellContainer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellContainer.h>
Public Types
typedef std::map< PHG4CylinderCellDefs::keytype, PHG4CylinderCell * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator, Iterator > Range
typedef std::pair< ConstIterator, ConstIterator > ConstRange
typedef std::set< int >::const_iterator LayerIter
typedef std::pair< LayerIter, LayerIter > LayerRange
Public Member Functions
PHG4CylinderCellContainer ()
virtual ~PHG4CylinderCellContainer ()
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
ConstIterator AddCylinderCell (const unsigned int detid, PHG4CylinderCell *newcylinderCell)
ConstIterator AddCylinderCellSpecifyKey (const PHG4CylinderCellDefs::keytype key, PHG4CylinderCell *newcylinderCell)
void RemoveCylinderCell (PHG4CylinderCellDefs::keytype key)
preferred removal method, key is currently the cell id
void RemoveCylinderCell (PHG4CylinderCell *cell)
inefficent, use key where possible instead
Iterator findOrAddCylinderCell (PHG4CylinderCellDefs::keytype key)
PHG4CylinderCellDefs::keytype genkey (const unsigned int detid)
ConstRange getCylinderCells (const unsigned int detid) const
return all cylinderCells matching a given detid
ConstRange getCylinderCells (void) const
return all hist
PHG4CylinderCell * findCylinderCell (PHG4CylinderCellDefs::keytype key)
unsigned int size (void) const
unsigned int num_layers (void) const
LayerRange getLayers () const
double getTotalEdep () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
Map cellmap
std::set< int > layers
Detailed Description
Definition at line 11 of file PHG4CylinderCellContainer.h.
Member Typedef Documentation
ConstIterator
typedef Map::const_iterator PHG4CylinderCellContainer::ConstIterator
Definition at line 17 of file PHG4CylinderCellContainer.h.
ConstRange
typedef std::pair<ConstIterator, ConstIterator> PHG4CylinderCellContainer::ConstRange
Definition at line 19 of file PHG4CylinderCellContainer.h.
Iterator
typedef Map::iterator PHG4CylinderCellContainer::Iterator
Definition at line 16 of file PHG4CylinderCellContainer.h.
LayerIter
typedef std::set<int>::const_iterator PHG4CylinderCellContainer::LayerIter
Definition at line 20 of file PHG4CylinderCellContainer.h.
LayerRange
typedef std::pair<LayerIter, LayerIter> PHG4CylinderCellContainer::LayerRange
Definition at line 21 of file PHG4CylinderCellContainer.h.
Map
typedef std::map<PHG4CylinderCellDefs::keytype,PHG4CylinderCell *> PHG4CylinderCellContainer::Map
Definition at line 15 of file PHG4CylinderCellContainer.h.
Range
typedef std::pair<Iterator, Iterator> PHG4CylinderCellContainer::Range
Definition at line 18 of file PHG4CylinderCellContainer.h.
Constructor & Destructor Documentation
PHG4CylinderCellContainer()
PHG4CylinderCellContainer::PHG4CylinderCellContainer ()
Definition at line 9 of file PHG4CylinderCellContainer.cc.
~PHG4CylinderCellContainer()
virtual PHG4CylinderCellContainer::~PHG4CylinderCellContainer () inline virtual
Definition at line 25 of file PHG4CylinderCellContainer.h.
Member Function Documentation
AddCylinderCell()
PHG4CylinderCellContainer::ConstIterator PHG4CylinderCellContainer::AddCylinderCell (const unsigned int detid, PHG4CylinderCell * newcylinderCell)
Definition at line 65 of file PHG4CylinderCellContainer.cc.
References PHG4CellDefs::SizeBinning::genkey(), PHG4CylinderCell::get_layer(), and PHG4CylinderCell::set_cell_id().
AddCylinderCellSpecifyKey()
PHG4CylinderCellContainer::ConstIterator PHG4CylinderCellContainer::AddCylinderCellSpecifyKey (const PHG4CylinderCellDefs::keytype key, PHG4CylinderCell * newcylinderCell)
Definition at line 75 of file PHG4CylinderCellContainer.cc.
References PHG4CylinderCell::get_layer(), and PHG4CylinderCell::set_cell_id().
findCylinderCell()
PHG4CylinderCell * PHG4CylinderCellContainer::findCylinderCell (PHG4CylinderCellDefs::keytype key)
Definition at line 128 of file PHG4CylinderCellContainer.cc.
findOrAddCylinderCell()
PHG4CylinderCellContainer::Iterator PHG4CylinderCellContainer::findOrAddCylinderCell (PHG4CylinderCellDefs::keytype key)
Definition at line 113 of file PHG4CylinderCellContainer.cc.
References PHG4CylinderCell::get_layer(), and PHG4CylinderCell::set_cell_id().
genkey()
PHG4CylinderCellDefs::keytype PHG4CylinderCellContainer::genkey (const unsigned int detid)
Definition at line 45 of file PHG4CylinderCellContainer.cc.
References PHG4CylinderCellDefs::cell_idbits, and PHG4CylinderCellDefs::keybits.
getCylinderCells() [1/2]
PHG4CylinderCellContainer::ConstRange PHG4CylinderCellContainer::getCylinderCells (const unsigned int detid) const
return all cylinderCells matching a given detid
Definition at line 89 of file PHG4CylinderCellContainer.cc.
References PHG4CylinderCellDefs::cell_idbits, and PHG4CylinderCellDefs::keybits.
getCylinderCells() [2/2]
PHG4CylinderCellContainer::ConstRange PHG4CylinderCellContainer::getCylinderCells (void) const
return all hist
Definition at line 108 of file PHG4CylinderCellContainer.cc.
getLayers()
LayerRange PHG4CylinderCellContainer::getLayers () const inline
Definition at line 74 of file PHG4CylinderCellContainer.h.
References layers.
getTotalEdep()
double PHG4CylinderCellContainer::getTotalEdep () const
Definition at line 141 of file PHG4CylinderCellContainer.cc.
identify()
void PHG4CylinderCellContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 25 of file PHG4CylinderCellContainer.cc.
num_layers()
unsigned int PHG4CylinderCellContainer::num_layers (void) const inline
Definition at line 72 of file PHG4CylinderCellContainer.h.
References layers.
RemoveCylinderCell() [1/2]
void PHG4CylinderCellContainer::RemoveCylinderCell (PHG4CylinderCell * cell) inline
inefficent, use key where possible instead
Definition at line 40 of file PHG4CylinderCellContainer.h.
References cellmap.
RemoveCylinderCell() [2/2]
void PHG4CylinderCellContainer::RemoveCylinderCell (PHG4CylinderCellDefs::keytype key) inline
preferred removal method, key is currently the cell id
Definition at line 35 of file PHG4CylinderCellContainer.h.
References cellmap.
Reset()
void PHG4CylinderCellContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 14 of file PHG4CylinderCellContainer.cc.
size()
unsigned int PHG4CylinderCellContainer::size (void) const inline
Definition at line 70 of file PHG4CylinderCellContainer.h.
References cellmap.
Member Data Documentation
cellmap
Map PHG4CylinderCellContainer::cellmap protected
Definition at line 80 of file PHG4CylinderCellContainer.h.
Referenced by RemoveCylinderCell(), and size().
layers
std::set<int> PHG4CylinderCellContainer::layers protected
Definition at line 81 of file PHG4CylinderCellContainer.h.
Referenced by getLayers(), and num_layers().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellContainer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellContainer.cc