E1039 Software: ParamRunRange Class Reference
ParamRunRange Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/ParamRunRange.h>
Classes
struct RangeItem
Public Member Functions
ParamRunRange ()
~ParamRunRange ()
void Add (const int run_b, const int run_e, const std::string map_id)
bool Find (const std::string map_id)
std::string Find (const int run, const bool exit_on_error=true)
void ReadFromFile (const std::string fn_tsv)
void ReadFromDB (const std::string schema)
void WriteToDB (const std::string schema)
Private Types
typedef std::vector< RangeItem > RangeList
Private Attributes
RangeList m_list
Detailed Description
Definition at line 7 of file ParamRunRange.h.
Member Typedef Documentation
RangeList
typedef std::vector<RangeItem> ParamRunRange::RangeList private
Definition at line 13 of file ParamRunRange.h.
Constructor & Destructor Documentation
ParamRunRange()
ParamRunRange::ParamRunRange () inline
Definition at line 17 of file ParamRunRange.h.
~ParamRunRange()
ParamRunRange::~ParamRunRange () inline
Definition at line 18 of file ParamRunRange.h.
References Add(), Find(), ParamRunRange::RangeItem::map_id, ReadFromDB(), ReadFromFile(), ParamRunRange::RangeItem::run_b, ParamRunRange::RangeItem::run_e, and WriteToDB().
Member Function Documentation
Add()
void ParamRunRange::Add (const int run_b, const int run_e, const std::string map_id)
Definition at line 12 of file ParamRunRange.cc.
References ParamRunRange::RangeItem::map_id, ParamRunRange::RangeItem::run_b, and ParamRunRange::RangeItem::run_e.
Referenced by ~ParamRunRange().
Find() [1/2]
bool ParamRunRange::Find (const std::string map_id)
Definition at line 21 of file ParamRunRange.cc.
Referenced by RunParamBase::SetMapIDbyDB(), RunParamBase::SetMapIDbyFile(), and ~ParamRunRange().
Find() [2/2]
std::string ParamRunRange::Find (const int run, const bool exit_on_error = true)
Definition at line 29 of file ParamRunRange.cc.
ReadFromDB()
void ParamRunRange::ReadFromDB (const std::string schema)
Definition at line 67 of file ParamRunRange.cc.
References DbSvc::DB1, DbSvc::HasTable(), DbSvc::Process(), and DbSvc::UseSchema().
Referenced by RunParamBase::SetMapIDbyDB(), and ~ParamRunRange().
ReadFromFile()
void ParamRunRange::ReadFromFile (const std::string fn_tsv)
Definition at line 41 of file ParamRunRange.cc.
Referenced by RunParamBase::SetMapIDbyFile(), and ~ParamRunRange().
WriteToDB()
void ParamRunRange::WriteToDB (const std::string schema)
Definition at line 83 of file ParamRunRange.cc.
References DbSvc::Con(), DbSvc::CreateTable(), DbSvc::DB1, DbSvc::DropTable(), and DbSvc::UseSchema().
Referenced by RunParamBase::WriteRangeToDB(), and ~ParamRunRange().
Member Data Documentation
m_list
RangeList ParamRunRange::m_list private
Definition at line 14 of file ParamRunRange.h.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/ParamRunRange.h
/home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/ParamRunRange.cc