Class Reference for E1039 Core & Analysis Software: PHFieldConfig Class Reference
PHFieldConfig Class Reference
PHFieldConfig store field configuration information.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig.h>
Public Types
enum FieldConfigTypes {
kFieldUniform = 0 , kField2D = 2 , kField3DCylindrical = 3 , kField3DCartesian = 1 ,
RegionalConst = 4 , kFieldSeaQuest = 5 , kFieldInvalid = 9999
}
Public Member Functions
virtual ~PHFieldConfig ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual FieldConfigTypes get_field_config () const
std::string get_field_config_description () const
virtual void set_field_config (FieldConfigTypes fieldConfig)
virtual const std::string & get_filename () const
virtual void set_filename (const std::string &filename)
virtual double get_magfield_rescale () const
virtual void set_magfield_rescale (double magfieldRescale)
virtual double get_field_mag_x () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_x (double fieldMagX)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_y () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_y (double fieldMagY)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_z () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_z (double fieldMagZ)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual const std::string & get_filename1 () const
field value in Tesla for target field model ONLY for PHFieldConfig_v3
virtual const std::string & get_filename2 () const
virtual double get_magfield_rescale1 () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
virtual double get_magfield_rescale2 () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
virtual void set_taregetmag_y (double fieldMagX)
field value in Tesla for target field model ONLY for PHFieldConfig_v3
virtual double get_taregetmag_y () const
field value in Tesla for target field model ONLY for PHFieldConfig_v3
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
PHFieldConfig ()
pure virtual interface class. not for direct use
Static Protected Attributes
static const std::string kInvalid_FileName
Detailed Description
PHFieldConfig store field configuration information.
Definition at line 19 of file PHFieldConfig.h.
Member Enumeration Documentation
FieldConfigTypes
enum PHFieldConfig::FieldConfigTypes
Enumerator
kFieldUniform
Constant field.
kField2D
2D field map expressed in cylindrical coordinates
kField3DCylindrical
3D field map expressed in cylindrical coordinates
kField3DCartesian
3D field map expressed in Cartesian coordinates
RegionalConst
kFieldSeaQuest
kFieldInvalid
invalid value
Definition at line 38 of file PHFieldConfig.h.
Constructor & Destructor Documentation
~PHFieldConfig()
PHFieldConfig::~PHFieldConfig () virtual
Definition at line 26 of file PHFieldConfig.cc.
PHFieldConfig()
PHFieldConfig::PHFieldConfig () protected
pure virtual interface class. not for direct use
Definition at line 22 of file PHFieldConfig.cc.
Member Function Documentation
get_field_config()
PHFieldConfig::FieldConfigTypes PHFieldConfig::get_field_config () const virtual
Reimplemented in PHFieldConfig_v3, PHFieldConfig_v2, and PHFieldConfig_v1.
Definition at line 76 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
get_field_config_description()
string PHFieldConfig::get_field_config_description () const
Definition at line 30 of file PHFieldConfig.cc.
References RegionalConst.
Referenced by PHFieldConfig_v1::identify(), PHFieldConfig_v2::identify(), and PHFieldConfig_v3::identify().
get_field_mag_x()
double PHFieldConfig::get_field_mag_x () const virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfig_v2.
Definition at line 118 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
get_field_mag_y()
double PHFieldConfig::get_field_mag_y () const virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfig_v2.
Definition at line 129 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
get_field_mag_z()
double PHFieldConfig::get_field_mag_z () const virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfig_v2.
Definition at line 140 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
get_filename()
const std::string & PHFieldConfig::get_filename () const virtual
Reimplemented in PHFieldConfig_v1.
Definition at line 85 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
get_filename1()
virtual const std::string& PHFieldConfig::get_filename1 () const inline virtual
field value in Tesla for target field model ONLY for PHFieldConfig_v3
field value in Tesla for target field model ONLY for PHFieldConfig_v3 ONLY for PHFieldConfig_v3
Reimplemented in PHFieldConfig_v3.
Definition at line 93 of file PHFieldConfig.h.
References kInvalid_FileName.
Referenced by PHFieldUtility::BuildFieldMap().
get_filename2()
virtual const std::string& PHFieldConfig::get_filename2 () const inline virtual
Reimplemented in PHFieldConfig_v3.
Definition at line 94 of file PHFieldConfig.h.
References kInvalid_FileName.
Referenced by PHFieldUtility::BuildFieldMap().
get_magfield_rescale()
double PHFieldConfig::get_magfield_rescale () const virtual
Reimplemented in PHFieldConfig_v1.
Definition at line 94 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
get_magfield_rescale1()
double PHFieldConfig::get_magfield_rescale1 () const virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
Reimplemented in PHFieldConfig_v3.
Definition at line 104 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
get_magfield_rescale2()
double PHFieldConfig::get_magfield_rescale2 () const virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
Reimplemented in PHFieldConfig_v3.
Definition at line 111 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
get_taregetmag_y()
double PHFieldConfig::get_taregetmag_y () const virtual
field value in Tesla for target field model ONLY for PHFieldConfig_v3
Reimplemented in PHFieldConfig_v3.
Definition at line 152 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
identify()
void PHFieldConfig::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHFieldConfig_v3, PHFieldConfig_v2, and PHFieldConfig_v1.
Definition at line 60 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap(), and PHFieldUtility::GetFieldConfigNode().
isValid()
int PHFieldConfig::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in PHFieldConfig_v3, PHFieldConfig_v2, and PHFieldConfig_v1.
Definition at line 71 of file PHFieldConfig.cc.
Reset()
void PHFieldConfig::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in PHFieldConfig_v3, PHFieldConfig_v2, and PHFieldConfig_v1.
Definition at line 66 of file PHFieldConfig.cc.
set_field_config()
void PHFieldConfig::set_field_config (PHFieldConfig::FieldConfigTypes fieldConfig) virtual
Reimplemented in PHFieldConfig_v3, and PHFieldConfig_v1.
Definition at line 81 of file PHFieldConfig.cc.
set_field_mag_x()
void PHFieldConfig::set_field_mag_x (double fieldMagX) virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfig_v2.
Definition at line 124 of file PHFieldConfig.cc.
set_field_mag_y()
void PHFieldConfig::set_field_mag_y (double fieldMagY) virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfig_v2.
Definition at line 135 of file PHFieldConfig.cc.
set_field_mag_z()
void PHFieldConfig::set_field_mag_z (double fieldMagZ) virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfig_v2.
Definition at line 146 of file PHFieldConfig.cc.
set_filename()
void PHFieldConfig::set_filename (const std::string & filename) virtual
Reimplemented in PHFieldConfig_v1.
Definition at line 90 of file PHFieldConfig.cc.
set_magfield_rescale()
void PHFieldConfig::set_magfield_rescale (double magfieldRescale) virtual
Reimplemented in PHFieldConfig_v1.
Definition at line 99 of file PHFieldConfig.cc.
set_taregetmag_y()
void PHFieldConfig::set_taregetmag_y (double fieldMagX) virtual
field value in Tesla for target field model ONLY for PHFieldConfig_v3
Reimplemented in PHFieldConfig_v3.
Definition at line 158 of file PHFieldConfig.cc.
Member Data Documentation
kInvalid_FileName
const std::string PHFieldConfig::kInvalid_FileName static protected
Definition at line 106 of file PHFieldConfig.h.
Referenced by get_filename1(), and get_filename2().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig.cc