Class Reference for E1039 Core & Analysis Software: PHG4VtxPointv1 Class Reference
PHG4VtxPointv1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4VtxPointv1.h>
Public Member Functions
PHG4VtxPointv1 ()
PHG4VtxPointv1 (const PHG4VtxPoint *vtx)
PHG4VtxPointv1 (const double x, const double y, const double z, const double t, const int id_value=INT_MIN)
virtual ~PHG4VtxPointv1 ()
void set_x (const double r)
void set_y (const double r)
void set_z (const double r)
void set_t (const double r)
void set_id (const int i)
double get_x () const
double get_y () const
double get_z () const
double get_t () const
int get_id () const
void identify (std::ostream &os=std::cout) const
Public Member Functions inherited from PHG4VtxPoint
virtual ~PHG4VtxPoint ()
bool operator== (const PHG4VtxPoint &) const
comparison of vertex value only, not on the id, per algorithm requirement in PHG4TruthInfoContainer::AddPrimaryVertex
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
double vx
double vy
double vz
double t0
int id
id tag for this vertex
Additional Inherited Members
Protected Member Functions inherited from PHG4VtxPoint
PHG4VtxPoint ()
Detailed Description
Definition at line 7 of file PHG4VtxPointv1.h.
Constructor & Destructor Documentation
PHG4VtxPointv1() [1/3]
PHG4VtxPointv1::PHG4VtxPointv1 () inline
Definition at line 10 of file PHG4VtxPointv1.h.
PHG4VtxPointv1() [2/3]
PHG4VtxPointv1::PHG4VtxPointv1 (const PHG4VtxPoint * vtx) inline
Definition at line 18 of file PHG4VtxPointv1.h.
PHG4VtxPointv1() [3/3]
PHG4VtxPointv1::PHG4VtxPointv1 (const double x, const double y, const double z, const double t, const int id_value = INT_MIN) inline
Definition at line 26 of file PHG4VtxPointv1.h.
~PHG4VtxPointv1()
virtual PHG4VtxPointv1::~PHG4VtxPointv1 () inline virtual
Definition at line 34 of file PHG4VtxPointv1.h.
Member Function Documentation
get_id()
int PHG4VtxPointv1::get_id () const inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 46 of file PHG4VtxPointv1.h.
References id.
get_t()
double PHG4VtxPointv1::get_t () const inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 45 of file PHG4VtxPointv1.h.
References t0.
get_x()
double PHG4VtxPointv1::get_x () const inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 42 of file PHG4VtxPointv1.h.
References vx.
get_y()
double PHG4VtxPointv1::get_y () const inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 43 of file PHG4VtxPointv1.h.
References vy.
get_z()
double PHG4VtxPointv1::get_z () const inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 44 of file PHG4VtxPointv1.h.
References vz.
identify()
void PHG4VtxPointv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4VtxPoint.
Definition at line 9 of file PHG4VtxPointv1.cc.
set_id()
void PHG4VtxPointv1::set_id (const int i) inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 40 of file PHG4VtxPointv1.h.
Referenced by PHG4DSTReader::process_event().
set_t()
void PHG4VtxPointv1::set_t (const double r) inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 39 of file PHG4VtxPointv1.h.
References t0.
Referenced by PHG4DSTReader::process_event(), and PHG4InEventReadBack::process_event().
set_x()
void PHG4VtxPointv1::set_x (const double r) inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 36 of file PHG4VtxPointv1.h.
References vx.
Referenced by PHG4DSTReader::process_event(), and PHG4InEventReadBack::process_event().
set_y()
void PHG4VtxPointv1::set_y (const double r) inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 37 of file PHG4VtxPointv1.h.
References vy.
Referenced by PHG4DSTReader::process_event(), and PHG4InEventReadBack::process_event().
set_z()
void PHG4VtxPointv1::set_z (const double r) inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 38 of file PHG4VtxPointv1.h.
References vz.
Referenced by PHG4DSTReader::process_event(), and PHG4InEventReadBack::process_event().
Member Data Documentation
id
int PHG4VtxPointv1::id protected
id tag for this vertex
Definition at line 58 of file PHG4VtxPointv1.h.
Referenced by get_id().
t0
double PHG4VtxPointv1::t0 protected
Definition at line 55 of file PHG4VtxPointv1.h.
Referenced by get_t(), and set_t().
vx
double PHG4VtxPointv1::vx protected
Definition at line 52 of file PHG4VtxPointv1.h.
Referenced by get_x(), and set_x().
vy
double PHG4VtxPointv1::vy protected
Definition at line 53 of file PHG4VtxPointv1.h.
Referenced by get_y(), and set_y().
vz
double PHG4VtxPointv1::vz protected
Definition at line 54 of file PHG4VtxPointv1.h.
Referenced by get_z(), and set_z().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4VtxPointv1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4VtxPointv1.cc