Class Reference for E1039 Core & Analysis Software: AnaBase Class Reference
AnaBase Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/AnaBase.h>
Public Member Functions
virtual ~AnaBase ()
virtual void SetInputTreeName (const std::string name)
virtual void SetInputBranchName (const std::string name)
virtual void Init ()
virtual void Analyze ()
virtual void End ()
virtual void ReadEventsFromFileList (const char *fn_list, const int n_max=0)
virtual void ReadEvents (const char *fname)
Protected Member Functions
AnaBase (const std::string label)
virtual void ProcessOneEvent ()
Protected Attributes
std::string m_label
std::string m_tree_name
std::string m_branch_name
std::string m_dir_out
std::ofstream m_ofs
Detailed Description
Definition at line 6 of file AnaBase.h.
Constructor & Destructor Documentation
AnaBase::AnaBase (const std::string label) protected
Definition at line 7 of file AnaBase.cc.
References m_dir_out, m_label, and m_ofs.
AnaBase::~AnaBase () virtual
Definition at line 20 of file AnaBase.cc.
References m_dir_out, and m_ofs.
Member Function Documentation
void AnaBase::Analyze () virtual
Reimplemented in AnaBG, ReAnaSignal, AnaSignal, and ReAnaBG.
Definition at line 42 of file AnaBase.cc.
void AnaBase::End () virtual
Reimplemented in AnaBG, ReAnaSignal, AnaSignal, and ReAnaBG.
Definition at line 47 of file AnaBase.cc.
void AnaBase::Init () virtual
Reimplemented in AnaBG, ReAnaSignal, AnaSignal, and ReAnaBG.
Definition at line 37 of file AnaBase.cc.
void AnaBase::ProcessOneEvent () protected virtual
Reimplemented in AnaBG, ReAnaSignal, AnaSignal, and ReAnaBG.
Definition at line 78 of file AnaBase.cc.
void AnaBase::ReadEvents (const char * fname) virtual
Reimplemented in AnaBG, and AnaSignal.
Definition at line 73 of file AnaBase.cc.
Referenced by ReadEventsFromFileList().
void AnaBase::ReadEventsFromFileList (const char * fn_list, const int n_max = 0) virtual
Definition at line 52 of file AnaBase.cc.
References m_ofs, and ReadEvents().
Referenced by ApplyRoadset2BG(), ApplyRoadset2Signal(), GenerateRoad(), and GenerateRoadBySignal().
virtual void AnaBase::SetInputBranchName (const std::string name) inline virtual
Definition at line 20 of file AnaBase.h.
References m_branch_name.
Referenced by ApplyRoadset2BG(), ApplyRoadset2Signal(), GenerateRoad(), and GenerateRoadBySignal().
virtual void AnaBase::SetInputTreeName (const std::string name) inline virtual
Definition at line 19 of file AnaBase.h.
References m_tree_name.
Referenced by ApplyRoadset2BG(), ApplyRoadset2Signal(), GenerateRoad(), and GenerateRoadBySignal().
Member Data Documentation
std::string AnaBase::m_branch_name protected
Definition at line 10 of file AnaBase.h.
Referenced by AnaSignal::ReadEvents(), AnaBG::ReadEvents(), and SetInputBranchName().
std::string AnaBase::m_dir_out protected
Definition at line 11 of file AnaBase.h.
Referenced by AnaBase(), AnaBG::DrawInteMax(), DrawRoadset::DrawOneSet(), ReAnaSignal::DrawOneVar(), ReAnaSignal::DrawOneVar2D(), ReAnaSignal::Init(), AnaBG::Init(), and ~AnaBase().
std::string AnaBase::m_label protected
Definition at line 8 of file AnaBase.h.
Referenced by AnaBase().
std::ofstream AnaBase::m_ofs protected
Definition at line 12 of file AnaBase.h.
Referenced by AnaBase(), ReAnaBG::Analyze(), AnaBG::Analyze(), GenRoadset::DisableRoadsByFoM(), GenRoadset::DisableRoadsByWeightFraction(), AnaBG::DrawInteMax(), AnaBG::Init(), ReadEventsFromFileList(), and ~AnaBase().
std::string AnaBase::m_tree_name protected
Definition at line 9 of file AnaBase.h.
Referenced by AnaSignal::ReadEvents(), AnaBG::ReadEvents(), and SetInputTreeName().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/AnaBase.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/AnaBase.cc