Class Reference for E1039 Core & Analysis Software: SQSpillMap_v1 Class Reference
SQSpillMap_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSpillMap_v1.h>
Public Member Functions
SQSpillMap_v1 ()
SQSpillMap_v1 (const SQSpillMap_v1 &hitmap)
SQSpillMap_v1 & operator= (const SQSpillMap_v1 &hitmap)
virtual ~SQSpillMap_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQSpillMap * Clone () const
bool empty () const
Return 'true' if this object holds no spill.
size_t size () const
Return the number of spills held.
size_t count (unsigned int idkey) const
Return the number of spills having spill ID = 'idkey'. Must be '0' or '1'.
void clear ()
Clear the list.
const SQSpill * get (unsigned int idkey) const
Return the SQSpill entry having spill ID = 'idkey'. Return '0' if no entry exists.
SQSpill * get (unsigned int idkey)
Return the SQSpill entry having spill ID = 'idkey'. Return '0' if no entry exists.
SQSpill * insert (const SQSpill *hit)
Insert the given SQSpill object.
size_t erase (unsigned int idkey)
Erase the SQSpill entry having spill ID = 'idkey'.
ConstIter begin () const
Return the const begin iterator.
ConstIter find (unsigned int idkey) const
Return the const iterator of the SQSpill entry having spill ID = 'idkey'.
ConstIter end () const
Return the const end iterator.
Iter begin ()
Return the begin iterator.
Iter find (unsigned int idkey)
Return the iterator of the SQSpill entry having spill ID = 'idkey'.
Iter end ()
Return the end iterator.
Public Member Functions inherited from SQSpillMap
virtual ~SQSpillMap ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from SQSpillMap
typedef std::map< unsigned int, SQSpill * > SpillMap
typedef std::map< unsigned int, SQSpill * >::const_iterator ConstIter
typedef std::map< unsigned int, SQSpill * >::iterator Iter
Protected Member Functions inherited from SQSpillMap
SQSpillMap ()
Detailed Description
Definition at line 18 of file SQSpillMap_v1.h.
Constructor & Destructor Documentation
SQSpillMap_v1() [1/2]
SQSpillMap_v1::SQSpillMap_v1 ()
Referenced by Clone().
SQSpillMap_v1() [2/2]
SQSpillMap_v1::SQSpillMap_v1 (const SQSpillMap_v1 & hitmap)
Definition at line 22 of file SQSpillMap_v1.cxx.
References begin(), SQSpill::Clone(), end(), and SQSpill::get_spill_id().
~SQSpillMap_v1()
SQSpillMap_v1::~SQSpillMap_v1 () virtual
Definition at line 43 of file SQSpillMap_v1.cxx.
References Reset().
Member Function Documentation
begin() [1/2]
Iter SQSpillMap_v1::begin () inline virtual
Return the begin iterator.
Reimplemented from SQSpillMap.
Definition at line 48 of file SQSpillMap_v1.h.
begin() [2/2]
ConstIter SQSpillMap_v1::begin () const inline virtual
Return the const begin iterator.
Reimplemented from SQSpillMap.
Definition at line 44 of file SQSpillMap_v1.h.
Referenced by operator=(), and SQSpillMap_v1().
clear()
void SQSpillMap_v1::clear () inline virtual
Clear the list.
Reimplemented from SQSpillMap.
Definition at line 35 of file SQSpillMap_v1.h.
References Reset().
Clone()
SQSpillMap* SQSpillMap_v1::Clone () const inline virtual
Reimplemented from SQSpillMap.
Definition at line 30 of file SQSpillMap_v1.h.
References SQSpillMap_v1().
count()
size_t SQSpillMap_v1::count (unsigned int idkey) const inline virtual
Return the number of spills having spill ID = 'idkey'. Must be '0' or '1'.
Reimplemented from SQSpillMap.
Definition at line 34 of file SQSpillMap_v1.h.
empty()
bool SQSpillMap_v1::empty () const inline virtual
Return 'true' if this object holds no spill.
Reimplemented from SQSpillMap.
Definition at line 32 of file SQSpillMap_v1.h.
end() [1/2]
Iter SQSpillMap_v1::end () inline virtual
Return the end iterator.
Reimplemented from SQSpillMap.
Definition at line 50 of file SQSpillMap_v1.h.
end() [2/2]
ConstIter SQSpillMap_v1::end () const inline virtual
Return the const end iterator.
Reimplemented from SQSpillMap.
Definition at line 46 of file SQSpillMap_v1.h.
Referenced by operator=(), and SQSpillMap_v1().
erase()
size_t SQSpillMap_v1::erase (unsigned int idkey) inline virtual
Erase the SQSpill entry having spill ID = 'idkey'.
Reimplemented from SQSpillMap.
Definition at line 40 of file SQSpillMap_v1.h.
find() [1/2]
Iter SQSpillMap_v1::find (unsigned int idkey) inline virtual
Return the iterator of the SQSpill entry having spill ID = 'idkey'.
Reimplemented from SQSpillMap.
Definition at line 49 of file SQSpillMap_v1.h.
find() [2/2]
ConstIter SQSpillMap_v1::find (unsigned int idkey) const inline virtual
Return the const iterator of the SQSpill entry having spill ID = 'idkey'.
Reimplemented from SQSpillMap.
Definition at line 45 of file SQSpillMap_v1.h.
get() [1/2]
SQSpill * SQSpillMap_v1::get (unsigned int idkey) virtual
Return the SQSpill entry having spill ID = 'idkey'. Return '0' if no entry exists.
Reimplemented from SQSpillMap.
Definition at line 68 of file SQSpillMap_v1.cxx.
References NULL.
get() [2/2]
const SQSpill * SQSpillMap_v1::get (unsigned int idkey) const virtual
Return the SQSpill entry having spill ID = 'idkey'. Return '0' if no entry exists.
Reimplemented from SQSpillMap.
Definition at line 62 of file SQSpillMap_v1.cxx.
References NULL.
identify()
void SQSpillMap_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQSpillMap.
Definition at line 57 of file SQSpillMap_v1.cxx.
insert()
SQSpill * SQSpillMap_v1::insert (const SQSpill * hit) virtual
Insert the given SQSpill object.
Reimplemented from SQSpillMap.
Definition at line 74 of file SQSpillMap_v1.cxx.
References SQSpill::Clone(), and SQSpill::get_spill_id().
isValid()
int SQSpillMap_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQSpillMap.
Definition at line 29 of file SQSpillMap_v1.h.
operator=()
SQSpillMap_v1 & SQSpillMap_v1::operator= (const SQSpillMap_v1 & hitmap)
Definition at line 32 of file SQSpillMap_v1.cxx.
References begin(), SQSpill::Clone(), end(), SQSpill::get_spill_id(), and Reset().
Reset()
void SQSpillMap_v1::Reset () virtual
Clear Event.
Reimplemented from SQSpillMap.
Definition at line 47 of file SQSpillMap_v1.cxx.
Referenced by clear(), operator=(), and ~SQSpillMap_v1().
size()
size_t SQSpillMap_v1::size (void) const inline virtual
Return the number of spills held.
Reimplemented from SQSpillMap.
Definition at line 33 of file SQSpillMap_v1.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSpillMap_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSpillMap_v1.cxx