Class Reference for E1039 Core & Analysis Software: PHG4CollimatorDetector Class Reference
PHG4CollimatorDetector Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CollimatorDetector.h>
Public Member Functions
PHG4CollimatorDetector (PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam="BLOCK", const int lyr=0)
constructor
virtual ~PHG4CollimatorDetector (void)
destructor
virtual void Construct (G4LogicalVolume *world)
construct
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
volume accessors
bool IsInBlock (G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 10 of file PHG4CollimatorDetector.h.
Constructor & Destructor Documentation
PHG4CollimatorDetector()
PHG4CollimatorDetector::PHG4CollimatorDetector (PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam = "BLOCK", const int lyr = 0)
constructor
Definition at line 27 of file PHG4CollimatorDetector.cc.
~PHG4CollimatorDetector()
virtual PHG4CollimatorDetector::~PHG4CollimatorDetector (void) inline virtual
destructor
Definition at line 19 of file PHG4CollimatorDetector.h.
Member Function Documentation
Construct()
void PHG4CollimatorDetector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 177 of file PHG4CollimatorDetector.cc.
References PHParameters::get_double_param(), PHG4Detector::GetName(), PHG4Detector::overlapcheck, and PHG4Utils::SetColour().
get_Layer()
int PHG4CollimatorDetector::get_Layer () const inline
Definition at line 32 of file PHG4CollimatorDetector.h.
Referenced by PHG4CollimatorSteppingAction::UserSteppingAction().
IsInBlock()
bool PHG4CollimatorDetector::IsInBlock (G4VPhysicalVolume * volume) const
Definition at line 35 of file PHG4CollimatorDetector.cc.
Referenced by PHG4CollimatorSteppingAction::UserSteppingAction().
SuperDetector() [1/2]
const std::string PHG4CollimatorDetector::SuperDetector () const inline
Definition at line 31 of file PHG4CollimatorDetector.h.
SuperDetector() [2/2]
void PHG4CollimatorDetector::SuperDetector (const std::string & name) inline
Definition at line 30 of file PHG4CollimatorDetector.h.
References PHG4Detector::name.
Referenced by PHG4CollimatorSubsystem::InitRunSubsystem(), and PHG4CollimatorSteppingAction::SetInterfacePointers().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CollimatorDetector.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CollimatorDetector.cc