Class Reference for E1039 Core & Analysis Software: PHG4Cell Class Reference
PHG4Cell Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4Cell.h>
Public Types
enum PROPERTY {
prop_stave_index = 1 , prop_half_stave_index = 2 , prop_module_index = 3 , prop_chip_index = 4 ,
prop_pixel_index = 5 , prop_phibin = 6 , prop_zbin = 7 , prop_ladder_z_index = 8 ,
prop_ladder_phi_index = 9 , prop_edep = 21 , prop_eion = 22 , prop_light_yield = 23 ,
prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1 , type_uint = 2 , type_float = 3 , type_unknown = -1 }
typedef std::map< PHG4HitDefs::keytype, float > EdepMap
typedef EdepMap::iterator EdepIterator
typedef EdepMap::const_iterator EdepConstIterator
typedef std::pair< EdepIterator, EdepIterator > EdepRange
typedef std::pair< EdepConstIterator, EdepConstIterator > EdepConstRange
typedef std::map< int, float > ShowerEdepMap
typedef ShowerEdepMap::iterator ShowerEdepIterator
typedef ShowerEdepMap::const_iterator ShowerEdepConstIterator
typedef std::pair< ShowerEdepIterator, ShowerEdepIterator > ShowerEdepRange
typedef std::pair< ShowerEdepConstIterator, ShowerEdepConstIterator > ShowerEdepConstRange
typedef std::pair< unsigned short, std::map< int, int > > tpccompress
typedef std::map< unsigned short, tpccompress > tpctod
Public Member Functions
virtual ~PHG4Cell ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Copy (PHG4Cell const &g4cell)
virtual void Reset ()
virtual void set_cellid (const PHG4CellDefs::keytype i)
virtual PHG4CellDefs::keytype get_cellid () const
virtual bool has_binning (const PHG4CellDefs::CellBinning) const
virtual void add_edep (const PHG4HitDefs::keytype g4hitid, const float edep)
virtual void add_edep (const PHG4HitDefs::keytype g4hitid, const int tbin, const float edep)
virtual void add_shower_edep (const int g4showerid, const float edep)
virtual EdepConstRange get_g4hits ()
virtual ShowerEdepConstRange get_g4showers ()
virtual short int get_detid () const
short int get_layer () const
virtual void add_edep (const float f)
virtual double get_edep () const
virtual void add_eion (const float f)
virtual double get_eion () const
virtual void add_light_yield (const float lightYield)
virtual float get_light_yield () const
virtual void set_chip_index (const int i)
virtual int get_chip_index () const
virtual void set_half_stave_index (const int i)
virtual int get_half_stave_index () const
virtual void set_ladder_phi_index (const int i)
virtual int get_ladder_phi_index () const
virtual void set_ladder_z_index (const int i)
virtual int get_ladder_z_index () const
virtual void set_module_index (const int i)
virtual int get_module_index () const
virtual void set_phibin (const int i)
virtual int get_phibin () const
virtual void set_pixel_index (const int i)
virtual int get_pixel_index () const
virtual void set_stave_index (const int i)
virtual int get_stave_index () const
virtual void set_zbin (const int i)
virtual int get_zbin () const
virtual void print () const
virtual bool has_property (const PROPERTY prop_id) const
virtual float get_property_float (const PROPERTY prop_id) const
virtual int get_property_int (const PROPERTY prop_id) const
virtual unsigned int get_property_uint (const PROPERTY prop_id) const
virtual void set_property (const PROPERTY prop_id, const float value)
virtual void set_property (const PROPERTY prop_id, const int value)
virtual void set_property (const PROPERTY prop_id, const unsigned int value)
Static Public Member Functions
static std::pair< const std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Member Functions
PHG4Cell ()
virtual unsigned int get_property_nocheck (const PROPERTY prop_id) const
virtual void set_property_nocheck (const PROPERTY prop_id, const unsigned int)
Friends
std::ostream & operator<< (std::ostream &stream, const PHG4Cell *cell)
Detailed Description
Definition at line 12 of file PHG4Cell.h.
Member Typedef Documentation
EdepConstIterator
typedef EdepMap::const_iterator PHG4Cell::EdepConstIterator
Definition at line 17 of file PHG4Cell.h.
EdepConstRange
typedef std::pair<EdepConstIterator, EdepConstIterator> PHG4Cell::EdepConstRange
Definition at line 19 of file PHG4Cell.h.
EdepIterator
typedef EdepMap::iterator PHG4Cell::EdepIterator
Definition at line 16 of file PHG4Cell.h.
EdepMap
typedef std::map<PHG4HitDefs::keytype, float> PHG4Cell::EdepMap
Definition at line 15 of file PHG4Cell.h.
EdepRange
typedef std::pair<EdepIterator, EdepIterator> PHG4Cell::EdepRange
Definition at line 18 of file PHG4Cell.h.
ShowerEdepConstIterator
typedef ShowerEdepMap::const_iterator PHG4Cell::ShowerEdepConstIterator
Definition at line 23 of file PHG4Cell.h.
ShowerEdepConstRange
typedef std::pair<ShowerEdepConstIterator, ShowerEdepConstIterator> PHG4Cell::ShowerEdepConstRange
Definition at line 25 of file PHG4Cell.h.
ShowerEdepIterator
typedef ShowerEdepMap::iterator PHG4Cell::ShowerEdepIterator
Definition at line 22 of file PHG4Cell.h.
ShowerEdepMap
typedef std::map<int, float> PHG4Cell::ShowerEdepMap
Definition at line 21 of file PHG4Cell.h.
ShowerEdepRange
typedef std::pair<ShowerEdepIterator, ShowerEdepIterator> PHG4Cell::ShowerEdepRange
Definition at line 24 of file PHG4Cell.h.
tpccompress
typedef std::pair<unsigned short,std::map<int,int> > PHG4Cell::tpccompress
Definition at line 27 of file PHG4Cell.h.
tpctod
typedef std::map<unsigned short,tpccompress> PHG4Cell::tpctod
Definition at line 28 of file PHG4Cell.h.
Member Enumeration Documentation
PROPERTY
enum PHG4Cell::PROPERTY
Procedure to add a new PROPERTY tag: 1.add new tag below with unique value, 2.add a short name to PHG4Cell::get_property_info
Enumerator
prop_stave_index
Maps coordinates.
prop_half_stave_index
prop_module_index
prop_chip_index
prop_pixel_index
prop_phibin
prop_zbin
prop_ladder_z_index
prop_ladder_phi_index
prop_edep
deposited energy
prop_eion
ionizing energy loss
prop_light_yield
for scintillation detectors, the amount of light produced
prop_MAX_NUMBER
max limit in order to fit into 8 bit unsigned number
Definition at line 110 of file PHG4Cell.h.
PROPERTY_TYPE
enum PHG4Cell::PROPERTY_TYPE
Enumerator
type_int
type_uint
type_float
type_unknown
Definition at line 136 of file PHG4Cell.h.
Constructor & Destructor Documentation
~PHG4Cell()
virtual PHG4Cell::~PHG4Cell () inline virtual
Definition at line 31 of file PHG4Cell.h.
PHG4Cell()
PHG4Cell::PHG4Cell () inline protected
Definition at line 156 of file PHG4Cell.h.
Member Function Documentation
add_edep() [1/3]
virtual void PHG4Cell::add_edep (const float f) inline virtual
Reimplemented in PHG4Cellv2, and PHG4Cellv1.
Definition at line 64 of file PHG4Cell.h.
add_edep() [2/3]
virtual void PHG4Cell::add_edep (const PHG4HitDefs::keytype g4hitid, const float edep) inline virtual
Reimplemented in PHG4CylinderCellv1, PHG4CylinderCell, PHG4Cellv2, and PHG4Cellv1.
Definition at line 45 of file PHG4Cell.h.
Referenced by PHG4CylinderCellReco::process_event(), and PHG4CylinderCellTPCReco::process_event().
add_edep() [3/3]
virtual void PHG4Cell::add_edep (const PHG4HitDefs::keytype g4hitid, const int tbin, const float edep) inline virtual
Definition at line 46 of file PHG4Cell.h.
add_eion()
virtual void PHG4Cell::add_eion (const float f) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 67 of file PHG4Cell.h.
add_light_yield()
virtual void PHG4Cell::add_light_yield (const float lightYield) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 70 of file PHG4Cell.h.
Referenced by PHG4CylinderCellReco::process_event().
add_shower_edep()
virtual void PHG4Cell::add_shower_edep (const int g4showerid, const float edep) inline virtual
Reimplemented in PHG4CylinderCellv1, PHG4CylinderCell, and PHG4Cellv1.
Definition at line 48 of file PHG4Cell.h.
Referenced by PHG4CylinderCellReco::process_event(), and PHG4CylinderCellTPCReco::process_event().
check_property()
bool PHG4Cell::check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type) static
Definition at line 78 of file PHG4Cell.cc.
Referenced by PHG4Cellv1::add_property(), PHG4Cellv1::get_property_float(), PHG4Cellv1::get_property_int(), PHG4Cellv1::get_property_uint(), and PHG4Cellv1::set_property().
Copy()
void PHG4Cell::Copy (PHG4Cell const & g4cell) virtual
Definition at line 8 of file PHG4Cell.cc.
References get_cellid(), get_property_nocheck(), and has_property().
get_cellid()
virtual PHG4CellDefs::keytype PHG4Cell::get_cellid () const inline virtual
Reimplemented in PHG4Cellv2, and PHG4Cellv1.
Definition at line 41 of file PHG4Cell.h.
Referenced by PHG4CellContainer::AddCell(), and Copy().
get_chip_index()
virtual int PHG4Cell::get_chip_index () const inline virtual
Reimplemented in PHG4CylinderCell, and PHG4Cellv1.
Definition at line 76 of file PHG4Cell.h.
get_detid()
virtual short int PHG4Cell::get_detid () const inline virtual
Reimplemented in PHG4Cellv2, and PHG4Cellv1.
Definition at line 60 of file PHG4Cell.h.
Referenced by get_layer().
get_edep()
virtual double PHG4Cell::get_edep () const inline virtual
Reimplemented in PHG4CylinderCellv1, PHG4CylinderCell, PHG4Cellv2, and PHG4Cellv1.
Definition at line 65 of file PHG4Cell.h.
Referenced by PHG4CylinderCellReco::process_event().
get_eion()
virtual double PHG4Cell::get_eion () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 68 of file PHG4Cell.h.
get_g4hits()
virtual EdepConstRange PHG4Cell::get_g4hits () inline virtual
Reimplemented in PHG4CylinderCellv1, PHG4CylinderCell, PHG4Cellv2, and PHG4Cellv1.
Definition at line 50 of file PHG4Cell.h.
get_g4showers()
virtual ShowerEdepConstRange PHG4Cell::get_g4showers () inline virtual
Reimplemented in PHG4CylinderCellv1, PHG4CylinderCell, and PHG4Cellv1.
Definition at line 55 of file PHG4Cell.h.
get_half_stave_index()
virtual int PHG4Cell::get_half_stave_index () const inline virtual
Reimplemented in PHG4CylinderCell, and PHG4Cellv1.
Definition at line 79 of file PHG4Cell.h.
get_ladder_phi_index()
virtual int PHG4Cell::get_ladder_phi_index () const inline virtual
Reimplemented in PHG4CylinderCellv2, PHG4CylinderCell, and PHG4Cellv1.
Definition at line 82 of file PHG4Cell.h.
get_ladder_z_index()
virtual int PHG4Cell::get_ladder_z_index () const inline virtual
Reimplemented in PHG4CylinderCellv2, PHG4CylinderCell, and PHG4Cellv1.
Definition at line 85 of file PHG4Cell.h.
get_layer()
short int PHG4Cell::get_layer () const inline
Definition at line 62 of file PHG4Cell.h.
References get_detid().
get_light_yield()
virtual float PHG4Cell::get_light_yield () const inline virtual
Reimplemented in PHG4CylinderCellv1, PHG4CylinderCell, and PHG4Cellv1.
Definition at line 71 of file PHG4Cell.h.
get_module_index()
virtual int PHG4Cell::get_module_index () const inline virtual
Reimplemented in PHG4CylinderCell, and PHG4Cellv1.
Definition at line 88 of file PHG4Cell.h.
get_phibin()
virtual int PHG4Cell::get_phibin () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 91 of file PHG4Cell.h.
get_pixel_index()
virtual int PHG4Cell::get_pixel_index () const inline virtual
Reimplemented in PHG4CylinderCell, and PHG4Cellv1.
Definition at line 94 of file PHG4Cell.h.
get_property_float()
virtual float PHG4Cell::get_property_float (const PROPERTY prop_id) const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 145 of file PHG4Cell.h.
get_property_info()
std::pair< const std::string, PHG4Cell::PROPERTY_TYPE > PHG4Cell::get_property_info (PROPERTY prop_id) static
Definition at line 42 of file PHG4Cell.cc.
References type_float, and type_int.
Referenced by PHG4Cellv1::add_property(), PHG4Cellv1::get_property_float(), PHG4Cellv1::get_property_int(), PHG4Cellv1::get_property_uint(), PHG4Cellv1::identify(), and PHG4Cellv1::set_property().
get_property_int()
virtual int PHG4Cell::get_property_int (const PROPERTY prop_id) const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 146 of file PHG4Cell.h.
get_property_nocheck()
virtual unsigned int PHG4Cell::get_property_nocheck (const PROPERTY prop_id) const inline protected virtual
Reimplemented in PHG4Cellv1.
Definition at line 157 of file PHG4Cell.h.
Referenced by Copy().
get_property_type()
string PHG4Cell::get_property_type (const PROPERTY_TYPE prop_type) static
Definition at line 89 of file PHG4Cell.cc.
Referenced by PHG4Cellv1::add_property(), PHG4Cellv1::get_property_float(), PHG4Cellv1::get_property_int(), PHG4Cellv1::get_property_uint(), and PHG4Cellv1::set_property().
get_property_uint()
virtual unsigned int PHG4Cell::get_property_uint (const PROPERTY prop_id) const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 147 of file PHG4Cell.h.
get_stave_index()
virtual int PHG4Cell::get_stave_index () const inline virtual
Reimplemented in PHG4CylinderCell, and PHG4Cellv1.
Definition at line 97 of file PHG4Cell.h.
get_zbin()
virtual int PHG4Cell::get_zbin () const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 102 of file PHG4Cell.h.
has_binning()
virtual bool PHG4Cell::has_binning (const PHG4CellDefs::CellBinning) const inline virtual
Reimplemented in PHG4Cellv2, and PHG4Cellv1.
Definition at line 42 of file PHG4Cell.h.
has_property()
virtual bool PHG4Cell::has_property (const PROPERTY prop_id) const inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 144 of file PHG4Cell.h.
Referenced by Copy().
identify()
void PHG4Cell::identify (std::ostream & os = std::cout) const virtual
Reimplemented in PHG4CylinderCellv3, PHG4CylinderCellv2, PHG4CylinderCellv1, PHG4CylinderCell, PHG4Cellv2, and PHG4Cellv1.
Definition at line 23 of file PHG4Cell.cc.
print()
virtual void PHG4Cell::print () const inline virtual
Reimplemented in PHG4Cellv2, and PHG4Cellv1.
Definition at line 105 of file PHG4Cell.h.
Reset()
void PHG4Cell::Reset () virtual
Reimplemented in PHG4Cellv2, and PHG4Cellv1.
Definition at line 35 of file PHG4Cell.cc.
set_cellid()
virtual void PHG4Cell::set_cellid (const PHG4CellDefs::keytype i) inline virtual
Reimplemented in PHG4Cellv2, and PHG4Cellv1.
Definition at line 39 of file PHG4Cell.h.
Referenced by PHG4CellContainer::AddCellSpecifyKey(), and PHG4CellContainer::findOrAddCell().
set_chip_index()
virtual void PHG4Cell::set_chip_index (const int i) inline virtual
Reimplemented in PHG4CylinderCell, and PHG4Cellv1.
Definition at line 75 of file PHG4Cell.h.
set_half_stave_index()
virtual void PHG4Cell::set_half_stave_index (const int i) inline virtual
Reimplemented in PHG4CylinderCell, and PHG4Cellv1.
Definition at line 78 of file PHG4Cell.h.
set_ladder_phi_index()
virtual void PHG4Cell::set_ladder_phi_index (const int i) inline virtual
Reimplemented in PHG4CylinderCellv2, PHG4CylinderCell, and PHG4Cellv1.
Definition at line 81 of file PHG4Cell.h.
set_ladder_z_index()
virtual void PHG4Cell::set_ladder_z_index (const int i) inline virtual
Reimplemented in PHG4CylinderCellv2, PHG4CylinderCell, and PHG4Cellv1.
Definition at line 84 of file PHG4Cell.h.
set_module_index()
virtual void PHG4Cell::set_module_index (const int i) inline virtual
Reimplemented in PHG4CylinderCell, and PHG4Cellv1.
Definition at line 87 of file PHG4Cell.h.
set_phibin()
virtual void PHG4Cell::set_phibin (const int i) inline virtual
Reimplemented in PHG4CylinderCellv1, PHG4CylinderCell, and PHG4Cellv1.
Definition at line 90 of file PHG4Cell.h.
set_pixel_index()
virtual void PHG4Cell::set_pixel_index (const int i) inline virtual
Reimplemented in PHG4CylinderCell, and PHG4Cellv1.
Definition at line 93 of file PHG4Cell.h.
set_property() [1/3]
virtual void PHG4Cell::set_property (const PROPERTY prop_id, const float value) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 148 of file PHG4Cell.h.
set_property() [2/3]
virtual void PHG4Cell::set_property (const PROPERTY prop_id, const int value) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 149 of file PHG4Cell.h.
set_property() [3/3]
virtual void PHG4Cell::set_property (const PROPERTY prop_id, const unsigned int value) inline virtual
Reimplemented in PHG4Cellv1.
Definition at line 150 of file PHG4Cell.h.
set_property_nocheck()
virtual void PHG4Cell::set_property_nocheck (const PROPERTY prop_id, const unsigned int) inline protected virtual
Reimplemented in PHG4Cellv1.
Definition at line 158 of file PHG4Cell.h.
set_stave_index()
virtual void PHG4Cell::set_stave_index (const int i) inline virtual
Reimplemented in PHG4CylinderCell, and PHG4Cellv1.
Definition at line 96 of file PHG4Cell.h.
set_zbin()
virtual void PHG4Cell::set_zbin (const int i) inline virtual
Reimplemented in PHG4CylinderCellv1, PHG4CylinderCell, and PHG4Cellv1.
Definition at line 101 of file PHG4Cell.h.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, const PHG4Cell * cell) friend
Definition at line 29 of file PHG4Cell.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4Cell.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4Cell.cc