Class Reference for E1039 Core & Analysis Software: PHG4HitDefs Namespace Reference
PHG4HitDefs Namespace Reference
Typedefs
typedef unsigned int keytype
Functions
int get_volume_id (const std::string &nodename)
Variables
static const unsigned int keybits = 16
static const unsigned int hit_idbits = sizeof(keytype)*8-keybits
static const keytype detid_mask = 0xffff0000
static const keytype hitid_mask = 0x0000ffff
Typedef Documentation
keytype
typedef unsigned int PHG4HitDefs::keytype
Definition at line 8 of file PHG4HitDefs.h.
Function Documentation
get_volume_id()
int PHG4HitDefs::get_volume_id (const std::string & nodename)
convert PHG4HitContainer node names in to ID number for the container. used in indexing volume ID in PHG4Shower
Definition at line 9 of file PHG4HitDefs.cc.
Variable Documentation
detid_mask
const keytype PHG4HitDefs::detid_mask = 0xffff0000 static
Definition at line 11 of file PHG4HitDefs.h.
Referenced by PHG4HitContainer::registerHitOnLayer().
hit_idbits
const unsigned int PHG4HitDefs::hit_idbits = sizeof(keytype)*8-keybits static
Definition at line 10 of file PHG4HitDefs.h.
Referenced by PHG4HitContainer::genkey(), PHG4Hitv1::get_detid(), PHG4HitContainer::getHits(), and PHG4HitContainer::registerHitOnLayer().
hitid_mask
const keytype PHG4HitDefs::hitid_mask = 0x0000ffff static
Definition at line 12 of file PHG4HitDefs.h.
Referenced by PHG4HitContainer::registerHitOnLayer().
keybits
const unsigned int PHG4HitDefs::keybits = 16 static
Definition at line 9 of file PHG4HitDefs.h.
Referenced by PHG4HitContainer::genkey(), and PHG4HitContainer::getHits().