Class Reference for E1039 Core & Analysis Software: SQStringMap_v1 Class Reference
SQStringMap_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQStringMap_v1.h>
Public Member Functions
SQStringMap_v1 ()
SQStringMap_v1 (const SQStringMap_v1 &map)
SQStringMap_v1 & operator= (const SQStringMap_v1 &map)
virtual ~SQStringMap_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQStringMap * Clone () const
bool empty () const
size_t size () const
size_t count (std::string key) const
void clear ()
const PHObject * get (std::string key) const
PHObject * get (std::string key)
PHObject * insert (std::string key, const PHObject *item)
size_t erase (std::string key)
ConstIter begin () const
ConstIter find (std::string key) const
ConstIter end () const
Iter begin ()
Iter find (std::string key)
Iter end ()
Public Member Functions inherited from SQStringMap
virtual ~SQStringMap ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from SQStringMap
typedef std::map< std::string, PHObject * > ObjectMap
typedef ObjectMap::const_iterator ConstIter
typedef ObjectMap::iterator Iter
Protected Member Functions inherited from SQStringMap
SQStringMap ()
Detailed Description
Definition at line 8 of file SQStringMap_v1.h.
Constructor & Destructor Documentation
SQStringMap_v1() [1/2]
SQStringMap_v1::SQStringMap_v1 ()
Referenced by Clone().
SQStringMap_v1() [2/2]
SQStringMap_v1::SQStringMap_v1 (const SQStringMap_v1 & map)
Definition at line 12 of file SQStringMap_v1.cxx.
References begin(), and end().
~SQStringMap_v1()
SQStringMap_v1::~SQStringMap_v1 () virtual
Definition at line 28 of file SQStringMap_v1.cxx.
References Reset().
Member Function Documentation
begin() [1/2]
Iter SQStringMap_v1::begin () inline virtual
Reimplemented from SQStringMap.
Definition at line 37 of file SQStringMap_v1.h.
begin() [2/2]
ConstIter SQStringMap_v1::begin () const inline virtual
Reimplemented from SQStringMap.
Definition at line 33 of file SQStringMap_v1.h.
Referenced by operator=(), and SQStringMap_v1().
clear()
void SQStringMap_v1::clear () inline virtual
Reimplemented from SQStringMap.
Definition at line 23 of file SQStringMap_v1.h.
References Reset().
Clone()
SQStringMap* SQStringMap_v1::Clone () const inline virtual
Reimplemented from SQStringMap.
Definition at line 18 of file SQStringMap_v1.h.
References SQStringMap_v1().
count()
size_t SQStringMap_v1::count (std::string key) const inline virtual
Reimplemented from SQStringMap.
Definition at line 22 of file SQStringMap_v1.h.
empty()
bool SQStringMap_v1::empty () const inline virtual
Reimplemented from SQStringMap.
Definition at line 20 of file SQStringMap_v1.h.
end() [1/2]
Iter SQStringMap_v1::end () inline virtual
Reimplemented from SQStringMap.
Definition at line 39 of file SQStringMap_v1.h.
end() [2/2]
ConstIter SQStringMap_v1::end () const inline virtual
Reimplemented from SQStringMap.
Definition at line 35 of file SQStringMap_v1.h.
Referenced by operator=(), and SQStringMap_v1().
erase()
size_t SQStringMap_v1::erase (std::string key) inline virtual
Reimplemented from SQStringMap.
Definition at line 28 of file SQStringMap_v1.h.
find() [1/2]
Iter SQStringMap_v1::find (std::string key) inline virtual
Reimplemented from SQStringMap.
Definition at line 38 of file SQStringMap_v1.h.
find() [2/2]
ConstIter SQStringMap_v1::find (std::string key) const inline virtual
Reimplemented from SQStringMap.
Definition at line 34 of file SQStringMap_v1.h.
get() [1/2]
PHObject * SQStringMap_v1::get (std::string key) virtual
Reimplemented from SQStringMap.
Definition at line 50 of file SQStringMap_v1.cxx.
References NULL.
get() [2/2]
const PHObject * SQStringMap_v1::get (std::string key) const virtual
Reimplemented from SQStringMap.
Definition at line 44 of file SQStringMap_v1.cxx.
References NULL.
identify()
void SQStringMap_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQStringMap.
Definition at line 39 of file SQStringMap_v1.cxx.
insert()
PHObject * SQStringMap_v1::insert (std::string key, const PHObject * item) virtual
Reimplemented from SQStringMap.
Definition at line 56 of file SQStringMap_v1.cxx.
References PHObject::clone().
isValid()
int SQStringMap_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQStringMap.
Definition at line 17 of file SQStringMap_v1.h.
operator=()
SQStringMap_v1 & SQStringMap_v1::operator= (const SQStringMap_v1 & map)
Definition at line 19 of file SQStringMap_v1.cxx.
References begin(), end(), and Reset().
Reset()
void SQStringMap_v1::Reset () virtual
Clear Event.
Reimplemented from SQStringMap.
Definition at line 32 of file SQStringMap_v1.cxx.
Referenced by clear(), operator=(), and ~SQStringMap_v1().
size()
size_t SQStringMap_v1::size (void) const inline virtual
Reimplemented from SQStringMap.
Definition at line 21 of file SQStringMap_v1.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQStringMap_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQStringMap_v1.cxx