E1039 Software: PHG4ParameterInterface Class Reference
PHG4ParameterInterface Class Reference abstract
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4ParameterInterface.h>
Public Member Functions
PHG4ParameterInterface (const std::string &name)
virtual ~PHG4ParameterInterface ()
void set_paramname (const std::string &name)
virtual void SetDefaultParameters ()=0
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
Protected Member Functions
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Private Attributes
PHG4Parameters * params
std::map< const std::string, double > dparams
std::map< const std::string, int > iparams
std::map< const std::string, std::string > cparams
std::map< const std::string, double > default_double
std::map< const std::string, int > default_int
std::map< const std::string, std::string > default_string
Detailed Description
This class is deprecated, please use PHG4Parameter instead. See https://github.com/sPHENIX-Collaboration/coresoftware/pull/405
Definition at line 12 of file PHG4ParameterInterface.h.
Constructor & Destructor Documentation
PHG4ParameterInterface()
PHG4ParameterInterface::PHG4ParameterInterface (const std::string & name)
Definition at line 11 of file PHG4ParameterInterface.cc.
~PHG4ParameterInterface()
virtual PHG4ParameterInterface::~PHG4ParameterInterface () inline virtual
Definition at line 16 of file PHG4ParameterInterface.h.
References get_double_param(), get_int_param(), get_string_param(), InitializeParameters(), PutOnParNode(), SaveToNodeTree(), set_default_double_param(), set_default_int_param(), set_default_string_param(), set_double_param(), set_int_param(), set_paramname(), set_string_param(), SetDefaultParameters(), and UpdateParametersWithMacro().
Member Function Documentation
get_double_param()
double PHG4ParameterInterface::get_double_param (const std::string & name) const
Definition at line 85 of file PHG4ParameterInterface.cc.
References PHG4Parameters::get_double_param(), and params.
Referenced by ~PHG4ParameterInterface().
get_int_param()
int PHG4ParameterInterface::get_int_param (const std::string & name) const
Definition at line 107 of file PHG4ParameterInterface.cc.
References PHG4Parameters::get_int_param(), and params.
Referenced by ~PHG4ParameterInterface().
get_string_param()
string PHG4ParameterInterface::get_string_param (const std::string & name) const
Definition at line 129 of file PHG4ParameterInterface.cc.
References PHG4Parameters::get_string_param(), and params.
Referenced by ~PHG4ParameterInterface().
InitializeParameters()
void PHG4ParameterInterface::InitializeParameters () protected
Definition at line 166 of file PHG4ParameterInterface.cc.
References default_double, default_int, default_string, params, PHG4Parameters::set_double_param(), PHG4Parameters::set_int_param(), PHG4Parameters::set_string_param(), and SetDefaultParameters().
Referenced by ~PHG4ParameterInterface().
PutOnParNode()
void PHG4ParameterInterface::PutOnParNode (PHCompositeNode * parNode, const std::string & nodename)
Definition at line 160 of file PHG4ParameterInterface.cc.
References PHCompositeNode::addNode(), and params.
Referenced by ~PHG4ParameterInterface().
SaveToNodeTree()
void PHG4ParameterInterface::SaveToNodeTree (PHCompositeNode * runNode, const std::string & nodename)
Definition at line 153 of file PHG4ParameterInterface.cc.
References params, and PHG4Parameters::SaveToNodeTree().
Referenced by ~PHG4ParameterInterface().
set_default_double_param()
void PHG4ParameterInterface::set_default_double_param (const std::string & name, const double dval) protected
Definition at line 22 of file PHG4ParameterInterface.cc.
References default_double.
Referenced by ~PHG4ParameterInterface().
set_default_int_param()
void PHG4ParameterInterface::set_default_int_param (const std::string & name, const int ival) protected
Definition at line 38 of file PHG4ParameterInterface.cc.
References default_int.
Referenced by ~PHG4ParameterInterface().
set_default_string_param()
void PHG4ParameterInterface::set_default_string_param (const std::string & name, const std::string & sval) protected
Definition at line 54 of file PHG4ParameterInterface.cc.
References default_string.
Referenced by ~PHG4ParameterInterface().
set_double_param()
void PHG4ParameterInterface::set_double_param (const std::string & name, const double dval)
Definition at line 69 of file PHG4ParameterInterface.cc.
References default_double, and dparams.
Referenced by ~PHG4ParameterInterface().
set_int_param()
void PHG4ParameterInterface::set_int_param (const std::string & name, const int ival)
Definition at line 91 of file PHG4ParameterInterface.cc.
References default_int, and iparams.
Referenced by ~PHG4ParameterInterface().
set_paramname()
void PHG4ParameterInterface::set_paramname (const std::string & name)
Definition at line 16 of file PHG4ParameterInterface.cc.
References params, and PHG4Parameters::set_name().
Referenced by ~PHG4ParameterInterface().
set_string_param()
void PHG4ParameterInterface::set_string_param (const std::string & name, const std::string & sval)
Definition at line 113 of file PHG4ParameterInterface.cc.
References cparams, and default_string.
Referenced by ~PHG4ParameterInterface().
SetDefaultParameters()
virtual void PHG4ParameterInterface::SetDefaultParameters () pure virtual
Referenced by InitializeParameters(), and ~PHG4ParameterInterface().
UpdateParametersWithMacro()
void PHG4ParameterInterface::UpdateParametersWithMacro ()
Definition at line 135 of file PHG4ParameterInterface.cc.
References cparams, dparams, iparams, params, PHG4Parameters::set_double_param(), PHG4Parameters::set_int_param(), and PHG4Parameters::set_string_param().
Referenced by ~PHG4ParameterInterface().
Member Data Documentation
cparams
std::map<const std::string, std::string> PHG4ParameterInterface::cparams private
Definition at line 42 of file PHG4ParameterInterface.h.
Referenced by set_string_param(), and UpdateParametersWithMacro().
default_double
std::map<const std::string, double> PHG4ParameterInterface::default_double private
Definition at line 44 of file PHG4ParameterInterface.h.
Referenced by InitializeParameters(), set_default_double_param(), and set_double_param().
default_int
std::map<const std::string, int> PHG4ParameterInterface::default_int private
Definition at line 45 of file PHG4ParameterInterface.h.
Referenced by InitializeParameters(), set_default_int_param(), and set_int_param().
default_string
std::map<const std::string, std::string> PHG4ParameterInterface::default_string private
Definition at line 46 of file PHG4ParameterInterface.h.
Referenced by InitializeParameters(), set_default_string_param(), and set_string_param().
dparams
std::map<const std::string, double> PHG4ParameterInterface::dparams private
Definition at line 40 of file PHG4ParameterInterface.h.
Referenced by set_double_param(), and UpdateParametersWithMacro().
iparams
std::map<const std::string, int> PHG4ParameterInterface::iparams private
Definition at line 41 of file PHG4ParameterInterface.h.
Referenced by set_int_param(), and UpdateParametersWithMacro().
params
PHG4Parameters* PHG4ParameterInterface::params private
Definition at line 39 of file PHG4ParameterInterface.h.
Referenced by get_double_param(), get_int_param(), get_string_param(), InitializeParameters(), PutOnParNode(), SaveToNodeTree(), set_paramname(), and UpdateParametersWithMacro().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4ParameterInterface.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4ParameterInterface.cc