E1039 Software: PHG4PolyconDetector Class Reference
PHG4PolyconDetector Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4PolyconDetector.h>
Public Member Functions
PHG4PolyconDetector (PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~PHG4PolyconDetector (void)
destructor
void Construct (G4LogicalVolume *world)
construct
bool IsInCylinder (const G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Private Attributes
PHParameters * params
G4VPhysicalVolume * cylinder_physi
int layer
std::string superdetector
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 12 of file PHG4PolyconDetector.h.
Constructor & Destructor Documentation
PHG4PolyconDetector()
PHG4PolyconDetector::PHG4PolyconDetector (PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 29 of file PHG4PolyconDetector.cc.
~PHG4PolyconDetector()
virtual PHG4PolyconDetector::~PHG4PolyconDetector (void) inline virtual
destructor
Definition at line 19 of file PHG4PolyconDetector.h.
References Construct(), and IsInCylinder().
Member Function Documentation
Construct()
void PHG4PolyconDetector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 48 of file PHG4PolyconDetector.cc.
References cylinder_physi, PHParameters::get_double_param(), PHParameters::get_int_param(), PHParameters::get_string_param(), PHParameters::get_vdouble_param(), PHG4Detector::GetName(), PHG4Detector::name, PHG4Detector::overlapcheck, params, PHParameters::Print(), and PHG4Utils::SetColour().
Referenced by ~PHG4PolyconDetector().
get_Layer()
int PHG4PolyconDetector::get_Layer () const inline
Definition at line 29 of file PHG4PolyconDetector.h.
References layer.
Referenced by PHG4PolyconSteppingAction::UserSteppingAction().
IsInCylinder()
bool PHG4PolyconDetector::IsInCylinder (const G4VPhysicalVolume * volume) const
Definition at line 38 of file PHG4PolyconDetector.cc.
References cylinder_physi.
Referenced by PHG4PolyconSteppingAction::UserSteppingAction(), and ~PHG4PolyconDetector().
SuperDetector() [1/2]
void PHG4PolyconDetector::SuperDetector (const std::string & name) inline
Definition at line 27 of file PHG4PolyconDetector.h.
References PHG4Detector::name, and superdetector.
Referenced by PHG4PolyconSubsystem::InitRunSubsystem(), PHG4PolyconSteppingAction::SetInterfacePointers(), and PHG4PolyconSteppingAction::UserSteppingAction().
SuperDetector() [2/2]
const std::string PHG4PolyconDetector::SuperDetector () const inline
Definition at line 28 of file PHG4PolyconDetector.h.
References superdetector.
Member Data Documentation
cylinder_physi
G4VPhysicalVolume* PHG4PolyconDetector::cylinder_physi private
Definition at line 33 of file PHG4PolyconDetector.h.
Referenced by Construct(), and IsInCylinder().
layer
int PHG4PolyconDetector::layer private
Definition at line 35 of file PHG4PolyconDetector.h.
Referenced by get_Layer().
params
PHParameters* PHG4PolyconDetector::params private
Definition at line 31 of file PHG4PolyconDetector.h.
Referenced by Construct().
superdetector
std::string PHG4PolyconDetector::superdetector private
Definition at line 36 of file PHG4PolyconDetector.h.
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4PolyconDetector.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4PolyconDetector.cc