E1039 Software: DecoParam Struct Reference
DecoParam Struct Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/online/decoder_maindaq/DecoParam.h>
Public Member Functions
DecoParam ()
~DecoParam ()
int InitMapper ()
Public Attributes
std::string fn_in
std::string dir_param
int sampling
int verbose
int time_wait
ChanMapTaiwan chan_map_taiwan
ChanMapV1495 chan_map_v1495
ChanMapScaler chan_map_scaler
unsigned short int runID
int spillID
int spillID_cntr
int spillID_slow
short targPos
short targPos_slow
unsigned int codaID
short spillType
short rocID
int eventIDstd
long int hitID
bool at_bos
unsigned int turn_id_max
Max turnOnset in a spill. Used to drop NIM3 events that came after the beam stops. See elog 15010.
time_t timeStart
time_t timeEnd
Detailed Description
This class contains all decoder parameters. Two types of parameters are included.
For controlling the decoder behavior.
For monitoring the condition of the decoder.
Definition at line 14 of file DecoParam.h.
Constructor & Destructor Documentation
DecoParam()
DecoParam::DecoParam ()
Definition at line 7 of file DecoParam.cc.
~DecoParam()
DecoParam::~DecoParam () inline
Definition at line 54 of file DecoParam.h.
References InitMapper().
Member Function Documentation
InitMapper()
int DecoParam::InitMapper ()
Definition at line 16 of file DecoParam.cc.
References chan_map_scaler, chan_map_taiwan, chan_map_v1495, RunParamBase::ReadFromDB(), runID, and RunParamBase::SetMapIDbyDB().
Referenced by ~DecoParam().
Member Data Documentation
at_bos
bool DecoParam::at_bos
Definition at line 45 of file DecoParam.h.
chan_map_scaler
ChanMapScaler DecoParam::chan_map_scaler
Definition at line 26 of file DecoParam.h.
Referenced by InitMapper().
chan_map_taiwan
ChanMapTaiwan DecoParam::chan_map_taiwan
Definition at line 24 of file DecoParam.h.
Referenced by InitMapper().
chan_map_v1495
ChanMapV1495 DecoParam::chan_map_v1495
Definition at line 25 of file DecoParam.h.
Referenced by InitMapper().
codaID
unsigned int DecoParam::codaID
Definition at line 39 of file DecoParam.h.
dir_param
std::string DecoParam::dir_param
Definition at line 19 of file DecoParam.h.
Referenced by Fun4AllEVIOInputManager::DirParam().
eventIDstd
int DecoParam::eventIDstd
Definition at line 42 of file DecoParam.h.
fn_in
std::string DecoParam::fn_in
Control parameters
Definition at line 18 of file DecoParam.h.
hitID
long int DecoParam::hitID
Definition at line 43 of file DecoParam.h.
rocID
short DecoParam::rocID
Definition at line 41 of file DecoParam.h.
runID
unsigned short int DecoParam::runID
Monitoring parameters
Definition at line 31 of file DecoParam.h.
Referenced by InitMapper().
sampling
int DecoParam::sampling
Definition at line 20 of file DecoParam.h.
Referenced by Fun4AllEVIOInputManager::EventSamplingFactor().
spillID
int DecoParam::spillID
Definition at line 33 of file DecoParam.h.
spillID_cntr
int DecoParam::spillID_cntr
Definition at line 34 of file DecoParam.h.
spillID_slow
int DecoParam::spillID_slow
Definition at line 35 of file DecoParam.h.
spillType
short DecoParam::spillType
Definition at line 40 of file DecoParam.h.
targPos
short DecoParam::targPos
Definition at line 36 of file DecoParam.h.
targPos_slow
short DecoParam::targPos_slow
Definition at line 37 of file DecoParam.h.
time_wait
int DecoParam::time_wait
Definition at line 22 of file DecoParam.h.
Referenced by Fun4AllEVIOInputManager::PretendSpillInterval().
timeEnd
time_t DecoParam::timeEnd
Definition at line 51 of file DecoParam.h.
timeStart
time_t DecoParam::timeStart
Definition at line 51 of file DecoParam.h.
turn_id_max
unsigned int DecoParam::turn_id_max
Max turnOnset in a spill. Used to drop NIM3 events that came after the beam stops. See elog 15010.
Definition at line 48 of file DecoParam.h.
verbose
int DecoParam::verbose
Definition at line 21 of file DecoParam.h.
Referenced by Fun4AllEVIOInputManager::fileopen().
The documentation for this struct was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/online/decoder_maindaq/DecoParam.h
/home/yuhw/GitHub/SeaQuest/e1039-core/online/decoder_maindaq/DecoParam.cc