Class Reference for E1039 Core & Analysis Software: PHG4CylinderCellGeom Class Reference
PHG4CylinderCellGeom Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellGeom.h>
Public Member Functions
PHG4CylinderCellGeom ()
virtual ~PHG4CylinderCellGeom ()
void identify (std::ostream &os=std::cout) const
int get_layer () const
double get_radius () const
double get_thickness () const
int get_binning () const
int get_zbins () const
int get_phibins () const
double get_zmin () const
double get_phistep () const
double get_phimin () const
double get_zstep () const
int get_etabins () const
double get_etastep () const
double get_etamin () const
virtual std::pair< double, double > get_zbounds (const int ibin) const
virtual std::pair< double, double > get_phibounds (const int ibin) const
virtual std::pair< double, double > get_etabounds (const int ibin) const
virtual double get_etacenter (const int ibin) const
virtual double get_zcenter (const int ibin) const
virtual double get_phicenter (const int ibin) const
virtual int get_etabin (const double eta) const
virtual int get_zbin (const double z) const
virtual int get_phibin (const double phi) const
void set_layer (const int i)
void set_binning (const int i)
void set_radius (const double r)
void set_thickness (const double t)
void set_zbins (const int i)
void set_zmin (const double z)
void set_zstep (const double z)
void set_phibins (const int i)
void set_phistep (const double phi)
void set_phimin (const double phi)
void set_etabins (const int i)
void set_etamin (const double z)
void set_etastep (const double z)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
void check_binning_method (const int i) const
void check_binning_method_eta (const std::string &src="") const
void check_binning_method_phi (const std::string &src="") const
std::string methodname (const int i) const
Protected Attributes
int layer
int binning
double radius
int nzbins
double zmin
double zstep
int nphibins
double phimin
double phistep
double thickness
Detailed Description
Definition at line 9 of file PHG4CylinderCellGeom.h.
Constructor & Destructor Documentation
PHG4CylinderCellGeom()
PHG4CylinderCellGeom::PHG4CylinderCellGeom ()
Definition at line 10 of file PHG4CylinderCellGeom.cc.
~PHG4CylinderCellGeom()
virtual PHG4CylinderCellGeom::~PHG4CylinderCellGeom () inline virtual
Definition at line 14 of file PHG4CylinderCellGeom.h.
Member Function Documentation
check_binning_method()
void PHG4CylinderCellGeom::check_binning_method (const int i) const protected
Definition at line 332 of file PHG4CylinderCellGeom.cc.
References binning, and methodname().
Referenced by get_zbin(), get_zbins(), get_zbounds(), get_zcenter(), get_zmin(), get_zstep(), set_zbins(), set_zmin(), and set_zstep().
check_binning_method_eta()
void PHG4CylinderCellGeom::check_binning_method_eta (const std::string & src = "") const protected
Definition at line 345 of file PHG4CylinderCellGeom.cc.
References binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, methodname(), and PHG4CylinderCellDefs::spacalbinning.
Referenced by get_etabin(), get_etabins(), get_etabounds(), get_etacenter(), get_etamin(), get_etastep(), set_etabins(), set_etamin(), and set_etastep().
check_binning_method_phi()
void PHG4CylinderCellGeom::check_binning_method_phi (const std::string & src = "") const protected
Definition at line 365 of file PHG4CylinderCellGeom.cc.
References binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, methodname(), PHG4CylinderCellDefs::sizebinning, and PHG4CylinderCellDefs::spacalbinning.
Referenced by get_phibin(), get_phibins(), get_phicenter(), get_phimin(), get_phistep(), set_phibins(), set_phimin(), and set_phistep().
get_binning()
int PHG4CylinderCellGeom::get_binning () const inline
Definition at line 20 of file PHG4CylinderCellGeom.h.
References binning.
get_etabin()
int PHG4CylinderCellGeom::get_etabin (const double eta) const virtual
Definition at line 246 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), nzbins, zmin, and zstep.
Referenced by PHG4CylinderCellReco::process_event().
get_etabins()
int PHG4CylinderCellGeom::get_etabins () const
Definition at line 110 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), and nzbins.
get_etabounds()
pair< double, double > PHG4CylinderCellGeom::get_etabounds (const int ibin) const virtual
Definition at line 203 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), nzbins, PHWHERE, zmin, and zstep.
get_etacenter()
double PHG4CylinderCellGeom::get_etacenter (const int ibin) const virtual
Definition at line 283 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), nzbins, PHWHERE, zmin, and zstep.
Referenced by PHG4CylinderCellReco::process_event().
get_etamin()
double PHG4CylinderCellGeom::get_etamin () const
Definition at line 123 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), and zmin.
get_etastep()
double PHG4CylinderCellGeom::get_etastep () const
Definition at line 117 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), and zstep.
Referenced by PHG4CylinderCellReco::process_event().
get_layer()
int PHG4CylinderCellGeom::get_layer () const inline
Definition at line 17 of file PHG4CylinderCellGeom.h.
References layer.
Referenced by PHG4CylinderCellGeomContainer::AddLayerCellGeom().
get_phibin()
int PHG4CylinderCellGeom::get_phibin (const double phi) const virtual
Definition at line 258 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), nphibins, phimin, and phistep.
Referenced by PHG4CylinderCellTPCReco::populate_rectangular_phibins(), PHG4CylinderCellTPCReco::populate_zigzag_phibins(), PHG4CylinderCellReco::process_event(), and PHG4CylinderCellTPCReco::process_event().
get_phibins()
int PHG4CylinderCellGeom::get_phibins () const
Definition at line 68 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), and nphibins.
Referenced by PHG4CylinderCellTPCReco::populate_rectangular_phibins(), PHG4CylinderCellTPCReco::populate_zigzag_phibins(), and PHG4CylinderCellTPCReco::process_event().
get_phibounds()
pair< double, double > PHG4CylinderCellGeom::get_phibounds (const int ibin) const virtual
Definition at line 219 of file PHG4CylinderCellGeom.cc.
References nphibins, phimin, phistep, and PHWHERE.
get_phicenter()
double PHG4CylinderCellGeom::get_phicenter (const int ibin) const virtual
Definition at line 296 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), nphibins, phimin, phistep, and PHWHERE.
Referenced by PHG4CylinderCellTPCReco::populate_rectangular_phibins(), PHG4CylinderCellTPCReco::populate_zigzag_phibins(), PHG4CylinderCellReco::process_event(), and PHG4CylinderCellTPCReco::process_event().
get_phimin()
double PHG4CylinderCellGeom::get_phimin () const
Definition at line 82 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), and phimin.
Referenced by PHG4CylinderCellTPCReco::process_event().
get_phistep()
double PHG4CylinderCellGeom::get_phistep () const
Definition at line 75 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), and phistep.
Referenced by PHG4CylinderCellTPCReco::populate_rectangular_phibins(), PHG4CylinderCellTPCReco::populate_zigzag_phibins(), and PHG4CylinderCellReco::process_event().
get_radius()
double PHG4CylinderCellGeom::get_radius () const inline
Definition at line 18 of file PHG4CylinderCellGeom.h.
References radius.
Referenced by PHG4CylinderCellTPCReco::populate_rectangular_phibins(), PHG4CylinderCellTPCReco::populate_zigzag_phibins(), and PHG4CylinderCellTPCReco::process_event().
get_thickness()
double PHG4CylinderCellGeom::get_thickness () const inline
Definition at line 19 of file PHG4CylinderCellGeom.h.
References thickness.
Referenced by PHG4CylinderCellTPCReco::populate_rectangular_phibins(), PHG4CylinderCellTPCReco::populate_zigzag_phibins(), and PHG4CylinderCellTPCReco::process_event().
get_zbin()
int PHG4CylinderCellGeom::get_zbin (const double z) const virtual
Definition at line 233 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), nzbins, PHG4CylinderCellDefs::sizebinning, zmin, and zstep.
Referenced by PHG4CylinderCellTPCReco::populate_zbins(), PHG4CylinderCellReco::process_event(), and PHG4CylinderCellTPCReco::process_event().
get_zbins()
int PHG4CylinderCellGeom::get_zbins () const
Definition at line 40 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), nzbins, and PHG4CylinderCellDefs::sizebinning.
Referenced by PHG4CylinderCellTPCReco::populate_zbins(), and PHG4CylinderCellTPCReco::process_event().
get_zbounds()
pair< double, double > PHG4CylinderCellGeom::get_zbounds (const int ibin) const virtual
Definition at line 189 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), nzbins, PHWHERE, PHG4CylinderCellDefs::sizebinning, zmin, and zstep.
get_zcenter()
double PHG4CylinderCellGeom::get_zcenter (const int ibin) const virtual
Definition at line 271 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), nzbins, PHWHERE, PHG4CylinderCellDefs::sizebinning, zmin, and zstep.
Referenced by PHG4CylinderCellTPCReco::populate_zbins(), PHG4CylinderCellReco::process_event(), and PHG4CylinderCellTPCReco::process_event().
get_zmin()
double PHG4CylinderCellGeom::get_zmin () const
Definition at line 47 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, and zmin.
Referenced by PHG4CylinderCellTPCReco::process_event().
get_zstep()
double PHG4CylinderCellGeom::get_zstep () const
Definition at line 54 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, and zstep.
Referenced by PHG4CylinderCellTPCReco::populate_zbins(), and PHG4CylinderCellReco::process_event().
identify()
void PHG4CylinderCellGeom::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 151 of file PHG4CylinderCellGeom.cc.
References binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, layer, nphibins, nzbins, phimin, phistep, radius, PHG4CylinderCellDefs::sizebinning, PHG4CylinderCellDefs::spacalbinning, thickness, zmin, and zstep.
Referenced by PHG4CylinderCellReco::InitRun().
methodname()
string PHG4CylinderCellGeom::methodname (const int i) const protected
Definition at line 309 of file PHG4CylinderCellGeom.cc.
References PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, PHG4CylinderCellDefs::sizebinning, and PHG4CylinderCellDefs::spacalbinning.
Referenced by check_binning_method(), check_binning_method_eta(), and check_binning_method_phi().
set_binning()
void PHG4CylinderCellGeom::set_binning (const int i) inline
Definition at line 43 of file PHG4CylinderCellGeom.h.
References binning.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
set_etabins()
void PHG4CylinderCellGeom::set_etabins (const int i)
Definition at line 144 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), and nzbins.
Referenced by PHG4CylinderCellReco::InitRun().
set_etamin()
void PHG4CylinderCellGeom::set_etamin (const double z)
Definition at line 130 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), and zmin.
Referenced by PHG4CylinderCellReco::InitRun().
set_etastep()
void PHG4CylinderCellGeom::set_etastep (const double z)
Definition at line 137 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), and zstep.
Referenced by PHG4CylinderCellReco::InitRun().
set_layer()
void PHG4CylinderCellGeom::set_layer (const int i) inline
Definition at line 42 of file PHG4CylinderCellGeom.h.
References layer.
Referenced by PHG4CylinderCellGeomContainer::AddLayerCellGeom(), PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
set_phibins()
void PHG4CylinderCellGeom::set_phibins (const int i)
Definition at line 89 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), and nphibins.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
set_phimin()
void PHG4CylinderCellGeom::set_phimin (const double phi)
Definition at line 103 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), and phimin.
Referenced by PHG4CylinderCellReco::InitRun().
set_phistep()
void PHG4CylinderCellGeom::set_phistep (const double phi)
Definition at line 96 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), and phistep.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
set_radius()
void PHG4CylinderCellGeom::set_radius (const double r) inline
Definition at line 44 of file PHG4CylinderCellGeom.h.
References radius.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
set_thickness()
void PHG4CylinderCellGeom::set_thickness (const double t) inline
Definition at line 45 of file PHG4CylinderCellGeom.h.
References thickness.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
set_zbins()
void PHG4CylinderCellGeom::set_zbins (const int i)
Definition at line 26 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), nzbins, and PHG4CylinderCellDefs::sizebinning.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
set_zmin()
void PHG4CylinderCellGeom::set_zmin (const double z)
Definition at line 33 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, and zmin.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
set_zstep()
void PHG4CylinderCellGeom::set_zstep (const double z)
Definition at line 61 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, and zstep.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
Member Data Documentation
binning
int PHG4CylinderCellGeom::binning protected
Definition at line 62 of file PHG4CylinderCellGeom.h.
Referenced by check_binning_method(), check_binning_method_eta(), check_binning_method_phi(), get_binning(), identify(), and set_binning().
layer
int PHG4CylinderCellGeom::layer protected
Definition at line 61 of file PHG4CylinderCellGeom.h.
Referenced by get_layer(), identify(), and set_layer().
nphibins
int PHG4CylinderCellGeom::nphibins protected
Definition at line 67 of file PHG4CylinderCellGeom.h.
Referenced by get_phibin(), get_phibins(), get_phibounds(), get_phicenter(), identify(), and set_phibins().
nzbins
int PHG4CylinderCellGeom::nzbins protected
Definition at line 64 of file PHG4CylinderCellGeom.h.
Referenced by get_etabin(), get_etabins(), get_etabounds(), get_etacenter(), get_zbin(), get_zbins(), get_zbounds(), get_zcenter(), identify(), set_etabins(), and set_zbins().
phimin
double PHG4CylinderCellGeom::phimin protected
Definition at line 68 of file PHG4CylinderCellGeom.h.
Referenced by get_phibin(), get_phibounds(), get_phicenter(), get_phimin(), identify(), and set_phimin().
phistep
double PHG4CylinderCellGeom::phistep protected
Definition at line 69 of file PHG4CylinderCellGeom.h.
Referenced by get_phibin(), get_phibounds(), get_phicenter(), get_phistep(), identify(), and set_phistep().
radius
double PHG4CylinderCellGeom::radius protected
Definition at line 63 of file PHG4CylinderCellGeom.h.
Referenced by get_radius(), identify(), and set_radius().
thickness
double PHG4CylinderCellGeom::thickness protected
Definition at line 70 of file PHG4CylinderCellGeom.h.
Referenced by get_thickness(), identify(), and set_thickness().
zmin
double PHG4CylinderCellGeom::zmin protected
Definition at line 65 of file PHG4CylinderCellGeom.h.
Referenced by get_etabin(), get_etabounds(), get_etacenter(), get_etamin(), get_zbin(), get_zbounds(), get_zcenter(), get_zmin(), identify(), set_etamin(), and set_zmin().
zstep
double PHG4CylinderCellGeom::zstep protected
Definition at line 66 of file PHG4CylinderCellGeom.h.
Referenced by get_etabin(), get_etabounds(), get_etacenter(), get_etastep(), get_zbin(), get_zbounds(), get_zcenter(), get_zstep(), identify(), set_etastep(), and set_zstep().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellGeom.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCellGeom.cc