E1039 Software: DPDigitizer Class Reference
DPDigitizer Class Reference
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/simulation/g4detectors/DPDigitizer.h>
Public Member Functions
DPDigitizer (const std::string &name="DPDigitizer", const int verbo=0)
virtual ~DPDigitizer ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
module initialization
int process_event (PHCompositeNode *topNode)
event processing
void digitize (std::string detectorGroupName, PHG4Hit &g4hit)
main external call, fill the digi hit vector
bool realize (SQHit &dHit)
realization process
int getDetectorID (std::string detectorName)
get the detectorID by detectorName
std::string getDetectorName (int detectorID)
get the detectorName by detectorID
int getTriggerLv (int detectorID)
Get the trigger level by detectorID.
DPDigiPlane & getDigiPlane (int detectorID)
Get the digi plane object by ID.
std::string toGroupName (std::string in)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::vector< DPDigiPlane > digiPlanes
array of digi planes
std::map< std::string,
std::vector< int > > map_groupID
map from geant sensitive detector name to the list of detectorIDs
std::map< std::string, int > map_detectorID
map from detectorName to detectorID
std::map< std::string,
std::string > map_g4name_group
std::map< std::string,
std::string > map_dname_group
GeomSvc * p_geomSvc
GeomSvc.
SQHitVector * digits
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 102 of file DPDigitizer.h.
Constructor & Destructor Documentation
DPDigitizer::DPDigitizer (const std::string & name = "DPDigitizer", const int verbo = 0)
Definition at line 503 of file DPDigitizer.cc.
References Fun4AllBase::Verbosity().
DPDigitizer::~DPDigitizer () virtual
Definition at line 510 of file DPDigitizer.cc.
Member Function Documentation
void DPDigitizer::digitize (std::string detectorGroupName, PHG4Hit & g4hit)
main external call, fill the digi hit vector
cm;
cm;
cm;
Definition at line 513 of file DPDigitizer.cc.
References digiPlanes, digits, SQHit_v1::get_detector_id(), SQHit_v1::get_element_id(), SQHit_v1::get_hit_id(), PHG4Hit::get_hit_id(), SQHit_v1::get_pos(), PHG4Hit::get_px(), PHG4Hit::get_py(), PHG4Hit::get_pz(), PHG4Hit::get_trkid(), PHG4Hit::get_x(), PHG4Hit::get_y(), PHG4Hit::get_z(), GeomSvc::getDetectorID(), GeomSvc::getDetectorName(), GeomSvc::getMeasurement(), LogDebug, LogInfo, map_groupID, nChamberPlanes, nDarkPhotonPlanes, nHodoPlanes, nPropPlanes, p_geomSvc, SQHitVector::push_back(), SQHit_v1::set_detector_id(), SQHit_v1::set_drift_distance(), SQHit_v1::set_element_id(), SQMCHit_v1::set_g4hit_id(), SQHit_v1::set_hit_id(), SQHit_v1::set_hodo_mask(), SQHit_v1::set_in_time(), SQHit_v1::set_pos(), SQMCHit_v1::set_track_id(), SQMCHit_v1::set_truth_x(), SQMCHit_v1::set_truth_y(), SQMCHit_v1::set_truth_z(), SQHitVector::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int DPDigitizer::getDetectorID (std::string detectorName) inline
get the detectorID by detectorName
Definition at line 125 of file DPDigitizer.h.
References map_detectorID.
std::string DPDigitizer::getDetectorName (int detectorID) inline
get the detectorName by detectorID
Definition at line 128 of file DPDigitizer.h.
References digiPlanes.
DPDigiPlane& DPDigitizer::getDigiPlane (int detectorID) inline
Get the digi plane object by ID.
Definition at line 134 of file DPDigitizer.h.
References digiPlanes.
int DPDigitizer::getTriggerLv (int detectorID) inline
Get the trigger level by detectorID.
Definition at line 131 of file DPDigitizer.h.
References digiPlanes.
int DPDigitizer::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
init map_g4name_group
Reimplemented from SubsysReco.
Definition at line 193 of file DPDigitizer.cc.
References Fun4AllReturnCodes::EVENT_OK, GeomSvc::instance(), LogInfo, nChamberPlanes, nDarkPhotonPlanes, NDETPLANES, nHodoPlanes, nPropPlanes, and Fun4AllBase::VERBOSITY_A_LOT.
int DPDigitizer::InitRun (PHCompositeNode * topNode) virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 665 of file DPDigitizer.cc.
References PHCompositeNode::addNode(), digiPlanes, digits, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), LogDebug, LogInfo, Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
int DPDigitizer::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 696 of file DPDigitizer.cc.
References Fun4AllReturnCodes::ABORTEVENT, digiPlanes, digitize(), Fun4AllReturnCodes::EVENT_OK, PHG4Hit::get_trkid(), GeomSvc::getDefaultSimList(), GeomSvc::getDetectorGroupName(), PHG4HitContainer::getHits(), PHG4Hit::identify(), LogDebug, LogInfo, Fun4AllBase::Name(), p_geomSvc, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
bool DPDigitizer::realize (SQHit & dHit)
realization process
Definition at line 758 of file DPDigitizer.cc.
References digiPlanes, SQHit::get_detector_id(), SQHit::get_drift_distance(), SQHit::get_element_id(), and SQHit::set_drift_distance().
string DPDigitizer::toGroupName (std::string in)
Definition at line 154 of file DPDigitizer.cc.
Member Data Documentation
std::vector<DPDigiPlane> DPDigitizer::digiPlanes private
array of digi planes
Definition at line 144 of file DPDigitizer.h.
Referenced by digitize(), getDetectorName(), getDigiPlane(), getTriggerLv(), InitRun(), process_event(), and realize().
SQHitVector* DPDigitizer::digits private
Definition at line 162 of file DPDigitizer.h.
Referenced by digitize(), and InitRun().
std::map<std::string, int> DPDigitizer::map_detectorID private
map from detectorName to detectorID
Definition at line 150 of file DPDigitizer.h.
Referenced by getDetectorID().
std::map<std::string, std::string> DPDigitizer::map_dname_group private
Definition at line 156 of file DPDigitizer.h.
std::map<std::string, std::string> DPDigitizer::map_g4name_group private
Definition at line 153 of file DPDigitizer.h.
std::map<std::string, std::vector<int> > DPDigitizer::map_groupID private
map from geant sensitive detector name to the list of detectorIDs
Definition at line 147 of file DPDigitizer.h.
Referenced by digitize().
GeomSvc* DPDigitizer::p_geomSvc private
GeomSvc.
Definition at line 159 of file DPDigitizer.h.
Referenced by digitize(), and process_event().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/simulation/g4detectors/DPDigitizer.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/simulation/g4detectors/DPDigitizer.cc