SeaQuest Offline Software: EventReducer Class Reference
EventReducer Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/EventReducer.h>
Public Member Functions
EventReducer (TString options)
~EventReducer ()
int reduceEvent (SRawEvent *rawEvent)
void setChamEff (double val)
void setChamResol (double val)
void sagittaReducer ()
void houghReducer ()
void deClusterize ()
void processCluster (std::vector< std::list< Hit >::iterator > &cluster)
void initHodoMaskLUT ()
void hodoscopeMask (std::list< Hit > &chamberhits, std::list< Hit > &hodohits)
bool lineCrossing (double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4)
EventReducer (TString options)
~EventReducer ()
int reduceEvent (SRawEvent *rawEvent)
void setChamEff (double val)
void setChamResol (double val)
void sagittaReducer ()
void houghReducer ()
void deClusterize ()
void processCluster (std::vector< std::list< Hit >::iterator > &cluster)
void initHodoMaskLUT ()
void hodoscopeMask (std::list< Hit > &chamberhits, std::list< Hit > &hodohits)
bool lineCrossing (double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4)
Private Types
typedef std::map< int,
std::vector< int > > LUT
typedef std::map< int,
std::vector< int > > LUT
Private Attributes
GeomSvc * p_geomSvc
JobOptsSvc * p_jobOptsSvc
TriggerAnalyzer * p_triggerAna
TRandom rndm
std::list< Hit > hitlist
std::list< Hit > hodohitlist
LUT h2celementID_lo
LUT h2celementID_hi
LUT c2helementIDs
bool afterhit
bool hodomask
bool outoftime
bool decluster
bool mergehodo
bool triggermask
bool sagitta
bool hough
bool externalpar
bool realization
bool difnim
double timeOffset
double chamEff
double chamResol
Detailed Description
Definition at line 27 of file EventReducer.h.
Member Typedef Documentation
typedef std::map<int, std::vector<int> > EventReducer::LUT private
Definition at line 74 of file EventReducer.h.
typedef std::map<int, std::vector<int> > EventReducer::LUT private
Definition at line 75 of file EventReducer.h.
Constructor & Destructor Documentation
EventReducer::EventReducer (TString options)
Definition at line 6 of file EventReducer.cxx.
References afterhit, TriggerAnalyzer::buildTriggerTree(), chamEff, chamResol, decluster, difnim, externalpar, hodomask, hough, TriggerAnalyzer::init(), initHodoMaskLUT(), JobOptsSvc::instance(), GeomSvc::instance(), JobOptsSvc::m_timingOffset, mergehodo, outoftime, p_geomSvc, p_jobOptsSvc, p_triggerAna, realization, rndm, sagitta, timeOffset, and triggermask.
EventReducer::~EventReducer ()
Definition at line 56 of file EventReducer.cxx.
References p_triggerAna, and triggermask.
EventReducer::EventReducer (TString options)
EventReducer::~EventReducer ()
Member Function Documentation
void EventReducer::deClusterize ()
Definition at line 238 of file EventReducer.cxx.
References hitlist, nChamberPlanes, and processCluster().
Referenced by reduceEvent().
void EventReducer::deClusterize ()
void EventReducer::hodoscopeMask (std::list< Hit > & chamberhits, std::list< Hit > & hodohits)
Definition at line 427 of file EventReducer.cxx.
References c2helementIDs, and nChamberPlanes.
Referenced by reduceEvent().
void EventReducer::hodoscopeMask (std::list< Hit > & chamberhits, std::list< Hit > & hodohits)
void EventReducer::houghReducer ()
void EventReducer::houghReducer ()
void EventReducer::initHodoMaskLUT ()
Definition at line 335 of file EventReducer.cxx.
References c2helementIDs, GeomSvc::get2DBoxSize(), GeomSvc::getDetectorID(), GeomSvc::getExpElementID(), GeomSvc::getPlaneNElements(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneType(), GeomSvc::getWireEndPoints(), h2celementID_hi, h2celementID_lo, lineCrossing(), p_geomSvc, TX_MAX, and TY_MAX.
Referenced by EventReducer().
void EventReducer::initHodoMaskLUT ()
bool EventReducer::lineCrossing (double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4)
Definition at line 460 of file EventReducer.cxx.
Referenced by initHodoMaskLUT().
bool EventReducer::lineCrossing (double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4)
void EventReducer::processCluster (std::vector< std::list< Hit >::iterator > & cluster)
Definition at line 271 of file EventReducer.cxx.
References hitlist, and tdcTime.
Referenced by deClusterize().
void EventReducer::processCluster (std::vector< std::list< Hit >::iterator > & cluster)
int EventReducer::reduceEvent (SRawEvent * rawEvent)
Definition at line 64 of file EventReducer.cxx.
References afterhit, chamEff, chamResol, decluster, deClusterize(), externalpar, SRawEvent::fAllHits, SRawEvent::fTriggerHits, GeomSvc::getDriftDistance(), GeomSvc::getMeasurement(), SRawEvent::getNChamberHitsAll(), GeomSvc::getPlaneType(), hitlist, hodohitlist, hodomask, hodoscopeMask(), SRawEvent::isFPGATriggered(), JobOptsSvc::m_mcMode, mergehodo, nChamberPlanes, nHodoPlanes, outoftime, p_geomSvc, p_jobOptsSvc, p_triggerAna, realization, SRawEvent::reIndex(), rndm, sagitta, sagittaReducer(), timeOffset, triggermask, TriggerAnalyzer::trimEvent(), USE_HIT, and USE_TRIGGER_HIT.
Referenced by main(), and KalmanFastTrackingWrapper::process_event().
int EventReducer::reduceEvent (SRawEvent * rawEvent)
void EventReducer::sagittaReducer ()
Definition at line 148 of file EventReducer.cxx.
References detectorID, GeomSvc::getPlanePosition(), GeomSvc::getPlaneType(), hitlist, nChamberPlanes, p_geomSvc, SAGITTA_DUMP_CENTER, SAGITTA_DUMP_WIN, SAGITTA_TARGET_CENTER, SAGITTA_TARGET_WIN, TX_MAX, Z_DUMP, and Z_TARGET.
Referenced by reduceEvent().
void EventReducer::sagittaReducer ()
void EventReducer::setChamEff (double val) inline
Definition at line 37 of file EventReducer.h.
References chamEff.
Referenced by main().
void EventReducer::setChamEff (double val) inline
Definition at line 38 of file EventReducer.h.
References chamEff.
void EventReducer::setChamResol (double val) inline
Definition at line 38 of file EventReducer.h.
References chamResol.
void EventReducer::setChamResol (double val) inline
Definition at line 39 of file EventReducer.h.
References chamResol.
Member Data Documentation
bool EventReducer::afterhit private
Definition at line 80 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
LUT EventReducer::c2helementIDs private
Definition at line 77 of file EventReducer.h.
Referenced by hodoscopeMask(), and initHodoMaskLUT().
double EventReducer::chamEff private
Definition at line 94 of file EventReducer.h.
Referenced by EventReducer(), reduceEvent(), and setChamEff().
double EventReducer::chamResol private
Definition at line 95 of file EventReducer.h.
Referenced by EventReducer(), reduceEvent(), and setChamResol().
bool EventReducer::decluster private
Definition at line 83 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
bool EventReducer::difnim private
Definition at line 90 of file EventReducer.h.
Referenced by EventReducer().
bool EventReducer::externalpar private
Definition at line 88 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
LUT EventReducer::h2celementID_hi private
Definition at line 76 of file EventReducer.h.
Referenced by initHodoMaskLUT().
LUT EventReducer::h2celementID_lo private
Definition at line 75 of file EventReducer.h.
Referenced by initHodoMaskLUT().
std::list< Hit > EventReducer::hitlist private
Definition at line 70 of file EventReducer.h.
Referenced by deClusterize(), processCluster(), reduceEvent(), and sagittaReducer().
std::list< Hit > EventReducer::hodohitlist private
Definition at line 71 of file EventReducer.h.
Referenced by reduceEvent().
bool EventReducer::hodomask private
Definition at line 81 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
bool EventReducer::hough private
Definition at line 87 of file EventReducer.h.
Referenced by EventReducer().
bool EventReducer::mergehodo private
Definition at line 84 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
bool EventReducer::outoftime private
Definition at line 82 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
GeomSvc * EventReducer::p_geomSvc private
Definition at line 58 of file EventReducer.h.
Referenced by EventReducer(), initHodoMaskLUT(), reduceEvent(), and sagittaReducer().
JobOptsSvc * EventReducer::p_jobOptsSvc private
Definition at line 61 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
TriggerAnalyzer * EventReducer::p_triggerAna private
Definition at line 64 of file EventReducer.h.
Referenced by EventReducer(), reduceEvent(), and ~EventReducer().
bool EventReducer::realization private
Definition at line 89 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
TRandom EventReducer::rndm private
Definition at line 67 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
bool EventReducer::sagitta private
Definition at line 86 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
double EventReducer::timeOffset private
Definition at line 93 of file EventReducer.h.
Referenced by EventReducer(), and reduceEvent().
bool EventReducer::triggermask private
Definition at line 85 of file EventReducer.h.
Referenced by EventReducer(), reduceEvent(), and ~EventReducer().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/EventReducer.h
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/src/EventReducer.cxx