SeaQuest Offline Software: PHG4mRICHSteppingAction Class Reference
PHG4mRICHSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4mRICHSteppingAction.h>
Public Member Functions
PHG4mRICHSteppingAction (PHG4mRICHDetector *detector, PHParameters *params)
constructor
virtual ~PHG4mRICHSteppingAction ()
destroctor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4mRICHDetector * detector_
pointer to the detector
int active
int IsBlackHole
int use_g4_steps
std::string detectorname
std::string superdetector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4Hit * hit
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 11 of file PHG4mRICHSteppingAction.h.
Constructor & Destructor Documentation
PHG4mRICHSteppingAction::PHG4mRICHSteppingAction (PHG4mRICHDetector * detector, PHParameters * params)
constructor
Definition at line 48 of file PHG4mRICHSteppingAction.cc.
virtual PHG4mRICHSteppingAction::~PHG4mRICHSteppingAction () inline virtual
destroctor
Definition at line 20 of file PHG4mRICHSteppingAction.h.
Member Function Documentation
void PHG4mRICHSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 170 of file PHG4mRICHSteppingAction.cc.
References absorberhits_, detectorname, hits_, superdetector, and PHG4SteppingAction::verbosity.
bool PHG4mRICHSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 61 of file PHG4mRICHSteppingAction.cc.
References active, detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), hit, IsBlackHole, PHG4mRICHDetector::IsInmRICH(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4HitContainer* PHG4mRICHSteppingAction::absorberhits_ private
Definition at line 43 of file PHG4mRICHSteppingAction.h.
Referenced by SetInterfacePointers().
int PHG4mRICHSteppingAction::active private
Definition at line 35 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction().
PHG4mRICHDetector* PHG4mRICHSteppingAction::detector_ private
pointer to the detector
Definition at line 32 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction().
std::string PHG4mRICHSteppingAction::detectorname private
Definition at line 38 of file PHG4mRICHSteppingAction.h.
Referenced by SetInterfacePointers().
PHG4Hit* PHG4mRICHSteppingAction::hit private
Definition at line 44 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4mRICHSteppingAction::hits_ private
pointer to hit container
Definition at line 42 of file PHG4mRICHSteppingAction.h.
Referenced by SetInterfacePointers().
int PHG4mRICHSteppingAction::IsBlackHole private
Definition at line 36 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction().
std::string PHG4mRICHSteppingAction::superdetector private
Definition at line 39 of file PHG4mRICHSteppingAction.h.
Referenced by SetInterfacePointers().
int PHG4mRICHSteppingAction::use_g4_steps private
Definition at line 37 of file PHG4mRICHSteppingAction.h.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4mRICHSteppingAction.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4mRICHSteppingAction.cc