Class Reference for E1039 Core & Analysis Software: SQRun Class Reference
SQRun Class Reference
An SQ interface class to hold the run-level info.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQRun.h>
Public Member Functions
virtual ~SQRun ()
void Reset ()
Clear Event.
virtual void identify (std::ostream &os=std::cout) const
virtual int get_run_id () const
Return the run ID.
virtual void set_run_id (const int a)
virtual int get_unix_time_begin () const
Return the Unix time when this run began.
virtual void set_unix_time_begin (const int a)
virtual int get_unix_time_end () const
Return the Unix time when this run ended.
virtual void set_unix_time_end (const int a)
virtual int get_fpga_enabled (const int chan) const
Return 'true' if the given channel ('chan') of the FPGA trigger was enabled in this run.
virtual void set_fpga_enabled (const int chan, const int a)
virtual int get_nim_enabled (const int chan) const
Return 'true' if the given channel ('chan') of the NIM trigger was enabled in this run.
virtual void set_nim_enabled (const int chan, const int a)
virtual int get_fpga_prescale (const int chan) const
Return the prescale factor of the given channel ('chan') of the FPGA trigger in this run.
virtual void set_fpga_prescale (const int chan, const int a)
virtual int get_nim_prescale (const int chan) const
Return the prescale factor of the given channel ('chan') of the NIM trigger in this run.
virtual void set_nim_prescale (const int chan, const int a)
virtual int get_v1495_id (const int chan) const
Return the ID of the chan-th V1495 boards.
virtual void set_v1495_id (const int chan, const int id)
virtual std::string get_run_desc () const
Return the run description of this run.
virtual void set_run_desc (const std::string a)
virtual int get_n_fee_event () const
Return the number of FEE events.
virtual void set_n_fee_event (const int a)
virtual int get_n_fee_prescale () const
Return the number of FEE-prescale events.
virtual void set_n_fee_prescale (const int a)
virtual int get_n_run_desc () const
Return the number of run-description events.
virtual void set_n_run_desc (const int a)
virtual int get_n_spill () const
Return the number of spill events.
virtual void set_n_spill (const int a)
virtual int get_n_evt_all () const
Return the number of all recorded events.
virtual void set_n_evt_all (const int a)
virtual int get_n_evt_dec () const
Return the number of decoded events. The online decoding usually skips a part of events in order to finish in time.
virtual void set_n_evt_dec (const int a)
virtual int get_n_phys_evt () const
Return the number of all PHYSICS events.
virtual void set_n_phys_evt (const int a)
virtual int get_n_phys_evt_bad () const
Return the number of bad PHYSICS events.
virtual void set_n_phys_evt_bad (const int a)
virtual int get_n_flush_evt () const
Return the number of all FLUSH events.
virtual void set_n_flush_evt (const int a)
virtual int get_n_flush_evt_bad () const
Return the number of bad FLUSH events.
virtual void set_n_flush_evt_bad (const int a)
virtual int get_n_hit () const
Return the number of all Taiwan-TDC hits.
virtual void set_n_hit (const int a)
virtual int get_n_t_hit () const
Return the number of all V1495-TDC (i.e. trigger) hits.
virtual void set_n_t_hit (const int a)
virtual int get_n_hit_bad () const
Return the number of bad Taiwan-TDC hits.
virtual void set_n_hit_bad (const int a)
virtual int get_n_t_hit_bad () const
Return the number of bad V1495-TDC (i.e. trigger) hits.
virtual void set_n_t_hit_bad (const int a)
virtual int get_n_v1495 () const
Return the number of all V1495 events.
virtual void set_n_v1495 (const int a)
virtual int get_n_v1495_d1ad () const
Return the number of V1495 events having 'd1ad'.
virtual void set_n_v1495_d1ad (const int a)
virtual int get_n_v1495_d2ad () const
Return the number of V1495 events having 'd2ad'.
virtual void set_n_v1495_d2ad (const int a)
virtual int get_n_v1495_d3ad () const
Return the number of V1495 events having 'd3ad'.
virtual void set_n_v1495_d3ad (const int a)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQRun ()
ClassDef (SQRun, 1)
Detailed Description
An SQ interface class to hold the run-level info.
Definition at line 18 of file SQRun.h.
Constructor & Destructor Documentation
~SQRun()
virtual SQRun::~SQRun () inline virtual
Definition at line 22 of file SQRun.h.
SQRun()
SQRun::SQRun () inline protected
Definition at line 115 of file SQRun.h.
Member Function Documentation
ClassDef()
SQRun::ClassDef (SQRun , 1) protected
get_fpga_enabled()
virtual int SQRun::get_fpga_enabled (const int chan) const inline virtual
Return 'true' if the given channel ('chan') of the FPGA trigger was enabled in this run.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 41 of file SQRun.h.
get_fpga_prescale()
virtual int SQRun::get_fpga_prescale (const int chan) const inline virtual
Return the prescale factor of the given channel ('chan') of the FPGA trigger in this run.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 47 of file SQRun.h.
get_n_evt_all()
virtual int SQRun::get_n_evt_all () const inline virtual
Return the number of all recorded events.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 71 of file SQRun.h.
get_n_evt_dec()
virtual int SQRun::get_n_evt_dec () const inline virtual
Return the number of decoded events. The online decoding usually skips a part of events in order to finish in time.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 74 of file SQRun.h.
get_n_fee_event()
virtual int SQRun::get_n_fee_event () const inline virtual
Return the number of FEE events.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 59 of file SQRun.h.
get_n_fee_prescale()
virtual int SQRun::get_n_fee_prescale () const inline virtual
Return the number of FEE-prescale events.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 62 of file SQRun.h.
get_n_flush_evt()
virtual int SQRun::get_n_flush_evt () const inline virtual
Return the number of all FLUSH events.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 83 of file SQRun.h.
get_n_flush_evt_bad()
virtual int SQRun::get_n_flush_evt_bad () const inline virtual
Return the number of bad FLUSH events.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 86 of file SQRun.h.
get_n_hit()
virtual int SQRun::get_n_hit () const inline virtual
Return the number of all Taiwan-TDC hits.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 89 of file SQRun.h.
get_n_hit_bad()
virtual int SQRun::get_n_hit_bad () const inline virtual
Return the number of bad Taiwan-TDC hits.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 95 of file SQRun.h.
get_n_phys_evt()
virtual int SQRun::get_n_phys_evt () const inline virtual
Return the number of all PHYSICS events.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 77 of file SQRun.h.
get_n_phys_evt_bad()
virtual int SQRun::get_n_phys_evt_bad () const inline virtual
Return the number of bad PHYSICS events.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 80 of file SQRun.h.
get_n_run_desc()
virtual int SQRun::get_n_run_desc () const inline virtual
Return the number of run-description events.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 65 of file SQRun.h.
get_n_spill()
virtual int SQRun::get_n_spill () const inline virtual
Return the number of spill events.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 68 of file SQRun.h.
get_n_t_hit()
virtual int SQRun::get_n_t_hit () const inline virtual
Return the number of all V1495-TDC (i.e. trigger) hits.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 92 of file SQRun.h.
get_n_t_hit_bad()
virtual int SQRun::get_n_t_hit_bad () const inline virtual
Return the number of bad V1495-TDC (i.e. trigger) hits.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 98 of file SQRun.h.
get_n_v1495()
virtual int SQRun::get_n_v1495 () const inline virtual
Return the number of all V1495 events.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 101 of file SQRun.h.
get_n_v1495_d1ad()
virtual int SQRun::get_n_v1495_d1ad () const inline virtual
Return the number of V1495 events having 'd1ad'.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 104 of file SQRun.h.
get_n_v1495_d2ad()
virtual int SQRun::get_n_v1495_d2ad () const inline virtual
Return the number of V1495 events having 'd2ad'.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 107 of file SQRun.h.
get_n_v1495_d3ad()
virtual int SQRun::get_n_v1495_d3ad () const inline virtual
Return the number of V1495 events having 'd3ad'.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 110 of file SQRun.h.
get_nim_enabled()
virtual int SQRun::get_nim_enabled (const int chan) const inline virtual
Return 'true' if the given channel ('chan') of the NIM trigger was enabled in this run.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 44 of file SQRun.h.
get_nim_prescale()
virtual int SQRun::get_nim_prescale (const int chan) const inline virtual
Return the prescale factor of the given channel ('chan') of the NIM trigger in this run.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 50 of file SQRun.h.
get_run_desc()
virtual std::string SQRun::get_run_desc () const inline virtual
Return the run description of this run.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 56 of file SQRun.h.
get_run_id()
virtual int SQRun::get_run_id () const inline virtual
Return the run ID.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 32 of file SQRun.h.
Referenced by DbUpRun::End(), DbUpRun::InitRun(), DbUpSpill::InitRun(), and DbUpRun::process_event().
get_unix_time_begin()
virtual int SQRun::get_unix_time_begin () const inline virtual
Return the Unix time when this run began.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 35 of file SQRun.h.
get_unix_time_end()
virtual int SQRun::get_unix_time_end () const inline virtual
Return the Unix time when this run ended.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 38 of file SQRun.h.
get_v1495_id()
virtual int SQRun::get_v1495_id (const int chan) const inline virtual
Return the ID of the chan-th V1495 boards.
Reimplemented in SQRun_v2.
Definition at line 53 of file SQRun.h.
Referenced by AnaDimuon::InitRun(), AnaDimuonLikeSign::InitRun(), and AnaDimuonV2::InitRun().
identify()
virtual void SQRun::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 26 of file SQRun.h.
Reset()
void SQRun::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 24 of file SQRun.h.
set_fpga_enabled()
virtual void SQRun::set_fpga_enabled (const int chan, const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 42 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_fpga_prescale()
virtual void SQRun::set_fpga_prescale (const int chan, const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 48 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_evt_all()
virtual void SQRun::set_n_evt_all (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 72 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_evt_dec()
virtual void SQRun::set_n_evt_dec (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 75 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_fee_event()
virtual void SQRun::set_n_fee_event (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 60 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_fee_prescale()
virtual void SQRun::set_n_fee_prescale (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 63 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_flush_evt()
virtual void SQRun::set_n_flush_evt (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 84 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_flush_evt_bad()
virtual void SQRun::set_n_flush_evt_bad (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 87 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_hit()
virtual void SQRun::set_n_hit (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 90 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_hit_bad()
virtual void SQRun::set_n_hit_bad (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 96 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_phys_evt()
virtual void SQRun::set_n_phys_evt (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 78 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_phys_evt_bad()
virtual void SQRun::set_n_phys_evt_bad (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 81 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_run_desc()
virtual void SQRun::set_n_run_desc (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 66 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_spill()
virtual void SQRun::set_n_spill (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 69 of file SQRun.h.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), Fun4AllEVIOInputManager::run(), Fun4AllVectEventInputManager::VectToE1039(), and Fun4AllRUSInputManager::VectToE1039().
set_n_t_hit()
virtual void SQRun::set_n_t_hit (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 93 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_t_hit_bad()
virtual void SQRun::set_n_t_hit_bad (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 99 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_v1495()
virtual void SQRun::set_n_v1495 (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 102 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_v1495_d1ad()
virtual void SQRun::set_n_v1495_d1ad (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 105 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_v1495_d2ad()
virtual void SQRun::set_n_v1495_d2ad (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 108 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_n_v1495_d3ad()
virtual void SQRun::set_n_v1495_d3ad (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 111 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_nim_enabled()
virtual void SQRun::set_nim_enabled (const int chan, const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 45 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_nim_prescale()
virtual void SQRun::set_nim_prescale (const int chan, const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 51 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_run_desc()
virtual void SQRun::set_run_desc (const std::string a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 57 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_run_id()
virtual void SQRun::set_run_id (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 33 of file SQRun.h.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), PHG4TruthSubsystem::InitRun(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_unix_time_begin()
virtual void SQRun::set_unix_time_begin (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 36 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
set_unix_time_end()
virtual void SQRun::set_unix_time_end (const int a) inline virtual
Reimplemented in SQRun_v2, and SQRun_v1.
Definition at line 39 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::fileclose(), and Fun4AllEVIOInputManager::run().
set_v1495_id()
virtual void SQRun::set_v1495_id (const int chan, const int id) inline virtual
Reimplemented in SQRun_v2.
Definition at line 54 of file SQRun.h.
Referenced by Fun4AllEVIOInputManager::run().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQRun.h