Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TrkDev/Fun4PatternDB.C File Reference
Fun4PatternDB.C File Reference
#include <iostream>
Functions
int Fun4PatternDB (const int nEvents=1, const int nmu=1, const double target_coil_pos_z=-300)
PHG4ParticleGun * get_gun (const char *name="PGUN")
Function Documentation
int Fun4PatternDB (const int nEvents = 1, const int nmu = 1, const double target_coil_pos_z = -300)
Definition at line 6 of file Fun4PatternDB.C.
References PHG4PSScanGenerator::add_particles(), PHG4SimpleEventGenerator::add_particles(), PHG4DSTReader::AddNode(), PHPy8ParticleTrigger::AddParticles(), Fun4AllServer::End(), HepMCNodeReader::insert_particle_filter_pid(), Fun4AllServer::instance(), GeomSvc::instance(), Fun4AllServer::PrintTimer(), PHPythia8::register_trigger(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), se, PHPythia8::set_config_file(), PHG4Reco::set_field_map(), PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHG4ParticleGeneratorBase::set_mom(), PHG4ParticleGeneratorBase::set_name(), HepMCNodeReader::set_particle_filter_on(), PHG4PSScanGenerator::set_px_step(), PHG4SimpleEventGenerator::set_pxpypz_range(), PHG4PSScanGenerator::set_pxpypz_range(), PHG4PSScanGenerator::set_py_step(), PHG4PSScanGenerator::set_pz_step(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), PHPythia8::set_trigger_AND(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4PSScanGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4PSScanGenerator::set_vertex_distribution_mean(), PHPythia8::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4PSScanGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4PSScanGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), PHG4PSScanGenerator::set_vertex_size_parameters(), PHG4ParticleGeneratorBase::set_vtx(), PHG4Reco::SetPhysicsList(), PHPy8ParticleTrigger::SetPzHighLow(), SetupSensitiveDetectors(), SetupTarget(), PHG4Reco::SetWorldMaterial(), PHG4Reco::SetWorldShape(), PHG4Reco::SetWorldSizeX(), PHG4Reco::SetWorldSizeY(), PHG4Reco::SetWorldSizeZ(), PHG4PSScanGenerator::Uniform, PHG4SimpleEventGenerator::Uniform, and Fun4AllBase::Verbosity().
PHG4ParticleGun* get_gun (const char * name = "PGUN")
Definition at line 213 of file Fun4PatternDB.C.
References Fun4AllServer::getSubsysReco(), Fun4AllServer::instance(), and se.