Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TrkDev/ana.C File Reference
ana.C File Reference
Functions
double ratio_error (const double a, const double b, const double ea, const double eb)
double binom_error (const double a, const double b)
TH1D * getEffHist (const char *hname, const TH1D *h1, const TH1D *h2)
void drawTimeNumber ()
void drawTimeMul ()
void drawTimeAna (const char *name, const char *cut)
void drawEffMul ()
void drawEffDS123Survey ()
void drawEffDSLevel (const char *tree="T", const char *var="pz<500", const char *cut="krecstat!=-1&&gndc>=18")
void drawEffDS23Survey ()
void ana ()
Function Documentation
void ana ()
Definition at line 283 of file ana.C.
References drawEffDSLevel().
double binom_error (const double a, const double b)
Definition at line 16 of file ana.C.
void drawEffDS123Survey ()
Definition at line 167 of file ana.C.
void drawEffDS23Survey ()
Definition at line 249 of file ana.C.
void drawEffDSLevel (const char * tree = "T", const char * var = "pz<500", const char * cut = "krecstat!=-1&&gndc>=18")
Definition at line 203 of file ana.C.
References tree.
Referenced by ana().
void drawEffMul ()
Definition at line 132 of file ana.C.
void drawTimeAna (const char * name, const char * cut)
Definition at line 91 of file ana.C.
void drawTimeMul ()
Definition at line 67 of file ana.C.
void drawTimeNumber ()
Definition at line 43 of file ana.C.
TH1D* getEffHist (const char * hname, const TH1D * h1, const TH1D * h2)
Definition at line 24 of file ana.C.
References binom_error().
double ratio_error (const double a, const double b, const double ea, const double eb)
Definition at line 3 of file ana.C.