SeaQuest Offline Software: ReadMySql Class Reference
ReadMySql Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/module_example/ReadMySql.h>
Public Member Functions
ReadMySql (const std::string &name="ReadMySql")
virtual ~ReadMySql ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int FillSQRun (SQRun *run_header, TSQLServer *server, const int run_id, const char *table="Run")
int FillSQSpill (SQSpillMap *spill_map, TSQLServer *server, const int run_id, const char *table="Spill")
int FillSQEvent (SQEvent *event_header, TSQLServer *server, const int event_id, const char *table="Event")
int FillSQHitMap (SQHitMap *hit_map, TSQLServer *server, const int event_id, const char *table="Hit")
int FillSQHitVector (SQHitVector *hit_vector, const std::string hit_type, TSQLServer *server, const int event_id, const char *table="Hit")
int FillSQTriggerHitVector (SQHitVector *hit_vector, const std::string hit_type, TSQLServer *server, const int event_id, const char *table="TriggerHit")
const std::string & get_hit_container_type () const
void set_hit_container_type (const std::string &hitContainerChoice)
const std::string & get_hit_type () const
void set_hit_type (const std::string &hitType)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static int getInt (TSQLRow *row, int id, int default_val=0)
static float getFloat (TSQLRow *row, int id, float default_val=0.)
static double getDouble (TSQLRow *row, int id, double default_val=0.)
static std::string getString (TSQLRow *row, int id, std::string default_val="")
Private Types
typedef std::map< std::string,
short > _m_detector_name_to_id
Private Member Functions
int MakeNodes (PHCompositeNode *topNode)
int GetNodes (PHCompositeNode *topNode)
int makeQueryInput ()
bool nextEntry ()
Private Attributes
std::string _hit_type
std::string _hit_container_type
std::string _server_name
int _port
std::string _user_name
std::string _password
std::string _input_shcema
std::string _table_name
int _run_id
int _spill_id
char _query [2000]
TSQLServer * _input_server
TSQLResult * _res
TSQLRow * _row
GeomSvc * p_geomSvc
std::vector< int > _event_ids
size_t _event
SQRun * _run_header
SQSpillMap * _spill_map
SQEvent * _event_header
SQHitMap * _hit_map
SQHitVector * _hit_vector
SQHitVector * _triggerhit_vector
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 35 of file ReadMySql.h.
Member Typedef Documentation
typedef std::map<std::string, short> ReadMySql::_m_detector_name_to_id private
Definition at line 120 of file ReadMySql.h.
Constructor & Destructor Documentation
ReadMySql::ReadMySql (const std::string & name = "ReadMySql")
Definition at line 41 of file ReadMySql.cxx.
References _event_ids.
virtual ReadMySql::~ReadMySql () inline virtual
Definition at line 40 of file ReadMySql.h.
Member Function Documentation
int ReadMySql::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 145 of file ReadMySql.cxx.
References Fun4AllReturnCodes::EVENT_OK, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int ReadMySql::FillSQEvent (SQEvent * event_header, TSQLServer * server, const int event_id, const char * table = "Event")
Definition at line 539 of file ReadMySql.cxx.
References getInt(), LogError, SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, SQEvent::MATRIX5, SQEvent::NIM1, SQEvent::NIM2, SQEvent::NIM3, SQEvent::NIM4, SQEvent::NIM5, SQEvent::set_coda_event_id(), SQEvent::set_event_id(), SQEvent::set_run_id(), SQEvent::set_spill_id(), and SQEvent::set_trigger().
Referenced by process_event().
int ReadMySql::FillSQHitMap (SQHitMap * hit_map, TSQLServer * server, const int event_id, const char * table = "Hit")
Definition at line 322 of file ReadMySql.cxx.
References getFloat(), getInt(), SQHitMap::insert(), LogError, SQHit::set_detector_id(), SQHit::set_drift_distance(), SQHit::set_element_id(), SQHit::set_hit_id(), SQHit::set_hodo_mask(), SQHit::set_in_time(), SQHit::set_pos(), and SQHit::set_tdc_time().
Referenced by process_event().
int ReadMySql::FillSQHitVector (SQHitVector * hit_vector, const std::string hit_type, TSQLServer * server, const int event_id, const char * table = "Hit")
Definition at line 374 of file ReadMySql.cxx.
References SQHit::get_detector_id(), SQHit::get_element_id(), GeomSvc::getDetectorID(), getFloat(), getInt(), GeomSvc::getMeasurement(), LogError, p_geomSvc, SQHitVector::push_back(), SQHit::set_detector_id(), SQHit::set_drift_distance(), SQHit::set_element_id(), SQHit::set_hit_id(), SQHit::set_hodo_mask(), SQHit::set_in_time(), SQHit::set_pos(), SQHit::set_tdc_time(), SQHit::set_trigger_mask(), and GeomSvc::toLocalDetectorName().
Referenced by process_event().
int ReadMySql::FillSQRun (SQRun * run_header, TSQLServer * server, const int run_id, const char * table = "Run")
Definition at line 600 of file ReadMySql.cxx.
References getInt(), getString(), LogError, SQRun::set_run_id(), and SQRun::set_spill_count().
Referenced by InitRun().
int ReadMySql::FillSQSpill (SQSpillMap * spill_map, TSQLServer * server, const int run_id, const char * table = "Spill")
Definition at line 641 of file ReadMySql.cxx.
References getInt(), SQSpillMap::insert(), LogError, SQSpill::set_run_id(), SQSpill::set_spill_id(), and SQSpill::set_target_pos().
Referenced by InitRun().
int ReadMySql::FillSQTriggerHitVector (SQHitVector * hit_vector, const std::string hit_type, TSQLServer * server, const int event_id, const char * table = "TriggerHit")
Definition at line 467 of file ReadMySql.cxx.
References SQHit::get_detector_id(), SQHit::get_element_id(), GeomSvc::getDetectorID(), getFloat(), getInt(), GeomSvc::getMeasurement(), LogError, p_geomSvc, SQHitVector::push_back(), SQHit::set_detector_id(), SQHit::set_drift_distance(), SQHit::set_element_id(), SQHit::set_hit_id(), SQHit::set_in_time(), SQHit::set_pos(), and SQHit::set_tdc_time().
Referenced by process_event().
const std::string& ReadMySql::get_hit_container_type () const inline
Definition at line 62 of file ReadMySql.h.
References _hit_container_type.
const std::string& ReadMySql::get_hit_type () const inline
Definition at line 70 of file ReadMySql.h.
References _hit_type.
double ReadMySql::getDouble (TSQLRow * row, int id, double default_val = 0.) static
Definition at line 302 of file ReadMySql.cxx.
References NULL.
float ReadMySql::getFloat (TSQLRow * row, int id, float default_val = 0.) static
Definition at line 292 of file ReadMySql.cxx.
References NULL.
Referenced by FillSQHitMap(), FillSQHitVector(), and FillSQTriggerHitVector().
int ReadMySql::getInt (TSQLRow * row, int id, int default_val = 0) static
Definition at line 275 of file ReadMySql.cxx.
References NULL.
Referenced by FillSQEvent(), FillSQHitMap(), FillSQHitVector(), FillSQRun(), FillSQSpill(), FillSQTriggerHitVector(), and InitRun().
int ReadMySql::GetNodes (PHCompositeNode * topNode) private
Definition at line 212 of file ReadMySql.cxx.
References _event_header, _hit_container_type, _hit_map, _hit_vector, _run_header, _spill_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and LogError.
Referenced by InitRun().
std::string ReadMySql::getString (TSQLRow * row, int id, std::string default_val = "") static
Definition at line 312 of file ReadMySql.cxx.
References NULL.
Referenced by FillSQRun().
int ReadMySql::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 67 of file ReadMySql.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int ReadMySql::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 71 of file ReadMySql.cxx.
References _event_ids, _input_server, _input_shcema, _password, _port, _query, _row, _run_header, _server_name, _spill_map, _user_name, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, FillSQRun(), FillSQSpill(), getInt(), GetNodes(), GeomSvc::instance(), LogError, MakeNodes(), makeQueryInput(), nextEntry(), p_geomSvc, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_QUIET.
int ReadMySql::MakeNodes (PHCompositeNode * topNode) private
Definition at line 151 of file ReadMySql.cxx.
References _event_header, _hit_container_type, _hit_map, _hit_vector, _run_header, _spill_map, _triggerhit_vector, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), LogInfo, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_SOME.
Referenced by InitRun().
int ReadMySql::makeQueryInput () private
Definition at line 253 of file ReadMySql.cxx.
References _input_server, _query, _res, and NULL.
Referenced by InitRun().
bool ReadMySql::nextEntry () private
Definition at line 264 of file ReadMySql.cxx.
References _res, _row, and NULL.
Referenced by InitRun().
int ReadMySql::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 118 of file ReadMySql.cxx.
References _event, _event_header, _event_ids, _hit_container_type, _hit_map, _hit_type, _hit_vector, _input_server, _triggerhit_vector, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, FillSQEvent(), FillSQHitMap(), FillSQHitVector(), FillSQTriggerHitVector(), SQEvent::identify(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
void ReadMySql::set_hit_container_type (const std::string & hitContainerChoice) inline
Definition at line 66 of file ReadMySql.h.
References _hit_container_type.
Referenced by Fun4ReadMySql(), and Fun4SeaQuest().
void ReadMySql::set_hit_type (const std::string & hitType) inline
Definition at line 74 of file ReadMySql.h.
References _hit_type.
Referenced by Fun4ReadMySql(), and Fun4SeaQuest().
Member Data Documentation
size_t ReadMySql::_event private
Definition at line 110 of file ReadMySql.h.
Referenced by process_event().
SQEvent* ReadMySql::_event_header private
Definition at line 115 of file ReadMySql.h.
Referenced by GetNodes(), MakeNodes(), and process_event().
std::vector<int> ReadMySql::_event_ids private
Definition at line 109 of file ReadMySql.h.
Referenced by InitRun(), process_event(), and ReadMySql().
std::string ReadMySql::_hit_container_type private
Definition at line 87 of file ReadMySql.h.
Referenced by get_hit_container_type(), GetNodes(), MakeNodes(), process_event(), and set_hit_container_type().
SQHitMap* ReadMySql::_hit_map private
Definition at line 116 of file ReadMySql.h.
Referenced by GetNodes(), MakeNodes(), and process_event().
std::string ReadMySql::_hit_type private
Definition at line 86 of file ReadMySql.h.
Referenced by get_hit_type(), process_event(), and set_hit_type().
SQHitVector* ReadMySql::_hit_vector private
Definition at line 117 of file ReadMySql.h.
Referenced by GetNodes(), MakeNodes(), and process_event().
TSQLServer* ReadMySql::_input_server private
Definition at line 102 of file ReadMySql.h.
Referenced by InitRun(), makeQueryInput(), and process_event().
std::string ReadMySql::_input_shcema private
Definition at line 93 of file ReadMySql.h.
Referenced by InitRun().
std::string ReadMySql::_password private
Definition at line 92 of file ReadMySql.h.
Referenced by InitRun().
int ReadMySql::_port private
Definition at line 90 of file ReadMySql.h.
Referenced by InitRun().
char ReadMySql::_query[2000] private
Definition at line 99 of file ReadMySql.h.
Referenced by InitRun(), and makeQueryInput().
TSQLResult* ReadMySql::_res private
Definition at line 103 of file ReadMySql.h.
Referenced by makeQueryInput(), and nextEntry().
TSQLRow* ReadMySql::_row private
Definition at line 104 of file ReadMySql.h.
Referenced by InitRun(), and nextEntry().
SQRun* ReadMySql::_run_header private
Definition at line 112 of file ReadMySql.h.
Referenced by GetNodes(), InitRun(), and MakeNodes().
int ReadMySql::_run_id private
Definition at line 95 of file ReadMySql.h.
std::string ReadMySql::_server_name private
Definition at line 89 of file ReadMySql.h.
Referenced by InitRun().
int ReadMySql::_spill_id private
Definition at line 96 of file ReadMySql.h.
SQSpillMap* ReadMySql::_spill_map private
Definition at line 113 of file ReadMySql.h.
Referenced by GetNodes(), InitRun(), and MakeNodes().
std::string ReadMySql::_table_name private
Definition at line 94 of file ReadMySql.h.
SQHitVector* ReadMySql::_triggerhit_vector private
Definition at line 118 of file ReadMySql.h.
Referenced by MakeNodes(), and process_event().
std::string ReadMySql::_user_name private
Definition at line 91 of file ReadMySql.h.
Referenced by InitRun().
GeomSvc* ReadMySql::p_geomSvc private
Definition at line 107 of file ReadMySql.h.
Referenced by FillSQHitVector(), FillSQTriggerHitVector(), and InitRun().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/module_example/ReadMySql.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/module_example/ReadMySql.cxx