Class Reference for E1039 Core & Analysis Software: UtilSRawEvent Namespace Reference
UtilSRawEvent Namespace Reference
A set of utility functions about SRawEvent.
Functions
bool SetEvent (SRawEvent *sraw, const SQEvent *evt, const bool do_assert=false)
bool SetSpill (SRawEvent *sraw, const SQSpill *sp, const bool do_assert=false)
bool SetHit (SRawEvent *sraw, const SQHitVector *hit_vec, std::map< int, size_t > *hitID_idx=0, const bool do_assert=false)
bool SetTriggerHit (SRawEvent *sraw, const SQHitVector *hit_vec, std::map< int, size_t > *hitID_idx=0, const bool do_assert=false)
Detailed Description
A set of utility functions about SRawEvent.
Function Documentation
bool UtilSRawEvent::SetEvent (SRawEvent * sraw, const SQEvent * evt, const bool do_assert = false)
Definition at line 10 of file UtilSRawEvent.cxx.
References SQEvent::get_event_id(), SQEvent::get_run_id(), SQEvent::get_spill_id(), SQEvent::get_trigger(), SQEvent::MATRIX5, SQEvent::NIM1, PHWHERE, SRawEvent::setEventInfo(), and SRawEvent::setTriggerBits().
Referenced by Fun4AllSRawEventOutputManager::Write().
bool UtilSRawEvent::SetHit (SRawEvent * sraw, const SQHitVector * hit_vec, std::map< int, size_t > * hitID_idx = 0, const bool do_assert = false)
Definition at line 48 of file UtilSRawEvent.cxx.
References SQHitVector::at(), Hit::detectorID, Hit::driftDistance, Hit::elementID, SRawEvent::emptyHits(), SQHit::get_detector_id(), SQHit::get_drift_distance(), SQHit::get_element_id(), SQHit::get_hit_id(), SQHit::get_pos(), SQHit::get_tdc_time(), Hit::index, SRawEvent::insertHit(), SQHit::is_in_time(), PHWHERE, Hit::pos, SRawEvent::reIndex(), Hit::setInTime(), SQHitVector::size(), and Hit::tdcTime.
Referenced by Fun4AllSRawEventOutputManager::Write().
bool UtilSRawEvent::SetSpill (SRawEvent * sraw, const SQSpill * sp, const bool do_assert = false)
Definition at line 34 of file UtilSRawEvent.cxx.
References SQSpill::get_target_pos(), PHWHERE, and SRawEvent::setTargetPos().
Referenced by Fun4AllSRawEventOutputManager::Write().
bool UtilSRawEvent::SetTriggerHit (SRawEvent * sraw, const SQHitVector * hit_vec, std::map< int, size_t > * hitID_idx = 0, const bool do_assert = false)
Definition at line 78 of file UtilSRawEvent.cxx.
References SQHitVector::at(), Hit::detectorID, Hit::driftDistance, Hit::elementID, SRawEvent::emptyTriggerHits(), SQHit::get_detector_id(), SQHit::get_drift_distance(), SQHit::get_element_id(), SQHit::get_hit_id(), SQHit::get_pos(), SQHit::get_tdc_time(), Hit::index, SRawEvent::insertTriggerHit(), SQHit::is_in_time(), PHWHERE, Hit::pos, Hit::setInTime(), SQHitVector::size(), and Hit::tdcTime.
Referenced by Fun4AllSRawEventOutputManager::Write().