SeaQuest Offline Software: PHG4MapsDetector Class Reference
PHG4MapsDetector Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4MapsDetector.h>
Public Member Functions
PHG4MapsDetector (PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam="BLOCK")
constructor
virtual ~PHG4MapsDetector ()
destructor
virtual void Construct (G4LogicalVolume *world)
construct
void set_stave_type (const int st)
void set_nominal_layer_radius (const G4double radius)
void set_pixel_x (const double pixel_x_in)
void set_pixel_z (const double pixel_z_in)
void set_pixel_thickness (const double pixel_thickness_in)
void SetPlaceZ (const G4double place_z)
void SetPlace (const G4double place_x, const G4double place_y, const G4double place_z)
void SetXRot (const G4double angle)
void SetYRot (const G4double angle)
void SetZRot (const G4double angle)
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
int IsActive () const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
void Detector (const std::string &name)
const std::string Detector () const
int get_Layer () const
void BlackHole (const int i=1)
int IsBlackHole () const
volume accessors
int IsInMaps (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Private Member Functions
void AddGeometryNode ()
int ConstructMaps (G4LogicalVolume *sandwich)
void SetDisplayProperty (G4AssemblyVolume *av)
void SetDisplayProperty (G4LogicalVolume *lv)
Private Attributes
G4double envelope_inner_radius
G4double envelope_outer_radius
G4double envelope_z
G4double place_in_x
G4double place_in_y
G4double place_in_z
G4double x_rot
G4double y_rot
G4double z_rot
int active
int absorberactive
int layer
int blackhole
int stave_type
G4double layer_nominal_radius
int N_staves
G4double phistep
G4double phitilt
double pixel_x
double pixel_z
double pixel_thickness
std::string layer_string
std::string detector_type
std::string superdetector
std::string stave_geometry_file
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 22 of file PHG4MapsDetector.h.
Constructor & Destructor Documentation
PHG4MapsDetector::PHG4MapsDetector (PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam = "BLOCK")
constructor
Definition at line 38 of file PHG4MapsDetector.cc.
References layer, layer_string, PHG4Detector::name, stave_type, and PHG4Detector::verbosity.
PHG4MapsDetector::~PHG4MapsDetector () virtual
destructor
Definition at line 80 of file PHG4MapsDetector.cc.
Member Function Documentation
void PHG4MapsDetector::AddGeometryNode () private
Definition at line 362 of file PHG4MapsDetector.cc.
References active, PHG4CylinderGeomContainer::AddLayerGeom(), PHCompositeNode::addNode(), detector_type, PHNodeIterator::findFirst(), PHG4CylinderGeomContainer::identify(), layer, layer_nominal_radius, N_staves, phistep, phitilt, pixel_thickness, pixel_x, pixel_z, stave_type, superdetector, PHG4Detector::topNode, and PHG4Detector::Verbosity().
Referenced by Construct().
void PHG4MapsDetector::BlackHole (const int i = 1) inline
Definition at line 65 of file PHG4MapsDetector.h.
References blackhole.
void PHG4MapsDetector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 102 of file PHG4MapsDetector.cc.
References AddGeometryNode(), ConstructMaps(), layer, layer_nominal_radius, PHWHERE, stave_type, and PHG4Detector::verbosity.
int PHG4MapsDetector::ConstructMaps (G4LogicalVolume * sandwich) private
Definition at line 125 of file PHG4MapsDetector.cc.
References layer, layer_nominal_radius, N_staves, PHG4Detector::overlapcheck, phistep, phitilt, SetDisplayProperty(), stave_geometry_file, stave_type, PHG4Detector::Verbosity(), and PHG4Detector::verbosity.
Referenced by Construct().
void PHG4MapsDetector::Detector (const std::string & name) inline
Definition at line 61 of file PHG4MapsDetector.h.
References detector_type, and PHG4Detector::name.
Referenced by PHG4MapsSubsystem::InitRunSubsystem().
const std::string PHG4MapsDetector::Detector () const inline
Definition at line 62 of file PHG4MapsDetector.h.
References detector_type.
int PHG4MapsDetector::get_Layer () const inline
Definition at line 63 of file PHG4MapsDetector.h.
References layer.
Referenced by PHG4MapsSteppingAction::UserSteppingAction().
int PHG4MapsDetector::IsActive () const inline
Definition at line 58 of file PHG4MapsDetector.h.
References active.
Referenced by PHG4MapsSteppingAction::UserSteppingAction().
int PHG4MapsDetector::IsBlackHole () const inline
Definition at line 66 of file PHG4MapsDetector.h.
References blackhole.
Referenced by PHG4MapsSteppingAction::UserSteppingAction().
int PHG4MapsDetector::IsInMaps (G4VPhysicalVolume * volume) const
Definition at line 86 of file PHG4MapsDetector.cc.
References layer_string.
Referenced by PHG4MapsSteppingAction::UserSteppingAction().
void PHG4MapsDetector::set_nominal_layer_radius (const G4double radius) inline
Definition at line 42 of file PHG4MapsDetector.h.
References layer_nominal_radius.
void PHG4MapsDetector::set_pixel_thickness (const double pixel_thickness_in) inline
Definition at line 45 of file PHG4MapsDetector.h.
References pixel_thickness.
void PHG4MapsDetector::set_pixel_x (const double pixel_x_in) inline
Definition at line 43 of file PHG4MapsDetector.h.
References pixel_x.
void PHG4MapsDetector::set_pixel_z (const double pixel_z_in) inline
Definition at line 44 of file PHG4MapsDetector.h.
References pixel_z.
void PHG4MapsDetector::set_stave_type (const int st) inline
Definition at line 41 of file PHG4MapsDetector.h.
References stave_type.
void PHG4MapsDetector::SetAbsorberActive (const int i = 1) inline
Definition at line 57 of file PHG4MapsDetector.h.
References absorberactive.
void PHG4MapsDetector::SetActive (const int i = 1) inline
Definition at line 56 of file PHG4MapsDetector.h.
References active.
void PHG4MapsDetector::SetDisplayProperty (G4AssemblyVolume * av) private
Definition at line 263 of file PHG4MapsDetector.cc.
Referenced by ConstructMaps(), and SetDisplayProperty().
void PHG4MapsDetector::SetDisplayProperty (G4LogicalVolume * lv) private
Definition at line 282 of file PHG4MapsDetector.cc.
References PHG4Utils::SetColour(), SetDisplayProperty(), and PHG4Detector::Verbosity().
void PHG4MapsDetector::SetPlace (const G4double place_x, const G4double place_y, const G4double place_z) inline
Definition at line 47 of file PHG4MapsDetector.h.
References place_in_x, place_in_y, and place_in_z.
void PHG4MapsDetector::SetPlaceZ (const G4double place_z) inline
Definition at line 46 of file PHG4MapsDetector.h.
References place_in_z.
void PHG4MapsDetector::SetXRot (const G4double angle) inline
Definition at line 53 of file PHG4MapsDetector.h.
References x_rot.
void PHG4MapsDetector::SetYRot (const G4double angle) inline
Definition at line 54 of file PHG4MapsDetector.h.
References y_rot.
void PHG4MapsDetector::SetZRot (const G4double angle) inline
Definition at line 55 of file PHG4MapsDetector.h.
References z_rot.
void PHG4MapsDetector::SuperDetector (const std::string & name) inline
Definition at line 59 of file PHG4MapsDetector.h.
References PHG4Detector::name, and superdetector.
Referenced by PHG4MapsSubsystem::InitRunSubsystem(), and PHG4MapsSteppingAction::SetInterfacePointers().
const std::string PHG4MapsDetector::SuperDetector () const inline
Definition at line 60 of file PHG4MapsDetector.h.
References superdetector.
Member Data Documentation
int PHG4MapsDetector::absorberactive private
Definition at line 86 of file PHG4MapsDetector.h.
Referenced by SetAbsorberActive().
int PHG4MapsDetector::active private
Definition at line 85 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), IsActive(), and SetActive().
int PHG4MapsDetector::blackhole private
Definition at line 88 of file PHG4MapsDetector.h.
Referenced by BlackHole(), and IsBlackHole().
std::string PHG4MapsDetector::detector_type private
Definition at line 102 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), and Detector().
G4double PHG4MapsDetector::envelope_inner_radius private
Definition at line 75 of file PHG4MapsDetector.h.
G4double PHG4MapsDetector::envelope_outer_radius private
Definition at line 76 of file PHG4MapsDetector.h.
G4double PHG4MapsDetector::envelope_z private
Definition at line 77 of file PHG4MapsDetector.h.
int PHG4MapsDetector::layer private
Definition at line 87 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), Construct(), ConstructMaps(), get_Layer(), and PHG4MapsDetector().
G4double PHG4MapsDetector::layer_nominal_radius private
Definition at line 92 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), Construct(), ConstructMaps(), and set_nominal_layer_radius().
std::string PHG4MapsDetector::layer_string private
Definition at line 102 of file PHG4MapsDetector.h.
Referenced by IsInMaps(), and PHG4MapsDetector().
int PHG4MapsDetector::N_staves private
Definition at line 93 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), and ConstructMaps().
G4double PHG4MapsDetector::phistep private
Definition at line 94 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), and ConstructMaps().
G4double PHG4MapsDetector::phitilt private
Definition at line 95 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), and ConstructMaps().
double PHG4MapsDetector::pixel_thickness private
Definition at line 98 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), and set_pixel_thickness().
double PHG4MapsDetector::pixel_x private
Definition at line 96 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), and set_pixel_x().
double PHG4MapsDetector::pixel_z private
Definition at line 97 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), and set_pixel_z().
G4double PHG4MapsDetector::place_in_x private
Definition at line 79 of file PHG4MapsDetector.h.
Referenced by SetPlace().
G4double PHG4MapsDetector::place_in_y private
Definition at line 80 of file PHG4MapsDetector.h.
Referenced by SetPlace().
G4double PHG4MapsDetector::place_in_z private
Definition at line 81 of file PHG4MapsDetector.h.
Referenced by SetPlace(), and SetPlaceZ().
std::string PHG4MapsDetector::stave_geometry_file private
Definition at line 105 of file PHG4MapsDetector.h.
Referenced by ConstructMaps().
int PHG4MapsDetector::stave_type private
Definition at line 91 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), Construct(), ConstructMaps(), PHG4MapsDetector(), and set_stave_type().
std::string PHG4MapsDetector::superdetector private
Definition at line 104 of file PHG4MapsDetector.h.
Referenced by AddGeometryNode(), and SuperDetector().
G4double PHG4MapsDetector::x_rot private
Definition at line 82 of file PHG4MapsDetector.h.
Referenced by SetXRot().
G4double PHG4MapsDetector::y_rot private
Definition at line 83 of file PHG4MapsDetector.h.
Referenced by SetYRot().
G4double PHG4MapsDetector::z_rot private
Definition at line 84 of file PHG4MapsDetector.h.
Referenced by SetZRot().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4MapsDetector.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4MapsDetector.cc