Class Reference for E1039 Core & Analysis Software: UtilHist Namespace Reference
UtilHist Namespace Reference
Functions
void FindFilledRange (TH1 *h1, int &bin_lo, int &bin_hi)
Find the lowest and highest bins ("bin_lo" and "bin_hi") out of non-empty bins of "h1".
void AutoSetRange (TH1 *h1, const int margin_lo=5, const int margin_hi=5)
Adjust the axis range via "h1->GetXaxis()->SetRange(bin_lo, bin_hi)" to zoom up non-empty bins.
void AutoSetRangeX (TH2 *h2, const int margin_lo=5, const int margin_hi=5)
void AutoSetRangeY (TH2 *h2, const int margin_lo=5, const int margin_hi=5)
Function Documentation
void UtilHist::AutoSetRange (TH1 * h1, const int margin_lo = 5, const int margin_hi = 5)
Adjust the axis range via "h1->GetXaxis()->SetRange(bin_lo, bin_hi)" to zoom up non-empty bins.
Definition at line 17 of file UtilHist.cc.
References FindFilledRange().
Referenced by CalibData::DrawHistHit(), OnlMonCham::DrawMonitor(), OnlMonProp::DrawMonitor(), OnlMonHodo::DrawMonitor(), OnlMonH4::DrawMonitor(), and OnlMonMainDaq::DrawMonitor().
void UtilHist::AutoSetRangeX (TH2 * h2, const int margin_lo = 5, const int margin_hi = 5)
Definition at line 29 of file UtilHist.cc.
References FindFilledRange().
Referenced by OnlMonTrigSig::DrawMonitor(), and OnlMonH4::DrawMonitor().
void UtilHist::AutoSetRangeY (TH2 * h2, const int margin_lo = 5, const int margin_hi = 5)
Definition at line 43 of file UtilHist.cc.
References FindFilledRange().
Referenced by OnlMonH4::DrawMonitor(), and OnlMonHodo::DrawMonitor().
void UtilHist::FindFilledRange (TH1 * h1, int & bin_lo, int & bin_hi)
Find the lowest and highest bins ("bin_lo" and "bin_hi") out of non-empty bins of "h1".
Definition at line 7 of file UtilHist.cc.
Referenced by AutoSetRange(), AutoSetRangeX(), AutoSetRangeY(), and OnlMonMainDaq::DrawMonitor().