E1039 Software: PHG4SquareTubeDetector Class Reference
PHG4SquareTubeDetector Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4SquareTubeDetector.h>
Public Member Functions
PHG4SquareTubeDetector (PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam="BLOCK", const int lyr=0)
constructor
virtual ~PHG4SquareTubeDetector (void)
destructor
virtual void Construct (G4LogicalVolume *world)
construct
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
volume accessors
bool IsInBlock (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Private Attributes
PHParameters * params
G4VPhysicalVolume * block_physi
int layer
std::string superdetector
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 10 of file PHG4SquareTubeDetector.h.
Constructor & Destructor Documentation
PHG4SquareTubeDetector()
PHG4SquareTubeDetector::PHG4SquareTubeDetector (PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam = "BLOCK", const int lyr = 0)
constructor
Definition at line 28 of file PHG4SquareTubeDetector.cc.
~PHG4SquareTubeDetector()
virtual PHG4SquareTubeDetector::~PHG4SquareTubeDetector (void) inline virtual
destructor
Definition at line 19 of file PHG4SquareTubeDetector.h.
References Construct(), and IsInBlock().
Member Function Documentation
Construct()
void PHG4SquareTubeDetector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 161 of file PHG4SquareTubeDetector.cc.
References block_physi, PHParameters::get_double_param(), PHParameters::get_string_param(), PHG4Detector::GetName(), PHG4Detector::overlapcheck, and params.
Referenced by ~PHG4SquareTubeDetector().
get_Layer()
int PHG4SquareTubeDetector::get_Layer () const inline
Definition at line 32 of file PHG4SquareTubeDetector.h.
References layer.
Referenced by PHG4SquareTubeSteppingAction::UserSteppingAction().
IsInBlock()
bool PHG4SquareTubeDetector::IsInBlock (G4VPhysicalVolume * volume) const
Definition at line 36 of file PHG4SquareTubeDetector.cc.
References block_physi, PHG4Detector::name, PHG4Detector::overlapcheck, and PHG4Utils::SetColour().
Referenced by PHG4SquareTubeSteppingAction::UserSteppingAction(), and ~PHG4SquareTubeDetector().
SuperDetector() [1/2]
void PHG4SquareTubeDetector::SuperDetector (const std::string & name) inline
Definition at line 30 of file PHG4SquareTubeDetector.h.
References PHG4Detector::name, and superdetector.
Referenced by PHG4SquareTubeSubsystem::InitRunSubsystem(), and PHG4SquareTubeSteppingAction::SetInterfacePointers().
SuperDetector() [2/2]
const std::string PHG4SquareTubeDetector::SuperDetector () const inline
Definition at line 31 of file PHG4SquareTubeDetector.h.
References superdetector.
Member Data Documentation
block_physi
G4VPhysicalVolume* PHG4SquareTubeDetector::block_physi private
Definition at line 38 of file PHG4SquareTubeDetector.h.
Referenced by Construct(), and IsInBlock().
layer
int PHG4SquareTubeDetector::layer private
Definition at line 41 of file PHG4SquareTubeDetector.h.
Referenced by get_Layer().
params
PHParameters* PHG4SquareTubeDetector::params private
Definition at line 36 of file PHG4SquareTubeDetector.h.
Referenced by Construct().
superdetector
std::string PHG4SquareTubeDetector::superdetector private
Definition at line 42 of file PHG4SquareTubeDetector.h.
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4SquareTubeDetector.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4SquareTubeDetector.cc