Class Reference for E1039 Core & Analysis Software: PHG4Showerv1 Class Reference
PHG4Showerv1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Showerv1.h>
Public Member Functions
PHG4Showerv1 ()
virtual ~PHG4Showerv1 ()
void identify (std::ostream &os=std::cout) const
PHG4Shower * Clone () const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
int get_id () const
void set_id (int id)
int get_parent_particle_id () const
void set_parent_particle_id (int parent_particle_id)
int get_parent_shower_id () const
void set_parent_shower_id (int parent_shower_id)
float get_x () const
void set_x (float x)
float get_y () const
void set_y (float y)
float get_z () const
void set_z (float z)
float get_position (unsigned int coor) const
void set_position (unsigned int coor, float xi)
float get_covar (unsigned int i, unsigned int j) const
void set_covar (unsigned int i, unsigned int j, float entry)
unsigned int get_nhits (int volume) const
void set_nhits (int volume, unsigned int nhits)
float get_edep (int volume) const
void set_edep (int volume, float edep)
float get_eion (int volume) const
void set_eion (int volume, float eion)
float get_light_yield (int volume) const
void set_light_yield (int volume, float light_yield)
float get_eh_ratio (int volume) const
void set_eh_ratio (int volume, float eh_ratio)
bool empty_g4particle_id () const
size_t size_g4particle_id () const
void add_g4particle_id (int id)
PHG4Shower::ParticleIdIter begin_g4particle_id ()
PHG4Shower::ParticleIdConstIter begin_g4particle_id () const
PHG4Shower::ParticleIdIter end_g4particle_id ()
PHG4Shower::ParticleIdConstIter end_g4particle_id () const
size_t remove_g4particle_id (int id)
void clear_g4particle_id ()
bool empty_g4vertex_id () const
size_t size_g4vertex_id () const
void add_g4vertex_id (int id)
PHG4Shower::VertexIdIter begin_g4vertex_id ()
PHG4Shower::VertexIdConstIter begin_g4vertex_id () const
PHG4Shower::VertexIdIter end_g4vertex_id ()
PHG4Shower::VertexIdConstIter end_g4vertex_id () const
size_t remove_g4vertex_id (int id)
void clear_g4vertex_id ()
bool empty_g4hit_id () const
size_t size_g4hit_id () const
void add_g4hit_id (int volume, PHG4HitDefs::keytype id)
PHG4Shower::HitIdIter begin_g4hit_id ()
PHG4Shower::HitIdConstIter begin_g4hit_id () const
PHG4Shower::HitIdIter find_g4hit_id (int volume)
PHG4Shower::HitIdConstIter find_g4hit_id (int volume) const
PHG4Shower::HitIdIter end_g4hit_id ()
PHG4Shower::HitIdConstIter end_g4hit_id () const
size_t remove_g4hit_id (int volume, int id)
size_t remove_g4hit_volume (int volume)
void clear_g4hit_id ()
Public Member Functions inherited from PHG4Shower
virtual ~PHG4Shower ()
virtual size_t remove_g4hit_id (int volume, PHG4HitDefs::keytype id)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from PHG4Shower
typedef std::set< int > ParticleIdSet
typedef ParticleIdSet::iterator ParticleIdIter
typedef ParticleIdSet::const_iterator ParticleIdConstIter
typedef std::set< int > VertexIdSet
typedef VertexIdSet::iterator VertexIdIter
typedef VertexIdSet::const_iterator VertexIdConstIter
typedef std::map< int, std::set< PHG4HitDefs::keytype > > HitIdMap
typedef HitIdMap::iterator HitIdIter
typedef HitIdMap::const_iterator HitIdConstIter
Protected Member Functions inherited from PHG4Shower
PHG4Shower ()
Detailed Description
Definition at line 13 of file PHG4Showerv1.h.
Constructor & Destructor Documentation
PHG4Showerv1()
PHG4Showerv1::PHG4Showerv1 ()
Definition at line 12 of file PHG4Showerv1.cc.
References set_covar().
Referenced by Clone(), and Reset().
~PHG4Showerv1()
virtual PHG4Showerv1::~PHG4Showerv1 () inline virtual
Definition at line 18 of file PHG4Showerv1.h.
Member Function Documentation
add_g4hit_id()
void PHG4Showerv1::add_g4hit_id (int volume, PHG4HitDefs::keytype id) inline virtual
Reimplemented from PHG4Shower.
Definition at line 91 of file PHG4Showerv1.h.
add_g4particle_id()
void PHG4Showerv1::add_g4particle_id (int id) inline virtual
Reimplemented from PHG4Shower.
Definition at line 71 of file PHG4Showerv1.h.
add_g4vertex_id()
void PHG4Showerv1::add_g4vertex_id (int id) inline virtual
Reimplemented from PHG4Shower.
Definition at line 81 of file PHG4Showerv1.h.
begin_g4hit_id() [1/2]
PHG4Shower::HitIdIter PHG4Showerv1::begin_g4hit_id () inline virtual
Reimplemented from PHG4Shower.
Definition at line 92 of file PHG4Showerv1.h.
begin_g4hit_id() [2/2]
PHG4Shower::HitIdConstIter PHG4Showerv1::begin_g4hit_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 93 of file PHG4Showerv1.h.
begin_g4particle_id() [1/2]
PHG4Shower::ParticleIdIter PHG4Showerv1::begin_g4particle_id () inline virtual
Reimplemented from PHG4Shower.
Definition at line 72 of file PHG4Showerv1.h.
begin_g4particle_id() [2/2]
PHG4Shower::ParticleIdConstIter PHG4Showerv1::begin_g4particle_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 73 of file PHG4Showerv1.h.
begin_g4vertex_id() [1/2]
PHG4Shower::VertexIdIter PHG4Showerv1::begin_g4vertex_id () inline virtual
Reimplemented from PHG4Shower.
Definition at line 82 of file PHG4Showerv1.h.
begin_g4vertex_id() [2/2]
PHG4Shower::VertexIdConstIter PHG4Showerv1::begin_g4vertex_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 83 of file PHG4Showerv1.h.
clear_g4hit_id()
void PHG4Showerv1::clear_g4hit_id () inline virtual
Reimplemented from PHG4Shower.
Definition at line 100 of file PHG4Showerv1.h.
clear_g4particle_id()
void PHG4Showerv1::clear_g4particle_id () inline virtual
Reimplemented from PHG4Shower.
Definition at line 77 of file PHG4Showerv1.h.
clear_g4vertex_id()
void PHG4Showerv1::clear_g4vertex_id () inline virtual
Reimplemented from PHG4Shower.
Definition at line 87 of file PHG4Showerv1.h.
Clone()
PHG4Shower* PHG4Showerv1::Clone () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 23 of file PHG4Showerv1.h.
References PHG4Showerv1().
empty_g4hit_id()
bool PHG4Showerv1::empty_g4hit_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 89 of file PHG4Showerv1.h.
empty_g4particle_id()
bool PHG4Showerv1::empty_g4particle_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 69 of file PHG4Showerv1.h.
empty_g4vertex_id()
bool PHG4Showerv1::empty_g4vertex_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 79 of file PHG4Showerv1.h.
end_g4hit_id() [1/2]
PHG4Shower::HitIdIter PHG4Showerv1::end_g4hit_id () inline virtual
Reimplemented from PHG4Shower.
Definition at line 96 of file PHG4Showerv1.h.
end_g4hit_id() [2/2]
PHG4Shower::HitIdConstIter PHG4Showerv1::end_g4hit_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 97 of file PHG4Showerv1.h.
end_g4particle_id() [1/2]
PHG4Shower::ParticleIdIter PHG4Showerv1::end_g4particle_id () inline virtual
Reimplemented from PHG4Shower.
Definition at line 74 of file PHG4Showerv1.h.
end_g4particle_id() [2/2]
PHG4Shower::ParticleIdConstIter PHG4Showerv1::end_g4particle_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 75 of file PHG4Showerv1.h.
end_g4vertex_id() [1/2]
PHG4Shower::VertexIdIter PHG4Showerv1::end_g4vertex_id () inline virtual
Reimplemented from PHG4Shower.
Definition at line 84 of file PHG4Showerv1.h.
end_g4vertex_id() [2/2]
PHG4Shower::VertexIdConstIter PHG4Showerv1::end_g4vertex_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 85 of file PHG4Showerv1.h.
find_g4hit_id() [1/2]
PHG4Shower::HitIdIter PHG4Showerv1::find_g4hit_id (int volume) inline virtual
Reimplemented from PHG4Shower.
Definition at line 94 of file PHG4Showerv1.h.
find_g4hit_id() [2/2]
PHG4Shower::HitIdConstIter PHG4Showerv1::find_g4hit_id (int volume) const inline virtual
Reimplemented from PHG4Shower.
Definition at line 95 of file PHG4Showerv1.h.
get_covar()
float PHG4Showerv1::get_covar (unsigned int i, unsigned int j) const virtual
Reimplemented from PHG4Shower.
Definition at line 108 of file PHG4Showerv1.cc.
Referenced by identify(), and isValid().
get_edep()
float PHG4Showerv1::get_edep (int volume) const virtual
Reimplemented from PHG4Shower.
Definition at line 126 of file PHG4Showerv1.cc.
Referenced by identify().
get_eh_ratio()
float PHG4Showerv1::get_eh_ratio (int volume) const virtual
Reimplemented from PHG4Shower.
Definition at line 150 of file PHG4Showerv1.cc.
get_eion()
float PHG4Showerv1::get_eion (int volume) const virtual
Reimplemented from PHG4Shower.
Definition at line 134 of file PHG4Showerv1.cc.
Referenced by identify().
get_id()
int PHG4Showerv1::get_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 29 of file PHG4Showerv1.h.
Referenced by identify().
get_light_yield()
float PHG4Showerv1::get_light_yield (int volume) const virtual
Reimplemented from PHG4Shower.
Definition at line 142 of file PHG4Showerv1.cc.
Referenced by identify().
get_nhits()
unsigned int PHG4Showerv1::get_nhits (int volume) const virtual
Reimplemented from PHG4Shower.
Definition at line 118 of file PHG4Showerv1.cc.
get_parent_particle_id()
int PHG4Showerv1::get_parent_particle_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 32 of file PHG4Showerv1.h.
Referenced by identify().
get_parent_shower_id()
int PHG4Showerv1::get_parent_shower_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 35 of file PHG4Showerv1.h.
Referenced by identify().
get_position()
float PHG4Showerv1::get_position (unsigned int coor) const inline virtual
Reimplemented from PHG4Shower.
Definition at line 47 of file PHG4Showerv1.h.
get_x()
float PHG4Showerv1::get_x () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 38 of file PHG4Showerv1.h.
Referenced by identify().
get_y()
float PHG4Showerv1::get_y () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 41 of file PHG4Showerv1.h.
Referenced by identify().
get_z()
float PHG4Showerv1::get_z () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 44 of file PHG4Showerv1.h.
Referenced by identify().
identify()
void PHG4Showerv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4Shower.
Definition at line 33 of file PHG4Showerv1.cc.
References get_covar(), get_edep(), get_eion(), get_id(), get_light_yield(), get_parent_particle_id(), get_parent_shower_id(), get_x(), get_y(), and get_z().
isValid()
int PHG4Showerv1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHG4Shower.
Definition at line 87 of file PHG4Showerv1.cc.
References get_covar().
remove_g4hit_id()
size_t PHG4Showerv1::remove_g4hit_id (int volume, int id) inline
Definition at line 98 of file PHG4Showerv1.h.
remove_g4hit_volume()
size_t PHG4Showerv1::remove_g4hit_volume (int volume) inline virtual
Reimplemented from PHG4Shower.
Definition at line 99 of file PHG4Showerv1.h.
remove_g4particle_id()
size_t PHG4Showerv1::remove_g4particle_id (int id) inline virtual
Reimplemented from PHG4Shower.
Definition at line 76 of file PHG4Showerv1.h.
remove_g4vertex_id()
size_t PHG4Showerv1::remove_g4vertex_id (int id) inline virtual
Reimplemented from PHG4Shower.
Definition at line 86 of file PHG4Showerv1.h.
Reset()
void PHG4Showerv1::Reset () inline virtual
Clear Event.
Reimplemented from PHG4Shower.
Definition at line 24 of file PHG4Showerv1.h.
References PHG4Showerv1().
set_covar()
void PHG4Showerv1::set_covar (unsigned int i, unsigned int j, float entry) virtual
Reimplemented from PHG4Shower.
Definition at line 103 of file PHG4Showerv1.cc.
Referenced by PHG4Showerv1().
set_edep()
void PHG4Showerv1::set_edep (int volume, float edep) inline virtual
Reimplemented from PHG4Shower.
Definition at line 57 of file PHG4Showerv1.h.
set_eh_ratio()
void PHG4Showerv1::set_eh_ratio (int volume, float eh_ratio) inline virtual
Reimplemented from PHG4Shower.
Definition at line 66 of file PHG4Showerv1.h.
set_eion()
void PHG4Showerv1::set_eion (int volume, float eion) inline virtual
Reimplemented from PHG4Shower.
Definition at line 60 of file PHG4Showerv1.h.
set_id()
void PHG4Showerv1::set_id (int id) inline virtual
Reimplemented from PHG4Shower.
Definition at line 30 of file PHG4Showerv1.h.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
set_light_yield()
void PHG4Showerv1::set_light_yield (int volume, float light_yield) inline virtual
Reimplemented from PHG4Shower.
Definition at line 63 of file PHG4Showerv1.h.
set_nhits()
void PHG4Showerv1::set_nhits (int volume, unsigned int nhits) inline virtual
Reimplemented from PHG4Shower.
Definition at line 54 of file PHG4Showerv1.h.
set_parent_particle_id()
void PHG4Showerv1::set_parent_particle_id (int parent_particle_id) inline virtual
Reimplemented from PHG4Shower.
Definition at line 33 of file PHG4Showerv1.h.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
set_parent_shower_id()
void PHG4Showerv1::set_parent_shower_id (int parent_shower_id) inline virtual
Reimplemented from PHG4Shower.
Definition at line 36 of file PHG4Showerv1.h.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
set_position()
void PHG4Showerv1::set_position (unsigned int coor, float xi) inline virtual
Reimplemented from PHG4Shower.
Definition at line 48 of file PHG4Showerv1.h.
set_x()
void PHG4Showerv1::set_x (float x) inline virtual
Reimplemented from PHG4Shower.
Definition at line 39 of file PHG4Showerv1.h.
set_y()
void PHG4Showerv1::set_y (float y) inline virtual
Reimplemented from PHG4Shower.
Definition at line 42 of file PHG4Showerv1.h.
set_z()
void PHG4Showerv1::set_z (float z) inline virtual
Reimplemented from PHG4Shower.
Definition at line 45 of file PHG4Showerv1.h.
size_g4hit_id()
size_t PHG4Showerv1::size_g4hit_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 90 of file PHG4Showerv1.h.
size_g4particle_id()
size_t PHG4Showerv1::size_g4particle_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 70 of file PHG4Showerv1.h.
size_g4vertex_id()
size_t PHG4Showerv1::size_g4vertex_id () const inline virtual
Reimplemented from PHG4Shower.
Definition at line 80 of file PHG4Showerv1.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Showerv1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Showerv1.cc