E1039 Software: half Class Reference
half Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/Half/half.h>
Classes
union uif
Public Member Functions
half ()
half (float f)
operator float () const
half operator- () const
half & operator= (half h)
half & operator= (float f)
half & operator+= (half h)
half & operator+= (float f)
half & operator-= (half h)
half & operator-= (float f)
half & operator*= (half h)
half & operator*= (float f)
half & operator/= (half h)
half & operator/= (float f)
half round (unsigned int n) const
bool isFinite () const
bool isNormalized () const
bool isDenormalized () const
bool isZero () const
bool isNan () const
bool isInfinity () const
bool isNegative () const
unsigned short bits () const
void setBits (unsigned short bits)
Static Public Member Functions
static half posInf ()
static half negInf ()
static half qNan ()
static half sNan ()
Static Private Member Functions
static short convert (int i)
static float overflow ()
Private Attributes
unsigned short _h
Static Private Attributes
static HALF_EXPORT_CONST uif _toFloat [1<< 16]
static HALF_EXPORT_CONST unsigned short _eLut [1<< 9]
Detailed Description
Definition at line 102 of file half.h.
Constructor & Destructor Documentation
half() [1/2]
half::half () inline
Definition at line 427 of file half.h.
half() [2/2]
half::half (float f) inline
Definition at line 438 of file half.h.
References half::uif::f, and half::uif::i.
Member Function Documentation
bits()
unsigned short half::bits () const inline
Definition at line 754 of file half.h.
Referenced by HepMCCompress::FloatToInt(), VariableArrayUtils::FloatToShortBits(), and halfFunction< T >::operator()().
convert()
static short half::convert (int i) static private
isDenormalized()
bool half::isDenormalized () const inline
Definition at line 677 of file half.h.
isFinite()
bool half::isFinite () const inline
Definition at line 661 of file half.h.
isInfinity()
bool half::isInfinity () const inline
Definition at line 702 of file half.h.
Referenced by halfFunction< T >::halfFunction().
isNan()
bool half::isNan () const inline
Definition at line 693 of file half.h.
Referenced by halfFunction< T >::halfFunction().
isNegative()
bool half::isNegative () const inline
Definition at line 711 of file half.h.
Referenced by halfFunction< T >::halfFunction().
isNormalized()
bool half::isNormalized () const inline
Definition at line 669 of file half.h.
isZero()
bool half::isZero () const inline
Definition at line 686 of file half.h.
negInf()
half half::negInf () inline static
Definition at line 727 of file half.h.
References _h.
operator float()
half::operator float () const inline
Definition at line 502 of file half.h.
operator*=() [1/2]
half & half::operator*= (half h) inline
Definition at line 629 of file half.h.
operator*=() [2/2]
half & half::operator*= (float f) inline
Definition at line 637 of file half.h.
operator+=() [1/2]
half & half::operator+= (half h) inline
Definition at line 597 of file half.h.
operator+=() [2/2]
half & half::operator+= (float f) inline
Definition at line 605 of file half.h.
operator-()
half half::operator- () const inline
Definition at line 572 of file half.h.
References _h.
operator-=() [1/2]
half & half::operator-= (half h) inline
Definition at line 613 of file half.h.
operator-=() [2/2]
half & half::operator-= (float f) inline
Definition at line 621 of file half.h.
operator/=() [1/2]
half & half::operator/= (half h) inline
Definition at line 645 of file half.h.
operator/=() [2/2]
half & half::operator/= (float f) inline
Definition at line 653 of file half.h.
operator=() [1/2]
half & half::operator= (half h) inline
Definition at line 581 of file half.h.
References _h.
operator=() [2/2]
half & half::operator= (float f) inline
Definition at line 589 of file half.h.
overflow()
static float half::overflow () static private
posInf()
half half::posInf () inline static
Definition at line 718 of file half.h.
References _h.
Referenced by std::numeric_limits< half >::infinity().
qNan()
half half::qNan () inline static
Definition at line 736 of file half.h.
References _h.
Referenced by std::numeric_limits< half >::quiet_NaN().
round()
half half::round (unsigned int n) const inline
Definition at line 513 of file half.h.
References _h.
setBits()
void half::setBits (unsigned short bits) inline
Definition at line 761 of file half.h.
Referenced by halfFunction< T >::halfFunction(), and VariableArrayUtils::ShortBitsToFloat().
sNan()
half half::sNan () inline static
Definition at line 745 of file half.h.
References _h.
Referenced by std::numeric_limits< half >::signaling_NaN().
Member Data Documentation
_eLut
HALF_EXPORT_CONST unsigned short half::_eLut[1<< 9] static private
Definition at line 231 of file half.h.
_h
unsigned short half::_h private
Definition at line 228 of file half.h.
Referenced by negInf(), operator-(), operator=(), posInf(), qNan(), round(), and sNan().
_toFloat
HALF_EXPORT_CONST uif half::_toFloat[1<< 16] static private
Definition at line 230 of file half.h.
The documentation for this class was generated from the following file:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/Half/half.h