var namespaces =
[
    [ "boost", "d4/da9/namespaceboost.html", "d4/da9/namespaceboost" ],
    [ "DPGEN", "d2/da1/namespaceDPGEN.html", null ],
    [ "findNode", "da/dc3/namespacefindNode.html", null ],
    [ "Fun4AllReturnCodes", "d1/d38/namespaceFun4AllReturnCodes.html", null ],
    [ "Fun4AllUtils", "dd/d3e/namespaceFun4AllUtils.html", null ],
    [ "HepMC", "d1/d98/namespaceHepMC.html", null ],
    [ "PHG4CellDefs", "d7/dba/namespacePHG4CellDefs.html", "d7/dba/namespacePHG4CellDefs" ],
    [ "PHG4CylinderCellDefs", "d2/da3/namespacePHG4CylinderCellDefs.html", null ],
    [ "PHG4HitDefs", "da/dd0/namespacePHG4HitDefs.html", null ],
    [ "PHG4StepStatusDecode", "d2/df6/namespacePHG4StepStatusDecode.html", null ],
    [ "PHG4TPCColorDefs", "d2/de8/namespacePHG4TPCColorDefs.html", null ],
    [ "PHG4TrackStatusDecode", "db/ded/namespacePHG4TrackStatusDecode.html", null ],
    [ "PHG4TrackUserInfo", "d2/d7f/namespacePHG4TrackUserInfo.html", null ],
    [ "phooldefs", "d3/d8a/namespacephooldefs.html", null ],
    [ "Pythia8", "d3/dee/namespacePythia8.html", null ],
    [ "SQGenFit", "d7/d95/namespaceSQGenFit.html", null ],
    [ "submit_bnl", "d1/d2b/namespacesubmit__bnl.html", null ],
    [ "submit_e1039", "d9/d8d/namespacesubmit__e1039.html", null ],
    [ "syncdefs", "d2/de5/namespacesyncdefs.html", null ],
    [ "UtilAsym", "dd/d97/namespaceUtilAsym.html", null ],
    [ "UtilBeam", "de/dba/namespaceUtilBeam.html", null ],
    [ "UtilDimuon", "d4/dcc/namespaceUtilDimuon.html", null ],
    [ "UtilHist", "d3/daf/namespaceUtilHist.html", null ],
    [ "UtilHodo", "d9/d7c/namespaceUtilHodo.html", null ],
    [ "UtilRoad", "de/dad/namespaceUtilRoad.html", null ],
    [ "UtilSQHit", "d0/dc5/namespaceUtilSQHit.html", null ],
    [ "UtilSRawEvent", "d6/d43/namespaceUtilSRawEvent.html", null ],
    [ "UtilTrack", "d2/d1e/namespaceUtilTrack.html", null ],
    [ "UtilTrigger", "df/d60/namespaceUtilTrigger.html", null ],
    [ "varids", "d1/db0/namespacevarids.html", null ]
];