Class Reference for E1039 Core & Analysis Software: UtilTrigger::TrigRoadset Class Reference
UtilTrigger::TrigRoadset Class Reference
Class to handle the trigger roadset.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/TrigRoadset.h>
Public Member Functions
TrigRoadset ()
virtual ~TrigRoadset ()
int RoadsetID () const
int LBTop () const
int LBBot () const
TrigRoads * PosTop ()
TrigRoads * PosBot ()
TrigRoads * NegTop ()
TrigRoads * NegBot ()
const TrigRoads * PosTop () const
const TrigRoads * PosBot () const
const TrigRoads * NegTop () const
const TrigRoads * NegBot () const
int LoadConfig (const std::string dir)
int LoadConfig (const int roadset_id)
int LoadConfig (const int firmware_LBTop, const int firmware_LBBot)
std::string str (const int level=0) const
Detailed Description
Class to handle the trigger roadset.
Typical usage:
#include <UtilAna/TrigRoadset.h>
UtilTrigger::TrigRoadset m_rs;
SQRun* sq_run = findNode::getClass<SQRun>(topNode, "SQRun");
if (!sq_run) return Fun4AllReturnCodes::ABORTEVENT;
int LBtop = sq_run->get_v1495_id(2);
int LBbot = sq_run->get_v1495_id(3);
int ret = m_rs.LoadConfig(LBtop, LBbot);
if (ret != 0) cout << "LoadConfig() returned " << ret << ".\n";
else          cout << "Roadset " << m_rs.str(1) << endl;
int road_pos = trk_pos.getTriggerRoad();
int road_neg = trk_neg.getTriggerRoad();
bool pos_top = m_rs.PosTop()->FindRoad(road_pos);
bool pos_bot = m_rs.PosBot()->FindRoad(road_pos);
bool neg_top = m_rs.NegTop()->FindRoad(road_neg);
bool neg_bot = m_rs.NegBot()->FindRoad(road_neg);
cout << "Roads: " << road_pos << " " << road_neg << " "
     << pos_top << pos_bot << neg_top << neg_bot << endl;
Definition at line 34 of file TrigRoadset.h.
Constructor & Destructor Documentation
TrigRoadset()
UtilTrigger::TrigRoadset::TrigRoadset ()
Definition at line 10 of file TrigRoadset.cc.
~TrigRoadset()
virtual UtilTrigger::TrigRoadset::~TrigRoadset () inline virtual
Definition at line 46 of file TrigRoadset.h.
Member Function Documentation
LBBot()
int UtilTrigger::TrigRoadset::LBBot () const inline
Definition at line 50 of file TrigRoadset.h.
LBTop()
int UtilTrigger::TrigRoadset::LBTop () const inline
Definition at line 49 of file TrigRoadset.h.
LoadConfig() [1/3]
int UtilTrigger::TrigRoadset::LoadConfig (const int firmware_LBTop, const int firmware_LBBot)
Definition at line 43 of file TrigRoadset.cc.
References LoadConfig().
LoadConfig() [2/3]
int UtilTrigger::TrigRoadset::LoadConfig (const int roadset_id)
Definition at line 33 of file TrigRoadset.cc.
References LoadConfig().
LoadConfig() [3/3]
int UtilTrigger::TrigRoadset::LoadConfig (const std::string dir)
Definition at line 23 of file TrigRoadset.cc.
References UtilTrigger::TrigRoads::LoadConfig().
Referenced by AnaDimuon::InitRun(), AnaDimuonLikeSign::InitRun(), AnaDimuonV2::InitRun(), and LoadConfig().
NegBot() [1/2]
TrigRoads* UtilTrigger::TrigRoadset::NegBot () inline
Definition at line 55 of file TrigRoadset.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
NegBot() [2/2]
const TrigRoads* UtilTrigger::TrigRoadset::NegBot () const inline
Definition at line 59 of file TrigRoadset.h.
NegTop() [1/2]
TrigRoads* UtilTrigger::TrigRoadset::NegTop () inline
Definition at line 54 of file TrigRoadset.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
NegTop() [2/2]
const TrigRoads* UtilTrigger::TrigRoadset::NegTop () const inline
Definition at line 58 of file TrigRoadset.h.
PosBot() [1/2]
TrigRoads* UtilTrigger::TrigRoadset::PosBot () inline
Definition at line 53 of file TrigRoadset.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
PosBot() [2/2]
const TrigRoads* UtilTrigger::TrigRoadset::PosBot () const inline
Definition at line 57 of file TrigRoadset.h.
PosTop() [1/2]
TrigRoads* UtilTrigger::TrigRoadset::PosTop () inline
Definition at line 52 of file TrigRoadset.h.
Referenced by AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), and AnaDimuonV2::process_event().
PosTop() [2/2]
const TrigRoads* UtilTrigger::TrigRoadset::PosTop () const inline
Definition at line 56 of file TrigRoadset.h.
RoadsetID()
int UtilTrigger::TrigRoadset::RoadsetID () const inline
Definition at line 48 of file TrigRoadset.h.
str()
std::string UtilTrigger::TrigRoadset::str (const int level = 0) const
Definition at line 79 of file TrigRoadset.cc.
References UtilTrigger::TrigRoads::str().
Referenced by AnaDimuon::InitRun(), AnaDimuonLikeSign::InitRun(), and AnaDimuonV2::InitRun().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/TrigRoadset.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/TrigRoadset.cc