Class Reference for E1039 Core & Analysis Software: AnaDimuon Class Reference
AnaDimuon Class Reference
An example class to analyze hodoscope hits in E1039 DST file.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/RecoData2024/src/AnaDimuon.h>
Public Member Functions
AnaDimuon (const std::string &name="AnaDimuon")
virtual ~AnaDimuon ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetOutputFileName (const std::string name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static void AnalyzeTree (TChain *tree)
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
An example class to analyze hodoscope hits in E1039 DST file.
Definition at line 14 of file AnaDimuon.h.
Constructor & Destructor Documentation
AnaDimuon()
AnaDimuon::AnaDimuon (const std::string & name = "AnaDimuon")
Definition at line 21 of file AnaDimuon.cc.
~AnaDimuon()
AnaDimuon::~AnaDimuon () virtual
Definition at line 33 of file AnaDimuon.cc.
Member Function Documentation
AnalyzeTree()
void AnaDimuon::AnalyzeTree (TChain * tree) static
Definition at line 140 of file AnaDimuon.cc.
References DimuonData::chisq_neg, DimuonData::chisq_pos, EventData::fpga_bits, DimuonData::mom, DimuonData::mom_neg, DimuonData::mom_pos, DimuonData::n_hits_neg, DimuonData::n_hits_pos, DimuonData::neg_bot, DimuonData::neg_top, DimuonData::pos, DimuonData::pos_bot, DimuonData::pos_neg, DimuonData::pos_pos, and DimuonData::pos_top.
End()
int AnaDimuon::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 132 of file AnaDimuon.cc.
References Fun4AllReturnCodes::EVENT_OK.
Init()
int AnaDimuon::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 38 of file AnaDimuon.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRun()
int AnaDimuon::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 43 of file AnaDimuon.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and SQRun::get_v1495_id().
process_event()
int AnaDimuon::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 68 of file AnaDimuon.cc.
References SQHitVector::begin(), DimuonData::chisq_neg, DimuonData::chisq_pos, EventData::D1, EventData::D2, EventData::D3m, EventData::D3p, SQHitVector::end(), EventData::event_id, Fun4AllReturnCodes::EVENT_OK, EventData::fpga_bits, SRecTrack::get_chisq(), SQHit::get_detector_id(), SQEvent::get_event_id(), SRecDimuon::get_mom(), SRecTrack::get_mom_vtx(), SRecTrack::get_num_hits(), SRecDimuon::get_pos(), SRecTrack::get_pos_vtx(), SQEvent::get_run_id(), SQEvent::get_spill_id(), SRecDimuon::get_track_id_neg(), SRecDimuon::get_track_id_pos(), SQEvent::get_trigger(), SRecEvent::getDimuon(), SRecEvent::getNDimuons(), SRecEvent::getTrack(), SRecTrack::getTriggerRoad(), SQEvent::MATRIX1, DimuonData::mom, DimuonData::mom_neg, DimuonData::mom_pos, DimuonData::n_hits_neg, DimuonData::n_hits_pos, DimuonData::neg_bot, DimuonData::neg_top, SQEvent::NIM1, EventData::nim_bits, DimuonData::pos, DimuonData::pos_bot, DimuonData::pos_neg, DimuonData::pos_pos, DimuonData::pos_top, DimuonData::road_neg, DimuonData::road_pos, EventData::run_id, and EventData::spill_id.
SetOutputFileName()
void AnaDimuon::SetOutputFileName (const std::string name) inline
Definition at line 34 of file AnaDimuon.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/RecoData2024/src/AnaDimuon.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/RecoData2024/src/AnaDimuon.cc