SeaQuest Offline Software: /home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/inc/SMillepede.h File Reference
SMillepede.h File Reference
#include "GlobalConsts.h"
#include <string>
#include <TFile.h>
#include <TTree.h>
#include <TH1D.h>
#include <TClonesArray.h>
#include "GeomSvc.h"
#include "SRecEvent.h"
#include "SMillepedeUtil.h"
#include "FastTracklet.h"
#include "KalmanFastTracking.h"
Classes
class SMillepede
Namespaces
MILLEPEDE
Parameters for alignment pocedure.
Functions
void initgl_ (int *, int *, int *, int *)
Interface for cross-compilation with fortran millepede program.
void parsig_ (int *, float *)
void initun_ (int *, float *)
void parglo_ (float *)
void constf_ (float *, float *)
void zerloc_ (float *, float *)
void equloc_ (float *, float *, float *, float *)
void fitloc_ ()
void fitglo_ (float *)
float errpar_ (int *)
Variables
static const int MILLEPEDE::NPLAN = nChamberPlanes
static const int MILLEPEDE::NPARTRK = 4
static const int MILLEPEDE::NPARPLAN = 3
static const int MILLEPEDE::NGLB = NPLAN*NPARPLAN
static const int MILLEPEDE::NSTDEV = 3
static const int MILLEPEDE::NHITSMIN = 15
static const double MILLEPEDE::CHISQMAX = 8.
static const double MILLEPEDE::PROBMIN = 0.9
static const double MILLEPEDE::MOMMIN = 25.
Function Documentation
void constf_ (float * , float *)
Referenced by SMillepede::constrainDetectors(), SMillepede::fixDetectorParameter(), and SMillepede::initMillepede().
void equloc_ (float * , float * , float * , float *)
Referenced by SMillepede::setSingleTrack().
float errpar_ (int *)
Referenced by SMillepede::fitAlignment().
void fitglo_ (float *)
Referenced by SMillepede::fitAlignment().
void fitloc_ ()
Referenced by SMillepede::setSingleTrack().
void initgl_ (int * , int * , int * , int *)
Interface for cross-compilation with fortran millepede program.
Referenced by SMillepede::initMillepede().
void initun_ (int * , float *)
Referenced by SMillepede::initMillepede().
void parglo_ (float *)
Referenced by SMillepede::initMillepede().
void parsig_ (int * , float *)
Referenced by SMillepede::initMillepede().
void zerloc_ (float * , float *)
Referenced by SMillepede::setSingleTrack().