Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/EvalJpsiAsymStat/macro_ana/DrawStatExp.C File Reference
DrawStatExp.C File Reference
Functions
void DrawOneParticle (const char *part)
void DrawOneVar (const char *part, const char *var, const double x_min, const double x_max)
void DrawStatExp ()
Variables
const double lumi_1w = 7e4
Macro to draw the anticipated precision of TSSA of J/psi and psi'.
const double df = 0.176
const double pol = 0.8
TFile * file
TCanvas * c1
Function Documentation
void DrawOneParticle (const char * part)
Definition at line 27 of file DrawStatExp.C.
References DrawOneVar(), and file.
Referenced by DrawStatExp().
void DrawOneVar (const char * part, const char * var, const double x_min, const double x_max)
Definition at line 39 of file DrawStatExp.C.
References c1, df, file, lumi_1w, and pol.
Referenced by DrawOneParticle().
void DrawStatExp ()
Definition at line 14 of file DrawStatExp.C.
References c1, df, DrawOneParticle(), lumi_1w, and pol.
Variable Documentation
TCanvas* c1
Definition at line 10 of file DrawStatExp.C.
const double df = 0.176
Definition at line 7 of file DrawStatExp.C.
Referenced by DrawOneVar(), and DrawStatExp().
TFile* file
Definition at line 9 of file DrawStatExp.C.
const double lumi_1w = 7e4
Macro to draw the anticipated precision of TSSA of J/psi and psi'.
One week of data taking is assumed. delta_{AN}^{1w} = 1 / (df * pol * sqrt(R * L^1w))
Definition at line 6 of file DrawStatExp.C.
Referenced by DrawOneVar(), and DrawStatExp().
const double pol = 0.8
Definition at line 8 of file DrawStatExp.C.
Referenced by DrawOneVar(), and DrawStatExp().