E1039 Software: Fun4AllSyncManager Class Reference
Fun4AllSyncManager Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/framework/fun4all/Fun4AllSyncManager.h>
Public Member Functions
Fun4AllSyncManager (const std::string &name="SYNCMANAGERNONAME")
virtual ~Fun4AllSyncManager ()
int registerInputManager (Fun4AllInputManager *InManager)
Fun4AllInputManager * getInputManager (const std::string &name)
int run (const int nevnts=0)
run n events (0 means up to end of file
int skip (const int nevnts=0)
skip n events (0 means up to the end of file). Skip means read, don't process.
int fileopen (const std::string &managername="NONE", const std::string &filename="NONE")
int fileclose (const std::string &managername="NONE")
int CurrentRun ()
void CurrentRun (const int ival)
void CurrentEvent (const int evt)
void Print (const std::string &what="ALL") const
void SegmentNumber (const int iseg)
int SegmentNumber () const
int BranchSelect (const std::string &managername, const std::string &branch, int iflag)
int BranchSelect (const std::string &branch, const int iflag)
int setBranches (const std::string &managername)
int setBranches ()
void TotalEvents (const int i)
int TotalEvents () const
void PrdfEvents (const int i)
int PrdfEvents () const
void GetInputFullFileList (std::vector< std::string > &fnames) const
void Repeat (const int i=-1)
void PushBackInputMgrsEvents (const int i)
int ResetEvent ()
const std::vector< Fun4AllInputManager * > GetInputManagers () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int CheckSync (unsigned i)
Private Attributes
int prdf_segment
int prdf_events
int events_total
int currentrun
int currentevent
int repeat
SyncObject * MasterSync
std::vector< Fun4AllInputManager * > InManager
std::vector< int > iretInManager
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 16 of file Fun4AllSyncManager.h.
Constructor & Destructor Documentation
Fun4AllSyncManager()
Fun4AllSyncManager::Fun4AllSyncManager (const std::string & name = "SYNCMANAGERNONAME")
Definition at line 22 of file Fun4AllSyncManager.cc.
~Fun4AllSyncManager()
Fun4AllSyncManager::~Fun4AllSyncManager () virtual
Definition at line 35 of file Fun4AllSyncManager.cc.
References InManager, MasterSync, and Fun4AllBase::verbosity.
Member Function Documentation
BranchSelect() [1/2]
int Fun4AllSyncManager::BranchSelect (const std::string & managername, const std::string & branch, int iflag)
Definition at line 291 of file Fun4AllSyncManager.cc.
References Fun4AllInputManager::BranchSelect(), InManager, and Fun4AllBase::Name().
Referenced by SegmentNumber().
BranchSelect() [2/2]
int Fun4AllSyncManager::BranchSelect (const std::string & branch, const int iflag)
Definition at line 306 of file Fun4AllSyncManager.cc.
References Fun4AllInputManager::BranchSelect(), and InManager.
CheckSync()
int Fun4AllSyncManager::CheckSync (unsigned i) private
Definition at line 379 of file Fun4AllSyncManager.cc.
References InManager, and MasterSync.
Referenced by GetInputManagers(), and run().
CurrentEvent()
void Fun4AllSyncManager::CurrentEvent (const int evt)
Definition at line 428 of file Fun4AllSyncManager.cc.
References currentevent, Fun4AllServer::EventNumber(), and Fun4AllServer::instance().
Referenced by CurrentRun(), Fun4AllEVIOInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllSRawEventInputManager::run(), Fun4AllHepMCPileupInputManager::run(), and Fun4AllHepMCInputManager::run().
CurrentRun() [1/2]
int Fun4AllSyncManager::CurrentRun () inline
Definition at line 35 of file Fun4AllSyncManager.h.
References currentrun.
Referenced by Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), and Fun4AllDummyInputManager::setSyncManager().
CurrentRun() [2/2]
void Fun4AllSyncManager::CurrentRun (const int ival) inline
Definition at line 36 of file Fun4AllSyncManager.h.
References CurrentEvent(), currentrun, and Print().
fileclose()
int Fun4AllSyncManager::fileclose (const std::string & managername = "NONE")
Definition at line 342 of file Fun4AllSyncManager.cc.
References Fun4AllInputManager::fileclose(), InManager, and Fun4AllBase::Name().
fileopen()
int Fun4AllSyncManager::fileopen (const std::string & managername = "NONE", const std::string & filename = "NONE")
Definition at line 276 of file Fun4AllSyncManager.cc.
References Fun4AllInputManager::fileopen(), InManager, and Fun4AllBase::Name().
GetInputFullFileList()
void Fun4AllSyncManager::GetInputFullFileList (std::vector< std::string > & fnames) const
Definition at line 387 of file Fun4AllSyncManager.cc.
References InManager.
Referenced by Fun4AllServer::GetInputFullFileList(), and PrdfEvents().
getInputManager()
Fun4AllInputManager * Fun4AllSyncManager::getInputManager (const std::string & name)
Definition at line 73 of file Fun4AllSyncManager.cc.
References InManager, Fun4AllBase::Name(), and NULL.
GetInputManagers()
const std::vector<Fun4AllInputManager *> Fun4AllSyncManager::GetInputManagers () const inline
Definition at line 53 of file Fun4AllSyncManager.h.
References CheckSync(), and InManager.
PrdfEvents() [1/2]
void Fun4AllSyncManager::PrdfEvents (const int i) inline
Definition at line 47 of file Fun4AllSyncManager.h.
References prdf_events.
Referenced by Fun4AllServer::PrdfEvents(), Fun4AllEVIOInputManager::run(), Fun4AllPrdfInputManager::run(), and Fun4AllSRawEventInputManager::run().
PrdfEvents() [2/2]
int Fun4AllSyncManager::PrdfEvents () const inline
Definition at line 48 of file Fun4AllSyncManager.h.
References GetInputFullFileList(), and prdf_events.
Print()
void Fun4AllSyncManager::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 361 of file Fun4AllSyncManager.cc.
References InManager, and Fun4AllBase::Name().
Referenced by CurrentRun(), Fun4AllServer::Print(), and skip().
PushBackInputMgrsEvents()
void Fun4AllSyncManager::PushBackInputMgrsEvents (const int i)
Definition at line 403 of file Fun4AllSyncManager.cc.
References InManager, and Fun4AllInputManager::PushBackEvents().
Referenced by Repeat().
registerInputManager()
int Fun4AllSyncManager::registerInputManager (Fun4AllInputManager * InManager)
Definition at line 51 of file Fun4AllSyncManager.cc.
References InManager, iretInManager, Fun4AllBase::Name(), Fun4AllInputManager::setSyncManager(), and Fun4AllBase::verbosity.
Referenced by Fun4AllServer::registerInputManager().
Repeat()
void Fun4AllSyncManager::Repeat (const int i = -1) inline
Definition at line 50 of file Fun4AllSyncManager.h.
References PushBackInputMgrsEvents(), repeat, and ResetEvent().
ResetEvent()
int Fun4AllSyncManager::ResetEvent ()
Definition at line 413 of file Fun4AllSyncManager.cc.
References InManager, Fun4AllBase::Name(), Fun4AllInputManager::ResetEvent(), and Fun4AllBase::verbosity.
Referenced by Fun4AllServer::process_event(), and Repeat().
run()
int Fun4AllSyncManager::run (const int nevnts = 0)
run n events (0 means up to end of file
Definition at line 88 of file Fun4AllSyncManager.cc.
References CheckSync(), currentrun, events_total, InManager, iretInManager, MasterSync, Fun4AllBase::Name(), repeat, Fun4AllInputManager::RunNumber(), Fun4AllBase::ThisName, and Fun4AllBase::verbosity.
SegmentNumber() [1/2]
void Fun4AllSyncManager::SegmentNumber (const int iseg) inline
Definition at line 39 of file Fun4AllSyncManager.h.
References prdf_segment.
Referenced by Fun4AllEVIOInputManager::run(), Fun4AllPrdfInputManager::run(), Fun4AllSRawEventInputManager::run(), and Fun4AllServer::SegmentNumber().
SegmentNumber() [2/2]
int Fun4AllSyncManager::SegmentNumber () const inline
Definition at line 40 of file Fun4AllSyncManager.h.
References BranchSelect(), prdf_segment, and setBranches().
setBranches() [1/2]
int Fun4AllSyncManager::setBranches (const std::string & managername)
Definition at line 317 of file Fun4AllSyncManager.cc.
References InManager, Fun4AllBase::Name(), and Fun4AllInputManager::setBranches().
setBranches() [2/2]
int Fun4AllSyncManager::setBranches ()
Definition at line 332 of file Fun4AllSyncManager.cc.
References InManager, and Fun4AllInputManager::setBranches().
Referenced by SegmentNumber().
skip()
int Fun4AllSyncManager::skip (const int nevnts = 0)
skip n events (0 means up to the end of file). Skip means read, don't process.
Definition at line 246 of file Fun4AllSyncManager.cc.
References InManager, PHWHERE, and Print().
TotalEvents() [1/2]
void Fun4AllSyncManager::TotalEvents (const int i) inline
Definition at line 45 of file Fun4AllSyncManager.h.
References events_total.
Referenced by Fun4AllServer::DstEvents().
TotalEvents() [2/2]
int Fun4AllSyncManager::TotalEvents () const inline
Definition at line 46 of file Fun4AllSyncManager.h.
References events_total.
Member Data Documentation
currentevent
int Fun4AllSyncManager::currentevent private
Definition at line 61 of file Fun4AllSyncManager.h.
Referenced by CurrentEvent().
currentrun
int Fun4AllSyncManager::currentrun private
Definition at line 60 of file Fun4AllSyncManager.h.
Referenced by CurrentRun(), and run().
events_total
int Fun4AllSyncManager::events_total private
Definition at line 59 of file Fun4AllSyncManager.h.
Referenced by run(), and TotalEvents().
InManager
std::vector<Fun4AllInputManager *> Fun4AllSyncManager::InManager private
Definition at line 64 of file Fun4AllSyncManager.h.
Referenced by BranchSelect(), CheckSync(), fileclose(), fileopen(), GetInputFullFileList(), getInputManager(), GetInputManagers(), Print(), PushBackInputMgrsEvents(), registerInputManager(), ResetEvent(), run(), setBranches(), skip(), and ~Fun4AllSyncManager().
iretInManager
std::vector<int> Fun4AllSyncManager::iretInManager private
Definition at line 65 of file Fun4AllSyncManager.h.
Referenced by registerInputManager(), and run().
MasterSync
SyncObject* Fun4AllSyncManager::MasterSync private
Definition at line 63 of file Fun4AllSyncManager.h.
Referenced by CheckSync(), run(), and ~Fun4AllSyncManager().
prdf_events
int Fun4AllSyncManager::prdf_events private
Definition at line 58 of file Fun4AllSyncManager.h.
Referenced by PrdfEvents().
prdf_segment
int Fun4AllSyncManager::prdf_segment private
Definition at line 57 of file Fun4AllSyncManager.h.
Referenced by SegmentNumber().
repeat
int Fun4AllSyncManager::repeat private
Definition at line 62 of file Fun4AllSyncManager.h.
Referenced by Repeat(), and run().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/fun4all/Fun4AllSyncManager.h
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/fun4all/Fun4AllSyncManager.cc