Class Reference for E1039 Core & Analysis Software: TruthEval Class Reference
TruthEval Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TargetSim/TruthEval/TruthEval.h>
Public Member Functions
TruthEval (const std::string &name="TruthEval", const std::string &out="eval.root")
virtual ~TruthEval ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int InitEvalTree ()
int ResetEvalVars ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Attributes
std::string _out_name
float target_angle
float target_r
float target_l
float target_z
float coil_in_r
float coil_ot_r
float coil_min_y_0
float coil_max_y_0
float coil_min_y_1
float coil_max_y_1
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 29 of file TruthEval.h.
Constructor & Destructor Documentation
TruthEval::TruthEval (const std::string & name = "TruthEval", const std::string & out = "eval.root")
Definition at line 45 of file TruthEval.cxx.
References coil_in_r, coil_max_y_0, coil_max_y_1, coil_min_y_0, coil_min_y_1, coil_ot_r, InitEvalTree(), ResetEvalVars(), target_angle, target_l, target_r, and target_z.
virtual TruthEval::~TruthEval () inline virtual
Definition at line 34 of file TruthEval.h.
Member Function Documentation
int TruthEval::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 264 of file TruthEval.cxx.
References _out_name, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int TruthEval::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 67 of file TruthEval.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int TruthEval::InitEvalTree ()
Definition at line 277 of file TruthEval.cxx.
References _out_name, PHTFileServer::get(), and PHTFileServer::open().
Referenced by TruthEval().
int TruthEval::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 71 of file TruthEval.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int TruthEval::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 79 of file TruthEval.cxx.
References coil_in_r, coil_max_y_0, coil_max_y_1, coil_min_y_0, coil_min_y_1, coil_ot_r, TruthTrack::det_id, TruthTrack::e, TruthTrack::edep_coil, TruthTrack::eta, PHG4Particle::get_e(), PHG4Hit::get_edep(), PHG4Hit::get_layer(), PHG4Particle::get_parent_id(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4VtxPoint::get_t(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), PHG4Hit::get_x(), PHG4VtxPoint::get_y(), PHG4Hit::get_y(), PHG4VtxPoint::get_z(), PHG4Hit::get_z(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetParticleRange(), PHG4TruthInfoContainer::GetVtx(), PHG4Hit::identify(), TruthTrack::mass, TruthTrack::p, TruthTrack::parentid, TruthTrack::path_coil, TruthTrack::pid, TruthTrack::pt, TruthTrack::px, TruthTrack::py, TruthTrack::pz, ResetEvalVars(), TruthTrack::t, target_angle, target_l, target_r, target_z, Fun4AllBase::Verbosity(), Fun4AllBase::verbosity, Fun4AllBase::VERBOSITY_SOME, TruthTrack::vx, TruthTrack::vy, and TruthTrack::vz.
int TruthEval::ResetEvalVars ()
Definition at line 293 of file TruthEval.cxx.
Referenced by process_event(), and TruthEval().
Member Data Documentation
std::string TruthEval::_out_name
Definition at line 45 of file TruthEval.h.
Referenced by End(), and InitEvalTree().
float TruthEval::coil_in_r
Definition at line 52 of file TruthEval.h.
Referenced by Fun4All_G4_BNL(), Fun4All_G4_BNL_R1(), process_event(), and TruthEval().
float TruthEval::coil_max_y_0
Definition at line 55 of file TruthEval.h.
Referenced by Fun4All_G4_BNL(), Fun4All_G4_BNL_R1(), process_event(), and TruthEval().
float TruthEval::coil_max_y_1
Definition at line 57 of file TruthEval.h.
Referenced by Fun4All_G4_BNL(), Fun4All_G4_BNL_R1(), process_event(), and TruthEval().
float TruthEval::coil_min_y_0
Definition at line 54 of file TruthEval.h.
Referenced by Fun4All_G4_BNL(), Fun4All_G4_BNL_R1(), process_event(), and TruthEval().
float TruthEval::coil_min_y_1
Definition at line 56 of file TruthEval.h.
Referenced by Fun4All_G4_BNL(), Fun4All_G4_BNL_R1(), process_event(), and TruthEval().
float TruthEval::coil_ot_r
Definition at line 53 of file TruthEval.h.
Referenced by Fun4All_G4_BNL(), Fun4All_G4_BNL_R1(), process_event(), and TruthEval().
float TruthEval::target_angle
Definition at line 47 of file TruthEval.h.
Referenced by Fun4All_G4_BNL_R1(), process_event(), and TruthEval().
float TruthEval::target_l
Definition at line 49 of file TruthEval.h.
Referenced by Fun4All_G4_BNL_R1(), Fun4All_G4_E1039_R2(), Fun4All_G4_E1039_R2_V2(), Fun4All_Test(), process_event(), and TruthEval().
float TruthEval::target_r
Definition at line 48 of file TruthEval.h.
Referenced by Fun4All_G4_BNL(), Fun4All_G4_BNL_R1(), process_event(), and TruthEval().
float TruthEval::target_z
Definition at line 50 of file TruthEval.h.
Referenced by Fun4All_G4_BNL(), Fun4All_G4_E1039_R2(), Fun4All_G4_E1039_R2_V2(), Fun4All_Test(), process_event(), and TruthEval().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TargetSim/TruthEval/TruthEval.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TargetSim/TruthEval/TruthEval.cxx