Class Reference for E1039 Core & Analysis Software: EventDispOfflineUI Class Reference
EventDispOfflineUI Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Display/interface/EventDispOfflineUI.h>
Public Member Functions
EventDispOfflineUI ()
virtual ~EventDispOfflineUI ()
int FetchNumEvents (const std::string fn_dst)
virtual void PrevEvent ()
virtual void Run (const int run_id, const std::string fn_dst)
Public Member Functions inherited from EventDispUI
EventDispUI ()
virtual ~EventDispUI ()
std::string GetDstPath (const int run, const int spill=0)
bool FindNewRuns ()
bool FindSpillDSTs ()
int FetchNumEvents (const int run, const int spill=0)
int OpenRunFile (const int run, const int spill=0)
virtual void NextEvent ()
void MoveEvent (const int i_evt)
void ReqEvtID ()
void ReqTrig ()
void ViewTop ()
void ViewSide ()
void View3D ()
void UpdateLabels ()
void SetAutoMode (bool value)
void Init (const bool online_mode)
virtual void Run ()
Protected Attributes
std::string m_fn_dst
Protected Attributes inherited from EventDispUI
RunList_t m_list_run
SpillList_t m_list_spill
int m_run
int m_spill
int m_n_evt
int m_i_evt
TGMainFrame * m_fr_main
TGCompositeFrame * m_fr_menu
TGCompositeFrame * m_fr_evt_mode
TGCompositeFrame * m_fr_evt_sel
TGCompositeFrame * m_fr_evt_next
TGCompositeFrame * m_fr_evt_prev
TGLabel * m_lbl_mode
TGLabel * m_lbl_run
TGLabel * m_lbl_n_evt
TGNumberEntry * m_ne_evt_id
TGNumberEntry * m_ne_trig
bool m_online_mode
bool m_auto_mode
pthread_t m_tid1
Additional Inherited Members
Protected Types inherited from EventDispUI
typedef std::vector< int > RunList_t
typedef std::vector< int > SpillList_t
Protected Member Functions inherited from EventDispUI
void BuildInterface ()
void UpdateInterface ()
void ExecNewEventCheck ()
int ReadNumber (const std::string msg="Run?")
Static Protected Member Functions inherited from EventDispUI
static void * FuncNewEventCheck (void *arg)
Static Protected Attributes inherited from EventDispUI
static const int RUN_MIN = 1000
static const int RUN_MAX = 40000
Detailed Description
Definition at line 6 of file EventDispOfflineUI.h.
Constructor & Destructor Documentation
EventDispOfflineUI()
EventDispOfflineUI::EventDispOfflineUI ()
Definition at line 21 of file EventDispOfflineUI.cxx.
References EventDispUI::m_auto_mode, and EventDispUI::m_online_mode.
~EventDispOfflineUI()
virtual EventDispOfflineUI::~EventDispOfflineUI () inline virtual
Definition at line 19 of file EventDispOfflineUI.h.
Member Function Documentation
FetchNumEvents()
int EventDispOfflineUI::FetchNumEvents (const std::string fn_dst)
Definition at line 28 of file EventDispOfflineUI.cxx.
Referenced by Run().
PrevEvent()
void EventDispOfflineUI::PrevEvent () virtual
Reimplemented from EventDispUI.
Definition at line 59 of file EventDispOfflineUI.cxx.
References Fun4AllInputManager::fileopen(), Fun4AllServer::getInputManager(), Fun4AllServer::instance(), m_fn_dst, EventDispUI::m_i_evt, EventDispUI::m_n_evt, Fun4AllServer::run(), Fun4AllServer::skip(), and EventDispUI::UpdateLabels().
Run()
void EventDispOfflineUI::Run (const int run_id, const std::string fn_dst) virtual
Definition at line 151 of file EventDispOfflineUI.cxx.
References EventDispUI::BuildInterface(), FetchNumEvents(), Fun4AllInputManager::fileopen(), Fun4AllServer::getInputManager(), Fun4AllServer::instance(), m_fn_dst, EventDispUI::m_i_evt, EventDispUI::m_n_evt, EventDispUI::m_run, EventDispUI::MoveEvent(), and EventDispUI::UpdateLabels().
Member Data Documentation
m_fn_dst
std::string EventDispOfflineUI::m_fn_dst protected
Definition at line 8 of file EventDispOfflineUI.h.
Referenced by PrevEvent(), and Run().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Display/interface/EventDispOfflineUI.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Display/interface/EventDispOfflineUI.cxx