E1039 Software: DbSvc::VarList Class Reference
DbSvc::VarList Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/db_svc/DbSvc.h>
Public Member Functions
unsigned int Size () const
void Add (const std::string name, const std::string type, const bool is_key=false)
void Get (const int idx, std::string &name, std::string &type, bool &is_key) const
Private Attributes
std::vector< std::string > m_name
std::vector< std::string > m_type
std::vector< bool > m_is_key
Detailed Description
Definition at line 13 of file DbSvc.h.
Member Function Documentation
Add()
void DbSvc::VarList::Add (const std::string name, const std::string type, const bool is_key = false)
Definition at line 225 of file DbSvc.cc.
Referenced by Size(), DbUpRun::UploadToDB(), DbUpSpill::UploadToScalerTable(), DbUpSpill::UploadToSlowContTable(), and DbUpSpill::UploadToSpillTable().
Get()
void DbSvc::VarList::Get (const int idx, std::string & name, std::string & type, bool & is_key) const
Definition at line 232 of file DbSvc.cc.
Referenced by DbSvc::CreateTable(), and Size().
Size()
unsigned int DbSvc::VarList::Size () const inline
Definition at line 18 of file DbSvc.h.
References Add(), DbSvc::DB1, DbSvc::DbSvc(), Get(), DbSvc::Guest, DbSvc::UseSchema(), and DbSvc::~DbSvc().
Referenced by DbSvc::CreateTable().
Member Data Documentation
m_is_key
std::vector<bool> DbSvc::VarList::m_is_key private
Definition at line 16 of file DbSvc.h.
m_name
std::vector<std::string> DbSvc::VarList::m_name private
Definition at line 14 of file DbSvc.h.
m_type
std::vector<std::string> DbSvc::VarList::m_type private
Definition at line 15 of file DbSvc.h.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/db_svc/DbSvc.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/db_svc/DbSvc.cc