Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CODAChainDev/G4_SensitiveDetectors.C File Reference
G4_SensitiveDetectors.C File Reference
#include <g4detectors/PHG4BlockSubsystem.h>
#include <TSQLServer.h>
#include <TSQLResult.h>
#include <TSQLRow.h>
Macros
#define LogDebug(exp) std::cout<<"DEBUG: " <<__FILE__<<": "<<__LINE__<<": "<< exp << std::endl
Functions
void SetupSensitiveDetectors (PHG4Reco *g4Reco, const int verbosity=0)
Macro Definition Documentation
#define LogDebug (exp) std::cout<<"DEBUG: " <<__FILE__<<": "<<__LINE__<<": "<< exp << std::endl
Definition at line 11 of file G4_SensitiveDetectors.C.
Referenced by SetupSensitiveDetectors().
Function Documentation
void SetupSensitiveDetectors (PHG4Reco * g4Reco, const int verbosity = 0)
Definition at line 15 of file G4_SensitiveDetectors.C.
References GeomSvc::getDetectorID(), GeomSvc::getDetectorX0(), GeomSvc::getDetectorY0(), GeomSvc::getDetectorZ0(), GeomSvc::getPlaneScaleX(), GeomSvc::getPlaneScaleY(), GeomSvc::getPlaneScaleZ(), GeomSvc::instance(), LogDebug, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and Fun4AllBase::verbosity.