Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/E1039Shielding/G4_SensitiveDetectors.C File Reference
G4_SensitiveDetectors.C File Reference
#include <string>
Macros
#define LogDebug(exp) std::cout<<"DEBUG: " <<__FILE__<<": "<<__LINE__<<": "<< exp << std::endl
Functions
void get_phys_param (TSQLServer *server, const string &pvName, int &lvID, double *place, double *rot)
void get_logi_param (TSQLServer *server, const int lvID, int &sID)
void get_soli_param (TSQLServer *server, const int sID, double *size)
void SetupSensitiveDetectors (PHG4Reco *g4Reco, std::string _server_name="seaquestdb01.fnal.gov", int _port=3310, std::string _user_name="seaguest", std::string _password="qqbar2mu+mu-", std::string _input_shcema="geometry_G17_run3")
Macro Definition Documentation
#define LogDebug (exp) std::cout<<"DEBUG: " <<__FILE__<<": "<<__LINE__<<": "<< exp << std::endl
Definition at line 3 of file G4_SensitiveDetectors.C.
Referenced by get_logi_param(), get_phys_param(), and get_soli_param().
Function Documentation
void get_logi_param (TSQLServer * server, const int lvID, int & sID)
Definition at line 49 of file G4_SensitiveDetectors.C.
References LogDebug.
Referenced by SetupDriftChamber(), and SetupSensitiveDetectors().
void get_phys_param (TSQLServer * server, const string & pvName, int & lvID, double * place, double * rot)
Definition at line 19 of file G4_SensitiveDetectors.C.
References LogDebug.
Referenced by SetupDriftChamber(), and SetupSensitiveDetectors().
void get_soli_param (TSQLServer * server, const int sID, double * size)
Definition at line 71 of file G4_SensitiveDetectors.C.
References LogDebug.
Referenced by SetupDriftChamber(), and SetupSensitiveDetectors().
void SetupSensitiveDetectors (PHG4Reco * g4Reco, std::string _server_name = "seaquestdb01.fnal.gov", int _port = 3310, std::string _user_name = "seaguest", std::string _password = "qqbar2mu+mu-", std::string _input_shcema = "geometry_G17_run3")
Definition at line 95 of file G4_SensitiveDetectors.C.
References Fun4AllReturnCodes::ABORTRUN, get_logi_param(), get_phys_param(), get_soli_param(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().