Class Reference for E1039 Core & Analysis Software: RoadListBase Class Reference
RoadListBase Class Reference
Base class to hold a set (list or map) of roads.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadListBase.h>
Public Member Functions
virtual ~RoadListBase ()
void SetPNTB (const int pn, const int tb)
void SetPosNeg (const int pn)
void SetTopBot (const int tb)
int GetPosNeg () const
int GetTopBot () const
std::string GetPosNegStr () const
std::string GetTopBotStr () const
void Frozen ()
bool IsFrozen ()
Protected Member Functions
RoadListBase ()
Protected Attributes
int m_pn
int m_tb
bool m_frozen
Detailed Description
Base class to hold a set (list or map) of roads.
Definition at line 6 of file RoadListBase.h.
Constructor & Destructor Documentation
RoadListBase()
RoadListBase::RoadListBase () protected
Definition at line 4 of file RoadListBase.cc.
~RoadListBase()
RoadListBase::~RoadListBase () virtual
Definition at line 12 of file RoadListBase.cc.
Member Function Documentation
Frozen()
void RoadListBase::Frozen () inline
Definition at line 25 of file RoadListBase.h.
References m_frozen.
Referenced by AnaBG::SetRoads().
GetPosNeg()
int RoadListBase::GetPosNeg () const inline
Definition at line 20 of file RoadListBase.h.
References m_pn.
GetPosNegStr()
std::string RoadListBase::GetPosNegStr () const inline
Definition at line 22 of file RoadListBase.h.
References m_pn.
Referenced by GenRoadset::DisableRoadsByFoM(), GenRoadset::DisableRoadsByWeightFraction(), DrawRoadset::DrawOneSet(), and GenRoadset::GenerateSymmetricRoadSetByFoM().
GetTopBot()
int RoadListBase::GetTopBot () const inline
Definition at line 21 of file RoadListBase.h.
References m_tb.
GetTopBotStr()
std::string RoadListBase::GetTopBotStr () const inline
Definition at line 23 of file RoadListBase.h.
References m_tb.
Referenced by GenRoadset::DisableRoadsByFoM(), GenRoadset::DisableRoadsByWeightFraction(), DrawRoadset::DrawOneSet(), and GenRoadset::GenerateSymmetricRoadSetByFoM().
IsFrozen()
bool RoadListBase::IsFrozen () inline
Definition at line 26 of file RoadListBase.h.
References m_frozen.
SetPNTB()
void RoadListBase::SetPNTB (const int pn, const int tb) inline
Definition at line 17 of file RoadListBase.h.
References m_pn, and m_tb.
Referenced by AnaSignal::AnaSignal(), DrawRoadset::DrawRoadset(), and GenRoadset::GenRoadset().
SetPosNeg()
void RoadListBase::SetPosNeg (const int pn) inline
Definition at line 18 of file RoadListBase.h.
References m_pn.
SetTopBot()
void RoadListBase::SetTopBot (const int tb) inline
Definition at line 19 of file RoadListBase.h.
References m_tb.
Member Data Documentation
m_frozen
bool RoadListBase::m_frozen protected
Definition at line 10 of file RoadListBase.h.
Referenced by Frozen(), and IsFrozen().
m_pn
int RoadListBase::m_pn protected
Definition at line 8 of file RoadListBase.h.
Referenced by GetPosNeg(), GetPosNegStr(), SetPNTB(), and SetPosNeg().
m_tb
int RoadListBase::m_tb protected
Definition at line 9 of file RoadListBase.h.
Referenced by GetTopBot(), GetTopBotStr(), SetPNTB(), and SetTopBot().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadListBase.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadListBase.cc