E1039 Software: SRawEvent Class Reference
SRawEvent Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/SRawEvent.h>
Public Types
enum TriggerType {
MATRIX1 = triggerBit(0), MATRIX2 = triggerBit(1), MATRIX3 = triggerBit(2), MATRIX4 = triggerBit(3),
MATRIX5 = triggerBit(4), NIM1 = triggerBit(5), NIM2 = triggerBit(6), NIM3 = triggerBit(7),
NIM4 = triggerBit(8), NIM5 = triggerBit(9)
}
typedef std::pair< Int_t, Int_t > hit_pair
Type of pair with two adjacent wires.
Public Member Functions
SRawEvent ()
~SRawEvent ()
void identify (std::ostream &os=std::cout) const
PHObject virtual overloads.
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SRawEvent * Clone () const
void DeepClone (SRawEvent *c)
std::list< Int_t > getHitsIndexInDetector (Short_t detectorID)
Gets.
std::list< Int_t > getHitsIndexInDetector (Short_t detectorID, Double_t x_exp, Double_t win)
std::list< Int_t > getHitsIndexInSuperDetector (Short_t detectorID)
std::list< Int_t > getHitsIndexInDetectors (std::vector< Int_t > &detectorIDs)
std::list< Int_t > getAdjacentHitsIndex (Hit &_hit)
Int_t getNHitsAll ()
Int_t getNTriggerHits ()
Int_t getNChamberHitsAll ()
Int_t getNHodoHitsAll ()
Int_t getNPropHitsAll ()
Int_t getNHitsInD0 ()
Int_t getNHitsInD1 ()
Int_t getNHitsInD2 ()
Int_t getNHitsInD3 ()
Int_t getNHitsInD3p ()
Int_t getNHitsInD3m ()
Int_t getNHitsInH1 ()
Int_t getNHitsInH2 ()
Int_t getNHitsInH3 ()
Int_t getNHitsInH4 ()
Int_t getNHitsInP1 ()
Int_t getNHitsInP2 ()
Int_t getNHitsInDetector (Short_t detectorID)
Int_t getNHitsInSuperDetector (Short_t detectorID)
Int_t getNHitsInDetectors (std::vector< Int_t > &detectorIDs)
std::vector< Hit > & getAllHits ()
std::vector< Hit > & getTriggerHits ()
Hit getTriggerHit (Int_t index)
Hit getHit (Int_t index)
Hit getHit (Short_t detectorID, Short_t elementID)
void setHitFlag (Int_t index, Short_t flag)
void setHitFlag (Short_t detectorID, Short_t elementID, Short_t flag)
Int_t getRunID ()
Int_t getEventID ()
Int_t getSpillID ()
void setEventInfo (Int_t runID, Int_t spillID, Int_t eventID)
Sets.
void setHit (Int_t index, Hit h)
void setTriggerHit (Int_t index, Hit h)
void insertHit (Hit h)
Insert a new hit.
void insertTriggerHit (Hit h)
Int_t findHit (Short_t detectorID, Short_t elementID)
Find a hit – binary search since hit list is sorted.
void reIndex (bool doSort=false)
Reset the number hits on each plane.
std::list< SRawEvent::hit_pair > getPartialHitPairsInSuperDetector (Short_t detectorID)
std::list< SRawEvent::hit_pair > getPartialHitPairsInSuperDetector (Short_t detectorID, Double_t x_exp, Double_t wind)
Int_t getTriggerBits ()
Set/get the trigger types.
void setTriggerBits (Int_t triggers[])
void setTriggerBits (Int_t triggers)
bool isTriggeredBy (Int_t trigger)
bool isNIMTriggered ()
bool isFPGATriggered ()
bool isEmuTriggered ()
Int_t getNRoadsPos ()
Int_t getNRoadsNeg ()
Int_t getNRoadsPosTop ()
Int_t getNRoadsPosBot ()
Int_t getNRoadsNegTop ()
Int_t getNRoadsNegBot ()
Short_t * getNRoads ()
void setTriggerEmu (bool flag)
void setNRoads (Short_t nRoads[])
void setNRoads (Int_t nRoads[])
Int_t getTargetPos ()
void setTargetPos (Short_t targetPos)
Int_t getTurnID ()
Int_t getRFID ()
Int_t getIntensity ()
Int_t getIntensity (Int_t i)
Int_t getIntensitySumBefore (Int_t n=16)
Int_t getIntensitySumAfter (Int_t n=16)
Int_t * getIntensityAll ()
void setTurnID (Int_t turnID)
void setRFID (Int_t rfID)
void setIntensity (const Int_t intensity[])
void setIntensity (Int_t i, Int_t val)
void setIntensity (Int_t val)
void mergeEvent (const SRawEvent &rawEvent)
Merge a event to this event.
void setEventInfo (SRawEvent *event)
Set the event info from another event.
void clear ()
Clear the internal event structure.
void empty ()
only empty the hit list, leave other information untouched
void print (std::ostream &os=std::cout) const
Print for debugging purposes.
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Private Attributes
Int_t fRunID
Int_t fEventID
Int_t fSpillID
Int_t fTriggerBits
Short_t fTargetPos
Int_t fTurnID
Int_t fRFID
Int_t fIntensity [33]
Short_t fTriggerEmu
Short_t fNRoads [4]
Int_t fNHits [nChamberPlanes+nHodoPlanes+nPropPlanes+1]
Hits of this event.
std::vector< Hit > fAllHits
std::vector< Hit > fTriggerHits
Friends
class EventReducer
Friend class which handles all kinds of hit list reduction.
Detailed Description
Definition at line 96 of file SRawEvent.h.
Member Typedef Documentation
hit_pair
typedef std::pair<Int_t, Int_t> SRawEvent::hit_pair
Type of pair with two adjacent wires.
Definition at line 169 of file SRawEvent.h.
Member Enumeration Documentation
TriggerType
enum SRawEvent::TriggerType
Enumerator
MATRIX1
MATRIX2
MATRIX3
MATRIX4
MATRIX5
NIM1
NIM2
NIM3
NIM4
NIM5
Definition at line 233 of file SRawEvent.h.
Constructor & Destructor Documentation
SRawEvent()
SRawEvent::SRawEvent ()
Definition at line 84 of file SRawEvent.cxx.
References fAllHits, fNHits, fTriggerHits, nChamberPlanes, nHodoPlanes, and nPropPlanes.
~SRawEvent()
SRawEvent::~SRawEvent ()
Definition at line 94 of file SRawEvent.cxx.
Member Function Documentation
clear()
void SRawEvent::clear ()
Clear the internal event structure.
Definition at line 605 of file SRawEvent.cxx.
References fAllHits, fEventID, fIntensity, fNHits, fNRoads, fRFID, fRunID, fSpillID, fTriggerBits, fTriggerEmu, fTriggerHits, fTurnID, nChamberPlanes, nHodoPlanes, and nPropPlanes.
Clone()
SRawEvent* SRawEvent::Clone () const inline
Definition at line 106 of file SRawEvent.h.
References Hit::detectorID.
DeepClone()
void SRawEvent::DeepClone (SRawEvent * c)
Definition at line 98 of file SRawEvent.cxx.
References fAllHits, fEventID, fIntensity, fNHits, fNRoads, fRFID, fRunID, fSpillID, fTargetPos, fTriggerBits, fTriggerHits, fTurnID, getAllHits(), getEventID(), getIntensity(), getNHitsInDetector(), getNRoads(), getRFID(), getRunID(), getSpillID(), getTargetPos(), getTriggerBits(), getTriggerHits(), getTurnID(), isEmuTriggered(), nChamberPlanes, nHodoPlanes, nPropPlanes, and setTriggerEmu().
Referenced by Fun4AllSRawEventInputManager::run().
empty()
void SRawEvent::empty () inline
only empty the hit list, leave other information untouched
Definition at line 223 of file SRawEvent.h.
References Hit::print().
findHit()
Int_t SRawEvent::findHit (Short_t detectorID, Short_t elementID)
Find a hit – binary search since hit list is sorted.
Definition at line 141 of file SRawEvent.cxx.
References fAllHits, fNHits, nChamberPlanes, nHodoPlanes, and nPropPlanes.
Referenced by getHit().
getAdjacentHitsIndex()
std::list< Int_t > SRawEvent::getAdjacentHitsIndex (Hit & _hit)
Definition at line 353 of file SRawEvent.cxx.
References Hit::detectorID, Hit::elementID, fAllHits, and fNHits.
getAllHits()
std::vector<Hit>& SRawEvent::getAllHits () inline
Definition at line 141 of file SRawEvent.h.
Referenced by TriggerAnalyzer::acceptEvent(), DeepClone(), SRawEventEmbed::process_event(), KalmanFastTrackingWrapper::ReMaskHits(), KalmanFastTracking::setRawEvent(), KalmanFastTracking::setRawEventDebug(), KalmanDSTrk::setRawEventDebug(), and KalmanDSTrk::setRawEventWorker().
getEventID()
Int_t SRawEvent::getEventID () inline
Definition at line 150 of file SRawEvent.h.
Referenced by DeepClone(), Fun4AllSRawEventInputManager::run(), and SRecEvent::setEventInfo().
getHit() [1/2]
Hit SRawEvent::getHit (Int_t index) inline
Definition at line 144 of file SRawEvent.h.
References Hit::elementID, and Hit::index.
Referenced by getHit(), KalmanTrack::KalmanTrack(), and SRecEvent::setRawEvent().
getHit() [2/2]
Hit SRawEvent::getHit (Short_t detectorID, Short_t elementID)
Definition at line 178 of file SRawEvent.cxx.
References findHit(), and getHit().
getHitsIndexInDetector() [1/2]
std::list< Int_t > SRawEvent::getHitsIndexInDetector (Short_t detectorID)
Gets.
Definition at line 187 of file SRawEvent.cxx.
References fAllHits, and fNHits.
Referenced by getPartialHitPairsInSuperDetector(), KalmanFastTracking::setRawEvent(), and KalmanDSTrk::setRawEventWorker().
getHitsIndexInDetector() [2/2]
std::list< Int_t > SRawEvent::getHitsIndexInDetector (Short_t detectorID, Double_t x_exp, Double_t win)
Definition at line 203 of file SRawEvent.cxx.
References fAllHits, and fNHits.
getHitsIndexInDetectors()
std::list< Int_t > SRawEvent::getHitsIndexInDetectors (std::vector< Int_t > & detectorIDs)
Definition at line 234 of file SRawEvent.cxx.
References fAllHits, and fNHits.
Referenced by KalmanFastTracking::setRawEvent(), and KalmanDSTrk::setRawEventWorker().
getHitsIndexInSuperDetector()
std::list< Int_t > SRawEvent::getHitsIndexInSuperDetector (Short_t detectorID)
Definition at line 219 of file SRawEvent.cxx.
References fAllHits, and fNHits.
getIntensity() [1/2]
Int_t SRawEvent::getIntensity () inline
Definition at line 201 of file SRawEvent.h.
Referenced by DeepClone().
getIntensity() [2/2]
Int_t SRawEvent::getIntensity (Int_t i) inline
Definition at line 202 of file SRawEvent.h.
getIntensityAll()
Int_t* SRawEvent::getIntensityAll () inline
Definition at line 205 of file SRawEvent.h.
Referenced by setEventInfo().
getIntensitySumAfter()
Int_t SRawEvent::getIntensitySumAfter (Int_t n = 16) inline
Definition at line 204 of file SRawEvent.h.
getIntensitySumBefore()
Int_t SRawEvent::getIntensitySumBefore (Int_t n = 16) inline
Definition at line 203 of file SRawEvent.h.
getNChamberHitsAll()
Int_t SRawEvent::getNChamberHitsAll ()
Definition at line 382 of file SRawEvent.cxx.
References fNHits, and nChamberPlanes.
Referenced by EventReducer::reduceEvent().
getNHitsAll()
Int_t SRawEvent::getNHitsAll () inline
Definition at line 118 of file SRawEvent.h.
Referenced by SRecEvent::setRawEvent().
getNHitsInD0()
Int_t SRawEvent::getNHitsInD0 ()
Definition at line 434 of file SRawEvent.cxx.
References fNHits.
Referenced by KalmanFastTracking::acceptEvent(), and KalmanDSTrk::acceptEvent().
getNHitsInD1()
Int_t SRawEvent::getNHitsInD1 ()
Definition at line 445 of file SRawEvent.cxx.
References fNHits.
Referenced by KalmanFastTracking::acceptEvent(), and KalmanDSTrk::acceptEvent().
getNHitsInD2()
Int_t SRawEvent::getNHitsInD2 ()
Definition at line 456 of file SRawEvent.cxx.
References fNHits.
Referenced by KalmanFastTracking::acceptEvent(), and KalmanDSTrk::acceptEvent().
getNHitsInD3()
Int_t SRawEvent::getNHitsInD3 ()
Definition at line 467 of file SRawEvent.cxx.
References getNHitsInD3m(), and getNHitsInD3p().
getNHitsInD3m()
Int_t SRawEvent::getNHitsInD3m ()
Definition at line 483 of file SRawEvent.cxx.
References fNHits.
Referenced by KalmanFastTracking::acceptEvent(), KalmanDSTrk::acceptEvent(), and getNHitsInD3().
getNHitsInD3p()
Int_t SRawEvent::getNHitsInD3p ()
Definition at line 472 of file SRawEvent.cxx.
References fNHits.
Referenced by KalmanFastTracking::acceptEvent(), KalmanDSTrk::acceptEvent(), and getNHitsInD3().
getNHitsInDetector()
Int_t SRawEvent::getNHitsInDetector (Short_t detectorID) inline
Definition at line 137 of file SRawEvent.h.
References Hit::detectorID.
Referenced by DeepClone().
getNHitsInDetectors()
Int_t SRawEvent::getNHitsInDetectors (std::vector< Int_t > & detectorIDs)
Definition at line 415 of file SRawEvent.cxx.
References fNHits, nChamberPlanes, nHodoPlanes, and nPropPlanes.
Referenced by KalmanFastTracking::acceptEvent(), and KalmanDSTrk::acceptEvent().
getNHitsInH1()
Int_t SRawEvent::getNHitsInH1 ()
Definition at line 494 of file SRawEvent.cxx.
References fNHits, and nChamberPlanes.
getNHitsInH2()
Int_t SRawEvent::getNHitsInH2 ()
Definition at line 505 of file SRawEvent.cxx.
References fNHits, and nChamberPlanes.
getNHitsInH3()
Int_t SRawEvent::getNHitsInH3 ()
Definition at line 516 of file SRawEvent.cxx.
References fNHits, and nChamberPlanes.
getNHitsInH4()
Int_t SRawEvent::getNHitsInH4 ()
Definition at line 527 of file SRawEvent.cxx.
References fNHits, nChamberPlanes, and nHodoPlanes.
getNHitsInP1()
Int_t SRawEvent::getNHitsInP1 ()
Definition at line 538 of file SRawEvent.cxx.
References fNHits, nChamberPlanes, and nHodoPlanes.
getNHitsInP2()
Int_t SRawEvent::getNHitsInP2 ()
Definition at line 549 of file SRawEvent.cxx.
References fNHits, nChamberPlanes, nHodoPlanes, and nPropPlanes.
getNHitsInSuperDetector()
Int_t SRawEvent::getNHitsInSuperDetector (Short_t detectorID) inline
Definition at line 138 of file SRawEvent.h.
References Hit::detectorID.
getNHodoHitsAll()
Int_t SRawEvent::getNHodoHitsAll ()
Definition at line 393 of file SRawEvent.cxx.
References fNHits, nChamberPlanes, and nHodoPlanes.
getNPropHitsAll()
Int_t SRawEvent::getNPropHitsAll ()
Definition at line 404 of file SRawEvent.cxx.
References fNHits, nChamberPlanes, nHodoPlanes, and nPropPlanes.
Referenced by KalmanFastTracking::acceptEvent(), and KalmanDSTrk::acceptEvent().
getNRoads()
Short_t* SRawEvent::getNRoads () inline
Definition at line 189 of file SRawEvent.h.
Referenced by DeepClone(), and setEventInfo().
getNRoadsNeg()
Int_t SRawEvent::getNRoadsNeg () inline
Definition at line 184 of file SRawEvent.h.
Referenced by KalmanFastTracking::acceptEvent(), and KalmanDSTrk::acceptEvent().
getNRoadsNegBot()
Int_t SRawEvent::getNRoadsNegBot () inline
Definition at line 188 of file SRawEvent.h.
getNRoadsNegTop()
Int_t SRawEvent::getNRoadsNegTop () inline
Definition at line 187 of file SRawEvent.h.
getNRoadsPos()
Int_t SRawEvent::getNRoadsPos () inline
Definition at line 183 of file SRawEvent.h.
Referenced by KalmanFastTracking::acceptEvent(), and KalmanDSTrk::acceptEvent().
getNRoadsPosBot()
Int_t SRawEvent::getNRoadsPosBot () inline
Definition at line 186 of file SRawEvent.h.
getNRoadsPosTop()
Int_t SRawEvent::getNRoadsPosTop () inline
Definition at line 185 of file SRawEvent.h.
getNTriggerHits()
Int_t SRawEvent::getNTriggerHits () inline
Definition at line 119 of file SRawEvent.h.
getPartialHitPairsInSuperDetector() [1/2]
std::list< SRawEvent::hit_pair > SRawEvent::getPartialHitPairsInSuperDetector (Short_t detectorID)
Definition at line 255 of file SRawEvent.cxx.
References fAllHits, getHitsIndexInDetector(), nChamberPlanes, nHodoPlanes, and nPropPlanes.
Referenced by KalmanFastTracking::buildPropSegments(), KalmanDSTrk::buildPropSegments(), KalmanFastTracking::buildTrackletsInStation(), and KalmanDSTrk::buildTrackletsInStation().
getPartialHitPairsInSuperDetector() [2/2]
std::list< SRawEvent::hit_pair > SRawEvent::getPartialHitPairsInSuperDetector (Short_t detectorID, Double_t x_exp, Double_t wind)
Definition at line 304 of file SRawEvent.cxx.
References fAllHits, getHitsIndexInDetector(), nChamberPlanes, nHodoPlanes, and nPropPlanes.
getRFID()
Int_t SRawEvent::getRFID () inline
Definition at line 200 of file SRawEvent.h.
Referenced by DeepClone(), and setEventInfo().
getRunID()
Int_t SRawEvent::getRunID () inline
Definition at line 149 of file SRawEvent.h.
Referenced by DeepClone(), Fun4AllSRawEventInputManager::run(), setEventInfo(), and SRecEvent::setEventInfo().
getSpillID()
Int_t SRawEvent::getSpillID () inline
Definition at line 151 of file SRawEvent.h.
Referenced by DeepClone(), Fun4AllSRawEventInputManager::run(), and SRecEvent::setEventInfo().
getTargetPos()
Int_t SRawEvent::getTargetPos () inline
Definition at line 195 of file SRawEvent.h.
Referenced by DeepClone(), setEventInfo(), and SRecEvent::setEventInfo().
getTriggerBits()
Int_t SRawEvent::getTriggerBits () inline
Set/get the trigger types.
Definition at line 174 of file SRawEvent.h.
Referenced by DeepClone(), SRawEventEmbed::process_event(), setEventInfo(), and SRecEvent::setEventInfo().
getTriggerHit()
Hit SRawEvent::getTriggerHit (Int_t index) inline
Definition at line 143 of file SRawEvent.h.
References Hit::index.
getTriggerHits()
std::vector<Hit>& SRawEvent::getTriggerHits () inline
Definition at line 142 of file SRawEvent.h.
Referenced by TriggerAnalyzer::acceptEvent(), and DeepClone().
getTurnID()
Int_t SRawEvent::getTurnID () inline
Definition at line 199 of file SRawEvent.h.
Referenced by DeepClone(), and setEventInfo().
identify()
void SRawEvent::identify (std::ostream & os = std::cout) const inline virtual
PHObject virtual overloads.
Reimplemented from PHObject.
Definition at line 103 of file SRawEvent.h.
References Hit::print().
Referenced by KalmanFastTrackingWrapper::process_event(), and Fun4AllSRawEventInputManager::run().
insertHit()
void SRawEvent::insertHit (Hit h)
Insert a new hit.
Definition at line 132 of file SRawEvent.cxx.
References Hit::detectorID, fAllHits, fNHits, nChamberPlanes, nHodoPlanes, and nPropPlanes.
Referenced by KalmanFastTrackingWrapper::BuildSRawEvent().
insertTriggerHit()
void SRawEvent::insertTriggerHit (Hit h) inline
Definition at line 160 of file SRawEvent.h.
References Hit::detectorID, nChamberPlanes, and nHodoPlanes.
Referenced by KalmanFastTrackingWrapper::BuildSRawEvent().
isEmuTriggered()
bool SRawEvent::isEmuTriggered () inline
Definition at line 182 of file SRawEvent.h.
Referenced by DeepClone(), and setEventInfo().
isFPGATriggered()
bool SRawEvent::isFPGATriggered ()
Definition at line 640 of file SRawEvent.cxx.
References isTriggeredBy(), MATRIX1, MATRIX2, MATRIX3, MATRIX4, and MATRIX5.
Referenced by EventReducer::reduceEvent(), KalmanFastTracking::setRawEvent(), and KalmanDSTrk::setRawEventWorker().
isNIMTriggered()
bool SRawEvent::isNIMTriggered ()
Definition at line 635 of file SRawEvent.cxx.
References isTriggeredBy(), NIM1, and NIM3.
isTriggeredBy()
bool SRawEvent::isTriggeredBy (Int_t trigger) inline
Definition at line 177 of file SRawEvent.h.
Referenced by isFPGATriggered(), and isNIMTriggered().
isValid()
int SRawEvent::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 105 of file SRawEvent.h.
mergeEvent()
void SRawEvent::mergeEvent (const SRawEvent & rawEvent)
Merge a event to this event.
Definition at line 571 of file SRawEvent.cxx.
References fAllHits, fIntensity, fRFID, fTargetPos, fTriggerHits, fTurnID, and reIndex().
print()
void SRawEvent::print (std::ostream & os = std::cout) const
Print for debugging purposes.
Definition at line 645 of file SRawEvent.cxx.
References fAllHits, fEventID, fNHits, fRunID, and nChamberPlanes.
reIndex()
void SRawEvent::reIndex (bool doSort = false)
Reset the number hits on each plane.
Reset the number of hits on each plane
Definition at line 560 of file SRawEvent.cxx.
References fAllHits, fNHits, nChamberPlanes, nHodoPlanes, and nPropPlanes.
Referenced by KalmanFastTrackingWrapper::BuildSRawEvent(), mergeEvent(), and EventReducer::reduceEvent().
Reset()
void SRawEvent::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 104 of file SRawEvent.h.
setEventInfo() [1/2]
void SRawEvent::setEventInfo (Int_t runID, Int_t spillID, Int_t eventID)
Sets.
Definition at line 125 of file SRawEvent.cxx.
References fEventID, fRunID, and fSpillID.
Referenced by KalmanFastTrackingWrapper::BuildSRawEvent(), and setEventInfo().
setEventInfo() [2/2]
void SRawEvent::setEventInfo (SRawEvent * event)
Set the event info from another event.
Definition at line 584 of file SRawEvent.cxx.
References getIntensityAll(), getNRoads(), getRFID(), getRunID(), getTargetPos(), getTriggerBits(), getTurnID(), isEmuTriggered(), setEventInfo(), setIntensity(), setNRoads(), setRFID(), setTargetPos(), setTriggerBits(), setTriggerEmu(), and setTurnID().
setHit()
void SRawEvent::setHit (Int_t index, Hit h) inline
Definition at line 155 of file SRawEvent.h.
References Hit::index.
setHitFlag() [1/2]
void SRawEvent::setHitFlag (Int_t index, Short_t flag) inline
Definition at line 146 of file SRawEvent.h.
References Hit::index.
setHitFlag() [2/2]
void SRawEvent::setHitFlag (Short_t detectorID, Short_t elementID, Short_t flag) inline
Definition at line 147 of file SRawEvent.h.
References setHitFlag().
Referenced by setHitFlag().
setIntensity() [1/3]
void SRawEvent::setIntensity (const Int_t intensity[]) inline
Definition at line 209 of file SRawEvent.h.
Referenced by setEventInfo().
setIntensity() [2/3]
void SRawEvent::setIntensity (Int_t i, Int_t val) inline
Definition at line 210 of file SRawEvent.h.
setIntensity() [3/3]
void SRawEvent::setIntensity (Int_t val) inline
Definition at line 211 of file SRawEvent.h.
setNRoads() [1/2]
void SRawEvent::setNRoads (Short_t nRoads[]) inline
Definition at line 191 of file SRawEvent.h.
Referenced by setEventInfo(), and TriggerAnalyzer::trimEvent().
setNRoads() [2/2]
void SRawEvent::setNRoads (Int_t nRoads[]) inline
Definition at line 192 of file SRawEvent.h.
setRFID()
void SRawEvent::setRFID (Int_t rfID) inline
Definition at line 208 of file SRawEvent.h.
Referenced by setEventInfo().
setTargetPos()
void SRawEvent::setTargetPos (Short_t targetPos) inline
Definition at line 196 of file SRawEvent.h.
Referenced by KalmanFastTrackingWrapper::BuildSRawEvent(), and setEventInfo().
setTriggerBits() [1/2]
void SRawEvent::setTriggerBits (Int_t triggers[])
Definition at line 626 of file SRawEvent.cxx.
References fTriggerBits, and triggerBit.
Referenced by KalmanFastTrackingWrapper::BuildSRawEvent(), and setEventInfo().
setTriggerBits() [2/2]
void SRawEvent::setTriggerBits (Int_t triggers) inline
Definition at line 176 of file SRawEvent.h.
setTriggerEmu()
void SRawEvent::setTriggerEmu (bool flag) inline
Definition at line 190 of file SRawEvent.h.
Referenced by DeepClone(), setEventInfo(), and TriggerAnalyzer::trimEvent().
setTriggerHit()
void SRawEvent::setTriggerHit (Int_t index, Hit h) inline
Definition at line 156 of file SRawEvent.h.
References Hit::index.
setTurnID()
void SRawEvent::setTurnID (Int_t turnID) inline
Definition at line 207 of file SRawEvent.h.
Referenced by setEventInfo().
Friends And Related Function Documentation
EventReducer
friend class EventReducer friend
Friend class which handles all kinds of hit list reduction.
Definition at line 229 of file SRawEvent.h.
Member Data Documentation
fAllHits
std::vector<Hit> SRawEvent::fAllHits private
Definition at line 270 of file SRawEvent.h.
Referenced by clear(), DeepClone(), findHit(), getAdjacentHitsIndex(), getHitsIndexInDetector(), getHitsIndexInDetectors(), getHitsIndexInSuperDetector(), getPartialHitPairsInSuperDetector(), insertHit(), mergeEvent(), print(), EventReducer::reduceEvent(), reIndex(), and SRawEvent().
fEventID
Int_t SRawEvent::fEventID private
Definition at line 250 of file SRawEvent.h.
Referenced by clear(), DeepClone(), print(), and setEventInfo().
fIntensity
Int_t SRawEvent::fIntensity[33] private
Definition at line 262 of file SRawEvent.h.
Referenced by clear(), DeepClone(), and mergeEvent().
fNHits
Int_t SRawEvent::fNHits[nChamberPlanes+nHodoPlanes+nPropPlanes+1] private
Hits of this event.
Definition at line 269 of file SRawEvent.h.
Referenced by clear(), DeepClone(), findHit(), getAdjacentHitsIndex(), getHitsIndexInDetector(), getHitsIndexInDetectors(), getHitsIndexInSuperDetector(), getNChamberHitsAll(), getNHitsInD0(), getNHitsInD1(), getNHitsInD2(), getNHitsInD3m(), getNHitsInD3p(), getNHitsInDetectors(), getNHitsInH1(), getNHitsInH2(), getNHitsInH3(), getNHitsInH4(), getNHitsInP1(), getNHitsInP2(), getNHodoHitsAll(), getNPropHitsAll(), insertHit(), print(), reIndex(), and SRawEvent().
fNRoads
Short_t SRawEvent::fNRoads[4] private
Definition at line 266 of file SRawEvent.h.
Referenced by clear(), and DeepClone().
fRFID
Int_t SRawEvent::fRFID private
Definition at line 261 of file SRawEvent.h.
Referenced by clear(), DeepClone(), and mergeEvent().
fRunID
Int_t SRawEvent::fRunID private
Definition at line 249 of file SRawEvent.h.
Referenced by clear(), DeepClone(), print(), and setEventInfo().
fSpillID
Int_t SRawEvent::fSpillID private
Definition at line 251 of file SRawEvent.h.
Referenced by clear(), DeepClone(), and setEventInfo().
fTargetPos
Short_t SRawEvent::fTargetPos private
Definition at line 257 of file SRawEvent.h.
Referenced by DeepClone(), and mergeEvent().
fTriggerBits
Int_t SRawEvent::fTriggerBits private
Definition at line 254 of file SRawEvent.h.
Referenced by clear(), DeepClone(), and setTriggerBits().
fTriggerEmu
Short_t SRawEvent::fTriggerEmu private
Definition at line 265 of file SRawEvent.h.
Referenced by clear().
fTriggerHits
std::vector<Hit> SRawEvent::fTriggerHits private
Definition at line 271 of file SRawEvent.h.
Referenced by clear(), DeepClone(), mergeEvent(), EventReducer::reduceEvent(), and SRawEvent().
fTurnID
Int_t SRawEvent::fTurnID private
Definition at line 260 of file SRawEvent.h.
Referenced by clear(), DeepClone(), and mergeEvent().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/SRawEvent.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/SRawEvent.cxx