E1039 Software: RndmEmbed Class Reference
RndmEmbed Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/embedding/RndmEmbed.h>
Public Member Functions
RndmEmbed (const std::string &name="RndmEmbed")
virtual ~RndmEmbed ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int InitEvalTree ()
int ResetEvalVars ()
const std::string & get_hit_container_choice () const
void set_hit_container_choice (const std::string &hitContainerChoice)
const std::string & get_out_name () const
void set_out_name (const std::string &outName)
void print_noise_rate () const
void set_noise_rate (const std::string &name, const double &rate)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
Private Attributes
std::string _hit_container_type
std::map< std::string, double > _noise_rate
size_t _event
GeomSvc * p_geomSvc
SQHitMap * _hit_map
SQHitVector * _hit_vector
std::string _out_name
TTree * _tout
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 43 of file RndmEmbed.h.
Constructor & Destructor Documentation
RndmEmbed()
RndmEmbed::RndmEmbed (const std::string & name = "RndmEmbed")
Definition at line 58 of file RndmEmbed.cxx.
~RndmEmbed()
virtual RndmEmbed::~RndmEmbed () inline virtual
Definition at line 48 of file RndmEmbed.h.
References End(), Init(), InitEvalTree(), InitRun(), process_event(), and ResetEvalVars().
Member Function Documentation
End()
int RndmEmbed::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 194 of file RndmEmbed.cxx.
References _out_name, _tout, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by ~RndmEmbed().
get_hit_container_choice()
const std::string& RndmEmbed::get_hit_container_choice () const inline
Definition at line 59 of file RndmEmbed.h.
References _hit_container_type.
get_out_name()
const std::string& RndmEmbed::get_out_name () const inline
Definition at line 67 of file RndmEmbed.h.
References _out_name.
GetNodes()
int RndmEmbed::GetNodes (PHCompositeNode * topNode) private
Definition at line 216 of file RndmEmbed.cxx.
References _hit_container_type, _hit_map, _hit_vector, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and LogInfo.
Referenced by InitRun(), and set_noise_rate().
Init()
int RndmEmbed::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 69 of file RndmEmbed.cxx.
References Fun4AllReturnCodes::EVENT_OK.
Referenced by ~RndmEmbed().
InitEvalTree()
int RndmEmbed::InitEvalTree ()
Definition at line 204 of file RndmEmbed.cxx.
References _out_name, _tout, PHTFileServer::get(), and PHTFileServer::open().
Referenced by InitRun(), and ~RndmEmbed().
InitRun()
int RndmEmbed::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 73 of file RndmEmbed.cxx.
References Fun4AllReturnCodes::EVENT_OK, GetNodes(), InitEvalTree(), GeomSvc::instance(), p_geomSvc, and ResetEvalVars().
Referenced by ~RndmEmbed().
print_noise_rate()
void RndmEmbed::print_noise_rate () const inline
Definition at line 75 of file RndmEmbed.h.
References _noise_rate.
process_event()
int RndmEmbed::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 86 of file RndmEmbed.cxx.
References _event, _hit_container_type, _hit_vector, _noise_rate, _tout, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, SQHit_v1::get_detector_id(), SQHit_v1::get_element_id(), GeomSvc::getDetectorID(), GeomSvc::getMeasurement(), GeomSvc::getPlane(), LogInfo, Plane::nElements, p_geomSvc, SQHitVector::push_back(), ResetEvalVars(), SQHit_v1::set_detector_id(), SQHit_v1::set_drift_distance(), SQHit_v1::set_element_id(), SQMCHit_v1::set_g4hit_id(), SQHit_v1::set_hit_id(), SQHit_v1::set_hodo_mask(), SQHit_v1::set_in_time(), SQHit_v1::set_pos(), SQMCHit_v1::set_track_id(), SQMCHit_v1::set_truth_x(), SQMCHit_v1::set_truth_y(), SQMCHit_v1::set_truth_z(), SQHitVector::size(), Plane::spacing, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by ~RndmEmbed().
ResetEvalVars()
int RndmEmbed::ResetEvalVars ()
Definition at line 212 of file RndmEmbed.cxx.
Referenced by InitRun(), process_event(), and ~RndmEmbed().
set_hit_container_choice()
void RndmEmbed::set_hit_container_choice (const std::string & hitContainerChoice) inline
Definition at line 63 of file RndmEmbed.h.
References _hit_container_type.
set_noise_rate()
void RndmEmbed::set_noise_rate (const std::string & name, const double & rate) inline
Definition at line 81 of file RndmEmbed.h.
References _noise_rate, and GetNodes().
set_out_name()
void RndmEmbed::set_out_name (const std::string & outName) inline
Definition at line 71 of file RndmEmbed.h.
References _out_name.
Member Data Documentation
_event
size_t RndmEmbed::_event private
Definition at line 92 of file RndmEmbed.h.
Referenced by process_event().
_hit_container_type
std::string RndmEmbed::_hit_container_type private
Definition at line 89 of file RndmEmbed.h.
Referenced by get_hit_container_choice(), GetNodes(), process_event(), and set_hit_container_choice().
_hit_map
SQHitMap* RndmEmbed::_hit_map private
Definition at line 96 of file RndmEmbed.h.
Referenced by GetNodes().
_hit_vector
SQHitVector* RndmEmbed::_hit_vector private
Definition at line 97 of file RndmEmbed.h.
Referenced by GetNodes(), and process_event().
_noise_rate
std::map<std::string, double> RndmEmbed::_noise_rate private
Definition at line 90 of file RndmEmbed.h.
Referenced by print_noise_rate(), process_event(), and set_noise_rate().
_out_name
std::string RndmEmbed::_out_name private
Definition at line 99 of file RndmEmbed.h.
Referenced by End(), get_out_name(), InitEvalTree(), and set_out_name().
_tout
TTree* RndmEmbed::_tout private
Definition at line 100 of file RndmEmbed.h.
Referenced by End(), InitEvalTree(), and process_event().
p_geomSvc
GeomSvc* RndmEmbed::p_geomSvc private
Definition at line 94 of file RndmEmbed.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/embedding/RndmEmbed.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/embedding/RndmEmbed.cxx