E1039 Software: PHG4Hitv1 Class Reference
PHG4Hitv1 Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4Hitv1.h>
Classes
union u_property
convert between 32bit inputs and storage type prop_storage_t
Public Member Functions
PHG4Hitv1 ()
PHG4Hitv1 (const PHG4Hit &g4hit)
virtual ~PHG4Hitv1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
float get_x (const int i) const
float get_y (const int i) const
float get_z (const int i) const
float get_t (const int i) const
float get_edep () const
PHG4HitDefs::keytype get_hit_id () const
int get_detid () const
int get_shower_id () const
int get_trkid () const
void set_x (const int i, const float f)
void set_y (const int i, const float f)
void set_z (const int i, const float f)
void set_t (const int i, const float f)
void set_edep (const float f)
void set_hit_id (const PHG4HitDefs::keytype i)
void set_shower_id (const int i)
void set_trkid (const int i)
virtual void print () const
bool has_property (const PROPERTY prop_id) const
float get_property_float (const PROPERTY prop_id) const
int get_property_int (const PROPERTY prop_id) const
unsigned int get_property_uint (const PROPERTY prop_id) const
void set_property (const PROPERTY prop_id, const float value)
void set_property (const PROPERTY prop_id, const int value)
void set_property (const PROPERTY prop_id, const unsigned int value)
virtual float get_px (const int i) const
virtual float get_py (const int i) const
virtual float get_pz (const int i) const
virtual float get_local_x (const int i) const
virtual float get_local_y (const int i) const
virtual float get_local_z (const int i) const
virtual float get_eion () const
virtual float get_light_yield () const
virtual float get_path_length () const
virtual unsigned int get_layer () const
virtual int get_scint_id () const
virtual int get_row () const
virtual int get_strip_z_index () const
virtual int get_strip_y_index () const
virtual int get_ladder_z_index () const
virtual int get_ladder_phi_index () const
virtual int get_index_i () const
virtual int get_index_j () const
virtual int get_index_k () const
virtual int get_index_l () const
virtual int get_hit_type () const
virtual void set_px (const int i, const float f)
virtual void set_py (const int i, const float f)
virtual void set_pz (const int i, const float f)
virtual void set_local_x (const int i, const float f)
virtual void set_local_y (const int i, const float f)
virtual void set_local_z (const int i, const float f)
virtual void set_eion (const float f)
virtual void set_light_yield (const float f)
virtual void set_path_length (const float f)
virtual void set_layer (const unsigned int i)
virtual void set_scint_id (const int i)
virtual void set_row (const int i)
virtual void set_strip_z_index (const int i)
virtual void set_strip_y_index (const int i)
virtual void set_ladder_z_index (const int i)
virtual void set_ladder_phi_index (const int i)
virtual void set_index_i (const int i)
virtual void set_index_j (const int i)
virtual void set_index_k (const int i)
virtual void set_index_l (const int i)
virtual void set_hit_type (const int i)
Public Member Functions inherited from PHG4Hit
PHG4Hit ()
virtual ~PHG4Hit ()
virtual void Copy (PHG4Hit const &g4hit)
virtual float get_avg_x () const
virtual float get_avg_y () const
virtual float get_avg_z () const
virtual float get_avg_t () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Types
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t, prop_storage_t > prop_map_t
Protected Member Functions
unsigned int get_property_nocheck (const PROPERTY prop_id) const
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui)
Protected Attributes
float x [2]
float y [2]
float z [2]
float t [2]
PHG4HitDefs::keytype hitid
int trackid
int showerid
float edep
prop_map_t prop_map
container for additional property
Additional Inherited Members
Public Types inherited from PHG4Hit
enum PROPERTY {
prop_eion = 1, prop_light_yield = 2, prop_px_0 = 10, prop_px_1 = 11,
prop_py_0 = 12, prop_py_1 = 13, prop_pz_0 = 14, prop_pz_1 = 15,
prop_path_length = 16, prop_local_x_0 = 20, prop_local_x_1 = 21, prop_local_y_0 = 22,
prop_local_y_1 = 23, prop_local_z_0 = 24, prop_local_z_1 = 25, prop_layer = 101,
prop_scint_id = 102, prop_row = 103, prop_strip_z_index = 110, prop_strip_y_index = 111,
prop_ladder_z_index = 112, prop_ladder_phi_index = 113, prop_stave_index = 114, prop_half_stave_index = 115,
prop_module_index = 116, prop_chip_index = 117, prop_local_pos_x_0 = 118, prop_local_pos_y_0 = 119,
prop_local_pos_z_0 = 120, prop_index_i = 121, prop_index_j = 122, prop_index_k = 123,
prop_index_l = 124, prop_hit_type = 125, prop_local_pos_x_1 = 128, prop_local_pos_y_1 = 126,
prop_local_pos_z_1 = 127, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
Static Public Member Functions inherited from PHG4Hit
static std::pair< const std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 15 of file PHG4Hitv1.h.
Member Typedef Documentation
prop_id_t
typedef uint8_t PHG4Hitv1::prop_id_t protected
storage types for additional property
Definition at line 113 of file PHG4Hitv1.h.
prop_map_t
typedef std::map<prop_id_t, prop_storage_t> PHG4Hitv1::prop_map_t protected
Definition at line 115 of file PHG4Hitv1.h.
prop_storage_t
typedef uint32_t PHG4Hitv1::prop_storage_t protected
Definition at line 114 of file PHG4Hitv1.h.
Constructor & Destructor Documentation
PHG4Hitv1() [1/2]
PHG4Hitv1::PHG4Hitv1 ()
PHG4Hitv1() [2/2]
PHG4Hitv1::PHG4Hitv1 (const PHG4Hit & g4hit) explicit
Definition at line 27 of file PHG4Hitv1.cc.
References PHG4Hit::Copy().
~PHG4Hitv1()
virtual PHG4Hitv1::~PHG4Hitv1 () inline virtual
Definition at line 20 of file PHG4Hitv1.h.
References identify(), and Reset().
Member Function Documentation
get_detid()
int PHG4Hitv1::get_detid () const virtual
Reimplemented from PHG4Hit.
Definition at line 49 of file PHG4Hitv1.cc.
References PHG4HitDefs::hit_idbits, and hitid.
Referenced by get_hit_id().
get_edep()
float PHG4Hitv1::get_edep () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 29 of file PHG4Hitv1.h.
References edep.
get_eion()
virtual float PHG4Hitv1::get_eion () const inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 60 of file PHG4Hitv1.h.
References get_property_float(), and PHG4Hit::prop_eion.
Referenced by PHG4HitEval::Copy().
get_hit_id()
PHG4HitDefs::keytype PHG4Hitv1::get_hit_id () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 30 of file PHG4Hitv1.h.
References get_detid(), and hitid.
get_hit_type()
virtual int PHG4Hitv1::get_hit_type () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 74 of file PHG4Hitv1.h.
References get_property_int(), PHG4Hit::prop_hit_type, set_local_x(), set_local_y(), set_local_z(), set_px(), set_py(), and set_pz().
get_index_i()
virtual int PHG4Hitv1::get_index_i () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 70 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_index_i.
get_index_j()
virtual int PHG4Hitv1::get_index_j () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 71 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_index_j.
get_index_k()
virtual int PHG4Hitv1::get_index_k () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 72 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_index_k.
get_index_l()
virtual int PHG4Hitv1::get_index_l () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 73 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_index_l.
get_ladder_phi_index()
virtual int PHG4Hitv1::get_ladder_phi_index () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 69 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_ladder_phi_index.
get_ladder_z_index()
virtual int PHG4Hitv1::get_ladder_z_index () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 68 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_ladder_z_index.
get_layer()
virtual unsigned int PHG4Hitv1::get_layer () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 63 of file PHG4Hitv1.h.
References get_property_uint(), and PHG4Hit::prop_layer.
get_light_yield()
virtual float PHG4Hitv1::get_light_yield () const inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 61 of file PHG4Hitv1.h.
References get_property_float(), and PHG4Hit::prop_light_yield.
Referenced by PHG4HitEval::Copy().
get_local_x()
float PHG4Hitv1::get_local_x (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 299 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_local_x_0, and PHG4Hit::prop_local_x_1.
Referenced by set_trkid().
get_local_y()
float PHG4Hitv1::get_local_y (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 314 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_local_y_0, and PHG4Hit::prop_local_y_1.
Referenced by set_trkid().
get_local_z()
float PHG4Hitv1::get_local_z (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 329 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_local_z_0, and PHG4Hit::prop_local_z_1.
Referenced by set_trkid().
get_path_length()
virtual float PHG4Hitv1::get_path_length () const inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 62 of file PHG4Hitv1.h.
References get_property_float(), and PHG4Hit::prop_path_length.
Referenced by PHG4HitEval::Copy().
get_property_float()
float PHG4Hitv1::get_property_float (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Hit.
Definition at line 95 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hitv1::u_property::fdata, PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), PHWHERE, prop_map, and PHG4Hit::type_float.
Referenced by get_eion(), get_light_yield(), get_local_x(), get_local_y(), get_local_z(), get_path_length(), get_px(), get_py(), get_pz(), identify(), print(), and set_trkid().
get_property_int()
int PHG4Hitv1::get_property_int (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Hit.
Definition at line 113 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), PHG4Hitv1::u_property::idata, PHWHERE, prop_map, and PHG4Hit::type_int.
Referenced by get_hit_type(), get_index_i(), get_index_j(), get_index_k(), get_index_l(), get_ladder_phi_index(), get_ladder_z_index(), get_row(), get_scint_id(), get_strip_y_index(), get_strip_z_index(), identify(), print(), and set_trkid().
get_property_nocheck()
unsigned int PHG4Hitv1::get_property_nocheck (const PROPERTY prop_id) const protected virtual
Reimplemented from PHG4Hit.
Definition at line 191 of file PHG4Hitv1.cc.
References prop_map.
Referenced by set_hit_type().
get_property_uint()
unsigned int PHG4Hitv1::get_property_uint (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Hit.
Definition at line 131 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), PHWHERE, prop_map, PHG4Hit::type_uint, and PHG4Hitv1::u_property::uidata.
Referenced by get_layer(), identify(), print(), and set_trkid().
get_px()
float PHG4Hitv1::get_px (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 202 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_px_0, and PHG4Hit::prop_px_1.
Referenced by set_trkid().
get_py()
float PHG4Hitv1::get_py (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 217 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_py_0, and PHG4Hit::prop_py_1.
Referenced by set_trkid().
get_pz()
float PHG4Hitv1::get_pz (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 232 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_pz_0, and PHG4Hit::prop_pz_1.
Referenced by set_trkid().
get_row()
virtual int PHG4Hitv1::get_row () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 65 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_row.
get_scint_id()
virtual int PHG4Hitv1::get_scint_id () const inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 64 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_scint_id.
Referenced by PHG4HitEval::Copy().
get_shower_id()
int PHG4Hitv1::get_shower_id () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 32 of file PHG4Hitv1.h.
References showerid.
get_strip_y_index()
virtual int PHG4Hitv1::get_strip_y_index () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 67 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_strip_y_index.
get_strip_z_index()
virtual int PHG4Hitv1::get_strip_z_index () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 66 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_strip_z_index.
get_t()
float PHG4Hitv1::get_t (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 28 of file PHG4Hitv1.h.
References t.
Referenced by identify().
get_trkid()
int PHG4Hitv1::get_trkid () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 33 of file PHG4Hitv1.h.
References trackid.
get_x()
float PHG4Hitv1::get_x (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 25 of file PHG4Hitv1.h.
References x.
Referenced by identify().
get_y()
float PHG4Hitv1::get_y (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 26 of file PHG4Hitv1.h.
References y.
Referenced by identify().
get_z()
float PHG4Hitv1::get_z (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 27 of file PHG4Hitv1.h.
References z.
Referenced by identify().
has_property()
bool PHG4Hitv1::has_property (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Hit.
Definition at line 88 of file PHG4Hitv1.cc.
References prop_map.
Referenced by set_trkid().
identify()
void PHG4Hitv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4Hit.
Definition at line 395 of file PHG4Hitv1.cc.
References edep, get_property_float(), PHG4Hit::get_property_info(), get_property_int(), get_property_uint(), get_t(), get_x(), get_y(), get_z(), hitid, prop_map, showerid, trackid, PHG4Hit::type_float, PHG4Hit::type_int, and PHG4Hit::type_uint.
Referenced by ~PHG4Hitv1().
print()
void PHG4Hitv1::print () const virtual
Reimplemented from PHG4Hit.
Definition at line 58 of file PHG4Hitv1.cc.
References edep, get_property_float(), PHG4Hit::get_property_info(), get_property_int(), get_property_uint(), hitid, prop_map, t, trackid, PHG4Hit::type_float, PHG4Hit::type_int, PHG4Hit::type_uint, x, y, and z.
Referenced by set_trkid().
Reset()
void PHG4Hitv1::Reset () virtual
Clear Event.
Reimplemented from PHG4Hit.
Definition at line 33 of file PHG4Hitv1.cc.
References edep, hitid, prop_map, set_t(), set_x(), set_y(), set_z(), and trackid.
Referenced by ~PHG4Hitv1().
set_edep()
void PHG4Hitv1::set_edep (const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 39 of file PHG4Hitv1.h.
References edep.
set_eion()
virtual void PHG4Hitv1::set_eion (const float f) inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 82 of file PHG4Hitv1.h.
References PHG4Hit::prop_eion, and set_property().
set_hit_id()
void PHG4Hitv1::set_hit_id (const PHG4HitDefs::keytype i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 40 of file PHG4Hitv1.h.
References hitid.
set_hit_type()
virtual void PHG4Hitv1::set_hit_type (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 96 of file PHG4Hitv1.h.
References get_property_nocheck(), PHG4Hit::prop_hit_type, and set_property().
set_index_i()
virtual void PHG4Hitv1::set_index_i (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 92 of file PHG4Hitv1.h.
References PHG4Hit::prop_index_i, and set_property().
set_index_j()
virtual void PHG4Hitv1::set_index_j (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 93 of file PHG4Hitv1.h.
References PHG4Hit::prop_index_j, and set_property().
set_index_k()
virtual void PHG4Hitv1::set_index_k (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 94 of file PHG4Hitv1.h.
References PHG4Hit::prop_index_k, and set_property().
set_index_l()
virtual void PHG4Hitv1::set_index_l (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 95 of file PHG4Hitv1.h.
References PHG4Hit::prop_index_l, and set_property().
set_ladder_phi_index()
virtual void PHG4Hitv1::set_ladder_phi_index (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 91 of file PHG4Hitv1.h.
References PHG4Hit::prop_ladder_phi_index, and set_property().
set_ladder_z_index()
virtual void PHG4Hitv1::set_ladder_z_index (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 90 of file PHG4Hitv1.h.
References PHG4Hit::prop_ladder_z_index, and set_property().
set_layer()
virtual void PHG4Hitv1::set_layer (const unsigned int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 85 of file PHG4Hitv1.h.
References PHG4Hit::prop_layer, and set_property().
set_light_yield()
virtual void PHG4Hitv1::set_light_yield (const float f) inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 83 of file PHG4Hitv1.h.
References PHG4Hit::prop_light_yield, and set_property().
set_local_x()
void PHG4Hitv1::set_local_x (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 344 of file PHG4Hitv1.cc.
References PHG4Hit::prop_local_x_0, PHG4Hit::prop_local_x_1, and set_property().
Referenced by get_hit_type().
set_local_y()
void PHG4Hitv1::set_local_y (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 361 of file PHG4Hitv1.cc.
References PHG4Hit::prop_local_y_0, PHG4Hit::prop_local_y_1, and set_property().
Referenced by get_hit_type().
set_local_z()
void PHG4Hitv1::set_local_z (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 378 of file PHG4Hitv1.cc.
References PHG4Hit::prop_local_z_0, PHG4Hit::prop_local_z_1, and set_property().
Referenced by get_hit_type().
set_path_length()
virtual void PHG4Hitv1::set_path_length (const float f) inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 84 of file PHG4Hitv1.h.
References PHG4Hit::prop_path_length, and set_property().
set_property() [1/3]
void PHG4Hitv1::set_property (const PROPERTY prop_id, const float value) virtual
Reimplemented from PHG4Hit.
Definition at line 149 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), PHG4Hitv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Hit::type_float.
Referenced by set_eion(), set_hit_type(), set_index_i(), set_index_j(), set_index_k(), set_index_l(), set_ladder_phi_index(), set_ladder_z_index(), set_layer(), set_light_yield(), set_local_x(), set_local_y(), set_local_z(), set_path_length(), set_px(), set_py(), set_pz(), set_row(), set_scint_id(), set_strip_y_index(), set_strip_z_index(), and set_trkid().
set_property() [2/3]
void PHG4Hitv1::set_property (const PROPERTY prop_id, const int value) virtual
Reimplemented from PHG4Hit.
Definition at line 163 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), PHG4Hitv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Hit::type_int.
set_property() [3/3]
void PHG4Hitv1::set_property (const PROPERTY prop_id, const unsigned int value) virtual
Reimplemented from PHG4Hit.
Definition at line 177 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), PHG4Hitv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Hit::type_uint.
set_property_nocheck()
void PHG4Hitv1::set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) inline protected virtual
Reimplemented from PHG4Hit.
Definition at line 100 of file PHG4Hitv1.h.
References prop_map.
set_px()
void PHG4Hitv1::set_px (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 247 of file PHG4Hitv1.cc.
References PHG4Hit::prop_px_0, PHG4Hit::prop_px_1, and set_property().
Referenced by get_hit_type().
set_py()
void PHG4Hitv1::set_py (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 264 of file PHG4Hitv1.cc.
References PHG4Hit::prop_py_0, PHG4Hit::prop_py_1, and set_property().
Referenced by get_hit_type().
set_pz()
void PHG4Hitv1::set_pz (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 281 of file PHG4Hitv1.cc.
References PHG4Hit::prop_pz_0, PHG4Hit::prop_pz_1, and set_property().
Referenced by get_hit_type().
set_row()
virtual void PHG4Hitv1::set_row (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 87 of file PHG4Hitv1.h.
References PHG4Hit::prop_row, and set_property().
set_scint_id()
virtual void PHG4Hitv1::set_scint_id (const int i) inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 86 of file PHG4Hitv1.h.
References PHG4Hit::prop_scint_id, and set_property().
set_shower_id()
void PHG4Hitv1::set_shower_id (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 41 of file PHG4Hitv1.h.
References showerid.
set_strip_y_index()
virtual void PHG4Hitv1::set_strip_y_index (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 89 of file PHG4Hitv1.h.
References PHG4Hit::prop_strip_y_index, and set_property().
set_strip_z_index()
virtual void PHG4Hitv1::set_strip_z_index (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 88 of file PHG4Hitv1.h.
References PHG4Hit::prop_strip_z_index, and set_property().
set_t()
void PHG4Hitv1::set_t (const int i, const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 38 of file PHG4Hitv1.h.
References t.
Referenced by Reset().
set_trkid()
void PHG4Hitv1::set_trkid (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 42 of file PHG4Hitv1.h.
References get_local_x(), get_local_y(), get_local_z(), get_property_float(), get_property_int(), get_property_uint(), get_px(), get_py(), get_pz(), has_property(), print(), set_property(), and trackid.
set_x()
void PHG4Hitv1::set_x (const int i, const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 35 of file PHG4Hitv1.h.
References x.
Referenced by Reset().
set_y()
void PHG4Hitv1::set_y (const int i, const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 36 of file PHG4Hitv1.h.
References y.
Referenced by Reset().
set_z()
void PHG4Hitv1::set_z (const int i, const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 37 of file PHG4Hitv1.h.
References z.
Referenced by Reset().
Member Data Documentation
edep
float PHG4Hitv1::edep protected
Definition at line 110 of file PHG4Hitv1.h.
Referenced by get_edep(), identify(), print(), Reset(), and set_edep().
hitid
PHG4HitDefs::keytype PHG4Hitv1::hitid protected
Definition at line 107 of file PHG4Hitv1.h.
Referenced by get_detid(), get_hit_id(), identify(), print(), Reset(), and set_hit_id().
prop_map
prop_map_t PHG4Hitv1::prop_map protected
container for additional property
Definition at line 132 of file PHG4Hitv1.h.
Referenced by get_property_float(), get_property_int(), get_property_nocheck(), get_property_uint(), has_property(), identify(), print(), Reset(), set_property(), and set_property_nocheck().
showerid
int PHG4Hitv1::showerid protected
Definition at line 109 of file PHG4Hitv1.h.
Referenced by get_shower_id(), identify(), and set_shower_id().
t
float PHG4Hitv1::t[2] protected
Definition at line 106 of file PHG4Hitv1.h.
Referenced by get_t(), print(), and set_t().
trackid
int PHG4Hitv1::trackid protected
Definition at line 108 of file PHG4Hitv1.h.
Referenced by get_trkid(), identify(), print(), Reset(), and set_trkid().
x
float PHG4Hitv1::x[2] protected
Definition at line 103 of file PHG4Hitv1.h.
Referenced by get_x(), print(), and set_x().
y
float PHG4Hitv1::y[2] protected
Definition at line 104 of file PHG4Hitv1.h.
Referenced by get_y(), print(), and set_y().
z
float PHG4Hitv1::z[2] protected
Definition at line 105 of file PHG4Hitv1.h.
Referenced by get_z(), print(), and set_z().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4Hitv1.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4Hitv1.cc