Class Reference for E1039 Core & Analysis Software: PHG4BlockGeom Class Reference
PHG4BlockGeom Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockGeom.h>
Public Member Functions
virtual ~PHG4BlockGeom ()
virtual void identify (std::ostream &os=std::cout) const
virtual int get_layer () const
virtual double get_size_x () const
virtual double get_size_y () const
virtual double get_size_z () const
virtual double get_center_x () const
virtual double get_center_y () const
virtual double get_center_z () const
virtual double get_z_rot () const
virtual double get_width () const
virtual double get_length () const
virtual double get_thickness () const
virtual double get_rot_matrix (const int, const int) const
virtual void set_layer (const int i)
virtual void set_size (const double sizex, const double sizey, const double sizez)
virtual void set_place (const double placex, const double placey, const double placez)
virtual void set_z_rot (const double z)
virtual void convert_local_to_global (const double, const double, const double, double &, double &, double &) const
virtual void convert_global_to_local (const double, const double, const double, double &, double &, double &) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
PHG4BlockGeom ()
Detailed Description
Definition at line 9 of file PHG4BlockGeom.h.
Constructor & Destructor Documentation
~PHG4BlockGeom()
virtual PHG4BlockGeom::~PHG4BlockGeom () inline virtual
Definition at line 13 of file PHG4BlockGeom.h.
PHG4BlockGeom()
PHG4BlockGeom::PHG4BlockGeom () inline protected
Definition at line 47 of file PHG4BlockGeom.h.
Member Function Documentation
convert_global_to_local()
virtual void PHG4BlockGeom::convert_global_to_local (const double , const double , const double , double & , double & , double &) const inline virtual
Definition at line 42 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
convert_local_to_global()
virtual void PHG4BlockGeom::convert_local_to_global (const double , const double , const double , double & , double & , double &) const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 39 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
get_center_x()
virtual double PHG4BlockGeom::get_center_x () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 21 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4BlockCellReco::InitRun().
get_center_y()
virtual double PHG4BlockGeom::get_center_y () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 22 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4BlockCellReco::InitRun().
get_center_z()
virtual double PHG4BlockGeom::get_center_z () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 23 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4BlockCellReco::InitRun().
get_layer()
virtual int PHG4BlockGeom::get_layer () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 17 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4BlockGeomContainer::AddLayerGeom(), and PHG4BlockCellReco::InitRun().
get_length()
virtual double PHG4BlockGeom::get_length () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 27 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
get_rot_matrix()
virtual double PHG4BlockGeom::get_rot_matrix (const int , const int) const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 30 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
get_size_x()
virtual double PHG4BlockGeom::get_size_x () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 18 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4BlockCellReco::InitRun().
get_size_y()
virtual double PHG4BlockGeom::get_size_y () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 19 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4BlockCellReco::InitRun().
get_size_z()
virtual double PHG4BlockGeom::get_size_z () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 20 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4BlockCellReco::InitRun().
get_thickness()
virtual double PHG4BlockGeom::get_thickness () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 28 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
get_width()
virtual double PHG4BlockGeom::get_width () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 26 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4BlockCellReco::InitRun().
get_z_rot()
virtual double PHG4BlockGeom::get_z_rot () const inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 24 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
identify()
void PHG4BlockGeom::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4BlockGeomv1.
Definition at line 7 of file PHG4BlockGeom.cc.
set_layer()
virtual void PHG4BlockGeom::set_layer (const int i) inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 32 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4BlockGeomContainer::AddLayerGeom().
set_place()
virtual void PHG4BlockGeom::set_place (const double placex, const double placey, const double placez) inline virtual
Definition at line 35 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
set_size()
virtual void PHG4BlockGeom::set_size (const double sizex, const double sizey, const double sizez) inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 33 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
set_z_rot()
virtual void PHG4BlockGeom::set_z_rot (const double z) inline virtual
Reimplemented in PHG4BlockGeomv1.
Definition at line 37 of file PHG4BlockGeom.h.
References PHOOL_VIRTUAL_WARN.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockGeom.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockGeom.cc