Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/EventDisplaySim/EventDisplay4Sim.C File Reference
EventDisplay4Sim.C File Reference
#include "G4_InsensitiveVolumes.C"
#include "G4_SensitiveDetectors.C"
#include "G4_Beamline.C"
#include "G4_Target.C"
Functions
int EventDisplay4Sim (const int nevent=10)
Variables
Fun4AllServer * se
EvtFilter * evt_filter
TGLViewer * view
TGNumberEntry * ne_evt_id
TGNumberEntry * ne_trig
Function Documentation
int EventDisplay4Sim (const int nevent = 10)
Definition at line 76 of file EventDisplay4Sim.C.
References PHG4SimpleEventGenerator::add_particles(), PHPy8ParticleTrigger::AddParticles(), SQPrimaryParticleGen::enableDrellYanGen(), SQPrimaryParticleGen::enableJPsiGen(), SQPrimaryParticleGen::enablePsipGen(), SQPrimaryParticleGen::enablePythia(), evt_filter, Fun4AllHepMCInputManager::fileopen(), PHG4Reco::InitRun(), PHEventDisplay::InitRun(), HepMCNodeReader::insert_particle_filter_pid(), recoConsts::instance(), Fun4AllServer::instance(), GeomSvc::instance(), ne_evt_id, ne_trig, recoConsts::Print(), PHFieldConfig::RegionalConst, PHPythia8::register_trigger(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), se, PHPythia8::set_config_file(), PHFlag::set_DoubleFlag(), PHPythia8::set_embedding_id(), PHG4Reco::set_field_map(), SQPrimaryParticleGen::set_massRange(), PHG4ParticleGeneratorBase::set_mom(), PHG4ParticleGeneratorBase::set_name(), HepMCNodeReader::set_particle_filter_on(), PHG4SimpleEventGenerator::set_pxpypz_range(), DPTriggerAnalyzer::set_road_set_file_name(), PHPythia8::set_trigger_AND(), PHEventDisplay::set_verbosity(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), Fun4AllHepMCInputManager::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHPythia8::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), PHG4ParticleGeneratorBase::set_vtx(), SQPrimaryParticleGen::set_xfRange(), PHG4Reco::SetPhysicsList(), PHPy8ParticleTrigger::SetPzHighLow(), SetupBeamline(), SetupInsensitiveVolumes(), SetupSensitiveDetectors(), SetupTarget(), PHG4Reco::SetWorldMaterial(), PHG4Reco::SetWorldShape(), PHG4Reco::SetWorldSizeX(), PHG4Reco::SetWorldSizeY(), PHG4Reco::SetWorldSizeZ(), Fun4AllServer::topNode(), PHG4SimpleEventGenerator::Uniform, GeomSvc::UseDbSvc(), Fun4AllBase::Verbosity(), and view.
Variable Documentation
EvtFilter* evt_filter
Definition at line 22 of file EventDisplay4Sim.C.
Referenced by EventDisplay4Sim(), Fun4CODA(), and Fun4DST().
TGNumberEntry* ne_evt_id
Definition at line 24 of file EventDisplay4Sim.C.
Referenced by EventDisplay4Sim().
TGNumberEntry* ne_trig
Definition at line 25 of file EventDisplay4Sim.C.
Referenced by EventDisplay4Sim().
Fun4AllServer* se
Definition at line 21 of file EventDisplay4Sim.C.
Referenced by Fun4AllSyncManager::CurrentEvent(), DisplayOn(), PHG4GDMLUtility::Dump_GDML(), Fun4AllSRawEventInputManager::enable_E1039_translation(), EventDisplay4Sim(), Fun4AllDstInputManager::fileopen(), Fun4All(), Fun4All_ExportGeom(), Fun4All_G4_BNL(), Fun4All_G4_BNL_R1(), Fun4All_G4_E1039(), Fun4All_G4_E1039_R1(), Fun4All_G4_E1039_R2(), Fun4All_G4_E1039_R2_V2(), Fun4All_ImportGeom(), Fun4All_Test(), Fun4AllEVIOInputManager::Fun4AllEVIOInputManager(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), Fun4AllOscarInputManager::Fun4AllOscarInputManager(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), Fun4AllReco(), Fun4AllSRawEventInputManager::Fun4AllSRawEventInputManager(), Fun4CODA(), Fun4DQ(), Fun4DST(), Fun4DumpGeom(), Fun4E1039Shielding(), Fun4EMCal(), Fun4HodoAccGap(), Fun4MainDaq(), Fun4MainDaqE906(), Fun4MultiRealDst(), Fun4PatternDB(), Fun4Pythia8Demo(), Fun4Sim(), Fun4Sim_pileup(), Fun4Sim_TrkQA(), Fun4SimDst(), Fun4SimMicroDst(), Fun4SRawEvent(), Fun4TrkDev(), OnlMonServer::FuncServer(), get_gun(), PHG4CylinderCellTPCReco::Init(), InitInput(), int_run(), matscan(), EventDispUI::MoveEvent(), EventDispUI::NextEvent(), PHEveDisplay::PHEveDisplay(), PHGeom_DSTInspection(), EventDispUI::PrevEvent(), RecoE1039Data(), RecoE1039Sim(), RecoE906Data(), Fun4AllInputManager::registerSubsystem(), Fun4AllServer::registerSubsystem(), Fun4AllInputManager::RejectEvent(), run(), splitDST(), TestOnlMonServer(), Fun4AllDstOutputManager::Write(), Fun4AllEventOutputManager::Write(), and Fun4AllFileOutStream::WriteEventOut().
TGLViewer* view
Definition at line 23 of file EventDisplay4Sim.C.
Referenced by EventDisplay4Sim().