Class Reference for E1039 Core & Analysis Software: E906SpillSelector Class Reference
E906SpillSelector Class Reference
A SubsysReco module to select good E906 spills.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/evt_filter/E906SpillSelector.h>
Public Member Functions
E906SpillSelector (const std::string &name="E906SpillSelector")
virtual ~E906SpillSelector ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetSpillListFile (const std::string fn_list)
void EnableOutput (const std::string fn_out="e906_spill_selector.tsv")
E906SpillSelector (const std::string &name="E906SpillSelector")
virtual ~E906SpillSelector ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetSpillListFile (const std::string fn_list)
void EnableOutput (const std::string fn_out="e906_spill_selector.tsv")
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
A SubsysReco module to select good E906 spills.
It can handle only the last E906 dataset, Run 6.
It outputs the counts of all and accepted events into a tsv file once EnableOutput() is called.
Typical usage:
E906SpillSelector* e906ss = new E906SpillSelector();
e906ss->EnableOutput();
se->registerSubsystem(e906ss);
It outputs the counts of all and accepted events into a tsv file once EnableOutput() is called.
Typical usage:
E906SpillSelector* e906ss = new E906SpillSelector();
e906ss->EnableOutput();
se->registerSubsystem(e906ss);
Definition at line 21 of file E906SpillSelector.h.
Constructor & Destructor Documentation
E906SpillSelector() [1/2]
E906SpillSelector::E906SpillSelector (const std::string & name = "E906SpillSelector")
Definition at line 11 of file E906SpillSelector.cxx.
~E906SpillSelector() [1/2]
E906SpillSelector::~E906SpillSelector () virtual
Definition at line 21 of file E906SpillSelector.cxx.
E906SpillSelector() [2/2]
E906SpillSelector::E906SpillSelector (const std::string & name = "E906SpillSelector")
~E906SpillSelector() [2/2]
virtual E906SpillSelector::~E906SpillSelector () virtual
Member Function Documentation
EnableOutput() [1/2]
void E906SpillSelector::EnableOutput (const std::string fn_out = "e906_spill_selector.tsv") inline
Definition at line 35 of file E906SpillSelector.h.
EnableOutput() [2/2]
void E906SpillSelector::EnableOutput (const std::string fn_out = "e906_spill_selector.tsv") inline
Definition at line 37 of file E906SpillSelector.h.
End() [1/2]
int E906SpillSelector::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
End() [2/2]
int E906SpillSelector::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 70 of file E906SpillSelector.cxx.
References Fun4AllReturnCodes::EVENT_OK.
Init() [1/2]
int E906SpillSelector::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Init() [2/2]
int E906SpillSelector::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 26 of file E906SpillSelector.cxx.
References Fun4AllReturnCodes::EVENT_OK, Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
InitRun() [1/2]
int E906SpillSelector::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
InitRun() [2/2]
int E906SpillSelector::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 47 of file E906SpillSelector.cxx.
References Fun4AllReturnCodes::ABORTEVENT, and Fun4AllReturnCodes::EVENT_OK.
process_event() [1/2]
int E906SpillSelector::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
process_event() [2/2]
int E906SpillSelector::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 61 of file E906SpillSelector.cxx.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and SQEvent::get_spill_id().
SetSpillListFile() [1/2]
void E906SpillSelector::SetSpillListFile (const std::string fn_list) inline
Definition at line 34 of file E906SpillSelector.h.
SetSpillListFile() [2/2]
void E906SpillSelector::SetSpillListFile (const std::string fn_list) inline
Definition at line 36 of file E906SpillSelector.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/evt_filter/E906SpillSelector.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/evt_filter/E906SpillSelector.cxx
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/E906SpillSelector.cc