Class Reference for E1039 Core & Analysis Software: HepMCNodeReader Class Reference
HepMCNodeReader Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/HepMCNodeReader.h>
Public Member Functions
HepMCNodeReader (const std::string &name="HEPMCREADER")
virtual ~HepMCNodeReader ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void Embed (const int i=1)
void VertexPosition (const double v_x, const double v_y, const double v_z)
void SmearVertex (const double s_x, const double s_y, const double s_z)
void SetT0 (const double t0)
void SetSeed (const unsigned int i)
Override seed.
void set_particle_filter_on (const bool a)
void insert_particle_filter_pid (const int a)
void enable_position_filter (const double x_min, const double x_max, const double y_min, const double y_max, const double z_min, const double z_max)
Enable and define a position filter. The x,y,z limits are in cm.
bool PassParticleFilter (HepMC::GenParticle *p)
void Set_bkg_mode ()
void Set_pxy2pz_rat (const double rat)
Sets the minimum Px(y)/Pz cut for inclusvie background generation.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
HepMCNodeReader take input from all subevents from PHHepMCGenEventMap and send them to simulation in Geant4 For HepMC subevent which is already simulated, they will not be simulated again in Geant4.
Definition at line 22 of file HepMCNodeReader.h.
Constructor & Destructor Documentation
HepMCNodeReader::HepMCNodeReader (const std::string & name = "HEPMCREADER")
Definition at line 54 of file HepMCNodeReader.cc.
HepMCNodeReader::~HepMCNodeReader () virtual
Definition at line 81 of file HepMCNodeReader.cc.
Member Function Documentation
void HepMCNodeReader::Embed (const int i = 1)
this function is depreciated. Embedding IDs are controlled for individually HEPMC subevents in Fun4AllHepMCInputManagers and event generators.
Definition at line 500 of file HepMCNodeReader.cc.
void HepMCNodeReader::enable_position_filter (const double x_min, const double x_max, const double y_min, const double y_max, const double z_min, const double z_max)
Enable and define a position filter. The x,y,z limits are in cm.
Definition at line 446 of file HepMCNodeReader.cc.
int HepMCNodeReader::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 86 of file HepMCNodeReader.cc.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and Fun4AllBase::Name().
void HepMCNodeReader::insert_particle_filter_pid (const int a) inline
Definition at line 58 of file HepMCNodeReader.h.
Referenced by EventDisplay4Sim(), Fun4DQ(), Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4PatternDB(), Fun4Sim(), Fun4TrkDev(), and RecoE1039Sim().
bool HepMCNodeReader::PassParticleFilter (HepMC::GenParticle * p)
Definition at line 457 of file HepMCNodeReader.cc.
Referenced by process_event().
int HepMCNodeReader::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Filter related to z-position of the decay
Dimemsion of FMAG: (43.2x160x503.) multiple slbas
pion interaction length for Fe
pion interaction length for Cu
pion interaction length of Target
pion interaction lenght of Shielding (concrete)
Filters for transverse momentum of decay muons
Fmag fucidual cut
Collimaator hole dimension (7.8 x 3.48 cm)
Collimator contribution
Shielding contribution
Dump contribution
Reimplemented from SubsysReco.
Definition at line 110 of file HepMCNodeReader.cc.
References Fun4AllReturnCodes::ABORTEVENT, PHG4InEvent::AddEmbeddedParticle(), PHG4InEvent::AddParticle(), PHG4InEvent::AddVtx(), Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, PHFlag::get_CharFlag(), PHHepMCGenEvent::get_collision_vertex(), PHHepMCGenEvent::get_embedding_id(), PHFlag::get_FloatFlag(), PHHepMCGenEvent::getEvent(), PHG4InEvent::identify(), PHHepMCGenEvent::identify(), recoConsts::instance(), PHHepMCGenEvent::is_simulated(), isfinal, PassParticleFilter(), PHWHERE, PHHepMCGenEventMap::rbegin(), PHHepMCGenEventMap::rend(), PHG4Particle::set_barcode(), PHG4Particle::set_pid(), PHG4Particle::set_px(), PHG4Particle::set_py(), PHG4Particle::set_pz(), Fun4AllBase::Verbosity(), and Fun4AllBase::verbosity.
void HepMCNodeReader::Set_bkg_mode () inline
added filter interface for bkg decay study Sets the inclusive background generation filters on
Definition at line 66 of file HepMCNodeReader.h.
void HepMCNodeReader::set_particle_filter_on (const bool a) inline
Definition at line 57 of file HepMCNodeReader.h.
Referenced by EventDisplay4Sim(), Fun4DQ(), Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4PatternDB(), Fun4Sim(), Fun4TrkDev(), and RecoE1039Sim().
void HepMCNodeReader::Set_pxy2pz_rat (const double rat) inline
Sets the minimum Px(y)/Pz cut for inclusvie background generation.
Definition at line 68 of file HepMCNodeReader.h.
void HepMCNodeReader::SetSeed (const unsigned int i) inline
Override seed.
Definition at line 51 of file HepMCNodeReader.h.
void HepMCNodeReader::SetT0 (const double t0) inline
Arbitary time shift for all sub-events. And the vertex shifts are better controlled for individually HEPMC subevents in Fun4AllHepMCInputManagers and event generators.
Definition at line 48 of file HepMCNodeReader.h.
void HepMCNodeReader::SmearVertex (const double s_x, const double s_y, const double s_z)
HepMCNodeReader::SmearVertex - WARNING - this function is depreciated. HepMCNodeReader::SmearVertex() smear each HEPMC subevents to a new vertex location. And the vertex smears are better controlled for individually HEPMC subevents in Fun4AllHepMCInputManagers and event generators. Positive value is Gauss smear, and negative values are flat smear
Definition at line 485 of file HepMCNodeReader.cc.
void HepMCNodeReader::VertexPosition (const double v_x, const double v_y, const double v_z)
this function is depreciated. HepMCNodeReader::VertexPosition() move all HEPMC subevents to a new vertex location. And the vertex shifts are better controlled for individually HEPMC subevents in Fun4AllHepMCInputManagers and event generators.
Definition at line 470 of file HepMCNodeReader.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/HepMCNodeReader.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/HepMCNodeReader.cc