Class Reference for E1039 Core & Analysis Software: PHFieldConfig_v2 Class Reference
PHFieldConfig_v2 Class Reference
PHFieldConfig_v2 implements field configuration information for uniform field model.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig_v2.h>
Public Member Functions
PHFieldConfig_v2 (double field_mag_x, double field_mag_y, double field_mag_z)
construct field configuration in units of Tesla
PHFieldConfig_v2 ()
default constructor for ROOT file IO
virtual ~PHFieldConfig_v2 ()
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
FieldConfigTypes get_field_config () const
double get_field_mag_x () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
void set_field_mag_x (double fieldMagX)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
double get_field_mag_y () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
void set_field_mag_y (double fieldMagY)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
double get_field_mag_z () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
void set_field_mag_z (double fieldMagZ)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Public Member Functions inherited from PHFieldConfig
virtual ~PHFieldConfig ()
std::string get_field_config_description () const
virtual void set_field_config (FieldConfigTypes fieldConfig)
virtual const std::string & get_filename () const
virtual void set_filename (const std::string &filename)
virtual double get_magfield_rescale () const
virtual void set_magfield_rescale (double magfieldRescale)
virtual const std::string & get_filename1 () const
field value in Tesla for target field model ONLY for PHFieldConfig_v3
virtual const std::string & get_filename2 () const
virtual double get_magfield_rescale1 () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
virtual double get_magfield_rescale2 () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v3
virtual void set_taregetmag_y (double fieldMagX)
field value in Tesla for target field model ONLY for PHFieldConfig_v3
virtual double get_taregetmag_y () const
field value in Tesla for target field model ONLY for PHFieldConfig_v3
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
double field_mag_x_
double field_mag_y_
double field_mag_z_
Additional Inherited Members
Public Types inherited from PHFieldConfig
enum FieldConfigTypes {
kFieldUniform = 0 , kField2D = 2 , kField3DCylindrical = 3 , kField3DCartesian = 1 ,
RegionalConst = 4 , kFieldSeaQuest = 5 , kFieldInvalid = 9999
}
Protected Member Functions inherited from PHFieldConfig
PHFieldConfig ()
pure virtual interface class. not for direct use
Static Protected Attributes inherited from PHFieldConfig
static const std::string kInvalid_FileName
Detailed Description
PHFieldConfig_v2 implements field configuration information for uniform field model.
Definition at line 19 of file PHFieldConfig_v2.h.
Constructor & Destructor Documentation
PHFieldConfig_v2() [1/2]
PHFieldConfig_v2::PHFieldConfig_v2 (double field_mag_x, double field_mag_y, double field_mag_z)
construct field configuration in units of Tesla
Definition at line 23 of file PHFieldConfig_v2.cc.
PHFieldConfig_v2() [2/2]
PHFieldConfig_v2::PHFieldConfig_v2 () inline
default constructor for ROOT file IO
Definition at line 31 of file PHFieldConfig_v2.h.
References PHFieldConfig_v2().
Referenced by clone(), and PHFieldConfig_v2().
~PHFieldConfig_v2()
PHFieldConfig_v2::~PHFieldConfig_v2 () virtual
Definition at line 33 of file PHFieldConfig_v2.cc.
Member Function Documentation
clone()
PHObject * PHFieldConfig_v2::clone () const virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 39 of file PHFieldConfig_v2.cc.
References PHFieldConfig_v2().
get_field_config()
FieldConfigTypes PHFieldConfig_v2::get_field_config () const inline virtual
Reimplemented from PHFieldConfig.
Definition at line 53 of file PHFieldConfig_v2.h.
References PHFieldConfig::kFieldUniform.
get_field_mag_x()
double PHFieldConfig_v2::get_field_mag_x () const inline virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented from PHFieldConfig.
Definition at line 59 of file PHFieldConfig_v2.h.
References field_mag_x_.
Referenced by identify().
get_field_mag_y()
double PHFieldConfig_v2::get_field_mag_y () const inline virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented from PHFieldConfig.
Definition at line 71 of file PHFieldConfig_v2.h.
References field_mag_y_.
Referenced by identify().
get_field_mag_z()
double PHFieldConfig_v2::get_field_mag_z () const inline virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented from PHFieldConfig.
Definition at line 83 of file PHFieldConfig_v2.h.
References field_mag_z_.
Referenced by identify().
identify()
void PHFieldConfig_v2::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHFieldConfig.
Definition at line 47 of file PHFieldConfig_v2.cc.
References PHFieldConfig::get_field_config_description(), get_field_mag_x(), get_field_mag_y(), get_field_mag_z(), and isValid().
isValid()
int PHFieldConfig_v2::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHFieldConfig.
Definition at line 69 of file PHFieldConfig_v2.cc.
Referenced by identify().
Reset()
void PHFieldConfig_v2::Reset () virtual
Clear Event.
Reimplemented from PHFieldConfig.
Definition at line 64 of file PHFieldConfig_v2.cc.
set_field_mag_x()
void PHFieldConfig_v2::set_field_mag_x (double fieldMagX) inline virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented from PHFieldConfig.
Definition at line 65 of file PHFieldConfig_v2.h.
References field_mag_x_.
set_field_mag_y()
void PHFieldConfig_v2::set_field_mag_y (double fieldMagY) inline virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented from PHFieldConfig.
Definition at line 77 of file PHFieldConfig_v2.h.
References field_mag_y_.
set_field_mag_z()
void PHFieldConfig_v2::set_field_mag_z (double fieldMagZ) inline virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented from PHFieldConfig.
Definition at line 89 of file PHFieldConfig_v2.h.
References field_mag_z_.
Member Data Documentation
field_mag_x_
double PHFieldConfig_v2::field_mag_x_ protected
Definition at line 96 of file PHFieldConfig_v2.h.
Referenced by get_field_mag_x(), and set_field_mag_x().
field_mag_y_
double PHFieldConfig_v2::field_mag_y_ protected
Definition at line 97 of file PHFieldConfig_v2.h.
Referenced by get_field_mag_y(), and set_field_mag_y().
field_mag_z_
double PHFieldConfig_v2::field_mag_z_ protected
Definition at line 98 of file PHFieldConfig_v2.h.
Referenced by get_field_mag_z(), and set_field_mag_z().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig_v2.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHField/PHFieldConfig_v2.cc