Class Reference for E1039 Core & Analysis Software: UtilBeam Namespace Reference
UtilBeam Namespace Reference
Functions
void ListOfRfValues (int &n_value, int *&list_values)
Make a list of QIE RF+nn values.
void ListOfRfValues (int &n_value, double *&list_values)
Make a list of QIE RF+nn values.
Function Documentation
ListOfRfValues() [1/2]
void UtilBeam::ListOfRfValues (int & n_value, double *& list_values)
Make a list of QIE RF+nn values.
This function uses an array of "double", instead of "int". It is suitable for the constructors of the TH1 classes.
int num_inte;
double* list_inte;
UtilBeam::ListOfRfValues(num_inte, list_inte);
TH1* h1_rf_inte = new TH1D("h1_rf_inte", "", num_inte - 1, list_inte);
Definition at line 48 of file UtilBeam.cc.
References ListOfRfValues().
ListOfRfValues() [2/2]
void UtilBeam::ListOfRfValues (int & n_value, int *& list_values)
Make a list of QIE RF+nn values.
The possible values for QIE RF+nn are not evenly distributed. This function just fills list_values with a list of all values. The values are taken from "float_2_linrom-2.xls" in DocDB 537.
Definition at line 10 of file UtilBeam.cc.
Referenced by AnaBG::Init(), OnlMonQie::InitRunOnlMon(), and ListOfRfValues().