Class Reference for E1039 Core & Analysis Software: PHParameters Class Reference
PHParameters Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/PHParameter/PHParameters.h>
Public Types
typedef std::map< const std::string, double > dMap
typedef dMap::const_iterator dIter
typedef std::vector< double > vdouble
typedef std::map< const std::string, vdouble > vdMap
typedef vdMap::const_iterator vdIter
typedef std::map< const std::string, int > iMap
typedef iMap::const_iterator iIter
typedef std::map< const std::string, std::string > strMap
typedef std::map< const std::string, std::string >::const_iterator strIter
Public Member Functions
PHParameters (const std::string &name)
PHParameters (const PHParameters &params, const std::string &name)
virtual ~PHParameters ()
void Print () const
size_t get_hash () const
hash of binary information for checking purpose
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
bool exist_int_param (const std::string &name) const
std::pair< std::map< const std::string, int >::const_iterator, std::map< const std::string, int >::const_iterator > get_all_int_params ()
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
bool exist_double_param (const std::string &name) const
std::pair< std::map< const std::string, double >::const_iterator, std::map< const std::string, double >::const_iterator > get_all_double_params ()
void set_vdouble_param (const std::string &name, const vdouble vdval)
vdouble get_vdouble_param (const std::string &name) const
bool exist_vdouble_param (const std::string &name) const
std::pair< std::map< const std::string, std::vector< double > >::const_iterator, std::map< const std::string, std::vector< double > >::const_iterator > get_all_vdouble_params ()
void set_string_param (const std::string &name, const std::string &str)
std::string get_string_param (const std::string &name) const
bool exist_string_param (const std::string &name) const
std::pair< std::map< const std::string, std::string >::const_iterator, std::map< const std::string, std::string >::const_iterator > get_all_string_params ()
void set_name (const std::string &name)
std::string Name () const
void FillFrom (const PdbParameterMap *saveparams)
void FillFrom (const PdbParameterMapContainer *saveparamcontainer, const int layer)
void FillFrom (const PHParameters *saveparams)
void SaveToNodeTree (PHCompositeNode *topNode, const std::string &nodename)
void SaveToNodeTree (PHCompositeNode *topNode, const std::string &nodename, const int layer)
int WriteToDB ()
int ReadFromDB ()
int ReadFromDB (const std::string &name, const int layer)
void CopyToPdbParameterMap (PdbParameterMap *myparm)
void printint () const
void printdouble () const
void printstring () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
unsigned int ConvertStringToUint (const std::string &str) const
Protected Attributes
PdbParameterMap * pdbparam
std::string detname
dMap doubleparams
vdMap vdoubleparams
iMap intparams
strMap stringparams
Detailed Description
Definition at line 17 of file PHParameters.h.
Member Typedef Documentation
dIter
typedef dMap::const_iterator PHParameters::dIter
Definition at line 22 of file PHParameters.h.
dMap
typedef std::map<const std::string, double> PHParameters::dMap
Definition at line 21 of file PHParameters.h.
iIter
typedef iMap::const_iterator PHParameters::iIter
Definition at line 27 of file PHParameters.h.
iMap
typedef std::map<const std::string, int> PHParameters::iMap
Definition at line 26 of file PHParameters.h.
strIter
typedef std::map<const std::string, std::string>::const_iterator PHParameters::strIter
Definition at line 29 of file PHParameters.h.
strMap
typedef std::map<const std::string, std::string> PHParameters::strMap
Definition at line 28 of file PHParameters.h.
vdIter
typedef vdMap::const_iterator PHParameters::vdIter
Definition at line 25 of file PHParameters.h.
vdMap
typedef std::map<const std::string, vdouble> PHParameters::vdMap
Definition at line 24 of file PHParameters.h.
vdouble
typedef std::vector<double> PHParameters::vdouble
Definition at line 23 of file PHParameters.h.
Constructor & Destructor Documentation
PHParameters() [1/2]
PHParameters::PHParameters (const std::string & name) inline explicit
Definition at line 31 of file PHParameters.h.
PHParameters() [2/2]
PHParameters::PHParameters (const PHParameters & params, const std::string & name)
Definition at line 47 of file PHParameters.cc.
~PHParameters()
virtual PHParameters::~PHParameters () inline virtual
Definition at line 34 of file PHParameters.h.
Member Function Documentation
ConvertStringToUint()
unsigned int PHParameters::ConvertStringToUint (const std::string & str) const protected
Definition at line 652 of file PHParameters.cc.
CopyToPdbParameterMap()
void PHParameters::CopyToPdbParameterMap (PdbParameterMap * myparm)
Definition at line 632 of file PHParameters.cc.
References PdbParameterMap::set_double_param(), PdbParameterMap::set_int_param(), and PdbParameterMap::set_string_param().
exist_double_param()
bool PHParameters::exist_double_param (const std::string & name) const
Definition at line 114 of file PHParameters.cc.
Referenced by PHG4CylinderGeomv1::ImportParameters(), PHParameterContainerInterface::set_default_double_param(), and PHParameterContainerInterface::set_double_param().
exist_int_param()
bool PHParameters::exist_int_param (const std::string & name) const
Definition at line 73 of file PHParameters.cc.
Referenced by PHG4CylinderGeomv1::ImportParameters(), PHG4CylinderGeomv2::ImportParameters(), PHParameterContainerInterface::set_default_int_param(), and PHParameterContainerInterface::set_int_param().
exist_string_param()
bool PHParameters::exist_string_param (const std::string & name) const
Definition at line 232 of file PHParameters.cc.
Referenced by PHParameterContainerInterface::set_default_string_param(), and PHParameterContainerInterface::set_string_param().
exist_vdouble_param()
bool PHParameters::exist_vdouble_param (const std::string & name) const
Definition at line 143 of file PHParameters.cc.
FillFrom() [1/3]
void PHParameters::FillFrom (const PdbParameterMap * saveparams)
Definition at line 254 of file PHParameters.cc.
References PdbParameterMap::get_cparam_iters(), PdbParameterMap::get_dparam_iters(), and PdbParameterMap::get_iparam_iters().
Referenced by PHParametersContainer::FillFrom(), and PHG4DetectorSubsystem::InitRun().
FillFrom() [2/3]
void PHParameters::FillFrom (const PdbParameterMapContainer * saveparamcontainer, const int layer)
Definition at line 287 of file PHParameters.cc.
References PdbParameterMap::get_cparam_iters(), PdbParameterMap::get_dparam_iters(), PdbParameterMap::get_iparam_iters(), and PdbParameterMapContainer::GetParameters().
FillFrom() [3/3]
void PHParameters::FillFrom (const PHParameters * saveparams)
Definition at line 325 of file PHParameters.cc.
References doubleparams, intparams, and stringparams.
get_all_double_params()
std::pair< std::map<const std::string, double>::const_iterator, std::map<const std::string, double>::const_iterator> PHParameters::get_all_double_params () inline
Definition at line 49 of file PHParameters.h.
References doubleparams.
Referenced by PHParameterContainerInterface::UpdateParametersWithMacro().
get_all_int_params()
std::pair<std::map<const std::string, int>::const_iterator, std::map<const std::string, int>::const_iterator> PHParameters::get_all_int_params () inline
Definition at line 44 of file PHParameters.h.
References intparams.
get_all_string_params()
std::pair< std::map<const std::string, std::string>::const_iterator, std::map<const std::string, std::string>::const_iterator> PHParameters::get_all_string_params () inline
Definition at line 60 of file PHParameters.h.
References stringparams.
get_all_vdouble_params()
std::pair< std::map<const std::string, std::vector<double> >::const_iterator, std::map<const std::string, std::vector<double> >::const_iterator> PHParameters::get_all_vdouble_params () inline
Definition at line 55 of file PHParameters.h.
References vdoubleparams.
get_double_param()
double PHParameters::get_double_param (const std::string & name) const
Definition at line 101 of file PHParameters.cc.
References PHWHERE.
Referenced by PHG4BlockDetector::Construct(), PHG4BNLTargetCoilDetector::Construct(), PHG4CollimatorDetector::Construct(), PHG4CylinderDetector::Construct(), PHG4EMCalDetector::Construct(), PHG4PolyconDetector::Construct(), PHG4SquareTubeDetector::Construct(), PHG4TargetCoilDetector::Construct(), PHG4TargetCoilV2Detector::Construct(), SQG4DipoleMagnetDetector::Construct(), PHParameterContainerInterface::get_double_param(), PHParameterInterface::get_double_param(), PHG4DetectorSubsystem::get_double_param(), PHG4CylinderGeomv1::ImportParameters(), PHG4BNLTargetCoilSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4PolyconSubsystem::InitRunSubsystem(), PHG4TargetCoilSubsystem::InitRunSubsystem(), PHG4TargetCoilV2Subsystem::InitRunSubsystem(), and PHParameterContainerInterface::set_default_double_param().
get_hash()
size_t PHParameters::get_hash () const
hash of binary information for checking purpose
Definition at line 164 of file PHParameters.cc.
get_int_param()
int PHParameters::get_int_param (const std::string & name) const
Definition at line 60 of file PHParameters.cc.
References PHWHERE.
Referenced by PHG4BlockDetector::Construct(), PHG4CylinderDetector::Construct(), PHG4PolyconDetector::Construct(), PHParameterContainerInterface::get_int_param(), PHParameterInterface::get_int_param(), PHG4DetectorSubsystem::get_int_param(), PHG4CylinderGeomv1::ImportParameters(), PHG4CylinderGeomv2::ImportParameters(), and PHParameterContainerInterface::set_default_int_param().
get_string_param()
string PHParameters::get_string_param (const std::string & name) const
Definition at line 219 of file PHParameters.cc.
References PHWHERE.
Referenced by PHG4BlockDetector::Construct(), PHG4CylinderDetector::Construct(), PHG4PolyconDetector::Construct(), PHG4SquareTubeDetector::Construct(), SQG4DipoleMagnetDetector::Construct(), PHParameterContainerInterface::get_string_param(), PHParameterInterface::get_string_param(), PHG4DetectorSubsystem::get_string_param(), and PHParameterContainerInterface::set_default_string_param().
get_vdouble_param()
PHParameters::vdouble PHParameters::get_vdouble_param (const std::string & name) const
Definition at line 130 of file PHParameters.cc.
References PHWHERE.
Referenced by PHG4PolyconDetector::Construct(), and PHG4DetectorSubsystem::get_vdouble_param().
Name()
std::string PHParameters::Name () const inline
Definition at line 63 of file PHParameters.h.
References detname.
Referenced by PHG4DetectorSubsystem::InitRun().
Print()
void PHParameters::Print () const
Definition at line 154 of file PHParameters.cc.
Referenced by PHG4BNLTargetCoilDetector::Construct(), PHG4CylinderDetector::Construct(), PHG4PolyconDetector::Construct(), PHG4TargetCoilDetector::Construct(), PHG4TargetCoilV2Detector::Construct(), PHG4BNLTargetCoilSubsystem::Print(), PHG4CylinderSubsystem::Print(), PHG4PolyconSubsystem::Print(), PHG4TargetCoilSubsystem::Print(), and PHG4TargetCoilV2Subsystem::Print().
printdouble()
void PHParameters::printdouble () const
Definition at line 201 of file PHParameters.cc.
Referenced by PHParameterContainerInterface::set_double_param().
printint()
void PHParameters::printint () const
Definition at line 83 of file PHParameters.cc.
Referenced by PHParameterContainerInterface::set_int_param().
printstring()
void PHParameters::printstring () const
Definition at line 242 of file PHParameters.cc.
Referenced by PHParameterContainerInterface::set_string_param().
ReadFromDB() [1/2]
int PHParameters::ReadFromDB ()
Definition at line 465 of file PHParameters.cc.
References PdbApplication::abort(), PdbBankManager::fetchBank(), PdbBankManager::getApplication(), PdbCalBank::getEntry(), PdbBankManager::instance(), PHWHERE, and PdbApplication::startRead().
Referenced by PHG4DetectorSubsystem::ReadParamsFromDB().
ReadFromDB() [2/2]
int PHParameters::ReadFromDB (const std::string & name, const int layer)
Definition at line 430 of file PHParameters.cc.
References PdbApplication::abort(), PdbBankManager::fetchBank(), PdbBankManager::getApplication(), PdbCalBank::getEntry(), PdbBankManager::instance(), PHWHERE, and PdbApplication::startRead().
SaveToNodeTree() [1/2]
void PHParameters::SaveToNodeTree (PHCompositeNode * topNode, const std::string & nodename)
Definition at line 345 of file PHParameters.cc.
References PHCompositeNode::addNode(), and PdbParameterMap::Reset().
Referenced by PHG4DetectorSubsystem::InitRun(), and PHParameterInterface::SaveToNodeTree().
SaveToNodeTree() [2/2]
void PHParameters::SaveToNodeTree (PHCompositeNode * topNode, const std::string & nodename, const int layer)
Definition at line 366 of file PHParameters.cc.
References PHCompositeNode::addNode(), PdbParameterMapContainer::AddPdbParameterMap(), PdbParameterMapContainer::GetParametersToModify(), and PdbParameterMap::Reset().
set_double_param()
void PHParameters::set_double_param (const std::string & name, const double dval)
Definition at line 95 of file PHParameters.cc.
Referenced by PHParameterInterface::InitializeParameters(), PHG4DetectorSubsystem::InitializeParameters(), PHG4BNLTargetCoilSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4PolyconSubsystem::InitRunSubsystem(), PHG4TargetCoilSubsystem::InitRunSubsystem(), PHG4TargetCoilV2Subsystem::InitRunSubsystem(), PHParameterContainerInterface::set_default_double_param(), PHParameterContainerInterface::set_double_param(), PHParameterContainerInterface::UpdateParametersWithMacro(), PHParameterInterface::UpdateParametersWithMacro(), and PHG4DetectorSubsystem::UpdateParametersWithMacro().
set_int_param()
void PHParameters::set_int_param (const std::string & name, const int ival)
Definition at line 54 of file PHParameters.cc.
Referenced by PHParameterInterface::InitializeParameters(), PHG4DetectorSubsystem::InitializeParameters(), PHParameterContainerInterface::set_default_int_param(), PHParameterContainerInterface::set_int_param(), PHParameterContainerInterface::UpdateParametersWithMacro(), PHParameterInterface::UpdateParametersWithMacro(), PHG4DetectorGroupSubsystem::UpdateParametersWithMacro(), and PHG4DetectorSubsystem::UpdateParametersWithMacro().
set_name()
void PHParameters::set_name (const std::string & name) inline
Definition at line 62 of file PHParameters.h.
References detname.
Referenced by PHG4DetectorSubsystem::Init(), and PHParameterInterface::set_paramname().
set_string_param()
void PHParameters::set_string_param (const std::string & name, const std::string & str)
Definition at line 213 of file PHParameters.cc.
Referenced by PHParameterInterface::InitializeParameters(), PHG4DetectorSubsystem::InitializeParameters(), PHParameterContainerInterface::set_default_string_param(), PHParameterContainerInterface::set_string_param(), PHParameterContainerInterface::UpdateParametersWithMacro(), PHParameterInterface::UpdateParametersWithMacro(), and PHG4DetectorSubsystem::UpdateParametersWithMacro().
set_vdouble_param()
void PHParameters::set_vdouble_param (const std::string & name, const vdouble vdval)
Definition at line 124 of file PHParameters.cc.
Referenced by PHG4DetectorSubsystem::InitializeParameters(), and PHG4DetectorSubsystem::UpdateParametersWithMacro().
WriteToDB()
int PHParameters::WriteToDB ()
Definition at line 392 of file PHParameters.cc.
References PdbApplication::abort(), PdbApplication::commit(), PdbBankManager::createBank(), PdbBankManager::getApplication(), PdbCalBank::getEntry(), PdbBankManager::instance(), PHWHERE, PdbCalBank::setLength(), and PdbApplication::startUpdate().
Referenced by PHG4DetectorSubsystem::SaveParamsToDB().
Member Data Documentation
detname
std::string PHParameters::detname protected
Definition at line 93 of file PHParameters.h.
Referenced by Name(), and set_name().
doubleparams
dMap PHParameters::doubleparams protected
Definition at line 94 of file PHParameters.h.
Referenced by FillFrom(), and get_all_double_params().
intparams
iMap PHParameters::intparams protected
Definition at line 96 of file PHParameters.h.
Referenced by FillFrom(), and get_all_int_params().
pdbparam
PdbParameterMap* PHParameters::pdbparam protected
Definition at line 92 of file PHParameters.h.
stringparams
strMap PHParameters::stringparams protected
Definition at line 97 of file PHParameters.h.
Referenced by FillFrom(), and get_all_string_params().
vdoubleparams
vdMap PHParameters::vdoubleparams protected
Definition at line 95 of file PHParameters.h.
Referenced by get_all_vdouble_params().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/PHParameter/PHParameters.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/PHParameter/PHParameters.cc