E1039 Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/SimChainDev/eve_disp_db.C File Reference
eve_disp_db.C File Reference
#include "Fun4DB.C"
Functions
void make_gui ()
void eve_disp_db ()
Variables
Fun4AllServer * se
TGLViewer * v
Function Documentation
void eve_disp_db ()
Definition at line 88 of file eve_disp_db.C.
References Fun4DB(), Fun4AllServer::getSubsysReco(), PHEventDisplay::InitRun(), PHG4Reco::InitRun(), Fun4AllServer::instance(), make_gui(), Fun4AllServer::topNode(), and v.
void make_gui ()
Definition at line 43 of file eve_disp_db.C.
Variable Documentation
Fun4AllServer* se
Definition at line 3 of file eve_disp_db.C.
TGLViewer* v
Definition at line 4 of file eve_disp_db.C.