Class Reference for E1039 Core & Analysis Software: SQGenFit::GFMeasurement Class Reference
SQGenFit::GFMeasurement Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/SQGenFit/GFMeasurement.h>
Public Member Functions
GFMeasurement (const SignedHit &rawHit, bool en=true)
GFMeasurement (const GFMeasurement &meas)
virtual ~GFMeasurement ()
virtual genfit::AbsMeasurement * clone () const override
void setTrackPtr (GFTrack *trackPtr)
void enableHitInFit (bool en=true)
SignedHit & getBeforeFitHit ()
void postFitUpdate ()
double getZ () const
bool isEnabled () const
void print (unsigned int debugLvl=0) const
Detailed Description
Definition at line 13 of file GFMeasurement.h.
Constructor & Destructor Documentation
GFMeasurement() [1/2]
SQGenFit::GFMeasurement::GFMeasurement (const SignedHit & rawHit, bool en = true)
Definition at line 21 of file GFMeasurement.cxx.
References Hit::detectorID, Hit::driftDistance, Hit::elementID, GeomSvc::getCellWidth(), GeomSvc::getEndPoints(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneResolution(), SignedHit::hit, Hit::index, and GeomSvc::instance().
Referenced by clone().
GFMeasurement() [2/2]
SQGenFit::GFMeasurement::GFMeasurement (const GFMeasurement & meas)
Definition at line 61 of file GFMeasurement.cxx.
~GFMeasurement()
virtual SQGenFit::GFMeasurement::~GFMeasurement () inline virtual
Definition at line 18 of file GFMeasurement.h.
Member Function Documentation
clone()
virtual genfit::AbsMeasurement* SQGenFit::GFMeasurement::clone () const inline override virtual
Definition at line 20 of file GFMeasurement.h.
References GFMeasurement().
enableHitInFit()
void SQGenFit::GFMeasurement::enableHitInFit (bool en = true) inline
Definition at line 24 of file GFMeasurement.h.
getBeforeFitHit()
SignedHit& SQGenFit::GFMeasurement::getBeforeFitHit () inline
Definition at line 25 of file GFMeasurement.h.
getZ()
double SQGenFit::GFMeasurement::getZ () const inline
Definition at line 28 of file GFMeasurement.h.
Referenced by SQGenFit::GFTrack::addMeasurement(), SQGenFit::GFTrack::getNearestMeasurementID(), and SQGenFit::GFMeasurementComp::operator()().
isEnabled()
bool SQGenFit::GFMeasurement::isEnabled () const inline
Definition at line 29 of file GFMeasurement.h.
postFitUpdate()
void SQGenFit::GFMeasurement::postFitUpdate ()
Definition at line 81 of file GFMeasurement.cxx.
print()
void SQGenFit::GFMeasurement::print (unsigned int debugLvl = 0) const
Definition at line 94 of file GFMeasurement.cxx.
References Hit::detectorID, Hit::driftDistance, Hit::elementID, GeomSvc::getInterceptionFast(), SignedHit::hit, Hit::index, GeomSvc::instance(), Hit::pos, and SignedHit::sign.
setTrackPtr()
void SQGenFit::GFMeasurement::setTrackPtr (GFTrack * trackPtr)
Definition at line 76 of file GFMeasurement.cxx.
Referenced by SQGenFit::GFTrack::addMeasurement().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/SQGenFit/GFMeasurement.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/SQGenFit/GFMeasurement.cxx