Class Reference for E1039 Core & Analysis Software: RoadInfo Class Reference
RoadInfo Class Reference
Class to hold one road.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadInfo.h>
Public Member Functions
RoadInfo (const int road_id=0)
RoadInfo (const RoadInfo &obj)
virtual ~RoadInfo ()
void SetRoadID (const int road_id)
int GetRoadID () const
void Add (const double weight, const int count=1)
void SetCount (const int count)
void SetWeight (const double weight)
int GetCount () const
double GetWeight () const
void Scale (const double val)
void AddBG (const double weight, const int count=1)
void SetCountBG (const int count)
void SetWeightBG (const double weight)
int GetCountBG () const
double GetWeightBG () const
void ScaleBG (const double val)
void SetOnOff (const bool on_off)
double GetOnOff () const
double GetFoM () const
Detailed Description
Class to hold one road.
Definition at line 8 of file RoadInfo.h.
Constructor & Destructor Documentation
RoadInfo() [1/2]
RoadInfo::RoadInfo (const int road_id = 0)
Definition at line 7 of file RoadInfo.cc.
RoadInfo() [2/2]
RoadInfo::RoadInfo (const RoadInfo & obj)
Definition at line 18 of file RoadInfo.cc.
~RoadInfo()
RoadInfo::~RoadInfo () virtual
Definition at line 38 of file RoadInfo.cc.
Member Function Documentation
Add()
void RoadInfo::Add (const double weight, const int count = 1)
Definition at line 43 of file RoadInfo.cc.
Referenced by RoadMap::Add().
AddBG()
void RoadInfo::AddBG (const double weight, const int count = 1)
Definition at line 54 of file RoadInfo.cc.
Referenced by RoadMap::AddBG().
GetCount()
int RoadInfo::GetCount () const inline
Definition at line 28 of file RoadInfo.h.
Referenced by RoadMap::Add(), UtilRoad::PrintList(), and UtilRoad::WriteToFile().
GetCountBG()
int RoadInfo::GetCountBG () const inline
Definition at line 35 of file RoadInfo.h.
Referenced by RoadMap::AddBG(), and UtilRoad::PrintList().
GetFoM()
double RoadInfo::GetFoM () const inline
Definition at line 42 of file RoadInfo.h.
Referenced by GenRoadset::DisableRoadsByFoM(), GenRoadset::GenerateSymmetricRoadSetByFoM(), and UtilRoad::PrintList().
GetOnOff()
double RoadInfo::GetOnOff () const inline
Definition at line 40 of file RoadInfo.h.
Referenced by GenRoadset::GenerateSymmetricRoadSetByFoM(), and UtilRoad::WriteToFile().
GetRoadID()
int RoadInfo::GetRoadID () const inline
Definition at line 23 of file RoadInfo.h.
Referenced by RoadMap::Add(), RoadMap::AddBG(), GenRoadset::GenerateSymmetricRoadSetByFoM(), UtilRoad::PrintList(), GenRoadset::SymmetrizeRoads(), and UtilRoad::WriteToFile().
GetWeight()
double RoadInfo::GetWeight () const inline
Definition at line 29 of file RoadInfo.h.
Referenced by RoadMap::Add(), GenRoadset::DisableRoadsByWeightFraction(), UtilRoad::PrintList(), and UtilRoad::WriteToFile().
GetWeightBG()
double RoadInfo::GetWeightBG () const inline
Definition at line 36 of file RoadInfo.h.
Referenced by RoadMap::AddBG(), and UtilRoad::PrintList().
Scale()
void RoadInfo::Scale (const double val)
Definition at line 49 of file RoadInfo.cc.
ScaleBG()
void RoadInfo::ScaleBG (const double val)
Definition at line 60 of file RoadInfo.cc.
SetCount()
void RoadInfo::SetCount (const int count) inline
Definition at line 26 of file RoadInfo.h.
SetCountBG()
void RoadInfo::SetCountBG (const int count) inline
Definition at line 33 of file RoadInfo.h.
SetOnOff()
void RoadInfo::SetOnOff (const bool on_off) inline
Definition at line 39 of file RoadInfo.h.
Referenced by GenRoadset::DisableRoadsByFoM(), GenRoadset::DisableRoadsByWeightFraction(), GenRoadset::GenerateSymmetricRoadSetByFoM(), and GenRoadset::SymmetrizeRoads().
SetRoadID()
void RoadInfo::SetRoadID (const int road_id) inline
Definition at line 22 of file RoadInfo.h.
SetWeight()
void RoadInfo::SetWeight (const double weight) inline
Definition at line 27 of file RoadInfo.h.
SetWeightBG()
void RoadInfo::SetWeightBG (const double weight) inline
Definition at line 34 of file RoadInfo.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadInfo.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/RoadInfo.cc