E1039 Software: /home/yuhw/GitHub/SeaQuest/e1039-core/online/decoder_maindaq/CodaInputManager.cc File Reference
CodaInputManager.cc File Reference
#include <iostream>
#include <iomanip>
#include <sstream>
#include <cstdlib>
#include <fstream>
#include <unistd.h>
#include "evio.h"
#include "UtilOnline.h"
#include "CodaInputManager.h"
Functions
int get_hex_bit (unsigned int hexNum, int numBitFromRight)
int get_hex_bits (unsigned int hexNum, int numBitFromRight, int numBits)
int get_bin_bit (unsigned int binNum, int numBitFromRight)
int get_bin_bits (unsigned int binNum, int numBitFromRight, int numBits)
void Abort (const char *message)
void PrintWords (int *words, int idx_begin, int idx_end, int idx_atte)
void PrintCodaEventSummary (int *words)
Function Documentation
Abort()
void Abort (const char * message)
Definition at line 216 of file CodaInputManager.cc.
Referenced by MainDaqParser::ProcessBoardData(), MainDaqParser::ProcessBoardFeeQIE(), MainDaqParser::ProcessBoardJyTDC2(), MainDaqParser::ProcessBoardStdFeeQIE(), MainDaqParser::ProcessBoardTriggerBit(), MainDaqParser::ProcessBoardTriggerCount(), MainDaqParser::ProcessBoardV1495TDC(), and MainDaqParser::ProcessPhysFlush().
get_bin_bit()
int get_bin_bit (unsigned int binNum, int numBitFromRight)
This function takes an integer, grabs a certain binary digit from a certain position in the binary number.
For example, if number = 11010001101011100 (or, 0d107356) then get_bin_bit(number, 3) would return 1 (or 0d01), representing 11010001101011100 <– this part of the number ^
Definition at line 176 of file CodaInputManager.cc.
Referenced by get_bin_bits(), MainDaqParser::ProcessBoardJyTDC2(), MainDaqParser::ProcessBoardStdJyTDC2(), MainDaqParser::ProcessBoardStdTriggerBit(), MainDaqParser::ProcessBoardStdV1495TDC(), MainDaqParser::ProcessBoardTriggerBit(), MainDaqParser::ProcessCodaFeeBoard(), and MainDaqParser::ProcessCodaFeePrescale().
get_bin_bits()
int get_bin_bits (unsigned int binNum, int numBitFromRight, int numBits)
This function takes an integer, grabs a certain number of binary digits from a certain position in the binary number.
For example, if number = 11010001101011100, then get_bin_bits(number, 3, 3) would return 110 (or 0d06), representing 11010001101011100 <– those parts of the number ^^^
Definition at line 194 of file CodaInputManager.cc.
References get_bin_bit().
Referenced by MainDaqParser::ProcessBoardJyTDC2(), MainDaqParser::ProcessBoardStdJyTDC2(), and MainDaqParser::ProcessCodaFeeBoard().
get_hex_bit()
int get_hex_bit (unsigned int hexNum, int numBitFromRight)
This function takes an integer, grabs a certain number of hexadecimal digits from a certain position in the hex representation of the number.
For example, if number = 0x10e59c (or, 0d107356) then get_hex_bit(number, 3) would return e (or 0d14), representing 0x10e59c <– those parts of the number
Definition at line 123 of file CodaInputManager.cc.
Referenced by MainDaqParser::ProcessBoardJyTDC2(), MainDaqParser::ProcessBoardStdJyTDC2(), and MainDaqParser::ProcessCodaFeeBoard().
get_hex_bits()
int get_hex_bits (unsigned int hexNum, int numBitFromRight, int numBits)
This function takes an integer, grabs a certain number of hexadecimal digits from a certain position in the hex representation of the number.
For example, if number = 0x10e59c (or, 0d107356) then get_bin_bits(number, 3, 3) would return e59 (or 0d3673), representing 0x10e59c <– those parts of the number ^^^
Definition at line 143 of file CodaInputManager.cc.
Referenced by PrintCodaEventSummary(), MainDaqParser::ProcessBoardFeeQIE(), MainDaqParser::ProcessBoardJyTDC2(), MainDaqParser::ProcessBoardStdFeeQIE(), MainDaqParser::ProcessBoardStdJyTDC2(), MainDaqParser::ProcessBoardStdV1495TDC(), MainDaqParser::ProcessBoardV1495TDC(), MainDaqParser::ProcessCodaFeeBoard(), MainDaqParser::ProcessCodaPhysics(), MainDaqParser::ProcessPhysBOSEOS(), and MainDaqParser::ProcessPhysFlush().
PrintCodaEventSummary()
void PrintCodaEventSummary (int * words)
Print out lists of ROCs and boards found in one Coda event.
This function might be useful when you check the word format independent of all main functions (like ProcessPhysFlush() & format()). But you should not assume that the output of this function is always consistent with those of the main functions, since this function decodes words by itself.
Definition at line 241 of file CodaInputManager.cc.
References get_hex_bits().
PrintWords()
void PrintWords (int * words, int idx_begin, int idx_end, int idx_atte)
Definition at line 222 of file CodaInputManager.cc.
Referenced by MainDaqParser::ProcessBoardData(), MainDaqParser::ProcessBoardTriggerBit(), MainDaqParser::ProcessBoardTriggerCount(), and MainDaqParser::ProcessPhysFlush().