Class Reference for E1039 Core & Analysis Software: Fun4AllEventOutStream Class Reference
Fun4AllEventOutStream Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/fun4all/Fun4AllEventOutStream.h>
Public Member Functions
virtual ~Fun4AllEventOutStream ()
virtual int StreamStatus ()
virtual int WriteEvent (Event *evt)
virtual int WriteEventOut (Event *)
virtual int CloseOutStream ()
int AddPacket (const int ipkt)
int DropPacket (const int ipkt)
int AddPacketRange (const int minpacket, const int maxpacket)
int DropPacketRange (const int minpacket, const int maxpacket)
void SetManager (Fun4AllEventOutputManager *myman)
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Print (const std::string &what="ALL") const
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
Fun4AllEventOutStream (const std::string &name="OUTSTREAM")
int resize_evtbuf (const unsigned int newsize)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
PHDWORD * evtbuf
unsigned int evtbuf_size
int add_or_remove
Packet ** plist
int max_npackets
int npackets
int default_addall
std::map< int, boost::numeric::interval< int > > addpktrange
std::map< int, boost::numeric::interval< int > > droppktrange
Fun4AllEventOutputManager * mymanager
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 30 of file Fun4AllEventOutStream.h.
Constructor & Destructor Documentation
~Fun4AllEventOutStream()
Fun4AllEventOutStream::~Fun4AllEventOutStream () virtual
Definition at line 26 of file Fun4AllEventOutStream.cc.
References evtbuf, and plist.
Fun4AllEventOutStream()
Fun4AllEventOutStream::Fun4AllEventOutStream (const std::string & name = "OUTSTREAM") protected
Definition at line 14 of file Fun4AllEventOutStream.cc.
Member Function Documentation
AddPacket()
int Fun4AllEventOutStream::AddPacket (const int ipkt)
Definition at line 151 of file Fun4AllEventOutStream.cc.
References AddPacketRange().
Referenced by Fun4AllEventOutputManager::AddPacket().
AddPacketRange()
int Fun4AllEventOutStream::AddPacketRange (const int minpacket, const int maxpacket)
Definition at line 165 of file Fun4AllEventOutStream.cc.
References add_or_remove, addpktrange, and PHWHERE.
Referenced by AddPacket(), and Fun4AllEventOutputManager::AddPacketRange().
CloseOutStream()
virtual int Fun4AllEventOutStream::CloseOutStream () inline virtual
Reimplemented in Fun4AllFileOutStream.
Definition at line 37 of file Fun4AllEventOutStream.h.
DropPacket()
int Fun4AllEventOutStream::DropPacket (const int ipkt)
Definition at line 158 of file Fun4AllEventOutStream.cc.
References DropPacketRange().
Referenced by Fun4AllEventOutputManager::DropPacket().
DropPacketRange()
int Fun4AllEventOutStream::DropPacketRange (const int minpacket, const int maxpacket)
Definition at line 197 of file Fun4AllEventOutStream.cc.
References add_or_remove, default_addall, droppktrange, and PHWHERE.
Referenced by DropPacket(), and Fun4AllEventOutputManager::DropPacketRange().
resize_evtbuf()
int Fun4AllEventOutStream::resize_evtbuf (const unsigned int newsize) protected
Definition at line 34 of file Fun4AllEventOutStream.cc.
References evtbuf, and evtbuf_size.
Referenced by WriteEvent().
SetManager()
void Fun4AllEventOutStream::SetManager (Fun4AllEventOutputManager * myman) inline
Definition at line 43 of file Fun4AllEventOutStream.h.
References mymanager.
Referenced by Fun4AllEventOutputManager::Fun4AllEventOutputManager().
StreamStatus()
virtual int Fun4AllEventOutStream::StreamStatus () inline virtual
Definition at line 34 of file Fun4AllEventOutStream.h.
WriteEvent()
int Fun4AllEventOutStream::WriteEvent (Event * evt) virtual
Definition at line 47 of file Fun4AllEventOutStream.cc.
References add_or_remove, addpktrange, default_addall, droppktrange, evtbuf, evtbuf_size, max_npackets, npackets, plist, resize_evtbuf(), Fun4AllBase::verbosity, and WriteEventOut().
Referenced by Fun4AllEventOutputManager::Write().
WriteEventOut()
virtual int Fun4AllEventOutStream::WriteEventOut (Event *) inline virtual
Reimplemented in Fun4AllRolloverFileOutStream, and Fun4AllFileOutStream.
Definition at line 36 of file Fun4AllEventOutStream.h.
Referenced by WriteEvent().
Member Data Documentation
add_or_remove
int Fun4AllEventOutStream::add_or_remove protected
Definition at line 53 of file Fun4AllEventOutStream.h.
Referenced by AddPacketRange(), DropPacketRange(), and WriteEvent().
addpktrange
std::map<int,boost::numeric::interval<int> > Fun4AllEventOutStream::addpktrange protected
Definition at line 59 of file Fun4AllEventOutStream.h.
Referenced by AddPacketRange(), and WriteEvent().
default_addall
int Fun4AllEventOutStream::default_addall protected
Definition at line 57 of file Fun4AllEventOutStream.h.
Referenced by DropPacketRange(), and WriteEvent().
droppktrange
std::map<int,boost::numeric::interval<int> > Fun4AllEventOutStream::droppktrange protected
Definition at line 60 of file Fun4AllEventOutStream.h.
Referenced by DropPacketRange(), and WriteEvent().
evtbuf
PHDWORD* Fun4AllEventOutStream::evtbuf protected
Definition at line 49 of file Fun4AllEventOutStream.h.
Referenced by resize_evtbuf(), WriteEvent(), and ~Fun4AllEventOutStream().
evtbuf_size
unsigned int Fun4AllEventOutStream::evtbuf_size protected
Definition at line 50 of file Fun4AllEventOutStream.h.
Referenced by resize_evtbuf(), and WriteEvent().
max_npackets
int Fun4AllEventOutStream::max_npackets protected
Definition at line 55 of file Fun4AllEventOutStream.h.
Referenced by WriteEvent().
mymanager
Fun4AllEventOutputManager* Fun4AllEventOutStream::mymanager protected
Definition at line 62 of file Fun4AllEventOutStream.h.
Referenced by SetManager(), and Fun4AllRolloverFileOutStream::WriteEventOut().
npackets
int Fun4AllEventOutStream::npackets protected
Definition at line 56 of file Fun4AllEventOutStream.h.
Referenced by WriteEvent().
plist
Packet** Fun4AllEventOutStream::plist protected
Definition at line 54 of file Fun4AllEventOutStream.h.
Referenced by WriteEvent(), and ~Fun4AllEventOutStream().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/fun4all/Fun4AllEventOutStream.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/fun4all/Fun4AllEventOutStream.cc