Class Reference for E1039 Core & Analysis Software: CalibData Class Reference
CalibData Class Reference
Class to hold calibration data.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/CalibData.h>
Public Member Functions
CalibData ()
virtual ~CalibData ()
TH2 * GetHistRT (const int ipl) const
void Init (CalibParam *ptr)
void FillEventInfo (const int rec_stat, const std::map< int, int > list_n_trk)
void FillTracklet (const Tracklet *trk)
void FillTrackletHits (const Tracklet *trk)
void FillHit (const int det_id, const double drift_dist, const double tdc_time, const double track_pos, const double wire_pos)
Fill the hit information.
void DrawHistEvent (const std::string dir_out)
void DrawHistHit (const std::string dir_out)
Detailed Description
Class to hold calibration data.
Definition at line 12 of file CalibData.h.
Constructor & Destructor Documentation
CalibData()
CalibData::CalibData ()
Definition at line 17 of file CalibData.cc.
~CalibData()
CalibData::~CalibData () virtual
Definition at line 23 of file CalibData.cc.
Member Function Documentation
DrawHistEvent()
void CalibData::DrawHistEvent (const std::string dir_out)
Definition at line 179 of file CalibData.cc.
Referenced by MakeRTCurve::DrawHistEvent(), and SRMakeRTCurve::DrawHistEvent().
DrawHistHit()
void CalibData::DrawHistHit (const std::string dir_out)
Definition at line 213 of file CalibData.cc.
References UtilHist::AutoSetRange(), CalibParam::GetAnaPlane(), GeomSvc::getDetectorName(), CalibParam::GetNumPlanes(), and GeomSvc::instance().
Referenced by MakeRTCurve::DrawHistHit(), and SRMakeRTCurve::DrawHistHit().
FillEventInfo()
void CalibData::FillEventInfo (const int rec_stat, const std::map< int, int > list_n_trk)
Definition at line 113 of file CalibData.cc.
Referenced by MakeRTCurve::AnalyzeFile(), and SRMakeRTCurve::process_event().
FillHit()
void CalibData::FillHit (const int det_id, const double drift_dist, const double tdc_time, const double track_pos, const double wire_pos)
Fill the hit information.
Here "track_dist" is the signed distance.
Definition at line 166 of file CalibData.cc.
Referenced by MakeRTCurve::AnalyzeFile(), and FillTrackletHits().
FillTracklet()
void CalibData::FillTracklet (const Tracklet * trk)
Definition at line 123 of file CalibData.cc.
References Tracklet::chisq, Tracklet::getNHits(), Tracklet::invP, Tracklet::stationID, Tracklet::tx, Tracklet::ty, Tracklet::x0, Tracklet::y0, and CalibParam::ZOfStationID().
Referenced by SRMakeRTCurve::AnaForOneStation(), and MakeRTCurve::AnalyzeFile().
FillTrackletHits()
void CalibData::FillTrackletHits (const Tracklet * trk)
Definition at line 146 of file CalibData.cc.
References FillHit(), Tracklet::getExpPositionW(), and Tracklet::hits.
Referenced by SRMakeRTCurve::AnaForOneStation().
GetHistRT()
TH2* CalibData::GetHistRT (const int ipl) const inline
Definition at line 49 of file CalibData.h.
Referenced by MakeRTCurve::DrawCalibResult(), SRMakeRTCurve::DrawCalibResult(), MakeRTCurve::ExtractRT(), and SRMakeRTCurve::ExtractRT().
Init()
void CalibData::Init (CalibParam * ptr)
Definition at line 28 of file CalibData.cc.
References GeomSvc::getDetectorName(), CalibParam::GetNumPlanes(), GeomSvc::getPlaneScaleX(), CalibParam::GetRMax(), CalibParam::GetTMax(), CalibParam::GetTMin(), and GeomSvc::instance().
Referenced by MakeRTCurve::Init(), and SRMakeRTCurve::InitRun().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/CalibData.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/CalibData.cc