E1039 Software: RunParamBase Class Reference
RunParamBase Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/RunParamBase.h>
Public Member Functions
RunParamBase (const std::string type, const std::string label, const std::string header)
virtual ~RunParamBase ()
void SetBaseDir (const std::string dir_base)
std::string GetBaseDir ()
std::string GetMapID ()
void SetMapID (const std::string map_id)
void SetMapIDbyFile (const std::string map_id)
void SetMapIDbyDB (const std::string map_id)
void SetMapIDbyFile (const int run)
void SetMapIDbyDB (const int run)
void ReadFromFile ()
void WriteToFile ()
void ReadFromLocalFile (const std::string fn_tsv)
void WriteToLocalFile (const std::string fn_tsv)
void ReadFromDB ()
void WriteToDB ()
void WriteRangeToDB ()
virtual void Print (std::ostream &os)
Protected Types
typedef std::vector< std::string > LineList
Protected Member Functions
std::string RangeFileName ()
std::string MapFileName ()
std::string SchemaName ()
std::string MapTableName ()
virtual int ReadFileCont (LineList &lines)
virtual int WriteFileCont (std::ostream &os)
virtual void ReadDbTable (DbSvc &db)
virtual void WriteDbTable (DbSvc &db)
Private Attributes
std::string m_dir_base
std::string m_type
std::string m_label
std::string m_header
std::string m_map_id
ParamRunRange m_range
Detailed Description
Definition at line 11 of file RunParamBase.h.
Member Typedef Documentation
LineList
typedef std::vector<std::string> RunParamBase::LineList protected
Definition at line 50 of file RunParamBase.h.
Constructor & Destructor Documentation
RunParamBase()
RunParamBase::RunParamBase (const std::string type, const std::string label, const std::string header)
Definition at line 11 of file RunParamBase.cc.
References m_dir_base.
~RunParamBase()
virtual RunParamBase::~RunParamBase () inline virtual
Definition at line 21 of file RunParamBase.h.
Member Function Documentation
GetBaseDir()
std::string RunParamBase::GetBaseDir () inline
Definition at line 24 of file RunParamBase.h.
References m_dir_base.
GetMapID()
std::string RunParamBase::GetMapID () inline
Definition at line 26 of file RunParamBase.h.
References m_map_id.
MapFileName()
std::string RunParamBase::MapFileName () protected
Definition at line 152 of file RunParamBase.cc.
References m_dir_base, m_label, m_map_id, and m_type.
Referenced by ReadFromFile(), SetMapID(), and WriteToFile().
MapTableName()
std::string RunParamBase::MapTableName () protected
Definition at line 166 of file RunParamBase.cc.
References m_map_id.
Referenced by ChanMapScaler::ReadDbTable(), CalibParamXT::ReadDbTable(), CalibParamInTimeTaiwan::ReadDbTable(), CalibParamInTimeV1495::ReadDbTable(), ChanMapTaiwan::ReadDbTable(), ChanMapV1495::ReadDbTable(), ReadFromDB(), SetMapID(), ChanMapScaler::WriteDbTable(), CalibParamInTimeTaiwan::WriteDbTable(), CalibParamXT::WriteDbTable(), CalibParamInTimeV1495::WriteDbTable(), ChanMapTaiwan::WriteDbTable(), ChanMapV1495::WriteDbTable(), and WriteToDB().
Print()
void RunParamBase::Print (std::ostream & os) virtual
Reimplemented in ChanMapV1495, ChanMapTaiwan, CalibParamInTimeV1495, CalibParamInTimeTaiwan, CalibParamXT, and ChanMapScaler.
Definition at line 140 of file RunParamBase.cc.
Referenced by SetMapID().
RangeFileName()
std::string RunParamBase::RangeFileName () protected
Definition at line 145 of file RunParamBase.cc.
References m_dir_base, m_label, and m_type.
Referenced by SetMapID(), SetMapIDbyDB(), and SetMapIDbyFile().
ReadDbTable()
void RunParamBase::ReadDbTable (DbSvc & db) protected virtual
Reimplemented in ChanMapV1495, ChanMapTaiwan, CalibParamInTimeV1495, CalibParamInTimeTaiwan, CalibParamXT, and ChanMapScaler.
Definition at line 185 of file RunParamBase.cc.
Referenced by ReadFromDB().
ReadFileCont()
int RunParamBase::ReadFileCont (LineList & lines) protected virtual
Reimplemented in ChanMapV1495, ChanMapTaiwan, CalibParamInTimeV1495, CalibParamInTimeTaiwan, CalibParamXT, and ChanMapScaler.
Definition at line 173 of file RunParamBase.cc.
Referenced by ReadFromLocalFile().
ReadFromDB()
void RunParamBase::ReadFromDB ()
Definition at line 97 of file RunParamBase.cc.
References DbSvc::DB1, DbSvc::HasTable(), m_map_id, MapTableName(), ReadDbTable(), SchemaName(), and DbSvc::UseSchema().
Referenced by DecoParam::InitMapper(), CalibInTime::InitRun(), CalibXT::InitRun(), and SetMapID().
ReadFromFile()
void RunParamBase::ReadFromFile ()
Definition at line 53 of file RunParamBase.cc.
References MapFileName(), and ReadFromLocalFile().
Referenced by SetMapID().
ReadFromLocalFile()
void RunParamBase::ReadFromLocalFile (const std::string fn_tsv)
Definition at line 63 of file RunParamBase.cc.
References ReadFileCont().
Referenced by ReadFromFile(), and SetMapID().
SchemaName()
std::string RunParamBase::SchemaName () protected
Definition at line 159 of file RunParamBase.cc.
References m_label, and m_type.
Referenced by ReadFromDB(), SetMapID(), SetMapIDbyDB(), WriteRangeToDB(), and WriteToDB().
SetBaseDir()
void RunParamBase::SetBaseDir (const std::string dir_base) inline
Definition at line 23 of file RunParamBase.h.
SetMapID()
void RunParamBase::SetMapID (const std::string map_id) inline
Definition at line 27 of file RunParamBase.h.
References MapFileName(), MapTableName(), Print(), RangeFileName(), ReadFromDB(), ReadFromFile(), ReadFromLocalFile(), SchemaName(), SetMapIDbyDB(), SetMapIDbyFile(), WriteRangeToDB(), WriteToDB(), WriteToFile(), and WriteToLocalFile().
SetMapIDbyDB() [1/2]
void RunParamBase::SetMapIDbyDB (const std::string map_id)
Definition at line 31 of file RunParamBase.cc.
References ParamRunRange::Find(), m_map_id, m_range, RangeFileName(), and ParamRunRange::ReadFromDB().
Referenced by DecoParam::InitMapper(), CalibInTime::InitRun(), CalibXT::InitRun(), and SetMapID().
SetMapIDbyDB() [2/2]
void RunParamBase::SetMapIDbyDB (const int run)
Definition at line 47 of file RunParamBase.cc.
References ParamRunRange::Find(), m_map_id, m_range, ParamRunRange::ReadFromDB(), and SchemaName().
SetMapIDbyFile() [1/2]
void RunParamBase::SetMapIDbyFile (const std::string map_id)
Definition at line 21 of file RunParamBase.cc.
References ParamRunRange::Find(), m_map_id, m_range, RangeFileName(), and ParamRunRange::ReadFromFile().
Referenced by SetMapID().
SetMapIDbyFile() [2/2]
void RunParamBase::SetMapIDbyFile (const int run)
Definition at line 41 of file RunParamBase.cc.
References ParamRunRange::Find(), m_map_id, m_range, RangeFileName(), and ParamRunRange::ReadFromFile().
WriteDbTable()
void RunParamBase::WriteDbTable (DbSvc & db) protected virtual
Reimplemented in ChanMapV1495, ChanMapTaiwan, CalibParamInTimeV1495, CalibParamInTimeTaiwan, CalibParamXT, and ChanMapScaler.
Definition at line 190 of file RunParamBase.cc.
Referenced by WriteToDB().
WriteFileCont()
int RunParamBase::WriteFileCont (std::ostream & os) protected virtual
Reimplemented in ChanMapV1495, ChanMapTaiwan, CalibParamInTimeV1495, CalibParamInTimeTaiwan, CalibParamXT, and ChanMapScaler.
Definition at line 179 of file RunParamBase.cc.
Referenced by WriteToLocalFile().
WriteRangeToDB()
void RunParamBase::WriteRangeToDB ()
Definition at line 135 of file RunParamBase.cc.
References m_range, SchemaName(), and ParamRunRange::WriteToDB().
Referenced by SetMapID().
WriteToDB()
void RunParamBase::WriteToDB ()
Definition at line 116 of file RunParamBase.cc.
References DbSvc::DB1, DbSvc::DropTable(), m_map_id, MapTableName(), SchemaName(), DbSvc::UseSchema(), and WriteDbTable().
Referenced by SetMapID().
WriteToFile()
void RunParamBase::WriteToFile ()
Definition at line 58 of file RunParamBase.cc.
References MapFileName(), and WriteToLocalFile().
Referenced by SetMapID().
WriteToLocalFile()
void RunParamBase::WriteToLocalFile (const std::string fn_tsv)
Definition at line 83 of file RunParamBase.cc.
References m_header, and WriteFileCont().
Referenced by SetMapID(), and WriteToFile().
Member Data Documentation
m_dir_base
std::string RunParamBase::m_dir_base private
Definition at line 12 of file RunParamBase.h.
Referenced by GetBaseDir(), MapFileName(), RangeFileName(), and RunParamBase().
m_header
std::string RunParamBase::m_header private
Definition at line 15 of file RunParamBase.h.
Referenced by WriteToLocalFile().
m_label
std::string RunParamBase::m_label private
Definition at line 14 of file RunParamBase.h.
Referenced by MapFileName(), RangeFileName(), and SchemaName().
m_map_id
std::string RunParamBase::m_map_id private
Definition at line 16 of file RunParamBase.h.
Referenced by GetMapID(), MapFileName(), MapTableName(), ReadFromDB(), SetMapIDbyDB(), SetMapIDbyFile(), and WriteToDB().
m_range
ParamRunRange RunParamBase::m_range private
Definition at line 17 of file RunParamBase.h.
Referenced by SetMapIDbyDB(), SetMapIDbyFile(), and WriteRangeToDB().
m_type
std::string RunParamBase::m_type private
Definition at line 13 of file RunParamBase.h.
Referenced by MapFileName(), RangeFileName(), and SchemaName().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/RunParamBase.h
/home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/RunParamBase.cc