SeaQuest Offline Software: PHG4mRICHDetector::mRichParameter Class Reference
PHG4mRICHDetector::mRichParameter Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4mRICHDetector.h>
Public Member Functions
mRichParameter ()
~mRichParameter ()
void SetPar_glassWindow (G4double x, G4double y)
void SetPar_sensor (G4double x, G4double y)
BoxPar * GetBoxPar (std::string componentName)
LensPar * GetLensPar (std::string componentName)
PolyPar * GetPolyPar (std::string componentName)
Private Attributes
BoxPar * holderBox
BoxPar * hollowVolume
BoxPar * foamHolderBox
PolyPar * foamHolderPoly
BoxPar * aerogel
LensPar * fresnelLens
PolyPar * mirror
BoxPar * glassWindow
BoxPar * sensor
PolyPar * readout
Detailed Description
Definition at line 78 of file PHG4mRICHDetector.h.
Constructor & Destructor Documentation
PHG4mRICHDetector::mRichParameter::mRichParameter ()
Definition at line 231 of file PHG4mRICHDetector.cc.
PHG4mRICHDetector::mRichParameter::~mRichParameter ()
Definition at line 505 of file PHG4mRICHDetector.cc.
Member Function Documentation
PHG4mRICHDetector::BoxPar * PHG4mRICHDetector::mRichParameter::GetBoxPar (std::string componentName)
Definition at line 519 of file PHG4mRICHDetector.cc.
Referenced by PHG4mRICHDetector::build_aerogel(), PHG4mRICHDetector::build_foamHolder(), PHG4mRICHDetector::build_holderBox(), and PHG4mRICHDetector::build_sensor().
PHG4mRICHDetector::LensPar * PHG4mRICHDetector::mRichParameter::GetLensPar (std::string componentName)
Definition at line 532 of file PHG4mRICHDetector.cc.
Referenced by PHG4mRICHDetector::Construct_a_mRICH().
PHG4mRICHDetector::PolyPar * PHG4mRICHDetector::mRichParameter::GetPolyPar (std::string componentName)
Definition at line 539 of file PHG4mRICHDetector.cc.
Referenced by PHG4mRICHDetector::build_foamHolder(), PHG4mRICHDetector::build_mirror(), and PHG4mRICHDetector::Construct_a_mRICH().
void PHG4mRICHDetector::mRichParameter::SetPar_glassWindow (G4double x, G4double y)
Definition at line 507 of file PHG4mRICHDetector.cc.
Referenced by PHG4mRICHDetector::build_sensor().
void PHG4mRICHDetector::mRichParameter::SetPar_sensor (G4double x, G4double y)
Definition at line 513 of file PHG4mRICHDetector.cc.
Referenced by PHG4mRICHDetector::build_sensor().
Member Data Documentation
BoxPar* PHG4mRICHDetector::mRichParameter::aerogel private
Definition at line 85 of file PHG4mRICHDetector.h.
BoxPar* PHG4mRICHDetector::mRichParameter::foamHolderBox private
Definition at line 83 of file PHG4mRICHDetector.h.
PolyPar* PHG4mRICHDetector::mRichParameter::foamHolderPoly private
Definition at line 84 of file PHG4mRICHDetector.h.
LensPar* PHG4mRICHDetector::mRichParameter::fresnelLens private
Definition at line 86 of file PHG4mRICHDetector.h.
BoxPar* PHG4mRICHDetector::mRichParameter::glassWindow private
Definition at line 88 of file PHG4mRICHDetector.h.
BoxPar* PHG4mRICHDetector::mRichParameter::holderBox private
Definition at line 81 of file PHG4mRICHDetector.h.
BoxPar* PHG4mRICHDetector::mRichParameter::hollowVolume private
Definition at line 82 of file PHG4mRICHDetector.h.
PolyPar* PHG4mRICHDetector::mRichParameter::mirror private
Definition at line 87 of file PHG4mRICHDetector.h.
PolyPar* PHG4mRICHDetector::mRichParameter::readout private
Definition at line 90 of file PHG4mRICHDetector.h.
BoxPar* PHG4mRICHDetector::mRichParameter::sensor private
Definition at line 89 of file PHG4mRICHDetector.h.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4mRICHDetector.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4mRICHDetector.cc