Class Reference for E1039 Core & Analysis Software: SQDimuonVector_v1 Class Reference
SQDimuonVector_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQDimuonVector_v1.h>
Public Member Functions
SQDimuonVector_v1 ()
SQDimuonVector_v1 (const SQDimuonVector_v1 &obj)
SQDimuonVector_v1 & operator= (const SQDimuonVector_v1 &obj)
virtual ~SQDimuonVector_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQDimuonVector * Clone () const
ConstIter begin () const
ConstIter end () const
Iter begin ()
Iter end ()
bool empty () const
size_t size () const
void clear ()
const SQDimuon * at (const size_t id) const
SQDimuon * at (const size_t id)
void push_back (const SQDimuon *dim)
size_t erase (const size_t id)
Public Member Functions inherited from SQDimuonVector
virtual ~SQDimuonVector ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
ClassDef (SQDimuonVector_v1, 1)
Protected Member Functions inherited from SQDimuonVector
SQDimuonVector ()
ClassDef (SQDimuonVector, 1)
Protected Attributes
Vector _vector
Additional Inherited Members
Public Types inherited from SQDimuonVector
typedef std::vector< SQDimuon * > Vector
typedef std::vector< SQDimuon * >::const_iterator ConstIter
typedef std::vector< SQDimuon * >::iterator Iter
Detailed Description
Definition at line 5 of file SQDimuonVector_v1.h.
Constructor & Destructor Documentation
SQDimuonVector_v1() [1/2]
SQDimuonVector_v1::SQDimuonVector_v1 ()
Referenced by Clone().
SQDimuonVector_v1() [2/2]
SQDimuonVector_v1::SQDimuonVector_v1 (const SQDimuonVector_v1 & obj)
Definition at line 10 of file SQDimuonVector_v1.cxx.
References begin(), and end().
~SQDimuonVector_v1()
SQDimuonVector_v1::~SQDimuonVector_v1 () virtual
Definition at line 26 of file SQDimuonVector_v1.cxx.
Member Function Documentation
at() [1/2]
SQDimuon * SQDimuonVector_v1::at (const size_t id) virtual
Implements SQDimuonVector.
Definition at line 48 of file SQDimuonVector_v1.cxx.
at() [2/2]
const SQDimuon * SQDimuonVector_v1::at (const size_t id) const virtual
Implements SQDimuonVector.
Definition at line 42 of file SQDimuonVector_v1.cxx.
begin() [1/2]
Iter SQDimuonVector_v1::begin () inline virtual
Implements SQDimuonVector.
Definition at line 19 of file SQDimuonVector_v1.h.
References _vector.
begin() [2/2]
ConstIter SQDimuonVector_v1::begin () const inline virtual
Implements SQDimuonVector.
Definition at line 17 of file SQDimuonVector_v1.h.
References _vector.
Referenced by operator=(), and SQDimuonVector_v1().
ClassDef()
SQDimuonVector_v1::ClassDef (SQDimuonVector_v1 , 1) protected
clear()
void SQDimuonVector_v1::clear () inline virtual
Implements SQDimuonVector.
Definition at line 23 of file SQDimuonVector_v1.h.
References Reset().
Clone()
SQDimuonVector* SQDimuonVector_v1::Clone () const inline virtual
Implements SQDimuonVector.
Definition at line 15 of file SQDimuonVector_v1.h.
References SQDimuonVector_v1().
empty()
bool SQDimuonVector_v1::empty () const inline virtual
Implements SQDimuonVector.
Definition at line 21 of file SQDimuonVector_v1.h.
References _vector.
end() [1/2]
Iter SQDimuonVector_v1::end () inline virtual
Implements SQDimuonVector.
Definition at line 20 of file SQDimuonVector_v1.h.
References _vector.
end() [2/2]
ConstIter SQDimuonVector_v1::end () const inline virtual
Implements SQDimuonVector.
Definition at line 18 of file SQDimuonVector_v1.h.
References _vector.
Referenced by operator=(), and SQDimuonVector_v1().
erase()
size_t SQDimuonVector_v1::erase (const size_t id) virtual
Implements SQDimuonVector.
Definition at line 59 of file SQDimuonVector_v1.cxx.
identify()
void SQDimuonVector_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Implements SQDimuonVector.
Definition at line 37 of file SQDimuonVector_v1.cxx.
isValid()
int SQDimuonVector_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Implements SQDimuonVector.
Definition at line 14 of file SQDimuonVector_v1.h.
operator=()
SQDimuonVector_v1 & SQDimuonVector_v1::operator= (const SQDimuonVector_v1 & obj)
Definition at line 17 of file SQDimuonVector_v1.cxx.
References begin(), and end().
push_back()
void SQDimuonVector_v1::push_back (const SQDimuon * dim) virtual
Implements SQDimuonVector.
Definition at line 54 of file SQDimuonVector_v1.cxx.
References SQDimuon::Clone().
Reset()
void SQDimuonVector_v1::Reset () virtual
Clear Event.
Implements SQDimuonVector.
Definition at line 31 of file SQDimuonVector_v1.cxx.
Referenced by clear().
size()
size_t SQDimuonVector_v1::size (void) const inline virtual
Implements SQDimuonVector.
Definition at line 22 of file SQDimuonVector_v1.h.
References _vector.
Member Data Documentation
_vector
Vector SQDimuonVector_v1::_vector protected
Definition at line 31 of file SQDimuonVector_v1.h.
Referenced by begin(), empty(), end(), and size().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQDimuonVector_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQDimuonVector_v1.cxx