Class Reference for E1039 Core & Analysis Software: mPHEveModuleBase Class Reference
mPHEveModuleBase Class Reference abstract
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Display/modules/mPHEveModuleBase.h>
Public Member Functions
virtual ~mPHEveModuleBase ()
virtual void init (PHCompositeNode *top_node)=0
virtual void init_run (PHCompositeNode *top_node)=0
virtual bool event (PHCompositeNode *top_node)=0
virtual void draw_event ()
void add_elements ()
void buffer_element (TEveElement *el, TEveElement *parent_elmt)
void clear_element_buffer ()
virtual void clear ()=0
virtual void end (PHCompositeNode *top_node)=0
Protected Types
typedef std::multimap
< TEveElement *, TEveElement * > elmtmap
typedef
elmtmap::iterator::value_type mvt
Protected Attributes
TEveManager * _evemanager
elmtmap _elmt_buffer
Detailed Description
Definition at line 24 of file mPHEveModuleBase.h.
Member Typedef Documentation
typedef std::multimap<TEveElement*, TEveElement*> mPHEveModuleBase::elmtmap protected
Definition at line 60 of file mPHEveModuleBase.h.
typedef elmtmap::iterator::value_type mPHEveModuleBase::mvt protected
Definition at line 62 of file mPHEveModuleBase.h.
Constructor & Destructor Documentation
virtual mPHEveModuleBase::~mPHEveModuleBase () inline virtual
Definition at line 27 of file mPHEveModuleBase.h.
Member Function Documentation
void mPHEveModuleBase::add_elements () inline
Definition at line 32 of file mPHEveModuleBase.h.
References _elmt_buffer, and _evemanager.
void mPHEveModuleBase::buffer_element (TEveElement * el, TEveElement * parent_elmt) inline
Definition at line 41 of file mPHEveModuleBase.h.
References _elmt_buffer.
virtual void mPHEveModuleBase::clear () pure virtual
Implemented in mTrkEveDisplay.
Referenced by PHEventDisplay::process_event().
void mPHEveModuleBase::clear_element_buffer () inline
Definition at line 47 of file mPHEveModuleBase.h.
References _elmt_buffer.
virtual void mPHEveModuleBase::draw_event () inline virtual
Definition at line 31 of file mPHEveModuleBase.h.
virtual void mPHEveModuleBase::end (PHCompositeNode * top_node) pure virtual
Implemented in mTrkEveDisplay.
virtual bool mPHEveModuleBase::event (PHCompositeNode * top_node) pure virtual
Implemented in mTrkEveDisplay.
Referenced by PHEventDisplay::process_event().
virtual void mPHEveModuleBase::init (PHCompositeNode * top_node) pure virtual
Implemented in mTrkEveDisplay.
virtual void mPHEveModuleBase::init_run (PHCompositeNode * top_node) pure virtual
Implemented in mTrkEveDisplay.
Referenced by PHEventDisplay::InitRun().
Member Data Documentation
elmtmap mPHEveModuleBase::_elmt_buffer protected
Definition at line 61 of file mPHEveModuleBase.h.
Referenced by add_elements(), buffer_element(), and clear_element_buffer().
TEveManager* mPHEveModuleBase::_evemanager protected
Definition at line 58 of file mPHEveModuleBase.h.
Referenced by add_elements(), and mTrkEveDisplay::mTrkEveDisplay().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Display/modules/mPHEveModuleBase.h