Class Reference for E1039 Core & Analysis Software: SQSlowCont_v1 Class Reference
SQSlowCont_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSlowCont_v1.h>
Public Member Functions
SQSlowCont_v1 ()
virtual ~SQSlowCont_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQSlowCont * Clone () const
PHObject * clone () const
Virtual copy constructor.
virtual std::string get_time_stamp () const
Return the time when this channel was read out.
virtual void set_time_stamp (const std::string a)
virtual std::string get_name () const
Return the name of this channel.
virtual void set_name (const std::string a)
virtual std::string get_value () const
Return the value of this channel.
virtual void set_value (const std::string a)
virtual std::string get_type () const
Return the type (i.e. caterogy name) of this channel.
virtual void set_type (const std::string a)
Public Member Functions inherited from SQSlowCont
virtual ~SQSlowCont ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Protected Member Functions inherited from SQSlowCont
SQSlowCont ()
Detailed Description
Definition at line 10 of file SQSlowCont_v1.h.
Constructor & Destructor Documentation
SQSlowCont_v1()
SQSlowCont_v1::SQSlowCont_v1 ()
Definition at line 15 of file SQSlowCont_v1.cxx.
Referenced by Clone(), clone(), and Reset().
~SQSlowCont_v1()
virtual SQSlowCont_v1::~SQSlowCont_v1 () inline virtual
Definition at line 13 of file SQSlowCont_v1.h.
Member Function Documentation
Clone()
SQSlowCont* SQSlowCont_v1::Clone () const inline virtual
Reimplemented from SQSlowCont.
Definition at line 19 of file SQSlowCont_v1.h.
References SQSlowCont_v1().
clone()
PHObject* SQSlowCont_v1::clone () const inline virtual
Virtual copy constructor.
Reimplemented from SQSlowCont.
Definition at line 20 of file SQSlowCont_v1.h.
References SQSlowCont_v1().
get_name()
virtual std::string SQSlowCont_v1::get_name (void) const inline virtual
Return the name of this channel.
Reimplemented from SQSlowCont.
Definition at line 25 of file SQSlowCont_v1.h.
Referenced by identify().
get_time_stamp()
virtual std::string SQSlowCont_v1::get_time_stamp () const inline virtual
Return the time when this channel was read out.
Reimplemented from SQSlowCont.
Definition at line 22 of file SQSlowCont_v1.h.
get_type()
virtual std::string SQSlowCont_v1::get_type () const inline virtual
Return the type (i.e. caterogy name) of this channel.
Reimplemented from SQSlowCont.
Definition at line 31 of file SQSlowCont_v1.h.
get_value()
virtual std::string SQSlowCont_v1::get_value () const inline virtual
Return the value of this channel.
Reimplemented from SQSlowCont.
Definition at line 28 of file SQSlowCont_v1.h.
identify()
void SQSlowCont_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQSlowCont.
Definition at line 18 of file SQSlowCont_v1.cxx.
References get_name().
isValid()
int SQSlowCont_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQSlowCont.
Definition at line 25 of file SQSlowCont_v1.cxx.
Reset()
void SQSlowCont_v1::Reset () inline virtual
Clear Event.
Reimplemented from SQSlowCont.
Definition at line 17 of file SQSlowCont_v1.h.
References SQSlowCont_v1().
set_name()
virtual void SQSlowCont_v1::set_name (const std::string a) inline virtual
Reimplemented from SQSlowCont.
Definition at line 26 of file SQSlowCont_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_time_stamp()
virtual void SQSlowCont_v1::set_time_stamp (const std::string a) inline virtual
Reimplemented from SQSlowCont.
Definition at line 23 of file SQSlowCont_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_type()
virtual void SQSlowCont_v1::set_type (const std::string a) inline virtual
Reimplemented from SQSlowCont.
Definition at line 32 of file SQSlowCont_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_value()
virtual void SQSlowCont_v1::set_value (const std::string a) inline virtual
Reimplemented from SQSlowCont.
Definition at line 29 of file SQSlowCont_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSlowCont_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQSlowCont_v1.cxx