Class Reference for E1039 Core & Analysis Software: SQTrack Class Reference
SQTrack Class Reference abstract
An SQ interface class to hold one true or reconstructed track.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQTrack.h>
Public Member Functions
virtual ~SQTrack ()
virtual void identify (std::ostream &os=std::cout) const =0
virtual void Reset ()=0
Clear Event.
virtual int isValid () const =0
isValid returns non zero if object contains vailid data
virtual SQTrack * Clone () const =0
virtual int get_track_id () const =0
Return the track ID, which is unique per event(?).
virtual void set_track_id (const int a)=0
virtual int get_rec_track_id () const =0
Return the track ID of associated reconstructed track. Valid only if this object holds truth track info.
virtual void set_rec_track_id (const int a)=0
virtual int get_charge () const =0
Return the charge, i.e. +1 or -1.
virtual void set_charge (const int a)=0
virtual int get_num_hits () const =0
Return the number of hits associated to this track.
virtual void set_num_hits (const int a)=0
virtual TVector3 get_pos_vtx () const =0
Return the track position at vertex.
virtual void set_pos_vtx (const TVector3 a)=0
virtual TVector3 get_pos_st1 () const =0
Return the track position at Station 1.
virtual void set_pos_st1 (const TVector3 a)=0
virtual TVector3 get_pos_st3 () const =0
Return the track position at Station 3.
virtual void set_pos_st3 (const TVector3 a)=0
virtual TLorentzVector get_mom_vtx () const =0
Return the track momentum at vertex.
virtual void set_mom_vtx (const TLorentzVector a)=0
virtual TLorentzVector get_mom_st1 () const =0
Return the track momentum at Station 1.
virtual void set_mom_st1 (const TLorentzVector a)=0
virtual TLorentzVector get_mom_st3 () const =0
Return the track momentum at Station 3.
virtual void set_mom_st3 (const TLorentzVector a)=0
virtual double get_chisq () const =0
virtual double get_chisq_target () const =0
virtual double get_chisq_dump () const =0
virtual double get_chsiq_upstream () const =0
virtual TVector3 get_pos_target () const =0
virtual TVector3 get_pos_dump () const =0
virtual TLorentzVector get_mom_target () const =0
virtual TLorentzVector get_mom_dump () const =0
virtual int get_hit_id (const int i) const =0
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQTrack ()
ClassDef (SQTrack, 1)
Detailed Description
An SQ interface class to hold one true or reconstructed track.
Definition at line 8 of file SQTrack.h.
Constructor & Destructor Documentation
~SQTrack()
virtual SQTrack::~SQTrack () inline virtual
Definition at line 10 of file SQTrack.h.
SQTrack()
SQTrack::SQTrack () inline protected
Definition at line 61 of file SQTrack.h.
Member Function Documentation
ClassDef()
SQTrack::ClassDef (SQTrack , 1) protected
Clone()
virtual SQTrack* SQTrack::Clone () const pure virtual
Implemented in SRecTrack, and SQTrack_v1.
Referenced by SQTrackVector_v1::push_back().
get_charge()
virtual int SQTrack::get_charge () const pure virtual
Return the charge, i.e. +1 or -1.
Implemented in SRecTrack, and SQTrack_v1.
Referenced by AnaSimDst::process_event(), TracePHG4Particle::process_event(), AnaTrack::process_event(), AnaEmbeddedData::process_event(), SimpleTree::process_event(), and TruthNodeMaker::process_event().
get_chisq()
virtual double SQTrack::get_chisq () const pure virtual
Implemented in SRecTrack, and SQTrack_v1.
get_chisq_dump()
virtual double SQTrack::get_chisq_dump () const pure virtual
Implemented in SRecTrack, and SQTrack_v1.
get_chisq_target()
virtual double SQTrack::get_chisq_target () const pure virtual
Implemented in SRecTrack, and SQTrack_v1.
get_chsiq_upstream()
virtual double SQTrack::get_chsiq_upstream () const pure virtual
Implemented in SRecTrack, and SQTrack_v1.
get_hit_id()
virtual int SQTrack::get_hit_id (const int i) const pure virtual
Implemented in SRecTrack, and SQTrack_v1.
get_mom_dump()
virtual TLorentzVector SQTrack::get_mom_dump () const pure virtual
Implemented in SRecTrack, and SQTrack_v1.
get_mom_st1()
virtual TLorentzVector SQTrack::get_mom_st1 () const pure virtual
Return the track momentum at Station 1.
Implemented in SRecTrack, and SQTrack_v1.
Referenced by AnaTrack::process_event().
get_mom_st3()
virtual TLorentzVector SQTrack::get_mom_st3 () const pure virtual
Return the track momentum at Station 3.
Implemented in SRecTrack, and SQTrack_v1.
Referenced by AnaTrack::process_event().
get_mom_target()
virtual TLorentzVector SQTrack::get_mom_target () const pure virtual
Implemented in SRecTrack, and SQTrack_v1.
get_mom_vtx()
virtual TLorentzVector SQTrack::get_mom_vtx () const pure virtual
Return the track momentum at vertex.
Implemented in SRecTrack, and SQTrack_v1.
Referenced by AnaSimDst::process_event(), AnaTrack::process_event(), AnaEmbeddedData::process_event(), and TruthNodeMaker::process_event().
get_num_hits()
virtual int SQTrack::get_num_hits () const pure virtual
Return the number of hits associated to this track.
Implemented in SRecTrack, and SQTrack_v1.
get_pos_dump()
virtual TVector3 SQTrack::get_pos_dump () const pure virtual
Implemented in SRecTrack, and SQTrack_v1.
get_pos_st1()
virtual TVector3 SQTrack::get_pos_st1 () const pure virtual
Return the track position at Station 1.
Implemented in SRecTrack, and SQTrack_v1.
Referenced by AnaTrack::process_event().
get_pos_st3()
virtual TVector3 SQTrack::get_pos_st3 () const pure virtual
Return the track position at Station 3.
Implemented in SRecTrack, and SQTrack_v1.
Referenced by AnaTrack::process_event().
get_pos_target()
virtual TVector3 SQTrack::get_pos_target () const pure virtual
Implemented in SRecTrack, and SQTrack_v1.
get_pos_vtx()
virtual TVector3 SQTrack::get_pos_vtx () const pure virtual
Return the track position at vertex.
Implemented in SRecTrack, and SQTrack_v1.
Referenced by AnaSimDst::process_event(), AnaTrack::process_event(), SimpleTree::process_event(), SQTruthVertexing::process_event(), and TruthNodeMaker::process_event().
get_rec_track_id()
virtual int SQTrack::get_rec_track_id () const pure virtual
Return the track ID of associated reconstructed track. Valid only if this object holds truth track info.
Implemented in SRecTrack, and SQTrack_v1.
Referenced by SQTruthVertexing::process_event().
get_track_id()
virtual int SQTrack::get_track_id () const pure virtual
Return the track ID, which is unique per event(?).
Implemented in SRecTrack, and SQTrack_v1.
Referenced by UtilTrack::FindTrackByID(), DoEmbedding::process_event(), SimpleTree::process_event(), SQTruthVertexing::process_event(), and TruthNodeMaker::process_event().
identify()
virtual void SQTrack::identify (std::ostream & os = std::cout) const pure virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Implemented in SRecTrack, and SQTrack_v1.
isValid()
virtual int SQTrack::isValid () const pure virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Implemented in SRecTrack, and SQTrack_v1.
Reset()
virtual void SQTrack::Reset () pure virtual
Clear Event.
Reimplemented from PHObject.
Implemented in SRecTrack, and SQTrack_v1.
set_charge()
virtual void SQTrack::set_charge (const int a) pure virtual
Implemented in SRecTrack, and SQTrack_v1.
set_mom_st1()
virtual void SQTrack::set_mom_st1 (const TLorentzVector a) pure virtual
Implemented in SRecTrack, and SQTrack_v1.
Referenced by TruthNodeMaker::process_event().
set_mom_st3()
virtual void SQTrack::set_mom_st3 (const TLorentzVector a) pure virtual
Implemented in SRecTrack, and SQTrack_v1.
Referenced by TruthNodeMaker::process_event().
set_mom_vtx()
virtual void SQTrack::set_mom_vtx (const TLorentzVector a) pure virtual
Implemented in SRecTrack, and SQTrack_v1.
set_num_hits()
virtual void SQTrack::set_num_hits (const int a) pure virtual
Implemented in SRecTrack, and SQTrack_v1.
Referenced by TruthNodeMaker::process_event().
set_pos_st1()
virtual void SQTrack::set_pos_st1 (const TVector3 a) pure virtual
Implemented in SRecTrack, and SQTrack_v1.
Referenced by TruthNodeMaker::process_event().
set_pos_st3()
virtual void SQTrack::set_pos_st3 (const TVector3 a) pure virtual
Implemented in SRecTrack, and SQTrack_v1.
Referenced by TruthNodeMaker::process_event().
set_pos_vtx()
virtual void SQTrack::set_pos_vtx (const TVector3 a) pure virtual
Implemented in SRecTrack, and SQTrack_v1.
set_rec_track_id()
virtual void SQTrack::set_rec_track_id (const int a) pure virtual
Implemented in SRecTrack, and SQTrack_v1.
Referenced by TruthNodeMaker::process_event().
set_track_id()
virtual void SQTrack::set_track_id (const int a) pure virtual
Implemented in SRecTrack, and SQTrack_v1.
Referenced by DoEmbedding::process_event().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQTrack.h