Class Reference for E1039 Core & Analysis Software: UtilDimuon Namespace Reference
UtilDimuon Namespace Reference
Functions
SQDimuon * FindDimuonByID (const SQDimuonVector *vec, const int id_dim, const bool do_assert=false)
Find a dimuon by dimuon ID in the given dimuon list.
void GetX1X2 (const SQDimuon *dim, double &x1, double &x2)
OBSOLETE: Use CalcVar() instead.
void GetX1X2 (const SQDimuon *dim, float &x1, float &x2)
OBSOLETE: Use CalcVar() instead.
double GetX1 (const SQDimuon *dim)
OBSOLETE: Use CalcVar() instead.
double GetX2 (const SQDimuon *dim)
OBSOLETE: Use CalcVar() instead.
void CalcVar (const SQDimuon *dim, double &mass, double &pT, double &x1, double &x2, double &xF)
Calculate the key kinematic variables of dimuon.
void CalcVar (const TLorentzVector &p_pos, const TLorentzVector &p_neg, double &mass, double &pT, double &x1, double &x2, double &xF)
Calculate the key kinematic variables of dimuon.
void CalcVar (const SQDimuon *dim, double &mass, double &pT, double &x1, double &x2, double &xF, double &costh, double &phi)
OBSOLETE: Use CalcVar(dim, mass, pT, x1, x2, xF) and Lab2CollinsSoper(dim, costh, phi) instead.
void CalcVar (const TLorentzVector &p_pos, const TLorentzVector &p_neg, double &mass, double &pT, double &x1, double &x2, double &xF, double &costh, double &phi)
OBSOLETE: Use CalcVar(dim, mass, pT, x1, x2, xF) and Lab2CollinsSoper(dim, costh, phi) instead.
void Lab2CollinsSoper (const SQDimuon *dim, double &costh, double &phi)
Convert the momenta of muon pair from Lab frame to Collins-Soper frame.
void Lab2CollinsSoper (const TLorentzVector &p1, const TLorentzVector &p2, double &costh, double &phi)
Convert the momenta of muon pair from Lab frame to Collins-Soper frame.
void Lab2CollinsSoper (const TVector3 &p1, const TVector3 &p2, double &costh, double &phi)
Convert the momenta of muon pair from Lab frame to Collins-Soper frame.
void Lab2CollinsSoper (const double px1, const double py1, const double pz1, const double px2, const double py2, const double pz2, double &costh, double &phi)
Convert the momenta of muon pair from Lab frame to Collins-Soper frame.
Function Documentation
void UtilDimuon::CalcVar (const SQDimuon * dim, double & mass, double & pT, double & x1, double & x2, double & xF)
Calculate the key kinematic variables of dimuon.
Typical usage:
double mass, pT, x1, x2, xF;
UtilDimuon::CalcVar(dim, mass, pT, x1, x2, xF);
Definition at line 70 of file UtilDimuon.cc.
References SQDimuon::get_mom_neg(), and SQDimuon::get_mom_pos().
Referenced by CalcVar(), SQPrimaryParticleGen::CrossSectionDrellYan(), SQPrimaryParticleGen::generateDimuon(), SQPrimaryParticleGen::generateDrellYan(), SubsysRecoSignal::process_event(), AnaSimDst::process_event(), AnaEmbeddedData::process_event(), and AnaSimDimuon::process_event().
void UtilDimuon::CalcVar (const TLorentzVector & p_pos, const TLorentzVector & p_neg, double & mass, double & pT, double & x1, double & x2, double & xF)
Calculate the key kinematic variables of dimuon.
Typical usage:
double mass, pT, x1, x2, xF;
UtilDimuon::CalcVar(mom_pos, mom_neg, mass, pT, x1, x2, xF);
Definition at line 83 of file UtilDimuon.cc.
References DPGEN::bv_cms, DPGEN::ebeam, DPGEN::mp, DPGEN::p_beam(), DPGEN::p_cms, DPGEN::p_target(), DPGEN::s, and DPGEN::sqrts.
void UtilDimuon::CalcVar (const SQDimuon * dim, double & mass, double & pT, double & x1, double & x2, double & xF, double & costh, double & phi)
OBSOLETE: Use CalcVar(dim, mass, pT, x1, x2, xF) and Lab2CollinsSoper(dim, costh, phi) instead.
Typical usage:
double mass, pT, x1, x2, xF, costh, phi;
UtilDimuon::CalcVar(dim, mass, pT, x1, x2, xF, costh, phi);
Definition at line 112 of file UtilDimuon.cc.
References CalcVar(), SQDimuon::get_mom_neg(), and SQDimuon::get_mom_pos().
void UtilDimuon::CalcVar (const TLorentzVector & p_pos, const TLorentzVector & p_neg, double & mass, double & pT, double & x1, double & x2, double & xF, double & costh, double & phi)
OBSOLETE: Use CalcVar(dim, mass, pT, x1, x2, xF) and Lab2CollinsSoper(dim, costh, phi) instead.
Definition at line 118 of file UtilDimuon.cc.
References CalcVar(), and Lab2CollinsSoper().
SQDimuon * UtilDimuon::FindDimuonByID (const SQDimuonVector * vec, const int id_dim, const bool do_assert = false)
Find a dimuon by dimuon ID in the given dimuon list.
This function returns a SQDimuon pointer if successful. Otherwise it returns '0' by default, or aborts when 'do_assert' = true.
Definition at line 12 of file UtilDimuon.cc.
References SQDimuonVector::begin(), SQDimuonVector::end(), and SQDimuon::get_dimuon_id().
double UtilDimuon::GetX1 (const SQDimuon * dim)
OBSOLETE: Use CalcVar() instead.
Definition at line 47 of file UtilDimuon.cc.
References GetX1X2().
void UtilDimuon::GetX1X2 (const SQDimuon * dim, double & x1, double & x2)
OBSOLETE: Use CalcVar() instead.
Definition at line 25 of file UtilDimuon.cc.
References E_BEAM, SQDimuon::get_mom_neg(), SQDimuon::get_mom_pos(), M_P, DPGEN::p_beam(), DPGEN::p_cms, and DPGEN::p_target().
Referenced by GetX1(), GetX1X2(), and GetX2().
void UtilDimuon::GetX1X2 (const SQDimuon * dim, float & x1, float & x2)
OBSOLETE: Use CalcVar() instead.
Definition at line 38 of file UtilDimuon.cc.
References GetX1X2().
double UtilDimuon::GetX2 (const SQDimuon * dim)
OBSOLETE: Use CalcVar() instead.
Definition at line 55 of file UtilDimuon.cc.
References GetX1X2().
void UtilDimuon::Lab2CollinsSoper (const SQDimuon * dim, double & costh, double & phi)
Convert the momenta of muon pair from Lab frame to Collins-Soper frame.
Definition at line 125 of file UtilDimuon.cc.
References SQDimuon::get_mom_neg(), and SQDimuon::get_mom_pos().
Referenced by CalcVar(), SQPrimaryParticleGen::generateDimuon(), Lab2CollinsSoper(), AnaSimDimuon::process_event(), and AnaEmbeddedData::process_event().
void UtilDimuon::Lab2CollinsSoper (const TLorentzVector & p1, const TLorentzVector & p2, double & costh, double & phi)
Convert the momenta of muon pair from Lab frame to Collins-Soper frame.
Definition at line 131 of file UtilDimuon.cc.
References Lab2CollinsSoper().
void UtilDimuon::Lab2CollinsSoper (const TVector3 & p1, const TVector3 & p2, double & costh, double & phi)
Convert the momenta of muon pair from Lab frame to Collins-Soper frame.
Definition at line 137 of file UtilDimuon.cc.
References Lab2CollinsSoper().
void UtilDimuon::Lab2CollinsSoper (const double px1, const double py1, const double pz1, const double px2, const double py2, const double pz2, double & costh, double & phi)
Convert the momenta of muon pair from Lab frame to Collins-Soper frame.
The code was written originally by Suguru Tamamushi. Only the cos(theta) and phi are returned at present.
Definition at line 147 of file UtilDimuon.cc.