SeaQuest Offline Software: updateAlignment Namespace Reference
updateAlignment Namespace Reference
Variables
tuple parser = OptionParser('Usage: %prog [options]')
tuple con = MySQLdb.connect(host = options.server, port = options.port, user = 'seaguest', passwd = 'qqbar2mu+mu-')
tuple cur = con.cursor()
list tableNames = [row[0] for row in cur.fetchall()]
list survey = []
tuple vals = line.strip()
list filedNames = survey[0]
string query = 'UPDATE %s.Planes SET '
Variable Documentation
tuple updateAlignment.con = MySQLdb.connect(host = options.server, port = options.port, user = 'seaguest', passwd = 'qqbar2mu+mu-')
Definition at line 16 of file updateAlignment.py.
Referenced by GeomSvc.init(), and main().
tuple updateAlignment.cur = con.cursor()
Definition at line 17 of file updateAlignment.py.
list updateAlignment.filedNames = survey[0]
Definition at line 41 of file updateAlignment.py.
tuple updateAlignment.parser = OptionParser('Usage: %prog [options]')
Definition at line 8 of file updateAlignment.py.
list updateAlignment.query = 'UPDATE %s.Planes SET '
Definition at line 43 of file updateAlignment.py.
Referenced by ReadMySql.FillSQEvent(), ReadMySql.FillSQHitMap(), ReadMySql.FillSQRun(), ReadMySql.FillSQSpill(), GeomSvc.init(), and main().
list updateAlignment.survey = []
Definition at line 35 of file updateAlignment.py.
list updateAlignment.tableNames = [row[0] for row in cur.fetchall()]
Definition at line 21 of file updateAlignment.py.
Referenced by MySQLSvc.initBakWriter(), MySQLSvc.initWriter(), and MySQLSvc.pushToFinalTables().
tuple updateAlignment.vals = line.strip()
Definition at line 37 of file updateAlignment.py.