SeaQuest Offline Software: PHG4PolyconSteppingAction Class Reference
PHG4PolyconSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4PolyconSteppingAction.h>
Public Member Functions
PHG4PolyconSteppingAction (PHG4PolyconDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4PolyconSteppingAction ()
destructor
bool UserSteppingAction (const G4Step *, bool)
stepping action
void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
void SaveLightYield (const int i=1)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4PolyconDetector * detector_
pointer to the detector
const PHParameters * params
PHG4HitContainer * hits_
pointer to hit container
PHG4Hit * hit
PHG4Shower * saveshower
G4VPhysicalVolume * savevolpre
G4VPhysicalVolume * savevolpost
int save_light_yield
int savetrackid
int saveprestepstatus
int savepoststepstatus
int active
int IsBlackHole
int use_g4_steps
double zmin
double zmax
double tmin
double tmax
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 15 of file PHG4PolyconSteppingAction.h.
Constructor & Destructor Documentation
PHG4PolyconSteppingAction::PHG4PolyconSteppingAction (PHG4PolyconDetector * detector, const PHParameters * parameters)
constructor
Definition at line 25 of file PHG4PolyconSteppingAction.cc.
References zmax, and zmin.
PHG4PolyconSteppingAction::~PHG4PolyconSteppingAction () virtual
destructor
Definition at line 50 of file PHG4PolyconSteppingAction.cc.
References hit.
Member Function Documentation
void PHG4PolyconSteppingAction::SaveLightYield (const int i = 1) inline
Definition at line 30 of file PHG4PolyconSteppingAction.h.
References save_light_yield.
void PHG4PolyconSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 306 of file PHG4PolyconSteppingAction.cc.
References detector_, PHG4Detector::GetName(), hits_, IsBlackHole, and PHG4PolyconDetector::SuperDetector().
bool PHG4PolyconSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 60 of file PHG4PolyconSteppingAction.cc.
References active, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4PolyconDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4Hit::get_x(), PHG4Hit::get_z(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), hit, hits_, IsBlackHole, PHG4PolyconDetector::IsInCylinder(), PHG4Hit::Reset(), save_light_yield, savepoststepstatus, saveprestepstatus, saveshower, savetrackid, savevolpost, savevolpre, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_light_yield(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4PolyconDetector::SuperDetector(), tmax, tmin, use_g4_steps, zmax, and zmin.
Member Data Documentation
int PHG4PolyconSteppingAction::active private
Definition at line 47 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction().
PHG4PolyconDetector* PHG4PolyconSteppingAction::detector_ private
pointer to the detector
Definition at line 33 of file PHG4PolyconSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4PolyconSteppingAction::hit private
Definition at line 39 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4PolyconSteppingAction().
PHG4HitContainer* PHG4PolyconSteppingAction::hits_ private
pointer to hit container
Definition at line 38 of file PHG4PolyconSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4PolyconSteppingAction::IsBlackHole private
Definition at line 48 of file PHG4PolyconSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
const PHParameters* PHG4PolyconSteppingAction::params private
Definition at line 35 of file PHG4PolyconSteppingAction.h.
int PHG4PolyconSteppingAction::save_light_yield private
Definition at line 43 of file PHG4PolyconSteppingAction.h.
Referenced by SaveLightYield(), and UserSteppingAction().
int PHG4PolyconSteppingAction::savepoststepstatus private
Definition at line 46 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4PolyconSteppingAction::saveprestepstatus private
Definition at line 45 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4PolyconSteppingAction::saveshower private
Definition at line 40 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4PolyconSteppingAction::savetrackid private
Definition at line 44 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4PolyconSteppingAction::savevolpost private
Definition at line 42 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4PolyconSteppingAction::savevolpre private
Definition at line 41 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction().
double PHG4PolyconSteppingAction::tmax private
Definition at line 53 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction().
double PHG4PolyconSteppingAction::tmin private
Definition at line 52 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4PolyconSteppingAction::use_g4_steps private
Definition at line 49 of file PHG4PolyconSteppingAction.h.
Referenced by UserSteppingAction().
double PHG4PolyconSteppingAction::zmax private
Definition at line 51 of file PHG4PolyconSteppingAction.h.
Referenced by PHG4PolyconSteppingAction(), and UserSteppingAction().
double PHG4PolyconSteppingAction::zmin private
Definition at line 50 of file PHG4PolyconSteppingAction.h.
Referenced by PHG4PolyconSteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4PolyconSteppingAction.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4PolyconSteppingAction.cc