Class Reference for E1039 Core & Analysis Software: OnlMonHodo Class Reference
OnlMonHodo Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonHodo.h>
Public Types
enum HodoType_t {
H1X , H2X , H3X , H4X ,
H1Y , H2Y , H4Y1 , H4Y2 ,
DP1T , DP1B , DP2T , DP2B
}
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Public Member Functions
OnlMonHodo (const HodoType_t type)
virtual ~OnlMonHodo ()
OnlMonClient * Clone ()
int InitOnlMon (PHCompositeNode *topNode)
int InitRunOnlMon (PHCompositeNode *topNode)
int ProcessEventOnlMon (PHCompositeNode *topNode)
int EndOnlMon (PHCompositeNode *topNode)
int FindAllMonHist ()
int DrawMonitor ()
Public Member Functions inherited from OnlMonClient
OnlMonClient ()
virtual ~OnlMonClient ()
void Title (const std::string &title)
std::string Title ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void GetBasicID (int *run_id=0, int *spill_id=0, int *event_id=0, int *spill_id_min=0, int *spill_id_max=0)
void GetBasicCount (int *n_evt=0, int *n_sp=0)
int StartMonitor ()
TH1 * FindMonHist (const std::string name, const bool non_null=true)
int SendHist (TSocket *sock, int sp_min, int sp_max)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Attributes
static const int N_DET = 2
Additional Inherited Members
Static Public Member Functions inherited from OnlMonClient
static void SetClearUsFlag (const bool val)
static bool GetClearUsFlag ()
Protected Types inherited from OnlMonClient
enum HistMode_t { MODE_ADD , MODE_UPDATE }
Protected Member Functions inherited from OnlMonClient
void RegisterHist (TH1 *h1, const HistMode_t mode=MODE_ADD)
void NumCanvases (const int num)
int NumCanvases ()
OnlMonCanvas * GetCanvas (const int num=0)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 5 of file OnlMonHodo.h.
Member Enumeration Documentation
HodoType_t
enum OnlMonHodo::HodoType_t
Enumerator
H1X
H2X
H3X
H4X
H1Y
H2Y
H4Y1
H4Y2
DP1T
DP1B
DP2T
DP2B
Definition at line 7 of file OnlMonHodo.h.
Constructor & Destructor Documentation
OnlMonHodo()
OnlMonHodo::OnlMonHodo (const HodoType_t type)
Definition at line 20 of file OnlMonHodo.cc.
References DP1B, DP1T, DP2B, DP2T, H1X, H1Y, H2X, H2Y, H3X, H4X, H4Y1, H4Y2, Fun4AllBase::Name(), OnlMonClient::NumCanvases(), and OnlMonClient::Title().
Referenced by Clone().
~OnlMonHodo()
virtual OnlMonHodo::~OnlMonHodo () inline virtual
Definition at line 23 of file OnlMonHodo.h.
Member Function Documentation
Clone()
OnlMonClient* OnlMonHodo::Clone () inline virtual
Reimplemented from OnlMonClient.
Definition at line 24 of file OnlMonHodo.h.
References OnlMonHodo().
DrawMonitor()
int OnlMonHodo::DrawMonitor () virtual
Reimplemented from OnlMonClient.
Definition at line 184 of file OnlMonHodo.cc.
References OnlMonCanvas::AddMessage(), UtilHist::AutoSetRange(), UtilHist::AutoSetRangeY(), OnlMonClient::GetCanvas(), OnlMonCanvas::GetMainPad(), N_DET, OnlMonCanvas::OK, OnlMonCanvas::SetStatus(), and OnlMonCanvas::WARN.
EndOnlMon()
int OnlMonHodo::EndOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 151 of file OnlMonHodo.cc.
References Fun4AllReturnCodes::EVENT_OK.
FindAllMonHist()
int OnlMonHodo::FindAllMonHist () virtual
Reimplemented from OnlMonClient.
Definition at line 156 of file OnlMonHodo.cc.
References OnlMonClient::FindMonHist(), and N_DET.
InitOnlMon()
int OnlMonHodo::InitOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 39 of file OnlMonHodo.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRunOnlMon()
int OnlMonHodo::InitRunOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 44 of file OnlMonHodo.cc.
References Fun4AllReturnCodes::ABORTEVENT, DP1B, DP1T, DP2B, DP2T, Fun4AllReturnCodes::EVENT_OK, GeomSvc::getPlaneNElements(), H1X, H1Y, H2X, H2Y, H3X, H4X, H4Y1, H4Y2, GeomSvc::instance(), N_DET, and OnlMonClient::RegisterHist().
ProcessEventOnlMon()
int OnlMonHodo::ProcessEventOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 126 of file OnlMonHodo.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, UtilSQHit::FindHitsFast(), and N_DET.
Member Data Documentation
N_DET
const int OnlMonHodo::N_DET = 2 static
Definition at line 8 of file OnlMonHodo.h.
Referenced by DrawMonitor(), FindAllMonHist(), InitRunOnlMon(), and ProcessEventOnlMon().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonHodo.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonHodo.cc