E1039 Software: PHGenFit::Measurement Class Reference
PHGenFit::Measurement Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHGenFitPkg/PHGenFit/Measurement.h>
Public Member Functions
Measurement ()
ctor
virtual ~Measurement ()
dtor
genfit::AbsMeasurement * getMeasurement ()
unsigned int get_cluster_ID () const
void set_cluster_ID (unsigned int clusterId)
Protected Attributes
genfit::AbsMeasurement * _measurement
unsigned int _clusterID
Detailed Description
Definition at line 16 of file Measurement.h.
Constructor & Destructor Documentation
Measurement()
PHGenFit::Measurement::Measurement () inline
ctor
Definition at line 19 of file Measurement.h.
References ~Measurement().
~Measurement()
PHGenFit::Measurement::~Measurement () virtual
dtor
Definition at line 11 of file Measurement.cc.
Referenced by Measurement().
Member Function Documentation
get_cluster_ID()
unsigned int PHGenFit::Measurement::get_cluster_ID () const inline
Definition at line 34 of file Measurement.h.
References _clusterID.
Referenced by PHGenFit::Track::addMeasurement().
getMeasurement()
genfit::AbsMeasurement* PHGenFit::Measurement::getMeasurement () inline
Definition at line 30 of file Measurement.h.
References _measurement.
Referenced by PHGenFit::Track::addMeasurement().
set_cluster_ID()
void PHGenFit::Measurement::set_cluster_ID (unsigned int clusterId) inline
Definition at line 38 of file Measurement.h.
References _clusterID.
Member Data Documentation
_clusterID
unsigned int PHGenFit::Measurement::_clusterID protected
Definition at line 45 of file Measurement.h.
Referenced by get_cluster_ID(), and set_cluster_ID().
_measurement
genfit::AbsMeasurement* PHGenFit::Measurement::_measurement protected
Definition at line 44 of file Measurement.h.
Referenced by getMeasurement(), PHGenFit::PlanarMeasurement::init(), and PHGenFit::SpacepointMeasurement::init().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHGenFitPkg/PHGenFit/Measurement.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHGenFitPkg/PHGenFit/Measurement.cc