Class Reference for E1039 Core & Analysis Software: OnlMonProp Class Reference
OnlMonProp Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonProp.h>
Public Types
enum PropType_t { P1, P2 }
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Public Member Functions
OnlMonProp (const PropType_t type)
virtual ~OnlMonProp ()
OnlMonClient * Clone ()
int InitOnlMon (PHCompositeNode *topNode)
int InitRunOnlMon (PHCompositeNode *topNode)
int ProcessEventOnlMon (PHCompositeNode *topNode)
int EndOnlMon (PHCompositeNode *topNode)
int FindAllMonHist ()
int DrawMonitor ()
Public Member Functions inherited from OnlMonClient
OnlMonClient ()
virtual ~OnlMonClient ()
void Title (const std::string &title)
std::string Title ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void GetBasicID (int *run_id=0, int *spill_id=0, int *event_id=0, int *spill_id_min=0, int *spill_id_max=0)
void GetBasicCount (int *n_evt=0, int *n_sp=0)
int StartMonitor ()
TH1 * FindMonHist (const std::string name, const bool non_null=true)
int SendHist (TSocket *sock, int sp_min, int sp_max)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Attributes
static const int N_PL = 4
Additional Inherited Members
Static Public Member Functions inherited from OnlMonClient
static void SetClearUsFlag (const bool val)
static bool GetClearUsFlag ()
Protected Types inherited from OnlMonClient
enum HistMode_t { MODE_ADD, MODE_UPDATE }
Protected Member Functions inherited from OnlMonClient
void RegisterHist (TH1 *h1, const HistMode_t mode=MODE_ADD)
void NumCanvases (const int num)
int NumCanvases ()
OnlMonCanvas * GetCanvas (const int num=0)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 5 of file OnlMonProp.h.
Member Enumeration Documentation
enum OnlMonProp::PropType_t
Enumerator
P1
P2
Definition at line 7 of file OnlMonProp.h.
Constructor & Destructor Documentation
OnlMonProp::OnlMonProp (const PropType_t type)
Definition at line 17 of file OnlMonProp.cc.
References Fun4AllBase::Name(), OnlMonClient::NumCanvases(), P1, P2, and OnlMonClient::Title().
Referenced by Clone().
virtual OnlMonProp::~OnlMonProp () inline virtual
Definition at line 18 of file OnlMonProp.h.
Member Function Documentation
OnlMonClient* OnlMonProp::Clone () inline virtual
Reimplemented from OnlMonClient.
Definition at line 19 of file OnlMonProp.h.
References OnlMonProp().
int OnlMonProp::DrawMonitor () virtual
Reimplemented from OnlMonClient.
Definition at line 114 of file OnlMonProp.cc.
References UtilHist::AutoSetRange(), OnlMonClient::GetCanvas(), OnlMonCanvas::GetMainPad(), and N_PL.
int OnlMonProp::EndOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 93 of file OnlMonProp.cc.
References Fun4AllReturnCodes::EVENT_OK.
int OnlMonProp::FindAllMonHist () virtual
Reimplemented from OnlMonClient.
Definition at line 98 of file OnlMonProp.cc.
References OnlMonClient::FindMonHist(), and N_PL.
int OnlMonProp::InitOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 26 of file OnlMonProp.cc.
References Fun4AllReturnCodes::EVENT_OK.
int OnlMonProp::InitRunOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 31 of file OnlMonProp.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, GeomSvc::getDetectorIDs(), GeomSvc::getDetectorName(), GeomSvc::getPlaneNElements(), GeomSvc::instance(), N_PL, P1, P2, and OnlMonClient::RegisterHist().
int OnlMonProp::ProcessEventOnlMon (PHCompositeNode * topNode) virtual
Reimplemented from OnlMonClient.
Definition at line 77 of file OnlMonProp.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and N_PL.
Member Data Documentation
const int OnlMonProp::N_PL = 4 static
Definition at line 8 of file OnlMonProp.h.
Referenced by DrawMonitor(), FindAllMonHist(), InitRunOnlMon(), and ProcessEventOnlMon().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonProp.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonProp.cc