E1039 Software: PHG4TruthEventAction Class Reference
PHG4TruthEventAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4TruthEventAction.h>
Public Member Functions
PHG4TruthEventAction (void)
constructor
virtual ~PHG4TruthEventAction (void)
destuctor
void BeginOfEventAction (const G4Event *)
void EndOfEventAction (const G4Event *)
int ResetEvent (PHCompositeNode *)
void SetInterfacePointers (PHCompositeNode *)
get relevant nodes from top node passed as argument
void AddTrackidToWritelist (const G4int trackid)
add id into track list
Public Member Functions inherited from PHG4EventAction
PHG4EventAction (void)
virtual ~PHG4EventAction ()
Private Member Functions
void SearchNode (PHCompositeNode *topNode)
void PruneShowers ()
void ProcessShowers ()
Private Attributes
std::set< G4int > writeList_
set of track ids to be written out
PHG4TruthInfoContainer * truthInfoList_
pointer to truth information container
int prev_existing_lower_key
int prev_existing_upper_key
std::map< int, PHG4HitContainer * > hitmap_
Detailed Description
Definition at line 16 of file PHG4TruthEventAction.h.
Constructor & Destructor Documentation
PHG4TruthEventAction()
PHG4TruthEventAction::PHG4TruthEventAction (void)
constructor
Definition at line 32 of file PHG4TruthEventAction.cc.
~PHG4TruthEventAction()
virtual PHG4TruthEventAction::~PHG4TruthEventAction (void) inline virtual
destuctor
Definition at line 25 of file PHG4TruthEventAction.h.
References AddTrackidToWritelist(), BeginOfEventAction(), EndOfEventAction(), ProcessShowers(), PruneShowers(), ResetEvent(), SearchNode(), and SetInterfacePointers().
Member Function Documentation
AddTrackidToWritelist()
void PHG4TruthEventAction::AddTrackidToWritelist (const G4int trackid)
add id into track list
Definition at line 192 of file PHG4TruthEventAction.cc.
References writeList_.
Referenced by PHG4TruthTrackingAction::PostUserTrackingAction(), and ~PHG4TruthEventAction().
BeginOfEventAction()
void PHG4TruthEventAction::BeginOfEventAction (const G4Event * evt) virtual
Reimplemented from PHG4EventAction.
Definition at line 39 of file PHG4TruthEventAction.cc.
References PHG4TruthInfoContainer::GetMap(), prev_existing_lower_key, prev_existing_upper_key, and truthInfoList_.
Referenced by ~PHG4TruthEventAction().
EndOfEventAction()
void PHG4TruthEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from PHG4EventAction.
Definition at line 55 of file PHG4TruthEventAction.cc.
References PHG4TruthInfoContainer::AddEmbededTrkId(), PHG4TruthInfoContainer::AddEmbededVtxId(), PHG4TruthInfoContainer::delete_particle(), PHG4TruthInfoContainer::delete_vtx(), PHG4UserPrimaryParticleInformation::get_embed(), PHG4Particle::get_parent_id(), PHG4UserPrimaryParticleInformation::get_user_track_id(), PHG4UserPrimaryParticleInformation::get_user_vtx_id(), PHG4Particle::get_vtx_id(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetParticleRange(), PHG4TruthInfoContainer::GetVtxRange(), prev_existing_lower_key, prev_existing_upper_key, ProcessShowers(), PruneShowers(), truthInfoList_, and writeList_.
Referenced by ~PHG4TruthEventAction().
ProcessShowers()
void PHG4TruthEventAction::ProcessShowers () private
Definition at line 322 of file PHG4TruthEventAction.cc.
References PHG4Shower::begin_g4hit_id(), PHG4Shower::end_g4hit_id(), PHG4HitContainer::findHit(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_light_yield(), PHG4Particle::get_pid(), PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), PHG4Hit::get_x(), PHG4Hit::get_y(), PHG4Hit::get_z(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetShowerRange(), PHG4TruthInfoContainer::GetVtx(), hitmap_, PHWHERE, PHG4Shower::set_covar(), PHG4Shower::set_edep(), PHG4Shower::set_eh_ratio(), PHG4Shower::set_eion(), PHG4Shower::set_light_yield(), PHG4Shower::set_nhits(), PHG4Shower::set_x(), PHG4Shower::set_y(), PHG4Shower::set_z(), and truthInfoList_.
Referenced by EndOfEventAction(), and ~PHG4TruthEventAction().
PruneShowers()
void PHG4TruthEventAction::PruneShowers () private
Definition at line 242 of file PHG4TruthEventAction.cc.
References PHG4Shower::begin_g4hit_id(), PHG4Shower::begin_g4particle_id(), PHG4TruthInfoContainer::delete_shower(), PHG4Shower::empty_g4hit_id(), PHG4Shower::empty_g4particle_id(), PHG4Shower::end_g4hit_id(), PHG4Shower::end_g4particle_id(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetShowerRange(), hitmap_, PHG4Shower::remove_g4hit_volume(), PHG4Shower::remove_g4particle_id(), and truthInfoList_.
Referenced by EndOfEventAction(), and ~PHG4TruthEventAction().
ResetEvent()
int PHG4TruthEventAction::ResetEvent (PHCompositeNode *) virtual
Reimplemented from PHG4EventAction.
Definition at line 237 of file PHG4TruthEventAction.cc.
References writeList_.
Referenced by PHG4TruthSubsystem::ResetEvent(), and ~PHG4TruthEventAction().
SearchNode()
void PHG4TruthEventAction::SearchNode (PHCompositeNode * topNode) private
Definition at line 210 of file PHG4TruthEventAction.cc.
References PHDataNode< T >::getData(), hitmap_, and PHNodeIterator::ls().
Referenced by SetInterfacePointers(), and ~PHG4TruthEventAction().
SetInterfacePointers()
void PHG4TruthEventAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
get relevant nodes from top node passed as argument
Reimplemented from PHG4EventAction.
Definition at line 197 of file PHG4TruthEventAction.cc.
References SearchNode(), and truthInfoList_.
Referenced by PHG4TruthSubsystem::process_event(), and ~PHG4TruthEventAction().
Member Data Documentation
hitmap_
std::map<int,PHG4HitContainer*> PHG4TruthEventAction::hitmap_ private
Definition at line 54 of file PHG4TruthEventAction.h.
Referenced by ProcessShowers(), PruneShowers(), and SearchNode().
prev_existing_lower_key
int PHG4TruthEventAction::prev_existing_lower_key private
Definition at line 51 of file PHG4TruthEventAction.h.
Referenced by BeginOfEventAction(), and EndOfEventAction().
prev_existing_upper_key
int PHG4TruthEventAction::prev_existing_upper_key private
Definition at line 52 of file PHG4TruthEventAction.h.
Referenced by BeginOfEventAction(), and EndOfEventAction().
truthInfoList_
PHG4TruthInfoContainer* PHG4TruthEventAction::truthInfoList_ private
pointer to truth information container
Definition at line 49 of file PHG4TruthEventAction.h.
Referenced by BeginOfEventAction(), EndOfEventAction(), ProcessShowers(), PruneShowers(), and SetInterfacePointers().
writeList_
std::set<G4int> PHG4TruthEventAction::writeList_ private
set of track ids to be written out
Definition at line 46 of file PHG4TruthEventAction.h.
Referenced by AddTrackidToWritelist(), EndOfEventAction(), and ResetEvent().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4TruthEventAction.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4main/PHG4TruthEventAction.cc