SeaQuest Offline Software: AnaFit Class Reference
AnaFit Class Reference
Class for fitting R-T histogram.
#include </home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/RTCurveFitter.h>
Public Member Functions
AnaFit ()
virtual ~AnaFit ()
virtual double operator() (const std::vector< double > &r) const
virtual double Up () const
void InitInput (TH2 *h2, double r_max, TGraph *gr_init)
void DoFit ()
void CalcChi2 (const std::vector< double > &pars, double &chi2, int &ndf) const
double EvalR (const double t, const double t1, const double t0, const TSpline3 *spl) const
double EvalR (const double t) const
TSpline3 * GetResultSpline () const
double GetResultDR () const
double GetResultT1 () const
double GetResultT0 () const
Protected Attributes
TFitterMinuit * m_minuit
TH2 * m_h2_RT
double m_t_min
double m_t_max
double m_r_max
double m_t1
double m_t0
double m_dr
TSpline3 * m_spl_t2r
Static Protected Attributes
static const int N_PT = 7
N of R-T points except the two edge points.
Private Member Functions
TSpline3 * CreateSpline (const std::vector< double > &pars) const
Detailed Description
Class for fitting R-T histogram.
Definition at line 12 of file RTCurveFitter.h.
Constructor & Destructor Documentation
AnaFit::AnaFit () inline
Definition at line 27 of file RTCurveFitter.h.
References m_spl_t2r.
virtual AnaFit::~AnaFit () inline virtual
Definition at line 28 of file RTCurveFitter.h.
Member Function Documentation
void AnaFit::CalcChi2 (const std::vector< double > & pars, double & chi2, int & ndf) const inline
N of parameters = N_PT + 3 pars[0] = T1 [1] = T0 [2] = DR (constant over T) [3]...[3+N_PT-1] = R at each T points
Note that the T position of each point is not fixed but depends on T1 & T0.
Definition at line 66 of file RTCurveFitter.h.
References CreateSpline(), EvalR(), m_h2_RT, m_minuit, and convertRTCurve::t0.
Referenced by DoFit(), and operator()().
TSpline3 * AnaFit::CreateSpline (const std::vector< double > & pars) const private
Definition at line 165 of file RTCurveFitter.h.
References m_r_max, N_PT, and convertRTCurve::t0.
Referenced by CalcChi2(), and DoFit().
void AnaFit::DoFit () inline
Definition at line 124 of file RTCurveFitter.h.
References CalcChi2(), CreateSpline(), m_dr, m_minuit, m_spl_t2r, m_t0, and m_t1.
double AnaFit::EvalR (const double t, const double t1, const double t0, const TSpline3 * spl) const
Definition at line 148 of file RTCurveFitter.h.
References m_r_max.
Referenced by CalcChi2(), and EvalR().
double AnaFit::EvalR (const double t) const
Definition at line 160 of file RTCurveFitter.h.
References EvalR(), m_spl_t2r, m_t0, and m_t1.
double AnaFit::GetResultDR () const inline
Definition at line 41 of file RTCurveFitter.h.
References m_dr.
TSpline3* AnaFit::GetResultSpline () const inline
Definition at line 40 of file RTCurveFitter.h.
References m_spl_t2r.
double AnaFit::GetResultT0 () const inline
Definition at line 43 of file RTCurveFitter.h.
References m_t0.
double AnaFit::GetResultT1 () const inline
Definition at line 42 of file RTCurveFitter.h.
References m_t1.
void AnaFit::InitInput (TH2 * h2, double r_max, TGraph * gr_init) inline
Definition at line 96 of file RTCurveFitter.h.
References m_h2_RT, m_minuit, m_r_max, m_t_max, m_t_min, N_PT, and convertRTCurve::t0.
double AnaFit::operator() (const std::vector< double > & r) const inline virtual
Definition at line 49 of file RTCurveFitter.h.
References CalcChi2().
virtual double AnaFit::Up () const inline virtual
Definition at line 31 of file RTCurveFitter.h.
Member Data Documentation
double AnaFit::m_dr protected
Definition at line 23 of file RTCurveFitter.h.
Referenced by DoFit(), and GetResultDR().
TH2* AnaFit::m_h2_RT protected
Definition at line 16 of file RTCurveFitter.h.
Referenced by CalcChi2(), and InitInput().
TFitterMinuit* AnaFit::m_minuit protected
Definition at line 15 of file RTCurveFitter.h.
Referenced by CalcChi2(), DoFit(), and InitInput().
double AnaFit::m_r_max protected
Definition at line 19 of file RTCurveFitter.h.
Referenced by CreateSpline(), EvalR(), and InitInput().
TSpline3* AnaFit::m_spl_t2r protected
Definition at line 24 of file RTCurveFitter.h.
Referenced by AnaFit(), DoFit(), EvalR(), and GetResultSpline().
double AnaFit::m_t0 protected
Definition at line 22 of file RTCurveFitter.h.
Referenced by DoFit(), EvalR(), and GetResultT0().
double AnaFit::m_t1 protected
Definition at line 21 of file RTCurveFitter.h.
Referenced by DoFit(), EvalR(), and GetResultT1().
double AnaFit::m_t_max protected
Definition at line 18 of file RTCurveFitter.h.
Referenced by InitInput().
double AnaFit::m_t_min protected
Definition at line 17 of file RTCurveFitter.h.
Referenced by InitInput().
const int AnaFit::N_PT = 7 static protected
N of R-T points except the two edge points.
Definition at line 14 of file RTCurveFitter.h.
Referenced by CreateSpline(), and InitInput().
The documentation for this class was generated from the following file:
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/RTCurveFitter.h