Class Reference for E1039 Core & Analysis Software: PHG4DetectorGroupSubsystem Class Reference
PHG4DetectorGroupSubsystem Class Reference abstract
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4DetectorGroupSubsystem.h>
Public Types
enum FILE_TYPE { none = 0 , xml = 1 , root = 2 }
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Public Member Functions
virtual ~PHG4DetectorGroupSubsystem ()
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitRunSubsystem (PHCompositeNode *)
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHG4ParametersContainer * GetParamsContainer () const
void set_double_param (const int detid, const std::string &name, const double dval)
double get_double_param (const int detid, const std::string &name) const
void set_int_param (const int detid, const std::string &name, const int ival)
int get_int_param (const int detid, const std::string &name) const
void set_string_param (const int detid, const std::string &name, const std::string &sval)
std::string get_string_param (const int detid, const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
int SaveParamsToFile (const FILE_TYPE ftyp)
int ReadParamsFromFile (const std::string &name, const FILE_TYPE ftyp, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int detid, const int i=1)
void SetAbsorberActive (const int detid, const int i=1)
void SetAbsorberTruth (const int detid, const int i=1)
void BlackHole (const int detid, const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
virtual void SetDefaultParameters ()=0
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector (void) const
return pointer to created detector object
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParameters * GetParams ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int process_event (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
PHG4DetectorGroupSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void AddDetId (const int i)
std::pair< std::set< int >::const_iterator, std::set< int >::const_iterator > GetDetIds () const
void set_default_double_param (const int detid, const std::string &name, const double dval)
void set_default_int_param (const int detid, const std::string &name, const int ival)
void set_default_string_param (const int detid, const std::string &name, const std::string &sval)
int BeginRunExecuted () const
void PrintDefaultParams () const
void PrintMacroParams () const
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Protected Attributes inherited from PHG4Subsystem
bool overlapcheck
PHParameters * params
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 12 of file PHG4DetectorGroupSubsystem.h.
Member Enumeration Documentation
FILE_TYPE
enum PHG4DetectorGroupSubsystem::FILE_TYPE
Enumerator
none
xml
root
Definition at line 15 of file PHG4DetectorGroupSubsystem.h.
Constructor & Destructor Documentation
~PHG4DetectorGroupSubsystem()
virtual PHG4DetectorGroupSubsystem::~PHG4DetectorGroupSubsystem () inline virtual
Definition at line 22 of file PHG4DetectorGroupSubsystem.h.
PHG4DetectorGroupSubsystem()
PHG4DetectorGroupSubsystem::PHG4DetectorGroupSubsystem (const std::string & name = "GenericSubsystem", const int lyr = 0) protected
Definition at line 22 of file PHG4DetectorGroupSubsystem.cc.
References Fun4AllBase::Name().
Member Function Documentation
AddDetId()
void PHG4DetectorGroupSubsystem::AddDetId (const int i) inline protected
Definition at line 73 of file PHG4DetectorGroupSubsystem.h.
BeginRunExecuted()
int PHG4DetectorGroupSubsystem::BeginRunExecuted () const inline protected
Definition at line 81 of file PHG4DetectorGroupSubsystem.h.
BlackHole()
void PHG4DetectorGroupSubsystem::BlackHole (const int detid, const int i = 1)
Definition at line 549 of file PHG4DetectorGroupSubsystem.cc.
References set_int_param().
CheckOverlap()
bool PHG4DetectorGroupSubsystem::CheckOverlap () const inline
Definition at line 38 of file PHG4DetectorGroupSubsystem.h.
get_double_param()
double PHG4DetectorGroupSubsystem::get_double_param (const int detid, const std::string & name) const
Definition at line 199 of file PHG4DetectorGroupSubsystem.cc.
References PHG4Parameters::get_double_param(), and PHG4ParametersContainer::GetParameters().
get_filetype()
FILE_TYPE PHG4DetectorGroupSubsystem::get_filetype () const inline
Definition at line 50 of file PHG4DetectorGroupSubsystem.h.
Referenced by InitRun().
get_int_param()
int PHG4DetectorGroupSubsystem::get_int_param (const int detid, const std::string & name) const
Definition at line 242 of file PHG4DetectorGroupSubsystem.cc.
References PHG4Parameters::get_int_param(), and PHG4ParametersContainer::GetParameters().
get_string_param()
string PHG4DetectorGroupSubsystem::get_string_param (const int detid, const std::string & name) const
Definition at line 287 of file PHG4DetectorGroupSubsystem.cc.
References PHG4Parameters::get_string_param(), and PHG4ParametersContainer::GetParameters().
GetDetIds()
std::pair<std::set<int>::const_iterator, std::set<int>::const_iterator> PHG4DetectorGroupSubsystem::GetDetIds () const inline protected
Definition at line 74 of file PHG4DetectorGroupSubsystem.h.
GetLayer()
int PHG4DetectorGroupSubsystem::GetLayer () const inline
Definition at line 65 of file PHG4DetectorGroupSubsystem.h.
GetParamsContainer()
PHG4ParametersContainer* PHG4DetectorGroupSubsystem::GetParamsContainer () const inline
Definition at line 39 of file PHG4DetectorGroupSubsystem.h.
Referenced by UpdateParametersWithMacro().
Init()
int PHG4DetectorGroupSubsystem::Init (PHCompositeNode *) final virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 42 of file PHG4DetectorGroupSubsystem.cc.
References InitSubsystem(), Fun4AllBase::Name(), and PHG4ParametersContainer::set_name().
InitializeParameters()
void PHG4DetectorGroupSubsystem::InitializeParameters () protected
Definition at line 401 of file PHG4DetectorGroupSubsystem.cc.
References PHG4ParametersContainer::AddPHG4Parameters(), PHG4ParametersContainer::GetParametersToModify(), Fun4AllBase::Name(), set_default_int_param(), PHG4Parameters::set_double_param(), PHG4Parameters::set_int_param(), PHG4Parameters::set_string_param(), and SetDefaultParameters().
InitRun()
int PHG4DetectorGroupSubsystem::InitRun (PHCompositeNode *) final virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 50 of file PHG4DetectorGroupSubsystem.cc.
References PHCompositeNode::addNode(), PHG4ParametersContainer::AddPHG4Parameters(), PHG4ParametersContainer::clear(), PHG4ParametersContainer::FillFrom(), PHNodeIterator::findFirst(), get_filetype(), PHG4ParametersContainer::GetAllParameters(), InitRunSubsystem(), Fun4AllBase::Name(), PHG4ParametersContainer::Name(), none, PdbParameterMapContainer::print(), ReadDB(), ReadParamsFromDB(), ReadParamsFromFile(), PHG4ParametersContainer::SaveToNodeTree(), SuperDetector(), UpdateParametersWithMacro(), and Fun4AllBase::Verbosity().
InitRunSubsystem()
virtual int PHG4DetectorGroupSubsystem::InitRunSubsystem (PHCompositeNode *) inline virtual
Definition at line 32 of file PHG4DetectorGroupSubsystem.h.
Referenced by InitRun().
InitSubsystem()
virtual int PHG4DetectorGroupSubsystem::InitSubsystem (PHCompositeNode *) inline virtual
Definition at line 36 of file PHG4DetectorGroupSubsystem.h.
Referenced by Init().
OverlapCheck()
void PHG4DetectorGroupSubsystem::OverlapCheck (const bool chk = true) inline
Definition at line 37 of file PHG4DetectorGroupSubsystem.h.
PrintDefaultParams()
void PHG4DetectorGroupSubsystem::PrintDefaultParams () const protected
Definition at line 559 of file PHG4DetectorGroupSubsystem.cc.
PrintMacroParams()
void PHG4DetectorGroupSubsystem::PrintMacroParams () const protected
Definition at line 598 of file PHG4DetectorGroupSubsystem.cc.
ReadDB()
int PHG4DetectorGroupSubsystem::ReadDB () const inline
Definition at line 49 of file PHG4DetectorGroupSubsystem.h.
Referenced by InitRun().
ReadParamsFromDB()
int PHG4DetectorGroupSubsystem::ReadParamsFromDB (const std::string & name, const int issuper)
Definition at line 472 of file PHG4DetectorGroupSubsystem.cc.
Referenced by InitRun().
ReadParamsFromFile()
int PHG4DetectorGroupSubsystem::ReadParamsFromFile (const std::string & name, const FILE_TYPE ftyp, const int issuper)
Definition at line 515 of file PHG4DetectorGroupSubsystem.cc.
References PHWHERE, root, and xml.
Referenced by InitRun().
SaveParamsToDB()
int PHG4DetectorGroupSubsystem::SaveParamsToDB ()
Definition at line 460 of file PHG4DetectorGroupSubsystem.cc.
References PHG4ParametersContainer::WriteToDB().
SaveParamsToFile()
int PHG4DetectorGroupSubsystem::SaveParamsToFile (const FILE_TYPE ftyp)
Definition at line 490 of file PHG4DetectorGroupSubsystem.cc.
References PHWHERE, root, PHG4ParametersContainer::WriteToFile(), and xml.
set_default_double_param()
void PHG4DetectorGroupSubsystem::set_default_double_param (const int detid, const std::string & name, const double dval) protected
Definition at line 326 of file PHG4DetectorGroupSubsystem.cc.
set_default_int_param()
void PHG4DetectorGroupSubsystem::set_default_int_param (const int detid, const std::string & name, const int ival) protected
Definition at line 351 of file PHG4DetectorGroupSubsystem.cc.
Referenced by InitializeParameters().
set_default_string_param()
void PHG4DetectorGroupSubsystem::set_default_string_param (const int detid, const std::string & name, const std::string & sval) protected
Definition at line 376 of file PHG4DetectorGroupSubsystem.cc.
set_double_param()
void PHG4DetectorGroupSubsystem::set_double_param (const int detid, const std::string & name, const double dval)
Definition at line 159 of file PHG4DetectorGroupSubsystem.cc.
Referenced by UpdateParametersWithMacro().
set_int_param()
void PHG4DetectorGroupSubsystem::set_int_param (const int detid, const std::string & name, const int ival)
Definition at line 204 of file PHG4DetectorGroupSubsystem.cc.
Referenced by BlackHole(), SetAbsorberActive(), SetAbsorberTruth(), and SetActive().
set_string_param()
void PHG4DetectorGroupSubsystem::set_string_param (const int detid, const std::string & name, const std::string & sval)
Definition at line 247 of file PHG4DetectorGroupSubsystem.cc.
Referenced by UpdateParametersWithMacro().
SetAbsorberActive()
void PHG4DetectorGroupSubsystem::SetAbsorberActive (const int detid, const int i = 1)
Definition at line 544 of file PHG4DetectorGroupSubsystem.cc.
References set_int_param().
SetAbsorberTruth()
void PHG4DetectorGroupSubsystem::SetAbsorberTruth (const int detid, const int i = 1)
Definition at line 554 of file PHG4DetectorGroupSubsystem.cc.
References set_int_param().
SetActive()
void PHG4DetectorGroupSubsystem::SetActive (const int detid, const int i = 1)
Definition at line 539 of file PHG4DetectorGroupSubsystem.cc.
References set_int_param().
SetCalibrationFileDir()
void PHG4DetectorGroupSubsystem::SetCalibrationFileDir (const std::string & calibdir) inline
Definition at line 56 of file PHG4DetectorGroupSubsystem.h.
SetDefaultParameters()
virtual void PHG4DetectorGroupSubsystem::SetDefaultParameters () pure virtual
Referenced by InitializeParameters().
SuperDetector() [1/2]
const std::string PHG4DetectorGroupSubsystem::SuperDetector () const inline
Definition at line 64 of file PHG4DetectorGroupSubsystem.h.
Referenced by InitRun().
SuperDetector() [2/2]
void PHG4DetectorGroupSubsystem::SuperDetector (const std::string & name)
Definition at line 153 of file PHG4DetectorGroupSubsystem.cc.
UpdateParametersWithMacro()
void PHG4DetectorGroupSubsystem::UpdateParametersWithMacro ()
Definition at line 292 of file PHG4DetectorGroupSubsystem.cc.
References PHG4ParametersContainer::GetParametersToModify(), GetParamsContainer(), PHG4Subsystem::params, set_double_param(), PHParameters::set_int_param(), and set_string_param().
Referenced by InitRun().
UseCalibFiles()
void PHG4DetectorGroupSubsystem::UseCalibFiles (const FILE_TYPE ftyp) inline
Definition at line 51 of file PHG4DetectorGroupSubsystem.h.
UseDB()
void PHG4DetectorGroupSubsystem::UseDB (const int i = 1) inline
Definition at line 48 of file PHG4DetectorGroupSubsystem.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4DetectorGroupSubsystem.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4DetectorGroupSubsystem.cc