Class Reference for E1039 Core & Analysis Software: MakeRTCurve Class Reference
MakeRTCurve Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/MakeRTCurve.h>
Public Member Functions
MakeRTCurve (const int iter)
virtual ~MakeRTCurve ()
void Init ()
void AnalyzeListOfFiles (const char *fn_list)
void AnalyzeFile (const char *fname)
void DrawHistEvent ()
void DrawHistHit ()
void ExtractRT ()
void WriteRT ()
void DrawCalibResult ()
void Verbosity (const int verb)
int Verbosity () const
Detailed Description
Definition at line 10 of file MakeRTCurve.h.
Constructor & Destructor Documentation
MakeRTCurve()
MakeRTCurve::MakeRTCurve (const int iter)
Definition at line 23 of file MakeRTCurve.cc.
~MakeRTCurve()
MakeRTCurve::~MakeRTCurve () virtual
Definition at line 41 of file MakeRTCurve.cc.
Member Function Documentation
AnalyzeFile()
void MakeRTCurve::AnalyzeFile (const char * fname)
Definition at line 78 of file MakeRTCurve.cc.
References Tracklet::chisq, CalibData::FillEventInfo(), CalibData::FillHit(), CalibData::FillTracklet(), Tracklet::getExpPositionW(), Tracklet::getNHits(), Tracklet::hits, Tracklet::stationID, Tracklet::tx, and Tracklet::ty.
Referenced by AnalyzeListOfFiles().
AnalyzeListOfFiles()
void MakeRTCurve::AnalyzeListOfFiles (const char * fn_list)
Definition at line 70 of file MakeRTCurve.cc.
References AnalyzeFile().
DrawCalibResult()
void MakeRTCurve::DrawCalibResult ()
Definition at line 225 of file MakeRTCurve.cc.
References CalibParam::GetAnaPlane(), GeomSvc::getDetectorName(), CalibParam::GetGraphT2R(), CalibData::GetHistRT(), CalibParam::GetNumPlanes(), CalibParam::GetRTCurve(), RTCurve::GetRWidth(), RTCurve::GetT2DRGraph(), RTCurve::GetT2RSpline(), and GeomSvc::instance().
DrawHistEvent()
void MakeRTCurve::DrawHistEvent ()
Definition at line 180 of file MakeRTCurve.cc.
References CalibData::DrawHistEvent().
DrawHistHit()
void MakeRTCurve::DrawHistHit ()
Definition at line 192 of file MakeRTCurve.cc.
References CalibData::DrawHistHit().
ExtractRT()
void MakeRTCurve::ExtractRT ()
Definition at line 197 of file MakeRTCurve.cc.
References FitRTDist::DoFit(), FitRTDist::FixT1T0(), CalibParam::GetAnaPlane(), CalibParam::GetGraphT2R(), CalibData::GetHistRT(), CalibParam::GetNumPlanes(), CalibParam::GetRMax(), CalibParam::GetRTCurve(), CalibParam::GetT0(), CalibParam::GetT1(), CalibParam::TimeWindowIsFixed(), and FitRTDist::Verbosity().
Init()
void MakeRTCurve::Init ()
Definition at line 46 of file MakeRTCurve.cc.
References CalibData::Init(), CalibParam::Init(), CalibParam::ReadRTParam(), and CalibParam::SetAnaPlanes().
Verbosity() [1/2]
int MakeRTCurve::Verbosity () const inline
Definition at line 45 of file MakeRTCurve.h.
Verbosity() [2/2]
void MakeRTCurve::Verbosity (const int verb) inline
Definition at line 44 of file MakeRTCurve.h.
WriteRT()
void MakeRTCurve::WriteRT ()
Definition at line 219 of file MakeRTCurve.cc.
References CalibParam::WriteRTGraph(), and CalibParam::WriteRTParam().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/MakeRTCurve.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/CalibChamXT/src/MakeRTCurve.cc