Class Reference for E1039 Core & Analysis Software: PHG4CylinderCell Class Reference
PHG4CylinderCell Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCell.h>
Public Types
typedef std::map< PHG4HitDefs::keytype, float > EdepMap
typedef EdepMap::iterator EdepIterator
typedef EdepMap::const_iterator EdepConstIterator
typedef std::pair< EdepIterator, EdepIterator > EdepRange
typedef std::pair< EdepConstIterator, EdepConstIterator > EdepConstRange
typedef std::map< int, float > ShowerEdepMap
typedef ShowerEdepMap::iterator ShowerEdepIterator
typedef ShowerEdepMap::const_iterator ShowerEdepConstIterator
typedef std::pair< ShowerEdepIterator, ShowerEdepIterator > ShowerEdepRange
typedef std::pair< ShowerEdepConstIterator, ShowerEdepConstIterator > ShowerEdepConstRange
Public Types inherited from PHG4Cell
enum PROPERTY {
prop_stave_index = 1 , prop_half_stave_index = 2 , prop_module_index = 3 , prop_chip_index = 4 ,
prop_pixel_index = 5 , prop_phibin = 6 , prop_zbin = 7 , prop_ladder_z_index = 8 ,
prop_ladder_phi_index = 9 , prop_edep = 21 , prop_eion = 22 , prop_light_yield = 23 ,
prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1 , type_uint = 2 , type_float = 3 , type_unknown = -1 }
typedef std::map< PHG4HitDefs::keytype, float > EdepMap
typedef EdepMap::iterator EdepIterator
typedef EdepMap::const_iterator EdepConstIterator
typedef std::pair< EdepIterator, EdepIterator > EdepRange
typedef std::pair< EdepConstIterator, EdepConstIterator > EdepConstRange
typedef std::map< int, float > ShowerEdepMap
typedef ShowerEdepMap::iterator ShowerEdepIterator
typedef ShowerEdepMap::const_iterator ShowerEdepConstIterator
typedef std::pair< ShowerEdepIterator, ShowerEdepIterator > ShowerEdepRange
typedef std::pair< ShowerEdepConstIterator, ShowerEdepConstIterator > ShowerEdepConstRange
typedef std::pair< unsigned short, std::map< int, int > > tpccompress
typedef std::map< unsigned short, tpccompress > tpctod
Public Member Functions
virtual ~PHG4CylinderCell ()
virtual void identify (std::ostream &os=std::cout) const
virtual EdepConstRange get_g4hits ()
virtual void add_edep (const PHG4HitDefs::keytype g4hitid, const float edep)
virtual void add_edep (const PHG4HitDefs::keytype g4hitid, const float edep, const float light_yield)
virtual ShowerEdepConstRange get_g4showers ()
virtual void add_shower_edep (const int g4showerid, const float edep)
virtual void set_cell_id (const PHG4CylinderCellDefs::keytype id)
virtual void set_layer (const unsigned int i)
virtual double get_edep () const
virtual unsigned int get_layer () const
virtual PHG4CylinderCellDefs::keytype get_cell_id () const
virtual int get_binz () const
virtual int get_binphi () const
virtual int get_bineta () const
virtual float get_light_yield () const
virtual int get_fiber_ID () const
virtual void set_phibin (const int i)
virtual void set_zbin (const int i)
virtual void set_etabin (const int i)
virtual void set_light_yield (float lightYield)
virtual void set_fiber_ID (int fiberId)
virtual void set_sensor_index (const std::string &si)
virtual std::string get_sensor_index () const
virtual void set_ladder_phi_index (const int i)
virtual int get_ladder_phi_index () const
virtual void set_ladder_z_index (const int i)
virtual int get_ladder_z_index () const
virtual int get_j_index () const
virtual void set_j_index (const int i)
virtual int get_k_index () const
virtual void set_k_index (const int i)
virtual int get_l_index () const
virtual void set_l_index (const int i)
virtual int get_pixel_index () const
virtual int get_chip_index () const
virtual int get_module_index () const
virtual int get_half_stave_index () const
virtual int get_stave_index () const
virtual void set_stave_index (const int si)
virtual void set_half_stave_index (const int i)
virtual void set_module_index (const int i)
virtual void set_chip_index (const int i)
virtual void set_pixel_index (const int i)
Public Member Functions inherited from PHG4Cell
virtual ~PHG4Cell ()
virtual void Copy (PHG4Cell const &g4cell)
virtual void Reset ()
virtual void set_cellid (const PHG4CellDefs::keytype i)
virtual PHG4CellDefs::keytype get_cellid () const
virtual bool has_binning (const PHG4CellDefs::CellBinning) const
virtual void add_edep (const PHG4HitDefs::keytype g4hitid, const int tbin, const float edep)
virtual short int get_detid () const
short int get_layer () const
virtual void add_edep (const float f)
virtual void add_eion (const float f)
virtual double get_eion () const
virtual void add_light_yield (const float lightYield)
virtual int get_phibin () const
virtual int get_zbin () const
virtual void print () const
virtual bool has_property (const PROPERTY prop_id) const
virtual float get_property_float (const PROPERTY prop_id) const
virtual int get_property_int (const PROPERTY prop_id) const
virtual unsigned int get_property_uint (const PROPERTY prop_id) const
virtual void set_property (const PROPERTY prop_id, const float value)
virtual void set_property (const PROPERTY prop_id, const int value)
virtual void set_property (const PROPERTY prop_id, const unsigned int value)
Protected Member Functions
PHG4CylinderCell ()
Protected Member Functions inherited from PHG4Cell
PHG4Cell ()
virtual unsigned int get_property_nocheck (const PROPERTY prop_id) const
virtual void set_property_nocheck (const PROPERTY prop_id, const unsigned int)
Additional Inherited Members
Static Public Member Functions inherited from PHG4Cell
static std::pair< const std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 11 of file PHG4CylinderCell.h.
Member Typedef Documentation
EdepConstIterator
typedef EdepMap::const_iterator PHG4CylinderCell::EdepConstIterator
Definition at line 16 of file PHG4CylinderCell.h.
EdepConstRange
typedef std::pair<EdepConstIterator, EdepConstIterator> PHG4CylinderCell::EdepConstRange
Definition at line 18 of file PHG4CylinderCell.h.
EdepIterator
typedef EdepMap::iterator PHG4CylinderCell::EdepIterator
Definition at line 15 of file PHG4CylinderCell.h.
EdepMap
typedef std::map<PHG4HitDefs::keytype, float> PHG4CylinderCell::EdepMap
Definition at line 14 of file PHG4CylinderCell.h.
EdepRange
typedef std::pair<EdepIterator, EdepIterator> PHG4CylinderCell::EdepRange
Definition at line 17 of file PHG4CylinderCell.h.
ShowerEdepConstIterator
typedef ShowerEdepMap::const_iterator PHG4CylinderCell::ShowerEdepConstIterator
Definition at line 22 of file PHG4CylinderCell.h.
ShowerEdepConstRange
typedef std::pair<ShowerEdepConstIterator, ShowerEdepConstIterator> PHG4CylinderCell::ShowerEdepConstRange
Definition at line 24 of file PHG4CylinderCell.h.
ShowerEdepIterator
typedef ShowerEdepMap::iterator PHG4CylinderCell::ShowerEdepIterator
Definition at line 21 of file PHG4CylinderCell.h.
ShowerEdepMap
typedef std::map<int, float> PHG4CylinderCell::ShowerEdepMap
Definition at line 20 of file PHG4CylinderCell.h.
ShowerEdepRange
typedef std::pair<ShowerEdepIterator, ShowerEdepIterator> PHG4CylinderCell::ShowerEdepRange
Definition at line 23 of file PHG4CylinderCell.h.
Constructor & Destructor Documentation
~PHG4CylinderCell()
virtual PHG4CylinderCell::~PHG4CylinderCell () inline virtual
Definition at line 26 of file PHG4CylinderCell.h.
PHG4CylinderCell()
PHG4CylinderCell::PHG4CylinderCell () inline protected
Definition at line 93 of file PHG4CylinderCell.h.
Member Function Documentation
add_edep() [1/2]
virtual void PHG4CylinderCell::add_edep (const PHG4HitDefs::keytype g4hitid, const float edep) inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv1.
Definition at line 37 of file PHG4CylinderCell.h.
add_edep() [2/2]
virtual void PHG4CylinderCell::add_edep (const PHG4HitDefs::keytype g4hitid, const float edep, const float light_yield) inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 38 of file PHG4CylinderCell.h.
add_shower_edep()
virtual void PHG4CylinderCell::add_shower_edep (const int g4showerid, const float edep) inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv1.
Definition at line 45 of file PHG4CylinderCell.h.
get_bineta()
virtual int PHG4CylinderCell::get_bineta () const inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 55 of file PHG4CylinderCell.h.
get_binphi()
virtual int PHG4CylinderCell::get_binphi () const inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 54 of file PHG4CylinderCell.h.
get_binz()
virtual int PHG4CylinderCell::get_binz () const inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 53 of file PHG4CylinderCell.h.
get_cell_id()
virtual PHG4CylinderCellDefs::keytype PHG4CylinderCell::get_cell_id () const inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 52 of file PHG4CylinderCell.h.
get_chip_index()
virtual int PHG4CylinderCell::get_chip_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 80 of file PHG4CylinderCell.h.
get_edep()
virtual double PHG4CylinderCell::get_edep () const inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv1.
Definition at line 50 of file PHG4CylinderCell.h.
get_fiber_ID()
virtual int PHG4CylinderCell::get_fiber_ID () const inline virtual
Definition at line 57 of file PHG4CylinderCell.h.
get_g4hits()
virtual EdepConstRange PHG4CylinderCell::get_g4hits () inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv1.
Definition at line 32 of file PHG4CylinderCell.h.
get_g4showers()
virtual ShowerEdepConstRange PHG4CylinderCell::get_g4showers () inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv1.
Definition at line 40 of file PHG4CylinderCell.h.
get_half_stave_index()
virtual int PHG4CylinderCell::get_half_stave_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 82 of file PHG4CylinderCell.h.
get_j_index()
virtual int PHG4CylinderCell::get_j_index () const inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 72 of file PHG4CylinderCell.h.
get_k_index()
virtual int PHG4CylinderCell::get_k_index () const inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 74 of file PHG4CylinderCell.h.
get_l_index()
virtual int PHG4CylinderCell::get_l_index () const inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 76 of file PHG4CylinderCell.h.
get_ladder_phi_index()
virtual int PHG4CylinderCell::get_ladder_phi_index () const inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv2.
Definition at line 68 of file PHG4CylinderCell.h.
get_ladder_z_index()
virtual int PHG4CylinderCell::get_ladder_z_index () const inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv2.
Definition at line 70 of file PHG4CylinderCell.h.
get_layer()
virtual unsigned int PHG4CylinderCell::get_layer () const inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 51 of file PHG4CylinderCell.h.
Referenced by PHG4CylinderCellContainer::AddCylinderCell(), PHG4CylinderCellContainer::AddCylinderCellSpecifyKey(), and PHG4CylinderCellContainer::findOrAddCylinderCell().
get_light_yield()
virtual float PHG4CylinderCell::get_light_yield () const inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv1.
Definition at line 56 of file PHG4CylinderCell.h.
get_module_index()
virtual int PHG4CylinderCell::get_module_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 81 of file PHG4CylinderCell.h.
get_pixel_index()
virtual int PHG4CylinderCell::get_pixel_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 79 of file PHG4CylinderCell.h.
get_sensor_index()
virtual std::string PHG4CylinderCell::get_sensor_index () const inline virtual
Reimplemented in PHG4CylinderCellv2.
Definition at line 66 of file PHG4CylinderCell.h.
get_stave_index()
virtual int PHG4CylinderCell::get_stave_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 83 of file PHG4CylinderCell.h.
identify()
virtual void PHG4CylinderCell::identify (std::ostream & os = std::cout) const inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv3, PHG4CylinderCellv2, and PHG4CylinderCellv1.
Definition at line 28 of file PHG4CylinderCell.h.
set_cell_id()
virtual void PHG4CylinderCell::set_cell_id (const PHG4CylinderCellDefs::keytype id) inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 47 of file PHG4CylinderCell.h.
Referenced by PHG4CylinderCellContainer::AddCylinderCell(), PHG4CylinderCellContainer::AddCylinderCellSpecifyKey(), and PHG4CylinderCellContainer::findOrAddCylinderCell().
set_chip_index()
virtual void PHG4CylinderCell::set_chip_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 88 of file PHG4CylinderCell.h.
set_etabin()
virtual void PHG4CylinderCell::set_etabin (const int i) inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 61 of file PHG4CylinderCell.h.
set_fiber_ID()
virtual void PHG4CylinderCell::set_fiber_ID (int fiberId) inline virtual
Definition at line 63 of file PHG4CylinderCell.h.
set_half_stave_index()
virtual void PHG4CylinderCell::set_half_stave_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 86 of file PHG4CylinderCell.h.
set_j_index()
virtual void PHG4CylinderCell::set_j_index (const int i) inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 73 of file PHG4CylinderCell.h.
set_k_index()
virtual void PHG4CylinderCell::set_k_index (const int i) inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 75 of file PHG4CylinderCell.h.
set_l_index()
virtual void PHG4CylinderCell::set_l_index (const int i) inline virtual
Reimplemented in PHG4CylinderCellv3.
Definition at line 77 of file PHG4CylinderCell.h.
set_ladder_phi_index()
virtual void PHG4CylinderCell::set_ladder_phi_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv2.
Definition at line 67 of file PHG4CylinderCell.h.
set_ladder_z_index()
virtual void PHG4CylinderCell::set_ladder_z_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv2.
Definition at line 69 of file PHG4CylinderCell.h.
set_layer()
virtual void PHG4CylinderCell::set_layer (const unsigned int i) inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 48 of file PHG4CylinderCell.h.
set_light_yield()
virtual void PHG4CylinderCell::set_light_yield (float lightYield) inline virtual
Reimplemented in PHG4CylinderCellv1.
Definition at line 62 of file PHG4CylinderCell.h.
set_module_index()
virtual void PHG4CylinderCell::set_module_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 87 of file PHG4CylinderCell.h.
set_phibin()
virtual void PHG4CylinderCell::set_phibin (const int i) inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv1.
Definition at line 59 of file PHG4CylinderCell.h.
set_pixel_index()
virtual void PHG4CylinderCell::set_pixel_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 89 of file PHG4CylinderCell.h.
set_sensor_index()
virtual void PHG4CylinderCell::set_sensor_index (const std::string & si) inline virtual
Reimplemented in PHG4CylinderCellv2.
Definition at line 65 of file PHG4CylinderCell.h.
set_stave_index()
virtual void PHG4CylinderCell::set_stave_index (const int si) inline virtual
Reimplemented from PHG4Cell.
Definition at line 85 of file PHG4CylinderCell.h.
set_zbin()
virtual void PHG4CylinderCell::set_zbin (const int i) inline virtual
Reimplemented from PHG4Cell.
Reimplemented in PHG4CylinderCellv1.
Definition at line 60 of file PHG4CylinderCell.h.
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderCell.h