Class Reference for E1039 Core & Analysis Software: SQDimuon Class Reference
SQDimuon Class Reference abstract
An SQ interface class to hold one true or reconstructed dimuon.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQDimuon.h>
Public Member Functions
virtual ~SQDimuon ()
virtual void identify (std::ostream &os=std::cout) const =0
virtual void Reset ()=0
Clear Event.
virtual int isValid () const =0
isValid returns non zero if object contains vailid data
virtual SQDimuon * Clone () const =0
virtual int get_dimuon_id () const =0
Return the dimuon ID, which is unique per event(?).
virtual void set_dimuon_id (const int a)=0
virtual int get_rec_dimuon_id () const =0
Return the dimuon ID of associated reconstructed dimuon. Valid only if this object holds truth dimuon info.
virtual void set_rec_dimuon_id (const int a)=0
virtual int get_pdg_id () const =0
Return the GPD ID of parent particle. It is valid only for true dimuon.
virtual void set_pdg_id (const int a)=0
virtual int get_track_id_pos () const =0
Return the track ID of the positive track.
virtual void set_track_id_pos (const int a)=0
virtual int get_track_id_neg () const =0
Return the track ID of the negative track.
virtual void set_track_id_neg (const int a)=0
virtual TVector3 get_pos () const =0
Return the dimuon position at vertex.
virtual void set_pos (const TVector3 a)=0
virtual TLorentzVector get_mom () const =0
Return the dimuon momentum at vertex.
virtual void set_mom (const TLorentzVector a)=0
virtual TLorentzVector get_mom_pos () const =0
Return the momentum of the positive track at vertex.
virtual void set_mom_pos (const TLorentzVector a)=0
virtual TLorentzVector get_mom_neg () const =0
Return the momentum of the negative track at vertex.
virtual void set_mom_neg (const TLorentzVector a)=0
virtual double get_mass () const =0
virtual double get_x1 () const =0
virtual double get_x2 () const =0
virtual double get_xf () const =0
virtual double get_chisq () const =0
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQDimuon ()
ClassDef (SQDimuon, 1)
Detailed Description
An SQ interface class to hold one true or reconstructed dimuon.
Definition at line 8 of file SQDimuon.h.
Constructor & Destructor Documentation
~SQDimuon()
virtual SQDimuon::~SQDimuon () inline virtual
Definition at line 10 of file SQDimuon.h.
SQDimuon()
SQDimuon::SQDimuon () inline protected
Definition at line 52 of file SQDimuon.h.
Member Function Documentation
ClassDef()
SQDimuon::ClassDef (SQDimuon , 1) protected
Clone()
virtual SQDimuon* SQDimuon::Clone () const pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by SQDimuonVector_v1::push_back().
get_chisq()
virtual double SQDimuon::get_chisq () const pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
get_dimuon_id()
virtual int SQDimuon::get_dimuon_id () const pure virtual
Return the dimuon ID, which is unique per event(?).
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by UtilDimuon::FindDimuonByID(), DoEmbedding::process_event(), and SimpleTree::process_event().
get_mass()
virtual double SQDimuon::get_mass () const pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by SimpleTree::process_event().
get_mom()
virtual TLorentzVector SQDimuon::get_mom () const pure virtual
Return the dimuon momentum at vertex.
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by AnaSimDst::process_event(), AnaSimDimuon::process_event(), SubsysRecoSignal::process_event(), AnaEmbeddedData::process_event(), and SimpleTree::process_event().
get_mom_neg()
virtual TLorentzVector SQDimuon::get_mom_neg () const pure virtual
Return the momentum of the negative track at vertex.
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by UtilAsym::CalcAngle(), UtilDimuon::CalcVar(), UtilDimuon::GetX1X2(), UtilDimuon::Lab2CollinsSoper(), AnaSimDst::process_event(), AnaSimDimuon::process_event(), AnaEmbeddedData::process_event(), and SimpleTree::process_event().
get_mom_pos()
virtual TLorentzVector SQDimuon::get_mom_pos () const pure virtual
Return the momentum of the positive track at vertex.
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by UtilAsym::CalcAngle(), UtilDimuon::CalcVar(), UtilDimuon::GetX1X2(), UtilDimuon::Lab2CollinsSoper(), AnaSimDst::process_event(), AnaSimDimuon::process_event(), AnaEmbeddedData::process_event(), and SimpleTree::process_event().
get_pdg_id()
virtual int SQDimuon::get_pdg_id () const pure virtual
Return the GPD ID of parent particle. It is valid only for true dimuon.
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by AnaSimDst::process_event(), TracePHG4Particle::process_event(), and SimpleTree::process_event().
get_pos()
virtual TVector3 SQDimuon::get_pos () const pure virtual
Return the dimuon position at vertex.
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by AnaSimDst::process_event(), AnaSimDimuon::process_event(), SubsysRecoSignal::process_event(), and SQTruthVertexing::process_event().
get_rec_dimuon_id()
virtual int SQDimuon::get_rec_dimuon_id () const pure virtual
Return the dimuon ID of associated reconstructed dimuon. Valid only if this object holds truth dimuon info.
Implemented in SRecDimuon, and SQDimuon_v1.
get_track_id_neg()
virtual int SQDimuon::get_track_id_neg () const pure virtual
Return the track ID of the negative track.
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by SubsysRecoSignal::process_event(), DoEmbedding::process_event(), SimpleTree::process_event(), and SQTruthVertexing::process_event().
get_track_id_pos()
virtual int SQDimuon::get_track_id_pos () const pure virtual
Return the track ID of the positive track.
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by SubsysRecoSignal::process_event(), DoEmbedding::process_event(), SimpleTree::process_event(), and SQTruthVertexing::process_event().
get_x1()
virtual double SQDimuon::get_x1 () const pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by SimpleTree::process_event().
get_x2()
virtual double SQDimuon::get_x2 () const pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by SimpleTree::process_event().
get_xf()
virtual double SQDimuon::get_xf () const pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by SimpleTree::process_event().
identify()
virtual void SQDimuon::identify (std::ostream & os = std::cout) const pure virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Implemented in SRecDimuon, and SQDimuon_v1.
isValid()
virtual int SQDimuon::isValid () const pure virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Implemented in SRecDimuon, and SQDimuon_v1.
Reset()
virtual void SQDimuon::Reset () pure virtual
Clear Event.
Reimplemented from PHObject.
Implemented in SRecDimuon, and SQDimuon_v1.
set_dimuon_id()
virtual void SQDimuon::set_dimuon_id (const int a) pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by DoEmbedding::process_event().
set_mom()
virtual void SQDimuon::set_mom (const TLorentzVector a) pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
set_mom_neg()
virtual void SQDimuon::set_mom_neg (const TLorentzVector a) pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
set_mom_pos()
virtual void SQDimuon::set_mom_pos (const TLorentzVector a) pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
set_pdg_id()
virtual void SQDimuon::set_pdg_id (const int a) pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
set_pos()
virtual void SQDimuon::set_pos (const TVector3 a) pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
set_rec_dimuon_id()
virtual void SQDimuon::set_rec_dimuon_id (const int a) pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by SQTruthVertexing::process_event().
set_track_id_neg()
virtual void SQDimuon::set_track_id_neg (const int a) pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by DoEmbedding::process_event().
set_track_id_pos()
virtual void SQDimuon::set_track_id_pos (const int a) pure virtual
Implemented in SRecDimuon, and SQDimuon_v1.
Referenced by DoEmbedding::process_event().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQDimuon.h