Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaTrkQA/macros/Fun4Sim_TrkQA.C File Reference
Fun4Sim_TrkQA.C File Reference
#include <TSystem.h>
#include <top/G4_Beamline.C>
#include <top/G4_Target.C>
#include <top/G4_InsensitiveVolumes.C>
#include <top/G4_SensitiveDetectors.C>
Functions
int Fun4Sim_TrkQA (const int nevent=10)
Function Documentation
int Fun4Sim_TrkQA (const int nevent = 10)
Definition at line 25 of file Fun4Sim_TrkQA.C.
References PHG4SimpleEventGenerator::add_particles(), SQReco::E1039, Fun4AllServer::End(), PHGeomUtility::ExportGeomtry(), PHFlag::get_CharFlag(), recoConsts::instance(), Fun4AllServer::instance(), GeomSvc::instance(), SQReco::KFREF, recoConsts::Print(), GeomSvc::printTable(), Fun4AllServer::PrintTimer(), PHFieldConfig::RegionalConst, Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), se, PHFlag::set_DoubleFlag(), SQReco::set_enable_eval(), SQReco::set_enable_eval_dst(), SQReco::set_enable_KF(), SQReco::set_eval_file_name(), SQReco::set_evt_reducer_opt(), PHG4Reco::set_field_map(), AnaTrkQA::set_out_name(), PHG4SimpleEventGenerator::set_pxpypz_range(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), SQReco::setFitterTy(), SQReco::setInputTy(), PHG4Reco::SetPhysicsList(), SetupBeamline(), SetupInsensitiveVolumes(), SetupSensitiveDetectors(), SetupTarget(), PHG4Reco::SetWorldMaterial(), PHG4Reco::SetWorldShape(), PHG4Reco::SetWorldSizeX(), PHG4Reco::SetWorldSizeY(), PHG4Reco::SetWorldSizeZ(), Fun4AllServer::topNode(), PHG4SimpleEventGenerator::Uniform, GeomSvc::UseDbSvc(), and Fun4AllBase::Verbosity().