E1039 Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TrkDev/Fun4TrkDev.C File Reference
Fun4TrkDev.C File Reference
#include <phool/recoConsts.h>
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/HepMCNodeReader.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <g4detectors/DPDigitizer.h>
#include <phpythia8/PHPythia8.h>
#include <g4eval/PHG4DSTReader.h>
#include <jobopts_svc/JobOptsSvc.h>
#include <geom_svc/GeomSvc.h>
#include <module_example/TrkEval.h>
#include <TSystem.h>
#include "G4_SensitiveDetectors.C"
#include "G4_Target.C"
Functions
int Fun4TrkDev (const int nEvents=1, const int nmu=1, const double x0_shift=0.0)
PHG4ParticleGun * get_gun (const char *name="PGUN")
Function Documentation
int Fun4TrkDev (const int nEvents = 1, const int nmu = 1, const double x0_shift = 0.0)
Definition at line 45 of file Fun4TrkDev.C.
References PHG4SimpleEventGenerator::add_particles(), PHG4DSTReader::AddNode(), PHPy8ParticleTrigger::AddParticles(), ana(), Fun4AllServer::End(), PHGeomUtility::ExportGeomtry(), GeomSvc::getDetectorX0(), JobOptsSvc::init(), HepMCNodeReader::insert_particle_filter_pid(), JobOptsSvc::instance(), Fun4AllServer::instance(), GeomSvc::instance(), JobOptsSvc::m_fMagFile, JobOptsSvc::m_kMagFile, RndmEmbed::print_noise_rate(), Fun4AllServer::PrintTimer(), PHFieldConfig::RegionalConst, PHPythia8::register_trigger(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), se, PHPythia8::set_config_file(), KalmanFastTrackingWrapper::set_DS_level(), PHG4Reco::set_field_map(), TrkEval::set_hit_container_choice(), SRawEventEmbed::set_in_name(), SRawEventEmbed::set_in_tree_name(), PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHG4ParticleGeneratorBase::set_mom(), PHG4ParticleGeneratorBase::set_name(), RndmEmbed::set_noise_rate(), TrkEval::set_out_name(), HepMCNodeReader::set_particle_filter_on(), PHG4SimpleEventGenerator::set_pxpypz_range(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), PHPythia8::set_trigger_AND(), SRawEventEmbed::set_trigger_bit(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHPythia8::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), PHG4ParticleGeneratorBase::set_vtx(), GeomSvc::setDetectorX0(), PHG4Reco::SetPhysicsList(), PHPy8ParticleTrigger::SetPzHighLow(), SetupSensitiveDetectors(), SetupTarget(), PHG4Reco::SetWorldMaterial(), PHG4Reco::SetWorldShape(), PHG4Reco::SetWorldSizeX(), PHG4Reco::SetWorldSizeY(), PHG4Reco::SetWorldSizeZ(), Fun4AllServer::topNode(), PHG4SimpleEventGenerator::Uniform, and Fun4AllBase::Verbosity().
PHG4ParticleGun* get_gun (const char * name = "PGUN")
Definition at line 329 of file Fun4TrkDev.C.
References Fun4AllServer::getSubsysReco(), Fun4AllServer::instance(), and se.