Class Reference for E1039 Core & Analysis Software: PHGeomUtility Class Reference
PHGeomUtility Class Reference
Toolsets to do geometry operations.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHGeometry/PHGeomUtility.h>
Static Public Member Functions
static TGeoManager * GetTGeoManager (PHCompositeNode *topNode)
Main user interface: DST node -> TGeoManager for downstream use.
static int ImportGeomFile (PHCompositeNode *topNode, const std::string &geometry_file)
TGeo ROOT/GDML/Macro file -> DST node with automatic file type discrimination based on file names.
static int ImportCurrentTGeoManager (PHCompositeNode *topNode)
gGeoManager -> DST node
static void ExportGeomtry (PHCompositeNode *topNode, const std::string &geometry_file)
DST node -> TGeoManager -> export files, like gdml, .root or .C formats.
static PHGeomTGeo * GetGeomTGeoNode (PHCompositeNode *topNode, bool build_new=true)
Get non-persistent PHGeomTGeo from DST nodes. If not found, make a new one.
static PHGeomIOTGeo * GetGeomIOTGeoNode (PHCompositeNode *topNode, bool build_new=true)
Get persistent PHGeomIOTGeo from DST nodes. If not found, make a new one.
static PHGeomIOTGeo * UpdateIONode (PHCompositeNode *topNode)
static PHGeomTGeo * LoadFromIONode (PHCompositeNode *topNode)
static std::string GenerateGeometryFileName (const std::string &filename_extension="gdml")
static bool RemoveGeometryFile (const std::string &file_name)
delete the geometry file after use
static void SetVerbosity (int v)
Verbosity for geometry IO like, TGeoMangers.
static int GetVerbosity ()
Verbosity for geometry IO like, TGeoMangers.
static std::string GetDSTNodeName ()
DST node name for RunTime geometry object.
static std::string GetDSTIONodeName ()
DST node name for persistent geometry storage node.
Protected Member Functions
PHGeomUtility ()
virtual ~PHGeomUtility ()
Detailed Description
Toolsets to do geometry operations.
Definition at line 16 of file PHGeomUtility.h.
Constructor & Destructor Documentation
PHGeomUtility()
PHGeomUtility::PHGeomUtility () protected
Definition at line 28 of file PHGeomUtility.cc.
~PHGeomUtility()
PHGeomUtility::~PHGeomUtility () protected virtual
Definition at line 32 of file PHGeomUtility.cc.
Member Function Documentation
ExportGeomtry()
void PHGeomUtility::ExportGeomtry (PHCompositeNode * topNode, const std::string & geometry_file) static
DST node -> TGeoManager -> export files, like gdml, .root or .C formats.
Definition at line 62 of file PHGeomUtility.cc.
GenerateGeometryFileName()
std::string PHGeomUtility::GenerateGeometryFileName (const std::string & filename_extension = "gdml") static
Make a name for tmp geometry file Geometry files gain a size of ~10MB and it used in translation from Geant4 to DST format. This tmp file should be on a local file system (/tmp/) and write/deletable
Definition at line 179 of file PHGeomUtility.cc.
Referenced by PHG4Reco::InitRun().
GetDSTIONodeName()
static std::string PHGeomUtility::GetDSTIONodeName () inline static
DST node name for persistent geometry storage node.
Definition at line 87 of file PHGeomUtility.h.
GetDSTNodeName()
static std::string PHGeomUtility::GetDSTNodeName () inline static
DST node name for RunTime geometry object.
Definition at line 80 of file PHGeomUtility.h.
GetGeomIOTGeoNode()
PHGeomIOTGeo * PHGeomUtility::GetGeomIOTGeoNode (PHCompositeNode * topNode, bool build_new = true) static
Get persistent PHGeomIOTGeo from DST nodes. If not found, make a new one.
Definition at line 147 of file PHGeomUtility.cc.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and NULL.
GetGeomTGeoNode()
PHGeomTGeo * PHGeomUtility::GetGeomTGeoNode (PHCompositeNode * topNode, bool build_new = true) static
Get non-persistent PHGeomTGeo from DST nodes. If not found, make a new one.
Definition at line 114 of file PHGeomUtility.cc.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and NULL.
Referenced by SQReco::InitGeom().
GetTGeoManager()
TGeoManager * PHGeomUtility::GetTGeoManager (PHCompositeNode * topNode) static
Main user interface: DST node -> TGeoManager for downstream use.
DST node -> TGeoManager for downstream use.
Definition at line 39 of file PHGeomUtility.cc.
References PHGeomTGeo::GetGeometry(), PHGeomTGeo::isValid(), and NULL.
Referenced by SQReco::InitGeom().
GetVerbosity()
int PHGeomUtility::GetVerbosity () static
Verbosity for geometry IO like, TGeoMangers.
Definition at line 287 of file PHGeomUtility.cc.
References PHFlag::FlagExist(), PHFlag::get_IntFlag(), and recoConsts::instance().
ImportCurrentTGeoManager()
int PHGeomUtility::ImportCurrentTGeoManager (PHCompositeNode * topNode) static
gGeoManager -> DST node
Definition at line 97 of file PHGeomUtility.cc.
References Fun4AllReturnCodes::EVENT_OK, PHGeomTGeo::GetGeometry(), PHGeomTGeo::isValid(), and PHGeomTGeo::SetGeometry().
ImportGeomFile()
int PHGeomUtility::ImportGeomFile (PHCompositeNode * topNode, const std::string & geometry_file) static
TGeo ROOT/GDML/Macro file -> DST node with automatic file type discrimination based on file names.
Definition at line 73 of file PHGeomUtility.cc.
References Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, PHGeomTGeo::GetGeometry(), NULL, PHGeomTGeo::Reset(), and PHGeomTGeo::SetGeometry().
Referenced by SQReco::InitGeom(), PHGeomFileImport::InitRun(), and PHG4Reco::InitRun().
LoadFromIONode()
PHGeomTGeo * PHGeomUtility::LoadFromIONode (PHCompositeNode * topNode) static
Build or update PHGeomTGeo node RUN/GEOMETRY based on the persistent PHGeomIOTGeo node RUN/GEOMETRY_IO
Returns
the updated PHGeomTGeo from DST tree
Definition at line 244 of file PHGeomUtility.cc.
References PHGeomIOTGeo::ConstructTGeoManager(), PHGeomIOTGeo::isValid(), NULL, and PHGeomTGeo::SetGeometry().
Referenced by SQReco::InitGeom().
RemoveGeometryFile()
bool PHGeomUtility::RemoveGeometryFile (const std::string & file_name) static
delete the geometry file after use
Definition at line 190 of file PHGeomUtility.cc.
Referenced by PHG4Reco::InitRun().
SetVerbosity()
void PHGeomUtility::SetVerbosity (int v) static
Verbosity for geometry IO like, TGeoMangers.
Definition at line 279 of file PHGeomUtility.cc.
References recoConsts::instance(), and PHFlag::set_IntFlag().
UpdateIONode()
PHGeomIOTGeo * PHGeomUtility::UpdateIONode (PHCompositeNode * topNode) static
Update persistent PHGeomIOTGeo node RUN/GEOMETRY_IO based on run-time object PHGeomTGeo at RUN/GEOMETRY
Returns
the updated PHGeomIOTGeo from DST tree
Definition at line 214 of file PHGeomUtility.cc.
References PHGeomTGeo::GetGeometry(), PHGeomTGeo::isValid(), NULL, and PHGeomIOTGeo::SetGeometry().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHGeometry/PHGeomUtility.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHGeometry/PHGeomUtility.cc