Class Reference for E1039 Core & Analysis Software: DPGEN Namespace Reference
DPGEN Namespace Reference
Functions
const TLorentzVector p_beam (0., 0., TMath::Sqrt(ebeam *ebeam-mp *mp), ebeam)
const TLorentzVector p_target (0., 0., 0., mp)
Variables
const double pi = TMath::Pi()
const double twopi = 2.*pi
const double sqrt2pi = TMath::Sqrt(twopi)
const double mp = 0.93827
const double mmu = 0.10566
const double mjpsi = 3.097
const double mpsip = 3.686
const double ebeam = 120.
const TLorentzVector p_cms = p_beam + p_target
const TVector3 bv_cms = p_cms.BoostVector()
const double s = p_cms.M2()
const double sqrts = p_cms.M()
Function Documentation
const TLorentzVector DPGEN::p_beam (0. , 0. , TMath:: Sqrtebeam *ebeam-mp *mp, ebeam)
Referenced by UtilDimuon::CalcVar(), SRecDimuon::calcVariables(), SQDimuon_v1::get_x1(), SQDimuon_v1::get_x2(), SQDimuon_v1::get_xf(), and UtilDimuon::GetX1X2().
const TLorentzVector DPGEN::p_target (0. , 0. , 0. , mp)
Referenced by UtilDimuon::CalcVar(), SRecDimuon::calcVariables(), SQDimuon_v1::get_x1(), SQDimuon_v1::get_x2(), SQDimuon_v1::get_xf(), and UtilDimuon::GetX1X2().
Variable Documentation
const TVector3 DPGEN::bv_cms = p_cms.BoostVector()
Definition at line 64 of file SQPrimaryParticleGen.C.
Referenced by UtilDimuon::CalcVar(), SRecDimuon::calcVariables(), and SQPrimaryParticleGen::generateDimuon().
const double DPGEN::ebeam = 120.
Definition at line 60 of file SQPrimaryParticleGen.C.
Referenced by UtilDimuon::CalcVar(), and SRecDimuon::calcVariables().
const double DPGEN::mjpsi = 3.097
Definition at line 56 of file SQPrimaryParticleGen.C.
Referenced by SQPrimaryParticleGen::CrossSectionJPsi(), and SQPrimaryParticleGen::generateJPsi().
const double DPGEN::mmu = 0.10566
Definition at line 55 of file SQPrimaryParticleGen.C.
Referenced by SRecTrack::getMomentumVertex().
const double DPGEN::mp = 0.93827
Definition at line 54 of file SQPrimaryParticleGen.C.
Referenced by UtilDimuon::CalcVar(), and SRecDimuon::calcVariables().
const double DPGEN::mpsip = 3.686
Definition at line 57 of file SQPrimaryParticleGen.C.
Referenced by SQPrimaryParticleGen::generatePsip().
const TLorentzVector DPGEN::p_cms = p_beam + p_target
Definition at line 63 of file SQPrimaryParticleGen.C.
Referenced by UtilDimuon::CalcVar(), SRecDimuon::calcVariables(), SQDimuon_v1::get_x1(), SQDimuon_v1::get_x2(), SQDimuon_v1::get_xf(), and UtilDimuon::GetX1X2().
const double DPGEN::pi = TMath::Pi()
Definition at line 49 of file SQPrimaryParticleGen.C.
Referenced by SQPrimaryParticleGen::CrossSectionDrellYan().
const double DPGEN::s = p_cms.M2()
Definition at line 65 of file SQPrimaryParticleGen.C.
Referenced by UtilDimuon::CalcVar(), SRecDimuon::calcVariables(), DrawHodo(), SQPrimaryParticleGen::generateDimuon(), halfToFloat(), kill_trailing(), MakeProjection(), operator>>(), half::round(), G4TBMagneticFieldSetup::SetMinStep(), PHG4Reco::SetPhysicsList(), PHG4PhenixDetector::SetWorldMaterial(), PHG4Reco::SetWorldMaterial(), PHG4PhenixDetector::SetWorldShape(), and PHG4Reco::SetWorldShape().
const double DPGEN::sqrt2pi = TMath::Sqrt(twopi)
Definition at line 51 of file SQPrimaryParticleGen.C.
Referenced by SQPrimaryParticleGen::CrossSectionJPsi().
const double DPGEN::sqrts = p_cms.M()
Definition at line 66 of file SQPrimaryParticleGen.C.
Referenced by UtilDimuon::CalcVar(), SQPrimaryParticleGen::CrossSectionJPsi(), SQPrimaryParticleGen::generateDimuon(), and SQDimuon_v1::get_xf().
const double DPGEN::twopi = 2.*pi
Definition at line 50 of file SQPrimaryParticleGen.C.
Referenced by PHG4BNLTargetCoilDetector::Construct(), PHG4TargetCoilV2Detector::Construct(), PHG4TargetCoilDetector::Construct(), PHG4PolyconDetector::Construct(), PHG4CylinderDetector::Construct(), and SQPrimaryParticleGen::generateDimuon().