E1039 Software: SQScaler Class Reference
SQScaler Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/interface_main/SQScaler.h>
Public Types
enum ScalerType_t { UNDEF = -1, BOS = 0, EOS = 1 }
Public Member Functions
virtual ~SQScaler ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual SQScaler * Clone () const
virtual PHObject * clone () const
Virtual copy constructor.
virtual ScalerType_t get_type () const
virtual void set_type (const ScalerType_t a)
virtual std::string get_name () const
virtual void set_name (const std::string a)
virtual int get_count () const
virtual void set_count (const int a)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQScaler ()
Private Member Functions
ClassDef (SQScaler, 1)
Detailed Description
Definition at line 11 of file SQScaler.h.
Member Enumeration Documentation
ScalerType_t
enum SQScaler::ScalerType_t
Enumerator
UNDEF
BOS
EOS
Definition at line 13 of file SQScaler.h.
Constructor & Destructor Documentation
~SQScaler()
virtual SQScaler::~SQScaler () inline virtual
Definition at line 19 of file SQScaler.h.
SQScaler()
SQScaler::SQScaler () inline protected
Definition at line 39 of file SQScaler.h.
References ClassDef().
Member Function Documentation
ClassDef()
SQScaler::ClassDef (SQScaler , 1) private
Referenced by SQScaler().
Clone()
virtual SQScaler* SQScaler::Clone () const inline virtual
Reimplemented in SQScaler_v1.
Definition at line 28 of file SQScaler.h.
References NULL.
clone()
virtual PHObject* SQScaler::clone () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SQScaler_v1.
Definition at line 29 of file SQScaler.h.
References NULL.
get_count()
virtual int SQScaler::get_count () const inline virtual
Reimplemented in SQScaler_v1.
Definition at line 35 of file SQScaler.h.
Referenced by DbUpSpill::PrintSpill(), and DbUpSpill::UploadToScalerTable().
get_name()
virtual std::string SQScaler::get_name (void) const inline virtual
Reimplemented in SQScaler_v1.
Definition at line 33 of file SQScaler.h.
get_type()
virtual ScalerType_t SQScaler::get_type () const inline virtual
Reimplemented in SQScaler_v1.
Definition at line 31 of file SQScaler.h.
References UNDEF.
identify()
virtual void SQScaler::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SQScaler_v1.
Definition at line 23 of file SQScaler.h.
isValid()
virtual int SQScaler::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SQScaler_v1.
Definition at line 27 of file SQScaler.h.
Reset()
virtual void SQScaler::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SQScaler_v1.
Definition at line 26 of file SQScaler.h.
set_count()
virtual void SQScaler::set_count (const int a) inline virtual
Reimplemented in SQScaler_v1.
Definition at line 36 of file SQScaler.h.
set_name()
virtual void SQScaler::set_name (const std::string a) inline virtual
Reimplemented in SQScaler_v1.
Definition at line 34 of file SQScaler.h.
set_type()
virtual void SQScaler::set_type (const ScalerType_t a) inline virtual
Reimplemented in SQScaler_v1.
Definition at line 32 of file SQScaler.h.
The documentation for this class was generated from the following file:
/home/yuhw/GitHub/SeaQuest/e1039-core/interface_main/SQScaler.h