Class Reference for E1039 Core & Analysis Software: SQEvent Class Reference
SQEvent Class Reference abstract
An SQ interface class to hold one event header.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQEvent.h>
Public Types
enum TriggerMask {
NIM1 = 0 , NIM2 = 1 , NIM3 = 2 , NIM4 = 3 ,
NIM5 = 4 , MATRIX1 = 5 , MATRIX2 = 6 , MATRIX3 = 7 ,
MATRIX4 = 8 , MATRIX5 = 9
}
Public Member Functions
virtual ~SQEvent ()
void Reset ()
Clear Event.
virtual void identify (std::ostream &os=std::cout) const
virtual int get_run_id () const =0
Return the run ID.
virtual void set_run_id (const int a)=0
virtual int get_spill_id () const =0
Return the spill ID.
virtual void set_spill_id (const int a)=0
virtual int get_event_id () const =0
Return the event ID, which is unique per run.
virtual void set_event_id (const int a)=0
virtual int get_coda_event_id () const
[Obsolete] Use SQHardEvent instead.
virtual void set_coda_event_id (const int a)
virtual int get_data_quality () const =0
Return the data-quality bits.
virtual void set_data_quality (const int a)=0
virtual int get_vme_time () const
[Obsolete] Use SQHardEvent instead.
virtual void set_vme_time (const int a)
virtual bool get_trigger (const SQEvent::TriggerMask i) const =0
Return the trigger bit (fired or not) of the selected trigger channel.
virtual void set_trigger (const SQEvent::TriggerMask i, const bool a)=0
virtual unsigned short get_trigger () const =0
Return the full trigger bits.
virtual void set_trigger (const unsigned short a)=0
virtual int get_raw_matrix (const unsigned short i) const
[Obsolete] Use SQHardEvent instead.
virtual void set_raw_matrix (const unsigned short i, const bool a)
virtual int get_after_inh_matrix (const unsigned short i) const
[Obsolete] Use SQHardEvent instead.
virtual void set_after_inh_matrix (const unsigned short i, const bool a)
virtual int get_qie_presum (const unsigned short i) const =0
Return the i-th QIE presum, where i=0...3.
virtual void set_qie_presum (const unsigned short i, const int a)=0
virtual int get_qie_trigger_count () const =0
Return the QIE trigger counts.
virtual void set_qie_trigger_count (const int a)=0
virtual int get_qie_turn_id () const =0
Return the QIE turn ID.
virtual void set_qie_turn_id (const int a)=0
virtual int get_qie_rf_id () const =0
Return the QIE RF ID.
virtual void set_qie_rf_id (const int a)=0
virtual int get_qie_rf_intensity (const short i) const =0
Return the i-th QIE RF intensity, where i=-16...+16.
virtual void set_qie_rf_intensity (const short i, const int a)=0
virtual short get_flag_v1495 () const
[Obsolete] Use SQHardEvent instead.
virtual void set_flag_v1495 (const short a)
virtual short get_n_board_qie () const
[Obsolete] Use SQHardEvent instead.
virtual void set_n_board_qie (const short a)
virtual short get_n_board_v1495 () const
[Obsolete] Use SQHardEvent instead.
virtual void set_n_board_v1495 (const short a)
virtual short get_n_board_taiwan () const
[Obsolete] Use SQHardEvent instead.
virtual void set_n_board_taiwan (const short a)
virtual short get_n_board_trig_bit () const
[Obsolete] Use SQHardEvent instead.
virtual void set_n_board_trig_bit (const short a)
virtual short get_n_board_trig_count () const
[Obsolete] Use SQHardEvent instead.
virtual void set_n_board_trig_count (const short a)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQEvent ()
ClassDef (SQEvent, 1)
Detailed Description
An SQ interface class to hold one event header.
Definition at line 17 of file SQEvent.h.
Member Enumeration Documentation
TriggerMask
enum SQEvent::TriggerMask
Enumerator
NIM1
NIM2
NIM3
NIM4
NIM5
MATRIX1
MATRIX2
MATRIX3
MATRIX4
MATRIX5
Definition at line 21 of file SQEvent.h.
Constructor & Destructor Documentation
~SQEvent()
virtual SQEvent::~SQEvent () inline virtual
Definition at line 34 of file SQEvent.h.
SQEvent()
SQEvent::SQEvent () inline protected
Definition at line 133 of file SQEvent.h.
Member Function Documentation
ClassDef()
SQEvent::ClassDef (SQEvent , 1) protected
get_after_inh_matrix()
virtual int SQEvent::get_after_inh_matrix (const unsigned short i) const inline virtual
[Obsolete] Use SQHardEvent instead.
Reimplemented in SQEvent_v1.
Definition at line 81 of file SQEvent.h.
get_coda_event_id()
virtual int SQEvent::get_coda_event_id () const inline virtual
[Obsolete] Use SQHardEvent instead.
Reimplemented in SQEvent_v1.
Definition at line 57 of file SQEvent.h.
get_data_quality()
virtual int SQEvent::get_data_quality () const pure virtual
Return the data-quality bits.
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by OnlMonMainDaq::ProcessEventOnlMon().
get_event_id()
virtual int SQEvent::get_event_id () const pure virtual
Return the event ID, which is unique per run.
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by UtilSQHit::FindHitsFast(), UtilSQHit::FindTriggerHitsFast(), AnaChamHit::process_event(), AnaHardEvent::process_event(), AnaSimRunInfo::process_event(), AnaSimDimuon::process_event(), SubsysRecoBG::process_event(), AnaEmbeddedData::process_event(), DoEmbedding::process_event(), AnaPileup::process_event(), AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), AnaDimuonV2::process_event(), SimpleTree::process_event(), EvtDispFilter::process_event(), EvtFilter::process_event(), and UtilSRawEvent::SetEvent().
get_flag_v1495()
virtual short SQEvent::get_flag_v1495 () const inline virtual
[Obsolete] Use SQHardEvent instead.
Reimplemented in SQEvent_v1.
Definition at line 107 of file SQEvent.h.
get_n_board_qie()
virtual short SQEvent::get_n_board_qie () const inline virtual
[Obsolete] Use SQHardEvent instead.
Reimplemented in SQEvent_v1.
Definition at line 111 of file SQEvent.h.
get_n_board_taiwan()
virtual short SQEvent::get_n_board_taiwan () const inline virtual
[Obsolete] Use SQHardEvent instead.
Reimplemented in SQEvent_v1.
Definition at line 119 of file SQEvent.h.
get_n_board_trig_bit()
virtual short SQEvent::get_n_board_trig_bit () const inline virtual
[Obsolete] Use SQHardEvent instead.
Reimplemented in SQEvent_v1.
Definition at line 123 of file SQEvent.h.
get_n_board_trig_count()
virtual short SQEvent::get_n_board_trig_count () const inline virtual
[Obsolete] Use SQHardEvent instead.
Reimplemented in SQEvent_v1.
Definition at line 127 of file SQEvent.h.
get_n_board_v1495()
virtual short SQEvent::get_n_board_v1495 () const inline virtual
[Obsolete] Use SQHardEvent instead.
Reimplemented in SQEvent_v1.
Definition at line 115 of file SQEvent.h.
get_qie_presum()
virtual int SQEvent::get_qie_presum (const unsigned short i) const pure virtual
Return the i-th QIE presum, where i=0...3.
Implemented in SQEvent_v2, and SQEvent_v1.
get_qie_rf_id()
virtual int SQEvent::get_qie_rf_id () const pure virtual
Return the QIE RF ID.
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by DoEmbedding::process_event(), and OnlMonQie::ProcessEventOnlMon().
get_qie_rf_intensity()
virtual int SQEvent::get_qie_rf_intensity (const short i) const pure virtual
Return the i-th QIE RF intensity, where i=-16...+16.
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by SubsysRecoBG::process_event(), AnaEmbeddedData::process_event(), DoEmbedding::process_event(), and OnlMonQie::ProcessEventOnlMon().
get_qie_trigger_count()
virtual int SQEvent::get_qie_trigger_count () const pure virtual
Return the QIE trigger counts.
Implemented in SQEvent_v2, and SQEvent_v1.
get_qie_turn_id()
virtual int SQEvent::get_qie_turn_id () const pure virtual
Return the QIE turn ID.
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by DoEmbedding::process_event(), and OnlMonQie::ProcessEventOnlMon().
get_raw_matrix()
virtual int SQEvent::get_raw_matrix (const unsigned short i) const inline virtual
[Obsolete] Use SQHardEvent instead.
Reimplemented in SQEvent_v1.
Definition at line 77 of file SQEvent.h.
get_run_id()
virtual int SQEvent::get_run_id () const pure virtual
Return the run ID.
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by UtilSQHit::FindHitsFast(), UtilSQHit::FindTriggerHitsFast(), AnaChamHit::process_event(), AnaSimRunInfo::process_event(), SubsysRecoBG::process_event(), DoEmbedding::process_event(), AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), AnaDimuonV2::process_event(), UtilSRawEvent::SetEvent(), Fun4AllSpillDstOutputManager::Write(), and Fun4AllSpillSRawEventOutputManager::Write().
get_spill_id()
virtual int SQEvent::get_spill_id () const pure virtual
Return the spill ID.
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by AnaChamHit::process_event(), AnaHardEvent::process_event(), MakeMyTree::process_event(), AnaEmbeddedData::process_event(), DoEmbedding::process_event(), FilterE906Nim3::process_event(), AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), AnaDimuonV2::process_event(), DbUpSpill::process_event(), EvtDispFilter::process_event(), E906SpillSelector::process_event(), OnlMonMainDaq::ProcessEventOnlMon(), UtilSRawEvent::SetEvent(), Fun4AllSRawEventOutputManagerV2::Write(), Fun4AllSpillDstOutputManager::Write(), Fun4AllSpillSRawEventOutputManager::Write(), and Fun4AllSRawEventOutputManager::Write().
get_trigger() [1/2]
virtual unsigned short SQEvent::get_trigger () const pure virtual
Return the full trigger bits.
Implemented in SQEvent_v2, and SQEvent_v1.
get_trigger() [2/2]
virtual bool SQEvent::get_trigger (const SQEvent::TriggerMask i) const pure virtual
Return the trigger bit (fired or not) of the selected trigger channel.
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by AnaChamHit::process_event(), AnaHodoHit::process_event(), AnaSimDst::process_event(), SRMakeRTCurve::process_event(), AnaSimDimuon::process_event(), SubsysRecoBG::process_event(), AnaEmbeddedData::process_event(), FilterE906Nim3::process_event(), AnaPileup::process_event(), AnaDimuon::process_event(), AnaDimuonLikeSign::process_event(), AnaDimuonV2::process_event(), SimpleTree::process_event(), EvtDispFilter::process_event(), EvtFilter::process_event(), FilterByTrigger::process_event(), OnlMonMainDaq::ProcessEventOnlMon(), OnlMonTrigEP::ProcessEventOnlMon(), OnlMonTrigV1495::ProcessEventOnlMon(), OnlMonV1495::ProcessEventOnlMon(), UtilSRawEvent::SetEvent(), and Fun4AllTriggerDstOutputManager::Write().
get_vme_time()
virtual int SQEvent::get_vme_time () const inline virtual
[Obsolete] Use SQHardEvent instead.
Reimplemented in SQEvent_v1.
Definition at line 65 of file SQEvent.h.
identify()
virtual void SQEvent::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SQEvent_v2, and SQEvent_v1.
Definition at line 38 of file SQEvent.h.
Referenced by EvtFilter::process_event().
Reset()
void SQEvent::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SQEvent_v2, and SQEvent_v1.
Definition at line 36 of file SQEvent.h.
set_after_inh_matrix()
virtual void SQEvent::set_after_inh_matrix (const unsigned short i, const bool a) inline virtual
Reimplemented in SQEvent_v1.
Definition at line 82 of file SQEvent.h.
set_coda_event_id()
virtual void SQEvent::set_coda_event_id (const int a) inline virtual
Reimplemented in SQEvent_v1.
Definition at line 58 of file SQEvent.h.
set_data_quality()
virtual void SQEvent::set_data_quality (const int a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_event_id()
virtual void SQEvent::set_event_id (const int a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), TruthNodeMaker::process_event(), PHG4SimpleEventGenerator::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_flag_v1495()
virtual void SQEvent::set_flag_v1495 (const short a) inline virtual
Reimplemented in SQEvent_v1.
Definition at line 108 of file SQEvent.h.
set_n_board_qie()
virtual void SQEvent::set_n_board_qie (const short a) inline virtual
Reimplemented in SQEvent_v1.
Definition at line 112 of file SQEvent.h.
set_n_board_taiwan()
virtual void SQEvent::set_n_board_taiwan (const short a) inline virtual
Reimplemented in SQEvent_v1.
Definition at line 120 of file SQEvent.h.
set_n_board_trig_bit()
virtual void SQEvent::set_n_board_trig_bit (const short a) inline virtual
Reimplemented in SQEvent_v1.
Definition at line 124 of file SQEvent.h.
set_n_board_trig_count()
virtual void SQEvent::set_n_board_trig_count (const short a) inline virtual
Reimplemented in SQEvent_v1.
Definition at line 128 of file SQEvent.h.
set_n_board_v1495()
virtual void SQEvent::set_n_board_v1495 (const short a) inline virtual
Reimplemented in SQEvent_v1.
Definition at line 116 of file SQEvent.h.
set_qie_presum()
virtual void SQEvent::set_qie_presum (const unsigned short i, const int a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_qie_rf_id()
virtual void SQEvent::set_qie_rf_id (const int a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), DoEmbedding::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_qie_rf_intensity()
virtual void SQEvent::set_qie_rf_intensity (const short i, const int a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), DoEmbedding::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_qie_trigger_count()
virtual void SQEvent::set_qie_trigger_count (const int a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by Fun4AllEVIOInputManager::run().
set_qie_turn_id()
virtual void SQEvent::set_qie_turn_id (const int a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), DoEmbedding::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_raw_matrix()
virtual void SQEvent::set_raw_matrix (const unsigned short i, const bool a) inline virtual
Reimplemented in SQEvent_v1.
Definition at line 78 of file SQEvent.h.
set_run_id()
virtual void SQEvent::set_run_id (const int a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), TruthNodeMaker::process_event(), PHG4SimpleEventGenerator::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_spill_id()
virtual void SQEvent::set_spill_id (const int a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), TruthNodeMaker::process_event(), PHG4SimpleEventGenerator::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_trigger() [1/2]
virtual void SQEvent::set_trigger (const SQEvent::TriggerMask i, const bool a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), DPTriggerAnalyzer::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_trigger() [2/2]
virtual void SQEvent::set_trigger (const unsigned short a) pure virtual
Implemented in SQEvent_v2, and SQEvent_v1.
set_vme_time()
virtual void SQEvent::set_vme_time (const int a) inline virtual
Reimplemented in SQEvent_v1.
Definition at line 66 of file SQEvent.h.
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQEvent.h