Class Reference for E1039 Core & Analysis Software: AnaPileup Class Reference
AnaPileup Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/PileupDev/src/AnaPileup.h>
Public Member Functions
AnaPileup (const std::string &name="AnaPileup.root")
virtual ~AnaPileup ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
===========================
int InitEvalTree ()
int ResetEvalVars ()
const std::string & get_out_name () const
void set_out_name (const std::string &outName)
void set_legacy_rec_container (bool b)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
\ module for pileup study
Author
Abinash Pun
module for bkg pile up study
Author
Abinash Pun
Created: December-2021
Definition at line 49 of file AnaPileup.h.
Constructor & Destructor Documentation
AnaPileup::AnaPileup (const std::string & name = "AnaPileup.root")
Definition at line 39 of file AnaPileup.cc.
AnaPileup::~AnaPileup () virtual
Definition at line 49 of file AnaPileup.cc.
Member Function Documentation
int AnaPileup::End (PHCompositeNode * topNode) virtual
===========================
Reimplemented from SubsysReco.
Definition at line 139 of file AnaPileup.cc.
References PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
const std::string& AnaPileup::get_out_name () const inline
Definition at line 65 of file AnaPileup.h.
int AnaPileup::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 75 of file AnaPileup.cc.
References Fun4AllReturnCodes::EVENT_OK.
int AnaPileup::InitEvalTree ()
For the pileup tree with hit information ======================
Trigger info
HODO HITS
CHAMBER HITS
Definition at line 281 of file AnaPileup.cc.
References PHTFileServer::get(), and PHTFileServer::open().
Referenced by InitRun().
int AnaPileup::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 100 of file AnaPileup.cc.
References Fun4AllReturnCodes::EVENT_OK, InitEvalTree(), GeomSvc::instance(), and ResetEvalVars().
int AnaPileup::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 113 of file AnaPileup.cc.
References Fun4AllReturnCodes::EVENT_OK, SQMCEvent::get_cross_section(), SQEvent::get_event_id(), SQEvent::get_trigger(), SQEvent::MATRIX1, SQEvent::MATRIX2, SQEvent::MATRIX3, SQEvent::MATRIX4, SQEvent::MATRIX5, SQEvent::NIM1, and SQEvent::NIM2.
int AnaPileup::ResetEvalVars ()
Definition at line 394 of file AnaPileup.cc.
Referenced by InitRun().
void AnaPileup::set_legacy_rec_container (bool b) inline
Definition at line 72 of file AnaPileup.h.
Referenced by Fun4Sim_pileup().
void AnaPileup::set_out_name (const std::string & outName) inline
Definition at line 69 of file AnaPileup.h.
Referenced by Fun4Sim_pileup().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/PileupDev/src/AnaPileup.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/PileupDev/src/AnaPileup.cc