Class Reference for E1039 Core & Analysis Software: SimpleTree Class Reference
SimpleTree Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TriggerAna/src/SimpleTree.h>
Public Member Functions
SimpleTree (const std::string &name="SimpleTree")
virtual ~SimpleTree ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetOutput (const char *out_name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 20 of file SimpleTree.h.
Constructor & Destructor Documentation
SimpleTree::SimpleTree (const std::string & name = "SimpleTree")
Definition at line 24 of file SimpleTree.cc.
virtual SimpleTree::~SimpleTree () inline virtual
Definition at line 56 of file SimpleTree.h.
Member Function Documentation
int SimpleTree::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 193 of file SimpleTree.cc.
References Fun4AllReturnCodes::EVENT_OK.
int SimpleTree::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 30 of file SimpleTree.cc.
References Fun4AllReturnCodes::EVENT_OK.
int SimpleTree::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 36 of file SimpleTree.cc.
References Fun4AllReturnCodes::EVENT_OK.
int SimpleTree::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Get MC Event Info
Get DAQ Event Info
Dimuon info
Track info
Hit info
Tracklet info (+ Sorted Hit info)
Reimplemented from SubsysReco.
Definition at line 48 of file SimpleTree.cc.
References SQDimuonVector::at(), SQTrackVector::at(), SQHitVector::at(), TrackletVector::at(), TrackData::charge, TrackletData::charge, TrackletData::chisq, HitData::detector_id, TrackletData::detector_id, TrackletData::detector_zpos, dID, DimuonData::dim_id, HitData::element_id, TrackletData::element_id_closest, TrackletData::element_id_exp, TrackletData::element_id_pos, EventData::event_id, Fun4AllReturnCodes::EVENT_OK, SQTrack::get_charge(), SQHit::get_detector_id(), SQDimuon::get_dimuon_id(), SQHit::get_element_id(), SQEvent::get_event_id(), SQHit::get_hit_id(), SQDimuon::get_mass(), SQDimuon::get_mom(), SQDimuon::get_mom_neg(), SQDimuon::get_mom_pos(), SQMCEvent::get_particle_id(), SQMCEvent::get_particle_momentum(), SQDimuon::get_pdg_id(), SQHit::get_pos(), SQTrack::get_pos_vtx(), SQMCEvent::get_process_id(), SQHit::get_tdc_time(), SQTrack::get_track_id(), SQHit::get_track_id(), SQDimuon::get_track_id_neg(), SQDimuon::get_track_id_pos(), SQEvent::get_trigger(), SQDimuon::get_x1(), SQDimuon::get_x2(), SQDimuon::get_xf(), Tracklet::getCharge(), Tracklet::getChisq(), GeomSvc::getExpElementID(), Tracklet::getExpPositionW(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::getNHits(), GeomSvc::getPlaneNElements(), GeomSvc::getPlanePosition(), HitData::hit_id, TrackletData::hit_id, TrackletData::in_plane, HitData::in_time, SQHit::is_in_time(), GeomSvc::isInPlane(), DimuonData::mass, DimuonData::mom, DimuonData::mom_neg, DimuonData::mom_pos, TrackletData::n_hits, MCEventData::particle_id, MCEventData::particle_mom, DimuonData::pdg_id, MCEventData::process_id, SQDimuonVector::size(), SQTrackVector::size(), SQHitVector::size(), TrackletVector::size(), HitData::tdc_time, TrackData::track_id, HitData::track_id, TrackletData::track_id, DimuonData::track_id_neg, DimuonData::track_id_pos, EventData::trig_bits, DimuonData::x1, DimuonData::x2, TrackletData::x_exp, DimuonData::xf, TrackletData::y_exp, and TrackData::zvtx.
void SimpleTree::SetOutput (const char * out_name)
Definition at line 220 of file SimpleTree.cc.
Referenced by Fun4SimMicroDst().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TriggerAna/src/SimpleTree.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TriggerAna/src/SimpleTree.cc