Class Reference for E1039 Core & Analysis Software: Fun4AllSRawEventInputManager Class Reference
Fun4AllSRawEventInputManager Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/Fun4AllSRawEventInputManager.h>
Public Member Functions
Fun4AllSRawEventInputManager (const std::string &name="DUMMY", const std::string &topnodename="TOP")
virtual ~Fun4AllSRawEventInputManager ()
int fileopen (const std::string &filenam)
int fileclose ()
int run (const int nevents=0)
int isOpen ()
void Print (const std::string &what="ALL") const
int ResetEvent ()
int PushBackEvents (const int i)
int GetSyncObject (SyncObject **mastersync)
int SyncIt (const SyncObject *mastersync)
void enable_E1039_translation ()
const std::string & get_branch_name () const
void set_branch_name (const std::string &branchName)
const std::string & get_tree_name () const
void set_tree_name (const std::string &treeName)
Public Member Functions inherited from Fun4AllInputManager
virtual ~Fun4AllInputManager ()
virtual int ReadInRunNode (PHCompositeNode *)
virtual std::string Filename ()
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
virtual int skip (const int nevt)
virtual int NoSyncPushBackEvents (const int)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
int ResetFileList ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
const std::list< std::string > GetFileList () const
const std::list< std::string > GetFileOpenedList () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int OpenNextFile ()
void E906ToE1039 ()
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
int segment
int isopen
int events_total
int events_thisfile
std::string topNodeName
PHCompositeNode * topNode
SyncObject * syncobject
std::string _tree_name
std::string _branch_name
TFile * _fin
TTree * _tin
SRawEvent * _srawEvent
bool _enable_e1039_translation
sraw event pointer on the DST node as well as the TTree, is this gonna be faster?
SQRun * run_header
SQSpillMap * spill_map
SQEvent * event_header
SQHitVector * hit_vec
SQHitVector * trig_hit_vec
Protected Attributes inherited from Fun4AllInputManager
std::vector< SubsysReco * > Subsystems
std::string InputNode
std::string filename
std::string topNodeName
std::list< std::string > filelist
std::list< std::string > filelist_copy
std::list< std::string > filelist_opened
Fun4AllSyncManager * mySyncManager
int repeat
int myrunnumber
int initrun
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 21 of file Fun4AllSRawEventInputManager.h.
Constructor & Destructor Documentation
Fun4AllSRawEventInputManager()
Fun4AllSRawEventInputManager::Fun4AllSRawEventInputManager (const std::string & name = "DUMMY", const std::string & topnodename = "TOP")
Definition at line 40 of file Fun4AllSRawEventInputManager.cxx.
References _srawEvent, PHCompositeNode::addNode(), PHNodeIterator::findFirst(), Fun4AllServer::instance(), syncobject, Fun4AllServer::topNode(), topNode, and topNodeName.
~Fun4AllSRawEventInputManager()
Fun4AllSRawEventInputManager::~Fun4AllSRawEventInputManager () virtual
Definition at line 79 of file Fun4AllSRawEventInputManager.cxx.
References fileclose(), isopen, and syncobject.
Member Function Documentation
E906ToE1039()
void Fun4AllSRawEventInputManager::E906ToE1039 () protected
Definition at line 123 of file Fun4AllSRawEventInputManager.cxx.
References _srawEvent, event_header, SQSpillMap::get(), SRawEvent::getAllHits(), SRawEvent::getEventID(), SRawEvent::getIntensity(), SRawEvent::getRFID(), SRawEvent::getRunID(), SRawEvent::getSpillID(), SRawEvent::getTriggerHits(), SRawEvent::getTurnID(), hit_vec, SQSpillMap::insert(), SRawEvent::isTriggeredBy(), SQEvent::MATRIX1, SRawEvent::MATRIX1, SQEvent::MATRIX2, SRawEvent::MATRIX2, SQEvent::MATRIX3, SRawEvent::MATRIX3, SQEvent::MATRIX4, SRawEvent::MATRIX4, SQEvent::MATRIX5, SRawEvent::MATRIX5, SQEvent::NIM1, SRawEvent::NIM1, SQEvent::NIM2, SRawEvent::NIM2, SQEvent::NIM3, SRawEvent::NIM3, SQEvent::NIM4, SRawEvent::NIM4, SQEvent::NIM5, SRawEvent::NIM5, SQHitVector::push_back(), run_header, SQEvent::set_data_quality(), SQHit::set_detector_id(), SQHit::set_element_id(), SQEvent::set_event_id(), SQHit::set_hit_id(), SQHit::set_in_time(), SQRun::set_n_spill(), SQEvent::set_qie_rf_id(), SQEvent::set_qie_rf_intensity(), SQEvent::set_qie_turn_id(), SQRun::set_run_id(), SQSpill::set_run_id(), SQEvent::set_run_id(), SQSpill::set_spill_id(), SQEvent::set_spill_id(), SQHit::set_tdc_time(), SQEvent::set_trigger(), SQSpillMap::size(), spill_map, and trig_hit_vec.
Referenced by run().
enable_E1039_translation()
void Fun4AllSRawEventInputManager::enable_E1039_translation ()
Definition at line 88 of file Fun4AllSRawEventInputManager.cxx.
References _enable_e1039_translation, PHCompositeNode::addNode(), event_header, PHNodeIterator::findFirst(), hit_vec, Fun4AllServer::instance(), run_header, spill_map, Fun4AllServer::topNode(), topNode, topNodeName, and trig_hit_vec.
fileclose()
int Fun4AllSRawEventInputManager::fileclose () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 282 of file Fun4AllSRawEventInputManager.cxx.
References _fin, Fun4AllInputManager::filelist, isopen, Fun4AllBase::Name(), and Fun4AllInputManager::repeat.
Referenced by fileopen(), run(), and ~Fun4AllSRawEventInputManager().
fileopen()
int Fun4AllSRawEventInputManager::fileopen (const std::string & filenam) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 182 of file Fun4AllSRawEventInputManager.cxx.
References _branch_name, _fin, _srawEvent, _tin, _tree_name, Fun4AllInputManager::AddToFileOpened(), events_thisfile, fileclose(), Fun4AllInputManager::filename, isopen, PHWHERE, segment, Fun4AllBase::ThisName, and Fun4AllBase::verbosity.
Referenced by OpenNextFile().
get_branch_name()
const std::string& Fun4AllSRawEventInputManager::get_branch_name () const inline
Definition at line 39 of file Fun4AllSRawEventInputManager.h.
References _branch_name.
get_tree_name()
const std::string& Fun4AllSRawEventInputManager::get_tree_name () const inline
Definition at line 47 of file Fun4AllSRawEventInputManager.h.
References _tree_name.
GetSyncObject()
int Fun4AllSRawEventInputManager::GetSyncObject (SyncObject ** mastersync) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 412 of file Fun4AllSRawEventInputManager.cxx.
References SyncObject::clone(), Fun4AllReturnCodes::SYNC_OK, and syncobject.
isOpen()
int Fun4AllSRawEventInputManager::isOpen () inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 29 of file Fun4AllSRawEventInputManager.h.
References isopen.
OpenNextFile()
int Fun4AllSRawEventInputManager::OpenNextFile () protected
Definition at line 316 of file Fun4AllSRawEventInputManager.cxx.
References Fun4AllInputManager::filelist, fileopen(), PHWHERE, and Fun4AllBase::verbosity.
Referenced by run().
Print()
void Fun4AllSRawEventInputManager::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllInputManager.
Definition at line 309 of file Fun4AllSRawEventInputManager.cxx.
References Fun4AllInputManager::Print().
PushBackEvents()
int Fun4AllSRawEventInputManager::PushBackEvents (const int i) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 352 of file Fun4AllSRawEventInputManager.cxx.
ResetEvent()
int Fun4AllSRawEventInputManager::ResetEvent () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 340 of file Fun4AllSRawEventInputManager.cxx.
References SyncObject::Reset(), and syncobject.
Referenced by run().
run()
int Fun4AllSRawEventInputManager::run (const int nevents = 0) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 224 of file Fun4AllSRawEventInputManager.cxx.
References _enable_e1039_translation, _srawEvent, _tin, Fun4AllSyncManager::CurrentEvent(), E906ToE1039(), Fun4AllReturnCodes::EVENT_OK, SyncObject::EventCounter(), SyncObject::EventNumber(), events_thisfile, events_total, fileclose(), Fun4AllInputManager::filelist, SRawEvent::getEventID(), SRawEvent::getRunID(), SRawEvent::getSpillID(), SRawEvent::identify(), isopen, Fun4AllInputManager::mySyncManager, Fun4AllBase::Name(), OpenNextFile(), Fun4AllSyncManager::PrdfEvents(), Fun4AllInputManager::RejectEvent(), ResetEvent(), SyncObject::RunNumber(), Fun4AllSyncManager::SegmentNumber(), SyncObject::SegmentNumber(), Fun4AllInputManager::SetRunNumber(), syncobject, Fun4AllBase::verbosity, and Fun4AllBase::VERBOSITY_A_LOT.
set_branch_name()
void Fun4AllSRawEventInputManager::set_branch_name (const std::string & branchName) inline
Definition at line 43 of file Fun4AllSRawEventInputManager.h.
References _branch_name.
set_tree_name()
void Fun4AllSRawEventInputManager::set_tree_name (const std::string & treeName) inline
Definition at line 51 of file Fun4AllSRawEventInputManager.h.
References _tree_name.
SyncIt()
int Fun4AllSRawEventInputManager::SyncIt (const SyncObject * mastersync) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 430 of file Fun4AllSRawEventInputManager.cxx.
References SyncObject::Different(), Fun4AllBase::Name(), PHWHERE, Fun4AllReturnCodes::SYNC_FAIL, Fun4AllReturnCodes::SYNC_OK, and syncobject.
Member Data Documentation
_branch_name
std::string Fun4AllSRawEventInputManager::_branch_name protected
Definition at line 68 of file Fun4AllSRawEventInputManager.h.
Referenced by fileopen(), get_branch_name(), and set_branch_name().
_enable_e1039_translation
bool Fun4AllSRawEventInputManager::_enable_e1039_translation protected
sraw event pointer on the DST node as well as the TTree, is this gonna be faster?
Definition at line 75 of file Fun4AllSRawEventInputManager.h.
Referenced by enable_E1039_translation(), and run().
_fin
TFile* Fun4AllSRawEventInputManager::_fin protected
Definition at line 70 of file Fun4AllSRawEventInputManager.h.
Referenced by fileclose(), and fileopen().
_srawEvent
SRawEvent* Fun4AllSRawEventInputManager::_srawEvent protected
Definition at line 72 of file Fun4AllSRawEventInputManager.h.
Referenced by E906ToE1039(), fileopen(), Fun4AllSRawEventInputManager(), and run().
_tin
TTree* Fun4AllSRawEventInputManager::_tin protected
Definition at line 71 of file Fun4AllSRawEventInputManager.h.
Referenced by fileopen(), and run().
_tree_name
std::string Fun4AllSRawEventInputManager::_tree_name protected
Definition at line 67 of file Fun4AllSRawEventInputManager.h.
Referenced by fileopen(), get_tree_name(), and set_tree_name().
event_header
SQEvent* Fun4AllSRawEventInputManager::event_header protected
Definition at line 78 of file Fun4AllSRawEventInputManager.h.
Referenced by E906ToE1039(), and enable_E1039_translation().
events_thisfile
int Fun4AllSRawEventInputManager::events_thisfile protected
Definition at line 62 of file Fun4AllSRawEventInputManager.h.
Referenced by fileopen(), and run().
events_total
int Fun4AllSRawEventInputManager::events_total protected
Definition at line 61 of file Fun4AllSRawEventInputManager.h.
Referenced by run().
hit_vec
SQHitVector* Fun4AllSRawEventInputManager::hit_vec protected
Definition at line 79 of file Fun4AllSRawEventInputManager.h.
Referenced by E906ToE1039(), and enable_E1039_translation().
isopen
int Fun4AllSRawEventInputManager::isopen protected
Definition at line 60 of file Fun4AllSRawEventInputManager.h.
Referenced by fileclose(), fileopen(), isOpen(), run(), and ~Fun4AllSRawEventInputManager().
run_header
SQRun* Fun4AllSRawEventInputManager::run_header protected
Definition at line 76 of file Fun4AllSRawEventInputManager.h.
Referenced by E906ToE1039(), and enable_E1039_translation().
segment
int Fun4AllSRawEventInputManager::segment protected
Definition at line 59 of file Fun4AllSRawEventInputManager.h.
Referenced by fileopen().
spill_map
SQSpillMap* Fun4AllSRawEventInputManager::spill_map protected
Definition at line 77 of file Fun4AllSRawEventInputManager.h.
Referenced by E906ToE1039(), and enable_E1039_translation().
syncobject
SyncObject* Fun4AllSRawEventInputManager::syncobject protected
Definition at line 65 of file Fun4AllSRawEventInputManager.h.
Referenced by Fun4AllSRawEventInputManager(), GetSyncObject(), ResetEvent(), run(), SyncIt(), and ~Fun4AllSRawEventInputManager().
topNode
PHCompositeNode* Fun4AllSRawEventInputManager::topNode protected
Definition at line 64 of file Fun4AllSRawEventInputManager.h.
Referenced by enable_E1039_translation(), and Fun4AllSRawEventInputManager().
topNodeName
std::string Fun4AllSRawEventInputManager::topNodeName protected
Definition at line 63 of file Fun4AllSRawEventInputManager.h.
Referenced by enable_E1039_translation(), and Fun4AllSRawEventInputManager().
trig_hit_vec
SQHitVector* Fun4AllSRawEventInputManager::trig_hit_vec protected
Definition at line 80 of file Fun4AllSRawEventInputManager.h.
Referenced by E906ToE1039(), and enable_E1039_translation().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/Fun4AllSRawEventInputManager.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/Fun4AllSRawEventInputManager.cxx