Class Reference for E1039 Core & Analysis Software: PHG4HitEval Class Reference
PHG4HitEval Class Reference
PHG4HitEval for evaluating PHG4Hitv1 in CINT readable evaluation trees.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4HitEval.h>
Public Member Functions
PHG4HitEval ()
PHG4HitEval (const PHG4Hit &g4hit)
virtual ~PHG4HitEval ()
virtual void Copy (PHG4Hit const &g4hit)
float get_eion () const
void set_eion (const float f)
int get_scint_id () const
void set_scint_id (const int i)
float get_light_yield () const
void set_light_yield (float lightYield)
float get_path_length () const
void set_path_length (float pathLength)
Public Member Functions inherited from PHG4Hitv1
PHG4Hitv1 ()
PHG4Hitv1 (const PHG4Hit &g4hit)
virtual ~PHG4Hitv1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
float get_x (const int i) const
float get_y (const int i) const
float get_z (const int i) const
float get_t (const int i) const
float get_edep () const
PHG4HitDefs::keytype get_hit_id () const
int get_detid () const
int get_shower_id () const
int get_trkid () const
void set_x (const int i, const float f)
void set_y (const int i, const float f)
void set_z (const int i, const float f)
void set_t (const int i, const float f)
void set_edep (const float f)
void set_hit_id (const PHG4HitDefs::keytype i)
void set_shower_id (const int i)
void set_trkid (const int i)
virtual void print () const
bool has_property (const PROPERTY prop_id) const
float get_property_float (const PROPERTY prop_id) const
int get_property_int (const PROPERTY prop_id) const
unsigned int get_property_uint (const PROPERTY prop_id) const
void set_property (const PROPERTY prop_id, const float value)
void set_property (const PROPERTY prop_id, const int value)
void set_property (const PROPERTY prop_id, const unsigned int value)
virtual float get_px (const int i) const
virtual float get_py (const int i) const
virtual float get_pz (const int i) const
virtual float get_local_x (const int i) const
virtual float get_local_y (const int i) const
virtual float get_local_z (const int i) const
virtual unsigned int get_layer () const
virtual int get_row () const
virtual int get_strip_z_index () const
virtual int get_strip_y_index () const
virtual int get_ladder_z_index () const
virtual int get_ladder_phi_index () const
virtual int get_index_i () const
virtual int get_index_j () const
virtual int get_index_k () const
virtual int get_index_l () const
virtual int get_hit_type () const
virtual void set_px (const int i, const float f)
virtual void set_py (const int i, const float f)
virtual void set_pz (const int i, const float f)
virtual void set_local_x (const int i, const float f)
virtual void set_local_y (const int i, const float f)
virtual void set_local_z (const int i, const float f)
virtual void set_layer (const unsigned int i)
virtual void set_row (const int i)
virtual void set_strip_z_index (const int i)
virtual void set_strip_y_index (const int i)
virtual void set_ladder_z_index (const int i)
virtual void set_ladder_phi_index (const int i)
virtual void set_index_i (const int i)
virtual void set_index_j (const int i)
virtual void set_index_k (const int i)
virtual void set_index_l (const int i)
virtual void set_hit_type (const int i)
Public Member Functions inherited from PHG4Hit
PHG4Hit ()
virtual ~PHG4Hit ()
virtual float get_avg_x () const
virtual float get_avg_y () const
virtual float get_avg_z () const
virtual float get_avg_t () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
float eion
int scint_id
float light_yield
a number proportional to the scintillation light yield.
float path_length
path length of the track to the hit
Protected Attributes inherited from PHG4Hitv1
float x [2]
float y [2]
float z [2]
float t [2]
PHG4HitDefs::keytype hitid
int trackid
int showerid
float edep
prop_map_t prop_map
container for additional property
Additional Inherited Members
Public Types inherited from PHG4Hit
enum PROPERTY {
prop_eion = 1 , prop_light_yield = 2 , prop_px_0 = 10 , prop_px_1 = 11 ,
prop_py_0 = 12 , prop_py_1 = 13 , prop_pz_0 = 14 , prop_pz_1 = 15 ,
prop_path_length = 16 , prop_local_x_0 = 20 , prop_local_x_1 = 21 , prop_local_y_0 = 22 ,
prop_local_y_1 = 23 , prop_local_z_0 = 24 , prop_local_z_1 = 25 , prop_layer = 101 ,
prop_scint_id = 102 , prop_row = 103 , prop_strip_z_index = 110 , prop_strip_y_index = 111 ,
prop_ladder_z_index = 112 , prop_ladder_phi_index = 113 , prop_stave_index = 114 , prop_half_stave_index = 115 ,
prop_module_index = 116 , prop_chip_index = 117 , prop_local_pos_x_0 = 118 , prop_local_pos_y_0 = 119 ,
prop_local_pos_z_0 = 120 , prop_index_i = 121 , prop_index_j = 122 , prop_index_k = 123 ,
prop_index_l = 124 , prop_hit_type = 125 , prop_local_pos_x_1 = 128 , prop_local_pos_y_1 = 126 ,
prop_local_pos_z_1 = 127 , prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1 , type_uint = 2 , type_float = 3 , type_unknown = -1 }
Static Public Member Functions inherited from PHG4Hit
static std::pair< const std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Types inherited from PHG4Hitv1
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t, prop_storage_t > prop_map_t
Protected Member Functions inherited from PHG4Hitv1
unsigned int get_property_nocheck (const PROPERTY prop_id) const
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui)
Detailed Description
PHG4HitEval for evaluating PHG4Hitv1 in CINT readable evaluation trees.
Definition at line 19 of file PHG4HitEval.h.
Constructor & Destructor Documentation
PHG4HitEval() [1/2]
PHG4HitEval::PHG4HitEval ()
Definition at line 13 of file PHG4HitEval.cc.
PHG4HitEval() [2/2]
PHG4HitEval::PHG4HitEval (const PHG4Hit & g4hit)
Definition at line 26 of file PHG4HitEval.cc.
References Copy().
~PHG4HitEval()
PHG4HitEval::~PHG4HitEval () virtual
Definition at line 21 of file PHG4HitEval.cc.
Member Function Documentation
Copy()
void PHG4HitEval::Copy (PHG4Hit const & g4hit) virtual
Reimplemented from PHG4Hit.
Definition at line 32 of file PHG4HitEval.cc.
References PHG4Hit::Copy(), eion, PHG4Hitv1::get_eion(), PHG4Hitv1::get_light_yield(), PHG4Hitv1::get_path_length(), PHG4Hitv1::get_scint_id(), light_yield, path_length, and scint_id.
Referenced by PHG4HitEval().
get_eion()
float PHG4HitEval::get_eion () const inline virtual
Reimplemented from PHG4Hitv1.
Definition at line 32 of file PHG4HitEval.h.
References eion.
get_light_yield()
float PHG4HitEval::get_light_yield () const inline virtual
Reimplemented from PHG4Hitv1.
Definition at line 55 of file PHG4HitEval.h.
References light_yield.
get_path_length()
float PHG4HitEval::get_path_length () const inline virtual
Reimplemented from PHG4Hitv1.
Definition at line 67 of file PHG4HitEval.h.
References path_length.
get_scint_id()
int PHG4HitEval::get_scint_id () const inline virtual
Reimplemented from PHG4Hitv1.
Definition at line 43 of file PHG4HitEval.h.
References scint_id.
set_eion()
void PHG4HitEval::set_eion (const float f) inline virtual
Reimplemented from PHG4Hitv1.
Definition at line 37 of file PHG4HitEval.h.
References eion.
set_light_yield()
void PHG4HitEval::set_light_yield (float lightYield) inline virtual
Reimplemented from PHG4Hitv1.
Definition at line 61 of file PHG4HitEval.h.
References light_yield.
set_path_length()
void PHG4HitEval::set_path_length (float pathLength) inline virtual
Reimplemented from PHG4Hitv1.
Definition at line 73 of file PHG4HitEval.h.
References path_length.
set_scint_id()
void PHG4HitEval::set_scint_id (const int i) inline virtual
Reimplemented from PHG4Hitv1.
Definition at line 49 of file PHG4HitEval.h.
References scint_id.
Member Data Documentation
eion
float PHG4HitEval::eion protected
Definition at line 80 of file PHG4HitEval.h.
Referenced by Copy(), get_eion(), and set_eion().
light_yield
float PHG4HitEval::light_yield protected
a number proportional to the scintillation light yield.
Definition at line 85 of file PHG4HitEval.h.
Referenced by Copy(), get_light_yield(), and set_light_yield().
path_length
float PHG4HitEval::path_length protected
path length of the track to the hit
Definition at line 88 of file PHG4HitEval.h.
Referenced by Copy(), get_path_length(), and set_path_length().
scint_id
int PHG4HitEval::scint_id protected
Definition at line 82 of file PHG4HitEval.h.
Referenced by Copy(), get_scint_id(), and set_scint_id().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4HitEval.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4HitEval.cc