Class Reference for E1039 Core & Analysis Software: SQMCHit_v1 Class Reference
SQMCHit_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQMCHit_v1.h>
Public Member Functions
SQMCHit_v1 ()
virtual ~SQMCHit_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQHit * Clone () const
virtual int get_track_id () const
Return the track ID associated with this hit. Probably the value is not properly set at present.
virtual void set_track_id (const int a)
virtual PHG4HitDefs::keytype get_g4hit_id () const
Return the Geant-hit ID associated with this hit.
virtual void set_g4hit_id (const PHG4HitDefs::keytype a)
virtual float get_truth_x () const
Return the true x-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_x (const float a)
virtual float get_truth_y () const
Return the true y-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_y (const float a)
virtual float get_truth_z () const
Return the true z-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_z (const float a)
virtual float get_truth_px () const
Return the true x-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_px (const float a)
virtual float get_truth_py () const
Return the true y-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_py (const float a)
virtual float get_truth_pz () const
Return the true z-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_pz (const float a)
Public Member Functions inherited from SQHit_v1
SQHit_v1 ()
virtual ~SQHit_v1 ()
virtual int get_hit_id () const
Return the ID of this hit.
virtual void set_hit_id (const int a)
virtual short get_detector_id () const
Return the detector ID of this hit.
virtual void set_detector_id (const short a)
virtual short get_element_id () const
Return the element ID of this hit.
virtual void set_element_id (const short id)
virtual short get_level () const
Return the trigger level of this hit. Meaningful only if this hit is of V1495 TDC.
virtual void set_level (const short level)
virtual float get_tdc_time () const
Return the TDC time (nsec) of this hit.
virtual void set_tdc_time (const float a)
virtual float get_drift_distance () const
Return the drift distance of this hit. Probably the value is not properly set at present. Meaningful only if this hit is of drift chamber or prop tube.
virtual void set_drift_distance (const float a)
virtual float get_pos () const
Return the absolute position of this hit. Probably the value is not properly set at present.
virtual void set_pos (const float a)
virtual bool is_in_time () const
Return 'true' if this hit is in the time window.
virtual void set_in_time (const bool a)
virtual bool is_hodo_mask () const
Return 'true' if this hit is accepted (or masked out?) by the hodoscope masking. Meaningful only if this hit is of drift chamber.
virtual void set_hodo_mask (const bool a)
virtual bool is_trigger_mask () const
Return 'true' if this hit is accepted (or masked out?) by the trigger-road masking. Meaningful only if this hit is of drift chamber.
virtual void set_trigger_mask (const bool a)
Public Member Functions inherited from SQHit
SQHit ()
virtual ~SQHit ()
virtual short get_tower_id () const
Not valid in E1039. To be deleted.
virtual void set_tower_id (const short a)
virtual float get_edep () const
Not valid in E1039. To be deleted.
virtual void set_edep (const float a)
virtual unsigned int get_n_cells () const
Return the number of cells included in this hit.
virtual CellMap get_cells () const
Return the list of all cells included in this hit.
virtual float get_cell (unsigned int i) const
Return the 'edep' value of the i-th cell.
virtual void add_cell (unsigned int i, float a)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from SQHit
enum HitQuality { InTime = 1<<0, HodoMask = 1<<1, TriggerMask = 1<<2 }
typedef std::map< short, float > CellMap
key -> plateID, float -> edep
Detailed Description
Definition at line 17 of file SQMCHit_v1.h.
Constructor & Destructor Documentation
SQMCHit_v1::SQMCHit_v1 ()
Definition at line 16 of file SQMCHit_v1.cxx.
Referenced by Clone(), and Reset().
virtual SQMCHit_v1::~SQMCHit_v1 () inline virtual
Definition at line 22 of file SQMCHit_v1.h.
Member Function Documentation
SQHit* SQMCHit_v1::Clone () const inline virtual
Reimplemented from SQHit_v1.
Definition at line 29 of file SQMCHit_v1.h.
References SQMCHit_v1().
virtual PHG4HitDefs::keytype SQMCHit_v1::get_g4hit_id () const inline virtual
Return the Geant-hit ID associated with this hit.
Reimplemented from SQHit.
Definition at line 34 of file SQMCHit_v1.h.
virtual int SQMCHit_v1::get_track_id () const inline virtual
Return the track ID associated with this hit. Probably the value is not properly set at present.
Reimplemented from SQHit.
Definition at line 31 of file SQMCHit_v1.h.
Referenced by identify().
virtual float SQMCHit_v1::get_truth_px () const inline virtual
Return the true x-momentum of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 46 of file SQMCHit_v1.h.
virtual float SQMCHit_v1::get_truth_py () const inline virtual
Return the true y-momentum of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 49 of file SQMCHit_v1.h.
virtual float SQMCHit_v1::get_truth_pz () const inline virtual
Return the true z-momentum of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 52 of file SQMCHit_v1.h.
virtual float SQMCHit_v1::get_truth_x () const inline virtual
Return the true x-position of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 37 of file SQMCHit_v1.h.
virtual float SQMCHit_v1::get_truth_y () const inline virtual
Return the true y-position of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 40 of file SQMCHit_v1.h.
virtual float SQMCHit_v1::get_truth_z () const inline virtual
Return the true z-position of this hit. Meaningful only if this hit is of MC.
Reimplemented from SQHit.
Definition at line 43 of file SQMCHit_v1.h.
void SQMCHit_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQHit_v1.
Definition at line 21 of file SQMCHit_v1.cxx.
References SQHit_v1::get_hit_id(), get_track_id(), and SQHit_v1::identify().
int SQMCHit_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQHit_v1.
Definition at line 33 of file SQMCHit_v1.cxx.
References SQHit_v1::isValid().
void SQMCHit_v1::Reset () inline virtual
Clear Event.
Reimplemented from SQHit_v1.
Definition at line 27 of file SQMCHit_v1.h.
References SQMCHit_v1().
virtual void SQMCHit_v1::set_g4hit_id (const PHG4HitDefs::keytype a) inline virtual
Reimplemented from SQHit.
Definition at line 35 of file SQMCHit_v1.h.
Referenced by SQDigitizer::digitizePlane(), RndmEmbed::process_event(), and SRawEventEmbed::process_event().
virtual void SQMCHit_v1::set_track_id (const int a) inline virtual
Reimplemented from SQHit.
Definition at line 32 of file SQMCHit_v1.h.
Referenced by SQDigitizer::digitizePlane(), RndmEmbed::process_event(), and SRawEventEmbed::process_event().
virtual void SQMCHit_v1::set_truth_px (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 47 of file SQMCHit_v1.h.
Referenced by SQDigitizer::digitizePlane().
virtual void SQMCHit_v1::set_truth_py (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 50 of file SQMCHit_v1.h.
Referenced by SQDigitizer::digitizePlane().
virtual void SQMCHit_v1::set_truth_pz (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 53 of file SQMCHit_v1.h.
Referenced by SQDigitizer::digitizePlane().
virtual void SQMCHit_v1::set_truth_x (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 38 of file SQMCHit_v1.h.
Referenced by SQDigitizer::digitizePlane(), RndmEmbed::process_event(), and SRawEventEmbed::process_event().
virtual void SQMCHit_v1::set_truth_y (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 41 of file SQMCHit_v1.h.
Referenced by SQDigitizer::digitizePlane(), RndmEmbed::process_event(), and SRawEventEmbed::process_event().
virtual void SQMCHit_v1::set_truth_z (const float a) inline virtual
Reimplemented from SQHit.
Definition at line 44 of file SQMCHit_v1.h.
Referenced by SQDigitizer::digitizePlane(), RndmEmbed::process_event(), and SRawEventEmbed::process_event().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQMCHit_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQMCHit_v1.cxx