E1039 Software: SRawEventEmbed Class Reference
SRawEventEmbed Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/embedding/SRawEventEmbed.h>
Public Member Functions
SRawEventEmbed (const std::string &name="SRawEventEmbed")
virtual ~SRawEventEmbed ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int InitEvalTree ()
int ResetEvalVars ()
const std::string & get_hit_container_choice () const
void set_hit_container_choice (const std::string &hitContainerChoice)
const std::string & get_out_name () const
void set_out_name (const std::string &outName)
void print_noise_rate () const
void set_noise_rate (const std::string &name, const double &rate)
const std::string & get_in_name () const
void set_in_name (const std::string &inName)
int get_trigger_bit () const
void set_trigger_bit (int triggerBit)
const std::string & get_in_tree_name () const
void set_in_tree_name (const std::string &inTreeName)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
Private Attributes
std::string _hit_container_type
std::map< std::string, double > _noise_rate
size_t _event
GeomSvc * p_geomSvc
SQHitMap * _hit_map
SQHitVector * _hit_vector
std::string _in_name
std::string _in_tree_name
TFile * _fin
TTree * _tin
int _tree_entry
int _trigger_bit
SRawEvent * _srawevent
std::string _out_name
TTree * _tout
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 45 of file SRawEventEmbed.h.
Constructor & Destructor Documentation
SRawEventEmbed()
SRawEventEmbed::SRawEventEmbed (const std::string & name = "SRawEventEmbed")
Definition at line 58 of file SRawEventEmbed.cxx.
~SRawEventEmbed()
virtual SRawEventEmbed::~SRawEventEmbed () inline virtual
Definition at line 50 of file SRawEventEmbed.h.
References End(), Init(), InitEvalTree(), InitRun(), process_event(), and ResetEvalVars().
Member Function Documentation
End()
int SRawEventEmbed::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 187 of file SRawEventEmbed.cxx.
References _out_name, _tout, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by ~SRawEventEmbed().
get_hit_container_choice()
const std::string& SRawEventEmbed::get_hit_container_choice () const inline
Definition at line 61 of file SRawEventEmbed.h.
References _hit_container_type.
get_in_name()
const std::string& SRawEventEmbed::get_in_name () const inline
Definition at line 87 of file SRawEventEmbed.h.
References _in_name.
get_in_tree_name()
const std::string& SRawEventEmbed::get_in_tree_name () const inline
Definition at line 103 of file SRawEventEmbed.h.
References _in_tree_name.
get_out_name()
const std::string& SRawEventEmbed::get_out_name () const inline
Definition at line 69 of file SRawEventEmbed.h.
References _out_name.
get_trigger_bit()
int SRawEventEmbed::get_trigger_bit () const inline
Definition at line 95 of file SRawEventEmbed.h.
References _trigger_bit.
GetNodes()
int SRawEventEmbed::GetNodes (PHCompositeNode * topNode) private
Definition at line 209 of file SRawEventEmbed.cxx.
References _hit_container_type, _hit_map, _hit_vector, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and LogInfo.
Referenced by InitRun(), and set_in_tree_name().
Init()
int SRawEventEmbed::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 74 of file SRawEventEmbed.cxx.
References Fun4AllReturnCodes::EVENT_OK.
Referenced by ~SRawEventEmbed().
InitEvalTree()
int SRawEventEmbed::InitEvalTree ()
Definition at line 197 of file SRawEventEmbed.cxx.
References _out_name, _tout, PHTFileServer::get(), and PHTFileServer::open().
Referenced by InitRun(), and ~SRawEventEmbed().
InitRun()
int SRawEventEmbed::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 78 of file SRawEventEmbed.cxx.
References _fin, _in_name, _in_tree_name, _srawevent, _tin, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, GetNodes(), InitEvalTree(), GeomSvc::instance(), LogInfo, p_geomSvc, and ResetEvalVars().
Referenced by ~SRawEventEmbed().
print_noise_rate()
void SRawEventEmbed::print_noise_rate () const inline
Definition at line 77 of file SRawEventEmbed.h.
References _noise_rate.
process_event()
int SRawEventEmbed::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 106 of file SRawEventEmbed.cxx.
References _event, _hit_container_type, _hit_vector, _srawevent, _tin, _tout, _tree_entry, _trigger_bit, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, SQHit_v1::get_detector_id(), SQHit_v1::get_element_id(), SRawEvent::getAllHits(), GeomSvc::getMeasurement(), SRawEvent::getTriggerBits(), LogInfo, p_geomSvc, SQHitVector::push_back(), ResetEvalVars(), SQHit_v1::set_detector_id(), SQHit_v1::set_drift_distance(), SQHit_v1::set_element_id(), SQMCHit_v1::set_g4hit_id(), SQHit_v1::set_hit_id(), SQHit_v1::set_hodo_mask(), SQHit_v1::set_in_time(), SQHit_v1::set_pos(), SQMCHit_v1::set_track_id(), SQMCHit_v1::set_truth_x(), SQMCHit_v1::set_truth_y(), SQMCHit_v1::set_truth_z(), SQHitVector::size(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_A_LOT, and Fun4AllBase::VERBOSITY_SOME.
Referenced by ~SRawEventEmbed().
ResetEvalVars()
int SRawEventEmbed::ResetEvalVars ()
Definition at line 205 of file SRawEventEmbed.cxx.
Referenced by InitRun(), process_event(), and ~SRawEventEmbed().
set_hit_container_choice()
void SRawEventEmbed::set_hit_container_choice (const std::string & hitContainerChoice) inline
Definition at line 65 of file SRawEventEmbed.h.
References _hit_container_type.
set_in_name()
void SRawEventEmbed::set_in_name (const std::string & inName) inline
Definition at line 91 of file SRawEventEmbed.h.
References _in_name.
set_in_tree_name()
void SRawEventEmbed::set_in_tree_name (const std::string & inTreeName) inline
Definition at line 107 of file SRawEventEmbed.h.
References _in_tree_name, and GetNodes().
set_noise_rate()
void SRawEventEmbed::set_noise_rate (const std::string & name, const double & rate) inline
Definition at line 83 of file SRawEventEmbed.h.
References _noise_rate.
set_out_name()
void SRawEventEmbed::set_out_name (const std::string & outName) inline
Definition at line 73 of file SRawEventEmbed.h.
References _out_name.
set_trigger_bit()
void SRawEventEmbed::set_trigger_bit (int triggerBit) inline
Definition at line 99 of file SRawEventEmbed.h.
References _trigger_bit, and triggerBit.
Member Data Documentation
_event
size_t SRawEventEmbed::_event private
Definition at line 118 of file SRawEventEmbed.h.
Referenced by process_event().
_fin
TFile* SRawEventEmbed::_fin private
Definition at line 127 of file SRawEventEmbed.h.
Referenced by InitRun().
_hit_container_type
std::string SRawEventEmbed::_hit_container_type private
Definition at line 115 of file SRawEventEmbed.h.
Referenced by get_hit_container_choice(), GetNodes(), process_event(), and set_hit_container_choice().
_hit_map
SQHitMap* SRawEventEmbed::_hit_map private
Definition at line 122 of file SRawEventEmbed.h.
Referenced by GetNodes().
_hit_vector
SQHitVector* SRawEventEmbed::_hit_vector private
Definition at line 123 of file SRawEventEmbed.h.
Referenced by GetNodes(), and process_event().
_in_name
std::string SRawEventEmbed::_in_name private
Definition at line 125 of file SRawEventEmbed.h.
Referenced by get_in_name(), InitRun(), and set_in_name().
_in_tree_name
std::string SRawEventEmbed::_in_tree_name private
Definition at line 126 of file SRawEventEmbed.h.
Referenced by get_in_tree_name(), InitRun(), and set_in_tree_name().
_noise_rate
std::map<std::string, double> SRawEventEmbed::_noise_rate private
Definition at line 116 of file SRawEventEmbed.h.
Referenced by print_noise_rate(), and set_noise_rate().
_out_name
std::string SRawEventEmbed::_out_name private
Definition at line 133 of file SRawEventEmbed.h.
Referenced by End(), get_out_name(), InitEvalTree(), and set_out_name().
_srawevent
SRawEvent* SRawEventEmbed::_srawevent private
Definition at line 131 of file SRawEventEmbed.h.
Referenced by InitRun(), and process_event().
_tin
TTree* SRawEventEmbed::_tin private
Definition at line 128 of file SRawEventEmbed.h.
Referenced by InitRun(), and process_event().
_tout
TTree* SRawEventEmbed::_tout private
Definition at line 134 of file SRawEventEmbed.h.
Referenced by End(), InitEvalTree(), and process_event().
_tree_entry
int SRawEventEmbed::_tree_entry private
Definition at line 129 of file SRawEventEmbed.h.
Referenced by process_event().
_trigger_bit
int SRawEventEmbed::_trigger_bit private
Definition at line 130 of file SRawEventEmbed.h.
Referenced by get_trigger_bit(), process_event(), and set_trigger_bit().
p_geomSvc
GeomSvc* SRawEventEmbed::p_geomSvc private
Definition at line 120 of file SRawEventEmbed.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/embedding/SRawEventEmbed.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/embedding/SRawEventEmbed.cxx