SeaQuest Offline Software: PHG4InnerHcalSteppingAction Class Reference
PHG4InnerHcalSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4InnerHcalSteppingAction.h>
Public Member Functions
PHG4InnerHcalSteppingAction (PHG4InnerHcalDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4InnerHcalSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
double GetLightCorrection (const double r) const
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4InnerHcalDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4Hit * hit
const PHParameters * params
PHG4HitContainer * savehitcontainer
PHG4Shower * saveshower
G4VPhysicalVolume * savevolpre
G4VPhysicalVolume * savevolpost
int savetrackid
int saveprestepstatus
int savepoststepstatus
int absorbertruth
int IsActive
int IsBlackHole
int n_scinti_plates
int light_scint_model
double light_balance_inner_corr
double light_balance_inner_radius
double light_balance_outer_corr
double light_balance_outer_radius
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 13 of file PHG4InnerHcalSteppingAction.h.
Constructor & Destructor Documentation
PHG4InnerHcalSteppingAction::PHG4InnerHcalSteppingAction (PHG4InnerHcalDetector * detector, const PHParameters * parameters)
constructor
Definition at line 42 of file PHG4InnerHcalSteppingAction.cc.
References detector_, PHG4Detector::GetName(), and PHG4SteppingAction::name.
PHG4InnerHcalSteppingAction::~PHG4InnerHcalSteppingAction () virtual
destructor
Definition at line 68 of file PHG4InnerHcalSteppingAction.cc.
References hit.
Member Function Documentation
double PHG4InnerHcalSteppingAction::GetLightCorrection (const double r) const
Definition at line 427 of file PHG4InnerHcalSteppingAction.cc.
References light_balance_inner_corr, light_balance_inner_radius, light_balance_outer_corr, and light_balance_outer_radius.
Referenced by UserSteppingAction().
void PHG4InnerHcalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 393 of file PHG4InnerHcalSteppingAction.cc.
References absorberhits_, detector_, PHG4Detector::GetName(), hits_, PHG4InnerHcalDetector::SuperDetector(), and PHG4SteppingAction::verbosity.
bool PHG4InnerHcalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 77 of file PHG4InnerHcalSteppingAction.cc.
References absorberhits_, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Hit::get_light_yield(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), GetLightCorrection(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), hit, hits_, IsActive, IsBlackHole, PHG4InnerHcalDetector::IsInInnerHcal(), light_balance_inner_corr, light_balance_inner_radius, light_balance_outer_corr, light_balance_outer_radius, light_scint_model, n_scinti_plates, PHWHERE, PHG4Hit::Reset(), savehitcontainer, savepoststepstatus, saveprestepstatus, saveshower, savetrackid, savevolpost, savevolpre, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_light_yield(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4HitContainer* PHG4InnerHcalSteppingAction::absorberhits_ private
Definition at line 36 of file PHG4InnerHcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4InnerHcalSteppingAction::absorbertruth private
Definition at line 49 of file PHG4InnerHcalSteppingAction.h.
PHG4InnerHcalDetector* PHG4InnerHcalSteppingAction::detector_ private
pointer to the detector
Definition at line 32 of file PHG4InnerHcalSteppingAction.h.
Referenced by PHG4InnerHcalSteppingAction(), SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4InnerHcalSteppingAction::hit private
Definition at line 37 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4InnerHcalSteppingAction().
PHG4HitContainer* PHG4InnerHcalSteppingAction::hits_ private
pointer to hit container
Definition at line 35 of file PHG4InnerHcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4InnerHcalSteppingAction::IsActive private
Definition at line 50 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4InnerHcalSteppingAction::IsBlackHole private
Definition at line 51 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
double PHG4InnerHcalSteppingAction::light_balance_inner_corr private
Definition at line 55 of file PHG4InnerHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4InnerHcalSteppingAction::light_balance_inner_radius private
Definition at line 56 of file PHG4InnerHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4InnerHcalSteppingAction::light_balance_outer_corr private
Definition at line 57 of file PHG4InnerHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4InnerHcalSteppingAction::light_balance_outer_radius private
Definition at line 58 of file PHG4InnerHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
int PHG4InnerHcalSteppingAction::light_scint_model private
Definition at line 53 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4InnerHcalSteppingAction::n_scinti_plates private
Definition at line 52 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
const PHParameters* PHG4InnerHcalSteppingAction::params private
Definition at line 38 of file PHG4InnerHcalSteppingAction.h.
PHG4HitContainer* PHG4InnerHcalSteppingAction::savehitcontainer private
Definition at line 39 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4InnerHcalSteppingAction::savepoststepstatus private
Definition at line 45 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4InnerHcalSteppingAction::saveprestepstatus private
Definition at line 44 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4InnerHcalSteppingAction::saveshower private
Definition at line 40 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4InnerHcalSteppingAction::savetrackid private
Definition at line 43 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4InnerHcalSteppingAction::savevolpost private
Definition at line 42 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4InnerHcalSteppingAction::savevolpre private
Definition at line 41 of file PHG4InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4InnerHcalSteppingAction.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4InnerHcalSteppingAction.cc