SeaQuest Offline Software: longJobManager Namespace Reference
longJobManager Namespace Reference
Variables
tuple parser = OptionParser('Usage: %prog [options]')
tuple conf = GU.JobConfig(options.config)
list jobInfo = [line.strip().split() for line in open(options.list)]
tuple runID = int(re.findall(r'_(\d+)_r', jobInfo[i][1])[0])
list cmds = []
list singleSize = job[5]
list optSizes = [[job[4] + i*singleSize, singleSize] for i in range(options.nJobs)]
tuple cmd = GU.makeCommand(options.job, job[2], conf, firstEvent = item[0], nEvents = item[1], outtag = '%s_%d' % (job[3], tag))
tuple nLeftJobs = len(jobInfo)
list outfiles = [os.path.join(conf.outdir, options.job, GU.version, GU.getSubDir(job[2]), '%s_%06d_%s_%s_%d.root' % (options.job, job[2], GU.version, job[3], i)) for i in range(options.nJobs)]
list logfiles = [os.path.join(conf.outdir, 'log', GU.version, GU.getSubDir(runID), '%s_%d.log' % (job[1], i)) for i in range(options.nJobs)]
list optfiles = [os.path.join(conf.outdir, 'opts', GU.version, GU.getSubDir(runID), '%s_%d.opts' % (job[1], i)) for i in range(options.nJobs)]
tuple targetFile = os.path.join(conf.outdir, options.job, GU.version, GU.getSubDir(job[2]), '%s_%06d_%s_%s.root' % (options.job, job[2], GU.version, job[3]))
Variable Documentation
tuple longJobManager.cmd = GU.makeCommand(options.job, job[2], conf, firstEvent = item[0], nEvents = item[1], outtag = '%s_%d' % (job[3], tag))
Definition at line 52 of file longJobManager.py.
list longJobManager.cmds = []
Definition at line 41 of file longJobManager.py.
tuple longJobManager.conf = GU.JobConfig(options.config)
Definition at line 29 of file longJobManager.py.
list longJobManager.jobInfo = [line.strip().split() for line in open(options.list)]
Definition at line 32 of file longJobManager.py.
list longJobManager.logfiles = [os.path.join(conf.outdir, 'log', GU.version, GU.getSubDir(runID), '%s_%d.log' % (job[1], i)) for i in range(options.nJobs)]
Definition at line 78 of file longJobManager.py.
tuple longJobManager.nLeftJobs = len(jobInfo)
Definition at line 64 of file longJobManager.py.
list longJobManager.optfiles = [os.path.join(conf.outdir, 'opts', GU.version, GU.getSubDir(runID), '%s_%d.opts' % (job[1], i)) for i in range(options.nJobs)]
Definition at line 100 of file longJobManager.py.
list longJobManager.optSizes = [[job[4] + i*singleSize, singleSize] for i in range(options.nJobs)]
Definition at line 44 of file longJobManager.py.
list longJobManager.outfiles = [os.path.join(conf.outdir, options.job, GU.version, GU.getSubDir(job[2]), '%s_%06d_%s_%s_%d.root' % (options.job, job[2], GU.version, job[3], i)) for i in range(options.nJobs)]
Definition at line 72 of file longJobManager.py.
tuple longJobManager.parser = OptionParser('Usage: %prog [options]')
Definition at line 14 of file longJobManager.py.
tuple longJobManager.runID = int(re.findall(r'_(\d+)_r', jobInfo[i][1])[0])
Definition at line 35 of file longJobManager.py.
Referenced by main(), SRawEvent.setEventInfo(), and SRecEvent.setEventInfo().
list longJobManager.singleSize = job[5]
Definition at line 43 of file longJobManager.py.
tuple longJobManager.targetFile = os.path.join(conf.outdir, options.job, GU.version, GU.getSubDir(job[2]), '%s_%06d_%s_%s.root' % (options.job, job[2], GU.version, job[3]))
Definition at line 104 of file longJobManager.py.