Class Reference for E1039 Core & Analysis Software: UtilOnline Class Reference
UtilOnline Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/UtilOnline.h>
Static Public Member Functions
static void UseOutputLocationForDevel ()
static void SetEndFileDir (const std::string dir)
static void SetCodaFileDir (const std::string dir)
static void SetDstFileDir (const std::string dir)
static void SetEDDstFileDir (const std::string dir)
static void SetOnlMonDir (const std::string dir)
static void SetSchemaMainDaq (const std::string sch)
static std::string GetEndFileDir ()
static std::string GetCodaFileDir ()
static std::string GetDstFileDir ()
static std::string GetEDDstFileDir ()
static std::string GetOnlMonDir ()
static std::string GetSchemaMainDaq ()
static int CodaFile2RunNum (const std::string name)
Convert the name of a Coda file to its run number.
static std::string RunNum2CodaFile (const int run)
Convert a run number to the corresponding name of Coda file.
static std::string RunNum2EndFile (const int run)
Convert a run number to the corresponding name of END file.
static std::string RunNum2DstFile (const int run)
Convert a run number to the corresponding name of DST file.
static std::string RunNum2EDDstFile (const int run)
Convert a run number to the corresponding name of edDST file.
static std::string GetSpillDstDir (const int run)
Get a directory of spill-level DST files.
static std::string GetSpillDstFile (const int run, const int spill)
Convert a run+spill number to the corresponding name of DST file.
static std::string GetSpillDstPath (const int run, const int spill)
static std::vector< std::string > GetListOfSpillDSTs (const int run, const std::string dir_dst="")
static std::string GetCodaFilePath (const int run)
static std::string GetEndFilePath (const int run)
static std::string GetDstFilePath (const int run)
static std::string GetEDDstFilePath (const int run)
static std::string Run6 (const int run, const int digit=6)
static std::string Spill9 (const int spill, const int digit=9)
Detailed Description
Definition at line 6 of file UtilOnline.h.
Member Function Documentation
CodaFile2RunNum()
int UtilOnline::CodaFile2RunNum (const std::string name) static
Convert the name of a Coda file to its run number.
The 1st argument can be a path, i.e. "/path/to/run_******_spin.dat".
Definition at line 56 of file UtilOnline.cc.
GetCodaFileDir()
static std::string UtilOnline::GetCodaFileDir () inline static
Definition at line 25 of file UtilOnline.h.
GetCodaFilePath()
std::string UtilOnline::GetCodaFilePath (const int run) static
Definition at line 143 of file UtilOnline.cc.
Referenced by CodaInputManager::NextCodaEvent().
GetDstFileDir()
static std::string UtilOnline::GetDstFileDir () inline static
Definition at line 26 of file UtilOnline.h.
Referenced by UtilMine::GetDstFilePath(), UtilMine::GetListOfSpillDSTs(), and GetListOfSpillDSTs().
GetDstFilePath()
std::string UtilOnline::GetDstFilePath (const int run) static
Definition at line 153 of file UtilOnline.cc.
GetEDDstFileDir()
static std::string UtilOnline::GetEDDstFileDir () inline static
Definition at line 27 of file UtilOnline.h.
GetEDDstFilePath()
std::string UtilOnline::GetEDDstFilePath (const int run) static
Definition at line 158 of file UtilOnline.cc.
Referenced by EventDispUI::GetDstPath().
GetEndFileDir()
static std::string UtilOnline::GetEndFileDir () inline static
Definition at line 24 of file UtilOnline.h.
GetEndFilePath()
std::string UtilOnline::GetEndFilePath (const int run) static
Definition at line 148 of file UtilOnline.cc.
Referenced by CodaInputManager::NextCodaEvent().
GetListOfSpillDSTs()
std::vector< std::string > UtilOnline::GetListOfSpillDSTs (const int run, const std::string dir_dst = "") static
Definition at line 116 of file UtilOnline.cc.
References GetDstFileDir().
GetOnlMonDir()
static std::string UtilOnline::GetOnlMonDir () inline static
Definition at line 28 of file UtilOnline.h.
Referenced by OnlMonClient::End(), and OnlMonCanvas::PostDraw().
GetSchemaMainDaq()
static std::string UtilOnline::GetSchemaMainDaq () inline static
Definition at line 29 of file UtilOnline.h.
Referenced by DecoError::AggregateData(), DecoStatusDb::DecoStatusDb(), and Fun4AllSpillDstOutputManager::EnableDB().
GetSpillDstDir()
std::string UtilOnline::GetSpillDstDir (const int run) static
Get a directory of spill-level DST files.
Definition at line 96 of file UtilOnline.cc.
Referenced by EventDispUI::FindSpillDSTs(), and EventDispUI::GetDstPath().
GetSpillDstFile()
std::string UtilOnline::GetSpillDstFile (const int run, const int spill) static
Convert a run+spill number to the corresponding name of DST file.
Definition at line 104 of file UtilOnline.cc.
Referenced by EventDispUI::GetDstPath().
GetSpillDstPath()
std::string UtilOnline::GetSpillDstPath (const int run, const int spill) static
Definition at line 111 of file UtilOnline.cc.
Run6()
std::string UtilOnline::Run6 (const int run, const int digit = 6) static
Definition at line 163 of file UtilOnline.cc.
RunNum2CodaFile()
std::string UtilOnline::RunNum2CodaFile (const int run) static
Convert a run number to the corresponding name of Coda file.
Definition at line 64 of file UtilOnline.cc.
RunNum2DstFile()
std::string UtilOnline::RunNum2DstFile (const int run) static
Convert a run number to the corresponding name of DST file.
Definition at line 80 of file UtilOnline.cc.
RunNum2EDDstFile()
std::string UtilOnline::RunNum2EDDstFile (const int run) static
Convert a run number to the corresponding name of edDST file.
Definition at line 88 of file UtilOnline.cc.
RunNum2EndFile()
std::string UtilOnline::RunNum2EndFile (const int run) static
Convert a run number to the corresponding name of END file.
Definition at line 72 of file UtilOnline.cc.
SetCodaFileDir()
void UtilOnline::SetCodaFileDir (const std::string dir) static
Definition at line 27 of file UtilOnline.cc.
SetDstFileDir()
void UtilOnline::SetDstFileDir (const std::string dir) static
Definition at line 32 of file UtilOnline.cc.
SetEDDstFileDir()
void UtilOnline::SetEDDstFileDir (const std::string dir) static
Definition at line 37 of file UtilOnline.cc.
SetEndFileDir()
void UtilOnline::SetEndFileDir (const std::string dir) static
Definition at line 22 of file UtilOnline.cc.
SetOnlMonDir()
void UtilOnline::SetOnlMonDir (const std::string dir) static
Definition at line 42 of file UtilOnline.cc.
SetSchemaMainDaq()
void UtilOnline::SetSchemaMainDaq (const std::string sch) static
Definition at line 47 of file UtilOnline.cc.
Spill9()
std::string UtilOnline::Spill9 (const int spill, const int digit = 9) static
Definition at line 170 of file UtilOnline.cc.
UseOutputLocationForDevel()
void UtilOnline::UseOutputLocationForDevel () static
Definition at line 15 of file UtilOnline.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/UtilOnline.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/UtilAna/UtilOnline.cc