E1039 Software: TriggerRoad Class Reference
TriggerRoad Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/TriggerRoad.h>
Public Member Functions
TriggerRoad ()
TriggerRoad (std::list< int > uniqueIDs)
TriggerRoad (Tracklet &track)
TriggerRoad (SRecTrack &track)
bool isValid ()
bool isEnabled ()
TriggerRoad reflectTB ()
TriggerRoad reflectLR ()
void addElement (int detectorID, int elementID)
void enable ()
void disable ()
int getNElements ()
int getDetectorID (int i)
int getElementID (int i)
int getUniqueID (int i)
int getRoadID ()
double weight () const
double ratio () const
double mratio () const
int getNEntries () const
double getpXMean () const
double getpXWidth () const
int getTB ()
int getLR ()
void print ()
void clear ()
bool operator== (const TriggerRoad &elem) const
TriggerRoad & operator+= (const TriggerRoad &elem)
Static Public Member Functions
static bool byTargetDump (const TriggerRoad &elem1, const TriggerRoad &elem2)
static bool byWeight (const TriggerRoad &elem1, const TriggerRoad &elem2)
static bool byMass (const TriggerRoad &elem1, const TriggerRoad &elem2)
static bool byPt (const TriggerRoad &elem1, const TriggerRoad &elem2)
static bool byRndFrequency (const TriggerRoad &elem1, const TriggerRoad &elem2)
static std::list< TriggerRoad > makeRoadList (int nHits, int dIDs[], int eIDs[], double z, double mass, double pX, double weight)
Public Attributes
int nPlus
int nMinus
int roadID
int groupID
double targetWeight
double dumpWeight
double lowMWeight
double highMWeight
std::vector< double > pXs
double px_min
double px_max
double px_mean
double rndf
bool enabled
std::vector< int > detectorIDs
std::vector< int > elementIDs
Friends
std::ostream & operator<< (std::ostream &os, const TriggerRoad &road)
Detailed Description
Definition at line 16 of file TriggerRoad.h.
Constructor & Destructor Documentation
TriggerRoad() [1/4]
TriggerRoad::TriggerRoad ()
TriggerRoad() [2/4]
TriggerRoad::TriggerRoad (std::list< int > uniqueIDs)
Definition at line 32 of file TriggerRoad.cxx.
References addElement().
TriggerRoad() [3/4]
TriggerRoad::TriggerRoad (Tracklet & track)
Definition at line 45 of file TriggerRoad.cxx.
References detectorIDs, elementIDs, GeomSvc::getExpElementID(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), GeomSvc::getPlanePosition(), GeomSvc::instance(), and GeomSvc::isInPlane().
TriggerRoad() [4/4]
TriggerRoad::TriggerRoad (SRecTrack & track)
Definition at line 72 of file TriggerRoad.cxx.
References detectorIDs, elementIDs, GeomSvc::getExpElementID(), SRecTrack::getExpPositionFast(), GeomSvc::getPlanePosition(), GeomSvc::instance(), and GeomSvc::isInPlane().
Member Function Documentation
addElement()
void TriggerRoad::addElement (int detectorID, int elementID)
Definition at line 158 of file TriggerRoad.cxx.
References detectorIDs, and elementIDs.
Referenced by TriggerAnalyzer::init(), isEnabled(), makeRoadList(), and TriggerRoad().
byMass()
bool TriggerRoad::byMass (const TriggerRoad & elem1, const TriggerRoad & elem2) static
Definition at line 190 of file TriggerRoad.cxx.
References mratio().
byPt()
bool TriggerRoad::byPt (const TriggerRoad & elem1, const TriggerRoad & elem2) static
Definition at line 195 of file TriggerRoad.cxx.
References px_min.
byRndFrequency()
bool TriggerRoad::byRndFrequency (const TriggerRoad & elem1, const TriggerRoad & elem2) static
Definition at line 200 of file TriggerRoad.cxx.
References rndf.
byTargetDump()
bool TriggerRoad::byTargetDump (const TriggerRoad & elem1, const TriggerRoad & elem2) static
Definition at line 180 of file TriggerRoad.cxx.
References ratio().
byWeight()
bool TriggerRoad::byWeight (const TriggerRoad & elem1, const TriggerRoad & elem2) static
Definition at line 185 of file TriggerRoad.cxx.
References weight().
clear()
void TriggerRoad::clear ()
Definition at line 144 of file TriggerRoad.cxx.
References detectorIDs, dumpWeight, elementIDs, enabled, pXs, roadID, and targetWeight.
Referenced by TriggerAnalyzer::init().
disable()
void TriggerRoad::disable () inline
Definition at line 37 of file TriggerRoad.h.
References enabled.
enable()
void TriggerRoad::enable () inline
Definition at line 36 of file TriggerRoad.h.
References enabled.
Referenced by makeRoadList().
getDetectorID()
int TriggerRoad::getDetectorID (int i) inline
Definition at line 41 of file TriggerRoad.h.
References detectorIDs.
getElementID()
int TriggerRoad::getElementID (int i) inline
Definition at line 42 of file TriggerRoad.h.
References elementIDs.
getLR()
int TriggerRoad::getLR ()
Definition at line 252 of file TriggerRoad.cxx.
References detectorIDs, elementIDs, GeomSvc::getPlaneNElements(), and GeomSvc::instance().
Referenced by getNEntries().
getNElements()
int TriggerRoad::getNElements () inline
Definition at line 40 of file TriggerRoad.h.
References detectorIDs.
getNEntries()
int TriggerRoad::getNEntries () const inline
Definition at line 53 of file TriggerRoad.h.
References getLR(), getpXMean(), getpXWidth(), getTB(), and pXs.
Referenced by operator<<().
getpXMean()
double TriggerRoad::getpXMean () const
Definition at line 223 of file TriggerRoad.cxx.
References pXs.
Referenced by getNEntries().
getpXWidth()
double TriggerRoad::getpXWidth () const
Definition at line 241 of file TriggerRoad.cxx.
References px_mean, and pXs.
Referenced by getNEntries(), and operator<<().
getRoadID()
int TriggerRoad::getRoadID ()
Definition at line 234 of file TriggerRoad.cxx.
References detectorIDs, elementIDs, and getTB().
Referenced by TriggerAnalyzer::acceptEvent(), Tracklet::getSRecTrack(), getUniqueID(), TriggerAnalyzer::init(), KalmanFastTracking::processOneTracklet(), KalmanDSTrk::processOneTracklet(), and TriggerAnalyzer::search().
getTB()
int TriggerRoad::getTB ()
Definition at line 277 of file TriggerRoad.cxx.
References detectorIDs.
Referenced by getNEntries(), getRoadID(), isValid(), and reflectTB().
getUniqueID()
int TriggerRoad::getUniqueID (int i) inline
Definition at line 43 of file TriggerRoad.h.
References detectorIDs, elementIDs, and getRoadID().
isEnabled()
bool TriggerRoad::isEnabled () inline
Definition at line 26 of file TriggerRoad.h.
References addElement(), enabled, reflectLR(), and reflectTB().
isValid()
bool TriggerRoad::isValid ()
Definition at line 104 of file TriggerRoad.cxx.
References detectorIDs, enabled, and getTB().
Referenced by TriggerAnalyzer::init(), and makeRoadList().
makeRoadList()
std::list< TriggerRoad > TriggerRoad::makeRoadList (int nHits, int dIDs[], int eIDs[], double z, double mass, double pX, double weight) static
Definition at line 324 of file TriggerRoad.cxx.
References addElement(), dumpWeight, enable(), GeomSvc::getDetectorName(), highMWeight, GeomSvc::instance(), isValid(), lowMWeight, px_max, px_mean, px_min, pXs, reflectTB(), targetWeight, and weight().
mratio()
double TriggerRoad::mratio () const inline
Definition at line 50 of file TriggerRoad.h.
References highMWeight, and lowMWeight.
Referenced by byMass().
operator+=()
TriggerRoad & TriggerRoad::operator+= (const TriggerRoad & elem)
Definition at line 205 of file TriggerRoad.cxx.
References dumpWeight, highMWeight, lowMWeight, nMinus, nPlus, px_max, px_mean, px_min, pXs, and targetWeight.
operator==()
bool TriggerRoad::operator== (const TriggerRoad & elem) const
Definition at line 166 of file TriggerRoad.cxx.
References detectorIDs, and elementIDs.
print()
void TriggerRoad::print ()
Definition at line 115 of file TriggerRoad.cxx.
References detectorIDs, elementIDs, and ratio().
ratio()
double TriggerRoad::ratio () const inline
Definition at line 49 of file TriggerRoad.h.
References dumpWeight, and targetWeight.
Referenced by byTargetDump(), operator<<(), and print().
reflectLR()
TriggerRoad TriggerRoad::reflectLR ()
Definition at line 310 of file TriggerRoad.cxx.
References detectorIDs, elementIDs, GeomSvc::getPlaneNElements(), and GeomSvc::instance().
Referenced by isEnabled().
reflectTB()
TriggerRoad TriggerRoad::reflectTB ()
Definition at line 297 of file TriggerRoad.cxx.
References detectorIDs, and getTB().
Referenced by isEnabled(), and makeRoadList().
weight()
double TriggerRoad::weight () const inline
Definition at line 48 of file TriggerRoad.h.
References dumpWeight, and targetWeight.
Referenced by byWeight(), makeRoadList(), and operator<<().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const TriggerRoad & road) friend
Definition at line 125 of file TriggerRoad.cxx.
Member Data Documentation
detectorIDs
std::vector<int> TriggerRoad::detectorIDs
Definition at line 115 of file TriggerRoad.h.
Referenced by addElement(), ClassImp(), clear(), getDetectorID(), getLR(), getNElements(), getRoadID(), getTB(), getUniqueID(), isValid(), operator==(), print(), reflectLR(), reflectTB(), and TriggerRoad().
dumpWeight
double TriggerRoad::dumpWeight
Definition at line 98 of file TriggerRoad.h.
Referenced by ClassImp(), clear(), makeRoadList(), operator+=(), ratio(), and weight().
elementIDs
std::vector<int> TriggerRoad::elementIDs
Definition at line 116 of file TriggerRoad.h.
Referenced by addElement(), ClassImp(), clear(), getElementID(), getLR(), getRoadID(), getUniqueID(), operator<<(), operator==(), print(), reflectLR(), and TriggerRoad().
enabled
bool TriggerRoad::enabled
Definition at line 112 of file TriggerRoad.h.
Referenced by ClassImp(), clear(), disable(), enable(), isEnabled(), and isValid().
groupID
int TriggerRoad::groupID
Definition at line 94 of file TriggerRoad.h.
Referenced by TriggerAnalyzer::init(), and operator<<().
highMWeight
double TriggerRoad::highMWeight
Definition at line 100 of file TriggerRoad.h.
Referenced by ClassImp(), makeRoadList(), mratio(), and operator+=().
lowMWeight
double TriggerRoad::lowMWeight
Definition at line 99 of file TriggerRoad.h.
Referenced by ClassImp(), makeRoadList(), mratio(), and operator+=().
nMinus
int TriggerRoad::nMinus
Definition at line 63 of file TriggerRoad.h.
Referenced by ClassImp(), and operator+=().
nPlus
int TriggerRoad::nPlus
Definition at line 62 of file TriggerRoad.h.
Referenced by ClassImp(), and operator+=().
px_max
double TriggerRoad::px_max
Definition at line 105 of file TriggerRoad.h.
Referenced by ClassImp(), makeRoadList(), operator+=(), and operator<<().
px_mean
double TriggerRoad::px_mean
Definition at line 106 of file TriggerRoad.h.
Referenced by ClassImp(), getpXWidth(), makeRoadList(), operator+=(), and operator<<().
px_min
double TriggerRoad::px_min
Definition at line 104 of file TriggerRoad.h.
Referenced by byPt(), ClassImp(), makeRoadList(), operator+=(), and operator<<().
pXs
std::vector<double> TriggerRoad::pXs
Definition at line 103 of file TriggerRoad.h.
Referenced by clear(), getNEntries(), getpXMean(), getpXWidth(), makeRoadList(), and operator+=().
rndf
double TriggerRoad::rndf
Definition at line 109 of file TriggerRoad.h.
Referenced by byRndFrequency(), ClassImp(), and operator<<().
roadID
int TriggerRoad::roadID
Definition at line 91 of file TriggerRoad.h.
Referenced by clear(), and TriggerAnalyzer::init().
targetWeight
double TriggerRoad::targetWeight
Definition at line 97 of file TriggerRoad.h.
Referenced by ClassImp(), clear(), makeRoadList(), operator+=(), ratio(), and weight().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/TriggerRoad.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/TriggerRoad.cxx