Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/macros/G4_InsensitiveVolumes.C File Reference
G4_InsensitiveVolumes.C File Reference
#include <g4detectors/PHG4BlockSubsystem.h>
#include <g4detectors/PHG4SquareTubeSubsystem.h>
#include <g4detectors/SQG4DipoleMagnetSubsystem.h>
Functions
void SetupInsensitiveVolumes (PHG4Reco *g4Reco, const bool toggle_shielding=true, const bool toggle_fmag=true, const bool toggle_kmag=true, const bool toggle_absorber=true, const int enable_fmag_filter=0, const double filter_max_slope=0.25, const double filter_min_energy=5.)
Function Documentation
void SetupInsensitiveVolumes (PHG4Reco * g4Reco, const bool toggle_shielding = true, const bool toggle_fmag = true, const bool toggle_kmag = true, const bool toggle_absorber = true, const int enable_fmag_filter = 0, const double filter_max_slope = 0.25, const double filter_min_energy = 5.)
Definition at line 19 of file G4_InsensitiveVolumes.C.
References PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by EventDisplay4Sim(), Fun4DQ(), Fun4DumpGeom(), Fun4Sim(), Fun4Sim_TrkQA(), InitInput(), and RecoE1039Sim().