Class Reference for E1039 Core & Analysis Software: GetRoad Class Reference
GetRoad Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TriggerAna/src/GetRoad.h>
Public Member Functions
GetRoad (const char *out_name, const int nevt)
void get_mc_roads (const int idata, const int nevt)
void get_old_roads (const int idata)
int channels_to_roadID (const std::vector< int > detectorIDs, const std::vector< int > elementIDs)
argument should be passed after sorted by detectorID number from station 1 to 4
bool roadID_to_channels (const int roadID, std::vector< int > &detectorIDs, std::vector< int > &elementIDs)
void reset_var ()
void get_road_id (const int i)
Detailed Description
Definition at line 27 of file GetRoad.h.
Constructor & Destructor Documentation
GetRoad()
GetRoad::GetRoad (const char * out_name, const int nevt = 0)
Save Road data
Event-by-event road trees
unique road tree
MC data
Definition at line 22 of file GetRoad.cc.
References get_mc_roads(), and get_old_roads().
Member Function Documentation
channels_to_roadID()
int GetRoad::channels_to_roadID (const std::vector< int > detectorIDs, const std::vector< int > elementIDs)
argument should be passed after sorted by detectorID number from station 1 to 4
Definition at line 300 of file GetRoad.cc.
References bottomIDs, and topIDs.
get_mc_roads()
void GetRoad::get_mc_roads (const int idata, const int nevt = 0)
Definition at line 106 of file GetRoad.cc.
References bottomIDs, HitData::detector_id, HitData::element_id, get_road_id(), GeomSvc::getMeasurement(), GeomSvc::getPlanePosition(), DimuonData::mass, DimuonData::mom_neg, DimuonData::mom_pos, reset_var(), topIDs, HitData::track_id, DimuonData::track_id_neg, DimuonData::track_id_pos, DimuonData::x1, DimuonData::x2, and DimuonData::xf.
Referenced by GetRoad().
get_old_roads()
void GetRoad::get_old_roads (const int idata = 2)
Definition at line 209 of file GetRoad.cc.
References GeomSvc::getMeasurement(), GeomSvc::getPlanePosition(), and reset_var().
Referenced by GetRoad().
get_road_id()
void GetRoad::get_road_id (const int i)
Definition at line 377 of file GetRoad.cc.
Referenced by get_mc_roads().
reset_var()
void GetRoad::reset_var ()
Definition at line 348 of file GetRoad.cc.
Referenced by get_mc_roads(), and get_old_roads().
roadID_to_channels()
bool GetRoad::roadID_to_channels (const int roadID, std::vector< int > & detectorIDs, std::vector< int > & elementIDs)
Definition at line 322 of file GetRoad.cc.
References bottomIDs, and topIDs.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TriggerAna/src/GetRoad.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/TriggerAna/src/GetRoad.cc