Class Reference for E1039 Core & Analysis Software: MultiThreadReco Class Reference
MultiThreadReco Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/MultiThreadReco/src/MultiThreadReco.h>
Public Member Functions
MultiThreadReco (const std::string &name="MultiThreadReco")
virtual ~MultiThreadReco ()
void SetOutputFileName (const std::string name)
void SaveRawEvent (const bool save)
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SQReco
SQReco (const std::string &name="SQReco")
virtual ~SQReco ()
void setInputTy (SQReco::INPUT_TYPE input_ty)
void setFitterTy (SQReco::FITTER_TYPE fitter_ty)
const TString & get_eval_file_name () const
void set_eval_file_name (const TString &evalFileName)
bool use_geom_io_node () const
void use_geom_io_node (const bool val)
const std::string & get_geom_file_name () const
void set_geom_file_name (const std::string &geomFileName)
bool is_KF_enabled () const
void set_enable_KF (bool enable)
void set_output_list_index (const int idx)
See KalmanFastTracking::setOutputListID().
bool is_eval_enabled () const
void set_enable_eval (bool enable)
bool is_eval_dst_enabled () const
void set_enable_eval_dst (bool enable)
void add_eval_list (int listID)
const TString & get_evt_reducer_opt () const
void set_evt_reducer_opt (const TString &opt)
void set_legacy_rec_container (const bool b=true)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from SQReco
enum INPUT_TYPE { E906 , E1039 }
enum FITTER_TYPE {
LEGACY , KF , KFREF , DAF ,
DAFREF
}
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SQReco
virtual int InitField (PHCompositeNode *topNode)
virtual int InitGeom (PHCompositeNode *topNode)
virtual int InitFastTracking ()
virtual int MakeNodes (PHCompositeNode *topNode)
virtual int GetNodes (PHCompositeNode *topNode)
int InitEvalTree ()
int ResetEvalVars ()
void ProcessEventPrep ()
void ProcessEventFinish ()
SRawEvent * BuildSRawEvent ()
int updateHitInfo (SRawEvent *sraw_event)
bool fitTrackCand (Tracklet &tracklet, KalmanFitter *fitter)
bool fitTrackCand (Tracklet &tracklet, SQGenFit::GFFitter *fitter)
void fillRecTrack (SRecTrack &recTrack)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from SQReco
SQReco::INPUT_TYPE _input_type
SQReco::FITTER_TYPE _fitter_type
int _output_list_idx
bool _enable_eval
TString _eval_file_name
TTree * _eval_tree
TClonesArray * _tracklets
std::vector< int > _eval_listIDs
bool _enable_eval_dst
TrackletVector * _tracklet_vector
TString _evt_reducer_opt
KalmanFastTracking * _fastfinder
EventReducer * _eventReducer
bool _enable_KF
KalmanFitter * _kfitter
SQGenFit::GFFitter * _gfitter
PHField * _phfield
SQGenFit::GFField * _gfield
recoConsts * rc
size_t _event
SQRun * _run_header
SQSpillMap * _spill_map
SQEvent * _event_header
SQHitVector * _hit_vector
SQHitVector * _triggerhit_vector
std::map< int, size_t > _m_hitID_idx
std::map< int, size_t > _m_trghitID_idx
bool _legacy_rec_container
SRawEvent * _rawEvent
SRecEvent * _recEvent
SQTrackVector * _recTrackVec
bool _use_geom_io_node
std::string _geom_file_name
TGeoManager * _t_geo_manager
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 7 of file MultiThreadReco.h.
Constructor & Destructor Documentation
MultiThreadReco()
MultiThreadReco::MultiThreadReco (const std::string & name = "MultiThreadReco")
Definition at line 9 of file MultiThreadReco.cc.
~MultiThreadReco()
MultiThreadReco::~MultiThreadReco () virtual
Definition at line 18 of file MultiThreadReco.cc.
Member Function Documentation
End()
int MultiThreadReco::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SQReco.
Definition at line 82 of file MultiThreadReco.cc.
References KScheduler::endThreads(), Fun4AllReturnCodes::EVENT_OK, and KScheduler::PushPoison().
Init()
int MultiThreadReco::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SQReco.
Definition at line 23 of file MultiThreadReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
InitRun()
int MultiThreadReco::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SQReco.
Definition at line 28 of file MultiThreadReco.cc.
References SQReco::_enable_KF, SQReco::_fitter_type, SQReco::_gfield, SQReco::_gfitter, SQReco::_kfitter, SQReco::_phfield, SQReco::_t_geo_manager, SQReco::DAF, SQReco::DAFREF, Fun4AllReturnCodes::EVENT_OK, SQReco::GetNodes(), SQGenFit::GFFitter::init(), KScheduler::Init(), SQReco::InitField(), SQReco::InitGeom(), SQReco::KF, SQReco::KFREF, SQReco::LEGACY, KScheduler::runThreads(), KScheduler::SaveRawEvent(), and KalmanFitter::setControlParameter().
process_event()
int MultiThreadReco::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SQReco.
Definition at line 64 of file MultiThreadReco.cc.
References SQReco::_input_type, SQReco::_rawEvent, SQReco::BuildSRawEvent(), SQReco::E1039, Fun4AllReturnCodes::EVENT_OK, and KScheduler::PushEvent().
SaveRawEvent()
void MultiThreadReco::SaveRawEvent (const bool save) inline
Definition at line 17 of file MultiThreadReco.h.
SetOutputFileName()
void MultiThreadReco::SetOutputFileName (const std::string name) inline
Definition at line 16 of file MultiThreadReco.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/MultiThreadReco/src/MultiThreadReco.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/MultiThreadReco/src/MultiThreadReco.cc