E1039 Software: DbSvc Class Reference
DbSvc Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/db_svc/DbSvc.h>
Classes
class VarList
Public Types
enum SvrId_t {
DB1, DB2, DB3, DB01,
UIUC
}
enum UsrId_t { Guest, Prod }
Public Member Functions
DbSvc (const SvrId_t svr_id=DB1, const UsrId_t usr_id=Guest, const std::string my_cnf="")
~DbSvc ()
void UseSchema (const char *name, const bool do_create=false, const bool do_drop=false)
void UseSchema (const std::string name, const bool do_create=false, const bool do_drop=false)
void DropTable (const char *name)
void DropTable (const std::string name)
bool HasTable (const char *name, const bool exit_on_false=false)
bool HasTable (const std::string name, const bool exit_on_false=false)
void CreateTable (const std::string name, const std::vector< std::string > list_var, const std::vector< std::string > list_type, const std::vector< std::string > list_key)
void CreateTable (const std::string name, const int n_var, const char **list_var, const char **list_type, const int n_key=0, const char **list_key=0)
void CreateTable (const std::string name, const VarList list)
TSQLServer * Con ()
TSQLStatement * Process (const char *query)
TSQLStatement * Process (const std::string query)
Private Member Functions
void SelectServer ()
void ConnectServer ()
Private Attributes
SvrId_t m_svr_id
UsrId_t m_usr_id
std::string m_svr
std::string m_my_cnf
TSQLServer * m_con
Detailed Description
Definition at line 9 of file DbSvc.h.
Member Enumeration Documentation
SvrId_t
enum DbSvc::SvrId_t
Enumerator
DB1
DB2
DB3
DB01
UIUC
Definition at line 11 of file DbSvc.h.
UsrId_t
enum DbSvc::UsrId_t
Enumerator
Guest
Prod
Definition at line 12 of file DbSvc.h.
Constructor & Destructor Documentation
DbSvc()
DbSvc::DbSvc (const SvrId_t svr_id = DB1, const UsrId_t usr_id = Guest, const std::string my_cnf = "")
Definition at line 38 of file DbSvc.cc.
References ExpandEnvironmentals(), FileExist(), and LogInfo.
Referenced by DbSvc::VarList::Size().
~DbSvc()
DbSvc::~DbSvc ()
Definition at line 58 of file DbSvc.cc.
Referenced by DbSvc::VarList::Size().
Member Function Documentation
Con()
TSQLServer* DbSvc::Con () inline
Definition at line 37 of file DbSvc.h.
References m_con, and Process().
Referenced by DbUpRun::UploadToDB(), DbUpSpill::UploadToScalerTable(), DbUpSpill::UploadToSlowContTable(), DbUpSpill::UploadToSpillTable(), ChanMapScaler::WriteDbTable(), CalibParamInTimeTaiwan::WriteDbTable(), CalibParamXT::WriteDbTable(), CalibParamInTimeV1495::WriteDbTable(), ChanMapTaiwan::WriteDbTable(), ChanMapV1495::WriteDbTable(), and ParamRunRange::WriteToDB().
ConnectServer()
void DbSvc::ConnectServer () private
User and password must be given in my.cnf, not here.
Definition at line 212 of file DbSvc.cc.
CreateTable() [1/3]
void DbSvc::CreateTable (const std::string name, const std::vector< std::string > list_var, const std::vector< std::string > list_type, const std::vector< std::string > list_key)
Definition at line 113 of file DbSvc.cc.
Referenced by HasTable(), DbUpRun::UploadToDB(), DbUpSpill::UploadToScalerTable(), DbUpSpill::UploadToSlowContTable(), DbUpSpill::UploadToSpillTable(), ChanMapScaler::WriteDbTable(), CalibParamInTimeTaiwan::WriteDbTable(), CalibParamXT::WriteDbTable(), CalibParamInTimeV1495::WriteDbTable(), ChanMapTaiwan::WriteDbTable(), ChanMapV1495::WriteDbTable(), and ParamRunRange::WriteToDB().
CreateTable() [2/3]
void DbSvc::CreateTable (const std::string name, const int n_var, const char ** list_var, const char ** list_type, const int n_key = 0, const char ** list_key = 0)
Definition at line 146 of file DbSvc.cc.
CreateTable() [3/3]
void DbSvc::CreateTable (const std::string name, const VarList list)
Definition at line 161 of file DbSvc.cc.
References DbSvc::VarList::Get(), and DbSvc::VarList::Size().
DropTable() [1/2]
void DbSvc::DropTable (const char * name)
Definition at line 93 of file DbSvc.cc.
Referenced by UseSchema(), ParamRunRange::WriteToDB(), and RunParamBase::WriteToDB().
DropTable() [2/2]
void DbSvc::DropTable (const std::string name) inline
Definition at line 30 of file DbSvc.h.
References DropTable(), and HasTable().
Referenced by DropTable().
HasTable() [1/2]
bool DbSvc::HasTable (const char * name, const bool exit_on_false = false)
Definition at line 103 of file DbSvc.cc.
Referenced by DropTable(), ParamRunRange::ReadFromDB(), RunParamBase::ReadFromDB(), DbUpRun::UploadToDB(), DbUpSpill::UploadToScalerTable(), DbUpSpill::UploadToSlowContTable(), and DbUpSpill::UploadToSpillTable().
HasTable() [2/2]
bool DbSvc::HasTable (const std::string name, const bool exit_on_false = false) inline
Definition at line 32 of file DbSvc.h.
References CreateTable(), and HasTable().
Referenced by HasTable().
Process() [1/2]
TSQLStatement * DbSvc::Process (const char * query)
This function runs Statement(), Process() and StoreResult() with error check. The return object (TSQLStatement*) must be deleted by user. Example: TSQLStatement* stmt = db_svc->Process(query); while (stmt->NextResultRow()) { int id = stmt->GetInt(0); int event = stmt->GetInt(1); } delete stmt;
Definition at line 187 of file DbSvc.cc.
Referenced by Con(), ChanMapScaler::ReadDbTable(), CalibParamInTimeTaiwan::ReadDbTable(), CalibParamXT::ReadDbTable(), CalibParamInTimeV1495::ReadDbTable(), ChanMapTaiwan::ReadDbTable(), ChanMapV1495::ReadDbTable(), and ParamRunRange::ReadFromDB().
Process() [2/2]
TSQLStatement* DbSvc::Process (const std::string query) inline
Definition at line 39 of file DbSvc.h.
References Process().
Referenced by Process().
SelectServer()
void DbSvc::SelectServer () private
Definition at line 199 of file DbSvc.cc.
UseSchema() [1/2]
void DbSvc::UseSchema (const char * name, const bool do_create = false, const bool do_drop = false)
Definition at line 63 of file DbSvc.cc.
Referenced by ParamRunRange::ReadFromDB(), RunParamBase::ReadFromDB(), DbSvc::VarList::Size(), DbUpRun::UploadToDB(), DbUpSpill::UploadToScalerTable(), DbUpSpill::UploadToSlowContTable(), DbUpSpill::UploadToSpillTable(), ParamRunRange::WriteToDB(), and RunParamBase::WriteToDB().
UseSchema() [2/2]
void DbSvc::UseSchema (const std::string name, const bool do_create = false, const bool do_drop = false) inline
Definition at line 27 of file DbSvc.h.
References DropTable(), and UseSchema().
Referenced by UseSchema().
Member Data Documentation
m_con
TSQLServer* DbSvc::m_con private
Definition at line 46 of file DbSvc.h.
Referenced by Con().
m_my_cnf
std::string DbSvc::m_my_cnf private
Definition at line 45 of file DbSvc.h.
m_svr
std::string DbSvc::m_svr private
Definition at line 44 of file DbSvc.h.
m_svr_id
SvrId_t DbSvc::m_svr_id private
Definition at line 42 of file DbSvc.h.
m_usr_id
UsrId_t DbSvc::m_usr_id private
Definition at line 43 of file DbSvc.h.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/db_svc/DbSvc.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/db_svc/DbSvc.cc