E1039 Software: PHGenEventListv1 Class Reference
PHGenEventListv1 Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/generators/phhepmc/PHGenEventListv1.h>
Public Types
typedef PHGenEventv1 PHGenEventVersion
Public Member Functions
PHGenEventListv1 ()
virtual ~PHGenEventListv1 ()
size_t size () const
const PHGenEvent * at (size_t i) const
PHGenEvent * at (size_t i)
bool has (unsigned int id) const
size_t find (unsigned int id) const
const PHGenEvent * fetch (unsigned int id) const
PHGenEvent * fetch (unsigned int id)
void insert (const PHGenEvent *genevent)
unsigned int generate_id () const
void remove (size_t i)
void clear ()
void identify (std::ostream &out=std::cout) const
void print (std::ostream &out=std::cout) const
void Reset ()
Clear Event.
Public Member Functions inherited from PHGenEventList
virtual ~PHGenEventList ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Private Member Functions
bool stale () const
void refresh () const
Private Attributes
std::vector< PHGenEventVersion > _genevents
bool _stale
std::map< unsigned int, const PHGenEvent * > _id_genevent_map
exclude from ROOT I/O
Additional Inherited Members
Protected Member Functions inherited from PHGenEventList
PHGenEventList ()
Detailed Description
Definition at line 12 of file PHGenEventListv1.h.
Member Typedef Documentation
PHGenEventVersion
typedef PHGenEventv1 PHGenEventListv1::PHGenEventVersion
Definition at line 15 of file PHGenEventListv1.h.
Constructor & Destructor Documentation
PHGenEventListv1()
PHGenEventListv1::PHGenEventListv1 ()
~PHGenEventListv1()
PHGenEventListv1::~PHGenEventListv1 () virtual
Definition at line 18 of file PHGenEventListv1.cc.
References _genevents, and _id_genevent_map.
Member Function Documentation
at() [1/2]
const PHGenEvent * PHGenEventListv1::at (size_t i) const virtual
Reimplemented from PHGenEventList.
Definition at line 43 of file PHGenEventListv1.cc.
References _genevents, _stale, and refresh().
Referenced by size().
at() [2/2]
PHGenEvent * PHGenEventListv1::at (size_t i) virtual
Reimplemented from PHGenEventList.
Definition at line 51 of file PHGenEventListv1.cc.
References _genevents, _stale, and refresh().
clear()
void PHGenEventListv1::clear () virtual
Reimplemented from PHGenEventList.
Definition at line 121 of file PHGenEventListv1.cc.
References _genevents, and _id_genevent_map.
Referenced by Reset(), and size().
fetch() [1/2]
const PHGenEvent * PHGenEventListv1::fetch (unsigned int id) const virtual
Reimplemented from PHGenEventList.
Definition at line 72 of file PHGenEventListv1.cc.
References _id_genevent_map, _stale, NULL, and refresh().
Referenced by size().
fetch() [2/2]
PHGenEvent * PHGenEventListv1::fetch (unsigned int id) virtual
Reimplemented from PHGenEventList.
Definition at line 80 of file PHGenEventListv1.cc.
References _id_genevent_map, _stale, NULL, and refresh().
find()
size_t PHGenEventListv1::find (unsigned int id) const virtual
Reimplemented from PHGenEventList.
Definition at line 64 of file PHGenEventListv1.cc.
References _genevents, _stale, and refresh().
Referenced by insert(), and size().
generate_id()
unsigned int PHGenEventListv1::generate_id () const virtual
Reimplemented from PHGenEventList.
Definition at line 106 of file PHGenEventListv1.cc.
References _id_genevent_map, _stale, and refresh().
Referenced by size().
has()
bool PHGenEventListv1::has (unsigned int id) const virtual
Reimplemented from PHGenEventList.
Definition at line 58 of file PHGenEventListv1.cc.
References _id_genevent_map, _stale, and refresh().
Referenced by insert(), and size().
identify()
void PHGenEventListv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHGenEventList.
Definition at line 23 of file PHGenEventListv1.cc.
References _stale, and refresh().
Referenced by print(), and size().
insert()
void PHGenEventListv1::insert (const PHGenEvent * genevent) virtual
Reimplemented from PHGenEventList.
Definition at line 88 of file PHGenEventListv1.cc.
References _genevents, _id_genevent_map, _stale, find(), PHGenEvent::get_id(), has(), and refresh().
Referenced by size().
print()
void PHGenEventListv1::print (std::ostream & out = std::cout) const virtual
Reimplemented from PHGenEventList.
Definition at line 28 of file PHGenEventListv1.cc.
References _genevents, _stale, identify(), refresh(), and size().
Referenced by size().
refresh()
void PHGenEventListv1::refresh () const private
Definition at line 126 of file PHGenEventListv1.cc.
References _genevents, _id_genevent_map, and _stale.
Referenced by at(), fetch(), find(), generate_id(), has(), identify(), insert(), print(), remove(), and stale().
remove()
void PHGenEventListv1::remove (size_t i) virtual
Reimplemented from PHGenEventList.
Definition at line 116 of file PHGenEventListv1.cc.
References _genevents, and refresh().
Reset()
void PHGenEventListv1::Reset () virtual
Clear Event.
Reimplemented from PHGenEventList.
Definition at line 38 of file PHGenEventListv1.cc.
References _stale, and clear().
Referenced by size().
size()
size_t PHGenEventListv1::size () const inline virtual
Reimplemented from PHGenEventList.
Definition at line 20 of file PHGenEventListv1.h.
References _genevents, at(), clear(), fetch(), find(), generate_id(), has(), identify(), insert(), print(), and Reset().
Referenced by print().
stale()
bool PHGenEventListv1::stale () const inline private
Definition at line 40 of file PHGenEventListv1.h.
References _stale, and refresh().
Member Data Documentation
_genevents
std::vector<PHGenEventVersion> PHGenEventListv1::_genevents private
Definition at line 43 of file PHGenEventListv1.h.
Referenced by at(), clear(), find(), insert(), print(), refresh(), remove(), size(), and ~PHGenEventListv1().
_id_genevent_map
std::map<unsigned int,const PHGenEvent*> PHGenEventListv1::_id_genevent_map mutable private
exclude from ROOT I/O
Definition at line 47 of file PHGenEventListv1.h.
Referenced by clear(), fetch(), generate_id(), has(), insert(), refresh(), and ~PHGenEventListv1().
_stale
bool PHGenEventListv1::_stale mutable private
Definition at line 46 of file PHGenEventListv1.h.
Referenced by at(), fetch(), find(), generate_id(), has(), identify(), insert(), print(), refresh(), Reset(), and stale().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/generators/phhepmc/PHGenEventListv1.h
/home/yuhw/GitHub/SeaQuest/e1039-core/generators/phhepmc/PHGenEventListv1.cc