E1039 Software: PHG4CylinderGeom Class Reference
PHG4CylinderGeom Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4CylinderGeom.h>
Public Member Functions
virtual ~PHG4CylinderGeom ()
virtual void identify (std::ostream &os=std::cout) const
virtual int get_layer () const
virtual double get_radius () const
virtual double get_thickness () const
virtual double get_zmin () const
virtual double get_zmax () const
virtual int get_nscint () const
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_layer (const int i)
virtual void set_radius (const double r)
virtual void set_thickness (const double t)
virtual void set_zmin (const double z)
virtual void set_zmax (const double z)
virtual void set_nscint (const int i)
virtual void set_tiltangle (const double i)
virtual void set_phi_slat_zero (const double phi)
virtual void find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[])
virtual void find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[])
virtual double get_strip_y_spacing () const
virtual double get_strip_z_spacing () const
virtual double get_strip_tilt () const
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
virtual void ImportParameters (const PHParameters &param)
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
PHG4CylinderGeom ()
Detailed Description
Definition at line 11 of file PHG4CylinderGeom.h.
Constructor & Destructor Documentation
~PHG4CylinderGeom()
virtual PHG4CylinderGeom::~PHG4CylinderGeom () inline virtual
Definition at line 15 of file PHG4CylinderGeom.h.
References identify().
PHG4CylinderGeom()
PHG4CylinderGeom::PHG4CylinderGeom () inline protected
Definition at line 55 of file PHG4CylinderGeom.h.
Member Function Documentation
find_segment_center()
virtual void PHG4CylinderGeom::find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[]) inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 36 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
find_strip_center()
virtual void PHG4CylinderGeom::find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[]) inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 37 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_layer()
virtual int PHG4CylinderGeom::get_layer () const inline virtual
Reimplemented in PHG4CylinderGeomv4, and PHG4CylinderGeomv1.
Definition at line 18 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4CylinderGeomContainer::AddLayerGeom(), PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
get_N_sensors_in_layer()
virtual int PHG4CylinderGeom::get_N_sensors_in_layer () const inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 45 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_N_strip_columns()
virtual int PHG4CylinderGeom::get_N_strip_columns () const inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 43 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_N_strips_per_column()
virtual int PHG4CylinderGeom::get_N_strips_per_column () const inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 44 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_nscint()
virtual int PHG4CylinderGeom::get_nscint () const inline virtual
Reimplemented in PHG4CylinderGeomv2.
Definition at line 23 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_phi_slat_zero()
virtual double PHG4CylinderGeom::get_phi_slat_zero () const inline virtual
Reimplemented in PHG4CylinderGeomv3.
Definition at line 25 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_pixel_thickness()
virtual double PHG4CylinderGeom::get_pixel_thickness () const inline virtual
Definition at line 49 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_pixel_x()
virtual double PHG4CylinderGeom::get_pixel_x () const inline virtual
Definition at line 48 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_pixel_z()
virtual double PHG4CylinderGeom::get_pixel_z () const inline virtual
Definition at line 47 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_radius()
virtual double PHG4CylinderGeom::get_radius () const inline virtual
Reimplemented in PHG4CylinderGeomv4, and PHG4CylinderGeomv1.
Definition at line 19 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4CylinderCellReco::InitRun(), PHG4CylinderCellTPCReco::InitRun(), and PHG4GenHit::process_event().
get_strip_tilt()
virtual double PHG4CylinderGeom::get_strip_tilt () const inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 41 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_strip_y_spacing()
virtual double PHG4CylinderGeom::get_strip_y_spacing () const inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 39 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_strip_z_spacing()
virtual double PHG4CylinderGeom::get_strip_z_spacing () const inline virtual
Reimplemented in PHG4CylinderGeomv4.
Definition at line 40 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_thickness()
virtual double PHG4CylinderGeom::get_thickness () const inline virtual
Reimplemented in PHG4CylinderGeomv4, and PHG4CylinderGeomv1.
Definition at line 20 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4CylinderCellReco::InitRun(), PHG4CylinderCellTPCReco::InitRun(), and PHG4GenHit::process_event().
get_tiltangle()
virtual double PHG4CylinderGeom::get_tiltangle () const inline virtual
Reimplemented in PHG4CylinderGeomv3.
Definition at line 24 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
get_zmax()
virtual double PHG4CylinderGeom::get_zmax () const inline virtual
Reimplemented in PHG4CylinderGeomv1.
Definition at line 22 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
get_zmin()
virtual double PHG4CylinderGeom::get_zmin () const inline virtual
Reimplemented in PHG4CylinderGeomv1.
Definition at line 21 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4CylinderCellTPCReco::InitRun().
identify()
void PHG4CylinderGeom::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4CylinderGeomv4, PHG4CylinderGeomv1, PHG4CylinderGeomv3, and PHG4CylinderGeomv2.
Definition at line 7 of file PHG4CylinderGeom.cc.
Referenced by ~PHG4CylinderGeom().
ImportParameters()
virtual void PHG4CylinderGeom::ImportParameters (const PHParameters & param) inline virtual
load parameters from PHParameters, which interface to Database/XML/ROOT files
Reimplemented in PHG4CylinderGeomv1, and PHG4CylinderGeomv2.
Definition at line 52 of file PHG4CylinderGeom.h.
Referenced by PHG4CylinderGeomv1::ImportParameters().
set_layer()
virtual void PHG4CylinderGeom::set_layer (const int i) inline virtual
Reimplemented in PHG4CylinderGeomv4, and PHG4CylinderGeomv1.
Definition at line 27 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PHG4CylinderGeomContainer::AddLayerGeom().
set_nscint()
virtual void PHG4CylinderGeom::set_nscint (const int i) inline virtual
Reimplemented in PHG4CylinderGeomv2.
Definition at line 32 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
set_phi_slat_zero()
virtual void PHG4CylinderGeom::set_phi_slat_zero (const double phi) inline virtual
Reimplemented in PHG4CylinderGeomv3.
Definition at line 34 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
set_radius()
virtual void PHG4CylinderGeom::set_radius (const double r) inline virtual
Reimplemented in PHG4CylinderGeomv1.
Definition at line 28 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
set_thickness()
virtual void PHG4CylinderGeom::set_thickness (const double t) inline virtual
Reimplemented in PHG4CylinderGeomv1.
Definition at line 29 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
set_tiltangle()
virtual void PHG4CylinderGeom::set_tiltangle (const double i) inline virtual
Reimplemented in PHG4CylinderGeomv3.
Definition at line 33 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
set_zmax()
virtual void PHG4CylinderGeom::set_zmax (const double z) inline virtual
Reimplemented in PHG4CylinderGeomv1.
Definition at line 31 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
set_zmin()
virtual void PHG4CylinderGeom::set_zmin (const double z) inline virtual
Reimplemented in PHG4CylinderGeomv1.
Definition at line 30 of file PHG4CylinderGeom.h.
References PHOOL_VIRTUAL_WARN.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4CylinderGeom.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4CylinderGeom.cc