Class Reference for E1039 Core & Analysis Software: PHCompositeNode Class Reference
PHCompositeNode Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHCompositeNode.h>
Public Member Functions
PHCompositeNode (const std::string &)
virtual ~PHCompositeNode ()
PHBoolean addNode (PHNode *)
virtual void prune ()
void print (const std::string &="")
virtual bool write (PHIOManager *, const std::string &="")
Public Member Functions inherited from PHNode
PHNode (const std::string &)
PHNode (const std::string &, const std::string &)
virtual ~PHNode ()
PHNode * getParent () const
PHBoolean isPersistent () const
void makePersistent ()
const std::string getObjectType () const
const std::string getType () const
const std::string getName () const
const std::string getClass () const
void setParent (PHNode *p)
void setName (const std::string &n)
void setObjectType (const std::string &type)
virtual void setResetFlag (const int val)
virtual PHBoolean getResetFlag () const
void makeTransient ()
Protected Member Functions
virtual void forgetMe (PHNode *)
Protected Member Functions inherited from PHNode
PHNode ()
PHNode (const PHNode &)
PHNode & operator= (const PHNode &)
Protected Attributes
PHPointerList< PHNode > subNodes
int deleteMe
Protected Attributes inherited from PHNode
PHNode * parent
bool persistent
std::string type
std::string objecttype
std::string name
std::string objectclass
bool reset_able
Friends
class PHNodeIterator
Detailed Description
Definition at line 14 of file PHCompositeNode.h.
Constructor & Destructor Documentation
PHCompositeNode()
PHCompositeNode::PHCompositeNode (const std::string & name)
Definition at line 20 of file PHCompositeNode.cc.
References PHCompositeNode(), and PHNode::type.
Referenced by PHCompositeNode().
~PHCompositeNode()
PHCompositeNode::~PHCompositeNode () virtual
Definition at line 27 of file PHCompositeNode.cc.
References PHPointerList< T >::clearAndDestroy(), deleteMe, and subNodes.
Member Function Documentation
addNode()
PHBoolean PHCompositeNode::addNode (PHNode * newNode)
Definition at line 40 of file PHCompositeNode.cc.
References PHPointerList< T >::append(), False, PHNode::getName(), PHWHERE, PHNode::setParent(), and subNodes.
Referenced by PHNodeIterator::addNode(), PHHepMCGenHelper::create_node_tree(), Fun4AllSRawEventInputManager::enable_E1039_translation(), Fun4AllEVIOInputManager::Fun4AllEVIOInputManager(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), Fun4AllHitMatrixInputManager::Fun4AllHitMatrixInputManager(), Fun4AllOscarInputManager::Fun4AllOscarInputManager(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), Fun4AllRUSInputManager::Fun4AllRUSInputManager(), Fun4AllSRawEventInputManager::Fun4AllSRawEventInputManager(), Fun4AllTrackQAv1InputManager::Fun4AllTrackQAv1InputManager(), Fun4AllVectEventInputManager::Fun4AllVectEventInputManager(), PHFieldUtility::GetFieldConfigNode(), PHFieldUtility::GetFieldMapNode(), PHGeomUtility::GetGeomIOTGeoNode(), PHGeomUtility::GetGeomTGeoNode(), Fun4AllServer::getNode(), PHG4GDMLUtility::GetOrMakeConfigNode(), PHG4ConeSubsystem::Init(), HepMCCompress::Init(), HepMCNodeReader::Init(), PHG4HeadReco::Init(), Fun4AllServer::InitNodeTree(), Fun4AllPrdfOutputManager::InitPrdfNode(), PHG4TruthSubsystem::InitRun(), PHG4DetectorGroupSubsystem::InitRun(), PHG4DetectorSubsystem::InitRun(), DoEmbedding::InitRun(), SQSingleMuonGen::InitRun(), PHG4BlockCellReco::InitRun(), PHG4CylinderCellReco::InitRun(), PHG4CylinderCellTPCReco::InitRun(), SQDigitizer::InitRun(), PHG4InEventCompress::InitRun(), PHG4InEventReadBack::InitRun(), PHG4ParticleGeneratorBase::InitRun(), PHG4ParticleGeneratorVectorMeson::InitRun(), PHG4PSScanGenerator::InitRun(), PHG4SimpleEventGenerator::InitRun(), SQCosmicGen::InitRun(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4BNLTargetCoilSubsystem::InitRunSubsystem(), PHG4CollimatorSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4EMCalSubsystem::InitRunSubsystem(), PHG4PolyconSubsystem::InitRunSubsystem(), PHG4SquareTubeSubsystem::InitRunSubsystem(), PHG4TargetCoilSubsystem::InitRunSubsystem(), PHG4TargetCoilV2Subsystem::InitRunSubsystem(), SQReco::MakeNodes(), PHParameterContainerInterface::PutOnParNode(), PHParameterInterface::PutOnParNode(), PHG4ParameterContainerInterface::PutOnParNode(), PHG4ParameterInterface::PutOnParNode(), PHParameters::SaveToNodeTree(), PHParametersContainer::SaveToNodeTree(), PHG4Parameters::SaveToNodeTree(), PHG4ParametersContainer::SaveToNodeTree(), and PHG4Reco::setupInputEventNodeReader().
forgetMe()
void PHCompositeNode::forgetMe (PHNode * child) protected virtual
Implements PHNode.
Definition at line 84 of file PHCompositeNode.cc.
References deleteMe, PHPointerListIterator< T >::pos(), PHPointerList< T >::removeAt(), and subNodes.
print()
void PHCompositeNode::print (const std::string & path = "") virtual
Implements PHNode.
Definition at line 128 of file PHCompositeNode.cc.
References PHNode::name, PHNode::print(), subNodes, and PHNode::type.
Referenced by PHNodeIterator::print().
prune()
void PHCompositeNode::prune () virtual
Implements PHNode.
Definition at line 64 of file PHCompositeNode.cc.
References PHNode::isPersistent(), PHPointerListIterator< T >::pos(), PHNode::prune(), PHPointerList< T >::removeAt(), and subNodes.
write()
bool PHCompositeNode::write (PHIOManager * IOManager, const std::string & path = "") virtual
Implements PHNode.
Definition at line 107 of file PHCompositeNode.cc.
References phooldefs::branchpathdelim, PHNode::name, subNodes, and PHNode::write().
Referenced by PHNodeIOManager::write().
Friends And Related Function Documentation
PHNodeIterator
friend class PHNodeIterator friend
Definition at line 16 of file PHCompositeNode.h.
Member Data Documentation
deleteMe
int PHCompositeNode::deleteMe protected
Definition at line 43 of file PHCompositeNode.h.
Referenced by forgetMe(), and ~PHCompositeNode().
subNodes
PHPointerList<PHNode> PHCompositeNode::subNodes protected
Definition at line 42 of file PHCompositeNode.h.
Referenced by addNode(), PHNodeIterator::cd(), PHNodeIterator::findFirst(), PHNodeIterator::forEach(), forgetMe(), PHNodeIterator::ls(), print(), prune(), write(), and ~PHCompositeNode().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHCompositeNode.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/phool/PHCompositeNode.cc