Class Reference for E1039 Core & Analysis Software: SQHardSpill Class Reference
SQHardSpill Class Reference abstract
An SQ interface class to hold the hardware-related data of one spill.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHardSpill.h>
Public Member Functions
virtual ~SQHardSpill ()
virtual void Reset ()=0
Clear Event.
virtual void identify (std::ostream &os=std::cout) const =0
virtual int isValid () const =0
isValid returns non zero if object contains vailid data
virtual SQHardSpill * clone () const =0
Virtual copy constructor.
virtual SQHardSpill * Clone () const =0
No use. Only for backward compatibility.
virtual int get_bos_coda_id () const =0
Return the Coda ID at BOS of this spill.
virtual void set_bos_coda_id (const int a)=0
virtual int get_bos_vme_time () const =0
Return the VME time at BOS of this spill.
virtual void set_bos_vme_time (const int a)=0
virtual int get_eos_coda_id () const =0
Return the Coda ID at EOS of this spill.
virtual void set_eos_coda_id (const int a)=0
virtual int get_eos_vme_time () const =0
Return the VME time at EOS of this spill.
virtual void set_eos_vme_time (const int a)=0
virtual double get_time_input () const =0
Return the time taken for the Coda input per spill.
virtual void set_time_input (const double a)=0
virtual double get_time_decode () const =0
Return the time taken for the word decoding per spill.
virtual void set_time_decode (const double a)=0
virtual double get_time_map () const =0
Return the time taken for the channel mapping per spill.
virtual void set_time_map (const double a)=0
virtual double get_time_subsys () const =0
Return the time taken for the SubsysReco event processing per spill.
virtual void set_time_subsys (const double a)=0
virtual double get_time_output () const =0
Return the time taken for the data output per spill.
virtual void set_time_output (const double a)=0
ClassDef (SQHardSpill, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQHardSpill ()
Detailed Description
An SQ interface class to hold the hardware-related data of one spill.
Definition at line 7 of file SQHardSpill.h.
Constructor & Destructor Documentation
SQHardSpill::SQHardSpill () inline protected
Definition at line 9 of file SQHardSpill.h.
virtual SQHardSpill::~SQHardSpill () inline virtual
Definition at line 12 of file SQHardSpill.h.
Member Function Documentation
SQHardSpill::ClassDef (SQHardSpill , 1)
virtual SQHardSpill* SQHardSpill::clone () const pure virtual
Virtual copy constructor.
Reimplemented from PHObject.
Implemented in SQHardSpill_v1.
virtual SQHardSpill* SQHardSpill::Clone () const pure virtual
No use. Only for backward compatibility.
Implemented in SQHardSpill_v1.
virtual int SQHardSpill::get_bos_coda_id () const pure virtual
Return the Coda ID at BOS of this spill.
Implemented in SQHardSpill_v1.
virtual int SQHardSpill::get_bos_vme_time () const pure virtual
Return the VME time at BOS of this spill.
Implemented in SQHardSpill_v1.
virtual int SQHardSpill::get_eos_coda_id () const pure virtual
Return the Coda ID at EOS of this spill.
Implemented in SQHardSpill_v1.
virtual int SQHardSpill::get_eos_vme_time () const pure virtual
Return the VME time at EOS of this spill.
Implemented in SQHardSpill_v1.
virtual double SQHardSpill::get_time_decode () const pure virtual
Return the time taken for the word decoding per spill.
Implemented in SQHardSpill_v1.
Referenced by OnlMonMainDaq::ProcessEventOnlMon().
virtual double SQHardSpill::get_time_input () const pure virtual
Return the time taken for the Coda input per spill.
Implemented in SQHardSpill_v1.
Referenced by OnlMonMainDaq::ProcessEventOnlMon().
virtual double SQHardSpill::get_time_map () const pure virtual
Return the time taken for the channel mapping per spill.
Implemented in SQHardSpill_v1.
Referenced by OnlMonMainDaq::ProcessEventOnlMon().
virtual double SQHardSpill::get_time_output () const pure virtual
Return the time taken for the data output per spill.
Implemented in SQHardSpill_v1.
Referenced by OnlMonMainDaq::ProcessEventOnlMon().
virtual double SQHardSpill::get_time_subsys () const pure virtual
Return the time taken for the SubsysReco event processing per spill.
Implemented in SQHardSpill_v1.
Referenced by OnlMonMainDaq::ProcessEventOnlMon().
virtual void SQHardSpill::identify (std::ostream & os = std::cout) const pure virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Implemented in SQHardSpill_v1.
virtual int SQHardSpill::isValid () const pure virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Implemented in SQHardSpill_v1.
virtual void SQHardSpill::Reset () pure virtual
Clear Event.
Reimplemented from PHObject.
Implemented in SQHardSpill_v1.
virtual void SQHardSpill::set_bos_coda_id (const int a) pure virtual
Implemented in SQHardSpill_v1.
virtual void SQHardSpill::set_bos_vme_time (const int a) pure virtual
Implemented in SQHardSpill_v1.
virtual void SQHardSpill::set_eos_coda_id (const int a) pure virtual
Implemented in SQHardSpill_v1.
virtual void SQHardSpill::set_eos_vme_time (const int a) pure virtual
Implemented in SQHardSpill_v1.
virtual void SQHardSpill::set_time_decode (const double a) pure virtual
Implemented in SQHardSpill_v1.
virtual void SQHardSpill::set_time_input (const double a) pure virtual
Implemented in SQHardSpill_v1.
virtual void SQHardSpill::set_time_map (const double a) pure virtual
Implemented in SQHardSpill_v1.
virtual void SQHardSpill::set_time_output (const double a) pure virtual
Implemented in SQHardSpill_v1.
Referenced by Fun4AllEVIOInputManager::run().
virtual void SQHardSpill::set_time_subsys (const double a) pure virtual
Implemented in SQHardSpill_v1.
Referenced by Fun4AllEVIOInputManager::run().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHardSpill.h