E1039 Software: halfFunction< T > Class Template Reference
halfFunction< T > Class Template Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/Half/halfFunction.h>
Public Member Functions
template<class Function >
halfFunction (Function f, half domainMin=-HALF_MAX, half domainMax=HALF_MAX, T defaultValue=0, T posInfValue=0, T negInfValue=0, T nanValue=0)
T operator() (half x) const
Private Attributes
T _lut [1<< 16]
Detailed Description
template<class T>
class halfFunction< T >
Definition at line 91 of file halfFunction.h.
Constructor & Destructor Documentation
halfFunction()
template<class T > template<class Function > halfFunction< T >::halfFunction (Function f, half domainMin = -HALF_MAX, half domainMax = HALF_MAX, T defaultValue = 0, T posInfValue = 0, T negInfValue = 0, T nanValue = 0)
Definition at line 126 of file halfFunction.h.
References halfFunction< T >::_lut, half::isInfinity(), half::isNan(), half::isNegative(), and half::setBits().
Member Function Documentation
operator()()
template<class T > T halfFunction< T >::operator() (half x) const inline
Definition at line 153 of file halfFunction.h.
References halfFunction< T >::_lut, and half::bits().
Member Data Documentation
_lut
template<class T > T halfFunction< T >::_lut[1<< 16] private
Definition at line 116 of file halfFunction.h.
Referenced by halfFunction< T >::halfFunction(), and halfFunction< T >::operator()().
The documentation for this class was generated from the following file:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/Half/halfFunction.h