Class Reference for E1039 Core & Analysis Software: SQScaler_v1 Class Reference
SQScaler_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQScaler_v1.h>
Public Member Functions
SQScaler_v1 ()
virtual ~SQScaler_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQScaler * Clone () const
Use Clone() or clone()??
PHObject * clone () const
Use Clone() or clone()??
virtual ScalerType_t get_type () const
Return 'BOS' or 'EOS' according to the timing when this channel was read out.
virtual void set_type (const ScalerType_t a)
virtual std::string get_name () const
Return the name of this scaler channel.
virtual void set_name (const std::string a)
virtual int get_count () const
Return the count of this scaler channel.
virtual void set_count (const int a)
Public Member Functions inherited from SQScaler
virtual ~SQScaler ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from SQScaler
enum ScalerType_t { UNDEF = -1 , BOS = 0 , EOS = 1 }
Protected Member Functions inherited from SQScaler
SQScaler ()
Detailed Description
Definition at line 10 of file SQScaler_v1.h.
Constructor & Destructor Documentation
SQScaler_v1()
SQScaler_v1::SQScaler_v1 ()
Definition at line 15 of file SQScaler_v1.cxx.
Referenced by Clone(), clone(), and Reset().
~SQScaler_v1()
virtual SQScaler_v1::~SQScaler_v1 () inline virtual
Definition at line 13 of file SQScaler_v1.h.
Member Function Documentation
Clone()
SQScaler* SQScaler_v1::Clone () const inline virtual
Use Clone() or clone()??
Reimplemented from SQScaler.
Definition at line 19 of file SQScaler_v1.h.
References SQScaler_v1().
clone()
PHObject* SQScaler_v1::clone () const inline virtual
Use Clone() or clone()??
Reimplemented from SQScaler.
Definition at line 20 of file SQScaler_v1.h.
References SQScaler_v1().
get_count()
virtual int SQScaler_v1::get_count () const inline virtual
Return the count of this scaler channel.
Reimplemented from SQScaler.
Definition at line 28 of file SQScaler_v1.h.
Referenced by identify().
get_name()
virtual std::string SQScaler_v1::get_name (void) const inline virtual
Return the name of this scaler channel.
Reimplemented from SQScaler.
Definition at line 25 of file SQScaler_v1.h.
Referenced by identify().
get_type()
virtual ScalerType_t SQScaler_v1::get_type () const inline virtual
Return 'BOS' or 'EOS' according to the timing when this channel was read out.
Reimplemented from SQScaler.
Definition at line 22 of file SQScaler_v1.h.
Referenced by identify().
identify()
void SQScaler_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQScaler.
Definition at line 18 of file SQScaler_v1.cxx.
References get_count(), get_name(), and get_type().
isValid()
int SQScaler_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQScaler.
Definition at line 27 of file SQScaler_v1.cxx.
References SQScaler::UNDEF.
Reset()
void SQScaler_v1::Reset () inline virtual
Clear Event.
Reimplemented from SQScaler.
Definition at line 17 of file SQScaler_v1.h.
References SQScaler_v1().
set_count()
virtual void SQScaler_v1::set_count (const int a) inline virtual
Reimplemented from SQScaler.
Definition at line 29 of file SQScaler_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_name()
virtual void SQScaler_v1::set_name (const std::string a) inline virtual
Reimplemented from SQScaler.
Definition at line 26 of file SQScaler_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_type()
virtual void SQScaler_v1::set_type (const ScalerType_t a) inline virtual
Reimplemented from SQScaler.
Definition at line 23 of file SQScaler_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQScaler_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQScaler_v1.cxx