SeaQuest Offline Software: TriggerAnalyzer Class Reference
TriggerAnalyzer Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/TriggerAnalyzer.h>
Public Member Functions
TriggerAnalyzer ()
~TriggerAnalyzer ()
bool init (std::string fileName, double cut_td=0., double cut_gun=1E8)
bool init ()
void makeRoadPairs ()
bool acceptEvent (TriggerRoad &p_road, TriggerRoad &m_road)
bool acceptEvent (int nHits, int detectorIDs[], int elementIDs[])
bool acceptEvent (SRawEvent *rawEvent, int mode=USE_TRIGGER_HIT)
void trimEvent (SRawEvent *rawEvent, std::list< Hit > &hitlist, int mode=USE_TRIGGER_HIT)
std::map< int, TriggerRoad > & getRoadsAll (int charge)
std::map< int, TriggerRoad > & getRoadsEnabled (int charge)
std::map< int, TriggerRoad > & getRoadsDisabled (int charge)
std::list< TriggerRoad > & getRoadsFound (int charge)
int getNRoadsPosTop ()
int getNRoadsPosBot ()
int getNRoadsNegTop ()
int getNRoadsNegBot ()
void buildTriggerTree ()
bool buildData (int nHits, int detectorIDs[], int elementIDs[])
void search (TNode *root, DataMatrix &data, int level, int charge)
void print (int charge)
void clear (int charge)
void printTree (TNode *root)
void clearTree (TNode *root)
void printRoadFound ()
void printData (DataMatrix &data)
void outputEnabled ()
Private Attributes
GeomSvc * p_geomSvc
std::map< int, TriggerRoad > roads [2]
std::map< int, TriggerRoad > roads_enabled [2]
std::map< int, TriggerRoad > roads_disabled [2]
int nRoads [2][2]
std::list< Trigger > triggers
DataMatrix data
TNode * root [2]
std::list< TriggerRoad > roads_found [2]
std::list< int > roads_temp
std::vector< int > detectorIDs_trigger
Detailed Description
Definition at line 35 of file TriggerAnalyzer.h.
Constructor & Destructor Documentation
TriggerAnalyzer::TriggerAnalyzer ()
Definition at line 26 of file TriggerAnalyzer.cxx.
References detectorIDs_trigger, GeomSvc::getDetectorIDs(), GeomSvc::instance(), p_geomSvc, and root.
TriggerAnalyzer::~TriggerAnalyzer ()
Definition at line 43 of file TriggerAnalyzer.cxx.
References clear().
Member Function Documentation
bool TriggerAnalyzer::acceptEvent (TriggerRoad & p_road, TriggerRoad & m_road)
Definition at line 216 of file TriggerAnalyzer.cxx.
References TriggerRoad::getRoadID(), and roads_enabled.
Referenced by acceptEvent(), MySQLSvc::getEvent(), main(), and trimEvent().
bool TriggerAnalyzer::acceptEvent (int nHits, int detectorIDs[], int elementIDs[])
Definition at line 306 of file TriggerAnalyzer.cxx.
References buildData(), data, nRoads, roads_enabled, roads_found, roads_temp, root, search(), and triggers.
bool TriggerAnalyzer::acceptEvent (SRawEvent * rawEvent, int mode = USE_TRIGGER_HIT)
Definition at line 270 of file TriggerAnalyzer.cxx.
References acceptEvent(), SRawEvent::getAllHits(), SRawEvent::getTriggerHits(), nChamberPlanes, nHodoPlanes, USE_HIT, and USE_TRIGGER_HIT.
bool TriggerAnalyzer::buildData (int nHits, int detectorIDs[], int elementIDs[])
Definition at line 224 of file TriggerAnalyzer.cxx.
References data, GeomSvc::getDetectorName(), GeomSvc::instance(), and p_geomSvc.
Referenced by acceptEvent().
void TriggerAnalyzer::buildTriggerTree ()
Definition at line 425 of file TriggerAnalyzer.cxx.
References TNode::add(), TNode::children, roads_enabled, and root.
Referenced by EventReducer::EventReducer(), MySQLSvc::initReader(), and main().
void TriggerAnalyzer::clear (int charge) inline
Definition at line 78 of file TriggerAnalyzer.h.
References clearTree(), roads_temp, and root.
Referenced by ~TriggerAnalyzer().
void TriggerAnalyzer::clearTree (TNode * root)
Definition at line 409 of file TriggerAnalyzer.cxx.
References TNode::children, and root.
Referenced by clear(), and printTree().
int TriggerAnalyzer::getNRoadsNegBot () inline
Definition at line 65 of file TriggerAnalyzer.h.
References nRoads.
Referenced by MySQLSvc::getEvent(), main(), and trimEvent().
int TriggerAnalyzer::getNRoadsNegTop () inline
Definition at line 64 of file TriggerAnalyzer.h.
References nRoads.
Referenced by MySQLSvc::getEvent(), main(), and trimEvent().
int TriggerAnalyzer::getNRoadsPosBot () inline
Definition at line 63 of file TriggerAnalyzer.h.
References nRoads.
Referenced by MySQLSvc::getEvent(), main(), and trimEvent().
int TriggerAnalyzer::getNRoadsPosTop () inline
Definition at line 62 of file TriggerAnalyzer.h.
References nRoads.
Referenced by MySQLSvc::getEvent(), main(), and trimEvent().
std::map<int, TriggerRoad>& TriggerAnalyzer::getRoadsAll (int charge) inline
Definition at line 56 of file TriggerAnalyzer.h.
References roads.
std::map<int, TriggerRoad>& TriggerAnalyzer::getRoadsDisabled (int charge) inline
Definition at line 58 of file TriggerAnalyzer.h.
References roads_disabled.
std::map<int, TriggerRoad>& TriggerAnalyzer::getRoadsEnabled (int charge) inline
Definition at line 57 of file TriggerAnalyzer.h.
References roads_enabled.
std::list<TriggerRoad>& TriggerAnalyzer::getRoadsFound (int charge) inline
Definition at line 59 of file TriggerAnalyzer.h.
References roads_found.
Referenced by main().
bool TriggerAnalyzer::init (std::string fileName, double cut_td = 0., double cut_gun = 1E8)
Definition at line 119 of file TriggerAnalyzer.cxx.
References TriggerRoad::clear(), dataFile, TriggerRoad::getRoadID(), TriggerRoad::isValid(), makeRoadPairs(), and roads.
Referenced by EventReducer::EventReducer(), MySQLSvc::initReader(), and main().
bool TriggerAnalyzer::init ()
Definition at line 49 of file TriggerAnalyzer.cxx.
References TriggerRoad::addElement(), convertRTCurve::fin, GeomSvc::getDetectorID(), TriggerRoad::getRoadID(), TriggerRoad::groupID, JobOptsSvc::instance(), makeRoadPairs(), p_geomSvc, TriggerRoad::roadID, and roads_enabled.
void TriggerAnalyzer::makeRoadPairs ()
Definition at line 193 of file TriggerAnalyzer.cxx.
References triggers.
Referenced by init().
void TriggerAnalyzer::outputEnabled ()
Definition at line 486 of file TriggerAnalyzer.cxx.
References roads_enabled, and triggers.
void TriggerAnalyzer::print (int charge) inline
Definition at line 77 of file TriggerAnalyzer.h.
References printTree(), roads_temp, and root.
void TriggerAnalyzer::printData (DataMatrix & data)
Definition at line 473 of file TriggerAnalyzer.cxx.
void TriggerAnalyzer::printRoadFound ()
Definition at line 463 of file TriggerAnalyzer.cxx.
References roads_temp.
Referenced by printTree().
void TriggerAnalyzer::printTree (TNode * root)
Definition at line 389 of file TriggerAnalyzer.cxx.
References TNode::children, clearTree(), printRoadFound(), roads_temp, and TNode::uniqueID.
Referenced by print().
void TriggerAnalyzer::search (TNode * root, DataMatrix & data, int level, int charge)
Definition at line 368 of file TriggerAnalyzer.cxx.
References TNode::children, TriggerRoad::getRoadID(), roads_enabled, roads_found, roads_temp, and TNode::uniqueID.
Referenced by acceptEvent().
void TriggerAnalyzer::trimEvent (SRawEvent * rawEvent, std::list< Hit > & hitlist, int mode = USE_TRIGGER_HIT)
Definition at line 526 of file TriggerAnalyzer.cxx.
References acceptEvent(), Hit::detectorID, Hit::driftDistance, Hit::elementID, GeomSvc::getMeasurement(), getNRoadsNegBot(), getNRoadsNegTop(), getNRoadsPosBot(), getNRoadsPosTop(), Hit::index, nRoads, p_geomSvc, Hit::pos, roads_found, Hit::setInTime(), SRawEvent::setNRoads(), SRawEvent::setTriggerEmu(), Hit::setTriggerMask(), and Hit::tdcTime.
Referenced by EventReducer::reduceEvent().
Member Data Documentation
DataMatrix TriggerAnalyzer::data private
Definition at line 105 of file TriggerAnalyzer.h.
Referenced by acceptEvent(), and buildData().
std::vector<int> TriggerAnalyzer::detectorIDs_trigger private
Definition at line 117 of file TriggerAnalyzer.h.
Referenced by TriggerAnalyzer().
int TriggerAnalyzer::nRoads[2][2] private
Definition at line 99 of file TriggerAnalyzer.h.
Referenced by acceptEvent(), getNRoadsNegBot(), getNRoadsNegTop(), getNRoadsPosBot(), getNRoadsPosTop(), and trimEvent().
GeomSvc* TriggerAnalyzer::p_geomSvc private
Definition at line 91 of file TriggerAnalyzer.h.
Referenced by buildData(), init(), TriggerAnalyzer(), and trimEvent().
std::map<int, TriggerRoad> TriggerAnalyzer::roads[2] private
Definition at line 94 of file TriggerAnalyzer.h.
Referenced by getRoadsAll(), and init().
std::map<int, TriggerRoad> TriggerAnalyzer::roads_disabled[2] private
Definition at line 96 of file TriggerAnalyzer.h.
Referenced by getRoadsDisabled().
std::map<int, TriggerRoad> TriggerAnalyzer::roads_enabled[2] private
Definition at line 95 of file TriggerAnalyzer.h.
Referenced by acceptEvent(), buildTriggerTree(), getRoadsEnabled(), init(), outputEnabled(), and search().
std::list<TriggerRoad> TriggerAnalyzer::roads_found[2] private
Definition at line 111 of file TriggerAnalyzer.h.
Referenced by acceptEvent(), getRoadsFound(), search(), and trimEvent().
std::list<int> TriggerAnalyzer::roads_temp private
Definition at line 114 of file TriggerAnalyzer.h.
Referenced by acceptEvent(), clear(), print(), printRoadFound(), printTree(), and search().
TNode* TriggerAnalyzer::root[2] private
Definition at line 108 of file TriggerAnalyzer.h.
Referenced by acceptEvent(), buildTriggerTree(), clear(), clearTree(), print(), and TriggerAnalyzer().
std::list<Trigger> TriggerAnalyzer::triggers private
Definition at line 102 of file TriggerAnalyzer.h.
Referenced by acceptEvent(), makeRoadPairs(), and outputEnabled().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/TriggerAnalyzer.h
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/src/TriggerAnalyzer.cxx