Class Reference for E1039 Core & Analysis Software: Fun4AllSRawEventOutputManagerV2 Class Reference
Fun4AllSRawEventOutputManagerV2 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaCustomFile/src/Fun4AllSRawEventOutputManagerV2.h>
Public Member Functions
Fun4AllSRawEventOutputManagerV2 (const std::string &myname="SRAWEVENTOUT", const std::string &file_name="srawevent.root")
virtual ~Fun4AllSRawEventOutputManagerV2 ()
void SetTreeName (const std::string name)
void SetBranchName (const std::string name)
virtual int Write (PHCompositeNode *startNode)
write starting from given node
Public Member Functions inherited from Fun4AllOutputManager
virtual ~Fun4AllOutputManager ()
destructor
virtual void Print (const std::string &what="ALL") const
print method (dump event selector)
virtual int AddNode (const std::string &)
add a node in outputmanager
virtual int StripNode (const std::string &)
not write a node in outputmanager
virtual int AddEventSelector (const std::string &recomodule)
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
virtual int outfileopen (const std::string &)
opens output file
virtual int RemoveNode (const std::string &)
removes a node from outputmanager
int WriteGeneric (PHCompositeNode *startNode)
Common method, called before calling virtual Write.
virtual int WriteNode (PHCompositeNode *)
write specified node
virtual std::vector< std::string > * EventSelector ()
retrieves pointer to vector of event selector module names
virtual std::vector< unsigned > * RecoModuleIndex ()
retrieves pointer to vector of event selector module ids
virtual int DoNotWriteEvent (std::vector< int > *retcodes) const
decides if event is to be written or not
virtual size_t EventsWritten () const
get number of Events
virtual std::string OutFileName () const
get output file name
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
void OpenFile ()
void CloseFile ()
Protected Member Functions inherited from Fun4AllOutputManager
Fun4AllOutputManager (const std::string &myname)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from Fun4AllOutputManager
size_t nEvents
Number of Events.
std::vector< std::string > EventSelectors
vector of event selectors modules
std::vector< unsigned > recomoduleindex
vector of associated module indexes
std::string outfilename
output file name
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 14 of file Fun4AllSRawEventOutputManagerV2.h.
Constructor & Destructor Documentation
Fun4AllSRawEventOutputManagerV2()
Fun4AllSRawEventOutputManagerV2::Fun4AllSRawEventOutputManagerV2 (const std::string & myname = "SRAWEVENTOUT", const std::string & file_name = "srawevent.root")
Definition at line 21 of file Fun4AllSRawEventOutputManagerV2.cc.
~Fun4AllSRawEventOutputManagerV2()
Fun4AllSRawEventOutputManagerV2::~Fun4AllSRawEventOutputManagerV2 () virtual
Definition at line 37 of file Fun4AllSRawEventOutputManagerV2.cc.
References CloseFile().
Member Function Documentation
CloseFile()
void Fun4AllSRawEventOutputManagerV2::CloseFile () protected
Definition at line 78 of file Fun4AllSRawEventOutputManagerV2.cc.
References Fun4AllBase::Verbosity().
Referenced by ~Fun4AllSRawEventOutputManagerV2().
OpenFile()
void Fun4AllSRawEventOutputManagerV2::OpenFile () protected
Definition at line 65 of file Fun4AllSRawEventOutputManagerV2.cc.
References PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Write().
SetBranchName()
void Fun4AllSRawEventOutputManagerV2::SetBranchName (const std::string name) inline
Definition at line 33 of file Fun4AllSRawEventOutputManagerV2.h.
SetTreeName()
void Fun4AllSRawEventOutputManagerV2::SetTreeName (const std::string name) inline
Definition at line 32 of file Fun4AllSRawEventOutputManagerV2.h.
Write()
int Fun4AllSRawEventOutputManagerV2::Write (PHCompositeNode *) virtual
write starting from given node
Reimplemented from Fun4AllOutputManager.
Definition at line 43 of file Fun4AllSRawEventOutputManagerV2.cc.
References SQSpillMap::get(), SQEvent::get_spill_id(), OpenFile(), PHWHERE, UtilSRawEvent::SetEvent(), UtilSRawEvent::SetHit(), UtilSRawEvent::SetSpill(), and UtilSRawEvent::SetTriggerHit().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaCustomFile/src/Fun4AllSRawEventOutputManagerV2.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaCustomFile/src/Fun4AllSRawEventOutputManagerV2.cc