Class Reference for E1039 Core & Analysis Software: GenRoadset Class Reference
GenRoadset Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/GenRoadset.h>
Public Member Functions
GenRoadset (const std::string label="gen_rs")
virtual ~GenRoadset ()
void SetMap (AnaSignal *ana_signal)
void SymmetrizeRoads ()
void GenerateRoadSetBySignal (const double frac_cut, const std::string rs_id)
void GenerateRoadSetByFoM (const double frac_cut, const std::string rs_id)
void GenerateSymmetricRoadSetByFoM (const double frac_cut, const std::string rs_id)
Public Member Functions inherited from AnaBase
virtual ~AnaBase ()
virtual void SetInputTreeName (const std::string name)
virtual void SetInputBranchName (const std::string name)
virtual void Init ()
virtual void Analyze ()
virtual void End ()
virtual void ReadEventsFromFileList (const char *fn_list, const int n_max=0)
virtual void ReadEvents (const char *fname)
Protected Member Functions
void DisableRoadsByWeightFraction (RoadList *road_list, const double frac)
void DisableRoadsByFoM (RoadList *road_list, const double frac)
int FlipRoadLeftRight (const int road)
int FlipRoadTopBottom (const int road)
Protected Member Functions inherited from AnaBase
AnaBase (const std::string label)
virtual void ProcessOneEvent ()
Protected Attributes
RoadMap * m_map_pos_top
RoadMap * m_map_pos_bot
RoadMap * m_map_neg_top
RoadMap * m_map_neg_bot
RoadList m_list_pos_top
RoadList m_list_pos_bot
RoadList m_list_neg_top
RoadList m_list_neg_bot
Protected Attributes inherited from AnaBase
std::string m_label
std::string m_tree_name
std::string m_branch_name
std::string m_dir_out
std::ofstream m_ofs
Detailed Description
Definition at line 8 of file GenRoadset.h.
Constructor & Destructor Documentation
GenRoadset()
GenRoadset::GenRoadset (const std::string label = "gen_rs")
Definition at line 10 of file GenRoadset.cc.
References m_list_neg_bot, m_list_neg_top, m_list_pos_bot, m_list_pos_top, and RoadListBase::SetPNTB().
~GenRoadset()
GenRoadset::~GenRoadset () virtual
Definition at line 24 of file GenRoadset.cc.
Member Function Documentation
DisableRoadsByFoM()
void GenRoadset::DisableRoadsByFoM (RoadList * road_list, const double frac) protected
Definition at line 172 of file GenRoadset.cc.
References RoadList::Get(), RoadInfo::GetFoM(), RoadListBase::GetPosNegStr(), RoadListBase::GetTopBotStr(), AnaBase::m_ofs, UtilRoad::PrintList(), RoadInfo::SetOnOff(), RoadList::Size(), and RoadList::SortByFoM().
Referenced by GenerateRoadSetByFoM().
DisableRoadsByWeightFraction()
void GenRoadset::DisableRoadsByWeightFraction (RoadList * road_list, const double frac) protected
Definition at line 144 of file GenRoadset.cc.
References RoadList::Get(), RoadListBase::GetPosNegStr(), RoadListBase::GetTopBotStr(), RoadInfo::GetWeight(), AnaBase::m_ofs, UtilRoad::PrintList(), RoadInfo::SetOnOff(), RoadList::Size(), and RoadList::SortBySignal().
Referenced by GenerateRoadSetBySignal().
FlipRoadLeftRight()
int GenRoadset::FlipRoadLeftRight (const int road) protected
Definition at line 200 of file GenRoadset.cc.
References UtilTrigger::Hodo2Road(), and UtilTrigger::Road2Hodo().
Referenced by GenerateSymmetricRoadSetByFoM(), and SymmetrizeRoads().
FlipRoadTopBottom()
int GenRoadset::FlipRoadTopBottom (const int road) protected
Definition at line 211 of file GenRoadset.cc.
References UtilTrigger::Hodo2Road(), and UtilTrigger::Road2Hodo().
Referenced by GenerateSymmetricRoadSetByFoM(), and SymmetrizeRoads().
GenerateRoadSetByFoM()
void GenRoadset::GenerateRoadSetByFoM (const double frac_cut, const std::string rs_id)
Definition at line 52 of file GenRoadset.cc.
References DisableRoadsByFoM(), m_list_neg_bot, m_list_neg_top, m_list_pos_bot, m_list_pos_top, m_map_neg_bot, m_map_neg_top, m_map_pos_bot, m_map_pos_top, and UtilRoad::WriteToFile().
GenerateRoadSetBySignal()
void GenRoadset::GenerateRoadSetBySignal (const double frac_cut, const std::string rs_id)
Definition at line 42 of file GenRoadset.cc.
References DisableRoadsByWeightFraction(), m_list_neg_bot, m_list_neg_top, m_list_pos_bot, m_list_pos_top, m_map_neg_bot, m_map_neg_top, m_map_pos_bot, m_map_pos_top, and UtilRoad::WriteToFile().
GenerateSymmetricRoadSetByFoM()
void GenRoadset::GenerateSymmetricRoadSetByFoM (const double frac_cut, const std::string rs_id)
Definition at line 62 of file GenRoadset.cc.
References RoadMap::Find(), FlipRoadLeftRight(), FlipRoadTopBottom(), RoadList::Get(), RoadInfo::GetFoM(), RoadInfo::GetOnOff(), RoadListBase::GetPosNegStr(), RoadInfo::GetRoadID(), RoadListBase::GetTopBotStr(), m_list_neg_bot, m_list_neg_top, m_list_pos_bot, m_list_pos_top, m_map_neg_bot, m_map_neg_top, m_map_pos_bot, m_map_pos_top, AnaBase::m_ofs, UtilRoad::PrintList(), RoadInfo::SetOnOff(), RoadList::Size(), RoadList::SortByFoM(), and UtilRoad::WriteToFile().
SetMap()
void GenRoadset::SetMap (AnaSignal * ana_signal)
Definition at line 29 of file GenRoadset.cc.
References RoadList::Add(), AnaSignal::GetRoadMapNegBot(), AnaSignal::GetRoadMapNegTop(), AnaSignal::GetRoadMapPosBot(), AnaSignal::GetRoadMapPosTop(), m_list_neg_bot, m_list_neg_top, m_list_pos_bot, m_list_pos_top, m_map_neg_bot, m_map_neg_top, m_map_pos_bot, and m_map_pos_top.
SymmetrizeRoads()
void GenRoadset::SymmetrizeRoads ()
Keep only the roads that are found in the four groups (i.e. count = 4).
Definition at line 218 of file GenRoadset.cc.
References FlipRoadLeftRight(), FlipRoadTopBottom(), RoadList::Get(), RoadInfo::GetRoadID(), m_list_neg_bot, m_list_neg_top, m_list_pos_bot, m_list_pos_top, RoadInfo::SetOnOff(), and RoadList::Size().
Member Data Documentation
m_list_neg_bot
RoadList GenRoadset::m_list_neg_bot protected
Definition at line 18 of file GenRoadset.h.
Referenced by GenerateRoadSetByFoM(), GenerateRoadSetBySignal(), GenerateSymmetricRoadSetByFoM(), GenRoadset(), SetMap(), and SymmetrizeRoads().
m_list_neg_top
RoadList GenRoadset::m_list_neg_top protected
Definition at line 17 of file GenRoadset.h.
Referenced by GenerateRoadSetByFoM(), GenerateRoadSetBySignal(), GenerateSymmetricRoadSetByFoM(), GenRoadset(), SetMap(), and SymmetrizeRoads().
m_list_pos_bot
RoadList GenRoadset::m_list_pos_bot protected
Definition at line 16 of file GenRoadset.h.
Referenced by GenerateRoadSetByFoM(), GenerateRoadSetBySignal(), GenerateSymmetricRoadSetByFoM(), GenRoadset(), SetMap(), and SymmetrizeRoads().
m_list_pos_top
RoadList GenRoadset::m_list_pos_top protected
Definition at line 15 of file GenRoadset.h.
Referenced by GenerateRoadSetByFoM(), GenerateRoadSetBySignal(), GenerateSymmetricRoadSetByFoM(), GenRoadset(), SetMap(), and SymmetrizeRoads().
m_map_neg_bot
RoadMap* GenRoadset::m_map_neg_bot protected
Definition at line 13 of file GenRoadset.h.
Referenced by GenerateRoadSetByFoM(), GenerateRoadSetBySignal(), GenerateSymmetricRoadSetByFoM(), and SetMap().
m_map_neg_top
RoadMap* GenRoadset::m_map_neg_top protected
Definition at line 12 of file GenRoadset.h.
Referenced by GenerateRoadSetByFoM(), GenerateRoadSetBySignal(), GenerateSymmetricRoadSetByFoM(), and SetMap().
m_map_pos_bot
RoadMap* GenRoadset::m_map_pos_bot protected
Definition at line 11 of file GenRoadset.h.
Referenced by GenerateRoadSetByFoM(), GenerateRoadSetBySignal(), GenerateSymmetricRoadSetByFoM(), and SetMap().
m_map_pos_top
RoadMap* GenRoadset::m_map_pos_top protected
Definition at line 10 of file GenRoadset.h.
Referenced by GenerateRoadSetByFoM(), GenerateRoadSetBySignal(), GenerateSymmetricRoadSetByFoM(), and SetMap().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/GenRoadset.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/GenRoadset/src/GenRoadset.cc