Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Display/macro/EventDisp4MainDaqDst.C File Reference
EventDisp4MainDaqDst.C File Reference
#include "G4_SensitiveDetectors.C"
#include "G4_Target.C"
Functions
void InitInput ()
void EventDisp4MainDaqDst (const bool online=true)
Function Documentation
void EventDisp4MainDaqDst (const bool online = true)
Definition at line 17 of file EventDisp4MainDaqDst.C.
References EventDispUI::Init(), InitInput(), and EventDispUI::Run().
void InitInput ()
(width, height, use_fieldmap, use_geofile, field-map name, geo-file name)
Definition at line 25 of file EventDisp4MainDaqDst.C.
References JobOptsSvc::init(), PHEventDisplay::InitRun(), PHG4Reco::InitRun(), JobOptsSvc::instance(), Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), se, PHG4Reco::SetPhysicsList(), SetupSensitiveDetectors(), SetupTarget(), PHG4Reco::SetWorldMaterial(), PHG4Reco::SetWorldShape(), PHG4Reco::SetWorldSizeX(), PHG4Reco::SetWorldSizeY(), PHG4Reco::SetWorldSizeZ(), Fun4AllServer::topNode(), and Fun4AllBase::Verbosity().
Referenced by EventDisp4MainDaqDst().