Class Reference for E1039 Core & Analysis Software: PHG4EtaPhiParameterization Class Reference
PHG4EtaPhiParameterization Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4EtaPhiParameterization.h>
Public Member Functions
PHG4EtaPhiParameterization (unsigned int neta, double minEta, double maxEta, unsigned int nphi, double startPhi, double deltaPhi, double radiusIn, double radiusOut, double centerZ)
virtual ~PHG4EtaPhiParameterization ()
virtual void Print (std::ostream &os=std::cout) const
void ComputeTransformation (const G4int copyNo, G4VPhysicalVolume *physVol) const
void ComputeDimensions (G4Tubs &ring, const G4int copyNo, const G4VPhysicalVolume *physVol) const
int GetIEta (int copyNo) const
int GetIPhi (int copyNo) const
Detailed Description
Definition at line 14 of file PHG4EtaPhiParameterization.h.
Constructor & Destructor Documentation
PHG4EtaPhiParameterization()
PHG4EtaPhiParameterization::PHG4EtaPhiParameterization (unsigned int neta, double minEta, double maxEta, unsigned int nphi, double startPhi, double deltaPhi, double radiusIn, double radiusOut, double centerZ)
Definition at line 13 of file PHG4EtaPhiParameterization.cc.
~PHG4EtaPhiParameterization()
PHG4EtaPhiParameterization::~PHG4EtaPhiParameterization () virtual
Definition at line 83 of file PHG4EtaPhiParameterization.cc.
Member Function Documentation
ComputeDimensions()
void PHG4EtaPhiParameterization::ComputeDimensions (G4Tubs & ring, const G4int copyNo, const G4VPhysicalVolume * physVol) const
Definition at line 114 of file PHG4EtaPhiParameterization.cc.
References GetIEta(), and GetIPhi().
ComputeTransformation()
void PHG4EtaPhiParameterization::ComputeTransformation (const G4int copyNo, G4VPhysicalVolume * physVol) const
Definition at line 105 of file PHG4EtaPhiParameterization.cc.
GetIEta()
int PHG4EtaPhiParameterization::GetIEta (int copyNo) const inline
Definition at line 40 of file PHG4EtaPhiParameterization.h.
Referenced by ComputeDimensions().
GetIPhi()
int PHG4EtaPhiParameterization::GetIPhi (int copyNo) const inline
Definition at line 41 of file PHG4EtaPhiParameterization.h.
Referenced by ComputeDimensions().
Print()
void PHG4EtaPhiParameterization::Print (std::ostream & os = std::cout) const virtual
Definition at line 90 of file PHG4EtaPhiParameterization.cc.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4EtaPhiParameterization.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4EtaPhiParameterization.cc