Class Reference for E1039 Core & Analysis Software: PHG4BlockCellReco Class Reference
PHG4BlockCellReco Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockCellReco.h>
Public Member Functions
PHG4BlockCellReco (const std::string &name="BLOCKRECO")
virtual ~PHG4BlockCellReco ()
int InitRun (PHCompositeNode *topNode)
module initialization
int process_event (PHCompositeNode *topNode)
event processing
int ResetEvent (PHCompositeNode *topNode)
Clean up after each event.
void SetDefaultParameters ()
void Detector (const std::string &d)
void etaxsize (const int i, const double deltaeta, const double deltax)
void checkenergy (const int i=1)
void set_timing_window (const int detid, const double tmin, const double tmax)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHG4ParameterContainerInterface
PHG4ParameterContainerInterface (const std::string &name)
virtual ~PHG4ParameterContainerInterface ()
void set_name (const std::string &name)
void set_double_param (const int id, const std::string &name, const double dval)
double get_double_param (const int id, const std::string &name) const
void set_int_param (const int id, const std::string &name, const int ival)
int get_int_param (const int id, const std::string &name) const
void set_string_param (const int id, const std::string &name, const std::string &sval)
std::string get_string_param (const int id, const std::string &name) const
void UpdateParametersWithMacro ()
void CreateInitialize (const int detid)
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
int ExistDetid (const int detid) const
Protected Member Functions
void set_size (const int i, const double sizeA, const double sizeB, const int what)
int CheckEnergy (PHCompositeNode *topNode)
bool lines_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double *rx, double *ry)
bool line_and_rectangle_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double *rr)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Member Functions inherited from PHG4ParameterContainerInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
const PHG4ParametersContainer * GetParamsContainer ()
PHG4ParametersContainer * GetParamsContainerModify ()
const PHG4Parameters * GetDefaultParameters ()
Static Protected Member Functions
static std::pair< double, double > get_etaphi (const double x, const double y, const double z)
static double get_eta (const double radius, const double z)
Protected Attributes
double sum_energy_g4hit
std::map< int, int > binning
std::map< int, std::pair
< double, double > > cell_size
std::map< int, std::pair
< double, double > > zmin_max
std::map< int, double > xstep
std::map< int, double > etastep
std::map< int, std::pair
< double, double > > tmin_max
std::set< int > implemented_detid
std::string detector
std::string hitnodename
std::string cellnodename
std::string geonodename
std::string seggeonodename
std::map< int, std::pair< int,
int > > n_x_z_bins
PHTimeServer::timer _timer
int chkenergyconservation
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 16 of file PHG4BlockCellReco.h.
Constructor & Destructor Documentation
PHG4BlockCellReco::PHG4BlockCellReco (const std::string & name = "BLOCKRECO")
Definition at line 33 of file PHG4BlockCellReco.cc.
References SetDefaultParameters().
virtual PHG4BlockCellReco::~PHG4BlockCellReco () inline virtual
Definition at line 22 of file PHG4BlockCellReco.h.
Member Function Documentation
void PHG4BlockCellReco::checkenergy (const int i = 1) inline
Definition at line 36 of file PHG4BlockCellReco.h.
References chkenergyconservation.
int PHG4BlockCellReco::CheckEnergy (PHCompositeNode * topNode) protected
Definition at line 709 of file PHG4BlockCellReco.cc.
References cellnodename, PHG4CellContainer::getCells(), Fun4AllBase::Name(), sum_energy_g4hit, and Fun4AllBase::verbosity.
Referenced by process_event().
void PHG4BlockCellReco::Detector (const std::string & d) inline
Definition at line 34 of file PHG4BlockCellReco.h.
References detector.
void PHG4BlockCellReco::etaxsize (const int i, const double deltaeta, const double deltax)
Definition at line 497 of file PHG4BlockCellReco.cc.
References PHG4ParameterContainerInterface::set_double_param().
double PHG4BlockCellReco::get_eta (const double radius, const double z) static protected
Definition at line 538 of file PHG4BlockCellReco.cc.
Referenced by InitRun().
pair< double, double > PHG4BlockCellReco::get_etaphi (const double x, const double y, const double z) static protected
Definition at line 528 of file PHG4BlockCellReco.cc.
Referenced by process_event().
int PHG4BlockCellReco::InitRun (PHCompositeNode * topNode) virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 50 of file PHG4BlockCellReco.cc.
References PHG4BlockCellGeomContainer::AddLayerCellGeom(), PHCompositeNode::addNode(), binning, cell_size, cellnodename, detector, PHG4CellDefs::etaphibinning, etastep, Fun4AllReturnCodes::EVENT_OK, PHG4ParameterContainerInterface::ExistDetid(), PHNodeIterator::findFirst(), geonodename, PHG4BlockGeomContainer::get_begin_end(), PHG4BlockGeom::get_center_x(), PHG4BlockGeom::get_center_y(), PHG4BlockGeom::get_center_z(), PHG4ParameterContainerInterface::get_double_param(), get_eta(), PHG4BlockGeom::get_layer(), PHG4BlockGeom::get_size_x(), PHG4BlockGeom::get_size_y(), PHG4BlockGeom::get_size_z(), PHG4BlockGeom::get_width(), PHG4ParameterContainerInterface::GetParamsContainer(), PHG4ParameterContainerInterface::GetParamsContainerModify(), hitnodename, PHG4BlockCellGeom::identify(), PHG4BlockGeomContainer::identify(), implemented_detid, n_x_z_bins, Fun4AllBase::Name(), PHG4ParametersContainer::Name(), PHG4ParameterContainerInterface::SaveToNodeTree(), seggeonodename, PHG4BlockCellGeom::set_binning(), PHG4BlockCellGeom::set_etabins(), PHG4BlockCellGeom::set_etamin(), PHG4BlockCellGeom::set_etastep(), PHG4BlockCellGeom::set_layer(), PHG4ParametersContainer::set_name(), set_size(), PHG4BlockCellGeom::set_xbins(), PHG4BlockCellGeom::set_xmin(), PHG4BlockCellGeom::set_xstep(), tmin_max, PHG4ParameterContainerInterface::UpdateParametersWithMacro(), Fun4AllBase::verbosity, xstep, and zmin_max.
bool PHG4BlockCellReco::line_and_rectangle_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double * rr) protected
Definition at line 613 of file PHG4BlockCellReco.cc.
References lines_intersect().
Referenced by process_event().
bool PHG4BlockCellReco::lines_intersect (double ax, double ay, double bx, double by, double cx, double cy, double dx, double dy, double * rx, double * ry) protected
Definition at line 553 of file PHG4BlockCellReco.cc.
Referenced by line_and_rectangle_intersect().
int PHG4BlockCellReco::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 248 of file PHG4BlockCellReco.cc.
References _timer, PHG4CellContainer::AddCell(), binning, cellnodename, cellptarray, CheckEnergy(), chkenergyconservation, PHG4CellDefs::etaphibinning, Fun4AllReturnCodes::EVENT_OK, PHG4CellDefs::EtaXsizeBinning::genkey(), PHTimeServer::timer::get(), PHG4BlockCellGeom::get_etabin(), PHG4BlockCellGeom::get_etacenter(), get_etaphi(), PHG4BlockCellGeom::get_etastep(), PHG4BlockCellGeom::get_xbin(), PHG4BlockCellGeom::get_xcenter(), PHG4BlockCellGeom::get_xstep(), PHG4HitContainer::getHits(), PHG4BlockCellGeomContainer::GetLayerCellGeom(), PHG4HitContainer::getLayers(), hitnodename, implemented_detid, line_and_rectangle_intersect(), n_x_z_bins, Fun4AllBase::Name(), PHWHERE, PHG4Hit::prop_light_yield, PHTimer::restart(), seggeonodename, PHTimer::stop(), sum_energy_g4hit, tmin_max, and Fun4AllBase::verbosity.
int PHG4BlockCellReco::ResetEvent (PHCompositeNode *) virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 44 of file PHG4BlockCellReco.cc.
References Fun4AllReturnCodes::EVENT_OK, and sum_energy_g4hit.
void PHG4BlockCellReco::set_size (const int i, const double sizeA, const double sizeB, const int what) protected
Definition at line 513 of file PHG4BlockCellReco.cc.
References binning, and cell_size.
Referenced by InitRun().
void PHG4BlockCellReco::set_timing_window (const int detid, const double tmin, const double tmax)
Definition at line 505 of file PHG4BlockCellReco.cc.
References PHG4ParameterContainerInterface::set_double_param().
void PHG4BlockCellReco::SetDefaultParameters () virtual
Implements PHG4ParameterContainerInterface.
Definition at line 777 of file PHG4BlockCellReco.cc.
References PHG4ParameterContainerInterface::set_default_double_param().
Referenced by PHG4BlockCellReco().
Member Data Documentation
PHTimeServer::timer PHG4BlockCellReco::_timer protected
Definition at line 62 of file PHG4BlockCellReco.h.
Referenced by process_event().
std::map<int, int> PHG4BlockCellReco::binning protected
Definition at line 49 of file PHG4BlockCellReco.h.
Referenced by InitRun(), process_event(), and set_size().
std::map<int, std::pair <double,double> > PHG4BlockCellReco::cell_size protected
Definition at line 50 of file PHG4BlockCellReco.h.
Referenced by InitRun(), and set_size().
std::string PHG4BlockCellReco::cellnodename protected
Definition at line 58 of file PHG4BlockCellReco.h.
Referenced by CheckEnergy(), InitRun(), and process_event().
int PHG4BlockCellReco::chkenergyconservation protected
Definition at line 63 of file PHG4BlockCellReco.h.
Referenced by checkenergy(), and process_event().
std::string PHG4BlockCellReco::detector protected
Definition at line 56 of file PHG4BlockCellReco.h.
Referenced by Detector(), and InitRun().
std::map<int, double> PHG4BlockCellReco::etastep protected
Definition at line 53 of file PHG4BlockCellReco.h.
Referenced by InitRun().
std::string PHG4BlockCellReco::geonodename protected
Definition at line 59 of file PHG4BlockCellReco.h.
Referenced by InitRun().
std::string PHG4BlockCellReco::hitnodename protected
Definition at line 57 of file PHG4BlockCellReco.h.
Referenced by InitRun(), and process_event().
std::set<int> PHG4BlockCellReco::implemented_detid protected
Definition at line 55 of file PHG4BlockCellReco.h.
Referenced by InitRun(), and process_event().
std::map<int, std::pair<int, int> > PHG4BlockCellReco::n_x_z_bins protected
Definition at line 61 of file PHG4BlockCellReco.h.
Referenced by InitRun(), and process_event().
std::string PHG4BlockCellReco::seggeonodename protected
Definition at line 60 of file PHG4BlockCellReco.h.
Referenced by InitRun(), and process_event().
double PHG4BlockCellReco::sum_energy_g4hit protected
Definition at line 48 of file PHG4BlockCellReco.h.
Referenced by CheckEnergy(), process_event(), and ResetEvent().
std::map<int, std::pair<double,double> > PHG4BlockCellReco::tmin_max protected
Definition at line 54 of file PHG4BlockCellReco.h.
Referenced by InitRun(), and process_event().
std::map<int, double> PHG4BlockCellReco::xstep protected
Definition at line 52 of file PHG4BlockCellReco.h.
Referenced by InitRun().
std::map<int, std::pair <double,double> > PHG4BlockCellReco::zmin_max protected
Definition at line 51 of file PHG4BlockCellReco.h.
Referenced by InitRun().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockCellReco.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockCellReco.cc