E1039 Software: MainDaqParser Class Reference
MainDaqParser Class Reference
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/online/decoder_maindaq/MainDaqParser.h>
Public Types
enum SpillType_t { TYPE_BOS = 1, TYPE_EOS = 2 }
Public Member Functions
MainDaqParser ()
~MainDaqParser ()
CodaInputManager * GetCoda ()
int OpenCodaFile (const std::string fname, const long file_size_min=32768, const int sec_wait=15, const int n_wait=40)
bool NextPhysicsEvent (EventData *&ed, SpillData *&sd, RunData *&rd)
int End ()
Public Attributes
DecoParam dec_par
DecoError dec_err
Private Member Functions
int ProcessCodaPrestart (int *words)
int ProcessCodaFee (int *words)
int ProcessCodaFeeBoard (int *words)
int ProcessCodaFeePrescale (int *words)
int ProcessCodaPhysics (int *words)
int ProcessPhysRunDesc (int *words)
int ProcessPhysPrestart (int *words)
int ProcessPhysSlow (int *words)
int ProcessPhysSpillCounter (int *words)
int ProcessPhysBOSEOS (int *words, const int type)
int ProcessPhysFlush (int *words)
int ProcessBoardData (int *words, int idx, int idx_roc_end, int e906flag)
int ProcessBoardScaler (int *words, int j)
int ProcessBoardTriggerBit (int *words, int j)
int ProcessBoardTriggerCount (int *words, int j)
int ProcessBoardFeeQIE (int *words, int j)
int ProcessBoardV1495TDC (int *words, int idx)
int ProcessBoardJyTDC2 (int *words, int idx_begin, int idx_roc_end)
int ProcessBoardStdTriggerBit (int *words, int idx)
int ProcessBoardStdTriggerCount (int *words, int idx)
int ProcessBoardStdFeeQIE (int *words, int idx)
int ProcessBoardStdV1495TDC (int *words, int idx)
int ProcessBoardStdJyTDC2 (int *words, int idx_begin, int idx_roc_end)
int PackOneSpillData ()
int ParseOneSpill ()
void SetEventInfo (EventInfo *evt, const int eventID)
Private Attributes
long m_file_size_min
int m_sec_wait
int m_n_wait
CodaInputManager * coda
RunData run_data
Variables for data storage.
SpillDataMap * list_sd
EventDataMap * list_ed
SpillData * sd_now
EventDataMap * list_ed_now
Detailed Description
Definition at line 8 of file MainDaqParser.h.
Member Enumeration Documentation
enum MainDaqParser::SpillType_t
Enumerator
TYPE_BOS
TYPE_EOS
Definition at line 57 of file MainDaqParser.h.
Constructor & Destructor Documentation
MainDaqParser::MainDaqParser ()
Definition at line 9 of file MainDaqParser.cc.
References coda, list_ed, list_ed_now, list_sd, and sd_now.
MainDaqParser::~MainDaqParser ()
Definition at line 19 of file MainDaqParser.cc.
References coda, list_ed, list_ed_now, and list_sd.
Member Function Documentation
int MainDaqParser::End ()
A function that is called when one input file is finished reading. We might have to parse any remaining Coda events here as we did in the original decoder via CloseOutput(), although such events are most likely useless since their spill info is imcomplete.
Definition at line 125 of file MainDaqParser.cc.
References CodaInputManager::CloseFile(), coda, dec_err, dec_par, DecoError::InitData(), DecoParam::is_online, RunData::n_evt_all, RunData::n_evt_dec, RunData::n_flush_evt, RunData::n_hit, RunData::n_hit_bad, RunData::n_phys_evt, RunData::n_t_hit, RunData::n_t_hit_bad, RunData::n_v1495, RunData::n_v1495_d1ad, RunData::n_v1495_d2ad, RunData::n_v1495_d3ad, NULL, DecoError::PrintData(), run_data, DecoParam::timeEnd, DecoParam::timeStart, and DecoParam::verbose.
Referenced by Fun4AllEVIOInputManager::fileclose().
CodaInputManager* MainDaqParser::GetCoda () inline
Definition at line 65 of file MainDaqParser.h.
References coda.
Referenced by Fun4AllEVIOInputManager::SetOnline().
bool MainDaqParser::NextPhysicsEvent (EventData *& ed, SpillData *& sd, RunData *& rd)
Definition at line 37 of file MainDaqParser.cc.
References coda, CodaInputManager::IsEnded(), list_ed_now, ParseOneSpill(), run_data, and sd_now.
Referenced by Fun4AllEVIOInputManager::run().
int MainDaqParser::OpenCodaFile (const std::string fname, const long file_size_min = 32768, const int sec_wait = 15, const int n_wait = 40)
Definition at line 27 of file MainDaqParser.cc.
References coda, dec_par, DecoParam::fn_in, m_file_size_min, m_n_wait, m_sec_wait, NULL, CodaInputManager::OpenFile(), and DecoParam::timeStart.
Referenced by Fun4AllEVIOInputManager::fileopen().
int MainDaqParser::PackOneSpillData () private
A part (most?) of lines in this loop had better be moved to a SubsysReco module for better function separation.
Run the mapping. It should be done here (after the event selection) since it takes the longest process time per event.
Definition at line 1312 of file MainDaqParser.cc.
References DecoError::AggregateData(), HitData::board, HitData::chan, DecoParam::chan_map_taiwan, DecoParam::chan_map_v1495, dec_err, dec_par, HitData::det, HitData::ele, EventData::event, ChanMapTaiwan::Find(), ChanMapV1495::Find(), DecoParam::is_online, list_ed, list_ed_now, EventData::list_hit, EventData::list_hit_trig, HitData::lvl, RunData::n_evt_all, RunData::n_evt_dec, RunData::n_hit, RunData::n_t_hit, HitData::roc, run_data, DecoParam::runID, DecoParam::sampling, sd_now, DecoError::SetID(), DecoParam::spillID, DecoParam::turn_id_max, and DecoParam::verbose.
Referenced by ProcessPhysBOSEOS().
int MainDaqParser::ParseOneSpill () private
Definition at line 61 of file MainDaqParser.cc.
References DecoParam::at_bos, coda, CODA_EVENT, DecoParam::codaID, dec_par, END_EVENT, FEE_PREFIX, DecoParam::fn_in, CodaInputManager::ForceEnd(), GO_EVENT, CodaInputManager::JumpCodaEvent(), m_file_size_min, m_n_wait, m_sec_wait, CodaInputManager::NextCodaEvent(), CodaInputManager::OpenFile(), PHYSICS_EVENT, PRESTART_EVENT, ProcessCodaFee(), ProcessCodaPhysics(), ProcessCodaPrestart(), and DecoParam::time_wait.
Referenced by NextPhysicsEvent().
int MainDaqParser::ProcessBoardData (int * words, int idx, int idx_roc_end, int e906flag) private
Process the word set of one board.
Parameters
[in] idx The 1st index of the target board (i.e. next to the e906flag).
[in] idx_roc_end The last index of the current ROC (not board). This index itself is not included in the word set of the current ROC, i.e. excluded endpoint.
Returns
The index that points to the e906flag of the next board (not the last word of the current board). Or "-1" in case of word overflow (i.e. N of words/board > N of words/ROC).
The sub-functions called by this function (like "ProcessBoardJyTDC2()") must return the index that points to the e906flag of the next board (not the last word of the current board).
Note #1: Taiwan TDC special case According to the crl file, the Taiwan TDC sets this flag (not 0xe906f018) when the number of flush events received exceeds the max defined in crl (9000). This case is expected to happen about 300 times per spill, since the flush events are sent 9300 times. The decoder stops reading all remaining words of such a Coda event.
Definition at line 673 of file MainDaqParser.cc.
References Abort(), DecoParam::codaID, dec_par, PrintWords(), ProcessBoardFeeQIE(), ProcessBoardJyTDC2(), ProcessBoardScaler(), ProcessBoardStdFeeQIE(), ProcessBoardStdJyTDC2(), ProcessBoardStdTriggerBit(), ProcessBoardStdTriggerCount(), ProcessBoardStdV1495TDC(), ProcessBoardTriggerBit(), ProcessBoardTriggerCount(), ProcessBoardV1495TDC(), and DecoParam::rocID.
Referenced by ProcessPhysBOSEOS(), and ProcessPhysFlush().
int MainDaqParser::ProcessBoardFeeQIE (int * words, int idx) private
Process one QIE event (flag "0xe906f01b").
Parameters
[in] idx The index of word "ID&N" (i.e. next to the e906flag word) of this board.
Returns
The index that points to the e906flag of the next board.
Word format: { 0xe906f01b, ID&N, [0xe906e906], N, {event #1},,, {event #7} }
ID&N = 0xAAAABBBB where AAAA = board ID and BBBB = N of words from "X" to end.
{event #*} ... described inside the function.
The word format is described in QIE_REadout_Format_Description.docx of DocDB 537, although the document is not fully up-to-date.
Known issue. See memo.txt.
Definition at line 806 of file MainDaqParser.cc.
References Abort(), dec_par, EventData::event, get_hex_bits(), EventData::n_qie, EventInfo::rf, EventInfo::rfOnset, DecoParam::runID, SetEventInfo(), EventInfo::sums, EventInfo::triggerCount, DecoParam::turn_id_max, and EventInfo::turnOnset.
Referenced by ProcessBoardData().
int MainDaqParser::ProcessBoardJyTDC2 (int * words, int idx_begin, int idx_roc_end) private
Process a set of words from board "e906flag=0xe906f018".
Parameters
[in] idx_begin The index of word "ID&N" (i.e. next to the e906flag word) of this board.
[in] idx_roc_end The last index of the current ROC (not board).
Returns
The index that points to the e906flag of the next board, i.e. the excluding endpoint of this board.
Word format: { e906flag, ID&N, [0xe906e906], X, {event #1}, {event #2},,, {event #7} }
ID&N = 0x0AAABBBB where AAA = board ID and BBBB = N of words from "X" to end. Actually board ID occupies one hex ".O.." according to Andrew and thus we can make stricter check.
{event #*} = { header, hit #1, hit #2,,, hit #n, eventID }
Description by Michelle(?): event block = block of data with specific number of events (words), for TDCs
xxx xxx xxx flag TDCheader dummyFlag totalNwords(evtLength) evtHeader xxx xxx xxx xxx xxx xxx... evtID evtHeader xxx xxx xxx xxx xxx xxx... evtID evtHeader xxx xxx xxx xxx xxx xxx... evtID TDCheader totalNwords(evtLength) evtHeader xxx xxx xxx xxx xxx xxx... evtID evtHeader xxx xxx xxx xxx xxx xxx... evtID
Index range of events: idx_events_begin <= idx < idx_events_end
The data of one physics event are complete. Let's insert hits to the storage.
Definition at line 993 of file MainDaqParser.cc.
References Abort(), DecoError::AddTdcError(), HitData::board, HitData::chan, DecoParam::codaID, dec_err, dec_par, DecoError::DIRTY_FINISH, HitData::event, EventData::event, DecoError::EVT_ID_ONLY, get_bin_bit(), get_bin_bits(), get_hex_bit(), get_hex_bits(), DecoParam::hitID, HitData::id, EventData::list_hit, DecoError::MULTIPLE_HEADER, RunData::n_hit_bad, EventData::n_tdc, HitData::roc, DecoParam::rocID, run_data, SetEventInfo(), DecoError::START_NOT_RISE, DecoError::START_WO_STOP, HitData::time, DecoError::WORD_ONLY89, and DecoError::WORD_OVERFLOW.
Referenced by ProcessBoardData().
int MainDaqParser::ProcessBoardScaler (int * words, int j) private
Definition at line 700 of file MainDaqParser.cc.
References ScalerData::board, ScalerData::chan, DecoParam::chan_map_scaler, ScalerData::coda, DecoParam::codaID, dec_par, ChanMapScaler::Find(), SpillData::list_scaler, SpillData::n_scaler, ScalerData::name, ScalerData::roc, DecoParam::rocID, DecoParam::spillID, DecoParam::spillType, ScalerData::type, ScalerData::value, and DecoParam::verbose.
Referenced by ProcessBoardData().
int MainDaqParser::ProcessBoardStdFeeQIE (int * words, int idx) private
Process one QIE event in standard physics event.
Parameters
[in] idx The index of word "ID&N" (i.e. next to the e906flag word) of this board.
Returns
The index that points to the e906flag of the next board.
Definition at line 1137 of file MainDaqParser.cc.
References Abort(), dec_par, EventData::event, DecoParam::eventIDstd, get_hex_bits(), EventData::n_qie, EventInfo::rf, EventInfo::rfOnset, DecoParam::runID, EventInfo::sums, EventInfo::triggerCount, DecoParam::turn_id_max, and EventInfo::turnOnset.
Referenced by ProcessBoardData().
int MainDaqParser::ProcessBoardStdJyTDC2 (int * words, int idx_begin, int idx_roc_end) private
Process a set of words from the Taiwan-TDC board in standard-physics event.
Parameters
[in] idx_begin The index of word "ID&N" (i.e. next to the e906flag word) of this board.
[in] idx_roc_end The last index of the current ROC (not board).
Returns
The index that points to the e906flag of the next board, i.e. the excluding endpoint of this board.
Definition at line 1257 of file MainDaqParser.cc.
References HitData::board, HitData::chan, dec_par, HitData::event, DecoParam::eventIDstd, get_bin_bit(), get_bin_bits(), get_hex_bit(), get_hex_bits(), DecoParam::hitID, HitData::id, EventData::list_hit, EventData::n_tdc, HitData::roc, DecoParam::rocID, and HitData::time.
Referenced by ProcessBoardData().
int MainDaqParser::ProcessBoardStdTriggerBit (int * words, int idx) private
Definition at line 1098 of file MainDaqParser.cc.
References dec_par, EventData::event, DecoParam::eventIDstd, get_bin_bit(), EventInfo::MATRIX, EventData::n_trig_b, EventInfo::NIM, and EventInfo::trigger_bits.
Referenced by ProcessBoardData().
int MainDaqParser::ProcessBoardStdTriggerCount (int * words, int idx) private
Definition at line 1115 of file MainDaqParser.cc.
References EventInfo::AfterInhMATRIX, dec_par, EventData::event, DecoParam::eventIDstd, EventData::n_trig_c, and EventInfo::RawMATRIX.
Referenced by ProcessBoardData().
int MainDaqParser::ProcessBoardStdV1495TDC (int * words, int idx) private
Process one v1495-TDC event in standard physics event.
Definition at line 1194 of file MainDaqParser.cc.
References HitData::board, HitData::chan, dec_par, HitData::event, EventData::event, DecoParam::eventIDstd, EventInfo::flag_v1495, get_bin_bit(), get_hex_bits(), DecoParam::hitID, HitData::id, EventData::list_hit_trig, RunData::n_v1495, EventData::n_v1495, RunData::n_v1495_d1ad, RunData::n_v1495_d2ad, RunData::n_v1495_d3ad, HitData::roc, DecoParam::rocID, run_data, and HitData::time.
Referenced by ProcessBoardData().
int MainDaqParser::ProcessBoardTriggerBit (int * words, int j) private
Definition at line 730 of file MainDaqParser.cc.
References Abort(), EventData::event, get_bin_bit(), EventInfo::MATRIX, EventData::n_trig_b, EventInfo::NIM, PrintWords(), SetEventInfo(), and EventInfo::trigger_bits.
Referenced by ProcessBoardData().
int MainDaqParser::ProcessBoardTriggerCount (int * words, int j) private
Definition at line 763 of file MainDaqParser.cc.
References Abort(), EventInfo::AfterInhMATRIX, EventData::event, EventData::n_trig_c, PrintWords(), EventInfo::RawMATRIX, and SetEventInfo().
Referenced by ProcessBoardData().
int MainDaqParser::ProcessBoardV1495TDC (int * words, int idx) private
Process one v1495-TDC event.
Word format: { 0xe906f005, boardID(?), N of words, {event #1},,, {event #7} }
{event #*} = { hit #1,,, hit #n, header, stop_hit, eventID_CPU, eventID_FPGA_high, eventID_FPGA_low }
This format was extracted by Kenichi from test file (scaler_6146.dat) on 2017-Jan-06.
< Stored in CPU
The two words (idx+3 & idx+4) mean event ID stored in FPGA, but is temporarily fixed to "0" as of 2017-Jan-11. Thus not checked for now.
0xxxyy where xx is the channel and yy is the channel time
Definition at line 905 of file MainDaqParser.cc.
References Abort(), HitData::board, HitData::chan, dec_par, HitData::event, EventData::event, EventInfo::flag_v1495, get_hex_bits(), DecoParam::hitID, HitData::id, EventData::list_hit_trig, RunData::n_v1495, EventData::n_v1495, RunData::n_v1495_d2ad, RunData::n_v1495_d3ad, HitData::roc, DecoParam::rocID, run_data, SetEventInfo(), and HitData::time.
Referenced by ProcessBoardData().
int MainDaqParser::ProcessCodaFee (int * words) private
Definition at line 167 of file MainDaqParser.cc.
References DecoParam::codaID, dec_par, FEE_EVENT, ProcessCodaFeeBoard(), ProcessCodaFeePrescale(), and DecoParam::verbose.
Referenced by ParseOneSpill().
int MainDaqParser::ProcessCodaFeeBoard (int * words) private
Definition at line 184 of file MainDaqParser.cc.
References FeeData::board, DecoParam::codaID, dec_par, FeeData::elim_window, FeeData::falling_enabled, RunData::fee, get_bin_bit(), get_bin_bits(), get_hex_bit(), get_hex_bits(), FeeData::hard, FeeData::highLimit, FeeData::lowLimit, FeeData::multihit_elim_enabled, RunData::n_fee_event, FeeData::roc, run_data, FeeData::segmentation, FeeData::selectWindow, FeeData::updating_enabled, and DecoParam::verbose.
Referenced by ProcessCodaFee().
int MainDaqParser::ProcessCodaFeePrescale (int * words) private
10 bits = FPGA1, ..., FPGA5, NIM1, ..., NIM5
8 words = FPGA1, ..., FPGA5, NIM1, ..., NIM3
Definition at line 238 of file MainDaqParser.cc.
References DecoParam::codaID, dec_par, RunData::fpga_enabled, RunData::fpga_prescale, get_bin_bit(), RunData::n_fee_prescale, RunData::prescale, run_data, RunData::trig_bit, and DecoParam::verbose.
Referenced by ProcessCodaFee().
int MainDaqParser::ProcessCodaPhysics (int * words) private
Process one Coda STANDARD_PHYSICS event.
Format of words: { 0:evLength, 1:eventCode, 2:headerLength, 3:headerCode, 4:codaEventID-4, 5:eventType, 6:"0", {roc data #1}, {roc data #2},,, {roc data #n} }
{roc data #*} = { rocEvLength, rocID, X, X, vmeTime, {board data #1}...{board data #n}, [e906c0da] }
rocEvLength = N of words on this ROC, excluding the word "rocEvLength" itself.
rocID = "AA" of "0x00AA0000"
The format of board data is taken care of in ProcessBoardData().
Ignore this for now; on 2019-05-30 by Kenichi
Definition at line 277 of file MainDaqParser.cc.
References BEGIN_SPILL, dec_err, dec_par, END_SPILL, FLUSH_EVENTS, get_hex_bits(), DecoError::GetFlushError(), DecoParam::has_1st_bos, RunData::n_flush_evt, RunData::n_flush_evt_bad, RunData::n_phys_evt, RunData::n_phys_evt_bad, PRESTART_INFO, ProcessPhysBOSEOS(), ProcessPhysFlush(), ProcessPhysPrestart(), ProcessPhysRunDesc(), ProcessPhysSlow(), ProcessPhysSpillCounter(), run_data, RUN_DESCRIPTOR, SLOW_CONTROL, SPILL_COUNTER, STANDARD_PHYSICS, TYPE_BOS, and TYPE_EOS.
Referenced by ParseOneSpill().
int MainDaqParser::ProcessCodaPrestart (int * words) private
Process one Coda Prestart event. It is called in main() on CODA_EVENT PRESTART_EVENT. Since the run number is given to the decoder only by this Prestart event, some initialization works have to be done here.
Definition at line 151 of file MainDaqParser.cc.
References coda, dec_par, DecoParam::InitMapper(), run_data, RunData::run_id, DecoParam::runID, DecoParam::sampling, CodaInputManager::SetRunNumber(), and RunData::utime_b.
Referenced by ParseOneSpill().
int MainDaqParser::ProcessPhysBOSEOS (int * words, const int type) private
Temporary adjustment (modified on 2020-01-15). Since spill ID is not always available in the cosmic-ray commissioning, a temporary ID is given here.
Regard the Slow Control info as primary (rather than Spill Counter)
initialize
Skip ROC 25 in END_SPILL since unknown words are placed for debug by Xinkun(?).
Skip this ROC without looking at board data since it's too small (was "< 5") (as also done in "case FLUSH_EVENTS").
Definition at line 481 of file MainDaqParser.cc.
References DecoParam::at_bos, SpillData::bos_coda_id, SpillData::bos_vme_time, DecoParam::codaID, dec_par, SpillData::eos_coda_id, SpillData::eos_vme_time, get_hex_bits(), DecoParam::has_1st_bos, SpillData::n_bos_spill, SpillData::n_eos_spill, PackOneSpillData(), ProcessBoardData(), DecoParam::rocID, SpillData::run_id, DecoParam::runID, SpillData::spill_id, SpillData::spill_id_slow, DecoParam::spillID, DecoParam::spillID_cntr, DecoParam::spillID_slow, DecoParam::spillType, SpillData::targ_pos, DecoParam::targPos, DecoParam::targPos_slow, DecoParam::turn_id_max, TYPE_BOS, and DecoParam::verbose.
Referenced by ProcessCodaPhysics().
int MainDaqParser::ProcessPhysFlush (int * words) private
Process one FLUSH_EVENTS event.
Parameters
[in] words The word array of one Coda event.
Returns
"0" if OK. "-1" if NG.
< If "true", print out ROCs & boards found.
Definition at line 569 of file MainDaqParser.cc.
References Abort(), DecoParam::codaID, DecoError::CountFlush(), dec_err, dec_par, get_hex_bits(), PrintWords(), ProcessBoardData(), DecoParam::rocID, DecoError::SetFlushError(), and DecoParam::verbose.
Referenced by ProcessCodaPhysics().
int MainDaqParser::ProcessPhysPrestart (int * words) private
Definition at line 349 of file MainDaqParser.cc.
Referenced by ProcessCodaPhysics().
int MainDaqParser::ProcessPhysRunDesc (int * words) private
Definition at line 326 of file MainDaqParser.cc.
References RunData::n_run_desc, run_data, and RunData::run_desc.
Referenced by ProcessCodaPhysics().
int MainDaqParser::ProcessPhysSlow (int * words) private
Process the Coda physics event from Spill Counter. Kenichi hasn't confirmed with any document but understand that the spill ID in Slow Control means ID of the previous spill. Since this info will be used in the next spill (BOS etc), this function increments the value ("atoi(value) + 1"). Because most of the slow-control values except TARGPOS_CONTROL etc. are of the previous spill, ID for those values are set to "spillID_slow - 1".
This function takes the Slow Control Physics Event, which is purely a blob of ASCII presented in the form of parsed and reversed unsigned int's. It slaps together the whole event into one big string of hex values, parses it into 2-digit/1-char chunks, flips every group of four characters.
Definition at line 389 of file MainDaqParser.cc.
References DecoParam::codaID, dec_par, SpillData::list_slow_cont, SpillData::n_slow, SlowControlData::name, SpillData::spill_id, DecoParam::spillID_slow, DecoParam::targPos_slow, SlowControlData::ts, SlowControlData::type, and DecoParam::verbose.
Referenced by ProcessCodaPhysics().
int MainDaqParser::ProcessPhysSpillCounter (int * words) private
Process the Coda physics event from Spill Counter. Kenichi hasn't confirmed with any document but understand that the spill ID from Spill Counter means ID of the previous spill. Since this info will be used in the next spill (BOS etc), this function increments the value ("atoi(spillNum) + 1").
Keep this new spill ID in the temporal variable (dec_par.spillID_cntr) since flush events can come after spill counter. Replace spillID with spillID_cntr at BOS.
Definition at line 456 of file MainDaqParser.cc.
References DecoParam::codaID, dec_par, RunData::n_spill, run_data, DecoParam::spillID_cntr, and DecoParam::verbose.
Referenced by ProcessCodaPhysics().
void MainDaqParser::SetEventInfo (EventInfo * evt, const int eventID) private
Definition at line 1367 of file MainDaqParser.cc.
References dec_par, EventInfo::eventID, DecoParam::runID, EventInfo::runID, DecoParam::spillID, and EventInfo::spillID.
Referenced by ProcessBoardFeeQIE(), ProcessBoardJyTDC2(), ProcessBoardTriggerBit(), ProcessBoardTriggerCount(), and ProcessBoardV1495TDC().
Member Data Documentation
CodaInputManager* MainDaqParser::coda private
Definition at line 12 of file MainDaqParser.h.
Referenced by End(), GetCoda(), MainDaqParser(), NextPhysicsEvent(), OpenCodaFile(), ParseOneSpill(), ProcessCodaPrestart(), and ~MainDaqParser().
DecoError MainDaqParser::dec_err
Definition at line 71 of file MainDaqParser.h.
Referenced by End(), PackOneSpillData(), ProcessBoardJyTDC2(), ProcessCodaPhysics(), and ProcessPhysFlush().
DecoParam MainDaqParser::dec_par
Definition at line 70 of file MainDaqParser.h.
Referenced by Fun4AllEVIOInputManager::DirParam(), End(), Fun4AllEVIOInputManager::EventSamplingFactor(), Fun4AllEVIOInputManager::fileopen(), OpenCodaFile(), PackOneSpillData(), ParseOneSpill(), Fun4AllEVIOInputManager::PretendSpillInterval(), ProcessBoardData(), ProcessBoardFeeQIE(), ProcessBoardJyTDC2(), ProcessBoardScaler(), ProcessBoardStdFeeQIE(), ProcessBoardStdJyTDC2(), ProcessBoardStdTriggerBit(), ProcessBoardStdTriggerCount(), ProcessBoardStdV1495TDC(), ProcessBoardV1495TDC(), ProcessCodaFee(), ProcessCodaFeeBoard(), ProcessCodaFeePrescale(), ProcessCodaPhysics(), ProcessCodaPrestart(), ProcessPhysBOSEOS(), ProcessPhysFlush(), ProcessPhysSlow(), ProcessPhysSpillCounter(), Fun4AllEVIOInputManager::run(), SetEventInfo(), and Fun4AllEVIOInputManager::SetOnline().
EventDataMap* MainDaqParser::list_ed private
Definition at line 17 of file MainDaqParser.h.
Referenced by MainDaqParser(), PackOneSpillData(), and ~MainDaqParser().
EventDataMap* MainDaqParser::list_ed_now private
Definition at line 20 of file MainDaqParser.h.
Referenced by MainDaqParser(), NextPhysicsEvent(), PackOneSpillData(), and ~MainDaqParser().
SpillDataMap* MainDaqParser::list_sd private
Definition at line 16 of file MainDaqParser.h.
Referenced by MainDaqParser(), and ~MainDaqParser().
long MainDaqParser::m_file_size_min private
Definition at line 9 of file MainDaqParser.h.
Referenced by OpenCodaFile(), and ParseOneSpill().
int MainDaqParser::m_n_wait private
Definition at line 11 of file MainDaqParser.h.
Referenced by OpenCodaFile(), and ParseOneSpill().
int MainDaqParser::m_sec_wait private
Definition at line 10 of file MainDaqParser.h.
Referenced by OpenCodaFile(), and ParseOneSpill().
RunData MainDaqParser::run_data private
Variables for data storage.
Definition at line 15 of file MainDaqParser.h.
Referenced by End(), NextPhysicsEvent(), PackOneSpillData(), ProcessBoardJyTDC2(), ProcessBoardStdV1495TDC(), ProcessBoardV1495TDC(), ProcessCodaFeeBoard(), ProcessCodaFeePrescale(), ProcessCodaPhysics(), ProcessCodaPrestart(), ProcessPhysRunDesc(), and ProcessPhysSpillCounter().
SpillData* MainDaqParser::sd_now private
Definition at line 19 of file MainDaqParser.h.
Referenced by MainDaqParser(), NextPhysicsEvent(), and PackOneSpillData().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/online/decoder_maindaq/MainDaqParser.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/online/decoder_maindaq/MainDaqParser.cc