SeaQuest Offline Software: SMillepede Class Reference
SMillepede Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/inc/SMillepede.h>
Public Member Functions
SMillepede ()
~SMillepede ()
void init (std::string configFileName="mille.conf")
void setEvent (SRawEvent *rawEvt, SRecEvent *recEvt)
void setEvent (TClonesArray *trks)
void addTrack (SRecTrack &trk)
void addTrack (Tracklet &trk)
void addVertex ()
void fitAlignment ()
void fixDetectorParameter (int detectorID, int parameterID, float val=0.)
void setDetectorParError (int detectorID, int parameterID, float err)
void setDetectorParameter (int detectorID, int parameterID, float val)
void constrainDetectors (int detectorID1, int detectorID2, int parameterID)
void bookEvaluationTree (std::string evalFileName)
void fillEvaluationTree ()
void printResults (std::string outputFileName, std::string incrementFileName)
void printQAPlots ()
int getNHitsOnDetector (int detectorID)
double getZOffsetVal (int detectorID)
double getWOffsetVal (int detectorID)
double getPhiOffsetVal (int detectorID)
double getZOffsetErr (int detectorID)
double getWOffsetErr (int detectorID)
double getPhiOffsetErr (int detectorID)
void initMillepede (std::string configFileName)
void setSingleTrack ()
bool acceptTrack (SRecTrack &recTrack)
bool acceptTrack (Tracklet &track)
Private Attributes
SRawEvent * rawEvent
SRecEvent * recEvent
float par_align [MILLEPEDE::NGLB]
float err_align [MILLEPEDE::NGLB]
std::vector< MPNode > nodes
GeomSvc * p_geomSvc
int nTracks
int nHits [MILLEPEDE::NPLAN]
KalmanFastTracking * tracker
TFile * evalFile
TTree * evalTree
TH1D * evalHist [MILLEPEDE::NPLAN]
int runID
int eventID
MPNode * evalNode
Detailed Description
Definition at line 92 of file SMillepede.h.
Constructor & Destructor Documentation
SMillepede::SMillepede ()
Definition at line 31 of file SMillepede.cxx.
References evalFile, evalTree, GeomSvc::instance(), p_geomSvc, and tracker.
SMillepede::~SMillepede ()
Definition at line 40 of file SMillepede.cxx.
References evalFile, evalHist, evalNode, evalTree, MILLEPEDE::NPLAN, and tracker.
Member Function Documentation
bool SMillepede::acceptTrack (SRecTrack & recTrack)
Definition at line 75 of file SMillepede.cxx.
References MILLEPEDE::CHISQMAX, SRecTrack::getChisq(), SRecTrack::getMomentumSt1(), SRecTrack::getNHits(), MILLEPEDE::MOMMIN, and MILLEPEDE::NHITSMIN.
Referenced by setEvent().
bool SMillepede::acceptTrack (Tracklet & track)
Definition at line 84 of file SMillepede.cxx.
References Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::getNHits(), Tracklet::getProb(), Tracklet::invP, MILLEPEDE::MOMMIN, MILLEPEDE::NHITSMIN, and MILLEPEDE::PROBMIN.
void SMillepede::addTrack (SRecTrack & trk)
Definition at line 171 of file SMillepede.cxx.
References TrkPar::_covar_kf, TrkPar::_state_kf, Hit::detectorID, Hit::driftDistance, fillEvaluationTree(), SRecTrack::getCovariance(), SRawEvent::getHit(), SRecTrack::getHitIndex(), SRecEvent::getLocalID(), SRecTrack::getNHits(), Node::getSmoothed(), SRecTrack::getStateVector(), SRecTrack::getZ(), nChamberPlanes, nHits, nodes, MILLEPEDE::NPLAN, rawEvent, recEvent, setSingleTrack(), and Node::setZ().
Referenced by setEvent().
void SMillepede::addTrack (Tracklet & trk)
Definition at line 125 of file SMillepede.cxx.
References Tracklet::calcChisq(), fillEvaluationTree(), KalmanFastTracking::fitTracklet(), Tracklet::hits, nChamberPlanes, nHits, nodes, MILLEPEDE::NPLAN, setSingleTrack(), and tracker.
void SMillepede::addVertex ()
Definition at line 217 of file SMillepede.cxx.
References MPNode::flag, MPNode::meas, nodes, MPNode::setDerivatives(), MPNode::sigma, MPNode::tx, MPNode::ty, MPNode::x0, MPNode::y0, MPNode::z, and Z_REF.
void SMillepede::bookEvaluationTree (std::string evalFileName)
Definition at line 622 of file SMillepede.cxx.
References evalFile, evalHist, evalNode, evalTree, eventID, GeomSvc::getDetectorName(), GeomSvc::getPlaneSpacing(), MILLEPEDE::NPLAN, p_geomSvc, and runID.
Referenced by main().
void SMillepede::constrainDetectors (int detectorID1, int detectorID2, int parameterID)
Definition at line 272 of file SMillepede.cxx.
References constf_(), MILLEPEDE::NGLB, and MILLEPEDE::NPARPLAN.
Referenced by initMillepede().
void SMillepede::fillEvaluationTree ()
Definition at line 639 of file SMillepede.cxx.
References evalFile, evalHist, evalNode, evalTree, and nodes.
Referenced by addTrack().
void SMillepede::fitAlignment ()
Definition at line 486 of file SMillepede.cxx.
References err_align, errpar_(), fitglo_(), MILLEPEDE::NGLB, and par_align.
Referenced by main().
void SMillepede::fixDetectorParameter (int detectorID, int parameterID, float val = 0.)
Definition at line 425 of file SMillepede.cxx.
References constf_(), err_align, MILLEPEDE::NGLB, MILLEPEDE::NPARPLAN, and par_align.
Referenced by initMillepede().
int SMillepede::getNHitsOnDetector (int detectorID) inline
Definition at line 127 of file SMillepede.h.
References nHits.
double SMillepede::getPhiOffsetErr (int detectorID) inline
Definition at line 133 of file SMillepede.h.
References err_align, and MILLEPEDE::NPARPLAN.
double SMillepede::getPhiOffsetVal (int detectorID) inline
Definition at line 130 of file SMillepede.h.
References err_align, and MILLEPEDE::NPARPLAN.
double SMillepede::getWOffsetErr (int detectorID) inline
Definition at line 132 of file SMillepede.h.
References err_align, and MILLEPEDE::NPARPLAN.
double SMillepede::getWOffsetVal (int detectorID) inline
Definition at line 129 of file SMillepede.h.
References err_align, and MILLEPEDE::NPARPLAN.
double SMillepede::getZOffsetErr (int detectorID) inline
Definition at line 131 of file SMillepede.h.
References err_align, and MILLEPEDE::NPARPLAN.
double SMillepede::getZOffsetVal (int detectorID) inline
Definition at line 128 of file SMillepede.h.
References err_align, and MILLEPEDE::NPARPLAN.
void SMillepede::init (std::string configFileName = "mille.conf")
Definition at line 55 of file SMillepede.cxx.
References err_align, initMillepede(), MILLEPEDE::NGLB, nHits, MILLEPEDE::NPLAN, nTracks, and par_align.
Referenced by main().
void SMillepede::initMillepede (std::string configFileName)
Definition at line 287 of file SMillepede.cxx.
References runAlignment::conf, constf_(), constrainDetectors(), detectorID, err_align, fixDetectorParameter(), GeomSvc::getCostheta(), GeomSvc::getDetectorID(), initgl_(), initun_(), MILLEPEDE::NGLB, MILLEPEDE::NPARPLAN, MILLEPEDE::NPARTRK, MILLEPEDE::NPLAN, MILLEPEDE::NSTDEV, p_geomSvc, par_align, parglo_(), parsig_(), and setDetectorParError().
Referenced by init().
void SMillepede::printQAPlots ()
Definition at line 531 of file SMillepede.cxx.
References err_align, evalFile, evalHist, evalTree, GeomSvc::getPlanePhiOffset(), GeomSvc::getPlaneWOffset(), GeomSvc::getPlaneZOffset(), nChamberPlanes, MILLEPEDE::NPARPLAN, MILLEPEDE::NPLAN, p_geomSvc, and par_align.
Referenced by main().
void SMillepede::printResults (std::string outputFileName, std::string incrementFileName)
Definition at line 498 of file SMillepede.cxx.
References err_align, evalHist, GeomSvc::getDetectorName(), GeomSvc::getPlanePhiOffset(), GeomSvc::getPlaneWOffset(), GeomSvc::getPlaneZOffset(), nHits, MILLEPEDE::NPARPLAN, MILLEPEDE::NPLAN, nTracks, p_geomSvc, and par_align.
Referenced by main().
void SMillepede::setDetectorParameter (int detectorID, int parameterID, float val) inline
Definition at line 116 of file SMillepede.h.
References MILLEPEDE::NPARPLAN, and par_align.
void SMillepede::setDetectorParError (int detectorID, int parameterID, float err) inline
Definition at line 115 of file SMillepede.h.
References err_align, and MILLEPEDE::NPARPLAN.
Referenced by initMillepede().
void SMillepede::setEvent (SRawEvent * rawEvt, SRecEvent * recEvt)
Definition at line 96 of file SMillepede.cxx.
References acceptTrack(), addTrack(), SRecEvent::getNTracks(), SRecEvent::getTrack(), nTracks, rawEvent, and recEvent.
Referenced by main().
void SMillepede::setEvent (TClonesArray * trks)
Definition at line 112 of file SMillepede.cxx.
References acceptTrack(), addTrack(), and nTracks.
void SMillepede::setSingleTrack ()
Definition at line 441 of file SMillepede.cxx.
References equloc_(), fitloc_(), MILLEPEDE::NGLB, nodes, MILLEPEDE::NPARPLAN, MILLEPEDE::NPARTRK, and zerloc_().
Referenced by addTrack().
Member Data Documentation
float SMillepede::err_align[MILLEPEDE::NGLB] private
Definition at line 150 of file SMillepede.h.
Referenced by fitAlignment(), fixDetectorParameter(), getPhiOffsetErr(), getPhiOffsetVal(), getWOffsetErr(), getWOffsetVal(), getZOffsetErr(), getZOffsetVal(), init(), initMillepede(), printQAPlots(), printResults(), and setDetectorParError().
TFile* SMillepede::evalFile private
Definition at line 166 of file SMillepede.h.
Referenced by bookEvaluationTree(), fillEvaluationTree(), printQAPlots(), SMillepede(), and ~SMillepede().
TH1D* SMillepede::evalHist[MILLEPEDE::NPLAN] private
Definition at line 168 of file SMillepede.h.
Referenced by bookEvaluationTree(), fillEvaluationTree(), printQAPlots(), printResults(), and ~SMillepede().
MPNode* SMillepede::evalNode private
Definition at line 171 of file SMillepede.h.
Referenced by bookEvaluationTree(), fillEvaluationTree(), and ~SMillepede().
TTree* SMillepede::evalTree private
Definition at line 167 of file SMillepede.h.
Referenced by bookEvaluationTree(), fillEvaluationTree(), printQAPlots(), SMillepede(), and ~SMillepede().
int SMillepede::eventID private
Definition at line 170 of file SMillepede.h.
Referenced by bookEvaluationTree().
int SMillepede::nHits[MILLEPEDE::NPLAN] private
Definition at line 160 of file SMillepede.h.
Referenced by addTrack(), getNHitsOnDetector(), init(), and printResults().
std::vector<MPNode> SMillepede::nodes private
Definition at line 153 of file SMillepede.h.
Referenced by addTrack(), addVertex(), fillEvaluationTree(), and setSingleTrack().
int SMillepede::nTracks private
Definition at line 159 of file SMillepede.h.
Referenced by init(), printResults(), and setEvent().
GeomSvc* SMillepede::p_geomSvc private
Definition at line 156 of file SMillepede.h.
Referenced by bookEvaluationTree(), initMillepede(), printQAPlots(), printResults(), and SMillepede().
float SMillepede::par_align[MILLEPEDE::NGLB] private
Definition at line 149 of file SMillepede.h.
Referenced by fitAlignment(), fixDetectorParameter(), init(), initMillepede(), printQAPlots(), printResults(), and setDetectorParameter().
SRawEvent* SMillepede::rawEvent private
Definition at line 145 of file SMillepede.h.
Referenced by addTrack(), and setEvent().
SRecEvent* SMillepede::recEvent private
Definition at line 146 of file SMillepede.h.
Referenced by addTrack(), and setEvent().
int SMillepede::runID private
Definition at line 169 of file SMillepede.h.
Referenced by bookEvaluationTree().
KalmanFastTracking* SMillepede::tracker private
Definition at line 163 of file SMillepede.h.
Referenced by addTrack(), SMillepede(), and ~SMillepede().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/inc/SMillepede.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/ktracker/src/SMillepede.cxx