SeaQuest Offline Software: KalmanTrack Class Reference
KalmanTrack Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/KalmanTrack.h>
Public Member Functions
KalmanTrack ()
Constructor, default one is for list::resize()
KalmanTrack (Seed _seed_input)
KalmanTrack (SRecTrack &_trk, SRawEvent *_rawevt, SRecEvent *_recevt)
Seed getSeed ()
Get the seed associated.
void flipCharge ()
Flip the sign of this track.
bool isValid ()
Self check to see if it is null.
int isInStation3 ()
Check if the seed goes to station 3+ or station 3-.
bool propagateTo (int detectorID)
Propagate the track to a designated position.
int getCurrentDetectorID ()
double getExpPosition ()
Get the expected position.
double getExpPosError ()
double getExpPositionX ()
double getExpPositionY ()
double getExpPosErrorX ()
double getExpPosErrorY ()
Node * getNearestNodePtr (double z)
void getExpPositionFast (double z, double &x, double &y, Node *_node=NULL)
void getExpPosErrorFast (double z, double &dx, double &dy, Node *_node=NULL)
double getExpLocalSlop ()
Get the expected slope.
double getExpLcSlopErr ()
double getExpLocalIntersection ()
double getExpLcIntersectionErr ()
bool addHit (Hit _hit)
void update ()
Update the track status.
void updateMomentum ()
Update the momentum.
void setCurrTrkpar (TrkPar &_trkpar)
set the current track parameter
double getMomentumVertex (double z, double &px, double &py, double &pz)
Get the rough vertex momentum.
std::list< int > & getHitIndexList ()
Get the list of hits associated.
std::list< Node > & getNodeList ()
std::vector< int > getMissedDetectorIDs ()
int getNHits ()
int getCharge ()
int getAssignedCharge ()
int getKickCharge ()
double getChisq ()
double getQuality ()
double getReducedChisq ()
double getChisqVertex ()
double getXZSlopeInStation (int stationID)
double getPositionInStation (int stationID, double &x, double &y, double &z)
double getMomentumInStation (int stationID)
double getMomentumUpstream ()
double getMomentumUpstream (double &px, double &py, double &pz)
int getNHitsInStation (int stationID)
double getMuIDAngle ()
void getSagittaInSuperDetector (int detectorID, double &pos_exp, double &window)
Node * getNodeDownstream ()
Get Nodes in both upstream and downstream which are closest to KMag.
Node * getNodeUpstream ()
bool operator< (const KalmanTrack &elem) const
Overriden operators.
bool operator== (const KalmanTrack &elem) const
bool similarity (const KalmanTrack &elem) const
void print ()
Debugging print.
void printNodes ()
int getNodeChisq (double *chisqs)
Quality monitoring methods.
int getAlignment (int level, int *detectorID, double *res, double *R, double *T)
int getPositions (int level, double *x, double *y, double *z)
int getMomentums (int level, double *px, double *py, double *pz)
int getHitsIndex (int *index)
TGraph getXZProjection ()
SRecTrack getSRecTrack ()
Output to SRecTrack.
KalmanTrack ()
Constructor, default one is for list::resize()
KalmanTrack (Seed _seed_input)
KalmanTrack (SRecTrack &_trk, SRawEvent *_rawevt, SRecEvent *_recevt)
Seed getSeed ()
Get the seed associated.
void flipCharge ()
Flip the sign of this track.
bool isValid ()
Self check to see if it is null.
int isInStation3 ()
Check if the seed goes to station 3+ or station 3-.
bool propagateTo (int detectorID)
Propagate the track to a designated position.
int getCurrentDetectorID ()
double getExpPosition ()
Get the expected position.
double getExpPosError ()
double getExpPositionX ()
double getExpPositionY ()
double getExpPosErrorX ()
double getExpPosErrorY ()
Node * getNearestNodePtr (double z)
void getExpPositionFast (double z, double &x, double &y, Node *_node=NULL)
void getExpPosErrorFast (double z, double &dx, double &dy, Node *_node=NULL)
double getExpLocalSlop ()
Get the expected slope.
double getExpLcSlopErr ()
double getExpLocalIntersection ()
double getExpLcIntersectionErr ()
bool addHit (Hit _hit)
void update ()
Update the track status.
void updateMomentum ()
Update the momentum.
void setCurrTrkpar (TrkPar &_trkpar)
set the current track parameter
double getMomentumVertex (double z, double &px, double &py, double &pz)
Get the rough vertex momentum.
std::list< int > & getHitIndexList ()
Get the list of hits associated.
std::list< Node > & getNodeList ()
std::vector< int > getMissedDetectorIDs ()
int getNHits ()
int getCharge ()
int getAssignedCharge ()
int getKickCharge ()
double getChisq ()
double getQuality ()
double getReducedChisq ()
double getChisqVertex ()
double getXZSlopeInStation (int stationID)
double getPositionInStation (int stationID, double &x, double &y, double &z)
double getMomentumInStation (int stationID)
double getMomentumUpstream ()
double getMomentumUpstream (double &px, double &py, double &pz)
int getNHitsInStation (int stationID)
double getMuIDAngle ()
void getSagittaInSuperDetector (int detectorID, double &pos_exp, double &window)
Node * getNodeDownstream ()
Get Nodes in both upstream and downstream which are closest to KMag.
Node * getNodeUpstream ()
bool operator< (const KalmanTrack &elem) const
Overriden operators.
bool operator== (const KalmanTrack &elem) const
bool similarity (const KalmanTrack &elem) const
void print ()
Debugging print.
void printNodes ()
int getNodeChisq (double *chisqs)
Quality monitoring methods.
int getAlignment (int level, int *detectorID, double *res, double *R, double *T)
int getPositions (int level, double *x, double *y, double *z)
int getMomentums (int level, double *px, double *py, double *pz)
int getHitsIndex (int *index)
TGraph getXZProjection ()
SRecTrack getSRecTrack ()
Output to SRecTrack.
Private Attributes
std::list< int > _hit_index
std::list< Node > _nodes
double _chisq
double _quality
double _chisq_vertex
Node _node_next
TrkPar _trkpar_curr
Seed _seed
Detailed Description
Definition at line 51 of file KalmanTrack.h.
Constructor & Destructor Documentation
KalmanTrack::KalmanTrack ()
Constructor, default one is for list::resize()
Default constructor for KalmanTrack, wiill only be used when resizing the track candidate list.
Definition at line 144 of file KalmanTrack.cxx.
References _chisq, _hit_index, _nodes, and update().
KalmanTrack::KalmanTrack (Seed _seed_input)
Definition at line 153 of file KalmanTrack.cxx.
References _chisq, TrkPar::_covar_kf, _hit_index, _nodes, _seed, TrkPar::_state_kf, _trkpar_curr, TrkPar::_z, Seed::axz, Seed::ayz, Seed::charge, Seed::getExpPositionX(), Seed::getExpPositionY(), GeomSvc::getPlanePosition(), GeomSvc::instance(), nChamberPlanes, nHodoPlanes, Seed::p, p_geomSvc, and update().
KalmanTrack::KalmanTrack (SRecTrack & _trk, SRawEvent * _rawevt, SRecEvent * _recevt)
Update the hit info. if needed
Definition at line 180 of file KalmanTrack.cxx.
References _chisq, TrkPar::_covar_kf, _hit_index, _nodes, TrkPar::_state_kf, TrkPar::_z, Hit::detectorID, Hit::driftDistance, Hit::elementID, SRecTrack::getChisq(), SRecTrack::getChisqAtNode(), SRecTrack::getCovariance(), GeomSvc::getDriftDistance(), Node::getFiltered(), SRawEvent::getHit(), SRecTrack::getHitIndex(), SRecEvent::getLocalID(), GeomSvc::getMeasurement(), SRecTrack::getNHits(), Node::getPredicted(), Hit::getSign(), Node::getSmoothed(), SRecTrack::getStateVector(), SRecTrack::getZ(), GeomSvc::instance(), p_geomSvc, Hit::pos, Node::setChisq(), Node::setFilterDone(), Node::setPredictionDone(), Node::setSmoothDone(), Node::setZ(), and Hit::tdcTime.
KalmanTrack::KalmanTrack ()
Constructor, default one is for list::resize()
KalmanTrack::KalmanTrack (Seed _seed_input)
KalmanTrack::KalmanTrack (SRecTrack & _trk, SRawEvent * _rawevt, SRecEvent * _recevt)
Member Function Documentation
bool KalmanTrack::addHit (Hit _hit)
Add a new hit to the hit list both in index list and node list
Definition at line 715 of file KalmanTrack.cxx.
References _hit_index, _node_next, _nodes, _trkpar_curr, KalmanFilter::filter(), Node::getFiltered(), Node::getPredicted(), Hit::index, KalmanFilter::instance(), Node::setPredictionDone(), and update().
bool KalmanTrack::addHit (Hit _hit)
Add a new hit to the hit list both in index list and node list
void KalmanTrack::flipCharge ()
Flip the sign of this track.
Definition at line 299 of file KalmanTrack.cxx.
References TrkPar::_covar_kf, _nodes, and TrkPar::flip_charge().
void KalmanTrack::flipCharge ()
Flip the sign of this track.
int KalmanTrack::getAlignment (int level, int * detectorID, double * res, double * R, double * T)
int KalmanTrack::getAlignment (int level, int * detectorID, double * res, double * R, double * T)
Definition at line 739 of file KalmanTrack.cxx.
References _nodes, GeomSvc::getCostheta(), GeomSvc::getSintheta(), GeomSvc::instance(), and p_geomSvc.
int KalmanTrack::getAssignedCharge () inline
Definition at line 117 of file KalmanTrack.h.
References _nodes.
int KalmanTrack::getAssignedCharge () inline
Definition at line 117 of file KalmanTrack.h.
References _nodes.
Referenced by print().
int KalmanTrack::getCharge () inline
Definition at line 116 of file KalmanTrack.h.
References _nodes.
int KalmanTrack::getCharge () inline
Definition at line 116 of file KalmanTrack.h.
References _nodes.
Referenced by print().
double KalmanTrack::getChisq () inline
Definition at line 119 of file KalmanTrack.h.
References _chisq.
double KalmanTrack::getChisq () inline
Definition at line 119 of file KalmanTrack.h.
References _chisq.
double KalmanTrack::getChisqVertex () inline
Definition at line 122 of file KalmanTrack.h.
References _chisq_vertex.
double KalmanTrack::getChisqVertex () inline
Definition at line 122 of file KalmanTrack.h.
References _chisq_vertex.
int KalmanTrack::getCurrentDetectorID () inline
Definition at line 74 of file KalmanTrack.h.
References _node_next, Hit::detectorID, and Node::getHit().
int KalmanTrack::getCurrentDetectorID () inline
Definition at line 74 of file KalmanTrack.h.
References _node_next, Hit::detectorID, and Node::getHit().
double KalmanTrack::getExpLcIntersectionErr ()
double KalmanTrack::getExpLcIntersectionErr ()
double KalmanTrack::getExpLcSlopErr ()
Definition at line 499 of file KalmanTrack.cxx.
References TrkPar::_covar_kf, _node_next, Node::getPredicted(), and Node::getProjector().
double KalmanTrack::getExpLcSlopErr ()
double KalmanTrack::getExpLocalIntersection ()
double KalmanTrack::getExpLocalIntersection ()
double KalmanTrack::getExpLocalSlop ()
Get the expected slope.
double KalmanTrack::getExpLocalSlop ()
Get the expected slope.
Definition at line 490 of file KalmanTrack.cxx.
References _node_next, TrkPar::_state_kf, Node::getPredicted(), and Node::getProjector().
double KalmanTrack::getExpPosError ()
Definition at line 391 of file KalmanTrack.cxx.
References TrkPar::_covar_kf, _node_next, Hit::detectorID, SMatrix::getABCt(), Node::getHit(), GeomSvc::getPlaneSpacing(), Node::getPredicted(), Node::getProjector(), and GeomSvc::instance().
double KalmanTrack::getExpPosError ()
void KalmanTrack::getExpPosErrorFast (double z, double & dx, double & dy, Node * _node = NULL)
void KalmanTrack::getExpPosErrorFast (double z, double & dx, double & dy, Node * _node = NULL)
Definition at line 459 of file KalmanTrack.cxx.
References TrkPar::_covar_kf, TrkPar::get_z(), Node::getFiltered(), getNearestNodePtr(), Node::getPredicted(), Node::getSmoothed(), Node::isFilterDone(), Node::isSmoothDone(), and NULL.
double KalmanTrack::getExpPosErrorX () inline
Definition at line 81 of file KalmanTrack.h.
References TrkPar::_covar_kf, _node_next, and Node::getPredicted().
double KalmanTrack::getExpPosErrorX () inline
Definition at line 81 of file KalmanTrack.h.
References TrkPar::_covar_kf, _node_next, and Node::getPredicted().
double KalmanTrack::getExpPosErrorY () inline
Definition at line 82 of file KalmanTrack.h.
References TrkPar::_covar_kf, _node_next, and Node::getPredicted().
double KalmanTrack::getExpPosErrorY () inline
Definition at line 82 of file KalmanTrack.h.
References TrkPar::_covar_kf, _node_next, and Node::getPredicted().
double KalmanTrack::getExpPosition ()
Get the expected position.
double KalmanTrack::getExpPosition ()
Get the expected position.
Definition at line 378 of file KalmanTrack.cxx.
References _node_next, TrkPar::_state_kf, Node::getPredicted(), Node::getProjector(), and LogInfo.
void KalmanTrack::getExpPositionFast (double z, double & x, double & y, Node * _node = NULL)
void KalmanTrack::getExpPositionFast (double z, double & x, double & y, Node * _node = NULL)
Definition at line 428 of file KalmanTrack.cxx.
References TrkPar::get_dxdz(), TrkPar::get_dydz(), TrkPar::get_x(), TrkPar::get_y(), TrkPar::get_z(), Node::getFiltered(), getNearestNodePtr(), Node::getPredicted(), Node::getSmoothed(), Node::isFilterDone(), Node::isSmoothDone(), and NULL.
Referenced by getMuIDAngle(), and getSagittaInSuperDetector().
double KalmanTrack::getExpPositionX () inline
Definition at line 79 of file KalmanTrack.h.
References _node_next, TrkPar::_state_kf, and Node::getPredicted().
double KalmanTrack::getExpPositionX () inline
Definition at line 79 of file KalmanTrack.h.
References _node_next, TrkPar::_state_kf, and Node::getPredicted().
double KalmanTrack::getExpPositionY () inline
Definition at line 80 of file KalmanTrack.h.
References _node_next, TrkPar::_state_kf, and Node::getPredicted().
double KalmanTrack::getExpPositionY () inline
Definition at line 80 of file KalmanTrack.h.
References _node_next, TrkPar::_state_kf, and Node::getPredicted().
std::list<int>& KalmanTrack::getHitIndexList () inline
Get the list of hits associated.
Definition at line 111 of file KalmanTrack.h.
References _hit_index.
std::list<int>& KalmanTrack::getHitIndexList () inline
Get the list of hits associated.
Definition at line 111 of file KalmanTrack.h.
References _hit_index.
Referenced by KalmanFastTracking::processOneTracklet(), and KalmanFastTracking::resolveLeftRight().
int KalmanTrack::getHitsIndex (int * index)
Definition at line 865 of file KalmanTrack.cxx.
References _hit_index.
int KalmanTrack::getHitsIndex (int * index)
int KalmanTrack::getKickCharge ()
int KalmanTrack::getKickCharge ()
Definition at line 617 of file KalmanTrack.cxx.
References getXZSlopeInStation().
Referenced by print().
std::vector<int> KalmanTrack::getMissedDetectorIDs ()
std::vector< int > KalmanTrack::getMissedDetectorIDs ()
Definition at line 877 of file KalmanTrack.cxx.
References _nodes.
double KalmanTrack::getMomentumInStation (int stationID)
Definition at line 548 of file KalmanTrack.cxx.
References _nodes, and detectorID.
double KalmanTrack::getMomentumInStation (int stationID)
int KalmanTrack::getMomentums (int level, double * px, double * py, double * pz)
Definition at line 816 of file KalmanTrack.cxx.
References _nodes.
int KalmanTrack::getMomentums (int level, double * px, double * py, double * pz)
double KalmanTrack::getMomentumUpstream () inline
Definition at line 127 of file KalmanTrack.h.
References _nodes.
Referenced by isValid().
double KalmanTrack::getMomentumUpstream () inline
Definition at line 127 of file KalmanTrack.h.
References _nodes.
double KalmanTrack::getMomentumUpstream (double & px, double & py, double & pz)
Definition at line 625 of file KalmanTrack.cxx.
References _nodes.
double KalmanTrack::getMomentumUpstream (double & px, double & py, double & pz)
double KalmanTrack::getMomentumVertex (double z, double & px, double & py, double & pz)
Get the rough vertex momentum.
double KalmanTrack::getMomentumVertex (double z, double & px, double & py, double & pz)
Get the rough vertex momentum.
Definition at line 343 of file KalmanTrack.cxx.
References _chisq_vertex, _nodes, KalmanFilter::fit_node(), TrkPar::get_mom(), Node::getChisq(), Node::getFiltered(), Node::getMeasurement(), Node::getMeasurementCov(), Node::getProjector(), KalmanFilter::instance(), KalmanFilter::setCurrTrkpar(), and Node::setZ().
double KalmanTrack::getMuIDAngle ()
Definition at line 851 of file KalmanTrack.cxx.
References _seed, getExpPositionFast(), Seed::getExpPositionX(), and Seed::getExpPositionY().
double KalmanTrack::getMuIDAngle ()
Node* KalmanTrack::getNearestNodePtr (double z)
Node * KalmanTrack::getNearestNodePtr (double z)
Definition at line 408 of file KalmanTrack.cxx.
References _nodes.
Referenced by getExpPosErrorFast(), and getExpPositionFast().
int KalmanTrack::getNHits () inline
Definition at line 115 of file KalmanTrack.h.
References _hit_index.
int KalmanTrack::getNHits () inline
Definition at line 115 of file KalmanTrack.h.
References _hit_index.
Referenced by getXZProjection().
int KalmanTrack::getNHitsInStation (int stationID)
int KalmanTrack::getNHitsInStation (int stationID)
Definition at line 641 of file KalmanTrack.cxx.
References _nodes, and detectorID.
int KalmanTrack::getNodeChisq (double * chisqs)
Quality monitoring methods.
int KalmanTrack::getNodeChisq (double * chisqs)
Quality monitoring methods.
Node * KalmanTrack::getNodeDownstream ()
Get Nodes in both upstream and downstream which are closest to KMag.
Definition at line 529 of file KalmanTrack.cxx.
References _nodes, detectorID, and NULL.
Node* KalmanTrack::getNodeDownstream ()
Get Nodes in both upstream and downstream which are closest to KMag.
std::list<Node>& KalmanTrack::getNodeList () inline
Definition at line 112 of file KalmanTrack.h.
References _nodes.
std::list<Node>& KalmanTrack::getNodeList () inline
Definition at line 112 of file KalmanTrack.h.
References _nodes.
Referenced by VertexFit::addTrack(), KalmanFastTracking::fitTrack(), KalmanFitter::initNodeList(), KalmanFastTracking::processOneTracklet(), KalmanFastTracking::resolveLeftRight(), KalmanFitter::setStartingParameter(), and KalmanFitter::updateTrack().
Node* KalmanTrack::getNodeUpstream ()
Node * KalmanTrack::getNodeUpstream ()
Definition at line 510 of file KalmanTrack.cxx.
References _nodes, detectorID, and NULL.
double KalmanTrack::getPositionInStation (int stationID, double & x, double & y, double & z)
Definition at line 586 of file KalmanTrack.cxx.
References _nodes, and detectorID.
double KalmanTrack::getPositionInStation (int stationID, double & x, double & y, double & z)
int KalmanTrack::getPositions (int level, double * x, double * y, double * z)
Definition at line 782 of file KalmanTrack.cxx.
References _nodes.
Referenced by getXZProjection().
int KalmanTrack::getPositions (int level, double * x, double * y, double * z)
double KalmanTrack::getQuality () inline
Definition at line 120 of file KalmanTrack.h.
References _quality.
double KalmanTrack::getQuality () inline
Definition at line 120 of file KalmanTrack.h.
References _quality.
double KalmanTrack::getReducedChisq () inline
Definition at line 121 of file KalmanTrack.h.
References _chisq, and _hit_index.
double KalmanTrack::getReducedChisq () inline
Definition at line 121 of file KalmanTrack.h.
References _chisq, and _hit_index.
void KalmanTrack::getSagittaInSuperDetector (int detectorID, double & pos_exp, double & window)
DetectorID of the relevant view of D1U, D1X and D1V
Definition at line 905 of file KalmanTrack.cxx.
References _nodes, GeomSvc::getCostheta(), getExpPositionFast(), GeomSvc::getPlanePosition(), GeomSvc::getSintheta(), GeomSvc::instance(), and p_geomSvc.
void KalmanTrack::getSagittaInSuperDetector (int detectorID, double & pos_exp, double & window)
Seed KalmanTrack::getSeed () inline
Get the seed associated.
Definition at line 61 of file KalmanTrack.h.
References _seed.
Seed KalmanTrack::getSeed () inline
Get the seed associated.
Definition at line 61 of file KalmanTrack.h.
References _seed.
SRecTrack KalmanTrack::getSRecTrack ()
Output to SRecTrack.
SRecTrack KalmanTrack::getSRecTrack ()
Output to SRecTrack.
Definition at line 954 of file KalmanTrack.cxx.
References _chisq, _nodes, SRecTrack::insertChisq(), SRecTrack::insertCovariance(), SRecTrack::insertHitIndex(), SRecTrack::insertStateVector(), SRecTrack::insertZ(), SRecTrack::setChisq(), and SRecTrack::swimToVertex().
Referenced by KalmanFastTracking::processOneTracklet().
TGraph KalmanTrack::getXZProjection ()
Definition at line 945 of file KalmanTrack.cxx.
References getNHits(), and getPositions().
TGraph KalmanTrack::getXZProjection ()
double KalmanTrack::getXZSlopeInStation (int stationID)
Definition at line 567 of file KalmanTrack.cxx.
References _nodes, and detectorID.
Referenced by getKickCharge().
double KalmanTrack::getXZSlopeInStation (int stationID)
int KalmanTrack::isInStation3 ()
Check if the seed goes to station 3+ or station 3-.
Definition at line 224 of file KalmanTrack.cxx.
References _seed, Seed::getExpPositionX(), Seed::getExpPositionY(), GeomSvc::getPlanePosition(), GeomSvc::instance(), GeomSvc::isInPlane(), and p_geomSvc.
int KalmanTrack::isInStation3 ()
Check if the seed goes to station 3+ or station 3-.
bool KalmanTrack::isValid ()
Self check to see if it is null.
bool KalmanTrack::isValid ()
Self check to see if it is null.
Definition at line 215 of file KalmanTrack.cxx.
References _nodes, getMomentumUpstream(), INVP_MAX, and INVP_MIN.
Referenced by KalmanFastTracking::processOneTracklet().
bool KalmanTrack::operator< (const KalmanTrack & elem) const
Overriden operators.
bool KalmanTrack::operator< (const KalmanTrack & elem) const
Overriden operators.
Definition at line 672 of file KalmanTrack.cxx.
References _quality.
bool KalmanTrack::operator== (const KalmanTrack & elem) const
Definition at line 677 of file KalmanTrack.cxx.
References _hit_index, and _quality.
bool KalmanTrack::operator== (const KalmanTrack & elem) const
void KalmanTrack::print ()
Debugging print.
void KalmanTrack::print ()
Debugging print.
Definition at line 972 of file KalmanTrack.cxx.
References _chisq, _hit_index, _nodes, _quality, TrkPar::_state_kf, _trkpar_curr, TrkPar::get_z(), getAssignedCharge(), getCharge(), and getKickCharge().
void KalmanTrack::printNodes ()
void KalmanTrack::printNodes ()
Definition at line 1003 of file KalmanTrack.cxx.
References _nodes.
bool KalmanTrack::propagateTo (int detectorID)
Propagate the track to a designated position.
bool KalmanTrack::propagateTo (int detectorID)
Propagate the track to a designated position.
Definition at line 324 of file KalmanTrack.cxx.
References _node_next, _trkpar_curr, detectorID, Hit::detectorID, KalmanFilter::instance(), KalmanFilter::predict(), and KalmanFilter::setCurrTrkpar().
void KalmanTrack::setCurrTrkpar (TrkPar & _trkpar) inline
set the current track parameter
Definition at line 105 of file KalmanTrack.h.
References _trkpar_curr.
Referenced by KalmanFastTracking::processOneTracklet(), and KalmanFitter::updateTrack().
void KalmanTrack::setCurrTrkpar (TrkPar & _trkpar) inline
set the current track parameter
Definition at line 105 of file KalmanTrack.h.
References _trkpar_curr.
bool KalmanTrack::similarity (const KalmanTrack & elem) const
Definition at line 685 of file KalmanTrack.cxx.
References _hit_index.
bool KalmanTrack::similarity (const KalmanTrack & elem) const
void KalmanTrack::update ()
Update the track status.
void KalmanTrack::update ()
Update the track status.
Definition at line 659 of file KalmanTrack.cxx.
References _chisq, _hit_index, _nodes, and _quality.
Referenced by addHit(), KalmanTrack(), and KalmanFitter::updateTrack().
void KalmanTrack::updateMomentum ()
Update the momentum.
void KalmanTrack::updateMomentum ()
Update the momentum.
Definition at line 245 of file KalmanTrack.cxx.
References _nodes, TrkPar::_state_kf, and _trkpar_curr.
Member Data Documentation
double KalmanTrack::_chisq private
Definition at line 163 of file KalmanTrack.h.
Referenced by getChisq(), getReducedChisq(), getSRecTrack(), KalmanTrack(), print(), and update().
double KalmanTrack::_chisq_vertex private
Definition at line 165 of file KalmanTrack.h.
Referenced by getChisqVertex(), and getMomentumVertex().
std::list< int > KalmanTrack::_hit_index private
Definition at line 160 of file KalmanTrack.h.
Referenced by addHit(), getHitIndexList(), getHitsIndex(), getNHits(), getReducedChisq(), KalmanTrack(), operator==(), print(), similarity(), and update().
Node KalmanTrack::_node_next private
Definition at line 167 of file KalmanTrack.h.
Referenced by addHit(), getCurrentDetectorID(), getExpLcSlopErr(), getExpLocalSlop(), getExpPosError(), getExpPosErrorX(), getExpPosErrorY(), getExpPosition(), getExpPositionX(), getExpPositionY(), and propagateTo().
std::list< Node > KalmanTrack::_nodes private
Definition at line 161 of file KalmanTrack.h.
Referenced by addHit(), flipCharge(), getAlignment(), getAssignedCharge(), getCharge(), getMissedDetectorIDs(), getMomentumInStation(), getMomentums(), getMomentumUpstream(), getMomentumVertex(), getNearestNodePtr(), getNHitsInStation(), getNodeDownstream(), getNodeList(), getNodeUpstream(), getPositionInStation(), getPositions(), getSagittaInSuperDetector(), getSRecTrack(), getXZSlopeInStation(), isValid(), KalmanTrack(), print(), printNodes(), update(), and updateMomentum().
double KalmanTrack::_quality private
Definition at line 164 of file KalmanTrack.h.
Referenced by getQuality(), operator<(), operator==(), print(), and update().
Seed KalmanTrack::_seed private
Definition at line 170 of file KalmanTrack.h.
Referenced by getMuIDAngle(), getSeed(), isInStation3(), and KalmanTrack().
TrkPar KalmanTrack::_trkpar_curr private
Definition at line 168 of file KalmanTrack.h.
Referenced by addHit(), KalmanTrack(), print(), propagateTo(), setCurrTrkpar(), and updateMomentum().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/inc/KalmanTrack.h
/home/yuhw/GitHub/SeaQuest/seaquest-ktracker/src/KalmanTrack.cxx