Class Reference for E1039 Core & Analysis Software: SQHardSpill_v1 Class Reference
SQHardSpill_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHardSpill_v1.h>
Public Member Functions
SQHardSpill_v1 ()
virtual ~SQHardSpill_v1 ()
SQHardSpill * clone () const
Virtual copy constructor.
SQHardSpill * Clone () const
No use. Only for backward compatibility.
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const
virtual int get_bos_coda_id () const
Return the Coda ID at BOS of this spill.
virtual void set_bos_coda_id (const int a)
virtual int get_bos_vme_time () const
Return the VME time at BOS of this spill.
virtual void set_bos_vme_time (const int a)
virtual int get_eos_coda_id () const
Return the Coda ID at EOS of this spill.
virtual void set_eos_coda_id (const int a)
virtual int get_eos_vme_time () const
Return the VME time at EOS of this spill.
virtual void set_eos_vme_time (const int a)
virtual double get_time_input () const
Return the time taken for the Coda input per spill.
virtual void set_time_input (const double a)
virtual double get_time_decode () const
Return the time taken for the word decoding per spill.
virtual void set_time_decode (const double a)
virtual double get_time_map () const
Return the time taken for the channel mapping per spill.
virtual void set_time_map (const double a)
virtual double get_time_subsys () const
Return the time taken for the SubsysReco event processing per spill.
virtual void set_time_subsys (const double a)
virtual double get_time_output () const
Return the time taken for the data output per spill.
virtual void set_time_output (const double a)
ClassDef (SQHardSpill_v1, 1)
Public Member Functions inherited from SQHardSpill
virtual ~SQHardSpill ()
ClassDef (SQHardSpill, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Protected Member Functions inherited from SQHardSpill
SQHardSpill ()
Detailed Description
Definition at line 6 of file SQHardSpill_v1.h.
Constructor & Destructor Documentation
SQHardSpill_v1()
SQHardSpill_v1::SQHardSpill_v1 ()
Definition at line 6 of file SQHardSpill_v1.cxx.
Referenced by clone(), and Clone().
~SQHardSpill_v1()
virtual SQHardSpill_v1::~SQHardSpill_v1 () inline virtual
Definition at line 19 of file SQHardSpill_v1.h.
Member Function Documentation
ClassDef()
SQHardSpill_v1::ClassDef (SQHardSpill_v1 , 1)
clone()
SQHardSpill* SQHardSpill_v1::clone () const inline virtual
Virtual copy constructor.
Implements SQHardSpill.
Definition at line 21 of file SQHardSpill_v1.h.
References SQHardSpill_v1().
Clone()
SQHardSpill* SQHardSpill_v1::Clone () const inline virtual
No use. Only for backward compatibility.
Implements SQHardSpill.
Definition at line 22 of file SQHardSpill_v1.h.
References SQHardSpill_v1().
get_bos_coda_id()
virtual int SQHardSpill_v1::get_bos_coda_id () const inline virtual
Return the Coda ID at BOS of this spill.
Implements SQHardSpill.
Definition at line 27 of file SQHardSpill_v1.h.
get_bos_vme_time()
virtual int SQHardSpill_v1::get_bos_vme_time () const inline virtual
Return the VME time at BOS of this spill.
Implements SQHardSpill.
Definition at line 30 of file SQHardSpill_v1.h.
get_eos_coda_id()
virtual int SQHardSpill_v1::get_eos_coda_id () const inline virtual
Return the Coda ID at EOS of this spill.
Implements SQHardSpill.
Definition at line 33 of file SQHardSpill_v1.h.
get_eos_vme_time()
virtual int SQHardSpill_v1::get_eos_vme_time () const inline virtual
Return the VME time at EOS of this spill.
Implements SQHardSpill.
Definition at line 36 of file SQHardSpill_v1.h.
get_time_decode()
virtual double SQHardSpill_v1::get_time_decode () const inline virtual
Return the time taken for the word decoding per spill.
Implements SQHardSpill.
Definition at line 42 of file SQHardSpill_v1.h.
get_time_input()
virtual double SQHardSpill_v1::get_time_input () const inline virtual
Return the time taken for the Coda input per spill.
Implements SQHardSpill.
Definition at line 39 of file SQHardSpill_v1.h.
get_time_map()
virtual double SQHardSpill_v1::get_time_map () const inline virtual
Return the time taken for the channel mapping per spill.
Implements SQHardSpill.
Definition at line 45 of file SQHardSpill_v1.h.
get_time_output()
virtual double SQHardSpill_v1::get_time_output () const inline virtual
Return the time taken for the data output per spill.
Implements SQHardSpill.
Definition at line 51 of file SQHardSpill_v1.h.
get_time_subsys()
virtual double SQHardSpill_v1::get_time_subsys () const inline virtual
Return the time taken for the SubsysReco event processing per spill.
Implements SQHardSpill.
Definition at line 48 of file SQHardSpill_v1.h.
identify()
void SQHardSpill_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Implements SQHardSpill.
Definition at line 33 of file SQHardSpill_v1.cxx.
isValid()
int SQHardSpill_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Implements SQHardSpill.
Definition at line 24 of file SQHardSpill_v1.h.
Reset()
void SQHardSpill_v1::Reset () virtual
Clear Event.
Implements SQHardSpill.
Definition at line 20 of file SQHardSpill_v1.cxx.
set_bos_coda_id()
virtual void SQHardSpill_v1::set_bos_coda_id (const int a) inline virtual
Implements SQHardSpill.
Definition at line 28 of file SQHardSpill_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_bos_vme_time()
virtual void SQHardSpill_v1::set_bos_vme_time (const int a) inline virtual
Implements SQHardSpill.
Definition at line 31 of file SQHardSpill_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_eos_coda_id()
virtual void SQHardSpill_v1::set_eos_coda_id (const int a) inline virtual
Implements SQHardSpill.
Definition at line 34 of file SQHardSpill_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_eos_vme_time()
virtual void SQHardSpill_v1::set_eos_vme_time (const int a) inline virtual
Implements SQHardSpill.
Definition at line 37 of file SQHardSpill_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_time_decode()
virtual void SQHardSpill_v1::set_time_decode (const double a) inline virtual
Implements SQHardSpill.
Definition at line 43 of file SQHardSpill_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_time_input()
virtual void SQHardSpill_v1::set_time_input (const double a) inline virtual
Implements SQHardSpill.
Definition at line 40 of file SQHardSpill_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_time_map()
virtual void SQHardSpill_v1::set_time_map (const double a) inline virtual
Implements SQHardSpill.
Definition at line 46 of file SQHardSpill_v1.h.
Referenced by Fun4AllEVIOInputManager::run().
set_time_output()
virtual void SQHardSpill_v1::set_time_output (const double a) inline virtual
Implements SQHardSpill.
Definition at line 52 of file SQHardSpill_v1.h.
set_time_subsys()
virtual void SQHardSpill_v1::set_time_subsys (const double a) inline virtual
Implements SQHardSpill.
Definition at line 49 of file SQHardSpill_v1.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHardSpill_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHardSpill_v1.cxx