SeaQuest Offline Software: PHG4SpacalSteppingAction Class Reference
PHG4SpacalSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SpacalSteppingAction.h>
Public Member Functions
PHG4SpacalSteppingAction (PHG4SpacalDetector *)
constructor
virtual ~PHG4SpacalSteppingAction ()
destroctor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
double get_zmin ()
double get_zmax ()
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4SpacalDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4Hit * hit
PHG4HitContainer * savehitcontainer
PHG4Shower * saveshower
int savetrackid
int savepoststepstatus
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 21 of file PHG4SpacalSteppingAction.h.
Constructor & Destructor Documentation
PHG4SpacalSteppingAction::PHG4SpacalSteppingAction (PHG4SpacalDetector * detector) explicit
constructor
Definition at line 30 of file PHG4SpacalSteppingAction.cc.
PHG4SpacalSteppingAction::~PHG4SpacalSteppingAction () virtual
destroctor
Definition at line 42 of file PHG4SpacalSteppingAction.cc.
References hit.
Member Function Documentation
double PHG4SpacalSteppingAction::get_zmax ()
Definition at line 376 of file PHG4SpacalSteppingAction.cc.
References detector_, PHG4SpacalDetector::get_geom(), and PHG4CylinderGeomv1::get_zmax().
Referenced by UserSteppingAction().
double PHG4SpacalSteppingAction::get_zmin ()
Definition at line 367 of file PHG4SpacalSteppingAction.cc.
References detector_, PHG4SpacalDetector::get_geom(), and PHG4CylinderGeomv1::get_zmin().
Referenced by UserSteppingAction().
void PHG4SpacalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 331 of file PHG4SpacalSteppingAction.cc.
References absorberhits_, detector_, PHG4Detector::GetName(), hits_, PHG4SpacalDetector::SuperDetector(), and PHG4SteppingAction::verbosity.
Referenced by PHG4SpacalSubsystem::process_event().
bool PHG4SpacalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 52 of file PHG4SpacalSteppingAction.cc.
References PHG4SpacalDetector::ABSORBER, absorberhits_, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4SpacalDetector::FIBER_CLADING, PHG4SpacalDetector::FIBER_CORE, PHG4CylinderGeom_Spacalv1::get_config(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4SpacalDetector::get_geom(), PHG4Hit::get_hit_id(), PHG4SpacalDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4Hit::get_x(), PHG4Hit::get_z(), get_zmax(), get_zmin(), PHG4HitContainer::GetID(), PHG4Detector::GetName(), PHG4SteppingAction::GetName(), PHG4SteppingAction::GetVisibleEnergyDeposition(), hit, hits_, PHG4Hit::identify(), PHG4SpacalDetector::INACTIVE, PHG4SpacalDetector::IsInCylinderActive(), PHG4CylinderGeom_Spacalv3::scint_id_coder::kfiber_bit, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_SameLengthFiberPerTower, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_Tilted, PHG4CylinderGeom_Spacalv1::kFullProjective_2DTaper_Tilted_SameLengthFiberPerTower, PHG4Hit::Reset(), savehitcontainer, savepoststepstatus, saveshower, savetrackid, PHG4CylinderGeom_Spacalv3::scint_id_coder::scint_ID, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_light_yield(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4SteppingAction::StoreLocalCoordinate(), PHG4SpacalDetector::SUPPORT, and PHG4SteppingAction::verbosity.
Member Data Documentation
PHG4HitContainer* PHG4SpacalSteppingAction::absorberhits_ private
Definition at line 50 of file PHG4SpacalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4SpacalDetector* PHG4SpacalSteppingAction::detector_ private
pointer to the detector
Definition at line 46 of file PHG4SpacalSteppingAction.h.
Referenced by get_zmax(), get_zmin(), SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4SpacalSteppingAction::hit private
Definition at line 51 of file PHG4SpacalSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4SpacalSteppingAction().
PHG4HitContainer* PHG4SpacalSteppingAction::hits_ private
pointer to hit container
Definition at line 49 of file PHG4SpacalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4HitContainer* PHG4SpacalSteppingAction::savehitcontainer private
Definition at line 52 of file PHG4SpacalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4SpacalSteppingAction::savepoststepstatus private
Definition at line 55 of file PHG4SpacalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4SpacalSteppingAction::saveshower private
Definition at line 53 of file PHG4SpacalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4SpacalSteppingAction::savetrackid private
Definition at line 54 of file PHG4SpacalSteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SpacalSteppingAction.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SpacalSteppingAction.cc