Class Reference for E1039 Core & Analysis Software: OnlMonUI Class Reference
OnlMonUI Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonUI.h>
Public Member Functions
OnlMonUI (OnlMonClientList_t *list)
~OnlMonUI ()
void SetAutoCycleFlag (bool value)
bool GetAutoCycleFlag ()
void SetCycleInterval (int val)
int GetCycleInterval ()
void Run ()
void UpdateFullSpillRange ()
void HandleSpRadAll ()
void HandleSpRadLast ()
void HandleSpRadRange ()
void HandleSpLastNum ()
void HandleSpEntLo ()
void HandleSpEntHi ()
void HandleSpSlider ()
void SyncSpillRange ()
Protected Member Functions
void BuildInterface ()
void StartBgProc ()
void ExecAutoCycle ()
This function does NOT work at present.
Static Protected Member Functions
static void * FuncAutoCycle (void *arg)
static void * ExecSpillRangeCheck (void *arg)
Detailed Description
Definition at line 16 of file OnlMonUI.h.
Constructor & Destructor Documentation
OnlMonUI()
OnlMonUI::OnlMonUI (OnlMonClientList_t * list)
Definition at line 16 of file OnlMonUI.cc.
~OnlMonUI()
OnlMonUI::~OnlMonUI () inline
Definition at line 38 of file OnlMonUI.h.
Member Function Documentation
BuildInterface()
void OnlMonUI::BuildInterface () protected
Definition at line 32 of file OnlMonUI.cc.
References OnlMonClient::GetClearUsFlag(), HandleSpRadAll(), and OnlMonComm::instance().
Referenced by Run().
ExecAutoCycle()
void OnlMonUI::ExecAutoCycle () protected
This function does NOT work at present.
The call of OnlMonClient::StartMonitor() crashes. The ROOT graphic classes seem not thread-safe since they manage global variables (like gPad). It is hard for me to control when global variables are auto-modified by GUI.
Definition at line 161 of file OnlMonUI.cc.
Referenced by FuncAutoCycle().
ExecSpillRangeCheck()
void * OnlMonUI::ExecSpillRangeCheck (void * arg) static protected
Definition at line 175 of file OnlMonUI.cc.
References UpdateFullSpillRange().
Referenced by StartBgProc().
FuncAutoCycle()
void * OnlMonUI::FuncAutoCycle (void * arg) static protected
Definition at line 148 of file OnlMonUI.cc.
References ExecAutoCycle().
Referenced by StartBgProc().
GetAutoCycleFlag()
bool OnlMonUI::GetAutoCycleFlag () inline
Definition at line 41 of file OnlMonUI.h.
GetCycleInterval()
int OnlMonUI::GetCycleInterval () inline
Definition at line 43 of file OnlMonUI.h.
HandleSpEntHi()
void OnlMonUI::HandleSpEntHi ()
Definition at line 263 of file OnlMonUI.cc.
References OnlMonComm::instance(), OnlMonComm::SetSpillRangeHigh(), and SyncSpillRange().
HandleSpEntLo()
void OnlMonUI::HandleSpEntLo ()
Definition at line 257 of file OnlMonUI.cc.
References OnlMonComm::instance(), OnlMonComm::SetSpillRangeLow(), and SyncSpillRange().
HandleSpLastNum()
void OnlMonUI::HandleSpLastNum ()
Definition at line 250 of file OnlMonUI.cc.
References OnlMonComm::instance(), and OnlMonComm::SetSpillNum().
HandleSpRadAll()
void OnlMonUI::HandleSpRadAll ()
Definition at line 210 of file OnlMonUI.cc.
References OnlMonComm::instance(), OnlMonComm::SetSpillMode(), and OnlMonComm::SP_ALL.
Referenced by BuildInterface().
HandleSpRadLast()
void OnlMonUI::HandleSpRadLast ()
Definition at line 221 of file OnlMonUI.cc.
References OnlMonComm::instance(), OnlMonComm::SetSpillMode(), and OnlMonComm::SP_LAST.
HandleSpRadRange()
void OnlMonUI::HandleSpRadRange ()
Definition at line 232 of file OnlMonUI.cc.
References OnlMonComm::GetFullSpillRange(), OnlMonComm::instance(), OnlMonComm::SetSpillMode(), OnlMonComm::SetSpillRange(), OnlMonComm::SP_RANGE, SyncSpillRange(), and UpdateFullSpillRange().
HandleSpSlider()
void OnlMonUI::HandleSpSlider ()
Definition at line 269 of file OnlMonUI.cc.
References OnlMonComm::instance(), OnlMonComm::SetSpillRange(), and SyncSpillRange().
Run()
void OnlMonUI::Run ()
Definition at line 26 of file OnlMonUI.cc.
References BuildInterface(), and StartBgProc().
SetAutoCycleFlag()
void OnlMonUI::SetAutoCycleFlag (bool value) inline
Definition at line 40 of file OnlMonUI.h.
SetCycleInterval()
void OnlMonUI::SetCycleInterval (int val) inline
Definition at line 42 of file OnlMonUI.h.
StartBgProc()
void OnlMonUI::StartBgProc () protected
Definition at line 142 of file OnlMonUI.cc.
References ExecSpillRangeCheck(), FuncAutoCycle(), and NULL.
Referenced by Run().
SyncSpillRange()
void OnlMonUI::SyncSpillRange ()
Definition at line 277 of file OnlMonUI.cc.
References OnlMonComm::GetSpillRange(), and OnlMonComm::instance().
Referenced by HandleSpEntHi(), HandleSpEntLo(), HandleSpRadRange(), and HandleSpSlider().
UpdateFullSpillRange()
void OnlMonUI::UpdateFullSpillRange ()
Definition at line 185 of file OnlMonUI.cc.
References OnlMonComm::GetFullSpillRange(), OnlMonComm::GetSpillSelectability(), OnlMonComm::instance(), and OnlMonComm::ReceiveFullSpillRange().
Referenced by ExecSpillRangeCheck(), and HandleSpRadRange().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonUI.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonUI.cc