Class Reference for E1039 Core & Analysis Software: PHG4TrackUserInfoV1 Class Reference
PHG4TrackUserInfoV1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4TrackUserInfoV1.h>
Public Member Functions
PHG4TrackUserInfoV1 ()
virtual ~PHG4TrackUserInfoV1 ()
void Print () const
void SetUserTrackId (const int val)
int GetUserTrackId () const
void SetUserParentId (const int val)
int GetUserParentId () const
void SetUserPrimaryId (const int val)
int GetUserPrimaryId () const
void SetWanted (const int val)
int GetWanted () const
void SetKeep (const int val)
int GetKeep () const
void SetShower (PHG4Shower *ptr)
PHG4Shower * GetShower () const
Detailed Description
Definition at line 15 of file PHG4TrackUserInfoV1.h.
Constructor & Destructor Documentation
PHG4TrackUserInfoV1()
PHG4TrackUserInfoV1::PHG4TrackUserInfoV1 () inline
Definition at line 18 of file PHG4TrackUserInfoV1.h.
~PHG4TrackUserInfoV1()
virtual PHG4TrackUserInfoV1::~PHG4TrackUserInfoV1 () inline virtual
Definition at line 21 of file PHG4TrackUserInfoV1.h.
Member Function Documentation
GetKeep()
int PHG4TrackUserInfoV1::GetKeep () const inline
Definition at line 45 of file PHG4TrackUserInfoV1.h.
GetShower()
PHG4Shower* PHG4TrackUserInfoV1::GetShower () const inline
Definition at line 48 of file PHG4TrackUserInfoV1.h.
GetUserParentId()
int PHG4TrackUserInfoV1::GetUserParentId () const inline
Definition at line 36 of file PHG4TrackUserInfoV1.h.
GetUserPrimaryId()
int PHG4TrackUserInfoV1::GetUserPrimaryId () const inline
Definition at line 39 of file PHG4TrackUserInfoV1.h.
GetUserTrackId()
int PHG4TrackUserInfoV1::GetUserTrackId () const inline
Definition at line 33 of file PHG4TrackUserInfoV1.h.
GetWanted()
int PHG4TrackUserInfoV1::GetWanted () const inline
Definition at line 42 of file PHG4TrackUserInfoV1.h.
Print()
void PHG4TrackUserInfoV1::Print () const inline
Definition at line 23 of file PHG4TrackUserInfoV1.h.
SetKeep()
void PHG4TrackUserInfoV1::SetKeep (const int val) inline
Definition at line 44 of file PHG4TrackUserInfoV1.h.
Referenced by PHG4TrackUserInfo::SetKeep().
SetShower()
void PHG4TrackUserInfoV1::SetShower (PHG4Shower * ptr) inline
Definition at line 47 of file PHG4TrackUserInfoV1.h.
Referenced by PHG4TrackUserInfo::SetShower().
SetUserParentId()
void PHG4TrackUserInfoV1::SetUserParentId (const int val) inline
Definition at line 35 of file PHG4TrackUserInfoV1.h.
Referenced by PHG4TrackUserInfo::SetUserParentId().
SetUserPrimaryId()
void PHG4TrackUserInfoV1::SetUserPrimaryId (const int val) inline
Definition at line 38 of file PHG4TrackUserInfoV1.h.
Referenced by PHG4TrackUserInfo::SetUserPrimaryId().
SetUserTrackId()
void PHG4TrackUserInfoV1::SetUserTrackId (const int val) inline
Definition at line 32 of file PHG4TrackUserInfoV1.h.
Referenced by PHG4TrackUserInfo::SetUserTrackId().
SetWanted()
void PHG4TrackUserInfoV1::SetWanted (const int val) inline
Definition at line 41 of file PHG4TrackUserInfoV1.h.
Referenced by PHG4TrackUserInfo::SetWanted().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4TrackUserInfoV1.h