Class Reference for E1039 Core & Analysis Software: PHG4BlockGeomContainer Class Reference
PHG4BlockGeomContainer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockGeomContainer.h>
Public Types
typedef std::map< int, PHG4BlockGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator, Iterator > Range
typedef std::pair< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHG4BlockGeomContainer ()
virtual ~PHG4BlockGeomContainer ()
void identify (std::ostream &os=std::cout) const
int AddLayerGeom (const int i, PHG4BlockGeom *mygeom)
int AddLayerGeom (PHG4BlockGeom *mygeom)
PHG4BlockGeom * GetLayerGeom (const int i)
int get_NLayers () const
std::pair< std::map< int, PHG4BlockGeom * >::const_iterator, std::map< int, PHG4BlockGeom * >::const_iterator > get_begin_end () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
std::map< int, PHG4BlockGeom * > _layergeoms
float _magfield
Detailed Description
Definition at line 10 of file PHG4BlockGeomContainer.h.
Member Typedef Documentation
ConstIterator
typedef Map::const_iterator PHG4BlockGeomContainer::ConstIterator
Definition at line 15 of file PHG4BlockGeomContainer.h.
ConstRange
typedef std::pair<ConstIterator, ConstIterator> PHG4BlockGeomContainer::ConstRange
Definition at line 17 of file PHG4BlockGeomContainer.h.
Iterator
typedef Map::iterator PHG4BlockGeomContainer::Iterator
Definition at line 14 of file PHG4BlockGeomContainer.h.
Map
typedef std::map<int,PHG4BlockGeom *> PHG4BlockGeomContainer::Map
Definition at line 13 of file PHG4BlockGeomContainer.h.
Range
typedef std::pair<Iterator, Iterator> PHG4BlockGeomContainer::Range
Definition at line 16 of file PHG4BlockGeomContainer.h.
Constructor & Destructor Documentation
PHG4BlockGeomContainer()
PHG4BlockGeomContainer::PHG4BlockGeomContainer ()
Definition at line 7 of file PHG4BlockGeomContainer.cc.
~PHG4BlockGeomContainer()
PHG4BlockGeomContainer::~PHG4BlockGeomContainer () virtual
Definition at line 13 of file PHG4BlockGeomContainer.cc.
Member Function Documentation
AddLayerGeom() [1/2]
int PHG4BlockGeomContainer::AddLayerGeom (const int i, PHG4BlockGeom * mygeom)
Definition at line 37 of file PHG4BlockGeomContainer.cc.
References PHG4BlockGeom::set_layer().
Referenced by PHG4BlockSubsystem::InitRunSubsystem(), PHG4CollimatorSubsystem::InitRunSubsystem(), and PHG4SquareTubeSubsystem::InitRunSubsystem().
AddLayerGeom() [2/2]
int PHG4BlockGeomContainer::AddLayerGeom (PHG4BlockGeom * mygeom)
Definition at line 50 of file PHG4BlockGeomContainer.cc.
References PHG4BlockGeom::get_layer().
get_begin_end()
std::pair<std::map<int,PHG4BlockGeom *>::const_iterator, std::map<int,PHG4BlockGeom *>::const_iterator> PHG4BlockGeomContainer::get_begin_end () const inline
Definition at line 28 of file PHG4BlockGeomContainer.h.
References _layergeoms.
Referenced by PHG4BlockCellReco::InitRun().
get_NLayers()
int PHG4BlockGeomContainer::get_NLayers () const inline
Definition at line 27 of file PHG4BlockGeomContainer.h.
References _layergeoms.
GetLayerGeom()
PHG4BlockGeom * PHG4BlockGeomContainer::GetLayerGeom (const int i)
Definition at line 63 of file PHG4BlockGeomContainer.cc.
References NULL.
identify()
void PHG4BlockGeomContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 24 of file PHG4BlockGeomContainer.cc.
Referenced by PHG4BlockCellReco::InitRun().
Member Data Documentation
_layergeoms
std::map<int,PHG4BlockGeom *> PHG4BlockGeomContainer::_layergeoms protected
Definition at line 31 of file PHG4BlockGeomContainer.h.
Referenced by get_begin_end(), and get_NLayers().
_magfield
float PHG4BlockGeomContainer::_magfield protected
Definition at line 32 of file PHG4BlockGeomContainer.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockGeomContainer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4BlockGeomContainer.cc