E1039 Software: PHFieldSeaQuest Class Reference
PHFieldSeaQuest Class Reference
untested code - I don't know if this is being used, drop me a line (with the field) and I test this - Chris P.
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHField/PHFieldSeaQuest.h>
Public Member Functions
PHFieldSeaQuest (const std::string &fmag_name, const std::string &kmag_name, const double fmag_scale=1.0, const double kmag_scale=1.0, const double targermag_y=5.0)
virtual ~PHFieldSeaQuest ()
void GetFieldValue (const double Point[4], double *Bfield) const
void identify (std::ostream &os=std::cout) const
Public Member Functions inherited from PHField
PHField (const int verb=0)
constructor
virtual ~PHField ()
void Verbosity (const int i)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
float zValues [4]
float kmagZOffset
PHField3DCartesian fmag
PHField3DCartesian kmag
PHFieldRegionalConst targetmag
Protected Attributes inherited from PHField
unsigned verb_
Detailed Description
untested code - I don't know if this is being used, drop me a line (with the field) and I test this - Chris P.
Definition at line 12 of file PHFieldSeaQuest.h.
Constructor & Destructor Documentation
PHFieldSeaQuest()
PHFieldSeaQuest::PHFieldSeaQuest (const std::string & fmag_name, const std::string & kmag_name, const double fmag_scale = 1.0, const double kmag_scale = 1.0, const double targermag_y = 5.0)
Definition at line 16 of file PHFieldSeaQuest.cc.
References kmagZOffset, PHFieldRegionalConst::set_mean_x(), PHFieldRegionalConst::set_mean_y(), PHFieldRegionalConst::set_mean_z(), targetmag, and zValues.
~PHFieldSeaQuest()
PHFieldSeaQuest::~PHFieldSeaQuest () virtual
Definition at line 39 of file PHFieldSeaQuest.cc.
Member Function Documentation
GetFieldValue()
void PHFieldSeaQuest::GetFieldValue (const double Point[4], double * Bfield) const virtual
access field value Follow the convention of G4ElectroMagneticField
Parameters
[in] Point space time coordinate. x, y, z, t in Geant4/CLHEP units
[out] Bfield field value. In the case of magnetic field, the order is Bx, By, Bz in in Geant4/CLHEP units
Implements PHField.
Definition at line 46 of file PHFieldSeaQuest.cc.
References fmag, PHField3DCartesian::GetFieldValue(), PHFieldRegionalConst::GetFieldValue(), kmag, kmagZOffset, targetmag, and zValues.
Referenced by identify().
identify()
void PHFieldSeaQuest::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHField.
Definition at line 73 of file PHFieldSeaQuest.cc.
References GetFieldValue().
Member Data Documentation
fmag
PHField3DCartesian PHFieldSeaQuest::fmag protected
Definition at line 35 of file PHFieldSeaQuest.h.
Referenced by GetFieldValue().
kmag
PHField3DCartesian PHFieldSeaQuest::kmag protected
Definition at line 36 of file PHFieldSeaQuest.h.
Referenced by GetFieldValue().
kmagZOffset
float PHFieldSeaQuest::kmagZOffset protected
Definition at line 33 of file PHFieldSeaQuest.h.
Referenced by GetFieldValue(), and PHFieldSeaQuest().
targetmag
PHFieldRegionalConst PHFieldSeaQuest::targetmag protected
Definition at line 37 of file PHFieldSeaQuest.h.
Referenced by GetFieldValue(), and PHFieldSeaQuest().
zValues
float PHFieldSeaQuest::zValues[4] protected
Definition at line 32 of file PHFieldSeaQuest.h.
Referenced by GetFieldValue(), and PHFieldSeaQuest().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHField/PHFieldSeaQuest.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHField/PHFieldSeaQuest.cc