Class Reference for E1039 Core & Analysis Software: SQTrackletFitter Class Reference
SQTrackletFitter Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQTrackletFitter.h>
Public Member Functions
SQTrackletFitter (bool KMAG_ON=true)
~SQTrackletFitter ()
int fit (Tracklet &tracklet)
core function - fit the tracklet and return the fit status
double getParameter (int idx)
retrieve the fit parameter value and error
double getParaError (int idx)
double getChi2 ()
retrieve the chi2
Detailed Description
Definition at line 10 of file SQTrackletFitter.h.
Constructor & Destructor Documentation
SQTrackletFitter()
SQTrackletFitter::SQTrackletFitter (bool KMAG_ON = true)
Definition at line 5 of file SQTrackletFitter.cxx.
References Tracklet::Eval(), PHFlag::get_DoubleFlag(), and recoConsts::instance().
~SQTrackletFitter()
SQTrackletFitter::~SQTrackletFitter ()
Definition at line 27 of file SQTrackletFitter.cxx.
Member Function Documentation
fit()
int SQTrackletFitter::fit (Tracklet & tracklet)
core function - fit the tracklet and return the fit status
Avoid too-small error, which causes NaN in Tracklet::operator+().
Definition at line 32 of file SQTrackletFitter.cxx.
References Tracklet::chisq, Tracklet::err_invP, Tracklet::err_tx, Tracklet::err_ty, Tracklet::err_x0, Tracklet::err_y0, Tracklet::invP, Tracklet::tx, Tracklet::ty, Tracklet::x0, and Tracklet::y0.
Referenced by KalmanFastTracking::fitTracklet().
getChi2()
double SQTrackletFitter::getChi2 () inline
retrieve the chi2
Definition at line 24 of file SQTrackletFitter.h.
getParaError()
double SQTrackletFitter::getParaError (int idx) inline
Definition at line 21 of file SQTrackletFitter.h.
getParameter()
double SQTrackletFitter::getParameter (int idx) inline
retrieve the fit parameter value and error
Definition at line 20 of file SQTrackletFitter.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQTrackletFitter.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/SQTrackletFitter.cxx