Class Reference for E1039 Core & Analysis Software: FlagSavev1 Class Reference
FlagSavev1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/FlagSavev1.h>
Public Member Functions
FlagSavev1 ()
ctor
virtual ~FlagSavev1 ()
dtor
FlagSavev1 * clone () const
Virtual copy constructor.
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains valid data
void identify (std::ostream &os=std::cout) const
int FillFromPHFlag (const PHFlag *flags)
int PutFlagsBack (PHFlag *flags)
Public Member Functions inherited from FlagSave
virtual ~FlagSave ()
dtor
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
int FillIntFromPHFlag (const PHFlag *flags)
int FillDoubleFromPHFlag (const PHFlag *flags)
int FillFloatFromPHFlag (const PHFlag *flags)
int FillCharFromPHFlag (const PHFlag *flags)
int PutIntToPHFlag (PHFlag *flags)
int PutDoubleToPHFlag (PHFlag *flags)
int PutFloatToPHFlag (PHFlag *flags)
int PutCharToPHFlag (PHFlag *flags)
void PrintIntFlag (std::ostream &os) const
void PrintDoubleFlag (std::ostream &os) const
void PrintFloatFlag (std::ostream &os) const
void PrintStringFlag (std::ostream &os) const
Protected Attributes
std::map< std::string, int > intflag
std::map< std::string, double > doubleflag
std::map< std::string, float > floatflag
std::map< std::string, std::string > stringflag
Detailed Description
Definition at line 12 of file FlagSavev1.h.
Constructor & Destructor Documentation
FlagSavev1()
FlagSavev1::FlagSavev1 () inline
ctor
Definition at line 17 of file FlagSavev1.h.
~FlagSavev1()
virtual FlagSavev1::~FlagSavev1 () inline virtual
dtor
Definition at line 19 of file FlagSavev1.h.
Member Function Documentation
clone()
FlagSavev1 * FlagSavev1::clone () const virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 7 of file FlagSavev1.cc.
References doubleflag, floatflag, intflag, and stringflag.
FillCharFromPHFlag()
int FlagSavev1::FillCharFromPHFlag (const PHFlag * flags) protected
Definition at line 101 of file FlagSavev1.cc.
References PHFlag::CharMap().
FillDoubleFromPHFlag()
int FlagSavev1::FillDoubleFromPHFlag (const PHFlag * flags) protected
Definition at line 77 of file FlagSavev1.cc.
References PHFlag::DoubleMap().
FillFloatFromPHFlag()
int FlagSavev1::FillFloatFromPHFlag (const PHFlag * flags) protected
Definition at line 89 of file FlagSavev1.cc.
References PHFlag::FloatMap().
FillFromPHFlag()
int FlagSavev1::FillFromPHFlag (const PHFlag * flags) virtual
Reimplemented from FlagSave.
Definition at line 44 of file FlagSavev1.cc.
FillIntFromPHFlag()
int FlagSavev1::FillIntFromPHFlag (const PHFlag * flags) protected
Definition at line 65 of file FlagSavev1.cc.
References PHFlag::IntMap().
identify()
void FlagSavev1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from FlagSave.
Definition at line 33 of file FlagSavev1.cc.
isValid()
int FlagSavev1::isValid () const virtual
isValid returns non zero if object contains valid data
Reimplemented from FlagSave.
Definition at line 20 of file FlagSavev1.cc.
PrintDoubleFlag()
void FlagSavev1::PrintDoubleFlag (std::ostream & os) const protected
Definition at line 174 of file FlagSavev1.cc.
PrintFloatFlag()
void FlagSavev1::PrintFloatFlag (std::ostream & os) const protected
Definition at line 190 of file FlagSavev1.cc.
PrintIntFlag()
void FlagSavev1::PrintIntFlag (std::ostream & os) const protected
Definition at line 158 of file FlagSavev1.cc.
PrintStringFlag()
void FlagSavev1::PrintStringFlag (std::ostream & os) const protected
Definition at line 206 of file FlagSavev1.cc.
PutCharToPHFlag()
int FlagSavev1::PutCharToPHFlag (PHFlag * flags) protected
Definition at line 147 of file FlagSavev1.cc.
References PHFlag::set_CharFlag().
PutDoubleToPHFlag()
int FlagSavev1::PutDoubleToPHFlag (PHFlag * flags) protected
Definition at line 125 of file FlagSavev1.cc.
References PHFlag::set_DoubleFlag().
PutFlagsBack()
int FlagSavev1::PutFlagsBack (PHFlag * flags) virtual
Reimplemented from FlagSave.
Definition at line 54 of file FlagSavev1.cc.
PutFloatToPHFlag()
int FlagSavev1::PutFloatToPHFlag (PHFlag * flags) protected
Definition at line 136 of file FlagSavev1.cc.
References PHFlag::set_FloatFlag().
PutIntToPHFlag()
int FlagSavev1::PutIntToPHFlag (PHFlag * flags) protected
Definition at line 114 of file FlagSavev1.cc.
References PHFlag::set_IntFlag().
Reset()
void FlagSavev1::Reset () inline virtual
Clear Event.
Reimplemented from FlagSave.
Definition at line 24 of file FlagSavev1.h.
Member Data Documentation
doubleflag
std::map<std::string, double> FlagSavev1::doubleflag protected
Definition at line 52 of file FlagSavev1.h.
Referenced by clone().
floatflag
std::map<std::string, float> FlagSavev1::floatflag protected
Definition at line 53 of file FlagSavev1.h.
Referenced by clone().
intflag
std::map<std::string, int> FlagSavev1::intflag protected
Definition at line 51 of file FlagSavev1.h.
Referenced by clone().
stringflag
std::map<std::string, std::string> FlagSavev1::stringflag protected
Definition at line 54 of file FlagSavev1.h.
Referenced by clone().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/FlagSavev1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/framework/ffaobjects/FlagSavev1.cc