Class Reference for E1039 Core & Analysis Software: SQDimuonVector Class Reference
SQDimuonVector Class Reference abstract
An SQ interface class to hold a list of SQDimuon objects.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQDimuonVector.h>
Public Types
typedef std::vector< SQDimuon * > Vector
typedef std::vector< SQDimuon * >::const_iterator ConstIter
typedef std::vector< SQDimuon * >::iterator Iter
Public Member Functions
virtual ~SQDimuonVector ()
virtual void identify (std::ostream &os=std::cout) const =0
virtual void Reset ()=0
Clear Event.
virtual int isValid () const =0
isValid returns non zero if object contains vailid data
virtual SQDimuonVector * Clone () const =0
virtual ConstIter begin () const =0
virtual ConstIter end () const =0
virtual Iter begin ()=0
virtual Iter end ()=0
virtual bool empty () const =0
virtual size_t size () const =0
virtual void clear ()=0
virtual const SQDimuon * at (const size_t id) const =0
virtual SQDimuon * at (const size_t id)=0
virtual void push_back (const SQDimuon *dim)=0
virtual size_t erase (const size_t id)=0
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQDimuonVector ()
ClassDef (SQDimuonVector, 1)
Detailed Description
An SQ interface class to hold a list of SQDimuon objects.
Below is the standard way to find this object in "topNode" and loop over each dimuon;
SQDimuonVector* dim_vec = findNode::getClass<SQDimuonVector>(topNode, "SQDimuonVector");
for (SQDimuonVector::ConstIter it = dim_vec->begin(); it != dim_vec->end(); it++) {
  SQDimuon* dim = *it;
  int dim_id = dim->get_dimuon_id();
}
Definition at line 19 of file SQDimuonVector.h.
Member Typedef Documentation
ConstIter
typedef std::vector<SQDimuon*>::const_iterator SQDimuonVector::ConstIter
Definition at line 22 of file SQDimuonVector.h.
Iter
typedef std::vector<SQDimuon*>::iterator SQDimuonVector::Iter
Definition at line 23 of file SQDimuonVector.h.
Vector
typedef std::vector<SQDimuon*> SQDimuonVector::Vector
Definition at line 21 of file SQDimuonVector.h.
Constructor & Destructor Documentation
~SQDimuonVector()
virtual SQDimuonVector::~SQDimuonVector () inline virtual
Definition at line 25 of file SQDimuonVector.h.
SQDimuonVector()
SQDimuonVector::SQDimuonVector () inline protected
Definition at line 46 of file SQDimuonVector.h.
Member Function Documentation
at() [1/2]
virtual const SQDimuon* SQDimuonVector::at (const size_t id) const pure virtual
Implemented in SQDimuonVector_v1.
Referenced by AnaSimDst::process_event(), MakeMyTree::process_event(), TracePHG4Particle::process_event(), AnaSimDimuon::process_event(), SubsysRecoSignal::process_event(), AnaEmbeddedData::process_event(), SimpleTree::process_event(), and SQTruthVertexing::process_event().
at() [2/2]
virtual SQDimuon* SQDimuonVector::at (const size_t id) pure virtual
Implemented in SQDimuonVector_v1.
begin() [1/2]
virtual ConstIter SQDimuonVector::begin () const pure virtual
Implemented in SQDimuonVector_v1.
Referenced by UtilDimuon::FindDimuonByID(), and DoEmbedding::process_event().
begin() [2/2]
virtual Iter SQDimuonVector::begin () pure virtual
Implemented in SQDimuonVector_v1.
ClassDef()
SQDimuonVector::ClassDef (SQDimuonVector , 1) protected
clear()
virtual void SQDimuonVector::clear () pure virtual
Implemented in SQDimuonVector_v1.
Referenced by TruthNodeMaker::process_event().
Clone()
virtual SQDimuonVector* SQDimuonVector::Clone () const pure virtual
Implemented in SQDimuonVector_v1.
empty()
virtual bool SQDimuonVector::empty () const pure virtual
Implemented in SQDimuonVector_v1.
end() [1/2]
virtual ConstIter SQDimuonVector::end () const pure virtual
Implemented in SQDimuonVector_v1.
Referenced by UtilDimuon::FindDimuonByID(), and DoEmbedding::process_event().
end() [2/2]
virtual Iter SQDimuonVector::end () pure virtual
Implemented in SQDimuonVector_v1.
erase()
virtual size_t SQDimuonVector::erase (const size_t id) pure virtual
Implemented in SQDimuonVector_v1.
identify()
virtual void SQDimuonVector::identify (std::ostream & os = std::cout) const pure virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Implemented in SQDimuonVector_v1.
isValid()
virtual int SQDimuonVector::isValid () const pure virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Implemented in SQDimuonVector_v1.
push_back()
virtual void SQDimuonVector::push_back (const SQDimuon * dim) pure virtual
Implemented in SQDimuonVector_v1.
Referenced by DoEmbedding::process_event(), SQTruthVertexing::process_event(), and TruthNodeMaker::process_event().
Reset()
virtual void SQDimuonVector::Reset () pure virtual
Clear Event.
Reimplemented from PHObject.
Implemented in SQDimuonVector_v1.
size()
virtual size_t SQDimuonVector::size () const pure virtual
Implemented in SQDimuonVector_v1.
Referenced by AnaSimDst::process_event(), MakeMyTree::process_event(), TracePHG4Particle::process_event(), AnaSimDimuon::process_event(), SubsysRecoSignal::process_event(), AnaEmbeddedData::process_event(), DoEmbedding::process_event(), SimpleTree::process_event(), and SQTruthVertexing::process_event().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQDimuonVector.h