Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/E1039Shielding/ana.C File Reference
ana.C File Reference
Functions
double ratio_error (const double a, const double b, const double ea, const double eb)
double binom_error (const double a, const double b)
TH1D * getEffHist (const char *hname, const TH1D *h1, const TH1D *h2)
void drawRelAcc ()
void drawAccPhi ()
void drawSnglAccPz ()
void ana ()
Function Documentation
void ana ()
Definition at line 291 of file ana.C.
References drawSnglAccPz().
Referenced by Fun4All_G4_BNL(), Fun4All_G4_BNL_R1(), Fun4All_G4_E1039(), Fun4All_G4_E1039_R1(), Fun4All_G4_E1039_R2(), Fun4All_G4_E1039_R2_V2(), Fun4E1039Shielding(), Fun4EMCal(), Fun4HodoAccGap(), Fun4Pythia8Demo(), Fun4Sim(), Fun4TrkDev(), RecoE1039Sim(), and run().
double binom_error (const double a, const double b)
Definition at line 16 of file ana.C.
Referenced by getEffHist().
void drawAccPhi ()
Definition at line 94 of file ana.C.
References c1, and getEffHist().
void drawRelAcc ()
Definition at line 53 of file ana.C.
Referenced by ana().
void drawSnglAccPz ()
Definition at line 191 of file ana.C.
References c1, and getEffHist().
Referenced by ana().
TH1D* getEffHist (const char * hname, const TH1D * h1, const TH1D * h2)
Definition at line 24 of file ana.C.
References binom_error().
Referenced by drawAccMass(), drawAccPhi(), and drawSnglAccPz().
double ratio_error (const double a, const double b, const double ea, const double eb)
Definition at line 3 of file ana.C.