Class Reference for E1039 Core & Analysis Software: SQMCEvent Class Reference
SQMCEvent Class Reference abstract
An SQ interface class to hold one simulated-event header.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQMCEvent.h>
Public Member Functions
virtual ~SQMCEvent ()
virtual void identify (std::ostream &os=std::cout) const =0
virtual void Reset ()=0
Clear Event.
virtual int isValid () const =0
isValid returns non zero if object contains vailid data
virtual SQMCEvent * Clone () const =0
virtual int get_process_id () const =0
Return the primary process ID.
virtual void set_process_id (const int a)=0
virtual double get_cross_section () const =0
Return the cross section.
virtual void set_cross_section (const double a)=0
virtual double get_weight () const =0
Return the event weight.
virtual void set_weight (const double a)=0
virtual int get_particle_id (const int i) const =0
Return the particle ID of the primary process, where i=0...3 for "0 + 1 -> 2 + 3".
virtual void set_particle_id (const int i, const int a)=0
virtual TLorentzVector get_particle_momentum (const int i) const =0
Return the particle momentum of the primary process, where i=0...3 for "0 + 1 -> 2 + 3".
virtual void set_particle_momentum (const int i, const TLorentzVector a)=0
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQMCEvent ()
ClassDef (SQMCEvent, 1)
Detailed Description
An SQ interface class to hold one simulated-event header.
It holds a set of variables that are peculiar to simulated event. All other variables that are common to real event are held by SQEvent.
Definition at line 12 of file SQMCEvent.h.
Constructor & Destructor Documentation
~SQMCEvent()
virtual SQMCEvent::~SQMCEvent () inline virtual
Definition at line 14 of file SQMCEvent.h.
SQMCEvent()
SQMCEvent::SQMCEvent () inline protected
Definition at line 37 of file SQMCEvent.h.
Member Function Documentation
ClassDef()
SQMCEvent::ClassDef (SQMCEvent , 1) protected
Clone()
virtual SQMCEvent* SQMCEvent::Clone () const pure virtual
Implemented in SQMCEvent_v1.
get_cross_section()
virtual double SQMCEvent::get_cross_section () const pure virtual
Return the cross section.
Implemented in SQMCEvent_v1.
Referenced by SubsysRecoBG::process_event(), and AnaPileup::process_event().
get_particle_id()
virtual int SQMCEvent::get_particle_id (const int i) const pure virtual
Return the particle ID of the primary process, where i=0...3 for "0 + 1 -> 2 + 3".
Implemented in SQMCEvent_v1.
Referenced by AnaSimDst::process_event(), TracePHG4Particle::process_event(), AnaSimDimuon::process_event(), and SimpleTree::process_event().
get_particle_momentum()
virtual TLorentzVector SQMCEvent::get_particle_momentum (const int i) const pure virtual
Return the particle momentum of the primary process, where i=0...3 for "0 + 1 -> 2 + 3".
Implemented in SQMCEvent_v1.
Referenced by AnaSimDst::process_event(), AnaSimDimuon::process_event(), and SimpleTree::process_event().
get_process_id()
virtual int SQMCEvent::get_process_id () const pure virtual
Return the primary process ID.
Implemented in SQMCEvent_v1.
Referenced by AnaSimDst::process_event(), TracePHG4Particle::process_event(), AnaSimDimuon::process_event(), and SimpleTree::process_event().
get_weight()
virtual double SQMCEvent::get_weight () const pure virtual
Return the event weight.
Implemented in SQMCEvent_v1.
Referenced by AnaSimDst::process_event(), TracePHG4Particle::process_event(), AnaSimDimuon::process_event(), SubsysRecoSignal::process_event(), and AnaEmbeddedData::process_event().
identify()
virtual void SQMCEvent::identify (std::ostream & os = std::cout) const pure virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Implemented in SQMCEvent_v1.
isValid()
virtual int SQMCEvent::isValid () const pure virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Implemented in SQMCEvent_v1.
Reset()
virtual void SQMCEvent::Reset () pure virtual
Clear Event.
Reimplemented from PHObject.
Implemented in SQMCEvent_v1.
set_cross_section()
virtual void SQMCEvent::set_cross_section (const double a) pure virtual
Implemented in SQMCEvent_v1.
Referenced by PHG4SimpleEventGenerator::process_event().
set_particle_id()
virtual void SQMCEvent::set_particle_id (const int i, const int a) pure virtual
Implemented in SQMCEvent_v1.
Referenced by TruthNodeMaker::process_event().
set_particle_momentum()
virtual void SQMCEvent::set_particle_momentum (const int i, const TLorentzVector a) pure virtual
Implemented in SQMCEvent_v1.
Referenced by TruthNodeMaker::process_event().
set_process_id()
virtual void SQMCEvent::set_process_id (const int a) pure virtual
Implemented in SQMCEvent_v1.
Referenced by TruthNodeMaker::process_event().
set_weight()
virtual void SQMCEvent::set_weight (const double a) pure virtual
Implemented in SQMCEvent_v1.
Referenced by PHG4SimpleEventGenerator::process_event().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQMCEvent.h