E1039 Software: VertexFit Class Reference
VertexFit Class Reference
#include </dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/ktracker/VertexFit.h>
Public Member Functions
VertexFit (const std::string &name="VertexFit")
~VertexFit ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void enableOptimization ()
Enable the optimization of final dimuon vertex z position.
void setControlParameter (int nMaxIteration, double tolerance)
Set the convergence control parameters.
int setRecEvent (SRecEvent *recEvent, int sign1=1, int sign2=-1)
Set the SRecEvent, main external call the use vertex fit.
void init ()
Initialize and reset.
void addHypothesis (double z, double sigz=50.)
void setStartingVertex (double z_start, double sigz_start)
void addTrack (int index, SRecTrack &_track)
Add one track parameter set into the fit.
void addTrack (int index, KalmanTrack &_track)
void addTrack (int index, TrkPar &_trkpar)
int processOnePair ()
After setting both tracks and hypothesis, start the iteration.
int findVertex ()
Find the primary vertex.
double findDimuonVertexFast (SRecTrack &track1, SRecTrack &track2)
double findSingleMuonVertex (SRecTrack &_track)
double findSingleMuonVertex (Node &_node_start)
double findSingleMuonVertex (TrkPar &_trkpar_start)
double getVertexZ0 ()
Gets.
double getVXChisq ()
double getKFChisq ()
int getNTracks ()
void updateVertex ()
Core function, update the vertex prediction according to the track info.
void bookEvaluation (std::string evalFileName="vtx_eval.root")
Evaluation.
void fillEvaluation ()
void print ()
Debugging output.
const std::string & get_eval_file_name () const
void set_eval_file_name (const std::string &evalFileName)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int InitField (PHCompositeNode *topNode)
int InitGeom (PHCompositeNode *topNode)
int MakeNodes (PHCompositeNode *topNode)
int GetNodes (PHCompositeNode *topNode)
Private Attributes
std::vector< TrkPar > _trkpar_curr
storage of the input track parameters
VtxPar _vtxpar_curr
vertex parameter
Node _node_vertex
Kalman node at the vertex.
KalmanFilter * _kmfit
pointer to external Kalman filter
double _chisq_vertex
chi squares
double _chisq_kalman
std::vector< double > z_start
Starting points.
std::vector< double > sig_z_start
std::vector< double > z_vertex
Temporary results.
std::vector< double > r_vertex
std::vector< double > chisq_km
std::vector< double > chisq_vx
int _max_iteration
convergence control parameter
double _tolerance
GenFitExtrapolator _extrapolator
Track extrapolator.
bool optimize
Flag to enable/disable optimization of final position.
JobOptsSvc * p_jobOptsSvc
TGeoManager * _t_geo_manager
SRecEvent * _recEvent
std::string evalFileName
Evaluation file and tree.
TFile * evalFile
TTree * evalTree
int runID
int eventID
int targetPos
int nPos
int nNeg
int p_idx_eval
int m_idx_eval
int choice_eval
int choice_by_kf_eval
int choice_by_vx_eval
int nStart
double z_start_eval [50]
int nIter_eval [50]
double chisq_kf_eval [50]
double chisq_vx_eval [50]
double z_vertex_eval [50]
double r_vertex_eval [50]
double m_chisq_kf_eval
double s_chisq_kf_eval
double m_z_vertex_eval
double s_z_vertex_eval
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 63 of file VertexFit.h.
Constructor & Destructor Documentation
VertexFit::VertexFit (const std::string & name = "VertexFit")
In construction, initialize the projector for the vertex node
disable target optimization by default
disable evaluation by default
Definition at line 46 of file VertexFit.cxx.
References _max_iteration, _node_vertex, _tolerance, BEAM_SPOT_X, BEAM_SPOT_Y, evalFile, evalFileName, evalTree, Node::getMeasurement(), Node::getMeasurementCov(), Node::getProjector(), JobOptsSvc::instance(), optimize, p_jobOptsSvc, X_VTX, and Y_VTX.
VertexFit::~VertexFit ()
Definition at line 85 of file VertexFit.cxx.
References evalFile, and evalTree.
Member Function Documentation
void VertexFit::addHypothesis (double z, double sigz = 50.) inline
Definition at line 89 of file VertexFit.h.
References sig_z_start, and z_start.
Referenced by setRecEvent().
void VertexFit::addTrack (int index, SRecTrack & _track)
Add one track parameter set into the fit.
Definition at line 480 of file VertexFit.cxx.
References TrkPar::_covar_kf, TrkPar::_state_kf, _trkpar_curr, TrkPar::_z, SRecTrack::getCovariance(), SRecTrack::getStateVector(), and SRecTrack::getZ().
Referenced by setRecEvent().
void VertexFit::addTrack (int index, KalmanTrack & _track)
Definition at line 464 of file VertexFit.cxx.
References _trkpar_curr, and KalmanTrack::getNodeList().
void VertexFit::addTrack (int index, TrkPar & _trkpar)
Definition at line 490 of file VertexFit.cxx.
References _trkpar_curr.
void VertexFit::bookEvaluation (std::string evalFileName = "vtx_eval.root")
Evaluation.
Definition at line 621 of file VertexFit.cxx.
References chisq_kf_eval, chisq_vx_eval, choice_by_kf_eval, choice_by_vx_eval, choice_eval, evalFile, evalTree, eventID, m_chisq_kf_eval, m_z_vertex_eval, nIter_eval, nStart, r_vertex_eval, runID, s_chisq_kf_eval, s_z_vertex_eval, targetPos, z_start_eval, and z_vertex_eval.
Referenced by Init().
void VertexFit::enableOptimization () inline
Enable the optimization of final dimuon vertex z position.
Definition at line 75 of file VertexFit.h.
References optimize.
int VertexFit::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 158 of file VertexFit.cxx.
References Fun4AllReturnCodes::EVENT_OK.
void VertexFit::fillEvaluation ()
Definition at line 647 of file VertexFit.cxx.
References chisq_kf_eval, chisq_km, chisq_vx, chisq_vx_eval, choice_by_kf_eval, choice_by_vx_eval, evalTree, m_chisq_kf_eval, m_z_vertex_eval, nStart, r_vertex, r_vertex_eval, s_chisq_kf_eval, s_z_vertex_eval, z_start, z_start_eval, z_vertex, and z_vertex_eval.
Referenced by setRecEvent().
double VertexFit::findDimuonVertexFast (SRecTrack & track1, SRecTrack & track2)
Definition at line 362 of file VertexFit.cxx.
References SRecTrack::getCharge(), NSLICES_FMAG, NSTEPS_TARGET, SRecTrack::swimToVertex(), and Z_DUMP.
Referenced by setRecEvent().
double VertexFit::findSingleMuonVertex (SRecTrack & _track)
Definition at line 584 of file VertexFit.cxx.
References TrkPar::_covar_kf, TrkPar::_state_kf, TrkPar::_z, SRecTrack::getCovariance(), SRecTrack::getStateVector(), and SRecTrack::getZ().
Referenced by findSingleMuonVertex().
double VertexFit::findSingleMuonVertex (Node & _node_start)
Definition at line 594 of file VertexFit.cxx.
References findSingleMuonVertex(), Node::getFiltered(), Node::getPredicted(), Node::getSmoothed(), Node::isFilterDone(), and Node::isSmoothDone().
double VertexFit::findSingleMuonVertex (TrkPar & _trkpar_start)
Definition at line 613 of file VertexFit.cxx.
References TrkPar::_covar_kf, _extrapolator, TrkPar::_state_kf, TrkPar::_z, GenFitExtrapolator::extrapolateToIP(), and GenFitExtrapolator::setInitialStateWithCov().
int VertexFit::findVertex ()
Find the primary vertex.
break the iteration if the z0 converges
Definition at line 495 of file VertexFit.cxx.
References _chisq_kalman, _chisq_vertex, _kmfit, _max_iteration, _node_vertex, VtxPar::_r, _tolerance, _trkpar_curr, _vtxpar_curr, KalmanFilter::fit_node(), Node::getChisq(), Node::getZ(), LogInfo, Node::resetFlags(), KalmanFilter::setCurrTrkpar(), Node::setZ(), updateVertex(), Z_DOWNSTREAM, and Z_UPSTREAM.
Referenced by processOnePair().
const std::string& VertexFit::get_eval_file_name () const inline
Definition at line 123 of file VertexFit.h.
References evalFileName.
double VertexFit::getKFChisq () inline
Definition at line 110 of file VertexFit.h.
References _chisq_kalman.
int VertexFit::GetNodes (PHCompositeNode * topNode) private
Definition at line 166 of file VertexFit.cxx.
References _recEvent, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, LogInfo, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int VertexFit::getNTracks () inline
Definition at line 111 of file VertexFit.h.
References _trkpar_curr.
double VertexFit::getVertexZ0 () inline
Gets.
Definition at line 108 of file VertexFit.h.
References VtxPar::_r, and _vtxpar_curr.
Referenced by setRecEvent().
double VertexFit::getVXChisq () inline
Definition at line 109 of file VertexFit.h.
References _chisq_vertex.
Referenced by setRecEvent().
int VertexFit::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 95 of file VertexFit.cxx.
References bookEvaluation(), evalFileName, and Fun4AllReturnCodes::EVENT_OK.
void VertexFit::init ()
Initialize and reset.
Two default starting points
Definition at line 390 of file VertexFit.cxx.
References _trkpar_curr, chisq_km, chisq_vx, r_vertex, sig_z_start, z_start, and z_vertex.
Referenced by setRecEvent().
int VertexFit::InitField (PHCompositeNode * topNode) private
Definition at line 178 of file VertexFit.cxx.
References Fun4AllReturnCodes::EVENT_OK, PHFieldUtility::GetFieldMapNode(), JobOptsSvc::m_fMagFile, JobOptsSvc::m_kMagFile, p_jobOptsSvc, and Fun4AllBase::verbosity.
Referenced by InitRun().
int VertexFit::InitGeom (PHCompositeNode * topNode) private
Definition at line 198 of file VertexFit.cxx.
References _t_geo_manager, Fun4AllReturnCodes::EVENT_OK, PHGeomUtility::GetTGeoManager(), and Fun4AllBase::verbosity.
Referenced by InitRun().
int VertexFit::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Single track finding doesn't require a propagation matrix
Reimplemented from SubsysReco.
Definition at line 102 of file VertexFit.cxx.
References _extrapolator, _kmfit, _t_geo_manager, KalmanFilter::enableDumpCorrection(), Fun4AllReturnCodes::EVENT_OK, PHFlag::get_DoubleFlag(), PHFieldUtility::GetFieldMapNode(), GetNodes(), PHField::identify(), GenFitExtrapolator::init(), InitField(), InitGeom(), recoConsts::instance(), KalmanFilter::instance(), MakeNodes(), GenFitExtrapolator::setLengthCalc(), GenFitExtrapolator::setPropCalc(), and Fun4AllBase::verbosity.
int VertexFit::MakeNodes (PHCompositeNode * topNode) private
Definition at line 162 of file VertexFit.cxx.
References Fun4AllReturnCodes::EVENT_OK.
Referenced by InitRun().
void VertexFit::print ()
Debugging output.
Definition at line 703 of file VertexFit.cxx.
References chisq_km, chisq_vx, sig_z_start, z_start, and z_vertex.
int VertexFit::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 140 of file VertexFit.cxx.
References _recEvent, Fun4AllReturnCodes::EVENT_OK, SRecEvent::identify(), LogInfo, setRecEvent(), SRecEvent::setRecStatus(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
int VertexFit::processOnePair ()
After setting both tracks and hypothesis, start the iteration.
Definition at line 423 of file VertexFit.cxx.
References _chisq_kalman, _chisq_vertex, VtxPar::_r, _vtxpar_curr, chisq_km, chisq_vx, findVertex(), LogInfo, nIter_eval, nStart, r_vertex, setStartingVertex(), sig_z_start, z_start, and z_vertex.
Referenced by setRecEvent().
void VertexFit::set_eval_file_name (const std::string & evalFileName) inline
Definition at line 127 of file VertexFit.h.
References evalFileName.
void VertexFit::setControlParameter (int nMaxIteration, double tolerance) inline
Set the convergence control parameters.
Definition at line 78 of file VertexFit.h.
References _max_iteration, and _tolerance.
int VertexFit::setRecEvent (SRecEvent * recEvent, int sign1 = 1, int sign2 = -1)
Set the SRecEvent, main external call the use vertex fit.
Definition at line 212 of file VertexFit.cxx.
References VtxPar::_r, _vtxpar_curr, addHypothesis(), addTrack(), SRecDimuon::calcVariables(), SRecDimuon::chisq_dump, SRecDimuon::chisq_kf, SRecDimuon::chisq_single, SRecDimuon::chisq_target, SRecDimuon::chisq_upstream, SRecDimuon::chisq_vx, choice_eval, evalTree, eventID, fillEvaluation(), findDimuonVertexFast(), SRecEvent::getChargedTrackIDs(), SRecTrack::getChisqDump(), SRecTrack::getChisqTarget(), SRecTrack::getChisqUpstream(), SRecTrack::getChisqVertex(), SRecTrack::getDumpPos(), SRecEvent::getEventID(), SRecTrack::getMomentumVertex(), SRecEvent::getNDimuons(), SRecEvent::getRunID(), SRecTrack::getTargetPos(), SRecEvent::getTargetPos(), SRecEvent::getTrack(), SRecTrack::getVertex(), getVertexZ0(), getVXChisq(), init(), SRecEvent::insertDimuon(), SRecTrack::isValid(), LogInfo, m_idx_eval, nNeg, nPos, optimize, p_idx_eval, SRecDimuon::p_neg, SRecDimuon::p_neg_single, SRecDimuon::p_pos, SRecDimuon::p_pos_single, processOnePair(), SRecDimuon::proj_dump_neg, SRecDimuon::proj_dump_pos, SRecDimuon::proj_target_neg, SRecDimuon::proj_target_pos, runID, SRecTrack::setZVertex(), targetPos, SRecDimuon::trackID_neg, SRecDimuon::trackID_pos, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_A_LOT, VFEXIT_FAIL_DIMUONPAIR, VFEXIT_FAIL_ITERATION, VFEXIT_SUCCESS, SRecDimuon::vtx, SRecDimuon::vtx_neg, and SRecDimuon::vtx_pos.
Referenced by process_event().
void VertexFit::setStartingVertex (double z_start, double sigz_start)
Initialize the starting vertex with a guess and large error
Definition at line 407 of file VertexFit.cxx.
References _chisq_kalman, _chisq_vertex, VtxPar::_cov, VtxPar::_r, _vtxpar_curr, BEAM_SPOT_X, BEAM_SPOT_Y, X_VTX, Y_VTX, and z_start.
Referenced by processOnePair().
void VertexFit::updateVertex ()
Core function, update the vertex prediction according to the track info.
Set the projector matrix from track state vector to the coordinate
Definition at line 550 of file VertexFit.cxx.
References _chisq_vertex, VtxPar::_cov, TrkPar::_covar_kf, _node_vertex, VtxPar::_r, TrkPar::_state_kf, _vtxpar_curr, SMatrix::getABCt(), SMatrix::getABtC(), SMatrix::getAtBC(), Node::getFiltered(), and SMatrix::invertMatrix().
Referenced by findVertex().
Member Data Documentation
double VertexFit::_chisq_kalman private
Definition at line 155 of file VertexFit.h.
Referenced by findVertex(), getKFChisq(), processOnePair(), and setStartingVertex().
double VertexFit::_chisq_vertex private
chi squares
Definition at line 154 of file VertexFit.h.
Referenced by findVertex(), getVXChisq(), processOnePair(), setStartingVertex(), and updateVertex().
GenFitExtrapolator VertexFit::_extrapolator private
Track extrapolator.
Definition at line 172 of file VertexFit.h.
Referenced by findSingleMuonVertex(), and InitRun().
KalmanFilter* VertexFit::_kmfit private
pointer to external Kalman filter
Definition at line 151 of file VertexFit.h.
Referenced by findVertex(), and InitRun().
int VertexFit::_max_iteration private
convergence control parameter
Definition at line 168 of file VertexFit.h.
Referenced by findVertex(), setControlParameter(), and VertexFit().
Node VertexFit::_node_vertex private
Kalman node at the vertex.
Definition at line 148 of file VertexFit.h.
Referenced by findVertex(), updateVertex(), and VertexFit().
SRecEvent* VertexFit::_recEvent private
Definition at line 181 of file VertexFit.h.
Referenced by GetNodes(), and process_event().
TGeoManager* VertexFit::_t_geo_manager private
Definition at line 179 of file VertexFit.h.
Referenced by InitGeom(), and InitRun().
double VertexFit::_tolerance private
Definition at line 169 of file VertexFit.h.
Referenced by findVertex(), setControlParameter(), and VertexFit().
std::vector<TrkPar> VertexFit::_trkpar_curr private
storage of the input track parameters
Definition at line 142 of file VertexFit.h.
Referenced by addTrack(), findVertex(), getNTracks(), and init().
VtxPar VertexFit::_vtxpar_curr private
vertex parameter
Definition at line 145 of file VertexFit.h.
Referenced by findVertex(), getVertexZ0(), processOnePair(), setRecEvent(), setStartingVertex(), and updateVertex().
double VertexFit::chisq_kf_eval[50] private
Definition at line 202 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
std::vector<double> VertexFit::chisq_km private
Definition at line 164 of file VertexFit.h.
Referenced by fillEvaluation(), init(), print(), and processOnePair().
std::vector<double> VertexFit::chisq_vx private
Definition at line 165 of file VertexFit.h.
Referenced by fillEvaluation(), init(), print(), and processOnePair().
double VertexFit::chisq_vx_eval[50] private
Definition at line 203 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
int VertexFit::choice_by_kf_eval private
Definition at line 196 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
int VertexFit::choice_by_vx_eval private
Definition at line 197 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
int VertexFit::choice_eval private
Definition at line 195 of file VertexFit.h.
Referenced by bookEvaluation(), and setRecEvent().
TFile* VertexFit::evalFile private
Definition at line 185 of file VertexFit.h.
Referenced by bookEvaluation(), VertexFit(), and ~VertexFit().
std::string VertexFit::evalFileName private
Evaluation file and tree.
Definition at line 184 of file VertexFit.h.
Referenced by get_eval_file_name(), Init(), set_eval_file_name(), and VertexFit().
TTree* VertexFit::evalTree private
Definition at line 186 of file VertexFit.h.
Referenced by bookEvaluation(), fillEvaluation(), setRecEvent(), VertexFit(), and ~VertexFit().
int VertexFit::eventID private
Definition at line 189 of file VertexFit.h.
Referenced by bookEvaluation(), and setRecEvent().
double VertexFit::m_chisq_kf_eval private
Definition at line 207 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
int VertexFit::m_idx_eval private
Definition at line 194 of file VertexFit.h.
Referenced by setRecEvent().
double VertexFit::m_z_vertex_eval private
Definition at line 209 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
int VertexFit::nIter_eval[50] private
Definition at line 201 of file VertexFit.h.
Referenced by bookEvaluation(), and processOnePair().
int VertexFit::nNeg private
Definition at line 192 of file VertexFit.h.
Referenced by setRecEvent().
int VertexFit::nPos private
Definition at line 191 of file VertexFit.h.
Referenced by setRecEvent().
int VertexFit::nStart private
Definition at line 199 of file VertexFit.h.
Referenced by bookEvaluation(), fillEvaluation(), and processOnePair().
bool VertexFit::optimize private
Flag to enable/disable optimization of final position.
Definition at line 175 of file VertexFit.h.
Referenced by enableOptimization(), setRecEvent(), and VertexFit().
int VertexFit::p_idx_eval private
Definition at line 193 of file VertexFit.h.
Referenced by setRecEvent().
JobOptsSvc* VertexFit::p_jobOptsSvc private
Definition at line 178 of file VertexFit.h.
Referenced by InitField(), and VertexFit().
std::vector<double> VertexFit::r_vertex private
Definition at line 163 of file VertexFit.h.
Referenced by fillEvaluation(), init(), and processOnePair().
double VertexFit::r_vertex_eval[50] private
Definition at line 205 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
int VertexFit::runID private
Definition at line 188 of file VertexFit.h.
Referenced by bookEvaluation(), and setRecEvent().
double VertexFit::s_chisq_kf_eval private
Definition at line 208 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
double VertexFit::s_z_vertex_eval private
Definition at line 210 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
std::vector<double> VertexFit::sig_z_start private
Definition at line 159 of file VertexFit.h.
Referenced by addHypothesis(), init(), print(), and processOnePair().
int VertexFit::targetPos private
Definition at line 190 of file VertexFit.h.
Referenced by bookEvaluation(), and setRecEvent().
std::vector<double> VertexFit::z_start private
Starting points.
Definition at line 158 of file VertexFit.h.
Referenced by addHypothesis(), fillEvaluation(), init(), print(), processOnePair(), and setStartingVertex().
double VertexFit::z_start_eval[50] private
Definition at line 200 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
std::vector<double> VertexFit::z_vertex private
Temporary results.
Definition at line 162 of file VertexFit.h.
Referenced by fillEvaluation(), init(), print(), and processOnePair().
double VertexFit::z_vertex_eval[50] private
Definition at line 204 of file VertexFit.h.
Referenced by bookEvaluation(), and fillEvaluation().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/ktracker/VertexFit.h
/dev/shm/kenichi/update-e1039-doc/e1039-core/packages/reco/ktracker/VertexFit.cxx