Class Reference for E1039 Core & Analysis Software: boost::shared_ptr< T > Class Template Reference
boost::shared_ptr< T > Class Template Reference
#include </data2/users/kenichi/e1039/git/e1039-doc/Doxygen_Assist/shared_ptr.hpp>
Public Types
typedef T element_type
typedef T value_type
typedef T * pointer
typedef boost::detail::shared_ptr_traits< T >::reference reference
Public Member Functions
shared_ptr ()
template<class Y >
shared_ptr (Y *p)
template<class Y , class D >
shared_ptr (Y *p, D d)
template<class Y , class D , class A >
shared_ptr (Y *p, D d, A a)
template<class Y >
shared_ptr (weak_ptr< Y > const &r)
template<class Y >
shared_ptr (weak_ptr< Y > const &r, boost::detail::sp_nothrow_tag)
template<class Y >
shared_ptr (shared_ptr< Y > const &r, typename boost::detail::sp_enable_if_convertible< Y, T >::type=boost::detail::sp_empty())
template<class Y >
shared_ptr (shared_ptr< Y > const &r, T *p)
template<class Y >
shared_ptr (shared_ptr< Y > const &r, boost::detail::static_cast_tag)
template<class Y >
shared_ptr (shared_ptr< Y > const &r, boost::detail::const_cast_tag)
template<class Y >
shared_ptr (shared_ptr< Y > const &r, boost::detail::dynamic_cast_tag)
template<class Y >
shared_ptr (shared_ptr< Y > const &r, boost::detail::polymorphic_cast_tag)
template<class Y >
shared_ptr (std::auto_ptr< Y > &r)
template<class Ap >
shared_ptr (Ap r, typename boost::detail::sp_enable_if_auto_ptr< Ap, int >::type=0)
shared_ptr & operator= (shared_ptr const &r)
template<class Y >
shared_ptr & operator= (shared_ptr< Y > const &r)
template<class Y >
shared_ptr & operator= (std::auto_ptr< Y > &r)
template<class Ap >
boost::detail::sp_enable_if_auto_ptr< Ap, shared_ptr & >::type operator= (Ap r)
void reset ()
template<class Y >
void reset (Y *p)
template<class Y , class D >
void reset (Y *p, D d)
template<class Y , class D , class A >
void reset (Y *p, D d, A a)
template<class Y >
void reset (shared_ptr< Y > const &r, T *p)
reference operator* () const
T * operator-> () const
T * get () const
bool unique () const
long use_count () const
void swap (shared_ptr< T > &other)
template<class Y >
bool _internal_less (shared_ptr< Y > const &rhs) const
void * _internal_get_deleter (boost::detail::sp_typeinfo const &ti) const
bool _internal_equiv (shared_ptr const &r) const
Friends
template<class Y >
class shared_ptr
template<class Y >
class weak_ptr
Detailed Description
template<class T>
class boost::shared_ptr< T >
Definition at line 164 of file shared_ptr.hpp.
Member Typedef Documentation
element_type
template<class T > typedef T boost::shared_ptr< T >::element_type
Definition at line 173 of file shared_ptr.hpp.
pointer
template<class T > typedef T* boost::shared_ptr< T >::pointer
Definition at line 175 of file shared_ptr.hpp.
reference
template<class T > typedef boost::detail::shared_ptr_traits<T>::reference boost::shared_ptr< T >::reference
Definition at line 176 of file shared_ptr.hpp.
value_type
template<class T > typedef T boost::shared_ptr< T >::value_type
Definition at line 174 of file shared_ptr.hpp.
Constructor & Destructor Documentation
shared_ptr() [1/14]
template<class T > boost::shared_ptr< T >::shared_ptr () inline
Definition at line 178 of file shared_ptr.hpp.
shared_ptr() [2/14]
template<class T > template<class Y > boost::shared_ptr< T >::shared_ptr (Y * p) inline explicit
Definition at line 183 of file shared_ptr.hpp.
References boost::detail::sp_enable_shared_from_this().
shared_ptr() [3/14]
template<class T > template<class Y , class D > boost::shared_ptr< T >::shared_ptr (Y * p, D d) inline
Definition at line 194 of file shared_ptr.hpp.
References boost::detail::sp_enable_shared_from_this().
shared_ptr() [4/14]
template<class T > template<class Y , class D , class A > boost::shared_ptr< T >::shared_ptr (Y * p, D d, A a) inline
Definition at line 201 of file shared_ptr.hpp.
References boost::detail::sp_enable_shared_from_this().
shared_ptr() [5/14]
template<class T > template<class Y > boost::shared_ptr< T >::shared_ptr (weak_ptr< Y > const & r) inline explicit
Definition at line 209 of file shared_ptr.hpp.
shared_ptr() [6/14]
template<class T > template<class Y > boost::shared_ptr< T >::shared_ptr (weak_ptr< Y > const & r, boost::detail::sp_nothrow_tag) inline
Definition at line 216 of file shared_ptr.hpp.
shared_ptr() [7/14]
template<class T > template<class Y > boost::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, typename boost::detail::sp_enable_if_convertible< Y, T >::type = boost::detail::sp_empty()) inline
Definition at line 227 of file shared_ptr.hpp.
shared_ptr() [8/14]
template<class T > template<class Y > boost::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, T * p) inline
Definition at line 240 of file shared_ptr.hpp.
shared_ptr() [9/14]
template<class T > template<class Y > boost::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, boost::detail::static_cast_tag) inline
Definition at line 245 of file shared_ptr.hpp.
shared_ptr() [10/14]
template<class T > template<class Y > boost::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, boost::detail::const_cast_tag) inline
Definition at line 250 of file shared_ptr.hpp.
shared_ptr() [11/14]
template<class T > template<class Y > boost::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, boost::detail::dynamic_cast_tag) inline
Definition at line 255 of file shared_ptr.hpp.
shared_ptr() [12/14]
template<class T > template<class Y > boost::shared_ptr< T >::shared_ptr (shared_ptr< Y > const & r, boost::detail::polymorphic_cast_tag) inline
Definition at line 264 of file shared_ptr.hpp.
shared_ptr() [13/14]
template<class T > template<class Y > boost::shared_ptr< T >::shared_ptr (std::auto_ptr< Y > & r) inline explicit
Definition at line 275 of file shared_ptr.hpp.
References boost::detail::sp_enable_shared_from_this().
shared_ptr() [14/14]
template<class T > template<class Ap > boost::shared_ptr< T >::shared_ptr (Ap r, typename boost::detail::sp_enable_if_auto_ptr< Ap, int >::type = 0) inline explicit
Definition at line 285 of file shared_ptr.hpp.
References boost::detail::sp_enable_shared_from_this().
Member Function Documentation
_internal_equiv()
template<class T > bool boost::shared_ptr< T >::_internal_equiv (shared_ptr< T > const & r) const inline
Definition at line 452 of file shared_ptr.hpp.
Referenced by boost::atomic_compare_exchange().
_internal_get_deleter()
template<class T > void* boost::shared_ptr< T >::_internal_get_deleter (boost::detail::sp_typeinfo const & ti) const inline
Definition at line 447 of file shared_ptr.hpp.
Referenced by boost::get_deleter().
_internal_less()
template<class T > template<class Y > bool boost::shared_ptr< T >::_internal_less (shared_ptr< Y > const & rhs) const inline
Definition at line 442 of file shared_ptr.hpp.
Referenced by boost::operator<().
get()
template<class T > T* boost::shared_ptr< T >::get () const inline
Definition at line 418 of file shared_ptr.hpp.
Referenced by boost::get_pointer(), boost::hash_value(), boost::operator!=(), boost::operator==(), and boost::shared_polymorphic_downcast().
operator*()
template<class T > reference boost::shared_ptr< T >::operator* () const inline
Definition at line 406 of file shared_ptr.hpp.
operator->()
template<class T > T* boost::shared_ptr< T >::operator-> () const inline
Definition at line 412 of file shared_ptr.hpp.
operator=() [1/4]
template<class T > template<class Ap > boost::detail::sp_enable_if_auto_ptr< Ap, shared_ptr & >::type boost::shared_ptr< T >::operator= (Ap r) inline
Definition at line 328 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
operator=() [2/4]
template<class T > shared_ptr& boost::shared_ptr< T >::operator= (shared_ptr< T > const & r) inline
Definition at line 299 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
operator=() [3/4]
template<class T > template<class Y > shared_ptr& boost::shared_ptr< T >::operator= (shared_ptr< Y > const & r) inline
Definition at line 308 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
operator=() [4/4]
template<class T > template<class Y > shared_ptr& boost::shared_ptr< T >::operator= (std::auto_ptr< Y > & r) inline
Definition at line 319 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
reset() [1/5]
template<class T > void boost::shared_ptr< T >::reset () inline
Definition at line 380 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
reset() [2/5]
template<class T > template<class Y > void boost::shared_ptr< T >::reset (shared_ptr< Y > const & r, T * p) inline
Definition at line 401 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
reset() [3/5]
template<class T > template<class Y > void boost::shared_ptr< T >::reset (Y * p) inline
Definition at line 385 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
reset() [4/5]
template<class T > template<class Y , class D > void boost::shared_ptr< T >::reset (Y * p, D d) inline
Definition at line 391 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
reset() [5/5]
template<class T > template<class Y , class D , class A > void boost::shared_ptr< T >::reset (Y * p, D d, A a) inline
Definition at line 396 of file shared_ptr.hpp.
References boost::shared_ptr< T >::swap().
swap()
template<class T > void boost::shared_ptr< T >::swap (shared_ptr< T > & other) inline
Definition at line 436 of file shared_ptr.hpp.
References boost::swap().
Referenced by boost::atomic_compare_exchange(), boost::atomic_exchange(), boost::atomic_store(), boost::shared_ptr< T >::operator=(), boost::shared_ptr< T >::reset(), and boost::swap().
unique()
template<class T > bool boost::shared_ptr< T >::unique () const inline
Definition at line 426 of file shared_ptr.hpp.
use_count()
template<class T > long boost::shared_ptr< T >::use_count () const inline
Definition at line 431 of file shared_ptr.hpp.
Friends And Related Function Documentation
shared_ptr
template<class T > template<class Y > friend class shared_ptr friend
Definition at line 464 of file shared_ptr.hpp.
weak_ptr
template<class T > template<class Y > friend class weak_ptr friend
Definition at line 465 of file shared_ptr.hpp.
The documentation for this class was generated from the following file:
/data2/users/kenichi/e1039/git/e1039-doc/Doxygen_Assist/shared_ptr.hpp