SeaQuest Offline Software: PHG4ForwardEcalSteppingAction Class Reference
PHG4ForwardEcalSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4ForwardEcalSteppingAction.h>
Public Member Functions
PHG4ForwardEcalSteppingAction (PHG4ForwardEcalDetector *)
constructor
virtual ~PHG4ForwardEcalSteppingAction ()
destroctor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Member Functions
int FindTowerIndex (G4TouchableHandle touch, int &j, int &k)
int ParseG4VolumeName (G4VPhysicalVolume *volume, int &j, int &k)
Private Attributes
PHG4ForwardEcalDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4HitContainer * hitcontainer
PHG4Hit * hit
PHG4Shower * saveshower
int absorbertruth
int light_scint_model
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 13 of file PHG4ForwardEcalSteppingAction.h.
Constructor & Destructor Documentation
PHG4ForwardEcalSteppingAction::PHG4ForwardEcalSteppingAction (PHG4ForwardEcalDetector * detector)
constructor
Definition at line 37 of file PHG4ForwardEcalSteppingAction.cc.
PHG4ForwardEcalSteppingAction::~PHG4ForwardEcalSteppingAction () virtual
destroctor
Definition at line 48 of file PHG4ForwardEcalSteppingAction.cc.
References hit.
Member Function Documentation
int PHG4ForwardEcalSteppingAction::FindTowerIndex (G4TouchableHandle touch, int & j, int & k) private
Definition at line 318 of file PHG4ForwardEcalSteppingAction.cc.
References ParseG4VolumeName().
Referenced by UserSteppingAction().
int PHG4ForwardEcalSteppingAction::ParseG4VolumeName (G4VPhysicalVolume * volume, int & j, int & k) private
Definition at line 332 of file PHG4ForwardEcalSteppingAction.cc.
Referenced by FindTowerIndex().
void PHG4ForwardEcalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 282 of file PHG4ForwardEcalSteppingAction.cc.
References absorberhits_, detector_, PHG4Detector::GetName(), hits_, PHG4ForwardEcalDetector::SuperDetector(), and PHG4SteppingAction::verbosity.
Referenced by PHG4ForwardEcalSubsystem::process_event().
bool PHG4ForwardEcalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 58 of file PHG4ForwardEcalSteppingAction.cc.
References absorberhits_, absorbertruth, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, FindTowerIndex(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4ForwardEcalDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4HitContainer::GetID(), PHG4Detector::GetName(), PHG4SteppingAction::GetVisibleEnergyDeposition(), hit, hitcontainer, hits_, PHG4ForwardEcalDetector::IsActive(), PHG4ForwardEcalDetector::IsBlackHole(), PHG4ForwardEcalDetector::IsInForwardEcal(), light_scint_model, NULL, PHG4Hit::Reset(), saveshower, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_index_j(), PHG4Hit::set_index_k(), PHG4Hit::set_index_l(), PHG4Hit::set_light_yield(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and PHG4SteppingAction::verbosity.
Member Data Documentation
PHG4HitContainer* PHG4ForwardEcalSteppingAction::absorberhits_ private
Definition at line 42 of file PHG4ForwardEcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4ForwardEcalSteppingAction::absorbertruth private
Definition at line 47 of file PHG4ForwardEcalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4ForwardEcalDetector* PHG4ForwardEcalSteppingAction::detector_ private
pointer to the detector
Definition at line 38 of file PHG4ForwardEcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4ForwardEcalSteppingAction::hit private
Definition at line 44 of file PHG4ForwardEcalSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4ForwardEcalSteppingAction().
PHG4HitContainer* PHG4ForwardEcalSteppingAction::hitcontainer private
Definition at line 43 of file PHG4ForwardEcalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4ForwardEcalSteppingAction::hits_ private
pointer to hit container
Definition at line 41 of file PHG4ForwardEcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4ForwardEcalSteppingAction::light_scint_model private
Definition at line 48 of file PHG4ForwardEcalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4ForwardEcalSteppingAction::saveshower private
Definition at line 45 of file PHG4ForwardEcalSteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4ForwardEcalSteppingAction.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc