Class Reference for E1039 Core & Analysis Software: PHG4Utils Class Reference
PHG4Utils Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Utils.h>
Static Public Member Functions
static double GetLengthForRapidityCoverage (const double radius, const double eta)
static double GetLengthForRapidityCoverage (const double radius)
static void SetPseudoRapidityCoverage (const double eta)
static void SetColour (G4VisAttributes *att, const std::string &mat)
static double get_theta (const double eta)
static double get_eta (const double theta)
static std::pair< double, double > get_etaphi (const double x, const double y, const double z)
static double get_eta (const double radius, const double z)
Detailed Description
Definition at line 8 of file PHG4Utils.h.
Member Function Documentation
get_eta() [1/2]
double PHG4Utils::get_eta (const double radius, const double z) static
Definition at line 61 of file PHG4Utils.cc.
get_eta() [2/2]
double PHG4Utils::get_eta (const double theta) static
Definition at line 40 of file PHG4Utils.cc.
get_etaphi()
pair< double, double > PHG4Utils::get_etaphi (const double x, const double y, const double z) static
Definition at line 47 of file PHG4Utils.cc.
get_theta()
double PHG4Utils::get_theta (const double eta) static
Definition at line 33 of file PHG4Utils.cc.
GetLengthForRapidityCoverage() [1/2]
double PHG4Utils::GetLengthForRapidityCoverage (const double radius) static
Definition at line 21 of file PHG4Utils.cc.
GetLengthForRapidityCoverage() [2/2]
double PHG4Utils::GetLengthForRapidityCoverage (const double radius, const double eta) static
Definition at line 12 of file PHG4Utils.cc.
Referenced by PHG4BNLTargetCoilSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), PHG4PolyconSubsystem::InitRunSubsystem(), PHG4TargetCoilSubsystem::InitRunSubsystem(), and PHG4TargetCoilV2Subsystem::InitRunSubsystem().
SetColour()
void PHG4Utils::SetColour (G4VisAttributes * att, const std::string & mat) static
Definition at line 75 of file PHG4Utils.cc.
Referenced by PHG4BlockDetector::Construct(), PHG4BNLTargetCoilDetector::Construct(), PHG4CollimatorDetector::Construct(), PHG4ConeDetector::Construct(), PHG4CylinderDetector::Construct(), PHG4PolyconDetector::Construct(), PHG4TargetCoilDetector::Construct(), and PHG4TargetCoilV2Detector::Construct().
SetPseudoRapidityCoverage()
void PHG4Utils::SetPseudoRapidityCoverage (const double eta) static
Definition at line 27 of file PHG4Utils.cc.
Referenced by PHG4Reco::set_rapidity_coverage().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Utils.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4Utils.cc