Class Reference for E1039 Core & Analysis Software: PHGeomIOTGeo Class Reference
PHGeomIOTGeo Class Reference
PHGeomIOTGeo store geometry information to DST files in the format of binary streamed TGeoVolume. It completely owns the geometry object For run-time use of TGeoManager, please use PHGeomTGeo For operation of this class with DST node, please use PHGeomUtility.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHGeometry/PHGeomIOTGeo.h>
Public Member Functions
PHGeomIOTGeo ()
PHGeomIOTGeo (const PHGeomIOTGeo &geom)
virtual ~PHGeomIOTGeo ()
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
void SetGeometry (const TGeoVolume *g)
PHGeomIOTGeo do NOT own this TGeoVolume * g. Internally, it will use g to make a copy which PHGeomIOTGeo fully owns.
TGeoManager * ConstructTGeoManager ()
Construct TGeoManager. The result TGeoManager is not yet closed and open for further editing.
TGeoVolume * GetGeometryCopy ()
std::vector< char > & GetData ()
const std::vector< char > & GetData () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
std::vector< char > Data
store the streamed geometry and its streamer via a binary stream
Detailed Description
PHGeomIOTGeo store geometry information to DST files in the format of binary streamed TGeoVolume. It completely owns the geometry object For run-time use of TGeoManager, please use PHGeomTGeo For operation of this class with DST node, please use PHGeomUtility.
Definition at line 25 of file PHGeomIOTGeo.h.
Constructor & Destructor Documentation
PHGeomIOTGeo() [1/2]
PHGeomIOTGeo::PHGeomIOTGeo ()
Definition at line 23 of file PHGeomIOTGeo.cc.
References PHObject::SplitLevel().
Referenced by clone().
PHGeomIOTGeo() [2/2]
PHGeomIOTGeo::PHGeomIOTGeo (const PHGeomIOTGeo & geom)
Definition at line 29 of file PHGeomIOTGeo.cc.
~PHGeomIOTGeo()
PHGeomIOTGeo::~PHGeomIOTGeo () virtual
Definition at line 34 of file PHGeomIOTGeo.cc.
References Reset().
Member Function Documentation
clone()
PHObject * PHGeomIOTGeo::clone () const virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 40 of file PHGeomIOTGeo.cc.
References PHGeomIOTGeo().
ConstructTGeoManager()
TGeoManager * PHGeomIOTGeo::ConstructTGeoManager ()
Construct TGeoManager. The result TGeoManager is not yet closed and open for further editing.
Definition at line 82 of file PHGeomIOTGeo.cc.
References GetGeometryCopy(), isValid(), and NULL.
Referenced by PHGeomUtility::LoadFromIONode().
GetData() [1/2]
std::vector<char>& PHGeomIOTGeo::GetData () inline
Definition at line 66 of file PHGeomIOTGeo.h.
References Data.
GetData() [2/2]
const std::vector<char>& PHGeomIOTGeo::GetData () const inline
Definition at line 72 of file PHGeomIOTGeo.h.
References Data.
GetGeometryCopy()
TGeoVolume * PHGeomIOTGeo::GetGeometryCopy ()
Make a copy of TGeoVolume. The caller is responsible for deleting the returned TGeoVolume The caller is also responsible for constructing a valid TGeoManager before calling this function
Definition at line 69 of file PHGeomIOTGeo.cc.
References Data, isValid(), and NULL.
Referenced by ConstructTGeoManager().
identify()
void PHGeomIOTGeo::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 112 of file PHGeomIOTGeo.cc.
References Data, and isValid().
isValid()
int PHGeomIOTGeo::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 131 of file PHGeomIOTGeo.cc.
References Data.
Referenced by ConstructTGeoManager(), GetGeometryCopy(), identify(), and PHGeomUtility::LoadFromIONode().
Reset()
void PHGeomIOTGeo::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 124 of file PHGeomIOTGeo.cc.
References Data.
Referenced by ~PHGeomIOTGeo().
SetGeometry()
void PHGeomIOTGeo::SetGeometry (const TGeoVolume * g)
PHGeomIOTGeo do NOT own this TGeoVolume * g. Internally, it will use g to make a copy which PHGeomIOTGeo fully owns.
Definition at line 47 of file PHGeomIOTGeo.cc.
References Data.
Referenced by PHGeomUtility::UpdateIONode().
Member Data Documentation
Data
std::vector<char> PHGeomIOTGeo::Data protected
store the streamed geometry and its streamer via a binary stream
Definition at line 80 of file PHGeomIOTGeo.h.
Referenced by GetData(), GetGeometryCopy(), identify(), isValid(), Reset(), and SetGeometry().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHGeometry/PHGeomIOTGeo.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/PHGeometry/PHGeomIOTGeo.cc