SeaQuest Offline Software: PHG4HcalPrototypeSubsystem Class Reference
PHG4HcalPrototypeSubsystem Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4HcalPrototypeSubsystem.h>
Public Member Functions
PHG4HcalPrototypeSubsystem (const std::string &name="BLOCK", const int layer=0)
constructor
virtual ~PHG4HcalPrototypeSubsystem (void)
destructor
int Init (PHCompositeNode *)
init
int process_event (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector (void) const
accessors (reimplemented)
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
void SetYRot (const G4double dbl)
void SetZRot (const G4double dbl)
void SetMaterial (const std::string &mat)
PHG4EventAction * GetEventAction () const
return pointer to this subsystem event action
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector ()
void BlackHole (const int i=1)
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4HcalPrototypeDetector * detector_
detector geometry
PHG4HcalPrototypeSteppingAction * steppingAction_
particle tracking "stepping" action
PHG4EventAction * eventAction_
G4double dimension [3]
G4double place_in_x
G4double place_in_y
G4double place_in_z
G4double rot_in_x
G4double rot_in_y
G4double rot_in_z
G4String material
int active
int absorberactive
int layer
int blackhole
std::string detector_type
std::string superdetector
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from PHG4Subsystem
bool overlapcheck
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 16 of file PHG4HcalPrototypeSubsystem.h.
Constructor & Destructor Documentation
PHG4HcalPrototypeSubsystem::PHG4HcalPrototypeSubsystem (const std::string & name = "BLOCK", const int layer = 0)
constructor
Definition at line 19 of file PHG4HcalPrototypeSubsystem.cc.
References dimension, and Fun4AllBase::Name().
virtual PHG4HcalPrototypeSubsystem::~PHG4HcalPrototypeSubsystem (void) inline virtual
destructor
Definition at line 25 of file PHG4HcalPrototypeSubsystem.h.
Member Function Documentation
void PHG4HcalPrototypeSubsystem::BlackHole (const int i = 1) inline
Definition at line 69 of file PHG4HcalPrototypeSubsystem.h.
References blackhole.
PHG4Detector * PHG4HcalPrototypeSubsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 133 of file PHG4HcalPrototypeSubsystem.cc.
References detector_.
PHG4EventAction* PHG4HcalPrototypeSubsystem::GetEventAction (void) const inline virtual
return pointer to this subsystem event action
Reimplemented from PHG4Subsystem.
Definition at line 63 of file PHG4HcalPrototypeSubsystem.h.
References eventAction_.
PHG4SteppingAction * PHG4HcalPrototypeSubsystem::GetSteppingAction (void) const virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 139 of file PHG4HcalPrototypeSubsystem.cc.
References steppingAction_.
int PHG4HcalPrototypeSubsystem::Init (PHCompositeNode * topNode) virtual
init
creates the detector_ object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from SubsysReco.
Definition at line 51 of file PHG4HcalPrototypeSubsystem.cc.
References absorberactive, active, PHCompositeNode::addNode(), PHG4HcalPrototypeDetector::BlackHole(), blackhole, detector_, detector_type, eventAction_, PHNodeIterator::findFirst(), layer, Fun4AllBase::Name(), PHG4Subsystem::overlapcheck, PHG4Detector::OverlapCheck(), rot_in_y, rot_in_z, PHG4HcalPrototypeDetector::SetAbsorberActive(), PHG4HcalPrototypeDetector::SetActive(), PHG4HcalPrototypeDetector::SetYRot(), PHG4HcalPrototypeDetector::SetZRot(), steppingAction_, PHG4HcalPrototypeDetector::SuperDetector(), and superdetector.
int PHG4HcalPrototypeSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 120 of file PHG4HcalPrototypeSubsystem.cc.
References PHG4HcalPrototypeSteppingAction::SetInterfacePointers(), and steppingAction_.
void PHG4HcalPrototypeSubsystem::SetAbsorberActive (const int i = 1) inline
Definition at line 65 of file PHG4HcalPrototypeSubsystem.h.
References absorberactive.
void PHG4HcalPrototypeSubsystem::SetActive (const int i = 1) inline
Definition at line 64 of file PHG4HcalPrototypeSubsystem.h.
References active.
void PHG4HcalPrototypeSubsystem::SetMaterial (const std::string & mat) inline
Definition at line 62 of file PHG4HcalPrototypeSubsystem.h.
References material.
void PHG4HcalPrototypeSubsystem::SetYRot (const G4double dbl) inline
Definition at line 59 of file PHG4HcalPrototypeSubsystem.h.
References rot_in_y.
void PHG4HcalPrototypeSubsystem::SetZRot (const G4double dbl) inline
Definition at line 60 of file PHG4HcalPrototypeSubsystem.h.
References rot_in_z.
void PHG4HcalPrototypeSubsystem::SuperDetector (const std::string & name) inline
Definition at line 66 of file PHG4HcalPrototypeSubsystem.h.
References superdetector.
const std::string PHG4HcalPrototypeSubsystem::SuperDetector () inline
Definition at line 67 of file PHG4HcalPrototypeSubsystem.h.
References superdetector.
Member Data Documentation
int PHG4HcalPrototypeSubsystem::absorberactive private
Definition at line 91 of file PHG4HcalPrototypeSubsystem.h.
Referenced by Init(), and SetAbsorberActive().
int PHG4HcalPrototypeSubsystem::active private
Definition at line 90 of file PHG4HcalPrototypeSubsystem.h.
Referenced by Init(), and SetActive().
int PHG4HcalPrototypeSubsystem::blackhole private
Definition at line 93 of file PHG4HcalPrototypeSubsystem.h.
Referenced by BlackHole(), and Init().
PHG4HcalPrototypeDetector* PHG4HcalPrototypeSubsystem::detector_ private
detector geometry
defives from PHG4Detector
Definition at line 75 of file PHG4HcalPrototypeSubsystem.h.
Referenced by GetDetector(), and Init().
std::string PHG4HcalPrototypeSubsystem::detector_type private
Definition at line 94 of file PHG4HcalPrototypeSubsystem.h.
Referenced by Init().
G4double PHG4HcalPrototypeSubsystem::dimension[3] private
Definition at line 81 of file PHG4HcalPrototypeSubsystem.h.
Referenced by PHG4HcalPrototypeSubsystem().
PHG4EventAction* PHG4HcalPrototypeSubsystem::eventAction_ private
Definition at line 80 of file PHG4HcalPrototypeSubsystem.h.
Referenced by GetEventAction(), and Init().
int PHG4HcalPrototypeSubsystem::layer private
Definition at line 92 of file PHG4HcalPrototypeSubsystem.h.
Referenced by Init().
G4String PHG4HcalPrototypeSubsystem::material private
Definition at line 89 of file PHG4HcalPrototypeSubsystem.h.
Referenced by SetMaterial().
G4double PHG4HcalPrototypeSubsystem::place_in_x private
Definition at line 82 of file PHG4HcalPrototypeSubsystem.h.
G4double PHG4HcalPrototypeSubsystem::place_in_y private
Definition at line 83 of file PHG4HcalPrototypeSubsystem.h.
G4double PHG4HcalPrototypeSubsystem::place_in_z private
Definition at line 84 of file PHG4HcalPrototypeSubsystem.h.
G4double PHG4HcalPrototypeSubsystem::rot_in_x private
Definition at line 85 of file PHG4HcalPrototypeSubsystem.h.
G4double PHG4HcalPrototypeSubsystem::rot_in_y private
Definition at line 86 of file PHG4HcalPrototypeSubsystem.h.
Referenced by Init(), and SetYRot().
G4double PHG4HcalPrototypeSubsystem::rot_in_z private
Definition at line 87 of file PHG4HcalPrototypeSubsystem.h.
Referenced by Init(), and SetZRot().
PHG4HcalPrototypeSteppingAction* PHG4HcalPrototypeSubsystem::steppingAction_ private
particle tracking "stepping" action
derives from PHG4SteppingActions
Definition at line 79 of file PHG4HcalPrototypeSubsystem.h.
Referenced by GetSteppingAction(), Init(), and process_event().
std::string PHG4HcalPrototypeSubsystem::superdetector private
Definition at line 95 of file PHG4HcalPrototypeSubsystem.h.
Referenced by Init(), and SuperDetector().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4HcalPrototypeSubsystem.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4HcalPrototypeSubsystem.cc