E1039 Software: EventHeader Class Reference
EventHeader Class Reference
base class for EventHeaders
#include </home/yuhw/GitHub/SeaQuest/e1039-core/framework/ffaobjects/EventHeader.h>
Public Member Functions
virtual ~EventHeader ()
dtor
virtual void Reset ()
Clear Event.
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains valid data
virtual int get_RunNumber () const
get Run Number
virtual void set_RunNumber (const int run)
set Run Number
virtual int get_EvtSequence () const
get Event Number
virtual void set_EvtSequence (const int)
set Event Number
virtual int get_EvtType () const
get Event Type (Data,rejected,EOR,BOR,...)
virtual void set_EvtType (const int)
set Event Type (Data,rejected,EOR,BOR,...)
virtual time_t get_TimeStamp () const
get ATP TimeStamp (unix time, convert with ctime()
virtual void set_TimeStamp (const time_t)
set TimeStamp
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Detailed Description
base class for EventHeaders
Definition at line 9 of file EventHeader.h.
Constructor & Destructor Documentation
~EventHeader()
virtual EventHeader::~EventHeader () inline virtual
dtor
Definition at line 14 of file EventHeader.h.
References identify(), isValid(), and Reset().
Member Function Documentation
get_EvtSequence()
virtual int EventHeader::get_EvtSequence () const inline virtual
get Event Number
Reimplemented in EventHeaderv1.
Definition at line 33 of file EventHeader.h.
get_EvtType()
virtual int EventHeader::get_EvtType () const inline virtual
get Event Type (Data,rejected,EOR,BOR,...)
Reimplemented in EventHeaderv1.
Definition at line 38 of file EventHeader.h.
get_RunNumber()
virtual int EventHeader::get_RunNumber () const inline virtual
get Run Number
Reimplemented in EventHeaderv1.
Definition at line 28 of file EventHeader.h.
get_TimeStamp()
virtual time_t EventHeader::get_TimeStamp () const inline virtual
get ATP TimeStamp (unix time, convert with ctime()
Reimplemented in EventHeaderv1.
Definition at line 43 of file EventHeader.h.
identify()
void EventHeader::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in EventHeaderv1.
Definition at line 19 of file EventHeader.cc.
Referenced by ~EventHeader().
isValid()
int EventHeader::isValid () const virtual
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Reimplemented in EventHeaderv1.
Definition at line 27 of file EventHeader.cc.
Referenced by ~EventHeader().
Reset()
virtual void EventHeader::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in EventHeaderv1.
Referenced by ~EventHeader().
set_EvtSequence()
virtual void EventHeader::set_EvtSequence (const int) inline virtual
set Event Number
Reimplemented in EventHeaderv1.
Definition at line 35 of file EventHeader.h.
set_EvtType()
virtual void EventHeader::set_EvtType (const int) inline virtual
set Event Type (Data,rejected,EOR,BOR,...)
Reimplemented in EventHeaderv1.
Definition at line 40 of file EventHeader.h.
set_RunNumber()
virtual void EventHeader::set_RunNumber (const int run) inline virtual
set Run Number
Reimplemented in EventHeaderv1.
Definition at line 30 of file EventHeader.h.
set_TimeStamp()
virtual void EventHeader::set_TimeStamp (const time_t) inline virtual
set TimeStamp
Reimplemented in EventHeaderv1.
Definition at line 45 of file EventHeader.h.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/ffaobjects/EventHeader.h
/home/yuhw/GitHub/SeaQuest/e1039-core/framework/ffaobjects/EventHeader.cc