Class Reference for E1039 Core & Analysis Software: SQHit Class Reference
SQHit Class Reference
An SQ interface class to hold one detector hit.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHit.h>
Public Types
enum HitQuality { InTime = 1<<0 , HodoMask = 1<<1 , TriggerMask = 1<<2 }
typedef std::map< short, float > CellMap
key -> plateID, float -> edep
Public Member Functions
SQHit ()
virtual ~SQHit ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual SQHit * Clone () const
virtual int get_hit_id () const
Return the ID of this hit.
virtual void set_hit_id (const int a)
virtual short get_detector_id () const
Return the detector ID of this hit.
virtual void set_detector_id (const short a)
virtual short get_element_id () const
Return the element ID of this hit.
virtual void set_element_id (const short a)
virtual short get_tower_id () const
Not valid in E1039. To be deleted.
virtual void set_tower_id (const short a)
virtual short get_level () const
Return the trigger level of this hit. Meaningful only if this hit is of V1495 TDC.
virtual void set_level (const short a)
virtual float get_tdc_time () const
Return the TDC time (nsec) of this hit.
virtual void set_tdc_time (const float a)
virtual float get_drift_distance () const
Return the drift distance of this hit. Probably the value is not properly set at present. Meaningful only if this hit is of drift chamber or prop tube.
virtual void set_drift_distance (const float a)
virtual float get_pos () const
Return the absolute position of this hit. Probably the value is not properly set at present.
virtual void set_pos (const float a)
virtual float get_edep () const
Not valid in E1039. To be deleted.
virtual void set_edep (const float a)
virtual int get_track_id () const
Return the track ID associated with this hit. Probably the value is not properly set at present.
virtual void set_track_id (const int a)
virtual PHG4HitDefs::keytype get_g4hit_id () const
Return the Geant-hit ID associated with this hit.
virtual void set_g4hit_id (const PHG4HitDefs::keytype a)
virtual float get_truth_x () const
Return the true x-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_x (const float a)
virtual float get_truth_y () const
Return the true y-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_y (const float a)
virtual float get_truth_z () const
Return the true z-position of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_z (const float a)
virtual float get_truth_px () const
Return the true x-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_px (const float a)
virtual float get_truth_py () const
Return the true y-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_py (const float a)
virtual float get_truth_pz () const
Return the true z-momentum of this hit. Meaningful only if this hit is of MC.
virtual void set_truth_pz (const float a)
virtual bool is_in_time () const
Return 'true' if this hit is in the time window.
virtual void set_in_time (const bool a)
virtual bool is_hodo_mask () const
Return 'true' if this hit is accepted (or masked out?) by the hodoscope masking. Meaningful only if this hit is of drift chamber.
virtual void set_hodo_mask (const bool a)
virtual bool is_trigger_mask () const
Return 'true' if this hit is accepted (or masked out?) by the trigger-road masking. Meaningful only if this hit is of drift chamber.
virtual void set_trigger_mask (const bool a)
virtual unsigned int get_n_cells () const
Return the number of cells included in this hit.
virtual CellMap get_cells () const
Return the list of all cells included in this hit.
virtual float get_cell (unsigned int i) const
Return the 'edep' value of the i-th cell.
virtual void add_cell (unsigned int i, float a)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Detailed Description
An SQ interface class to hold one detector hit.
Definition at line 20 of file SQHit.h.
Member Typedef Documentation
CellMap
typedef std::map<short, float> SQHit::CellMap
key -> plateID, float -> edep
Definition at line 23 of file SQHit.h.
Member Enumeration Documentation
HitQuality
enum SQHit::HitQuality
Enumerator
InTime
HodoMask
TriggerMask
Definition at line 104 of file SQHit.h.
Constructor & Destructor Documentation
SQHit()
SQHit::SQHit () inline
Definition at line 25 of file SQHit.h.
~SQHit()
virtual SQHit::~SQHit () inline virtual
Definition at line 26 of file SQHit.h.
Member Function Documentation
add_cell()
virtual void SQHit::add_cell (unsigned int i, float a) inline virtual
Definition at line 102 of file SQHit.h.
Clone()
virtual SQHit* SQHit::Clone () const inline virtual
Reimplemented in SQMCHit_v1, SQHit_v1, SQCalMCHit_v1, and SQCalHit_v1.
Definition at line 35 of file SQHit.h.
References NULL.
Referenced by SQHitMap_v1::insert(), SQHitMap_v1::operator=(), SQHitVector_v1::operator=(), SQHitVector_v1::push_back(), SQHitMap_v1::SQHitMap_v1(), and SQHitVector_v1::SQHitVector_v1().
get_cell()
virtual float SQHit::get_cell (unsigned int i) const inline virtual
Return the 'edep' value of the i-th cell.
Definition at line 101 of file SQHit.h.
get_cells()
virtual CellMap SQHit::get_cells () const inline virtual
Return the list of all cells included in this hit.
Reimplemented in SQCalHit_v1.
Definition at line 100 of file SQHit.h.
get_detector_id()
virtual short SQHit::get_detector_id () const inline virtual
Return the detector ID of this hit.
Reimplemented in SQHit_v1, and SQCalHit_v1.
Definition at line 42 of file SQHit.h.
Referenced by UtilHodo::Track2D::AddHit(), mTrkEveDisplay::draw_hits(), UtilTrigger::ExtractRoadID(), UtilTrack::FindDetectorHitsOfTrack(), UtilSQHit::FindFirstHits(), UtilSQHit::FindHits(), UtilSQHit::FindHitsFast(), UtilSQHit::FindTriggerHitsFast(), CalibHitPos::process_event(), CheckEventData::process_event(), AnaChamHit::process_event(), AnaEmbeddedData::process_event(), AnaDimuon::process_event(), SimpleTree::process_event(), CalibDriftDist::process_event(), CalibHitElementPos::process_event(), CalibHodoInTime::process_event(), DPTriggerAnalyzer::process_event(), SQChamberRealization::process_event(), SQGeomAcc::process_event(), TruthNodeMaker::process_event(), UtilSRawEvent::SetHit(), and UtilSRawEvent::SetTriggerHit().
get_drift_distance()
virtual float SQHit::get_drift_distance () const inline virtual
Return the drift distance of this hit. Probably the value is not properly set at present. Meaningful only if this hit is of drift chamber or prop tube.
Reimplemented in SQHit_v1.
Definition at line 57 of file SQHit.h.
Referenced by CheckEventData::process_event(), AnaChamHit::process_event(), SQChamberRealization::process_event(), UtilSRawEvent::SetHit(), and UtilSRawEvent::SetTriggerHit().
get_edep()
virtual float SQHit::get_edep () const inline virtual
Not valid in E1039. To be deleted.
Reimplemented in SQCalHit_v1.
Definition at line 63 of file SQHit.h.
get_element_id()
virtual short SQHit::get_element_id () const inline virtual
Return the element ID of this hit.
Reimplemented in SQHit_v1, and SQCalHit_v1.
Definition at line 45 of file SQHit.h.
Referenced by mTrkEveDisplay::draw_hits(), UtilTrigger::ExtractRoadID(), UtilSQHit::FindFirstHits(), CalibHitPos::process_event(), CheckEventData::process_event(), AnaChamHit::process_event(), AnaModule::process_event(), SimpleTree::process_event(), CalibDriftDist::process_event(), CalibHitElementPos::process_event(), CalibHodoInTime::process_event(), DPTriggerAnalyzer::process_event(), SQChamberRealization::process_event(), SQGeomAcc::process_event(), UtilSRawEvent::SetHit(), and UtilSRawEvent::SetTriggerHit().
get_g4hit_id()
virtual PHG4HitDefs::keytype SQHit::get_g4hit_id () const inline virtual
Return the Geant-hit ID associated with this hit.
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 69 of file SQHit.h.
get_hit_id()
virtual int SQHit::get_hit_id () const inline virtual
Return the ID of this hit.
Reimplemented in SQHit_v1, and SQCalHit_v1.
Definition at line 39 of file SQHit.h.
Referenced by mTrkEveDisplay::draw_tracks(), SQHitMap_v1::insert(), SQHitMap_v1::operator=(), DoEmbedding::process_event(), SimpleTree::process_event(), UtilSRawEvent::SetHit(), UtilSRawEvent::SetTriggerHit(), and SQHitMap_v1::SQHitMap_v1().
get_level()
virtual short SQHit::get_level () const inline virtual
Return the trigger level of this hit. Meaningful only if this hit is of V1495 TDC.
Reimplemented in SQHit_v1.
Definition at line 51 of file SQHit.h.
Referenced by CalibHodoInTime::process_event().
get_n_cells()
virtual unsigned int SQHit::get_n_cells () const inline virtual
Return the number of cells included in this hit.
Reimplemented in SQCalHit_v1.
Definition at line 99 of file SQHit.h.
get_pos()
virtual float SQHit::get_pos () const inline virtual
Return the absolute position of this hit. Probably the value is not properly set at present.
Reimplemented in SQHit_v1.
Definition at line 60 of file SQHit.h.
Referenced by CalibHitPos::process_event(), SimpleTree::process_event(), UtilSRawEvent::SetHit(), and UtilSRawEvent::SetTriggerHit().
get_tdc_time()
virtual float SQHit::get_tdc_time () const inline virtual
Return the TDC time (nsec) of this hit.
Reimplemented in SQHit_v1.
Definition at line 54 of file SQHit.h.
Referenced by UtilSQHit::FindFirstHits(), AnaChamHit::process_event(), SimpleTree::process_event(), CalibDriftDist::process_event(), CalibHodoInTime::process_event(), UtilSRawEvent::SetHit(), and UtilSRawEvent::SetTriggerHit().
get_tower_id()
virtual short SQHit::get_tower_id () const inline virtual
Not valid in E1039. To be deleted.
Reimplemented in SQCalHit_v1.
Definition at line 48 of file SQHit.h.
get_track_id()
virtual int SQHit::get_track_id () const inline virtual
Return the track ID associated with this hit. Probably the value is not properly set at present.
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 66 of file SQHit.h.
Referenced by UtilTrack::FindDetectorHitsOfTrack(), UtilTrack::FindHitsOfTrack(), DoEmbedding::process_event(), SimpleTree::process_event(), SQGeomAcc::process_event(), and TruthNodeMaker::process_event().
get_truth_px()
virtual float SQHit::get_truth_px () const inline virtual
Return the true x-momentum of this hit. Meaningful only if this hit is of MC.
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 81 of file SQHit.h.
get_truth_py()
virtual float SQHit::get_truth_py () const inline virtual
Return the true y-momentum of this hit. Meaningful only if this hit is of MC.
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 84 of file SQHit.h.
get_truth_pz()
virtual float SQHit::get_truth_pz () const inline virtual
Return the true z-momentum of this hit. Meaningful only if this hit is of MC.
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 87 of file SQHit.h.
get_truth_x()
virtual float SQHit::get_truth_x () const inline virtual
Return the true x-position of this hit. Meaningful only if this hit is of MC.
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 72 of file SQHit.h.
get_truth_y()
virtual float SQHit::get_truth_y () const inline virtual
Return the true y-position of this hit. Meaningful only if this hit is of MC.
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 75 of file SQHit.h.
get_truth_z()
virtual float SQHit::get_truth_z () const inline virtual
Return the true z-position of this hit. Meaningful only if this hit is of MC.
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 78 of file SQHit.h.
identify()
virtual void SQHit::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SQMCHit_v1, SQHit_v1, SQCalMCHit_v1, and SQCalHit_v1.
Definition at line 30 of file SQHit.h.
is_hodo_mask()
virtual bool SQHit::is_hodo_mask () const inline virtual
Return 'true' if this hit is accepted (or masked out?) by the hodoscope masking. Meaningful only if this hit is of drift chamber.
Reimplemented in SQHit_v1.
Definition at line 93 of file SQHit.h.
is_in_time()
virtual bool SQHit::is_in_time () const inline virtual
Return 'true' if this hit is in the time window.
Reimplemented in SQHit_v1.
Definition at line 90 of file SQHit.h.
Referenced by UtilSQHit::FindFirstHits(), UtilSQHit::FindHits(), SimpleTree::process_event(), DPTriggerAnalyzer::process_event(), UtilSRawEvent::SetHit(), and UtilSRawEvent::SetTriggerHit().
is_trigger_mask()
virtual bool SQHit::is_trigger_mask () const inline virtual
Return 'true' if this hit is accepted (or masked out?) by the trigger-road masking. Meaningful only if this hit is of drift chamber.
Reimplemented in SQHit_v1.
Definition at line 96 of file SQHit.h.
isValid()
virtual int SQHit::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SQMCHit_v1, SQHit_v1, SQCalMCHit_v1, and SQCalHit_v1.
Definition at line 34 of file SQHit.h.
Reset()
virtual void SQHit::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SQMCHit_v1, SQHit_v1, SQCalMCHit_v1, and SQCalHit_v1.
Definition at line 33 of file SQHit.h.
set_detector_id()
virtual void SQHit::set_detector_id (const short a) inline virtual
Reimplemented in SQHit_v1, and SQCalHit_v1.
Definition at line 43 of file SQHit.h.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_drift_distance()
virtual void SQHit::set_drift_distance (const float a) inline virtual
Reimplemented in SQHit_v1.
Definition at line 58 of file SQHit.h.
Referenced by SQDigitizer::digitizeEMCal(), CalibDriftDist::process_event(), CalibHodoInTime::process_event(), SQChamberRealization::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), Fun4AllEVIOInputManager::run(), and SQReco::updateHitInfo().
set_edep()
virtual void SQHit::set_edep (const float a) inline virtual
Reimplemented in SQCalHit_v1.
Definition at line 64 of file SQHit.h.
set_element_id()
virtual void SQHit::set_element_id (const short a) inline virtual
Reimplemented in SQHit_v1, and SQCalHit_v1.
Definition at line 46 of file SQHit.h.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_g4hit_id()
virtual void SQHit::set_g4hit_id (const PHG4HitDefs::keytype a) inline virtual
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 70 of file SQHit.h.
set_hit_id()
virtual void SQHit::set_hit_id (const int a) inline virtual
Reimplemented in SQHit_v1, and SQCalHit_v1.
Definition at line 40 of file SQHit.h.
Referenced by Fun4AllSRawEventInputManager::E906ToE1039(), DoEmbedding::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and Fun4AllEVIOInputManager::run().
set_hodo_mask()
virtual void SQHit::set_hodo_mask (const bool a) inline virtual
Reimplemented in SQHit_v1.
Definition at line 94 of file SQHit.h.
Referenced by SQDigitizer::digitizeEMCal(), and SQReco::updateHitInfo().
set_in_time()
virtual void SQHit::set_in_time (const bool a) inline virtual
Reimplemented in SQHit_v1.
Definition at line 91 of file SQHit.h.
Referenced by SQDigitizer::digitizeEMCal(), Fun4AllSRawEventInputManager::E906ToE1039(), CalibDriftDist::process_event(), CalibHodoInTime::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), and SQReco::updateHitInfo().
set_level()
virtual void SQHit::set_level (const short a) inline virtual
Reimplemented in SQHit_v1.
Definition at line 52 of file SQHit.h.
Referenced by Fun4AllEVIOInputManager::run().
set_pos()
virtual void SQHit::set_pos (const float a) inline virtual
Reimplemented in SQHit_v1.
Definition at line 61 of file SQHit.h.
Referenced by SQDigitizer::digitizeEMCal(), CalibHitPos::process_event(), CalibDriftDist::process_event(), CalibHitElementPos::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), Fun4AllEVIOInputManager::run(), and SQReco::updateHitInfo().
set_tdc_time()
virtual void SQHit::set_tdc_time (const float a) inline virtual
Reimplemented in SQHit_v1.
Definition at line 55 of file SQHit.h.
Referenced by SQDigitizer::digitizeEMCal(), Fun4AllSRawEventInputManager::E906ToE1039(), SQChamberRealization::process_event(), Fun4AllHitMatrixInputManager::run(), Fun4AllTrackQAv1InputManager::run(), Fun4AllEVIOInputManager::run(), and SQReco::updateHitInfo().
set_tower_id()
virtual void SQHit::set_tower_id (const short a) inline virtual
Reimplemented in SQCalHit_v1.
Definition at line 49 of file SQHit.h.
set_track_id()
virtual void SQHit::set_track_id (const int a) inline virtual
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 67 of file SQHit.h.
Referenced by DoEmbedding::process_event().
set_trigger_mask()
virtual void SQHit::set_trigger_mask (const bool a) inline virtual
Reimplemented in SQHit_v1.
Definition at line 97 of file SQHit.h.
Referenced by SQReco::updateHitInfo().
set_truth_px()
virtual void SQHit::set_truth_px (const float a) inline virtual
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 82 of file SQHit.h.
set_truth_py()
virtual void SQHit::set_truth_py (const float a) inline virtual
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 85 of file SQHit.h.
set_truth_pz()
virtual void SQHit::set_truth_pz (const float a) inline virtual
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 88 of file SQHit.h.
set_truth_x()
virtual void SQHit::set_truth_x (const float a) inline virtual
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 73 of file SQHit.h.
set_truth_y()
virtual void SQHit::set_truth_y (const float a) inline virtual
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 76 of file SQHit.h.
set_truth_z()
virtual void SQHit::set_truth_z (const float a) inline virtual
Reimplemented in SQMCHit_v1, and SQCalMCHit_v1.
Definition at line 79 of file SQHit.h.
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHit.h