Class Reference for E1039 Core & Analysis Software: UtilAsym Namespace Reference
UtilAsym Namespace Reference
Functions
void CalcAngle (const SQDimuon *dim, const int pol_sign, double &xb, double &xt, double &phi_s_tf)
void CalcAngle (const TVector3 &mu0, const TVector3 &mu1, const int pol_sign, double &xb, double &xt, double &phi_s_tf)
void CalcAngle (const TLorentzVector &mu0, const TLorentzVector &mu1, const int pol_sign, double &xb, double &xt, double &phi_s_tf)
Convert the momenta of two muons in the lab frame to "phi_s_tf", "xb" and "xt".
Function Documentation
CalcAngle() [1/3]
void UtilAsym::CalcAngle (const SQDimuon * dim, const int pol_sign, double & xb, double & xt, double & phi_s_tf)
Definition at line 7 of file UtilAsym.cc.
References SQDimuon::get_mom_neg(), and SQDimuon::get_mom_pos().
Referenced by CalcAngle().
CalcAngle() [2/3]
void UtilAsym::CalcAngle (const TLorentzVector & mu0, const TLorentzVector & mu1, const int pol_sign, double & xb, double & xt, double & phi_s_tf)
Convert the momenta of two muons in the lab frame to "phi_s_tf", "xb" and "xt".
Imported from "asymmetry.C" written by Abinash.
Definition at line 22 of file UtilAsym.cc.
CalcAngle() [3/3]
void UtilAsym::CalcAngle (const TVector3 & mu0, const TVector3 & mu1, const int pol_sign, double & xb, double & xt, double & phi_s_tf)
Definition at line 12 of file UtilAsym.cc.
References CalcAngle(), and M_MU.