E1039 Software: TrkEval Class Reference
TrkEval Class Reference
General purposed evaluation module.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/module_example/TrkEval.h>
Public Member Functions
TrkEval (const std::string &name="TrkEval")
virtual ~TrkEval ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int InitEvalTree ()
int ResetEvalVars ()
const std::string & get_hit_container_choice () const
void set_hit_container_choice (const std::string &hitContainerChoice)
const std::string & get_out_name () const
void set_out_name (const std::string &outName)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
General purposed evaluation module.
Author
Haiwang Yu, yuhw@.nosp@m.nmsu.nosp@m..edu
Created: 08-27-2018
Definition at line 44 of file TrkEval.h.
Constructor & Destructor Documentation
TrkEval::TrkEval (const std::string & name = "TrkEval")
Definition at line 58 of file TrkEval.cxx.
virtual TrkEval::~TrkEval () inline virtual
Definition at line 49 of file TrkEval.h.
Member Function Documentation
int TrkEval::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 851 of file TrkEval.cxx.
References PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
const std::string& TrkEval::get_hit_container_choice () const inline
Definition at line 60 of file TrkEval.h.
const std::string& TrkEval::get_out_name () const inline
Definition at line 68 of file TrkEval.h.
int TrkEval::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 71 of file TrkEval.cxx.
References Fun4AllReturnCodes::EVENT_OK.
int TrkEval::InitEvalTree ()
Definition at line 862 of file TrkEval.cxx.
References PHTFileServer::get(), and PHTFileServer::open().
Referenced by InitRun().
int TrkEval::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 75 of file TrkEval.cxx.
References Fun4AllReturnCodes::EVENT_OK, InitEvalTree(), GeomSvc::instance(), and ResetEvalVars().
int TrkEval::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 88 of file TrkEval.cxx.
References Fun4AllReturnCodes::ABORTRUN, and Fun4AllReturnCodes::EVENT_OK.
int TrkEval::ResetEvalVars ()
Definition at line 998 of file TrkEval.cxx.
References NDET.
Referenced by InitRun().
void TrkEval::set_hit_container_choice (const std::string & hitContainerChoice) inline
Definition at line 64 of file TrkEval.h.
Referenced by Fun4DB(), Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4PatternDB(), Fun4Sim(), and Fun4TrkDev().
void TrkEval::set_out_name (const std::string & outName) inline
Definition at line 72 of file TrkEval.h.
Referenced by Fun4DB(), Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4PatternDB(), Fun4Sim(), and Fun4TrkDev().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/module_example/TrkEval.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/module_example/TrkEval.cxx