Class Reference for E1039 Core & Analysis Software: Tracklet Class Reference
Tracklet Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/FastTracklet.h>
Public Member Functions
Tracklet ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
Tracklet * Clone () const
void print (std::ostream &os=std::cout)
void sortHits ()
int getNHits () const
int getNAllHits ()
double getProb () const
double getMomProb () const
double getChisq () const
double getExpPositionX (double z) const
double getExpPosErrorX (double z) const
double getExpPositionY (double z) const
double getExpPosErrorY (double z) const
double getExpPositionW (int detectorID) const
int getExpElementID (int detectorID) const
TVector3 getMomentumSt1 () const
TVector3 getMomentumSt3 () const
TVector3 getExpMomentum (double z) const
SignedHit getSignedHit (int index)
double Eval (const double *par)
double Eval4 (const double *par)
double calcChisq ()
void addDummyHits ()
double getMomentum () const
int getCharge () const
Return the charge (+1 or -1) of this tracklet.
void getXZInfoInSt1 (double &tx_st1, double &x0_st1) const
void getXZErrorInSt1 (double &err_tx_st1, double &err_x0_st1) const
bool operator< (const Tracklet &elem) const
bool similarity (const Tracklet &elem) const
Tracklet merge (Tracklet &elem)
Tracklet operator+ (const Tracklet &elem) const
Tracklet operator* (const Tracklet &elem) const
SRecTrack getSRecTrack (bool hyptest=true)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Public Attributes
int stationID
int nXHits
int nUHits
int nVHits
double chisq
double chisq_vtx
std::list< SignedHit > hits
PropSegment seg_x
PropSegment seg_y
double tx
double ty
double x0
double y0
double invP
double err_tx
double err_ty
double err_x0
double err_y0
double err_invP
double residual [nChamberPlanes]
Detailed Description
Definition at line 123 of file FastTracklet.h.
Constructor & Destructor Documentation
Tracklet()
Tracklet::Tracklet ()
Definition at line 500 of file FastTracklet.cxx.
References nChamberPlanes, and residual.
Referenced by Clone(), and Reset().
Member Function Documentation
addDummyHits()
void Tracklet::addDummyHits ()
Definition at line 900 of file FastTracklet.cxx.
References Hit::detectorID, SignedHit::hit, hits, sortHits(), and stationID.
calcChisq()
double Tracklet::calcChisq ()
The drift distance of a hit is ignored if the drift sign of the hit is not fixed.
Definition at line 929 of file FastTracklet.cxx.
References chisq, getXZInfoInSt1(), hits, nStations, residual, stationID, tx, ty, x0, and y0.
Referenced by Eval(), Eval4(), merge(), operator*(), operator+(), print(), KalmanFastTracking::removeBadHits(), and KalmanDSTrk::removeBadHits().
Clone()
Tracklet* Tracklet::Clone () const inline
Definition at line 132 of file FastTracklet.h.
References Tracklet().
Referenced by TrackletVector::push_back().
Eval()
double Tracklet::Eval (const double * par)
Definition at line 986 of file FastTracklet.cxx.
References calcChisq(), invP, tx, ty, x0, and y0.
Referenced by KalmanDSTrk::KalmanDSTrk(), and SQTrackletFitter::SQTrackletFitter().
Eval4()
double Tracklet::Eval4 (const double * par)
Definition at line 998 of file FastTracklet.cxx.
References calcChisq(), tx, ty, x0, and y0.
getCharge()
int Tracklet::getCharge () const
Return the charge (+1 or -1) of this tracklet.
This function should be as simple as possible, in order to reduce the computation time. Therefore the condition of the charge determination uses only "x0" and "tx" (at St. 2+3). The formula was obtained practically by the study in DocDB 9505. This function is valid for both the parallel and anti-parallel FMag+KMag polarity combination. But it is not guaranteed to be valid when the FMag and/or KMag field strength is changed largely.
Definition at line 745 of file FastTracklet.cxx.
References FMAGSTR, tx, and x0.
Referenced by SQGenFit::GFTrack::getCharge(), getExpPositionX(), getMomentum(), getSRecTrack(), getXZInfoInSt1(), print(), SimpleTree::process_event(), KalmanDSTrk::processOneTracklet(), KalmanTrack::setTracklet(), and SQGenFit::GFTrack::setTracklet().
getChisq()
double Tracklet::getChisq () const inline
Definition at line 157 of file FastTracklet.h.
References chisq.
Referenced by AnaModule::process_event(), and SimpleTree::process_event().
getExpElementID()
int Tracklet::getExpElementID (int detectorID) const
Definition at line 657 of file FastTracklet.cxx.
References getExpPositionW().
getExpMomentum()
TVector3 Tracklet::getExpMomentum (double z) const
Definition at line 593 of file FastTracklet.cxx.
References getMomentumSt1(), getMomentumSt3(), nStations, and stationID.
Referenced by SQGenFit::GFTrack::setTracklet().
getExpPosErrorX()
double Tracklet::getExpPosErrorX (double z) const
Definition at line 613 of file FastTracklet.cxx.
References err_invP, err_tx, err_x0, nStations, and stationID.
Referenced by KalmanFastTracking::getExtrapoWindowsInSt1(), KalmanDSTrk::getExtrapoWindowsInSt1(), getSRecTrack(), KalmanFastTracking::hodoMask(), KalmanDSTrk::hodoMask(), KalmanFastTracking::muonID_hodoAid(), KalmanDSTrk::muonID_hodoAid(), and print().
getExpPosErrorY()
double Tracklet::getExpPosErrorY (double z) const
Definition at line 638 of file FastTracklet.cxx.
References err_ty, and err_y0.
Referenced by KalmanFastTracking::getExtrapoWindowsInSt1(), KalmanDSTrk::getExtrapoWindowsInSt1(), getSRecTrack(), KalmanFastTracking::hodoMask(), KalmanDSTrk::hodoMask(), KalmanFastTracking::muonID_hodoAid(), KalmanDSTrk::muonID_hodoAid(), and print().
getExpPositionW()
double Tracklet::getExpPositionW (int detectorID) const
Definition at line 646 of file FastTracklet.cxx.
References getExpPositionX(), and getExpPositionY().
Referenced by MakeRTCurve::AnalyzeFile(), CalibData::FillTrackletHits(), getExpElementID(), main(), AnaTrack::process_event(), AnaModule::process_event(), and SimpleTree::process_event().
getExpPositionX()
double Tracklet::getExpPositionX (double z) const
Definition at line 598 of file FastTracklet.cxx.
References getCharge(), invP, nStations, stationID, tx, and x0.
Referenced by KalmanFastTracking::acceptTracklet(), KalmanDSTrk::acceptTracklet(), getExpPositionW(), KalmanFastTracking::getExtrapoWindowsInSt1(), KalmanDSTrk::getExtrapoWindowsInSt1(), getMomentum(), KalmanFastTracking::getSagittaWindowsInSt1(), KalmanDSTrk::getSagittaWindowsInSt1(), getSRecTrack(), KalmanFastTracking::hodoMask(), KalmanDSTrk::hodoMask(), KalmanFastTracking::muonID_comp(), KalmanDSTrk::muonID_comp(), KalmanFastTracking::muonID_hodoAid(), KalmanDSTrk::muonID_hodoAid(), KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), print(), AnaModule::process_event(), SimpleTree::process_event(), KalmanDSTrk::processOneTracklet(), KalmanFastTracking::resolveLeftRight(), KalmanDSTrk::resolveLeftRight(), KalmanFastTracking::resolveSingleLeftRight(), KalmanDSTrk::resolveSingleLeftRight(), KalmanTrack::setTracklet(), SQGenFit::GFTrack::setTracklet(), and TriggerRoad::TriggerRoad().
getExpPositionY()
double Tracklet::getExpPositionY (double z) const
Definition at line 633 of file FastTracklet.cxx.
References ty, and y0.
Referenced by KalmanFastTracking::acceptTracklet(), KalmanDSTrk::acceptTracklet(), getExpPositionW(), KalmanFastTracking::getExtrapoWindowsInSt1(), KalmanDSTrk::getExtrapoWindowsInSt1(), KalmanFastTracking::getSagittaWindowsInSt1(), KalmanDSTrk::getSagittaWindowsInSt1(), getSRecTrack(), KalmanFastTracking::hodoMask(), KalmanDSTrk::hodoMask(), KalmanFastTracking::muonID_comp(), KalmanDSTrk::muonID_comp(), KalmanFastTracking::muonID_hodoAid(), KalmanDSTrk::muonID_hodoAid(), KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), print(), AnaModule::process_event(), SimpleTree::process_event(), KalmanDSTrk::processOneTracklet(), KalmanFastTracking::resolveLeftRight(), KalmanDSTrk::resolveLeftRight(), KalmanFastTracking::resolveSingleLeftRight(), KalmanDSTrk::resolveSingleLeftRight(), KalmanTrack::setTracklet(), SQGenFit::GFTrack::setTracklet(), and TriggerRoad::TriggerRoad().
getMomentum()
double Tracklet::getMomentum () const
Definition at line 703 of file FastTracklet.cxx.
References getCharge(), getExpPositionX(), tx, and x0.
Referenced by merge(), operator*(), and operator+().
getMomentumSt1()
TVector3 Tracklet::getMomentumSt1 () const
Definition at line 1066 of file FastTracklet.cxx.
References getXZInfoInSt1(), invP, and ty.
Referenced by getExpMomentum(), and print().
getMomentumSt3()
TVector3 Tracklet::getMomentumSt3 () const
Definition at line 1075 of file FastTracklet.cxx.
References invP, tx, and ty.
Referenced by getExpMomentum(), and print().
getMomProb()
double Tracklet::getMomProb () const
Definition at line 585 of file FastTracklet.cxx.
References invP.
getNAllHits()
int Tracklet::getNAllHits () inline
Definition at line 148 of file FastTracklet.h.
References hits.
getNHits()
int Tracklet::getNHits () const inline
Definition at line 145 of file FastTracklet.h.
References nUHits, nVHits, and nXHits.
Referenced by MakeRTCurve::AnalyzeFile(), CalibData::FillTracklet(), SRMakeRTCurve::FindBestTracklet(), getProb(), operator<(), AnaTrack::process_event(), AnaModule::process_event(), SimpleTree::process_event(), and similarity().
getProb()
double Tracklet::getProb () const
Definition at line 569 of file FastTracklet.cxx.
References chisq, getNHits(), nStations, and stationID.
Referenced by isValid(), and operator<().
getSignedHit()
SignedHit Tracklet::getSignedHit (int index)
Definition at line 973 of file FastTracklet.cxx.
References hits.
getSRecTrack()
SRecTrack Tracklet::getSRecTrack (bool hyptest = true)
Definition at line 1009 of file FastTracklet.cxx.
References PropSegment::a, chisq, err_invP, err_tx, err_ty, err_x0, getCharge(), getExpPosErrorX(), getExpPosErrorY(), getExpPositionX(), getExpPositionY(), PropSegment::getNHits(), TriggerRoad::getRoadID(), getXZErrorInSt1(), getXZInfoInSt1(), hits, SRecTrack::insertCovariance(), SRecTrack::insertHitIndex(), SRecTrack::insertStateVector(), SRecTrack::insertZ(), invP, seg_x, seg_y, SRecTrack::setChisq(), SRecTrack::setNHitsInPT(), SRecTrack::setPTSlope(), SRecTrack::setTriggerRoad(), SRecTrack::swimToVertex(), tx, ty, and x0.
Referenced by KalmanFastTracking::processOneTracklet(), and KalmanDSTrk::processOneTracklet().
getXZErrorInSt1()
void Tracklet::getXZErrorInSt1 (double & err_tx_st1, double & err_x0_st1) const
Definition at line 764 of file FastTracklet.cxx.
References err_invP, err_tx, and err_x0.
Referenced by getSRecTrack(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
getXZInfoInSt1()
void Tracklet::getXZInfoInSt1 (double & tx_st1, double & x0_st1) const
Definition at line 750 of file FastTracklet.cxx.
References getCharge(), invP, tx, and x0.
Referenced by calcChisq(), getMomentumSt1(), getSRecTrack(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
identify()
void Tracklet::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 129 of file FastTracklet.h.
References stationID.
isValid()
int Tracklet::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 506 of file FastTracklet.cxx.
References chisq, err_tx, err_ty, err_x0, err_y0, getProb(), hits, nStations, nUHits, nVHits, nXHits, stationID, tx, ty, x0, and y0.
Referenced by KalmanFastTracking::acceptTracklet(), KalmanDSTrk::acceptTracklet(), KalmanFastTracking::buildBackPartialTracks(), KalmanDSTrk::buildBackPartialTracks(), KalmanFastTracking::buildGlobalTracks(), KalmanDSTrk::buildGlobalTracks(), KalmanDSTrk::buildTrackletsInStation(), KalmanFastTracking::buildTrackletsInStation(), KalmanFastTrackletting::buildTrackletsInStation(), merge(), KalmanFastTracking::removeBadHits(), and KalmanDSTrk::removeBadHits().
merge()
Tracklet Tracklet::merge (Tracklet & elem)
Definition at line 867 of file FastTracklet.cxx.
References calcChisq(), chisq_vtx, err_invP, err_tx, err_ty, err_x0, err_y0, getMomentum(), hits, invP, isValid(), seg_x, seg_y, stationID, tx, ty, x0, and y0.
Referenced by KalmanFastTracking::buildGlobalTracks(), and KalmanDSTrk::buildGlobalTracks().
operator*()
Tracklet Tracklet::operator* (const Tracklet & elem) const
Definition at line 815 of file FastTracklet.cxx.
References calcChisq(), err_invP, err_tx, err_ty, err_x0, err_y0, getMomentum(), hits, invP, nStations, nUHits, nVHits, nXHits, stationID, tx, ty, x0, and y0.
operator+()
Tracklet Tracklet::operator+ (const Tracklet & elem) const
Definition at line 779 of file FastTracklet.cxx.
References calcChisq(), err_invP, err_tx, err_ty, err_x0, err_y0, getMomentum(), hits, invP, nStations, nUHits, nVHits, nXHits, stationID, tx, ty, x0, and y0.
operator<()
bool Tracklet::operator< (const Tracklet & elem) const
Definition at line 662 of file FastTracklet.cxx.
References chisq, getNHits(), and getProb().
print()
void Tracklet::print (std::ostream & os = std::cout)
Definition at line 1081 of file FastTracklet.cxx.
References calcChisq(), chisq, err_invP, err_tx, err_ty, err_x0, err_y0, getCharge(), getExpPosErrorX(), getExpPosErrorY(), getExpPositionX(), getExpPositionY(), getMomentumSt1(), getMomentumSt3(), hits, invP, KMAGSTR, nUHits, nVHits, nXHits, residual, stationID, tx, ty, x0, and y0.
Referenced by KalmanFastTracking::buildBackPartialTracks(), KalmanDSTrk::buildBackPartialTracks(), KalmanFastTracking::buildGlobalTracks(), KalmanDSTrk::buildGlobalTracks(), KalmanDSTrk::buildTrackletsInStation(), KalmanFastTracking::buildTrackletsInStation(), main(), SQGenFit::GFTrack::print(), KalmanFastTracking::removeBadHits(), KalmanDSTrk::removeBadHits(), KalmanFastTracking::resolveLeftRight(), KalmanDSTrk::resolveLeftRight(), KalmanFastTracking::resolveSingleLeftRight(), and KalmanDSTrk::resolveSingleLeftRight().
Reset()
void Tracklet::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 130 of file FastTracklet.h.
References Tracklet().
similarity()
bool Tracklet::similarity (const Tracklet & elem) const
Definition at line 675 of file FastTracklet.cxx.
References getNHits(), and hits.
sortHits()
void Tracklet::sortHits () inline
Definition at line 142 of file FastTracklet.h.
References hits.
Referenced by addDummyHits(), KalmanDSTrk::buildTrackletsInStation(), KalmanFastTracking::buildTrackletsInStation(), and KalmanFastTrackletting::buildTrackletsInStation().
Member Data Documentation
chisq
double Tracklet::chisq
Definition at line 222 of file FastTracklet.h.
Referenced by MakeRTCurve::AnalyzeFile(), KalmanFastTracking::buildBackPartialTracks(), KalmanDSTrk::buildBackPartialTracks(), calcChisq(), CalibData::FillTracklet(), SRMakeRTCurve::FindBestTracklet(), SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getChisq(), getProb(), getSRecTrack(), isValid(), operator<(), print(), and AnaTrack::process_event().
chisq_vtx
double Tracklet::chisq_vtx
Definition at line 225 of file FastTracklet.h.
Referenced by KalmanFastTracking::buildGlobalTracks(), KalmanDSTrk::buildGlobalTracks(), and merge().
err_invP
double Tracklet::err_invP
Definition at line 245 of file FastTracklet.h.
Referenced by SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getExpPosErrorX(), getSRecTrack(), getXZErrorInSt1(), merge(), operator*(), operator+(), and print().
err_tx
double Tracklet::err_tx
Definition at line 241 of file FastTracklet.h.
Referenced by SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getExpPosErrorX(), getSRecTrack(), getXZErrorInSt1(), isValid(), merge(), operator*(), operator+(), print(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
err_ty
double Tracklet::err_ty
Definition at line 242 of file FastTracklet.h.
Referenced by SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getExpPosErrorY(), getSRecTrack(), isValid(), merge(), operator*(), operator+(), print(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
err_x0
double Tracklet::err_x0
Definition at line 243 of file FastTracklet.h.
Referenced by SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getExpPosErrorX(), getSRecTrack(), getXZErrorInSt1(), isValid(), merge(), operator*(), operator+(), print(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
err_y0
double Tracklet::err_y0
Definition at line 244 of file FastTracklet.h.
Referenced by SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getExpPosErrorY(), isValid(), merge(), operator*(), operator+(), print(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
hits
std::list<SignedHit> Tracklet::hits
Definition at line 228 of file FastTracklet.h.
Referenced by addDummyHits(), MakeRTCurve::AnalyzeFile(), KalmanDSTrk::buildTrackletsInStation(), KalmanFastTracking::buildTrackletsInStation(), KalmanFastTrackletting::buildTrackletsInStation(), calcChisq(), CalibData::FillTrackletHits(), getNAllHits(), KalmanFastTracking::getSagittaWindowsInSt1(), KalmanDSTrk::getSagittaWindowsInSt1(), getSignedHit(), getSRecTrack(), PatternDBUtil::GetTrackletKey(), isValid(), main(), merge(), operator*(), operator+(), print(), AnaTrack::process_event(), KalmanDSTrk::processOneTracklet(), KalmanFastTracking::removeBadHits(), KalmanDSTrk::removeBadHits(), KalmanFastTracking::resolveLeftRight(), KalmanDSTrk::resolveLeftRight(), KalmanFastTracking::resolveSingleLeftRight(), KalmanDSTrk::resolveSingleLeftRight(), KalmanTrack::setTracklet(), SQGenFit::GFTrack::setTracklet(), similarity(), and sortHits().
invP
double Tracklet::invP
Definition at line 239 of file FastTracklet.h.
Referenced by KalmanFastTracking::buildGlobalTracks(), KalmanDSTrk::buildGlobalTracks(), Eval(), CalibData::FillTracklet(), SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getExpPositionX(), getMomentumSt1(), getMomentumSt3(), getMomProb(), getSRecTrack(), getXZInfoInSt1(), main(), merge(), KalmanFastTracking::muonID_comp(), KalmanDSTrk::muonID_comp(), KalmanFastTracking::muonID_hodoAid(), KalmanDSTrk::muonID_hodoAid(), KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), operator*(), operator+(), print(), AnaTrack::process_event(), KalmanDSTrk::processOneTracklet(), and KalmanTrack::setTracklet().
nUHits
int Tracklet::nUHits mutable
Definition at line 218 of file FastTracklet.h.
Referenced by KalmanDSTrk::buildTrackletsInStation(), KalmanFastTracking::buildTrackletsInStation(), KalmanFastTrackletting::buildTrackletsInStation(), getNHits(), isValid(), operator*(), operator+(), print(), KalmanFastTracking::removeBadHits(), and KalmanDSTrk::removeBadHits().
nVHits
int Tracklet::nVHits mutable
Definition at line 219 of file FastTracklet.h.
Referenced by KalmanDSTrk::buildTrackletsInStation(), KalmanFastTracking::buildTrackletsInStation(), KalmanFastTrackletting::buildTrackletsInStation(), getNHits(), isValid(), operator*(), operator+(), print(), KalmanFastTracking::removeBadHits(), and KalmanDSTrk::removeBadHits().
nXHits
int Tracklet::nXHits mutable
Definition at line 217 of file FastTracklet.h.
Referenced by KalmanDSTrk::buildTrackletsInStation(), KalmanFastTracking::buildTrackletsInStation(), KalmanFastTrackletting::buildTrackletsInStation(), getNHits(), isValid(), operator*(), operator+(), print(), KalmanFastTracking::removeBadHits(), and KalmanDSTrk::removeBadHits().
residual
double Tracklet::residual[nChamberPlanes]
Definition at line 248 of file FastTracklet.h.
Referenced by calcChisq(), print(), KalmanFastTracking::removeBadHits(), KalmanDSTrk::removeBadHits(), and Tracklet().
seg_x
PropSegment Tracklet::seg_x
Definition at line 231 of file FastTracklet.h.
Referenced by SQReco::fitTrackCand(), getSRecTrack(), merge(), KalmanFastTracking::muonID_comp(), KalmanDSTrk::muonID_comp(), KalmanFastTracking::muonID_hodoAid(), KalmanDSTrk::muonID_hodoAid(), KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), KalmanFastTracking::processOneTracklet(), and KalmanDSTrk::processOneTracklet().
seg_y
PropSegment Tracklet::seg_y
Definition at line 232 of file FastTracklet.h.
Referenced by SQReco::fitTrackCand(), getSRecTrack(), merge(), KalmanFastTracking::muonID_comp(), KalmanDSTrk::muonID_comp(), KalmanFastTracking::muonID_hodoAid(), KalmanDSTrk::muonID_hodoAid(), KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), KalmanFastTracking::processOneTracklet(), and KalmanDSTrk::processOneTracklet().
stationID
int Tracklet::stationID
Definition at line 214 of file FastTracklet.h.
Referenced by KalmanFastTracking::acceptTracklet(), KalmanDSTrk::acceptTracklet(), addDummyHits(), MakeRTCurve::AnalyzeFile(), KalmanDSTrk::buildTrackletsInStation(), KalmanFastTracking::buildTrackletsInStation(), KalmanFastTrackletting::buildTrackletsInStation(), calcChisq(), CalibData::FillTracklet(), SRMakeRTCurve::FindBestTracklet(), KalmanDSTrk::fitTracklet(), getExpMomentum(), getExpPosErrorX(), getExpPositionX(), KalmanFastTracking::getExtrapoWindowsInSt1(), KalmanDSTrk::getExtrapoWindowsInSt1(), getProb(), KalmanFastTracking::getSagittaWindowsInSt1(), KalmanDSTrk::getSagittaWindowsInSt1(), KalmanFastTracking::hodoMask(), KalmanDSTrk::hodoMask(), identify(), SRMakeRTCurve::InAcceptance(), isValid(), main(), merge(), KalmanFastTracking::muonID_comp(), KalmanDSTrk::muonID_comp(), KalmanFastTracking::muonID_hodoAid(), KalmanDSTrk::muonID_hodoAid(), KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), operator*(), operator+(), print(), SRMakeRTCurve::process_event(), AnaTrack::process_event(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
tx
double Tracklet::tx
Definition at line 235 of file FastTracklet.h.
Referenced by MakeRTCurve::AnalyzeFile(), calcChisq(), Eval(), Eval4(), CalibData::FillTracklet(), SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getCharge(), getExpPositionX(), getMomentum(), getMomentumSt3(), getSRecTrack(), getXZInfoInSt1(), SRMakeRTCurve::InAcceptance(), isValid(), main(), merge(), KalmanFastTracking::muonID_comp(), KalmanDSTrk::muonID_comp(), KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), operator*(), operator+(), print(), AnaTrack::process_event(), KalmanDSTrk::processOneTracklet(), KalmanFastTracking::resolveLeftRight(), KalmanDSTrk::resolveLeftRight(), and KalmanTrack::setTracklet().
ty
double Tracklet::ty
Definition at line 236 of file FastTracklet.h.
Referenced by MakeRTCurve::AnalyzeFile(), calcChisq(), Eval(), Eval4(), CalibData::FillTracklet(), SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getExpPositionY(), getMomentumSt1(), getMomentumSt3(), getSRecTrack(), SRMakeRTCurve::InAcceptance(), isValid(), main(), merge(), KalmanFastTracking::muonID_comp(), KalmanDSTrk::muonID_comp(), KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), operator*(), operator+(), print(), AnaTrack::process_event(), KalmanDSTrk::processOneTracklet(), KalmanFastTracking::resolveLeftRight(), KalmanDSTrk::resolveLeftRight(), and KalmanTrack::setTracklet().
x0
double Tracklet::x0
Definition at line 237 of file FastTracklet.h.
Referenced by calcChisq(), Eval(), Eval4(), CalibData::FillTracklet(), SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getCharge(), getExpPositionX(), getMomentum(), getSRecTrack(), getXZInfoInSt1(), SRMakeRTCurve::InAcceptance(), isValid(), main(), merge(), operator*(), operator+(), print(), AnaTrack::process_event(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
y0
double Tracklet::y0
Definition at line 238 of file FastTracklet.h.
Referenced by calcChisq(), Eval(), Eval4(), CalibData::FillTracklet(), SQTrackletFitter::fit(), KalmanDSTrk::fitTracklet(), getExpPositionY(), SRMakeRTCurve::InAcceptance(), isValid(), main(), merge(), operator*(), operator+(), print(), AnaTrack::process_event(), KalmanFastTracking::resolveLeftRight(), and KalmanDSTrk::resolveLeftRight().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/FastTracklet.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/FastTracklet.cxx