SeaQuest Offline Software: PHG4SectorDetector Class Reference
PHG4SectorDetector Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SectorDetector.h>
Public Member Functions
PHG4SectorDetector (PHCompositeNode *Node, const std::string &dnam="SECTOR")
constructor
virtual ~PHG4SectorDetector (void)
destructor
virtual void Construct (G4LogicalVolume *world)
construct
virtual G4UserSteppingAction * GetSteppingAction ()
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
virtual void OverlapCheck (const bool chk=true)
volume accessors
bool IsInSectorActive (G4VPhysicalVolume *)
bool IsInSectorInactive (G4VPhysicalVolume *)
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual std::string GetName () const
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from PHG4Sector::PHG4SectorConstructor
PHG4SectorConstructor (std::string name)
virtual ~PHG4SectorConstructor ()
void Construct_Sectors (G4LogicalVolume *WorldLog)
void OverlapCheck (bool check)
Private Attributes
G4Region * _region
std::string superdetector
Additional Inherited Members
Public Attributes inherited from PHG4Sector::PHG4SectorConstructor
std::string name_base
Sector_Geometry geom
G4VisAttributes * DetectorVisAtt
Protected Types inherited from PHG4Sector::PHG4SectorConstructor
typedef std::map< G4String,
G4LogicalVolume * > map_log_vol_t
typedef std::pair< G4String,
G4int > phy_vol_idx_t
typedef std::map
< phy_vol_idx_t, G4PVPlacement * > map_phy_vol_t
Protected Member Functions inherited from PHG4Sector::PHG4SectorConstructor
G4VSolid * Construct_Sectors_Plane (const std::string &name, const double start_z, const double thickness, G4VSolid *SecConeBoundary_Det)
G4LogicalVolume * RegisterLogicalVolume (G4LogicalVolume *)
G4PVPlacement * RegisterPhysicalVolume (G4PVPlacement *v, const bool active=false)
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Protected Attributes inherited from PHG4Sector::PHG4SectorConstructor
bool overlapcheck_sector
map_log_vol_t map_log_vol
map_phy_vol_t map_phy_vol
map_phy_vol_t map_active_phy_vol
all physics volume
Detailed Description
Definition at line 21 of file PHG4SectorDetector.h.
Constructor & Destructor Documentation
PHG4SectorDetector::PHG4SectorDetector (PHCompositeNode * Node, const std::string & dnam = "SECTOR")
constructor
Definition at line 26 of file PHG4SectorDetector.cc.
virtual PHG4SectorDetector::~PHG4SectorDetector (void) inline virtual
destructor
Definition at line 30 of file PHG4SectorDetector.h.
Member Function Documentation
void PHG4SectorDetector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 58 of file PHG4SectorDetector.cc.
References PHG4Sector::PHG4SectorConstructor::Construct_Sectors(), PHG4Sector::PHG4SectorConstructor::DetectorVisAtt, PHG4Sector::PHG4SectorConstructor::map_log_vol, PHG4Sector::PHG4SectorConstructor::name_base, and PHG4Utils::SetColour().
virtual G4UserSteppingAction* PHG4SectorDetector::GetSteppingAction (void) inline virtual
Reimplemented from PHG4Detector.
Definition at line 43 of file PHG4SectorDetector.h.
References _region.
bool PHG4SectorDetector::IsInSectorActive (G4VPhysicalVolume * volume)
Definition at line 35 of file PHG4SectorDetector.cc.
References PHG4Sector::PHG4SectorConstructor::map_active_phy_vol.
Referenced by PHG4SectorSteppingAction::UserSteppingAction().
bool PHG4SectorDetector::IsInSectorInactive (G4VPhysicalVolume * volume)
Definition at line 51 of file PHG4SectorDetector.cc.
virtual void PHG4SectorDetector::OverlapCheck (const bool chk = true) inline virtual
Reimplemented from PHG4Detector.
Definition at line 55 of file PHG4SectorDetector.h.
References PHG4Detector::OverlapCheck().
Referenced by PHG4SectorSubsystem::Init().
void PHG4SectorDetector::SuperDetector (const std::string & name) inline
Definition at line 51 of file PHG4SectorDetector.h.
References PHG4Detector::name, and superdetector.
Referenced by PHG4SectorSubsystem::Init(), and PHG4SectorSteppingAction::SetInterfacePointers().
const std::string PHG4SectorDetector::SuperDetector () const inline
Definition at line 52 of file PHG4SectorDetector.h.
References superdetector.
Member Data Documentation
G4Region* PHG4SectorDetector::_region private
Definition at line 64 of file PHG4SectorDetector.h.
Referenced by GetSteppingAction().
std::string PHG4SectorDetector::superdetector private
Definition at line 66 of file PHG4SectorDetector.h.
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SectorDetector.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4SectorDetector.cc