SeaQuest Offline Software: PHG4OuterHcalSteppingAction Class Reference
PHG4OuterHcalSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4OuterHcalSteppingAction.h>
Public Member Functions
PHG4OuterHcalSteppingAction (PHG4OuterHcalDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4OuterHcalSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual int Init ()
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
double GetLightCorrection (const double r) const
void FieldChecker (const G4Step *)
void EnableFieldChecker (const int i=1)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4OuterHcalDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4Hit * hit
const PHParameters * params
PHG4HitContainer * savehitcontainer
PHG4Shower * saveshower
G4VPhysicalVolume * savevolpre
G4VPhysicalVolume * savevolpost
int savetrackid
int saveprestepstatus
int savepoststepstatus
int enable_field_checker
int absorbertruth
int IsActive
int IsBlackHole
int n_scinti_plates
int light_scint_model
double light_balance_inner_corr
double light_balance_inner_radius
double light_balance_outer_corr
double light_balance_outer_radius
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 13 of file PHG4OuterHcalSteppingAction.h.
Constructor & Destructor Documentation
PHG4OuterHcalSteppingAction::PHG4OuterHcalSteppingAction (PHG4OuterHcalDetector * detector, const PHParameters * parameters)
constructor
Definition at line 58 of file PHG4OuterHcalSteppingAction.cc.
References detector_, PHG4Detector::GetName(), and PHG4SteppingAction::name.
PHG4OuterHcalSteppingAction::~PHG4OuterHcalSteppingAction () virtual
destructor
Definition at line 85 of file PHG4OuterHcalSteppingAction.cc.
References hit.
Member Function Documentation
void PHG4OuterHcalSteppingAction::EnableFieldChecker (const int i = 1) inline
Definition at line 33 of file PHG4OuterHcalSteppingAction.h.
References enable_field_checker.
void PHG4OuterHcalSteppingAction::FieldChecker (const G4Step * aStep)
Definition at line 464 of file PHG4OuterHcalSteppingAction.cc.
References Fun4AllServer::getHisto(), Fun4AllServer::instance(), Fun4AllServer::isHistoRegistered(), and Fun4AllServer::registerHisto().
Referenced by UserSteppingAction().
double PHG4OuterHcalSteppingAction::GetLightCorrection (const double r) const
Definition at line 453 of file PHG4OuterHcalSteppingAction.cc.
References light_balance_inner_corr, light_balance_inner_radius, light_balance_outer_corr, and light_balance_outer_radius.
Referenced by UserSteppingAction().
int PHG4OuterHcalSteppingAction::Init () virtual
Reimplemented from PHG4SteppingAction.
Definition at line 94 of file PHG4OuterHcalSteppingAction.cc.
References enable_field_checker, and PHG4SteppingAction::GetIntOpt().
void PHG4OuterHcalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 419 of file PHG4OuterHcalSteppingAction.cc.
References absorberhits_, detector_, PHG4Detector::GetName(), hits_, PHG4OuterHcalDetector::SuperDetector(), and PHG4SteppingAction::Verbosity().
bool PHG4OuterHcalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 101 of file PHG4OuterHcalSteppingAction.cc.
References absorberhits_, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, enable_field_checker, FieldChecker(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Hit::get_light_yield(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), GetLightCorrection(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), hit, hits_, IsActive, IsBlackHole, PHG4OuterHcalDetector::IsInOuterHcal(), light_balance_inner_corr, light_balance_inner_radius, light_balance_outer_corr, light_balance_outer_radius, light_scint_model, n_scinti_plates, PHWHERE, PHG4Hit::Reset(), savehitcontainer, savepoststepstatus, saveprestepstatus, saveshower, savetrackid, savevolpost, savevolpre, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_light_yield(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4HitContainer* PHG4OuterHcalSteppingAction::absorberhits_ private
Definition at line 40 of file PHG4OuterHcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4OuterHcalSteppingAction::absorbertruth private
Definition at line 55 of file PHG4OuterHcalSteppingAction.h.
PHG4OuterHcalDetector* PHG4OuterHcalSteppingAction::detector_ private
pointer to the detector
Definition at line 36 of file PHG4OuterHcalSteppingAction.h.
Referenced by PHG4OuterHcalSteppingAction(), SetInterfacePointers(), and UserSteppingAction().
int PHG4OuterHcalSteppingAction::enable_field_checker private
Definition at line 50 of file PHG4OuterHcalSteppingAction.h.
Referenced by EnableFieldChecker(), Init(), and UserSteppingAction().
PHG4Hit* PHG4OuterHcalSteppingAction::hit private
Definition at line 41 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4OuterHcalSteppingAction().
PHG4HitContainer* PHG4OuterHcalSteppingAction::hits_ private
pointer to hit container
Definition at line 39 of file PHG4OuterHcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4OuterHcalSteppingAction::IsActive private
Definition at line 56 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4OuterHcalSteppingAction::IsBlackHole private
Definition at line 57 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
double PHG4OuterHcalSteppingAction::light_balance_inner_corr private
Definition at line 61 of file PHG4OuterHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4OuterHcalSteppingAction::light_balance_inner_radius private
Definition at line 62 of file PHG4OuterHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4OuterHcalSteppingAction::light_balance_outer_corr private
Definition at line 63 of file PHG4OuterHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4OuterHcalSteppingAction::light_balance_outer_radius private
Definition at line 64 of file PHG4OuterHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
int PHG4OuterHcalSteppingAction::light_scint_model private
Definition at line 59 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4OuterHcalSteppingAction::n_scinti_plates private
Definition at line 58 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
const PHParameters* PHG4OuterHcalSteppingAction::params private
Definition at line 42 of file PHG4OuterHcalSteppingAction.h.
PHG4HitContainer* PHG4OuterHcalSteppingAction::savehitcontainer private
Definition at line 43 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4OuterHcalSteppingAction::savepoststepstatus private
Definition at line 49 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4OuterHcalSteppingAction::saveprestepstatus private
Definition at line 48 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4OuterHcalSteppingAction::saveshower private
Definition at line 44 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4OuterHcalSteppingAction::savetrackid private
Definition at line 47 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4OuterHcalSteppingAction::savevolpost private
Definition at line 46 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4OuterHcalSteppingAction::savevolpre private
Definition at line 45 of file PHG4OuterHcalSteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4OuterHcalSteppingAction.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4OuterHcalSteppingAction.cc