E1039 Software: /home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/TriggerRoad.cxx File Reference
TriggerRoad.cxx File Reference
#include <iomanip>
#include <stdlib.h>
#include <algorithm>
#include "TriggerRoad.h"
#include "geom_svc/GeomSvc.h"
Functions
ClassImp (TriggerRoad) TriggerRoad
std::ostream & operator<< (std::ostream &os, const TriggerRoad &road)
Function Documentation
ClassImp()
ClassImp (TriggerRoad)
Definition at line 8 of file TriggerRoad.cxx.
References TriggerRoad::detectorIDs, TriggerRoad::dumpWeight, TriggerRoad::elementIDs, TriggerRoad::enabled, TriggerRoad::highMWeight, TriggerRoad::lowMWeight, TriggerRoad::nMinus, TriggerRoad::nPlus, TriggerRoad::px_max, TriggerRoad::px_mean, TriggerRoad::px_min, TriggerRoad::rndf, and TriggerRoad::targetWeight.
operator<<()
std::ostream& operator<< (std::ostream & os, const TriggerRoad & road)
Definition at line 125 of file TriggerRoad.cxx.
References TriggerRoad::elementIDs, TriggerRoad::getNEntries(), TriggerRoad::getpXWidth(), TriggerRoad::groupID, TriggerRoad::px_max, TriggerRoad::px_mean, TriggerRoad::px_min, TriggerRoad::ratio(), TriggerRoad::rndf, and TriggerRoad::weight().