Class Reference for E1039 Core & Analysis Software: PHG4InputFilter Class Reference
PHG4InputFilter Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4InputFilter.h>
Public Member Functions
PHG4InputFilter (const std::string &name="G4INPUTFILTER")
virtual ~PHG4InputFilter ()
int process_event (PHCompositeNode *topNode)
void set_eta_range (const double min, const double max)
void set_etamin (const double min)
void set_etamax (const double max)
void set_ptmin (const double min)
void set_ptmax (const double max)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
double get_eta (const double x, const double y, const double z)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
double etamin
double etamax
double ptmin
double ptmax
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 10 of file PHG4InputFilter.h.
Constructor & Destructor Documentation
PHG4InputFilter()
PHG4InputFilter::PHG4InputFilter (const std::string & name = "G4INPUTFILTER")
Definition at line 12 of file PHG4InputFilter.cc.
~PHG4InputFilter()
virtual PHG4InputFilter::~PHG4InputFilter () inline virtual
Definition at line 14 of file PHG4InputFilter.h.
Member Function Documentation
get_eta()
double PHG4InputFilter::get_eta (const double x, const double y, const double z) protected
Definition at line 98 of file PHG4InputFilter.cc.
Referenced by process_event().
process_event()
int PHG4InputFilter::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 21 of file PHG4InputFilter.cc.
References PHG4InEvent::DeleteParticle(), etamax, etamin, Fun4AllReturnCodes::EVENT_OK, get_eta(), PHG4InEvent::GetParticles_Modify(), PHG4InEvent::identify(), PHWHERE, ptmax, ptmin, and Fun4AllBase::verbosity.
set_eta_range()
void PHG4InputFilter::set_eta_range (const double min, const double max) inline
Definition at line 18 of file PHG4InputFilter.h.
References etamax, and etamin.
set_etamax()
void PHG4InputFilter::set_etamax (const double max) inline
Definition at line 20 of file PHG4InputFilter.h.
References etamax.
set_etamin()
void PHG4InputFilter::set_etamin (const double min) inline
Definition at line 19 of file PHG4InputFilter.h.
References etamin.
set_ptmax()
void PHG4InputFilter::set_ptmax (const double max) inline
Definition at line 22 of file PHG4InputFilter.h.
References ptmax.
set_ptmin()
void PHG4InputFilter::set_ptmin (const double min) inline
Definition at line 21 of file PHG4InputFilter.h.
References ptmin.
Member Data Documentation
etamax
double PHG4InputFilter::etamax protected
Definition at line 27 of file PHG4InputFilter.h.
Referenced by process_event(), set_eta_range(), and set_etamax().
etamin
double PHG4InputFilter::etamin protected
Definition at line 26 of file PHG4InputFilter.h.
Referenced by process_event(), set_eta_range(), and set_etamin().
ptmax
double PHG4InputFilter::ptmax protected
Definition at line 29 of file PHG4InputFilter.h.
Referenced by process_event(), and set_ptmax().
ptmin
double PHG4InputFilter::ptmin protected
Definition at line 28 of file PHG4InputFilter.h.
Referenced by process_event(), and set_ptmin().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4InputFilter.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4InputFilter.cc