Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/Efficiency/run.C File Reference
run.C File Reference
#include <TSystem.h>
Functions
int run (const int nEvents=1)
Function Documentation
int run (const int nEvents = 1)
Definition at line 10 of file run.C.
References ana(), Fun4AllServer::End(), Fun4AllInputManager::fileopen(), recoConsts::init(), recoConsts::instance(), Fun4AllServer::instance(), GeomSvc::instance(), recoConsts::Print(), Fun4AllServer::PrintTimer(), AnaModule::registerDetector(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), se, PHFlag::set_BoolFlag(), PHFlag::set_DoubleFlag(), AnaModule::set_output_filename(), GeomSvc::UseDbSvc(), and Fun4AllBase::Verbosity().
Referenced by CheckCalibParam(), CheckChanMap(), CheckGeomParam(), Daemon4MainDaq(), draw_real_dst(), DbUpRun::End(), FindExistingRuns(), EventDispUI::FindNewRuns(), Fun4CODA(), Fun4DST(), Fun4MainDaq(), Fun4MainDaqE906(), Fun4MultiRealDst(), GeomSvc::initPlaneDbSvc(), DbUpRun::InitRun(), EventDispUI::OpenRunFile(), OnlMonMainDaq::ProcessEventOnlMon(), OnlMonQie::ProcessEventOnlMon(), DecoStatusDb::RunFinished(), DecoStatusDb::RunStarted(), DecoStatusDb::RunUpdated(), EventHeaderv1::set_RunNumber(), CodaInputManager::SetRunNumber(), and Fun4AllSpillDstOutputManager::Write().