Class Reference for E1039 Core & Analysis Software: SQTrackVector Class Reference
SQTrackVector Class Reference abstract
An SQ interface class to hold a list of SQTrack objects.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQTrackVector.h>
Public Types
typedef std::vector< SQTrack * > Vector
typedef std::vector< SQTrack * >::const_iterator ConstIter
typedef std::vector< SQTrack * >::iterator Iter
Public Member Functions
virtual ~SQTrackVector ()
virtual void identify (std::ostream &os=std::cout) const =0
virtual void Reset ()=0
Clear Event.
virtual int isValid () const =0
isValid returns non zero if object contains vailid data
virtual SQTrackVector * Clone () const =0
virtual ConstIter begin () const =0
virtual ConstIter end () const =0
virtual Iter begin ()=0
virtual Iter end ()=0
virtual bool empty () const =0
virtual size_t size () const =0
virtual void clear ()=0
virtual const SQTrack * at (const size_t id) const =0
virtual SQTrack * at (const size_t id)=0
virtual void push_back (const SQTrack *trk)=0
virtual size_t erase (const size_t id)=0
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Member Functions
SQTrackVector ()
ClassDef (SQTrackVector, 1)
Detailed Description
An SQ interface class to hold a list of SQTrack objects.
Below is the standard way to find this object in "topNode" and loop over each track;
SQTrackVector* trk_vec = findNode::getClass<SQTrackVector>(topNode, "SQTrackVector");
for (SQTrackVector::ConstIter it = trk_vec->begin(); it != trk_vec->end(); it++) {
  SQTrack* trk = *it;
  int trk_id = trk->get_track_id();
}
Definition at line 19 of file SQTrackVector.h.
Member Typedef Documentation
ConstIter
typedef std::vector<SQTrack*>::const_iterator SQTrackVector::ConstIter
Definition at line 22 of file SQTrackVector.h.
Iter
typedef std::vector<SQTrack*>::iterator SQTrackVector::Iter
Definition at line 23 of file SQTrackVector.h.
Vector
typedef std::vector<SQTrack*> SQTrackVector::Vector
Definition at line 21 of file SQTrackVector.h.
Constructor & Destructor Documentation
~SQTrackVector()
virtual SQTrackVector::~SQTrackVector () inline virtual
Definition at line 25 of file SQTrackVector.h.
SQTrackVector()
SQTrackVector::SQTrackVector () inline protected
Definition at line 46 of file SQTrackVector.h.
Member Function Documentation
at() [1/2]
virtual const SQTrack* SQTrackVector::at (const size_t id) const pure virtual
Implemented in SQTrackVector_v1.
Referenced by AnaSimDst::process_event(), MakeMyTree::process_event(), TracePHG4Particle::process_event(), AnaTrack::process_event(), AnaEmbeddedData::process_event(), AnaDimuonLikeSign::process_event(), AnaDimuonV2::process_event(), SimpleTree::process_event(), SQTruthVertexing::process_event(), SQVertexing::process_event(), and TruthNodeMaker::process_event().
at() [2/2]
virtual SQTrack* SQTrackVector::at (const size_t id) pure virtual
Implemented in SQTrackVector_v1.
begin() [1/2]
virtual ConstIter SQTrackVector::begin () const pure virtual
Implemented in SQTrackVector_v1.
Referenced by UtilTrack::FindTrackByID(), and DoEmbedding::process_event().
begin() [2/2]
virtual Iter SQTrackVector::begin () pure virtual
Implemented in SQTrackVector_v1.
ClassDef()
SQTrackVector::ClassDef (SQTrackVector , 1) protected
clear()
virtual void SQTrackVector::clear () pure virtual
Implemented in SQTrackVector_v1.
Referenced by TruthNodeMaker::process_event().
Clone()
virtual SQTrackVector* SQTrackVector::Clone () const pure virtual
Implemented in SQTrackVector_v1.
empty()
virtual bool SQTrackVector::empty () const pure virtual
Implemented in SQTrackVector_v1.
end() [1/2]
virtual ConstIter SQTrackVector::end () const pure virtual
Implemented in SQTrackVector_v1.
Referenced by UtilTrack::FindTrackByID(), and DoEmbedding::process_event().
end() [2/2]
virtual Iter SQTrackVector::end () pure virtual
Implemented in SQTrackVector_v1.
erase()
virtual size_t SQTrackVector::erase (const size_t id) pure virtual
Implemented in SQTrackVector_v1.
identify()
virtual void SQTrackVector::identify (std::ostream & os = std::cout) const pure virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Implemented in SQTrackVector_v1.
isValid()
virtual int SQTrackVector::isValid () const pure virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Implemented in SQTrackVector_v1.
push_back()
virtual void SQTrackVector::push_back (const SQTrack * trk) pure virtual
Implemented in SQTrackVector_v1.
Referenced by SQReco::fillRecTrack(), DoEmbedding::process_event(), and TruthNodeMaker::process_event().
Reset()
virtual void SQTrackVector::Reset () pure virtual
Clear Event.
Reimplemented from PHObject.
Implemented in SQTrackVector_v1.
size()
virtual size_t SQTrackVector::size () const pure virtual
Implemented in SQTrackVector_v1.
Referenced by AnaSimDst::process_event(), MakeMyTree::process_event(), TracePHG4Particle::process_event(), AnaTrack::process_event(), AnaEmbeddedData::process_event(), DoEmbedding::process_event(), SimpleTree::process_event(), SQTruthVertexing::process_event(), SQVertexing::process_event(), and TruthNodeMaker::process_event().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQTrackVector.h