Class Reference for E1039 Core & Analysis Software: SQHitMap_v1 Class Reference
SQHitMap_v1 Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHitMap_v1.h>
Public Member Functions
SQHitMap_v1 ()
SQHitMap_v1 (const SQHitMap_v1 &hitmap)
SQHitMap_v1 & operator= (const SQHitMap_v1 &hitmap)
virtual ~SQHitMap_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
SQHitMap * Clone () const
bool empty () const
size_t size () const
size_t count (unsigned int idkey) const
void clear ()
const SQHit * get (unsigned int idkey) const
SQHit * get (unsigned int idkey)
SQHit * insert (const SQHit *hit)
size_t erase (unsigned int idkey)
ConstIter begin () const
ConstIter find (unsigned int idkey) const
ConstIter end () const
Iter begin ()
Iter find (unsigned int idkey)
Iter end ()
Public Member Functions inherited from SQHitMap
virtual ~SQHitMap ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Additional Inherited Members
Public Types inherited from SQHitMap
typedef std::map< unsigned int, SQHit * > HitMap
typedef std::map< unsigned int, SQHit * >::const_iterator ConstIter
typedef std::map< unsigned int, SQHit * >::iterator Iter
Protected Member Functions inherited from SQHitMap
SQHitMap ()
Detailed Description
Definition at line 18 of file SQHitMap_v1.h.
Constructor & Destructor Documentation
SQHitMap_v1() [1/2]
SQHitMap_v1::SQHitMap_v1 ()
Referenced by Clone().
SQHitMap_v1() [2/2]
SQHitMap_v1::SQHitMap_v1 (const SQHitMap_v1 & hitmap)
Definition at line 22 of file SQHitMap_v1.cxx.
References begin(), SQHit::Clone(), end(), and SQHit::get_hit_id().
~SQHitMap_v1()
SQHitMap_v1::~SQHitMap_v1 () virtual
Definition at line 43 of file SQHitMap_v1.cxx.
References Reset().
Member Function Documentation
begin() [1/2]
Iter SQHitMap_v1::begin () inline virtual
Reimplemented from SQHitMap.
Definition at line 48 of file SQHitMap_v1.h.
begin() [2/2]
ConstIter SQHitMap_v1::begin () const inline virtual
Reimplemented from SQHitMap.
Definition at line 44 of file SQHitMap_v1.h.
Referenced by operator=(), and SQHitMap_v1().
clear()
void SQHitMap_v1::clear () inline virtual
Reimplemented from SQHitMap.
Definition at line 35 of file SQHitMap_v1.h.
References Reset().
Clone()
SQHitMap* SQHitMap_v1::Clone () const inline virtual
Reimplemented from SQHitMap.
Definition at line 30 of file SQHitMap_v1.h.
References SQHitMap_v1().
count()
size_t SQHitMap_v1::count (unsigned int idkey) const inline virtual
Reimplemented from SQHitMap.
Definition at line 34 of file SQHitMap_v1.h.
empty()
bool SQHitMap_v1::empty () const inline virtual
Reimplemented from SQHitMap.
Definition at line 32 of file SQHitMap_v1.h.
end() [1/2]
Iter SQHitMap_v1::end () inline virtual
Reimplemented from SQHitMap.
Definition at line 50 of file SQHitMap_v1.h.
end() [2/2]
ConstIter SQHitMap_v1::end () const inline virtual
Reimplemented from SQHitMap.
Definition at line 46 of file SQHitMap_v1.h.
Referenced by operator=(), and SQHitMap_v1().
erase()
size_t SQHitMap_v1::erase (unsigned int idkey) inline virtual
Reimplemented from SQHitMap.
Definition at line 40 of file SQHitMap_v1.h.
find() [1/2]
Iter SQHitMap_v1::find (unsigned int idkey) inline virtual
Reimplemented from SQHitMap.
Definition at line 49 of file SQHitMap_v1.h.
find() [2/2]
ConstIter SQHitMap_v1::find (unsigned int idkey) const inline virtual
Reimplemented from SQHitMap.
Definition at line 45 of file SQHitMap_v1.h.
get() [1/2]
SQHit * SQHitMap_v1::get (unsigned int idkey) virtual
Reimplemented from SQHitMap.
Definition at line 68 of file SQHitMap_v1.cxx.
References NULL.
get() [2/2]
const SQHit * SQHitMap_v1::get (unsigned int idkey) const virtual
Reimplemented from SQHitMap.
Definition at line 62 of file SQHitMap_v1.cxx.
References NULL.
identify()
void SQHitMap_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SQHitMap.
Definition at line 57 of file SQHitMap_v1.cxx.
insert()
SQHit * SQHitMap_v1::insert (const SQHit * hit) virtual
Reimplemented from SQHitMap.
Definition at line 74 of file SQHitMap_v1.cxx.
References SQHit::Clone(), and SQHit::get_hit_id().
isValid()
int SQHitMap_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from SQHitMap.
Definition at line 29 of file SQHitMap_v1.h.
operator=()
SQHitMap_v1 & SQHitMap_v1::operator= (const SQHitMap_v1 & hitmap)
Definition at line 32 of file SQHitMap_v1.cxx.
References begin(), SQHit::Clone(), end(), SQHit::get_hit_id(), and Reset().
Reset()
void SQHitMap_v1::Reset () virtual
Clear Event.
Reimplemented from SQHitMap.
Definition at line 47 of file SQHitMap_v1.cxx.
Referenced by clear(), operator=(), and ~SQHitMap_v1().
size()
size_t SQHitMap_v1::size (void) const inline virtual
Reimplemented from SQHitMap.
Definition at line 33 of file SQHitMap_v1.h.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHitMap_v1.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/interface_main/SQHitMap_v1.cxx