E1039 Software: /home/yuhw/GitHub/SeaQuest/e1039-core/online/evio/ceMsgLib.c File Reference
ceMsgLib.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ceMsg.h"
Functions
char * ceMsg (int, int, char *, int)
void cePmsg (char *, int)
void cemsg_ (int *num, int *flag, char *out, int maxout)
void cepmsg_ (char *string, int *num, int s_len)
Variables
CE_TBL_ENTRY ceMsgTbl []
static char * lastmsg = (char *)0
Function Documentation
char * ceMsg (int num, int flag, char * out, int maxout)
Definition at line 58 of file ceMsgLib.c.
References CEMSG_ALL, CEMSG_CODE, CEMSG_ERROR, CEMSG_FAC, CEMSG_FATAL, CEMSG_INFO, CEMSG_MSG, CEMSG_NAME, CEMSG_SEV, cemsg_severity, CEMSG_WARN, lastmsg, coda_error_table_entry::msg, coda_error_table_entry::name, NULL, and coda_error_table_entry::num.
Referenced by cemsg_(), and cePmsg().
void cemsg_ (int * num, int * flag, char * out, int maxout)
Definition at line 52 of file ceMsgLib.c.
References ceMsg().
void cePmsg (char * string, int num)
Definition at line 157 of file ceMsgLib.c.
References ceMsg(), CEMSG_ALL, and NULL.
Referenced by cepmsg_(), and main().
void cepmsg_ (char * string, int * num, int s_len)
Definition at line 147 of file ceMsgLib.c.
References cePmsg().
Variable Documentation
CE_TBL_ENTRY ceMsgTbl[]
Definition at line 9 of file ceMsgTbl.c.
char* lastmsg = (char *)0 static
Definition at line 45 of file ceMsgLib.c.
Referenced by ceMsg().