Class Reference for E1039 Core & Analysis Software: SQGeomAcc Class Reference
SQGeomAcc Class Reference
An SubsysReco module to skip a simulated event in which a muon or a muon pair doesn't pass through the geometric acceptance.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4dst/SQGeomAcc.h>
Public Types
enum MuonMode_t {
UNDEF_MUON, SINGLE, SINGLE_T, SINGLE_B,
PAIR, PAIR_TBBT, PAIR_TTBB
}
enum PlaneMode_t { UNDEF_PLANE, HODO, CHAM, HODO_CHAM }
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Public Member Functions
SQGeomAcc (const std::string &name="SQGeomAcc")
virtual ~SQGeomAcc ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetMuonMode (MuonMode_t mode)
void SetPlaneMode (PlaneMode_t mode)
void SetNumOfH1EdgeElementsExcluded (const unsigned int num)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
An SubsysReco module to skip a simulated event in which a muon or a muon pair doesn't pass through the geometric acceptance.
Typical usage:
SQGeomAcc* geom_acc = new SQGeomAcc();
geom_acc->SetMuonMode(SQGeomAcc::PAIR_TBBT);
geom_acc->SetPlaneMode(SQGeomAcc::HODO_CHAM);
geom_acc->SetNumOfH1EdgeElementsExcluded(4); // 0 by default
se->registerSubsystem(geom_acc);
This module must be registered after SQDigitizer since it uses SQHits. All the available modes are listed and explained in the sections of MuonMode_t and PlaneMode_t. Elements at the left and right edges of H1T and H1B can be excluded via SetNumOfH1EdgeElementsExcluded(), where the four elements at each edge are planned to be excluded from the trigger logic.
The chamber acceptance is defined by D0X, D2X, D3pX and D3mX (not Xp, U, Up, V nor Vp). This definition should be simple and sufficient in terms of the "geometric" acceptance. D0U/V and D2U/V are identical to D0X and D2X in the plane size. U/V of D3p/m are larger than X but the X-U-V overlapping region is almost identical to X.
The effect of detection/reconstruction inefficiencies is not considered by this module. It can/should be studied with other modules, like SQChamberRealization and SQReco.
Definition at line 31 of file SQGeomAcc.h.
Member Enumeration Documentation
enum SQGeomAcc::MuonMode_t
Enumerator
UNDEF_MUON
SINGLE
SINGLE_T
SINGLE_B
PAIR
PAIR_TBBT
PAIR_TTBB
Definition at line 33 of file SQGeomAcc.h.
enum SQGeomAcc::PlaneMode_t
Enumerator
UNDEF_PLANE
HODO
CHAM
HODO_CHAM
Definition at line 42 of file SQGeomAcc.h.
Constructor & Destructor Documentation
SQGeomAcc::SQGeomAcc (const std::string & name = "SQGeomAcc")
Definition at line 12 of file SQGeomAcc.cc.
SQGeomAcc::~SQGeomAcc () virtual
Definition at line 22 of file SQGeomAcc.cc.
Member Function Documentation
int SQGeomAcc::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 105 of file SQGeomAcc.cc.
References Fun4AllReturnCodes::EVENT_OK.
int SQGeomAcc::Init (PHCompositeNode *) virtual
Called during initialization, i.e. registered via Fun4AllServer::registerSubsystem(). Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 27 of file SQGeomAcc.cc.
References Fun4AllReturnCodes::EVENT_OK, Fun4AllBase::Name(), UNDEF_MUON, and UNDEF_PLANE.
int SQGeomAcc::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 40 of file SQGeomAcc.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Name().
int SQGeomAcc::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Prepare a set of detector planes used to define the geometric acceptance. Planes are selected by their names for convenience and convert names to IDs for process speed.
Extract and arrange the contents of SQHitVector. What we need here is a list of planes having hits per true track.
Check if each true track has a hit on all required planes and count up such tracks
Reimplemented from SubsysReco.
Definition at line 50 of file SQGeomAcc.cc.
References Fun4AllReturnCodes::ABORTEVENT, SQHitVector::begin(), CHAM, SQHitVector::end(), Fun4AllReturnCodes::EVENT_OK, SQHit::get_detector_id(), SQHit::get_element_id(), SQHit::get_track_id(), HODO, HODO_CHAM, GeomSvc::instance(), PAIR, PAIR_TBBT, PAIR_TTBB, SINGLE, SINGLE_B, and SINGLE_T.
void SQGeomAcc::SetMuonMode (MuonMode_t mode) inline
Definition at line 63 of file SQGeomAcc.h.
References mode.
Referenced by Fun4All(), Fun4AllStep1(), Fun4Sim(), and RecoE1039Sim().
void SQGeomAcc::SetNumOfH1EdgeElementsExcluded (const unsigned int num) inline
Definition at line 65 of file SQGeomAcc.h.
Referenced by Fun4All(), Fun4AllStep1(), Fun4Sim(), and RecoE1039Sim().
void SQGeomAcc::SetPlaneMode (PlaneMode_t mode) inline
Definition at line 64 of file SQGeomAcc.h.
References mode.
Referenced by Fun4All(), Fun4AllStep1(), Fun4Sim(), and RecoE1039Sim().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4dst/SQGeomAcc.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4dst/SQGeomAcc.cc