Class Reference for E1039 Core & Analysis Software: /dev/shm/kenichi/update-github-e1039-doc/e1039-analysis/AnaRealDstSimple/draw_real_dst.cc File Reference
draw_real_dst.cc File Reference
Functions
TTree * GetTree (const int run, const int spill=0)
ROOT macro to look into the E1039 DST file in a simple way.
void PrintTreeElements (TTree *tree)
Sub-function to just print out the list of tree variables.
void draw_real_dst (const int run=318, const int spill=0)
Main function.
Function Documentation
draw_real_dst()
void draw_real_dst (const int run = 318, const int spill = 0)
Main function.
Definition at line 25 of file draw_real_dst.cc.
References GetTree(), and PrintTreeElements().
GetTree()
TTree * GetTree (const int run, const int spill = 0)
ROOT macro to look into the E1039 DST file in a simple way.
Sub-function to open the ROOT file and get the tree.
This macro uses TTree::Draw() to plot the contents of the E1039 DST file, rather than the Fun4All event loop. Anyone can try it for quick checks, but not recommended to use it for serious analyses because it cannot make use of the mapping and calibration info of the e1039-core framework.
It still needs the library file of the e1039-core framework to interpret the SQ data structure. On "seaquestdaq01" and "e1039-monitor", you can just execute the following command before running this macro; source /data2/e1039/this-e1039.sh
The variable name that you can use in TTree::Draw() is given in the e1039-core header files, e.g. /data2/e1039/core/include/interface_main/SQHit.h
Definition at line 60 of file draw_real_dst.cc.
Referenced by draw_real_dst().
PrintTreeElements()
void PrintTreeElements (TTree * tree)
Sub-function to just print out the list of tree variables.
Definition at line 87 of file draw_real_dst.cc.
Referenced by draw_real_dst().