Class Reference for E1039 Core & Analysis Software: PdbParameterMapContainer Class Reference
PdbParameterMapContainer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbParameterMapContainer.h>
Public Types
typedef std::map< int, PdbParameterMap * > parMap
typedef parMap::const_iterator parIter
typedef std::pair< parIter, parIter > parConstRange
Public Member Functions
PdbParameterMapContainer ()
virtual ~PdbParameterMapContainer ()
void print () const
void Reset ()
Clear Event.
void AddPdbParameterMap (const int layer, PdbParameterMap *params)
const PdbParameterMap * GetParameters (const int layer) const
PdbParameterMap * GetParametersToModify (const int layer)
parConstRange get_ParameterMaps () const
int WriteToFile (const std::string &detector_name, const std::string &extension, const std::string &dir=".")
write PdbParameterMapContainer to an external file with root or xml extension.
Public Member Functions inherited from PdbCalChan
PdbCalChan ()
virtual ~PdbCalChan ()
ClassDef (PdbCalChan, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Protected Attributes
std::map< int, PdbParameterMap * > parametermap
Detailed Description
Definition at line 10 of file PdbParameterMapContainer.h.
Member Typedef Documentation
parConstRange
typedef std::pair<parIter, parIter> PdbParameterMapContainer::parConstRange
Definition at line 16 of file PdbParameterMapContainer.h.
parIter
typedef parMap::const_iterator PdbParameterMapContainer::parIter
Definition at line 15 of file PdbParameterMapContainer.h.
parMap
typedef std::map<int, PdbParameterMap *> PdbParameterMapContainer::parMap
Definition at line 14 of file PdbParameterMapContainer.h.
Constructor & Destructor Documentation
PdbParameterMapContainer()
PdbParameterMapContainer::PdbParameterMapContainer () inline
Definition at line 18 of file PdbParameterMapContainer.h.
~PdbParameterMapContainer()
PdbParameterMapContainer::~PdbParameterMapContainer () virtual
Definition at line 21 of file PdbParameterMapContainer.cc.
Member Function Documentation
AddPdbParameterMap()
void PdbParameterMapContainer::AddPdbParameterMap (const int layer, PdbParameterMap * params)
Definition at line 53 of file PdbParameterMapContainer.cc.
References PHWHERE.
Referenced by PHParametersContainer::CopyToPdbParameterMapContainer(), PHG4ParametersContainer::CopyToPdbParameterMapContainer(), PHParameters::SaveToNodeTree(), PHG4Parameters::SaveToNodeTree(), and WriteToFile().
get_ParameterMaps()
parConstRange PdbParameterMapContainer::get_ParameterMaps () const inline
Definition at line 28 of file PdbParameterMapContainer.h.
References parametermap.
Referenced by PHG4ParametersContainer::CreateAndFillFrom(), PHParametersContainer::FillFrom(), and PHG4ParametersContainer::FillFrom().
GetParameters()
const PdbParameterMap * PdbParameterMapContainer::GetParameters (const int layer) const
Definition at line 64 of file PdbParameterMapContainer.cc.
References NULL.
Referenced by PHParameters::FillFrom(), and PHG4Parameters::FillFrom().
GetParametersToModify()
PdbParameterMap * PdbParameterMapContainer::GetParametersToModify (const int layer)
Definition at line 75 of file PdbParameterMapContainer.cc.
References NULL.
Referenced by PHParameters::SaveToNodeTree(), and PHG4Parameters::SaveToNodeTree().
print()
void PdbParameterMapContainer::print () const virtual
Implements PdbCalChan.
Definition at line 32 of file PdbParameterMapContainer.cc.
Referenced by PHG4DetectorGroupSubsystem::InitRun(), and PHG4DetectorSubsystem::InitRun().
Reset()
void PdbParameterMapContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 42 of file PdbParameterMapContainer.cc.
Referenced by PHParametersContainer::SaveToNodeTree(), and PHG4ParametersContainer::SaveToNodeTree().
WriteToFile()
int PdbParameterMapContainer::WriteToFile (const std::string & detector_name, const std::string & extension, const std::string & dir = ".")
write PdbParameterMapContainer to an external file with root or xml extension.
Definition at line 86 of file PdbParameterMapContainer.cc.
References AddPdbParameterMap(), PdbBankID::getInternalValue(), and PHTimeStamp::getTics().
Member Data Documentation
parametermap
std::map<int, PdbParameterMap *> PdbParameterMapContainer::parametermap protected
Definition at line 34 of file PdbParameterMapContainer.h.
Referenced by get_ParameterMaps().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbParameterMapContainer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/database/pdbcal/base/PdbParameterMapContainer.cc