E1039 Software: CalibParamInTimeTaiwan Class Reference
CalibParamInTimeTaiwan Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/CalibParamInTimeTaiwan.h>
Classes
struct ParamItem
Public Member Functions
CalibParamInTimeTaiwan ()
virtual ~CalibParamInTimeTaiwan ()
void Add (const std::string det, const short ele, const double center, const double width)
void Add (const std::string det_name, const short det_id, const short ele, const double center, const double width)
bool Find (const short det, const short ele, double &center, double &width)
void Print (std::ostream &os)
Public Member Functions inherited from CalibParamBase
CalibParamBase (const std::string label, const std::string header)
virtual ~CalibParamBase ()
Public Member Functions inherited from RunParamBase
RunParamBase (const std::string type, const std::string label, const std::string header)
virtual ~RunParamBase ()
void SetBaseDir (const std::string dir_base)
std::string GetBaseDir ()
std::string GetMapID ()
void SetMapID (const std::string map_id)
void SetMapIDbyFile (const std::string map_id)
void SetMapIDbyDB (const std::string map_id)
void SetMapIDbyFile (const int run)
void SetMapIDbyDB (const int run)
void ReadFromFile ()
void WriteToFile ()
void ReadFromLocalFile (const std::string fn_tsv)
void WriteToLocalFile (const std::string fn_tsv)
void ReadFromDB ()
void WriteToDB ()
void WriteRangeToDB ()
Protected Member Functions
int ReadFileCont (LineList &lines)
int WriteFileCont (std::ostream &os)
void ReadDbTable (DbSvc &db)
void WriteDbTable (DbSvc &db)
Protected Member Functions inherited from RunParamBase
std::string RangeFileName ()
std::string MapFileName ()
std::string SchemaName ()
std::string MapTableName ()
Private Types
typedef std::vector< ParamItem > List_t
typedef std::pair< short, short > DetEle_t
typedef std::pair< double, double > CenterWidth_t
typedef std::map< DetEle_t, CenterWidth_t > Map_t
Private Attributes
List_t m_list
Used to keep all information in the added order.
Map_t m_map
Used in Find() for better speed.
Additional Inherited Members
Protected Types inherited from RunParamBase
typedef std::vector< std::string > LineList
Detailed Description
Definition at line 5 of file CalibParamInTimeTaiwan.h.
Member Typedef Documentation
CenterWidth_t
typedef std::pair<double, double> CalibParamInTimeTaiwan::CenterWidth_t private
Definition at line 17 of file CalibParamInTimeTaiwan.h.
DetEle_t
typedef std::pair<short, short> CalibParamInTimeTaiwan::DetEle_t private
Definition at line 16 of file CalibParamInTimeTaiwan.h.
List_t
typedef std::vector<ParamItem> CalibParamInTimeTaiwan::List_t private
Definition at line 13 of file CalibParamInTimeTaiwan.h.
Map_t
typedef std::map<DetEle_t, CenterWidth_t> CalibParamInTimeTaiwan::Map_t private
Definition at line 18 of file CalibParamInTimeTaiwan.h.
Constructor & Destructor Documentation
CalibParamInTimeTaiwan()
CalibParamInTimeTaiwan::CalibParamInTimeTaiwan ()
Definition at line 14 of file CalibParamInTimeTaiwan.cc.
~CalibParamInTimeTaiwan()
virtual CalibParamInTimeTaiwan::~CalibParamInTimeTaiwan () inline virtual
Definition at line 23 of file CalibParamInTimeTaiwan.h.
References Add(), CalibParamInTimeTaiwan::ParamItem::center, CalibParamInTimeTaiwan::ParamItem::det, CalibParamInTimeTaiwan::ParamItem::det_name, CalibParamInTimeTaiwan::ParamItem::ele, Find(), Print(), ReadDbTable(), ReadFileCont(), CalibParamInTimeTaiwan::ParamItem::width, WriteDbTable(), and WriteFileCont().
Member Function Documentation
Add() [1/2]
void CalibParamInTimeTaiwan::Add (const std::string det, const short ele, const double center, const double width)
Definition at line 87 of file CalibParamInTimeTaiwan.cc.
References GeomSvc::getDetectorID(), GeomSvc::instance(), and GeomSvc::toLocalDetectorName().
Referenced by ReadDbTable(), ReadFileCont(), and ~CalibParamInTimeTaiwan().
Add() [2/2]
void CalibParamInTimeTaiwan::Add (const std::string det_name, const short det_id, const short ele, const double center, const double width)
Definition at line 106 of file CalibParamInTimeTaiwan.cc.
References CalibParamInTimeTaiwan::ParamItem::center, CalibParamInTimeTaiwan::ParamItem::det, CalibParamInTimeTaiwan::ParamItem::det_name, CalibParamInTimeTaiwan::ParamItem::ele, m_list, m_map, and CalibParamInTimeTaiwan::ParamItem::width.
Find()
bool CalibParamInTimeTaiwan::Find (const short det, const short ele, double & center, double & width)
Definition at line 120 of file CalibParamInTimeTaiwan.cc.
References m_map.
Referenced by CalibInTime::process_event(), CalibXT::process_event(), and ~CalibParamInTimeTaiwan().
Print()
void CalibParamInTimeTaiwan::Print (std::ostream & os) virtual
Reimplemented from RunParamBase.
Definition at line 133 of file CalibParamInTimeTaiwan.cc.
References m_list.
Referenced by ~CalibParamInTimeTaiwan().
ReadDbTable()
void CalibParamInTimeTaiwan::ReadDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 48 of file CalibParamInTimeTaiwan.cc.
References Add(), RunParamBase::MapTableName(), and DbSvc::Process().
Referenced by ~CalibParamInTimeTaiwan().
ReadFileCont()
int CalibParamInTimeTaiwan::ReadFileCont (LineList & lines) protected virtual
Reimplemented from RunParamBase.
Definition at line 20 of file CalibParamInTimeTaiwan.cc.
References Add().
Referenced by ~CalibParamInTimeTaiwan().
WriteDbTable()
void CalibParamInTimeTaiwan::WriteDbTable (DbSvc & db) protected virtual
Reimplemented from RunParamBase.
Definition at line 64 of file CalibParamInTimeTaiwan.cc.
References DbSvc::Con(), DbSvc::CreateTable(), m_list, and RunParamBase::MapTableName().
Referenced by ~CalibParamInTimeTaiwan().
WriteFileCont()
int CalibParamInTimeTaiwan::WriteFileCont (std::ostream & os) protected virtual
Reimplemented from RunParamBase.
Definition at line 37 of file CalibParamInTimeTaiwan.cc.
References m_list.
Referenced by ~CalibParamInTimeTaiwan().
Member Data Documentation
m_list
List_t CalibParamInTimeTaiwan::m_list private
Used to keep all information in the added order.
Definition at line 14 of file CalibParamInTimeTaiwan.h.
Referenced by Add(), Print(), WriteDbTable(), and WriteFileCont().
m_map
Map_t CalibParamInTimeTaiwan::m_map private
Used in Find() for better speed.
Definition at line 19 of file CalibParamInTimeTaiwan.h.
Referenced by Add(), and Find().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/CalibParamInTimeTaiwan.h
/home/yuhw/GitHub/SeaQuest/e1039-core/online/chan_map/CalibParamInTimeTaiwan.cc