Class Reference for E1039 Core & Analysis Software: Fun4AllSpillSRawEventOutputManager Class Reference
Fun4AllSpillSRawEventOutputManager Class Reference
Fun4AllOutputManager to generate spill-level SRawEvent output files.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/Fun4AllSpillSRawEventOutputManager.h>
Public Member Functions
Fun4AllSpillSRawEventOutputManager (const std::string &dir_base, const std::string &myname="SPILLSRAWEVENTOUT")
virtual ~Fun4AllSpillSRawEventOutputManager ()
void SetTreeName (const std::string name)
void SetBranchName (const std::string name)
void EnableDB (const std::string name_schema="user_e1039_maindaq", const std::string name_table="sraw_file_status", const bool refresh_db=false)
void EnableSQLiteDB (const bool use=true)
virtual int Write (PHCompositeNode *startNode)
write starting from given node
Public Member Functions inherited from Fun4AllOutputManager
virtual ~Fun4AllOutputManager ()
destructor
virtual void Print (const std::string &what="ALL") const
print method (dump event selector)
virtual int AddNode (const std::string &)
add a node in outputmanager
virtual int StripNode (const std::string &)
not write a node in outputmanager
virtual int AddEventSelector (const std::string &recomodule)
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
virtual int outfileopen (const std::string &)
opens output file
virtual int RemoveNode (const std::string &)
removes a node from outputmanager
int WriteGeneric (PHCompositeNode *startNode)
Common method, called before calling virtual Write.
virtual int WriteNode (PHCompositeNode *)
write specified node
virtual std::vector< std::string > * EventSelector ()
retrieves pointer to vector of event selector module names
virtual std::vector< unsigned > * RecoModuleIndex ()
retrieves pointer to vector of event selector module ids
virtual int DoNotWriteEvent (std::vector< int > *retcodes) const
decides if event is to be written or not
virtual size_t EventsWritten () const
get number of Events
virtual std::string OutFileName () const
get output file name
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
void CloseFile ()
void OpenFile ()
void UpdateDBStatus (const int status)
Update the status stored in SQLite DB. Obsolete.
Protected Member Functions inherited from Fun4AllOutputManager
Fun4AllOutputManager (const std::string &myname)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0 , VERBOSITY_SOME = 1 , VERBOSITY_MORE = 2 , VERBOSITY_EVEN_MORE = 3 ,
VERBOSITY_A_LOT = 4 , VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from Fun4AllOutputManager
size_t nEvents
Number of Events.
std::vector< std::string > EventSelectors
vector of event selectors modules
std::vector< unsigned > recomoduleindex
vector of associated module indexes
std::string outfilename
output file name
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Fun4AllOutputManager to generate spill-level SRawEvent output files.
Definition at line 16 of file Fun4AllSpillSRawEventOutputManager.h.
Constructor & Destructor Documentation
Fun4AllSpillSRawEventOutputManager()
Fun4AllSpillSRawEventOutputManager::Fun4AllSpillSRawEventOutputManager (const std::string & dir_base, const std::string & myname = "SPILLSRAWEVENTOUT")
Definition at line 23 of file Fun4AllSpillSRawEventOutputManager.cxx.
~Fun4AllSpillSRawEventOutputManager()
Fun4AllSpillSRawEventOutputManager::~Fun4AllSpillSRawEventOutputManager () virtual
Definition at line 46 of file Fun4AllSpillSRawEventOutputManager.cxx.
References CloseFile().
Member Function Documentation
CloseFile()
void Fun4AllSpillSRawEventOutputManager::CloseFile () protected
Definition at line 102 of file Fun4AllSpillSRawEventOutputManager.cxx.
References DbSvc::Con(), UpdateDBStatus(), and Fun4AllBase::Verbosity().
Referenced by Write(), and ~Fun4AllSpillSRawEventOutputManager().
EnableDB()
void Fun4AllSpillSRawEventOutputManager::EnableDB (const std::string name_schema = "user_e1039_maindaq", const std::string name_table = "sraw_file_status", const bool refresh_db = false)
Definition at line 53 of file Fun4AllSpillSRawEventOutputManager.cxx.
References DbSvc::VarList::Add(), DbSvc::CreateTable(), DbSvc::DB1, DbSvc::DropTable(), DbSvc::HasTable(), and DbSvc::UseSchema().
EnableSQLiteDB()
void Fun4AllSpillSRawEventOutputManager::EnableSQLiteDB (const bool use = true) inline
Definition at line 51 of file Fun4AllSpillSRawEventOutputManager.h.
OpenFile()
void Fun4AllSpillSRawEventOutputManager::OpenFile () protected
Definition at line 124 of file Fun4AllSpillSRawEventOutputManager.cxx.
References DbSvc::Con(), PHWHERE, UpdateDBStatus(), and Fun4AllBase::Verbosity().
Referenced by Write().
SetBranchName()
void Fun4AllSpillSRawEventOutputManager::SetBranchName (const std::string name) inline
Definition at line 49 of file Fun4AllSpillSRawEventOutputManager.h.
SetTreeName()
void Fun4AllSpillSRawEventOutputManager::SetTreeName (const std::string name) inline
Definition at line 48 of file Fun4AllSpillSRawEventOutputManager.h.
UpdateDBStatus()
void Fun4AllSpillSRawEventOutputManager::UpdateDBStatus (const int status) protected
Update the status stored in SQLite DB. Obsolete.
This function assumes the SQLite DB file exists with the proper table contents. We have to manually execute the following commands beforehand;
sqlite3 /path/to/data_status.db
create table data_status (
    run_id          INTEGER,
    spill_id        INTEGER,
     utime_deco     INTEGER DEFAULT 0,
    status_deco     INTEGER DEFAULT 0,
     utime_reco_cpu INTEGER DEFAULT 0,
    status_reco_cpu INTEGER DEFAULT 0,
     utime_reco_gpu INTEGER DEFAULT 0,
    status_reco_gpu INTEGER DEFAULT 0,
    UNIQUE(run_id, spill_id)
  );
Definition at line 175 of file Fun4AllSpillSRawEventOutputManager.cxx.
References DbSvc::Con(), and DbSvc::LITE.
Referenced by CloseFile(), and OpenFile().
Write()
int Fun4AllSpillSRawEventOutputManager::Write (PHCompositeNode *) virtual
write starting from given node
Reimplemented from Fun4AllOutputManager.
Definition at line 73 of file Fun4AllSpillSRawEventOutputManager.cxx.
References CloseFile(), SQSpillMap::get(), SQEvent::get_run_id(), SQEvent::get_spill_id(), OpenFile(), PHWHERE, UtilSRawEvent::SetEvent(), UtilSRawEvent::SetHit(), UtilSRawEvent::SetSpill(), and UtilSRawEvent::SetTriggerHit().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/Fun4AllSpillSRawEventOutputManager.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/ktracker/Fun4AllSpillSRawEventOutputManager.cxx