Class Reference for E1039 Core & Analysis Software: PHG4CylinderDetector Class Reference
PHG4CylinderDetector Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderDetector.h>
Public Member Functions
PHG4CylinderDetector (PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~PHG4CylinderDetector (void)
destructor
void Construct (G4LogicalVolume *world)
construct
bool IsInCylinder (const G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
Public Member Functions inherited from PHG4Detector
PHG4Detector (PHCompositeNode *Node)
constructor
PHG4Detector (PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk=true)
virtual void Print (const std::string &what="ALL") const
Additional Inherited Members
Protected Attributes inherited from PHG4Detector
PHCompositeNode * topNode
int verbosity
std::string name
bool overlapcheck
Detailed Description
Definition at line 12 of file PHG4CylinderDetector.h.
Constructor & Destructor Documentation
PHG4CylinderDetector()
PHG4CylinderDetector::PHG4CylinderDetector (PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 27 of file PHG4CylinderDetector.cc.
~PHG4CylinderDetector()
virtual PHG4CylinderDetector::~PHG4CylinderDetector (void) inline virtual
destructor
Definition at line 19 of file PHG4CylinderDetector.h.
Member Function Documentation
Construct()
void PHG4CylinderDetector::Construct (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 46 of file PHG4CylinderDetector.cc.
References PHParameters::get_double_param(), PHParameters::get_int_param(), PHParameters::get_string_param(), PHG4Detector::GetName(), PHG4Detector::name, PHG4Detector::overlapcheck, PHParameters::Print(), and PHG4Utils::SetColour().
get_Layer()
int PHG4CylinderDetector::get_Layer () const inline
Definition at line 29 of file PHG4CylinderDetector.h.
Referenced by PHG4CylinderSteppingAction::UserSteppingAction().
IsInCylinder()
bool PHG4CylinderDetector::IsInCylinder (const G4VPhysicalVolume * volume) const
Definition at line 36 of file PHG4CylinderDetector.cc.
Referenced by PHG4CylinderSteppingAction::UserSteppingAction().
SuperDetector() [1/2]
const std::string PHG4CylinderDetector::SuperDetector () const inline
Definition at line 28 of file PHG4CylinderDetector.h.
SuperDetector() [2/2]
void PHG4CylinderDetector::SuperDetector (const std::string & name) inline
Definition at line 27 of file PHG4CylinderDetector.h.
References PHG4Detector::name.
Referenced by PHG4CylinderSubsystem::InitRunSubsystem(), PHG4CylinderSteppingAction::SetInterfacePointers(), and PHG4CylinderSteppingAction::UserSteppingAction().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderDetector.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/PHG4CylinderDetector.cc