Class Reference for E1039 Core & Analysis Software: OnlMonCanvas Class Reference
OnlMonCanvas Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonCanvas.h>
Public Types
enum MonStatus_t { OK = 0, WARN = 1, ERROR = 2, UNDEF = 3 }
Public Member Functions
OnlMonCanvas (const std::string name, const std::string title, const int num)
virtual ~OnlMonCanvas ()
void SetBasicID (const int run_id, const int spill_id=0, const int event_id=0, const int spill_id_min=0, const int spill_id_max=0)
void SetBasicCount (const int n_evt=0, const int n_sp=0)
void AddMessage (const char *msg)
MonStatus_t GetStatus ()
void SetStatus (const MonStatus_t stat)
void SetWorseStatus (const MonStatus_t stat)
TPad * GetMainPad ()
void PreDraw (const bool at_end=false)
void PostDraw (const bool at_end=false)
Protected Attributes
std::string m_name
std::string m_title
int m_num
TCanvas m_can
TPad m_pad_title
TPad m_pad_main
TPad m_pad_msg
TPaveText m_pate_msg
MonStatus_t m_mon_status
int m_run
int m_spill
int m_event
int m_spill_min
int m_spill_max
int m_n_evt
int m_n_sp
Detailed Description
Definition at line 11 of file OnlMonCanvas.h.
Member Enumeration Documentation
enum OnlMonCanvas::MonStatus_t
Enumerator
OK
WARN
ERROR
UNDEF
Definition at line 13 of file OnlMonCanvas.h.
Constructor & Destructor Documentation
OnlMonCanvas::OnlMonCanvas (const std::string name, const std::string title, const int num)
Definition at line 16 of file OnlMonCanvas.cc.
OnlMonCanvas::~OnlMonCanvas () virtual
Definition at line 30 of file OnlMonCanvas.cc.
Member Function Documentation
void OnlMonCanvas::AddMessage (const char * msg)
Definition at line 50 of file OnlMonCanvas.cc.
References m_pate_msg.
Referenced by OnlMonReco::DrawMonitor(), OnlMonTrigNim::DrawMonitor(), OnlMonMainDaq::DrawMonitor(), OnlMonH4::DrawMonitor(), and OnlMonHodo::DrawMonitor().
TPad * OnlMonCanvas::GetMainPad ()
Definition at line 74 of file OnlMonCanvas.cc.
References m_pad_main.
Referenced by OnlMonReco::DrawMonitor(), OnlMonTrigNim::DrawMonitor(), OnlMonTrigSig::DrawMonitor(), OnlMonMainDaq::DrawMonitor(), OnlMonCham::DrawMonitor(), OnlMonProp::DrawMonitor(), OnlMonH4::DrawMonitor(), OnlMonHodo::DrawMonitor(), and OnlMonV1495::DrawMonitor().
MonStatus_t OnlMonCanvas::GetStatus () inline
Definition at line 41 of file OnlMonCanvas.h.
References m_mon_status.
void OnlMonCanvas::PostDraw (const bool at_end = false)
Definition at line 117 of file OnlMonCanvas.cc.
References ERROR, UtilOnline::GetOnlMonDir(), m_can, m_mon_status, m_name, m_num, m_pad_msg, m_pate_msg, m_run, OK, and WARN.
void OnlMonCanvas::PreDraw (const bool at_end = false)
Definition at line 80 of file OnlMonCanvas.cc.
References m_can, m_event, m_n_evt, m_n_sp, m_name, m_num, m_pad_main, m_pad_msg, m_pad_title, m_run, m_spill_max, m_spill_min, and m_title.
void OnlMonCanvas::SetBasicCount (const int n_evt = 0, const int n_sp = 0)
Definition at line 44 of file OnlMonCanvas.cc.
References m_n_evt, and m_n_sp.
void OnlMonCanvas::SetBasicID (const int run_id, const int spill_id = 0, const int event_id = 0, const int spill_id_min = 0, const int spill_id_max = 0)
Definition at line 35 of file OnlMonCanvas.cc.
References m_event, m_run, m_spill, m_spill_max, and m_spill_min.
void OnlMonCanvas::SetStatus (const MonStatus_t stat) inline
Definition at line 42 of file OnlMonCanvas.h.
References m_mon_status.
Referenced by OnlMonReco::DrawMonitor(), OnlMonTrigNim::DrawMonitor(), OnlMonMainDaq::DrawMonitor(), OnlMonH4::DrawMonitor(), and OnlMonHodo::DrawMonitor().
void OnlMonCanvas::SetWorseStatus (const MonStatus_t stat)
Definition at line 56 of file OnlMonCanvas.cc.
References ERROR, m_mon_status, OK, UNDEF, and WARN.
Referenced by OnlMonMainDaq::DrawMonitor().
Member Data Documentation
TCanvas OnlMonCanvas::m_can protected
Definition at line 19 of file OnlMonCanvas.h.
Referenced by PostDraw(), and PreDraw().
int OnlMonCanvas::m_event protected
Definition at line 28 of file OnlMonCanvas.h.
Referenced by PreDraw(), and SetBasicID().
MonStatus_t OnlMonCanvas::m_mon_status protected
Definition at line 24 of file OnlMonCanvas.h.
Referenced by GetStatus(), PostDraw(), SetStatus(), and SetWorseStatus().
int OnlMonCanvas::m_n_evt protected
Definition at line 31 of file OnlMonCanvas.h.
Referenced by PreDraw(), and SetBasicCount().
int OnlMonCanvas::m_n_sp protected
Definition at line 32 of file OnlMonCanvas.h.
Referenced by PreDraw(), and SetBasicCount().
std::string OnlMonCanvas::m_name protected
Definition at line 16 of file OnlMonCanvas.h.
Referenced by PostDraw(), and PreDraw().
int OnlMonCanvas::m_num protected
Definition at line 18 of file OnlMonCanvas.h.
Referenced by PostDraw(), and PreDraw().
TPad OnlMonCanvas::m_pad_main protected
Definition at line 21 of file OnlMonCanvas.h.
Referenced by GetMainPad(), and PreDraw().
TPad OnlMonCanvas::m_pad_msg protected
Definition at line 22 of file OnlMonCanvas.h.
Referenced by PostDraw(), and PreDraw().
TPad OnlMonCanvas::m_pad_title protected
Definition at line 20 of file OnlMonCanvas.h.
Referenced by PreDraw().
TPaveText OnlMonCanvas::m_pate_msg protected
Definition at line 23 of file OnlMonCanvas.h.
Referenced by AddMessage(), and PostDraw().
int OnlMonCanvas::m_run protected
Definition at line 26 of file OnlMonCanvas.h.
Referenced by PostDraw(), PreDraw(), and SetBasicID().
int OnlMonCanvas::m_spill protected
Definition at line 27 of file OnlMonCanvas.h.
Referenced by SetBasicID().
int OnlMonCanvas::m_spill_max protected
Definition at line 30 of file OnlMonCanvas.h.
Referenced by PreDraw(), and SetBasicID().
int OnlMonCanvas::m_spill_min protected
Definition at line 29 of file OnlMonCanvas.h.
Referenced by PreDraw(), and SetBasicID().
std::string OnlMonCanvas::m_title protected
Definition at line 17 of file OnlMonCanvas.h.
Referenced by PreDraw().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonCanvas.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonCanvas.cc