SeaQuest Offline Software: PHG4HcalSteppingAction Class Reference
PHG4HcalSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4HcalSteppingAction.h>
Public Member Functions
PHG4HcalSteppingAction (PHG4HcalDetector *)
constructor
virtual ~PHG4HcalSteppingAction ()
destroctor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
void set_zmin (const float z)
void set_zmax (const float z)
float GetLightCorrection (float r)
void SetLightCorrection (float inner_radius, float inner_corr, float outer_radius, float outer_corr)
void SetLightScintModel (const bool b=true)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4HcalDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4Hit * hit
float zmin
float zmax
bool light_scint_model_
bool light_balance_
float light_balance_inner_radius_
float light_balance_inner_corr_
float light_balance_outer_radius_
float light_balance_outer_corr_
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 11 of file PHG4HcalSteppingAction.h.
Constructor & Destructor Documentation
PHG4HcalSteppingAction::PHG4HcalSteppingAction (PHG4HcalDetector * detector)
constructor
Definition at line 22 of file PHG4HcalSteppingAction.cc.
virtual PHG4HcalSteppingAction::~PHG4HcalSteppingAction () inline virtual
destroctor
Definition at line 20 of file PHG4HcalSteppingAction.h.
Member Function Documentation
float PHG4HcalSteppingAction::GetLightCorrection (float r)
Definition at line 285 of file PHG4HcalSteppingAction.cc.
References light_balance_inner_corr_, light_balance_inner_radius_, light_balance_outer_corr_, and light_balance_outer_radius_.
Referenced by UserSteppingAction().
void PHG4HcalSteppingAction::set_zmax (const float z) inline
Definition at line 30 of file PHG4HcalSteppingAction.h.
References zmax.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalSteppingAction::set_zmin (const float z) inline
Definition at line 29 of file PHG4HcalSteppingAction.h.
References zmin.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 252 of file PHG4HcalSteppingAction.cc.
References absorberhits_, detector_, PHG4Detector::GetName(), hits_, PHG4HcalDetector::SuperDetector(), and PHG4SteppingAction::verbosity.
Referenced by PHG4HcalSubsystem::process_event().
void PHG4HcalSteppingAction::SetLightCorrection (float inner_radius, float inner_corr, float outer_radius, float outer_corr) inline
Definition at line 33 of file PHG4HcalSteppingAction.h.
References light_balance_, light_balance_inner_corr_, light_balance_inner_radius_, light_balance_outer_corr_, and light_balance_outer_radius_.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalSteppingAction::SetLightScintModel (const bool b = true) inline
Definition at line 42 of file PHG4HcalSteppingAction.h.
References light_scint_model_.
Referenced by PHG4HcalSubsystem::InitRun().
bool PHG4HcalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 39 of file PHG4HcalSteppingAction.cc.
References absorberhits_, PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4HcalDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4Hit::get_z(), PHG4HitContainer::GetID(), GetLightCorrection(), PHG4Detector::GetName(), PHG4SteppingAction::GetVisibleEnergyDeposition(), hit, hits_, PHG4Hit::identify(), PHG4HcalDetector::INACTIVE, PHG4HcalDetector::IsInCylinderActive(), light_balance_, light_scint_model_, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_light_yield(), PHG4Hit::set_path_length(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), zmax, and zmin.
Member Data Documentation
PHG4HitContainer* PHG4HcalSteppingAction::absorberhits_ private
Definition at line 54 of file PHG4HcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4HcalDetector* PHG4HcalSteppingAction::detector_ private
pointer to the detector
Definition at line 50 of file PHG4HcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4HcalSteppingAction::hit private
Definition at line 55 of file PHG4HcalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4HcalSteppingAction::hits_ private
pointer to hit container
Definition at line 53 of file PHG4HcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
bool PHG4HcalSteppingAction::light_balance_ private
Definition at line 60 of file PHG4HcalSteppingAction.h.
Referenced by SetLightCorrection(), and UserSteppingAction().
float PHG4HcalSteppingAction::light_balance_inner_corr_ private
Definition at line 62 of file PHG4HcalSteppingAction.h.
Referenced by GetLightCorrection(), and SetLightCorrection().
float PHG4HcalSteppingAction::light_balance_inner_radius_ private
Definition at line 61 of file PHG4HcalSteppingAction.h.
Referenced by GetLightCorrection(), and SetLightCorrection().
float PHG4HcalSteppingAction::light_balance_outer_corr_ private
Definition at line 64 of file PHG4HcalSteppingAction.h.
Referenced by GetLightCorrection(), and SetLightCorrection().
float PHG4HcalSteppingAction::light_balance_outer_radius_ private
Definition at line 63 of file PHG4HcalSteppingAction.h.
Referenced by GetLightCorrection(), and SetLightCorrection().
bool PHG4HcalSteppingAction::light_scint_model_ private
Definition at line 59 of file PHG4HcalSteppingAction.h.
Referenced by SetLightScintModel(), and UserSteppingAction().
float PHG4HcalSteppingAction::zmax private
Definition at line 57 of file PHG4HcalSteppingAction.h.
Referenced by set_zmax(), and UserSteppingAction().
float PHG4HcalSteppingAction::zmin private
Definition at line 56 of file PHG4HcalSteppingAction.h.
Referenced by set_zmin(), and UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4HcalSteppingAction.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4HcalSteppingAction.cc