Class Reference for E1039 Core & Analysis Software: EventDispUI Class Reference
EventDispUI Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Display/interface/EventDispUI.h>
Public Member Functions
EventDispUI ()
virtual ~EventDispUI ()
std::string GetDstPath (const int run, const int spill=0)
bool FindNewRuns ()
bool FindSpillDSTs ()
int FetchNumEvents (const int run, const int spill=0)
int OpenRunFile (const int run, const int spill=0)
virtual void NextEvent ()
virtual void PrevEvent ()
void MoveEvent (const int i_evt)
void ReqEvtID ()
void ReqTrig ()
void ViewTop ()
void ViewSide ()
void View3D ()
void UpdateLabels ()
void SetAutoMode (bool value)
void Init (const bool online_mode)
virtual void Run ()
Protected Types
typedef std::vector< int > RunList_t
typedef std::vector< int > SpillList_t
Protected Member Functions
void BuildInterface ()
void UpdateInterface ()
void ExecNewEventCheck ()
int ReadNumber (const std::string msg="Run?")
Static Protected Member Functions
static void * FuncNewEventCheck (void *arg)
Protected Attributes
RunList_t m_list_run
SpillList_t m_list_spill
int m_run
int m_spill
int m_n_evt
int m_i_evt
TGMainFrame * m_fr_main
TGCompositeFrame * m_fr_menu
TGCompositeFrame * m_fr_evt_mode
TGCompositeFrame * m_fr_evt_sel
TGCompositeFrame * m_fr_evt_next
TGCompositeFrame * m_fr_evt_prev
TGLabel * m_lbl_mode
TGLabel * m_lbl_run
TGLabel * m_lbl_n_evt
TGNumberEntry * m_ne_evt_id
TGNumberEntry * m_ne_trig
bool m_online_mode
bool m_auto_mode
pthread_t m_tid1
Static Protected Attributes
static const int RUN_MIN = 1000
static const int RUN_MAX = 40000
Detailed Description
Definition at line 12 of file EventDispUI.h.
Member Typedef Documentation
RunList_t
typedef std::vector<int> EventDispUI::RunList_t protected
Definition at line 16 of file EventDispUI.h.
SpillList_t
typedef std::vector<int> EventDispUI::SpillList_t protected
Definition at line 17 of file EventDispUI.h.
Constructor & Destructor Documentation
EventDispUI()
EventDispUI::EventDispUI ()
Definition at line 22 of file EventDispUI.cxx.
~EventDispUI()
virtual EventDispUI::~EventDispUI () inline virtual
Definition at line 45 of file EventDispUI.h.
Member Function Documentation
BuildInterface()
void EventDispUI::BuildInterface () protected
Definition at line 298 of file EventDispUI.cxx.
References m_auto_mode, m_fr_evt_mode, m_fr_evt_next, m_fr_evt_prev, m_fr_evt_sel, m_fr_main, m_fr_menu, m_lbl_mode, m_lbl_n_evt, m_lbl_run, m_ne_evt_id, m_ne_trig, and UpdateInterface().
Referenced by Run(), and EventDispOfflineUI::Run().
ExecNewEventCheck()
void EventDispUI::ExecNewEventCheck () protected
Definition at line 453 of file EventDispUI.cxx.
References FetchNumEvents(), FindNewRuns(), m_auto_mode, m_i_evt, m_list_run, m_run, MoveEvent(), and OpenRunFile().
Referenced by FuncNewEventCheck().
FetchNumEvents()
int EventDispUI::FetchNumEvents (const int run, const int spill = 0)
Definition at line 86 of file EventDispUI.cxx.
References GetDstPath().
Referenced by ExecNewEventCheck(), and OpenRunFile().
FindNewRuns()
bool EventDispUI::FindNewRuns ()
Definition at line 53 of file EventDispUI.cxx.
References GetDstPath(), m_list_run, RUN_MAX, and RUN_MIN.
Referenced by ExecNewEventCheck(), and Init().
FindSpillDSTs()
bool EventDispUI::FindSpillDSTs ()
Definition at line 66 of file EventDispUI.cxx.
References UtilOnline::GetSpillDstDir(), m_list_spill, and m_run.
Referenced by Init().
FuncNewEventCheck()
void * EventDispUI::FuncNewEventCheck (void * arg) static protected
Definition at line 447 of file EventDispUI.cxx.
References ExecNewEventCheck().
Referenced by Run().
GetDstPath()
std::string EventDispUI::GetDstPath (const int run, const int spill = 0)
Definition at line 44 of file EventDispUI.cxx.
References UtilOnline::GetEDDstFilePath(), UtilOnline::GetSpillDstDir(), UtilOnline::GetSpillDstFile(), and m_online_mode.
Referenced by FetchNumEvents(), FindNewRuns(), and OpenRunFile().
Init()
void EventDispUI::Init (const bool online_mode)
Do all needed before showing GUI.
Definition at line 236 of file EventDispUI.cxx.
References FindNewRuns(), FindSpillDSTs(), m_list_run, m_list_spill, m_online_mode, m_run, m_spill, and ReadNumber().
MoveEvent()
void EventDispUI::MoveEvent (const int i_evt)
Definition at line 156 of file EventDispUI.cxx.
References Fun4AllServer::instance(), m_i_evt, m_n_evt, m_run, m_spill, OpenRunFile(), Fun4AllServer::run(), Fun4AllServer::skip(), and UpdateLabels().
Referenced by ExecNewEventCheck(), Run(), and EventDispOfflineUI::Run().
NextEvent()
void EventDispUI::NextEvent () virtual
Definition at line 112 of file EventDispUI.cxx.
References Fun4AllServer::instance(), m_auto_mode, m_i_evt, m_n_evt, m_online_mode, Fun4AllServer::run(), and UpdateLabels().
OpenRunFile()
int EventDispUI::OpenRunFile (const int run, const int spill = 0)
Definition at line 98 of file EventDispUI.cxx.
References FetchNumEvents(), Fun4AllInputManager::fileopen(), GetDstPath(), Fun4AllServer::getInputManager(), Fun4AllServer::instance(), m_i_evt, m_n_evt, m_run, m_spill, and UpdateLabels().
Referenced by ExecNewEventCheck(), MoveEvent(), PrevEvent(), and Run().
PrevEvent()
void EventDispUI::PrevEvent () virtual
Reimplemented in EventDispOfflineUI.
Definition at line 131 of file EventDispUI.cxx.
References Fun4AllServer::instance(), m_auto_mode, m_i_evt, m_n_evt, m_online_mode, m_run, m_spill, OpenRunFile(), Fun4AllServer::run(), Fun4AllServer::skip(), and UpdateLabels().
ReadNumber()
int EventDispUI::ReadNumber (const std::string msg = "Run?") protected
Definition at line 269 of file EventDispUI.cxx.
Referenced by Init().
ReqEvtID()
void EventDispUI::ReqEvtID ()
Definition at line 175 of file EventDispUI.cxx.
References Fun4AllServer::getSubsysReco(), Fun4AllServer::instance(), m_ne_evt_id, and EvtFilter::set_event_id_req().
ReqTrig()
void EventDispUI::ReqTrig ()
Definition at line 183 of file EventDispUI.cxx.
References Fun4AllServer::getSubsysReco(), Fun4AllServer::instance(), m_ne_trig, and EvtFilter::set_trigger_req().
Run()
void EventDispUI::Run () virtual
Definition at line 288 of file EventDispUI.cxx.
References BuildInterface(), FuncNewEventCheck(), m_online_mode, m_run, m_spill, m_tid1, MoveEvent(), NULL, and OpenRunFile().
SetAutoMode()
void EventDispUI::SetAutoMode (bool value)
Definition at line 227 of file EventDispUI.cxx.
References m_auto_mode, and UpdateInterface().
UpdateInterface()
void EventDispUI::UpdateInterface () protected
Definition at line 425 of file EventDispUI.cxx.
References m_auto_mode, m_fr_evt_mode, m_fr_evt_next, m_fr_evt_prev, m_fr_evt_sel, m_fr_menu, and m_online_mode.
Referenced by BuildInterface(), and SetAutoMode().
UpdateLabels()
void EventDispUI::UpdateLabels ()
Definition at line 212 of file EventDispUI.cxx.
References m_i_evt, m_lbl_mode, m_lbl_n_evt, m_lbl_run, m_n_evt, m_online_mode, and m_run.
Referenced by MoveEvent(), NextEvent(), OpenRunFile(), EventDispOfflineUI::PrevEvent(), PrevEvent(), and EventDispOfflineUI::Run().
View3D()
void EventDispUI::View3D ()
Definition at line 205 of file EventDispUI.cxx.
References Fun4AllServer::getSubsysReco(), Fun4AllServer::instance(), and PHEventDisplay::set_view_3d().
ViewSide()
void EventDispUI::ViewSide ()
Definition at line 198 of file EventDispUI.cxx.
References Fun4AllServer::getSubsysReco(), Fun4AllServer::instance(), and PHEventDisplay::set_view_side().
ViewTop()
void EventDispUI::ViewTop ()
Definition at line 191 of file EventDispUI.cxx.
References Fun4AllServer::getSubsysReco(), Fun4AllServer::instance(), and PHEventDisplay::set_view_top().
Member Data Documentation
m_auto_mode
bool EventDispUI::m_auto_mode protected
Definition at line 40 of file EventDispUI.h.
Referenced by BuildInterface(), EventDispOfflineUI::EventDispOfflineUI(), ExecNewEventCheck(), NextEvent(), PrevEvent(), SetAutoMode(), and UpdateInterface().
m_fr_evt_mode
TGCompositeFrame* EventDispUI::m_fr_evt_mode protected
Definition at line 28 of file EventDispUI.h.
Referenced by BuildInterface(), and UpdateInterface().
m_fr_evt_next
TGCompositeFrame* EventDispUI::m_fr_evt_next protected
Definition at line 30 of file EventDispUI.h.
Referenced by BuildInterface(), and UpdateInterface().
m_fr_evt_prev
TGCompositeFrame* EventDispUI::m_fr_evt_prev protected
Definition at line 31 of file EventDispUI.h.
Referenced by BuildInterface(), and UpdateInterface().
m_fr_evt_sel
TGCompositeFrame* EventDispUI::m_fr_evt_sel protected
Definition at line 29 of file EventDispUI.h.
Referenced by BuildInterface(), and UpdateInterface().
m_fr_main
TGMainFrame* EventDispUI::m_fr_main protected
Definition at line 26 of file EventDispUI.h.
Referenced by BuildInterface().
m_fr_menu
TGCompositeFrame* EventDispUI::m_fr_menu protected
Definition at line 27 of file EventDispUI.h.
Referenced by BuildInterface(), and UpdateInterface().
m_i_evt
int EventDispUI::m_i_evt protected
Definition at line 24 of file EventDispUI.h.
Referenced by ExecNewEventCheck(), MoveEvent(), NextEvent(), OpenRunFile(), EventDispOfflineUI::PrevEvent(), PrevEvent(), EventDispOfflineUI::Run(), and UpdateLabels().
m_lbl_mode
TGLabel* EventDispUI::m_lbl_mode protected
Definition at line 33 of file EventDispUI.h.
Referenced by BuildInterface(), and UpdateLabels().
m_lbl_n_evt
TGLabel* EventDispUI::m_lbl_n_evt protected
Definition at line 35 of file EventDispUI.h.
Referenced by BuildInterface(), and UpdateLabels().
m_lbl_run
TGLabel* EventDispUI::m_lbl_run protected
Definition at line 34 of file EventDispUI.h.
Referenced by BuildInterface(), and UpdateLabels().
m_list_run
RunList_t EventDispUI::m_list_run protected
Definition at line 18 of file EventDispUI.h.
Referenced by ExecNewEventCheck(), FindNewRuns(), and Init().
m_list_spill
SpillList_t EventDispUI::m_list_spill protected
Definition at line 19 of file EventDispUI.h.
Referenced by FindSpillDSTs(), and Init().
m_n_evt
int EventDispUI::m_n_evt protected
Definition at line 23 of file EventDispUI.h.
Referenced by MoveEvent(), NextEvent(), OpenRunFile(), EventDispOfflineUI::PrevEvent(), PrevEvent(), EventDispOfflineUI::Run(), and UpdateLabels().
m_ne_evt_id
TGNumberEntry* EventDispUI::m_ne_evt_id protected
Definition at line 36 of file EventDispUI.h.
Referenced by BuildInterface(), and ReqEvtID().
m_ne_trig
TGNumberEntry* EventDispUI::m_ne_trig protected
Definition at line 37 of file EventDispUI.h.
Referenced by BuildInterface(), and ReqTrig().
m_online_mode
bool EventDispUI::m_online_mode protected
Definition at line 39 of file EventDispUI.h.
Referenced by EventDispOfflineUI::EventDispOfflineUI(), GetDstPath(), Init(), NextEvent(), PrevEvent(), Run(), UpdateInterface(), and UpdateLabels().
m_run
int EventDispUI::m_run protected
Definition at line 21 of file EventDispUI.h.
Referenced by ExecNewEventCheck(), FindSpillDSTs(), Init(), MoveEvent(), OpenRunFile(), PrevEvent(), Run(), EventDispOfflineUI::Run(), and UpdateLabels().
m_spill
int EventDispUI::m_spill protected
Definition at line 22 of file EventDispUI.h.
Referenced by Init(), MoveEvent(), OpenRunFile(), PrevEvent(), and Run().
m_tid1
pthread_t EventDispUI::m_tid1 protected
Definition at line 41 of file EventDispUI.h.
Referenced by Run().
RUN_MAX
const int EventDispUI::RUN_MAX = 40000 static protected
Definition at line 15 of file EventDispUI.h.
Referenced by FindNewRuns().
RUN_MIN
const int EventDispUI::RUN_MIN = 1000 static protected
Definition at line 14 of file EventDispUI.h.
Referenced by FindNewRuns().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Display/interface/EventDispUI.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/Display/interface/EventDispUI.cxx