E1039 Software: PHGenFit::Track Class Reference
PHGenFit::Track Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHGenFitPkg/PHGenFit/Track.h>
Public Member Functions
Track (genfit::AbsTrackRep *rep, TVector3 seed_pos, TVector3 seed_mom, TMatrixDSym seed_cov, const int v=0)
Default ctor.
Track (const PHGenFit::Track &t)
Copy constructor.
virtual ~Track ()
Default dtor.
int addMeasurement (PHGenFit::Measurement *measurement)
Add measurement.
int addMeasurements (std::vector< PHGenFit::Measurement *> &measurements)
int deleteLastMeasurement ()
int updateOneMeasurementKalman (const std::vector< PHGenFit::Measurement *> &measurements, std::map< double, std::shared_ptr< PHGenFit::Track > > &incr_chi2s_new_tracks, const int base_tp_idx=-1, const int direction=1, const float blowup_factor=1., const bool use_fitted_state=false) const
double extrapolateToPlane (genfit::MeasuredStateOnPlane &state, TVector3 O, TVector3 n, const int tr_point_id=0) const
double extrapolateToLine (genfit::MeasuredStateOnPlane &state, TVector3 line_point, TVector3 line_direction, const int tr_point_id=0) const
double extrapolateToCylinder (genfit::MeasuredStateOnPlane &state, double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id=0, const int direction=1) const
double extrapolateToPoint (genfit::MeasuredStateOnPlane &state, TVector3 P, const int tr_point_id=0) const
genfit::MeasuredStateOnPlane * extrapolateToPlane (TVector3 O, TVector3 n, const int tr_point_id=0) const
genfit::MeasuredStateOnPlane * extrapolateToLine (TVector3 line_point, TVector3 line_direction, const int tr_point_id=0) const
genfit::MeasuredStateOnPlane * extrapolateToCylinder (double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id=0, const int direction=1) const
genfit::MeasuredStateOnPlane * extrapolateToPoint (TVector3 P, const int tr_point_id=0) const
genfit::Track * getGenFitTrack ()
genfit::Track * getGenFitTrack () const
double get_chi2 () const
double get_ndf () const
double get_charge () const
TVector3 get_mom () const
const std::vector< unsigned int > & get_cluster_IDs () const
void set_cluster_IDs (const std::vector< unsigned int > &clusterIDs)
int get_verbosity () const
void set_verbosity (int verbosity)
Private Attributes
int verbosity
genfit::Track * _track
std::vector< unsigned int > _clusterIDs
Detailed Description
Definition at line 35 of file Track.h.
Constructor & Destructor Documentation
Track() [1/2]
PHGenFit::Track::Track (genfit::AbsTrackRep * rep, TVector3 seed_pos, TVector3 seed_mom, TMatrixDSym seed_cov, const int v = 0)
Default ctor.
Definition at line 43 of file Track.cc.
References _track, and verbosity.
Track() [2/2]
PHGenFit::Track::Track (const PHGenFit::Track & t)
Copy constructor.
Definition at line 62 of file Track.cc.
References _clusterIDs, _track, get_cluster_IDs(), getGenFitTrack(), and verbosity.
~Track()
PHGenFit::Track::~Track () virtual
Default dtor.
Definition at line 110 of file Track.cc.
References _clusterIDs, and _track.
Member Function Documentation
addMeasurement()
int PHGenFit::Track::addMeasurement (PHGenFit::Measurement * measurement)
Add measurement.
Definition at line 68 of file Track.cc.
References _clusterIDs, _track, PHGenFit::Measurement::get_cluster_ID(), and PHGenFit::Measurement::getMeasurement().
addMeasurements()
int PHGenFit::Track::addMeasurements (std::vector< PHGenFit::Measurement *> & measurements)
Definition at line 81 of file Track.cc.
References _clusterIDs, and _track.
Referenced by main().
deleteLastMeasurement()
int PHGenFit::Track::deleteLastMeasurement ()
Definition at line 101 of file Track.cc.
References _clusterIDs, and _track.
extrapolateToCylinder() [1/2]
double PHGenFit::Track::extrapolateToCylinder (genfit::MeasuredStateOnPlane & state, double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0, const int direction = 1) const
Definition at line 210 of file Track.cc.
References _track, LogError, LogWarning, NULL, verbosity, and WILD_DOUBLE.
Referenced by extrapolateToCylinder(), and main().
extrapolateToCylinder() [2/2]
genfit::MeasuredStateOnPlane * PHGenFit::Track::extrapolateToCylinder (double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0, const int direction = 1) const
Definition at line 299 of file Track.cc.
References extrapolateToCylinder(), NULL, and WILD_DOUBLE.
extrapolateToLine() [1/2]
double PHGenFit::Track::extrapolateToLine (genfit::MeasuredStateOnPlane & state, TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0) const
Definition at line 168 of file Track.cc.
References _track, NULL, and WILD_DOUBLE.
Referenced by extrapolateToLine(), and main().
extrapolateToLine() [2/2]
genfit::MeasuredStateOnPlane * PHGenFit::Track::extrapolateToLine (TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0) const
Definition at line 198 of file Track.cc.
References extrapolateToLine(), NULL, and WILD_DOUBLE.
extrapolateToPlane() [1/2]
double PHGenFit::Track::extrapolateToPlane (genfit::MeasuredStateOnPlane & state, TVector3 O, TVector3 n, const int tr_point_id = 0) const
track_point 0 is the first one, and -1 is the last one
Definition at line 124 of file Track.cc.
References _track, NULL, and WILD_DOUBLE.
Referenced by extrapolateToPlane().
extrapolateToPlane() [2/2]
genfit::MeasuredStateOnPlane * PHGenFit::Track::extrapolateToPlane (TVector3 O, TVector3 n, const int tr_point_id = 0) const
Definition at line 156 of file Track.cc.
References extrapolateToPlane(), NULL, and WILD_DOUBLE.
extrapolateToPoint() [1/2]
double PHGenFit::Track::extrapolateToPoint (genfit::MeasuredStateOnPlane & state, TVector3 P, const int tr_point_id = 0) const
Definition at line 643 of file Track.cc.
References _track, NULL, and WILD_DOUBLE.
Referenced by extrapolateToPoint().
extrapolateToPoint() [2/2]
genfit::MeasuredStateOnPlane * PHGenFit::Track::extrapolateToPoint (TVector3 P, const int tr_point_id = 0) const
Definition at line 672 of file Track.cc.
References extrapolateToPoint(), NULL, and WILD_DOUBLE.
get_charge()
double PHGenFit::Track::get_charge () const
Definition at line 708 of file Track.cc.
References _track, and verbosity.
get_chi2()
double PHGenFit::Track::get_chi2 () const
Definition at line 684 of file Track.cc.
References _track.
get_cluster_IDs()
const std::vector<unsigned int>& PHGenFit::Track::get_cluster_IDs () const inline
Definition at line 95 of file Track.h.
Referenced by Track().
get_mom()
TVector3 PHGenFit::Track::get_mom () const
Definition at line 744 of file Track.cc.
References _track.
get_ndf()
double PHGenFit::Track::get_ndf () const
Definition at line 696 of file Track.cc.
References _track.
get_verbosity()
int PHGenFit::Track::get_verbosity () const inline
Definition at line 103 of file Track.h.
getGenFitTrack() [1/2]
genfit::Track* PHGenFit::Track::getGenFitTrack () inline
Definition at line 83 of file Track.h.
Referenced by PHGenFit::Fitter::processTrack(), and Track().
getGenFitTrack() [2/2]
genfit::Track* PHGenFit::Track::getGenFitTrack () const inline
Definition at line 85 of file Track.h.
set_cluster_IDs()
void PHGenFit::Track::set_cluster_IDs (const std::vector< unsigned int > & clusterIDs) inline
Definition at line 99 of file Track.h.
set_verbosity()
void PHGenFit::Track::set_verbosity (int verbosity) inline
Definition at line 107 of file Track.h.
updateOneMeasurementKalman()
int PHGenFit::Track::updateOneMeasurementKalman (const std::vector< PHGenFit::Measurement *> & measurements, std::map< double, std::shared_ptr< PHGenFit::Track > > & incr_chi2s_new_tracks, const int base_tp_idx = -1, const int direction = 1, const float blowup_factor = 1., const bool use_fitted_state = false) const
A new TrackPoint created in addMeasurement PHGenFit: clusterID also registerd
Get the pointer of the TrackPoint just created
Definition at line 312 of file Track.cc.
References LogDebug, LogWarning, NULL, and verbosity.
Member Data Documentation
_clusterIDs
std::vector<unsigned int> PHGenFit::Track::_clusterIDs private
Definition at line 119 of file Track.h.
Referenced by addMeasurement(), addMeasurements(), deleteLastMeasurement(), Track(), and ~Track().
_track
genfit::Track* PHGenFit::Track::_track private
Definition at line 117 of file Track.h.
Referenced by addMeasurement(), addMeasurements(), deleteLastMeasurement(), extrapolateToCylinder(), extrapolateToLine(), extrapolateToPlane(), extrapolateToPoint(), get_charge(), get_chi2(), get_mom(), get_ndf(), Track(), and ~Track().
verbosity
int PHGenFit::Track::verbosity private
Definition at line 115 of file Track.h.
Referenced by extrapolateToCylinder(), get_charge(), Track(), and updateOneMeasurementKalman().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHGenFitPkg/PHGenFit/Track.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/PHGenFitPkg/PHGenFit/Track.cc