SeaQuest Offline Software: PHG4ForwardCalCellReco Class Reference
PHG4ForwardCalCellReco Class Reference
#include </home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4ForwardCalCellReco.h>
Public Member Functions
PHG4ForwardCalCellReco (const std::string &name="FWDCALCELLRECO")
virtual ~PHG4ForwardCalCellReco ()
int InitRun (PHCompositeNode *topNode)
module initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
end of process
void Detector (const std::string &d)
void checkenergy (const int i=1)
double get_timing_window_min (const int i)
double get_timing_window_max (const int i)
void set_timing_window (const int i, const double tmin, const double tmax)
void set_timing_window_defaults (const double tmin, const double tmax)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int CheckEnergy (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::string detector
std::string hitnodename
std::string cellnodename
PHTimeServer::timer _timer
int nbins [2]
int chkenergyconservation
std::map< unsigned int,
PHG4CylinderCell * > celllist
double tmin_default
timing window size in ns. This is for a simple simulation of the ADC integration window starting from 0ns to this value. Default to infinity, i.e. include all hits
double tmax_default
std::map< int, std::pair
< double, double > > tmin_max
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 13 of file PHG4ForwardCalCellReco.h.
Constructor & Destructor Documentation
PHG4ForwardCalCellReco::PHG4ForwardCalCellReco (const std::string & name = "FWDCALCELLRECO")
Definition at line 23 of file PHG4ForwardCalCellReco.cc.
References nbins.
virtual PHG4ForwardCalCellReco::~PHG4ForwardCalCellReco () inline virtual
Definition at line 19 of file PHG4ForwardCalCellReco.h.
Member Function Documentation
void PHG4ForwardCalCellReco::checkenergy (const int i = 1) inline
Definition at line 31 of file PHG4ForwardCalCellReco.h.
References chkenergyconservation.
int PHG4ForwardCalCellReco::CheckEnergy (PHCompositeNode * topNode) protected
Definition at line 155 of file PHG4ForwardCalCellReco.cc.
References cellnodename, PHG4HitContainer::getHits(), hitnodename, Fun4AllBase::Name(), and Fun4AllBase::verbosity.
Referenced by process_event().
void PHG4ForwardCalCellReco::Detector (const std::string & d) inline
Definition at line 30 of file PHG4ForwardCalCellReco.h.
References detector.
int PHG4ForwardCalCellReco::End (PHCompositeNode * topNode) virtual
end of process
Reimplemented from SubsysReco.
Definition at line 148 of file PHG4ForwardCalCellReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
double PHG4ForwardCalCellReco::get_timing_window_max (const int i) inline
Definition at line 34 of file PHG4ForwardCalCellReco.h.
References tmax_default.
double PHG4ForwardCalCellReco::get_timing_window_min (const int i) inline
Definition at line 33 of file PHG4ForwardCalCellReco.h.
References tmin_default.
int PHG4ForwardCalCellReco::InitRun (PHCompositeNode * topNode) virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 34 of file PHG4ForwardCalCellReco.cc.
References PHCompositeNode::addNode(), cellnodename, detector, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), hitnodename, and PHWHERE.
int PHG4ForwardCalCellReco::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 76 of file PHG4ForwardCalCellReco.cc.
References _timer, PHG4CylinderCellContainer::AddCylinderCellSpecifyKey(), celllist, cellnodename, CheckEnergy(), chkenergyconservation, Fun4AllReturnCodes::EVENT_OK, PHTimeServer::timer::get(), PHG4HitContainer::getHits(), PHG4HitContainer::getLayers(), hitnodename, Fun4AllBase::Name(), PHTimer::restart(), PHTimer::stop(), tmax_default, tmin_default, and Fun4AllBase::verbosity.
void PHG4ForwardCalCellReco::set_timing_window (const int i, const double tmin, const double tmax) inline
Definition at line 35 of file PHG4ForwardCalCellReco.h.
References convertRT::tmax, tmax_default, convertRT::tmin, and tmin_default.
void PHG4ForwardCalCellReco::set_timing_window_defaults (const double tmin, const double tmax) inline
Definition at line 38 of file PHG4ForwardCalCellReco.h.
References convertRT::tmax, tmax_default, convertRT::tmin, and tmin_default.
Member Data Documentation
PHTimeServer::timer PHG4ForwardCalCellReco::_timer protected
Definition at line 47 of file PHG4ForwardCalCellReco.h.
Referenced by process_event().
std::map<unsigned int, PHG4CylinderCell *> PHG4ForwardCalCellReco::celllist protected
Definition at line 50 of file PHG4ForwardCalCellReco.h.
Referenced by process_event().
std::string PHG4ForwardCalCellReco::cellnodename protected
Definition at line 46 of file PHG4ForwardCalCellReco.h.
Referenced by CheckEnergy(), InitRun(), and process_event().
int PHG4ForwardCalCellReco::chkenergyconservation protected
Definition at line 49 of file PHG4ForwardCalCellReco.h.
Referenced by checkenergy(), and process_event().
std::string PHG4ForwardCalCellReco::detector protected
Definition at line 44 of file PHG4ForwardCalCellReco.h.
Referenced by Detector(), and InitRun().
std::string PHG4ForwardCalCellReco::hitnodename protected
Definition at line 45 of file PHG4ForwardCalCellReco.h.
Referenced by CheckEnergy(), InitRun(), and process_event().
int PHG4ForwardCalCellReco::nbins[2] protected
Definition at line 48 of file PHG4ForwardCalCellReco.h.
Referenced by PHG4ForwardCalCellReco().
double PHG4ForwardCalCellReco::tmax_default protected
Definition at line 54 of file PHG4ForwardCalCellReco.h.
Referenced by get_timing_window_max(), process_event(), set_timing_window(), and set_timing_window_defaults().
double PHG4ForwardCalCellReco::tmin_default protected
timing window size in ns. This is for a simple simulation of the ADC integration window starting from 0ns to this value. Default to infinity, i.e. include all hits
Definition at line 53 of file PHG4ForwardCalCellReco.h.
Referenced by get_timing_window_min(), process_event(), set_timing_window(), and set_timing_window_defaults().
std::map<int, std::pair<double,double> > PHG4ForwardCalCellReco::tmin_max protected
Definition at line 55 of file PHG4ForwardCalCellReco.h.
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4ForwardCalCellReco.h
/home/yuhw/GitHub/SeaQuest/seaquest-offline/simulation/g4detectors/PHG4ForwardCalCellReco.cc