Class Reference for E1039 Core & Analysis Software: PropSegment Class Reference
PropSegment Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/FastTracklet.h>
Public Member Functions
PropSegment ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PropSegment * Clone () const
void init ()
void print (std::ostream &os=std::cout) const
double getExpPosition (double z) const
double getClosestApproach (double z, double pos)
double getPosRef (double default_val=-9999.)
int getNHits () const
int getNPlanes () const
void fit ()
void fit_2hits ()
void fit_34hits ()
void linearFit_simple ()
void linearFit_iterative ()
void resolveLR ()
void resolveLR (int setting)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const
Virtual copy constructor.
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
void SplitLevel (const int i)
int SplitLevel () const
void BufferSize (const int i)
int BufferSize () const
Public Attributes
double a
double b
double err_a
double err_b
double chisq
int nHodoHits
Hit hodoHits [4]
SignedHit hits [4]
Detailed Description
Definition at line 54 of file FastTracklet.h.
Constructor & Destructor Documentation
PropSegment()
PropSegment::PropSegment ()
Definition at line 129 of file FastTracklet.cxx.
References hits, hodoHits, and Hit::index.
Referenced by Clone().
Member Function Documentation
Clone()
PropSegment* PropSegment::Clone () const inline
Definition at line 63 of file FastTracklet.h.
References PropSegment().
fit()
void PropSegment::fit ()
Definition at line 274 of file FastTracklet.cxx.
References a, b, chisq, Hit::detectorID, fit_2hits(), fit_34hits(), getNHits(), SignedHit::hit, hits, Hit::index, and LogInfo.
Referenced by KalmanFastTracking::buildPropSegments(), KalmanDSTrk::buildPropSegments(), KalmanFastTracking::muonID_search(), and KalmanDSTrk::muonID_search().
fit_2hits()
void PropSegment::fit_2hits ()
Definition at line 329 of file FastTracklet.cxx.
References a, b, chisq, err_a, err_b, SignedHit::hit, hits, and Hit::pos.
Referenced by fit().
fit_34hits()
void PropSegment::fit_34hits ()
Definition at line 373 of file FastTracklet.cxx.
References linearFit_simple(), and resolveLR().
Referenced by fit().
getClosestApproach()
double PropSegment::getClosestApproach (double z, double pos)
Definition at line 168 of file FastTracklet.cxx.
References a, and b.
getExpPosition()
double PropSegment::getExpPosition (double z) const inline
Definition at line 76 of file FastTracklet.h.
References a, and b.
getNHits()
int PropSegment::getNHits () const
Definition at line 190 of file FastTracklet.cxx.
References hits.
Referenced by fit(), SQReco::fitTrackCand(), Tracklet::getSRecTrack(), isValid(), print(), KalmanFastTracking::processOneTracklet(), and KalmanDSTrk::processOneTracklet().
getNPlanes()
int PropSegment::getNPlanes () const
Definition at line 200 of file FastTracklet.cxx.
References SignedHit::hit, hits, and Hit::index.
Referenced by isValid(), and print().
getPosRef()
double PropSegment::getPosRef (double default_val = -9999.)
Definition at line 173 of file FastTracklet.cxx.
References SignedHit::hit, hits, Hit::index, and Hit::pos.
Referenced by KalmanFastTracking::muonID_search(), and KalmanDSTrk::muonID_search().
identify()
void PropSegment::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 60 of file FastTracklet.h.
References print().
init()
void PropSegment::init ()
Definition at line 136 of file FastTracklet.cxx.
References a, b, chisq, err_a, err_b, and hits.
Referenced by KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), and Reset().
isValid()
int PropSegment::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 210 of file FastTracklet.cxx.
References a, b, chisq, getNHits(), and getNPlanes().
Referenced by KalmanFastTracking::buildPropSegments(), and KalmanDSTrk::buildPropSegments().
linearFit_iterative()
void PropSegment::linearFit_iterative ()
Definition at line 436 of file FastTracklet.cxx.
References a, b, chisq, Hit::driftDistance, SignedHit::hit, hits, SignedHit::pos(), and SignedHit::sign.
linearFit_simple()
void PropSegment::linearFit_simple ()
Definition at line 379 of file FastTracklet.cxx.
References a, b, chisq, err_a, err_b, hits, and SignedHit::pos().
Referenced by fit_34hits().
print()
void PropSegment::print (std::ostream & os = std::cout) const
Definition at line 148 of file FastTracklet.cxx.
References a, b, chisq, Hit::detectorID, Hit::elementID, getNHits(), getNPlanes(), SignedHit::hit, hits, and Hit::index.
Referenced by KalmanFastTracking::buildPropSegments(), KalmanDSTrk::buildPropSegments(), and identify().
Reset()
void PropSegment::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 61 of file FastTracklet.h.
References init().
resolveLR() [1/2]
void PropSegment::resolveLR ()
Definition at line 223 of file FastTracklet.cxx.
References Hit::elementID, SignedHit::hit, hits, Hit::index, and SignedHit::sign.
Referenced by fit_34hits().
resolveLR() [2/2]
void PropSegment::resolveLR (int setting)
Definition at line 266 of file FastTracklet.cxx.
References hits, and SignedHit::sign.
Member Data Documentation
a
double PropSegment::a
Definition at line 105 of file FastTracklet.h.
Referenced by fit(), fit_2hits(), SQReco::fitTrackCand(), getClosestApproach(), getExpPosition(), Tracklet::getSRecTrack(), init(), isValid(), linearFit_iterative(), linearFit_simple(), print(), KalmanFastTracking::processOneTracklet(), and KalmanDSTrk::processOneTracklet().
b
double PropSegment::b
Definition at line 106 of file FastTracklet.h.
Referenced by fit(), fit_2hits(), getClosestApproach(), getExpPosition(), init(), isValid(), linearFit_iterative(), linearFit_simple(), and print().
chisq
double PropSegment::chisq
Definition at line 111 of file FastTracklet.h.
Referenced by fit(), fit_2hits(), init(), isValid(), linearFit_iterative(), linearFit_simple(), and print().
err_a
double PropSegment::err_a
Definition at line 107 of file FastTracklet.h.
Referenced by fit_2hits(), init(), and linearFit_simple().
err_b
double PropSegment::err_b
Definition at line 108 of file FastTracklet.h.
Referenced by fit_2hits(), init(), and linearFit_simple().
hits
SignedHit PropSegment::hits[4]
Definition at line 118 of file FastTracklet.h.
Referenced by KalmanFastTracking::buildPropSegments(), KalmanDSTrk::buildPropSegments(), fit(), fit_2hits(), getNHits(), getNPlanes(), getPosRef(), init(), linearFit_iterative(), linearFit_simple(), KalmanFastTracking::muonID_search(), KalmanDSTrk::muonID_search(), print(), PropSegment(), and resolveLR().
hodoHits
Hit PropSegment::hodoHits[4]
Definition at line 115 of file FastTracklet.h.
Referenced by KalmanFastTracking::muonID_hodoAid(), KalmanDSTrk::muonID_hodoAid(), and PropSegment().
nHodoHits
int PropSegment::nHodoHits
Definition at line 114 of file FastTracklet.h.
Referenced by KalmanFastTracking::muonID_hodoAid(), KalmanDSTrk::muonID_hodoAid(), KalmanFastTracking::muonID_search(), and KalmanDSTrk::muonID_search().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/FastTracklet.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/interface/FastTracklet.cxx