Class Reference for E1039 Core & Analysis Software: PHG4UserPrimaryParticleInformation Class Reference
PHG4UserPrimaryParticleInformation Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4UserPrimaryParticleInformation.h>
Public Member Functions
PHG4UserPrimaryParticleInformation (const int emb)
void Print () const
int get_embed () const
void set_user_track_id (int val)
int get_user_track_id () const
void set_user_vtx_id (int val)
int get_user_vtx_id () const
void set_user_barcode (int bcd)
int get_user_barcode () const
Detailed Description
Definition at line 7 of file PHG4UserPrimaryParticleInformation.h.
Constructor & Destructor Documentation
PHG4UserPrimaryParticleInformation()
PHG4UserPrimaryParticleInformation::PHG4UserPrimaryParticleInformation (const int emb) inline
Definition at line 10 of file PHG4UserPrimaryParticleInformation.h.
Member Function Documentation
get_embed()
int PHG4UserPrimaryParticleInformation::get_embed () const inline
Definition at line 22 of file PHG4UserPrimaryParticleInformation.h.
Referenced by PHG4TruthEventAction::EndOfEventAction().
get_user_barcode()
int PHG4UserPrimaryParticleInformation::get_user_barcode () const inline
Definition at line 31 of file PHG4UserPrimaryParticleInformation.h.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
get_user_track_id()
int PHG4UserPrimaryParticleInformation::get_user_track_id () const inline
Definition at line 25 of file PHG4UserPrimaryParticleInformation.h.
Referenced by PHG4TruthEventAction::EndOfEventAction().
get_user_vtx_id()
int PHG4UserPrimaryParticleInformation::get_user_vtx_id () const inline
Definition at line 28 of file PHG4UserPrimaryParticleInformation.h.
Referenced by PHG4TruthEventAction::EndOfEventAction().
Print()
void PHG4UserPrimaryParticleInformation::Print () const inline
Definition at line 16 of file PHG4UserPrimaryParticleInformation.h.
set_user_barcode()
void PHG4UserPrimaryParticleInformation::set_user_barcode (int bcd) inline
Definition at line 30 of file PHG4UserPrimaryParticleInformation.h.
Referenced by PHG4PrimaryGeneratorAction::GeneratePrimaries().
set_user_track_id()
void PHG4UserPrimaryParticleInformation::set_user_track_id (int val) inline
Definition at line 24 of file PHG4UserPrimaryParticleInformation.h.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
set_user_vtx_id()
void PHG4UserPrimaryParticleInformation::set_user_vtx_id (int val) inline
Definition at line 27 of file PHG4UserPrimaryParticleInformation.h.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
The documentation for this class was generated from the following file:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4main/PHG4UserPrimaryParticleInformation.h