E1039 Software: KalmanPrgTrk Class Reference
KalmanPrgTrk Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/KalmanPrgTrk.h>
Public Member Functions
KalmanPrgTrk (const PHField *field, const TGeoManager *geom, bool flag=true)
~KalmanPrgTrk ()
void Verbosity (const int a)
int Verbosity () const
void printTimers ()
int setRawEvent (SRawEvent *event_input)
void setRawEventDebug (SRawEvent *event_input)
bool acceptEvent (SRawEvent *rawEvent)
void buildTrackletsInStation (int stationID, int listID, double *pos_exp=NULL, double *window=NULL)
Tracklet finding stuff.
void buildBackPartialTracks ()
void buildGlobalTracks ()
int fitTracklet (Tracklet &tracklet)
bool acceptTracklet (Tracklet &tracklet)
bool hodoMask (Tracklet &tracklet)
bool muonID_comp (Tracklet &tracklet)
bool muonID_search (Tracklet &tracklet)
bool muonID_hodoAid (Tracklet &tracklet)
void buildPropSegments ()
void resolveLeftRight (SRawEvent::hit_pair hpair, int &LR1, int &LR2)
void resolveLeftRight (Tracklet &tracklet, double threshold)
void resolveSingleLeftRight (Tracklet &tracklet)
void removeBadHits (Tracklet &tracklet)
int reduceTrackletList (std::list< Tracklet > &tracklets)
void getSagittaWindowsInSt1 (Tracklet &tracklet, double *pos_exp, double *window, int st1ID)
void getExtrapoWindowsInSt1 (Tracklet &tracklet, double *pos_exp, double *window, int st1ID)
void printAtDetectorBack (int stationID, std::string outputFileName)
SRecTrack processOneTracklet (Tracklet &tracklet)
Track fitting stuff.
bool fitTrack (KalmanTrack &kmtrk)
void resolveLeftRight (KalmanTrack &kmtrk)
std::list< Tracklet > & getFinalTracklets ()
Final output.
std::list< Tracklet > & getBackPartials ()
std::list< Tracklet > & getTrackletList (int i)
std::list< SRecTrack > & getSRecTracks ()
std::list< PropSegment > & getPropSegments (int i)
void chi2fit (int n, double x[], double y[], double &a, double &b)
Tool, a simple-minded chi square fit.
Private Attributes
int verbosity
SRawEvent * rawEvent
std::vector< Hit > hitAll
std::list< Tracklet > trackletsInSt [5]
std::list< SRecTrack > stracks
std::list< PropSegment > propSegs [2]
std::vector< int > detectorIDs_mask [4]
Configurations of tracklet finding.
std::vector< int > detectorIDs_maskX [4]
std::vector< int > detectorIDs_maskY [4]
std::list< int > hitIDs_mask [4]
std::vector< int > detectorIDs_muidHodoAid [2]
std::vector< int > stationIDs_mask [nStations]
int detectorIDs_muid [2][4]
double z_ref_muid [2][4]
std::list< int > hitIDs_muid [2][4]
std::list< int > hitIDs_muidHodoAid [2]
double z_mask [nHodoPlanes+nPropPlanes]
double x_mask_min [nHodoPlanes+nPropPlanes][72]
double x_mask_max [nHodoPlanes+nPropPlanes][72]
double y_mask_min [nHodoPlanes+nPropPlanes][72]
double y_mask_max [nHodoPlanes+nPropPlanes][72]
std::vector< int > superIDs [nChamberPlanes/6+2]
For following part, id = 0, 1, 2, 3, 4, 5, 6 stand for station 0, 1, 2, 3+, 3-, and prop tubes X-Z and Y-Z.
double u_win [nChamberPlanes/6]
double u_costheta [nChamberPlanes/6]
double u_sintheta [nChamberPlanes/6]
double z_plane_x [nChamberPlanes/6]
double z_plane_u [nChamberPlanes/6]
double z_plane_v [nChamberPlanes/6]
double costheta_plane [nChamberPlanes+1]
double sintheta_plane [nChamberPlanes+1]
double z_plane [nChamberPlanes+1]
double slope_max [nChamberPlanes+1]
double intersection_max [nChamberPlanes+1]
double resol_plane [nChamberPlanes+1]
double spacing_plane [nChamberPlanes+1]
int s_detectorID [3]
Tracklet tracklet_curr
ROOT::Math::Minimizer * minimizer [2]
ROOT::Math::Functor fcn
KalmanFitter * kmfitter
GeomSvc * p_geomSvc
JobOptsSvc * p_jobOptsSvc
const bool enable_KF
std::map< std::string, PHTimer * > _timers
Detailed Description
Definition at line 35 of file KalmanPrgTrk.h.
Constructor & Destructor Documentation
KalmanPrgTrk::KalmanPrgTrk (const PHField * field, const TGeoManager * geom, bool flag = true) explicit
Definition at line 28 of file KalmanPrgTrk.cxx.
References _timers, costheta_plane, detectorIDs_mask, detectorIDs_maskX, detectorIDs_maskY, detectorIDs_muid, detectorIDs_muidHodoAid, enable_KF, Tracklet::Eval(), fcn, GeomSvc::get2DBoxSize(), GeomSvc::getCostheta(), GeomSvc::getDetectorID(), GeomSvc::getDetectorIDs(), GeomSvc::getPlaneNElements(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneResolution(), GeomSvc::getPlaneScaleY(), GeomSvc::getPlaneSpacing(), GeomSvc::getSintheta(), JobOptsSvc::instance(), GeomSvc::instance(), intersection_max, kmfitter, JobOptsSvc::m_enableKMag, JobOptsSvc::m_st0_reject, JobOptsSvc::m_st1_reject, JobOptsSvc::m_st2_reject, JobOptsSvc::m_st3m_reject, JobOptsSvc::m_st3p_reject, minimizer, MUID_Z_REF, nChamberPlanes, nHodoPlanes, nPropPlanes, nStations, p_geomSvc, p_jobOptsSvc, GeomSvc::printAlignPar(), GeomSvc::printTable(), GeomSvc::printWirePosition(), resol_plane, s_detectorID, KalmanFitter::setControlParameter(), sintheta_plane, slope_max, spacing_plane, stationIDs_mask, superIDs, tracklet_curr, TX_MAX, TY_MAX, u_costheta, u_sintheta, u_win, X0_MAX, x_mask_max, x_mask_min, Y0_MAX, y_mask_max, y_mask_min, z_mask, z_plane, z_plane_u, z_plane_v, z_plane_x, and z_ref_muid.
KalmanPrgTrk::~KalmanPrgTrk ()
Definition at line 339 of file KalmanPrgTrk.cxx.
References enable_KF, kmfitter, and minimizer.
Member Function Documentation
bool KalmanPrgTrk::acceptEvent (SRawEvent * rawEvent)
Definition at line 532 of file KalmanPrgTrk.cxx.
References detectorIDs_maskX, SRawEvent::getNHitsInD0(), SRawEvent::getNHitsInD1(), SRawEvent::getNHitsInD2(), SRawEvent::getNHitsInD3m(), SRawEvent::getNHitsInD3p(), SRawEvent::getNHitsInDetectors(), SRawEvent::getNPropHitsAll(), SRawEvent::getNRoadsNeg(), SRawEvent::getNRoadsPos(), and LogInfo.
Referenced by setRawEvent().
bool KalmanPrgTrk::acceptTracklet (Tracklet & tracklet)
Definition at line 1299 of file KalmanPrgTrk.cxx.
References Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), hodoMask(), GeomSvc::isInKMAG(), Tracklet::isValid(), LogInfo, muonID_comp(), muonID_search(), nStations, p_geomSvc, Tracklet::stationID, and Z_KMAG_BEND.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), and buildTrackletsInStation().
void KalmanPrgTrk::buildBackPartialTracks ()
Remove bad hits if needed
Definition at line 569 of file KalmanPrgTrk.cxx.
References acceptTracklet(), chi2fit(), Tracklet::chisq, detectorIDs_muid, fitTracklet(), GeomSvc::getPlaneType(), hitAll, hitIDs_muid, hodoMask(), Tracklet::isValid(), LogInfo, nChamberPlanes, p_geomSvc, Tracklet::print(), reduceTrackletList(), removeBadHits(), resolveLeftRight(), trackletsInSt, TX_MAX, X0_MAX, z_mask, and z_plane.
Referenced by setRawEvent().
void KalmanPrgTrk::buildGlobalTracks ()
Resolve the left-right with a tight pull cut, then a loose one, then resolve by single projections
Remove bad hits if needed
Definition at line 702 of file KalmanPrgTrk.cxx.
References _timers, acceptTracklet(), buildTrackletsInStation(), Tracklet::chisq_vtx, fitTracklet(), SRecTrack::getChisqVertex(), getExtrapoWindowsInSt1(), Tracklet::getMomentum(), getSagittaWindowsInSt1(), hodoMask(), Tracklet::invP, SRecTrack::isValid(), Tracklet::isValid(), LogInfo, JobOptsSvc::m_enableKMag, Tracklet::merge(), MERGE_THRES, p_jobOptsSvc, Tracklet::print(), processOneTracklet(), removeBadHits(), resolveLeftRight(), resolveSingleLeftRight(), and trackletsInSt.
Referenced by setRawEvent().
void KalmanPrgTrk::buildPropSegments ()
Definition at line 1558 of file KalmanPrgTrk.cxx.
References PropSegment::fit(), SRawEvent::getPartialHitPairsInSuperDetector(), hitAll, PropSegment::hits, PropSegment::isValid(), LogInfo, PropSegment::print(), propSegs, rawEvent, and superIDs.
Referenced by setRawEvent().
void KalmanPrgTrk::buildTrackletsInStation (int stationID, int listID, double * pos_exp = NULL, double * window = NULL)
Tracklet finding stuff.
Definition at line 1133 of file KalmanPrgTrk.cxx.
References acceptTracklet(), fitTracklet(), SRawEvent::getPartialHitPairsInSuperDetector(), hitAll, Tracklet::hits, Tracklet::isValid(), LogInfo, Tracklet::nUHits, NULL, Tracklet::nVHits, Tracklet::nXHits, Tracklet::print(), rawEvent, Tracklet::sortHits(), spacing_plane, Tracklet::stationID, superIDs, trackletsInSt, TX_MAX, TY_MAX, u_costheta, u_sintheta, u_win, z_plane, z_plane_u, z_plane_v, and z_plane_x.
Referenced by buildGlobalTracks(), and setRawEvent().
void KalmanPrgTrk::chi2fit (int n, double x[], double y[], double & a, double & b)
Tool, a simple-minded chi square fit.
Definition at line 2006 of file KalmanPrgTrk.cxx.
Referenced by buildBackPartialTracks().
bool KalmanPrgTrk::fitTrack (KalmanTrack & kmtrk)
Definition at line 1939 of file KalmanPrgTrk.cxx.
References KalmanTrack::getNodeList(), kmfitter, KalmanFitter::processOneTrack(), and KalmanFitter::updateTrack().
Referenced by processOneTracklet(), and resolveLeftRight().
int KalmanPrgTrk::fitTracklet (Tracklet & tracklet)
Definition at line 1623 of file KalmanPrgTrk.cxx.
References Tracklet::chisq, Tracklet::err_invP, Tracklet::err_tx, Tracklet::err_ty, Tracklet::err_x0, Tracklet::err_y0, Tracklet::invP, INVP_MAX, INVP_MIN, JobOptsSvc::m_enableKMag, minimizer, nStations, p_jobOptsSvc, Tracklet::stationID, tracklet_curr, Tracklet::tx, TX_MAX, Tracklet::ty, TY_MAX, Tracklet::x0, X0_MAX, Tracklet::y0, and Y0_MAX.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), buildTrackletsInStation(), removeBadHits(), resolveLeftRight(), and resolveSingleLeftRight().
std::list<Tracklet>& KalmanPrgTrk::getBackPartials () inline
Definition at line 105 of file KalmanPrgTrk.h.
References trackletsInSt.
void KalmanPrgTrk::getExtrapoWindowsInSt1 (Tracklet & tracklet, double * pos_exp, double * window, int st1ID)
Definition at line 1702 of file KalmanPrgTrk.cxx.
References costheta_plane, Tracklet::getExpPosErrorX(), Tracklet::getExpPosErrorY(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), GeomSvc::getPlaneType(), GeomSvc::getUinStereoPlane(), nStations, p_geomSvc, sintheta_plane, Tracklet::stationID, and z_plane.
Referenced by buildGlobalTracks().
std::list<Tracklet>& KalmanPrgTrk::getFinalTracklets () inline
Final output.
Definition at line 104 of file KalmanPrgTrk.h.
References trackletsInSt.
Referenced by KalmanFastTrackingWrapper::process_event().
std::list<PropSegment>& KalmanPrgTrk::getPropSegments (int i) inline
Definition at line 108 of file KalmanPrgTrk.h.
References propSegs.
void KalmanPrgTrk::getSagittaWindowsInSt1 (Tracklet & tracklet, double * pos_exp, double * window, int st1ID)
Definition at line 1730 of file KalmanPrgTrk.cxx.
References Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), GeomSvc::getPlaneType(), GeomSvc::getUinStereoPlane(), Tracklet::hits, nStations, p_geomSvc, s_detectorID, SAGITTA_DUMP_CENTER, SAGITTA_DUMP_WIN, SAGITTA_TARGET_CENTER, SAGITTA_TARGET_WIN, Tracklet::stationID, Z_DUMP, z_plane, and Z_TARGET.
Referenced by buildGlobalTracks().
std::list<SRecTrack>& KalmanPrgTrk::getSRecTracks () inline
Definition at line 107 of file KalmanPrgTrk.h.
References stracks.
Referenced by KalmanFastTrackingWrapper::process_event().
std::list<Tracklet>& KalmanPrgTrk::getTrackletList (int i) inline
Definition at line 106 of file KalmanPrgTrk.h.
References trackletsInSt.
bool KalmanPrgTrk::hodoMask (Tracklet & tracklet)
Definition at line 1329 of file KalmanPrgTrk.cxx.
References Tracklet::getExpPosErrorX(), Tracklet::getExpPosErrorY(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), hitAll, hitIDs_mask, LogInfo, nChamberPlanes, nStations, Tracklet::stationID, stationIDs_mask, x_mask_max, x_mask_min, y_mask_max, y_mask_min, and z_mask.
Referenced by acceptTracklet(), buildBackPartialTracks(), and buildGlobalTracks().
bool KalmanPrgTrk::muonID_comp (Tracklet & tracklet)
Definition at line 1452 of file KalmanPrgTrk.cxx.
References Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::invP, LogInfo, MUID_EMP_P0, MUID_EMP_P1, MUID_EMP_P2, MUID_R_CUT, MUID_REJECT, MUID_THE_P0, MUID_Z_REF, nStations, propSegs, Tracklet::seg_x, Tracklet::seg_y, Tracklet::stationID, Tracklet::tx, and Tracklet::ty.
Referenced by acceptTracklet().
bool KalmanPrgTrk::muonID_hodoAid (Tracklet & tracklet)
Definition at line 1509 of file KalmanPrgTrk.cxx.
References Tracklet::getExpPosErrorX(), Tracklet::getExpPosErrorY(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), hitAll, hitIDs_muidHodoAid, PropSegment::hodoHits, Tracklet::invP, MUID_EMP_P0, MUID_EMP_P1, MUID_EMP_P2, MUID_REJECT, MUID_THE_P0, MUID_Z_REF, nChamberPlanes, PropSegment::nHodoHits, nStations, Tracklet::seg_x, Tracklet::seg_y, Tracklet::stationID, x_mask_max, x_mask_min, y_mask_max, y_mask_min, and z_mask.
Referenced by muonID_search().
bool KalmanPrgTrk::muonID_search (Tracklet & tracklet)
Definition at line 1380 of file KalmanPrgTrk.cxx.
References detectorIDs_muid, PropSegment::fit(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), PropSegment::getPosRef(), SignedHit::hit, hitAll, hitIDs_muid, PropSegment::hits, PropSegment::init(), Tracklet::invP, GeomSvc::isInPlane(), MUID_EMP_P0, MUID_EMP_P1, MUID_EMP_P2, MUID_REJECT, MUID_THE_P0, MUID_Z_REF, muonID_hodoAid(), nChamberPlanes, PropSegment::nHodoHits, nStations, p_geomSvc, Tracklet::seg_x, Tracklet::seg_y, SignedHit::sign, Tracklet::stationID, Tracklet::tx, Tracklet::ty, z_mask, and z_ref_muid.
Referenced by acceptTracklet().
void KalmanPrgTrk::printAtDetectorBack (int stationID, std::string outputFileName)
Definition at line 1778 of file KalmanPrgTrk.cxx.
References GeomSvc::getPlaneCenterX(), GeomSvc::getPlaneCenterY(), GeomSvc::getPlanePosition(), GeomSvc::getPlaneScaleX(), GeomSvc::getPlaneScaleY(), p_geomSvc, and trackletsInSt.
void KalmanPrgTrk::printTimers ()
Definition at line 1992 of file KalmanPrgTrk.cxx.
References _timers.
Referenced by KalmanFastTrackingWrapper::process_event().
SRecTrack KalmanPrgTrk::processOneTracklet (Tracklet & tracklet)
Track fitting stuff.
Definition at line 1822 of file KalmanPrgTrk.cxx.
References TrkPar::_covar_kf, TrkPar::_state_kf, TrkPar::_z, PropSegment::a, fitTrack(), Tracklet::getCharge(), KalmanTrack::getChisq(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), KalmanTrack::getHitIndexList(), PropSegment::getNHits(), KalmanTrack::getNodeList(), GeomSvc::getPlanePosition(), TriggerRoad::getRoadID(), KalmanTrack::getSRecTrack(), Tracklet::getSRecTrack(), Tracklet::hits, Tracklet::invP, KalmanTrack::isValid(), LogInfo, p_geomSvc, KalmanTrack::print(), KalmanTrack::printNodes(), Tracklet::seg_x, Tracklet::seg_y, KalmanTrack::setCurrTrkpar(), SRecTrack::setKalmanStatus(), SRecTrack::setNHitsInPT(), SRecTrack::setPTSlope(), SRecTrack::setTriggerRoad(), Tracklet::tx, and Tracklet::ty.
Referenced by buildGlobalTracks(), and setRawEvent().
int KalmanPrgTrk::reduceTrackletList (std::list< Tracklet > & tracklets)
Definition at line 1665 of file KalmanPrgTrk.cxx.
References LogInfo.
Referenced by buildBackPartialTracks().
void KalmanPrgTrk::removeBadHits (Tracklet & tracklet)
Definition at line 993 of file KalmanPrgTrk.cxx.
References Tracklet::calcChisq(), Hit::detectorID, Hit::driftDistance, fitTracklet(), GeomSvc::getPlaneType(), SignedHit::hit, Tracklet::hits, Hit::index, Tracklet::isValid(), LogInfo, nChamberPlanes, Tracklet::nUHits, NULL, Tracklet::nVHits, Tracklet::nXHits, p_geomSvc, Hit::print(), Tracklet::print(), Tracklet::residual, resol_plane, resolveSingleLeftRight(), and SignedHit::sign.
Referenced by buildBackPartialTracks(), and buildGlobalTracks().
void KalmanPrgTrk::resolveLeftRight (SRawEvent::hit_pair hpair, int & LR1, int & LR2)
Definition at line 1093 of file KalmanPrgTrk.cxx.
References hitAll, intersection_max, slope_max, and z_plane.
Referenced by buildBackPartialTracks(), and buildGlobalTracks().
void KalmanPrgTrk::resolveLeftRight (Tracklet & tracklet, double threshold)
Definition at line 862 of file KalmanPrgTrk.cxx.
References costheta_plane, Tracklet::err_tx, Tracklet::err_ty, Tracklet::err_x0, Tracklet::err_y0, fitTracklet(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::getXZErrorInSt1(), Tracklet::getXZInfoInSt1(), Tracklet::hits, intersection_max, LogInfo, Tracklet::print(), sintheta_plane, slope_max, Tracklet::stationID, Tracklet::tx, Tracklet::ty, Tracklet::x0, Tracklet::y0, and z_plane.
void KalmanPrgTrk::resolveLeftRight (KalmanTrack & kmtrk)
Definition at line 1952 of file KalmanPrgTrk.cxx.
References fitTrack(), KalmanTrack::getHitIndexList(), KalmanTrack::getNodeList(), GeomSvc::getPlaneResolution(), GeomSvc::getUinStereoPlane(), and p_geomSvc.
void KalmanPrgTrk::resolveSingleLeftRight (Tracklet & tracklet)
Definition at line 970 of file KalmanPrgTrk.cxx.
References costheta_plane, fitTracklet(), Tracklet::getExpPositionX(), Tracklet::getExpPositionY(), Tracklet::hits, LogInfo, Tracklet::print(), sintheta_plane, and z_plane.
Referenced by buildGlobalTracks(), and removeBadHits().
int KalmanPrgTrk::setRawEvent (SRawEvent * event_input)
Definition at line 352 of file KalmanPrgTrk.cxx.
References _timers, acceptEvent(), buildBackPartialTracks(), buildGlobalTracks(), buildPropSegments(), buildTrackletsInStation(), detectorIDs_maskX, detectorIDs_maskY, detectorIDs_muid, detectorIDs_muidHodoAid, enable_KF, SRawEvent::getAllHits(), SRawEvent::getHitsIndexInDetector(), SRawEvent::getHitsIndexInDetectors(), hitAll, hitIDs_mask, hitIDs_muid, hitIDs_muidHodoAid, SRawEvent::isFPGATriggered(), LogInfo, JobOptsSvc::m_mcMode, p_jobOptsSvc, processOneTracklet(), propSegs, rawEvent, stracks, TFEXIT_FAIL_BACKPARTIAL, TFEXIT_FAIL_GLOABL, TFEXIT_FAIL_MULTIPLICITY, TFEXIT_FAIL_ST2_TRACKLET, TFEXIT_FAIL_ST3_TRACKLET, TFEXIT_SUCCESS, trackletsInSt, and verbosity.
Referenced by KalmanFastTrackingWrapper::process_event().
void KalmanPrgTrk::setRawEventDebug (SRawEvent * event_input)
Definition at line 346 of file KalmanPrgTrk.cxx.
References SRawEvent::getAllHits(), hitAll, and rawEvent.
void KalmanPrgTrk::Verbosity (const int a) inline
Definition at line 42 of file KalmanPrgTrk.h.
References verbosity.
Referenced by KalmanFastTrackingWrapper::InitRun().
int KalmanPrgTrk::Verbosity () const inline
Definition at line 43 of file KalmanPrgTrk.h.
References verbosity.
Member Data Documentation
std::map< std::string, PHTimer* > KalmanPrgTrk::_timers private
Definition at line 207 of file KalmanPrgTrk.h.
Referenced by buildGlobalTracks(), KalmanPrgTrk(), printTimers(), and setRawEvent().
double KalmanPrgTrk::costheta_plane[nChamberPlanes+1] private
Definition at line 169 of file KalmanPrgTrk.h.
Referenced by getExtrapoWindowsInSt1(), KalmanPrgTrk(), resolveLeftRight(), and resolveSingleLeftRight().
std::vector<int> KalmanPrgTrk::detectorIDs_mask[4] private
Configurations of tracklet finding.
Definition at line 134 of file KalmanPrgTrk.h.
Referenced by KalmanPrgTrk().
std::vector<int> KalmanPrgTrk::detectorIDs_maskX[4] private
Definition at line 135 of file KalmanPrgTrk.h.
Referenced by acceptEvent(), KalmanPrgTrk(), and setRawEvent().
std::vector<int> KalmanPrgTrk::detectorIDs_maskY[4] private
Definition at line 136 of file KalmanPrgTrk.h.
Referenced by KalmanPrgTrk(), and setRawEvent().
int KalmanPrgTrk::detectorIDs_muid[2][4] private
Definition at line 144 of file KalmanPrgTrk.h.
Referenced by buildBackPartialTracks(), KalmanPrgTrk(), muonID_search(), and setRawEvent().
std::vector<int> KalmanPrgTrk::detectorIDs_muidHodoAid[2] private
Definition at line 138 of file KalmanPrgTrk.h.
Referenced by KalmanPrgTrk(), and setRawEvent().
const bool KalmanPrgTrk::enable_KF private
Definition at line 205 of file KalmanPrgTrk.h.
Referenced by KalmanPrgTrk(), setRawEvent(), and ~KalmanPrgTrk().
ROOT::Math::Functor KalmanPrgTrk::fcn private
Definition at line 193 of file KalmanPrgTrk.h.
Referenced by KalmanPrgTrk().
std::vector<Hit> KalmanPrgTrk::hitAll private
Definition at line 119 of file KalmanPrgTrk.h.
Referenced by buildBackPartialTracks(), buildPropSegments(), buildTrackletsInStation(), hodoMask(), muonID_hodoAid(), muonID_search(), resolveLeftRight(), setRawEvent(), and setRawEventDebug().
std::list<int> KalmanPrgTrk::hitIDs_mask[4] private
Definition at line 137 of file KalmanPrgTrk.h.
Referenced by hodoMask(), and setRawEvent().
std::list<int> KalmanPrgTrk::hitIDs_muid[2][4] private
Definition at line 146 of file KalmanPrgTrk.h.
Referenced by buildBackPartialTracks(), muonID_search(), and setRawEvent().
std::list<int> KalmanPrgTrk::hitIDs_muidHodoAid[2] private
Definition at line 147 of file KalmanPrgTrk.h.
Referenced by muonID_hodoAid(), and setRawEvent().
double KalmanPrgTrk::intersection_max[nChamberPlanes+1] private
Definition at line 177 of file KalmanPrgTrk.h.
Referenced by KalmanPrgTrk(), and resolveLeftRight().
KalmanFitter* KalmanPrgTrk::kmfitter private
Definition at line 196 of file KalmanPrgTrk.h.
Referenced by fitTrack(), KalmanPrgTrk(), and ~KalmanPrgTrk().
ROOT::Math::Minimizer* KalmanPrgTrk::minimizer[2] private
Definition at line 192 of file KalmanPrgTrk.h.
Referenced by fitTracklet(), KalmanPrgTrk(), and ~KalmanPrgTrk().
GeomSvc* KalmanPrgTrk::p_geomSvc private
Definition at line 199 of file KalmanPrgTrk.h.
Referenced by acceptTracklet(), buildBackPartialTracks(), getExtrapoWindowsInSt1(), getSagittaWindowsInSt1(), KalmanPrgTrk(), muonID_search(), printAtDetectorBack(), processOneTracklet(), removeBadHits(), and resolveLeftRight().
JobOptsSvc* KalmanPrgTrk::p_jobOptsSvc private
Definition at line 202 of file KalmanPrgTrk.h.
Referenced by buildGlobalTracks(), fitTracklet(), KalmanPrgTrk(), and setRawEvent().
std::list<PropSegment> KalmanPrgTrk::propSegs[2] private
Definition at line 130 of file KalmanPrgTrk.h.
Referenced by buildPropSegments(), getPropSegments(), muonID_comp(), and setRawEvent().
SRawEvent* KalmanPrgTrk::rawEvent private
Definition at line 118 of file KalmanPrgTrk.h.
Referenced by buildPropSegments(), buildTrackletsInStation(), setRawEvent(), and setRawEventDebug().
double KalmanPrgTrk::resol_plane[nChamberPlanes+1] private
Definition at line 180 of file KalmanPrgTrk.h.
Referenced by KalmanPrgTrk(), and removeBadHits().
int KalmanPrgTrk::s_detectorID[3] private
Definition at line 186 of file KalmanPrgTrk.h.
Referenced by getSagittaWindowsInSt1(), and KalmanPrgTrk().
double KalmanPrgTrk::sintheta_plane[nChamberPlanes+1] private
Definition at line 170 of file KalmanPrgTrk.h.
Referenced by getExtrapoWindowsInSt1(), KalmanPrgTrk(), resolveLeftRight(), and resolveSingleLeftRight().
double KalmanPrgTrk::slope_max[nChamberPlanes+1] private
Definition at line 176 of file KalmanPrgTrk.h.
Referenced by KalmanPrgTrk(), and resolveLeftRight().
double KalmanPrgTrk::spacing_plane[nChamberPlanes+1] private
Definition at line 183 of file KalmanPrgTrk.h.
Referenced by buildTrackletsInStation(), and KalmanPrgTrk().
std::vector<int> KalmanPrgTrk::stationIDs_mask[nStations] private
Definition at line 141 of file KalmanPrgTrk.h.
Referenced by hodoMask(), and KalmanPrgTrk().
std::list<SRecTrack> KalmanPrgTrk::stracks private
Definition at line 126 of file KalmanPrgTrk.h.
Referenced by getSRecTracks(), and setRawEvent().
std::vector<int> KalmanPrgTrk::superIDs[nChamberPlanes/6+2] private
For following part, id = 0, 1, 2, 3, 4, 5, 6 stand for station 0, 1, 2, 3+, 3-, and prop tubes X-Z and Y-Z.
Definition at line 158 of file KalmanPrgTrk.h.
Referenced by buildPropSegments(), buildTrackletsInStation(), and KalmanPrgTrk().
Tracklet KalmanPrgTrk::tracklet_curr private
Definition at line 189 of file KalmanPrgTrk.h.
Referenced by fitTracklet(), and KalmanPrgTrk().
std::list<Tracklet> KalmanPrgTrk::trackletsInSt[5] private
Definition at line 123 of file KalmanPrgTrk.h.
Referenced by buildBackPartialTracks(), buildGlobalTracks(), buildTrackletsInStation(), getBackPartials(), getFinalTracklets(), getTrackletList(), printAtDetectorBack(), and setRawEvent().
double KalmanPrgTrk::u_costheta[nChamberPlanes/6] private
Definition at line 162 of file KalmanPrgTrk.h.
Referenced by buildTrackletsInStation(), and KalmanPrgTrk().
double KalmanPrgTrk::u_sintheta[nChamberPlanes/6] private
Definition at line 163 of file KalmanPrgTrk.h.
Referenced by buildTrackletsInStation(), and KalmanPrgTrk().
double KalmanPrgTrk::u_win[nChamberPlanes/6] private
Definition at line 161 of file KalmanPrgTrk.h.
Referenced by buildTrackletsInStation(), and KalmanPrgTrk().
int KalmanPrgTrk::verbosity private
Definition at line 115 of file KalmanPrgTrk.h.
Referenced by setRawEvent(), and Verbosity().
double KalmanPrgTrk::x_mask_max[nHodoPlanes+nPropPlanes][72] private
Definition at line 152 of file KalmanPrgTrk.h.
Referenced by hodoMask(), KalmanPrgTrk(), and muonID_hodoAid().
double KalmanPrgTrk::x_mask_min[nHodoPlanes+nPropPlanes][72] private
Definition at line 151 of file KalmanPrgTrk.h.
Referenced by hodoMask(), KalmanPrgTrk(), and muonID_hodoAid().
double KalmanPrgTrk::y_mask_max[nHodoPlanes+nPropPlanes][72] private
Definition at line 154 of file KalmanPrgTrk.h.
Referenced by hodoMask(), KalmanPrgTrk(), and muonID_hodoAid().
double KalmanPrgTrk::y_mask_min[nHodoPlanes+nPropPlanes][72] private
Definition at line 153 of file KalmanPrgTrk.h.
Referenced by hodoMask(), KalmanPrgTrk(), and muonID_hodoAid().
double KalmanPrgTrk::z_mask[nHodoPlanes+nPropPlanes] private
Definition at line 150 of file KalmanPrgTrk.h.
Referenced by buildBackPartialTracks(), hodoMask(), KalmanPrgTrk(), muonID_hodoAid(), and muonID_search().
double KalmanPrgTrk::z_plane[nChamberPlanes+1] private
Definition at line 173 of file KalmanPrgTrk.h.
Referenced by buildBackPartialTracks(), buildTrackletsInStation(), getExtrapoWindowsInSt1(), getSagittaWindowsInSt1(), KalmanPrgTrk(), resolveLeftRight(), and resolveSingleLeftRight().
double KalmanPrgTrk::z_plane_u[nChamberPlanes/6] private
Definition at line 165 of file KalmanPrgTrk.h.
Referenced by buildTrackletsInStation(), and KalmanPrgTrk().
double KalmanPrgTrk::z_plane_v[nChamberPlanes/6] private
Definition at line 166 of file KalmanPrgTrk.h.
Referenced by buildTrackletsInStation(), and KalmanPrgTrk().
double KalmanPrgTrk::z_plane_x[nChamberPlanes/6] private
Definition at line 164 of file KalmanPrgTrk.h.
Referenced by buildTrackletsInStation(), and KalmanPrgTrk().
double KalmanPrgTrk::z_ref_muid[2][4] private
Definition at line 145 of file KalmanPrgTrk.h.
Referenced by KalmanPrgTrk(), and muonID_search().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/KalmanPrgTrk.h
/home/yuhw/GitHub/SeaQuest/e1039-core/packages/ktracker/KalmanPrgTrk.cxx