Class Reference for E1039 Core & Analysis Software: OnlMonParam Class Reference
OnlMonParam Class Reference
Class to get OnlMon run-dependent parameters from the configuration directory.
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonParam.h>
Public Member Functions
OnlMonParam (const OnlMonClient *omc)
OnlMonParam (const std::string name)
virtual ~OnlMonParam ()
void BaseDir (const std::string dir_base)
std::string BaseDir () const
void RunID (const int run_id)
int RunID () const
void Verbosity (const bool verb)
int Verbosity () const
void DoAssert (const bool val)
bool DoAssert () const
std::string GetCharParam (const std::string par_name)
double GetDoubleParam (const std::string par_name)
int GetIntParam (const std::string par_name)
bool GetBoolParam (const std::string par_name)
Protected Member Functions
std::string FindParamInDir (const std::string par_name)
bool FindParamInFile (const std::string file_name, const int run, const std::string par_name, std::string &par_value)
Protected Attributes
std::string m_name
std::string m_dir_base
int m_run_id
int m_verb
bool m_do_assert
Detailed Description
Class to get OnlMon run-dependent parameters from the configuration directory.
The OnlMon client often needs run-dependent parameters when judging the goodness of data quality in OnlMonClient::DrawMonitor(). Such parameters should be first defined in TSV files under the configuration directory, which is by default /data2/e1039/onlmon/param. They are then read via OnlMonParam::GetIntParam() etc.
This class aborts the program when a value of the requested parameter doesn't exist. You can chage this behavior by OnlMonParam::DoAssert().
The run number is automatically selected via recoConsts. You can use OnlMonParam::RunID() when you have to fix it.
Typical usage:
OnlMonParam param(this);
int n_ttdc = param.GetIntParam("N_TAIWAN_TDC");
Definition at line 26 of file OnlMonParam.h.
Constructor & Destructor Documentation
OnlMonParam() [1/2]
OnlMonParam::OnlMonParam (const OnlMonClient * omc)
Definition at line 12 of file OnlMonParam.cc.
OnlMonParam() [2/2]
OnlMonParam::OnlMonParam (const std::string name)
Definition at line 22 of file OnlMonParam.cc.
~OnlMonParam()
OnlMonParam::~OnlMonParam () virtual
Definition at line 32 of file OnlMonParam.cc.
Member Function Documentation
BaseDir() [1/2]
std::string OnlMonParam::BaseDir () const inline
Definition at line 40 of file OnlMonParam.h.
References m_dir_base.
BaseDir() [2/2]
void OnlMonParam::BaseDir (const std::string dir_base) inline
Definition at line 39 of file OnlMonParam.h.
References m_dir_base.
DoAssert() [1/2]
bool OnlMonParam::DoAssert () const inline
Definition at line 49 of file OnlMonParam.h.
References m_do_assert.
DoAssert() [2/2]
void OnlMonParam::DoAssert (const bool val) inline
Definition at line 48 of file OnlMonParam.h.
References m_do_assert.
FindParamInDir()
std::string OnlMonParam::FindParamInDir (const std::string par_name) protected
Definition at line 83 of file OnlMonParam.cc.
References FindParamInFile(), PHFlag::get_IntFlag(), recoConsts::instance(), m_dir_base, m_do_assert, m_name, m_run_id, and m_verb.
Referenced by GetBoolParam(), GetCharParam(), GetDoubleParam(), and GetIntParam().
FindParamInFile()
bool OnlMonParam::FindParamInFile (const std::string file_name, const int run, const std::string par_name, std::string & par_value) protected
Definition at line 120 of file OnlMonParam.cc.
References m_verb.
Referenced by FindParamInDir().
GetBoolParam()
bool OnlMonParam::GetBoolParam (const std::string par_name)
Definition at line 70 of file OnlMonParam.cc.
References FindParamInDir(), m_do_assert, and m_verb.
GetCharParam()
std::string OnlMonParam::GetCharParam (const std::string par_name)
Definition at line 37 of file OnlMonParam.cc.
References FindParamInDir(), and m_verb.
GetDoubleParam()
double OnlMonParam::GetDoubleParam (const std::string par_name)
Definition at line 44 of file OnlMonParam.cc.
References FindParamInDir(), m_do_assert, and m_verb.
GetIntParam()
int OnlMonParam::GetIntParam (const std::string par_name)
Definition at line 57 of file OnlMonParam.cc.
References FindParamInDir(), m_do_assert, and m_verb.
Referenced by OnlMonMainDaq::DrawMonitor().
RunID() [1/2]
int OnlMonParam::RunID () const inline
Definition at line 43 of file OnlMonParam.h.
References m_run_id.
RunID() [2/2]
void OnlMonParam::RunID (const int run_id) inline
Definition at line 42 of file OnlMonParam.h.
References m_run_id.
Verbosity() [1/2]
int OnlMonParam::Verbosity () const inline
Definition at line 46 of file OnlMonParam.h.
References m_verb.
Verbosity() [2/2]
void OnlMonParam::Verbosity (const bool verb) inline
Definition at line 45 of file OnlMonParam.h.
References m_verb.
Member Data Documentation
m_dir_base
std::string OnlMonParam::m_dir_base protected
Definition at line 29 of file OnlMonParam.h.
Referenced by BaseDir(), and FindParamInDir().
m_do_assert
bool OnlMonParam::m_do_assert protected
Definition at line 32 of file OnlMonParam.h.
Referenced by DoAssert(), FindParamInDir(), GetBoolParam(), GetDoubleParam(), and GetIntParam().
m_name
std::string OnlMonParam::m_name protected
Definition at line 28 of file OnlMonParam.h.
Referenced by FindParamInDir().
m_run_id
int OnlMonParam::m_run_id protected
Definition at line 30 of file OnlMonParam.h.
Referenced by FindParamInDir(), and RunID().
m_verb
int OnlMonParam::m_verb protected
Definition at line 31 of file OnlMonParam.h.
Referenced by FindParamInDir(), FindParamInFile(), GetBoolParam(), GetCharParam(), GetDoubleParam(), GetIntParam(), and Verbosity().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonParam.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/online/onlmonserver/OnlMonParam.cc