E1039 Software: PHG4BNLTargetCoilSteppingAction Class Reference
PHG4BNLTargetCoilSteppingAction Class Reference
#include </home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4BNLTargetCoilSteppingAction.h>
Public Member Functions
PHG4BNLTargetCoilSteppingAction (PHG4BNLTargetCoilDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4BNLTargetCoilSteppingAction ()
destructor
bool UserSteppingAction (const G4Step *, bool)
stepping action
void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
void SaveLightYield (const int i=1)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
void SetOpt (const std::string &name, const int i)
bool IntOptExist (const std::string &name)
int GetIntOpt (const std::string &name)
std::string GetName () const
Private Attributes
PHG4BNLTargetCoilDetector * detector_
pointer to the detector
const PHParameters * params
PHG4HitContainer * hits_
pointer to hit container
PHG4Hit * hit
PHG4Shower * saveshower
G4VPhysicalVolume * savevolpre
G4VPhysicalVolume * savevolpost
int save_light_yield
int savetrackid
int saveprestepstatus
int savepoststepstatus
int active
int IsBlackHole
int use_g4_steps
double zmin
double zmax
double tmin
double tmax
Additional Inherited Members
Protected Attributes inherited from PHG4SteppingAction
int verbosity
std::string name
Detailed Description
Definition at line 15 of file PHG4BNLTargetCoilSteppingAction.h.
Constructor & Destructor Documentation
PHG4BNLTargetCoilSteppingAction()
PHG4BNLTargetCoilSteppingAction::PHG4BNLTargetCoilSteppingAction (PHG4BNLTargetCoilDetector * detector, const PHParameters * parameters)
constructor
Definition at line 25 of file PHG4BNLTargetCoilSteppingAction.cc.
References zmax, and zmin.
~PHG4BNLTargetCoilSteppingAction()
PHG4BNLTargetCoilSteppingAction::~PHG4BNLTargetCoilSteppingAction () virtual
destructor
Definition at line 50 of file PHG4BNLTargetCoilSteppingAction.cc.
References hit.
Member Function Documentation
SaveLightYield()
void PHG4BNLTargetCoilSteppingAction::SaveLightYield (const int i = 1) inline
Definition at line 30 of file PHG4BNLTargetCoilSteppingAction.h.
References save_light_yield.
SetInterfacePointers()
void PHG4BNLTargetCoilSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 308 of file PHG4BNLTargetCoilSteppingAction.cc.
References detector_, PHG4Detector::GetName(), hits_, IsBlackHole, and PHG4BNLTargetCoilDetector::SuperDetector().
UserSteppingAction()
bool PHG4BNLTargetCoilSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 60 of file PHG4BNLTargetCoilSteppingAction.cc.
References active, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4BNLTargetCoilDetector::get_elem_id(), PHG4Hit::get_hit_id(), PHG4BNLTargetCoilDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4Hit::get_x(), PHG4Hit::get_z(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4SteppingAction::GetVisibleEnergyDeposition(), hit, hits_, IsBlackHole, PHG4BNLTargetCoilDetector::IsInCylinder(), PHG4Hit::Reset(), save_light_yield, savepoststepstatus, saveprestepstatus, saveshower, savetrackid, savevolpost, savevolpre, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_light_yield(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4BNLTargetCoilDetector::SuperDetector(), tmax, tmin, use_g4_steps, zmax, and zmin.
Member Data Documentation
active
int PHG4BNLTargetCoilSteppingAction::active private
Definition at line 47 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction().
detector_
PHG4BNLTargetCoilDetector* PHG4BNLTargetCoilSteppingAction::detector_ private
pointer to the detector
Definition at line 33 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
hit
PHG4Hit* PHG4BNLTargetCoilSteppingAction::hit private
Definition at line 39 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4BNLTargetCoilSteppingAction().
hits_
PHG4HitContainer* PHG4BNLTargetCoilSteppingAction::hits_ private
pointer to hit container
Definition at line 38 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
IsBlackHole
int PHG4BNLTargetCoilSteppingAction::IsBlackHole private
Definition at line 48 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
params
const PHParameters* PHG4BNLTargetCoilSteppingAction::params private
Definition at line 35 of file PHG4BNLTargetCoilSteppingAction.h.
save_light_yield
int PHG4BNLTargetCoilSteppingAction::save_light_yield private
Definition at line 43 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by SaveLightYield(), and UserSteppingAction().
savepoststepstatus
int PHG4BNLTargetCoilSteppingAction::savepoststepstatus private
Definition at line 46 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction().
saveprestepstatus
int PHG4BNLTargetCoilSteppingAction::saveprestepstatus private
Definition at line 45 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction().
saveshower
PHG4Shower* PHG4BNLTargetCoilSteppingAction::saveshower private
Definition at line 40 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction().
savetrackid
int PHG4BNLTargetCoilSteppingAction::savetrackid private
Definition at line 44 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction().
savevolpost
G4VPhysicalVolume* PHG4BNLTargetCoilSteppingAction::savevolpost private
Definition at line 42 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction().
savevolpre
G4VPhysicalVolume* PHG4BNLTargetCoilSteppingAction::savevolpre private
Definition at line 41 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction().
tmax
double PHG4BNLTargetCoilSteppingAction::tmax private
Definition at line 53 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction().
tmin
double PHG4BNLTargetCoilSteppingAction::tmin private
Definition at line 52 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction().
use_g4_steps
int PHG4BNLTargetCoilSteppingAction::use_g4_steps private
Definition at line 49 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by UserSteppingAction().
zmax
double PHG4BNLTargetCoilSteppingAction::zmax private
Definition at line 51 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by PHG4BNLTargetCoilSteppingAction(), and UserSteppingAction().
zmin
double PHG4BNLTargetCoilSteppingAction::zmin private
Definition at line 50 of file PHG4BNLTargetCoilSteppingAction.h.
Referenced by PHG4BNLTargetCoilSteppingAction(), and UserSteppingAction().
The documentation for this class was generated from the following files:
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4BNLTargetCoilSteppingAction.h
/home/yuhw/GitHub/SeaQuest/e1039-core/simulation/g4detectors/PHG4BNLTargetCoilSteppingAction.cc