Class Reference for E1039 Core & Analysis Software: SQGenFit::GFFitter Class Reference
SQGenFit::GFFitter Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/SQGenFit/GFFitter.h>
Public Member Functions
GFFitter ()
~GFFitter ()
void setVerbosity (unsigned int v)
void init (GFField *field, const TString &fitter_choice="KalmanFitterRefTrack")
int processTrack (GFTrack &track, bool display=false)
const TString & getFitterType () const
genfit::AbsKalmanFitter * getGenFitFitter ()
void displayEvent ()
Detailed Description
Definition at line 15 of file GFFitter.h.
Constructor & Destructor Documentation
GFFitter()
SQGenFit::GFFitter::GFFitter ()
Definition at line 14 of file GFFitter.cxx.
~GFFitter()
SQGenFit::GFFitter::~GFFitter ()
Definition at line 17 of file GFFitter.cxx.
Member Function Documentation
displayEvent()
void SQGenFit::GFFitter::displayEvent ()
Definition at line 102 of file GFFitter.cxx.
getFitterType()
const TString& SQGenFit::GFFitter::getFitterType () const inline
Definition at line 26 of file GFFitter.h.
getGenFitFitter()
genfit::AbsKalmanFitter* SQGenFit::GFFitter::getGenFitFitter () inline
Definition at line 27 of file GFFitter.h.
init()
void SQGenFit::GFFitter::init (GFField * field, const TString & fitter_choice = "KalmanFitterRefTrack")
Definition at line 29 of file GFFitter.cxx.
Referenced by MultiThreadReco::InitRun(), SQReco::InitRun(), and main().
processTrack()
int SQGenFit::GFFitter::processTrack (GFTrack & track, bool display = false)
Definition at line 50 of file GFFitter.cxx.
References SQGenFit::GFTrack::checkConsistency(), and SQGenFit::GFTrack::getGenFitTrack().
Referenced by SQReco::fitTrackCand(), and main().
setVerbosity()
void SQGenFit::GFFitter::setVerbosity (unsigned int v)
Definition at line 23 of file GFFitter.cxx.
Referenced by main().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/SQGenFit/GFFitter.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/packages/reco/SQGenFit/GFFitter.cxx