Class Reference for E1039 Core & Analysis Software: PHPy8ParticleTrigger Class Reference
PHPy8ParticleTrigger Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/PHPythia8/PHPy8ParticleTrigger.h>
Public Member Functions
PHPy8ParticleTrigger (const std::string &name="PHPy8ParticleTrigger")
virtual ~PHPy8ParticleTrigger ()
bool Apply (Pythia8::Pythia *pythia)
void AddParticles (std::string particles)
void AddParticles (int particle)
void AddParticles (std::vector< int > particles)
void AddParents (std::string parents)
void AddParents (int parent)
void AddParents (std::vector< int > parents)
void SetPtHigh (double pt)
void SetPtLow (double pt)
void SetPtHighLow (double ptHigh, double ptLow)
void SetPHigh (double p)
void SetPLow (double p)
void SetPHighLow (double pHigh, double pLow)
void SetEtaHigh (double eta)
void SetEtaLow (double eta)
void SetEtaHighLow (double etaHigh, double etaLow)
void SetAbsEtaHigh (double eta)
void SetAbsEtaLow (double eta)
void SetAbsEtaHighLow (double etaHigh, double etaLow)
void SetPxHigh (double pz)
void SetPxLow (double pz)
void SetPxHighLow (double pzHigh, double pzLow)
void SetPyHigh (double pz)
void SetPyLow (double pz)
void SetPyHighLow (double pzHigh, double pzLow)
void SetPzHigh (double pz)
void SetPzLow (double pz)
void SetPzHighLow (double pzHigh, double pzLow)
void PrintConfig ()
Public Member Functions inherited from PHPy8GenTrigger
virtual ~PHPy8GenTrigger ()
virtual std::string GetName ()
std::vector< int > convertToInts (std::string s)
void Verbosity (int v)
Additional Inherited Members
Protected Member Functions inherited from PHPy8GenTrigger
PHPy8GenTrigger (const std::string &name="PHPy8GenTrigger")
constructor
Protected Attributes inherited from PHPy8GenTrigger
int _verbosity
Detailed Description
Definition at line 11 of file PHPy8ParticleTrigger.h.
Constructor & Destructor Documentation
PHPy8ParticleTrigger::PHPy8ParticleTrigger (const std::string & name = "PHPy8ParticleTrigger")
Definition at line 8 of file PHPy8ParticleTrigger.C.
PHPy8ParticleTrigger::~PHPy8ParticleTrigger () virtual
Definition at line 50 of file PHPy8ParticleTrigger.C.
References PHPy8GenTrigger::_verbosity, and PrintConfig().
Member Function Documentation
void PHPy8ParticleTrigger::AddParents (std::string parents)
Definition at line 152 of file PHPy8ParticleTrigger.C.
References PHPy8GenTrigger::convertToInts().
void PHPy8ParticleTrigger::AddParents (int parent)
Definition at line 157 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::AddParents (std::vector< int > parents)
Definition at line 161 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::AddParticles (std::string particles)
Definition at line 139 of file PHPy8ParticleTrigger.C.
References PHPy8GenTrigger::convertToInts().
Referenced by EventDisplay4Sim(), Fun4DQ(), Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4PatternDB(), Fun4Pythia8Demo(), Fun4Sim(), Fun4TrkDev(), and RecoE1039Sim().
void PHPy8ParticleTrigger::AddParticles (int particle)
Definition at line 144 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::AddParticles (std::vector< int > particles)
Definition at line 148 of file PHPy8ParticleTrigger.C.
bool PHPy8ParticleTrigger::Apply (Pythia8::Pythia * pythia) virtual
Reimplemented from PHPy8GenTrigger.
Definition at line 54 of file PHPy8ParticleTrigger.C.
References PHPy8GenTrigger::_verbosity.
void PHPy8ParticleTrigger::PrintConfig ()
Definition at line 378 of file PHPy8ParticleTrigger.C.
Referenced by ~PHPy8ParticleTrigger().
void PHPy8ParticleTrigger::SetAbsEtaHigh (double eta)
Definition at line 251 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetAbsEtaHighLow (double etaHigh, double etaLow)
Definition at line 271 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetAbsEtaLow (double eta)
Definition at line 261 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetEtaHigh (double eta)
Definition at line 223 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetEtaHighLow (double etaHigh, double etaLow)
Definition at line 243 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetEtaLow (double eta)
Definition at line 233 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPHigh (double p)
Definition at line 190 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPHighLow (double pHigh, double pLow)
Definition at line 210 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPLow (double p)
Definition at line 200 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPtHigh (double pt)
Definition at line 165 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPtHighLow (double ptHigh, double ptLow)
Definition at line 177 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPtLow (double pt)
Definition at line 171 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPxHigh (double pz)
Definition at line 279 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPxHighLow (double pzHigh, double pzLow)
Definition at line 299 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPxLow (double pz)
Definition at line 289 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPyHigh (double pz)
Definition at line 312 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPyHighLow (double pzHigh, double pzLow)
Definition at line 332 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPyLow (double pz)
Definition at line 322 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPzHigh (double pz)
Definition at line 345 of file PHPy8ParticleTrigger.C.
void PHPy8ParticleTrigger::SetPzHighLow (double pzHigh, double pzLow)
Definition at line 365 of file PHPy8ParticleTrigger.C.
Referenced by EventDisplay4Sim(), Fun4DQ(), Fun4E1039Shielding(), Fun4HodoAccGap(), Fun4PatternDB(), Fun4Sim(), Fun4TrkDev(), and RecoE1039Sim().
void PHPy8ParticleTrigger::SetPzLow (double pz)
Definition at line 355 of file PHPy8ParticleTrigger.C.
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/PHPythia8/PHPy8ParticleTrigger.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/generators/PHPythia8/PHPy8ParticleTrigger.C