Class Reference for E1039 Core & Analysis Software: SQDigitizer Class Reference
SQDigitizer Class Reference
#include </dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/SQDigitizer.h>
Public Member Functions
SQDigitizer (const std::string &name="SQDigitizer", const int verbose=0)
virtual ~SQDigitizer ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
module initialization
int process_event (PHCompositeNode *topNode)
event processing
void digitizePlane (const std::string &detName)
main external call, fill the digi hit vector
void digitizeEMCal (const std::string &detName)
digitize the emcal hits
bool realize (SQHit &dHit)
realization process
int getTriggerLv (int detectorID)
Get the trigger level by detectorID.
void registerEMCal (std::string ecalName, int ecalID=100)
Register additional EMCal detector for digitizing.
void set_enable_st1dc (const bool en)
enable/disable certain detectors
void set_enable_dphodo (const bool en)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes inherited from Fun4AllBase
std::string ThisName
int verbosity
The verbosity level. 0 means not verbose at all.
Detailed Description
Definition at line 23 of file SQDigitizer.h.
Constructor & Destructor Documentation
SQDigitizer::SQDigitizer (const std::string & name = "SQDigitizer", const int verbose = 0)
Definition at line 56 of file SQDigitizer.cc.
References Fun4AllBase::Verbosity().
SQDigitizer::~SQDigitizer () virtual
Definition at line 66 of file SQDigitizer.cc.
Member Function Documentation
void SQDigitizer::digitizeEMCal (const std::string & detName)
digitize the emcal hits
Definition at line 244 of file SQDigitizer.cc.
References PHG4Hit::get_edep(), PHG4Hit::get_hit_id(), PHG4Hit::get_index_l(), PHG4Hit::get_px(), PHG4Hit::get_py(), PHG4Hit::get_pz(), PHG4Hit::get_scint_id(), PHG4Hit::get_shower_id(), PHG4Hit::get_trkid(), PHG4Hit::get_x(), PHG4Hit::get_y(), PHG4Hit::get_z(), PHG4HitContainer::getHits(), SQHitVector::push_back(), SQCalHit_v1::set_detector_id(), SQHit::set_drift_distance(), SQCalHit_v1::set_element_id(), SQCalMCHit_v1::set_g4hit_id(), SQHit::set_hodo_mask(), SQHit::set_in_time(), SQHit::set_pos(), SQCalMCHit_v1::set_shower_id(), SQHit::set_tdc_time(), SQCalMCHit_v1::set_track_id(), SQCalMCHit_v1::set_truth_px(), SQCalMCHit_v1::set_truth_py(), SQCalMCHit_v1::set_truth_pz(), SQCalMCHit_v1::set_truth_x(), SQCalMCHit_v1::set_truth_y(), SQCalMCHit_v1::set_truth_z(), SQHitVector::size(), and PHG4HitContainer::size().
Referenced by process_event().
void SQDigitizer::digitizePlane (const std::string & detName)
main external call, fill the digi hit vector
Definition at line 152 of file SQDigitizer.cc.
References PHG4Hit::get_hit_id(), SQHit_v1::get_pos(), PHG4Hit::get_px(), PHG4Hit::get_py(), PHG4Hit::get_pz(), PHG4Hit::get_trkid(), PHG4Hit::get_x(), PHG4Hit::get_y(), PHG4Hit::get_z(), GeomSvc::getCellWidth(), GeomSvc::getDCA(), GeomSvc::getExpElementID(), PHG4HitContainer::getHits(), GeomSvc::getInterception(), GeomSvc::getMeasurement(), GeomSvc::getPlaneNElements(), GeomSvc::getPlaneOverlap(), GeomSvc::getPlanePosition(), GeomSvc::isInPlane(), nChamberPlanes, nHodoPlanes, nPropPlanes, SQHitVector::push_back(), SQHit_v1::set_detector_id(), SQHit_v1::set_drift_distance(), SQHit_v1::set_element_id(), SQMCHit_v1::set_g4hit_id(), SQHit_v1::set_hit_id(), SQHit_v1::set_hodo_mask(), SQHit_v1::set_in_time(), SQHit_v1::set_pos(), SQHit_v1::set_tdc_time(), SQMCHit_v1::set_track_id(), SQMCHit_v1::set_truth_px(), SQMCHit_v1::set_truth_py(), SQMCHit_v1::set_truth_pz(), SQMCHit_v1::set_truth_x(), SQMCHit_v1::set_truth_y(), SQMCHit_v1::set_truth_z(), SQHitVector::size(), and PHG4HitContainer::size().
Referenced by process_event().
int SQDigitizer::getTriggerLv (int detectorID) inline
Get the trigger level by detectorID.
Definition at line 49 of file SQDigitizer.h.
References GeomSvc::getTriggerLv().
int SQDigitizer::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 36 of file SQDigitizer.cc.
References Fun4AllReturnCodes::EVENT_OK, GeomSvc::getDetectorName(), GeomSvc::instance(), nChamberPlanes, nDarkPhotonPlanes, nHodoPlanes, nPropPlanes, and Fun4AllBase::Verbosity().
int SQDigitizer::InitRun (PHCompositeNode * topNode) virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 69 of file SQDigitizer.cc.
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
int SQDigitizer::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 129 of file SQDigitizer.cc.
References digitizeEMCal(), digitizePlane(), Fun4AllReturnCodes::EVENT_OK, Fun4AllBase::Name(), nChamberPlanes, nDarkPhotonPlanes, nHodoPlanes, nPropPlanes, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
bool SQDigitizer::realize (SQHit & dHit)
realization process
Definition at line 292 of file SQDigitizer.cc.
void SQDigitizer::registerEMCal (std::string ecalName, int ecalID = 100) inline
Register additional EMCal detector for digitizing.
Definition at line 52 of file SQDigitizer.h.
Referenced by Fun4DQ(), and Fun4EMCal().
void SQDigitizer::set_enable_dphodo (const bool en) inline
Definition at line 56 of file SQDigitizer.h.
Referenced by Fun4Sim().
void SQDigitizer::set_enable_st1dc (const bool en) inline
enable/disable certain detectors
Definition at line 55 of file SQDigitizer.h.
Referenced by Fun4Sim().
The documentation for this class was generated from the following files:
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/SQDigitizer.h
/dev/shm/kenichi/update-github-e1039-doc/e1039-core/simulation/g4detectors/SQDigitizer.cc